### ISSUE TITLE
Extend currentUser Type to allow extra variables.

### ISSUE THREAD

**Issue by Burnsy** [redwoodjs/redwood#1006]
When the user calls 
```js 
const { currentUser } = useAuth()
```
https://github.com/redwoodjs/redwood/blob/e40ffe1f85b582d04ff74fd072261ce95da8e20a/packages/auth/src/AuthProvider.tsx#L11-L48

the only thing that is typed is

https://github.com/redwoodjs/redwood/blob/e40ffe1f85b582d04ff74fd072261ce95da8e20a/packages/auth/src/AuthProvider.tsx#L11-L13

so if the user passes through any more variables such as name or email etc. then it will return that it does not exist in the type.
As seen here
![CleanShot 2020-08-26 at 13 50 34](https://user-images.githubusercontent.com/15834048/91305570-22567b80-e7a3-11ea-9044-0ceba376424d.png)

So when the user is using typescript they need it to be extendable in a typed file so that they can define what extra variables might be in the object

When speaking to @peterp he mentioned the solution could be with to do with generics

**Comment by dthyresson** [comment]
Something to try might be (h/t to @peterp):

```js
export type CurrentUser = Record<string, any> & { roles?: Array<string> }
```

The CurrentUser should be able to have any number of user-defined attributes (id, name, email, user_metadata, etc).

But if `roles` is define, in needs to be an array of string(s).

**Comment by dac09** [comment]
I believe this was resolved in v0.26(ish). The type of currentUser is inferred from `./api/src/lib/auth#getCurrentUser` - so in theory if you want a different type, you can just type the return of that function.

**Comment by theoradicella** [comment]
In spite of typing the return of that function, it stills happens the same.

**Comment by dac09** [comment]
Hi @theoradicella, first thing I would try is regenerating the types - "yarn rw g types". 


If it's still an issue, would it be possible to provide a reproduction via Gitpod? 

https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md#creating-a-reproduction-to-include-with-issues
