### ISSUE TITLE
Add back functionality to Router

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#1013]
It should be easy to navigate back. Right now there's no built-in way to do this. We already use `navigate` to navigate programatically. It might make sense to add the back-navigation feature there:

```
navigate.back()
```

The way it's done natively with web apis is via history's `back` and `go` properties. `back` does what you would expect, and `go` takes a number, so you can go back multiple pages. Do we want to enable that kind of functionality too?

**Comment by shakti97** [comment]
I would like to work on the issue @peterp @jtoar

**Comment by thedavidprice** [comment]
Hi @shakti97 I assigned this issue to you 🚀 Please let me know if you're no longer interested so I can open it up for someone else.

If you haven't already, please do take a look at our getting started information for contributors: https://github.com/redwoodjs/redwood/issues/1266

Lastly, don't hesitate to reach out if you have any questions along the way

**Comment by shakti97** [comment]
okay, yes I am working on it.

**Comment by Tobbe** [comment]
@shakti97 Interested in hearing about the solution you're going for, if you have gotten that far yet 🙂 What would the API look like for the user?

**Comment by thedavidprice** [comment]
@jtoar curious if this will be resolved along with the upcoming a11y improvements?

**Comment by saideepesh000** [comment]
Hey @thedavidprice @jtoar @peterp, can I work on this.

**Comment by KrisCoulson** [comment]
@thedavidprice just looking through a couple of the outstanding tickets in the router project. Figured this could be bump/resurface @saideepesh000 question. What should the api look like for this. Took a peak at the react-router and they use history.goBack() wonder if `goBack` or  just `back` is sufficient Since @saideepesh000  is correct and navigate is an exported function

**Comment by thedavidprice** [comment]
@jtoar is the one who can help direct. I'll give him a nudge. Ping me again if/as needed. And thank you both for resurfacing this one!

**Comment by jtoar** [comment]
@saideepesh000 no correction needed! as you said, `navigate`'s a function, it would be counterintuitive to add another function, `back`, as a property. Ok, one correction: just so you know that you can do this in JS, functions can have properties, which can be other functions (since functions are just `Object`s or whatever (I should really learn JS)). so `navigate.back` is perfectly possible, but probably not a good idea 😅 

The first comment was more of a "what would this look like" instead of one-to-one blueprint. Always ok to start with a clean slate when it comes to ideas. We don't want to be restricted by code—code should be the vehicle for our ideas!

As @KrisCoulson got at, this is an opportunity to think about our whole history API. And given the recent router changes (the Set component), it's prime time to make this a little more modern.

@saideepesh000 do you still want to take this one? Don't want to pressure you, just want you to know that you're more than welcome to it! @Tobbe and I can help you the whole way.

**Comment by thedavidprice** [comment]
this is done and will be in v0.36.0, correct?

**Comment by jtoar** [comment]
@thedavidprice yes
