### ISSUE TITLE
[Bug?]: URL for GraphiQL header help docs is wrong (again!)

### ISSUE THREAD

**Issue by Benjamin-Lee** [redwoodjs/redwood#10219]
### What's not working?

This seems to be a problem for me since I reported a very similar problem in #8359. The casing of the url is now fixed:

https://redwoodjs.com/docs/cli-commands#setup-graphiql-headers

However, there doesn't seem to be any headings that match. Is this it? https://redwoodjs.com/docs/cli-commands#setup-graphql

I still clearly haven't learned the right way to setup graphiql headers yet 😆

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 14.3.1
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.5.0 - /private/var/folders/gw/sk03t1cn3wlgclyc55yst44w0000gn/T/xfs-b4308ea5/node
    Yarn: 3.7.0 - /private/var/folders/gw/sk03t1cn3wlgclyc55yst44w0000gn/T/xfs-b4308ea5/yarn
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.3.1
  npmPackages:
    @redwoodjs/auth-supabase-setup: 7.1.3 => 7.1.3 
    @redwoodjs/core: 7.1.3 => 7.1.3
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by ahaywood** [comment]
Hey @Benjamin-Lee Thanks for taking the time to report this ... I'll make sure this gets in front of the right people.

**Comment by dthyresson** [comment]
HI @Benjamin-Lee sorry for that experience. We're in fact sunsetting the graphical header feature in v7 and have moved it to Studio as the headers were not entirely reliable and we felt we could improve the experience.

<img width="1335" alt="image" src="https://github.com/redwoodjs/redwood/assets/1051633/466144ca-f5cb-46a1-8028-c32b4456fa59">


This will automatically set the headers.

The docs for v7 have removed the graphical headers feature.

Do let me know how I can help you try Studio and get the headers set properly -- are you using dbAuth?
