### ISSUE TITLE
[Bug?]: Maybe Regression: cannot delete `/api` directory and have the app still build

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#10264]
### What's not working?

Coming soon with RSC, we will no longer have an `/api` directory. I tried to see how close I could get to this future with the latest canary by deleting everything in `/api`. The build would fail unless two conditions were met:

* The`db/prisma.schema` file must be present
* There must be at least 1 directive in `api/src/directives`

### How do we reproduce the bug?

In the latest canary, delete the `/api` directory and try to `yarn rw build`

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
I created the test project and then destroyed the API side. I worked through the errors I had getting `yarn rw build` to work and PR'd the changes in the draft mentioned above. 

I didn't run into any directive related issues however so maybe I'm missing something. I'm not sure if we will want the PR but it's there as a starting point I guess. Fancy checking if using that branch works for building your api-less project?

**Comment by Josh-Walker-GM** [comment]
Cool thanks! I'll check it out, reproduce it, and update the branch accordingly

**Comment by Josh-Walker-GM** [comment]
Your goal here was to simply not have a `api` directory at all right?

My branch will handle that case for your app - the `yarn rw build` will build the web successfully. I didn't code it to handle the case of only having some api side files like you have in the latest commit to that repo.

What are your thoughts on build working for either:
1. You have no `api` directory whatsoever
2. You have an `api` directory but it has some requirements, like a directive, schema etc

I don't know if it'll be wise to try go through any possible partial state the `api` side might be in right? 😅

**Comment by cannikin** [comment]
Yep I wanted to be able to remove `/api` completely, but if I removed `/db` or `/directives` then the build wouldn't complete, so that's as close as I could get (so that people could still clone the repo and follow along with the Walkthrough). But you're saying that with your branch I could now remove those and everything builds? That's great! Let's get this merged and a new canary pushed ASAP!

Those two cases sounds good to me, I definitely wasn't thinking we should try to get api to build in all possible permutations of files/directories that could be present. I would say the only cases to worry about are `/api` doesn't exist at all, or `/api` contains everything we would expect a regular Redwood app to have.

**Comment by Josh-Walker-GM** [comment]
Fixed in #10265 and improved in #10275
