### ISSUE TITLE
[Bug?]: Setup command for `auth0` isn't working

### ISSUE THREAD

**Issue by ssalasky** [redwoodjs/redwood#10287]
### What's not working?

I'm following the instructions [here](https://redwoodjs.com/docs/auth/auth0) to get auth0 setup. However, when I run the command I get this error:

<img width="1282" alt="image" src="https://github.com/redwoodjs/redwood/assets/25517414/8092347f-2b87-43c4-bb71-10a3c598da74">

When I try to run the command again with any of the following flags it also fails:
- `yarn rw setup auth auth0 -f`
- `yarn rw setup auth auth0 -W`
- `yarn rw setup auth auth0 --ignore-workspace-root-check`

I have been able to run other CLI commands without problems so I'm not sure if I am doing something wrong, but it felt like this might be a bug so I wanted to file a report.

### How do we reproduce the bug?

Just start a basic project and run the `yarn rw setup auth auth0` command

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 14.2
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - /var/folders/ks/yqvs37sj0sz0vlpcsn0nsmkh0000gn/T/yarn--1711290294077-0.6071494911487529/node
    Yarn: 1.22.19 - /var/folders/ks/yqvs37sj0sz0vlpcsn0nsmkh0000gn/T/yarn--1711290294077-0.6071494911487529/yarn
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 123.0.6312.58
    Safari: 17.2
  npmPackages:
    @redwoodjs/core: 7.1.3 => 7.1.3 
    @redwoodjs/project-config: 7.1.3 => 7.1.3
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Hey @ssalasky :wave: Thanks for trying out redwood! 

I think this might be an issue around yarn versions. I see `Yarn: 1.22.19` in your `yarn rw info` report but I would have expected it to have been yarn version 4.

We use corepack to have your redwood project use a version of yarn that will work well with the framework. This is done by having `"packageManager": "yarn@4.1.0"` in the `package.json`. Is this a project you have upgraded or is this a new redwood project? If it has been upgraded then you might have some existing configuration that is interfering with this, namely in the `.yarnrc.yml` file where there could be a line `yarnPath: "./path-to-some-script.js".

Happy to help further but I might need to confirm what some of those files have in them. I'll also try to see if we have specific documentation on this somewhere on our forums or docs.

**Comment by ssalasky** [comment]
That was the problem. I should have checked that. Thanks for looking into it!
