### ISSUE TITLE
[Bug?]: Running `yarn create redwood-app` fails with recommended Node & Yarn Versions

### ISSUE THREAD

**Issue by evansibok** [redwoodjs/redwood#10289]
### What's not working?

Starting up a new redwood project with `yarn create redwood-app` fails.

### How do we reproduce the bug?

1. Go to a new terminal window
2. Run `yarn create redwood-app demo`
3. You'll get the error below

```
yarn create redwood-app demo
yarn create v1.22.21
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "20.11.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**PS:** Note that running `create-redwood-app demo` works however.

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 14.4
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - /private/var/folders/1q/m38hblrd4ksfw85tccbsk05m0000gn/T/xfs-530c3d9f/node
    Yarn: 4.1.0 - /private/var/folders/1q/m38hblrd4ksfw85tccbsk05m0000gn/T/xfs-530c3d9f/yarn
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Safari: 17.4
  npmPackages:
    @redwoodjs/core: 7.1.3 => 7.1.3 
    @redwoodjs/project-config: 7.1.3 => 7.1.3
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Hi @evansibok :wave:

We occasionally see issues like this where some other (non-redwood) package has version issues when running `yarn create redwood-app`. The latest one I could find was #8884. 

Are you able to consistently reproduce this? My gut reaction is that this is related to some form of yarn cache and my recommendation would be to clean the cache. I think there may be a link or two within #8884 to some yarn issues that discuss potential solutions.

**Comment by evansibok** [comment]
Hi @Josh-Walker-GM So I guess it's the same with the link you sent me.

I mentioned though that running `create-redwood-app <app-name>` directly works though.

I open the issue because it seemed like `yarn create redwood-app` is the main command expected to be used.

So if this is a yarn related issue then I guess we can close this.

Thank you
