### ISSUE TITLE
How to use Gatsby with Redwood in a monorepo setup?

### ISSUE THREAD

**Issue by freddydumont** [redwoodjs/redwood#1036]
For many reasons, including static site generation, automatic image optimization and i18n, I prefer to use Gatsby for my marketing / landing pages. (on `example.com`)

However I definitely want to use redwood for the app itself. (on `app.example.com`)

So I'm wondering what's the best setup here.

Should I just add another "side" to my redwood app and continue working with `yarn` workspaces?
```
- web
- app
- api
package.json
```

Or should I import the full redwood repo in a `lerna` configuration?
```
- web (gatsby)
- app (redwood)
   - api
   - webapp
   package.json
package.json
```

In either case, how do I deal with shared files like the `tailwindcss` theme etc.

Any guidance here would be greatly appreciated. Thanks

**Comment by alvincrespo** [comment]
@freddydumont This is a great question! You might get more traction on the forums here: https://community.redwoodjs.com/

I've had success there asking these kind of architectural questions.

**Comment by freddydumont** [comment]
Thanks @alvincrespo I'll try over there too

**Comment by thedavidprice** [comment]
Hi all! I took a stab at an initial question to get the conversation rolling. Closing this out for now in favor of the forums. But please do re-open or ping us if conversation doesn't move forward.
