### ISSUE TITLE
[Bug?]: Autocomplete and auto-import not working on v7.3.0 for JS projects

### ISSUE THREAD

**Issue by higajooj** [redwoodjs/redwood#10422]
### What's not working?

Short after updating to v7.3.0 I started noticing some LSP problems. It turns out autocomplete barely works anymore with `.js, .jsx` files. I am using neovim 0.9.5. 

Previously (RW v7.1.3), when I typed:

`useA` -> `import { useAtom } from 'jotai'` would show up, or
`<Bui` -> `import { Building } from 'lucide-react'`.

Now, with RW 7.3, I don't get any autocompletion at all from any package installed, besides code from within my workspace (say, `import { useAuth } from 'src/auth'`, which works just fine).

Also, when hitting `CTRL+Space` in the following situation, before I would get all possible imports.
![image](https://github.com/redwoodjs/redwood/assets/22334857/ffc927f4-1e65-413b-a2a4-ee28fe820761)

Now, nothing shows up.
![image](https://github.com/redwoodjs/redwood/assets/22334857/02ab913e-fa86-44d7-a51e-c11710b070f2)

I use [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server), but just to make sure this bug is not related with my editor, environment or LSP config, I also tested using [vtsls](https://github.com/yioneko/vtsls) and [typescript-tools](https://github.com/pmizio/typescript-tools.nvim), results were still the same. I don't use any fancy configuration, and all other JavaScript projects I have (not using Redwood) works normally.

Now, two things worth mentioning. 
1. When I rename files from `.jsx` to `.tsx`, everthing works normally just like before, so this is only affecting JavaScript files (`.js`, `.jsx`)
2. VS Code doesn't seem to be affected, so autocomplete and auto import works even with `.js,.jsx` files.

This is what bugs me the most. I work 90% slower on VS code and I also can't convert my whole project to TypeScript.

I also tried creating a brand new Redwood project (`yarn create redwood-app`), installed lucide-react `yarn workspace web add lucide-react`, and when I go to any `.jsx` file (page, component, cell) nothing shows up (like the screenshot above).

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by higajooj** [comment]
### Update!!

I've been able to pin this issue down to exactly thiis:
`aa`
chore(deps): update dependency typescript to v5.4.3 [link](url)
```

**Comment by higajooj** [comment]
### Update!!

I've been able to track this issue down to exactly this:
[chore(deps): update dependency typescript to v5.4.3](https://github.com/redwoodjs/redwood/releases/tag/v7.3.0)

VS Code uses its own bundled typescript. If you see [here](https://code.visualstudio.com/updates/v1_88#_typescript-54), VS Code 1.88 just got rolled out with typescript v5.4 - version 1.87 and previous versions were using typescript <= 5.3. That's why I had it breaking with Neovim but not VS Code.

This is not something that affects Redwood exclusively. The simplest way to reproduce this bug is to create a Vite app using React + Javascript, install some package (Lucide or Jotai like I used as example, or any other), and just bring autocomplete to see if any imports show up. If you get your hands on VS Code >= 1.88, the same issue stated above should happen to you.

Worth remembering that this is only affecting `.js` and `.jsx` files.

**Comment by Tobbe** [comment]
Thanks for the update @higajooj! That's some great detective work right there 🙂 🕵️ 

As a workaround for any VSCode users you can downgrade your RW project's TS version to 5.4.2 and then tell VSCode to use the workspace version of TS instead of its built-in version. Just click the TS version number in the status bar, and choose 5.4.2 in the popup you get at the top of the screen
![image](https://github.com/redwoodjs/redwood/assets/30793/05e22b61-a752-4e6d-9fc6-1c3dc3182322)
![image](https://github.com/redwoodjs/redwood/assets/30793/dc1426a0-d5b9-4056-afaf-4efbd5e5ba23)
(I'm still on an older version of VSCode, and have 5.4.3 as my workspace version. Your numbers will look different)

**Comment by higajooj** [comment]
Thanks @Tobbe! Unfortunately 5.4.2 is also broken. The solution is to stay on 5.3.x for now.

**Comment by Tobbe** [comment]
@higajooj BTW, is this only for RW projects, or do you see the same issue in other projects as well?

**Comment by higajooj** [comment]
@Tobbe, both Redwood and plain Vite apps are affected (`npm create vite`). I'm not sure about other frameworks.

**Comment by higajooj** [comment]
Fixed on TypeScript 5.4.5

https://github.com/microsoft/vscode/issues/209849#issuecomment-2043320180
https://github.com/microsoft/TypeScript/issues/57740
https://github.com/microsoft/TypeScript/issues/58115
https://github.com/microsoft/TypeScript/issues/58113

**Comment by Josh-Walker-GM** [comment]
Hey @higajooj, I just merged in the dependency upgrade, confirmed it fixed the problem for me locally then released it in v7.4.1. Can you confirm that v7.4.1 works as expected for you?

**Comment by higajooj** [comment]
It's working 👍🏻. I was using
```
  "resolutions": {
    "typescript": "5.3.2"
  }
```
to keep up with latest Redwood without breaking my dev environment.

Thanks @Josh-Walker-GM and @Tobbe !

**Comment by Josh-Walker-GM** [comment]
Fixed in #10452
