### ISSUE TITLE
[Auth] Common AuthProvider & use*  changes for middleware auth

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#10435]
Currently in PR: https://github.com/redwoodjs/redwood/pull/10420

Update the implementation for the common `AuthProvider` in packages/auth/src/AuthProvider/AuthProvider.tsx
and the relevant functions:
- useCurrentUser
- useForgotPassword
- useReauthenticate
- ....

to use server auth state

**Comment by dthyresson** [comment]
PR: https://github.com/redwoodjs/redwood/pull/10420 approved and closed.
