### ISSUE TITLE
[Bug?]: Cannot wrap components in RedwoodApolloProvider in jest tests

### ISSUE THREAD

**Issue by cadlagtrader** [redwoodjs/redwood#10500]
### What's not working?
When using Redwood >=7.4 and only n a subset of jest tests (no obvious pattern, so could be path dependant on the module loading order)

In FetchConfigProvider.js, 
```useAuth = _auth.useNoAuth,```
_auth.useNoAuth is undefined. _auth only has a useAuth function (see screenshot)

<img width="799" alt="Screenshot 2024-04-23 at 13 53 59" src="https://github.com/redwoodjs/redwood/assets/20140769/2ee82835-cde2-43e6-bbf8-495e16d01444">

```
[Error: Uncaught [TypeError: useAuth is not a function]]
    3: "The above error occurred in the <FetchConfigProvider> component:·
        at FetchConfigProvider ([...]/node_modules/@redwoodjs/web/dist/components/FetchConfigProvider.js:28:5)
        at RedwoodApolloProvider ([...]/node_modules/@redwoodjs/web/dist/apollo/index.js:255:5)
        at children ([...]/web/src/providers/AtomProvider/AtomProvider.tsx:35:31)
        at MockParamsProvider ([...]/node_modules/@redwoodjs/testing/dist/web/MockParamsProvider.js:13:3)
        at LocationProvider ([...]/node_modules/@redwoodjs/router/dist/location.js:18:5)
        at GraphQLHooksProvider ([...]/node_modules/@redwoodjs/web/dist/components/GraphQLHooksProvider.js:34:5)
        at ErrorBoundary ([...]/node_modules/@redwoodjs/web/dist/apollo/index.js:243:1)
        at ApolloProvider ([...]/node_modules/@apollo/client/react/context/ApolloProvider.js:6:21)
        at ApolloProviderWithFetchConfig ([...]/node_modules/@redwoodjs/web/dist/apollo/index.js:66:5)
        at FetchConfigProvider ([...]/node_modules/@redwoodjs/web/dist/components/FetchConfigProvider.js:28:5)
        at RedwoodApolloProvider ([...]/node_modules/@redwoodjs/web/dist/apollo/index.js:255:5)
        at _HelmetProvider ([...]/node_modules/react-helmet-async/lib/index.js:483:5)
        at RedwoodProvider ([...]/node_modules/@redwoodjs/web/dist/components/RedwoodProvider.js:14:5)
        at MockProviders ([...]/node_modules/@redwoodjs/testing/dist/web/MockProviders.js:32:3)
        at Provider ([...]/node_modules/jotai/react.js:13:23)
        at children ([...]/web/src/providers/AtomProvider/AtomProvider.tsx:26:25)
        at children ([...]/web/config/jest.context.setup.tsx:22:31)·
    React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary."
```

### How do we reproduce the bug?

1. Create a new redwood project from template
2. Add dbAuth
3. Generate a home page
4. In HomePage.test.tsx change 

```
render(<HomePage /> )
``` 
into 
```
render(
        <RedwoodApolloProvider>
          <HomePage />
        </RedwoodApolloProvider>
      )
``` 

Test fails with
 ```
Error name:    "TypeError"
    Error message: "useAuth is not a function"
```

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 14.4.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - /private/var/folders/h9/thbt2zkx6vz00tyc4dq4bt_c0000gp/T/xfs-5a85eb81/node
    Yarn: 4.1.1 - /private/var/folders/h9/thbt2zkx6vz00tyc4dq4bt_c0000gp/T/xfs-5a85eb81/yarn
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 124.0.6367.62
    Safari: 17.4.1
  npmPackages:
    @redwoodjs/auth-supertokens-setup: 7.4.2 => 7.4.2 
    @redwoodjs/cli-data-migrate: 7.4.2 => 7.4.2 
    @redwoodjs/cli-storybook: 7.4.2 => 7.4.2 
    @redwoodjs/core: 7.4.2 => 7.4.2 
    @redwoodjs/realtime: 7.4.2 => 7.4.2 
    @redwoodjs/studio: 11.3.1 => 11.3.1
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by cadlagtrader** [comment]
Hi @Tobbe, I think I narrowed down the issue. 
RedwoodApolloProvider has a default for useAuth = _auth.useNoAuth. Somehow this default is not working anymore. 
I have added the steps to reproduce above

**Comment by cadlagtrader** [comment]
Hello @dac09 - thanks for looking into it!

Using your project and ```yarn rw test web```
- no error when i run from a system terminal 
- same error when running from vscode terminal

I have tried to remove all launch configuration + all extensions in vscode, still hitting the same error. Both terminals are using zsh and node 20 installed through nvm

It seems @redwoodjs/auth module is not loaded properly (only useAuth and createAuthentication are available in the watcher). Just to confirm, I only see the issue with rw>=7.4. Could it be the new esm/cjs change ?

**Comment by dac09** [comment]
Heyooo, so I tried the same thing in both vscode terminal (zsh also) - and the javascript debugger terminal, still can't see it error out! 

For reference I'm using Volta, and tried Node v20.10.10 and v20.12.2, and v20.11.1 to check. 

Could totally be the esm/cjs change (kind of has to be!). There's a little hint in your screenshot too, where it says `__esModule: true`. Trying to understand why it might be picking up esm instead of cjs. 


---

I just noticed you had an extra step here: 
> render(
>        <RedwoodApolloProvider>
>          <HomePage />
>        </RedwoodApolloProvider>
>      )

- When you got the error, did you change the test also? Or just left the render as is?
- Could you help me understand why you're wrapping in ApolloProvider? 
- Where is RedwoodApolloProvider imported from? This could tell us where this esm stuff is coming from!

**Comment by cadlagtrader** [comment]
OK, so my mistake🙈: I was using my test project, not yours when testing in vscode (they are similar except for this RedwoodApolloProvder wrapping the HomePage).
So now vscode and the terminal are consistent.

The issue boils down to the RedwoodApolloProvider we instantiate in a TestWrapper for several of our tests. I had added it to my test project to isolate the issue. 

When I add the same to your test project, I get the same error stack including the error message below
    Error name:    "TypeError"
    Error message: "useAuth is not a function"

So the bifurcation is: when RedwoodApolloProvider is invoked either in a jest TestWrapper or inside a test without a useAuth prop:
-RW<7.4 is fine with no prop for useAuth
-RW>=7.4 fails because useNoAuth in undefined

This is not a blocking issue for us as I can set the useAuth of RedwoodApolloProvider to the useAuth implementation of our auth provider in my tests

Thanks!

**Comment by dac09** [comment]
Thanks for getting back and the break down @cadlagtrader ✌️✌️✌️

I'm closing the issue as there is a resolution in your comment here: https://github.com/redwoodjs/redwood/issues/10500#issuecomment-2085549533

if anyone else comes across this again, or would like to help debug further please feel free to comment and we can reopen the issue.
