### ISSUE TITLE
[Bug?]: HydrateRoot and TypeError: Cannot read properties of undefined ... at Object.prerenderLoader on whichever page first loads

### ISSUE THREAD

**Issue by nivivive** [redwoodjs/redwood#10506]
### What's not working?

We're getting this error on our app for whichever page first loads:
```
101:5035 TypeError: Cannot read properties of undefined (reading 'ComingSoonPage')
    at Object.prerenderLoader (https://staging.xx.com/assets/index-67e49102.js:2419:6659)
    at m (https://staging.xx.com/assets/index-67e49102.js:434:53666)
    at l8 (https://staging.xx.com/assets/index-67e49102.js:38:19551)
    at yZ (https://staging.xx.com/assets/index-67e49102.js:40:44101)
    at vZ (https://staging.xx.com/assets/index-67e49102.js:40:39819)
    at Ume (https://staging.xx.com/assets/index-67e49102.js:40:39745)
    at Ww (https://staging.xx.com/assets/index-67e49102.js:40:39596)
    at BI (https://staging.xx.com/assets/index-67e49102.js:40:35959)
    at dZ (https://staging.xx.com/assets/index-67e49102.js:40:34906)
    at T (https://staging.xx.com/assets/index-67e49102.js:25:1611)
```

When looking at our Datadog RUM recording, it looks like the user very briefly sees a 500 page flicker on first time opening the app and thereafter, the screen refreshes and the issue goes away.

I tried following these steps but the issue still persists. https://community.redwoodjs.com/t/error-while-hydrating/4920

I’m not currently prerendering or SSR any route, but I’m wondering if you’ve seen this type of issue before and if adding prerender tag or something like that would help?

Our AWS Cloudfront is set up like this:
- Default root object: index.html
- Error pages:
    - 403: response page path: /index.html, http response code: 200
    - 404: response page path: /index.html, http response: 200

Switching the settings to this doesn't solve the issue either:
- Default root object: 200.html
- Error pages:
    - 403: response page path: /200.html, http response code: 200
    - 404: response page path: /200.html, http response: 200

I've also tried removing hydrateRoot from web/src/entry.client.tsx, but I'm still getting the same issue.

Is there anywhere else in the Redwood app that's hydrating and/or prerendering the app even if none of our routes have 'prerender' tag? How do we debug further?

### What's your environment? (If it applies)

Doesn't reproduce locally, is happening on deployed environments - we deploy to AWS Lambda/Cloudfront

### Are you interested in working on this?

- [x] I'm interested in working on this

**Comment by dthyresson** [comment]
@Tobbe I think you may have helped on the related community post — any ideas here?

**Comment by Tobbe** [comment]
@nivivive You say it's not happening locally. Is that true even if you do `yarn rw build` and then `yarn rw serve`?

> Is there anywhere else in the Redwood app that's hydrating and/or prerendering the app even if none of our routes have 'prerender' tag? How do we debug further?

Nothing is prerendered by default. 
Can you reproduce the issue reliably on your own? Or have you only seen it in Datadog? If you can reproduce on your own, could you please try turning off JavaScript in your browser, navigate to a page that would show the error, and then copy/paste the html you get back from the server here, so that I can see it?

**Comment by nivivive** [comment]
Sorry for the delay here. I am able to reproduce the issue reliably, but as I'm trying to get the html you requested, I discovered a weird thing that I'm trying to troubleshoot and I'm wondering if that's what is causing the core issue. I'll let you know more as soon as I find out

**Comment by nivivive** [comment]
Was able to mitigate the issue - we think it had to do with third party settings

**Comment by dthyresson** [comment]
> Was able to mitigate the issue - we think it had to do with third party settings

@nivivive Glad it’s behaving better. Could you elaborate on what that third party might be so we can know for the future of people see this behavior we can ask “Do you have X setup?”

Thanks!
