### ISSUE TITLE
taillwind css generator util missing

### ISSUE THREAD

**Issue by CR1AT0RS** [redwoodjs/redwood#1053]
Hi,

I am following the docs and `yarn rw g tailwind` is not showing up in command line. Not sure why util command is missing from the cli?

❯ yarn rw --version
yarn run v1.22.5
$ /Users/XXXX/Downloads/redwoodblog/node_modules/.bin/rw --version
0.16.0
✨  Done in 1.10s.
❯ yarn rw g util tailwinds
yarn run v1.22.5
$ /Users/XXXX/Downloads/redwoodblog/node_modules/.bin/rw g util tailwinds
rw generate <type>

Save time by generating boilerplate code

Commands:
  rw g auth <provider>       Generate an auth configuration
  rw g cell <name>           Generate a cell component
  rw g component <name>      Generate a component
  rw g dataMigration <name>  Generate a data migration
  rw g deploy <provider>     Generate a deployment configuration
  rw g function <name>       Generate a Function
  rw g layout <name>         Generate a layout component
  rw g page <name> [path]    Generate a page and route component
  rw g scaffold <model>      Generate Pages, SDL, and Services files based on a
                             given DB schema Model. Also accepts <path/model>
  rw g sdl <model>           Generate a GraphQL schema and service component
                             based on a given DB schema Model
  rw g service <name>        Generate a service component

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Also see the Redwood CLI Reference
(​https://redwoodjs.com/reference/command-line-interface#generate-alias-g​)

Unknown argument: tailwinds
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by peterp** [comment]
Hey there!

This is totally a misstep on our part because this command will only be available in the next release that's coming out today:`v0.17.0`

**Comment by peterp** [comment]
Until we've released it here are some docs for setting it up: https://redwoodjs.com/docs/webpack-configuration#adding-tailwindcss

**Comment by CR1AT0RS** [comment]
Oh thanks! Ya I knew there was something wrong with the version. But I saw the latest version 0.16.0 so I thought maybe it's something else. Thanks!

**Comment by CR1AT0RS** [comment]
This was resolved since 0.17.0 is out. Closing this request!
