### ISSUE TITLE
[Docs]: useCache!!!

### ISSUE THREAD

**Issue by razzeee** [redwoodjs/redwood#10546]
### Summary and description

Was reading the fragments docs, then stumbled over this

https://redwoodjs.com/docs/graphql/fragments#usecache

https://github.com/redwoodjs/redwood/blob/610716579d3398f5b15da078b5a684a09f6ac495/docs/docs/graphql/fragments.md?plain=1#L179

I guess it's a placeholder?

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by dthyresson** [comment]
Hi @razzeee thanks for noting.

I've already addressed this in https://github.com/redwoodjs/redwood/pull/10054 we just have not merged and re-deployed the docs.

@Tobbe and @Josh-Walker-GM should we get https://github.com/redwoodjs/redwood/pull/10054 in?
