### ISSUE TITLE
Firebase Auth: Allow the user to define the `AuthProvider`

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#1058]
The Firebase AuthProvider currently is set to use Google to sign in.

```js
    login: async () => {
      const provider = new client.auth.GoogleAuthProvider()
      return client.auth().signInWithRedirect(provider)
    },
```

There are other issues about firebase and signup, but this issue specifically concerns being able to set other providers for Firebase such as:

* FirebaseAuthProvider
* EmailAuthProvider
* FacebookAuthProvider
* FederatedAuthProvider
* GithubAuthProvider
* OAuthProvider
* PlayGamesAuthProvider
* TwitterAuthProvider

and even

* PhoneAuthOptions

**Comment by dthyresson** [comment]
Could a solution be to have the provider be set as an option to the login?

```js
    login: async (options) => {
      const provider = (options && options.provider) || new client.auth.GoogleAuthProvider()
 ...
```

for example:

```js
await logIn({ provider:   new firebase.auth.FacebookAuthProvider() })
```

or if scopes need to be set

```
const provider = new firebase.auth.FacebookAuthProvider() 
provider.addScope('user_birthday');
await logIn({ provider })
```

The nice thing about this is would support OAuth for Apple etc:

```
const provider = new firebase.auth.OAuthProvider('apple.com');
```

**Comment by jtoar** [comment]
@dthyresson does https://github.com/redwoodjs/redwood/pull/1412 close this one? It doesn't seem to 100% right?

**Comment by dthyresson** [comment]
@jtoar I think we should close this out as the Firebase client does support several providers

```js
// @TODO: Firebase doesn't export a list of providerIds they use
// But I found them here: https://github.com/firebase/firebase-js-sdk/blob/a5768b0aa7d7ce732279931aa436e988c9f36487/packages/rules-unit-testing/src/api/index.ts
export type oAuthProvider =
  | 'google.com'
  | 'facebook.com'
  | 'github.com'
  | 'twitter.com'
  | 'microsoft.com'
  | 'apple.com'
```

However, it does not allow passing `scope` to those as in:

```js
const provider = new firebase.auth.OAuthProvider('apple.com');
provider.addScope('email');
provider.addScope('name');
await logIn({ provider })
```

or

```js
const provider = new firebase.auth.OAuthProvider('apple.com');
provider.addScope('email');
provider.addScope('name');
await logIn({ provider })
```

I think scopes should be a new issue.

**Comment by doesnotexist** [comment]
I think provider.addScope is handled in the current implementation:
https://github.com/redwoodjs/redwood/blob/main/packages/auth/src/authClients/firebase.ts#L48-L50
