### ISSUE TITLE
Inject "HOST" into Redwood's Context

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#1063]
Right now it's very difficult to tell which domain your code is running on. Usually you know this, and it's fine since you only have a finite amount of environments, but your code does not.

It would be nice if we made this available in Redwood's context.

-  [x] Netlify
```js
const getNetlifySiteFromContext = (context) => {
  const data = context.clientContext.custom.netlify
  const decoded = JSON.parse(Buffer.from(data, 'base64').toString('utf-8'))
  console.log(JSON.stringify(decoded))
  return decoded
}
```
I do wish this was just an env var; it's apparently available at build time: DEPLOY_URL
https://community.netlify.com/t/are-deploy-url-deploy-prime-url-available-outside-of-netlify-toml/634/9

- [ ] Vercel: Some discussion here, but doesn't look promising: https://github.com/vercel/vercel/issues/1054

**Comment by thedavidprice** [comment]
This feels like an obvious miss for Netlify and Vercel. Should definitely be a default ENV Var. 

That aside, what about a redwood.toml option? The value could be added to web/ however we like including as ENV Var. Could even have different options for staging and production. 

Perhaps this would work for API as well if we got fancy during build (although not exactly sure how this would work).
