### ISSUE TITLE
Add "removeDeprecatedGapUtilities: true" to generated tailwind config

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#1064]
You get this warning from the folks at Tailwind, let's do the right thing and remove it in our generated configuration: https://tailwindcss.com/docs/upcoming-changes

**Comment by peterp** [comment]
More information about this:

We generate a tailwind configuration with the following command: `yarn rw generate util tailwind`, we should modify the generated configuration to include:
```js
// tailwind.config.js
module.exports = {
  future: {
    removeDeprecatedGapUtilities: true,
  },
  // ...
}
```

**Comment by helpsdev** [comment]
Hi there, I'm a first-time contributor, any chance I can work on this?

**Comment by christianto88** [comment]
@peterp hi i would like to take this task

**Comment by forresthayes** [comment]
@helpsdev & @christianto88 

Hi! My [pull request](#1179) is already under review for this issue. 

There are a lot of other great first issues available if you're interested in tackling some of those!

**Comment by thedavidprice** [comment]
Hi @helpsdev and @christianto88 Thank you both for offering to help!! We welcome you both to the community. As Forrest mentioned, this one is already in process. Please take a look at this link with some tips for getting started on other Issues: https://github.com/redwoodjs/redwood/issues/1266

Don't hesitate to reach out as needed.
