### ISSUE TITLE
[Bug?]: yarn rw setup auth supabase not working

### ISSUE THREAD

**Issue by jcianca** [redwoodjs/redwood#10678]
### What's not working?

Trying to setup Supabase Auth following the HowTo and I get errors. 

web/src/pages/SignupPage/SignupPage.tsx
`import { useAuth } from '@redwoodjs/auth'`
error on useAuth says: Module '"@redwoodjs/auth-supabase-web"' has no exported member 'useAuth'.

Going to signup page says:
The requested module 'http://localhost:8910/[...]/auth6/web/node_modules/.vite/deps/@redwoodjs_auth.js?v=43111126' doesn't provide an export named: 'useAuth'

Console:
[console-export-2024-5-22_20-20-25.txt](https://github.com/redwoodjs/redwood/files/15410075/console-export-2024-5-22_20-20-25.txt)

### How do we reproduce the bug?

```
yarn create redwood-app
yarn install
yarn rw setup auth supabase
```
- Updated my .env file and redwood.toml and ran dev, home page works fine
- Create a signup page according to the "How To: Supabase Auth" and when I go to that page I notice the errors

I run yarn install and it shows:
@supabase/supabase-js is listed by your project with version 2.43.3, which doesn't satisfy what @redwoodjs/auth-supabase-web (pe0efc) requests (2.43.2).
- I add @supabase/supabase-js@2.43.2 and update package.json and yarn install looks normal but still have the useAuth issue.

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 14.4.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - /private/var/folders/8c/st4fqgxj5nv0fn8yjz4xdvhw0000gn/T/xfs-d2b35eed/node
    Yarn: 4.2.2 - /private/var/folders/8c/st4fqgxj5nv0fn8yjz4xdvhw0000gn/T/xfs-d2b35eed/yarn
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 124.0.6367.210
    Safari: 17.4.1
  npmPackages:
    @redwoodjs/auth-supabase-setup: 7.6.2 => 7.6.2 
    @redwoodjs/core: 7.6.2 => 7.6.2 
    @redwoodjs/project-config: 7.6.2 => 7.6.2 
  redwood.toml:
    [web]
      title = "Redwood App"
      port = 8910
      apiUrl = "/.redwood/functions"
      includeEnvironmentVariables = ["SUPABASE_URL", "SUPABASE_KEY"]
    [api]
      port = 8911
    [browser]
      open = true
    [notifications]
      versionUpdates = ["latest"]
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Tobbe** [comment]
@jcianca sorry you're having problems. 

Did you try with just the basic HomePage example from our docs? https://redwoodjs.com/docs/auth/supabase#basic-example
Does that work for you?

Can you share your SignupPage? Sounds like some import is a bit wrong on there

**Comment by jcianca** [comment]
Thanks for the quick response! I tried this and it works, so I guess it isn't a bug but a documentation issue? I was following the SignupPage from here: https://redwoodjs.com/docs/how-to/supabase-auth

I now got it all working by changing every instance of `import { useAuth } from '@redwoodjs/auth'` to  `import { useAuth } from 'src/auth'`. I'm not sure why the How To says to import from @redwoodjs/auth but that doesn't seem to work... if it's just out of date I'd be happy to update that.

**Comment by Tobbe** [comment]
Yes, that document is out of date! We used to do it that way before, but have switched to importing from `src/auth`. Must have forgotten to update that guide. Would be great if you could update the docs 🙏

**Comment by jcianca** [comment]
Ok sounds great! I submitted a PR [#10679](https://github.com/redwoodjs/redwood/pull/10679)
Sorry I'm new here, should I update the title of this issue to reflect that it was a docs issue? Who closes this issue? Thanks!

**Comment by dthyresson** [comment]
Hi @jcianca and thanks for finding this issue and the docs fix.

> Who closes this issue?

I'll reference this issue in your PR and when the PR is merged, this issue will automatically close.
