### ISSUE TITLE
[RFC]: Omit front side - use Redwoodjs as a Server only

### ISSUE THREAD

**Issue by Tsimopak** [redwoodjs/redwood#10715]
### Summary

I'd suggest to create and build only backend side, to allow developers to use any web/mobile front framework and tech.

### Motivation

I think that would be great to allow more versatile tools for the developer to use

### Detailed proposal

I guess from the beginning we could could create a redwood project with `--backend` flag or something like that to allow only backend code to be generated

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Tobbe** [comment]
A great first step here would be to set up a regular Redwood project, and then document what it takes to get rid of the web side of things. 
@Tsimopak is that something you'd be interested in doing?

**Comment by Tsimopak** [comment]
Thanks Tobbe! I wish I would have enough time to do that! unfortunately I have no time to do that, hopefully in the future if it would still be relevant

**Comment by dthyresson** [comment]
FYI, there is discussion of this topic in the Community by me and @Tsimopak here: https://community.redwoodjs.com/t/use-redwoodjs-generator-to-create-crud-operations-and-graphql-sdls-from-prisma-scheme/7174/12
