### ISSUE TITLE
[Bug?]: dbAuth handler resePasword does not validate password format as signup does

### ISSUE THREAD

**Issue by irg1008** [redwoodjs/redwood#10724]
### What's not working?

dbAuth handler resePasword does not validate password format as signup does

Basically on signUp handler we can set a custom password validation like for exmaple:
```typescript
...
    passwordValidation: (password) => {
      validate(password, 'password', {
        length: { minimum: 8 },
        format: {
          pattern: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/,
          message:
            'Password must contain at least 1 uppercase letter, 1 lowercase letter, and 1 number',
        },
      })

      return true
    },
...
``` 

But then in the "resetPassword" handler the password is set to the database as it comes from the client, be that a simple number....

We should be able to validate the password somehow, maybe using the same passwordValidation as sign up since that makes sense

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by dac09** [comment]
Hello @irg1008 thanks for raising this, and I can confirm that you cannot currenly customise the validation function on the server side for reset password. 

@cannikin I looked through the dbAuth handler, and it would be relatively straightforward (I think!) to call the options - `(this.options.signup as SignupFlowOptions).passwordValidation` in the forgot password flow too. 

If you have time, do you think you could look at this one please?

**Comment by irg1008** [comment]
I think I can do this no problem

**Comment by irg1008** [comment]
Okay I just created de PR. Check it out if you find the time. Could this mean breaking changes since could affect some users bussiness logic?

**Comment by Josh-Walker-GM** [comment]
This was closed by https://github.com/redwoodjs/redwood/pull/10734 or is there more work to be done on this?
