### ISSUE TITLE
[Bug?]: graphiql authImpersonation breaking on windows

### ISSUE THREAD

**Issue by irg1008** [redwoodjs/redwood#10752]
### What's not working?

When using authImpersination for testing graphql using redwood studio, and then navigating to the `Playground` tab, throws the next error on windows:

```powershell
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:236:11)
    at defaultLoad (node:internal/modules/esm/load:128:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:409:13)
    ...
 ```
 
Removing [studio.graphiql.authImpersonation] makes it work again

I see tha the function causing this issue is `generateAuthHeaders`

I wouldn't mind taking a look and trying to fix it but any guidence would be useful to narrow it down

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by irg1008** [comment]
Related to #9545

**Comment by Josh-Walker-GM** [comment]
Hey @irg1008, you can find the code for studio in this repo: https://github.com/redwoodjs/studio. 

For the main repo we started using a single function to generate the import string. We had been doing it individually across the code base and had been inconsistent in our approach - which led to bugs like this every now and then. This code might be transferable if you think it is correct to solve this issue:
https://github.com/redwoodjs/redwood/blob/93222ddfc51a650bc9330725c7f3d56cb7847f9e/packages/vite/src/utils.ts#L31-L37

**Comment by irg1008** [comment]
I will take a look when I get the time, in the meantime I have moved to WSL and no issues so far. On the other hand, do you know if the team is discussing about adding support for "shared" code or packages in monorepo? I mean sharing code and being able to import it both in web and api (my use cases are zod schemas)

I am being able to use this schemas when inside "scripts" folder and web, but importing inside api and it won't work without compiling etc

I know of a couple of issues regarding this but they are stale or are 1 or more years old. I could open a new issue but I don't want to start bloating the repo
