### ISSUE TITLE
Proposal: Add "Paper Cuts" category to v1 Roadmap

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1080]
cc @mojombo 

**Suggestion**
Add a "Paper Cuts" category to the v1 Roadmap. It will be the lowest priority; perhaps not even v1 required.

**The Why**
There is not a specific category for DX. Overall, I think the current state of the DX is in remarkable shape. But I there's another subset of minor DX issues that can be major annoyances. These can be hard to track and prioritize — for example, I personally have been sitting on a few `yarn create redwood-app` tasks that aren't problems, e.g. checking engines _before_ trying to install. But when they go wrong they have an outsized impact on the overall experience. And there's also the reverse side of this — I aliased `yarn rw` to `rw` and it's been a sheer delight at the command line. Nothing's broken, but it makes me happier.

- Installation hiccups
- Managing Env Vars across an app's lifecycle
- Debugging
- Prisma Relations not working after Scaffolding (we have this handled in an issue already)
- Not knowing which documentation to search (or use) for a specific component of Redwood. E.g Prisma CRUD is what you need when working in a normal Services file (not obvious to someone new to the framework without digging in a bit)

**Comment by amorriscode** [comment]
I'll admit, I have thought that the documentation could use a bit of massaging. Sometimes when I need to find something in the docs, I end up looking in the tutorial (didn't take notes when it happened so I don't have a solid example).

I wonder if there could be subsections in the docs. For example, there could be one for `Database` and underneath it you'd find migrations, schema relations, and information about the Prisma studio (which I missed until I read the `CLI` page).

In the end I've started to use the search a lot more. Maybe that makes all of this pointless. 😅
