### ISSUE TITLE
[Bug?]: MockGraphQLQuery not working when original query uses fragments

### ISSUE THREAD

**Issue by irg1008** [redwoodjs/redwood#10807]
### What's not working?

When mocking a graphql query inside a component to be able to render Cell children, it breaks when using fragments inside the Cell Query.

My query in `ChatMessagesCell.tsx`:
```typescript
export const QUERY: TypedDocumentNode<
  ChatMessagesQuery,
  ChatMessagesQueryVariables
> = gql`
  query ChatMessagesQuery($chatRoomId: String!) {
    chatMessages(chatRoomId: $chatRoomId) {
      id
      body
      createdAt
      user {
        id
        displayName
      }
    }
  }
`
```

Then I mock this query inside a parent component `Chatbox.stories.tsx`:
```tsx
    mockGraphQLQuery<ChatMessagesQuery, ChatMessagesQueryVariables>(
      'ChatMessagesQuery',
      (_variables) => {
        console.log('standard().chatMessages', standard().chatMessages)
        return {
          chatMessages: standard().chatMessages,
        }
      }
    )
```

This works as it should, mocks the list using the standard values

![image](https://github.com/redwoodjs/redwood/assets/47559427/01e5701c-f873-4ecf-97f3-40b9da665c32)

BUT THEN:

My query with fragments in `ChatMessagesCell.tsx`:
```typescript
registerFragment(gql`
  fragment ChatMessageFragment on ChatMessage {
    id
    body
    createdAt
    user {
      id
      displayName
    }
  }
`)

export const QUERY: TypedDocumentNode<
  ChatMessagesQuery,
  ChatMessagesQueryVariables
> = gql`
  query ChatMessagesQuery($chatRoomId: String!) {
    chatMessages(chatRoomId: $chatRoomId) {
      ...ChatMessageFragment
    }
  }
`
```

With the same mock. The list is created from the `standard()` function but the inner objects are empty

![image](https://github.com/redwoodjs/redwood/assets/47559427/0fd4cb6c-73b6-442d-aeec-815069d63a28)

Am I missing something when using fragments? I followed the docs carefuly but maybe (probably) I missed something

Thanks guys and sorry to open so many issues but that means I really like and want this to improve!

### Are you interested in working on this?

- [x] I'm interested in working on this

**Comment by dthyresson** [comment]
Hi @irg1008 and thanks for writing up this issue — I’ll have to recreate it with. Small reproduction.

One question: for the log output of your mock is that from running a test or using storybook?

**Comment by dthyresson** [comment]
> If need me to create a small repo please say so

If you could, that would be really helpful for me to reproduce and know we are seeing the same thing.

Thanks!

**Comment by irg1008** [comment]
Okay there you go: https://github.com/irg1008/issue-redwood-fragments-storybook.git

1. Install (yarn install, etc)
2. `yarn rw dev`
3. `yarn rw storybook`
4. Open storybook > Components > Chat: See that IS WORKING
5. Go to `ChatCell.tsx`
6. Uncomment and comment to swap to using fragment
7. Open storybook > Components > Chat: NOT WORKING

**Comment by dthyresson** [comment]
Hi @irg1008 I forked and made PR on your demo repo here: https://github.com/irg1008/issue-redwood-fragments-storybook/pull/1

The cells themselves appear to mock ok, but when the cell is then used in a component (or maybe even a page) and that story then doesn't appear to "pass along" the mocked data so to speak. Am investigating still.

**Comment by irg1008** [comment]
I just merged it. If you need any help I am starting to learn the redwood repo I can help

**Comment by dthyresson** [comment]
Hi @irg1008 thanks to @arimendelow we think we figured it out. Ignore the updates I made to your reproduction repo as having the two cells with the two queries can confuse the issue. but try using:

```

// Define your own mock data here:
export const standard = (/* vars, { ctx, req } */) => ({
  chatMessages: Array.from({ length: 20 }, (_, index) => ({
    __typename: 'ChatMessage',
    body: `Message${index + 1}`,
    createdAt: '2021-07-01T00:00:00.000Z',
    id: index + 1,
    user: {
      __typename: 'ChatUser',
      displayName: `User ${(index % 5) + 1}`, // Cycle through 5 different users
      id: (index % 5) + 1,
    },
    chatRoomId: '42',
  })) satisfies ChatMessage[],
})
```

in `ChatCell.mock.ts`.


Notice the `__typename` in the data to note what the GraphQL types are. This appears to be needed so that Apollo can understand have to use the fragments and map the data coming back.

Some more info in: https://github.com/mswjs/msw/issues/630

Can you see if that works for you?

We'll update the Fragment docs (or if you feel like making a docs PR, that'd be amazing) and then think about how this might be done more transparently. But it is good practice I guess to include the typenames since that in fact does come back in real-world cases from Yoga.

**Comment by irg1008** [comment]
Oh my god I would have never thought of that, will try it tomorrow and let you know. And will happily make the PR to the fragment docs. Thanks!

**Comment by dthyresson** [comment]
> I would have never thought of that

We didn't either -- until we found that issue and then it actually makes perfect sense. 

Under the covers RedwoodJS replies on https://www.apollographql.com/docs/react/data/fragments/#usefragment and we think that needs to know the type to properly match up data with the fragment in the query.

**Comment by irg1008** [comment]
Okay it's working!, closing this know. Great work the RedwoodJS team is amazing
