### ISSUE TITLE
[RFC] Dropping support for IE 11

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#1082]
We're considering dropping support for Internet Explorer in the packages that we ship for the web: 

- @redwoodjs/web
- @redwoodjs/forms

The reason for this is that we want to reduce our bundle size. We would also provide instructions on how to build your own versions of the packages if you wish to support older browsers. Microsoft is dropping support for IE 11 [in a year.](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666).

I would like to get a sense from the community about if and how this would impact their decision to use Redwood.

**Comment by Burnsy** [comment]
I personally think this is a great, as I had to deal with many bugs in the past just because it does not work well on ie 11. Like local storage. 

My only want would be. We could show some kind of customisable compatibility page that could tell them that they would need to vist the application on a modern browser like edge or chrome.

**Comment by dac09** [comment]
No objections from us at Tape - its a dev product so expect people on decent browsers anyway!

**Comment by quantuminformation** [comment]
Can't stand ie11, couldn't drop it faster IMO

**Comment by peterp** [comment]
@Burnsy Regarding the idea of warning users that their browser isn't supported, I was thinking we can do something like this in `web/src/index.html`:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <title>Amazing APP!</title>
  </head>
  <body>
    <div id="redwood-app">
       Uh oh, the browser you're using it 12 years old and unfortunately we don't support it.
    </div>
  </body>
</html>
```

The idea would be that `id="redwood-app"` is replaced once the React stuff renders, but we could also make the rendering of the error conditional based lack of support for your browser.

**Comment by Burnsy** [comment]
That would work well, and also would work for other languages as the dev would define the strings and also could be heavily customized!
