### ISSUE TITLE
[Bug]: Docs search is broken

### ISSUE THREAD

**Issue by irg1008** [redwoodjs/redwood#10862]
### What's not working?

Guays the search is broken after 7.7 update:
![image](https://github.com/redwoodjs/redwood/assets/47559427/d678c41f-33b0-4b86-b133-79d17bcd6c00)

Rolling back to 7.6 works:
![image](https://github.com/redwoodjs/redwood/assets/47559427/32760e47-7ba3-4d68-b58b-96948db9249c)

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Thanks for flagging this up we made some changes to our site yesterday and this appears to have upset the crawler. Looking into this now.

**Comment by Josh-Walker-GM** [comment]
Looks like things are back working now. Would you mind double checking things are back working on your end @irg1008?

**Comment by irg1008** [comment]
It works!
