### ISSUE TITLE
[Bug?]: yarn rw upgrade for 7.7.1 error

### ISSUE THREAD

**Issue by SquirrelJimmy** [redwoodjs/redwood#10866]
### What's not working?

✖ Could not finish installation. Please run `yarn install` and then `yarn dedupe`, before continuing
◼ Refreshing the Prisma client
◼ De-duplicating dependencies
◼ One more thing..

yarn install
➤ YN0000: · Yarn 4.1.1
➤ YN0000: ┌ Resolution step
➤ YN0082: │ graphql-sse@npm:2.5.3: No candidates found
➤ YN0000: └ Completed in 0s 673ms
➤ YN0000: · Failed with errors in 0s 679ms

### How do we reproduce the bug?

redwood version 7.4.3 upgrade 7.7.1

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 14.3
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - /private/var/folders/87/d_6_sw8s66z292l5f78rw1740000gn/T/xfs-b6e7eb37/node
    Yarn: 4.1.1 - /private/var/folders/87/d_6_sw8s66z292l5f78rw1740000gn/T/xfs-b6e7eb37/yarn
  Databases:
    SQLite: 3.41.2 - /opt/anaconda3/bin/sqlite3
  Browsers:
    Chrome: 126.0.6478.114
    Safari: 17.3
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 7.7.1 => 7.4.3 
    @redwoodjs/core: 7.7.1 => 7.4.3
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by SquirrelJimmy** [comment]
when I upgrade version morethan 7.6.0，I will get the same error

**Comment by Josh-Walker-GM** [comment]
Hmm it looks like that package does exist at that version: https://www.npmjs.com/package/graphql-sse/v/2.5.3. This has happened in the past where for some unknown reason things can't be found on npm when they do exist. 

I'll try to look back and see if I can find anything we have got on any previous issues like this and follow up here. For now my only advice would be to try again or see if clearing any caches help, sorry!

**Comment by Tobbe** [comment]
@SquirrelJimmy Checking back in here – did you try again? Did it work?

**Comment by Tobbe** [comment]
Closing for now as no further info has been provided by the OP

**Comment by SquirrelJimmy** [comment]
> @SquirrelJimmy Checking back in here – did you try again? Did it work?

Not Work

**Comment by SquirrelJimmy** [comment]
> Closing for now as no further info has been provided by the OP

Sorry, It's my network proxy issue, It works now
