### ISSUE TITLE
“build and copy” tooling to improve package dev process

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#109]
Add a command to the redwood project that watches, builds and copies the packages to your desired destination.

As an example `yarn build-and-copy ../example-todo/`

This would check `./packages/*` for changes, build them, and copy those changes into `../example-todo/node_modules/@redwoodjs/<package>/`

- Would improve the current process/commands `rw self build` and `rw self link` from #90
- original conversation here #100  

- [ ] update `docs/contributing.md`

**Comment by thedavidprice** [comment]
Peter got started here:
https://github.com/redwoodjs/redwood/pull/319

This is a heavy lift. Would be helpful, but isn’t on the immediate list of priorities.

**Comment by peterp** [comment]
This is now done!
