### ISSUE TITLE
[Feature]: ESLint flat config support for @redwoodjs/eslint-plugin

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [redwoodjs/redwood#10909]
### What's not working?

Coming over from https://github.com/eslint/eslint/issues/18093 -> https://github.com/redwoodjs/redwood/issues/10897#issuecomment-2209352326: ESLint is migrating to a [new "flat config" format](https://eslint.org/docs/latest/use/configure/configuration-files-new) that will be the default in ESLint v9.

It doesn't look like `@redwoodjs/eslint-config` has support yet. I'm posting this issue here as a reference & cross-linking it to the table in https://github.com/eslint/eslint/issues/18093. If there's anything technical blocking the extension from supporting flat configs, please let us know - we'd be happy to try to help! 💜 

Additional resources:
* [Configuration Migration Guide](https://eslint.org/docs/latest/use/configure/migration-guide)
* [Plugin Migration Guide](https://eslint.org/docs/latest/extend/plugin-migration-flat-config)
* Blog posts on the new config system: [Part 1: Background](https://eslint.org/blog/2022/08/new-config-system-part-1), [Part 2: Introduction to flat config](https://eslint.org/blog/2022/08/new-config-system-part-2)

Per https://github.com/redwoodjs/redwood/issues/10897#issuecomment-2209352326, this issue is specifically for 🍌 `@redwoodjs/eslint-plugin`, not 🍎 `@redwoodjs/eslint-config`.

### How do we reproduce the bug?

Make an `eslint.config.js` with:

```js
import redwood from '@redwoodjs/eslint-plugin'

export default [/ * ... */ ]
```

...but the package doesn't yet export any configs we can use here in the flat config format.

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 13.2
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /var/folders/sr/j__6_9gn0dv557z0xf3p7y8h0000gn/T/yarn--1719857847260-0.8362240404148904/node
    Yarn: 1.22.19 - /var/folders/sr/j__6_9gn0dv557z0xf3p7y8h0000gn/T/yarn--1719857847260-0.8362240404148904/yarn
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by Tobbe** [comment]
Thanks for your issues and the PR. I'll try to dig and and follow up with any questions I might have
