### ISSUE TITLE
[Bug?]: Deploy to Vercel breaks all server functions (500 errors with cryptic messages)

### ISSUE THREAD

**Issue by DrakenKor** [redwoodjs/redwood#10926]
### What's not working?

Hi,
My RedwoodJS project, which was running fine previously, now breaks on deployment in the live environment.

All backend functions are throwing 500 errors, with cryptic messages. Everything is working same as before locally (100% fine). These functions are event/timer driven as well as user triggered, all are broken.

My intuition says that the way Vercel is building Redwoodjs is changed, and this change is breaking the site

Not sure if it's related to Vercel changing the deployment for RedwoodJS:

https://github.com/redwoodjs/redwood/issues/10022

Currently my project, which serves a client, is down and I've tried the following fixes on my end (No resolution):

Upgrade Redwood from ~7.6 to latest 7.7.2
Add a vercel.json with some basic configuration:
![image](https://github.com/redwoodjs/redwood/assets/9381459/42c25f7d-21dd-44af-b1ab-5775c42b77a3)

Errors:
![image](https://github.com/redwoodjs/redwood/assets/9381459/6c38af13-932b-433f-8141-cef9840ce1a1)

Complete error from backend function:
```

Unhandled Rejection: SyntaxError: Unexpected end of JSON input
at parse (<anonymous>)
at JSON.parse (/var/task/node_modules/core-js/modules/esnext.json.parse.js:249:56)
at IncomingMessage.<anonymous> (/opt/rust/nodejs.js:1:12751)
at IncomingMessage.emit (node:events:519:28)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.


```

### How do we reproduce the bug?
Deploy redwood 7.7.2 to Vercel, with atleast 1 backend function apart from graphql. 

### What's your environment? (If it applies)

```
My local environment
System:
    OS: macOS 14.5
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /var/folders/r5/mjyksjsd78b81bj1lyrtd0980000gn/T/yarn--1720509206850-0.9503137294015356/node
    Yarn: 1.22.17 - /var/folders/r5/mjyksjsd78b81bj1lyrtd0980000gn/T/yarn--1720509206850-0.9503137294015356/yarn
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 7.7.2 => 7.7.2 
    @redwoodjs/core: 7.7.2 => 7.7.2 
  redwood.toml:
    [web]
    title = "Rin Kim Law"
    port = 8910
    apiUrl = "/api"
    includeEnvironmentVariables = [
      'AS_CLIENT_ID',
      'APP_URL',
      'ENVIRONMENT'
      # Add any ENV vars that should be available to the web side to this array
      # See https://redwoodjs.com/docs/environment-variables#web
    ]
    [api]
    port = 8911
    [browser]
    open = true
    [notifications]
    versionUpdates = ["latest"]
```

### Update
I just noticed that Vercel now have a 'comments middleware' that applies to all routes, and it's an edge function. This could be the culprit:

![image](https://github.com/redwoodjs/redwood/assets/9381459/005cb65a-531f-46f2-8bed-078536c8ac87)

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by RinKimLaw** [comment]
Hi does anyone else have any issues with Vercel deployed Redwood? I've deleted my project off Vercel given my experience I wouldn't recommend Vercel as a deploy target for RedwoodJS.

**Comment by dthyresson** [comment]
Hi @DrakenKor and @RinKimLaw I was working with Vercel to improve the deployment and have them fix the build issue where functions didn't get configured for memory or duration and I think their cli update https://github.com/vercel/vercel/pull/11776 got released before we could let you and other Vercel users know.

I have a draft for the docs change: https://github.com/redwoodjs/redwood/pull/10891

We intended to have fixes for https://github.com/redwoodjs/redwood/issues/10022 and https://github.com/redwoodjs/redwood/issues/1664 with https://github.com/vercel/vercel/pull/11776.

Documents support for Vercel API endpoint (ie, functions) configuration via export const config syntax.

I'll try a few builds and deploys as well but, could you try:

1. not using vercel.json
2. confirmed the functions the new upcoming docs 

```
By default, API requests in Vercel have a timeout limit of 15 seconds, but can be configured to be up to 90 seconds. Pro and other plans allow for longer [duration](https://vercel.com/docs/functions/runtimes#max-duration) and larger [memory-size limits](https://vercel.com/docs/functions/runtimes#memory-size-limits).

To change the `maxDuration` or `memory` per function, export a `config` with the settings you want applied in your function. For example:

```ts
import type { APIGatewayEvent, Context } from 'aws-lambda'

import { logger } from 'src/lib/logger'

export const config = {
  maxDuration: 30,
  memory: 512,
}

export const handler = async (event: APIGatewayEvent, _context: Context) => {
  logger.info(`${event.httpMethod} ${event.path}: vercel function`)

  return {
    statusCode: 200,
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      data: 'vercel function',
    }),
```

Thanks and appreciate patience as we wanted to make the RW + Vercel experience better.

**Comment by dthyresson** [comment]
@DrakenKor Could you give me some more information on:

> I just noticed that Vercel now have a 'comments middleware' that applies to all routes, and it's an edge function. This could be the culprit.

I used your https://github.com/DrakenKor/vercel-redwood-tester to reproduce and shared with Vercel to try it out.

If you could update that repo with how you have setup and edge function, I can try that and then get in touch with Vercel to see what might be happening.

I'll try with an example like: 

```ts
export const config = {
  runtime: 'edge',
}

export default function handler(_req: Request) {
  return new Response('Hello World')
}

```

**Comment by RinKimLaw** [comment]
This is the error I see as well:

![image](https://github.com/user-attachments/assets/db505e17-e6bf-45d4-97d2-b73c977ce97a)

I didn't have any edge functions configured, but vercel deployed one of my functions at the edge anyway.

**Comment by RinKimLaw** [comment]
Hi,
I've redeployed our site with a new config on each backend function that has the runtime value nodejs20.x:
![image](https://github.com/user-attachments/assets/d50d85a2-b951-4011-859a-4f5e49419096)

I can confirm the system is now fully functional again, and that the config maxDuration & memory is being honoured.

So I can confirm that this is a bug with RedwoodJS backend functions deployed as **edge functions** on Vercel. Any edge function will throw 502/500 and if a backend function is wrapped with a middleware edge function, that'll also throw 502/500.

 My issue is resolved but if I can be of any further assistance please let me know.

**Comment by dthyresson** [comment]
@RinKimLaw or @DrakenKor 

> I can confirm the system is now fully functional again, and that the config maxDuration & memory is being honoured.

Great to hear!

> So I can confirm that this is a bug with RedwoodJS backend functions deployed as edge functions on Vercel. Any edge function will throw 502/500 and if a backend function is wrapped with a middleware edge function, that'll also throw 502/500.

Can you share more details about this? Am a bit confused if you have edge functions or not.

Actually, maybe we should pair on it to resolve faster -- then I can also communicate back to Vercel any issues more clearly.

Could you find some time next week perhaps here: https://savvycal.com/dt/redwoodjs

Thanks!

**Comment by RinKimLaw** [comment]
@dthyresson 

To summarise:
The issue arose for us when some of our backend functions were automatically deployed as edge functions by Vercel. We had no edge function config (Or any other config) in our Redwoodjs project and the edge function config is some default config by Vercel. I noticed that there was a middleware edge function and this wrapped all the backend functions, and all the backend functions were throwing 502/500 errors. Then you gave your suggestion on how to configure the functions for Vercel using `export const config = {}`  syntax and I was finally able to configure all my backend functions as node20.x functions, and the errors stopped. The middleware function disappeared.

I know that NextJS has a middleware edge function deployed by default, and I think Vercel's default deploy for RedwoodJS introduced that middleware similar to NextJS. I think when they changed the config method for RedwoodJS, they broke the default deployment config.

**Comment by DrakenKor** [comment]
@dthyresson I've booked a time for you on (I assume) your Monday evening (My Tuesday morning)

**Comment by phil714** [comment]
@dthyresson hey I'm having a similar issue as this, I see the middleware functions in my vercel as an edge function and also have the bad gateway error when attempting to call api/auth. Per the doc, I added the code below to both my auth.ts & graphql.ts file but haven't seen any changes. Am I missing something obvious ? Thanks

My repository: https://github.com/phil714/family-recipes

```
export const config = {
  runtime: 'nodejs20.x',
}
```

**Comment by dthyresson** [comment]
> having a similar issue as this

The middleware present is apparently to be expected.

The https://github.com/vercel/vercel/pull/11776 should fix.

I'd suggest making sure you have updated your vercel cli to the latest version.

make sure your Vercel cli is the latest ... the I tested last, the fix was in the following so needs to be at least this:

```
vercel-redwood-tester main % vercel --version
Vercel CLI 34.3.1
34.3.1
```
If not, please `npm i -g vercel@latest.`

Ifr this persists, I may have to get in touch with our contacts at Vercel.

**Comment by dthyresson** [comment]
@phil714 when you run the Redwood deploy script for Vercel the Vercel cli command is used:

https://github.com/redwoodjs/redwood/blob/003ec5612d343c727569b126f2effb22e15450da/packages/cli/src/commands/deploy/vercel.js#L5

So we need to know what version of that command is currently installed and upgrade it to a version that fixed the way Vercel builds so that the configuration can be applied properly.

it would have been installed at some point when setting up Vercel deployment.

This isn’t unique to Vercel. Netlify has a cli command it used to build and package up an app for its system to accept. Vercel does this too using its command.

if you could run those command in the above comment to determine the version and if it’s older than the number listed , then upgrade using the upgrade command also listed.

We need to have the latest version running or it won’t ally the configuration properly

**Comment by phil714** [comment]
I noticed that in my build, it seems to be running the version 37 and also installed vercel manually into my project. Anything else I should look into ?
<img width="1196" alt="Screenshot 2024-10-12 at 3 51 46 PM" src="https://github.com/user-attachments/assets/0fd5bf9a-1ada-439b-9644-401560cb4a2e">

**Comment by phil714** [comment]
Would this resolve the issue ? They will apparently allow NodeJS to be used in the middlewares. 
https://github.com/vercel/next.js/discussions/46722

My vercel deployment is still breaking from the 502, like mentioned above, my build is using the latest version of the vercel-cli and I added a `const config = {}` to both my functions.

**Comment by emreozincegedik** [comment]
hello, I was able to bypass this error by adding SESSION_SECRET to vercel environment variables. After this the 502 error was resolved. Even though I resolved the 502, now the vercel is not setting the set-cookie header. Any idea how to move from here?
