### ISSUE TITLE
[Bug?]: cannot set bodyLimit using server.ts

### ISSUE THREAD

**Issue by tilmann** [redwoodjs/redwood#10958]
### What's not working?

After updating from v6 to v7 I am trying to migrate from the existing server.config.js to server.ts.

I need to configure the bodyLimit:

If I use the following server.ts and remove the server.config.js the bodyLimit for our deployed app (azure app service in a container) the value in server.ts is ignored.

We are starting the server for our app service using `yarn rw serve api --port 8911`

### How do we reproduce the bug?

- set the bodyLimit as shown in the code
- start the server and try a request with some MB in the body

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 14.5
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - /private/var/folders/ys/x3sc951n7zsbd01tmk3j5g9m0000gn/T/xfs-cad50a9b/node
    Yarn: 3.2.3 - /private/var/folders/ys/x3sc951n7zsbd01tmk3j5g9m0000gn/T/xfs-cad50a9b/yarn
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Edge: 126.0.2592.102
    Safari: 17.5
  npmPackages:
    @redwoodjs/auth-azure-active-directory-setup: 7.7.2 => 7.7.2 
    @redwoodjs/cli-data-migrate: 7.7.2 => 7.7.2 
    @redwoodjs/cli-storybook: 7.7.2 => 7.7.2 
    @redwoodjs/core: 7.7.2 => 7.7.2
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Hey @tilmann 👋 

> set the bodyLimit as shown in the code

Did you mean to include a code snippet with this or is this covered in our documentation etc?

**Comment by dthyresson** [comment]
I’m picking up issue triage this week from @Josh-Walker-GM and was hoping @tilmann that you could share a reproduction or example. Does this involve uploads? 

Might https://github.com/redwoodjs/redwood/pull/10573 fix it?

**Comment by tilmann** [comment]
I tested it again with rw 8.3 and it works perfectly. 

Thanks team.
