### ISSUE TITLE
Remove cache-and-network fetchPolicy

### ISSUE THREAD

**Issue by dnprock** [redwoodjs/redwood#1104]
I found that post-v0.12 Cell's Success function is always called twice. I trace the issue to the following change:

https://github.com/redwoodjs/redwood/pull/796

My guess is the Apollo Client will return data from the cache first and redwoodjs calls Success. Then it issues a network query and redwoodjs calls Success again. I think we should move back to using the default behavior. cache-and-network should be used for frequently updated data. But currently, it's used for all Cells.

https://medium.com/@galen.corey/understanding-apollo-fetch-policies-705b5ad71980

"I have found ‘cache-and-network’ to be a good option for displaying data that gets updated frequently. While the ‘cache first’ policy emphasizes quick responses to queries, ‘cache-and-network’ puts a little more weight on keeping the cache up-to-date with what is on the server. Implementing this fetch policy can be a good fix if you have data that is changing frequently and your queries are returning out-of-date information."

Calling Success twice can result in unpredictable rendering behaviors. I describe one example here:

https://community.redwoodjs.com/t/warning-cant-perform-a-react-state-update-on-an-unmounted-component/1142

**Comment by thedavidprice** [comment]
Thanks for this @dnprock! Looping in @peterp

**Comment by peterp** [comment]
I don't know why this wasn't on my radar. I agree. Let's get this in.

**Comment by amorriscode** [comment]
@peterp I'd love to take this one on!

**Comment by thedavidprice** [comment]
Related #1240

**Comment by thedavidprice** [comment]
@dnprock 

This should be resolved by #1250 

You can test the latest code using the canary release `0.19.2-canary.36`. Via command line use `yarn rw upgrade -t canary` to upgrade to the latest canary release. (Note: canaries should be considered unstable)
