### ISSUE TITLE
Dependabot Improvement: Auto-merge patch releases

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1122]
@peterp I suggest we consider having Dependabot auto-merge if the following conditions are met:
- patch release
- set minimum compatibility, e.g. 90%
- not a package like `core-js` that requires specific coordination

Reactions and/or suggestions?

**Comment by peterp** [comment]
@thedavidprice I like it!

**Comment by peterp** [comment]
This was shipped, radsauce.
