### ISSUE TITLE
Disable GraphiQL playground and introspection in production

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#113]
According to the [docs](https://www.apollographql.com/docs/apollo-server/testing/graphql-playground/) this is done automatically when `NODE_ENV` is set to `production`, but this doesn't seem to be the case for the `apollo-graphql-lambda`

**Comment by cannikin** [comment]
Can confirm, this is the tutorial blog deployed to Netlify but the GraphQL GUI still comes up: https://hungry-hawking-c81bc6.netlify.com/.netlify/functions/graphql

**Comment by thedavidprice** [comment]
Taking a look into this to see if it’s anything obvious. 

Any sense of where this fits on priorities for 0.1 milestone tasks?

**Comment by cannikin** [comment]
Yeah on the call Tom and I thought it wasn't absolutely necessary for the 0.1 release.

**Comment by thedavidprice** [comment]
Haven’t run this, but based on docs I have a sense of the problem:
1. Netlify sets `NODE_ENV` to `development` for build process to include all `devDependencies`: https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-environment
    - It does not appear that Netlify has an equivalent default preconfigured for Deployment
2. By default, Apollo enables GraphQL Playground (as well as introspection) _unless_ `NODE_ENV` is set to `production`: https://www.apollographql.com/docs/apollo-server/testing/graphql-playground/

**Possible Fix:**
Using `netlify.toml`, add `NODE_ENV = production` to the Netlify production “context" :
https://docs.netlify.com/site-deploys/overview/#deploy-contexts

**Comment by thedavidprice** [comment]
@cannikin There’s a (good) chance I’m not fully understanding how Netlify “contexts” work, e.g. it might be setting the whole build—>deploy process for a specific branch to context.production. But created a PR attempting a fix here:
https://github.com/cannikin/redwoodblog/pull/1

Worst case we run it by the Slack channel #netlify-hammer
