### ISSUE TITLE
Add helpful next steps to end of `create-redwood-app`

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#114]
Create shows the following when the command has finished:
```terminal
Initialized a git repository.

Success! Created MyProject at /Users/peterp/Personal/redwoodjs/MyProject
Inside that directory, you can run several commands:

  yarn start
    Starts the development server.

  yarn build
    Bundles the app into static files for production.

  yarn test
    Starts the test runner.

  yarn eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd xxx
  yarn start

Happy hacking!
✨  Done in 29.52s.
```

I think it would be great to point to the tutorial, to mention some commands, and the first steps to get the project working.

**Comment by thedavidprice** [comment]
Also consider:
- [ ] initial git init during yarn create installation

**Comment by thedavidprice** [comment]
@peterp I could use some help with this one. (pretty please!)

The state of the art (based on create-react-app) is apparently no fancier than `console.log(..)` with lots of spaces. Oh, and some `chalk()` for color. Easy peasy.

However, I'm stuck on two counts:
1) I can't break out of async hell. No matter what I do within the same file, I'm not able to log messages _after_  Listr does it's thing. They always end up happening during or before list tasks and display all over the place.
2) I'd like to catch a return from Listr to determine if the tasks were successful and then make the "Success Messages" execute only on successful task. I was attempting to catch Listr `STATE` observables to do this, but again got stuck in the async nightmare --> my state was always "PENDING". Here's the info on Listr:
https://github.com/SamVerschueren/listr#observables

This stuff isn't mission-critical right now. So when the dust settles would be great to review over screenshare.

**Comment by thedavidprice** [comment]
We reverted “git init” in CRA bootstrap. #175 Should add to this list
- [ ] add copy about suggesting “git init"
