### ISSUE TITLE
[Bug?]: Running `yarn rw storybook` command fails

### ISSUE THREAD

**Issue by craigwduckett** [redwoodjs/redwood#11427]
### What's not working?

Running the command `yarn rw storybook` results in an error `Unknown argument: storybook`

This is using the latest version of rw v8

### How do we reproduce the bug?

Following the Quick start guide.

- Run `yarn rw storybook`

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 14.6.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.1 - /private/var/folders/03/w63mvxks223fp36qypkn93lc0000gn/T/xfs-bc515cb5/node
    Yarn: 4.4.0 - /private/var/folders/03/w63mvxks223fp36qypkn93lc0000gn/T/xfs-bc515cb5/yarn
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 128.0.6613.114
    Safari: 17.6
  npmPackages:
    @redwoodjs/core: 8.0.0 => 8.0.0
    @redwoodjs/project-config: 8.0.0 => 8.0.0
  redwood.toml:
    [web]
      title = "Redwood App"
      port = 8910
      apiUrl = "/.redwood/functions" # You can customize graphql and dbauth urls individually too: see https://redwoodjs.com/docs/app-configuration-redwood-toml#api-paths
      includeEnvironmentVariables = [
        # Add any ENV vars that should be available to the web side to this array
        # See https://redwoodjs.com/docs/environment-variables#web
      ]
    [api]
      port = 8911
    [browser]
      open = true
    [notifications]
      versionUpdates = ["latest"]
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Hey @craigwduckett 👋 What storybook related dependencies might you have in your package.json? It would also be helpful to know what the contents of your `./redwood/commandCache.json` file is.

**Comment by craigwduckett** [comment]
@Josh-Walker-GM 

Here is my package.json
```
{
  "private": true,
  "workspaces": {
    "packages": [
      "api",
      "web"
    ]
  },
  "devDependencies": {
    "@redwoodjs/core": "8.0.0",
    "@redwoodjs/project-config": "8.0.0"
  },
  "eslintConfig": {
    "extends": "@redwoodjs/eslint-config",
    "root": true
  },
  "engines": {
    "node": "=20.x"
  },
  "prisma": {
    "seed": "yarn rw exec seed"
  },
  "packageManager": "yarn@4.4.0",
  "resolutions": {
    "@storybook/react-dom-shim@npm:7.6.17": "https://verdaccio.tobbe.dev/@storybook/react-dom-shim/-/react-dom-shim-8.0.8.tgz",
    "@apollo/client/rehackt": "0.1.0"
  }
}
```
And commandCache.json file
```
{
  "@redwoodjs/cli-storybook-vite": {
    "storybook": {
      "aliases": [
        "sb"
      ],
      "description": "Launch Storybook: a tool for building UI components and pages in isolation"
    }
  },
  "@redwoodjs/cli-data-migrate": {
    "data-migrate <command>": {
      "aliases": [
        "dataMigrate",
        "dm"
      ],
      "description": "Migrate the data in your database"
    }
  },
  "_builtin": [
    "build",
    "check",
    "diagnostics",
    "console",
    "c",
    "deploy",
    "destroy",
    "d",
    "dev",
    "exec",
    "experimental",
    "exp",
    "generate",
    "g",
    "info",
    "lint",
    "prerender",
    "render",
    "prisma",
    "record",
    "serve",
    "setup",
    "test",
    "ts-to-js",
    "type-check",
    "tsc",
    "tc",
    "upgrade"
  ]
}
```

**Comment by Josh-Walker-GM** [comment]
Hmm all looks great to me. One thing to try is the classic delete the node_modules folder and do `yarn install` again. If that doesn't help it might be useful here to see the output you get on your terminal when you run `yarn rw storybook`

**Comment by craigwduckett** [comment]
Ok cool, that doesnt seemed to have resolved the issue however I am behind a VPN so will try on full access PC later today.

**Comment by rkmitra1** [comment]
RW v8.0 storybook was failing for me too (rw v7.4.4 upgraded to v8.0). Specifically, storybook was starting up but all stories failed.

add Josh's resolutions to my package.json fixed the problem.
```
  "resolutions": {
    "@storybook/react-dom-shim@npm:7.6.17": "https://verdaccio.tobbe.dev/@storybook/react-dom-shim/-/react-dom-shim-8.0.8.tgz",
    "@apollo/client/rehackt": "0.1.0"
  }
```

**Comment by Tobbe** [comment]
@rkmitra1 can you please post the full output of `yarn rw info`? 
Can you also please tell us what version of React you're using? 
And, finally, do you need both of those resolutions? (I'm suspecting you only need the storybook one)

Thanks! 🙏

**Comment by craigwduckett** [comment]
@Josh-Walker-GM @Tobbe This appears to be a me issue as, I can successfully get storybook working on my personal computer. So I will close this issue.

**Comment by rkmitra1** [comment]
yarn rw info

```
  System:
    OS: macOS 14.6.1
    Shell: 5.9 - /usr/local/bin/zsh
  Binaries:
    Node: 20.15.1 - /private/var/folders/ym/rlx3czsd03z0st7q1sdzg09m0000gn/T/xfs-6f70ce75/node
    Yarn: 4.3.1 - /private/var/folders/ym/rlx3czsd03z0st7q1sdzg09m0000gn/T/xfs-6f70ce75/yarn
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 128.0.6613.113
    Edge: 128.0.2739.67
    Safari: 17.6
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 8.0.0 => 8.0.0
    @redwoodjs/core: 8.0.0 => 8.0.0
    @redwoodjs/project-config: 8.0.0 => 8.0.0
  redwood.toml:
    [web]
      title = "Redwood App"
      port = 8910
      apiUrl = "/.redwood/functions" # You can customize graphql and dbauth urls individually too: see https://redwoodjs.com/docs/app-configuration-redwood-toml#api-paths
      includeEnvironmentVariables = [
        # Add any ENV vars that should be available to the web side to this array
        # See https://redwoodjs.com/docs/environment-variables#web
      ]
    [api]
      port = 8911
    [browser]
      open = true
    [notifications]
      versionUpdates = ["latest"]
      ```
      
      React version (via yarn why react)
      ```
      yarn why react
├─ @redwoodjs/auth@npm:8.0.0
│  └─ react@npm:18.3.1 (via npm:18.3.1)
│
├─ @redwoodjs/router@npm:8.0.0 [82169]
│  └─ react@npm:18.3.1 (via npm:18.3.1)
│
├─ @redwoodjs/vite@npm:8.0.0
│  └─ react@npm:18.3.1 (via npm:18.3.1)
│
└─ root-workspace-0b6124@workspace:.
   └─ react@npm:19.0.0-rc-8269d55d-20240802 (via npm:19.0.0-rc-8269d55d-20240802)
   ```
   
   ## package.json resolution
   
   1. You are correct, i do not need     "@apollo/client/rehackt": "0.1.0"
I removed it and storybook works.
2. I do need     "@storybook/react-dom-shim@npm:7.6.17": "https://verdaccio.tobbe.dev/@storybook/react-dom-shim/-/react-dom-shim-8.0.8.tgz",
to make story book work
3. my error without the shim is:
```
import_react_dom.default.unmountComponentAtNode is not a function. (In 'import_react_dom.default.unmountComponentAtNode(el)', 'import_react_dom.default.unmountComponentAtNode' is undefined)
```

**Comment by Josh-Walker-GM** [comment]
Thanks @rkmitra1! 

> │
> └─ root-workspace-0b6124@workspace:.
>  └─ react@npm:19.0.0-rc-8269d55d-20240802 (via npm:19.0.0-rc-8269d55d-20240802)

Is interesting. With standard v8 we'd expect react v18.3.1. We'd likely only expect 19 if you were using the experimental ssr or rsc features - is that the case?

**Comment by rkmitra1** [comment]
re: using React 19

No. Not using ssr or rsc. This is just on an existing app that I upgraded to RW v8.0 for testing.

May be related to this RW app updated to us Prisma 5.19 (for typedSql)

**Comment by Josh-Walker-GM** [comment]
So there's nothing else in your project setting react to v19? Like no other resolutions?

I expect we'll have that updated prisma version out next week as part v8.1.0.
