### ISSUE TITLE
[Bug?]: new navlink activeclassname behavior and materialui

### ISSUE THREAD

**Issue by michalgm** [redwoodjs/redwood#11448]
### What's not working?

the navlink component now overrides the className prop with the activeClassName prop if the link is active - even if no activeClassName is specified. This results in active navLink elements receiving default styling. This is especially problematic for frameworks like material UI that dynamically create css classes based on styling properties (such as `sx`). I had been dynamically creating my navLink styles using `sx` and 
```
const matchInfo = useMatch(to)
const isActive = matchInfo.match
```

Perhaps it would be more intutive/flexible behavior to only override the className prop if an activeclassName is defined?
I think changing line 46 of `packages/router/src/navLink.tsx` to
```
        className={matchInfo.match && activeClassName ? activeClassName : className}
``` 
would do the trick?

### How do we reproduce the bug?

create a NavLink with a className but no activeClassName - it will revert to default text formatting when active.

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Hey @michalgm 👋 

I agree that your experience of having no `activeClassName` so it being replaced with nothing is not what I'd want.

Is you `activeClassName` conditionally undefined or always undefined? Right now our `NavLink` requires the `activeClassName` prop. We'd probably recommend just using a `Link` if there's always just one style applied regardless of whether it's the active route. If your usage is that it's conditionally undefined then we should work through this more!

**Comment by michalgm** [comment]
Ah - you are 100% correct - if I just replace my `NavLink` with `Link`, everything works as expected. Since I am managing all the styling myself (conditionally based on the `useMatch(to)`), NavLink wasn't really gaining me anything anyway. 
Thanks for the tip!

FWIW, I was rendering the NavLink using the Material UI Button component, like so:
```
  return <Button component={Link} to={to} {...rest} {...props} />
```
I'm assuming that (and the fact I am still using JS vs TS) is why I didn't get any complaints about not passing an `activeClassName`

**Comment by Josh-Walker-GM** [comment]
Awesome! I assume implementing things like this hasn't been a limitation of our `NavLink` and is more related to wanting to use some custom logic/libraries?

Yeah my gut reaction would be that a combo of the indirection and just plain JS over TS is probably what reduced any dev time errors/linting here.

Do you feel like we're good with this issue then and can close?

**Comment by michalgm** [comment]
Yeah - ok to close! Thanks!
