### ISSUE TITLE
Add  devtool: "cheap-module-eval-source-map" for easier debugging the source map?

### ISSUE THREAD

**Issue by guledali** [redwoodjs/redwood#1145]
@peterp @cannikin  @thedavidprice  Please add this line below into [webpack.development.js](https://github.com/redwoodjs/redwood/blob/main/packages/core/config/webpack.common.js)

```javascript
 devtool: isEnvProduction ? 'source-map' : 'cheap-module-eval-source-map'
```

It would help with debugging redwood app from the source tab, example screenshots below

**before**
<img width="659" alt="Screenshot 2020-09-12 at 13 49 46" src="https://user-images.githubusercontent.com/20647282/92994925-e8a1a680-f4fe-11ea-9c0e-e16383528577.png">

**after**
<img width="598" alt="Screenshot 2020-09-12 at 13 48 06" src="https://user-images.githubusercontent.com/20647282/92994928-f6efc280-f4fe-11ea-98ad-c3ff999e4ae9.png">

**Comment by peterp** [comment]
Hey @guledali,

We already have this over here: https://github.com/redwoodjs/redwood/blob/main/packages/core/config/webpack.common.js#L154

Are you experiencing a situation where we don't have sourcemaps in Redwood?
