### ISSUE TITLE
[Docs]: 'Redwood community discussion' link after succesful upgrade via CLI command 'yarn rw upgrade' leads to empty results

### ISSUE THREAD

**Issue by jgal1** [redwoodjs/redwood#11463]
### Summary and description

First off, I'm just getting back to working on my project after a month break and I'm super happy to see background jobs as a first class feature in version 8.0.0, thank you!!! I had setup inngest in the past, and after getting welcome emails, and some light background jobs to work via inngest, I really didn't feel like dealing with deploying it via vercel because local dev was a pain, I can't recall the details, but it was enough that I'd really been putting off setting up a proper background queue and testing it in a production ready environment. Long story short I am very excited to try v8.0.0. 

Now back to the issue, it's really a minor nit and (most likely) an easy fix, but when I upgrade redwood the link to the community notes is shows no results, then I navigate to the announcements and find it. I believe the link is getting generated from this line of code https://github.com/redwoodjs/redwood/blob/b04f00cd0f89559eef8ec7b4a8a97352ac3fefed/packages/cli/src/commands/upgrade.js#L153 . So for version 8.0.0 the link that gets generated is https://community.redwoodjs.com/search?q=8.0.0%23announcements , which shows no results for me. Maybe I have some cached filters or something, but I don't think that's the case. Ideally, that'd navigate directly to https://community.redwoodjs.com/t/redwood-v8-0-0-upgrade-guide/7250 which doesn't currently seem to be in a format that could be auto-generated. Even https://community.redwoodjs.com/c/announcements/5 might be a better option as I quickly see the upgrade guides. Without getting to deep into the code, I'm not sure if the url can easily be autogenerated without some standardization of the discussion link, or maybe just fixing the tags on the upgrade post not sure. But in any case a fix adds a tiny bit less friction, I know I used to just close the link and assume there wasn't a discussion. 
![Screenshot 2024-09-06 at 10 15 50 PM](https://github.com/user-attachments/assets/41ff1fb0-de6a-4ef6-96d8-1d38770ce1fa)

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Hey @jgal1 👋 Awesome to hear you're getting back into Redwood! Be sure to give any feedback you have when you start checking out the jobs feature!

We've spoke about this internally but then failed to take any action because we didn't quite know a good replacement. I think the static link you pointed out - https://community.redwoodjs.com/c/announcements/5 - would work well! Do you fancy adding a PR to change that line to point to that link?
