### ISSUE TITLE
Fix Generated Service Test Template

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1148]
The current test generated for a Service does not work.
- error in dmmf.datamodel.models from `core/dist/configs/node/jest.setup.js`

We should also confirm the test itself is a good starter template.

**Comment by thedavidprice** [comment]
@RobertBroersma could use your help here if you have the time!

**Comment by RobertBroersma** [comment]
@thedavidprice I guess the little hack I used has run it's course: https://github.com/redwoodjs/redwood/issues/782

While the issue I linked over there is open I'll try to find another hack. (As soon as I get my local setup working!)
