### ISSUE TITLE
Discussion: Tests generated along with Scaffold

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1149]
@peterp @cannikin @jtoar 

Currently, `yarn rw g scaffold ...` only generates a test for the Service code. What, if any, additional tests should we consider adding:
- is anything else necessary?
- should we consider what's helpful for directionally showing/teaching how to test without adding unnecessary overhead?
- what might be the minimum functionality to be tested, e.g. ModelCells file, Service, Form? 
- at a minimum, some instructions about where to find test docs and perhaps recommendations about what kind of tests to consider

I'm wary of adding too much here. I do think there's a need to have an API test (Service) and Web test (but what?). 

Dom pointed out we do not provide any templates or examples about how to test forms, so this might be a good opportunity.

> Note: this is a priority for the [Testing v1 Roadmap](https://github.com/redwoodjs/redwood/projects/4)

**Comment by cannikin** [comment]
@thedavidprice What'd we decide at the end of the meeting on Tuesday? We talked about adding settings to SKIP generating tests and storybook, but what'd we decide to do here?

**Comment by thedavidprice** [comment]
Per discussion, we're going to leave this as is --> Service file test will be generated only. We are not going to add additional tests for the components.
