### ISSUE TITLE
[Bug]: Double quotes for strings fail auth setup command

### ISSUE THREAD

**Issue by antonmoiseev** [redwoodjs/redwood#11526]
### What's not working?

If I change prettier settings to use double quotes for strings, then `yarn rw setup auth dbAuth` command fails with "Failed to import cookieName" error.

### How do we reproduce the bug?

1. Generate new project with `yarn create redwood-app my-app --ts` command.
2. In prettier.config.js file set `singleQuote: false`.
3. Run `yarn rw lint --fix` in the command line.
4. Commit the changes.
5. Run `yarn rw setup auth dbAuth` and observe the error:
    <img width="460" alt="image" src="https://github.com/user-attachments/assets/139d2ab4-1ab0-447e-949b-818040a327fc">

### What's your environment? (If it applies)

```shell
System:
  OS: macOS 14.5
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.17.0 - /private/var/folders/fn/l_969nyj4bb2j2qcn8qsw2fw0000gn/T/xfs-2b9ea658/node
  Yarn: 4.4.0 - /private/var/folders/fn/l_969nyj4bb2j2qcn8qsw2fw0000gn/T/xfs-2b9ea658/yarn
Databases:
  SQLite: 3.43.2 - /usr/bin/sqlite3
Browsers:
  Safari: 17.5
npmPackages:
  @redwoodjs/auth-dbauth-setup: 8.1.0 => 8.1.0
  @redwoodjs/core: 8.1.0 => 8.1.0
  @redwoodjs/project-config: 8.1.0 => 8.1.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Would you be able to confirm that v8.1.1 fixes this problem for you @antonmoiseev?

**Comment by antonmoiseev** [comment]
Confirmed, thank for you!
