### ISSUE TITLE
[Bug?]: (Jobs) Environment is not correctly set in the Job worker

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#11569]
### What's not working?

Demonstrate that the environment is not correctly set in the job worker.

Knowing that the environment is correctly set the job will let a developer use different storage adapters per environment. For example, in the `development` environment, the job will use the `file` storage adapter, but in the `production` environment, the job will use the `s3` storage adapter.

## Steps to reproduce

See: https://github.com/dthyresson/jobs-environment for an example app

1. Run `yarn dev`
2. Start the jobs by running `yarn jobs work`
2. Open the browser and navigate to `http://localhost:8910/graphql`
3. Run the following query:

```graphql
query TestJobsEnvironment {
  logEnvironment
}
```

Can see that the environment is correctly set in the service to `development` when `yarn rw dev` is running.

```bash
api | 11:51:33 🐛 Processing GraphQL Parameters
api | 11:51:33 🐛 graphql-server GraphQL execution started: TestJobsEnvironment
api | 11:51:33 🌲 The environment in the service
api | 🗒 Custom
api | {
api |   "environment": "development"
api | }
api | 11:51:33 🌲 LogEnvironmentJob [RedwoodJob] Scheduling LogEnvironmentJob
api | 🗒 Custom
api | {
api |   "path": "LogEnvironmentJob/LogEnvironmentJob",
api |   "args": [],
api |   "runAt": "2024-09-15T15:51:33.280Z",
api |   "queue": "default",
api |   "priority": 50
api | }
api | 11:51:33 🐛 graphql-server GraphQL execution completed: TestJobsEnvironment
api | 11:51:33 🐛 Processing GraphQL Parameters done.
```

However, when the jobs are running, the environment is undefined.

```bash
api | 11:52:03 🐛 Processing GraphQL Parameters
11:51:32 🐛 [rw-jobs-worker.*.0] Checking for jobs in all (*) queues...
11:51:32 🌲 [RedwoodJob] Started job 8 (LogEnvironmentJob/LogEnvironmentJob:LogEnvironmentJob)
11:51:32 🌲 LogEnvironmentJob is performing...
11:51:32 🌲 The environment in the service
11:51:32 🚦  LogEnvironmentJob is undefined
11:51:32 🌲 LogEnvironmentJob is done
11:51:32 🐛 [RedwoodJob] Job 8 success
```

However, if you run the jobs with  `NODE_ENV=development yarn rw jobs work` the environment is correctly set to `development`.

```bash
11:53:51 🐛 [rw-jobs-worker.*.0] Checking for jobs in all (*) queues...
11:53:51 🌲 [RedwoodJob] Started job 10 (LogEnvironmentJob/LogEnvironmentJob:LogEnvironmentJob)
11:53:51 🌲 LogEnvironmentJob is performing...
🗒 Custom
{
  "environment": "development"
}
11:53:51 🌲 LogEnvironmentJob is development
11:53:51 🌲 LogEnvironmentJob is done
11:53:51 🐛 [RedwoodJob] Job 10 success
11:53:51 🐛 [rw-jobs-worker.*.0] Checking for jobs in all (*) queues...
```

> Note:
>
> There is checking in the jobs cli commands for the environment to add the logger formatter, but that must > have a different way of getting the environment.

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by cannikin** [comment]
Hmm, the log statement in both the service and the job is `'The environment in the service'` so I'm slight confused which one is showing in the log snippets! To be clear, the job isn't calling the service, you're just logging the ENV in the job itself, looks like.

Jobs will load your `.env` when you `yarn rw jobs work` so if you have `NODE_ENV` defined there, it'll use it. But I don't do any special overriding that says something like if `NODE_ENV` is `undefined`, set it to `development` which is what we tend to do in other places in the framework. But I guess we should be doing that here to have parity with at least the `yarn rw dev` command. I'll get into it on Monday!

**Comment by dthyresson** [comment]
> the log statement in both the service and the job is `'The environment in the service'`

Ah, my bad copy/paste on:

https://github.com/dthyresson/jobs-environment/blob/09a4181cae13d409edfca3c91ad91b01103a8d2e/api/src/jobs/LogEnvironmentJob/LogEnvironmentJob.ts#L9

The job itself reports:

```bash
11:51:32 🌲 [RedwoodJob] Started job 8 (LogEnvironmentJob/LogEnvironmentJob:LogEnvironmentJob)
11:51:32 🌲 LogEnvironmentJob is performing...
11:51:32 🌲 The environment in the service <---- this is really the job
11:51:32 🚦  LogEnvironmentJob is undefined
11:51:32 🌲 LogEnvironmentJob is done
```

After my typo fix with just `yarn rw dev`:

```bash
02:11:19 🐛 [rw-jobs-worker.*.0] Checking for jobs in all (*) queues...
02:11:19 🌲 [RedwoodJob] Started job 11 (LogEnvironmentJob/LogEnvironmentJob:LogEnvironmentJob)
02:11:19 🌲 LogEnvironmentJob is performing...
02:11:19 🌲 The environment in the job
02:11:19 🚦  LogEnvironmentJob is undefined in job
02:11:19 🌲 LogEnvironmentJob is done
02:11:19 🐛 [RedwoodJob] Job 11 success
02:11:19 🐛 [rw-jobs-worker.*.0] Checking for jobs in all (*) queues...
02:11:24 🐛 [rw-jobs-worker.*.0] Checking for jobs in all (*) queues...
```
