### ISSUE TITLE
[Bug?]: WebAuthn depends on specific User model name

### ISSUE THREAD

**Issue by antonmoiseev** [redwoodjs/redwood#11594]
### What's not working?

`DbAuthHandler` allows overriding names for auth and credential fields. However `DbAuthHandler` doesn't respect overridden name for the User model in `webAuthnAuthenticate()` method [here](https://github.com/redwoodjs/redwood/blob/d2fe56cc64f55bb6be1d8108904c541c3366e5a8/packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts#L914). This breaks WebAuthn login flow if User model is renamed.

### How do we reproduce the bug?

1. Generate new Redwood app
2. Setup dbAuth authentication with WebAuthn support.
4. Rename User model and UserCredential models to Account and AccountCredential respectively.
5. Attempt to go through WebAuthn login flow. It fails on the login step with the following error:
    ```json
    {
      "error": "this.dbCredentialAccessor.findFirst(...).user is not a function"
    }
    ```

### What's your environment? (If it applies)

```shell
System:
  OS: macOS 14.5
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.17.0 - /private/var/folders/fn/l_969nyj4bb2j2qcn8qsw2fw0000gn/T/xfs-1224282a/node
  Yarn: 4.4.1 - /private/var/folders/fn/l_969nyj4bb2j2qcn8qsw2fw0000gn/T/xfs-1224282a/yarn
Databases:
  SQLite: 3.43.2 - /usr/bin/sqlite3
Browsers:
  Safari: 17.5
npmPackages:
  @redwoodjs/core: 8.1.1 => 8.1.1
  @redwoodjs/project-config: 8.1.1 => 8.1.1
  @redwoodjs/realtime: 8.1.1 => 8.1.1
  @redwoodjs/studio: 12 => 12.0.0
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by antonmoiseev** [comment]
I had a [related issue](https://github.com/redwoodjs/redwood/issues/8743) before, that one was fixed, but WebAuthn still doesn't work.

**Comment by Josh-Walker-GM** [comment]
Hahah @antonmoiseev Yeah I just read this issue and thought "hmm this sounds familiar"! Do you want to make a PR for this fix? Would be awesome if you had the capacity!

**Comment by antonmoiseev** [comment]
@Josh-Walker-GM here is the [PR](https://github.com/redwoodjs/redwood/pull/11605)
