### ISSUE TITLE
Running `yarn rwt copy ../redwood` on windows won't work

### ISSUE THREAD

**Issue by RobertBroersma** [redwoodjs/redwood#1161]
On command prompt:
```
yarn rwt copy ../redwood`:

'rsync' is not recognized as an internal or external command,
operable program or batch file.
```
Perhaps fixable by using https://github.com/mattijs/node-rsync

On WSL:
```
yarn rwt copy ../redwood

Error: ENOENT: no such file or directory, chmod '/mnt/c/Home/repos/redwood-app/node_modules/.bin/api-server'
```
Which is definitely a lie
```
ls /mnt/c/Home/repos/redwood-app/node_modules/.bin/api-server

/mnt/c/Home/repos/redwood-app/node_modules/.bin/api-server
```

All runs after rimraffing all `node_modules` and running `yarn`

Save me, @peterp !

**Comment by peterp** [comment]
@RobertBroersma Can't you install rsync?

@Tobbe added some documentation over here: https://github.com/redwoodjs/redwood/blob/8838427d668b5762a6defd11358932e68d55a704/CONTRIBUTING.md#L45-L46

**Comment by RobertBroersma** [comment]
I managed to get it to work in WSL, but I have no idea how!

I'm just gonna close this as it seems like a problem with my system then...
