### ISSUE TITLE
[Bug?]: CellSuccessProps no longer has the data type on queryResult

### ISSUE THREAD

**Issue by richard-stafflink** [redwoodjs/redwood#11640]
### What's not working?

When using `CellSuccessProps` the TData type on these fields used to be typed, but now are always `any`:
1. `queryResult.fetchMore.data`
2. `queryResult.previousData`

The TData generic type that was passed in with `CellSuccessProps<TData, ....>` used to be passed down and inherited by `QueryOperationResult`

### How do we reproduce the bug?

1. Create a new RW app: `yarn create redwood-app my-redwood-project --typescript`
2. Add the "Post" example model in `schama.prisma`
3. `yarn rw prisma migrate dev`
4. `yarn redwood generate scaffold post`
5. Add the code below in the `Success` function of `web/src/components/Post/PostCell/PostCell.tsx`
```ts
  if ('variables' in queryResult) {
    const { data } = await queryResult.fetchMore({
      variables: { id: post.id },
    })

    // data is `any` but should be `FindPostById`
    const _data = data

    // previousData is `any` but should be `FindPostById`
    const _previousData = queryResult.previousData
  }
```

### What's your environment? (If it applies)

```shell
N/A
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by richard-stafflink** [comment]
PR to fix this: https://github.com/redwoodjs/redwood/pull/11639

**Comment by Josh-Walker-GM** [comment]
Thankss @richard-stafflink! Awesome you've opened a PR for this too! I'll see if either myself or someone else can take a look as soon as possible.

**Comment by dthyresson** [comment]
https://github.com/redwoodjs/redwood/pull/11639 is merged
