### ISSUE TITLE
[Docs]: cookieName is required on when mimicking dbAuth cookie generation on v7.6.2

### ISSUE THREAD

**Issue by ejsinfuego** [redwoodjs/redwood#11694]
### Summary and description

i'd like to thank you all for your hard work and dedication for making this framework. 

maybe it's nice to have some heads up on the sample code on [Oauth](https://docs.redwoodjs.com/docs/how-to/oauth/#creating-users-and-identities) that a cookie name is required when using dbauth v7.6.2

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by dthyresson** [comment]
> ### Summary and description
> i'd like to thank you all for your hard work and dedication for making this framework.

You're welcome!

> 
> maybe it's nice to have some heads up on the sample code on [Oauth](https://docs.redwoodjs.com/docs/how-to/oauth/#creating-users-and-identities) that a cookie name is required when using dbauth v7.6.2
> 

Could you suggest some wording or a code example for this for us to review to make sure it resolves your issue?

Thanks.

**Comment by ejsinfuego** [comment]
Sure.

![image](https://github.com/user-attachments/assets/6ab86690-9eb7-4758-a31a-b41ae4a7388f)

Maybe we can have that kind of that info component that says "On dbAuth version 7.6.2, cookie name is required. You can check on /api/src/functions/auth.ts"

I tried to use the sample code in the docs as reference to implement my custom OAuth. Cant make it work because I am accustomed to dbAuth v7.0.0 until i noticed the cookie name on v7.6.2 is session_8911 which is different from the sample code on documentation.

**Comment by Muhammad-Owais-Warsi** [comment]
Hi, is anyone working on this ? I would love to solve the issue.

**Comment by dthyresson** [comment]
HI @Muhammad-Owais-Warsi ... could you clarify what you are looking for?

* docs to say that cookieName is required
* how to use or set cookie name when customizing dbAuth?v(did you implement an OAuth solution)
* using dbAuth in general is having an issue
* need n OAuth solution for Redwood or dbAuth

**Comment by Muhammad-Owais-Warsi** [comment]
@dthyresson as per the issue states , that cookieName is required on docs, that's what I am thinking to add. Thanks :)

**Comment by dthyresson** [comment]
> as per the issue states , that cookieName is required on docs, that's what I am thinking to add. 

@Muhammad-Owais-Warsi it helps us to have an example and show where in the docs.

 Would a note/callout of:

 "On dbAuth version 7.6.2, cookie name is required. You can check on /api/src/functions/auth.ts"

here 
<img width="838" alt="image" src="https://github.com/user-attachments/assets/8a298e55-8c34-4a82-bf4d-f207f0b135bb">


Be what you think will help?

Just looking for example where in the docs to include that tip.

**Comment by Muhammad-Owais-Warsi** [comment]
Right, maybe  I have misunderstood something. Sorry for the inconvenience. Thanks

**Comment by ejsinfuego** [comment]
hello, i hope this will help


```
import { cookieName } from '@redwoodjs/auth-dbauth-api'

//on dbAuth v7.6.2, cookie name is required

const secureCookie = (user) => {
  const expires = new Date()
  expires.setFullYear(expires.getFullYear() + 1)

 //... the rest of the code

  const cookieAttrs = [
    `Expires=${expires.toUTCString()}`,
    'HttpOnly=true',
    'Path=/',
    'SameSite=Strict',
    `Secure=${process.env.NODE_ENV !== 'development'}`,
  ]
  const data = JSON.stringify({ id: user.id })

  const encrypted = CryptoJS.AES.encrypt(
    data,
    process.env.SESSION_SECRET
  ).toString()
  return [`${cookieName}=${encrypted}`, ...cookieAttrs].join('; ')
}
```

**Comment by dthyresson** [comment]
Thanks @ejsinfuego . Could you make a PR with this how to docs change and reference this issue? That way the change and update can get reviewed and merged.

**Comment by ejsinfuego** [comment]
Sure. I will. Thank you so much!
