### ISSUE TITLE
create-redwood-app includes private Verdaccio registry causing installation failure

### ISSUE THREAD

**Issue by mrkimani-ndegwa** [redwoodjs/redwood#11706]
### What's not working?

When creating a new Redwood project with `npx create-redwood-app`, the generated package.json includes a private Verdaccio registry that causes installation to fail for new users.

## Current Behavior
The generated package.json includes a private registry reference:
```
json
"resolutions": {
    "@storybook/react-dom-shim@npm:7.6.17": "https://verdaccio.tobbe.dev/@storybook/react-dom-shim/-/react-dom-shim-8.0.8.tgz"
}
```

This causes yarn install to fail with:
> error Couldn't find package "//verdaccio.tobbe.dev/" on the "npm" registry.

### How do we reproduce the bug?

- Run npx create-redwood-app@latest my-app
- Navigate to project directory: cd my-app
- Run yarn install
- Observe the Verdaccio registry error

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by carsonwlee** [comment]
I'm having this issue also

**Comment by dthyresson** [comment]
> ### What's not working?
> When creating a new Redwood project with `npx create-redwood-app`, the generated package.json includes a private Verdaccio registry that causes installation to fail for new users.
> 
> ## Current Behavior
> The generated package.json includes a private registry reference:
> 
> ```
> json
> "resolutions": {
>     "@storybook/react-dom-shim@npm:7.6.17": "https://verdaccio.tobbe.dev/@storybook/react-dom-shim/-/react-dom-shim-8.0.8.tgz"
> }
> ```
> 
> This causes yarn install to fail with:
> 
> > error Couldn't find package "//verdaccio.tobbe.dev/" on the "npm" registry.
> 
> ### How do we reproduce the bug?
> * Run npx create-redwood-app@latest my-app
> * Navigate to project directory: cd my-app
> * Run yarn install
> * Observe the Verdaccio registry error
> 

@Tobbe as this message references one of your packages do you have any ideas how to resolve?

**Comment by andychongyz** [comment]
Prefix the `yarn` command with `corepack` works for me. Instead of running `yarn install`, run `corepack yarn install`

**Comment by iamwinner422** [comment]
> From #10899, prefixing the `yarn` command with `corepack` works for me. Instead of running `yarn install`, run `corepack yarn install`

That really works! Thanks 🎉

**Comment by Tobbe** [comment]
Yeah, the issue here isn't the registry link. The issue is that yarn isn't installed properly. Yarn needs to be installed/enabled by corepack. If you have a globally installed yarn version already, please uninstall that first.

We have a page for yarn in our documentation https://docs.redwoodjs.com/docs/how-to/using-yarn
