### ISSUE TITLE
[Bug?]: Server is killed and doesn't come back up when saving changes

### ISSUE THREAD

**Issue by o0charlie0o** [redwoodjs/redwood#11719]
### What's not working?

When the server restarts after making a code change it is killed and doesn't come back up. After some investigation it appears to have been introduced with this pr: https://github.com/redwoodjs/redwood/pull/11691

Essentially if the first promise wins then it resolves and `await this.startApiServer()` is called. The problem here is the second promise still executes so after 2 seconds it still kills the server anyways.

Running the following code in chrome dev tools console will demonstrate the issue:

```javascript
const promise1 = new Promise((resolve) => {
  setTimeout(() => {
    console.log('Promise 1 resolved');
    resolve('First');
  }, 100);
});

const promise2 = new Promise((resolve) => {
  setTimeout(() => {
    console.log('Promise 2 resolved');
    resolve('Second');
  }, 200);
});

Promise.race([promise1, promise2]).then((value) => {
  console.log('Race settled with:', value);
});
```

Output is:
Promise 1 resolved
Race settled with: First
Promise 2 resolved

### How do we reproduce the bug?

Make a change in some code on the api side and save so the server restarts

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by s98berg** [comment]
After upgrading to 8.4.1 the same thing happens in my project that if I edit in the api the server shuts down and doesn't start again. I use vscode on mac. Really glad I found the bug report here, because I've spent hours debugging.

**Comment by cadlagtrader** [comment]
Same thing happening to me on 8.4.1 without editing any file. 



It seems ```yarn rw dev api``` touch trustedDocumentSotore when starting and 8.4.1 fails to restart it
> [change] /src/lib/trustedDocumentsStore.ts

**Comment by Lijwent** [comment]
I have almost the same problem, the API comes back up but is still killed
`api | 01:16:28 🌲 request completed 88ms`
`api | Building...`
`api | Took 747 ms`
`api | Shutting down API server.`
`api | 01:16:29 🌲 Starting a postgresql pool with 1 connections. 
``api | Debugger attached.`
`01:16:30 | 🌲 My custom log`
 `api | API server did not exit within 2 seconds, forcefully closing it.`

**Comment by Philzen** [comment]
Oh yeah, i'm also seeing this after the upgrade to 8.4.1:

```shell
gen | File system change: change api/src/services/interviewPostprocessing/interviewPostprocessing.ts
gen | Modified Directory named module: api/src/services/interviewPostprocessing/interviewPostprocessing.ts 1 ms
api | Shutting down API server.
api | Took 2003 ms
api | Debugger listening on ws://127.0.0.1:18911/c114f28b-8f88-4c9d-a207-e4cd67a3ed2d
api | For help, see: https://nodejs.org/en/docs/inspector
api | 
api | 12:06:36 🌲 Configuring api side
api | Importing Server Functions... 
api | /auth 1268 ms
api | /livekit 1265 ms
api | ...Done importing in 1269 ms
api | API server did not exit within 2 seconds, forcefully closing it.
web | 12:07:02 PM [vite] http proxy error: /auth?method=getToken
web | Error: connect ECONNREFUSED :::8911
web |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
```

But this doesn't happen deterministically, so it makes sense that this must be down to some sort of race condition (#11731 :rocket: )

**Comment by Tobbe** [comment]
Yeah, this has been bugging me too. Thanks for the nudge here @Philzen 🙏

**Comment by lintfail** [comment]
Could we please have a patch release with this fix? Thanks in advance @Tobbe
