### ISSUE TITLE
[Bug?]: Headers in Subscription

### ISSUE THREAD

**Issue by dennemark** [redwoodjs/redwood#11732]
### What's not working?

Hi,
I am using custom headers in my graph ql client config.
```ts
  httpLinkConfig: {
    credentials: 'include',
    headers: {
      'slug': getSlug(),
    },
  },
```
they reach the backend of graphql when setting context. However not within a subscription. I can see it in my network tab, that the event stream is missing the slug header.
Looking at SSELink, the header infos are not forwarded properly here and in the authorization line below.
https://github.com/redwoodjs/redwood/blob/05dca60f4d6711fd48f06b3d06fa1f02e839b42c/packages/web/src/apollo/sseLink.ts#L108

### How do we reproduce the bug?

Use the countdown redwood example, add httpLinkConfig as shown above. Check network tab, if headers of subscription are included.

### What's your environment? (If it applies)

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 20.11.0 
    Yarn: 4.4.0 
  npmPackages:
    @redwoodjs/auth-custom-setup: 8.4.0 => 8.4.0 
    @redwoodjs/auth-dbauth-setup: 8.4.0 => 8.4.0 
    @redwoodjs/cli-data-migrate: 8.4.0 => 8.4.0 
    @redwoodjs/core: 8.4.0 => 8.4.0 
    @redwoodjs/realtime: 8.4.0 => 8.4.0 
    @redwoodjs/studio: 11.4.0 => 11.4.0
```

### Are you interested in working on this?

I tried a patched version and it seems to work. I could contribute the necessary changes. See the commented spots

```ts
 const { credentials, referrer, referrerPolicy, ...rest } = httpLinkConfig?.headers || {}; // here ...rest

    this.client = createClient({
      url,
      headers: async () => {
        const token = await auth.tokenFn();
        if (!token) {
          return { ...headers, ...rest };  // here ...rest
        }
        return {
          Authorization: `Bearer ${token}`,
          "auth-provider": auth.authProviderType,
          ...headers,
          ...rest // here ...rest
        };
      },
```

- [x] I'm interested in working on this

**Comment by Tobbe** [comment]
> I could contribute the necessary changes.

Yes please 🙏  That'd be awesome! 🎉
