### ISSUE TITLE
Fix webpack merge not a function error 

### ISSUE THREAD

**Issue by sebastiaandekker** [redwoodjs/redwood#1174]
**Issue:** When trying to add configuration to webpack according to the 2nd format inside the [docs](https://redwoodjs.com/docs/webpack-configuration#configuring-webpack), i get the error 'merge is not a function'.

**Fix:** @core/config/webpack.common.js change `const merge = require('webpack-merge')` to `const { merge } = require('webpack-merge')`.

The other webpack config files already do this.

**Comment by peterp** [comment]
Hey @sebastiaandekker, thanks for opening this issue! It seems like we got some of them, but not all of them, the last one is over here: https://github.com/redwoodjs/redwood/blob/1266692489cb9f248f7c027b165bd8a59ab0a3b3/packages/core/config/webpack.common.js#L12

**Comment by peterp** [comment]
Closed by #1188
