### ISSUE TITLE
Something went wrong in a new app deployed to Netlify

### ISSUE THREAD

**Issue by pepibumur** [redwoodjs/redwood#1182]
👋 Hi!
First of all, thanks for the amazing work on the framework and the documentation. It's very easy to get started and learn about all the RedwoodJS ideas.

I followed the tutorial and deployed my app to Netlify. Everything works fine locally, however, when I tried to access the app deployed on Netlify I get a "something went wrong" error. I've searched in the community forum and on the issues on this repository and I found one issue from a long time ago that was related to issues with Firefox. I believe it's not the same issue here.

The browser console shows the following error:

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/663605/93669941-ab598d80-fa97-11ea-9cdb-a4674c6b0d75.png">

Any idea what might be causing that issue?

**Comment by dthyresson** [comment]
@pepibumur Is there any chance you can share your code repo? Does the same issue occur in local dev using Firefox?

**Comment by pepibumur** [comment]
Hey @dthyresson, the web app is at https://app.tuistpro.io, and it works locally with any browser. It's a private repository but I gave you access to [it](https://github.com/tuist-pro/app). Let me know if that helps to debug the issue.

**Comment by dthyresson** [comment]
@pepibumur I can launch the site in dev ... and see the dev "splash" page ... but you have no Routes or pages defined.

Recently, [this commit](https://github.com/redwoodjs/redwood/commit/1def1c19d180b4c0f12da239696b10dc27d0d412)

https://github.com/redwoodjs/redwood/commit/1def1c19d180b4c0f12da239696b10dc27d0d412

removed the splash page from production.

Perhaps that's causing it?

If you add a basic "home" page route, does this issue still happen?

Also, I cannot see your env setting on Netlify -- I am assuming you have set the DATABASE_URL to a publicly available Postgres database url/connection string.

**Comment by pepibumur** [comment]
🤦 That was the issue:
<img width="196" alt="image" src="https://user-images.githubusercontent.com/663605/93793915-bb0fd800-fc37-11ea-83a9-98131c292fce.png">

I wrongly assumed that I'd get the same screen after deploying to Netlify. Thanks for your help @dthyresson.

**Comment by peterp** [comment]
Hey @pepibumur 👋 

Let's keep this open, and change the original screen to say something along the lines of: "Hey! You'll only see it during development and will be removed from production!"

**Comment by peterp** [comment]
I would also have assumed that you should've seen a 404 not found page.
