### ISSUE TITLE
Functions require the apiProxyPath in local development

### ISSUE THREAD

**Issue by pepibumur** [redwoodjs/redwood#1183]
## Context
I followed the tutorial to create a new function. Right after creating the function, `test-function`, I went to the browser and tried to open the URL http://localhost:8910/test-function. To my surprise, the response from the function is not returned.

After reading the documentation further, I stumbled upon the `apiProxyPath` configuration, so I tried to open the following URL http://localhost:8910/.netlify/functions/test-function, and that worked.

## What
If that's the expected behavior, I think it's a bid odd as a user that I have to prefix my funcitons with a path that depends on the deployment platform. [This cookbook](https://redwoodjs.com/cookbook/custom-function) first says that we should open the URL with the prefix, but further down it shows an example where the prefix is not necessary:

![image](https://user-images.githubusercontent.com/663605/93670721-c0d1b600-fa9d-11ea-9953-1527810c6363.png)

Do I need to configure something to be able to open the functions without using the path prefix? Or is it possible that there's  a bug in the webpack configuration that makes the development environment to behave as in production?

**Comment by dthyresson** [comment]
> I went to the browser and tried to open the URL http://localhost:8910/test-function. 

Hi @pepibumur can you try port 8911 instead of 8910?

That is:

`http://localhost:8911/test-function` (as the screenshot shows)

instead of 

`http://localhost:8910/test-function`

and see if that works?

**Comment by pepibumur** [comment]
Hey @dthyresson 👋 
Your suggestion worked, thanks a lot! I wonder if the documentation should state the port differences more clearly?
