### ISSUE TITLE
`yarn rw info` broken at least in MacOS

### ISSUE THREAD

**Issue by AntonioMeireles** [redwoodjs/redwood#1204]
Hi all, 

just to report that ...

```yarn rw info
yarn run v1.22.5
$ /.../redwoodTest/node_modules/.bin/rw info
Error: Cannot access environment info
TypeError: (e || []).filter is not a function
    at/.../redwoodTest/node_modules/envinfo/dist/envinfo.js:1:73314
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 5)
    at async Object.handler (/.../redwoodTest/node_modules/@redwoodjs/cli/dist/commands/info.js:32:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
context: MacOS 10.15.6 (19G2021), Homebrew's zsh, rw v0.19.1 (was same in .0) 

Thanks in advance and keep the **great** work!

António

**Comment by forresthayes** [comment]
confirming the bug:

macOS 10.15.6
node 12.18.2

> ❯ yarn rw info
yarn run v1.22.5
$ /.../redwood-site/node_modules/.bin/rw info
Error: Cannot access environment info
TypeError: (e || []).filter is not a function
    at /.../redwood-site/node_modules/envinfo/dist/envinfo.js:1:73314
    at async Promise.all (index 5)
    at async Object.handler (/.../redwood-site/node_modules/@redwoodjs/cli/dist/commands/info.js:32:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

also, (note: the following was resolved when, per @thedavidprice's suggestion, I ran `yarn add -W envinfo`)

> ❯ yarn envinfo
yarn run v1.22.5
$ /.../redwood-site/node_modules/.bin/envinfo
(node:28426) UnhandledPromiseRejectionWarning: TypeError: (e || []).filter is not a function
    at /.../redwood-site/node_modules/envinfo/dist/envinfo.js:1:73314
    at async Promise.all (index 72)
(node:28426) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28426) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by thedavidprice** [comment]
@forresthayes Just want to make sure I understand correctly.

1. You ran `yarn add -W envinfo` (which installed the lasted version of envinfo in your project)
2. _And_ then you were able to run `yarn rw info` successfully?

**Comment by forresthayes** [comment]
Sorry, no, I meant that the second error, from running `yarn envinfo`, was resolved after I ran `yarn add -W envinfo`. However, the original problem with `yarn rw info` persists for me.

**Comment by thedavidprice** [comment]
@forresthayes @AntonioMeireles I've merged the PR updated envinfo. Could either of you take the latest canary `0.19.2-canary.3` for a spin in your local project and report back if it resolved the issue?
- `yarn rw upgrade -t canary`
- `yarn envinfo --version` --> confirm this is v7.7.3
- `yarn rw info` --> 🤞

**Comment by forresthayes** [comment]
I upgraded to the canary version:
`yarn envinfo --version`--> 7.7.2 (?)
but `yarn rw info` worked correctly 😀

**Comment by thedavidprice** [comment]
7.7.2? Well, that's strange indeed. 🤔

But I'll take it! A fix is a fix.

Thanks again for the help, you two.

**Comment by AntonioMeireles** [comment]
(sorry lag - was sleeping - as in Europe :-) ) . yes, i can confirm too that the fix works. **THANKS**!
