### ISSUE TITLE
Scaffold generator does not create API files correctly: Cannot save a Post

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#124]
Going through tutorial near line#414. Clicking “Save” on `/posts/new` throws several errors:

```
bundle.esm.js:69      POST http://localhost:8910/.netlify/functions/graphql 400 (Bad Request)
backend.js:6      [GraphQL error]: Message: Unknown type "PostInput"., Location: [object Object], Path: undefined
backend.js:6     [Network error]: ServerError: Response not successful: Received status code 400

bundle.esm.js:63     Uncaught (in promise) Error: Network error: Response not successful: Received status code 400
    at new ApolloError (bundle.esm.js:63)
    at Object.error (bundle.esm.js:1030)
    at notifySubscription (Observable.js:140)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.error (Observable.js:240)
    at bundle.esm.js:869
    at Set.forEach (<anonymous>)
    at Object.error (bundle.esm.js:869)
    at notifySubscription (Observable.js:140)
    at onNotify (Observable.js:179)
```

**Comment by thedavidprice** [comment]
Here’s a screenshot of output from running `yarn rw g scaffold post`:
<img width="584" alt="Screen Shot 2020-02-17 at 11 53 24 PM" src="https://user-images.githubusercontent.com/2951/74715163-d073de00-51e0-11ea-9e71-4aacfd9db386.png">

Confirming Pages, Routes, Cells, and Components were created. The following were **not created:**
- `api/src/graphql/posts.sdl.js`
- `api/src/services/posts.js`

**Confirming working correctly** after manually copying the two files from https://github.com/cannikin/redwoodblog

==> Error is caused by misfire in scafold generators.

**Comment by peterp** [comment]
This is a bug I introduced, I'll fix it.
