### ISSUE TITLE
`Cell` appears to be showing `Loading` state after a mutation has run

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#1240]
After a mutation the Loading state is shown again, even though the cache is updated optimistically.

**Comment by qooqu** [comment]
Removing fetchPolicy in withCell.js (defaults to cache-first) seems to fix it. Might cause other problems though.

Adding a beforeQuery hook in the cell is an effective workaround.

**Comment by thedavidprice** [comment]
GAH! @qooqu that page flash is terrible. Thanks for taking the time to create that example.

This should be resolved by #1250 

You can test the latest code using the canary release `0.19.2-canary.36`. Via command line use `yarn rw upgrade -t canary` to upgrade to the latest canary release. (Note: canaries should be considered unstable)

**Comment by qooqu** [comment]
Just tested `0.19.2-canary.36`. No flashing. Thanks!
