### ISSUE TITLE
Support Supabase Third Party Login

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#1246]
Supabase [released support](https://supabase.io/docs/library/user-management/#third-party-logins
) for third party login (similar to those providers offered by Netlify Identity).

https://supabase.io/docs/library/user-management/#third-party-logins

```
Third Party Logins
We currently support the following OAuth providers:

Google
Github
Gitlab
Bitbucket
```

One interesting aspect to this is that after authenticating, 

> The user will now appear in your database in the auth.users table

The Redwood [Playground Auth](https://github.com/redwoodjs/playground-auth) has an example of Supabase login and signup.

Activating these providers requires secret keys:

```
You can enable providers by navigating to Authentication > Settings > External OAuth Providers and inputting your Client ID and Secret for each.

To fetch these you need to:

* Generate Client ID and Secret (google, github, gitlab, bitbucket)
* Enter Authorized Redirect URI: http://<your-project>.supabase.co/auth/v1/callback on provider dashboard
```

To implement, one may be able to follow the similar example found in the Auth0 client's `restoreAuthState` method that can handle the callback and process 

```
After authenticating you should be redirected to <your-site-url>/?access_token=xyzabc&expires_in=3600&refresh_token=abcdef&token_type=bearer. This base url can be updated on the Supabase dashboard at Authorization > Settings.
```

and then store the access and refresh tokens via [saveSession](https://github.com/supabase/supabase-js/blob/master/src/Auth.js#L122) as

```
supabase.auth.saveSession(
  access_token, // from callback URL
  refresh_token, // from callback URL
  Math.round(Date.now() / 1000) + expires_in, // current time + seconds from callback URL
  null // currentUser not present yet
)
```

**Comment by FractalHQ** [comment]
My "SITE URL" is set to `http://localhost:5555/admin/`.  However, after signing up, I am redirected to `https://localhost:5555/`, instead of `http://localhost:5555/admin/`.  This is causing some issues.  Am I missing something?

**Comment by thedavidprice** [comment]
Hi @FractalHQ! Thanks for checking in, but do know this probably isn't the best place to get the most help. I recommend starting a new post on the Redwood Forums: https://community.redwoodjs.com Be sure to include info about which Auth provider you’re using (Supabase, yes?) and how you've attempted to set up. You can loop me in `@thedavid` and I'll make sure you get some help. 

Also, you can try our Chat on Discord. It's good for quick help but for more technical items things can get lost in the shuffle: https://discord.gg/redwoodjs

Lastly, if you haven't already please do check out the [Redwood Auth Documentation about Supabase](https://redwoodjs.com/docs/authentication#supabase).

**Comment by dthyresson** [comment]
Hi @FractalHQ I was just this morning informed of this Supabase and GoTrue issue

https://github.com/supabase/supabase/issues/640

I think that’s what you are seeing and Supabase is fixing it presently. You can track that issue for progress and then can update the Supabase client accordingly.

I think you’ll be able to set a redirect or callback url.

**Comment by FractalHQ** [comment]
@dthyresson Thanks so much!!  @thedavidprice Ah yes sorry- this wasn't the best place.  Thanks for the prompt help!!
