### ISSUE TITLE
‘yarn rw g’ generated names are singular when input is plural

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#125]
See line#536 of Tutorial where we create first cell with `yarn rw g cell blog_posts`. Note that input is plural but output is singular in `/BlogPostCell/BlogPostCell.js`:
```
$ yarn rw g cell blog_posts
yarn run v1.22.0
$ /Users/price/Repos/redwoodblog/node_modules/.bin/rw g cell blog_posts
  ✔ Generating cell files...
    ✔ Writing `./web/src/components/BlogPostCell/BlogPostCell.js`...
✨  Done in 1.12s.
```

**Comment by thedavidprice** [comment]
Note: when I later ran `yarn rw g cell blog_posts`, the generator gracefully failed without messing with existing files. The “red x” was nice but too subtle. Would be helpful to have a more explict message such as “Humbly refusing to overrite existing files. Did you enter the correct component type and an unused name?"

**Comment by cannikin** [comment]
So some generated files should be either singular or plural on purpose, overriding what the user input. 

* SDL and service files are always plural
* Scaffolds automatically generate singular or plural for several different files

I'm trying to remember if there was any reason for cells, components, layouts and pages to override what the user input...I don't think so? I may have just copied and pasted that filename output code from another generator. 😬

**Comment by thedavidprice** [comment]
Understood! But to be clear, though, at this part of the Tutorial I've already created:
`/BlogPostCell/BlogPostCell.js`

So when I then try to run `yarn rw g cell blog_posts`, it is **failing** because it's trying to recreate `/BlogPostCell/BlogPostCell.js` instead of `/BlogPostCell/BlogPostsCell.js`. Does that make sense?

See: https://github.com/redwoodjs/tutorial/pull/19 roughly line#534 of `README-comments.md`

Also including @peterp because now seems like it's potentially an issue with generator conversation.

**Comment by cannikin** [comment]
Ahh interesting. Yeah now I don't remember if mine did it correctly (kept whatever pluralization you used at the command line) and the refactor busted it, or if it was always like that.

**Comment by thedavidprice** [comment]
@cannikin @peterp Any progress on this one?
