### ISSUE TITLE
Add error diagnostic when Private.unauthenticated is pointing to a non-existent named route

### ISSUE THREAD

**Issue by aldonline** [redwoodjs/redwood#1257]
Expected:

* <Private unauthenticated="idontexist"/> should result in an error ("named route 'idontexist' not found")

Actual:

* As of rw 0.19.1, this error is not caught

<img width="492" alt="Screen Shot 2020-10-02 at 9 42 20 AM" src="https://user-images.githubusercontent.com/154884/94948343-03c75c80-0494-11eb-8169-d4d75ee5c68b.png">

**Comment by aldonline** [comment]
@thedavidprice I think this one should be tagged "project-structure". The code to fix this is in "@redwoodjs/structure".
But from a user's point of view, this is experienced as a VSCode issue.

**Comment by jtoar** [comment]
See https://github.com/redwoodjs/redwood/issues/3887#issuecomment-1118642662.
