### ISSUE TITLE
VS Code Extension: change `Redwood.js` to `Redwood`

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1259]
The VS Code Extension currently uses "Redwood.js" in the name and throughout the extension. All occurrences should be changed to "Redwood" (so drop the .js).

Note: I did a quick search-namespace check. Although there is such a thing as "Redwood IDE", it's low traffic and won't get in the way of VS Code Marketplace or Google Search.

cc @aldonline

**Comment by aldonline** [comment]
I fixed several occurrences in v0.0.8. Let's leave this open. If anyone finds an occurrence, please add a comment and a screenshot/link

**Comment by aldonline** [comment]
I think I got'em all. Closing this issue. Re-open if you see one popping up :)
