### ISSUE TITLE
Dependabot's Bump dotenv-webpack from 2.0.0 to 3.0.0 causing issues with Auth0 SPA client

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#1262]
From Discord:

> António MeirelesToday at 5:22 AM
humm. at sight auth(0) looks busted in latest canary revs. getting Uncaught SyntaxError: Unexpected token ':' and a white screen of death. (steps to repro -  yarn create redwood-app  foo; (cd foo; yarn rw g auth auth0; yarn rw upgrade -t canary;) any clues / known issue 

I was able to verify this issue (with auth0-spa and not just any auth provider) and console error points to:

`app.chunk.js:xxxxx Uncaught SyntaxError: Unexpected token ':'`

```js
    function installNextTickImplementation() {
        registerImmediate = function(handle) {
            {"env": {}}.nextTick(function () { runIfPresent(handle); });
        };
    }
```

possibly something to do with `env`.

The same error was referenced in a FontAwesome issue with 

https://github.com/FortAwesome/react-fontawesome/issues/385

> I had the same issue. It was caused by dotenv-webpack version 3.0.0. Downgrading it to 2.0.0 resolved the issue.

And need to see if the same upgrade to webpack 3 is causing this problem.

Should try to downgrade webpack back to v2 in core and see if cannot prevent dependabot's upgrading it.

https://github.com/redwoodjs/redwood/commit/38c9710d09e886bcd561acce03ba7635194270eb#diff-f4f412caa68d8fde92b3d6bd3c2b3be1

I had a look to see why dependabot bumped from 2.0.0 to 3.0.0 even though the version used a caret

`"dotenv-webpack": "^2.0.0",`

which *should* keep the version between under 3.

https://classic.yarnpkg.com/en/docs/dependency-versions#toc-caret-ranges

>-= 2.0.0 < 3.0.0

But apparently the default config for apps is for dependabot is to *increase versions*:

> By default, version requirements are increased if it's an app and the range widened if it's a library (widen_ranges is used for javascript ,python, php:composer, go:dep and increase_versions_if_necessary is used for ruby:bundler and rust:cargo).

https://dependabot.com/docs/config-file/#version_requirement_updates

So:

Question for @thedavidprice or @peterp:

1. `@redwoodjs/core` being treated as an app, not a module?
2. if so then this issue might go away
3. for now to resolve, will manually set the version range such that it won't be bumped to 3

```
"dotenv-webpack@>=2.0.0 <3.0.0":
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/dotenv-webpack/-/dotenv-webpack-2.0.0.tgz#064ae42dbb214778d8aff0c76dc97253594f9ec3"
  integrity sha512-Omo5IpVl7XRgWXeZjxdfqOBEApJPxGLMOIx3F/w/W7ppUKgYMOXrk4eczlQrErPD4X0YRESlyGJek3O4uobRnw==
  dependencies:
    dotenv-defaults "^2.0.0"
```

**Comment by AntonioMeireles** [comment]
core issue upstream is [here](https://github.com/mrsteele/dotenv-webpack/issues/240). and yes downgrading for now is the way to go (as done [elsewhere](https://github.com/mozilla-extensions/normandy-devtools/pull/455)) imho. 

THNKS!

**Comment by dthyresson** [comment]
I had a look to see why dependabot bumped from 2.0.0 to 3.0.0 even though the version used a caret

`"dotenv-webpack": "^2.0.0",`

which *should* keep the version between under 3.

https://classic.yarnpkg.com/en/docs/dependency-versions#toc-caret-ranges

>-= 2.0.0 < 3.0.0

But apparently the default config for apps is for dependabot is to *increase versions*:

> By default, version requirements are increased if it's an app and the range widened if it's a library (widen_ranges is used for javascript ,python, php:composer, go:dep and increase_versions_if_necessary is used for ruby:bundler and rust:cargo).

https://dependabot.com/docs/config-file/#version_requirement_updates

So:

Question for @thedavidprice or @peterp:

1. `@redwoodjs/core` being treated as an app, not a module?
2. if so then this issue might go away
3. for now to resolve, will manually set the version range such that it won't be bumped to 3

```
"dotenv-webpack@>=2.0.0 <3.0.0":
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/dotenv-webpack/-/dotenv-webpack-2.0.0.tgz#064ae42dbb214778d8aff0c76dc97253594f9ec3"
  integrity sha512-Omo5IpVl7XRgWXeZjxdfqOBEApJPxGLMOIx3F/w/W7ppUKgYMOXrk4eczlQrErPD4X0YRESlyGJek3O4uobRnw==
  dependencies:
    dotenv-defaults "^2.0.0"
```

**Comment by dthyresson** [comment]
Note:
storybook/core@5.3.19 uses `dotenv-webpack "^1.7.0"`

but downgraded and seems to resolve issue.

**Comment by thedavidprice** [comment]
Thanks, all! 

**re: Dependabot** --> Those PRs are opened automatically, but we are merging them manually after some (limited) inspection and confirming tests and/or QA (if applicable) look good. Both Peter and I have had a mixed experience so far.

I believe Peter is using the "Auth-Playground" for QA before we do any releases. I think a better way forward in general would be to add automation that triggers CI on Auth-Playground using the latest canary. But that's for another day.
