### ISSUE TITLE
Enchancing Readme.md with table of content.

### ISSUE THREAD

**Issue by simarpreetsingh-019** [redwoodjs/redwood#1265]
I have a suggestion of Enhancing Readme.md by adding a table of content to main readme.md also just like we have in contributors.md , will enhance the readability of readme also.

I would like to work on this issue.

**Comment by thedavidprice** [comment]
Hi @simarpreetsingh-019 Thanks for offering to help!

This repo's README.md is used on our website here: https://redwoodjs.com/docs/introduction And you can see below the right sidebar is a TOC. 
<img width="1242" alt="Screen Shot 2020-10-03 at 12 31 46 PM" src="https://user-images.githubusercontent.com/2951/95000384-20879100-0575-11eb-819a-c7e5af23a38c.png">

## Other Ways to Get Started as a Contributor
So let's pass on this suggestion. However, we ❤️ that you'd like to help as a contributor and want to help! If you'd like to start with documentation, take a look at the list of Issues in our Website repo:
- https://github.com/redwoodjs/redwoodjs.com/issues

And a couple other places to get started might be with Issues we've labeled here:
- https://redwoodjs.com/good-first-issue
and here:
- https://github.com/redwoodjs/redwood/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest

Lastly, please don't hesitate to ask the community for help getting started:
- https://community.redwoodjs.com
- https://discord.gg/redwoodjs
