### ISSUE TITLE
Force migration of database schema during prototyping

### ISSUE THREAD

**Issue by jeliasson** [redwoodjs/redwood#1281]
This issue is the ability to force a database migration during early prototyping of a RedwoodJS project without have to worry about schema conflicts etc.

## Related
Prisma has released a public prototype doc (thanks @alberto-prisma)
[Public Prototype Docs - Iterating on your database schema during prototyping](https://www.notion.so/Public-Prototype-Docs-Iterating-on-your-database-schema-during-prototyping-d2e4a0271f0643dda1c4929111f05522)

### Meanwhile
While we're waiting for an awesome `prisma` stable build, and implemented nicely in Redwood, I've [created a hacky bash script](https://github.com/jeliasson/redwoodjs-db-reset/blob/master/scripts/db-reset.sh) to do some of the heavy lifting, primary for Postgres. Feel free to try out it out and/or send improvements in a PR.

Ping @dthyresson @thedavidprice @alberto-prisma in the `#quick-help` discussion on Discord. Thanks! ❤

**Comment by thedavidprice** [comment]
I really like the idea of being able to do a reset, aka `yarn rw db --do-over`.

In this case, where we're not worried about data, I wonder how possible it would be to have a generic SQL flow to drop any type of database and then run the migrations. 🤔

**Comment by dthyresson** [comment]
@jeliasson Has the new [Prisma migrate flow](https://www.prisma.io/docs/guides/application-lifecycle/developing-with-prisma-migrate) addressed the prototyping issues?

For example, the wanted [db push](https://www.prisma.io/docs/guides/application-lifecycle/prototyping-schema-db-push/) 
 to help specifically with "Schema prototyping with db push"?

If so, then we can close out this issue.

**Comment by jeliasson** [comment]
@dthyresson Definitely. 🙏🏻
