### ISSUE TITLE
Canary release publishing is not setting correct canary version on @redwoodjs dependencies

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1286]
Canary releases are successfully being published for all packages. However, some `@redwoodjs` packages are _not_ being installed at the canary release version. Instead, they are at the current stable release `0.19.2`.

### Reproducing the Issue
- run `yarn rw upgrade -t canary` in a Redwood project
- inspecting `package.json` in each of the main installed packages (e.g. `node_modules/@redwoodjs` for `core`, `api`, `auth`, `forms`, `router`,  and `web`) shows the correct canary version for the package as well as for each `@redwoodjs` dependency
- however, the `package.json` shows **v0.19.2** for the installed packages `cli`, `dev-server`, `eslint-config`,`eslint-plugin-redwood`, `internal`, `structure`, `testing`

### Diagnosis
`yarn.lock` is showing some funky versions. 

`@redwoodjs/core` is correct:
```
"@redwoodjs/core@^0.19.2-canary.45":
  version "0.19.2-canary.45"
...
```
`@redwoodjs/cli` includes the  `+hash`, which means semver resolves to `0.19.2`:
```
"@redwoodjs/cli@^0.19.2-canary.45+f354b564":
  version "0.19.2"
```

It's most likely this started after I released the `.2` patch. Which means it might resolve once `v0.20.0` is released.

## Workaround
For now, the workaround is manually installing the packages at the correct canary version. So after running `yarn rw upgrade -t canary` to upgrade to `0.19.2-canary.45`, for example, you'd then need to run:
```
yarn add -W @redwoodjs/cli@0.19.2-canary.45 @redwoodjs/dev-server@0.19.2-canary.45  @redwoodjs/eslint-config@0.19.2-canary.45 @redwoodjs/eslint-plugin-redwood@0.19.2-canary.45  @redwoodjs/internal@0.19.2-canary.45  @redwoodjs/structure@0.19.2-canary.45  @redwoodjs/testing@0.19.2-canary.45 
```

Yeah, I know... 🤢

**Comment by AntonioMeireles** [comment]
fwiw, afaict,  alternatively placing snippet bellow inside top level's  `package.json` will do the trick for now ...
```
  "resolutions": {
    "@redwoodjs/cli": "0.19.2-canary.52",
    "@redwoodjs/web": "0.19.2-canary.52",
    "@redwoodjs/dev-server": "0.19.2-canary.52",
    "@redwoodjs/eslint-config": "0.19.2-canary.52",
    "@redwoodjs/eslint-plugin-redwood": "0.19.2-canary.52",
    "@redwoodjs/internal": "0.19.2-canary.52",
    "@redwoodjs/structure": "0.19.2-canary.52",
    "@redwoodjs/testing": "0.19.2-canary.52"
  }
```

**Comment by thedavidprice** [comment]
Not sure if these are helpful, but Next canary publishing for reference/research:
- Main script: https://github.com/vercel/next.js/blob/canary/publish-release.sh
- Used in this Action: https://github.com/vercel/next.js/blob/canary/.github/workflows/build_test_deploy.yml

**Comment by peterp** [comment]
I think I've mentioned this before, but perhaps using yarn's upgrade command is not the way to go.

Would it be possible to:

1. Grab the latest canary version string from npm.
2. Programatically modify the `"@redwoodjs/*"` packages in `package.json` files.
3. Run `yarn install`

**Comment by thedavidprice** [comment]
@peterp That’s definitely possible, but in this case, it seems there's something else that's out of sorts with the Canaries.

Even if you manually try to upgrade to canaries right now, the dependency packages do not upgrade.

Our current published version is now at `v0.19.3`. The latest canary is at `v0.19.2-canary.61`. So I thought this reinforced my potential "semver" issue, but I couldn't get it to work even when pinning the packages. 

### Examples
1. Manually changed the 5 `@redwoodjs/*` package versions to `"^0.19.2-canary.61"`
2. Then tried to pin via `"0.19.2-canary.61"`

Ran  `yarn` (and then `yarn --force`).

In both cases, `node_modules/@redwoodjs/cli/package.json` is at `"0.19.3"`

## Questions and Possible Next Steps
It's my understanding this will resolve once we publish v0.20.0. However:

- This is going to make testing the v0.20.0 hard. Is there a way to manually publish + "reset" the canary publishing? (If so, let's document it as well.)
- It's likely things became out of sync when I published v0.19.2, although I don't know why or if for certain. Either way, it would be good to document the "right" workflow for publishing patch releases and then make sure the canaries work accordingly.

**Comment by thedavidprice** [comment]
@peterp I can confirm `yarn rw upgrade -t canary` is now working after you used Lerna to publish the "ghost" tag v0.19.4

For diagnosing, here's what I see after running the upgrade command:
- in `/package.json`: "@redwoodjs/core": "^0.19.5-canary.4"
- `node_modules/@redwoodjs/core/package.json`
    - package version at `"version": "0.19.5-canary.4+f68f2245",`
    - included dependency CLI at `"@redwoodjs/cli": "^0.19.5-canary.4+f68f2245",`
- `node_modules/@redwoodjs/cli/package.json`
    - package version is at `"version": "0.19.5-canary.4+f68f2245",`

I don't understand where the `+f68...` is coming from. But it seems that when the canaries were publishing at the previous patch `0.19.2` after `0.19.3` was released, the `+f68...` was causing semver to install the dependencies at `0.19.3`. 

Strange all around.

**Comment by pi0neerpat** [comment]
> I don't understand where the +f68... is coming from

I found this related discussion that might help https://github.com/lerna/lerna/issues/1893#issuecomment-583124032 and it turns out the sha is supposed to be included here, but npm strips it out!

**Comment by thedavidprice** [comment]
> turns out the sha is supposed to be included here, but npm strips it out

^^ Ah, very interesting!

We did resolve this back in October. But good to know as there are still occasional hiccups.
