### ISSUE TITLE
Unable to import ts/tsx components using short import path | v0.19.2

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#1290]
When trying to import a component without the absolute import path, error from webpack
```
Module not found: Can't resolve '../../components/AddTodo' in '/Users/xxx/Experiments/rw-example-todo/web/src/pages/HomePage'
```
Reproduced in example todo app, by renaming AddTodo.js to AddTodo.tsx. Also seeing the same issue on our app.

I suspect the issue may have been introduced here: https://github.com/redwoodjs/redwood/pull/1102/files

---

### Work around for now
Instead of importing the file like this:
```
import AddTodo from 'src/components/AddTodo'
```
can be imported like this
```
import AddTodo from '../../components/AddTodo/AddTodo'
```
Ugly I know!

---

RW Version: 0.19.2

**Comment by dac09** [comment]
Some more info. My hunch seems to be correct, adding logs into `packages/core/src/babelPlugins/babel-plugin-redwood-directory-named-import.ts`

It looks like when its TS, the importPath that's generated in the `getNewPath` function [here](https://github.com/redwoodjs/redwood/blob/3e1d453d282531f1a05f08d442c93f695bd6ccee/packages/core/src/babelPlugins/babel-plugin-redwood-directory-named-import.ts#L5) has something extra added to the path

Console logs:
```
web | xxx dirname ->  ../../components/AddTodo
web | xxx basename ->  AddTodo
web | xxx path ->  /Users/dac09/Experiments/rw-example-todo/web/src/components/AddTodo/AddTodo/AddTodo
web | xxx error -> Error: Cannot find module '/Users/dac09/Experiments/rw-example-todo/web/src/components/AddTodo/AddTodo/AddTodo'
```

**Comment by dac09** [comment]
Logs from 

```
web | xxx dirname ->  ../../components
web | xxx basename ->  AddTodo
web | xxx path ->  /Users/dac09/Experiments/rw-example-todo/web/src/components/AddTodo/AddTodo
web | 💥 null path
web | xxx New path null
```

It looks like it can't resolve the file in [this line](https://github.com/redwoodjs/redwood/blob/3e1d453d282531f1a05f08d442c93f695bd6ccee/packages/core/src/babelPlugins/babel-plugin-redwood-directory-named-import.ts#L25)

**Comment by thedavidprice** [comment]
Thanks, Danny! And ugly indeed.

@peterp this one's for you (and on my list to show you when you're back)
