### ISSUE TITLE
eslint-config: consider consuming  "simple-import-sort" eslint plugin

### ISSUE THREAD

**Issue by AntonioMeireles** [redwoodjs/redwood#1297]
Hi all, 

please consider within the  RW linting machinery to ship by default `simple-import-sort` eslint plugin as would make code objectively more readable out of the box (again IMHO), and (more debatable) also eventually the `json` one. 

current workaround is to use (in top-level's `package.json`)
```json
"devDependencies": {
    "@redwoodjs/core": "^0.19.2-canary.45",
    "eslint-plugin-json": "2.1.2",
    "eslint-plugin-simple-import-sort": "5.0.3"
  },
  "eslintConfig": {
    "extends": [
      "@redwoodjs/eslint-config"
    ],
    "plugins": [
      "json",
      "simple-import-sort"
    ],
    "rules": {
      "json/*": [
        "error",
        "allowComments"
      ],
      "simple-import-sort/sort": "error"
    }
  }, 
```  
but IMHO would be really nice if stuff coming from generators would come 'nice' by default.  

All the Best, 

António

P.S. ironically "_import sorting_" is already referred as a feature of `eslint-config` [here](https://github.com/redwoodjs/redwood/blob/main/packages/eslint-config/index.js#L8)

**Comment by thedavidprice** [comment]
Hi @AntonioMeireles Appreciate the suggestion. It would be helpful to see how this will change the code formatting. Could you possibly provide an example of formatted _before_ and _after_ using the `simple-import-sort` plugin?

**Comment by AntonioMeireles** [comment]
@thedavidprice 

check snippet bellow for the before and after. 

<img width="513" alt="image" src="https://user-images.githubusercontent.com/743527/95447967-7b94fb80-095a-11eb-96ba-32b05be30922.png">

it's an opinionated/stylistic thing - it just enforces import sorting in a consistent/predictable way (which imho improves a bit code readability) 

regarding the `json` plugin, main use case is to reduce noise in the vscode rw plugin, as without it vscode's  plugin  rants about the 3 `package.json` having syntax issues. 

all the best!

**Comment by thedavidprice** [comment]
Got it. This is helpful, thanks!

> regarding the json plugin, main use case is to reduce noise in the vscode rw plugin, as without it vscode's plugin rants about the 3 package.json having syntax issues.

^^ completely understood

Handing this over to @peterp for consideration when he's back next week. PP, I'd give these a +1 but I haven't done much of our eslint config to-date.

The request is to add: 
```
    "eslint-plugin-json": "2.1.2",
    "eslint-plugin-simple-import-sort": "5.0.3"
```

See OP for settings.

**Comment by AntonioMeireles** [comment]
Oops, just a quick side note: 

there was a typo im my original copy & paste. no need at all to hard-lock the versions so  it would be something along ...

> "eslint-plugin-json": "^2.1.2",
> "eslint-plugin-simple-import-sort": "^5.0.3"

&& thanks!

António

**Comment by AntonioMeireles** [comment]
just a quick note to point that the import sort part is going to be addressed by https://github.com/redwoodjs/redwood/pull/1381 :-)

**Comment by Krisztiaan** [comment]
@AntonioMeireles I never actually used `eslint` for `json`, do you think it's worth it?

**Comment by AntonioMeireles** [comment]
@Krisztiaan 

> @AntonioMeireles I never actually used `eslint` for `json`, do you think it's worth it?

for sophisticated use cases `eslint` definitively not the most adequate tool to tackle json. OTOH `eslint-plugin-json` handles the obvious typos sanely and has the side benefit to reduce noise in vscode when using the RW vscode plugin (which frankly is the reason why i added it :-) ).

**Comment by peterp** [comment]
Hey there - we actually had something like this in our ESLint configuration before, but we removed it because it made it more difficult for people to contribute, and it didn't work with directory named modules.

Now that we have the babel-module for directory-named-modules we could probably try this again.
