### ISSUE TITLE
[redwood-tools] package linking fails silently if CLI commands invoke yarn to install packages

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1302]
During the development of the new `setup` command, strange behavior was occurring during testing:
- https://github.com/redwoodjs/redwood/issues/1223#issuecomment-703510327
...and also during the improvement of the auth generator...
- https://github.com/redwoodjs/redwood/pull/1251#issuecomment-704283623

It seems that anytime a command runs `yarn install` (at the beginning for `yarn rw setup tailwind` and the end for `yarn rw g auth ...`) the linking from redwood-tools `yarn rwt ...` is broken. However, the terminal output doesn't indicate anything has changed. 

Ideally, redwood-tools would re-run if `yarn install` is run and changes the link to local packages.

**Comment by Tobbe** [comment]
Most ideally we would make sure `yarn install` doesn't mess with the links at all. Especially since the `yarn build:watch` `yarn rwt copy:watch` workflow doesn't work on windows (see https://github.com/redwoodjs/redwood/issues/701)

**Comment by thedavidprice** [comment]
we use "link" but the actual process is literally copying the packages from Framework into a Project. I don't understand the mechanics (yet), but we'd want to add a watch on the destination `node_modules` as well -- while `yarn rwt cpw ...` is running, if it detects changes to node_modules@redwoodjs/package it would re-run copy.

**Comment by jtoar** [comment]
I think this has been resolved now with the new `yarn rwt link` command; didn't see this come up while I was developing the setup a11y command.
