### ISSUE TITLE
Offline support?

### ISSUE THREAD

**Issue by chrisdrackett** [redwoodjs/redwood#1319]
Curious if any though has been put into supporting a site working without an internet connection. Thinking about local caching, optimistic updates, change tracking for when a client comes back online.

**Comment by thedavidprice** [comment]
At one time, @phzbox put together a great document with thoughts about this. He has a lot of experience with offline. It was early days for Redwood so hasn't been implemented yet.

With your permission, Dominic, I could share the Google Doc link. Or please do add it yourself and help us get up to speed!

**Comment by thedavidprice** [comment]
@chrisdrackett would welcome help toward this end if you're interested! In that case, it would be better to move the discussion over to the Forums https://community.redwoodjs.com

No pressure of course.

**Comment by thedavidprice** [comment]
Thanks @phzbox 

@chrisdrackett I've moved the conversation over to the Forums in hopes of getting some momentum:
https://community.redwoodjs.com/t/offline-support/1305

Closing this one. Thank you both!
