### ISSUE TITLE
Could add a tutorial for PWA?

### ISSUE THREAD

**Issue by zwl1619** [redwoodjs/redwood#133]
Could add a tutorial for PWA?

**Comment by thedavidprice** [comment]
Hi @zwl1619 Thanks for taking a look at RedwoodJS! Internally we are definitely focused on PWA and just good ol' fashioned end-user performance. Out of the box we already cover:
- [x] Code splitting on routes
- [x] https when deploying to Netlify
- [x] static file folder to drop in your manifest.json

To help us focus on issues that matter to you, could you tell us more about 1) specific PWA topics that matter most to you (not included above) and 2) your end-user use case(s) that matter most to you?

And keep a lookout for more documentation coming online soon. And in the meantime be sure to take a look at our Tutorial repo and Router documentation if you haven't already:
- https://github.com/redwoodjs/tutorial
- https://github.com/redwoodjs/redwood/blob/master/packages/router/README.md

**Comment by andrewlamyw** [comment]
👋Hi, may I know where shall I put the `manifest.webmanifest` file?🙏

**Comment by andrewlamyw** [comment]
Other than adding `manifest.json` in the `web\public` folder, what else do I need to tweak to make it work?

**Comment by Tobbe** [comment]
There has been some more PWA talk in both the forum and in other issues and PRs. Here are a couple of links
https://community.redwoodjs.com/t/offline-support/1305
https://github.com/redwoodjs/redwood/pull/1372

Does any of the existing discussions answer your question?

**Comment by shogs** [comment]
> dandv

redwood js uses prisma for database access layer and prisma comes with support for mongodb:

https://www.prisma.io/docs/concepts/database-connectors/mongodb
