### ISSUE TITLE
`rw upgrade -t ...` fails if either `web/` or `api/` are not present

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1343]
Currently, the Upgrade command with `--tag` option assumes _both_ the Web and API sides exist and, therefore, the corresponding `@redwoodjs/api|web|etc` packages should all be installed. In the case there is no API directory, for example, `yarn rw upgrade -t canary` will fail with the error: `...no @redwoodjs/api package found`

**TO DO**
- check for existing packages (might be simpler to check if directories exist then assume corresponding Redwood packages included)
- then build list of packages to install with the given tag

> Note: this does not affect `yarn rw upgrade` which always upgrades to the latest stable version and does check for existing packages.

**Comment by thedavidprice** [comment]
Confirming this is still an issue with the improved upgrade command

**Comment by rainkinz** [comment]
I am probably missing something, but I just tried this and it seems to work:

```
➜  x-redwood-test-project git:(main) yarn rw upgrade -t canary
yarn run v1.23.0-20220118.1001
$ /Users/brendan/Projects/kuripai/x-redwood-test-project/node_modules/.bin/rw upgrade -t canary
  ✔ Checking latest version
  ✔ Checking latest version
  ✔ Updating your project package.json(s)
    ✔ Updating /Users/brendan/Projects/kuripai/x-redwood-test-project/package.json woot
    ↓ Updating /Users/brendan/Projects/kuripai/x-redwood-test-project/api/package.json woot [skipped]
    ✔ Updating /Users/brendan/Projects/kuripai/x-redwood-test-project/web/package.json woot
  ✔ Running yarn install
  ✔ Refreshing the Prisma client
  ✔ De-duplicating dependencies
  ✔ One more thing...

    🎉 Your project has been upgraded to RedwoodJS 0.42.1-canary.9!

    Please review the release notes for any manual steps:
    ❖ Redwood community discussion (https://community.redwoodjs.com/search?q=0.42.1-canary.9%23announcements)
    ❖ GitHub Release notes (https://github.com/redwoodjs/redwood/releases)

✨  Done in 67.33s.
```

It looks like the list of paths generated does include `api':

https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/upgrade.js#L220
```
const updatePaths = [
    getPaths().base,
    getPaths().api.base,
    getPaths().web.base,
  ]
```

but are subsequently checked for existence and skipped if they don't exist:

https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/upgrade.js#L226
```
return new Listr(
    updatePaths.map((basePath) => {
      const pkgJsonPath = path.join(basePath, 'package.json')
      return {
        title: `Updating ${pkgJsonPath}`,
        task: () =>
          updatePackageJsonVersion(basePath, ctx.versionToUpgradeTo, options),
        skip: () => !fs.existsSync(pkgJsonPath),
      }
    })
  )
```

**Comment by thedavidprice** [comment]
Agreed! Huge help confirming whether or not this is resolved @rainkinz 🚀
