### ISSUE TITLE
[Docs] Adding Table of Content to Readme.md

### ISSUE THREAD

**Issue by ng29** [redwoodjs/redwood#1379]
Hey @peterp / @dominicchapman / @thedavidprice 
Describe the problem
Missing table of contents in readme.

Describe the improvement
The idea for Adding Table of Content to Readme.md to add additional enhancement and readability to the docs file.
A clear and concise description of the improvement.

I would like to work on this

**Comment by thedavidprice** [comment]
Hi @ng29 Thanks for offering to help!

This repo's README.md is used on our website here: https://redwoodjs.com/docs/introduction And you can see below the right sidebar is a TOC. 
<img width="1242" alt="Screen Shot 2020-10-03 at 12 31 46 PM" src="https://user-images.githubusercontent.com/2951/95000384-20879100-0575-11eb-819a-c7e5af23a38c.png">

## Other Ways to Get Started as a Contributor
So let's pass on this suggestion. However, we ❤️ that you'd like to help as a contributor and want to help! If you'd like to start with documentation, take a look at the list of Issues in our Website repo:
- https://github.com/redwoodjs/redwoodjs.com/issues

And a couple other places to get started might be with Issues we've labeled here:
- https://redwoodjs.com/good-first-issue
and here:
- https://github.com/redwoodjs/redwood/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest

Lastly, please don't hesitate to ask the community for help getting started:
- https://community.redwoodjs.com
- https://discord.gg/redwoodjs
