### ISSUE TITLE
Scaffold create and delete mutations don't update the UI

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#1384]
Re @cannikin, some of the scaffold's create and delete mutations don't update the UI anymore.

## Create

![create](https://user-images.githubusercontent.com/32992335/96644572-1dfb9a00-12de-11eb-9263-7d0ddbfd13bf.gif)

This used to worked in ApolloClient v2 because of the cache-and-network fetch policy. But the cache-and-network fetch policy in v3 doesn't seem to be exactly the same, so we use cache-first now (which is also Apollo's default). 

But since cache-first considers its job done as long as something's in the cache (even an empty array), the create mutation has to take care of updating the cache (it doesn't right now).

## Delete

![delete](https://user-images.githubusercontent.com/32992335/96644576-1f2cc700-12de-11eb-84cf-d196c5770e7f.gif)

> Note that the delete button on the Posts page works because it specifies refetchQueries. So maybe we could just do that for the other ones too? That's what I thought, but it doesn't seem to be working. TBD.

Working on a fix now.

**Comment by thedavidprice** [comment]
@jtoar Did you see this PR from Peter? https://github.com/redwoodjs/redwood/pull/1342

**Comment by jtoar** [comment]
@thedavidprice Yeah I'm pretty sure that's just for updating an item using the edit button--apollo handles those kinds of mutations really well.

**Comment by thedavidprice** [comment]
Ah, got it. I went through this too quickly the first time.

And, um, HOW HAS NO ONE ELSE REPORTED THIS YET 🤯

I think we're within 24 hour of trying to get v0.20 out. Are you working on this now? Would be fantastic to have it resolved. Thanks in advance!

**Comment by jtoar** [comment]
I think @cannikin brought it up at the last meeting? That's why I started on this at least. Kind of hard to remember among all the apollo things going on :sweat_smile:.

But yeah I'll prioritize a fix in that time!

**Comment by thedavidprice** [comment]
Fixed in #1387
