### ISSUE TITLE
Deploying on Netlify: "Failed to upload file: graphql"

### ISSUE THREAD

**Issue by tctrautman** [redwoodjs/redwood#1385]
Hey all, before diving in here I want to take a moment to thank the core team and community -- I've had such a great time working with Redwood the last few months.  But I've run into an issue and would appreciate any debugging recommendations that you might have.

I've been receiving the following error when trying to deploy to Netlify today:
```
8:20:16 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
8:21:33 PM: Failed to upload file: graphql
8:21:33 PM: Failing build: Failed to deploy site
```

This is my graphql.js:
```
import {
  createGraphQLHandler,
  makeMergedSchema,
  makeServices,
} from '@redwoodjs/api'

import schemas from 'src/graphql/**/*.{js,ts}'
import services from 'src/services/**/*.{js,ts}'

import { getCurrentUser } from 'src/lib/auth'
import { db } from 'src/lib/db'

export const handler = createGraphQLHandler({
  getCurrentUser,
  schema: makeMergedSchema({
    schemas,
    services: makeServices({ services }),
  }),
  onException: () => {
    // Disconnect from your database with an unhandled exception.
    db.$disconnect()
  },
})
```

I'm on version `0.19.3`, and had a successful deploy on `0.19.1`.  I've gone through the release notes for `0.19` to make sure I've done the needed recent manual code changes, and - though I haven't gone through all version release notes again, I've always made note to make the needed changes since I started at `0.11`.

I've also searched github issues but haven't found others running into this problem (though [this](https://github.com/redwoodjs/redwood/issues/1196) yielded a similar error, but seemed to be prisma config issue.

Right now my leading theory is that some `/api` packages that I've installed since my last successful deploy, which are used in my services file, have increased to a size beyond the max lambda function size.  This theory assumes that all services files get bundled into the the `graphql.js` file, but I'm not actually sure if that's actually what's happening.

Does this theory sound reasonable to you all or might there be something else going on here?  Any ideas on how else I might go about debugging?

**Comment by tctrautman** [comment]
After looking at this with fresh eyes this morning I've gone ahead and confirmed my theory: upon removing a large npm package my builds succeeded.

In my case it's because I was using `puppeteer`, which installs a browser (🤦 ), instead of `puppeteer-core`.

I haven't quite resolved my problem yet, but I have a clear [path](https://bitsofco.de/how-to-use-puppeteer-in-a-netlify-aws-lambda-function/#:~:text=Install%20the%20full%20puppeteer%20package,which%20Puppeteer%20package%20to%20use) forward and think this is safe to close.

**Comment by Tobbe** [comment]
Great that you figured it out @tctrautman!

In the future, if you run in to this again, this is how you can troubleshoot/debug

```
$ yarn workspace api add -D @netlify/zip-it-and-ship-it
$ yarn rw build api
$ yarn zip-it-and-ship-it api/dist/functions/ zipped
```

Now you will have the bundled files in `zipped/` and can see exactly how big they are and what's in them.

**Comment by tctrautman** [comment]
Perfect, thank you @Tobbe!
