### ISSUE TITLE
Add prismaVersion field to the redwood query

### ISSUE THREAD

**Issue by divyenduz** [redwoodjs/redwood#1395]
Feature request, this would help with debugging. 

![image](https://user-images.githubusercontent.com/746482/96986501-03196780-1522-11eb-8081-a92507e32b66.png)

Prisma version can be fetched from 

```ts
const { prismaVersion } = require('@prisma/client')
console.log(prismaVersion.client)
```

**Comment by peterp** [comment]
Awesome 👍

**Comment by lumenCodes** [comment]
🤔

**Comment by jvanbaarsen** [comment]
I went ahead and gave this a shot. I wasn't able to find any tests that would cover this particular use case, so please let me know if/where I can add those.
