### ISSUE TITLE
Tutorial: Code block in 'Saving Data' section

### ISSUE THREAD

**Issue by virenb** [redwoodjs/redwood#1429]
URL: [https://redwoodjs.com/tutorial/saving-data](https://redwoodjs.com/tutorial/saving-data)

In the Saving Data section of the tutorial, I believe two of the code blocks (attached) need to be updated with a self closing tag, for the component, Flash? 

![Screen Shot 2020-11-02 at 6 19 32 PM](https://user-images.githubusercontent.com/10731287/97929897-389b2d80-1d38-11eb-8886-9467cb3faa39.png)
![Screen Shot 2020-11-02 at 6 19 23 PM](https://user-images.githubusercontent.com/10731287/97929899-389b2d80-1d38-11eb-92a8-33055f139c95.png)

It is causing the error of 'failed to compile'

(In one of the final code blocks on this page, the Flash component uses a self closing tag)

**Comment by thedavidprice** [comment]
Hi @virenb Thanks for the help here. I believe the confusion is coming from how the `//...` is implying a placeholder for the rest of the block of code. These snippets are balancing between 1) showing what needs to be updated while 2) giving enough information to provide context without being overwhelming.

Take a look at the final code for `ContactPage.js` at the [bottom of the page](https://redwoodjs.com/tutorial/saving-data) in the section "Here's the final ContactPage.js page:". Given that we don't want to show that entire block of code every time, _do you have any ideas or suggestions about how we can make the blocks of code in your comment more understandable?_

Lastly, the Tutorial and all documentation is in this repo https://github.com/redwoodjs/redwoodjs.com I'm going to close out this Issue for now. If you'd like to continue the conversation (or even open a PR, which is very welcome!), please do so in the [redwoodjs.com](https://github.com/redwoodjs/redwoodjs.com) repo and reference this Issue. 

Thanks again!

**Comment by Tobbe** [comment]
@thedavidprice I actually think this is a valid issue. 
@virenb I'll fix it tomorrow. Thanks for reporting

**Comment by thedavidprice** [comment]
Ah, understood and I misread. Thank you @Tobbe!

**Comment by virenb** [comment]
Hi all, 
Sorry for creating the issue on the wrong repository. 
@Tobbe, I'd be happy to update and create a pull request, if you'd like.

**Comment by thedavidprice** [comment]
@virenb Please do! We ❤️ new contributors.

**Comment by jtoar** [comment]
Looks like this one's been fixed!
