### ISSUE TITLE
Orphaned comma breaking `yarn rw g scaffold` command when no field with `string` type is present in model

### ISSUE THREAD

**Issue by hyliancoder** [redwoodjs/redwood#1435]
# Bug report

## Describe the bug

I have a implicit many-to-many between my user and channel model. but the scaffold is failing.

I added a title field as string, because sniffing down the other instances of where that form is generated the `,` line its failing on (see step 3 below) should be `TextField`, via this import line used on any generated forms `import { Form, FormError, FieldError, Label, TextField, NumberField, Submit } from '@redwoodjs/forms';`
![generated form data screenshot](https://i.imgur.com/XZToEa6.png)

but instead when I tried to scaffold my channel model it doesn't see any text fields needed, and like it should, skips the need to import `TextField` but instead of being empty, throws an orphaned comma `,` and halts the whole scaffold due to that orphaned comma. 

## To reproduce

1. create a model without a field with type of string (id doesnt count in this case since it isnt used in the form):
![model screenshot](https://i.imgur.com/zEd4F7t.png)

2. run your migrations `yarn rw db save` && `yarn rw db up`

3. run scaffold for your models. `yarn rw g scaffold <model>` in this case i'll use `yarn rw g scaffold channel`
![scaffold generate error screenshot](https://i.imgur.com/ytR3rJw.png)

4. to 'fix' it, you'll need to add a field with type of string to the model and do migrations in step 2.
![tempfix for model screenshot](https://i.imgur.com/hdVbgNH.png)

## Expected behavior

run `yarn rw g scaffold channel` and it successfully generate scaffolding, along with conditionally removing fields like `TextField` from the Form when not used.

## System information

- OS: macOS
- Browser (if applies): Firefox, Chrome
- Version of @redwoodjs: 0.20.0
- Version of Node.js: 15.0.1

**Comment by Tobbe** [comment]
![image](https://user-images.githubusercontent.com/30793/98112242-29d08a00-1ea2-11eb-8797-c89237cd4c1a.png)

**Comment by hyliancoder** [comment]
https://github.com/redwoodjs/redwood/pull/1436

**Comment by Tobbe** [comment]
Thinking about this some more I'm not sure this is a usecase we should support. So instead of generating broken code, a message could be printed about not finding any editable fields, and then exit the generator before generating any code.

Haven't fully decided yet, but that's the way I'm leaning right now.
