### ISSUE TITLE
Prisma to support setting a foreign key like any other field - update scaffolds

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#1437]
https://github.com/prisma/prisma/issues/2152

This means we can include a `TextField` input for any foreign key relationships on a model and can create related records correctly, instead of hacking the foreign-key-to-prisma-connect-syntax hack that we [thought about adding](https://github.com/prisma/prisma/issues/2152#issuecomment-621375111).

**Comment by thedavidprice** [comment]
Once these changes are made, we'll also need to update:
1. [Schema Relations Doc](https://redwoodjs.com/docs/schema-relations): just delete and/or update with helpful links and the video recording by Ryan C.?
2. Remove the [output warning when the CLI Scaffold Generator](https://github.com/redwoodjs/redwood/pull/984) is run

**Comment by jtoar** [comment]
While I don't think we warn when scaffolding anymore, it doesn't look like we've updated the schem relations doc or the scaffolds yet.
