### ISSUE TITLE
Generate Entity Relationship Diagram (Database Schema Visualization)

### ISSUE THREAD

**Issue by aldonline** [redwoodjs/redwood#1438]
# Idea

* Provide a built-in way to generate an Entity Relationship Diagram from schema.prisma (or directly from the database)
* Make it easy to access for Redwood developers
  * `rw erd` (ERD = Entity Relationship Diagram)
    * Generates a diagram and opens an image/svg or maybe an interactive webapp
  * in VSCode `Redwood: Open Entity Relationship Diagram`
    * Same as above, but opens the diagram in the context of VSCode

# Why?

* Even the simplest built-in diagram can help us enrich the workflow and tutorials

# Implementation?

Ideally, prisma.io should provide this (since we're treating schema.prisma as our source of truth). Unfortunately, I couldn't find a concrete solution to this problem (maybe I missed something, @schickling?). Here are two related (open) issues:

* [ER diagram from the schema (prisma/prisma#772)](https://github.com/prisma/prisma/issues/772)
* [Visual schema designer (prisma/studio#198)](https://github.com/prisma/studio/issues/198)

As @dthyresson pointed out, there is a [prisma->DBML generator, which we can then feed to dbdiagram.io](https://twitter.com/prisma/status/1311295053084721152). But this isn't something we can integrate into our tooling since it depends on an online service.

Any ideas/pointers for the implementation are welcome :)

**Comment by nikolasburk** [comment]
Note that there are currently two open source tools that do something similar:

- [emyann/prisma-uml](https://github.com/emyann/prisma-uml)
- [notiz-dev/prisma-dbml-generator](https://github.com/notiz-dev/prisma-dbml-generator) ([more info](https://notiz.dev/blog/prisma-dbml-generator#dbml-generator))

**Comment by initplatform** [comment]
Can I ask what you used to generate the current diagrams in the documentation? I really like their look.

![image](https://user-images.githubusercontent.com/47506789/112154868-14db6580-8bbb-11eb-8c24-57c28ff9679c.png)

**Comment by thedavidprice** [comment]
@noire-munich I think you'll be interested in seeing the visual graphing tools mentioned in [this comment above](https://github.com/redwoodjs/redwood/issues/1438#issuecomment-722438213).

**Comment by noire-munich** [comment]
Thanks @thedavidprice , I was aware of prisma-dbml-generator only, but if we are to go that way, generating a diagram any time we need to see the schema, our IDEs have a native solution based on DB introspection that works correctly - we're on IntelliJ' suite, PyCharm & PhpStorm.
Might be possible to code something more *dynamic* but it's a topic on its own right :-\\.

@aldonline has anything come up in your radar about this issue, since November ?

**Comment by thedavidprice** [comment]
@noire-munich and another one just from today!

https://apis.guru/graphql-voyager/

**Comment by jtoar** [comment]
See https://github.com/redwoodjs/redwood/issues/3887#issuecomment-1118642662.
