### ISSUE TITLE
Configure what files generate command creates

### ISSUE THREAD

**Issue by viperfx** [redwoodjs/redwood#1444]
As the application grows, one might need to change the content of what the commands generate, or if just by design, wanting to avoid creating tests or storybook files for certain generate commands.

**Suggestion for the command options**
```
--no--test
--no-story
```

**Suggestions for the global options via config**

```
[web]
  port = 8910
  apiProxyPath = "/.netlify/functions"
  [generate]
    [cells]
      stories = "true"
      tests = "false"
    [pages]
      stories = "false"
      tests = "true"
```

Credit to @dthyresson for the [command and config suggestions](https://community.redwoodjs.com/t/is-is-possible-to-change-what-the-rw-g-command-generate/308/5?u=viperfx)

**Comment by jvanbaarsen** [comment]
@dthyresson Is this something that PRs will be accepted for? Or still in the proposal stage?

**Comment by dthyresson** [comment]
@jvanbaarsen good question ... I added the "discussion" label so perhaps we can get some feedback from @peterp or @thedavidprice or @cannikin 

I think if it touches the toml, then probably some rounds on what that structure would be as well as the naming and option commands.

**Comment by dthyresson** [comment]
I am also not convinced it needs to be in toml, but perhaps just as options to the generator. Though I see why it would be cumbersome to add the flag each time ... but I do that with ``--crud` on my sdl/services often.

**Comment by cannikin** [comment]
Yeah I was thinking the other day we should probably add flags for each generator for all the individual components and default them to `true` which would preserve the current behavior. Then yargs gives you the `--no-` variant for free.

Being able to set those options permanently in a config file somewhere makes sense. `redwood.toml` seems like the most logical location to me!

**Comment by jvanbaarsen** [comment]
@cannikin Can you assign this one to me? I'd like to work on this, feels like a nice "Good first issue"

**Comment by jvanbaarsen** [comment]
@cannikin I'm I correct in thinking that the following generators would need to have flags:
- [ ] Cell
- [ ] Component
- [ ] layout
- [ ] page
- [ ] scaffold
- [ ] service

I think the other ones either only have one template file, or are not really useful to ignore.

**Comment by cannikin** [comment]
Yup that list sounds right to me

**Comment by dthyresson** [comment]
Not this changes this feature request, but I have started using @aldonline 's Redwood IDE and using it vs the explorer to navigate cells, pages, etc in VS Code and that it omits those test and stories in the tree, I am much more apt to leave those generated files because I *know* that I *should* write tests and stories ... and there is not a great way to stub out generate those files after the fact.

**Comment by jvanbaarsen** [comment]
@dthyresson I actually really would like this option for myself, since I don't write stories for every component. See my question about this on the forum for more context: https://community.redwoodjs.com/t/when-do-stories-make-sense-for-pages/1380

**Comment by dthyresson** [comment]
> @dthyresson I actually really would like this option for myself, since I don't write stories for every component. See my question about this on the forum for more context: https://community.redwoodjs.com/t/when-do-stories-make-sense-for-pages/1380

@jvanbaarsen Oh, I agree with you. It will be a nice option to have -- I just wanted to put in the history of the issue that there can be another perspective.

I actually think I would want stories just for cells and components -- and not so much layouts and pages.

So this feature will help me not to generate those  :)

**Comment by viperfx** [comment]
Progress on this looks great so far 👍 

@jvanbaarsen are you still planning to have global settings inside a TOML? Still feel it would be useful to have default generator behavior defined there.

**Comment by jvanbaarsen** [comment]
@viperfx Yes :-) I'm doing this in between my day job tasks in. So it will take a bit to complete. This week I have vacation (And are not planning on doing any programming 😉) So I'll start working on this again next week!

**Comment by jvanbaarsen** [comment]
I just realise that Scaffolding doesn't have any tests or stories. So no flag is required there. I'll put the PR up for review.

**Comment by jvanbaarsen** [comment]
@viperfx The Global setting is something I'd like to add after the flags have been merged.
