### ISSUE TITLE
Publish PR packages to NPM

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#1458]
Currently whenever a PR is merged a "canary" package is automatically published to npm. This is a super nice feature! I'd like to suggest we expand this to also automatically publish PR packages as soon as a PR comes in (and it passes all tests).

This idea originally came up in chat, so here's the transcript

> @Tobbe: Like if I make a PR (and all tests pass), could we publish a pr version of RW? Like 0.20.0-pr.5557. That would make it really easy for someone to test my PR changes by just installing that RW version
> @dthyresson: that might publish code that has not been reviewed though or approved.
> @Tobbe: Yeah, any PR would become a package. But the only way to install that package would be to explicitly specify the exact package name.
> @Tobbe: It would, for example, let me make a PR for my version of RW without apollo client, and you could install the package to test it out
> @Tobbe: So it's easier for anyone to test stuff before it gets merged (and a canary release is available)

The need/want for this recently came up again here https://github.com/redwoodjs/redwood/pull/1311#issuecomment-723924890 which prompted me to create a proper issue for it

**Comment by jeliasson** [comment]
This would indeed be super helpful. Some features may require additional time to complete (discussions, reviews, documentation) so having something to test and target PR packages before it hits the main branch (canary or release) would be a game changer. 👏🏻

**Comment by Tobbe** [comment]
After some discussion with @peterp we decided that we don't want to publish packages to npm. One reason being that they're difficult to delete and manage.

But we do want to make it easier to test and demo code that's in a PR. We are open to suggestions on how to do this that doesn't involve publishing to npm. In addition to installing from the npmjs registry, npm can also install from GitHub repos and local or remote tarballs. So we're looking for a solution that utilizes those additional sources somehow
