### ISSUE TITLE
useMatch does not match against query params

### ISSUE THREAD

**Issue by viperfx** [redwoodjs/redwood#1460]
When using a Link that does routing with a query params such as `routes.home({filter: "DASHBOARD"})`, this matches for all home routes and does not distinguish between query params

**Comment by Tobbe** [comment]
Could you provide a small reproduction example please?

**Comment by viperfx** [comment]
When using a link like so

```
<Link to={routes.feedback({filter: "IDEA"})}>
<Link to={routes.feedback({filter: "ISSUE"})}>
```

it produces a URL like so /feedback?filter=IDEA and /feedback?filter=ISSUE

When using `const matchInfo = useMatch(to)` and passed in an example like the above, it matches for /feedback/ but ignores the query params

**Comment by jtoar** [comment]
Might be the same as #2362

**Comment by LBrian** [comment]
> Might be the same as #2362

This is the same issue @dthyresson mentioned in #2362 regarding `queryString` matching and the root cause is `matchPath` doesn't take `location.search` into account, we should be able to tackle this in #2362 as a whole.

**Comment by LBrian** [comment]
PR #2683
