### ISSUE TITLE
VS Code Extension wont load in remote - ssh mode.

### ISSUE THREAD

**Issue by chasak** [redwoodjs/redwood#1478]
Redwood vscode extension wont load when I use it with remote - ssh extension. The error says 
"Cannot activate the 'Redwood IDE' extension because it depends on the 'Browser Preview' extension, which is not loaded. Would you like to reload the window to load the extension?"
If I reload the window again, the issue pops up again.

**Comment by viperfx** [comment]
Ive noticed this in WSL mode on windows too. The extension is unusable for me, and I get the exact message you mentioned.

**Comment by BstevensG4G** [comment]
I think more of us should make a comment in this issue on the vs code repository. I really think this may be something that could either resolve or at least give the extension builder the opportunity to debug this issue!
Feature: Specifying the load order of extensions (reduce startup wait-time) #46846

**Comment by Forwardslash-development** [comment]
Same issue here.  Win10/WSL2/Ubuntu20/VSCode. Commenting to follow.

**Comment by thedavidprice** [comment]
Hi all. We are in between major changes and updates to the Extension. The current codebase is effectively going to be replaced, which is a great thing overall. It's still just a couple of months out.

We're paying attention to these Issues and will update accordingly. Thanks for your patience!

**Comment by jtoar** [comment]
See https://github.com/redwoodjs/redwood/issues/3887#issuecomment-1118642662.
