### ISSUE TITLE
Lock auth client versions

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#1479]
Currently when running the auth generator we add the relevant client library to the user's `web/package.json`, like this `packages/cli/src/commands/generate/auth/providers/supabase.js:export const webPackages = ['@supabase/supabase-js']`

The problem is that we don't specify a version for, in this case, the supabase client library. So when a new version is released our generated code might break. Case in point: https://github.com/redwoodjs/redwood/issues/1426 supabase released a new version where some methods changed names, so now whenever a RW user tries to generate supabase based auth, the code will be broken. If @supabase/supabase-js was pinned to `0.36.5` (which is the last version we support) this wouldn't have happened.

Do you all agree? Any input?

/cc @dthyresson @peterp

**Comment by peterp** [comment]
@Tobbe Yeah, I agree, makes total sense.

**Comment by dthyresson** [comment]
This also introduces an inverse consideration: how to recognize when to bump versions. But that can be solved by process - watching the auth providers to see when enhancements warrant a bump.

But, agree — should lock. We saw unexpected behavior with Tailwind setup when it could bump PostCSS and it did not play well with others in RW.

**Comment by dthyresson** [comment]
For Supabase, we can lock via a [Caret range](https://classic.yarnpkg.com/en/docs/dependency-versions/#toc-caret-ranges):


> Allow changes that do not modify the first non-zero digit in the version, either the 3 in 3.1.4 or the 4 in 0.4.2.

`"@supabase/supabase-js": "^1.1.1",`

To just 1.1.

I can add this to my PR for supporting OAuth: https://github.com/redwoodjs/redwood/pull/1669
