### ISSUE TITLE
CRUD generation does not respect @id data type

### ISSUE THREAD

**Issue by chris-hailstorm** [redwoodjs/redwood#148]
ENVIRONMENT

    $ yarn rw --version
    0.0.1-alpha.31

OBSERVATION

Following the Post example in the tutorial. Run:

    $ yarn rw g scaffold post

All files are generated and updated.  Run the db save / db up cycle.

Visit the web app -- create a new post -- works fine.

Now click Show, Edit or Delete -- get a `404 - Page not found`.

My `schema.prisma` defines this model (note `@id` field is `cuid`, not `autoincrement`):

    model Post {
      id        String 	@id @default(cuid())
      title     String
      body      String
      createdAt DateTime @default(now())
    }

The sqlite DB has `id` as a text field, as expected for `cuid`:

    sqlite> .dump Post
        CREATE TABLE IF NOT EXISTS "Post" (
        "body" TEXT NOT NULL DEFAULT '' ,
        "createdAt" DATE NOT NULL DEFAULT '1970-01-01 00:00:00' ,
        "id" TEXT NOT NULL  ,
        "title" TEXT NOT NULL DEFAULT '' ,
        PRIMARY KEY ("id")
    );

However the data type is given as `Int` in `Routes.js`:

    <Route path="/posts/{id:Int}" page={PostPage} name="post" />
    <Route path="/posts/{id:Int}/edit" page={EditPostPage} name="editPost" />

Other files seem right; not sure I know every file touched by generation however.

ATTEMPTED FIX

Manually changing `{id:Int}` to `{id}` in `Routes.js` -- works.

Note that `{id:String}` does NOT work, which is odd but OK.

**Comment by cannikin** [comment]
Good catch, we're on it.

**Comment by cannikin** [comment]
Fixed! Just waiting for a release...
