### ISSUE TITLE
`g auth`: Don't overwrite without asking

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#1480]
This is what my `web/package.json` file looked like
![image](https://user-images.githubusercontent.com/30793/99197013-ecb4a380-278f-11eb-80b3-fea16eecc5e1.png)

Then I ran the supabase auth generator, and without warning and without asking, this is what I ended up with
![image](https://user-images.githubusercontent.com/30793/99197109-b62b5880-2790-11eb-9805-c6084c69d872.png)

I think the generator should exit with a message telling the user to run with `--force` if the user wants the generator to overwrite existing code.

**Comment by jtoar** [comment]
Actually not sure when this was implemented but sure enough it's there: https://s.tape.sh/olE8ltw3.

**Comment by jtoar** [comment]
Implemented in https://github.com/redwoodjs/redwood/pull/2272/commits/b71cfe8f945399ff2a33c2402749ffb10723ffd4, thanks @cannikin!

**Comment by cannikin** [comment]
![image](https://media.giphy.com/media/y8fXirTJjj6E0/giphy.gif)
