### ISSUE TITLE
Two web workspaces with a shared api workspace.

### ISSUE THREAD

**Issue by viperfx** [redwoodjs/redwood#1487]
I currently have a use case with an existing redwood application where I want to share the same API project and database with two web front-ends. So I want to have two web workspaces.

The reason I need to do this is that I want to use redwood with multi-tenant portal. Where the admin is hosted at app.mydomain.com but I also want to serve a customer portal at customer1.mydomain.com, customer2.mydomain.com. These portals would share and use the same API for auth and data.

I realized that since redwood is a SPA, I won't be able to serve both portals under the same /web folder, and easily detect if the app should serve a customer portal or admin portal.

However, if I had two web projects, that shared the same API, this could solve the problem nicely. 

```
redwood project
- /admin (web)
- /customer (web)
- /api 
- netlify.toml
```

I currently use netlify to host the site. The web side is deployed as an SPA, and the API is deployed as a graphql serverless API.

**Comment by peterp** [comment]
Hey @viperfx ,

Is the customer (web) side also built in Redwood, or with some other framework?

**Comment by viperfx** [comment]
Hey @peterp 

sorry I should have clarified. My plan is to build the customer web side is also built with redwood, given I can figure out how to share the API. I think it makes sense, since I can share a good amount of code and will help with speed of development.

**Comment by viperfx** [comment]
Let me know if you need more info @peterp

**Comment by peterp** [comment]
@viperfx Unfortunately at this point it's easily doable - we have a concept called "sides," but we haven't expanded the `redwood.toml` file to introduce more than `web` or `api`

**Comment by peterp** [comment]
@viperfx If you're interested in contribution that - I could help you introduce that feature.

**Comment by viperfx** [comment]
Sure - that sounds great! Would like to contribute that. I am available on
the discord under the same name, if you need to contact me

**Comment by growms** [comment]
@viperfx hello, did you progress on that issue ?

**Comment by Tobbe** [comment]
With the introduction of React Server Components we're thinking of totally reorganizing RW projects. Possibly getting rid of workspaces altogether. We'll definitely keep this in mind (multiple web "sides"). 

@growms Thanks for creating that forum post, that's perfect. Let's keep the discussion going there instead.

The core team won't spend any time on this particular issue right now, so closing for now.
