### ISSUE TITLE
query-engine-rhel-openssl-1.0.x is opened in notepad when I create or upgrade a Redwood app

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#1489]
Whenever I run `yarn create redwood-app` or `yarn rw upgrade -t canary` Notepad is launched showing the file `query-enginge-rhel-openssl-1.0.x`, see screenshot below

![image](https://user-images.githubusercontent.com/30793/99579708-d7818400-29de-11eb-9518-9353b1df655f.png)

```terminal
tobbe@XPS9550 MINGW64 ~/dev/redwood/rwtut (main)
$ yarn rw info
yarn run v1.22.4
$ C:\Users\tobbe\dev\redwood\rwtut\node_modules\.bin\rw info

  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 14.4.0 - ~\AppData\Local\Temp\yarn--1605726641121-0.7410713023439661\node.CMD
    Yarn: 1.22.4 - ~\AppData\Local\Temp\yarn--1605726641121-0.7410713023439661\yarn.CMD
  Browsers:
    Chrome: 86.0.4240.198
    Edge: Spartan (44.19041.423.0), Chromium (86.0.622.69)
  npmPackages:
    @redwoodjs/core: ^0.20.0 => 0.20.0

Done in 3.51s.
```

```terminal
$ git --version
git version 2.29.1.windows.1
```

Doesn't seem to affect anything. It's just annoying and weird 🤔

**Comment by Tobbe** [comment]
Just happened to me again, this time when running `yarn rw db up`. So things point towards Prisma...

**Comment by peterp** [comment]
Woah, this is super strange :/

**Comment by Tobbe** [comment]
![image](https://user-images.githubusercontent.com/30793/99724282-b0e14d00-2ab3-11eb-9ea7-73ae087a40f6.png)

Ran `db up` again, and it happens at the end, when, or after, running `prisma generate`

**Comment by Tobbe** [comment]
Manually running `prisma generate` directly causes the same behavior. So maybe shouldn't really blame Redwood here...

**Comment by Tobbe** [comment]
This is one fix for the problem...
![image](https://user-images.githubusercontent.com/30793/99725294-2e598d00-2ab5-11eb-9be8-360c9d6d5561.png)

**Comment by Tobbe** [comment]
I opened an issue with Prisma as well, see if they have any ideas https://github.com/prisma/prisma/issues/4308

**Comment by Tobbe** [comment]
Now that we're back with `binaryTargets = ["native"]` this isn't an issue anymore

https://github.com/redwoodjs/create-redwood-app/blob/b51080ba5d08a4e55dce301eac0ea42b909327c3/api/db/schema.prisma#L5
