### ISSUE TITLE
Form control causes error

### ISSUE THREAD

**Issue by chris-hailstorm** [redwoodjs/redwood#150]
ENVIRONMENT

    $ yarn rw --version
    0.0.1-alpha.31

OBSERVATION

In the "Introducing Form Helpers" section of the tutorial, this code fails:

    // web/src/pages/ContactPage/ContactPage.js
    import { Form, TextField } from '@redwoodjs/web'
    import BlogLayout from 'src/layouts/BlogLayout'
    
    const ContactPage = (props) => {
      return (
        <BlogLayout>
          <Form>
            <TextField name="input" />
          </Form>
        </BlogLayout>
      )
    }
    
    export default ContactPage

Applying that code results in "Something went wrong."

Commenting out the `TextField` element -- no change, still the same error.

Commenting out the `Form` element -- page ok (without the form, obviously).

Seems there is something wrong with `Form`.

**Comment by cannikin** [comment]
We're renaming `RedwoodForm` to just `Form`. We've updated it in the tutorial but we haven't released the next alpha version of Redwood yet which actually includes that change.

**Comment by chris-hailstorm** [comment]
Confirmed that `RedwoodForm` works in 0.0.1-alpha.31, thanks.
