### ISSUE TITLE
Add disableHostCheck to config - support for WSL2 localhost to aliased host

### ISSUE THREAD

**Issue by viperfx** [redwoodjs/redwood#1511]
I have a use case where I am running my web app on WSL2 and I can access on the windows host through localhost just fine.

My application needs to be developed to expect a subdomain host to the WSL2 IP. But adding the WSL IP to the hosts file. So I can access RW via a URL like portal.rwapp.local. 

I have also set the host in the TOML file to 0.0.0.0.

I am able to access the API server, however the web app provide a page with a text saying "Invalid Host header".

Ive done some research and I need to be able to control the webpack config option called disableHostCheck - https://webpack.js.org/configuration/dev-server/#devserverdisablehostcheck

I propose this be added to the webpack config with a default of false, and so the TOML config can override with true when needed in cases like this.

PS - I am not able to develop for this scenario until this works, I am searching for other solutions but not come across any yet. If you know a workaround, please let me know.

**Comment by Tobbe** [comment]
I haven't tried myself, but maybe try `yarn rw dev --fwd="--disableHostCheck=true"`

Read more here https://github.com/redwoodjs/redwood/issues/534

**Comment by viperfx** [comment]
Works perfectly! Glad to know it's been solved already!
