### ISSUE TITLE
Documentation: Forms - Document use of SelectField

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#1517]
While SelectField was [added to the forms package](https://github.com/redwoodjs/redwood/blob/main/packages/forms/src/index.tsx#L341), it is missing documentation.

![image](https://user-images.githubusercontent.com/1051633/100351856-1bb1ed00-2fba-11eb-85f9-eef9c691fe20.png)

Needs example with validation and error handling as well.

**Comment by mbush92** [comment]
@dthyresson I have opened a draft PR #526 to address this missing documentation.  Can you please review and let me know if anything needs to be expanded on in the explanation or any other changes.

**Comment by thedavidprice** [comment]
Thanks @mbush92 🚀

Assigned this to you and looped in @dthyresson for review on https://github.com/redwoodjs/redwoodjs.com/pull/526

**Comment by dthyresson** [comment]
One tiny wording change and we'll merge. The docs were excellent.

**Comment by dthyresson** [comment]
Approved and merged redwoodjs/redwoodjs.com#526
