### ISSUE TITLE
CLI - Browser Open Command - Localhost default 

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#1518]
From a discussion thread on Discord:

> I've been developing react projects on a VPS on DO for awhile , and i'm used to when I preview the project the address in browser being `<serverIP> + <project specfiiedPort>`
>
> So how can I be writing code on a VPS, but when I view my rw project it goes to localhost?!

The developer [configured the web host](https://github.com/redwoodjs/redwood/blob/53349fd121f9198a8fdb5c0217cec8c4f8b6badd/packages/core/config/webpack.development.js#L19) and port in redwood.toml:

```
    host: redwoodConfig.web.host || 'localhost',
    port: redwoodConfig.web.port,
```

https://github.com/redwoodjs/redwood/blob/53349fd121f9198a8fdb5c0217cec8c4f8b6badd/packages/core/config/webpack.development.js#L19

But when using the `open` command or `dev` with browser open set to true, it tries to open the port on `localhost` not the host specified possibly due to:

```
execa(`open http://localhost:${getConfig().web.port}`, { shell: true })
```

https://github.com/redwoodjs/redwood/blob/53349fd121f9198a8fdb5c0217cec8c4f8b6badd/packages/cli/src/commands/open.js#L16

Should this respect the `host` config instead?

**Comment by saideepesh000** [comment]
Hey @dthyresson, @peterp, could you be more clear on what should be done, I might have a look into it.

**Comment by dthyresson** [comment]
@saideepesh000 The issue stemps from a report in the RedwoodJS [Discord Community](https://discord.com/invite/jjSYEQd):

![image](https://user-images.githubusercontent.com/1051633/110951224-d1f3d500-8312-11eb-9951-626ff76f8ce8.png)

And specifically this user was installing RW on Digital Ocean using a Virtual Private Server (VPS) -- something a little more advanced (and manual self-hosting) than the typical deploys to Netlify or Vercel.


He reports that

> when using the open command or dev with browser open set to true, it tries to open the port on localhost not the host specified

I imagine he wanted it to open to the host on DO.

As I do not use Digital Ocean or a VPS, I am not sure how to replicate or test this issue unfortunately -- but it one does configure RW in the fashion above, it looked like the open command had a hardcoded `localhost`.

But we'd need an installation to test this change

**Comment by thedavidprice** [comment]
I don't believe this is an issue any longer as the developer could forward options to the rw dev command (which is using Webpack Dev Server behind the scenes): https://redwoodjs.com/docs/webpack-configuration#pass-settings-with-forward

Any way to pass this information along? Assuming it's resolved since it's been many months now.

**Comment by jtoar** [comment]
Based on @thedavidprice's comment, this one seems ok to close.
