### ISSUE TITLE
Documentation - Forms - dataType deprecated in favor of transformValue

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#1531]
While searching a Discourse support question about how to handle SelectField integer value, it was noted that one should use `transformValue`.

However, the documentation still says to [use `dataType`](https://redwoodjs.com/docs/form#datatype):

https://redwoodjs.com/docs/form#datatype

> If the type to coerce the input to can’t be inferred automatically, like making a Float from a <TextField> for example, you can explicitly set the InputField's dataType attribute to Boolean, Float, Int, or Json.

> In the future, we'll let you pass a function to this attribute so you can do the coercion however you want.

I think that the `transformValue` may refer to this future case as the code warns that `dataType` is deprecated:

>  'Using the "dataType" prop on form input fields is deprecated. Use "transformValue" instead.'

https://github.com/redwoodjs/redwood/blob/6cf2a9a38c73dbf82d7ec1c75479eec3f7234143/packages/forms/src/index.tsx#L435

Need to update documentation -- and also include this on the missing SelectField Issue https://github.com/redwoodjs/redwood/issues/1517

**Comment by Tobbe** [comment]
Fixed by https://github.com/redwoodjs/redwoodjs.com/pull/488
