### ISSUE TITLE
useMutation options info is lost with new BYO gql client implementation

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#1532]
Before (this is from v0.20.0):

![image](https://user-images.githubusercontent.com/30793/100553803-6076a600-3290-11eb-9fcc-e7f95eda359c.png)

![image](https://user-images.githubusercontent.com/30793/100553805-68364a80-3290-11eb-8633-4691aa491e0d.png)

Now (this is from v0.21.1-canary.9):

![image](https://user-images.githubusercontent.com/30793/100553679-6d46ca00-328f-11eb-830b-455dc28f85b5.png)

![image](https://user-images.githubusercontent.com/30793/100553894-2a85f180-3291-11eb-8b96-395fafdff2c9.png)

As you can see from the screenshots above, intellisense for `useMutation` shows `variables` as only option available now, whereas before it showed all available options. Which means VS Code won't autocomplete things like `awaitRefe...` for you.

**Comment by Tobbe** [comment]
If I make it a `.tsx` file it's even worse. Then it won't even compile

![image](https://user-images.githubusercontent.com/30793/100555256-7ee19f00-329a-11eb-9356-8f0eca15a4aa.png)

**Comment by jtoar** [comment]
This might be closed by #2485.
