### ISSUE TITLE
Use GHActions to Auto Publish to NPM and Update Dependencies accordingly...

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#155]
...and potentially sync with publishing `redwoodjs/create-redwood-app` releases based on dependencies.

Conceptually I know this is possible. Don't really have the details as of yet but wanted to test the waters.

**Comment by thedavidprice** [comment]
Also, pros/cons to also publishing to GH Packages... ?

**Comment by peterp** [comment]
Without understanding what changes a pull-request has made it's very difficult to figure out semver properly.

**Comment by thedavidprice** [comment]
Roger that and agreed. I think in the case where projects use branches named with the corresponding release (to manage milestones), something like auto-publishing could be possible. Too much process for us where we are at today, though, to consider something equivalent.

In the future, we could add a GHAction that opens PRs across repos where the packages need to be upgraded (e.g. Example Apps and mostly Create Redwood App). But I'm just thinking out loud here.

Closing this for now 'cause not a near-term priority.
