### ISSUE TITLE
Netlify is not configured to be able use netlify dev --live to host the dev site on a publicly available tunneled url

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#1554]
The current `deploy netlify` generator creates a `netlify.toml` for use with [netlify dev](https://www.netlify.com/products/dev/) but it lacks the configuration to work with `--live` that can host the dev site on a publicly available tunneled url to be used to preview features for feedback,. etc.

Needs the following settings:

```
[dev]
  command = "yarn rw dev"
  framework = "#custom"
  targetPort = 8910 # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on
```

**Comment by jtoar** [comment]
Closing this one out in favor of #1831; it's more recent and these are the same thing (I think—please reopen if I'm mistaken!)
