### ISSUE TITLE
`yarn rw setup tailwind` depends on `mv`, which isn't always available

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#1557]
Depending on what options you pick when installing git on windows you might not have `mv` available in PowerShell or Cmd. 

See more here https://community.redwoodjs.com/t/tailwind-setup-on-windows/1557

A few ideas on how to handle this:
 * Document somewhere that on RW only supports running in a GitBash env or WSL when on Windows
 * Detect that mv isn't available when running the tailwind setup command and suggest trying in GitBash or WSL if os == Windows
 * Use something instead of `mv` that is available

**Comment by peterp** [comment]
Lame, we should change this:
https://github.com/redwoodjs/redwood/blob/6b7f58d7c96d3338e2f324b776c5222c8a4192d5/packages%2Fcli%2Fsrc%2Fcommands%2Fsetup%2Ftailwind%2Ftailwind.js#L160

to just use `fs.renameSync`
