### ISSUE TITLE
Logging v1 Experience: Status, Objectives, Decisions

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#1578]
### Objectives and Considerations

* API side only
* Want to use/overrride `console` to be backward compatible and no need to refactor existing. Plus, developers are accustomed to it and will reduce risk of mixing a `console.info` that does one thing and a `logger.info` that does another (Edit: probably not going to override)
* Support transports to log to a destination like LogFlare
* Support file system logging **in dev only**
* Logging should (or have option to) log to multiple destinations and outputs. For example, log to std out for Netlify functions logging but also to Logflare with appropriate formats
* API dev server output to format log NDJSON log statements "prettified"
* Support redaction (tokens, pwds, emails, etc)

### Proposed Implementation

* Create a `api/lib/logger.ts` just as is done with Prisma
* Uses/overrides console
* Wrapper any logger that also supports log, info, warn, error etc
* [pino](https://github.com/pinojs/pino) is the pragmatic, sensible default
* added via a `setup` generator
* generator also can configure [pino with logflare](https://github.com/Logflare/pino-logflare) via `--logflare`
* generator can also setup [Prisma logging](https://www.prisma.io/docs/concepts/components/prisma-client/logging) to modify `db.js` to add 

```
const db = new PrismaClient({
  log: ['query', 'info', 'warn'],
})
```

* generator has option to setup dev file system logging in `logs/*` and add to gitignore, etc.

* [pino-colada](https://github.com/lrlna/pino-colada) added as an api dev dependency to prettify pino filesystem logging in dev

### Decisions to Make

* Create an interface similar to AuthProvider? Allow people to choose? Or go with Pino. I favor go with pino.
* Should override console or just ask developers to now use `logger.info()`
* pino can setup multiple destinations with different formatters. can do stdout (pino format), stdout (like normal console message), logflare destination etc.

### Questions

* Reach out to the pino team to see if an integration as a web framework makes sense? https://github.com/pinojs/pino/blob/master/docs/web.md
* Can [pino's browser feature](https://github.com/pinojs/pino/blob/master/docs/browser.md) support sending dev-only api log statements to the browser console (as requested [here](https://community.redwoodjs.com/t/where-is-the-server-side-api-console-output-or-log/485/6)) and references in [Issue 509](https://github.com/redwoodjs/redwood/issues/509)?

### Concerns

* [Vercel has a LogFlare](https://vercel.com/integrations/logflare) so may not be needed for that deployment target. 

### Other ideas

* Putting logger in the GraphQL context. Great, but how use it to functions when not using a service. So, no.

Get listed on LogFlare as:

![image](https://user-images.githubusercontent.com/1051633/101937387-cb3cb100-3baf-11eb-8b13-44b99c9c80f4.png)

**Comment by dthyresson** [comment]
@dac09 Let's pick this topic up again!

**Comment by thedavidprice** [comment]
![UqZ4imFIoljlr5O2sM](https://user-images.githubusercontent.com/2951/109851005-ff040180-7c07-11eb-881b-c3befac48fc0.gif)
