### ISSUE TITLE
The <Link> component increases the length of window.history when path doesn't change

### ISSUE THREAD

**Issue by phillipkregg** [redwoodjs/redwood#1584]
For example, in the tutorial, when you create an About page link like this:

`<Link to={routes.about()}>About</Link>`

![image](https://user-images.githubusercontent.com/1066044/102446553-b3bc5880-3ff3-11eb-98ee-9f344106893b.png)

Then clicking "About" 10 times, you would have to click the back button 11 times to actually go back to the previous page.

It seems like there should be an additional check to only increase the history if the actual path changes.

**Comment by Tobbe** [comment]
@phillipkregg Thanks for the issue report. I think this is actually a pretty common behaviour. At work (not a RW project) we've worked around it by doing this

```
export function useSafeNavigation() {
  const history = useHistory();

  return useCallback(
    (routeObj: string | LocationDescriptorObject) => {
      if (
        typeof routeObj === "string" &&
        routeObj !== history.location.pathname
      ) {
        history.push(routeObj);
      } else if (
        typeof routeObj === "object" &&
        routeObj.pathname &&
        routeObj.pathname !== history.location.pathname
      ) {
        history.push(routeObj);
      }
    },
    [history]
  );
}
```

That's only for when you navigate using JS code, but something similar could be implemented for a `<Link>` component.

**Comment by phillipkregg** [comment]
Ok thanks for the workaround.   Just wanted to make sure this wasn't a bug.

**Comment by phillipkregg** [comment]
Just as a note, I tried this same behavior with the <Link> component within Next.js and it doesn't increase the length of window history as you click.  If you click a link multiple times, and the link points to the current route, you only have to click the browser's back button once to go back to the previous page.

**Comment by thedavidprice** [comment]
Agreed this should be our default behavior for the Router (unless there are use-cases, requirements otherwise I'm not aware of). As is, this seems annoying at best.

Added to the Project Board for v1 release. Needs more discussion.
