### ISSUE TITLE
yarn rw setup i18n fails 

### ISSUE THREAD

**Issue by dekc** [redwoodjs/redwood#1590]
Running the cli command `yarn rw setup i18n` fails at the "Adding locale file for 'site' namespace" step with the error: `The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined`

Issue is you are missing the "contents" argument to your library packages/cli/src/commands/setup/i18n/i18n.js:  `writeFile()` method ( a wrapper to Node's `fs.writeFileSync()` which expects a contents arg). I assume your intention was to simply create an emtpy site.json file and in that case try: 

`const fd = fs.openSync(<filePath>, 'w')`

- the "w" flag makes sure the file is created if not existing, and if the file exists it overwrites it with a new file, overriding its content.
- use the "a" flag to avoid overwriting. The file is still created if not existing. 

Cheers.

**Comment by jvanbaarsen** [comment]
@dekc Could you try this again on the latest version? If it is still not working, can you then tell a bit more about your setup? Or maybe create a sample repo where this is demonstrated?

I ran this against a test project and it seem to have worked for me.

**Comment by thedavidprice** [comment]
Thanks @dekc for reporting this! Per @jvanbaarsen's request, could you run `yarn rw info` in your project and then copy+paste the output?

**Comment by thedavidprice** [comment]
Confirming this 🐛 running `v0.25.2-canary.20`:
```bash
$ yarn rw setup i18n          
yarn run v1.22.10
$ /Users/price/Repos/xx-delete/node_modules/.bin/redwood setup i18n
  ✔ Installing packages...
  ✔ Configuring i18n...
  ✖ Adding locale file for 'site' namespace
    → The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    Adding import to index.js...
    One more thing...
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
