### ISSUE TITLE
How to deploy on a self managed server?

### ISSUE THREAD

**Issue by xrd** [redwoodjs/redwood#1593]
I read the documentation on deployment. I don't see instructions on deploying on my own server. Should I consider a derivative of the netlify or other deployment options? 

I don't see a `yarn serve` command in the `package.json` which I assumed I would find to at least start a simple server. And didn't find an equivalent command in the list produced from `yarn rw`.

I know this is a question with many different moving pieces and constrains, but is there at least a best practice for the simplest case? I'm not looking for the final solution, just the quickest solution for running all the pieces (and building the right front end components, etc.)

Or, perhaps an example where you could deploy inside a docker container?

**Comment by xrd** [comment]
To my, redwoods reminds me of Rails. I know I could put an nginx proxy in front of http://localhost:8910. But I would like to know the equivalent of running `RAILS_ENV=production rails s` where the development environment isn't used, without the expectations of hot reloading, etc.

**Comment by pixelkritzel** [comment]
https://redwoodjs.com/cookbook/self-hosting-redwood

**Comment by peterp** [comment]
Thanks @pixelkritzel , @xrd does this seem reasonable or are you looking for an even higher level of abstraction?

**Comment by xrd** [comment]
This is great. I'm not sure how I missed it. Thanks to you both.
