### ISSUE TITLE
Storybook: Add a way to define a custom Provider and configuration

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#1595]
We should allow the users to define a `storybook.preview.js` configuration file. This would allow people to add additional decorators.

- [x] Add `storybookPreviewConfig` path to `getPaths()`, it should be a `web/config/storybook.preview.js` file.
- [x] Import that over here: https://github.com/redwoodjs/redwood/blob/e598a5116ba53785dae0a80fd9820b9ae5fa24d1/packages/core/config/storybook/preview.js#L10-L11
- [x] Make sure that it's optional and that a user is able to define a new decorator.
- [ ] Document this feature.

**Comment by viveksonar** [comment]
Hello Im new to opensource and would love to contribute/fix this issue.
Can I take this.

**Comment by viveksonar** [comment]
Hello is this issue still open.
New to open source and would love to contribute to this.

**Comment by peterp** [comment]
Hi @viveksonar, it is indeed! 

I would love to have you contribute it, hit me up on discord if you need any help

**Comment by viveksonar** [comment]
Can i get the discord invite or the link
Im pretty lost.

**Comment by jangxyz** [comment]
Hi, any updates?

I've noticed that storybook has upgraded to v6, so I wonder whether redwood should support v6 out of the box. I left a topic in the [forum](https://community.redwoodjs.com/t/upgrading-storybook-to-v6/1914).

**Comment by viveksonar** [comment]
Hey Peter I tried to do it but I couldn't make it .
I'm new to react and still learning for now I will opt out of this issue
may be in future after I have decent knowledge I will go through other
issues.

Sorry

Best,
Peter

**Comment by thedavidprice** [comment]
I believe this is now resolved via https://github.com/redwoodjs/redwood/pull/2054 which will be included in v0.28

@peterp correct?

**Comment by peterp** [comment]
Yup, this is resolved!

**Comment by peterp** [comment]
Resolved by #2054
