### ISSUE TITLE
Prisma `findOne` Deprecation requires updating Scaffold Generator

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1612]
@cannikin 

Redwood v0.22 is upgraded to Prisma v2.12.1:
- https://github.com/prisma/prisma/releases/tag/2.12.0
- Rename `findOne` to `findUnique`

Generators will need to be updated accordingly.

NOTE: Prisma now included a Code Mod command. We can instruct users to run the code mod in the future to fix issue in their project.

_In Screenshot below, disregard the Jest test failure. Just using this to show Prisma warning and code._
<img width="730" alt="Screen Shot 2021-01-07 at 10 27 35 AM" src="https://user-images.githubusercontent.com/2951/103930022-f7761f80-50d2-11eb-8c5e-08960f7fff35.png">

**Comment by cannikin** [comment]
The scaffold generator uses `findOne()` in the generated service, we gotta update that!

**Comment by cannikin** [comment]
@96RadhikaJadhav Want to take this one? This one actually generates the code that the other issue is documenting. This one's more awesome anyway. 😉

**Comment by Darth-Knoppix** [comment]
Just a heads up, the scaffold generator also changes the top level exports of `@prisma/client` so input types are now under Prisma namespace.

## From the Prisma release notes

Before
```ts
import { PrismaClient, User, UserCreateInput } from '@prisma/client'

async function createUser(input: UserCreateInput): Promise<User> {
  return prisma.user.create(input)
}
```

After
```ts
import { PrismaClient, User, Prisma } from '@prisma/client'

async function createUser(input: Prisma.UserCreateInput): Promise<User> {
  return prisma.user.create(input)
}
```
