### ISSUE TITLE
ReactFilestack crashes the page

### ISSUE THREAD

**Issue by ofu997** [redwoodjs/redwood#1622]
While following the[ file upload](https://redwoodjs.com/cookbook/file-uploads) recipe, I the ImageForm page crashes on importing and using ReactFilestack. React inspector suggests it's a FatalErrorBoundary, while dev inspector gives me this output: 'index.js:1 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.'

**Comment by Tobbe** [comment]
Sorry to hear you're having problems with the recipe @ofu997. Do you have a link to a GitHub repo we can look at? Or if you could post some code that reproduces the error. Thanks.

**Comment by forresthayes** [comment]
I think we might need to update the [recipe](https://github.com/redwoodjs/redwoodjs.com/blob/main/cookbook/File_Upload.md) to use the [latest filestack-react release](https://github.com/filestack/filestack-react#migration-from-3xx-and-4xx):

```javascript
<PickerInline apikey='YOUR_APIKEY'/>
``` 

@ofu997, would you be interested to make a PR?

**Comment by ofu997** [comment]
> I think we might need to update the [recipe](https://github.com/redwoodjs/redwoodjs.com/blob/main/cookbook/File_Upload.md) to use the [latest filestack-react release](https://github.com/filestack/filestack-react#migration-from-3xx-and-4xx):
> 
> ```js
> <PickerInline apikey='YOUR_APIKEY'/>
> ```
> 
> @ofu997, would you be interested to make a PR?

**Comment by ofu997** [comment]
@forresthayes PickerInline works. How would I make a PR?

**Comment by forresthayes** [comment]
cool, I'm glad that worked. If you'd like to update the File Upload recipe, the cookbook source files are in the [redwoodjs.com repo](https://github.com/redwoodjs/redwoodjs.com). The ['readme'](https://github.com/redwoodjs/redwoodjs.com#redwoodjscom) has instructions for getting set up and the File Upload recipe is `redwoodjs.com/cookbook/File_Upload.md`
<br>
If you haven't already, you're welcome to join the [Redwood Community Forum](https://community.redwoodjs.com/) and [Discord Chat](https://discord.com/invite/jjSYEQd). Lots of folks there are happy to help with questions about contributing or whatever!
