### ISSUE TITLE
resolve test package dependency duplicates

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1631]
@peterp @Tobbe _moving conversation here from [#1625/comment](https://github.com/redwoodjs/redwood/pull/1625#issuecomment-758837173)_

Outstanding Questions:
> If whatwg-fetch should be removed, should we remove the other packages too? Or should whatwg-fetch only be in this top level package.json, but moved to dependencies? The top level package.json doesn't have any other deps, only devDeps. @peterp What do you think?

----
## Original comment

@thedavidprice I noticed that too. I did dig in to it a little bit. It was added to that file by @peterp in this commit
```
commit da6ebb41bb02d5eaf43495726fcea0ce46397e34
Author: Peter Pistorius <peter.pistorius@gmail.com>
Date:   Sun Jun 14 14:31:26 2020 +0200

    Move testing things to global package.
```

```diff
diff --git a/package.json b/package.json
index 5dbbb66b..22d0ec86 100644
--- a/package.json
+++ b/package.json
@@ -16,11 +16,16 @@
     "@babel/runtime-corejs3": "^7.9.2",
     "babel-plugin-auto-import": "^1.0.5",
     "babel-plugin-module-resolver": "^4.0.0",
+    "bundlesize": "^0.18.0",
     "cross-env": "^7.0.2",
     "jest": "^25.2.3",
     "lerna": "^3.20.2",
     "nodemon": "^2.0.2",
-    "typescript": "^3.8.3"
+    "typescript": "^3.8.3",
+    "@testing-library/react": "10.2.1",
+    "@testing-library/jest-dom": "5.10.0",
+    "msw": "0.19.3",
+    "whatwg-fetch": "3.0.0"
   },
   "eslintConfig": {
     "extends": "@redwoodjs/eslint-config",
@@ -43,4 +48,4 @@
     "lint": "yarn eslint packages",
     "lint:fix": "yarn eslint --fix packages"
   }
-}
+}
\ No newline at end of file
```

If whatwg-fetch should be removed, should we remove the other packages too? Or should whatwg-fetch only be in this top level package.json, but moved to `dependencies`? The top level package.json doesn't have any other deps, only devDeps. @peterp What do you think?

_Originally posted by @Tobbe in https://github.com/redwoodjs/redwood/issues/1625#issuecomment-758837173_

**Comment by jtoar** [comment]
Seems similar to https://github.com/redwoodjs/redwood/issues/452.

**Comment by Josh-Walker-GM** [comment]
`whatwg-fetch` is currently only found in:
https://github.com/redwoodjs/redwood/blob/1f51e1e317416854ac0fd9987e1470ba986a0d29/packages/testing/package.json#L56
