### ISSUE TITLE
Web Tests error in v0.22.1

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1633]
@peterp 

Web tests are failing due to an import error. I found this preparing for v0.23 and traced it back to v0.22. Possible the issue came from https://github.com/redwoodjs/redwood/pull/1465 I tried to diagnose but got stuck.
 
<img width="812" alt="Screen Shot 2021-01-12 at 4 57 31 PM" src="https://user-images.githubusercontent.com/2951/104392604-44a12980-54f7-11eb-9735-f7129c4c2bca.png">

```console
Cannot find module '@redwoodjs/router/dist/index' from '../node_modules/@redwoodjs/testing/dist/MockRouter.js'

    Require stack:
      /Users/price/Repos/xx-delete/node_modules/@redwoodjs/testing/dist/MockRouter.js
      src/Routes.js
      /Users/price/Repos/xx-delete/node_modules/@redwoodjs/testing/dist/MockProviders.js
      /Users/price/Repos/xx-delete/node_modules/@redwoodjs/testing/dist/customRender.js
      /Users/price/Repos/xx-delete/node_modules/@redwoodjs/testing/dist/index.js
      /Users/price/Repos/xx-delete/node_modules/@redwoodjs/core/dist/configs/browser/jest.setup.js

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/@redwoodjs/testing/dist/MockRouter.js:31:14)
```

**Comment by peterp** [comment]
This is fixed over here: https://github.com/redwoodjs/create-redwood-app/commit/11780ed5608016079fe3f22c92f42f713cad86a9
