### ISSUE TITLE
[core] Storybook config bug

### ISSUE THREAD

**Issue by pi0neerpat** [redwoodjs/redwood#1642]
redwood v0.23.0

When running `yarn rw storybook` Getting unexpected token '.' here
https://github.com/redwoodjs/redwood/blob/d4271793befb029357f39ac8b0e9126611023b59/packages/core/config/storybook/main.js#L13

Its fixed by removing the "?". Weird maybe webpack doesn't like fancy javascript in its config?

UPDATE: just confirmed this does affect a fresh yarn create project

**Comment by thedavidprice** [comment]
Thanks @pi0neerpat! Possible you'd be available to initiate a PR to fix this (while still handling the possible Null case)?

**Comment by Tobbe** [comment]
> Weird maybe webpack doesn't like fancy javascript in its config?

Seems like you're right. Found this webpack issue https://github.com/webpack/webpack/issues/10227
Basically webpack 4 (which is what we're using) will never get optional chaining support. Webpack 5 already has it.

**Comment by thedavidprice** [comment]
@Tobbe is this where the Issue thread takes a hard right turn and becomes a discussion about when/if we're going to upgrade Webpack? 

😆

**Comment by Tobbe** [comment]
> @Tobbe is this where the Issue thread takes a hard right turn and becomes a discussion about when/if we're going to upgrade Webpack?
> 
> 😆

Haha. I've already been down that path with @peterp regarding another thing I'm working on. Too bad people are reporting double build times when switching from wp4 to 5 🙁
