### ISSUE TITLE
Service / SDL generation is broken when using relations

### ISSUE THREAD

**Issue by jvanbaarsen** [redwoodjs/redwood#1649]
I'm noticing when you have a relation column that has a different name then the Table it is referring to you get an error like this:
```
  ✖ Generating SDL files...
    → No schema definition found for `Author` in schema.prisma file
No schema definition found for `Author` in schema.prisma file
```

This happens when you for example have two tables, Post and User, and you name the user relation different on Post like this:

```
model Post {
  id       Int    @id @default(autoincrement())
  title    String
  author   User   @relation(fields: [authorId], references: [id])
  authorId Int
}

model User {
  id    Int    @id @default(autoincrement())
  posts Post[]
}
```

To make it easier to reproduce you can use this repo/branch: https://github.com/jvanbaarsen/rw-examples

It happens when you run: `yarn rw g sdl post`

**Comment by thedavidprice** [comment]
Thanks @jvanbaarsen! Looping in @cannikin

**Comment by cannikin** [comment]
Looks like we'll need to do more introspection when generating the field names and/or GraphQL types.

**Comment by brentjanderson** [comment]
I've run into the same issue. Oddly, I can get it to work in some circumstances but not in othes:


## This does not work
```
model ThingOne {
  id   String @id @default(uuid())
  name String // Why is this needed?

  oneReferencesOnThingTwo      ThingTwo[] @relation("OneReferenceOnThingTwo")
  anotherReferencessOnThingTwo ThingTwo[] @relation("AnotherReferenceOnThingTwo")
}

model ThingTwo {
  id String @id @default(uuid())

  oneReferenceToThingOne       ThingOne  @relation("OneReferenceOnThingTwo", fields: [oneReferenceToThingOneId], references: [id])
  oneReferenceToThingOneId     String
  anotherReferenceToThingOne   ThingOne? @relation("AnotherReferenceOnThingTwo", fields: [anotherReferenceToThingOneId], references: [id])
  anotherReferenceToThingOneId String?
}
```

## This does work

```
model ThingOne {
  id   String @id @default(uuid())
  name String // Why is this needed?

  oneReferencesOnThingTwo      ThingTwo[] @relation("OneReferenceOnThingTwo")
  anotherReferencessOnThingTwo ThingTwo[] @relation("AnotherReferenceOnThingTwo")
}

model ThingTwo {
  id String @id @default(uuid())

  thingOne          ThingOne  @relation("OneReferenceOnThingTwo", fields: [thingOneId], references: [id])
  thingOneId        String
  anotherThingOne   ThingOne? @relation("AnotherReferenceOnThingTwo", fields: [anotherThingOneId], references: [id])
  anotherThingOneId String?
}
```

The diff, if it helps:
```diff
model ThingOne {
  id   String @id @default(uuid())
  name String // Why is this needed?

  oneReferencesOnThingTwo      ThingTwo[] @relation("OneReferenceOnThingTwo")
  anotherReferencessOnThingTwo ThingTwo[] @relation("AnotherReferenceOnThingTwo")
}

model ThingTwo {
  id String @id @default(uuid())

-  oneReferenceToThingOne       ThingOne  @relation("OneReferenceOnThingTwo", fields: [oneReferenceToThingOneId], references: [id])
+  thingOne                     ThingOne  @relation("OneReferenceOnThingTwo", fields: [thingOneId], references: [id])
-  oneReferenceToThingOneId     String
+  thingOneId        String
-  anotherReferenceToThingOne   ThingOne? @relation("AnotherReferenceOnThingTwo", fields: [anotherReferenceToThingOneId], references: [id])
+  anotherThingOne   ThingOne? @relation("AnotherReferenceOnThingTwo", fields: [anotherThingOneId], references: [id])
-  anotherReferenceToThingOneId String?
+  anotherThingOneId String?
}
```

[I've put up a repo demoing this issue](https://github.com/brentjanderson/rw-multi-column-error/). I've tagged the commit where it does not work as `broken` and the commit where it does work as `works`. The way to test it:

`git checkout broken && yarn rw g sdl -f ThingTwo` should give you an error:

```terminal
No schema definition found for `OneReferenceToThingOne` in schema.prisma file
```

I don't know what significance there is in the difference between each model. But it's weird that one works, the other doesn't, and unless I'm staring past it the only thing that has changed is the name of the fields?

**Comment by cannikin** [comment]
You're on the latest version of Redwood, right @brentjanderson? 0.25.1?

**Comment by brentjanderson** [comment]
> You're on the latest version of Redwood, right @brentjanderson? 0.25.1?

That's correct. The linked repo demoing the issue was minted with the latest version of Redwood today.

**Comment by cannikin** [comment]
HMMMM

The error is coming from here: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/lib/index.js#L35-L64 But the code that calls that is this line I'm guessing: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/sdl/sdl.js#L112 Which specifically tries to look it up by `field.type`, which would be `User`, which is correct. hmmmmmmmmm
