### ISSUE TITLE
Generating components/cells does not update Storybook 

### ISSUE THREAD

**Issue by KrisCoulson** [redwoodjs/redwood#1650]
When browsing through tutorial part 2 it is mentioned twice that storybook will automatically refresh with the generated components.

> Storybook should refresh and our "Generated" Comment story will be ready to go:
> Storybook updates with a new CommentsCell under the Cells folder

This is not the case, storybook does rebuild according to the console but does not actually refresh with the generated components. The only way is to kill storybook and reload.

Captured this gif as to what I am seeing
![2021-01-15 23 06 57](https://user-images.githubusercontent.com/6943688/104805755-39642d00-5787-11eb-8ae9-4cd5e0e8c363.gif)

**Comment by thedavidprice** [comment]
@peterp thoughts on this one?

**Comment by jtoar** [comment]
Storybook now updates:

https://user-images.githubusercontent.com/32992335/145751246-104a8f22-0314-4f62-94b9-9b9e4472c366.mp4

**Comment by KrisCoulson** [comment]
🔥
