### ISSUE TITLE
Auth token is not properly verified for supabase or Netlify in production

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#1652]
In `decoders/supabase.ts` we have this

```
  if (process.env.NODE_ENV === 'production') {
    if (!process.env.SUPABASE_JWT_SECRET) {
      throw new Error('`SUPABASE_JWT_SECRET` env var is not set.')
    }
```

I have **not** set that env var, so I would expect to see that error, but I don't.

![image](https://user-images.githubusercontent.com/30793/104853332-6c7dfc00-5900-11eb-8c1a-b515ad172d76.png)

I'm logging NODE_ENV in getCurrentUser, and this is what it prints

![image](https://user-images.githubusercontent.com/30793/104853341-7ef83580-5900-11eb-9e73-677723359b0f.png)

I tried manually setting NODE_ENV, but then I get this error

![image](https://user-images.githubusercontent.com/30793/104853354-90414200-5900-11eb-9d31-98237b52c7a6.png)

So `NODE_ENV` is not set, and setting it breaks the build.

What all this means is that both Supabase and Netlify auth will just run `jwt.decode(token)`, which decodes the token without first verifying it. (The proper call for Supabase is `jwt.verify(token, secret)`)

**Comment by thedavidprice** [comment]
Woah, great catch @Tobbe!
