### ISSUE TITLE
Add E2E Integration tests to CI

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1658]
dependent on https://github.com/redwoodjs/redwood/pull/1637

Ideally, the CI (via GitHub actions) will do the following:
- Trigger on PR merge (note: also possible to use PR Packages and therefore trigger each PR update, although I'm not sure this is necessary)
- Using the published canary versions, _including the canary for create-redwood-app package_, run our Cypress test script ([here](https://github.com/redwoodjs/redwood/blob/main/tasks/test-tutorial), with files in `e2e/` directory). Instructions can be found in [Contributing.md](https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md#integration-tests)
- To figure out --> how to message/notify on success or failure? If this is run outside the PR, where will the alerts show up?

**Comment by Tobbe** [comment]
> * Trigger on PR merge (note: also possible to use PR Packages and therefore trigger each PR update, although I'm not sure this is necessary)

I came here from #1637 to suggest exactly this, but of course you had already thought about it 🙂 I think it's worth it, running on PR updates. Should help ensure we have a stable main branch. Not saying it has been a problem so far, but it will help it stay that way going forward. Would also help with your last point. Blocking merge on failing tests.

**Comment by thedavidprice** [comment]
We'll just chalk it up to "great minds think alike", right? 😆

Totally game to try on PR updates/commits and see how it works!

**Comment by thedavidprice** [comment]
Closing in favor of https://github.com/redwoodjs/redwood/issues/1886
