### ISSUE TITLE
Upgrade Command should run from root regardless of current directory

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1659]
If a user runs `yarn rw upgrade ...` from a directory other than project root, there are cases where the root `package.json` is not handled correctly by yarn ('cause yarn is a mess when it comes to this command).

We need to ensure Execa has cwd set whenever it is called:
https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/upgrade.js

**Comment by jeliasson** [comment]
@thedavidprice 👋
To which path do we want to `cwd` to, and is there any specific case/command you think of?

```js
// traverses from ./node_modules/@redwoodjs/cli/dist/commands
const example1 = path.resolve(__dirname, '../../../../../')

// traverses from ./api (for some reason?)
const example2 = path.resolve(process.cwd(), '..') 
```
Both examples resolves to the root of the project.

**Comment by thedavidprice** [comment]
Check out the helpers here!
https://github.com/redwoodjs/redwood/blob/main/packages/internal/src/paths.ts

**Comment by Aditya-1804078** [comment]
I am new to open source community, can you please assign this issue to me?? Working on this issue would be a start for me.

**Comment by jeliasson** [comment]
@Aditya-1804078 
I'm sure you'll have @thedavidprice blessing, so go for it. Let us know if you'd need any help to get started, and welcome to the open source community! 😊

**Comment by thedavidprice** [comment]
Indeed! Thanks for jumping in here @Aditya-1804078 

**Getting Started with Contributing Docs**
- https://redwoodjs.com/docs/contributing
- CLI Package: https://github.com/redwoodjs/redwood/blob/main/packages/cli/README.md

**Code Reference**
- Command to update: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/upgrade.js
- Take a look at how setting working directory is handled here: https://github.com/redwoodjs/redwood/blob/2f44c51217eca65f4e2ca8c2679a50918ff62deb/packages/cli/src/commands/setup/tailwind/tailwind.js#L146

**Comment by qooqu** [comment]
hi all - just submitted a pr

https://github.com/redwoodjs/redwood/pull/2081

**Comment by thedavidprice** [comment]
and merged!
