### ISSUE TITLE
Upgrade webpack v4 to v5

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#1667]
Previously we were blocked by the fact that Storybook was on Webpack 4, but they've already upgraded to Webpack 5.

Here are the docs for upgrading: https://webpack.js.org/migrate/5/

**Comment by peterp** [comment]
It looks like Storybook does not support Webpack 5: https://github.com/storybookjs/storybook/pull/13392 :/

**Comment by Tobbe** [comment]
We use `chalk` a lot. Would this be an issue for us as well? https://github.com/facebook/create-react-app/pull/10198

**Comment by Tobbe** [comment]
Storybook Wp5 support:
![image](https://user-images.githubusercontent.com/30793/107099091-14585c80-6811-11eb-8aa8-f82fefec7f44.png)

**Comment by thedavidprice** [comment]
Now that we've upgraded to Storybook v6, which is using Webpack v5, when should we prioritize upgrading to Webpack v5 @peterp?

**Comment by dthyresson** [comment]
@jtoar Will an upgrade to Webpack v5 be needed if upgrading to PostCss 8? See: https://github.com/redwoodjs/redwood/issues/2123
