### ISSUE TITLE
Browser does not automatically reload after generating HomePage

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#167]
In the tutorial we have the user sitting on the "Welcome to Redwood" page at `/`. We then generate the homepage at "/" and say the browser will automatically reload to show them, but it doesn't. Reloading manually got it to show.

This might have something to do with only watching existing files for changes, instead of new files being created?

**Comment by thedavidprice** [comment]
@cannikin I just tested and this is working fine for me. Using latest master for both RWJS and CRA. Tested on Chrome.

`yarn rw dev` auto opens page
`yarn redwood generate page home /` and the page reloads correctly.

Closing for now.
