### ISSUE TITLE
403 AccessDenied on PR builds

### ISSUE THREAD

**Issue by jeliasson** [redwoodjs/redwood#1671]
I'm trying to bring in PR build #1627 but I get an `403 AccessDenied` on the [package](https://rw-pr-redwoodjs-com.s3.amazonaws.com/1627/redwoodjs-core-0.23.0-07ee94d1.tgz). Are the packages missing, or has the S3 bucket policy changed?

```
yarn rw upgrade --pr 1627:0.23.0-07ee94d
```

/cc @peterp @Tobbe

**Comment by Tobbe** [comment]
Works for me 🤷 

For that particular PR you can get it by upgrading to canary now, since it's been merged. But yeah, the links works for me, I can download the packages.

**Comment by Tobbe** [comment]
Tried the actual pr upgrade command as well, and that works too

**Comment by thedavidprice** [comment]
So you can't see this @jeliasson?

<img width="756" alt="Screen Shot 2021-01-26 at 4 20 32 PM" src="https://user-images.githubusercontent.com/2951/105924075-6cfa4f00-5ff2-11eb-8010-a73b824b038d.png">

I wonder if we have some kind of regional networking issues... no idea why that would be the case. Or how to test.

**Comment by Tobbe** [comment]
So it mostly works for me

![image](https://user-images.githubusercontent.com/30793/105950440-aec8db00-606e-11eb-884f-603b4992e783.png)

But I did get that `<Error>` once when I tried opening one of the links in an incognito window. But then when I tried again it downloaded just fine, even in incognito

**Comment by jeliasson** [comment]
Interesting. There must been a typo on my end where I wrote `yarn rw upgrade --pr 1627:0.23.0-07ee94d1` instead of `yarn rw upgrade --pr 1627:0.23.0-07ee94d`. Observe the extra `1` in the end, which naturally result in another url being fetched (which then gives 403).

I'll close this issue for now, and reopen if I see this behavior again minus the fat fingers 😅
