### ISSUE TITLE
Cannot start storybook after adding afterQuery

### ISSUE THREAD

**Issue by jangxyz** [redwoodjs/redwood#1673]
As described in [this thread](https://community.redwoodjs.com/t/afterquery-conflicts-with-storybook/1726),

`yarn rw sb` fails with the following error after adding `afterQuery` to a cell:

```
ERROR in ./src/components/PostCell/PostCell.mock.js
Module not found: Error: Can't resolve './' in '/Users/kjh/play/_ground/redwood/check-after-query/web/src/components/PostCell'
 @ ./src/components/PostCell/PostCell.mock.js 1:0-32 2:24-34
 @ ./src sync .+(mock).(js|ts)$
 @ ../node_modules/@redwoodjs/core/dist/storybook/StorybookProvider.js
 @ ../node_modules/@redwoodjs/core/config/storybook/preview.js
 @ multi ../node_modules/@storybook/core/dist/server/common/polyfills.js ../node_modules/@storybook/core/dist/server/preview/globals.js ../node_modules/@redwoodjs/core/config/storybook/preview.js ../node_modules/@redwoodjs/core/config/storybook/generated-entry.js ../node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true
```

This could be easily repeated by generating a cell and adding a default `afterQuery` implementation.

```bash
yarn create redwood-app check-after-query
cd check-after-query
yarn rw g cell post
echo 'export const afterQuery = (data) => ({...data})' >> web/src/components/PostCell/PostCell.js
yarn rw storybook 
```

<img width="1440" alt="Screen Shot 2021-01-26 at 19 16 53" src="https://user-images.githubusercontent.com/52015/106003595-b2ec0b80-60f5-11eb-9656-9909c32926be.png">

Tested on v0.23.0 (macos 10.15.7, node v14.15.3)

Halting and restarting storybook, or re-installing `node_modules/` does not work,
but simply commenting out the `afterQuery` line make storybook work again.

**Comment by dac09** [comment]
Repro'd, confirmed bug is created in `babel-plugin-redwood-mock-cell-data`. Looking to fix now :)

**Comment by dac09** [comment]
Thanks for reporting this @jangxyz, and for the simple repro steps as well!
