### ISSUE TITLE
Framework `yarn build` command is skipping `packages/create-redwood-app`

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1677]
@peterp This is a strange one. During a run-through of the new publishing stuffz, I noticed there wasn't a `dist/` directory in `create-redwood-app`. Turns out `yarn build` is skipping `create-redwood-app`:
s
<img width="507" alt="Screen Shot 2021-01-27 at 9 05 29 PM" src="https://user-images.githubusercontent.com/2951/106095407-9d241980-60e8-11eb-9719-71a253a37a34.png">

<img width="199" alt="Screen Shot 2021-01-27 at 9 06 26 PM" src="https://user-images.githubusercontent.com/2951/106095420-a44b2780-60e8-11eb-8383-06b19fcfa70c.png">

**However**, if I `yarn workspace create-redwood-app build` it works as expected.

Not sure how to debug this one. Definitely couldn't find a fix. The workaround, for now, is manually confirming and running `yarn build` in the CRWA directory.

**Comment by peterp** [comment]
Hey @thedavidprice 

I've fixed this now, but wanted to explain how. When you run `yarn build` it runs `yarn lerna build:js` which looks at all the `package.json` files in `./packages/*` and tries to find a script called `build:js`.

CRWA didn't have one! I'm not sure why/ how this worked previously

**Comment by thedavidprice** [comment]
@peterp Thanks for walking through this! And, yes, I saw the `build:js` used by Lerna but it didn't seem quite obvious to me why Lerna wasn't using `build` instead (no need to explain now, that's a minor thing).

So it seems Lerna is itself handling both JS and TS here `"build": "lerna run build:js && ttsc --build --verbose"`. For most of the packages, that ends up being identical to the `build` scripts specific within each individual package. There are **two** exceptions I think: CLI and Web packages.

## CLI
Here are the scripts inside `packages/cli/package.json`:
```
"build": "yarn build:js && yarn build:clean-dist",
"build:clean-dist": "yarn rimraf 'dist/**/__tests__'",
"build:js": "babel src -d dist --extensions \".js,.ts,.tsx\" --copy-files --no-copy-ignored",
```

I tested and can confirm the `build:js` _is NOT_ identical. The `__tests__` **are** included in the `/dist`

## Web
Here are the related scripts inside `packages/web/package.json`:
```
"build": "yarn build:js && yarn build:types",
"build:js": "babel src -d dist --extensions \".js,.ts,.tsx\"",
"build:types": "ttsc --build --verbose && node ./scripts/postBuild.js",
```

Here is [postBuild.js](https://github.com/redwoodjs/redwood/blob/main/packages/web/scripts/postBuild.js)

After running the script and examining the results in `dist/`, it does not appear the script is necessary anymore.

# Proposal to Sync up Commands
- CLI: add `build:clean-dist` to end of `build:js`. Use `build:js` for `build`
- Web: remove postBuild.js script and references in package scripts

**Comment by thedavidprice** [comment]
FYI: I'm making an assumption that there's a specific Lerna build-time reason for not just running `yarn lerna build` and instead using `yarn lerna build:js && ttsc --build --verbose` --> is there a performance issue (or some weird gotcha)?

**Comment by peterp** [comment]
@thedavidprice The reason is the following:

1. We first transpile the javascript which means we remove all the type information and only emit the JS files.
2. We then use TypeScript to compile only the types, but of the entire project, in a way we use the step to check that everything is working together as required. Previously we had it so that each individual package built it's own types, but that caused problems with circular requirements.

**Comment by thedavidprice** [comment]
@peterp thanks! Very helpful and confirms + extends my understanding.

Did you see the comment above about variations in build with Cli and Web?
https://github.com/redwoodjs/redwood/issues/1677#issuecomment-769209928

**Comment by peterp** [comment]
Ah! Thanks for catching these - I think CLI should definitely work the way you've suggested, but I think for web we can actually remove the `postbuild` step. I'll test to confirm.

**Comment by thedavidprice** [comment]
@peterp See PR https://github.com/redwoodjs/redwood/pull/1687
