### ISSUE TITLE
Add root-path to api-server

### ISSUE THREAD

**Issue by jeliasson** [redwoodjs/redwood#1693]
This issue and PR #1691 seeks to add optional argument `root-path` to `@redwoodjs/api-server`. This will allow to pass which root path that should be used for the functions, which is useful when the api server is behind a proxy and served under e.g. `example.com/api`. In it's current implementation, behind a `/api` prefix, address `example.com/api/health` would result in `Function "api" was not found`.

### Motivation
From #quick-help at Discord
> @jeliasson wrote
> I have a RedwoodJS project running serverfull in Kubernetes with two deployments (and two separate images). One deployment for `web` proxied to `/`, and one deployment for `api` proxied to `/api`. The issue I'm facing is that address `/api` will will return `Function "api" was not found.` and I think this is because the api expects to be served under the root, i.e. `/`, along with the web. To work around this I have set `apiProxyPath` in `redwood.toml` to `/api/api` which works but it's quite ugly on local development (as GraphQL calls are made to `/api/api/graphql`) and might bring problems down the road. 

### Usage
Build and enter the `api` directory
```bash
yarn rw build api
cd api
```
#### Default behavior
This would prefix `/` which is the default behavior of `rw-api-server`.
```bash
yarn rw-api-server --port 8911 --functions ./dist/functions
```

#### --root-path
This would prefix `/api/<function>` on the following root path inputs:
* `api`
* `api/`
* `/api`
* `/api/`

```bash
yarn rw-api-server --port 8911 --functions ./dist/functions --root-path api
yarn rw-api-server --port 8911 --functions ./dist/functions --root-path api/
yarn rw-api-server --port 8911 --functions ./dist/functions --root-path /api
yarn rw-api-server --port 8911 --functions ./dist/functions --root-path /api/
```

### Todo
- [X] Decide path forward
- [ ] Code review
- [ ] Documentation

### Related PR
#1691 Add root-path to api-server

**Comment by jeliasson** [comment]
@peterp Your input is highly appreciated!

**Comment by thedavidprice** [comment]
closed by https://github.com/redwoodjs/redwood/pull/1691
