### ISSUE TITLE
[CLI] generate auth command breaks web

### ISSUE THREAD

**Issue by pi0neerpat** [redwoodjs/redwood#1700]
Just hit this on Canary. Still need to diagnose, making issue now just in case release is planned in next day or so.

**Comment by thedavidprice** [comment]
Ah, definitely keep us posted (and curious as to which command specifically).

Please also keep a watch on this PR: https://github.com/redwoodjs/redwood/pull/1685

**Comment by thedavidprice** [comment]
@pi0neerpat any updates on this one?

**Comment by thedavidprice** [comment]
#1685 has been merged and will be included in v0.24 release. I've tested the `setup auth` commands and they seem to be working correctly.

Please do test on v0.24 and let me know otherwise.
