### ISSUE TITLE
URLs with named routes not generated from Links as expected

### ISSUE THREAD

**Issue by tctrautman** [redwoodjs/redwood#1702]
Hello!

I believe I've stumbled onto a bug where Links don't generate the expected URL for some named routes.  Specifically, named routes with a variable as part (but not all) of a path.

For example, let's say this is the entirety of your routes file:
```
<Router>
      <Route path="/" page={HomePage} name="home" />
      <Route path="/{descriptor}/good-named-route" page={GoodNamedRoutePage} name="goodNamedRoute" />
      <Route path="/{descriptor}-bad-named-route" page={BadNamedRoutePage} name="badNamedRoute" />
      <Route notfound page={NotFoundPage} />
</Router>
```

And on your home page you have these Links:
```
        <Link to={routes.goodNamedRoute({ descriptor: 'very' })}>
          Good Named Route
        </Link>
        <Link to={routes.badNamedRoute({ descriptor: 'very' })}>
          Bad Named Route
        </Link>
```

The first Link would bring the user to the following URL in dev:
```http://localhost:8910/very/good-named-route```

But the second Link would bring the user to this (in my opinion) sub-optimal URL in dev:
```http://localhost:8910/%7Bdescriptor%7D-bad-named-route?descriptor=very```

I've pushed this small example up [here](https://github.com/tctrautman/named-routing-example) if you'd like to take a closer look.

Is this something that is expected or is there a known workaround?

I'm 100% open to the possibility that I've accidentally overlooked a section of the docs that describes how to address this, though in an initial pass I couldn't find anything in the docs, Github issues, Discord and Discourse.  Any thoughts or help would be appreciated!

**Comment by Tobbe** [comment]
> `<Route path="/{descriptor}-bad-named-route" page={BadNamedRoutePage} name="badNamedRoute" />`

That's not a syntax that's supported by the router. Named parameters can only be full url path segments. So what you're describing is expected behavior.

That said, this could 100% be better documented!

As for workarounds, I'd love to help you with that. But I think I'd have to see your exact use-case. Can you share?

**Comment by tctrautman** [comment]
Ah, thanks @Tobbe!  This would certainly explain it.

Here's a use-case that's similar to mine.

Let's say we're trying to build a site that's SEO-optimized for dog-related google searches.  We might build a page that's optimized for the keyword "best dog food," which would ideally have the path `/best-dog-food`, since the path is a consideration for SEO.

But this term is general enough of a keyword that it's likely to be highly competitive.  So, another strategy would be go after similar, less-competitive keywords by creating a _series_ of pages that are each individually optimized for a specific dog breed (e.g. "best dog food for Chihuahuas"), which could be generated from a `DogBreed` table.*

This is where it would be helpful to have a named parameter as _part_ of a path segment since we'd like each page to have a path that's SEO-optimized.  In this case, our path in the `<Route />` component would be something like `/best-dog-food-for-{breedName}`.

If this is a case that we think is worth supporting, and it's a candidate for "a good first issue," I could take a look and try to submit a PR later this week.

_*side note: this is only really a good strategy if you have other data that allow you to customize the content of each page.  Otherwise we're likely just going to generate spam, which isn't good for users and doesn't rank well._

**Comment by Tobbe** [comment]
I really have no idea about seo, but wouldn't `/best-dog-food/{breedName}` work just as well? You still get all your keywords in the url, it's basically the same length. It's still understandable for both humans and machines.

**Comment by tctrautman** [comment]
My understanding is that there are significant benefits to having the exact term that someone would type into google as a path segment, but I can't speak to _how_ beneficial that is relative to alternative you mentioned.  I'll see if I can dig up some research on this, though.

**Comment by tctrautman** [comment]
Hmm, so after looking into this for a few minutes I struggled to find a resource that talks about the difference between these two ways of including keywords in the path.  I know I've read that before, but the fact that I couldn't find a resource that describes the importance might indicate it's not _that_ big of a deal. I'll close out this issue & rename it so others can chime in at a later time if they think it's important.

Though, unfortunately in my case I already have a series of pages on a site that's live that are using this structure.  I'll just use an `<a />` tag instead of a `<Link />` to get the URLs generating correctly and keep my fingers crossed that the Router continues to know how to handle named parameters as part of a path segment (as seems to be the case right now.)

**Comment by Tobbe** [comment]
SEO is a lot of guessing and not a lot of hard facts... Thanks for posting your workaround with the regular `<a>` tags. Named path parameters are an integral part of the way the router works and we have no plans to remove those.

**Comment by tctrautman** [comment]
Perfect, thanks for the help @Tobbe!
