### ISSUE TITLE
Storybook

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [redwoodjs/redwood#1709]
It will be nice if some details are provided on the Storybook integration is planned

**Comment by KrisCoulson** [comment]
@VinayaSathyanarayana what type of information are you looking for? Storybook is already implemented if you are looking for more info on how to implement @cannikin 's Tutorial Part 2 has a really good intro

**Comment by thedavidprice** [comment]
Is this what you're looking for?
https://redwoodjs.com/tutorial2/introduction-to-storybook

**Comment by VinayaSathyanarayana** [comment]
On the main page it still says storybook (Coming soon)

**Comment by dthyresson** [comment]
> On the main page it still says storybook (Coming soon)

Oh, you are referring the this repo's README in the `Technologies` section.

https://github.com/redwoodjs/redwood/blob/main/README.md

@VinayaSathyanarayana Would you suggest any of the above mentioned links in included as helpful? And if so which?

**Comment by jonniebigodes** [comment]
@dthyresson  i have been checking on the integration on and off and the awesome job you guys did integrating Storybook. But i was checking the tutorial and something peeked my interest. With Storybook 6.0.x controls and args are included as one of the features and the tutorial doesn't mention that. Probably not a bad idea to adjust the snippets to mimic what the user /reader sees when adding Storybook to his/her project.

Let me know and we can move from there.

Stay safe

**Comment by thedavidprice** [comment]
@jonniebigodes great to see you here! You've been missed 😄 

Unfortunately, Redwood is currently using Storybook 5. There's a lot of moving parts (I believe) to upgrade to v6. We'd like to do it, it's just not been a priority for us given all the other things happening to get Redwood v1 released soon.

Help welcome. But if it's too many moving parts that require someone like Peter to review and answer questions, we might not get his full focus for another month or so.

**Comment by jonniebigodes** [comment]
@thedavidprice i've been keeping a close eye on the project. Sorry for not being so active but i had to shift my attention to other tasks. 

Let me know what is that's required and i can get in touch with the Storybook maintainers and we could work something out.

**Comment by thedavidprice** [comment]
@jonniebigodes Thanks for offering. @peterp did all the amazing Redwood + Storybook integration work, so he'd be the one to provide guidance here.

**Comment by peterp** [comment]
We've now upgraded to Storybook 6.0 in this PR: #2054
