### ISSUE TITLE
Check for existence of routes before creating them again

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#171]
If you run a generator twice with `--force` it will append its routes again, even if those exact same routes already exist.

**Comment by sharcastic** [comment]
Hey @cannikin, I tried looking into this issue and I have a doubt. I'm assuming that even if we have the flag `--force`, we need to check the existence of routes before creating them again. 
In the function `writeFile` in lib/index.js, the statement `if (!overwriteExisting && _fs.default.existsSync(target))` skips out the error statement and goes ahead with its default behaviour if you set `force` flag as true. So if we end up removing overwriteExisting from the if statement, we could solve this but there would be no point of passing around overwriteExisting anymore (unless its used in some other file, in which case I'm wrong about this).

I wanted to ask what should change between the default behaviour of this command and when we use the `force` flag ideally.

**Comment by cannikin** [comment]
Hi @sharcastic thanks for taking a look at this! 

I wouldn't mess with `writeFile` as it's used all over the place. I was planning on just doing a `match()` against the current content of the router file and the new routes that were about to be added in the `addRoutesToRouterTask()` function. If a match exists then do nothing, otherwise continue with the logic that's already there (reduce and replace).

**Comment by sharcastic** [comment]
Got it. 2 points here.

i. Do we go ahead with replacing the generated route file and route test file or do we not replace them if something with that name already exists?

ii. The solution you suggested seems to work in most of the scenarios. But in a scenario where they are importing some/all of the routes from a different file (because those routes are just components after all), would this solution work?

**Comment by cannikin** [comment]
i. When you say "something with that name" do you mean the file itself, Routes.js? If we didn't overwrite THAT then we'd never be able to add the routes! Or did you mean something else?

ii. Hmmm good question on the imports...we hadn't planned that far ahead. 😅I'd be inclined to just optimize for the single Routes.js file and then if people start importing and getting duplicate routes then they can open a new issue and we can deal with it then. What do you think?

**Comment by sharcastic** [comment]
i. So assume I run `yarn rw generate page about` which creates 2 new files, AboutPage.js and AboutPage.test.js other than changing the main Routes.js file. If I then run `yarn rw generate page about --force`, should I replace the already existing AboutPage and its test file with the newly generated files or should we keep the older version of it? (Leaning towards keeping the older version if you ask me incase they had made some changes to it.)

ii. I think so too. At this stage of the project, I'm pretty sure you guys already have your hands full with things which are of higher priority! 😄

**Comment by cannikin** [comment]
Ahh okay. Yeah so right now when we say `--force` we *really* mean force: everything is overwritten and it doesn't care if you have changes in there or not. We'd like to add a prompt on each file asking if you want to overwrite with a y/n/a choice, but that's on our TODO list! But for now we're okay with a hardcore overwrite for everything.

**Comment by sharcastic** [comment]
Hey @cannikin, I have forked the repo and created a new branch. Here is the link https://github.com/sharcastic/redwood/tree/pp-fix-check-existence-routes-before-adding
Is it ok if i raise a PR for this?

**Comment by thedavidprice** [comment]
@sharcastic go for it! It’s easiest to review as a PR. Once you create it, assign him as the reviewer. And please do mention this Issue #171 to create a link back here. Appreciate you working on this.
