### ISSUE TITLE
Some of the generated ts files on Windows fail to use ensurePosixPaths

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood#1719]
A good example is `redwood/types/routes.d.ts`

```
import type NotFoundPageType from 'c:\work\learning\redwood\redwoodblog\web\src\pages\NotFoundPage\NotFoundPage'
```

This results in VS Code confusion (it could probably be fixed via VS Code settings, but fixing the incorrect file generator would be more appropriate)

**Comment by Tobbe** [comment]
Relevant code here https://github.com/redwoodjs/redwood/blob/19bb1b5f39dae7d6863096b560bc3549889a7b9a/packages/core/src/babelPlugins/babel-plugin-redwood-routes-auto-loader.ts#L52-L63

**Comment by Tobbe** [comment]
Fixed by https://github.com/redwoodjs/redwood/issues/1742
