### ISSUE TITLE
RFC: Remove prisma from @redwoodjs/api dependency

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#1728]
## What?
Remove prisma from @redwoodjs/api dependency, so we can upgrade/downgrade as a user of redwood, without needing to mess with lockfiles or resolutions.

Currently even if you install prisma, yarn resolves the version specified inside the api package.json for use with redwood (so just doing the install is kind of pointless).

We have to use resolutions like this forum post: https://community.redwoodjs.com/t/intermittent-prisma-error-in-production/1762/5

## How would this work?
- Move prisma to peer dependency in `@redwoodjs/api`
- Add prisma to dependency in crwa api template

cc @peterp @thedavidprice

**Comment by thedavidprice** [comment]
I understand the need, but I _really_ don't want to do this.

Preference would be to offer the steps from Forum comment (above) as help content in doc, post, inline-comment, etc. Downgrading Prisma should be a _very_ rare edge case. 🤞

**Comment by dac09** [comment]
I realised because the CLI is so closely tied in with prisma, it makes sense not to do this for now. We can re-visit later if this continues to be an issue

**Comment by peterp** [comment]
I think that the parts that are closely tied to Prisma are only the generation commands now that we alias the Prisma command. I think those commands are generally used in the beginning of a project, and not when a user is at the point where they're upgrading Prisma.

I think allowing user's to upgrade Prisma will be a plus, and we should consider making this as easy as possible.

**Comment by dac09** [comment]
Hmm, yeah. This was before we started proxying the prisma commands. I'll reopen and leave it here for further discussion

**Comment by thedavidprice** [comment]
Our configuration and DX, not just with generators, are still tightly coupled to Prisma at this time. I'd want to see some stability on Prisma's side before we consider projects needing to manage, and upgrade, Prisma versions in addition to Redwood versions. So far Prisma has not had many examples of backward compatibility for more than a few minor versions once they've deprecated features, syntax, etc.

> I think allowing users to upgrade Prisma will be a plus, and we should consider making this as easy as possible.

^^ I don't understand what needs to be different to achieve this. Currently, there's nothing blocking users from installing a more recent version of Prisma in their project if they want. (Am I incorrect, or incomplete, in my understanding?)

Yes, downgrading was/is a hassle. But having to downgrade was a whole other mess in and of itself.

**Comment by jtoar** [comment]
@thedavidprice asked me to close this one out as resolved
