### ISSUE TITLE
RBAC: Add hasRole to API

### ISSUE THREAD

**Issue by jeliasson** [redwoodjs/redwood#1730]
Currently we have `hasRole` method on the web side of things, but it would be neat having it on the api side. We currently have `requireAuth`, but that will throw an error while `hasRole` would most likely return a boolean. 

For now it's super easy to just add copy the `requireAuth` logic and change out the throwing of exceptions to boolean, but would be nice seeing a native way in future RedwoodJS versions.

/cc @dthyresson

**Comment by dthyresson** [comment]
Idea here is to move

```
  if (
    typeof role !== 'undefined' &&
    typeof role === 'string' &&
    !context.currentUser.roles?.includes(role)
  ) {
    throw new ForbiddenError("You don't have access to do that.")
  }

  if (
    typeof role !== 'undefined' &&
    Array.isArray(role) &&
    !context.currentUser.roles?.some((r) => role.includes(r))
  ) {
    throw new ForbiddenError("You don't have access to do that.")
  }
```

into a `hasRole()` that returns a boolean and then use that to raise the `ForbiddenError`.

That way a `hasRole()` could even be used in a directive or maybe GraphQL shield to protect a service resolver easily.

**Comment by dthyresson** [comment]
Note this PR should also address the inconsistency in role vs roles in requireAuth.

The params and docs should both use `roles`.

**Comment by jtoar** [comment]
Do secure services kind of handle this? https://redwoodjs.com/docs/services#secure-services
