### ISSUE TITLE
Auth Provider: https://fusionauth.io/

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [redwoodjs/redwood#1731]
Please support https://fusionauth.io/ as an Auth Provider. This will be essential where want more control of Auth

**Comment by voidmain** [comment]
I poked around quickly at the Redwood docs and it looks like it implements Implicit Grant with most of the providers. This grant is deprecated, so I would steer clear of it completely (it's extremely insecure).

It might be quite simple to integrate FusionAuth with Redwood securely though by just using OIDC and the Authorization Code Grant. In most cases, all you need are 2 routes that handle sending the user over to FusionAuth and then handling the redirect back from FusionAuth. 

Our 5-minute setup guide is a good place to start: https://fusionauth.io/docs/v1/tech/5-minute-setup-guide/

**Comment by dthyresson** [comment]
Hi @voidmain. FusionAuth is definitely new to the RedwoodJS team (and me) -- so thanks for making us aware of it! 

As we'd like to support many popular Auth providers to give people flexibility and choice in authentication (sometimes certain providers cannot be used in certain countries for various reasons) -- knowing more about how best to implement FusionAuth is helpful.

Typically, the AuthProvider leverages the provider's client SDK and follows their implementation.

Is https://github.com/FusionAuth/fusionauth-typescript-client the client you'd recommend?

Also, could you elaborate on this `grant is deprecated, so I would steer clear of it completely` -- is that in reference to FusionAuth's use on an implicit grant or Auth0 or one of the other supported providers?

If there's something we should remedy, we definitely would like know how better to do so.

**Comment by VinayaSathyanarayana** [comment]
next-auth supports fusionauth.io 
Does RedwoodJs use next-auth.js behind the scenes?

**Comment by dthyresson** [comment]
> Does RedwoodJs use next-auth.js behind the scenes?

@VinayaSathyanarayana @redwoodjs/auth is a lightweight wrapper around popular SPA authentication libraries, but does not use next-auth.

You can see in the [Authentication docs](https://redwoodjs.com/docs/authentication) [https://redwoodjs.com/docs/authentication](https://redwoodjs.com/docs/authentication) some examples of the implementation -- and how one would implement a new provider like FusionAuth.

Also, for an example new auth provider implementation you can follow how @nunopato is [currently implementing NHost authentication](https://github.com/redwoodjs/redwood/pull/1725) in https://github.com/redwoodjs/redwood/pull/1725.

**Comment by voidmain** [comment]
@dthyresson our TypeScript client is definitely the best way to implement directly with FusionAuth. However, I would definitely recommend using OpenID Connect using the Authorization Code Grant and the Userinfo endpoint instead. This is compliant with a well known specification and makes it really simple to just plug in new identity providers.

In terms of the Implicit Grant being deprecated, you can review the upcoming OAuth 2.1 specification to see that it is being removed here:

https://tools.ietf.org/html/draft-ietf-oauth-v2-1-01

You can also read more on the issues with Implicit Grant at these places:

https://oauth.net/2/grant-types/implicit/
https://fusionauth.io/learn/expert-advice/oauth/differences-between-oauth-2-oauth-2-1/
https://developer.okta.com/blog/2019/05/01/is-the-oauth-implicit-flow-dead
https://medium.com/oauth-2/why-you-should-stop-using-the-oauth-implicit-grant-2436ced1c926

There are hundreds of blogs and articles on this if you search for "implicit grant deprecated".

We also have an eBook coming out soon on OAuth and it has a section that shows the most common attack vector for Implicit Grant. Basically, a third-party JavaScript library can easily steal a user's access token in 1 line of JavaScript. Once they steal the token, they are able to do anything as that user (eeck!).

The best way to implement OAuth (and pretty much any authentication these days) is via OpenID Connect and the Authorization Code Grant.

**Comment by Josh-Walker-GM** [comment]
Hey all! I'm going to close this issue but anyone feel free to reopen and get the discussion rolling again. 

We do now support custom auth implementations which can be shared. This can be used to implement third-party auth providers that we as the redwood team haven't implemented ourselves. The docs for this feature can be found at: https://redwoodjs.com/docs/auth/custom
