### ISSUE TITLE
Product Idea: Dashboard Composed of Cells

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [redwoodjs/redwood#1732]
The idea is that one should be able to compose a dashboard with multiple cells
Page->Grid->Cells

Each cell can show 
+ Static Data
+ Streaming Data (Support for Time Series Data and GraphQL Subscriptions)

Note: Each Cell can be independently linked to different data sources

**Comment by thedavidprice** [comment]
Feels a bit like https://vida.io/ !

Also @VinayaSathyanarayana this is a great topic but will likely get lost here in the GH Issues. Maybe try starting a discussion on the Forums? (Also, search for some similar topics in the Forums. I believe some people were thinking about a similar idea but for backend Admin Dashboard.)

https://community.redwoodjs.com

**Comment by VinayaSathyanarayana** [comment]
Thanks @thedavidprice.

**Comment by thedavidprice** [comment]
Conversation has moved here --> https://community.redwoodjs.com/t/spreadsheet-style-editing-in-cell-page/1786
