### ISSUE TITLE
Support Prisma Native Types Postgres BigInt in SDL

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#1733]
I ran into a case today where a  column was set in Prisma scheme to `Int` which is `int4` in Postgres.

But, I had a case where Filestack wanted to set that column to a value above its limits (ie, files with size > 2GB=ish -- 2,147,483,647) as had some people upload 3GB and 5GB files. While I can handle that in filestack to set a maximum size etc, it revealed that I cannot set the schema to use `BigInt` even with `previewFeatures = ["nativeTypes"]` support set.

The schema is fine and I can generate migrations (even in the new prisma migrate) but the SDL won't recognize the type -- even though RW uses `graphql-scalars` which adds that support.

I think a solution might be to add `BigIntResolver` to:

```diff
// redwood/packages/api/src/makeMergedSchema/rootSchema.ts

export interface Resolvers {
+ BigIntResolver: typeof BigIntResolver
   Date: typeof DateResolver
   Time: typeof TimeResolver
   DateTime: typeof DateTimeResolver
   JSON: typeof JSONResolver
   JSONObject: typeof JSONObjectResolver
   Query: Record<string, unknown>
}
```

and then in same, map to `BigInt`:

```

export const resolvers: Resolvers = {
  BigInt: BigIntResolver,
  Date: DateResolver,
  Time: TimeResolver,
  DateTime: DateTimeResolver,
  JSON: JSONResolver,
  JSONObject: JSONObjectResolver,

```

Note: a workaround for non-native types is to use a `Float` instead of `Int`.

**Comment by thedavidprice** [comment]
This feels like a v1 requirement for sure, right?

Also, @cannikin, it didn't hit me until now --> with the new DB Type support coming in Prisma v2.16, will there be necessary changes to the Scaffold Generator? Assuming "no" but....

**Comment by cannikin** [comment]
It doesn't HAVE to change, but it would be nice if you had a datatype of `TEXT` that we show a textarea in the form instead of a single-line text input.

**Comment by cannikin** [comment]
We should also verify that native types doesn't change the object that `getDMMF()` gives you. That's the function that parses the raw schema file into an object that we look at to determine what field types and stuff everything is. Right now the type is `String`. I would hope that for their own backwards compatibility they kept that and added an additional field with the equivalent native type.

If they *didn't* do that, and `String` is now like `Text` or something, that'll break the existing scaffold and we'll have much bigger problems. :(

**Comment by dthyresson** [comment]
@cannikin and @thedavidprice the mapping (PG) for String is

https://www.prisma.io/docs/concepts/components/preview-features/native-types/native-types-mappings#string

![image](https://user-images.githubusercontent.com/1051633/107539141-ac986d80-6b92-11eb-9afa-0a3da22e80a0.png)

Are you asking to test scaffolds when the schema is something like

```
model Post {
...
  name   varchar
  letter   char
  info      xml
}
```

?

**Comment by cannikin** [comment]
Okay so all of those native types, `getDMMF()` will list them as `String` it sounds like. That's what the generators expect and we should be okay then.

The nice-to-have would be that if you have a `text` (and `citext`) the scaffolds would show a textarea instead of input.

**Comment by jtoar** [comment]
Might be combined with #2980

**Comment by jtoar** [comment]
@dthyresson Did you still want to prioritize this for v1? Looks like our resolver interface hasn't changed still:

https://github.com/redwoodjs/redwood/blob/229c3cf59399119a8169bc56e3908c99e904ea6b/packages/graphql-server/src/rootSchema.ts#L44-L51

**Comment by dthyresson** [comment]
@jtoar The interface and adding the scalar was simple, but the testing and adding it to the scenarios got non-trivial because of the way the scenario formatted the values to compare.

But, it would be a good issue to get in/revisit so yes please assign to me. Thanks.

**Comment by dthyresson** [comment]
Closed and fixed by https://github.com/redwoodjs/redwood/pull/4035
