### ISSUE TITLE
RW generates invalid TS types file for the router

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#1742]
When you build a Redwood project (`yarn rw build`) there's a babel script that looks at your routes and generates up a `routes.d.ts` file in the `.redwood` folder.

This is what that file might look like (on Windows)

```ts
declare module '@redwoodjs/router' {
  interface AvailableRoutes {
    homePageProxy: () => "/proxy"
    home: () => "/"
  }
}

import type FatalErrorPageType from 'C:\Users\tobbe\dev\redwood\tstest\web\src\pages\FatalErrorPage\FatalErrorPage'
import type HomePageType from 'C:\Users\tobbe\dev\redwood\tstest\web\src\pages\HomePage\HomePage'
import type HomePageProxyPageType from 'C:\Users\tobbe\dev\redwood\tstest\web\src\pages\HomePageProxyPage\HomePageProxyPage'
import type NotFoundPageType from 'C:\Users\tobbe\dev\redwood\tstest\web\src\pages\NotFoundPage\NotFoundPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const HomePageProxyPage: typeof HomePageProxyPageType
  const NotFoundPage: typeof NotFoundPageType
}
```

So, two issues here

1. This is a types file, that is only used when generating/building types. As soon as that's done it's not used anymore. So all those global definitions will not be available after, when they're actually needed.
2. All the import paths are wrong on Windows. Need to be slash or double backslash.

**Comment by adriatic** [comment]
> So all those global definitions will not be available after when they're actually needed.

How then did anything "typescript" work? Or, are you saying that nothing did work and I caught just something on the very surface?

A side note: did you know that the VS Code team at some point in the past when a lot of code already existed as typescript, decided to rewrite everything in TypeScript? They cited the hugely improved support for refactoring as the key reason (meaning that they would still be refactoring stuff that is already judged good enough 😄

**Comment by Tobbe** [comment]
> How then did anything "typescript" work?

I suspect most people just kept the routes file as a .js file even if they had other .ts(x) files in their project

**Comment by adriatic** [comment]
That was my fear as one of RW main thrusts should be focused on "making" people use Typescript - and that is best done by demonstrating the advantages of TS in the form of very clear examples.

**Comment by Tobbe** [comment]
When TS support is more mature the plan is to switch over to generating TS projects by default. That'll get people using it :)

**Comment by adriatic** [comment]
> When TS support is more mature

By this, you mean the RW ability to use TS, not the state of TS itself, right?

By the way, it was very helpful to meet you virtually yesterday. In the end, you held your baby - a very cute baby indeed.

**Comment by mojombo** [comment]
> one of RW main thrusts should be focused on "making" people use Typescript

@adriatic For the record, this is not a goal of Redwood. We want to provide a first class TypeScript experience for those that want it, but Redwood is perfectly happy for authors to write their apps in JavaScript.

**Comment by adriatic** [comment]
@mojombo, you are correct and I am clumsy. Making people do anything is silly, providing incentives is a lot better. Note that @Tobbe stated that [above](https://github.com/redwoodjs/redwood/issues/1742#issuecomment-774490510).

Thanks for taking my foot out of my mouth 😄

**Comment by Tobbe** [comment]
> By this, you mean the RW ability to use TS, not the state of TS itself, right?

Yes, I was talking about how well RW and TS work together. TypeScript as a language is more than mature enough :) 


> In the end, you held your baby - a very cute baby indeed.

Thank you 🙂 She has made appearances before 🙂
