### ISSUE TITLE
RW Prisma `migrate resolve` command and DX

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1748]
Continuing from https://github.com/redwoodjs/redwood/pull/1720

We need to figure out the DX for `prisma migrate resolve`, which will be necessary for upgrading deployed projects (non-destructively) to the new Prisma Migrate.

> Note: we could choose to handle this with documentation, covering both Linux/Windows use case. I would prefer to solve this as the command line, however, as it's likely a priority use-case for most production projects.

The recommended solution is interactive and requests the connection string when run. The other two commands like this are `introspect` and `migrate status`:

- thoughts about how to handle these, either with interactivity or custom options?
- I don't think it's a priority we need to have custom, interactive support for `introspect`

> Windows issue with passing Env Var value via CLI --> to handle cross-platform, we use the `cross-env` package

Example:
```bash
rw prisma migrate resolve
...
> asks for connection string for DB to be resolved
> asks for other flags, e.g. the  --applied or --rolled-back, of which one must be specified and will require a migration ID
...
runs command
```

**Comment by peterp** [comment]
I don't think we shouldn't try to aim for this for the initial release of this prisma upgrade. I think we should just use env vars.

**Comment by peterp** [comment]
But, if we do want to go this route:

[prompts](https://www.npmjs.com/package/prompts) is an amazing package that makes this easy to do. I would suggest we allow people to use an env-var, but ask them to enter it if it's undefined.

**Comment by dthyresson** [comment]
> I think we should just use env vars.

@peterp Are you suggesting that each RedwoodJS app declare two env-vars: one for the development database and one for production (or even multiple staging, integ if so happens)?

How then does the developer specify which to use when resolving?  I think I will likely resolve production manually and not part of a deploy build process.

I think there was some discussion around declaring an environment and then have `.env.development` and `.env.production` and thus DATABASE_URL would be the same env-var, just with the appropriate value.

**Comment by peterp** [comment]
> Are you suggesting that each RedwoodJS app declare two env-vars

Nope, just one: `DATABASE_URL` env-var. If you wanted to switch to production you would have to specify the connection string and then run the command, like this:

```terminal
DATABASE_URL=psql://connection.string yarn rw prisma migrate resolve
```

**Comment by dthyresson** [comment]
> What I mean here is that you must explicitly specify the env var before running the command. Not define an env-var in a configuration file.

Ok, that's fair. Makes sense. Since `resolve` is such an explicit command that having to specify clearly the prod (or target db) seems appropriate.

Note, I wanted to see what happens with a target dev db:

```
yarn rw prisma migrate resolve --applied 20210208124006_migration
```
And the `applied` argument wasn't recognized:

```
Examples:
  'yarn rw prisma migrate dev'  No additional options required

For more commands, options, and examples, see Redwood CLI Reference
(​https://redwoodjs.com/docs/cli-commands#prisma​)

Unknown argument: applied
```

**Comment by peterp** [comment]
@dthyresson Check out my new fixes for this: https://github.com/redwoodjs/redwood/pull/1750

**Comment by thedavidprice** [comment]
@Tobbe can you help us understand Windows concerns regarding passing Env Var at the command line, e.g.:
```bash
DATABASE_URL=psql://connection.string yarn rw prisma migrate resolve
```

My understanding is that this works for some cases, e.g. Git Bash, but not all cases, correct? Is there a standard way to do this that works in all Windows cases?

**Comment by thedavidprice** [comment]
## Current Status
For the near-term, we are going to handle this via documentation (likely via Forum) and advise users to pass DATABASE_URL with the command (per Peter's example above). 

> Note: this is not possible for most Windows command prompts. This leaves Windows users with the only option of setting DATABASE_URL to the production connection string in either `schema.prisma` (bad option) or `.env` (also a bad option). In both cases, they'd be overwriting their local DB connection string, could forget they've done so, and possibly make data/structure changes to prod or commit the secret to git and push-a-roney. 👎

## Best Case
We need to escalate this with the Prisma team and push for a resolution on their end, top-down. It's just not an acceptable solution as-is to require users to add production secrets to local files in order to upgrade to the new Prisma Migrate. 

If you're listening, @janpio and @Jolg42, let's connect in the ol' Slack channel and discuss. We have ideas.

**Comment by Tobbe** [comment]
So I wrote a test script

![image](https://user-images.githubusercontent.com/30793/107493342-c71c1800-6b8d-11eb-9ae9-dce27e6347a2.png)

In git-bash:

![image](https://user-images.githubusercontent.com/30793/107493399-d8652480-6b8d-11eb-930a-f3442fad3db4.png)

PowerShell

![image](https://user-images.githubusercontent.com/30793/107493490-f599f300-6b8d-11eb-968d-715bba5602df.png)

Cmd

![image](https://user-images.githubusercontent.com/30793/107493601-16fadf00-6b8e-11eb-83ce-5f82f34f9ead.png)

So you're right, it works in git-bash, but not anywhere else

Using Cmd, the correct syntax is this

![image](https://user-images.githubusercontent.com/30793/107494549-37776900-6b8f-11eb-9032-97dad74db0f0.png)

For PowerShell there really doesn't seem to be a clean way to even do this. See here for more info: https://stackoverflow.com/questions/1420719/powershell-setting-an-environment-variable-for-a-single-command-only

**Comment by Tobbe** [comment]
git-bash

![image](https://user-images.githubusercontent.com/30793/107495521-7eb22980-6b90-11eb-8043-7724ae57eafb.png)

PowerShell

![image](https://user-images.githubusercontent.com/30793/107495619-9ee1e880-6b90-11eb-81b1-44ab32ed8509.png)

Cmd

![image](https://user-images.githubusercontent.com/30793/107495573-8d004580-6b90-11eb-97d1-5e0f222821f5.png)

```
npx cross-env ECHO_ENV=testing && node .\echoenv.js
```
The above seems to work everywhere 👍

**Comment by Tobbe** [comment]
So in theory you should be able to do

```
npx cross-env DATABASE_URL=psql://connection.string yarn rw prisma migrate resolve
```

But I have not tried it with that exact command, only with my test node script as you see in my previous posts.
The command should work for all platforms, so if you want to have just one command for everyone that'd be the way to go. Or you can split it up and recommend the version without cross-env for unix-like OSes

**Comment by thedavidprice** [comment]
Genius @Tobbe 🚀🚀

I'll take it for a spin today!

**Comment by thedavidprice** [comment]
Update --> works great on Mac (as expected).
