### ISSUE TITLE
[v0.25 release dependency] RW Prisma Command improvements (discussion)

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1749]
Continuing from #1720

**Potential Problems**
1. Can use _always_ pass through flags for specific Prisma commands?
    - E.g. `yarn rw prisma migrate dev --name migration-name` did fail because Yargs tries to understand the --name flag
    - In the case above, I've added an initial hacky workaround for only `migrate dev` to handle `--name` automatically and accept `--create-only` when passed by the user.

**Questions**
1. Should we add tests to Prisma commands? ((can use previous DB Command tests as reference)
2. ~~Should we pass a default Prisma migration name with the option to customize like we did with `rw db save`? That would be my preference.~~ Had to add this as initial workaround to Problem 1 above.
3. How can we improve `--help` output? Currently yargs `--help` always displays for the top-level command _and_ all other commands; ideally yargs default would only display for the top-level and otherwise display would be Prisma CLI help for specific commands E.g. `yarn rw prisma db seed --help`
    - `rw prisma db push --help` (for example) to output `yarn prisma db push --help`

**Possible Improvements**:
1. aliases, E.g. `dev` for `migrate dev` or `push` for `db push` (probably would need some switchin')

**Comment by peterp** [comment]
> E.g. yarn rw prisma migrate dev --name migration-name did fail because Yargs tries to understand the --name flag

Solved.

> In the case above, I've added an initial hacky workaround for only migrate dev to handle --name automatically and accept --create-only when passed by the user.

Does `migrate` not handle this automatically? From the docs:

> Migrate your schema - you will be prompted to name the migration file (for example, first_migration)

> Should we add tests to Prisma commands? ((can use previous DB Command tests as reference)

I don't think it's required; since we're not mapping commands it doesn't really make sense to me.

> How can we improve --help output? Currently yargs --help always displays for the top-level command and all other commands; ideally yargs default would only display for the top-level and otherwise display would be Prisma CLI help for specific commands E.g. yarn rw prisma db seed --help

Fixed!

> aliases, E.g. dev for migrate dev or push for db push (probably would need some switchin')

I think we should avoid this until we've got a better idea of how everything works and maybe until it becomes stable in Prisma.

**Comment by dthyresson** [comment]
Ran

`yarn rw prisma migrate dev --create-only`

Because my path has spaces and parentheses in it on OSX, I get and error seen before with storybook and other commands where the path isn't surroundend by quotes, etc.

```
$ '/Users/dthyresson/some path (with parens)/projects/redwoodjs/teams/node_modules/.bin/rw' prisma migrate dev --create-only
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `yarn prisma migrate dev --create-only --preview-feature --name migration --create-only --schema /Users/dthyresson/some path (with parens)/projects/redwoodjs/teams/api/db/schema.prisma'

...

Unknown arguments: create-only, createOnly, dev
error Command failed with exit code 1.

```

**Comment by dthyresson** [comment]
Also getting a warning message about ` @prisma/cli`

```
warn @prisma/cli has been renamed to prisma.
Please uninstall @prisma/cli: yarn remove @prisma/cli
And install prisma: yarn add prisma
Prisma schema loaded from db/schema.prisma
```

**Comment by dthyresson** [comment]
@thedavidprice Currently, I was unable to name a migration when issuing:

```
yarn rw prisma migrate dev --create-only
```

Responds with:

```
Prisma Migrate created the following migration without applying it 20210208124006_migration

You can now edit it....
```

Is this expected?
