### ISSUE TITLE
Typescript - refetchQueries not typed

### ISSUE THREAD

**Issue by noire-munich** [redwoodjs/redwood#1752]
`refetchQueries` is not typed so we get an error while in `.tsx` files.

Conversation moved from https://community.redwoodjs.com/t/is-refetchqueries-deprecated/1791/9

Also a PR for this #1751

**Comment by jtoar** [comment]
@dac09 does #2485 close this one?

**Comment by dac09** [comment]
Yep! We will now get `refetchQueries` as well as all the other Apollo client functions available to a Cell.
