### ISSUE TITLE
E2E Integration test is failed at `4. Getting Dynamic`

### ISSUE THREAD

**Issue by wafuwafu13** [redwoodjs/redwood#1754]
#### Do

Ref: https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md#integration-tests
```zsh
~/desktop/redwood
$ yarn build
$ ./tasks/test-tutorial
```

#### Result

<img width="748" alt="スクリーンショット 2021-02-08 12 17 49" src="https://user-images.githubusercontent.com/50798936/107172038-ade95f00-6a07-11eb-8689-82430e86a78f.png">

#### stack trace

```
  at <unknown> (http://localhost:8910/__cypress/runner/cypress_runner.js:156511:27)
From previous event:
    at Context.exec (http://localhost:8910/__cypress/runner/cypress_runner.js:156484:106)
From Your Spec Code:
    at Context.eval (webpack:///cypress/integration/tutorial/tutorial.js:83:8)
```

**Comment by wafuwafu13** [comment]
When I changed

https://github.com/redwoodjs/redwood/blob/e5cab915943228d85fb773c0bb47a45346194864/tasks/e2e/cypress/integration/tutorial/tutorial.js#L83-L88

to

```javascript
cy.exec(`cd ${BASE_DIR}; yarn rw db save`)
cy.exec(`cd ${BASE_DIR}; yarn rw db up`)
```

, error don't occured at `tutorial.js:83:8`, but different error occured.

<img width="1418" alt="スクリーンショット 2021-02-08 12 51 39" src="https://user-images.githubusercontent.com/50798936/107174314-433b2200-6a0d-11eb-84bc-0fb1bb0f50be.png">

#### log

```
api |
api | TypeError: Cannot read property 'findMany' of undefined
api |
api | at /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.Vz8NJSsP/api/src/services/posts/posts.js(Object.posts):4
api | 1  import { db } from 'src/lib/db'
api | 2
api | 3  export const posts = () => {
api | 4    return db.post.findMany()
api | 5  }
api | 6
api | 7  export const post = ({ id }) => {
api | 8    return db.post.findUnique({
api | 9      where: { id },
api |

...

api | TypeError: Cannot read property 'create' of undefined
api |
api | at /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.Vz8NJSsP/api/src/services/posts/posts.js(Object.createPost):14
api | 9       where: { id },
api | 10    })
api | 11  }
api | 12
api | 13  export const createPost = ({ input }) => {
api | 14    return db.post.create({
api | 15      data: input,
api | 16    })
api | 17  }
api | 18
api | 19  export const updatePost = ({ id, input }) => {
api |
```

**Comment by peterp** [comment]
Thanks for this! We're busy upgrading Redwood to the latest version of Prisma and the CLI has a bunch of breaking changes.

**Comment by thedavidprice** [comment]
When I merged https://github.com/redwoodjs/redwood/pull/1720 I updated the E2E tests and can confirm everything was passing.

I believe something is broken with the RW Prisma command since then but not with the E2E itself.

**Comment by thedavidprice** [comment]
@peterp confirming the E2E is broken now on latest canary. The error was related to Yargs parsing the Prisma command during Getting Dynamic.

I haven't been able to look into the specifics, but I'm assuming something happened here https://github.com/redwoodjs/redwood/pull/1750 Could you possibly take a look?

**Comment by thedavidprice** [comment]
This is resolved as of https://github.com/redwoodjs/redwood/pull/1761

@wafuwafu13 please do let us know if you have further issues. Thanks!
