### ISSUE TITLE
DB is not truncated after Scenario's were added

### ISSUE THREAD

**Issue by jvanbaarsen** [redwoodjs/redwood#1756]
After Redwood added the Scenario feature I'm noticing that my test DB is not being truncated in between tests. I look at the jest config and noticed that https://github.com/redwoodjs/redwood/commit/6823af340f6d1d511ebb22140e41f444230fe5a7#diff-7d9933d3f0db7efd0233969efe34fd5c90e97d5b8ab8755427beea8f038f0aa6L11 was previously responsible for clearing out the test DB.

I'm wondering if upgrading from an existing app, do I need to do anything else to make this work?

@cannikin I believe you were the original creator of this feature, maybe you can shed some light on this :)

**Comment by cannikin** [comment]
There's an open PR here that's hoping to improve the resiliency on the teardown: https://github.com/redwoodjs/redwood/pull/1714

Right now the scenario logic looks to see the name of every model that scenarios are created for, then issues a `DELETE` after the test is done. Someone pointed out (in that same PR above) that it isn't tracking any OTHER records you may have created during your test. For example, you're in the `User` tests (and have `User` scenarios) but you create a `Post`. It would still be there at the end of the test. Does this sound like what you're seeing, or something totally different?

**Comment by jvanbaarsen** [comment]
@cannikin Thanks for responding this quickly :-) I currently only have two models, I tried adding a scenario file for both of the models and change my tests from `it(...)` to `scenario(...), (scenario)`. 

The models are called users and tasks, so no pascal casing. 

Even after adding a scenario file for both the models the problem remains. I do think that the two issues are pretty much tied together somehow.

**Comment by jvanbaarsen** [comment]
After testing this with sqlite instead of postgres I'm sure the issues are related, since in sqlite everything works as expected!

**Comment by cannikin** [comment]
Ahhh that sounds like it might be the capitalization issue then. Hopefully that PR is just the medicine you need!

**Comment by jvanbaarsen** [comment]
@cannikin Yep, I'm keeping an eye on that PR, I'll make sure to check out canary once it is merged. When that is the fix I'll close this issue.

**Comment by jvanbaarsen** [comment]
With the latest release this has been fixed :)
