### ISSUE TITLE
Generated Component Template Breaks ESLint Rule

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#176]
See screenshot of component template below. It would make sense that our generators build templates that conform/pass tests and linters (in this case). 

Thoughts on prioritizing this (is it a real issue)? And/or thoughts on quick fix that still usefuly guides user as we’re trying to do here?

<img width="509" alt="Screen Shot 2020-03-04 at 10 24 18 AM" src="https://user-images.githubusercontent.com/2951/75911306-37f67400-5e04-11ea-9688-ab78fd68bbb2.png">

Something like this will work (maybe), but then we need to handle in test templates and… <begin javascript spiral>?
```javascript
const Foo = (props = Foo) => {
  return <>I am {props}.</>
}

export default Foo

```

**Comment by cannikin** [comment]
Yeah we should probably generate things that don't have any complaints. I'll update the template to remove that `props`.
