### ISSUE TITLE
Use createMany in Seed database example once out of Preview

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#1771]
Prisma 2.16 introduced a `createMany` function to efficiently bulk load data.

By using `createMany` one no longer has to iterate over a set of records to load data -- and no longer has to worry about Promises resolving per record creation.

It is also much much faster (according to Prisma).

Note in 2.16 seeds get created on `migrate reset`.

Example:

```
const result = await db.user.createMany({
  data: [
    { email: "alice@prisma.io" },
    { email: "mark@prisma.io" },
    { email: "jackie@prisma.io" },
    { email: "bob@prisma.io" },
  ],
})

console.log(`Created ${result.count} users!`)
```

However, since this feature is in preview right now (2.16), one must enable it with the createMany preview flag:

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["createMany"]
}
```

When `createMany` moves out of preview can consider modifying the `seed.js` accordingly -- and even possible loading json data and passing into createMany for an easier loading pattern.

**Comment by dthyresson** [comment]
For Postgres databases, one can use `skipDuplicates` to only create new records.

```
skipDuplicates?	
boolean
Do not insert records with unique fields or ID fields that already exist. Only supported by databases that support ON CONFLICT DO NOTHING.
```


```
const result = await db.user.createMany({
  data: [
    { email: "alice@prisma.io" },
    { email: "mark@prisma.io" },
    { email: "jackie@prisma.io" },
    { email: "bob@prisma.io" },
  ],
  skipDuplicates: true,
})
```

**Comment by simoncrypta** [comment]
I love the idea, we can maybe already add the example on the comment and replace 
```
  // existence of a record before trying to create it). For example:
  //
  //   const existing = await db.user.findMany({ where: { email: 'admin@email.com' }})
  //   if (!existing.length) {
  //     await db.user.create({ data: { name: 'Admin', email: 'admin@email.com' }})
  //   }
```
by something like 
```
  //existence of a record before trying to create it). For example:
  /*
    const result = await db.user.createMany({
      data: [
        { email: "alice@prisma.io" },
        { email: "mark@prisma.io" },
        { email: "jackie@prisma.io" },
        { email: "bob@prisma.io" },
      ],
    })
    console.log(`Created ${result.count} users!`)
  */
  // Note: To use createMany in Prisma you need to add previewFeatures flag in the schema.prisma file :
  /*
    generator client {
      provider        = "prisma-client-js"
      previewFeatures = ["createMany"]
    }
  */
```
I know that makes a long comment section, but I feel is something that many people want to know!

**Comment by dthyresson** [comment]
@simoncrypta Thanks! Want to take this on as a PR for release 0.25?

The file to change is: https://github.com/redwoodjs/redwood/blob/main/packages/create-redwood-app/template/api/db/seed.js

I think that comment section is a good place for the example that you showed.

Might:

* Not use prisma.io emails, but example.com
* Link to the [docs for createMany](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#createmany-preview): https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#createmany-preview
* Make note of `skipDuplicates` option

**Comment by simoncrypta** [comment]
@dthyresson Yes with pleasure and think you for the hint! I will work on it today.
