### ISSUE TITLE
Use Babel for Auto Importing instead of Webpack

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#178]
_This issue is non-urgent and can wait until after March 10th milestone._

This was initially attempted in #152 See attempted changes to `babel-preset.js` [here](https://github.com/redwoodjs/redwood/blob/d2c8a8e0025a71b91989ef19c765958ef4590b54/packages/core/config/babel-preset.js) and changes to `webpack.common.js` [here](https://github.com/redwoodjs/redwood/blob/d2c8a8e0025a71b91989ef19c765958ef4590b54/packages/core/config/webpack.common.js)

This implementation worked as expected for running Jest tests. However, the Babel setting to auto-import React was not working as expected — effectively React was not importing and the app throws errors when attempting to run `yarn rw dev`. This is the root cause of the browser console error reported [here](https://github.com/redwoodjs/redwood/pull/152#issuecomment-592287624).

The issue with using Babel to handle React auto-importing is possibly a conflict with our ESLint configuration. The plugin `bable-plugin-auto-import` describes a similar case for implementation with Create React App and gives explicit instruction for overriding config by disabling ESLint. Some related links:
- https://www.npmjs.com/package/babel-plugin-auto-import#using-with-create-react-app
- https://github.com/PavelDymkov/babel-plugin-auto-import/issues/5
- https://github.com/timarney/react-app-rewired#how-to-rewire-your-create-react-app-project

**To Consider:**
- Do we still want to move these types of setting from Webpack to Babel?
- If we move forward, we need to 1) determine why auto-import isn’t working as expected and 2) make sure our `yarn rw test` commands work as expected with any new config.

**Comment by peterp** [comment]
Closed by #193
