### ISSUE TITLE
convo: apollo network-and-cache / loading vs refetching networkStatus

### ISSUE THREAD

**Issue by wminshew** [redwoodjs/redwood#1781]
apollo triggers a loading state from `network-and-cache` even if some or all of the target [exists in cache](https://github.com/apollographql/apollo-client/issues/7605). I understand the cache policy was updated to avoid re-loading on mutations, but switching pages still triggers the loading state even if all of the page content is cached (a workaround I've been using is judiciously setting some queries to `fetchPolicy: cache-first`, but it's far from an ideal dev ux). I am not sure if [this](https://www.apollographql.com/docs/react/data/queries/#inspecting-loading-states) or [this](https://github.com/apollographql/apollo-client/issues/7605#issuecomment-777155518) are worth exploring/implementing, but wanted to start the conversation (apologies if I missed it elsewhere)

iiuc, a cell implementation that didn't trigger `Loading` components when `networkStatus === 4` would solve both the mutation and page switch issue

**Comment by jtoar** [comment]
@wminshew great catch and write up; sorry we didn't get to this sooner but #2641 will handle this!
