### ISSUE TITLE
Running tests while pointed to a postgresql database causes sql error 42P01 `relation "post" does not exist`

### ISSUE THREAD

**Issue by n-j-m** [redwoodjs/redwood#1782]
While following the Tutorial II I switched the database provider to postgresql instead of sqlite. When I got to _**Our First Test**_, some of the tests failed and I saw the error `relation "post" does not exist` in the terminal output.  I turned on query logging for the prisma client and received the output below.

![image](https://user-images.githubusercontent.com/411630/107612556-202a9100-6c0c-11eb-8209-80d0936bb576.png)

It seems that the SQL generated for the DELETE statement fails to properly quote and prefix the table name (`DELETE FROM post` instead of `DELETE FROM "public"."Post"`). This causes the SQL error and seems to cause the tests to fail.

I've created a repo from the code that was causing there error [here](https://github.com/n-j-m/redwood-tutorial).

Here's a gist of the [docker-compose file](https://gist.github.com/n-j-m/db2529e090146197776c2c293f5b2ef1) I'm using to run the postgres database.

**Comment by thedavidprice** [comment]
Hi there @n-j-m! Wondering if you set a test DB Env Var for your local Postgres? It's kind of a sneaky step -- maybe we could figure out a way to a) check what `schema.prisma` has as the Provider and b) confirm the Test DB connection string is a match... if not then message the user via console 🤔

Regardless, here's the Doc section:
https://redwoodjs.com/docs/local-postgres-setup#local-test-db

Does that do the trick?

**Comment by n-j-m** [comment]
@thedavidprice, I did set the `TEST_DATABASE_URL` env var in `.env.default`. I'm not sure that's the issue, however. Each time the tests execute, the test database is created (if it doesn't exist) and it leaves the scenario data in the `Post` table (because the delete fails).

I'm thinking the problem is in the [`teardown` function here](https://github.com/redwoodjs/redwood/blob/d61734296bf843d50933d36cabb2a9ea25ede919/packages/core/src/configs/node/jest.setup.js#L31). As you can see, the `teardown` function executes raw SQL to do the delete, whereas the `seedScenario` function uses the prisma ORM to insert the data. This raw delete SQL is not correct for postgresql since the `Post` table is created with a quoted, case-sensitive name. This also explains why this works for a SQLite database, which doesn't have case-sensitive table names.

**Comment by thedavidprice** [comment]
Super helpful @n-j-m 

The `teardown` function you referenced was just recently updated here https://github.com/redwoodjs/redwood/pull/1714 and released in [v0.25.0](https://github.com/redwoodjs/redwood/releases/tag/v0.25.0) just yesterday.

Can you confirm this is indeed still an issue with yesterday's v0.25 release? Fingers crossed the new function is the fix we need here 🤞

**Comment by jtoar** [comment]
I think this's been resolved; we've made several updates to teardown since, most notably:
- https://github.com/redwoodjs/redwood/pull/3716
