### ISSUE TITLE
cli storybook --open option is opposite

### ISSUE THREAD

**Issue by jangxyz** [redwoodjs/redwood#1783]
The cli storybook command provides `--open` option whether to open the browser on start:

```
# yarn rw sb --help
...
   --open     Open storybooks in your browser on start [boolean] [default: false]
...
```

But currently it *opens the browser by default (which is false), and does not open when `--open` is given*.

This happens because while the start-storybook `--ci` option in DOES NOT open browser when given:

```
# ./node_modules/bin/start-storybook --help
...
  --ci                          CI mode (skip interactive prompts, don't open browser)
...
``` 

The code is implemented the other way around. ([cli/src/commands/storybook.js@v0.24.0](https://github.com/redwoodjs/redwood/blob/502d11064d91927c4a1b5a9c91d310c55d45a3d6/packages/cli/src/commands/storybook.js#L50)):

```javascript
  execa(
    `yarn ${build ? 'build' : 'start'}-storybook`,
    [
      '--config-dir ../node_modules/@redwoodjs/core/config/storybook',
      // ...
      open && '--ci',
    ].filter(Boolean),
    {
      // ...
    }
  )
```

`--ci` should be given only when open is false (`!open`)

**Comment by jangxyz** [comment]
Though this is an easy fix -- literally a single character would be sufficient,
I wonder whether the idea in the first place was to set default as `true`, like the dev command.

The first ta-da moments are indeed impressive :)

On a side note, I think it is feasible that we add `!build` condition as well
since `build-storybook` does not provide `--ci`.

**Comment by peterp** [comment]
@jangxyz Thanks for this! I think when I wrote the storybook stuff that `--open` was not an available command. I agree that open should be the default and I agree that we shouldn't be sending the `--ci` option to Storybook.

**Comment by jvanbaarsen** [comment]
Submitting a PR for this 👍
