### ISSUE TITLE
(critical bug v0.25 canary) `rw prisma` append and prepend content is blocking interactive and throwing error

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1786]
@dac09 @dthyresson @peterp (Note: DT and I just worked through what's going on here).

## Problem
Using `0.25.1-canary.2`, which includes https://github.com/redwoodjs/redwood/pull/1785, interactive Prisma commands throw an error.

--> So a user **cannot** run interactive Prisma commands like `migrate dev`, `reset`, etc.

To reproduce:
- `rw upgrade -t canary`
- `rw prisma migrate reset` or `... migrate dev` if you don't have existing migrations

## Diagnosis
I believe the issue is actually with the _prepended_ content that displays the full CLI command with flags being run. In the case of `rw prisma migrate reset`:

1. we prepend the line:
```bash
Running prisma cli: 
yarn prisma migrate reset --preview-feature --schema "/Users/price/Repos/tdp-tutorial-blog-test/api/db/schema.prisma"
```
2. which causes Prisma to throw 'cause "non-interactive":
```bash
Error: We detected that your environment is non-interactive. Running this command in not supported in this context.
```
3. which also triggers our appended Redwood Tip, which will display on both `--help` and `error`:
```bash
...
🦺 Redwood CLI Tip    
```

<img width="892" alt="Screen Shot 2021-02-12 at 4 50 05 PM" src="https://user-images.githubusercontent.com/2951/107836823-4a3a9b00-6d53-11eb-95eb-19e8785c3991.png">

**Comment by dac09** [comment]
Added fix in PR above!
