### ISSUE TITLE
Exit status code is always zero for failed test in yarn rw test

### ISSUE THREAD

**Issue by brgmnn** [redwoodjs/redwood#1788]
When running `yarn rw test --no-watch` the status code is zero even if tests have failed. The output log states that the command failed with an exit code of 1 but upon inspecting the last command exit code (via `echo $?`) it's still zero. 

![image](https://user-images.githubusercontent.com/1955273/107837549-33e20e80-6d56-11eb-85fe-1c93d349220e.png)

Associated Redwood info:
```shell
 » yarn rw info
yarn run v1.22.10
$ /Users/daniel/Code/LoopUp/sherwood/sherwood-admin-ticket-portal/node_modules/.bin/rw info

  System:
    OS: macOS 10.15.7
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.3 - /var/folders/qn/40g470191zb8sqvzqhv9r2p80000gn/T/yarn--1613179197434-0.3059933859284285/node
    Yarn: 1.22.10 - /var/folders/qn/40g470191zb8sqvzqhv9r2p80000gn/T/yarn--1613179197434-0.3059933859284285/yarn
  Databases:
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Firefox: 85.0
    Safari: 14.0.3
  npmPackages:
    @redwoodjs/core: 0.23.0 => 0.23.0

✨  Done in 3.14s.
```

**Comment by dac09** [comment]
Thanks for raising this @brgmnn. Between us Daniels, we'll get this fixed ;)

**Comment by dthyresson** [comment]
@dac09 and @jvanbaarsen This issue I believe is the same? https://github.com/redwoodjs/redwood/issues/1794

**Comment by jvanbaarsen** [comment]
@dthyresson I'm not sure, I'm seeing a different error. I'd keep both open and test when the fix comes out.
