### ISSUE TITLE
RW Prisma commands don't seem to work in combination with RWT

### ISSUE THREAD

**Issue by jvanbaarsen** [redwoodjs/redwood#1794]
I'm trying to debug a couple of things in my app, so I'm using the `rwt copy` way of syncing my local checked out version of Redwood to my project. I noticed that all the CLI commands seem to work except the ones that interact with Prisma, in those cases I get this error:

```
› yarn redwood prisma
yarn run v1.22.10
$ /Users/jeroen/Development/rw-scenarios/node_modules/.bin/redwood prisma
Running prisma cli:
yarn prisma

/Users/jeroen/Development/rw-scenarios/node_modules/yargs/yargs.js:1172
      else throw err
           ^

TypeError: innerYargs._parseArgs is not a function
    at Object.runCommand (/Users/jeroen/Development/rw-scenarios/node_modules/yargs/lib/command.js:200:45)
    at Object.parseArgs [as _parseArgs] (/Users/jeroen/Development/rw-scenarios/node_modules/yargs/yargs.js:1087:30)
    at Object.get [as argv] (/Users/jeroen/Development/rw-scenarios/node_modules/yargs/yargs.js:1021:21)
    at Object.<anonymous> (/Users/jeroen/Development/rw-scenarios/node_modules/@redwoodjs/cli/dist/index.js:20:171)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The problems seems to be on this line: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/prisma.ts#L101.

I noticed a PR was created to improve on this command a bit, so I also tested it against that pr (#1790), but that didn't change anything problem persists.

## Reproduce steps:

1. Check out latest main for redwood repo
2. Run `yarn build:watch`
3. Have a RW project and run `rwt copy:watch` in that project
4. run the command `rw test` or `rw prisma` (anything really that interacts with Prisma)

**Comment by jvanbaarsen** [comment]
What do ya know.. Writing down your issues helps :) It turned out I had a global installed @prisma/cli version on my system which was shimmed with asdf. Removed it and reshimmed everything and now it works like a charm.

Closing

**Comment by dac09** [comment]
@jvanbaarsen sent you a message on discord. Can't repro using a fresh redwood app.

**Comment by dac09** [comment]
I think I found the issue - it only pops up under the contributor workflow (strange right?!). I think its to do with the version of execa being invoked.

**Comment by jvanbaarsen** [comment]
@dac09 Yeah it only happens in the contributor flow I think. I'll double check if it also happens against canary.

**Comment by dac09** [comment]
Once you confirm I'll add the fix to my hotfix branch!

**Comment by thedavidprice** [comment]
Recommended `rwt` flow to use is now `rwt link`, which has been greatly improved since this issue was opened. And all Redwood CLI commands are working accordingly.
