### ISSUE TITLE
Convert `cli/commands/prisma.ts` back to `.js`

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#1797]
The CLI package is not a TypeScript project and we don't have plans to convert it to TypeScript just yet. The fact that it compiles is a fluke of babel. 

If we want types let's use JSDocs!

**Comment by saideepesh000** [comment]
Hey @peterp @thedavidprice, can I work on it

**Comment by thedavidprice** [comment]
@saideepesh000 Yes please! Assigning to you now.
