### ISSUE TITLE
Only allow a function for the `standard` export in mock files.

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#1801]
In the past we allowed an object to be exported from standard, in order to simplify the differences in the code we're going to require that it's a function.

```
// MyCell.mock.js

// we allowed this in the past
export const standard = { test: { id: 42 } }


// NOW we will require it to be a function
export const standard  = () => ({ test: { id: 42 } })
```

**Comment by peterp** [comment]
https://github.com/redwoodjs/redwood/pull/1740/files#r577359361

**Comment by thedavidprice** [comment]
@peterp any change you'd be available to work on this for inclusion in the next release? (ETA before Thanksgiving)

@jtoar could also help if/as needed.

**Comment by peterp** [comment]
@thedavidprice Sorry, I'm not available

**Comment by thedavidprice** [comment]
💯understood @peterp 

What do you think about taking this on @jtoar?
