### ISSUE TITLE
@typescript-eslint mismatch with eslint

### ISSUE THREAD

**Issue by jangxyz** [redwoodjs/redwood#1802]
I've noticed at least some rule for @typescript-eslint does not match the one with eslint:

[eslint-config/index.js](https://github.com/redwoodjs/redwood/blob/d25b1eca452c9725b36788e890140ce4396263e7/packages/eslint-config/index.js#L115-L117):
```javascript
  'no-unused-vars': [
    'error',
    { varsIgnorePattern: '^_', argsIgnorePattern: '^_' },
  ]
```

but no corresponding rule for typescript.

It's no big deal extending my `package.json` to handle this,
```json
...
  "eslintConfig": {
    "extends": "@redwoodjs/eslint-config",
    "rules": {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { "varsIgnorePattern": "^_", "argsIgnorePattern": "^_" },
      ]
    }
  }
...
```
I just thought it would make more sense if rw supports it out of the box.

I am not aware if any other typescript rules are mis-aligned as well or not.

**Comment by peterp** [comment]
🤦 Would you mind opening a PR and adding this?

**Comment by jangxyz** [comment]
Not at all. Here you go.
