### ISSUE TITLE
Need to include the scenario seeding function in try/catch

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#1804]
https://github.com/redwoodjs/redwood/blob/main/packages/core/src/configs/node/jest.setup.js#L76-L81

This chunk of code makes sure that an error in a test still causes the scenario data to be removed afterwords. However, if there is an error with the seeding process itself, the error is *not* caught and some records will remain in the database.

We need to either add a try/catch around this line of code, or just move it into the try/catch that's immediately following it:
https://github.com/redwoodjs/redwood/blob/main/packages/core/src/configs/node/jest.setup.js#L75

**Comment by agiannelli** [comment]
🙋‍♀️

**Comment by cannikin** [comment]
You got it!

**Comment by cannikin** [comment]
P.S. Meant to include a link to this earlier, it shows how to use your local copy of the Redwood repo in an app for quick testing: https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md

We've been seeing `yarn rwt copy:watch` randomly error out in the middle of copying so if a change you made doesn't seem to be working in the app, check that that process is still running! If it gets to be too annoying you can just `yarn rwt copy` manually each time after making a change to the repo code and waiting for the build over there to complete.

Let us know if you get stuck anywhere, trying to get this running the first time is tough, I had to ask @peterp to explain the process to me on like four separate occasions (sorry Peter)!

**Comment by cannikin** [comment]
Closed by #1818
