### ISSUE TITLE
Update scenario syntax to allow extra options to be passed to `create`

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#1805]
## Problem

According to these docs, it's possible to pass extra options besides `data` when creating a new record:

https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries#create-a-related-record

(The example uses `include` to be sure that the nested records' data is also returned.) Right now we take the scenario object and set it as the `data` key automatically, but this provides no way to include these additional options.

Current syntax:

```javascript
export const standard = defineScenario({
  comment: {
    jane: {
      name: 'Jane Doe',
      body: 'I like trees',
      post: {
        create: {
          title: 'Redwood Leaves',
          body: 'The quick brown fox jumped over the lazy dog.',
        },
      },
    },
  }
})
```

We end up passing this off to prisma by doing:

```javascript
import { standard } from 'comment.scenario'

db['comment'].create({ data: standard.comment.jane })
```

This syntax provides no room to pass additional keys in addition to `data`

## Proposed Solution

If we just go up a level and have the scenario define the data key, it can define additional ones as well:

```javascript
export const standard = defineScenario({
  comment: {
    jane: {
      data: {
        name: 'Jane Doe',
        body: 'I like trees',
        post: {
          create: {
            title: 'Redwood Leaves',
            body: 'The quick brown fox jumped over the lazy dog.',
          },
        },
      },
      include: { posts: true }
    }
  }
})
```

And then we simply update the scenario creation code to:

```javascript
db['comment'].create(standard.comment.jane)
```

This assignment happens here: https://github.com/redwoodjs/redwood/blob/main/packages/core/src/configs/node/jest.setup.js#L16

## Generators/Templates

We'll need to update the scenario template for this new syntax as well. The code the generates the scenario object lives here: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/service/service.js#L87-L91

**Comment by mojombo** [comment]
That seems reasonable and is quite easy to understand.

**Comment by jvanbaarsen** [comment]
This would be great to have! Right now you need to do data fetching if you run into this situation :+1:

**Comment by thedavidprice** [comment]
fixed in https://github.com/redwoodjs/redwood/pull/1818

**Comment by cannikin** [comment]
Hmm, I may have linked the wrong issue @thedavidprice. That teardown fix would NOT close this one, sorry!

**Comment by cannikin** [comment]
It was #1804!

**Comment by agiannelli** [comment]
I'll take it!

**Comment by thedavidprice** [comment]
@agiannelli thank you 🚀

**Comment by thedavidprice** [comment]
@agiannelli Took this one off your to-do list for now. Just let me know if anything changes! No pressure either way.

**Comment by callingmedic911** [comment]
Hello @cannikin @thedavidprice, I'd be glad to give this a try this weekend. Is it okay to pick this one up?

**Comment by cannikin** [comment]
Absolutely!

**Comment by cannikin** [comment]
We'll need to include a nice chunk of Release Notes for this one, since anyone using scenarios will need to update *all* of them to include the new nested `data` object.
