### ISSUE TITLE
What about Tom's association with Gravatar?

### ISSUE THREAD

**Issue by bl-ue** [redwoodjs/redwood#1811]
I thought @mojombo was associated with Gravatar (used by many, many services).  In this fantastic brag :smile: I don't see any such reference.  Mistake?
 
>Redwood is the latest open source project initiated by Tom Preston-Werner, cofounder of GitHub (most popular code host on the planet), creator of Jekyll (one of the first and most popular static site generators), author of the Semantic Versioning specification (powers the Node packaging ecosystem), and inventor of TOML (an obvious, minimal configuration language used by many projects).

**Comment by thedavidprice** [comment]
Ha! You are correct, indeed. He created Gravatar and sold it to Automattic (the Wordpress folks). 

Want to take a stab at adding that via a PR? It could be as simple as adding `creator of the avatar service Gravatar` after the `creator of Jekyll` phrase.

Doc is here: https://github.com/redwoodjs/redwood/blob/main/README.md

And PR submission is 💯 welcome! (But never with any pressure.)

**Comment by bl-ue** [comment]
Sure @thedavidprice, I'll open a PR right now.
