### ISSUE TITLE
Allow running a single test by file path

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#1812]
It would be nice if you could run only a single file with our test runner… you can normally with Jest, but we’ve intercepted the second argument and require that it either be web or api to run the suite for one whole side:

```
rob$ yarn rw test web/src/components/Article/Article.test.js

Invalid values:
  Argument: side, Given: "web/src/components/Article/Article.test.js", Choices: "web", "api"
```

I'm guessing this is a yargs thing...instead of requiring one or the other we should allow *anything* and then do a little additional work to determine if it's a valid side, otherwise assume it's a full path to a file.

**Comment by peterp** [comment]
It would be amazing if we wrapped Jest the same way that we're wrapping Prisma's commands. So that you can pass any default arguments, but we provide some sane defaults for Redwood's context.

**Comment by cannikin** [comment]
So the command would become `yarn rw jest`?

**Comment by jvanbaarsen** [comment]
@cannikin wouldn't we be able to alias `rw jest` to `rw test`?

**Comment by cannikin** [comment]
That's what we're doing now, but from @peterp's comment it sounds like he's suggesting doing what we do for Prisma: we used to have `yarn rw db` but we got rid of that and as of 0.25 just proxy to the *real* Prisma commands with `yarn rw prisma`. This makes it easier to find documentation and not worry about trying to keep up with Prisma's changing migrate API.

**Comment by jvanbaarsen** [comment]
What I meant was to still proxy the command over to `jest`, but then do that with `test`. So basically everything behind `rw test` will be forwarded to `yarn run jest`

**Comment by cannikin** [comment]
Yep we definitely could, I'm just not sure  how literal @peterp was being! :)
