### ISSUE TITLE
Setting "typeRoots" in tsconfig.json for jest

### ISSUE THREAD

**Issue by jangxyz** [redwoodjs/redwood#1820]
I am trying to make vscode understand `describe`, `it` and etc for test files, but following [the document on typescript](https://redwoodjs.com/docs/typescript#web) did not help.

![image](https://user-images.githubusercontent.com/52015/108490340-0103c180-72e6-11eb-980d-0fefe2839c2a.png)

Googling around for couple of hours, I [found out](https://github.com/kulshekhar/ts-jest/issues/889) that setting `compilerOptions.typeRoots` option to something else prevents from finding jest types.

From the [tsconfig docs](https://www.typescriptlang.org/tsconfig#typeRoots): 
> By default all visible ”`@types`” packages are included in your compilation. Packages in `node_modules/@types` of any enclosing folder are considered visible. For example, that means packages within `./node_modules/@types/`, `../node_modules/@types/`, `../../node_modules/@types/`, and so on.
> 
> If `typeRoots` is specified, _only_ packages under `typeRoots` will be included.

`typeRoots` is currently set to "`../.redwood`", which I guess is mainly for types built by redwood like routes, but this is blocking the default behavior.

I have actually succeeded on removing errors by commenting out the `typeRoots` option.

![image](https://user-images.githubusercontent.com/52015/108491367-28a75980-72e7-11eb-8bbe-ecd168949fb6.png)

(Which I guess means that I can't use named routes)

I don't know if I can set the default behavior of recursively searching for `node_modules/@types`, but I'm assuming setting only for the root directory will be fine for redwood?

```js
...
  "typeRoots": ["../.redwood", "../node_modules/@types"],
...
```

This is the same issue with https://github.com/redwoodjs/redwood/issues/1400#issuecomment-719673834 . I don't know if others are having same issues -- vscode errors seem to pop all over the place. If it is a common issue, I wonder if this can be included in the docs.

**Comment by Tobbe** [comment]
`"typeRoots": ["../.redwood", "../node_modules/@types"],` looks good to me. But I'd wait for @peterp and/or @dac09 to comment as well.

If they don't see any problems with this it should definitely be added to https://redwoodjs.com/docs/typescript#web

**Comment by peterp** [comment]
👍 This is the way.

**Comment by peterp** [comment]
@jangxyz Would you be keen to open a PR for this?

**Comment by realStandal** [comment]
Ran into this as well and just wanted to make sure API's `tsconfig` isn't left out of the party :)
