### ISSUE TITLE
Why using backticks, when single quotes are just fine

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood#1825]
Running the command `yarn create redwood-app ./redwoodblog` results with these log messages:
```
  √ Creating Redwood app
    √ Creating directory 'c:\work\learning\redwood\redwoodblog'
  > Installing packages
    √ Checking node and yarn compatibility
    / Running `yarn install`... (This could take a while)
```
Note that the last line uses backticks instead of single quotes, it is likely a typo.

**Comment by jvanbaarsen** [comment]
Hi @adriatic 👋,

Looking at the code I think this was done because otherwise we had to escape the character. The reason it is with `'` in the `creating directory` line is because we do a string interpolation there.

If you're up for it, can you create a PR to make this in line?

**Comment by adriatic** [comment]
Hello, @jvanbaarsen Jeroen

Can you point me to the location where this code leaves (it would be nice if one could run 'grep' from the browser pointing to the redwood repo)?

**Comment by Tobbe** [comment]
> Note that the last line uses backticks instead of single quotes, it is likely a typo.

I don't think it's a typo. Backticks are used to indicate code or a command. Something executable.

**Comment by jvanbaarsen** [comment]
@Tobbe Ah yeah that makes sense.
