### ISSUE TITLE
Support Netlify Dev Live Site Forwarding by configuring netlify.toml

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#1831]
Netlify Dev 

https://www.netlify.com/products/dev/

supports live streaming/forwarding to localhost.

However, a few configuration settings are necessary and the `netlify.toml` can be updated to support it:

```
[dev]
  # Note be sure to `netlify link` your site first
  command = "yarn rw dev"
  framework = "#custom"
  targetPort = 8910 # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on
```

**Comment by jtoar** [comment]
Also adding this here, cause important: netlify dev might be needed for the IDE.

**Comment by dthyresson** [comment]
This was completed as part of Netlify toml rework and Redwood framework detection.

See: https://github.com/redwoodjs/redwood/pull/2712
