### ISSUE TITLE
netlify identity tokens need to be refreshed

### ISSUE THREAD

**Issue by benatkin** [redwoodjs/redwood#1833]
[I'm discussing on the forum.](https://community.redwoodjs.com/t/should-development-mode-mean-all-bets-are-off-netlify-identity/1857/7) I've been debugging it long enough that I think the issue exists. I should have complete answers soon, but I thought I would start an issue now.

I've checked several times that I'm using Netlify Identity Widget with Redwood according to the docs, yet after a delay I keep finding myself partially or completely logged out. I just tracked it down to an expired token.

I think this is partly an upstream issue, but I don't think `netlifyIdentity.currentUser()` returns a promise, so `await netlifyIdentity.currentUser()` isn't sufficient to get a fresh token. I think `await netlifyIdentity.currentUser?.jwt?()` is.

Sorry for the partial message. I'm working on fixing the issue [my project](https://github.com/ResourcesCo/app) and will provide more info as I get it.

**Comment by benatkin** [comment]
[currentUser in netlify-identity-widget](https://github.com/netlify/netlify-identity-widget/blob/master/src/netlify-identity.js#L48) calls [currentUser](https://github.com/netlify/gotrue-js/blob/master/src/index.js#L114) which calls [User.recoverSession](https://github.com/netlify/gotrue-js/blob/master/src/user.js#L26) and none appear to return promises

**Comment by benatkin** [comment]
[Here's where our netlify authClient it gets the token by calling currentUser](https://github.com/redwoodjs/redwood/blob/main/packages/auth/src/authClients/netlify.ts#L45)

**Comment by benatkin** [comment]
[I also reported it upstream, since redwood seems to be doing the same thing the react example in netlify-identity-widget.](https://github.com/netlify/netlify-identity-widget/issues/433)

**Comment by benatkin** [comment]
I was able to fix it in my app by overriding `currentUser` in the `client` passed to `AuthProvider` and making it await on `jwt()` before the promise:

```jsx
import netlifyIdentity from 'netlify-identity-widget'

const currentUser = async () => {
  const currentUser = netlifyIdentity.currentUser()
  if (typeof currentUser?.jwt === 'function') {
    console.log('awaiting currentUser.jwt() before returning currentUser')
    await currentUser.jwt()
  }
  return currentUser
}

const netlifyIdentityWrapped = new Proxy(netlifyIdentity, {
  get(target, name) {
    return name === 'currentUser' ? currentUser : target[name]
  },
})

ReactDOM.render(
  <FatalErrorBoundary page={FatalErrorPage}>
    <AuthProvider client={netlifyIdentityWrapped} type="netlify">
      <RedwoodApolloProvider>
        <Routes />
      </RedwoodApolloProvider>
    </AuthProvider>
  </FatalErrorBoundary>,
  document.getElementById('redwood-app')
)
```

**Comment by dthyresson** [comment]
@benatkin 
Do you think your example

```js
 const currentUser = netlifyIdentity.currentUser()
  if (typeof currentUser?.jwt === 'function') {
    console.log('awaiting currentUser.jwt() before returning currentUser')
    await currentUser.jwt()
  }
  return currentUser
```

which I saw similar code for in https://github.com/netlify/gotrue-js/issues/71#issuecomment-697464294

should be part of the

```js
    restoreAuthState: async () => {
      return client.currentUser()
    },
```

for the netlify AuthProvider?

https://github.com/redwoodjs/redwood/blob/f9524ac61bbf9c2621620ba3f853849a37364c41/packages/auth/src/authClients/netlify.ts#L50

**Comment by benatkin** [comment]
Yeah, it seems like with my fix there could be a delay.

Would the restoreAuth solution work after having the site open for over an hour, which is how long before tokens need to be refreshed?

If not, perhaps calling jwt() in both restoreAuth and getToken is needed.

My proxy patch is working all the time except it glitched once. I can try returning a proxied currentUser in my proxy which proxies token to a proxy which proxies accessToken to the value obtained from jwt() and see if that fixes it more.

**Comment by benatkin** [comment]
It's on https://app.resources.co/ by the way. Anyone can sign in with GitHub.

**Comment by dthyresson** [comment]
@benatkin There have been some improvement made to token refreshing sinch this issue came up.

Can we confirm it is still an issue in v0.33.2+?

Thanks!
