### ISSUE TITLE
we broke Scaffold `useFlash`

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1839]
For Scaffolded UI, we include `useFlash` for all CRUD. However, Flash messages no longer appear for each case:
- Create (`NewPost.js`) = ⛔ 
- Read = NA
- Update (`EditPostCell.js`) = ⛔ 
- Delete (`Post.js`) = ⛔ 
- Delete (`Posts.js`) = ✅ 

The Contact Submit Flash message is working correctly. 

My suspicion is that we broke this sometime during the Apollo v3 upgrade process.

## Video Demo of missing Flash messaging

https://user-images.githubusercontent.com/2951/108792379-f8a1c580-7535-11eb-88e1-fca8cf1d4ca4.mov

**Comment by cannikin** [comment]
Maybe related to https://github.com/redwoodjs/redwood/issues/1701

We kind of came to the conclusion to replace ours with https://react-hot-toast.com/

**Comment by thedavidprice** [comment]
'cause Hot Toast is the best. name. ever.

**Comment by Burnsy** [comment]
We have been using react-hot-toast as a replacement for use flash and its been splendid.

**Comment by cannikin** [comment]
While we're up for breaking things, I'm thinking I'll just use the real API from react-hot-toast rather than trying to proxy everything through our stuff like `useFlash` and `addMessage`. Should we have people import from `react-hot-toast` or do we import/export ourselves in `@redwoodjs/web` so you still import from there?

If I can figure out how to do it, I'll forward messages from `addMessage` to `toast` but output a big warning to the console to let people know that they should be using the real toast API and ours will be going away as of v1.0.

**Comment by cannikin** [comment]
@peterp How do you feel about adding react-hot-toast to `web`? Or should we make it a separate package like `forms` to save package sizes for those that end up not using it? Looks like the compiled size of the production, gzipped minified bundle is 3.5kb. 11kb before gzip.

**Comment by peterp** [comment]
I'm using it on Snaplet as well and it's awesome!

> If I can figure out how to do it, I'll forward messages from addMessage to toast but output a big warning to the console to let people know that they should be using the real toast API and ours will be going away as of v1.0.

Sounds like a plan!

**Comment by Burnsy** [comment]
Maybe it would just be best to cut it out and just recommend it in a cookbook, as then redwood does not need to worry about wrapping it and keeping it up to date! @peterp @cannikin

**Comment by cannikin** [comment]
We do want something nice in the scaffolds though...

I was planning on just importing * and exporting everything back out in `@redwoodjs/web` so you would use the native interface. I was just going to wrap for pre-v1.0 so people that are currently using `<Flash>` aren't screwed.

**Comment by Burnsy** [comment]
I think opt in could work nicely like forms so if you wanted to just use it by its self there would not be a problem, or you could use the wrapper if wanted!
