### ISSUE TITLE
Unsupported syntax used in common webpack config

### ISSUE THREAD

**Issue by jth0024** [redwoodjs/redwood#1880]
**System Info**
* Mac OS 10.15.5
* Node v12.16.2

**Steps To Reproduce**

1. Run `yarn create redwood-app`
2. Run `yarn redwood dev`

**Expected Behavior**
The app starts and opens in a new window

**Actual Behavior**
The app crashes due to the nullish coalescing operator being used in the `@redwoodjs/core/config/webpack.common.js`. This operator was not supported until node v14.5.x.

**Comment by brentjanderson** [comment]
I experienced this as well with the move to redwood v0.26 today. Upgraded to v14 to fix it, but that may have broken other things in my workflow at the same time.

**Comment by thedavidprice** [comment]
Great catch! Working on a fix and patch release now!!

**Comment by thedavidprice** [comment]
full error:
```bash
web | /Users/price/Repos/xx-delete/node_modules/@redwoodjs/core/config/webpack.common.js:175
web |         redwoodPaths.web.index ??
web |                                 ^
web |
web | SyntaxError: Unexpected token '?'
web |     at wrapSafe (internal/modules/cjs/loader.js:915:16)
web |     at Module._compile (internal/modules/cjs/loader.js:963:27)
web |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
web |     at Module.load (internal/modules/cjs/loader.js:863:32)
web |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
web |     at Module.require (internal/modules/cjs/loader.js:887:19)
web |     at require (internal/modules/cjs/helpers.js:74:18)
web |     at Object.<anonymous> (/Users/price/Repos/xx-delete/node_modules/@redwoodjs/core/config/webpack.development.js:7:23)
web |     at Module._compile (internal/modules/cjs/loader.js:999:30)
web |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by thedavidprice** [comment]
Patched! Thanks, all.

https://github.com/redwoodjs/redwood/releases/tag/v0.26.2
