### ISSUE TITLE
Router Docs - Remove idea of sharing router outside of Redwood

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#1888]
From @peterp via Discord when asked why

> Just curious: why is [this section](https://redwoodjs.com/docs/redwood-router#installation-and-use-outside-of-a-redwood-app) about RR written?

that could allow the router to be used in a non-RWJS project

> We've pretty much abandoned the idea of sharing that outside of Redwood, we should remove that.

See: https://github.com/redwoodjs/redwood/blob/main/packages/router/README.md#installation-and-use-outside-of-a-redwood-app

```
If you'd like to use RR in a non-Redwood app, you can! Start by installing it:

$ yarn add @redwoodjs/router
```

It is suggested that this section be removed from the docs.

**Comment by Tobbe** [comment]
Closed by #1900
