### ISSUE TITLE
Error in the initially creatated redwoodblog app

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood#1889]
**Context**:
Run `yarn create redwood-app ./redwoodblog`

Then: 
```
cd redwoodblog
yarn redwood dev
```

Press F10 (open [chrome developer tools](https://developers.google.com/web/tools/chrome-devtools/open)) and observe:

![image](https://user-images.githubusercontent.com/2712405/109427753-d2f73f00-79c1-11eb-91cb-e192baca9d66.png)

```
index.js:1 Warning: Expected server HTML to contain a matching <main> in <div>.
    in main (created by SplashPage)
    in SplashPage (created by RouterImpl)
    in RouterImpl (created by LocationProvider)
    in LocationProvider (created by Context.Consumer)
    in Location (created by Router)
    in Router (created by Routes)
    in Routes (created by App)
    in FlashProvider (created by RedwoodApolloProvider)
    in GraphQLHooksProvider (created by RedwoodApolloProvider)
    in ApolloProvider (created by ApolloProviderWithFetchConfig)
    in ApolloProviderWithFetchConfig (created by RedwoodApolloProvider)
    in FetchConfigProvider (created by RedwoodApolloProvider)
    in RedwoodApolloProvider (created by App)
    in FatalErrorBoundary (created by App)
    in App
```
---

yarn run v1.22.5
$ c:\work\rw-samples\redwoodblog\node_modules\.bin\rw info

  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 12.19.0 - ~\AppData\Local\Temp\yarn--1614533972588-0.5906548225930557\node.CMD
    Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1614533972588-0.5906548225930557\yarn.CMD
  Browsers:
    Chrome: 88.0.4324.190
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.81)
  npmPackages:
    @redwoodjs/core: ^0.26.2 => 0.26.2

Done in 3.27s.

---

Note: creation of the first page (`yarn redwood generate page home /`) removes the issue reported above and introduces the problem reported in [Cannot find module '~__REDWOOD__USER_ROUTES_FOR_MOCK'](https://github.com/redwoodjs/redwood/issues/1887), confirmed by @Tobbe:

![image](https://user-images.githubusercontent.com/2712405/109428247-41d59780-79c4-11eb-8b1c-1f5dd2645ef4.png)

**Comment by dac09** [comment]
Closing this as it duplicates #1894 and #1887, and the other issues have conversations.
