### ISSUE TITLE
Exposing useLazyQuery to allow for integration with promise-based packages

### ISSUE THREAD

**Issue by semagraph** [redwoodjs/redwood#1893]
I've recently been trying to integrate react-select into redwood in order to write a cookbook, however react-select (https://react-select.com/home#async) (and many other libraries) require a promise-based functions. Redwood uses the Apollo Client's useQuery hook, which is not promised based and instead returns { loading, error, data } (https://www.apollographql.com/docs/react/data/queries/). I did checked if useLazyQuery was exposed, but it doesn't seem to be. However exposing it would allow for a drop-in replacement to useQuery, and would mitigate the need for writing a promise-based handler and using another graphql client (e.g. graphql-request).

This would allow redwood users to do something like:

```
const GET_PRODUCTS = gql`...`

function ProductSelect() {
    const [query, setQuery] = useState('')
    const [loadProducts, { called, loading, data }] = useLazyQuery(
        GET_PRODUCTS,
        { variables: { query: query } }
      );
    
    return (
      <AsyncSelect loadOptions={loadProducts} />
    )
}
```
instead of having to setup of a promise-based handler.

**Comment by o0charlie0o** [comment]
For what it's worth useLazyQuery used to be exposed and only recently was taken out. We use it and had to switch to importing it from @apollo/client.

**Comment by semagraph** [comment]
Interesting, seems like it was removed, merged again in september (https://github.com/redwoodjs/redwood/commit/ca3c54644d108025061f2914800fe834651be978), and then removed again since then

**Comment by thedavidprice** [comment]
Ah, looks like this change is related to the Apollo Client v3 upgrade. I believe we attempted `import * from '@apollo/client' but ran into significant issues with the way Appollo changed their exports. (Or possible it was a change related to limiting initial package import size.) Then we recently separated Apollo Client to provide support for swapping the GraphQL client.

Here's where the imports are currently located in `@redwoodjs/web/apollo`: https://github.com/redwoodjs/redwood/blob/main/packages/web/src/apollo/index.tsx

@peterp could you confirm the reasoning behind selecting a limited set of imports? And/or ideas about how we could make it more clear which packages are being imported directly + simply instructions to to import others?

**Comment by peterp** [comment]
We placed it in a sub-folder because we want to reduce the bundle size for people who do not use Apollo.

**Comment by Tobbe** [comment]
As others have said, we use `@apollo/client` by default in new RW projects. But we have recently made it possible for projects to replace that, and use whatever gql client they want. To facilitate this we wanted to be as client agnostic as possible, and one thing we did to accomplish that was to limit the gql client exports we expose to the bare minimum (`useQuery` and `useMutation`). It's also those we let you provide over-rides for when configuring your own client.

That being said, an even more recent change is to move all of the apollo-specific code to `@redwoodjs/web/apollo`, so now we could reexport everything from apollo from there without tying the internals of RW to apollo.
BUT
We have kind of the same story with `react-hook-form` which we use internally for our `@redwoodjs/forms` package. And there we encourage people for import straight from `react-hook-form` if they need any of the advanced functionality (see https://redwoodjs.com/tutorial/saving-data#one-more-thing)

So, I vote we keep it as it is, but just like we do for r-h-f, maybe mention somewhere that you can import ac directly for additional functionality.

**Comment by semagraph** [comment]
I'm satisfied with that, so client.query is seems to be the best solution in this case. For those that are interested, this is what a usage example would look like:

`
  import { useApolloClient } from '@apollo/client'

  const SelectWrapper = () => {
    const client = useApolloClient()
  
    const loadOptions = async (inputValue) => {
      const { data } = await client.query({
        query: GET_PRODUCTS,
        variables: { query: inputValue },
      })
  
      return data.products.map((product) => {
        return { label: product.name, value: product.id }
      })
    }
  
    return (
          <AsyncSelect
            loadOptions={(value) => fetchOptions(value)}
          />
    )
  }
`

**Comment by thedavidprice** [comment]
Thanks all. I've continued discussion about how to better document this information over here https://github.com/redwoodjs/redwoodjs.com/issues/604
