### ISSUE TITLE
ASK: Deploy Redwoodjs with Cloudflare Page

### ISSUE THREAD

**Issue by muhrusdi** [redwoodjs/redwood#1899]
Can i deploy the redwood app to the cloudflare page?

**Comment by thedavidprice** [comment]
Hi @muhrusdi To the best of my knowledge, no one has tried to deploy Redwood on Cloudflare. Personally, I am a big fan of their products. However, their alternative to AWS Lambdas, which is Cloudflare Workers, is a [V8 runtime](https://developers.google.com/apps-script/guides/v8-runtime), which is _not_ the same as a Node.js runtime. This means the Redwood API will most likely not run on Cloudflare Workers. In the case of a very simple app, it might be fine. But once you add things like Prisma Client it's almost sure to fail.

If you wanted to run an experiment, you could try to deploy Redwood's Web side to Cloudflares CDN and the API site directly to AWS Lambdas using [these instructions](https://redwoodjs.com/docs/deploy#aws-serverless-deploy) for a Redwood AWS deploy target.

I'm closing this Issue for now, but don't hesitate to continue the conversation. The Redwood [Forums](https://community.redwoodjs.com) or [Chat](https://discord.gg/redwoodjs) could be great places to see if anyone in the community is interested in this topic as well.

**Comment by methyl** [comment]
FWIW, it seems Prisma supports Cloudflare Workers now: https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-cloudflare-workers

**Comment by MzicoDim** [comment]
Waking up this old issue because Cloudflare has been adding Node compatibility and TCP sockets to workers over the past couple weeks:

https://blog.cloudflare.com/workers-node-js-asynclocalstorage/
https://blog.cloudflare.com/workers-node-js-apis-stream-path/
https://developers.cloudflare.com/workers/platform/changelog/#2023-05-16

**Comment by brendonmatos** [comment]
With unjs toolkit, more specifically with unjs/unenv and unjs/nitrojs this could be possible.
#6923
