### ISSUE TITLE
Apollo Devtools couldn't detect Apollo Client

### ISSUE THREAD

**Issue by andrew-hwahin** [redwoodjs/redwood#1901]
Have anyone managed to use the Apollo Devtools with Redwood app?

![image](https://user-images.githubusercontent.com/61768800/109933389-5092b600-7d06-11eb-9106-bce98a6314d0.png)

According to the [Apollo Devtools documentation](https://github.com/apollographql/apollo-client-devtools#configuration):

![image](https://user-images.githubusercontent.com/61768800/109934716-ca776f00-7d07-11eb-8769-a6910c13ca87.png)

**Comment by jtoar** [comment]
Hey @andrew-hwahin I tried just now and managed to get it working with a super bare bones example:
![image](https://user-images.githubusercontent.com/32992335/110008131-3b029980-7cd0-11eb-8e8e-9e474f328757.png)
Mind sharing a little more about your setup so we could help you debug? Are you able to see the `__APOLLO_CLIENT__` global in your web console?

**Comment by andrew-hwahin** [comment]
Thanks for helping 🙏 @jtoar I just tried to set up a barebone RedwoodJS test project and it's working.

But in my actual project, I can't see any queries under the "Watched queries" section even though the queries had run successfully.

![image](https://user-images.githubusercontent.com/61768800/110282339-4aa81800-8019-11eb-8e45-10360dbe716c.png)

I'm able to see the `__APOLLO_CLIENT__` in my web console.

![image](https://user-images.githubusercontent.com/61768800/110282458-7c20e380-8019-11eb-90fd-ee7365ecd94b.png)

**Comment by jtoar** [comment]
@andrew-hwahin Your response was very detailed so I'm very sorry for never responding!

I've used the Apollo Client dev tools quiet a few times recently (we've upgraded to a new minor) and they've been working quite well. I'll close this for now but if you run into this again and let me know; I'm happy to reopen.
