### ISSUE TITLE
[release bug] hoisting `node_modules` in `web/` is back again in latest canary `0.26.3-canary.6`

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1907]
@peterp @dac09 

Using the latest CRWA template and canary, which is upgraded to React v17 in https://github.com/redwoodjs/redwood/pull/1705, I'm seeing hoisted `node_modules` in `web/`, which is a change from current release v0.26.2. (see screenshot below)

I'm getting different results than the last time we ran into this:
- pass **e2e** = ✅
- `yarn rw test` (on a project that completed e2e) runs and passes tests successfully = ✅
- **prerender** fails due to `ReferenceError: _client is not defined` = ⛔️

<img width="214" alt="Screen Shot 2021-03-04 at 2 15 11 PM" src="https://user-images.githubusercontent.com/2951/110038963-5a5fed80-7cf5-11eb-9d56-07125dbb9fb1.png">

## How to Replicate
1. Running E2E locally, you can either use the project created in tmp/ directory or create a project to target via `yarn babel-node packages/create-redwood-app/src/create-redwood-app.js path/to/project`. If you choose the latter, do upgrade via `yarn rw upgrade -t canary`.
  - `web/node_modules` will contain hoisted packages
2. Run e2e script if you want to confirm `rw test` with passing tests
3. With or without e2e, add `prerender` to a page and run `yarn rw build`

**Comment by dac09** [comment]
@thedavidprice I believe describes 2 problems I believe

1. Linking local packages causes prerender to fail: https://github.com/redwoodjs/redwood/issues/1931
(this doesn't cause the hoisting, unless your project was in canary)

2. Update to react 17 is causing prerender to break in contributor workflows
I suspect this is because of the mismatch in react versions in the installed dependency (redwood/core@0.26.2 which uses react 16.x) and the project's web (using react 17.x)

This rears it heads as a) un-hoisted node modules b) `ReferenceError: _client is not defined`

**Comment by dac09** [comment]
Just to add, we can verify what I'm stating in (2) what causes this using `yarn why react` on your project. 

You should see 2 versions of react:
```
info Reasons this module exists
   - "workspace-aggregator-8853e7d7-9509-4537-99d3-9120f3a936d6" depends on it
   - Hoisted from "_project_#@redwoodjs#core#@storybook#react#@storybook#addons#@storybook#api#react"
   - Hoisted from "_project_#@redwoodjs#core#@storybook#react#@storybook#core#@storybook#ui#react"
   - Hoisted from "_project_#@redwoodjs#core#@storybook#react#@storybook#core#@storybook#ui#@storybook#components#react"
info Disk size without dependencies: "332KB"
info Disk size with unique dependencies: "520KB"
info Disk size with transitive dependencies: "600KB"
info Number of shared dependencies: 5
=> Found "web#react@17.0.1"
info This module exists because "_project_#web" depends on it.
info Disk size without dependencies: "364KB"
info Disk size with unique dependencies: "412KB"
info Disk size with transitive dependencies: "440KB"
info Number of shared dependencies: 3
```

16.x from storybook, 17.x on your local dependency.
