### ISSUE TITLE
Improve CLI speed by making FS calls lazy

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#1938]
If anyone is keen to fix some low hanging fruit for improving the performance of the CLI the "setup auth" command is doing a lot of filesystem work outside of functions.

https://github.com/redwoodjs/redwood/blob/4792d73e74fb734f76405c553d408000410d85b3/packages/cli/src/commands/setup/auth/auth.js#L13-L15

https://github.com/redwoodjs/redwood/blob/4792d73e74fb734f76405c553d408000410d85b3/packages/cli/src/commands/setup/auth/auth.js#L19-L40

So the moment the command is imported (whenever we run the CLI) it does a bunch of computation. We should keep those sort of things in the builder/ handler so that they're only run during execution.

**Comment by renansoares** [comment]
hi, can I assign this issue to me?

**Comment by peterp** [comment]
Done, thanks!
