### ISSUE TITLE
Newly generated postsPage.js is recently broken

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood#1944]
Instead of the usual page:

![image](https://user-images.githubusercontent.com/2712405/110372796-b8097800-801c-11eb-8db4-a69410f2f7f3.png)

Today, I am getting this

![image](https://user-images.githubusercontent.com/2712405/110372609-81cbf880-801c-11eb-8da4-eb91f9a64ae0.png)

I would guess that this was introduced by someone's work on the prerendering task. As I am still working on [The command "yarn rw prisma migrate dev" blocks the cmder terminal](https://github.com/redwoodjs/redwood/issues/1940), I hope that I will not "scolded" for just reporting this issue without a PR 😄

**Comment by jvanbaarsen** [comment]
Hi @adriatic,

Thanks for reporting :-)

>  I hope that I will not "scolded" for just reporting this issue without a PR

Just to be sure, reporting an issue is as important as coming up with a PR, so you will never be "scolded" for reporting an issue!

**Comment by adriatic** [comment]
> Just to be sure, reporting an issue is as important as coming up with a PR, so you will never be "scolded" for reporting an issue!

This was the rule in my "kingdom", but it is better to check than to assume 😸

**Comment by adriatic** [comment]
@thedavidprice @peterp @jvanbaarsen this issue stops me in my track (writing [Developing Redwood applications on Windows platform](https://github.com/redwoodjs/redwoodjs.com/wiki/Developing-Redwood-applications#developing-redwood-applications-on-windows-platform)). The tutorial code is being referenced nearly everywhere in my text so I created **[my own repo](https://github.com/adriatic/rw-debugging)** that contains the Tutorial I sample code, as a courtesy to our readers. (Caveat - this repo will be moved to a better place, that has yet to be defined)

I wrote this to prevent this issue to fall between the cracks.

**Comment by thedavidprice** [comment]
Hi @adriatic It looks like you’re missing the import for Scaffold CSS in your `App.js`. If you ran the Scaffold generator, you should have `import './scaffold.css'` in your `web/src/App.js`.
- is it possible you upgraded from a version prior to v0.26 and the import was lost in the manual code mods?
- have you tried re-generating the Post model via `yarn rw g scaffold post --force`? (NOTE: this will overwrite any customizations you might have made to generated files)

**Comment by Tobbe** [comment]
It's `yarn rw g scaffold post` that should create `scaffold.css` in the "Getting Dynamic" section. But it's weird that you don't have that, because you must at some point have run that command to get the Posts page that looks unstyled.

**Comment by thedavidprice** [comment]
You run the command Tobbe mentions above here: https://redwoodjs.com/tutorial/getting-dynamic#creating-a-post-editor 

This is the output you _should_ see when you run `yarn rw g scaffold post`:
```bash
$ yarn rw g scaffold post -f
...
  ✔ Generating scaffold files...
    ✔ Successfully wrote file `./api/src/graphql/posts.sdl.js`
    ✔ Successfully wrote file `./api/src/services/posts/posts.scenarios.js`
    ✔ Successfully wrote file `./api/src/services/posts/posts.test.js`
    ✔ Successfully wrote file `./api/src/services/posts/posts.js`
    ✔ Successfully wrote file `./web/src/layouts/PostsLayout/PostsLayout.js`
    ✔ Successfully wrote file `./web/src/pages/EditPostPage/EditPostPage.js`
    ✔ Successfully wrote file `./web/src/pages/PostPage/PostPage.js`
    ✔ Successfully wrote file `./web/src/pages/PostsPage/PostsPage.js`
    ✔ Successfully wrote file `./web/src/pages/NewPostPage/NewPostPage.js`
    ✔ Successfully wrote file `./web/src/components/EditPostCell/EditPostCell.js`
    ✔ Successfully wrote file `./web/src/components/Post/Post.js`
    ✔ Successfully wrote file `./web/src/components/PostCell/PostCell.js`
    ✔ Successfully wrote file `./web/src/components/PostForm/PostForm.js`
    ✔ Successfully wrote file `./web/src/components/Posts/Posts.js`
    ✔ Successfully wrote file `./web/src/components/PostsCell/PostsCell.js`
    ✔ Successfully wrote file `./web/src/components/NewPost/NewPost.js`
  ✔ Adding scaffold routes...
  ✔ Adding scaffold asset imports...
✨  Done in 3.56s.
```

The `scaffold.css` import is added to `App.js` in the final step above, "Adding scaffold asset imports".

If you're curious here's the source code for the Scaffold command with respective template directories:
https://github.com/redwoodjs/redwood/tree/main/packages/cli/src/commands/generate/scaffold

**Comment by thedavidprice** [comment]
Lastly, if you ever want to look at a reference codebase of what the final Tutorial should produce, see this repo (which is what we recommend people use to start the Tutorial II). It does have some styling applied, but that's the only significant difference:
https://github.com/redwoodjs/redwood-tutorial

**Comment by adriatic** [comment]
Added later - checked the Tutorial text again - and there is the creation of the CSS - [Creating a Post Editor](https://redwoodjs.com/tutorial/getting-dynamic#creating-a-post-editor). While my stubbornness makes me believe that the command `yarn rw g scaffold post` was not here a few hours ago, it will be easy to determine whether I suffered from some temporary blindness
`
