### ISSUE TITLE
Prisma implicit many-to-many relationship connect to existing record

### ISSUE THREAD

**Issue by andrew-hwahin** [redwoodjs/redwood#1947]
According to [Prisma Docs on Implicit relations](https://www.prisma.io/docs/support/help-articles/working-with-many-to-many-relations#implicit-relations) 👇

![image](https://user-images.githubusercontent.com/61768800/110437202-15222e00-80f0-11eb-9fb6-ccb4932d7583.png)

When I try it on my [repo](https://github.com/andrew-hwahin/Redwood-Prisma-Many-to-Many), it shows the following error message 👇

![image](https://user-images.githubusercontent.com/61768800/110437616-895cd180-80f0-11eb-85cb-76a79aaf53c5.png)

Does anyone use Prisma many to many implicit relations encounter this issue?

This is my `schema.prisma` 👇

![image](https://user-images.githubusercontent.com/61768800/110438520-6ed72800-80f1-11eb-88d3-010e5eee3403.png)

This is the `createPost` function in my `api/src/services/posts/posts.js` 👇

![image](https://user-images.githubusercontent.com/61768800/110439083-fcb31300-80f1-11eb-9b8b-5507089a3d12.png)

**Comment by Tobbe** [comment]
I'm certainly no expert here, but aren't you missing the `set` from their example?

**Comment by andrew-hwahin** [comment]
@Tobbe You're right! Thanks for pointing it out. 🙏

I've updated my code 👇 and it still can't detect `tags`

![image](https://user-images.githubusercontent.com/61768800/110444896-836aee80-80f8-11eb-9d80-9e5f223c4b83.png)

![image](https://user-images.githubusercontent.com/61768800/110444843-73eba580-80f8-11eb-822f-130b47394e9c.png)

**Comment by Tobbe** [comment]
I figured it out! 😃 

It should be `connect`, not `set`

```
export const createPost = ({ input }) => {
  const data = {
    title: input.title,
    tags: { connect: input.tags.map((id) => ({ id })) },
  }

  return db.post.create({
    data,
  })
}
```

**Comment by Tobbe** [comment]
To see that it worked I opened prisma studio

![image](https://user-images.githubusercontent.com/30793/110454764-ee500180-80c7-11eb-95a4-88c493ba962f.png)

`yarn rw prisma studio`

**Comment by andrew-hwahin** [comment]
Omg, thanks @Tobbe !! 🙇‍♂️ I've been stuck on this problem for days 😭 you're my saviour! 🦸‍♂️

**Comment by Tobbe** [comment]
HTH 🙂
