### ISSUE TITLE
Increase eslint compatibility

### ISSUE THREAD

**Issue by chris-hailstorm** [redwoodjs/redwood#195]
ENVIRONMENT

alpha33

OBSERVATION

I'm using a common eslint ruleset (airbnb).  A number of common eslint rules complain a lot in Redwood code because of auto-importing and other nice things you're doing for developers.

ESlint rules I need to turn off currently --

`import/no-unresolved` -- example, complains in `index.js` about `@redwoodjs/web`

`no-undef` -- example, complains in `Routes.js` that `HomePage` is not defined

`react/react-in-jsx-scope` -- example, complains in many files that `React` is not in scope

Turning off those rules is a not desirable.  Although they raise false complaints re: things Redwood is auto-importing, turning them off would mean I lose protection every other time I mess something up.  Don't want to turn the rule off; don't want to disable Redwood automation.

I've been looking for a way to more selectively disable eslinst rules, like don't apply `import/no-unresolved` to libraries named like `@redwood/*`.  So far no luck in being that selective.

DETAILS

Here's the `.eslintrc.js` file I'd like to use:

```
module.exports = {
  "env": {
    "browser": true,
    "jest": true
  },
  "extends": ["airbnb", "prettier"],
  "plugins": ["prettier"],
  "rules": {
    "no-return-assign": ["off"],
    "prefer-promise-reject-errors": ["off"],
    "prettier/prettier": ["error"],
    "react/jsx-filename-extension": ["off"],
    "react/react-in-jsx-scope": ["off"],
    "react/prop-types": ["warn"]
  }
};
```

**Comment by thedavidprice** [comment]
@chris-hailstorm doing some TLC on stale issues. If this is no longer relevant and/or you found a solution, please let me know.

By now you’ve probably found where our core config files reside for Redwood Apps:
https://github.com/redwoodjs/redwood/tree/master/packages/eslint-plugin-redwood

And within the App the config is used here:
https://github.com/redwoodjs/create-redwood-app/blob/a5ffc2b62f54eb748218137e03a0c7a26cf50408/package.json#L12

@peterp correct me if I’m wrong, but in order for Chris to use his settings above, he could:
1. create that config file and add it within root directory (or maybe a new “lib/“ within root)
2. modify his App `package.json` accordingly

Lastly, if I have it correct and this works well, let me know so I can add this to our Docs.

**Comment by thedavidprice** [comment]
closing out but can reopen if still needs to be addressed
