### ISSUE TITLE
Include `ts-to-js` transpiling within create-redwood-app.js (instead of the current separate CLI command)

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1954]
Currently, we skip the `...rw ts-to-js` command in the current E2E tests, which is good for testings a TS project. However, since this is a critical path and the default for new project installation, it seems to me we should include it. And I don't believe the E2E tests will differ based on project being TS or JS, will it?

A simple way would be to change this line by removing `--no-javascript` flag:
https://github.com/redwoodjs/redwood/blob/5dbb9e0a87bde6fbfac391202ca4417fc7023aeb/tasks/run-e2e#L43

Is there reason to _not_ do this here? If so, where else could we add the test?

**Comment by thedavidprice** [comment]
Scratch that. I wrote this after diagnosing QA problems but hadn't looked at the GitHub runner. Confirming we _are_ testing this command in the CI Check.

The `run-e2e.js` Yargs options are not intuitive for local workflows. Will re-evaluate and suggest next steps.

**Comment by peterp** [comment]
Sorry that this isn't as intuitive as I imagined, the reason why we're doing this is because we don't install the packages once the project is created. This means the `rw` command isn't available.

We copy the packages from the framework and then install everything, then we convert it.

If you do `run-e2e --help` you get the following options:

```bash
Options:
  --version                   Show version number                      [boolean]
  --create-project, --create                           [boolean] [default: true]
  --copy-framework, --copy                             [boolean] [default: true]
  --js-project, --js                                   [boolean] [default: true]
  --auto-start, --start                                [boolean] [default: true]
  --help                      Show help                                [boolean]

Examples:
  run-cypress
  run-cypress /tmp/redwood-app --no-js-project
```

Not supplying any options does everything standard; so in your case I think you want to point it to an existing project?

`./tasks/run-e2e /path/to/existing-project --no-create --no-copy --no-js`

**Comment by thedavidprice** [comment]
It made sense why once I went through the CI workflow along with command. Thanks!

Yes, that's what I did. Then upgraded to canary and then ran ts-to-js. Confirming it all worked.

**Comment by peterp** [comment]
I can also make the code that transpiles the TS to JS part of `create-redwood-app` instead of a separate command, which is probably what I should do so that we don't have these issues.

Re-opening with that as the task.

**Comment by thedavidprice** [comment]
@peterp bumping this one. I think your comment above about transpiling as part of CRWA is the right way to go.

Updating title.

**Comment by Josh-Walker-GM** [comment]
@jtoar Thoughts on closing this one out? We now include both js and ts templates in the create redwood app package and simply copy over the relevant template at install time - no transpilation needed. I think this meets the general theme of this issue.

**Comment by jtoar** [comment]
@Josh-Walker-GM good call!
