### ISSUE TITLE
[v0.27 blocking] `rw prerender` fails locally

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1955]
Running the E2E tests locally, I am hitting the following error when `yarn rw build` is run:
```bash
Command failed with exit code 1: yarn rw prerender
Could not resolve "/Users/price/Repos/xx-delete/web/src/pages/FatalErrorPage" in file /Users/price/Repos/xx-delete/web/src/App.js.
Not all routes were succesfully prerendered
we could not prerender your page, but your Redwood app should still work fine.
This could mean that a library you're using does not support SSR.
ReferenceError: _client is not defined
    at RedwoodApolloProvider (/Users/price/Repos/xx-delete/web/node_modules/@redwoodjs/web/dist/apollo/index.js:93:15)
    at processChild (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom-server.node.development.js:3043:14)
    at resolve (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at Object.renderToString (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at runPrerender (/Users/price/Repos/xx-delete/node_modules/@redwoodjs/prerender/dist/runPrerender.js:67:43)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  context: [Object: null prototype] {}
}
error Command failed with exit code 1.
$ /Users/price/Repos/xx-delete/node_modules/.bin/rw prerender
[19:31:01] Prerendering /about -> web/dist/about.html [started]
[19:31:06] Prerendering /about -> web/dist/about.html [failed]
[19:31:06] → _client is not defined
```

I'm using a separate project I created with `yarn babel-node` — note: I had to run first with --no-javascript, then upgrade to canary. The other option is to create the project in tmp and open that directory.

E2E Sets the following routes to prerender:
- Home
- About
- NotFoundPage

I tried with just About page and received the same error.

**Comment by thedavidprice** [comment]
**Update:**
Prerender also fails in my Redwood Tutorial Blog test project, upgraded to the latest canary.

**Comment by thedavidprice** [comment]
**Deploy Update:**
BUT, 'cause I'm going insane, when I deploy Redwood Tutorial Blog test I get a "success" for build and prerender. What?

https://app.netlify.com/sites/redwoodjs-tutorial-test/deploys/6048403e9e75c50007bd0ff9

**Comment by thedavidprice** [comment]
My system info:
```bash
System:
    OS: macOS 11.1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4
    Yarn: 1.22.10 
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 89.0.4389.82
    Firefox: 85.0
    Safari: 14.0.2
  npmPackages:
    @redwoodjs/core: ^0.26.3-canary.23 => 0.26.3-canary.23+5dbb9e0a 
```

**Comment by peterp** [comment]
I think this might be because of symlinking via `rwt link`

Try copying the "packages" from the Redwood framework into "packages" of your project. (If that's setup as a workspace.)

`cp -r /path/to/redwood/packages /path/to/redwood/project/packages`

The run `yarn install`

**Comment by thedavidprice** [comment]
This was a stand alone project using canary releases. No linking involved. 

Also failed on my Tutorial project using canary.

**Comment by thedavidprice** [comment]
## Hoisting is an artifact from upgrading (to be clear, I upgraded in the "correct" sequence)
> Maybe you forgot to update react and add resolutions?

^^ So, I did not forget. But, yes indeed, this is the result of hoisting, **which happened during the upgrade process.** (Note: I upgraded to canary _at the end_ of the process, after I added resolutions and manually set the version of React packages.)

### Solution + TO DO
After the steps outlined below in "replication", I can confirm that this hoisting is resolved:
- `git clean -fxd` (watch out for .env!)
- `yarn`

_Update:_ Oh and I just tried and can confirm this works:
- `rm -rf web/node_modules`
- `yarn --force`

--> The reason this is important is that our _normal_ upgrade path **breaks** for this release. So I'm trying to get ahead of that.
- I guess we could have people clean and install. Or maybe `yarn --force` will do it.
- Is there a diagnostic we could give people at the command line; maybe associate with `rw upgrade` --> check for hoisted modules and alert if found (note: this won't work for this upgrade since they won't have most recent installed... trying to brainstorm) Is there a way we can resolve for the future?

#### TO DO
For now, we just need to make this clear in the Upgrade Guide. I suggest a final step 1) delete web/node_modules then 2) yarn --force. But we need to alert and be clear. And then be ready to answer a million incoming requests "Prerender is broken, HELP"

^^ Maybe there is a diagnostic we can insert into v0.27? @danny maybe into Prerender code itself?

## Replication
### 1. Creating a new project from the `main` branch CRWA template
Using babel-node, I spun up a new project _without_ installation or conversation from TS to JS.
- The project had resolutions and React 17 in the template, but was on Redwood v0.26.2
- I ran `yarn install`
- I ran `yarn rw upgrade -t canary`
- I then ran `yarn rw ts-to-js` 

Hoisted modules look like this:
<img width="201" alt="Screen Shot 2021-03-10 at 8 00 05 AM" src="https://user-images.githubusercontent.com/2951/110658574-a50abb00-8176-11eb-93b1-4f7485f06670.png">

### 2. Upgraded an existing project using Release Notes draft
In my existing project using v0.26.2, I went through the upgrade steps in this sequence:
- added resolutions in package.json
- manually set React v17 in web/package.json
- set Node engine to 14; confirmed .nvmrc with lts/*
- ran `yarn rw upgrade -t canary`

Hoisted modules look like this:
<img width="208" alt="Screen Shot 2021-03-10 at 8 02 57 AM" src="https://user-images.githubusercontent.com/2951/110659019-0a5eac00-8177-11eb-8da3-77407d2b5c62.png">

**Comment by thedavidprice** [comment]
fixed by https://github.com/redwoodjs/redwood/pull/1962
