### ISSUE TITLE
[api] Add support for prisma where

### ISSUE THREAD

**Issue by pi0neerpat** [redwoodjs/redwood#1956]
It seems there is not full support for `where` in Prisma ([documentation](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#where))

For example if I want to find a token which matches both the `contractAddress` and `chainId`

```js
  let token = await db.token.findOne({
    where: {
      AND: [
        {
          contractAddress,
        },
        {
          chainId,
        },
      ],
    },
  })
```

I get this error, which suggests that the full `where` features are not available.

```
Unknown arg `AND` in where.AND for type TokenWhereUniqueInput. Did you mean `id`? Available args:
  type TokenWhereUniqueInput {
  id?: String
```

I get a similar error if I try with 

```js
  let token = await db.token.findOne({
    where: {
          contractAddress,
          chainId,
        },
    },
```

It seems that `TokenWhereUniqueInput` exists somewhere, but is not made visible in the `.sdl` files. Would it be possible to update the `<type>WhereUniqueInput` auto-generated sdls to support more than just query by `id`?

At the very least, it would be nice to be able to overwrite the redwood-generated(?) sdl. Even if I include my own sdl it isn't recognized. eg:

```js
  type TokenWhereUniqueInput {
    contractAddress?: String
  }
```

Also I'm still on 0.24.0, and apologize if this has been added.

**Comment by peterp** [comment]
This has worked nicely for me for awhile - maybe you should regenerate your prisma client via `yarn rw db up` (old prisma syntax).

**Comment by peterp** [comment]
Or could you share your `api/src/lib/db.js` file?

**Comment by pi0neerpat** [comment]
Hi there! I'm still using the old commands `yarn rw db up` since I'm on `v0.24.0`

```js
// api/src/lib/db.js
import { PrismaClient } from '@prisma/client'

export const db = new PrismaClient()
```

For now I've resorted to using `findFirst` which achieves the same result (mostly)

**Comment by peterp** [comment]
Do you have a jsconfig.json file?

**Comment by peterp** [comment]
Ah, I see, I think I misunderstood the problem! I think this is working as expected. FindOne works with unique fields. It has been renamed  to `findUnique` in order to help understand that issue:

`Wraps all unique fields of a model so that individual records can be selected.`

![Uploading image.png…]()





Wraps all unique fields of a model so that individual records can be selected.
--

**Comment by pi0neerpat** [comment]
OK I think I get it now. I am still confused though on why they are forcing the `where` here to only include unique variables. Its a bit confusing to overload `where` like this. A better term like `whereUnique` would be more appropriate.

So... I guess my hacky usage of `findFirst` is actually the correct way to return a unique value using (full-feature) `where`?

**Comment by pi0neerpat** [comment]
The day I need to think about performance for my graphql server is the day I hire an engineer, because we just hit 500k users.

Thanks a bunch for your help!
