### ISSUE TITLE
[RFC] Add top level `typings` folder

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#1963]
I would like to introduce a typings folder to Redwood.

The typings folder will contain generated types, as well as types that a user can define, as an example a user will be able to define the type returned via `api/src/lib/auth::getCurrentUser`

```ts
// ./typings/auth.d.ts
declare module @redwoodjs/auth {
    export interface CurrentUser {
       email: string
       teamId: string
       isAdmin: boolean
    }
}
```

This typing will then be available via:
1. the global context: `context.currentUser.isAdmin`
2. `const { currentUser} = useAuth()` 
3. The return value of `getCurrentUser` in `api/src/lib/auth` would have to match this type.

The generated types that we currently place in `.redwood` can also be placed here.

Thanks @Burnsy for pushing me to publishing this.

**Comment by peterp** [comment]
↑↑↑ Please excuse errors, this is late night, after a wine, pseudo-code.

**Comment by Burnsy** [comment]
Say no more this would be great to allow us to completely type our contexts no more hack jobs with a custom useAuth hook!

**Comment by dac09** [comment]
Hey @Burnsy, @peterp - is it important for this to be user modifiable?

I was thinking to hide it away in the `.redwood` folder, and infer the type from src/lib/auth#getCurrentUser. So if you type that function correctly (or it can be inferred by TS), context.currentUser will also be correctly typed.

Is this going to prevent you guys from doing something you're looking to?

**Comment by dac09** [comment]
Sounds good man :)

**Comment by dac09** [comment]
Are we still exploring this further @peterp or shall we close this PR?

**Comment by dac09** [comment]
Closing this as this is something I added to the Typescript changes in v0.33. You can now have your own typings in the root of the project in `./types`. I discussed the folder name with Tom already, and it reads well I think.
