### ISSUE TITLE
After upgrade to 0.27: Context creation failed

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#1993]
After upgrading to v0.27 I'm seeing this error
> Context creation failed: Per request context is not initialized, please use `initPerRequestContext`

![image](https://user-images.githubusercontent.com/30793/110997518-d0abc200-837d-11eb-90b6-0c11c7171450.png)
(this is on localhost)

Most likely related to https://github.com/redwoodjs/redwood/pull/1789

This has also been reported by @Burnsy and other people

@peterp any idea how to fix this?

**Comment by thedavidprice** [comment]
**Update:** The Redwood Core Team is looking into this now as a priority issue to resolve. Will fix, release a patch, and communicate what's happening once we have a resolution.

**Comment by noire-munich** [comment]
That crashes any test with `mockCurrentUser` too, but so far I haven't seen it with `yarn rw dev`

**Comment by thedavidprice** [comment]
@noire-munich have you been able to resolve the issue using v0.27.1?

**Comment by noire-munich** [comment]
@thedavidprice not at all:

```shell
FAIL   api  api/src/services/structures/structures.test.ts (28.903 s)
  ● structures › creates a structure

    Per request context is not initialized, please use `initPerRequestContext`

      54 | describe('structures', () => {
      55 |   scenario('creates a structure', async (scenario) => {
    > 56 |     mockCurrentUser(scenario.user.one)
         |     ^
      57 |     const result = await createStructure({
      58 |       input: { label: 'String', languages: ['FR'] },
      59 |     })

      at setContext (../node_modules/@redwoodjs/api/dist/globalContext.js:80:13)
      at mockCurrentUser (../node_modules/@redwoodjs/core/dist/configs/node/jest.setup.js:110:3)
      at src/services/structures/structures.test.ts:56:5
      at Object.<anonymous> (../node_modules/@redwoodjs/core/dist/configs/node/jest.setup.js:102:20)

```

That worked like a charm in v0.26.x

**Comment by peterp** [comment]
@noire-munich

Could you add this to your `api/jest.config.js` file:

```
process.env.SAFE_GLOBAL_CONTEXT = '1'
```

**Comment by noire-munich** [comment]
@peterp thanks, it works!
Did I miss something in the latest upgrades notes?

**Comment by peterp** [comment]
Nope, it's my fault, we'll fix this up

**Comment by noire-munich** [comment]
Ah! well that's a quick fix :) thanks again.
