### ISSUE TITLE
v0.27 DateField error

### ISSUE THREAD

**Issue by andrew-hwahin** [redwoodjs/redwood#1995]
Steps to reproduce using create-redwood-app@0.27.0:
1. yarn create redwood-app my-redwood-app-v27
2. In the `schema.prisma`, add `birthdate DateTime?` to the UserExample model.
3. `yarn rw prisma migrate dev`
4. `yarn rw generate scaffold UserExample`
5.  When I browse http://localhost:8912/user-examples/new it'll show this error 👇

![image](https://user-images.githubusercontent.com/61768800/111014665-cc17f580-83df-11eb-8562-2d2c1230e089.png)

[Link to the repo](https://github.com/andrew-hwahin/my-redwood-app-v27/blob/main/web/src/components/UserExampleForm/UserExampleForm.js)

There is another user who faced this issue too as communicated in the [Discord channel](https://discord.com/channels/679514959968993311/716252919875240007/819857592994103296).

**Comment by andrew-hwahin** [comment]
@cannikin I think it might be related to #1906. Could you guide us on how to solve this issue? 🙏

**Comment by andrew-hwahin** [comment]
Other than the `replace of undefined issue` the DateField will also throw out an error for an empty value.

**Comment by guledali** [comment]
Try adding a question mark after the `value`

Or maybe try this

```javascript
if(value) {
 return value.replace()
}
```

**Comment by jvanbaarsen** [comment]
@andrew-hwahin I looks as if you have an optional `birthday` field (The ? indicates that in prisma.schema: `birthdate DateTime?`). 

Because of this the value can be `null` in the database, if you'd put a check in the `formatDateTime` as @guledali suggests it _should_ work.

Your formatDateTime would look like this:

```javascript
const formatDate = (value) => {
  if (value) {
    return value.replace(..yourreplacement)
  } 
}
```

**Comment by cannikin** [comment]
Whoops, forgot about the classic null case! I'm on it...

**Comment by cannikin** [comment]
I did one that fixed datetime fields in general, but this is a new (smaller) issue!
