### ISSUE TITLE
`yarn rw prisma format` error

### ISSUE THREAD

**Issue by andrewlamyw** [redwoodjs/redwood#1999]
Running `yarn rw prisma format` produces `Error: Could not find a schema.prisma file that is required for this command.`

![image](https://user-images.githubusercontent.com/11419166/111041598-e00d3700-8473-11eb-8bec-ee806285fa44.png)

Running `yarn rw prisma format --schema=./api/db/schema.prisma` produces `Unknown argument: schema`. I think Prisma 2.18.0 still does not support the `--schema` argument for the `format` command.

![image](https://user-images.githubusercontent.com/11419166/111041827-36c74080-8475-11eb-861d-817804bd0795.png)

**Comment by dthyresson** [comment]
> does not support the `--schema` argument for the `format` command.

From looking at

https://github.com/redwoodjs/redwood/blob/4fc08124b37be6d70ce4ebf2957069d9060cd137/packages/cli/src/commands/prisma.ts#L62

the `format` command is not one that is considered when appending the schema:

```js
      ['generate', 'introspect', 'db', 'migrate', 'studio'].includes(argv[0])
    ) {
      if (!fs.existsSync(paths.api.dbSchema)) {
        console.error(
          c.error('\n Cannot run command. No Prisma Schema found.\n')
        )
        process.exit(1)
      }
    ```

**Comment by dthyresson** [comment]
Also note that while `format` is in the help section, 

```

npx prisma -help

Usage

  $ prisma [command]

Commands

            init   Setup Prisma for your app
        generate   Generate artifacts (e.g. Prisma Client)
          studio   Open Prisma Studio
          format   Format your schema
         migrate   Migrate your database (Preview)
              db   Manage your database schema and lifecycle (Preview)
```


it is not mentioned in the [current Prisma CLI reference](https://www.prisma.io/docs/reference/api-reference/command-reference).

**Comment by dthyresson** [comment]
As a workaround you may invoke:

```
npx prisma format --schema=./api/db/schema.prisma

Environment variables loaded from .env
Prisma schema loaded from api/db/schema.prisma
Formatted /.../api/db/schema.prisma in 954ms 🚀
```
