### ISSUE TITLE
Redwood on JS Party?!

### ISSUE THREAD

**Issue by jerodsanto** [redwoodjs/redwood#20]
Howdy from [JS Party](https://changelog.com/jsparty)! 👋 

We'd love to have you on the show sometime soon. It seems like Redwood is in a great state to begin a conversation around it. We've been talking JAMStack a fair bit, but until now we haven't seen anyone step up to the plate with a full-stack, opinionated offering to tie all the concepts together.

Interested? Please email jerod@changelog.com to coordinate. 

Looking forward to it! 💚

**Comment by mojombo** [comment]
Sent you an email. Cheers!
