### ISSUE TITLE
Missing task "run-verdaccio"

### ISSUE THREAD

**Issue by webstackdev** [redwoodjs/redwood#2003]
The `publish-local` task has the following error output if Verdaccio isn't running to provide a local NPM repository:

`Error: Verdaccio is not listening on port 4873, start it with './tasks/run-verdaccio'`

But there isn't a `run-verdaccio` task in the project yet. I'd send a PR, but I'm not sure the best way to approach it - I'm using Verdaccio in a Docker container on my workstation.

**Comment by webstackdev** [comment]
I found the task, it's `run-local-npm` in `tasks`. I'll push a PR for a change in the `publish-local` task.

**Comment by Tobbe** [comment]
Fixed in #2004
