### ISSUE TITLE
Verbosely route data to empty in Cells.

### ISSUE THREAD

**Issue by Burnsy** [redwoodjs/redwood#2005]
Hi all, 

After a conversation with @peterp and @Tobbe we came to the conclusion that some more work should be done around the Cells to make it easier to make sure the route of Cell Part of `empty` used if things like indented arrays are returning `[]`

for example if we take the query of
```jsx
export const QUERY = gql`
  query POSTS {
    response {
      posts {
        id
        body
        createdAt
        userId
      }
      extraVars
      # ...etc
    }
  }
`
```

we would maybe want to show the empty cell if posts inside of the response is empty.

So we would need to make the afterQuery look like this 
```jsx
export const afterQuery = ({ response }) => {
  return response.posts.length === 0 ? undefined : response
}
```

The easier way would be to allow the user to override `isEmpty`

so they could just do
 ```jsx
export const isEmpty = ({response}) => response.posts.length === 0
```

and if the isEmpty returns true it then forces the Empty Function to run 

---------------

List of TODO's 

- [ ] Override isEmpty()
- [ ] have afterQuery() run before the override'ed isEmpty()
- [ ] fix bug where afterQuery is not ran on Empty so if the user mutated the empty to return null then success would error.

**Comment by Tobbe** [comment]
I just ran into this myself, where my query was returning two "objects", and I wanted to render `Empty` if either one is empty.

```js
export const QUERY = gql`
  query TeamCoachQuery($teamId: Int!, $coachId: Int!) {
    team(id: $teamId) {
      id
      name
      club
    }
    coach(id: $coachId) {
      id
      UserToCoach {
        user {
          firstName
          lastName
        }
      }
    }
  }
`
```

If either `team` or `coach` is empty, I want to render `Empty`

**Comment by Tobbe** [comment]
```
export const isEmpty = ({ response, isResponseEmpty }) =>
  isResponseEmpty(response) || response.posts.length === 0
```

This would definitely solve my use case 👍

**Comment by callingmedic911** [comment]
@thedavidprice @jtoar Gentle reminder about my comment above. 🙂

**Comment by jtoar** [comment]
@callingmedic911 extending as well as overriding sounds great! Just to clarify, in your example, is `isResponseEmpty` the original?

Although switching the order up may be a breaking change, I thought `afterQuery` would run before `isEmpty` as well. We should ask about that one and see what people think.

But do feel free to proceed with the first change! 🚀

**Comment by callingmedic911** [comment]
>Just to clarify, in your example, is `isResponseEmpty` the original?

Yes.
