### ISSUE TITLE
cli destroy page does not clean up stories and test files

### ISSUE THREAD

**Issue by jangxyz** [redwoodjs/redwood#2006]
tested on: `v0.27.1`

cli destroy command works well for `component`s, but does not remove the directory entirely for `page`s.

```
$ yarn rw d page Home
yarn run v1.22.10
$ /Users/kjh/play/_ground/redwood/redwood-0.27.1/node_modules/.bin/rw d page Home
  ✔ Destroying page files...
    ✔ Destroying `./web/src/pages/HomePage/HomePage`...
    ✔ Cleaning up empty directories...
      ↓ Removing empty `./web/src/pages/HomePage`... [skipped]
        → Not empty
  ✔ Cleaning up routes file...
✨  Done in 2.48s.
```

<img width="720" alt="Screen Shot 2021-03-15 at 20 37 42" src="https://user-images.githubusercontent.com/52015/111148372-e6fc8c80-85ce-11eb-954d-bc4e4e501a4d.png">

<img width="720" alt="Screen Shot 2021-03-15 at 20 38 20" src="https://user-images.githubusercontent.com/52015/111148390-ebc14080-85ce-11eb-879c-32ad66a41e6c.png">

I found that the `filesFn` argument in [commands/destroy/helpers.js#tasks](https://github.com/redwoodjs/redwood/blob/v0.27.1/packages/cli/src/commands/destroy/helpers.js#L12) only passes `{ name }` as an argument, and while the function for component accepts `tests` and `stories` argument to `true` by default, ([commands/generate/component/component.js#L10](https://github.com/redwoodjs/redwood/blob/v0.27.1/packages/cli/src/commands/generate/component/component.js#L10))
it does not for pages. ([commands/generate/page/page.js#L41](https://github.com/redwoodjs/redwood/blob/v0.27.1/packages/cli/src/commands/generate/page/page.js#L41))

I can't be sure whether the `files` function in page generator should accept `true` as default for `tests` and `stories` , but at least passing them as arguments while calling the functions seems safe.

// [commands/destroy/page/page.js#L31](https://github.com/redwoodjs/redwood/blob/v0.27.1/packages/cli/src/commands/destroy/page/page.js#L31)
```typescript
        task: async () => {
          const p = pathName(path, name)
          const f = pageFiles({
            name,
            stories: true, // <-- here
            test: true, // <-- and here
            path: p,
            ...templateVars(p),
          })
          return deleteFilesTask(f)
        },
```

**Comment by thedavidprice** [comment]
Ah, great catch. I believe the test and story files were added to Page generation _after_ the Destroy command was created.

Any chance you would be interested in working on a PR for this @jangxyz? No pressure either way.

**Comment by thedavidprice** [comment]
## Reproducing
I generated an About page, which create these files and the associated Route.js route:
<img width="197" alt="Screen Shot 2021-05-14 at 9 28 57 AM" src="https://user-images.githubusercontent.com/2951/118300811-31976980-b497-11eb-9ef8-430fe35481fd.png">

Running `yarn rw d page about` remove the page component and route, but it leaves these files behind:
<img width="196" alt="Screen Shot 2021-05-14 at 9 28 39 AM" src="https://user-images.githubusercontent.com/2951/118300918-512e9200-b497-11eb-8673-a66f66888371.png">

## Steps To Fix
1. Audit destroy commands that create stories and tests
I've confirmed that `yarn rw d component [name]` successfully deletes all files. We should confirm this is correct for all types.

2. Fix the code referenced by @jangxyz in OP. Use other generator types as reference.

**Comment by pdjota** [comment]
#2568 should address this issue cc: @thedavidprice
