### ISSUE TITLE
Bug (Windows) with suggested fix : Pages in a subdirectory

### ISSUE THREAD

**Issue by cjreimer** [redwoodjs/redwood#2015]
Hello, I'm a rookie and this is my first issue, so let me know if you have any suggestions for posting differently.

I ran into the same issue as https://community.redwoodjs.com/t/bug-when-namespacing-a-scaffold/1803

I am running on a Windows machine.   When I prefix a directory in front of my pages (example: pages\Admin\NewProejctPage)  I get the following error:

> ./src/Routes.js 5:11
> Module parse failed: Unexpected token (5:11)
> File was processed with these loaders:
>  * ../node_modules/babel-loader/lib/index.js
> You may need an additional loader to handle the result of these loaders.
> |   loader: () => import("D:/CENGYS/Dev/cengys-r/web/src/pages/AboutPage/AboutPage")
> | };
> > const Admin/NewProjectPage = {
> |   name: "Admin/NewProjectPage",
> |   loader: () => import("D:/CENGYS/Dev/cengys-r/web/src/pages/Admin/NewProjectPage/NewProjectPage")
> 

I did a bit of searching into the redwood codebase (my first foray) and noticed the following in:

redwood/packages/internal/src/paths.ts

```
`export const processPagesDir = (
  webPagesDir: string = getPaths().web.pages
): Array<PagesDependency> => {
  const pagePaths = glob.sync('**/**/*Page.{js,jsx,ts,tsx}', {
    cwd: webPagesDir,
  })
  return pagePaths.map((pagePath) => {
    const p = path.parse(pagePath)

```
    const importName = p.dir.replace(path.sep, '')
    const importPath = importStatementPath(
      path.join(webPagesDir, p.dir, p.name)
    )
    const importStatement = `const ${importName} = { name: '${importName}', loader: import('${importPath}') }`
    return {
      importName,
      const: importName,
      importPath,
      path: path.join(webPagesDir, pagePath),
      importStatement,
    }

On my Windows machine, glob is returning forward slashes, while the path.sep returns a backslash '\\'

Thus, the following does not work as intended:
` const importName = p.dir.replace(path.sep, '')`

Just to make sure, I wrote a little test app, and glob returns ...

   ["AboutPage/AboutPage.js","Admin/NewProjectPage/NewProjectPage.js",

It looks like this should be a simple fix.  I appreciate all your efforts ... RedwoodJS is impressive!

**Comment by Tobbe** [comment]
@cjreimer Thanks for taking the time to write this issue report. Would you be interested in trying to write a PR for it as well, trying to fix the issue?

If you are, I'd suggest first taking a look in packages/internal/src/__tests__/paths.test.js. We have a test there for the `processPagesDir` function, but it only looks at the path. We should add tests for the name as well.

No pressure if you don't want to, or don't have the time. Just let me know either way.

**Comment by cjreimer** [comment]
@Tobbe I'll give it a try.  It will be my first adventure into working on an open-source repo, or anything close to this for that matter.  I'll read the docs before I ask any questions.

David also requested on the forum that I post the output of yarn rw info (below) and link in @jtoar.
```
 
  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 14.15.5 - C:\Users\CURTIS~1\AppData\Local\Temp\yarn--1615985388592-0.9351226760517277\node.CMD
    Yarn: 1.22.10 - C:\Users\CURTIS~1\AppData\Local\Temp\yarn--1615985388592-0.9351226760517277\yarn.CMD
  Browsers:
    Chrome: 89.0.4389.82
    Edge: Spartan (44.19041.423.0)
  npmPackages:
    @redwoodjs/core: ^0.27.1 => 0.27.1
```

**Comment by cjreimer** [comment]
@Tobbe I submitted pr #2022 
Is there anything else I need to do to get it reviewed?

**Comment by Tobbe** [comment]
@cjreimer Review submitted, please have a look! 🙂

**Comment by thedavidprice** [comment]
Thanks for this @cjreimer! Greatly appreciate you jumping in with us. This is great.

I'm adding this as a priority for the next release.

**Comment by thedavidprice** [comment]
Fixed via https://github.com/redwoodjs/redwood/pull/2022
