### ISSUE TITLE
Route parameters that do not immediately follow a slash do not work

### ISSUE THREAD

**Issue by svenhanssen** [redwoodjs/redwood#2019]
I tried using a route path with a param that immediately followed a `@` instead of a `/` but this doesn't work. 

```
<Route path="/@{username}" page={UserDetailsPage} name="user" />
```

When generating a link, for example with `routes.user({ username: 'sven' })`, the generated links becomes `http://localhost:8910/@%7Busername%7D?username=sven`, as `http://localhost.8910/@sven` was expected.

**Comment by Tobbe** [comment]
You are correct. It's designed to work this way.

But I think this makes the second request for support for something like this. If you want, it would be great if you could try and find the other issue on the same subject and link it here. It could also have just been a forum post, so if you don't find an issue, see if you can find a post. Thanks!

**Comment by svenhanssen** [comment]
I searched everywhere (Discource Forums, Discord, Github), but unfortunately I couldn't find a request similar to this ...

**Comment by Tobbe** [comment]
Thanks for looking. I'll see what I can dig up

**Comment by Tobbe** [comment]
Found it! This is the one I was thinking of https://github.com/redwoodjs/redwood/issues/1702

**Comment by jtoar** [comment]
@svenhanssen We've implemented this feature! I think in https://github.com/redwoodjs/redwood/pull/3699 (you can see the tests we added for it in https://github.com/redwoodjs/redwood/pull/3718).
