### ISSUE TITLE
Hot reload no longer works

### ISSUE THREAD

**Issue by chris-hailstorm** [redwoodjs/redwood#202]
ENVIRONMENT

alpha33

OBSERVATION

How reloading has been working well.  Now there is no reload when I save a changed component.

Example, I have components like `web/src/components/menus/BasicMenu/BasicMenu.js`. If I change and save that file, there is no reload visible in the `yarn rw dev` CLI output, and there is no reload activity in the Chrome developer console (not even the "app didn't change" message).

Here's what I see on the `yarn rw dev` CLI output:

    16:44:49  db | Watching... /Users/chris/proj/aw-hammer/api/prisma/schema.prisma
    16:44:49  db |
    16:44:49  db | ✔ Generated Prisma Client to ./../node_modules/@prisma/client in 137ms
    16:44:49  db |
    16:44:49 api | Listening on http://localhost:8911
    16:44:49 api | Watching /Users/chris/proj/aw-hammer/api
    16:44:49 api |
    16:44:49 api | Now serving
    16:44:49 api |
    16:44:49 api | ► http://localhost:8911/graphql/
    16:44:49 web | ℹ ｢wds｣: Project is running at http://localhost:8910/
    16:44:49 web | ℹ ｢wds｣: webpack output is served from /
    16:44:49 web | ℹ ｢wds｣: Content not from webpack is served from /Users/chris/proj/aw-hammer/web
    16:44:49 web | ℹ ｢wds｣: 404s will fallback to /index.html

I see "watching" messages for the schema file and the `api` project, but not for `web`.

If I stop and re-start `yarn rw dev`, the changes become effective.  So I don't think this is an issue with the components, but rather with whatever watcher should respond to file changes.

I've been changing React source files, but no project config, so this is kind of mystifying.

**Comment by peterp** [comment]
@chris-hailstorm Is this still the case?

**Comment by chris-hailstorm** [comment]
I’ve just moved to 0.2.0 so not sure yet. This behavior was sporadic in 0.2.0. I’ll report back on 0.2.0 after a day’s use.

**Comment by thedavidprice** [comment]
@chris-hailstorm any further issues with this? Let me know or feel free to close. Thanks!

**Comment by chris-hailstorm** [comment]
This has continued but it's sporadic.  I haven't found any helpful clues.

**Comment by chris-hailstorm** [comment]
Closing since I can't pin this down.  Will try to find a reproducible case along the way.
