### ISSUE TITLE
Incorrect RouteProps type regarding `redirect` prop for Route component

### ISSUE THREAD

**Issue by jangxyz** [redwoodjs/redwood#2023]
Though it is not documented, I assume the `redirect` prop in `<Route />` to be used in redirections, so we can do

```jsx
<Router>
  <Route path="/" redirect="/home" />
  <Route page="/home" page={HomePage} />
</Router>
```

instead of nesting `<Redirect />` component, like this:

```jsx
<Router>
  <Route path="/" page={() => <Redirect to={'/home'} />} />
  <Route page="/home" page={HomePage} />
</Router>
```

A minor problem is that `page` prop is required, as declared in the `RouteProp` interface: [packages/router/src/router.tsx@v0.27.1](https://github.com/redwoodjs/redwood/blob/v0.27.1/packages/router/src/router.tsx#L20-L28)

```typescript
interface RouteProps {
  page: Spec | React.ComponentType<unknown> | ((props: any) => JSX.Element)
  path?: string
  name?: string
  notfound?: boolean
  redirect?: string
  prerender?: boolean
  whileLoading?: () => ReactChild | null
}
```

I ended up adding a bogus `page` prop just to make my compiler happy..

```jsx
  <Route path="/" redirect="/home" page={() => null} />
```

Maybe it would be better to make `page` optional, at least only when we have `redirect`?

**Comment by Tobbe** [comment]
You are correct. `page` should have been optional. 

This is being corrected as part of my rewrite of the router here https://github.com/redwoodjs/redwood/pull/1898
