### ISSUE TITLE
jest: add 'src' path to jest default config

### ISSUE THREAD

**Issue by jangxyz** [redwoodjs/redwood#2039]
Importing from absolute paths in test files throws "Cannot find module" error. 

Currently this test code:
```jsx
import { render } from '@redwoodjs/testing'

import HomePage from './HomePage'
import data from 'src/model/data' // <-- here

describe('HomePage', () => {
  it('renders successfully', () => {
    expect(() => {
      render(<HomePage />)
    }).not.toThrow()
  })

  it('reads data', () => {
    expect(data).toBe(3)
  })
})
```

throws error:

![image](https://user-images.githubusercontent.com/52015/111777925-46bca580-88f7-11eb-8e1b-5a1b28bea585.png)

Changing it to relative path (`import data from '../../model/data'`) works fine.

As redwood supports `src` path alias out of the box, it seems natural to expect the same for test codes as well.

I got it working by adding `moduleNameMapper` configuration to `web/config/jest.config.js`: 
(from [jest configuration#moduleNameMapper](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring))

```javascript
config.moduleNameMapper = config.moduleNameMapper || {}
config.moduleNameMapper['src/(.*)'] = '<rootDir>/src/$1'
```

Since like `jest.createConfig.ts` is already using `moduleNameMapper` heavily,  

https://github.com/redwoodjs/redwood/blob/f0b2ac5a944ef3d03aae631cfb1270891f4f78b8/packages/core/src/configs/browser/jest.createConfig.ts#L20-L47

I think it would be plausible to add `src` alias too.

**Comment by peterp** [comment]
Weird, this should be handled by babel - which jest should be using

**Comment by jtoar** [comment]
@dac09 fixed this in a recent release (perhaps the last one even).
