### ISSUE TITLE
Firefox bug and “Something went wrong in browser”: Router regex not supported in Firefox

### ISSUE THREAD

**Issue by Ameobea** [redwoodjs/redwood#205]
The `reroute` function generates Regexes that use named capture groups: https://github.com/redwoodjs/redwood/blob/7a5cc6733f54a9ac49356c609e996884517022d2/packages/router/src/util.js#L33

This [isn't supported](https://bugzilla.mozilla.org/show_bug.cgi?id=1362154) in Firefox (and probably a lot of other browsers) and causes examples to break there with "invalid regexp" errors.  You'll probably need to either [polyfill](https://babeljs.io/docs/en/babel-plugin-transform-named-capturing-groups-regex) it with Babel or switch off of named capture groups.

**Comment by thedavidprice** [comment]
Looks like a similar issue in the forum with some browser console output:
https://community.redwoodjs.com/t/running-into-an-issue-at-getting-dynamic-in-the-tutorial/149/6

**Comment by thedavidprice** [comment]
Currently we do NOT have a fix for this. Please use alternate browser for now.

**Comment by thedavidprice** [comment]
Not to get our hopes up about a FF fix coming just in time, but there's been activity on their upstream issue as of 15 days ago:
https://bugzilla.mozilla.org/show_bug.cgi?id=1367105
