### ISSUE TITLE
Resolve 4 warnings from new CodeQuality CI checks

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#2050]
@peterp @dac09 

For v0.28 release, I'd like us to assess and prioritize the current Code Scanning warnings:
https://github.com/redwoodjs/redwood/security/code-scanning

Please take a look when you have a chance. And I'll put on list for discussion next week.

**Comment by peterp** [comment]
I've closed them since they're not relevant. 2x are in the dev server. 1x is not a secret, and 1x is irrelevant.

**Comment by thedavidprice** [comment]
That's what it seemed so thank you for taking a look and confirming. Perfect!

Closing out.
