### ISSUE TITLE
Configuration to `createLogger()`with prettyPrint options overwrites prettyPrint defaults

### ISSUE THREAD

**Issue by realStandal** [redwoodjs/redwood#2051]
The following is a bug-report for the `canary` API-side logging.

A configuration such as:

```JavaScript
export const logger = createLogger({
  options: {
    prettyPrint: {
      translateTime: 'yyyy-mm-dd HH:MM:ss',
    },
  },
})
```

Will overwrite all defaults, resulting in output similar to:

![Incorrectly formatted log output](https://user-images.githubusercontent.com/25166787/111891533-2f9ab800-89ca-11eb-9988-abc876034e0c.png)

As opposed to:

![Correctly formatted log ouput](https://user-images.githubusercontent.com/25166787/111891541-417c5b00-89ca-11eb-906b-fcdd572f1fb4.png)

Resulting in the need to re-define defaults, brining `createLogger's` call to:

```JavaScript
export const logger = createLogger({
  options: {
    prettyPrint: {
      colorize: true,
      ignore: 'hostname,pid',
      levelFirst: true,
      messageFormat: false,
      translateTime: 'yyyy-mm-dd HH:MM:ss',
    },
  },
})
```

**Comment by dthyresson** [comment]
These prettyPrint options are lost when setting prettyPrint to anything otehr than true -- that is, you either have to include all the defaults when you wish to add or change a default:

```js
export const defaultLoggerOptions: LoggerOptions = {
  prettyPrint: isPretty && {
    colorize: true,
    ignore: 'hostname,pid',
    levelFirst: true,
    messageFormat: false,
    translateTime: true,
  },
  prettifier: isPretty && prettifier,
  level: logLevel,
  // nestedKey: 'log',
  redact: redactionsList,
}
```
There is `prettyOptions` type that defines all the possible options:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/afdb4fac83531e27b6ba7a13e65e519b87bcaa30/types/pino/index.d.ts#L544

Will consider a `defaultPrettyOptions` that can be used as the base to then supplement or merged in to append.
