### ISSUE TITLE
Incorrect type declarations for Prisma logging-middleware event emitters

### ISSUE THREAD

**Issue by realStandal** [redwoodjs/redwood#2052]
The following is a bug-report for the `canary` API-side logging.

When using [the provided](https://community.redwoodjs.com/t/redwood-logging-ideas/1046/17) `api/src/lib/prisma.ts`, the following type-warning is encountered:

![Client.$on() error](https://user-images.githubusercontent.com/25166787/111891739-602f2180-89cb-11eb-9dfd-467aad9f9f9c.png)

Where `client.$on()` takes on the following signature:

![client.$on() signature](https://user-images.githubusercontent.com/25166787/111891750-789f3c00-89cb-11eb-9cdd-b7e38085223e.png)

With the following types being used, as generated by `rw prisma generate` in `node_modules/.prisma/client`:

![$on() declaration](https://user-images.githubusercontent.com/25166787/111891767-a8e6da80-89cb-11eb-84d1-483df3d4aa9e.png)

!["U" declaration](https://user-images.githubusercontent.com/25166787/111891768-b00de880-89cb-11eb-9095-5dccf8a894a5.png)

**Comment by realStandal** [comment]
Possibly related to #2053

**Comment by dthyresson** [comment]
I had seen this TS warning, but as yet had not figured out a workaround or solution to find that exact type definition.

This issue gives me some direction, thanks!

**Comment by dthyresson** [comment]
See: https://github.com/prisma/prisma/blob/1d0045fe60dc1992173f3f5be84b24129f0d45a3/src/packages/client/src/generation/TSClient/PrismaClient.ts#L45

```js
export class PrismaClient<
  T extends Prisma.PrismaClientOptions = Prisma.PrismaClientOptions,
  U = 'log' extends keyof T ? T['log'] extends Array<Prisma.LogLevel | Prisma.LogDefinition> ? Prisma.GetEvents<T['log']> : never : never,
  GlobalReject = 'rejectOnNotFound' extends keyof T
```
