### ISSUE TITLE
Prisma requesting TypeScript `4.1.0` on `rw prisma generate`

### ISSUE THREAD

**Issue by realStandal** [redwoodjs/redwood#2053]
The following is a bug-report for the `canary` version of Redwood, `0.27.2-canary.26`. (`rw upgrade -t canary`)

When running `rw prisma generate` to update `@prisma/client` typings, the following warning is given by Prisma:

![Prisma request TypeScript version 4.1.0](https://user-images.githubusercontent.com/25166787/111891806-05e29080-89cc-11eb-81bf-09217b8c89e7.png)

**Comment by dthyresson** [comment]
This may be related to some logging TS, but I have not experiences this warning (yet).

**Comment by dthyresson** [comment]
FYI I just received this warning/error in CI on a new PR:

```terminal
yarn install v1.22.10
[1/4] Resolving packages...
warning Resolution field "typescript@4.1.3" is incompatible with requested version "typescript@~4.0.2"
```

**Comment by dthyresson** [comment]
@realStandal My issue in the CI run resolved itself -- the error was due to the CI runner not being able to dl a package. Re-triggering corrected it.

But, could you try:

`yarn why typescript`

And let us know what you see? It might give an answer or point in a direction.

**Comment by dthyresson** [comment]
> `ts-morph` would satisfy Prisma's constraint.

Actually @dac09 suggested that `ts-morph` might be the "cause". Will have to dig deeper, but thanks for confirming.

**Comment by dthyresson** [comment]
On an upgrade to v0.28 I saw this warning as well:

```terminal
Prisma schema loaded from db/schema.prisma
prisma:warn Your typescript version is 4.0.7, which is outdated. Please update it to 4.1.0 or newer in order to use Prisma Client.
```

**Comment by dthyresson** [comment]
@peterp or @aldonline Is ts-morph something that can be updated/removed from `@redwoodjs#structure` to alleviate the above mentioned Prisma Typescript warning?
