### ISSUE TITLE
[Generators] Scaffold generator broken, possibly others

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#2057]
https://community.redwoodjs.com/t/generate-scaffold-error/1966

> It's possible that an update to Prisma may have changed how they introspect the schema file and report what it contains. We use the output of that introspection to figure out what fields to generate in the scaffold. 
>
> That error is in the code that's generated for the test file for a service. It tests making an update to a field and then checking that the update actually occurred in the database. What should have been a string from the prisma introspection is now an object instead, and that's what's being output in the generated file.

The code that generates the lines he's seeing is here in the service generator:

```javascript
  scalarFields.forEach((field) => {
    if (foreignKeys.includes(field.name)) {
      inputObj[field.name] = `scenario.${modelName}.two.${field.name}`
    } else {
      inputObj[field.name] = scenarioFieldValue(field)
    }
  })
```

If `field.name` was an object instead of a string (which is has been up until this point) we would see this exact error.

**Comment by thedavidprice** [comment]
Just asked in the Forum post about Redwood and Prisma versions. Want to confirm there's nothing out of sync, which could happen if Prisma was manually installed in the project.

But definitely weird.
