### ISSUE TITLE
Minor issue - easy fix - Scaffolded Checkboxes not displaying correctly

### ISSUE THREAD

**Issue by cjreimer** [redwoodjs/redwood#2062]
@cannikin I'm tagging you as I understand you have had a lot to do with the scaffolds.  Thanks for all your work on this!

I recently generated a scaffold that includes a Boolean field.
In the created form I get a checkbox with no width:

![image](https://user-images.githubusercontent.com/51102303/112083655-71a43500-8b55-11eb-9734-5e106a4c59c5.png)

It appears to be a CSS issue.  Simply  removing one line in scaffold.css works for me to fix the issue:

```
.rw-input[type='checkbox'] {
  /*width: initial;*/
  margin-left: 0;
}
```

Making this change results in:
![image](https://user-images.githubusercontent.com/51102303/112083871-d95a8000-8b55-11eb-9d9b-8fb2a8df7742.png)

I am on Windows and tested this on Chrome, Edge and Firefox.
Notes:  
1.  I copied the latest 'scaffold.css.template' from the codebase into my app to make sure that I wasn't outdated on the scaffold.css.

I am a CSS rookie, so it would be great if someone could review this as a potential fix to the scaffold.

Thanks!

**Comment by Tobbe** [comment]
![image](https://user-images.githubusercontent.com/30793/112110400-1ef96600-8bb3-11eb-87f4-dc8c96469e6b.png)

I'm guessing there was a reason I did that... But I can't remember right now 🙁 
Could also be that some other style changed, that affects this.

Do you have a project I can clone that reproduces this bug?

**Comment by cjreimer** [comment]
Thanks @Tobbe for encouraging me to create a project that reproduces it.  I now have more information.  I wrongly assumed that if I wasn't using tailwindcss on the page that it wouldn't affect the checkbox display.  It turns out it doesn't appear to be tailwindcss itself, but rather tailwindcss/forms.  The checkbox display works after the command

`yarn rw setuptailwind`

but doesn't work after I install tailwindcss/forms

from my package.json file:
```
"dependencies": {
    "@redwoodjs/forms": "^0.27.1",
    "@redwoodjs/router": "^0.27.1",
    "@redwoodjs/web": "^0.27.1",
    "prop-types": "^15.7.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "@tailwindcss/forms": "0.2.1"
  },
  "devDependencies": {
    "autoprefixer": "9.8.6",
    "postcss-loader": "4.0.2",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat"
  }
````
The repo with this is at:
https://github.com/cjreimer/cjr-redwood-checkbox

I did check the proposed fix from the original post on a base redwood app and it does corrupt the checkbox to center it.
![image](https://user-images.githubusercontent.com/51102303/112235628-0cac1600-8c0d-11eb-835c-9c1bee687769.png)

I believe the issue is because of the width in rw-input, which gets applied to all inputs

```
.rw-input {
  display: block;
  margin-top: 0.5rem;
  width: 100%;
  ....

```

One solution would be to point to a different css class if it's a checkbox.

Something like .rw-input-checkbox

To implement in redwood, this would require a change to the actual scaffold template file, namely 
`   src/commands/generate/scaffold/templates/components/NameForm.js.template`
and possibly more (further review required).  I did check this concept and it appears to address the original issue.

So, the question is, do we want to make a change to the scaffold.css and the template to fix a minor incompatibility with tailwindcss/forms, which can easily be fixed by any user who knows what they are doing in their own application's scaffold.css ?

**Comment by Tobbe** [comment]
> So, the question is, do we want to make a change to the scaffold.css and the template to fix a minor incompatibility with tailwindcss/forms

My gut reaction is "No". But I know how much a lot of RW devs and users love TW, so, maybe? 

I'm pretty sure if someone said "Hey, I added Bootstrap, and now my forms look different" we'd be like "Yeah, no shit" 😄 and close the issue without further action 🙂 

It does seem to be a pretty small and simple fix though, for this case... @thedavidprice What say you?

**Comment by thedavidprice** [comment]
Will get to a review + recommendation just after we're done with the v0.28 release. Thanks all!

**Comment by cannikin** [comment]
Can we add an override for the 100% width on check/radio boxes?

```css
.rw-input {
  width: 100%;
  ....
}
.rw-input[type="checkbox"], .rw-input[type="radio"] {
  width: auto;
}
```

I should have done that to start with, I forgot about 100% width affecting those guys!

We should definitely change this in the real scaffold.css so everyone gets it going forward.

**Comment by cjreimer** [comment]
Thanks for replying @cannikin.

I tested your proposal to just override the 100% width with auto, and it does **not** work in my app with tailwindcss/forms.

However, 

```
.rw-input[type='checkbox'] {
  width: 1rem;
}
```

does appear to work for the checkbox in apps both with and without tailwindcss/forms.

**Comment by cannikin** [comment]
Sounds good to me! PR incoming...

**Comment by cjreimer** [comment]
Thanks @cannikin !
