### ISSUE TITLE
multiValueHeaders are not handled by awsLambda request handler

### ISSUE THREAD

**Issue by bhumilsarvaiya** [redwoodjs/redwood#2065]
The awsLambda requestHandler defined in dev-server and api-server package doesn't handle multi-value headers. For example when multiple cookies are set in response. Example code:

```js
let express = require("express");
let serverless = require("serverless-http");

let app = express();

app.use((req, res) => {
    res.cookie('x', 'y');
    res.cookie('a', 'b');
    res.json({});
});

export const handler = serverless(app);
```

Saving the above code in file api/functions/temp.js and then calling api http://localhost:8911/temp, it can be confirmed that the cookies are not sent back in the response. It is because in function `expressResponseForLambdaResult`, `lambdaResult` returns `multiValueHeaders` which is completely ignored.

**Comment by thedavidprice** [comment]
Thank you@bhumilsarvaiya Looping in @peterp for discussion.

**Comment by thedavidprice** [comment]
Very nice! @peterp is asleep now (in South Africa) but I'll keep this on his radar for some thoughts + direction. This week we're focused on getting v0.28 released, FYI.

Depending on your availability and the amount of work required, opening a draft PR does help move the discussion forward. We might not move forward and merge it, but we always welcome taking that step. Keep me posted if you're interested and/or have questions.

**Comment by bhumilsarvaiya** [comment]
Sure, will do that.

**Comment by jtoar** [comment]
@dthyresson @dac09 Could I assign this to one of you guys?

**Comment by dthyresson** [comment]
> @dthyresson @dac09 Could I assign this to one of you guys?

We'll have to adapt this connect to Fastify -- and check it still ins an issue since this was raised when the api-server was still Express.

Can assign to me. I seem to have lost my assignment permissions.

**Comment by dthyresson** [comment]
I chatted with SuperTokens the morning and they are implementing multiValueHeaders as part of their SuperTokens JWT support.

Will revisit this issue and attach to their PR when submitted.

**Comment by dthyresson** [comment]
This issue will be resolved by https://github.com/redwoodjs/redwood/pull/3981 when merged in.
