### ISSUE TITLE
Add a flag to toml to allow a user to toggle esbuild

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2069]
Instead of having to use the `--esbuild` flag

**Comment by thedavidprice** [comment]
@peterp assuming we want this in v0.28. Prioritizing accordingly.

**Comment by peterp** [comment]
@thedavidprice I think I would like to get this into the next release so that @dac09 can test it out with prerendering.

**Comment by dac09** [comment]
Hey @peterp - would you like me to take this over?

**Comment by thedavidprice** [comment]
FYI: I'm going to work on this for the Contributors Workshop tomorrow.
