### ISSUE TITLE
Figure out a way to remove PageLoadingContext

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2070]
Earlier this evening we discussed removing the PageLoadingContext from the Router because it adds a layer of complexity that's difficult to reason about.

The initial idea is to remove PageLoadingContext, but make it optional in some routes.

Maybe @Tobbe, @dac09 , @jtoar and myself can come up with some nice.

Thanks to @jtoar for bringing this up.

**Comment by jtoar** [comment]
The main reason we wanted to remove page loading context was that it made the router hard to understand. This may not be as acute after we finish some of the refactors that are underway (most notably https://github.com/redwoodjs/redwood/pull/3772).
