### ISSUE TITLE
Hide implementation details for Prisma logging

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2074]
In the upcoming release (v0.28.0) we've added the ability to log prisma events via a `api/src/lib/prisma.ts` file which configures the way Prisma emits events and associates the user's logger to those events in order to capture them.

My concern is that Prisma modifies their logging api and that a bunch of user's would have to update their logging code in order to upgrade to a future release.

My proposal is such that the capturing of Prisma logging events is obscured:

```ts
// /api/src/lib/db.ts

import { PrismaClient } from '@prisma/client'

import { emitLogLevels, handlePrismaLogging } from '@redwoodjs/api/logger'

import { logger } from './logger'

/*
 * Instance of the Prisma Client
 */
export const db = new PrismaClient({
  log: emitLogLevels(['info', 'warn', 'error']),
})

handlePrismaLogging({
  db,
  logger,
  logLevels: ['info', 'warn', 'error'],
})
```

We could then remove `api/src/lib/prisma.ts` and keep `/api/src/lib/db.ts` standard.

**Comment by peterp** [comment]
@dthyresson Let me know if you have any concerns about this.

**Comment by dthyresson** [comment]
> We could then remove `api/src/lib/prisma.ts` and keep `/api/src/lib/db.ts` standard.

Agree, that is definitely the preferred option.

I see that by passing in both a `logger` and the `db` 

```js
handlePrismaLogging({
  db,
  logger,
  logLevels: ['info', 'warn', 'error'],
})
```

that will remove the need to import Prisma (but maybe I'll still have to include Prisma types?) into the logger -- since not all  api implementations will include Prisma.

**Comment by dthyresson** [comment]
But won't `{handlePrismaLogging } from '@redwoodjs/api/logger'` mean that I'll have to 

`import { PrismaClient, Prisma } from '@prisma/client'`

in the logger this tying Prisma and Logger together?

**Comment by dthyresson** [comment]
Actually looking into it more, since `"@prisma/client": "2.x.0",` is already in the api, then the logger package will just be using the types.

I'll give it a go.

**Comment by dthyresson** [comment]
The one issue might be that `LogLevel` and `LogDefinition` as types only in the *generated* Prisma client.

See: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client/#the-prismaclient-npm-package

and

See: https://github.com/prisma/prisma/blob/master/src/packages/client/index.d.ts

```js
export * from '.prisma/client'
```

**Comment by dthyresson** [comment]
But ... I can simply define them I imagine based on the Prisma types:

```js
type LogLevel = 'info' | 'query' | 'warn' | 'error'
type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
```

**Comment by dthyresson** [comment]
It's currently working great. I'll just have to update the docs and I can PR.
