### ISSUE TITLE
[RFC] Change glob import syntax

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2077]
Right now importing a bunch of files is supported on the api side. This can be done with the following syntax:

`import schemas from 'src/graphql/**/*.{js,ts}'`

When we detect `**` we kick in the globbing syntax features. I would like to propose that we consider making it look something like this instead:

`import schemas from 'glob://src/graphql/**/*.{js,ts}`

The proposal has two benefits:
1. It's easier to match in regex.
2. It's clear that there's something different going on here. Whereas the prior work doesn't.

**Comment by jtoar** [comment]
@peterp the new syntax definitely checks the second box. Is the goal of making it stand out to dissuade users from changing it?

**Comment by jtoar** [comment]
Another suggestion: we could add a comment above the line, explaining it's a babel macro

**Comment by peterp** [comment]
I'm happy to just close this. The original syntax doesn't seem to bother anyone, so maybe that was premature.

**Comment by jtoar** [comment]
I just saw VS Code suggest this in autocomplete—so maybe we should change it? First time I've seen this happen.

![image](https://user-images.githubusercontent.com/32992335/124066265-5d01f380-da06-11eb-92c2-20ced497972e.png)

**Comment by jtoar** [comment]
I just saw VS Code suggest this in autocomplete—so maybe we should change it? First time I've seen this happen.

<img width="493" alt="Screen Shot 2021-07-01 at 12 52 12 AM" src="https://user-images.githubusercontent.com/32992335/124066425-a05c6200-da06-11eb-8323-8d5c7ee50a7d.png">

**Comment by peterp** [comment]
We've decided that this is not required.

**Comment by peterp** [comment]
Wanted to leave this here as a resource, the first part of a URI is called the scheme, and it's fairly common to create you own, but here's a list of "approved schemes:"

https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml#uri-schemes-1
