### ISSUE TITLE
rwt link error: "https://registry.yarnpkg.com/@redwoodjs%2f.DS_Store: Not found".

### ISSUE THREAD

**Issue by KrisCoulson** [redwoodjs/redwood#2078]
When running through the contributor documentation I ran into an issue when trying to run rwt link on my newly created redwood-app

![image](https://user-images.githubusercontent.com/6943688/112284348-5fee8a80-8c46-11eb-8a87-912457336024.png)

I ran `yarn install`: it worked 
I ran `yarn rwt link` it fails
I ran `yarn install` again and it continuously fails

`yarn-error.log` information
```
Arguments: 
  /usr/local/Cellar/node/15.2.1/bin/node /usr/local/Cellar/yarn/1.22.10/libexec/bin/yarn.js install

PATH: 
  /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Yarn version: 
  1.22.10

Node version: 
  15.2.1

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/@redwoodjs%2f.DS_Store: Not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:66988:18)
      at Request.self.callback (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:140749:22)
      at Request.emit (node:events:329:20)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:141721:10)
      at Request.emit (node:events:329:20)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:141643:12)
      at Object.onceWrapper (node:events:435:28)
      at IncomingMessage.emit (node:events:341:22)
      at endReadableNT (node:internal/streams/readable:1294:12)
      at processTicksAndRejections (node:internal/process/task_queues:80:21)
```

Additionally, I did downgrade node to 14.16.0 just to check if the node version was to high and had a similar issue

**Comment by Tobbe** [comment]
@dac09 Could you take a look at this please?

**Comment by dac09** [comment]
Thanks for raising this @KrisCoulson I'll have a fix for this soon, I found this happening on my machine occasionally too.

For now, what you can do is remove the `.DS_Store` file in `redwood/packages/.DS_Store`. 

And run `yarn rwt unlink && yarn rwt link`

**Comment by thedavidprice** [comment]
@dac09 is this related to work in https://github.com/redwoodjs/redwood/pull/1960 ?

**Comment by KrisCoulson** [comment]
> Thanks for raising this @KrisCoulson I'll have a fix for this soon, I found this happening on my machine occasionally too.
> 
> 
> 
> For now, what you can do is remove the `.DS_Store` file in `PATH_TO_REDWOOD/packages/.DS_Store`. 
> 
> 
> 
> And run `yarn rwt unlink && yarn rwt link`
> 
> 
> 
> If you're struggling still, it might help if you do a reinstall of the redwood modules like so, before running link
> 
> `rm -rf node_modules/@redwoodjs && yarn install --check-files`

Awesome thanks for the tip @dac09 I will give it a shot this afternoon

**Comment by dac09** [comment]
> @dac09 is this related to work in #1960 ?

@thedavidprice 1960 will solve this yes, but there's some outstanding questions there (see PR discussion) before we can get it merged.

**Comment by KrisCoulson** [comment]
@dac09 unfortunately I still could not get this to work following your instructions above. I still ran into errors. I will patiently wait for #1960

**Comment by jtoar** [comment]
@KrisCoulson since #1960 got merged I'll close this out; let me know if it's still not solved for you!
