### ISSUE TITLE
yarn redwood generate page home / not working

### ISSUE THREAD

**Issue by patcito** [redwoodjs/redwood#208]
When I run:

`yarn redwood generate page home /` 

I get the following error:

`Error: ENOENT: no such file or directory, scandir '/home/pat/repos/redwoodblog/node_modules/@redwoodjs/cli/dist/commands/generate/commands'
`
I was able to fix it by doing the following:

`cp -R /home/pat/repos/redwoodblog/node_modules/@redwoodjs/cli/dist/commands/generate /home/pat/repos/redwoodblog/node_modules/@redwoodjs/cli/dist/commands/Generate`

It seems like there's an issue with case sensitive directory naming? I'm on Ubuntu so this may be why.

**Comment by thedavidprice** [comment]
Issue indeed! And hot off the press a fix has already been merged into master here #204 just not published yet.

Thanks for letting us know. And keep us posted about how things go as you work through the Tutorial.
