### ISSUE TITLE
Add types to config files

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2088]
I saw this in another PR and I think it's a really great addition:

This add types to the jest configurations, I think we should do the same for all our configs.
https://github.com/redwoodjs/redwood/blob/0002df4f75e9119f92eaf74d49fb3fe6635e43ad/packages/testing/jest.config.js#L1

- [ ] Find all the config files: babel, webpack, storybook, etc.
- [ ] Figure out if they have type definitions.
- [ ] If they do, add them.

**Comment by renansoares** [comment]
can I pick up this?

**Comment by thedavidprice** [comment]
@renansoares Yes, please! Thank you for jumping in and offering. 

Keep Peter in the loop as you go. And let us know if you have any questions.

**Comment by renansoares** [comment]
hi @peterp, could I add it to all functions that return some config that has defined external typing? ex: this line for webpack

https://github.com/redwoodjs/redwood/blob/439f23142805c87a369ba1597bd4099d6ba1d473/packages/core/config/webpack.common.js#L36

in this case, I would need to add something like `  /** @return {import('webpack').RuleSetRule} */`

I'm wondering if there is some limit to not pollute much the code...

**Comment by peterp** [comment]
@renansoares I think it's ok to add it to the top-level `module.exports`
