### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood#2092]
Running `yarn rw prisma migrate dev` [Tutorial/getting dynamic](https://learn.redwoodjs.com/docs/tutorial/getting-dynamic#migrations)
```
api | (node:29384) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
api | (Use `node --trace-warnings ...` to show where the warning was created)
api | (node:29384) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
api | (node:29384) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```

  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 14.16.0 - ~\AppData\Local\Temp\yarn--1616619444356-0.4627899714501982\node.CMD
    Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1616619444356-0.4627899714501982\yarn.CMD
  Browsers:
    Chrome: 89.0.4389.90
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.57)
  npmPackages:
    @redwoodjs/core: ^0.27.1 => 0.27.1

**Comment by thedavidprice** [comment]
Confirming I see this as well on Mac OS when running `yarn rw dev`.

Needs further diagnosis.

**Comment by peterp** [comment]
This is fixed in esbuild. The dev-server will become deprecated, and we'll use `api-server` in watch mode instead.

**Comment by peterp** [comment]
@adriatic Please try using `yarn rw dev --esbuild` when v0.28.0 is released

**Comment by adriatic** [comment]
Will do and report back here
