### ISSUE TITLE
Add per request global context test to E2E

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#2095]
@peterp when we discussed adding a test for the changes in https://github.com/redwoodjs/redwood/pull/1789, I believe you had an idea for adding a test to our E2E runner.

Making sure we follow-up and discuss next steps (if any).

**Comment by peterp** [comment]
I've added a jest test fo this, and as for e2e they're enabled by default, so if the e2e tests are working then so is the per-request context!

I don't think we need anything else.
