### ISSUE TITLE
how to implement RBAC

### ISSUE THREAD

**Issue by debianmaster** [redwoodjs/redwood#212]
Thanks for great work! this sounds promising.
the tough part now..
How to implement RBAC / AuthZ on top of redwood?  
I love redwood is using graphql but question of authz remains un answered.  could you add an example ?  or guide me to some references

**Comment by peterp** [comment]
Thanks! We had authorisation stuff in earlier, but we had to take it out. We want to support auth0 and Netlify identity as a start.

We'll get back onto adding that really quickly, it's very important to what we consider our ideal use case.

I've opened an issue here #214.

**Comment by thedavidprice** [comment]
@debianmaster Thanks for asking! Going to close this out in favor of consolidating topic to #214 Please do join the conversation there if/as needed. 

Wish we could offer more at this time including a schedule, but we are simply not there yet. Definitely on our list of priorities.
