### ISSUE TITLE
Should searchParams overwrite path params?

### ISSUE THREAD

**Issue by KrisCoulson** [redwoodjs/redwood#2121]
While working with the new Set component and digging through some code I noticed that we don't split `pathParams`  from `searchParams`. They are all just considered `params`. 

In the `router.tsx` searchParams will overwrite whatever you have in your path. 
https://github.com/redwoodjs/redwood/blob/49bea7cad18178511d9c21fd3edee0526aa187ee/packages/router/src/router.tsx#L128-L129

Example Route
```/user/{id:Int}/contact/{contactId:Int}?contactId=12```

by passing `contactId=12` that will override whatever is being sent as a pathParam.  This particular example would also fail. If this was a cell the `contactId` would be passed to the cell as string 12 and the graphql query would fail due to it expecting an Int. Like the example, this is concerning because the param values get passed to Cell components as props.

I am not sure what the answer here is. 
Should they be separated into`{ params, searchParam}` ?
Should we document this limitation?
Should `pathParams` overwrite `searchParams` ?

This is an edge case but could easily happen. Figured I would raise this up to start a discussion.

**Comment by Tobbe** [comment]
As I mentioned when we talked about it, I think we should keep them as one, cuz it's really nice being able to do 
```
const MyPage = ({ contactId }) => { /* ... */ }
```
and just have it available in the page

But I do think we should switch the logic around, so `pathParams` overwrites `searchParams`. That way no user can come and just overwrite your variables by appending ?whatever to the URL.

And all of this should definitely be documented!

But this is just my opinion. I'm also curious to hear what others think.

**Comment by benatkin** [comment]
I think that path params should overwrite searchParams if one is allowed to override the other, and that it's a minor security issue if it doesn't. If I wanted to keep an eye on a user with the ID `50` being updated, I might add a log alert for `PATCH /user/50`. If they were able to hide it behind `PATCH /user/95?id=50` that would be bad.

I would also consider throwing an error if the same parameter is given both in the path and the query rather than having one override the other.

**Comment by KrisCoulson** [comment]
@peterp @Tobbe @jtoar im working on a few of the router tickets. What's the call on this ticket? I we just spreading ```{...pathParams, ....searchParams }``` or do we want to go with separate params. There are a few tickets in the Router Epic #2567 that would depend on what we choose here.

**Comment by Tobbe** [comment]
My preference would be to switch them around: `{ ...searchParams, ...pathParams }`

**Comment by KrisCoulson** [comment]
> My preference would be to switch them around: `{ ...searchParams, ...pathParams }`
Yeahh woops yeah pathParams should overwrite searchParams

**Comment by facinick** [comment]
Hello, can I fix this? How do I find issues that no one is working on already?

**Comment by KrisCoulson** [comment]
@facinick definitely!  no one is assigned to this one so I would say just open up a PR with some changes and link it to this issue.
