### ISSUE TITLE
Upgrade to PostCss 8 so that can use later versions of TailwindCss/UI

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#2123]
Currently one has to use a PostCss compatible version of TailwindCss.

```js
  "devDependencies": {
    "autoprefixer": "9.8.6",
    "postcss-loader": "4.0.2",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat"
  }
}
```

@jtoar I recall you looked into this when creating the Tailwind setup.

@thedavidprice thinks it may have been related to WebPack 4 or 5.

What do you think it would take to upgrade to PostCss 8 and then be able to use the latest TW releases?

@Burnsy is using https://github.com/ben-rogerson/twin.macro and has some issues given it requires 8 with RW requires 7.

**Comment by dthyresson** [comment]
@jtoar has proposed adding this PostCSS update to a 28.x patch.

**Comment by jtoar** [comment]
Seems like this is just a matter of upgrading css-loader to v5 so far, which is being handled in #2402. Will make sure that's all that's needed.
