### ISSUE TITLE
Navigating to a route not previously visited flashes white

### ISSUE THREAD

**Issue by o0charlie0o** [redwoodjs/redwood#2124]
I just went up from `0.26.2` to `0.28.0` and now when I navigate to a route using Link that I haven't yet visited in the current session the screen briefly flashes white before displaying the next route. This was not the case in `0.26.2` and before. The 2 routes I've navigated between have the same overall layout and navigation. I suspect it may have something to do with the new `<Set wrap={}>` feature which we are not currently using. Maybe implementing that would resolve the flashing issue but I still think this is a bug.

Edit:
I realized I can't easily use the Set feature anyways with our current Layout component because it takes a couple of props to dynamically render some things in the layout between different pages.

**Comment by dthyresson** [comment]
@dac09 Is visiting `route not previously visited flashes white` issue reported here related to prerender and if one needs to import the Page in Routes?

**Comment by Tobbe** [comment]
Manually importing the page would be a good first test no matter what 🙂 @o0charlie0o Could you do that please, and see if the flashes goes away?

**Comment by o0charlie0o** [comment]
@Tobbe @dthyresson Manually importing the pages does indeed fix the issue.

**Comment by dthyresson** [comment]
Thanks! @o0charlie0o.

@dac09 Does 

> Manually importing the pages does indeed fix the issue.

need to be added to documentation, or is there another issue?

**Comment by o0charlie0o** [comment]
@dthyresson @dac09 If any documentation were to change regarding manual imports in the Routes file then the comments in the template should probably change too assuming this is intended and there isn't an underlying bug.

https://github.com/redwoodjs/redwood/blob/439f23142805c87a369ba1597bd4099d6ba1d473/packages/create-redwood-app/template/web/src/Routes.tsx#L1-L8

**Comment by dac09** [comment]
I do think this is still a bug and worth investigating. Importing the page means that it isn't going to be code split, which isn't ideal, but also tells me it's something to do with the page-loader component!

**Comment by o0charlie0o** [comment]
@Tobbe Assuming this issue can be closed based on the following PR being merged?
- https://github.com/redwoodjs/redwood/pull/3772

**Comment by Tobbe** [comment]
Indeed! 😀
