### ISSUE TITLE
Router seems not to be working in testing

### ISSUE THREAD

**Issue by jvanbaarsen** [redwoodjs/redwood#2131]
I have a very straight forward test (Just checking if no error is thrown), it renders a link on that page, in the browser this works, but in the tests I get this error:

```
Error: Uncaught [TypeError: _router.routes.signin is not a function]
```

I'm wondering if this is something that just me is seeing, or that a bug might have slipped in when we introduced <Set> into the router. (This worked before that upgrade)

**Comment by jvanbaarsen** [comment]
I double checked my assumption, when I removed the `<Set>` around the routes the test are OK, so somehow the tests aren't aware of any routes inside a `<Set>`

**Comment by Tobbe** [comment]
Could you please describe exactly how to reproduce this? Or a project we can run that shows the bug?
Thanks Jeroen!

**Comment by jvanbaarsen** [comment]
I'll create a test project for you!

**Comment by jvanbaarsen** [comment]
@Tobbe https://github.com/jvanbaarsen/rw-router/tree/main. Just check it out and run `rw test web`

**Comment by Tobbe** [comment]
@jvanbaarsen Thank you, that's really helpful. 

I can confirm the bug. This is the output I get

![image](https://user-images.githubusercontent.com/30793/112729657-9cafcf80-8f2d-11eb-8812-b757f4503c07.png)

And here's the code that causes it to fail

```javascript
// web/src/pages/SomePagePage/SomePagePage.test.js
import { render } from '@redwoodjs/testing'

import SomePagePage from './SomePagePage'

describe('SomePagePage', () => {
  it('renders successfully', () => {
    expect(() => {
      render(<SomePagePage />)
    }).not.toThrow()
  })
})
```

**Comment by Tobbe** [comment]
I've tried debugging this for a while, and I think I know what's wrong. My guess is that the location isn't set properly when running the tests. But I can't get console.log to print anything when added to stuff inside the RW framework and running the tests. So I'm a bit stuck at the moment 🙁

**Comment by Tobbe** [comment]
I'm making progress! I just figured out we have a separate `MockRouter` that we use for testing. When I rewrote the main router I should have updated the mock router too. I'm off to bed now, but will have a look at MockRouter tomorrow
