### ISSUE TITLE
@apollo/client no longer exported from web

### ISSUE THREAD

**Issue by vchoy** [redwoodjs/redwood#2132]
Similar to:

https://github.com/redwoodjs/redwood/issues/1184

Error:
Module not found: Error: Can't resolve '@apollo/client' ( in [web] form component))

### Reproduce
Upgrade RW to 0.28 or 0.28.1

Works fine in 0.27.1 and below.

**Comment by peterp** [comment]
Hey @vchoy,

Please import this direct from apollo.

**Comment by vchoy** [comment]
Understood @peterp,

`/`import { useLazyQuery } from '@redwoodjs/web/node_modules/@apollo/client'
seems to work.
I'll PR an updated documentation

**Comment by vchoy** [comment]
Dev notes:

I have tried to import directly as new package added to web component of rw `@apollo/client` however, this resulted in apollo client context missing.

Importing from directly node_modules under @redwoodjs/web doesn't sound quite right. Sorry i'm new to rw

**Comment by vchoy** [comment]
PR for documentation change: https://github.com/redwoodjs/redwoodjs.com/pull/651/commits/d47c1a6627ce1eb00ed515ea2059508d36ac0c0c

**Comment by vchoy** [comment]
Closing this as the answer is to remove the yarn.lock file and regenerate on yarn install.
