### ISSUE TITLE
Fix `CONTRIBUTING.md#integration-tests`

### ISSUE THREAD

**Issue by wafuwafu13** [redwoodjs/redwood#2136]
https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md#integration-tests

`./tasks/test-tutorial` have been replaced by `./tasks/test-tutorial.js` in https://github.com/redwoodjs/redwood/pull/1896, and `tasks/test-tutorial.js` have been replaced by `tasks/run-e2e` in https://github.com/redwoodjs/redwood/pull/1810 .

**Comment by devhmac** [comment]
I'm happy to update these couple lines in the docs if that's all good!

**Comment by thedavidprice** [comment]
@devhmac yes please! This is in need of updating asap (oops!).

Should be `.tasks/run-e2e` from the command line.

If you open a PR, loop me in and we'll get it merged quickly.
