### ISSUE TITLE
Allow `beforeQuery` in a Cell component to receive the params

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2139]
The router/ location is a form of state. It would be great to be able to grab the params and use that in a GraphQL query.

Something like:
```
export const beforeQuery = ({ params, ...props }) => {
   return {
       variables: {
           documentId: params.id
       }       
   }
}
```

I think this should be fairly achievable by passing the params in the `withCell`

**Comment by Tobbe** [comment]
Semi-related to https://github.com/redwoodjs/redwood/issues/2121 maybe it should be `beforeQuery = ({ pathParams, searchParams, ...props })` to avoid conflicts. The solution here should be aligned with whatever is decided for #2121

**Comment by jtoar** [comment]
@peterp just to clarify: normally how it goes is the Page receives the router/location as props, then you pass those down into a Cell. The change your suggesting would eliminate the need to ever pass router/location props from a Page to a Cell? Basically, this part of the tutorial would be irrelevant: https://learn.redwoodjs.com/docs/tutorial/routing-params#using-the-param

**Comment by peterp** [comment]
Yeah - What I'm seeing in my own development is that a lot of my cell's variables are based on the current location in that path params.

So I either do that with `useParams` in the container component and pass it in. Maybe there's a flag that we can toggle on the cell to enable this behaviour, or we could create a HOC that does this for us.

I'm on the fence - since we exposed `createCell` and people can compose cells programmatically this may not be an issue anymore.

**Comment by ajoslin103** [comment]
I ended up wrapping things in LocationProvider, then I could then call useLocation() hook

https://community.redwoodjs.com/t/detect-the-current-route-in-a-view/587/11?u=ajoslin103
