### ISSUE TITLE
Introduce top-level `CellPage` component

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2140]
Now that we have the amazing `Set` component in the Router, Thanks @Tobbe, which removes a bunch of boilerplate, and I often find that I have a page that directly calls a cell.

I think a good addition would be to introduce a "CellPage" component, which is a Page that has the lifecycle methods of a "Cell."

This may also be a good starting point for `getStaticProps`

**Comment by Tobbe** [comment]
Here's an example from the tutorial

![image](https://user-images.githubusercontent.com/30793/112816482-c11cc080-9081-11eb-97cb-22e053ab02c7.png)

This could be simplified to just a `<HomeCellPage>` that directly exported `QUERY`, `Success` etc. 

Here's another example

![image](https://user-images.githubusercontent.com/30793/112817309-91ba8380-9082-11eb-83bd-e21fb8f761c1.png)

But that brings up the question of reusability. What if you wanted to use `<BlogPostCell>` in more than one place? If it was called `<BlogPostCellPage>` it'd be weird to include it as part of another page.

**Comment by peterp** [comment]
Could also be called `CellPage`

**Comment by cjreimer** [comment]
OK, I've been stewing on this since @peterp posted this.  I like the idea of having fewer almost empty source code files.  However, so far from my experience, I like the feel of "Cells" and "Pages" being distinct.  So rather than creating a new combined cell/page type, I'll throw out another idea.

My proposal is as follows:
- Allow an alternative form of a cell implemented in a 'hook' type format within a page (or any other component)

A simple use case, based upon the tutorial, is below :

```
import BlogPost from 'src/components/BlogPost'
import { useCell } from 'src/components/CellHook'

const QUERY = gql`
  query BlogPostQuery($id: Int!) {
    post(id: $id) {
      id
      title
      body
      createdAt
    }
  }
`

const BlogPostPage = ({ id }) => {
  const Loading = () => <div>Loading...</div>

  const Empty = () => <div>Empty</div>

  const Failure = ({ error }) => <div>Error: {error.message}</div>

  const Success = ({ post }) => {
    return (
      <div className="-mt-10">
        <BlogPost post={post} />
      </div>
    )
  }

  const BlogPostCellTest = useCell({ QUERY, Loading, Empty, Failure, Success })

  return <BlogPostCellTest id={id} />
}

export default BlogPostPage

```

This allows us to keep the source file count down in many cases.  I created a basic useCell hook-style component based upon withCellHOC, and the concept works.   It doesn't use babel and doesn't break any existing Cell code, as it is an alternative.

Thoughts?

**Comment by corbt** [comment]
@cjreimer 's proposal is similar to what I proposed in https://github.com/redwoodjs/redwood/issues/2205 . I'm not sure there's any advantage to implementing this as a hook though -- cells don't need to provide any state or callbacks to their parents?

If we ship https://github.com/redwoodjs/redwood/issues/2205, there may be less need for a first-class `CellPage`. For cells that map to pages 1:1, you can just define the cell inline in the page's source file by calling `createCell`. Here's how the tutorial `HomePage.js` might look:

```js
// web/src/pages/HomePage.js

import { createCell } from '@redwoodjs/web'

const QUERY = gql`
  query {
    posts {
      id
      title
      body
      createdAt
    }
  }
`;

const Loading = () => <div>Loading...</div>;
const Empty = () => <div>No posts yet!</div>;
const Failure = ({ error }) => <div>Error loading posts: {error.message}</div>;
const Success = ({ posts }) => posts.map((post) => <BlogPost post={post} summary />);

const HomePageCell = createCell({ QUERY, Loading, Empty, Failure, Success });

export default HomePageCell;
```

**Comment by cjreimer** [comment]
Yes, my error for calling it 'hook' style.  @corbt is correct.

I like your idea of calling it `createCell`.  In addition to your example, it also gives us the flexibility to create and incorporate a cell directly in a page or other component without creating additional files.  Hey, we can create 5 different cells within a page component if we wanted to.

**Comment by peterp** [comment]
@cjreimer @corbt Love the collaborative effort here. This is what makes open-source amazing, the refinements of ideas following along the same thread of thought. Kudos to the both of you.

**Comment by peterp** [comment]
Closing in favour of #2205
