### ISSUE TITLE
[Prisma Bug] Error while generating Prisma client in Example Blog

### ISSUE THREAD

**Issue by ncphillips** [redwoodjs/redwood#215]
This project looks great! I'm hoping to get a demo going with [TinaCMS](http://github.com/tinacms/tinacms) added to it for content editing. 

Unfortunately, running `yarn rw db up` threw an error while I was trying to setup the `example-blog`.

```
Migrate database up... [completed]
Generating the Prisma client... [started]
Error: Error: Command was killed with SIGSEGV (Segmentation fault): /Users/ncphillips/Code/ncphillips/example-blog/node_modules/prisma2/query-engine-darwin --enable_raw_queries cli --dmmf
Generating the Prisma client... [failed]
→ Command failed with exit code 1: prisma2 generate
Command failed with exit code 1: prisma2 generate
✨  Done in 1.66s.
```

I can reliably reproduce by following the [Install Steps](https://github.com/redwoodjs/example-blog/#installation) for the Example Blog, even from a fresh clone. The only thing I changed from teh repo is I switched the datasource provider to `sqlite`.

| OS | macOS 10.15.3 |
| node |  12.14.1 |
| yarn | 1.15.2 |

**Comment by peterp** [comment]
Hey @ncphillips, you're the second person (that we know of) that has experienced this segfault. @sw-yx was the other one. I'll report this to the Prisma team!

**Comment by ncphillips** [comment]
Wicked! I updated the title to appropriately pass the buck 😉

**Comment by janpio** [comment]
Hey @ncphillips, thanks for reporting this - I created a sister issue over at Prisma so we do not spam this one with our investigation: https://github.com/prisma/prisma2/issues/1819 You can subscribe to that one for updates, and we might @ mention you to e.g. request more information.

**Comment by janpio** [comment]
@ncphillips, can you still reproduce the problem with the segfault? If so, could you zip up the whole project and send it over to piotrowski@prisma.io?

We currently can reproduce this ourselves consistently, but have a theory that the binary might have been corrupted somehow. Having the actual file would allow us to check that.

**Comment by ncphillips** [comment]
@janpio done 👍

**Comment by janpio** [comment]
Thank you so much, with the binary you sent in we can indeed reproduce the error consistently. Something is funky here. Very funky.

To work around this, you can download the binary manually from https://prisma-builds.s3-eu-west-1.amazonaws.com/master/d3b0ceed5d87544b9d2decb70e08664f9047bb73/darwin/prisma.gz, unpack it and rename the file `prisma` to `query-engine-darwin`, then replace the existing `node_modules/prisma2/query-engine-darwin` file with it. Then you should be able to successfully run `yarn rw db up`.

Would actually be great if you could try these steps, just to confirm this really works and there is nothing on your system messing with these files (one of the theories we are currently looking into... yes, it sounds crazy).

**Comment by ncphillips** [comment]
Yeeeee boi

<img width="568" alt="image" src="https://user-images.githubusercontent.com/824015/76581335-cc6e6f80-64b1-11ea-87dc-838488f78efd.png">

**Comment by janpio** [comment]
Ok - thank you! So the problem definitely is in the downloading or unpacking of the binary. 

We are investigating and will try to figure out what exactly is wrong here, but also implement measures to warn users or fix it for them (if possible). We'll keep you updated here.

**Comment by peterp** [comment]
Amazing, thanks @janpio. I'm going to close this.

**Comment by bpenno** [comment]
I am receiving a similar issue on Windows although in my case the Generating Prisma client step would just hang and I had to terminate it after leaving it for 10 minutes. Eg.

![image](https://user-images.githubusercontent.com/10125593/76813652-8fef9a80-6848-11ea-9dec-ddd16132ae9b.png)

I looked into the solution above that worked for @janpio but my the Prisma node module didn't contain a query-engine-darwin file to replace. I do have these following files though - query-engine-rhel-openssl-1.0x and query-engine-windows.exe. Should I be looking to update one of those instead?

**Comment by bpenno** [comment]
Nevermind - I just realized I needed to update the binaryTargets in the schema.prisma file from `binaryTargets = ["native", "rhel-openssl-1.0.x"]` to `binaryTargets = ["native", "windows"]`

**Comment by thedavidprice** [comment]
@janpio I think we have something of like kind to this being reported in our forum running Prisma2 preview023.

Could you take a look and add any suggestions? This is another strange one…

https://community.redwoodjs.com/t/tutorial-fetching-posts-throws-errors/162/12

**Comment by janpio** [comment]
Will do, but I think I have also seen an issue from the user in our repo. Thanks for pinging me.
