### ISSUE TITLE
Do not verify the auth0 token during development

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2155]
I would like to have two paths for the auth0 token:

1. development: decode
2. production: decode and verify

I have fairly slow internet and I'm finding it _really_ difficult to work against auth0. Maybe a second choice is to cache the key to disk or something?

I think we can protect against not verify in production with tests.

@dthyresson thoughts?

**Comment by Tobbe** [comment]
We can do the same checks we do for netlify, to only decode in dev/test

**Comment by dthyresson** [comment]
As @Tobbe noted, this is how `NetlifyIdentity` behaves already (see: https://github.com/redwoodjs/redwood/blob/b4a63efe7057fa182a2257f7dbbf67784658efb5/packages/api/src/auth/decoders/netlify.ts#L14):
```js
  if (
    process.env.NODE_ENV === 'development' ||
    process.env.NODE_ENV === 'test'
  ) {
    return jwt.decode(token)
  } else {
    const clientContext = req.context.clientContext as NetlifyContext
    return clientContext?.user || null
  }

```

One could do the same and just

https://github.com/redwoodjs/redwood/blob/b4a63efe7057fa182a2257f7dbbf67784658efb5/packages/api/src/auth/decoders/auth0.ts#L40

when not development or test.

**Comment by peterp** [comment]
The reason why I pinged @dthyresson is because I think it was this way before, but we might have changed it because we had security concerns... If I'm remembering correctly, but if we're OK with this 👍
