### ISSUE TITLE
E2E: Add Logger check to CI

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#2160]
related to https://github.com/redwoodjs/redwood/issues/1886

@dthyresson Can you suggest a basic Logger functionality check (or checks) we could include in the Cypress tests? It likely needs to be file or path-based as we spin up the dev server in a separate process than Cypress, which means I'm not sure if Cypress has access to the console (I can verify). 

We can make code modifications, which is probably an ideal Cypress use case if applicable.

**Comment by dthyresson** [comment]
@thedavidprice I have not used Cypress before, but I think we would:

* update `logger.ts` in api-side to use a file as a destination to a tmp directory (probably similar to that I use in CI tests)
* update the blog post service to import the logger and do a few trace, info, debugs
* check that log file has some expected content

**Comment by dthyresson** [comment]
Chatted with @thedavidprice and @dac09  and will add `04-api` Cypress integration to test logger.
