### ISSUE TITLE
0.28.3 Submitting a form with an empty DateField will throw an error.

### ISSUE THREAD

**Issue by andrew-hwahin** [redwoodjs/redwood#2162]
RedwoodJS version 0.28.3 ([Sample repo GitHub link](https://github.com/andrew-hwahin/my-redwood-app-v0.28.3))
---------------------------------------------------------------
The DateField is set as optional by excluding `validation={{ required: true }}` 👇
[web/src/components/UserExampleForm/UserExampleForm.js](https://github.com/andrew-hwahin/my-redwood-app-v0.28.3/blob/main/web/src/components/UserExampleForm/UserExampleForm.js) 
```
import { DateField } from '@redwoodjs/forms'
...
  <DateField
    name="birthday"
    defaultValue={props.userExample?.birthday}
    className="rw-input"
    errorClassName="rw-input rw-input-error"
  />
...
```

`birthday` is set as an optional field in sdl 👇
[api/src/graphql/userExamples.sdl.js](https://github.com/andrew-hwahin/my-redwood-app-v0.28.3/blob/main/api/src/graphql/userExamples.sdl.js) 
```
input CreateUserExampleInput {
  email: String!
  name: String
  birthday: DateTime
}
```

![image](https://user-images.githubusercontent.com/61768800/113124007-aa27cb00-9247-11eb-8e23-d2559a3856bd.png)

Expected to be able to submit empty date value.

**Comment by cjreimer** [comment]
Yes, I saw this as well and looked at it briefly in the code.  Looks like the exception will need to be caught in the coercion function.  Let me know if you'd like me to take a stab at it.

**Comment by thedavidprice** [comment]
> Let me know if you'd like me to take a stab at it.

Do you mean updating/fixing in the Framework itself? If so, please do!

**Comment by jtoar** [comment]
@cjreimer thanks for your eagerness and hard work here! Safe to bring this one to a close?

**Comment by cjreimer** [comment]
Yes, I believe this issue can be closed.
