### ISSUE TITLE
@apollo/client cannot be resolved

### ISSUE THREAD

**Issue by KrisCoulson** [redwoodjs/redwood#2165]
In a recent update `@apollo/client` can no longer be resolved
![image](https://user-images.githubusercontent.com/6943688/113208083-40e39000-9226-11eb-952b-9ec5d03a09e1.png)

We have documentation stating that useLazyQuery can be imported from `@apollo/client`
![image](https://user-images.githubusercontent.com/6943688/113208194-5d7fc800-9226-11eb-8890-50d8fc655bbc.png)

I believe that at som. point when the GrapqhlProvider was being introduced this fell through the cracks. Installing `@apollo/client` directly into `src/web` fixes it not being resolved. 

Should users be required to install `@apollo/client` or should these be exported from `@redwoodjs/web/apollo` or make `@apollo/client` available to be imported.

**Comment by KrisCoulson** [comment]
A related PR for updating the documentation was recently submitted by @vchoy

https://github.com/redwoodjs/redwoodjs.com/pull/651

Additionally  tagging @peterp  @Tobbe  from @thedavidprice  request https://discord.com/channels/679514959968993311/716252919875240007/826917616400597023

**Comment by thedavidprice** [comment]
@KrisCoulson can you copy+paste the imports in your `web/src/App.js`? Curious if Apollo from redwood web is there.

**Comment by KrisCoulson** [comment]
@thedavidprice 

```
import { AuthProvider } from '@redwoodjs/auth'
import { isBrowser } from '@redwoodjs/prerender/browserUtils'
import netlifyIdentity from 'netlify-identity-widget'
import { FatalErrorBoundary } from '@redwoodjs/web'
import { RedwoodApolloProvider } from '@redwoodjs/web/apollo'
import FatalErrorPage from 'src/pages/FatalErrorPage'
```

**Comment by thedavidprice** [comment]
@KrisCoulson I successfully tried `import { useLazyQuery } from '@apollo/client'` in my test project. Not sure how to diagnose further. Given that multiple people have reported now, I believe something is going on here 🤔

Any chance you have a repo or example code to share?

@jtoar have you run into this recently?

**Comment by KrisCoulson** [comment]
@thedavidprice besides my main project where the issue is happening I am not able to reproduce... on my redwood-dev test app I just tried the manual import from `@apollo/client` and it is imported with no errors.

**Comment by Tobbe** [comment]
@KrisCoulson Can you please check where the @apollo/client package is located on your filesystem in your two different projects? Do you have just one copy in both projects?

I want to make sure yarn hasn't made any funny decisions here 😬

**Comment by KrisCoulson** [comment]
@Tobbe its actually kinda wierd. Hear me out I add `@apollo/client` in a different branch to `workspace web` and it started working. Which was expected but then I switched back to my `main` branch os that I could answer your question and cleared all the `node_modules` and it isn't throwing that exact error anymore... but it is throwing a different error.

![image](https://user-images.githubusercontent.com/6943688/113253499-2cc97e00-927a-11eb-8d4f-ea1161705cc8.png)

Do note the whole app is wrapped in the `RedwoodApolloProvider`
![image](https://user-images.githubusercontent.com/6943688/113253720-80d46280-927a-11eb-84e7-371cbf05068d.png)

**Comment by Tobbe** [comment]
Do you have a node_modules in both / and web/ ? Where is @apollo/client? In just one of them? In both?

**Comment by vchoy** [comment]
@Tobbe , it's bundled as part of:

<base rw app>node_modules/@redwoodjs/web/node_modules/@apollo/client

**Comment by Tobbe** [comment]
Thanks. Is that's the case both when it's working and when it's not working?

**Comment by Tobbe** [comment]
Running `yarn why @apollo/client` in both a project where it's working and one where it's not working would be very helpful 🙂

**Comment by Tobbe** [comment]
For me, in an app where it works, this is what I get
```
$ yarn why @apollo/client
yarn why v1.22.4
[1/4] Why do we have the module "@apollo/client"...?
[2/4] Initialising dependency graph...
warning Resolution field "// Temporary fix for" does not end with a valid package name and will be ignored
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@apollo/client@3.3.13"
info Reasons this module exists
   - "_project_#web#@redwoodjs#web" depends on it
   - Hoisted from "_project_#web#@redwoodjs#web#@apollo#client"
info Disk size without dependencies: "5.24MB"
info Disk size with unique dependencies: "6.43MB"
info Disk size with transitive dependencies: "6.59MB"
info Number of shared dependencies: 17
Done in 1.80s.
```

**Comment by KrisCoulson** [comment]
@Tobbe  pretty much the same 
```
yarn why @apollo/client
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "@apollo/client"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@apollo/client@3.3.13"
info Reasons this module exists
   - "_project_#web" depends on it
   - Hoisted from "_project_#web#@apollo#client"
info Disk size without dependencies: "5.71MB"
info Disk size with unique dependencies: "10.57MB"
info Disk size with transitive dependencies: "10.82MB"
info Number of shared dependencies: 18
=> Found "@redwoodjs/web#@apollo/client@3.3.12"
info This module exists because "_project_#web#@redwoodjs#web" depends on it.
info Disk size without dependencies: "5.16MB"
info Disk size with unique dependencies: "10.02MB"
info Disk size with transitive dependencies: "10.27MB"
info Number of shared dependencies: 18
✨  Done in 1.25s.
```

**Comment by Tobbe** [comment]
That's super weird. Only diff is the patch version (12 vs 13).

Well, maybe it isn't so bad to tell people that if they want to use features from apollo directly, they need to be explicit about it and run `yarn workspace web add @apollo/client`?

Unless, of course, someone else has a better solution

**Comment by thedavidprice** [comment]
has anyone tried the following in a "broken" project?
1. delete _all_ node_modules from ./, web/, and api/
2. delete yarn.lock
3. `yarn`

Wondering if that clears up the import error?

**Comment by KrisCoulson** [comment]
@thedavidprice yes i have tried that removed api,web,and src using 'rm -rf web/node_modules' and the like for the other locations and the ran 'yarn --force' similar to one of the upgrade paths from a few releases ago

**Comment by thedavidprice** [comment]
@KrisCoulson and deleted `yarn.lock`?

This is really, really strange.

**Comment by KrisCoulson** [comment]
Hmm I might not have explicitly deleted the yarn lock file will give that a look try as soon as I get back to my computer

**Comment by KrisCoulson** [comment]
@thedavidprice I think that might have fixed it! I removed all `node_modules` and `yarn.lock` and the ran `yarn --force` and it seems to be working correctly  now.

And I think when I hit this error below was because I had `@apollo/client` manually added and there was an invariant mismatched I think from what redwood was using internally and what I was using in my web directory so this has now been fixed.

![image](https://user-images.githubusercontent.com/6943688/113352850-b10b1800-92f1-11eb-895a-47a285bd566e.png)

@vchoy Can you let me know if removing your `yarn.lock` and `node_modules` folders resolves the issue for you? Then I can close this issue.

**Comment by thedavidprice** [comment]
Well, glad it's fixed! But wowza is yarn.lock a mystery to me sometimes.

Wondering if we need to add this as a Forums post or something for others to find. 🤔
