### ISSUE TITLE
Route parameter type provides wrong type for named routes

### ISSUE THREAD

**Issue by jangxyz** [redwoodjs/redwood#2169]
Having

```jsx
<Route path="/product/{id:Int}" page={ProductPage} name="product" />
```

would make `routes.product({ id })` method available, but only `string` values are available.
This raises _false_ error on `.ts` files.

```ts
routes.product({ id: 123 }) // Type 'number' is not assignable to type 'string'. ts(2322)
```

![image](https://user-images.githubusercontent.com/52015/113260335-1a4a5580-9309-11eb-8860-0c188e3eb678.png)

Here is the generated `.redwood/types/routes.d.ts` file:

```ts
import '@redwoodjs/router'

type ParseRouteParameters<Route> =
  Route extends `${string}/{${infer Param}:${string}}/${infer Rest}`
    ? { [Entry in Param | keyof ParseRouteParameters<`/${Rest}`>]: string }
    : Route extends `${string}/{${infer Param}:${string}}`
      ? { [Entry in Param]: string } // <-- HERE?
      : Route extends `${string}/{${infer Param}}`
        ? { [Entry in Param]: string }
        : Record<string, string>

declare module '@redwoodjs/router' {
  interface AvailableRoutes {
    product: (params?: ParseRouteParameters<"/product/{id:Int}">) => "/product/{id:Int}"
  }
}
```
It should at least support core route parameter types.

I tried adding these two lines, and it seems to fix the issue.

```ts
type ParseRouteParameters<Route> =
  Route extends `${string}/{${infer Param}:${string}}/${infer Rest}`
    ? { [Entry in Param | keyof ParseRouteParameters<`/${Rest}`>]: string }

    // check for Int type
    : Route extends `${string}/{${infer Param}:Int}`
      ? { [Entry in Param]: number }

      : Route extends `${string}/{${infer Param}:${string}}`
        ? { [Entry in Param]: string }
        : Route extends `${string}/{${infer Param}}`
          ? { [Entry in Param]: string }
          : Record<string, string>
```

**Comment by Tobbe** [comment]
@dac09 Tagging you as I know you recently made a bunch of awesome improvements to the typings of the named routes

**Comment by dac09** [comment]
Hey @jangxyz - thanks for raising this! 

I was worried this might come up. I think the type is actually correct, because 
- The names routes function actually generates the string to navigate to, and urls params are always strings
- when you put in {id:Int} you're actually specifying how to _parse_ the url parameter in the page, not what it's type is when you pass it in

Let me know if my logic here makes sense, or if you disagree - totally open to a different interpretation.

**Comment by jangxyz** [comment]
@dac09 I can see that `{id:Int}` originally meant for correctly parsing the url parameters. Its purpose would be to block requests with wrong type of parameters (such as `/product/fancy-macbook`).
But why stop there? It seems only too strange to specify type on one side, and abandon the type on the other.

My original idea was to align the type specifications all the way: from route parameters to component props.

We want `{id:Int}` because, well, the id field should be an integer.

```js
<Route path="/product/{id:Int}" page={ProductPage} name="product" />
```

So it naturally follows to declare type as `number` in the component as well:

```ts
const ProductPage: React.FC<{ id: number }> = ({ id }) => { ... }
```

However we can't use this id prop -- or any other product ids passed along -- as an argument to `routes.product()`. There is no error on runtime, but type declaration says it's wrong.

```typescript
routes.product({ id }) // ts says: error! You are giving us a number, but we think it should be a string
```
(But this _is_ a number! I even declared in the Routes!)

To prevent from typescript throwing errors I am currently wrapping every usage with String: `routes.product({ id: String(id) })` (which feels very redundant)

To me this feels awkward, and requires me to think that route is something special. That product id's are numbers, inside components, in url requests, and also probably in api's, but NOT when you pass it as an argument to build the route path. If route parameter types can work in both directions -- handling url requests(inward) and building url paths(outward) -- it would be a much simpler realization.

**Comment by Tobbe** [comment]
@jangxyz That's a great, well thought out, response! Either way this goes, I still just wanted to let you know that 🙂

**Comment by dac09** [comment]
@jangxyz I think you're right, this is a very well reasoned argument. I'll get a fix in (and maybe a patch @thedavidprice ?) soon

Complex types ftw!

**Comment by dac09** [comment]
@jangxyz If you have an apetite for even more complicated types, please do take a look at the PR. 

I've added some additional functionality too
