### ISSUE TITLE
Logger - Include option to override console.log and user Logger instead?

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#2170]
Question for the Redwood community.

When upgrading some existing RW apps, I have had existing `console.log` statements.

There is a way to override `console` and use the Redwood longer instead so that `console.log` maps to `logger.info` and then also map the other console levels (warn, debug, etc).

See: 

https://github.com/redwoodjs/redwood/blob/f1149a9fcc2483b6f1a5bdaa4531026eeab5385f/packages/api/src/logger/index.ts#L214

```js
const logger = pino(options, stream as DestinationStream)
console.log = logger.info.bind(logger) // if option to override ... could to all info, warn, debug, error etc
return logger
```

The benefit of this is that then anything that uses console will prettyPrint in dev, etc. and perhaps? other packages that use console would output to the logger.

```terminal
api | Change detected, building...
api | INFO [2021-04-01 01:30:18.036 +0000]: Done. Took 2061ms.
```

vs 
```terminal
api | Done. Took 2676ms.
```

Do we think this should be done by default? Or add an option to the logger options?

**Comment by jacebenson** [comment]
I'm in favor of not overwriting the console.log functionality.  I like knowing I can log to the console without an issue with the logging library (not that there is any).

**Comment by dthyresson** [comment]
Upon reflection, I don't think this idea is a good one :) Closing.
