### ISSUE TITLE
GraphQL Errors - Do they reveal too much about the underlying error in Production?

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#2171]
Currently, the default GraphQL handler formats errors in dev but returns the error:

https://github.com/redwoodjs/redwood/blob/f1149a9fcc2483b6f1a5bdaa4531026eeab5385f/packages/api/src/functions/graphql.ts#L109

```js
formatError: (error) => {
      if (isDevEnv) {
        // I want the dev-server to pick this up!?
        // TODO: Move the error handling into a separate package
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        import('@redwoodjs/dev-server/dist/error')
          .then(({ handleError }) => {
            return handleError(error.originalError as Error)
          })
          .then(console.log)
          .catch(() => {})
      }
      return error
    },
```

This can reveal the message like:

```js
{
  "errors": [
    {
      "message": "Cannot query field \"missing\" on type \"Model\".",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED"
      }
    }
  ]
}
```

when here `missing` isn't available in the SDL.

Do these error reveal too much in production?

In the app's `graphql` one can use:

```js
import { logger } from 'src/lib/logger'

// ...

export const handler = createGraphQLHandler({
// ...
  formatError: (error) => {
    logger.error({ graphQL: error }, error.message)
    return new Error('A much better but less revealing message') // possible use https://www.apollographql.com/docs/apollo-server/data/errors/#error-codes
  },
```

Maybe one could determine the same type of the original error (see: https://www.apollographql.com/docs/apollo-server/data/errors/#error-codes) but then override the message in a new error of same type?

Thoughts?

**Comment by dthyresson** [comment]
For example:

```js
  formatError: (error) => {
    logger.error({ graphQL: error }, error.message)
    return new ValidationError('GraphQL Validation failed.')
  },
```

results in:

```js
{
  "errors": [
    {
      "message": "GraphQL Validation failed.",
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED"
      }
    }
  ]
}
```

**Comment by dthyresson** [comment]
Have discovered that might want to use the originalError:

```js

    const originalError = error.originalError

    logger.error(
      { graphQL: error, originalError: originalError },
      error.message
    )

    if (originalError instanceof ValidationError) {
      return new ValidationError('Validation failed.')
    } else if (originalError instanceof ForbiddenError) {
      return new ForbiddenError(originalError.message)
    } else if (originalError instanceof AuthenticationError) {
      return new AuthenticationError(originalError.message)
    } else {
      return new Error('An error occurred.')
    }
  },
```

Note: this was for testing, probably can just return the origin

**Comment by thedavidprice** [comment]
@dthyresson I'm not clear on a) which examples above are in dev vs. production and b) which are console vs. logger. (Or maybe that's _exactly_ the question you're trying to get to 😆 )

Overall, 100% agreed on nothing related to schema, SDL, etc should be visible for production console. And, if I understand correctly, I really like the idea about being able to "link" a production client-side error with a specific Logger, um, log.

**Comment by dthyresson** [comment]
The Masked Errors plugin https://www.envelop.dev/plugins/use-masked-errors for envelop as part of https://github.com/redwoodjs/redwood/pull/2827 will address this issue.
