### ISSUE TITLE
Followed tutorial on windows, failed to compile

### ISSUE THREAD

**Issue by r3wt** [redwoodjs/redwood#219]
![image](https://user-images.githubusercontent.com/4483325/76434715-08a3b200-6384-11ea-9fa9-f467336c0b09.png)

**Comment by r3wt** [comment]
possible hint, something doesn't seem **right** here:

![image](https://user-images.githubusercontent.com/4483325/76436454-3db10400-6386-11ea-8191-a7fa1e587f22.png)

notice the path given on the home route... seems to be the directory of the git executable for some reason. weird, my project isn't even on the same drive.

**Comment by jdambron** [comment]
I can confirm the issue on Windows. It is not related to the route path though as it is already happening in the initial generation (before even adding the route).

**Comment by cannikin** [comment]
@peterp We're using `path` as a variable name which clobbers the actual `path` library in some cases...could be this is causing issues on Windows? https://github.com/redwoodjs/redwood/blob/master/packages/cli/src/commands/generate/commands/page.js#L57

**Comment by peterp** [comment]
This is now released in `v0.2.2`, thanks for letting us know about this!

**Comment by r3wt** [comment]
@peterp awesome job, thanks for the quick response. i'll be sure to check it out.
