### ISSUE TITLE
"Changes Detected" After Mutating SQLite

### ISSUE THREAD

**Issue by m-leon** [redwoodjs/redwood#220]
When using the dev-server with a SQLite database, chokidar triggers a reload after a mutation. This slows down the response from any mutation calls to a crawl and gives a bad first impression in my opinion to some devs who are playing around with the example repositories.

Would you accept a pull request that ignores files with the name "dev.sqlite" or that end with ".sqlite"?

**Comment by peterp** [comment]
🤦‍♂

> Would you accept a pull request that ignores files with the name "dev.sqlite" or that end with ".sqlite"?

Yup, we could probably ignore `*.db` as well.
