### ISSUE TITLE
RFC: `<PrivateSet>`

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#2204]
If you have a bunch of private routes, and you want them all to share a Layout, you have to do this

```
<Private unauthenticated="home">
  <Set wrap={AdminLayout}>
    <Route path="/admin/posts/new" page={NewPostPage} name="newPost" />
    <Route path="/admin/posts/{id:Int}/edit" page={EditPostPage} name="editPost" />
    <Route path="/admin/posts/{id:Int}" page={PostPage} name="post" />
    <Route path="/admin/posts" page={PostsPage} name="posts" />
  </Set>
</Private>
```

This RFC proposes a new component, `<PrivateSet>`, to limit nesting (and typing) in the routes file. It would take the union of props from Private and Set, and internally just render a Private and a Set, with the correct props passed to each.

The above example would look like this

```
<PrivateSet wrap={AdminLayout} unauthenticated="home">
  <Route path="/admin/posts/new" page={NewPostPage} name="newPost" />
  <Route path="/admin/posts/{id:Int}/edit" page={EditPostPage} name="editPost" />
  <Route path="/admin/posts/{id:Int}" page={PostPage} name="post" />
  <Route path="/admin/posts" page={PostsPage} name="posts" />
</PrivateSet>
```

**Comment by peterp** [comment]
Nice, I like it.

**Comment by thedavidprice** [comment]
The proposal definitely makes sense!

Instead of ending up with both `<Private />` _and_ `<PrivateSet />`, could just make this possible: 
`<Private wrap={AdminLayout} ... />`
?

**Comment by Tobbe** [comment]
> <Private wrap={AdminLayout} ... />

Funny that you should mention that. @cannikin wanted that too.

Implementation would be **much** easier just doing a `<PrivateSet>`. But that's a pretty poor excuse if `<Private wrap...` is what we want.

**Comment by cannikin** [comment]
@mojombo mentioned the opposite: what if we only had `<Set>` and `private` was just an attribute you could set on it? So everything is either a Set or a Route and some Sets can be private...

**Comment by Tobbe** [comment]
> what if we only had `<Set>` and `private` was just an attribute you could set on it?

If we did, it would look like this https://github.com/redwoodjs/redwood/pull/2209 :D

**Comment by ehowey** [comment]
I like the `Set` with a `private` attribute idea! Funny that this RFC is here because I was just wondering this with some things I was trying out with RW.

Keep up the great work!

**Comment by jtoar** [comment]
Closing this out because I think it was implemented in https://github.com/redwoodjs/redwood/pull/2364 🚀
