### ISSUE TITLE
The example Quick Start does not use Prisma correctly any more

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood#2206]
Running the command `yarn rw prisma migrate dev` results with:

```javascript

PS C:\work\redwood\my-redwood-app> yarn rw prisma generate dev
yarn run v1.22.5
$ C:\work\redwood\my-redwood-app\node_modules\.bin\rw prisma generate dev

Running Prisma CLI:
yarn prisma generate dev --schema "C:\work\redwood\my-redwood-app\api\db\schema.prisma"

Error: Could not find a schema.prisma file that is required for this command.
You can either provide it with --schema, set it as `prisma.schema` in your package.json or put it into the default location ./prisma/schema.prisma https://pris.ly/d/prisma-schema-location
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\work\redwood\my-redwood-app>
```

**Note the error stating that the schema.prisma needs to be at the location it already is.**

P.S. Please do not tell me "we appreciate PRs" - in this case I do not know for sure what is wrong and how to fix it. My guess is that the Prisma API changed, so it is invoked incorrectly in this example. This is the reason I am reporting this issue here.

---

To simplify the verification  of this issue, I am providing the app in **[this repository](https://github.com/congral/my-redwood-app)**

**Comment by adriatic** [comment]
### Added later FALSE ALARM 

I used the incorrect command to generate the migration - instead of 
```
yarn rw prisma migrate dev
```

I typed in
```
yarn rw prisma generate dev
```

(instead of the word `migrate` i typed `generate`)

**Leaving this issue as the RWJS Cli should protect itself from people making such errors**

**Comment by thedavidprice** [comment]
Hi @adriatic Are you referring to the example Quick Start here: https://redwoodjs.com/docs/quick-start ? 

> Error: Could not find a schema.prisma file that is required for this command.

^^ In your comment above, you reference running this prisma command:
- `yarn rw prisma migrate dev`

But in the first line of the console log output you pasted, you used _this_ command:
- `yarn rw prisma generate dev`

Please confirm if this does, indeed, resolve the error. Yes? If so, we can next discuss what can possibly be done about improved error handling, which would be a Prisma CLI Issue for this case.

> P.S. Please do not tell me "we appreciate PRs" - in this case I do not know for sure what is wrong and how to fix it.

^^ ha! appreciate you making this clear and understood. I wouldn't know what to have you PR either!

## Replicate the error
Just to be clear, is this how I would replicate the error?
1. `yarn create redwood-app ./my-redwood-app`
2. cd ./my-redwood-app
3. `yarn rw prisma generate dev`

**Comment by adriatic** [comment]
Hello, @thedavidprice - yes, you correctly understood everything I wrote. Mistakenly I used the verb `generate` instead of the correct one `migrate` (I have no idea what made me do that mistake). Your steps needed to replicate my mistake are correctly stated above.

**Note just for @thedavidprice: My plan was to use this most simple example (https://redwoodjs.com/docs/quick-start) to illustrate my point that the process of persisting a complete RW app is not reversible. More in my next issue I am working on now.

**Comment by thedavidprice** [comment]
@adriatic Got it. Understood and thanks for confirming.

Should we close out this Issue?

**Comment by adriatic** [comment]
I guess we can - but I will keep the flag that [CLI Commands](https://redwoodjs.com/docs/cli-commands) need to be more "fool proof"

**Comment by thedavidprice** [comment]
> but I will keep the flag that CLI Commands need to be more "fool proof"

Indeed! For all of us 😉 

The challenge specifically with this one is the underlying Prisma CLI, which adds to the complexity. Yes, please add to the list!
