### ISSUE TITLE
Seperate Type generation from transpilation

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2219]
Right now we transpile (via babel) and generate typescript types in the same babel plugins. This is undesirable because we want to keep transpilation as fast as possible, and we may want to switch from babel to something else in the future, which would mean that we need to rewrite/ move a bunch of code.

I would like to propose that we create a separate process that watches specific files for changes and generates the required types for them.

We could have two phases:

1. Generate all types: CurrentUser/ Routes/ GlobalContext/ SDL Schema
2. Watch and generate types when "Routes" change: Params/ PageImports/ Routes

This could be a separate command, but would also be invoked when `yarn rw dev` is called.

**Comment by dac09** [comment]
I like this idea a lot, because it opens up avenues for generating types for queries too using graphql-code-generator

**Comment by jtoar** [comment]
@peterp I'm going to bring this up for discussion, but this doesn't seem like a `v1-priority` right? We could release a v1 rc without it?

**Comment by dac09** [comment]
Closing this as implemented in v0.33 of release. @peterp please open if not :)
