### ISSUE TITLE
[RFC] `yarn rw serve [web,api]` for serving build redwood apps

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#2233]
https://github.com/redwoodjs/redwood/pull/2217 adds a `yarn rw serve api` command, and upon discussion we've realised that we should also have the ability to serve the web side.

My proposal is to provide the following commands:

### 1. `yarn rw serve` 
When run with no "side" param, the command will run a server that serves both the api and web sides. 
- The api paths will be detected from `apiProxyPath` in the project's `redwood.toml`
- CORS issues not present, as both api and web are running in the same server

**When would you use this?** 
- debugging your redwood app locally that you built with `yarn rw build`
- potentially for deploying a single server to heroku/dokku/digital ocean/docker

### 2. `yarn rw serve web`
- Will serve only the contents in `web/dist`
- Will take a param `--apiHost`, and setup a proxy that forwards request from `apiProxyPath` (in redwood.toml) -> `apiHost`

**When would you use this?**
- debugging e.g. prerender would be a good case
- if you want to run your web and api sides on separate servers/containers. Often considered good practice for scalability, because the api side will likely have much higher scaling requirements (vertical and horizontal) than the web side which only serves static data, and ideally uses cache headers
- personally i feel its better to use nginx (or equivalent) to serve static files though. But that can be a challenge to setup when you just want something running quickly!

### 3. `yarn rw serve api`
Functions as it does now. Does not serve the web side.

**When would you use this**
- if you want to run just the api side on a server e.g. running on render.com

This should massively simply things for those trying to self host as well. Feedback, comments and crtiques welcome!

**Comment by jeliasson** [comment]
💯 

My two cents here would be that I expect (would assume) arguments passed to e.g. `yarn rw serve api` would be passed to the `rw-api-server`, e.g. `yarn rw serve api --port 9999` would results in `yarn rw-api-server --port 9999` and it's defaults. I'm pretty sure that is what you meant in #2217 on the comment tho;
> The command simply proxies to `rw-api-server` in `@redwoodjs/api-server`

Another thing worth considering might be what options that could be passed to `yarn rw serve` and how that would conflict with respective sides options. If we consider the api option [`--root-path`](https://github.com/redwoodjs/redwood/commit/4ab7a9fe9b1d07b447eaeed5098657b663b924c3), it would be weird passing that in `yarn rw serve --root-path /api/`. However, in my serverful setup I would probably do `yarn rw serve api --root-path /api/` for the api, as the web would be built and spun up on a nginx-container with a CDN infront of it. For now, I suggest that `yarn rw serve` don't take any options.

**Comment by dac09** [comment]
> Another thing worth considering might be what options that could be passed to yarn rw serve and how that would conflict with respective sides options. If we consider the api option --root-path, it would be weird passing that in yarn rw serve --root-path /api/.

Agreed! I think when you run just `serve` it won't accept rootPath, the rootPath should be automatically detecting from the redwood toml. Web won't accept rootPath either (because why?).

**Comment by thedavidprice** [comment]
@dac09 if options are not applicable to all included sides, should we specify?
--api-port
--web-something
--fancy (applies to all)

?

**Comment by dac09** [comment]
In the PR, I implemented the flags specific to each command (so no confusion!)

e.g. https://github.com/redwoodjs/redwood/pull/2234/files#diff-001ab4208ca160c155aebe7ec9e87c2df652bb32a41bbd1d15cc2fad88c7208eR26

so:
- rw serve -> uses bothCliOptions
- rw serve web  -> uses webCliOptions
- rw serve api -> uses apiCliOptions
