### ISSUE TITLE
Create new project on windows

### ISSUE THREAD

**Issue by alvarosaavedra** [redwoodjs/redwood#225]
When trying to create a new project on windows if path has space in a folder name, the creation will fail.

**Comment by thedavidprice** [comment]
Hi @alvarosaavedra Thanks for letting us know and sorry for the trouble.

We are already tracking this issue here #222 so closing this one out. But are you ok to move forward near-term with a work-around?

**Comment by thedavidprice** [comment]
@alvarosaavedra Oh, one more Windows issue you should know about in advance here #219

**Comment by peterp** [comment]
This is now fixed in v0.2.2: 
![image](https://user-images.githubusercontent.com/44849/76691358-69641080-664a-11ea-9eac-d5ae04cd2de9.png)
