### ISSUE TITLE
yarn link for local dev -- command "redwood" not found

### ISSUE THREAD

**Issue by chris-hailstorm** [redwoodjs/redwood#226]
ENVIRONMENT

0.1.0

OBSERVATION

Following the instructions in `CONTRIBUTING.md`, I forked the redwood repo, git-cloned my fork to my machine, and made local changes. To test these, I followed the steps to run `yarn link` in my local `packages/cli` folder and run `yarn link yarn link "@redwoodjs/cli"` in my app root directory.  Those commands all completed with no issues.

Then we I tried to use the cli to run `yarn redwood generate scaffold`, I got the error message "command redwood not found".  I tried repeating the `yarn link` cycle with `core`, same error.

REQUEST

`CONTRIBUTING.md` could use a detailed explanation of how to use a local redwood Git repo in lieu of the published version.  It seems like some steps relating to `yarn link` are missing.

**Comment by cannikin** [comment]
Yeah, thanks to yarn you have to manually make bins executable again when there's a change. :(

    chmod +x node_modules/.bin/redwood && yarn rw g scaffold Foo

You'll need to do that every time you build the `cli` package. You can automatically build changes with `yarn build:watch` over in `cli` (note that this will not pick up changes to the generator templates).

**Comment by cannikin** [comment]
I added a note to the contributing guide, thanks for the heads-up!  https://github.com/redwoodjs/redwood/blob/master/CONTRIBUTING.md#yarn-buildwatch

**Comment by thedavidprice** [comment]
@chris-hailstorm The `yarn link` process has been painful at best for local dev so far. Peter and I have talked about a better implementation of our own but not taken a stab at it yet. Initial conversation notes here https://github.com/redwoodjs/redwood/issues/109

fwiw
