### ISSUE TITLE
[Auth] Firebase token not decoded in getCurrentUser

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#2260]
As title

If I log `decodedToken` from getCurrentUser, with a firebase auth provider
```
export const getCurrentUser = async (decoded, { type, token }) => {
  logger.debug({
    decoded,
    type,
    token,
  })
```

The "decoded" token simply returns the token, without actually decoding.

### Expected result
Firebase's authHandler should return a decoded user, instead of the raw token.

**Comment by dac09** [comment]
Should use this function from firebaseAdminApp

```
  const firebaseAuth = firebaseAdminApp.auth()

  const decodedToken = await firebaseAuth.verifyIdToken(token)
```

**Comment by peterp** [comment]
Bringing this up again: I think there's a ton of value in the community and providers owning these so that they're not part of the RedwoodJS codebase.

We're spending a ton of time understanding and fixing implementation details of other people's products. I do see a ton of value in them existing, but we support so many now that it's becoming tough to keep track of them.

I think it would be great if extract the mapped auth clients into separate packages and offer them as things that people can install.

**Comment by dac09** [comment]
@peterp 100% agreed. Is this something you envision before 1.0? I was putting it off till then.

**Comment by peterp** [comment]
I think it's open for discussion. I guess the downsides are that we'll quickly introduce a breaking change after v1.0, but on the upside we have other priorities and this just isn't as important.

Maybe there's a middle ground where we can architect something quick 'n dirty that allows us to move quickly, but works nicely post v1.0.

**Comment by thedavidprice** [comment]
I think this will be a challenge to complete before v1, but we should at least start an RFC Issue:
- determining which, if any, packages will retain "official Redwood support". If so, where should they live?
- determine/find maintainers for other provider packages --> as a first step could move to stand-alone repo in `redwoodjs/` organization with a "this repo is looking for a lead maintainer" or something like that.

Lastly is the outstanding capability for `setup` command to take packages a part of this critical path? I think it would be ideal for `rw setup auth redwoodjs-firebase-setup` (for example)  where `redwoojs-firebase-setup` was a package that, along with boilerplat and config, installs the package `redwoodjs-firebase`.

**Comment by jtoar** [comment]
`v1-priority` for this issue doesn't imply that it has to be solved, but it seems like we need a more definite plan.

**Comment by doesnotexist** [comment]
Fixed by https://github.com/redwoodjs/redwood/pull/3347
