### ISSUE TITLE
[CSS/Storybook]: Chakra UI components not rendering properly in Storybook

### ISSUE THREAD

**Issue by ehowey** [redwoodjs/redwood#2266]
Hello,

As mentioned in the chat the styles/components for Chakra UI (and also Theme UI) are not being properly rendered in Storybook. What I have done to try and fix this is a custom `storybook.preview.js` which you can see in the minimal repro.

It sounds like others have tried to fix this as well without luck. I can do some more investigating in the coming week.  I made some minimal efforts to fix this myself but stopped after running into it with both Theme-UI and Chakra-UI.  One similarity of these two css-in-js frameworks is that they both use Emotion as their core logic provider.  So maybe something that actually roots back in Emotion and Storybook??

Here is a minimal repro: https://github.com/ehowey/chakra-storybook-rw

**Comment by keithtelliott** [comment]
Thanks for posting this issue Eric.  

I observe the same issue:  Chakra components do not style correctly in Storybook.  However, I observe that they are fine when rendered via the app on my localhost (after starting the dev server with 'yarn rw dev').   For example, buttons appear, but the style of the buttons is not correct.  

I browsed your minimal repo and can confirm that I setup my Chakra UI and Storybook settings in the same fashion (wrap the <Routes /> component in App.js with <ChakraProvider> and add a decorator to web/config/storybook.preview.js).  

I don't have a solution, but just wanted to support this issue with my observations.  For now, I have been using Storybook to confirm basic Chakra component functionality (but not the styles).  

Thanks,
  Keith

**Comment by ehowey** [comment]
This was posted in the Discord chat.  Just cross posting it here because I think it is relevant. Looks like this is maybe a known issue in Chakra and a fix/update is in the works.

https://github.com/chakra-ui/chakra-ui/pull/3586

**Comment by natansevero** [comment]
For anyone that is searching for a solution, you can checkout this post: https://dev.to/carlosrafael22/what-i-ve-learned-with-chakra-ui-so-far-4f5e

In the `3. Integrating with Storybook is not so smooth currently` topic, you can see a work around to handle with this issue.

**Comment by rafaelsorto** [comment]
Thank you for sharking @natansevero I had no idea why Chakra UI was not working correctly under Storybook. The solution described there works!

**Comment by tundera** [comment]
@thedavidprice Happy to help out with this one too

**Comment by thedavidprice** [comment]
## Update
The amazing core team from Chakra started a PR over here #3715

It would be fantastic to for anyone to take a look, comment, offer suggestions about an integration feature wishlist, etc. And of course most of all it's helpful to test out the code!
