### ISSUE TITLE
currentUser in `@redwoodjs/auth` does not have types

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2267]
I'm getting this error from the generated TypeScript types:

![image](https://user-images.githubusercontent.com/44849/114519358-a11ffc00-9c40-11eb-8ed0-69cebd566a90.png)

On the api side `context.currentUser` works well, but on the web side it's just an empty "roles" object.

**Comment by dac09** [comment]
Hey @peterp it looks like interfaces can't extend union types. Could you please show me how you're defining the return type for your `getCurrentUser` function?

**Comment by peterp** [comment]
@dac09 I'm not actually defining a return type: I'm just returning my User model from Prisma which does have to union types on it. If I define the type by hand would it solve this?

**Comment by dac09** [comment]
> If I define the type by hand would it solve this?
Yes I believe it would. This is because, for some reason the prisma types don't carry across to the web side.

Will discuss with the prisma team if there's a solution for this!

**Comment by dac09** [comment]
Ok, update on the issue. It's definitely a case of union types that can't be added to the definition of CurrentUser. As you can see from your screenshot, prisma's generated types defines your return type as the union type
```
User & {
memberships: Member[]
}
```

Thanks for raising this and the screenshot there peter, weirdly my vscode doesn't complain about this.

Could you please confirm that manually defining the return type of getCurrentUser works for you? I'll add a summary, and make it searchable for others in the future.

**Comment by dac09** [comment]
My bad Union types refer to  `typeA |  typeB` not `typeA & typeB`. The second work just fine. Would need to dig further why CurrentUser doesn't seem to come through for you.

Working example here: https://github.com/dac09/prisma-ts-repro . Might be worth opening this project on your machine and seeing if you get the same error!

**Comment by dac09** [comment]
@peterp could we close this issue if its working ok for you?

**Comment by peterp** [comment]
Yup!
