### ISSUE TITLE
Compute types for `aggregate`, `groupBy`

### ISSUE THREAD

**Issue by millsp** [redwoodjs/redwood#2268]
We need to improve output types for `aggregate`, `groupBy`

![image](https://user-images.githubusercontent.com/18401805/114523990-1d1c4300-9c45-11eb-8d08-140172f1d8a4.png)

Solution to be taken from:
https://github.com/millsp/ts-toolbelt/blob/master/sources/Any/Compute.ts

**Comment by thedavidprice** [comment]
looping in @dac09 @peterp @Tobbe

**Comment by dac09** [comment]
Thanks for raising this @millsp - might this issue be better placed with the prisma team at https://github.com/prisma/prisma since the type comes from the prisma client?

**Comment by dac09** [comment]
Woops. I just saw your org now, @millsp!

I tend to use db, and get better types that way, rather than `ctx.prisma`

So,
```
import db from 'src/lib/db'
```

and then 
```
const aggregate = await db.order (....)
```

Could you let me know if this works better for you? I guess i'll have to dig into the context types.
