### ISSUE TITLE
Following tutorial, yarn create redwood-app on macOS errors (when using N rather than NVM)

### ISSUE THREAD

**Issue by zischwartz** [redwoodjs/redwood#227]
I'm running macOS 10.15.3 (19D76), following the [tutorial](https://redwoodjs.com/tutorial/installation-starting-development), when I run 

```
yarn create redwood-app ./redwoodblog
```

It fails because of node engine incompatibilities (full output below).  I tried yarn's `--ignore-engines` flag [but it doesn't seem to work for `create`](https://github.com/yarnpkg/yarn/issues/7096).

One thing, I'm using [`n`](https://github.com/tj/n) not nvm to manage my node versions, and tried some other  node versions, but they all had issues. So maybe it's `n` related? Maybe notably I can successfully install the [example blog repo](https://github.com/redwoodjs/example-blog) by cloning it down and running `yarn`.

Running with:
```
▶ node --version
v12.16.1
▶ yarn --version
1.19.2
```

Full output:

```
▶ yarn create redwood-app ./redwoodblog
yarn create v1.19.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info @expo/traveling-fastlane-linux@1.13.1: The platform "darwin" is incompatible with this module.
info "@expo/traveling-fastlane-linux@1.13.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-darwin-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
info "@expo/ngrok-bin-darwin-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-freebsd-ia32@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-freebsd-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-freebsd-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-freebsd-x64@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-freebsd-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-arm@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-linux-arm@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-arm@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-linux-arm64@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-linux-arm64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-arm64@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-linux-ia32@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-linux-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-linux-x64@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-linux-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-sunos-x64@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-sunos-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-win32-ia32@2.2.8-beta.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-win32-x64@2.2.8-beta.1: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-win32-x64@2.2.8-beta.1" is an optional dependency and failed compatibility check. Excluding it from installation.
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "12.16.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

Thanks!

**Comment by thedavidprice** [comment]
Hi @zischwartz This one's a bit strange. Your versions are just fine and, in the case they weren't, you wouldn't see the error until further down the chain of steps when the bootstrap calls 'yarn install'. Here's a screenshot of what you should see on a successful installation:
<img width="693" alt="Screen Shot 2020-03-11 at 4 49 54 PM" src="https://user-images.githubusercontent.com/2951/76474275-576b3f00-63b8-11ea-9313-285ca6dcff69.png">

Steps 1-4 are just yarn getting the executable package from NPM. Then the executable (installer) runs starting with "Creating Redwood app".

Also, the `@expo/...` packages are not used anywhere in the Redwood app (packag.json or dependencies). 

Seems most likely something related to your specific system. I'm not at all familiar with https://github.com/tj/n Is there a reason to not use NVM in your case? And how are you managing `yarn` installation as well?

We'll get you going soon enough! It'll be worth it 😄

**Comment by elebumm** [comment]
I receive the same error as well:

```
error @google-cloud/functions-emulator@1.0.0-beta.5: The engine "node" is incompatible with this module. Expected version "~6".
error Found incompatible module
```

Of course, this is from the google-cloud functions emulator, which I assume is not anywhere in this project.

**Comment by elebumm** [comment]
A one time fix is to do: `yarn config set ignore-engines true` and then run the command from the tutorial again.  That worked for me.

I believe the issue comes up with multiple version with `yarn` and it not being managed by `nvm` etc.

**Comment by thedavidprice** [comment]
More weirdness indeed. Did a quick search on https://github.com/yarnpkg/yarn/issues and found something similar but unresolved and unhelpul. 

Would be helpful to know if you’re using anything other than these recommendations to install/manage `yarn`:
https://classic.yarnpkg.com/en/docs/install#mac-stable

Yarn is currently at v1.22.4 — possible to update to latest?

And given that your Node and Yarn versions meet the engine requirments, have you tried running without the `—ignore-engines` flag?

There are a couple manual workarounds I can suggest including cloning the create-redwood-app repo. Let me know if that would be most helpful for now.

**Comment by elebumm** [comment]
Thanks for the reply @thedavidprice. 

I truly believe the issue came down to having multiple versions of yarn. Running a `which yarn` showed that the yarn was running in `/usr/local/bin/yarn` which meant it wasn't running in my local `nvm` instance. 

I `brew uninstall yarn` and then did a `npm install -g yarn` in my nvm instance which then made a new yarn in that `nvm` instance.

I still found that when I did a `yarn create...` it gave me the same error, but this time I was able to ignore engines using the command in my previous answer. Perhaps a caching issue on mac and yarn?

Glad I got it working though. Hopefully @zischwartz this answer helps you too.

Going through the tutorial and it's working great. Loving redwood so far.

Cheers David.

**Comment by thedavidprice** [comment]
@elebumm good to hear and thanks for sharing the details.

@zischwartz any chance you’ve got things to work?

**Comment by zischwartz** [comment]
Did some more investigating, including updated [`n`](https://github.com/tj/n) to the latest version, cleaning my yarn cache, but so far the only thing that worked was the one time fix `yarn config set ignore-engines true`. But it worked,  I'm able to successfully run `yarn create redwood-app ./blog`  now! 🎉

> Seems most likely something related to your specific system. I'm not at all familiar with https://github.com/tj/n Is there a reason to not use NVM in your case?  

Totally just my personal preference for `n` over `NVM`. Looking at the usage stats in both of those repos, while `NVM` is certainly more popular, `n`  does seem to a significant amount of use. Maybe a note in the documentation [here](https://redwoodjs.com/tutorial/prerequisites) is in order?  Something like, "We recommend `NVM`, if you use `n` you may need to run `yarn config set ignore-engines true`"?

(Also sorry for all that expo related output in the log, hope I didn't confuse anybody!)

**Comment by thedavidprice** [comment]
Hi All. Thanks again for your help and troubleshooting here.

I have created a new category in our forum for "Troubleshooting & How To", which also includes a new topic that attempts to address everything you've reported here. Please do read through the following and provide feedback as needed:
https://community.redwoodjs.com/t/installation-error-multiple-versions-of-yarn-or-using-version-manager-other-than-nvm/102

I'm assuming everyone is in a good place and has now moved forward. If not, please open another Issue as needed. I'm cllosing this one for now.

Looking forward to seeing some future apps in our "Show & Tell" on the forum! 🚀

**Comment by fnky** [comment]
Just to chime in; the cause of the errors is because there are global modules installed which are incompatible with your current node version. Running `yarn create` is equivalent to `yarn global add`, which means that it validates the globally installed packages.

For example; use an old version of node and install a module that targets older node versions and then switch to a newer version and do a global install. This will fail due to incompatible engines, specified by the module.

The issue itself is that `yarn create` accept arguments like `--ignore-engines` to have yarn ignore engines as part of the validation.
