### ISSUE TITLE
Redwood Language Server crashes in VSCode

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood#2271]
I am working on several "VSCode settings"  issues in the Jest Testing context which will result with the PR for updating the file `redwood/packages/create-redwood-app/template/.vscode/settings.json`. At this point, I do not know what the Redwood Language Server is, so this issue should stay open until I find the reason for this crash

Our goal so ensure that any Redwood app behaves identically whether it is running from the terminal console or from VSCode.

---

![image](https://user-images.githubusercontent.com/2712405/114580171-9ec39f00-9c4c-11eb-9775-314e6b6be21f.png)

Context:

```
$ c:\work\redwood\redwood-tutorial\node_modules\.bin\rw info

  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 14.16.0 - ~\AppData\Local\Temp\yarn--1618327861245-0.1030020922303434\node.CMD
    Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1618327861245-0.1030020922303434\yarn.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.906.0), Chromium (89.0.774.75)
  npmPackages:
    @redwoodjs/core: ^0.28.3 => 0.28.3

Done in 3.61s.
```

**Comment by thedavidprice** [comment]
**Status of Language Server and VS Code Extension:**
There's a major rewrite happening, which has been in progress for a while. We've agreed to reach a stable v1 release candidate before making the final push — each time there's a breaking change to the Redwood API, it involves re-writing aspects of Structure and the Extension, which was too much to keep up with.

**Comment by adriatic** [comment]
Given Aldo's daily workload (some small bird told me about that) I am definitively going to get proficient in writing VSCode extensions, as there are so many aspects of RW that I could make both Aldo and his clone fully occupied.

**Comment by orta** [comment]
I've got a stack trace for the crash, looks like a missing dependency in the shipped bundle

![Screen Shot 2021-06-09 at 4 41 15 PM](https://user-images.githubusercontent.com/49038/121386022-8cf73300-c941-11eb-9258-19294f43e8f0.png)

**Comment by thedavidprice** [comment]
Thank you for passing this along @orta! We are definitely still following this Issue. Behind the scenes, there is early progress on a 100% overhaul of the extension to be released in coordination with Redwood v1. Unfortunately, this means the current extension is buggy to the point of unusable. 

More to come. Just not yet, unfortunately.
