### ISSUE TITLE
Accessibility: Lint warning with roles in Private route

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#2303]
![image](https://user-images.githubusercontent.com/1051633/115031114-cfe2e000-9e95-11eb-98cd-4c471dc3784f.png)

@jtoar I am seeing this warning lint message in v30 when I declare roles on a Private route about `ARIA roles`.

Is this something to be concerned with or need to addess?

**Comment by peterp** [comment]
Uh oh, yeah, we should definitely attempt to fix this - maybe we can disable this rule in lint configuration for the Routes.* file?
