### ISSUE TITLE
Error creating project using CRWA script from main branch

### ISSUE THREAD

**Issue by renansoares** [redwoodjs/redwood#2316]
I just rebased my local redwood development branch, not sure if there is something wrong with my local envinroment.

The command ``yarn babel-node packages/create-redwood-app/src/create-redwood-app.js test-project`` gives me this error:

```
  ✔ Creating Redwood app
    ✔ Creating directory '/Users/renansdeandrade/redwood/test-project'
  ❯ Installing packages
    ✔ Checking node and yarn compatibility
    ✖ Running 'yarn install'... (This could take a while)
      → info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    Convert TypeScript files to JavaScript

Error: Command failed with exit code 1: yarn install
error Couldn't find package "@babel/preset-runtime-corejs3@^7.10.4" required by "@redwoodjs/core@^0.30.0" on the "npm" registry.
```

Can someone also try to reproduce?

**Comment by renansoares** [comment]
I see it's actually here: https://github.com/redwoodjs/redwood/blob/0b93201eee511fcd237e32ef0be0b76241d3ffa4/packages/create-redwood-app/template/yarn.lock#L1872

**Comment by thedavidprice** [comment]
@renansoares Just tried to reproduce and not seeing the error. I did update the create-rw-app/template/yarn.lock after releasing v0.30.1, however.

@peterp I'm still not convinced about the benefit of including template/yarn.lock My preference is still to remove it entirely.

**Comment by renansoares** [comment]
@thedavidprice I see package is not there anymore after you updated it, thx

**Comment by dthyresson** [comment]
@renansoares and @thedavidprice Sounds like this issues is resolved. Ok to close?
