### ISSUE TITLE
[RFC] CLI scripts and command line args with redwood context

### ISSUE THREAD

**Issue by viperfx** [redwoodjs/redwood#2320]
I have an increasing need for CLI scripts that need the redwood context. I have spoken with others that are developing applications who would also find this useful. 

Here are my use cases:
- create special database seed scripts for different scenarios 
- sync stripe products and prices (especially useful after seed command wipes the DB)
- one off CLI commands used for local development only.

**Comment by viperfx** [comment]
Wanted to add a specific use case I am blocked on right now

I am looking through the node worker and client - https://github.com/jbielick/faktory_worker_node

I cannot share the code of the redwood API like services, db etc.. with the worker script. Similar issue to not being able to run CLI scripts and create node scripts that share redwood API context

If i mistaken on this assumption - do let me know!

**Comment by dac09** [comment]
Another couple of usecases from me. Assuming I'm triggering the script from the command line:
- running cleanup jobs on a regular basis e.g. delete stale/expired data
- sync data between platforms e.g. email -> email marketing platform

**Comment by dac09** [comment]
Copying this over here for visibility. Suggestion for implementation -> 
In essence what needs to be done is:
1. add a new cli command `yarn rw run-script` (naming TBD)
2. command should call the script with the provided name, similar to this file here: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/dataMigrate/up.js
key parts of the file being the babelRequireHook (line 12-18) and runScript (101-108)

**Comment by dthyresson** [comment]
I think a name that uses "run" or some variant feels most familiar to me probably because of `heroku run`. See: https://devcenter.heroku.com/articles/one-off-dynos#an-example-one-off-dyno

**Comment by simoncrypta** [comment]
> I think a name that uses "run" or some variant feels most familiar to me probably because of `heroku run`. See: https://devcenter.heroku.com/articles/one-off-dynos#an-example-one-off-dyno

Agree with @dthyresson and I find confusing to remember two words concatenate like `run-script`  or `runScript`. I prefer when they keep it one word or add another command if they have some variate (` yarn rw run script` or `yarn rw run something` )

**Comment by viperfx** [comment]
Hmm yea I like run. That's nice and simple. easy to remember. What about the generate? What do we want to call this concept? `generate runScript`or `generate script`?

**Comment by dthyresson** [comment]
> What about the generate?

Can you provide an example template for what the script file would look like?

**Comment by dthyresson** [comment]
I think I lean towards `generate script`

**Comment by viperfx** [comment]
The script template so far is a very simple skeleton like so 

```
import { db } from 'src/lib/db'

export default async () => {
  // Your script here...
}
```

I am looking into support arbitrary args and kwargs for any script, so hooking in the yargs lib .... most just an idea at the moment.

**Comment by viperfx** [comment]
Got a decent amount working and have a PR up at #2436
