### ISSUE TITLE
Disabling automatic imports / src path aliasing magic

### ISSUE THREAD

**Issue by stephenhandley** [redwoodjs/redwood#2334]
I'd prefer to minimize any magic tooling for imports. Is there a way to disable the following? 
- automatic route imports
- src path aliasing

**Comment by peterp** [comment]
Hey @stephenhandley, you can remove `src` from your paths in`tsconfig.json` or `jsconfig.json` and I believe vscode will ignore the alias.

We do not import routes automatically, we import the pages (I'm assuming this is what you mean), but if you don't want to import them magically then you can just import them yourself and they won't be imported anymore.

**Comment by peterp** [comment]
Please let me know if there's anything else and feel free to open this issue again.
