### ISSUE TITLE
RFC: [CI] Publish release candidate packages from `release/*` branches

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#2342]
## Why?
Currently we have no way of publishing a release candidate (for either minor or patch releases) from a branch. 

## What?
We should have a github workflow that will publish release candidate packages i.e. `0.31.0-rc1`, `0.31.1-rc3`, automatically from `release/*` branches. 

Versioning conventions should follow the Canary release workflow (configured on the main branch), but ofcourse we need to indicate its a release candidate, rather than a canary build

**Comment by dac09** [comment]
cc @Tobbe, @peterp  would love if we could make this happen next release!

**Comment by dac09** [comment]
@renansoares - I know you said you were interested in automation - does this look like something you fancy helping out with? 

Thanks!

**Comment by renansoares** [comment]
hey @dac09, yay thanks for reminding me! o// :D 

sure, It does look like something I would like to help with. can you assign it to me?
