### ISSUE TITLE
Cannot activate the 'Redwood IDE' extension because it depends on the 'Browser Preview' extension

### ISSUE THREAD

**Issue by BstevensG4G** [redwoodjs/redwood#2344]
While working remotely in WSL on Windows 10 VS Code reveals this message box every time it loads a redwood project making the extension unusable. Various issues in other repositories may give clues to its resolution.
[VS Code Extension wont load in remote - ssh mode. #1478](https://github.com/redwoodjs/redwood/issues/1478)

If nothing else this feature request seems like an invaluable tool for extension builders to aid in debugging
[Feature: Specifying the load order of extensions (reduce startup wait-time) #46846](https://github.com/microsoft/vscode/issues/46846)

**Comment by vladiftimie** [comment]
I'm experiencing the same issue ... any workarounds so far? 😕

**Comment by thedavidprice** [comment]
Hi all. We are in between major changes and updates to the Extension. The current codebase is effectively going to be replaced, which is a great thing overall. It's still just a couple months out.

We're paying attention to these Issues and will update accordingly. Thanks for your patience!

**Comment by thedavidprice** [comment]
^^ @aldonline any way to do this with the current set up?

@am1ru1 No ETA at this time, unfortunately. Our focus is primarily on reaching the framework v1-rc
