### ISSUE TITLE
Allow users to disable VSCode redwood warnings

### ISSUE THREAD

**Issue by jvanbaarsen** [redwoodjs/redwood#2352]
I have an app where I want to check if something runs in Development mode, otherwise, something shouldn't render.

My editor keeps complaining to me "Env value NODE_ENV is not available". I noticed that this is coming from the RW VSCode plugin. After adding this to my .env file all my tests stopped working (Because they then also run in dev mode).

it would be great if we could disable certain checks, if an ENV Var is not in my local .env there is probably a reason for it.

**Comment by jtoar** [comment]
See https://github.com/redwoodjs/redwood/issues/3887#issuecomment-1118642662.
