### ISSUE TITLE
Auth: Default Magiclink to always showUI

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#2361]
See: https://github.com/redwoodjs/playground-auth/pull/60

@shahbaz17 has suggested that the default behavior of Magiclink should always be to show the UI as in:

![image](https://user-images.githubusercontent.com/1051633/116282617-fe47a180-a758-11eb-8123-ed24c11a13f4.png)

That way, only if the developer doesn't want the confirm message, then they can explicitly set `showUI: false`

This Magic claims will reduce friction/confusion as to what has happened after clicking login/sign up

```js
export const magicLink = (client: MagicLink): AuthClientMagicLink => {
  return {
    type: 'magicLink',
    client,
    login: async ({ email, showUI }) =>
      await client.auth.loginWithMagicLink({ email, showUI }),
    logout: async () => {
      await client.user.logout()
    },
    signup: async ({ email, showUI }) =>
      await client.auth.loginWithMagicLink({ email, showUI }),
    getToken: async () => await client.user.getIdToken(),
    getUserMetadata: async () =>
      (await client.user.isLoggedIn()) ? await client.user.getMetadata() : null,
  }
}
```

**Comment by peterp** [comment]
👍  Let's do it!

**Comment by shahbaz17** [comment]
Can I work on this @peterp?

This would be an easy fix.

**Comment by jtoar** [comment]
@shahbaz17 sorry for the late reply; you can absolutely work on this!

**Comment by shahbaz17** [comment]
@jtoar https://github.com/redwoodjs/redwood/pull/2629 is ready for review.
