### ISSUE TITLE
[RW 0.31] Window Focus partially  reseting view to top 

### ISSUE THREAD

**Issue by Burnsy** [redwoodjs/redwood#2365]
Video showing not fully resetting in 31.0

https://user-images.githubusercontent.com/15834048/116427323-d715d080-a83b-11eb-8298-b04bcc31e35a.mov

**Comment by thedavidprice** [comment]
Looping in @jtoar

**Comment by Burnsy** [comment]
This seems to be an initial bug with if you have a fixed banner at the top of the page then the page starts slower. so working as expected when moved things to sticky it now resets to top of the page!
