### ISSUE TITLE
Use Prisma comments when generating/scaffolding

### ISSUE THREAD

**Issue by brentjanderson** [redwoodjs/redwood#2372]
[Prisma will attach `///` comments in a prisma.schema file to generated AST.](https://www.prisma.io/docs/concepts/components/prisma-schema#comments) If redwood is using that AST to generate e.g. services & GraphQL schema, those comments could be made available in other parts of the project.

**Comment by peterp** [comment]
Nice @brentjanderson 👏,, can you expand a bit on your idea to suggest where these should show up?

**Comment by brentjanderson** [comment]
Looks like I didn’t expand much on this initially 😅  

Specifically, it could be handy to include prisma comments as GraphQL documentation on each field of SDL. Comments on Prisma models, fields, and enums would be added as comments on GraphQL types, fields, and enums.

**Comment by jtoar** [comment]
We do use `getDMMF` in the sdl generator:
https://github.com/redwoodjs/redwood/blob/f19481bc249f3655ecc5257d59388004ae24a513/packages/cli/src/lib/index.js#L6
which [the docs say](https://www.prisma.io/docs/concepts/components/prisma-schema#comments) include the triple-slash comments:
> Note: `///` comments are not present of the generated Prisma Client, but are present in the internal Data Model Meta Format (DMMF).

@brentjanderson so the idea would be we just copy them over to the sdl right?

**Comment by brentjanderson** [comment]
Yes, that’s the idea.

**Comment by dthyresson** [comment]
Docs/comments cn be added via docs option: https://github.com/redwoodjs/redwood/blob/15dd2c9b7dd0930fc04a0a2964996e91880c8d90/packages/cli/src/commands/generate/sdl/sdl.js#L275

and 
<img width="798" alt="image" src="https://github.com/redwoodjs/redwood/assets/1051633/6cb11ad5-24b0-4464-9451-de32cc476e48">
