### ISSUE TITLE
Exit `yarn rw db up` early on error

### ISSUE THREAD

**Issue by janpio** [redwoodjs/redwood#239]
Issues like https://github.com/redwoodjs/redwood/issues/215 show that currently the second `prisma2` command is executed even when the first one fails:

```
Migrate database up... [completed]
Generating the Prisma client... [started]
Error: Error: Command was killed with SIGSEGV (Segmentation fault): /Users/ncphillips/Code/ncphillips/example-blog/node_modules/prisma2/query-engine-darwin --enable_raw_queries cli --dmmf
Generating the Prisma client... [failed]
→ Command failed with exit code 1: prisma2 generate
Command failed with exit code 1: prisma2 generate
✨  Done in 1.66s.
```

It would probably be a good idea do exit if the first command returns an error (although that should not happen in the first place of course).

**Comment by peterp** [comment]
Closed by cbfaf23acd9c915e14d14fb24ca02d05572d1307
