### ISSUE TITLE
Performances of tests on web side 

### ISSUE THREAD

**Issue by noire-munich** [redwoodjs/redwood#2397]
I began writing ui tests this week and noticed the execution time was anormally long:

![Screenshot from 2021-04-28 15-30-10](https://user-images.githubusercontent.com/10271407/116521951-e5fc9180-a8d4-11eb-8737-78d40f70ea56.png)

for a simple test on a checkbox input, we got an average of 80s of execution.

I thought the problem was in the code so I stripped the test from everything and ran it again with this, with the same results:

```
return expect(true).toBeTruthy()
```

that should happen in the blink of an eye.

I then proceeded to run a scaffolded test on an empty page, again with the same results, roughly 80 seconds of execution.

This does not happen on the api side where things are faster.

Also, I cannot tell if this is because of the latest release or not, since we were not working our ui tests before it.

`yarn rw info`:
```
$ /Workspace/Code/SportOffice/node_modules/.bin/rw info

  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.0.0 - /tmp/yarn--1619703829981-0.901556945091893/node
    Yarn: 1.22.5 - /tmp/yarn--1619703829981-0.901556945091893/yarn
  Browsers:
    Chrome: 90.0.4430.85
    Firefox: 88.0
  npmPackages:
    @redwoodjs/core: ^0.31.0 => 0.31.0 

Done in 7.99s.
```

**Comment by noire-munich** [comment]
Investing further I noticed the api felt also a bit off, here's what a single `yarn rw dev api` runs, according to `htop`

![Screenshot from 2021-04-29 15-42-05](https://user-images.githubusercontent.com/10271407/116560286-84065100-a901-11eb-95a3-0b3c517d718c.png)

Not sure it's what's expected.

I used to be able to kill off either side with a simple `cmd + c` but it doesn't work anymore.

**Comment by peterp** [comment]
@noire-munich can try running `yarn rw test web`?

With regards to the api - I'm almost at the point where I'll deprecate the `dev-server`, could you try running: `yarn rw dev --esbuild` instead?

**Comment by noire-munich** [comment]
Sure!

`yarn rw dev --esbuild` crashes graphql, I'd be toasted without it:

```
yarn run v1.22.5
$ /Workspace/Code/SportOffice/node_modules/.bin/rw dev --esbuild
$ /Workspace/Code/SportOffice/node_modules/.bin/cross-env NODE_ENV=development NODE_OPTIONS=--enable-source-maps yarn rw-api-server-watch
$ /Workspace/Code/SportOffice/node_modules/.bin/cross-env ESBUILD=1
$ /Workspace/Code/SportOffice/node_modules/.bin/rw-api-server-watch
$ /Workspace/Code/SportOffice/node_modules/.bin/webpack-dev-server --config ../node_modules/@redwoodjs/core/config/webpack.development.js
api esbuild | Building API...
api esbuild | Built in 210 ms
api esbuild | Importing API... 
web esbuild | ℹ ｢wds｣: Project is running at http://localhost:8910/
web esbuild | ℹ ｢wds｣: webpack output is served from /
web esbuild | ℹ ｢wds｣: Content not from webpack is served from /Workspace/Code/SportOffice/web
web esbuild | ℹ ｢wds｣: 404s will fallback to /index.html
api esbuild | FirebaseAppError: The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.
api esbuild |     at FirebaseAppError.FirebaseError [as constructor] (/Workspace/Code/SportOffice/node_modules/firebase-admin/lib/utils/error.js:44:28)
api esbuild |     at FirebaseAppError.PrefixedFirebaseError [as constructor] (/Workspace/Code/SportOffice/node_modules/firebase-admin/lib/utils/error.js:90:28)
api esbuild |     at new FirebaseAppError (/Workspace/Code/SportOffice/node_modules/firebase-admin/lib/utils/error.js:125:28)
api esbuild |     at FirebaseNamespaceInternals.initializeApp (/Workspace/Code/SportOffice/node_modules/firebase-admin/lib/firebase-namespace.js:65:23)
api esbuild |     at FirebaseNamespace.initializeApp (/Workspace/Code/SportOffice/node_modules/firebase-admin/lib/firebase-namespace.js:355:30)
api esbuild |     at Object.<anonymous> (/Workspace/Code/SportOffice/api/dist/functions/poulpulate.js:88:46)
api esbuild |     at Module._compile (internal/modules/cjs/loader.js:1185:30)
api esbuild |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
api esbuild |     at Module.load (internal/modules/cjs/loader.js:1034:32)
api esbuild |     at Function.Module._load (internal/modules/cjs/loader.js:917:16) {
api esbuild |   errorInfo: {
api esbuild |     code: 'app/duplicate-app',
api esbuild |     message: 'The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.'
api esbuild |   },
api esbuild |   codePrefix: 'app'
api esbuild | }
web esbuild | [HPM] Error occurred while trying to proxy request /graphql from localhost:8910 to http://[::1]:8911 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
web esbuild | [HPM] Error occurred while trying to proxy request /graphql from localhost:8910 to http://[::1]:8911 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
web esbuild | [HPM] Error occurred while trying to proxy request /graphql from localhost:8910 to http://[::1]:8911 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

> @noire-munich can try running yarn rw test web?

I have, executing all tests, I've got a load of errors - I really didn't work my web tests :-\. The Checkbox test, ran within all tests, takes 32s. Executed on a pattern filter - alone - it takes 77s. In neither cases does it yield errors.

**Comment by noire-munich** [comment]
Update: I "fixed" the crash related to Firebase, it happened because I had 2 functions graphql and another one. The other one was obsolete so I removed it, however a local esbuild did not take into account the deletion of the obsolete code in `api/dist`, so I had to do it manually.
This did not happen on preprod & prod, the fix went smoothly. I'll stick to `esbuild` from now on, since it handles pretty well changing branches while the app is running it suits me.

**Comment by jtoar** [comment]
https://github.com/redwoodjs/redwood/issues/3646 would go a long way in improving the performance of web-side tests.

**Comment by jtoar** [comment]
https://github.com/redwoodjs/redwood/pull/4024 re-parallelized running web tests; those should be significantly faster now according to David's conclusions in this comment: https://github.com/redwoodjs/redwood/pull/4024#issuecomment-1017021137. We can still do a lot (_a lot_) more for performance it, just isn't our focus yet. @noire-munich although this issue is from a while ago, v0.42 should've sped up your web tests—if could confirm that'd be much appreciated!

**Comment by noire-munich** [comment]
@jtoar Took me some time to get it to work - because I had to work the i18n mocking of my tests.
I can confirm it works way faster though, 3 tests in 10s, very much appreciated!
First thing I did after bumping to v0.42.
I tried it working only the test suite mentioned in this issue.
