### ISSUE TITLE
create-redwood-app failure with axios 503

### ISSUE THREAD

**Issue by qiwang97** [redwoodjs/redwood#240]
i  start with:
```
yarn create redwood-app redwood-test
```

It failed with axios .
 
And i turn to:
```
 create-redwood-app ./test-3
```
It failed also with axios.

![image](https://user-images.githubusercontent.com/37304367/76583306-d628bf00-6513-11ea-80ad-c01cfbc94911.png)

Then i find this and i think the reason is  using proxy.
i have no choice but to use proxy (like v2ray) for some reason.
By the way, `npx create-react-app ./test` works without any error.
So anyone has any solution?

**Comment by thedavidprice** [comment]
Hi @qiwang97 appreciate you trying out Redwood! Hopefully we’ll get this sorted quickly.

Really strange indeed that your `responseURL` has localhost in front of the release URL. The create-redwood-app script simply downloads the latest release, unzips, and then installs. Whether you use `yarn` or `npm` shouldn’t make a difference. (And in this case you are fine to proceed if `npx` was successful.)

Can you check your yarn version for me with `yarn —version`? Also, how do you install/manage yarn on your system?

**Comment by qiwang97** [comment]
thanks for response.
Here is my work environment:

- macOS Catalina 10.15.3
- nvm by brew
- node v13.3.0 by `nvm use`
- npm v6.13.1
- yarn v1.22.4 by `node i -g yarn`

**Comment by peterp** [comment]
@qiwang97 Could you let me know what the error was when you ran `yarn create redwood-app`?

**Comment by thedavidprice** [comment]
@qiwang97 it seems you are having an issue similar to this one. Can you please confirm one way or the other?
- https://github.com/axios/axios/issues/2667

It is also possible you have correctly configured npm to handle the proxy, but not for yarn. The [Yarn Config Docs](https://classic.yarnpkg.com/en/docs/cli/config/) are not very helpful but are a good reference. I looked up some examples by searching for `yarn config set proxy example`. Here were a few results you could try:
- https://tharakatechmind.wordpress.com/2018/03/19/how-to-setup-node-js-and-npm-behind-proxy/
- http://www.mannoun.net/how-to-configure-npm-and-yarn-behind-proxy-server/

Could you please try to set config on your end and then let us know? If you do diagnose the problem + solution, I would like to add this to our Troubleshooting guide for others in the community with the same problem.

Thanks!

**Comment by qiwang97** [comment]
@peterp  sorry for my mistake. The reason for the failure is just like what @thedavidprice  said. 
@thedavidprice  thanks for your help.

i  checked no proxy for my npm and yarn.
```
 // echo null
npm config get proxy

// echo undefined
yarn config get proxy
```

And i failed again with setting  npm/yarn proxy and no ssl.
Struggled but no  progress.

**Comment by thedavidprice** [comment]
@qiwang97 bummer, but thank you for trying!

This is going to take a bit of time on our end to try a solution. In the meantime, can you confirm you are able to work around (via npm create) and start exploring the tutorial? There's one other option that's a bit more manual but I can provide instructions if needed.

**Comment by qiwang97** [comment]
> @qiwang97 bummer, but thank you for trying!
> 
> This is going to take a bit of time on our end to try a solution. In the meantime, can you confirm you are able to work around (via npm create) and start exploring the tutorial? There's one other option that's a bit more manual but I can provide instructions if needed.


 i think i can start by your [document](https://redwoodjs.com/docs) but i'm unfamiliar with Prisma. Could you please provide me an initial repository  by only running `yarn create redwood-app redwood-test`?

**Comment by thedavidprice** [comment]
Hi @qiwang97 Here are instructions for a manual setup process. Let me know if you have any problems or questions. Otherwise, this should get you ready to begin building your own app.

https://community.redwoodjs.com/t/how-to-manually-bootstrap-install-create-redwood-app/115

**Comment by qiwang97** [comment]
> https://community.redwoodjs.com/t/how-to-manually-bootstrap-install-create-redwood-app/115

i try and it works. Thanks a lot. 😁
