### ISSUE TITLE
Sourcemaps are not disabled in production 

### ISSUE THREAD

**Issue by Burnsy** [redwoodjs/redwood#2416]
Here is a snippet in my codebase from everfund.co.uk

![image](https://user-images.githubusercontent.com/15834048/116736001-349a5080-a9e7-11eb-8368-cea2d2c72c1c.png)

it should be disabled by default.

**Comment by jvanbaarsen** [comment]
@Burnsy I'm wondering, why *should* they be disabled? They don't add any overhead for the end-user correct? I believe they only download when the dev tools are opened.

**Comment by thedavidprice** [comment]
@dthyresson @dac09 can either of you confirm this has been resolved? My understanding is that source maps are no longer included in production, correct?

**Comment by thedavidprice** [comment]
@dthyresson re-ping

**Comment by jtoar** [comment]
I don't think this one's been solved yet as the only `sourceMap` toggle we have is for CSS:

https://github.com/redwoodjs/redwood/blob/8874cf7a27a916c10e88b337b4a74536a12ecca1/packages/core/config/webpack.common.js#L52

**Comment by thedavidprice** [comment]
queued up for Core Team discussion
