### ISSUE TITLE
Proposal) Directives helper for redwood!

### ISSUE THREAD

**Issue by guledali** [redwoodjs/redwood#242]
I think redwood should ship with helpers or directives for more declarative ui. Why?

- It’s easier for eyes to scan the code
- Less code to write which it more elegant
- Directives are more fun to use!

Another benefit I can see here is when there is an official `redwood vscode extension` in the future. We could provide snippets.

Here is an example with **jsx**

![jsx](https://user-images.githubusercontent.com/20647282/76609020-f908a280-6516-11ea-8057-702548676a6b.png)

Here is the same code with **redwood directives helper**
![directives](https://user-images.githubusercontent.com/20647282/76609072-0c1b7280-6517-11ea-95ae-3d9ff17a3be6.png)

Other helpers could be
`rw-if`
`rw-else`
`rw-elseif`
`rw-class`
`rw-show`
`rw-model` Maybe for inputs

For reference checkout https://github.com/peakchen90/babel-plugin-react-directives

@peterp  @thedavidprice @mojombo  @cannikin  What do you guys think

**Comment by thedavidprice** [comment]
@guledali thank you for this suggestion. As a next step, I’d like to continue with community discussion — so our forum is definitely the right place. I saw your post in the forum, but most of the rich details are here in the issue. How about this for next steps:
1. update the forum topic with the information in this thread
2. check back here and I’ll close out this issue and, more importantly, loop in a few others I think will be interested in this as well

Sound good?

**Comment by guledali** [comment]
@thedavidprice You can close it now! I have updated my post in the forum 👍

**Comment by thedavidprice** [comment]
Fantastic! Will do and also spreading the word to hep get the conversation started.
