### ISSUE TITLE
Services/Typscript: ResolverArgs not exported by '@redwoodjs/api/dist/types'

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#2437]
I created a new RW app using Typescript and generated sdl + services for a model `Activity`.

In the service, I get the warning that `@redwoodjs/api/dist/types` has no exported member `ResolverArgs`

![image](https://user-images.githubusercontent.com/1051633/116879932-536b3380-abef-11eb-9a29-4dbb1e0f1120.png)

But it is used 

```js
export const Activity = {
  activityType: (
    _obj,
    { root }: ResolverArgs<Prisma.ActivityWhereUniqueInput>
  ) => db.activity.findUnique({ where: { id: root.id } }).activityType(),
  member: (_obj, { root }: ResolverArgs<Prisma.ActivityWhereUniqueInput>) =>
    db.activity.findUnique({ where: { id: root.id } }).member(),
  repository: (_obj, { root }: ResolverArgs<Prisma.ActivityWhereUniqueInput>) =>
    db.activity.findUnique({ where: { id: root.id } }).repository(),
}
```

**Comment by dac09** [comment]
To me the import from `@redwoodjs/api/dist/types` doesn't look right (but I can see that its in the template).

Also I have no idea what this type should be :P @peterp ?
