### ISSUE TITLE
Version 0.31.2 Auth - Firebase Issue

### ISSUE THREAD

**Issue by cjreimer** [redwoodjs/redwood#2454]
As posted in the forum:

I seem to be experiencing a firebase authentication issue with 0.31.2. 

With 0.31.2, on the API side, the `context.currentUser` is null, even when logged in.  This works in 0.30.0

I rolled back the auth package to 0.31.0 and it works again. I re-upgraded the auth package to 0.30.2 and it fails. Note, that the firebase packages appear to be the same through all this.

I noticed the following in @redwoodjs/auth/package.json

“version”: “0.30.2-canary.42+76fb8141”

Do we have a versioning issue?

**Comment by Tobbe** [comment]
I hope this has now been resolved. Please see here https://community.redwoodjs.com/t/redwood-v0-31-0/2066/12 

If you do try again, it would be very kind of you to report back if it works or not. Thanks 🙂

**Comment by cjreimer** [comment]
Look good!  Thanks!
