### ISSUE TITLE
Request: Generator for lambda functions

### ISSUE THREAD

**Issue by zachlatta** [redwoodjs/redwood#248]
I'm in the process of creating my first Redwood app and wanted to create a custom lambda function.

It took some digging in the example repos to figure out that I needed to create a file in `api/src/functions/` and export a handler per https://redwoodjs.com/docs/the-development-server.html#the-development-server.

I imagine this format might be a common convention in the serverless world, but as someone that is being introduced to serverless programming through Redwood, it would be great if the correct format for lambda functions in Redwood was discoverable via generators.

(Redwood is awesome! 🌲)

**Comment by thedavidprice** [comment]
@peterp Were you thinking instructions for doing this should be added to our docs?

**Comment by peterp** [comment]
@thedavidprice I think they should be in the `dev-server` we're going to be renaming that to `function-server` to allow people to have a self-hosted option.

**Comment by peterp** [comment]
Closed by #517
