### ISSUE TITLE
[yarn rw serve] Kill child server process if parent is killed

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#2488]
Right now when serving with `yarn rw serve`, and the parent process is killed, the child process (the API server) continues to run and serve requests. It must be killed separately.

/cc @peterp @dac09

**Comment by peterp** [comment]
-  [ ] make `serve` do pm2.

**Comment by cannikin** [comment]
Interesting...I thought maybe we could include an `init.d` script that you could choose to install, so everything starts on startup, but pm2 is probably much more robust?

**Comment by peterp** [comment]
@cannikin Yup! It can totally do that, I think it's called cluster mode

**Comment by cannikin** [comment]
I think we fixed this longggg ago, so closing for now!
