### ISSUE TITLE
Firebase Auth does not prompt for user (when multiple accounts logged in)

### ISSUE THREAD

**Issue by ryanmdoyle** [redwoodjs/redwood#2489]
Working on an app that uses firebase (just the google provider) as auth.  I work on a computer that uses multiple Google Account (personal, work, etc).

Currently, when I `logIn()`, the user that's the browser default will authenticate, so if I have multiple Google accounts that I am signed in to (lets say work@gmail.com and personal@gmail.com), it just goes with the browser default without asking which account to sign in with. Convenient with only one account, a pain if you have multiple accounts though as the only way to change who you are logging in as is to go to you google accounts and sign out, or change the browser user.

I found [this article](https://groups.google.com/g/firebase-talk/c/gxBm0WKCuIY) where it outlines using `setCustomParameters` on the GoogleAuthProvider so that the client is always prompted for the account to login with.

Right now it looks like the only way to achieve this is by going into the actual Google auth provider in the Redwood packages and adding it, but I would need to do that every time I update RW.

Thoughts on adding it as an option?

**Comment by peterp** [comment]
@ryanmdoyle I'm assuming that adding this as a default option for other's wouldn't impede them in any way? If so, then we should just create a PR and add this.

**Comment by dthyresson** [comment]
The example code is:

```js
var provider = new firebase.auth.GoogleAuthProvider();
provider.setCustomParameters({
  prompt: 'select_account'
});
```
> Specify additional custom OAuth provider parameters that you want to send with the OAuth request. To add a custom parameter, call setCustomParameters on the initialized provider with an object containing the key as specified by the OAuth provider documentation and the corresponding value


We'd have to confirm that

```js
  const getProvider = (providerId: oAuthProvider) => {
    return new client.auth.OAuthProvider(providerId)
  }
```

can accept `setCustomParameters` when used in the `signInWithPopup(provider)` for OAuth.

There's a good case to be made to pass options into the provider not only for this case but also scopes like:

> Specify additional OAuth 2.0 scopes that you want to request from the authentication provider. To add a scope, call addScope.

```js
provider.addScope('https://www.googleapis.com/auth/contacts.readonly');
```

**Comment by ryanmdoyle** [comment]
Ok, finished off the school year (teacher by day) so I took another look.

Seem like there are only 2 different methods we would need to handle, being `setCustomparameters`, and `addScope` Possibly `credential` as well. 

While maintaining the ability to in the OAuth provider or the `{email: "", password: ''}` as the first argumentof the login/signup, we would have to pass the options as the second argument and change the documentation to explicitly pass the provider, email/password object, or `undefined`.  

If an options object is passed to logIn or SignUp, we can `addCustomParameters` directly, and loop over an array of "scopes" to handle the `addScope` functionality.

So, ultimately, we would be able to pass objects like:
```js
logIn(
  undefined,
  {
    customParameters: {
      prompt: 'select_account'
    },
    scopes: [
      'profile',
      'email'
    ]
  }
)
```

`customParameters` can accept the [Authentication URI parameters object](https://developers.google.com/identity/protocols/oauth2/openid-connect#authenticationuriparameters)
`scopes` could accept an array of scopes to be added.

So in the firebase.js we would end up with something like: (only relevant code shown)
```js
const firebase = client => {
  const getProvider = providerId => {
    return new client.auth.OAuthProvider(providerId);
  }; 

  return {
    login: (withAuth = 'google.com', options) => {

      const provider = getProvider(withAuth);
      if (options) {
        if (options.setCustomParameters){
          provider.setCustomParameters(options.setCustomParameters)
        }
        if (options.addScope) {
          options.addScope.forEach(scope => provider.addScope(scope))
        }
      }
      return client.auth().signInWithPopup(provider);
    },
}
```

I don't foresee any problems with this, it doesn't change anything with how anyone might currently have their provider or an object with the email/pass being passed as the first argument. It would just require anyone who wanted to pass options to additionally explicitly pass in a first argument for the provider.

This is the first thing I've ever looked at beyond contributing to docs so...thoughts?

**Comment by ryanmdoyle** [comment]
Spoke too soon.  I realized shortly after leaving the above comment that the RW LogIn only accepts a single argument, so the `firebase.login` should also only have 1 argument.

I left/hide my previous comment to see my first thoughts, but here is my proposed solution:

The `firebase.login` (and `signup`) should accept `options` instead of `withAuth`.

The current `isPasswordCreds()` will still check if the  redwood `LogIn()` function contains an email/password within the options and would login that way if they were provided. 

If there is no email/password, we can get the OAuth provider using 'google.com' or whatever is passed in for the key `providerId`.

Finally, we check for any `customParameters` or `scopes`, and add the custom parameters and scopes passed in to the options object.

Looking like this in the end: (only relevant code included)
```js
const isPasswordCreds = withCreds => {
  const creds = withCreds;
  return creds.email !== undefined && creds.password !== undefined;
};

const firebase = client => {
  const getProvider = providerId => {
    return new client.auth.OAuthProvider(providerId);
  }; 

  const repackagePromise = fireBasePromise => {
    return new _promise.default((resolve, reject) => {
      fireBasePromise.then(result => resolve(result)).catch(error => reject(error));
    });
  };

  return {
  // Changes all to apply here
    login: (options = { providerId: 'google.com '}) => {
     
      // Use isPasswordCreds to auth with email if needed
      if (isPasswordCreds(options)) {
        return repackagePromise(client.auth().signInWithEmailAndPassword(options.email, options.password));
      }

      // Get OAuth provider.  Run any options passed in.
      const provider = getProvider(options.providerId || 'google.com');
      if (options.customParameters) {
        provider.setCustomParameters(options.customParameters)
      }
      if (options.scopes) {
        options.scopes.forEach(scope => provider.addScope(scope))
      }
      return repackagePromise(client.auth().signInWithPopup(provider));
    },

  }
}
```

Perhaps also rewording the `isPasswordCreds` to `hasPasswordCreds` to make it more readable.

I think that should work, but thoughts appreciated.

**Comment by thedavidprice** [comment]
@ryanmdoyle this is _very_ helpful. Thank you! 

Because the core maintainers are are lazer focused on a v1-release-candidate, this change won't be on our priority roadmap. If you are available and interested in tackling a PR, we'd welcome it and could support the effort. No pressure on our end.

Make sense? Thoughts either way?

**Comment by ryanmdoyle** [comment]
I'm get to work on a PR for this and the documentation for it. 

Just wanted to reach out first in case anyone with more familiarity had any thoughts.

**Comment by ryanmdoyle** [comment]
Just a reference within this issue in case needed for my future self, I ended up adding the options capabilities by checking the inputs for the `logIn` and `signUp` methods and casting the input to a single object. 

That object is then checked for an email/password and authenticates using that if provided.

If no email/password are provided, it authenticates using the provider given, and applies any options.

Currently working on a PR to updated the docs as well.
