### ISSUE TITLE
Chinese translation needed?

### ISSUE THREAD

**Issue by hszhakka** [redwoodjs/redwood#249]
Do the docs need a Chinese version? Maybe I could help. I know Chinese.

**Comment by thedavidprice** [comment]
Wow, @hszhakka this seems like an amazing offer. @mojombo what are you thoughts about when/if this is helpful — would we host on our website or link elsewhere?

**Comment by dthyresson** [comment]
@clairefro and @cannikin Should this issue for Chinese translation be moved to the learn repo?

**Comment by clairefro** [comment]
We currently have translation set up only for the tutorials. If @hszhakka is interested in starting a Chinese translation of the tutorial, that would be totally welcome! 

If interested, feel free to open an issue in the [tutorials repo](https://github.com/redwoodjs/learn.redwoodjs.com) and I'll get it set up

**Comment by jtoar** [comment]
Going to close this one; @hszhakka if you're still interested, as @clairefro mentioned, we've got a great translation workflow now. You caught us really early before we had any infrastructure; but no pressure of course!
