### ISSUE TITLE
Cache magic.link's token

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2501]
We re-request a token from magic.link with every request. This is really inefficient because the token is valid for 15 minutes. Magic.link doesn't return an expiration time, so we should cache the token for at least ~10 minutes.

![image](https://user-images.githubusercontent.com/44849/118038215-21846a80-b36f-11eb-87ba-e928b9247624.png)

Here are the steps to fix this:

1. Grab and cache the token (in memory) over here: https://github.com/redwoodjs/redwood/blob/ef0d09350ef53de8251e0970f690444c1d1a218f/packages/auth/src/authClients/magicLink.ts#L23
This function is called for each graphql-request, so we can use it to invalidate that cached token.
2. Store a timestamp for when the token should expire (now + 10 minutes).
3. With each request check if the timestamp has expired, if it has re-request a new token and recycle.

**Comment by simoncrypta** [comment]
Ah! I was thinking that I was crazy, I'm happy that magic.link do not require to re-request a token every request. 

I could take this, but where should I store the timestamp ?

**Comment by peterp** [comment]
thanks @simoncrypta! I would just store it as a mutable variable inside the `export const magicLink` closure
