### ISSUE TITLE
deleting a page doesnt delete files

### ISSUE THREAD

**Issue by wbrijesh** [redwoodjs/redwood#2506]
after running 
`yarn rw d page pagename`

the page files are still there

**Comment by thedavidprice** [comment]
Thanks for reporting this @wbrijesh This is a duplicate of https://github.com/redwoodjs/redwood/issues/2006 I'm closing this out. But would you be interested in helping with the fix? If so, please comment in #2006 and we'll help out as best we can! Also, the community chat and forums are a great place to get help as a new contributor.

- https://community.redwoodjs.com/
- https://discord.gg/jjSYEQd
