### ISSUE TITLE
Windows: create-redwood-app generates a broken app

### ISSUE THREAD

**Issue by weaversam8** [redwoodjs/redwood#254]
Hello folks! I'm running Windows 10, Node v12.16.1, Yarn 1.22.4, and Redwood 0.2.0.

When I follow [the tutorial](https://redwoodjs.com/tutorial/installation-starting-development), and I get to the point where I need to run `yarn rw dev`, the application fails with this error:

![image](https://user-images.githubusercontent.com/2546219/76690825-aadcc780-661a-11ea-918b-94a0f6524475.png)

```
Failed to compile.

./src/Routes.js
Module not found: Error: Can't resolve 'srcpagesFatalErrorPage' in 'C:\Users\weave\Documents\rw-productivity-sam\web\src'
```

This to me seems like a failure to escape slashes in path names. Any idea where I can fix this?

**Comment by peterp** [comment]
Hey @weaversam8, we've fixed this, I'm going to release `v0.2.1` that'll work for you.

**Comment by peterp** [comment]
This is now fixed
![image](https://user-images.githubusercontent.com/44849/76691346-433e7080-664a-11ea-858b-9079f2711f21.png)

**Comment by weaversam8** [comment]
Awesome, thanks so much!

For future folks stumbling on this issue, updating the dependency for `@redwoodjs/core` in `package.json` will suffice, you don't need to create a whole new app again.

**Comment by thedavidprice** [comment]
How to upgrade your RedwoodJS app:
https://community.redwoodjs.com/t/how-to-upgrade-redwoodjs-app-and-packages/122
