### ISSUE TITLE
Suggestion - Redwood scaffold generator - file naming

### ISSUE THREAD

**Issue by cjreimer** [redwoodjs/redwood#2543]
Hello all!

> There are only two hard things in Computer Science:
> cache invalidation and naming things. — Phil Karlton

I've used the scaffold generator extensively in my app to develop admin pages.  As the app grows, I find that I'm having more challenges staying on top of the organization of the files.  One small concern is that the scaffolded pages are scattered about due to file and directory naming, and are not organized together.  That is, the scaffolded files / directory don't sort nicely by domain.

Yes, I know it is not that hard to search for a file instead of scrolling down the file tree in vscode, but it does help me to think more clearly about my code organization if there is structure to it.  So my simple suggestion is to rename a few of the files the scaffold generator produces so that the files sort into nice little group.  An example using the output of the scaffold generator for `post` is below.  With the proposed changes the 'post(s)' files will all be grouped together.

The existing generator provides:

in /components
* EditPostCell
* NewPost
* Post
* PostCell
* PostForm
* Posts
* PostsCell

and in /layouts
- PostsLayout

and in /pages
* EditPostPage
* NewPostPage
* PostPage
* PostsPage

I propose we change our file and directory names as follows:

in /components
* **PostEditCell**
* **PostNew**
* Post
* PostCell
* PostForm
* Posts
* PostsCell

and in /layouts

- PostsLayout

and in /pages
* **PostEditPage**
* **PostNewPage**
* PostPage
* PostsPage

This would be a simple change, but I hope it would be helpful for anyone that keeps scaffolded code in their codebase.  Thoughts?  I suspect there will be a few different philosophies on file naming out there, but I believe that many follow the convention with the domain/model before the action/type of component.

I may have some further tops of discussion regarding code and file organization, but those are for another day.

**Comment by Tobbe** [comment]
Thanks for bringing this up. I've also been feeling the code organization pains as my apps grow.

An open PR that I also think can/will help with this is https://github.com/redwoodjs/redwood/pull/2430

**Comment by cjreimer** [comment]
@Tobbe, thanks for linking #2430!  I'm looking forward to using it!

Is it addressing the above regarding scaffolds as well?  I didn't see it in the pr, but I didn't check the committed code.

**Comment by Tobbe** [comment]
No, it doesn't include your proposed change. But it would allow you to put all the scaffolded files in their own folder, so it'd be easy to find/see what files belong together even though they don't start with the same prefix.

But I like both ideas, and think they have value even if used together 👍

**Comment by jtoar** [comment]
@cjreimer This isn't quite what you want but might help; if you generate your scaffold like this:

```
yarn rw g scaffold admin/post
```

where `admin` is the name of a directory that you want all your scaffold components to be in (it doesn't have to exist), all the scaffold components will be generated in it, in their respective categories:

<img src="https://user-images.githubusercontent.com/32992335/118404317-4e62a700-b627-11eb-91c8-a36012a987ac.png" width="200" />

**Comment by cjreimer** [comment]
Thanks, Dominic!

Yes, you are correct!  I have been using this and have collected all my "admin"scaffolded  components together.  I'm currently at 91 components in my Admin area and growing.

I believe I could also do the following to nest it further:

`yarn rw g scaffold admin/post/post`

And I may be forced into this further nesting yet, but I don't like nesting too deep either.  There's a good chance I'll probably have to reorganize to address other factors as well, and @Tobbe's suggestion of #2430 will help address that.

Thanks for the tip!

**Comment by jtoar** [comment]
@cannikin would love to hear your thoughts on this one when you get the chance!

**Comment by cannikin** [comment]
I went with the current naming structure because it made sense when you read it/say it out loud..."hey take a look at the new post cell." I was influenced by Rails naming conventions, of course. :)

But now that I've generated my fair share of scaffolds I agree that moving the model name to the front would be worth the tradeoff of grouping everything much nicer.

I've also thought about installing everything in a directory by default:

* components/Posts/PostsCell.js
* components/Posts/PostNewCell.js
* etc.

Maybe it's time to make that change as well?

Also, we should make a new issue for this, but now that we have `<Set>` I've thought about creating a single `Scaffold.js` layout that all scaffolds would share, rather than each having their own. It's probably more common that all the admin pages have a similar look and feel than every one of them be unique, so doing this would help facilitate that. The problem here is injecting the title of the section back up into the layout. Any news on that default `SetContext` being created automatically with a `<Set>` @Tobbe? 😃

**Comment by jtoar** [comment]
+1 for installing everything in a directory by default. The main consideration is how that would affect the tutorial (would it make things more/less confusing that only the scaffold installs files into a directory?); and also, how do you opt out of this behavior? With a new flag `--no-prefix` or something similar?

There's two issues about using `<Set>` in scaffolds:
- https://github.com/redwoodjs/redwood/issues/2546
- https://github.com/redwoodjs/redwood/issues/1022

Neither has an answer for injecting the title though I think

**Comment by cjreimer** [comment]
I also love Rob's idea of putting all the scaffold files into one directory based upon the model.   There might be a few people who prefer the separate directories, but my guess is that they will be in the very low minority (< 2.21 % 😃 ) .... Feel free to post here if you are one of those and prove me wrong!  So, I don't know if we need a flag to maintain the current behavior.... although I'm not necessarily opposed to it.

A common layout file Rob suggested would also great, and I think this could be a future PR to address.

In addition, I think there's room for a further future PR to optionally (with a flag) allow some of the ideas presented in [https://community.redwoodjs.com/t/perfect-file-structure-for-redwood-web/1575](https://community.redwoodjs.com/t/perfect-file-structure-for-redwood-web/1575).  I'd ideally like to see the components dedicated to pages in subdirectories of those pages (or something similar) ... but that's another discussion.

**My suggestion for an implementation PR at this time:**
1.  Make the files named as per the original post (standard behavior- no flag opt out).
2.  Group the files as per Rob's suggestion by default (standard behavior - no flag to opt out).  If there are complaints, we can always re-introduce the separate directories with a flag.

I can help out with this ... just want to make sure we have reasonable buy-in before proceeding.

**Comment by Tobbe** [comment]
> I've also thought about installing everything in a directory by default:

Would this be different than just `yarn rw g scaffold posts/Post` that we can already do?


> Any news on that default `SetContext` being created automatically with a `<Set>` @Tobbe? 😃

I'm going to need that for my own project(s), so I'll do it there first, then I'll contribute back. But I'd say this is ~3 weeks out still

**Comment by jtoar** [comment]
> Would this be different than just `yarn rw g scaffold posts/Post` that we can already do?

@Tobbe it doesn't seem like it would be different, it'd just be doing it by default. I think that's still a win because the `post/Post` syntax isn't super findable still, and like @cjreimer said, most people seem to want to use it!

**Comment by cjreimer** [comment]
I think we can proceed and I'll try to get to code for a PR soon.

Just to be clear, I think we are talking about something slightly different than currently available:

If we currently run `yarn rw g scaffold posts/Post` we would currently get:

in /components/
* Posts/
  * EditPostCell/
    * EditPostCell.js  
  * NewPost/
    * NewPost.js
  * Post/
    * Post.js
  * PostCell/
    * PostCell.js
  * PostForm/
    * PostForm.js
  * Posts/
    * Posts.js
  * PostsCell/
    * PostsCell.js

... and similar for layouts and pages.

Under the proposed change, if we run `yarn rw g scaffold admin/Post` we would get:

in /components/
* Admin/
  * Post/
    * PostEditCell.js  
    * PostNew.js
    * Post.js
    * PostCell.js
    * PostForm.js
    * Posts.js
    * PostsCell.js

... and similar for layouts and pages.

**Comment by Tobbe** [comment]
So one big folder with all the components, tests, stories and scenarios?

**Comment by cjreimer** [comment]
Redwood currently isn't generating stories and tests for scaffolds on the web side.  Has anyone asked for them?  Do we need them?

If we do, perhaps that's where an option flag comes into play.   My personal preference would be to have

in /components/
* Admin/
  * Post/
    * Tests/
      * All test files
    * Stories/
      * All story files
    * PostEditCell.js
    * PostNew.js
    * Post.js
    * PostCell.js
    * PostForm.js
    * Posts.js
    * PostsCell.js

**Comment by jtoar** [comment]
@cjreimer I remember @guledali asking for them a while back; the reason we didn't do it before was we didn't know what testing and storybook would end up looking like, but now that those have been integrated, it's definitely something we could think about. It would make scaffolds that much more awesome!

It's probably better save that for another PR though; it would balloon the scope. if you want to take on the other things discussed here, it seems like you can start working on the two things you mentioned:

> - Make the files named as per the original post (standard behavior- no flag opt out).
> - Group the files as per Rob's suggestion by default (standard behavior - no flag to opt out). If there are complaints, we can always re-introduce the separate directories with a flag.

**Comment by cjreimer** [comment]
Sounds good!  I'll put it into my work queue.

**Comment by Tobbe** [comment]
> Redwood currently isn't generating stories and tests for scaffolds on the web side.

You're right! It was a while since I last used the scaffolding stuff...

Definitely like Dom's suggestion of leaving the tests etc for another PR 👍
