### ISSUE TITLE
Typescript - Scenario Template - cannot find name "defineScenario"

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#2549]
When creating a new Typescript service in the Redwood api, the scenario file warns that it cannot find "defineScenario":

![image](https://user-images.githubusercontent.com/1051633/118682426-6de80400-b7ce-11eb-9437-300b7dd07b42.png)

![image](https://user-images.githubusercontent.com/1051633/118682628-9ff96600-b7ce-11eb-87a6-c6c81c30a761.png)

related is:

![image](https://user-images.githubusercontent.com/1051633/118685980-93c2d800-b7d1-11eb-9e91-552efbef3ee2.png)

**Comment by jtoar** [comment]
@cannikin you want to take this one? 😉

**Comment by cannikin** [comment]
Solution: never use Typescript

#wontfix ;)
