### ISSUE TITLE
Information  related to contribution

### ISSUE THREAD

**Issue by SANJAY-NT** [redwoodjs/redwood#2561]
I am a beginner at open source contributions and found this was a interesting place to start with can I know how can I become a part of this community.

**Comment by thedavidprice** [comment]
Hi @SANJAY-NT Your participation and contribution is very welcome!! And there's a vibrant, helpful community to go on this journey with you.

The best "getting started" overview we have right now is this [GitHub Issue from last Hacktoberfest](https://github.com/redwoodjs/redwood/issues/1266). It will link to docs, online community forums and chat, and suggest ways to get started.

It's last minute, but I am hosting a Redwood Contributors Workshop today. You're very welcome to join if you can! I hope to do another one within the next month — join the Forums and watch for Announcements:
- [Redwood Contributors Workshop Details](https://community.redwoodjs.com/t/contributing-workshop-for-redwoodjs-this-thursday/2123)
