### ISSUE TITLE
`unauthenticated` is not a suggested prop of `<Set>`

### ISSUE THREAD

**Issue by realStandal** [redwoodjs/redwood#2562]
This issue is related to PR #2364. It could also be that my project uses TypeScript; either way, it is not actively blocking me from using the `<Set>` component as intended, this issue is just for DX.

When using the new `private` prop on the `<Set>` component, I'd expect `unauthenticated` to be a suggested prop; like it is/was for `<Private>`.

I'm expecting that, as I begin to type unauthenticated, it will appear as a suggestion in my IDE, much like `private` is.

Right now, VSCode does not suggest it, but _it does_ know about it, and will **not** throw a TS error once I've fully typed out the prop's name:

![image](https://user-images.githubusercontent.com/25166787/118971417-65faa200-b93d-11eb-828e-4f18baf60376.png)

![image](https://user-images.githubusercontent.com/25166787/118970279-0b147b00-b93c-11eb-872e-0eb21ac9fd1a.png)

A better example of what it is I'm expecting:

![image](https://user-images.githubusercontent.com/25166787/118971295-3e0b3e80-b93d-11eb-8e8a-250c3b35d1f2.png)

Thank you, as always :)

**Comment by Tobbe** [comment]
### 💯 

I don't know how to make it do that though 🙁 We have the same issue for the `<Route>` component where some combinations of props should be enforced, and some combinations disallowed. And I tried, but failed, to make it work like that.

For this specific scenario though, I'd recommend you just go with using `<Private>`. Since `<Private>` === `<Set private` now, you can also use the `wrap` prop on `<Private>`.

```jsx
<Private unauthenticated="login" wrap={DashboardLayout}>
```

**Comment by realStandal** [comment]
Thank you @Tobbe, `<Private>` worked just as you say. Dropping some more of my findings here, hopefully it has some info you didn't already know about.

I spent a few more minutes last night tinkering with my routes, I was able to find that `unauthenticated` not showing up in autocomplete comes from its use after `private`. If I type it before I specify private, I get autocomplete back (as expected, on `<Private>`). The issue seems to revolve around the private prop, as once I move unauthenticated, `wrap` looses its suggestion; which now appears behind private. More specifically, it occurs when `private` is defined using the boolean short-hand for `true`. If I explicitly set `private={true}`, autocomplete for props defined after it comes back. The issue also occurs when using the boolean short-hand and splitting the component into multiple lines.

It doesn't seem to be an issue with VSCode, as `<Route>`'s autocomplete worked after specifying `notfound`.

![image](https://user-images.githubusercontent.com/25166787/119152629-7afb3200-ba1e-11eb-9878-6cf6a9545ca1.png)

I've never ran into anything like this, I'm assuming it has to do with the use of generics on the Set and Private components. I also thought of how my IDE is marking the props of Set and Private as `JSX attributes` (where as Route provides them as a `property`). However, I have other components which expose their props in a similar way, and the value after a short-hand boolean worked fine:

![image](https://user-images.githubusercontent.com/25166787/119153964-b813f400-ba1f-11eb-8274-02e53f07d76b.png)

Updating `Set.d.ts` to not use generics, and defining the Set component in a way similar to Route (`declare const Set: React.VFC<...>`) also did nothing; updating its props to use an `interface` did no good as well.

**Comment by thedavidprice** [comment]
cc @dac09 @peterp --> I'm not sure if this one is on the master TS list yet.

**Comment by Tobbe** [comment]
> I don't know how to make it do that though 🙁 We have the same issue for the `<Route>` component where some combinations of props should be enforced, and some combinations disallowed. And I tried, but failed, to make it work like that.

I finally solved this! https://github.com/redwoodjs/redwood/pull/2592

Unfortunately the same fix doesn't help with `<Set>`. I think it is because a set can take any prop, and any number of props (that it'll then forward to all wrapper components).

Specifically for `private` I think VS Code gets confused because it's a JS/TS keyword.

**Comment by realStandal** [comment]
Hey @jtoar I get the same behavior your image shows:

![image](https://user-images.githubusercontent.com/25166787/145700472-262f42ce-1da9-40f0-a5d1-62bb9e390a6f.png)

However, the behavior I described in this issue, specifically in my [second comment](https://github.com/redwoodjs/redwood/issues/2562#issuecomment-846003783) is still occuring:

![image](https://user-images.githubusercontent.com/25166787/145700491-7c9dc6bf-f2b2-469b-8811-7dfa64ae8ffd.png)

Note how `private` is being defined using the truthy shorthand and appears before `unauthenticated`.

If I use the long-form to define `private`:

![image](https://user-images.githubusercontent.com/25166787/145700509-e225cd8f-9ece-4508-8717-5677acf8c304.png)

Or if `unauthenticated` is put before `private`:

![image](https://user-images.githubusercontent.com/25166787/145700517-24b97b1c-2ed8-4037-9739-120dcf0a9d16.png)

It's very nuanced, and entirely revolves around DX - no functionality is broken, if I use the short-hand and put unauthenticated after it, everything works as expected.

Happy to close the issue or if y'all would rather leave no stone unturned you can keep it open - I'm with the overall consensus, it doesn't and hasn't affected me sense. I just saw something, so I said something 😄

**Comment by jtoar** [comment]
@realStandal Thanks for clarifying! `unauthenticated` is literally the worst prop to type so we can leave this one open 😅

**Comment by serpilacar** [comment]
Seems like it's somehow related to naming of this prop. If you rename `private` to `isPrivate` (or something else) in the `Set` definition it works as expected. This doesn't even seem like an issue related to Redwood imo but most likely something related to Typescript/VSCode IntelliSense. 

Suggestion of other props also does not work after using `private`:

![Image](https://github.com/redwoodjs/redwood/assets/17191440/a99ce92b-38d9-4fea-a08b-60c158261fba)

For instance `prerender` prop has exactly same declaration as `private`: is a boolean and optional for `Set`. Suggestions of other props after `prerender` works properly:

![Image](https://github.com/redwoodjs/redwood/assets/17191440/56171739-293d-4f59-9f7b-2a2e121d958d)

After changing prop name to `isPrivate` in Set declaration:

![Image](https://github.com/redwoodjs/redwood/assets/17191440/09c6dda3-9273-4110-9b3f-2ff0aae4c24b)

![Image](https://github.com/redwoodjs/redwood/assets/17191440/5b8cc564-ffbd-45e3-968d-dbf7e42504e0)

**Comment by Tobbe** [comment]
@serpilacar Thanks for digging into this!

It's probably because `private` is a reserved word in the JS language, or at least a "future reserved word"
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#future_reserved_words
