### ISSUE TITLE
Cell generators not handling plurals/singular names

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#2565]
## What?
- **Singular form** `yarn rw g cell member`
This indicates I want to get a cell to fetch a member by id. What it should do:

- [x] generate the correct query (and name it correctly so it doesn't conflict with the plural)
- [x] generate the correct mock
- [ ] pass the correct props in the success test

- **Plural form**  `yarn rw g cell members`

- [x] generate the correct query
- [x] generate mock that returns an array
- [ ] pass the correct props in the success test

**Comment by jtoar** [comment]
Also see https://github.com/redwoodjs/redwood/issues/684
