### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#2567]
In the Router, there's a lot of room for polish. Not all of these are required for a `v1` release candidate, but the more of them we can address the better the `v1` Router experience will be. Here's a running list of paper cuts that that would make the DX that much better:

- Allow partial matches with NavLink #2362
- RFC: Optional path parameters #2429
- Route parameters that do not immediately follow a slash do not work #2019
- Allow beforeQuery in a Cell component to receive the params #2139
- Allow params to be appended to an existing route #2141
- `unauthenticated` is not a suggested prop of `<Set>` #2562

There are of course some must-haves. Here's an incomplete list:

- Route tolerance for trailing slash #156
  - One of our oldest issues. If you want to take this one, you could implement Tom's comment here https://github.com/redwoodjs/redwood/issues/156#issuecomment-592725261.
- The <Link> component increases the length of window.history when path doesn't change #1584
- we really need to nail down the documentation for if and when there's a page flash, and how to avoid it #2124
- it seems like searchParams shouldn't overwrite pathParams #2121
- Routes that aren't defined should fail at build time #206
- BUG: Private routes that match non-private routes redirect even with direct match #2590
  - This one's being worked on!

### TypeScript

The idea of having a typed router got a lot of attention early on, when our TS skills as a core team were at their weakest. Now that we've been through the ringer, it seems like now's a good time to come back around to this topic:

- Routes that aren't defined should fail at build time #206

**Comment by KrisCoulson** [comment]
@jtoar going to add this here as well.

- Private routes that match non-private routes redirect even with direct match https://github.com/redwoodjs/redwood/issues/2590
