### ISSUE TITLE
BUG:  Private routes that match non-private routes redirect even with direct match

### ISSUE THREAD

**Issue by KrisCoulson** [redwoodjs/redwood#2590]
When using dynamic routes if the private route is a match it will redirect to the unauthenticated page.

The problem is even though there is a direct match with `/about` the router will still match on `/{param}` as an authenticated route and it will redirect to the `/home` page.

```javascript
    <Router>
      <Route path="/about" page={AboutPage} name="about" />
      <Route path="/" page={HomePage} name="home" />
      <Private unauthenticated="home">
        <Route path="/{param}" page={ParamsPage} name="param" />
      </Private>
      <Route notfound page={NotFoundPage} />
    </Router>
 ```
 
 There is one test that would suggest that even though `/about ` comes first it would hit a match but this does not take into account if a the param is in a privte route.
https://github.com/redwoodjs/redwood/blob/0555cbe726e17f5e2e9832a62655c7c96c830163/packages/router/src/__tests__/router.test.tsx#L446-L465
 
 I have verified this on my current project and with a clone of the tutorial project.
 
Video from project.
https://user-images.githubusercontent.com/6943688/119086548-76049700-b9ba-11eb-8f23-0aafc46e8977.mov

Expected behavior is we have a match on `/about` and that it does not get redirected.

**Comment by Tobbe** [comment]
I'm working on a fix
