### ISSUE TITLE
Improving GH Action CI: build, lint, test

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#260]
Currently we are using GH Actions for CI, however, GH Actions are early and don’t support our setup (lerna and yarn workspaces for the CRA app). It might be best to move the redwoodjs/redwood CI to something like CircleCI as our needs continue to grow.

## Caching
Ideally `node_modules` would be cached for root and each package (currently managed by lerna)  using [GH Actions Cache](https://github.com/actions/cache). See also [how to cache dependencies.](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows)

This is not yet possible. Related:
- GH Actions not able to cache multiple workspace paths: /actions/cache/issues/16
    - and related PR to add the multi-path support: actions/cache/pull/180
- Node Docker Container support for Yarn2: nodejs/docker-node/issues/1180
- Found Actions specific to Yarn 2 here: https://github.com/sergioramos/yarn-actions
    - which I found here: https://github.com/sdras/awesome-actions

## Run only on “changed” packages
- [ ] employ something like `lerna changed` to build+test against modified packages only (need to choose what our reference will be… last npm release is more than needed but might be good enough first step. Ideally just new commits.)
- [ ] Might need to separate into two Actions: 1) build and 2) test

## Other Actions to consider adding
- [ ] when new packages are published, auto-open PR on other repos that includes updated versions in `packages.json` Could possibly go as far as creating a new release of `create-redwood-app` (but don’t forget about needed to check for updates to `yarn.lock`)
- [ ] monitor build size: see #196

**Comment by peterp** [comment]
>  employ something like lerna changed to build+test against modified packages only (need to choose what our reference will be… last npm release is more than needed but might be good enough first step. Ideally just new commits.)

I think it's OK to run all the tests for all of the packages since they may be interdependent modifications

> Might need to separate into two Actions: 1) build and 2) test

I don't think running build is going to give us anything actionable or useful during CI

**Comment by thedavidprice** [comment]
**re: Modified packages**
Ah, great point. I feel like I’ve seen something like this via CircleCI that _must_ account for dependencies. The main object would be pre-emptive ways to reduce CI run time, which might not even be an issue near-term if at all. And/or caching node_modules to avoid unnecessary `yarn install` might be 80% of the efficiency gain anyway. 

**re: Build**
It's just success/fail with the same output we get locally. Seems important to run given current low test coverage across packages (and increasing community PRs). Note: current running CI includes build, lint, and test. If it turns out to be unhelpful, can easily turn it off.

**Comment by thedavidprice** [comment]
Current GH Action has been working well with no complaints or experience with tediously long run time.

GH Action cache capability hasn’t budged and the only PR addressing multi-path caching was deemed unviable. 

There’s a separate Issue already for monitoring build size, which is likely the only remaining prioity here.

Closing.
