### ISSUE TITLE
Cell generators don't fail for lowercased models

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#2607]
SDL and Service generators fail if the model's lowercased. For example, given the following model `post`...

```prisma
// api/db/schema.prisma

model post {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

running `yarn rw g sdl post` (or `service post`) outputs:

```
~/p/r/_/cells (main)> yarn rw g sdl post
yarn run v1.22.10
$ /Users/dominicsaadi/projects/redwood/_sandbox/cells/node_modules/.bin/rw g sdl post
  ✖ Generating SDL files...
    → No schema definition found for `Post` in schema.prisma file
No schema definition found for `Post` in schema.prisma file
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

But Cell's don't fail; instead they generate a broken file:

![image](https://user-images.githubusercontent.com/32992335/119215809-e37cfa00-ba84-11eb-879c-7c2ae47c05a1.png)

The problematic's line here I think:

https://github.com/redwoodjs/redwood/blob/873a5f0f519a9f7ecd9759c8a1375e5676bf324f/packages/cli/src/commands/generate/cell/cell.js#L72-L77

**Comment by jtoar** [comment]
It'd also be nicer if the generated list template used the singular version for `map`'s argument:

```diff
- {users.map((item) => {
-   return <li key={user.id}>{JSON.stringify(user)}</li>
+ {users.map((user) => {
+  return <li key={user.id}>{JSON.stringify(user)}</li>
})}

```

**Comment by cannikin** [comment]
This could be a relatively easy fix. When I first wrote this code there was nothing in the response from `getDMMF()` that denoted anything special about the model name, so I just did:

    pascalcase(pluralize.singular(name))

Based on Prisma's recommendations for naming your models (PascalCase like `UserPreference`)

Now I bet there's a properly like `modelName` or something that returns what it ACTUALLY is, and also won't freak out if the table name is different (there's a `dbName` property now, I believe, in case you change your table name with `@map` in the schema).

**Comment by jtoar** [comment]
Fixed in https://github.com/redwoodjs/redwood/pull/3616.
