### ISSUE TITLE
Architecture improvements to `rwt link`

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2617]
**Only copy files that are published**

Redwood's tools `link` command can create false positives because it  copies _all the files_, but it should only copy the files that are published in the package. A list of the published files can be retrieved with the npm command `npm publish --dry-run --json`:

The false positive here is that it could work when you run `yarn rwt link`, but it may not when you publish an actual package because an expected file is not in the bundle.

```terminal
$ cd packages/cli
$ yarn build
$ npm publish --dry-run --json

{
  "id": "@redwoodjs/cli@0.32.2",
  "name": "@redwoodjs/cli",
  "version": "0.32.2",
  "size": 78207,
  "unpackedSize": 342000,
  "shasum": "32c42d8723a9e1b27564693ee17bb3572fc4ce5b",
  "integrity": "sha512-DrjTSj7cNwWk0wdyF3mAesO+iiJuhnVip6jUBwfDw1pQ0GbtU0ylrSJeS7rQQSHNPqSQWiCjEZ8gZ9BCbAcbYg==",
  "filename": null,
  "files": [
    {
      "path": "dist/commands/generate/layout/templates/layout.tsx.a11yTemplate",
      "size": 864,
      "mode": 420
    },
    {
      "path": "dist/commands/setup/auth/auth.js",
      "size": 12334,
      "mode": 420
    },
    /* snip */
}
```

**Copy the packages into a path that other dev-time tools ignore**

Right now the the packages are copied into a top-level `redwood` directory and linked via workspaces. This causes problems with `yarn test` since it looks for files matching `**/*.test.*`. There are likely other tools that would also cause similar problems. The solution here is to move the files into `node_modules/.rwjsPackages` since no user-land tools will run look for things in node_modules.

**Add flags to skip steps**

Right now the `link` command in `./tasks` also builds the project - I would love to use it in the e2e tests, but for this I need to be able to disable the automatic building.

/cc @dac09

**Comment by dac09** [comment]
> Right now the link command in ./tasks also builds the project - I would love to use it in the e2e tests, but for this I need to be able to disable the automatic building.

It has a slilghtly unusual `--watch` flag @peterp. You can do `rwt link --no-watch` and it'll copy and link once. 

> Right now the the packages are copied into a top-level redwood directory and linked via workspaces. This causes problems 

Agreed! Look forward to the solution here.

> The false positive here is that it could work when you run yarn rwt link, but it may not when you publish an actual package because an expected file is not in the bundle.

I meant to handle this case using this bit here: https://github.com/redwoodjs/redwood/blob/main/tasks/build-link#L89-L99

I know it works for the majority of cases, but maybe its not for others?

**Comment by dac09** [comment]
Replaced by Rufus. Closing
