### ISSUE TITLE
Remove deprecated features for v1

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#2631]
The codebase currently includes many items indicating v1 deprecation.

We should find those and deprecate them.

**Comment by jacebenson** [comment]
Would this include the old cli commands like yarn rw db save?

**Comment by jtoar** [comment]
@jacebenson look to @thedavidprice for the final word, but I think the answer is yes.

**Comment by thedavidprice** [comment]
If you search the codebase, you get 37 instances of "deprecated" — all those features gotta go!
<img width="249" alt="Screen Shot 2021-05-25 at 9 22 20 PM" src="https://user-images.githubusercontent.com/2951/119602130-5e088b00-bd9f-11eb-996d-57b95c72f4ce.png">

**Comment by thedavidprice** [comment]
> Would this include the old cli commands like yarn rw db save?

^^ Yes, great reminder. Currently we just call the new `prisma` command when someone runs that command. But it should be removed completely.

**Comment by callingmedic911** [comment]
@thedavidprice @jtoar I'd be glad to pick this up. Let me know.

**Comment by dac09** [comment]
Hey @callingmedic911 and all, I believe I did remove a whole bunch of depracated stuff a little while ago, but there's a handful left. Assigning to you, thank you :)
