### ISSUE TITLE
RFC - DX Experience updating/overwriting SDL w/ Service scenarios and tests via generators

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#2639]
I recently had a suboptimal DX when iterating on a schema and incrementally generating the SDL.

In short, I had 

* built a model "Entry"
* migrated
* generated the services and sdl via `rw g sdl Entry --crud`
* written scenarios and tests for my crud services

I then added additional attributed to my Model and I wanted to update the SDL so I did what I typically had done in past (though then I had *not* written scenarios or tests) and `rw g sdl Entry --crud --force` since I knew that would overwrite my SDL and service and I was ok with that.

### What Happened

But, this time I lost *all* my custom scenario data I setup and lost *all* the tests I had written. 😢

Fortunately, I had just committed to GitHub so I could restore the scenario and tests.

### The DX I Want

But, what **I want is a way to safely and incrementally iterate on me Model schema and update the SDL** -- just the SDL. I'm fine with no change to the service and fine with no changes to scenarios and tests -- in fact I want to manually update those with the new Model attributes because they may be required now and my tests will fail when creating a Model item.

### Proposal

I propose adding an `--update` or `--refresh` optional parameter to the `rw g sdl` generator.

A command `rw g sdl Model --crud --update` would:

* only re-create the SDL file 
* not update tests
* not update scenarios

An argument against this approach is that one may have added new service methods and thus added these to the SDL, for example 'findBySlug` and that would be overwritten.

In that case, perhaps iterating and using the generator isn't the best option -- and any and every schema change demands manual SDL editing.

**Comment by cjreimer** [comment]
@dthyresson, I like your idea!  I, too, found that a few more granularity options in the generators would be helpful as features and attributes get added to the codebase.  I found myself temporarily renaming files so I could run the generators and then put the files I didn't want to be overwritten back.  

For me, the `--update` flag is not clear that it will only update the actual SDL file.  What if I were to only want it to update the service file?  Or a test file?  Also, the `rw g sdl Model` confused me as I assumed it would only write the sdl file and not the service file as well.  We already have a `rw g service Model` command to just generate the service file.


Some ideas/suggestions on implementation are as follows.
1.  I like to idea of having to write `--force` if I want to overwrite.  This keeps that behavior consistent.
2.  Add a new command `rw g api Model` which generates both the sdl and the service file (similar to the existing `rw g sdl Model` command
3.  Modify the `rw g sdl Model` command to only generate the sdl file.
4.  Add a `--noTests` flag that would stop the generations of test and scenario files (or alternatively set the following in the `redwood.toml` file, which I believe is already underway but not completed.

```
[ generate ]
tests = false
```

Thus, the command to do what you are proposing would simply be:

`rw g sdl Model --crud --force`

and the command to update only the service file would be:

`rw g service Model --crud --force --noTests`

A future feature could be interactive capabilities, where anytime a generator runs into an existing file, it prompts the user if the file should be overwritten or not.  That could eliminate having to remember the option flags.

**Comment by thedavidprice** [comment]
closing in favor of #4540
