### ISSUE TITLE
You must register a useQuery hook via the `GraphQLHooksProvider`

### ISSUE THREAD

**Issue by ashrays** [redwoodjs/redwood#2640]
I've been following tutorial2, but at the point of adding CommentCell to BlogPost, I've Encounter this error.

![Screenshot from 2021-05-26 18-39-53](https://user-images.githubusercontent.com/42745486/119665560-260e5000-be52-11eb-9f62-0b483d01211a.png)

**Comment by thedavidprice** [comment]
Hi there @ashrays I'll see if I can get you pointed in the right direction here. The best place for quick help might be our Chat (on Discord): https://discord.gg/jjSYEQd

If it takes more discussion, you can start a thread in our Forums and paste code + repo for reproduction: https://community.redwoodjs.com

Overall, this kind of thing is really hard to diagnose without code snippets.

Storybook aside, is your code working in your app? E.g. does `yarn rw dev` work? I'd start de-bugging there.

Once you know the code is working and `<Blogpost>...<CommentCell />...</Blogpost>` is working, you'll need to update the file `web/src/components/BlogPost/BlogPost.stories.js`. My guess is that once you added the CommentCell component, you're no longer returning the correct prop(s) to render the story with mock data.
 
<img width="230" alt="Screen Shot 2021-05-26 at 1 27 57 PM" src="https://user-images.githubusercontent.com/2951/119726651-327cb380-be26-11eb-8662-d96293dda25f.png">

**Comment by ashrays** [comment]
@thedavidprice thankyou for your response, I'll put up more info in a bit, The thing is I've followed the tutorial perfectly, which is why I kept the question brief, though others might be encountering the same error, I believe it has something to do with graphql mapping/spoofing done by redwood to get storybook to work.

So on [this](https://learn.redwoodjs.com/docs/tutorial2/multiple-comments) page,  "Let's add our CommentsCell to the actual blog post display page" - is exactly where this error occurs 

This section 
"Shouldn't the CommentsCell cause an actual GraphQL request? How does this work?

Redwood has added some functionality around Storybook so if you're testing a component that itself isn't a Cell (like BlogPost) but that renders a cell (CommentsCell) that it needs to mock the GraphQL and use the standard mock that goes along with that Cell. Pretty cool, huh?"

the functionality that this describes is what might be causing the issue, I Have abandoned the tutorial assuming this part is getting re-written. what else can I share?

here is the exact state of my code. https://github.com/ashrays/redwood-tutorial

**Comment by rminami** [comment]
Hi, I encountered this problem as well. 

The issue mysteriously went away when I upgraded my Redwood JS to version 0.32.2 (if you started at the example repo at the beginning of part 2, you're probably on 0.31.2). 

I'm still not sure what the issue was, since within Storybook we should be getting our props from `standard` at `CommentsCell.stories.js` and not be making any GraphQL calls, but this might help you get going again.

Btw, `CommentsCell` should not render correctly when we run `yarn rw dev`, since we have not implemented the backend for comments at this point in the tutorial.

**Comment by ashrays** [comment]
@rminami I think you are right. just noticed the version. Let me try and do the tutorial from 0.32.2 and close the issue.

**Comment by ashrays** [comment]
works with the newer 32.2 version. thank you @rminami, @thedavidprice. The tutorial codebase has to be updated.

**Comment by standup75** [comment]
Just for reference if someone lands here by way of searching for the error message. I had the problem with Redwood 5.0.6 where for some reason the @redwood/testing package had its own @redwood/web package in its node_modules folder. Probably something we missed during the migration to 5. Anyway, upgrading to the latest fixed it, probably cause it runs `De-duplicating dependencies` ?
