### ISSUE TITLE
Update `schemaPath:` value in `config.ts` 

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#2644]
Related to https://github.com/redwoodjs/redwoodjs.com/pull/703#discussion_r639964924 and Docs PR https://github.com/redwoodjs/redwoodjs.com/pull/703

We currently have an incorrect default value in https://github.com/redwoodjs/redwood/blob/e6c941aea36433ebb790c75c62a0a0dfc9edb998/packages/internal/src/config.ts#L67

It should be:
`schemaPath: './api/db/schema.prisma'`

**Comment by thedavidprice** [comment]
@pdjota has offered to work on this. Thanks in advance!

**Comment by pdjota** [comment]
yes, will take care of it soon.
