### ISSUE TITLE
Graphql/prisma Subscriptions?

### ISSUE THREAD

**Issue by johndevor** [redwoodjs/redwood#269]
Probably way too early to ask, but any plan for supporting them?

**Comment by thedavidprice** [comment]
Making sure I connect the dots between this Issue and the forum conversation — might you @johndevor also be ‘john’ in the forum? 😄

https://community.redwoodjs.com/t/graphql-prisma-subscriptions/121

Going to close this out in favor of moving discussion to the forum. Thanks!

**Comment by johndevor** [comment]
Thanks. Yes, sorry for the duplication!
