### ISSUE TITLE
Netlify functions failing with missing dependency

### ISSUE THREAD

**Issue by o0charlie0o** [redwoodjs/redwood#2690]
We recently upgraded from `0.28.4` to `0.32.2` and noticed our functions except for the main graphql one now fail with the following error:

> Error: Cannot find module 'graphql-tag'\\nRequire stack:\\n- /var/task/src/node_modules/@redwoodjs/api/dist/makeMergedSchema/rootSchema.js\\n- /var/task/src/node_modules/@redwoodjs/api/dist/makeMergedSchema/makeMergedSchema.js\\n- /var/task/src/node_modules/@redwoodjs/api/dist/index.js\\n- /var/task/src/api/dist/lib/auth.js\\n- /var/task/src/api/dist/lib/index.js

I've retested everything on `0.28.4` again and it works just fine. I will incrementally test each upgrade from `0.28.4` to `0.32.2` to find which version introduced the issue but just wanted to open this now to hopefully start a discussion. We are really looking forward to working with some of the features introduced in `0.32.2`.

**Comment by thedavidprice** [comment]
Hi @o0charlie0o Errors like this normally indicate something went wrong with yarn.lock and node_modules during installation(s). My guess is that your code is fine🤞Some steps to debug:
- look through the three package.json files (root, web/, and api/) and confirm you have the correct versions for `@redwoodjs` packages in each. Look for duplicate packages as well
- delete your `node_module` directories (in root, api/, and web/)
    - I do this using `git clean -fxd -e .env` WARNING: this removes anything that is `.gitignore`'d _except_ your .env file (if you have one). So if you have anything else local-only that you want to keep, you should probably just delete node_modules manually
- run `yarn install --force`

Does that work? If "yes", celebrate! If "no", try:
- all the steps above up to `yarn install`
- before you run `yarn install`, first delete `yarn.lock` and then run `yarn install`

**Comment by o0charlie0o** [comment]
Thanks for your suggestions @thedavidprice. First let me say that regenerating the lock file ultimately fixed the issue but I did test every version with a netlify deploy between `0.28.4` through `0.32.2` and it wasn't I hit `0.32` that I started experiencing the error. Have done this on 2 different branches now so I'm not sure what's going on with the upgrade between `0.31` and `0.32` but it does seem to be corrupting something.

**Comment by thedavidprice** [comment]
Great to hear it's resolved!

> Have done this on 2 different branches now so I'm not sure what's going on with the upgrade between 0.31 and 0.32 but it does seem to be corrupting something.

This has been an ongoing complaint of ours with Yarn. We've been doing a lot to mitigate these problems ongoing, including recreating the `yarn rw upgrade` command (coming with v0.33) and using a different strategy to manage dependencies within the Redwood packages. Fingers crossed we'll be seeing improvements with the upcoming releases.

Most of all, thanks for fighting through the mess with us!
