### ISSUE TITLE
Add command `yarn rw upgrade`

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#271]
> We need a single command you can run to update everything at once. - TPW
- [x] **Step 1**: simple cli command that bumps our 4 packages to latest version and then runs yarn install
    - bonus: flag to check if upgrade is available/needed (compared to installed)
- [ ] **Step 2**: background checks for new versions; prompt users at the command line when new versions are available

> And eventually even provide codemods to update code.
> But that’s a lot of work, we can save that for much later. For now manual instructions would be great. - TPW
- [ ] **Step 2.5**: include manual instructions for updates to files and code
- [ ] **Step 3**: include interactive steps to create/change files and code

**Comment by peterp** [comment]
This is already done :)

**Comment by peterp** [comment]
This is now done!
