### ISSUE TITLE
Could not find query-engine binary

### ISSUE THREAD

**Issue by steveoOn** [redwoodjs/redwood#272]
I'm new to Redwood, and I love this project, hover when I follow up the tutorial go to `yarn rw g scaffold post`chapter and I got the error message:
```
$ yarn rw g scaffold post
yarn run v1.21.1
$ /Users/rensiwen/Documents/redwood-projects/redwoodblog/node_modules/.bin/rw g scaffold post
  ✖ Generating scaffold files...
    → Could not find query-engine binary. Searched in /Users/rensiwen/Documents/redwood-projects/redwoodblog/node_modules/@prisma/sdk/query-
…
    Adding scaffold routes...
    Adding scaffold asset imports...
Could not find query-engine binary. Searched in /Users/rensiwen/Documents/redwood-projects/redwoodblog/node_modules/@prisma/sdk/query-engine-darwin and /Users/rensiwen/Documents/redwood-projects/redwoodblog/node_modules/@prisma/query-engine-darwin
✨  Done in 1.85s.
```
It seems like @prisma folder dose not contain the file called `query-engine-darwin`
![image](https://user-images.githubusercontent.com/8326506/76719584-2488c880-6775-11ea-85f7-daa104b6c7ba.png)

The environment:
```
$ node -v
  v13.3.0
```

**Comment by peterp** [comment]
It looks like `query-engine-darwin` was not downloaded correctly in Prisma's post install step.

I think you may be able to download it again:

```bash
cd node_modules/@prisma/client
yarn download
```
```

**Comment by steveoOn** [comment]
> It looks like `query-engine-darwin` was not downloaded correctly in Prisma's post install step.
> 
> I think you may be able to download it again:
> 
> ```shell
> cd node_modules/@prisma/client
> yarn download
> ```

Thanks for the tips, I tried to download again in `client` folder, and it won't work, but switch to `sdk` folder download again...it works!

But I do not have any clue of why this happens.  I strictly follow the tutorial step by step. maybe due to network traffic issues?

**Comment by peterp** [comment]
This is usually caused by a network error. I think the Prisma team are trying to figure out a way to make this more resilient.

**Comment by steveoOn** [comment]
yes, thanks~ @peterp
