### ISSUE TITLE
Page generator cannot update routes file when `<Router>` has `useAuth` prop

### ISSUE THREAD

**Issue by realStandal** [redwoodjs/redwood#2746]
I'm running into the following when using `yarn rw g page Foo`, when my `<Router>` has a prop:

```
  √ Generating page files...
    √ Successfully wrote file `./web\src\pages\FooPage\FooPage.stories.tsx`
    √ Successfully wrote file `./web\src\pages\FooPage\FooPage.test.tsx`
    √ Successfully wrote file `./web\src\pages\FooPage\FooPage.tsx`
  × Updating routes file...
    → object null is not iterable (cannot read property Symbol(Symbol.iterator))
object null is not iterable (cannot read property Symbol(Symbol.iterator))
error Command failed with exit code 1.
```

My router for context:

```TSX
<Router useAuth={useRouterAuth}>
  <Route notfound page={NotFoundPage} />

  <Set wrap={[AuthLayout]}>
    <Set wrap={[AuthRedirect]}>
      <Route path="/signup" page={SignupPage} name="signup" />
      <Route path="/login" page={LoginPage} name="login" />
    </Set>
    <Route path="/confirm" page={ConfirmPage} name="confirm" />
  </Set>

  <Private unauthenticated="login" wrap={[DashboardLayout, PageLayout]}>
    <Route path="/" page={DashboardPage} name="dashboard" />
    <Route path="/users" page={UserListPage} name="users" />
    <Route path="/user/{id}" page={UserPage} name="user" />
    <Route path="/roles" page={RoleListPage} name="roles" />
  </Private>
</Router>
```

I'd be happy to work on a fix, I assume it has to do with [this line in the CLI lib file](https://github.com/redwoodjs/redwood/blob/d8defc9ac2c277d4749716d0d778a1bd661041f2/packages/cli/src/lib/index.js#L411).

This is an expression I came up with [that is working for my use case](https://regexr.com/5ue0n) and a prop-less `<Router>`.

```JavaScript
/<Router*[^>]+>(\s*)/
```

I'm not incredibly confident with regular expressions, I'm making an issue hoping someone sees a flaw I don't and to make sure I'm on the right track before I go hacking away and re-learning my way around setting up the contributing environment.

**Comment by Tobbe** [comment]
The asterix after 'r' means "zero or more 'r', so I'd get rid of that, and use it instead of '+' after the negative character group instead, to still match `<Router>`

```
/<Router[^>]*>(\s*)/
```

That said, there has been some talk about maybe move over to something more sophisticated than regexes, so I'd wait until you hear from someone else before starting on an implementation

**Comment by thedavidprice** [comment]
^^ @peterp @dac09 Any reactions or direction about this one? Both regarding how it might be handled and priority for v1?

Thanks for the offer to help @realStandal!

**Comment by jtoar** [comment]
It looks like this was fixed in https://github.com/redwoodjs/redwood/pull/3519. Using @realStandal's example, I now see the new route being added appropriately:

```diff
     <Router useAuth={useRouterAuth}>
+      <Route path="/foo" page={FooPage} name="foo" />
       <Route notfound page={NotFoundPage} />

       <Set wrap={[AuthLayout]}>
         <Set wrap={[AuthRedirect]}>
           <Route path="/signup" page={SignupPage} name="signup" />
           <Route path="/login" page={LoginPage} name="login" />
         </Set>
         <Route path="/confirm" page={ConfirmPage} name="confirm" />
       </Set>

       <Private unauthenticated="login" wrap={[DashboardLayout, PageLayout]}>
         <Route path="/" page={DashboardPage} name="dashboard" />
         <Route path="/users" page={UserListPage} name="users" />
         <Route path="/user/{id}" page={UserPage} name="user" />
         <Route path="/roles" page={RoleListPage} name="roles" />
       </Private>
     </Router>
```
