### ISSUE TITLE
ensure that `api/types` are ignored by dev-server

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2750]
It seems that generating the api types was causing my dev-server to reload.

**Comment by peterp** [comment]
We already ignore a bunch of files in the dev-server, we just need to add `api/types/**` to that list.

**Comment by soham4abc** [comment]
@thedavidprice  Where is the list where you ignore the files? I am working in this issue.

**Comment by peterp** [comment]
@soham4abc Thanks!

Here: https://github.com/redwoodjs/redwood/blob/558ecee62a70cf7169eae3bc076cd20b6f5fd044/packages/dev-server/src/watchApiSide.ts#L68-L70

and here: https://github.com/redwoodjs/redwood/blob/38f975abf9e46416ae50b3ce2e1fd8db837206cd/packages/api-server/src/watch.ts#L37-L49

**Comment by soham4abc** [comment]
OK. On it Thank you!!

**Comment by thedavidprice** [comment]
I believe this is being fixed in #2807
