### ISSUE TITLE
New TS project can't find NotFoundPage

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#2754]
It seems like new (i.e. created from scratch) TypeScript Redwood Apps can't find the `NotFoundPage`. Steps to reproduce:
1. create a TS project: `yarn create redwood-app x-ts-route-error --ts`
2. go to `Routes.js`
3. observe:

![image](https://user-images.githubusercontent.com/32992335/121071590-fb42c680-c784-11eb-848e-e8839cec97f2.png)

**Comment by peterp** [comment]
I believe the issue here is that we do not run `rw-gen` when a new project is launched. We should add this to the list of tasks that are completed once a RWJS site is booted.

**Comment by Abheetarora** [comment]
cant we just import the notFoundPage from the pages. I guess that will resolve the issue.

**Comment by jtoar** [comment]
@Abheetarora that would solve it, but we don't want to have to import any Pages in the Routes file—one of our stylistic decisions is that they should be available automatically.
