### ISSUE TITLE
Linting error in functional test project

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#2758]
Just a small linting error in the (amazing!!!) functional test project

![image](https://user-images.githubusercontent.com/32992335/121105674-64dcc800-c7b9-11eb-9cd7-8b7856296b3b.png)

I think it's as simple as adding the key prop:

```diff
 export const Success = ({ posts }) => (
   <div className="divide-y divide-grey-700">
     {posts.map((post) => (
+      <BlogPost key={post.id} post={post} />
     ))}
   </div>
 )
```

**Comment by RhnSharma** [comment]
I would like to take this one.
