### ISSUE TITLE
using git bash on windows breaks route path generation

### ISSUE THREAD

**Issue by Thieffen** [redwoodjs/redwood#277]
Hello.

Corrections made by #219  solved the create-app process.

However, down the road, there is still an issue with route generation when you create a page specifiying a path :

![home_page_creation](https://user-images.githubusercontent.com/847877/76852050-d1814500-684a-11ea-9565-da7ea2f85f33.png)

As you can see, GIT Bash on Windows is replacing any path starting with "/"

In [this discussion](https://github.com/moby/moby/issues/24029#issuecomment-250412919) , @thaJeztah suggested to prefix the path with a double slash.

![home_page_creation_dble_slash](https://user-images.githubusercontent.com/847877/76852398-83207600-684b-11ea-8340-a647e2b0d3f4.png)

![home_page_creation_dble_slash_noquote](https://user-images.githubusercontent.com/847877/76852408-86b3fd00-684b-11ea-9470-be357add3838.png)

A solution would be to modify `packages/cli/src/commands/generate/commands/page.js` code, detect if command `path` parameter is looking like a windows path, and then only take the relevant part at the end.

Might be also considered as a purely GIT Bash related issue.

**Comment by thedavidprice** [comment]
Wow, @Thieffen not sure we could have diagnosed this one easily without your help. We’ll take a look. 

Thank you!

**Comment by thaJeztah** [comment]
Yes, quite some people tripped over this behavior; glad my answer ok that issue helped you find it 🤗👍

**Comment by H4rliquinn** [comment]
Just started learning Redwood today and I noticed this issue in a few of the auto-generated files. Came to find this. It's not hard to fix them, so it didn't stop me from enjoying the tutorial. I'm using PowerShell, though, not GitBash and it is still doing it. I expected it was a Windows issue.

**Comment by jonniebigodes** [comment]
@H4rliquinn there was a recent pr that was meant to address this type of issue with windows, more specifically #331 i haven't had the time to fully test it but it seems that the it's still a issue.

**Comment by thedavidprice** [comment]
@H4rliquinn which version of Redwood are you using? And, specifically, are you on >v0.3.0? One way to tell is to try and run `yarn rw info` from your app directory. Please do paste the output here if it runs.

**Comment by Thieffen** [comment]
Seems to be OK using VSCode + Powershell 5.1 on Windows 10 :

![capt](https://user-images.githubusercontent.com/847877/78269372-c7796a80-7509-11ea-8b8e-e241041a83b3.PNG)

**Comment by thedavidprice** [comment]
RWJS v0.5.0

Tested this locally on my Windows 10 virtual machine. Confirming both Powershell and Bash on Ubuntu are working correctly 👍

closing
