### ISSUE TITLE
Handle binaryTargets differently in the Tutorial

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#278]
@peterp @cannikin

See Peter's suggestion here #270 
> Maybe a short term solution is to remove the binary targets line in the prisma configuration, and then suggest that people change it to binaryTargets = ["native", "rhel-openssl-1.0.x"] when they want to deploy to Netlify?

Also another Windows specific issue+solution here #215 
> Nevermind - I just realized I needed to update the binaryTargets in the schema.prisma file from binaryTargets = ["native", "rhel-openssl-1.0.x"] to binaryTargets = ["native", "windows”]

Piecing these together for possible next steps:
1. remove `binaryTargets = ["native", "rhel-openssl-1.0.x”]` from create-redwood-app default `schema.prisma`
2. add instructions to Tutorial deploy section about setting binaryTargets
3. need different settings for Mac and Windows

Does this seem correct?

**Comment by cannikin** [comment]
Yep that sounds correct. I can add that line to the tutorial after lunch!

**Comment by cannikin** [comment]
It seems like this will end up being the same issue as the provider—this needs to be IN the code so that a deployment to Netlify can work. However when you're in local dev you'll need to remove again to keep working?

**Comment by peterp** [comment]
Closed by https://github.com/redwoodjs/create-redwood-app/issues/38
