### ISSUE TITLE
Redwood contributing - yarn rwt cp on Windows

### ISSUE THREAD

**Issue by cjreimer** [redwoodjs/redwood#2789]
It took me a while to get 
`yarn rwt cp`
working on my Windows machine.  In the end, I found it was a permissions issue and found two fixes:

1.  Running the shell or VSCode as an Administrator (not the ideal solution, but works)
2.  Turning on Windows Developer Mode in the settings.

![image](https://user-images.githubusercontent.com/51102303/121447137-ae184d80-c95a-11eb-9666-10307e77a0b9.png)

I believe the 2nd option should be preferred.

So, how can we make it easier for others? I propose two items:

1.  I'll draft a change to the contributing.md doc.
2.  Should we try to guide Windows users who run the command to ensure they are in developer mode?

I'm thinking we watch for an exception in the fixProjectBinaries function, and if we catch an exception, and the platform is Windows, we throw out an error message to the console suggesting that the Windows Developer Mode be turned on.

Is this type of warning / prompt appropriate?  Thoughts?

**Comment by Tobbe** [comment]
That's interesting. 

> Running the shell or VSCode as an Administrator (not the ideal solution, but works)

When you run VSCode as admin, I assume you also run the rwt command in the VSCode console, right?

> Turning on Windows Developer Mode in the settings.

I must have turned this on for some other reason, because I don't remember having to do it for RW specifically. Do you know exactly what it does that makes rwt work?

**Comment by Tobbe** [comment]
> I'm thinking we watch for an exception in the fixProjectBinaries function, and if we catch an exception, and the platform is Windows, we throw out an error message to the console suggesting that the Windows Developer Mode be turned on.

If we wanted, we could be more specific in our check:
https://stackoverflow.com/questions/41231586/how-to-detect-if-developer-mode-is-active-on-windows-10

**Comment by Tobbe** [comment]
> Do you know exactly what it does that makes rwt work?

Symlinks! You answered that in your contributing docs pr. Thank you :)

**Comment by Tobbe** [comment]
Closed by https://github.com/redwoodjs/redwood/pull/2790
