### ISSUE TITLE
Add `--cwd` to RedwoodJS CLI

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2792]
RedwoodJS CLI determines if a RedwoodJS project is present by taking the current working directory and searching upwards for a `redwood.toml` file.

Specifying the `cwd` is not currently exposed to the end-users, but can be beneficial, especially to contributors of RedwoodJS, since they can edit the code in RedwoodJS framework repo and run it against a test project.

Internally we already have the `RWJS_CWD` env-var.

`yarn rw --cwd ../../path/to/redwoodjs/project`

**Comment by thedavidprice** [comment]
@peterp I'm prioritizing this for v1 but after v1-rc release. Please let me know otherwise.
