### ISSUE TITLE
Add `getPaths`, `getConfig` and `structure` to global context of CLI

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2793]
The CLI has a single entry point, and most commands use one of the functions above to determine how to operate.

I think we should execute these functions at launch and make them available to the global context instead of having people individually run these functions.

**Comment by thedavidprice** [comment]
@peterp I'm setting this as a v1 priority but _not_ critical path for v1-rc release. Would you like to prioritize for v1-rc?
