### ISSUE TITLE
Auth: Add Facebook Login with FB JS SDK

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#2804]
@olance started PR https://github.com/redwoodjs/redwood/pull/1406 which is now closed but remains a great starting place to pick this up in the future.

Currently this not a v1 priority. But it would be a welcome addition to Redwood Auth.

Lastly, in the future we will be moving Auth Providers into separate packages outside the main Redwood Framework. If this project resumes, it should be architected as a standalone package, e.g. `redwoodjs-auth-facebook`, which could have first class integration support through the `rw setup auth ...` command.

**Comment by dthyresson** [comment]
FYI Facebook authentication is possible using [Supabase third-party auth](https://supabase.io/docs/guides/auth#third-party-logins).

**Comment by jtoar** [comment]
We don't want anymore auth providers till we've settled on how to decouple auth (which is well underway). We'll also need maintainers for future providers, so I'm going to close this as taking on a new provider is going to be a bit of a commitment that we probably shouldn't solicit anymore.
