### ISSUE TITLE
Expose types from Cell when they're used

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#2811]
We're not currently generating types for when we _use_ Cells. i.e. the Cell input props, which are used to make the graphql query.

**Comment by peterp** [comment]
I shared a way of handling this in the generated mirror cell files:

![image](https://user-images.githubusercontent.com/44849/121772261-99170680-cb74-11eb-948c-8fdc69c4afe1.png)

`InternalProps` would be the Query Data + Query Variables + Props on the Success Component.
`ExteralProps` are `InternalProps` minus the Query Data.

**Comment by dac09** [comment]
Hey Peter see PR :)

**Comment by dac09** [comment]
So after a bit of experimenting, if we don't want a `CellProps` export the cell itself, we can have a template like this:

Bit complicated, but maybe ok for a generated type
```
type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof ${queryResultType} | 'updating'
> & ${queryVariablesType}

export default function (props: CellInputs): ReturnType<SuccessType>
```

However, I need to get the operation name from the gql part of the cell, so I can pass in `queryVariablesType` and `queryResultType` - so there's a dependency on https://github.com/redwoodjs/redwood/pull/2756

**Comment by dac09** [comment]
Alternative 2: Instead of having our own mirrorCell generator, that parses the gql AST, maybe we should have it as a plugin for graphql-codegen (which already parses all the queries anyway).
