### ISSUE TITLE
Private routes not rendering

### ISSUE THREAD

**Issue by darryl-snow** [redwoodjs/redwood#2815]
Adding the `private` attribute to the Set results in these pages being blank - nothing is rendered. Remove the private keyword and they render fine. Same result if I use `<Private>`. No errors in the console or terminal. Same result after clearing local storage and logging in again.

```
<Set private unauthenticated="home" wrap={PrivateLayout}>
  <Route path="/dashboard" page={DashboardPage} name="dashboard" />
  <Route path="/profile" page={ProfilePage} name="profile" />
 </Set>
```

Version: 33.2
Repo: https://github.com/darryl-snow/web-app-boilerplate/tree/main/web/src
Demo: https://web-app-boilerplate.netlify.app

**Comment by Tobbe** [comment]
I tried to reproduce this by cloning your repo. But I can't get it working.
Is there anything I need to do to make it run?

I clone it, `yarn install` it, link it to a Netlify site with identity enabled.
Is there anything else?

Whenever I try to login the API side crashes with this message in my console

![image](https://user-images.githubusercontent.com/30793/121782073-2758b000-cba8-11eb-98f7-a0591976cbe9.png)

**Comment by darryl-snow** [comment]
Strange... it's literally just a brand new out of the box redwood app. The only change I've made is to add materialUI and generate the netlify authentication per the tutorial.

**Comment by Tobbe** [comment]
If I go back to commit 31d6e61 it works.

Actually, seems to be enough to take Routes.js from 31d6e61.

I'll continue investigating tomorrow

**Comment by darryl-snow** [comment]
Yeah in 31d6e61 I just commented out the private Set to leave those routes public and it works. As soon as I make them private they don't render at all. Thanks for your help!

**Comment by Tobbe** [comment]
Yeah, but the problem for me is that I don't even get to the "render" stage at all since my API server crashes before that. And the first front-end <-> back-end interaction that happens is `getCurrentUser`, so that's where I think something goes wrong. Maybe when `<Private>` calls `useAuth` or `hasRole`.

**Comment by Tobbe** [comment]
I don't know why, but for some reason I had to remove your layouts to make it work for me

```jsx
import { Router, Route, Set } from '@redwoodjs/router'

const Routes = () => {
  return (
    <Router>
      <Route path="/" page={HomePage} name="home" />
      <Route notfound page={NotFoundPage} />
      <Set private unauthenticated="home">
        <Route path="/profile" page={ProfilePage} name="profile" />
        <Route path="/dashboard" page={DashboardPage} name="dashboard" />
      </Set>
    </Router>
  )
}

export default Routes
```

With that I could reproduce your issue.

For some reason Redwood gets stuck at loading your auth state.

Do this and go to /dashboard and you see what I mean

```jsx
<Route path="/dashboard" page={DashboardPage} name="dashboard" whileLoading={() => <>Loading...</>} />
```

**Comment by Tobbe** [comment]
Solved it!

Your RW installation is broken. And it's not your fault, it's yarn...

1. Go through all your project.json files and pin the version of RW (`"@redwoodjs/api": "v0.33.2"`, note that it's without the `^`-character)
2. Delete node_modules, web/node_mdules and api/node_modules
3. Delete yarn.lock
4. Reinstall everything: `yarn install`

Things should be working again

**Comment by darryl-snow** [comment]
THANK YOU! So grateful that you spent time looking into this - I was beating my head against the desk for ages. It's always something small in the end. If you ever make it to Singapore then give me a shout - you've earned yourself some drinks!

**Comment by mct-dev** [comment]
Hey, is there a better solution to this?  I'm having the same issue but with a newer version of redwood - 0.35.0

Same exact situation though.  Auth with netlify identity, brand new redwood app.  Private route breaks it, but removing private route fixes it.  ☹️

**Comment by Tobbe** [comment]
@mct-dev sorry no one has gotten back to you. Are you still having this problem? Do you have a git repo I can look at?
