### ISSUE TITLE
`rw exec` exits early when running scripts that spawn other processes  

### ISSUE THREAD

**Issue by viperfx** [redwoodjs/redwood#2843]
I am planning some docs for the cli script, and I was just trying the task worker example with Faktory

I used this specific example when I was developing the CLI script and had this in my redwood app. This used to work in the initial contribution, but something might have changed to make this type of script not work as expected.

```
import { db } from '../api/src/lib/db'
import { logger } from '../api/src/lib/logger'
const faktory = require('faktory-worker')
faktory.register('ResizeImage', async ({ id, size }) => {
  console.log('run ResizeImage')
})
export default async ({ args }) => {
  faktory.work()
}
```

node.js version:
14
npm/yarn version:
1.22.5
faktory-server version:
Faktory 1.5.1
facktory-worker package version:
4.1.4

Per the docs `faktory.work()` "Starts a worker. Doesn't resolve until the worker is shut down. Only call this once per-process."

**Current behavior**
Exits the script straight away and the worker is not run.

**Comment by viperfx** [comment]
I have cross-posted the issue the Faktory worker node repo at https://github.com/jbielick/faktory_worker_node/issues/157

Perhaps @jbielick could give some clues as to why it may not be working as expected.

**Comment by viperfx** [comment]
Ive created a repo to reproduce the issue with steps - https://github.com/viperfx/redwood-faktory-worker

**Comment by viperfx** [comment]
Josh (the author of Faktory) has left a comment suggesting that the problem is likely due to the `process.exit(0)` we are doing. See https://github.com/jbielick/faktory_worker_node/issues/157#issuecomment-866180337

@peterp @dac09 I am going to put a PR that adds a flag to not exit the script to allow for usage with libraries that require this.

**Comment by dac09** [comment]
> The docs mention that await faktory.work() will block until the worker stops, but this is not true anymore. In other words, that comment / documentation is wrong. faktory.work() resolves after the worker starts up successfully. To avoid a memory leak, it does not hold a promise until shutdown.

Looking at his comment here, I don't think that's going to necessarily solve your problem. 

What you want to do is wait till your job is finished, and I guess you can wrap faktory.work somehow

**Comment by jbielick** [comment]
> What you want to do is wait till your job is finished, and I guess you can wrap faktory.work somehow

This is a worker process. It runs continuously until it is stopped, constantly polling the queues for work. I don't think the intention is to start it and stop after completing a job.

It will indeed fix the issue if process.exit(0) were removed because there's no promise to await on, but the node process won't shut down until there are no remaining events on the event loop and no open sockets. The same would be true of a webserver process—it runs until it's stopped because it always holds an open socket. Since `faktory.work()` opens a pool of connections and loops (async) until it's told to stop, the process would continue running. process.exit(0) is what's killing it abruptly right after it starts polling for jobs.

**Comment by dac09** [comment]
I've updated the title to reflect this now, thanks both - I now understand how faktory works, and it makes total sense and is a valid usecase.

We just need to make sure regular scripts still exit OK, and I guess we can remove the `process.exit(0)`. Listr behaviour can sometimes be a little odd!

**Comment by viperfx** [comment]
Ive tested the scripts with Faktory and some simple promises with await/async syntax. 

```
export const sleep = (waitTimeInMs) => new Promise((resolve) => setTimeout(resolve, waitTimeInMs))

export default async ({ args }) => {
  console.log("starting sleep")
  await sleep(10000)
  console.log("ending sleep")
}
```

I can confirm that it does exit when you expect, and in the case of Faktory it says running.

**Comment by viperfx** [comment]
Put up a pr #2881 2881
