### ISSUE TITLE
Scaffold generator does not support Typescript

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#2854]
While the Cell generator supports Typescript, the scaffold templates are still just Javascript.

Would need to:

* Update templates to tsx and use proper types
* Update scaffold command to convert files to TS

**Comment by thedavidprice** [comment]
Hmm, let's figure out what happened (seems like a regression from a merge reconcile) and get it updated. Thanks DT!

**Comment by dthyresson** [comment]
@dac09 and @thedavidprice doesn't https://github.com/redwoodjs/redwood/pull/2967 fix this issue?
