### ISSUE TITLE
Custom auth provider with redirect to Private route after login, redirecting back to unauthenticated route

### ISSUE THREAD

**Issue by benada002** [redwoodjs/redwood#2863]
### Problem
If you have a custom auth provider where the `login`  function redirects to a `Private` route you get redirected to the `unauthenticated` route (`/unauthenticatedRoute?redirectTo=${currentLocation}`).

### Why
This happens because `reauthenticate`, which would set the `loading` state of the `AuthProvider` to `true`, is called after the `login`  function, which navigates to the `Private` route, with a state where `isAuthenticated` is `false` and `loading` is also `false`. Which leads to this unexpected redirection behavior.

### Solution
Set the `loading` state of the `AuthProvider` to `true` before calling `this.rwClient.login(options)`, in the `logIn` function, like:
```javascript
logIn = async (options?: any) = {
    this.setState({ ...this.state, isAuthenticated: true })
    const loginOutput = await this.rwClient.login(options)
    await this.reauthenticate()
    return loginOutput
}
```

I can also create a PR, if you want.

**Comment by dthyresson** [comment]
Thanks @benada002 PR's are absolutely welcome!

@Tobbe do you think this is related in anyway to https://github.com/redwoodjs/redwood/issues/1892 ?

**Comment by Tobbe** [comment]
@benada002 Do you mean `loading` instead of `isAuthenticated` here in your code snippet?
```
this.setState({ ...this.state, isAuthenticated: true })
```

@dthyresson I don't think they're about the same error case.

**Comment by benada002** [comment]
@Tobbe Yes, of course. Sorry about that.

**Comment by Tobbe** [comment]
No need to be sorry :)  I just wanted to make sure I understood correctly. Thanks for digging in to this part of the code, it's not the easiest to wrap your head around 👍

**Comment by thedavidprice** [comment]
> I can also create a PR, if you want.

@benada002 wanted to confirm your interest and availability in opening a PR, correct? This has currently been assigned to you. No pressure, but your help is very welcome.

**Comment by benada002** [comment]
@thedavidprice Yes I'm interested in creating a PR.

Should same also be done for `signUp` and `logOut`, as they are also mutating the auth state?

**Comment by dthyresson** [comment]
> @thedavidprice Yes I'm interested in creating a PR.
> 
> Should same also be done for `signUp` and `logOut`, as they are also mutating the auth state?

Would `logOut` still set `isAuthenticated: true` or `false`?

Probably for signUp too unless there is some additional email confirmation that's needed, but I don't think that is the case in these.

**Comment by thedavidprice** [comment]
> Should same also be done for signUp and logOut, as they are also mutating the auth state?

It would seem so. But if it's not obvious, please do open the PR addressing your solution (above) and loop in @Tobbe for discussion about `signUp`, `logOut`, and/or any other considerations that may come up. It's often easier to discuss and evaluate while working with a PR.

Thanks! Do let us know if you have any questions about contributing. There are docs on the website as well as CONTRIBUTING.md here in the codebase. Most of all, take advantage of the dedicated topics in the Redwood [Forums](https://community.redwoodjs.com) and [Chat](https://discord.gg/jjSYEQd) to get help.

**Comment by benada002** [comment]
I looked at it again and saw that even `reauthenticate` (which is called by `logIn` and `signUp`) doesn't set the `loading` state to true before doing it's thing.
```javascript
  reauthenticate = async () => {
    const notAuthenticatedState: AuthProviderState = {
      isAuthenticated: false,
      currentUser: null,
      userMetadata: null,
      loading: false,
      hasError: false,
    }

    try {
      const userMetadata = await this.rwClient.getUserMetadata()
      if (!userMetadata) {
        this.setState(notAuthenticatedState)
      } else {
        await this.getToken()

        const currentUser = this.props.skipFetchCurrentUser
          ? null
          : await this.getCurrentUser()

        this.setState({
          ...this.state,
          userMetadata,
          currentUser,
          isAuthenticated: true,
          loading: false,
        })
      }
    } catch (e) {
      this.setState({
        ...notAuthenticatedState,
        hasError: true,
        error: e,
      })
    }
  }
```
I think it wouldn't hurt to also set `loading` to true in `signUp` and `logOut` since <Set private> and Private are returning just `null` or `whileLoading`:
```javascript
if (loading) {
  return route.props?.whileLoading?.() || null
}
```
So as long as loading gets set to `false` again it should be fine.

But I'm creating a PR so you can see it.

**Comment by benada002** [comment]
I drafted a PR (https://github.com/redwoodjs/redwood/pull/2872) now where the loading is set to true in logIn.
