### ISSUE TITLE
Go To Definition [of Cell (in VSCode)] takes you to index.d.ts

### ISSUE THREAD

**Issue by ajoslin103** [redwoodjs/redwood#2867]
Go To Definition [of Cell (in VSCode)] takes you to the [mirrored] index.d.ts in the .redwood folder 

I have _no_ idea what to do, other than report this

(same result for Go To Definition, and Go To Type Definition)

lord knows this is not a show-stopper 

more like an oddity

**Comment by thedavidprice** [comment]
@peterp thoughts on this one?

**Comment by jtoar** [comment]
We thought we fixed this in https://github.com/redwoodjs/redwood/pull/2614 (we closed an issue similar to this one: https://github.com/redwoodjs/redwood/issues/669#issuecomment-854544501). Definitely still an issue though, I've reproduced it
