### ISSUE TITLE
`yarn rw test` cannot find `@redwoodjs/testing/configs/api/index.js`

### ISSUE THREAD

**Issue by LBrian** [redwoodjs/redwood#2871]
RR `v.0.34.0`

![Screen Shot 2021-06-22 at 5 59 42 pm](https://user-images.githubusercontent.com/3888780/122886995-c9844f00-d383-11eb-97ed-330de1265be8.png)

I believe this is a side effect from https://github.com/redwoodjs/redwood/commit/784113134316a3bcc6563d5e74d4fc4d36e7509d cc @peterp @thedavidprice

**Comment by LBrian** [comment]
This should be an easy fix, I can create a PR later for this

**Comment by thedavidprice** [comment]
Hi @LBrian Can you confirm you followed the "Code Modifications" section in the [v0.34](https://github.com/redwoodjs/redwood/releases/tag/v0.34.0) release notes. Specifically the jest config files:
```
// api/jest.config.js
 
module.exports = require('@redwoodjs/testing/config/jest/api')

```

In our QA for this release, `yarn rw test` is working successfully. I cannot replicate this error.

Deleting `node_modules` might be necessary. And/or a forced install with `yarn install --force`.

If none of those do the trick, we might need the following to diagnose:
- your system info `yarn rw info`
- code or repo to try and reproduce

**Comment by LBrian** [comment]
My bad, overlooked `jest` config section while quickly reading through change log of `0.34`, problem resolved, thx @thedavidprice
