### ISSUE TITLE
Dockerize api-side

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#2874]
We want to provide a multi phase builds docker image so that we can build the api side, and then discard all the node_modules that are required to build it, so that we're only left with the awesome packages that are needed.

**Comment by thedavidprice** [comment]
To Discuss: contexts for using Docker
1. local development
2. deployment

Do we need to support both?

**Comment by pi0neerpat** [comment]
Hi folks, I've got a working Docker build Github Action, thanks to lots of help from @jeliasson 

https://gist.github.com/pi0neerpat/711ed1027eeb66735e457fa930cd707b

One thing to add is the need to **separate `prisma migrate` from the build process**. Instead we should run it immediately before the image is deployed. Otherwise, there is a gap in time where the database and deployed image will be mismatched

Another reason we should separate it is for security, so we aren't including DATABASE_URL in the image itself.

**Comment by jeliasson** [comment]
Good initiative!

> We want to provide a multi phase builds docker image so that we can build the api side, and then discard all the node_modules that are required to build it, so that we're only left with the awesome packages that are needed.

@peterp What would be the best way to figure out which packages that would be required at runtime? It is not as easy as `yarn install` vs `yarn install --production` yet, right? 😅

> To Discuss: contexts for using Docker
>     1. local development
>     2. deployment
> Do we need to support both?

@thedavidprice In the context of having a multi phase build and discard the required build packages for a slim runtime image, I think it would focus on deployment.

> One thing to add is the need to **separate `prisma migrate` from the build process**. Instead we should run it immediately before the image is deployed. Otherwise, there is a gap in time where the database and deployed image will be mismatched

@pi0neerpat Agreed. A way could be to utilize dockers `command` argument to pass e.g. `yarn rw deploy docker --migrate` (or `--migrate-seed`) to do migrate and seeding before running `ENTRYPOINT`.

> Another reason we should separate it is for security, so we aren't including DATABASE_URL in the image itself.

:100:

I have written a [forum post](https://community.redwoodjs.com/t/self-hosting-redwoodjs-on-kubernetes/2236#apidockerfile-4) that uses multi phase build for the web package, but having a slim one for api would be great!

**Comment by peterp** [comment]
@jeliasson Here are the packages required for build:

```
```

**Comment by peterp** [comment]
There are other ways that we can handle this as well. We could potential use esbuild to create a bundle, or zip it and ship it.

**Comment by ajcwebdev** [comment]
Something we'll want to discuss at a certain point as well is using Docker for production versus just using it for development. Looks like they've got a new feature out that could help out with dev:

https://www.docker.com/blog/tech-preview-docker-dev-environments/

**Comment by Josh-Walker-GM** [comment]
@jtoar - I'll close this one now you merged in #9024 but feel free to reopen if you think it hasn't been solved. With our (exp.) docker setup command we now have a recommended way to dockerise the API side.
