### ISSUE TITLE
VSCode doesn't suggest imports for `<Private>`

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#2897]
![image](https://user-images.githubusercontent.com/30793/123513767-3bfc7400-d68f-11eb-94a9-1533905479e2.png)

When I try to use `<Private>` in my Routes.tsx file VSCode should know to suggest that it can be imported from `@redwoodjs/router`

![image](https://user-images.githubusercontent.com/30793/123513929-38b5b800-d690-11eb-9f54-5ef7dbe4fd85.png)

\#typescript

**Comment by Tobbe** [comment]
Actually it does work if I first accept the suggestion to import React

![image](https://user-images.githubusercontent.com/30793/123514012-a530b700-d690-11eb-8794-15fd5a17b805.png)

Why do I need to do that?

**Comment by mcmx** [comment]
I know this is an old issue, but it works for me, I believe this can be closed.

Can someone else confirm?

**Comment by Tobbe** [comment]
> I know this is an old issue, but it works for me, I believe this can be closed.
> 
> Can someone else confirm?

Are you in a TS project? Strict mode on or off?

**Comment by mcmx** [comment]
Yes, it is a TS project, strict was off, I add it to `web/tsconfig.json` and set it to **true**, still VSCode suggests Private from `@redwood/router`

Also created a new project, added `strict` and `alwaysStrict`, opened VSCode and still suggests Private from `@redwood/router`

Is this the correct way to enable strict and test this?

**Comment by Tobbe** [comment]
> Is this the correct way to enable strict and test this?

You've done it the correct way 👍 

And I can confirm that it works! Thanks @mcmx
