### ISSUE TITLE
RFC - Logger - Should production logging default to a lower level, like debug?

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#2901]
As per docs:

>The logger detects you current environment and will default an appropriate minimum log level.

> In Development, the default is trace while in Production, the default is warn.

> This means that output in your dev server can be verbose, but when you deploy you won't miss out on critical issues.

* Should production be debug?
* Docs need to make this config clearer with a callout

**Comment by thedavidprice** [comment]
Will be fixed by redwoodjs/redwoodjs.com#736
