### ISSUE TITLE
rw typeCheck or rw typecheck

### ISSUE THREAD

**Issue by simoncrypta** [redwoodjs/redwood#2904]
In the [doc](https://redwoodjs.com/docs/typescript#running-type-checks) they said to use `yarn rw typecheck`,
but in reality, the command is `yarn rw typeCheck` #2812 

So should we update the doc, update the command or create an alias for typecheck ?

I think is more conventional to use lowercase or kebab-case than camelCase for CLI

**Comment by peterp** [comment]
@simoncrypta I think we should change the command, it should either be `typecheck` or `type-check`

**Comment by simoncrypta** [comment]
> @simoncrypta I think we should change the command, it should either be `typecheck` or `type-check`

I have a preference for `typecheck`, one character less and still readable 

I can open a PR right now and change it later if we go for `type-check`

**Comment by simoncrypta** [comment]
Also it's already have alias for `tsc`, `tc` and `type-check`
