### ISSUE TITLE
Naming standard for CLI options

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#2978]
We should standardize naming for CLI options prior to v1-rc.

---

_Originally posted by @dac09 in https://github.com/redwoodjs/redwood/issues/2906#issuecomment-870421486_

> Just a headsup - we now have two patterns - dataMigrate (camel cased) and typecheck. Might be an idea to add an alias to typecheck to support `typeCheck` and an alias to dataMigrate to support `datamigrate`

_Originally posted by @thedavidprice in https://github.com/redwoodjs/redwood/issues/2906#issuecomment-875157924_

> Actually, we have three patterns:
> 1. lower case one-word `datamigrate`
> 2. camel case `dataMigrate
> 3. lower case hyphen two-word `data-migrate` (in case of ts-to-js)
> 
> Personally, I prefer option 3 combined with an alias rule to use the first letter of each word, e.g. `data-migrate` aliased `dm`.
> 
> Regardless, let's do pick one way and stick with it.

**Comment by dac09** [comment]
Thanks for creating this DP! I'll pick this up tomorrow so that we're not introducing a breaking change `rw typeCheck` or `rw type-check` -> `rw typecheck` in the next release.

**Comment by thedavidprice** [comment]
@dac09 Sound great, but I'm also fine with breaking. I just think we should standardize between `dataMigrate`, `typecheck`, and `ts-to-js`. My preference would be:
- `data-migrate` alias `dm`
- `type-check` alias `tc`
- `ts-to-js` alias `tj`

But definitely open to discussion.

**Comment by simoncrypta** [comment]
I think kebab-case (lower case hyphen two-word) make sense in CLI when the command have more than 1 word. I really like the alias with 1 or 2 letters, but we will probably have a collision at some time with 2 commands. What should we do at this case ? Pick the most use for the alias and don't make alias for the other ?

**Comment by dac09** [comment]
Hey all, just wanted to point out that a lot of the cases are automatically handled by yargs, but we must follow yarg's rules.

If you name it `type-check`, it automatically supports `tc`, `typeCheck`.
If you name it 'typecheck', it only supports 'typecheck' automatically
 

> lower case one-word datamigrate
@thedavidprice this isn't a pattern that's currently supported :), just checked.

**Comment by thedavidprice** [comment]
@dac09 My guess is that you're thinking about how Yargs handles the objects (maybe...?)

> @thedavidprice this isn't a pattern that's currently supported :), just checked.

Correct. I am meaning to suggest it's a rule/standard we use.

**Comment by dac09** [comment]
Ah, understood - words are confusing sometimes 🤣. PR ready for you though!
