### ISSUE TITLE
Expose `PrismaClient` constructor

### ISSUE THREAD

**Issue by nikolasburk** [redwoodjs/redwood#298]
Currently it's not possible to instantiate `PrismaClient` with custom options which is why sometimes (ugly) [hacks](https://github.com/lachlanjc/covid19/blob/master/redwood-hack/api-dbInstance.js) are necessary to do so when it's need. 

Exposing the constructor can also be helpful for [logging](https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/api.md#logging), e.g. for monitoring the generated DB queries.

**Comment by thedavidprice** [comment]
Oh man, @cannikin would probably ❤️ implementing this! 

😉

**Comment by cannikin** [comment]
This is actually done! Just need to test before merging: https://github.com/redwoodjs/redwood/pull/289

**Comment by peterp** [comment]
It's merged!
