### ISSUE TITLE
Bug: Can't create CRUD version of service with Float Prisma field type

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#2980]
If a model in your prisma schema contains a Float field type, the code that turns the scenario data into a test throws an error. Basically https://github.com/redwoodjs/redwood/issues/2859, just for Floats.

Example model:

```prisma
model Entry {
  id           Int      @id @default(autoincrement())
  purchaseName String
  date         DateTime @default(now())
  description  String
  amount       Float
  category     String
}

```

**Comment by dthyresson** [comment]
FYI - There are many flavors of floats.

See https://github.com/Urigo/graphql-scalars/tree/master/src/scalars

`NonNegativeFloat` `PositiveFloat` etc.

Floats are tricky datatypes.

See Prisma https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#float

> Float maps to Double in 2.17.0 and later - see release notes and Video: Changes to the default mapping of Float in Prisma 2.17.0 for more information about this change.

hence, why the SDL can be a Decimal, I think.

Also, there is some SDL and Prisma mapping done:

https://github.com/redwoodjs/redwood/blob/a4bcec0b4843f1a1eb542a4bd43c77ee3e30f51e/packages/cli/src/commands/generate/sdl/sdl.js#L55

**Comment by dthyresson** [comment]
Actually, I realized that Float is a standard GraphQL scalar type.

Also reported in https://github.com/redwoodjs/redwood/issues/3214

Fixed in https://github.com/redwoodjs/redwood/pull/3218
