### ISSUE TITLE
"Something went wrong" broken pages during db schema creation

### ISSUE THREAD

**Issue by danspratling** [redwoodjs/redwood#300]
After following the tutorial exactly, the user is unable to proceed past the database creation step.

To reproduce:
1. Follow the tutorial up to the end of the 'Layouts' section - everything works as expected
2. Complete the 'Getting Dynamic' section
3. Navigate to localhost:8910 - you'll see the 'Something went wrong' page. Every page created so far looks this way, including 404 pages. (this was not the case before running the db commands).
4. Navigate to localhost:8910/posts - this page looks as expected
5. Navigate to localhost:8910/posts/new - another 'Something went wrong' page
6. The user is now unable to proceed with the tutorial
<img width="706" alt="Screenshot 2020-03-19 at 12 42 18" src="https://user-images.githubusercontent.com/11349104/77068892-500eeb80-69df-11ea-966b-a95ebe1e18ec.png">

**Comment by cannikin** [comment]
Is this in Firefox by any chance? We have a router regex issue that we're working on in Firefox: #205

**Comment by danspratling** [comment]
Yes. Yes, it is. So it's my browser? I didn't think to test that out. So the current solution for this (till the bug is fixed) is to work in chrome?
