### ISSUE TITLE
Add current CLI commands to `packages/cli/README.md`

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#301]
The doc does not include the commands (with options) available along with a brief description for each. See: 
https://github.com/redwoodjs/redwood/blob/master/packages/cli/README.md

- Also needs to include info that we use [Yargs](https://github.com/yargs/yargs) for the CLI.
- Should mention `—help` flag.

Running `yarn rw —help` outputs this list:
```
Commands:
  rw build [app..]    Build for production.
  rw db <command>     Database tools.                        [aliases: database]
  rw dev [app..]      Run development servers.
  rw generate <type>  Save time by generating boilerplate code.     [aliases: g]
  rw lint             Lint your files.
  rw open [port]      Open your project in your browser.
  rw test [app..]     Run Jest tests for api and web.
```

And here’s the cli/ package directory with all commands:
https://github.com/redwoodjs/redwood/tree/master/packages/cli/src/commands

**Comment by AryanJ-NYC** [comment]
Feel free to assign me! I'm super down. I _kinda_ wanted to do this in the scope of #285 but figured I'd keep PRs small.

Thanks!

**Comment by thedavidprice** [comment]
Boom. Take ‘er away!!

**Comment by thedavidprice** [comment]
And, to be clear, there’s probably a lot of reconciling/cleanup to do as you sort through things. Don’t hesistate at all to ask questions as they come up.

**Comment by thedavidprice** [comment]
Closing this. Has effectively moved to #322
