### ISSUE TITLE
RFC: Telemetry—gathering Redwood CLI usage statistics

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#3012]
We're going to try and get a quick telemetry implementation into the code in time for 1.0. We're hoping this help inform some general direction decisions for 2.0 and other projects.

Telemetry will be opt-out and completely anonymous—nothing that could potentially identify an individual person or machine will be included.

Here's what Next.js collects for their telemetry: https://nextjs.org/telemetry

Here's what we're currently thinking of capturing, but feel free to make recommendations!

**Command Invocation**

* `yarn create redwood-app` 
* `yarn rw [args]`

**Data collected from each command**

* The command that was run, ex. `yarn rw g cell` (will definitely NOT include environment variables)
* Most info from `yarn rw info`:
  ```
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 
      Yarn: 1.22.10 
    Databases:
      SQLite: 3.32.3 
    Browsers:
      Chrome: 91.0.4472.114
      Firefox: 67.0.4
      Safari: 14.1.1
    npmPackages:
      @redwoodjs/core: ^0.34.0 => 0.34.1
  ```
* Whether the command was run by a CI (look for `IS_CI` env var)
* Number of routes

**Command-Specific Data**

* How long it took for the dev server to start
* How long it took for a build to complete

**Opting Out**

Setting an environment variable `REDWOOD_TELEMETRY_DISABLED=1` or `DO_NOT_TRACK=1` will stop all telemetry being sent.

**Comment by peterp** [comment]
Maybe we can follow the recommendation of this article and also adhere to "DO_NOT_TRACK=1": https://consoledonottrack.com/

**Comment by realStandal** [comment]
Would it not be possible to have it ask the developer when running `yarn create redwood-app` to opt-in to telemetry? This is how I've encountered it on every tool that's, at least, been upfront about collecting data. It also seems there's no way to opt-out of that initial, `create app` "phone-home".

> We're hoping this help inform some general direction decisions for 2.0 and other projects.

What are "other projects"? Open source? Proprietary? _Whose_ projects, I suppose is a better question.

Hope this isn't taken negatively, but then again, I'm fairly negatively-minded on these sorts of things; just the opinions and concerns of one person.

**Comment by peterp** [comment]
> Would it not be possible to have it ask the developer when running yarn create redwood-app to opt-in to telemetry

This is a RFC (request for comment) and we're discussing what we're going to implement, so your suggestions are super helpful. I think asking for it to be "opt-in" is a good suggestion!

**Comment by peterp** [comment]
> Hope this isn't taken negatively, but then again, I'm fairly negatively-minded on these sorts of things; just the opinions and concerns of one person.

Which is fair stance to take, but IMHO the 👎  you left in the parent post was a bit harsh, and made me read your initial comment negatively, before I read the last paragraph!

**Comment by simoncrypta** [comment]
Telemetry gives good valuable data for the future of this project. I think that if we kindly ask for when `yarn create redwood-app` is executing, most of us will say yes if we are confident that the data is anonymous and use for good reason. If we say no, that simply write `DO_NOT_TRACK=1`, so is like an opt-out but with an opt-in at the beginning of a new project.

**Comment by ajcwebdev** [comment]
For the sake of comparison here's how I've seen some other projects handle this:

## Nuxt.js

A message displays the first time you start your dev server that allows you to opt in or not.

```
NuxtJS collects completely anonymous data about usage.
This will help us improve Nuxt developer experience over time.
Read more on https://git.io/nuxt-telemetry

? Are you interested in participating? (Y/n) 
```

In addition to giving you the option to opt out through the CLI, they also provide [three options for configuring your project to opt out](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-telemetry#opting-out).

### Using `npx nuxt telemetry disable`

```bash
npx nuxt telemetry [status|enable|disable] [-g,--global] [dir]
```

### Using an environment variable

```bash
NUXT_TELEMETRY_DISABLED=1
```

### Setting `telemetry: false` in your `nuxt.config.js`:

```javascript
export default {
  telemetry: false
}
```

## AWS SAM

A message displays the first time you initialize a project telling you how to turn off telemetry but does not let you opt out through the CLI.

```
SAM CLI now collects telemetry to better understand customer needs.
You can OPT OUT and disable telemetry collection by setting
the environment variable SAM_CLI_TELEMETRY=0 in your shell.

Thanks for your help!
Learn More:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html
```

Their docs provide instructions for opting out [for a single session or for your profile in all sessions](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html).

### Disabling telemetry for a session

> In macOS and Linux operating systems, you can disable telemetry for a single session. To disable telemetry for your current session, run the following command to set the environment variable SAM_CLI_TELEMETRY to false. You must repeat the command for each new terminal or session.

```bash
export SAM_CLI_TELEMETRY=0
```

### Disabling telemetry for your profile in all sessions

To disable telemetry in Linux

```bash
echo "export SAM_CLI_TELEMETRY=0" >>~/.profile
source ~/.profile
```

To disable telemetry in macOS

```bash
echo "export SAM_CLI_TELEMETRY=0" >>~/.profile
source ~/.profile
```

To disable telemetry in Windows

```bash
setx SAM_CLI_TELEMETRY 0
refreshenv
```

**Comment by realStandal** [comment]
> > Hope this isn't taken negatively, but then again, I'm fairly negatively-minded on these sorts of things; just the opinions and concerns of one person.
> 
> Which is fair stance to take, but IMHO the 👎 you've left in the parent post was a bit harsh, and made me read your initial comment negatively, before I read the last paragraph!

Sorry you took it that way @peterp, glad the paragraph worked, though; I'll retract it seeing as our discussion defeats my purpose putting it there lol

Simon's thoughts sums up my opinions. I agree the benefits to framework are clear and worthwhile, and just wanted to push up what wavered my confidence in something like this.

**Comment by thedavidprice** [comment]
I appreciate the discussion that is happening here; especially the back and forth willingness to understand each other's point of view regarding a topic that (rightfully) stirs debate. 

Redwood team, I think we began implementation before setting the appropriated context with community, along with also inviting community discussion for both concerns _and_ collaboration. 

I suggest:
- We mark this PR as a draft
- We open a discussion on the Forums, focused more on the why and what. We can time-bound discussion as needed (a week or two?)
- Based on discussion we can have a virtual community meeting for discussion if needed 

The goal of any analytics is to enable us to build Redwood even better. 

This is also an opportunity to create and strengthen _trust_, which is what continues to make Redwood great. 

---

As always, these suggestions are open to any/all feedback and pushback. So what say you all?

**Comment by cannikin** [comment]
@thedavidprice What do we want to do about this re: v1.0? We haven't had any movement in more than a month now. Should we put on the docket for the next core meeting to discuss?

**Comment by thedavidprice** [comment]
> Should we put on the docket for the next core meeting to discuss?

Yes! Was on the list but no time today. On the v1 Roadmap, I currently put it as a priority _after_ the initial v1-rc is out — meaning fine to do during the RC cycle as it's not breaking. But TBD

Thanks for the ping!
