### ISSUE TITLE
Tutorial: specify use of src directory within web directory

### ISSUE THREAD

**Issue by roquesf** [redwoodjs/redwood#302]
In tutorial, specify that folders `components`, `layouts`, `pages` are within `src` folder which is within `web` folder. Currently specifying that these folders are directly within `web` folder. Plus a quick description of  `web/src` folder would be needed.

Direct link to section where update needed:
https://redwoodjs.com/tutorial/redwood-file-structure#the-web-directory

Screenshot of current folder tree as in tutorial
![Directories tree](https://user-images.githubusercontent.com/300/76236828-7f0cac80-61ea-11ea-9007-40766d088c4e.png)

**Comment by cannikin** [comment]
Great catch, we'll clean that up!

**Comment by cannikin** [comment]
I moved this issue to the repo with the tutorial, you can track progress there: https://github.com/redwoodjs/redwoodjs.com/issues/52
