### ISSUE TITLE
Type issue with redactionsList and redactOptions deconstruction in Logger

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#3022]
See:

![image](https://user-images.githubusercontent.com/1051633/125017805-dd95a500-e041-11eb-9b36-efc3f1c742a0.png)

```
Type 'string[] | redactOptions' must have a '[Symbol.iterator]()' method that returns an iterator.ts(2488)
```

Also, logger could be improved such that one does not need to import the standard redaction list  -- it simply appends -- or make it clear that setting will overwrite it.

**Comment by jtoar** [comment]
It's the `redactOptions` from pino that needs a `[Symbol.iterator]()` method right? I'd think it'd be ok to spread something typed `string[]`

**Comment by jtoar** [comment]
> Also, logger could be improved such that one does not need to import the standard redaction list -- it simply appends -- or make it clear that setting will overwrite it.

And this sounds nice!

**Comment by dthyresson** [comment]
> It's the `redactOptions` from pino that needs a `[Symbol.iterator]()` method right? I'd think it'd be ok to spread something typed `string[]`

Right, the issue is that the redact options are `string[] | redactOptions` and can spread the array of string, but not `redactOptions` and that is

```js
    interface redactOptions {
        paths: string[];
        censor?: string | ((v: any) => any) | undefined;
        remove?: boolean | undefined;
    }
```

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b502fdf090447303e3e214d8b6d56f043fe55ada/types/pino/index.d.ts#L777

Actually, perhaps

```js
export const redactionsList: string[] | redactOptions = [
  'access_token',
  'accessToken',
  'DATABASE_URL',
  'email',
  'event.headers.authorization',
  'host',
  'jwt',
  'JWT',
  'password',
  'params',
  'secret',
]
```

should just be `string[]`.

**Comment by dthyresson** [comment]
Awaiting fixes for https://github.com/prisma/prisma/issues/8291 and https://github.com/prisma/prisma/blob/d06e6097a7d0fc4d66d9a7bd86992cd4d28b1f3f/src/packages/client/src/generation/TSClient/PrismaClient.ts as encountering these type issues when building with a fix.
