### ISSUE TITLE
TS error in default auth.ts

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#3024]
Reproduce:
1. `yarn build:test-project`
2. `cd blog-test-project`
3. `yarn rw setup auth netlify`

Now, in `/api/src/lib/auth.ts` I get this

![image](https://user-images.githubusercontent.com/30793/125053521-7f9aa900-e0a5-11eb-9f3e-dafaf65f56d0.png)

**Comment by dthyresson** [comment]
@Tobbe I was working on this file last night in the setup in https://github.com/redwoodjs/redwood/pull/3006 and was thinking that this file needs to be Typescript and how typing would help clarify and type for role - string or array of strings.

Essentially, this auth file should be ts.
