### ISSUE TITLE
Default auth.[jt]s is not formatted correctly

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#3025]
Reproduce:
1. `yarn build:test-project`
2. `cd blog-test-project`
3. `yarn rw setup auth netlify`
4. Go to `/api/src/lib/auth.ts`
5. Format the file (Alt+Shift+F for me)

This is the diff I get:
```diff
diff --git a/api/src/lib/auth.ts b/api/src/lib/auth.ts
index deffa2e..0f186e9 100644
--- a/api/src/lib/auth.ts
+++ b/api/src/lib/auth.ts
@@ -1,4 +1,3 @@
-
 import { AuthenticationError, ForbiddenError, parseJWT } from '@redwoodjs/api'

 /**
@@ -13,7 +12,11 @@ import { AuthenticationError, ForbiddenError, parseJWT } from '@redwoodjs/api'
  *
  * @see https://github.com/redwoodjs/redwood/tree/main/packages/auth for examples
  */
-export const getCurrentUser = async (decoded, { _token, _type }, { _event, _context }) => {
+export const getCurrentUser = async (
+  decoded,
+  { _token, _type },
+  { _event, _context }
+) => {
   return { ...decoded, roles: parseJWT({ decoded }).roles }
 }
```

Minor thing for sure, but I think our generated files should be formatted the way our prettier.js setup wants them.

**Comment by jtoar** [comment]
> Minor thing for sure, but I think our generated files should be formatted the way our prettier.js setup wants them.

Definitely. Feels like a must from a DX perspective. Also discussed here in https://github.com/redwoodjs/redwood/issues/1551

**Comment by dthyresson** [comment]
@Tobbe I think I may have sorted the formatting out here: https://github.com/redwoodjs/redwood/pull/3006:

```
-export const getCurrentUser = async (decoded, { _token, _type }, { _event, _context }) => {

+export const getCurrentUser = async (
  decoded,
  { _token, _type },
  { _event, _context }
) => {
  return { ...decoded, roles: parseJWT({ decoded }).roles }
}```
