### ISSUE TITLE
useMutation refetchQueries alternative format - without variables

### ISSUE THREAD

**Issue by cjreimer** [redwoodjs/redwood#3030]
The useMutation refetchQueries option is typed and works appropriately for a query such as the following:

```
  const [updateRequirement] = useMutation(UPDATE_REQUIREMENT_MUTATION, {
    onCompleted: () => {
      toast.success('Requirement updated')
    },
    refetchQueries: [{ query: QUERY, variables: { projectId } }],
  })
```

The challenge is that in some places in the code, we do not have all the variables of the query handy, and need to prop-drill them down if we want to run the same query.  Apollo conveniently provides a second option as discussed here
https://www.apollographql.com/docs/react/data/mutations/#making-all-other-cache-updates
and
https://stackoverflow.com/questions/55638965/use-existing-variables-when-using-refetchqueries-in-react-apollo

with this format:

```
import { getOperationName } from 'apollo-link'
  const [updateRequirement] = useMutation(UPDATE_REQUIREMENT_MUTATION, {
    onCompleted: () => {
      toast.success('Requirement updated')
    },
    refetchQueries: [getOperationName(QUERY)],
  })

```

I've tested, and the refetchQuery runs fine, utilizing the previously executed variables, rather than explicitly requiring variables. 
 However, this breaks the typing in redwoodjs and causes a typescript error.

Would there be any concerns with adding this second type of refetchQuery into the redwoodjs types?

**Comment by jtoar** [comment]
@cjreimer great write up; very easy to follow!

> Would there be any concerns with adding this second type of refetchQuery into the redwoodjs types?

I don't think there's any concerns. But I'll get someone who knows more about TS than I do in here to confirm; @dac09 what do you think?

**Comment by dac09** [comment]
No objection from me at all! I think we should expose all the available types on useMutation and useQuery!
