### ISSUE TITLE
Layout generator props type is too strict

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3035]
e.g. When running 
```
yarn rw g layout Test
```

it will generate the type

```ts
type TestLayoutProps = {
  children: React.ReactNode
}
```

Which creates an error in TestLayout.test.tsx, because children is a required param. 

### What should it do?
`children` should be optional

**Comment by jtoar** [comment]
@dac09 should we just change the test to include a child instead? 

Trying to think of cases where a layout wouldn't have any children—maybe it would be if you had more specific slots for children, to render them in multiple, different places

**Comment by dac09** [comment]
I actually have a Layout which I reuse as a `whilePageLoading` loader with additional props! 

I think in most cases yes - layouts should have children, but I think it's also accurate to say they don't _need_ to have children.

**Comment by Albert-Gao** [comment]
I was fixing it like this:

<img width="177" alt="image" src="https://user-images.githubusercontent.com/18282328/126065004-4350a93f-424e-4b63-bbf0-fe16a7db3f7a.png">

It does not matter as this test will be replaced later, but we should avoid the type error here

But then what about just making that `children` prop as optional, maybe there are cases which it would happen after a conditional rendering? Normally, yes, it should come with a children.

I think let's just make it a optional? Happy to submit a PR for this.

**Comment by dac09** [comment]
Yeah absolutely @Albert-Gao tag me on it after you raise the PR :)

@jtoar okay with you? Happy to discuss further if required.

**Comment by Albert-Gao** [comment]
Summited @dac09
