### ISSUE TITLE
Create Redwood equivalent of `prisma2 migrate fix` command

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#304]
After running migrations prisma creates a `migrate.lock` file which tracks which migrations have been run against the database. In some circumstances there could be a conflict in that file (multiple devs creating migrations). Prisma provides a command `prisma2 migrate fix` to fix it. We should create our own version of that, maybe something like:

* `yarn rw db fix`
* `yarn rw db migrate-fix`
* `yarn rw db up:fix`

**Comment by peterp** [comment]
It does not look like Prisma is going to add this feature anymore.
