### ISSUE TITLE
Error while deploying web side with prerender through Serverles

### ISSUE THREAD

**Issue by panchopoliti** [redwoodjs/redwood#3042]
Hey everyone! I am trying to prerender the DashboardPage of my app. When I run `yarn rw build web` locally in my project, everything works successfully. 

But when I am trying to deploy it through serverless CLI, I get this error
```
/Users/franciscopoliti/ProgrammingProjects/WA/wildmetrics/node_modules/@redwoodjs/web/dist/components/createCell.js:3
import { createCell } from "@redwoodjs/web";
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1172:16)
    at Module._compile (internal/modules/cjs/loader.js:1220:27)
    at Module._compile (/Users/franciscopoliti/ProgrammingProjects/WA/wildmetrics/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Object.newLoader [as .js] (/Users/franciscopoliti/ProgrammingProjects/WA/wildmetrics/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/franciscopoliti/ProgrammingProjects/WA/wildmetrics/node_modules/@redwoodjs/web/dist/index.js:105:19)

Prerendering /dashboard -> web/dist/dashboard.html [failed]
```
I am using this plugin (https://github.com/tgfischer/serverless-build-client) to deploy the client with environment variables 

When I deploy with the command `yarn rw build web --no-prerender`, everything works perfectly. But running `yarn rw build web` throws the error described above.

The runtime defined in serverless.yml:  nodejs14.x

Thanks so much for the help!

**Comment by peterp** [comment]
Hey @dac09, I was chatting with Pancho earlier, have you ever come across something like this?

**Comment by dac09** [comment]
Afraid not :/ But clearly it seems the babel config isn't being picked up in prerender.

@panchopoliti would you please confirm that you see the error if you build using the command `yarn rw build web --no-prerender && yarn rw prerender` ?

Thanks!

**Comment by peterp** [comment]
Could the `cwd` have something to do with it? Like if they're in `./web` instead of the root?

**Comment by dac09** [comment]
> Could the cwd have something to do with it? Like if they're in ./web instead of the root?
I just verified this - you are indeed correct 💯! I'll see if I can find a fix for it, probably the "ignore" key in the babelRequireHook

**Comment by dac09** [comment]
@panchopoliti the temporary work around maybe to make sure you're running the build command from the root of your project, and not from the web directory.

I'll get a fix in for this soon :)

**Comment by panchopoliti** [comment]
Exactly it is like this @dac09 🙁. Adding `cwd: ../` as a param in my serverless.yml works perfectly and I can deploy 💪 

Thanks so much for the help @dac09 and @peterp 😄

**Comment by dthyresson** [comment]
I heard from  @panchopoliti in Discord the issue was solved. Even though my runtime in serverless.yml was defined as 14.x, the settings of the lambda were in 10.x.

Can we close out the issue? Thanks!

**Comment by dac09** [comment]
> Can we close out the issue? Thanks!
not the same issue DT!

**Comment by dthyresson** [comment]
> not the same issue DT!

Ah, you are of course right. Apologies. Deleting the comment.
