### ISSUE TITLE
Framework Build - Typescript Error

### ISSUE THREAD

**Issue by cjreimer** [redwoodjs/redwood#3053]
Hello,

I'm having trouble building the framework as soon as I touch a typescript file.  I've tried touching files in both the internal and web packages and get the same issue.  The error I get is:

```
[9:18:22 a.m.] Project '../../packages/web/tsconfig.json' is out of date because oldest output '../../packages/web/dist/config.d.ts' is older than newest input '../../packages/web/src/components/GraphQLHooksProvider.tsx'

[9:18:22 a.m.] Building project 'D:/dev/redwoodjs/redwood/packages/web/tsconfig.json'...

D:\dev\redwoodjs\redwood\tasks\framework-tools\node_modules\typescript\lib\typescript.js:2479
            throw e;
            ^

Error: Debug Failure. False expression: File extension for signature expected to be dts
Verbose Debug Information: Found: .map for D:/dev/redwoodjs/redwood/packages/web/dist/components/GraphQLHooksProvider.d.ts.map:: All output files: ["D:/dev/redwoodjs/redwood/packages/web/dist/components/GraphQLHooksProvider.d.ts.map","D:/dev/redwoodjs/redwood/packages/web/dist/components/GraphQLHooksProvider.d.ts"]
    at updateShapeSignature (D:\dev\redwoodjs\redwood\tasks\framework-tools\node_modules\typescript\lib\typescript.js:112521:30)      
    at Object.getFilesAffectedBy (D:\dev\redwoodjs\redwood\tasks\framework-tools\node_modules\typescript\lib\typescript.js:112475:18) 
    at getNextAffectedFile (D:\dev\redwoodjs\redwood\tasks\framework-tools\node_modules\typescript\lib\typescript.js:112948:51)       
    at getSemanticDiagnosticsOfNextAffectedFile (D:\dev\redwoodjs\redwood\tasks\framework-tools\node_modules\typescript\lib\typescript.js:113578:32)
    at Object.getSemanticDiagnostics (D:\dev\redwoodjs\redwood\tasks\framework-tools\node_modules\typescript\lib\typescript.js:113623:20)
    at getSemanticDiagnostics (D:\dev\redwoodjs\redwood\tasks\framework-tools\node_modules\typescript\lib\typescript.js:116921:62)    
    at executeSteps (D:\dev\redwoodjs\redwood\tasks\framework-tools\node_modules\typescript\lib\typescript.js:117064:25)
    at Object.done (D:\dev\redwoodjs\redwood\tasks\framework-tools\node_modules\typescript\lib\typescript.js:116867:13)
    at build (D:\dev\redwoodjs\redwood\tasks\framework-tools\node_modules\typescript\lib\typescript.js:117536:32)
    at Object.build (D:\dev\redwoodjs\redwood\tasks\framework-tools\node_modules\typescript\lib\typescript.js:117718:101)
error Command failed with exit code 1.

```

Thinking my framework was corrupted, I've tried blowing away the framework and recloning.  The framework builds from a fresh install, but the build fails as soon as I touch a typescript file.

Note, I am on Windows.

**Comment by Tobbe** [comment]
I had a quick chat to @cjreimer about this on Discord. I'm running into this issue as well on Windows. But it doesn't seem to happen as often to me as it does him.

What works for me is to run `yarn build:clean && yarn build`. After that I can use `yarn rwfw project:sync` in my test rw app to test my changes.

**Comment by Tobbe** [comment]
Not sure if this is relevant, but dropping it here for someone with a better understanding to take a look. The error message is very similar.

https://github.com/cevek/ttypescript/issues/121

**Comment by simoncrypta** [comment]
> What works for me is to run yarn build:clean && yarn build. 
It didn't work for me, so I tried something a little more radical, and it's work for me :
Delete the repo and re clone. 

It's think the problem come from an old typescript definition inside something with .gitinore.

**Comment by cjreimer** [comment]
**Update:**
OK, thanks to help from @Tobbe, I can now build using the following commands in sequence:

```
yarn build:clean
yarn build
```

I believe I need to run the `yarn build:clean` every time I change a type ... but haven't fully validated that.

I have also played with the following:
```
Modified \redwood\tasks\framework-tools\package.json
  Added    "ts-patch": "1.4.1",
  Modified     "build:watch": "lerna run build:watch --parallel; tsp --build",
```
but with mixed success.  It might just be a fluke that it worked in some cases.
A v2 of ts-patch is being worked on and might provide some additional options.

**Comment by Tobbe** [comment]
@cannikin had this happen to him as well, so not a Windows (only) issue

**Comment by peterp** [comment]
I'm wondering if the `--parallel` flag on the build command is causing issues. Perhaps the initial build should use the framework level `build:js` script, and then use the top-level framework `build:types` command.

In order to test:

https://github.com/redwoodjs/redwood/blob/ecf8aa983a2ead57593e201e922ee589ecf5e19f/tasks/framework-tools/src/lib/framework.mjs#L145-L153

Modify this to run `build:js`, and then afterwards add:
 ```
  execa.sync(
    'yarn build:types',
    {
      shell: true,
      stdio: 'inherit',
      cwd: path.resolve(__dirname, '../../'),
    }
  )
```

**Comment by amorriscode** [comment]
I was trying to help @alicelovescake debug her local build and we are both experiencing the same issue (both on Mac).

@peterp I may misunderstood what you meant above but I basically replaced the following:

https://github.com/redwoodjs/redwood/blob/ecf8aa983a2ead57593e201e922ee589ecf5e19f/tasks/framework-tools/src/lib/framework.mjs#L145-L153

with:

```javascript
  execa.sync('yarn build:js', {
    shell: true,
    stdio: 'inherit',
    cwd: path.resolve(__dirname, '../../'),
  })

  execa.sync('yarn build:types', {
    shell: true,
    stdio: 'inherit',
    cwd: path.resolve(__dirname, '../../'),
  })
```

to no avail. 😓

**Comment by thedavidprice** [comment]
The issue here is that the ttsc package we use to build types (and then rebuild) has a bug with the latest typescript version. The resulting behavior is that **re**-building can often fail. See @Tobbe link above https://github.com/redwoodjs/redwood/issues/3053#issuecomment-881515563

@jtoar has proposed two proposed solutions:
- clean before every re-build #3074
- remove ttsc package #3082

If you want to keep using `rwfw` for the time being, you'll just need to run `build:clean` if you run into this error. `rwt link` is still an option.

**Comment by amorriscode** [comment]
@thedavidprice thanks for sharing those, currently relying on manually running `build:clean` when working with TypeScript files.

One thing to note: I also see this when running `rwt link`.

**Comment by thedavidprice** [comment]
> One thing to note: I also see the build error when running rwt link.

Ah, that makes sense as it's the same ttsc usage. But is it also blocking the re-build? I've not had these problems myself, so it's been unclear to me where/when it's occuring.
