### ISSUE TITLE
Any plans to support react-native or react-native web?

### ISSUE THREAD

**Issue by skv-headless** [redwoodjs/redwood#306]
It's gonna be so awesome to have file structure like this

/api
/web
/mobile

**Comment by peterp** [comment]
100%

Our current thinking is to add a configuration option to `redwood.toml` that allows you to specify the target. Right now we have a fixed `api` and `web` side that target nodejs lambdas and browsers, but we would love to support electron and react-native.

**Comment by thedavidprice** [comment]
@peterp did you want to leave this Issue open for discussion? Or ok to close out?

**Comment by mojombo** [comment]
I think we can close out. @thedavidprice maybe you can add to the Discussions category on the forum? Thanks for the question, @skv-headless, it's going to be an awesome future!

**Comment by skv-headless** [comment]
Ok. I will keep this issue in mind. After having some experience with redwood I will try to write down a vision of react-native integration

**Comment by thedavidprice** [comment]
Done! The thread continues:

https://community.redwoodjs.com/t/any-plans-to-support-react-native-or-react-native-web/219
