### ISSUE TITLE
cache stale time setup?

### ISSUE THREAD

**Issue by Albert-Gao** [redwoodjs/redwood#3061]
Made a simple to do app, everything works great and so easy to pick up.

just a little issue, when navigating between list page and detail page (both renders a `Cell`), 

1. start the app
2. show the list (Request sent)
3. click todo item go to detail
4. go back to list  (Request sent)

Is there a way we can setup a longer cache stale time or invalidation check so we can avoid the request in step 4? Like only invalidate after 10min or a mutation

**Comment by jtoar** [comment]
Hey @Albert-Gao, glad you're finding the framework easy to pick up! The request in step 4 is by-design and is easily configurable. Redwood makes Apollo Client’s default `fetchPolicy` `cache-and-network`. This means that the client constantly checks to see if there’s anything’s new. You can get out of this by changing the `fetchPolicy` to something like `cache-first`: https://www.apollographql.com/docs/react/data/queries/#setting-a-fetch-policy. 

You can change the `fetchPolicy` in the `beforeQuery` lifecycle method of a Cell.

**Comment by Albert-Gao** [comment]
Thanks, works like a charm now :)

**Comment by Albert-Gao** [comment]
But interestingly,

this works

```
    fetchPolicy: 'cache-first',
```

while this is not working:

```
    fetchPolicy: 'cache-first',
    nextFetchPolicy: 'cache-first',
```

why the step4 falls under the `fetchPolicy` rather than `nextFetchPolicy`....
