### ISSUE TITLE
dbAuth: Add a `loginHandler` similar to the `signupHandler`

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#3064]
The idea being that you can get in the middle of the login process and make sure you really want the user to be able to log in. Maybe you check that have verified their email address first, and if not, block their login.

https://community.redwoodjs.com/t/dbauth-is-here-host-your-own-authentication-the-old-fashioned-way/2267/21?u=rob

**Comment by realStandal** [comment]
I just wanted to say/ask before answering your (Rob's) question from the forum, is `loginHandler` going to be the equivalent of `signupHandler` or is it more a `loginSideEffect`? Where side-effect runs in addition to `dbAuth's` default behavior but doesn't replace it; and the handler would more-or-less replace it akin to `signup` can nullify a signup.

My personal use would be the side-effect, I think `dbAuths` behavior is fine and I only slightly want to augment it. I don't, however, want that to push what could be an adaptable feature for others/my future self into an unnecessary box.

---

Continuing from the forum post, quote from @cannikin:

> Should a loginHandler always have to be defined, or do you think loginHandler() is optional, and if you don’t define it, it falls back to the current behavior (returning the ID of the user that needs to be saved to the cookie)?

Following suite with `signupHandler` seems best imo, making it required. What I ask in response to your second quote, below, kind of builds into this opinion, though:
* If `loginHandler` can return whatever it pleases, maybe just provide the `rw setup` boilerplate for returning the user's ID. Similar to `signup` which provides the minimal saving to the DB.
* If `loginHandler` is more like `loginSideEffect`, it runs some logic in addition to login, then it not being required makes more sense than following along with `signupHandler`.

> If you do define it, you can include any logic you want, you just need to make sure to return the user ID just like the default behavior? Maybe loginHandler() is passed the user record that matches the username/password, and then you can inspect that data (or even pull additional data from the DB if necessary) and determine whether to return the ID, or throw an error. You can then respond to that error in your LoginPage…

The whole user record seems fine to me. The only issue maybe applications storing a lot of data in their user record, but that maybe a bigger/not `dbAuths` problem.

Either way, I like the idea of making `login` more flexible than the under-glorified `beforeResolver` I brought up on the forum, my counter-question is: would `dbAuth` restrict what is returned to the user's ID, or is it giving away that responsibility to the handler and it becomes our responsibility to not return `hashedPassword` or `salt`? Or is that your question lol.

The returning-what-we-want seems fine to me, seems it fits better with the rest of RW's philosophy on taking away the tedious/boilerplate/conventional aspects of a process (auth) and clearly exposing the business-logic component of it. I'd only question the security implications that you may, unknowingly, expose an application's developer to in allowing it; storing the `salt` within the session cookie.

The handler containing any logic and throwing an error disallowing the login, passing the error back to the client was exactly what I was thinking. For example, being able to check for the existence of a record in another table (not `user`), ensuring fields of `user` are present and contain expected values, making and awaiting a request to an external API, ...

**Comment by dthyresson** [comment]
Whichever the implementation, I want to propose two considerations:

1. That the handler function be able to support Netlify background function naming (ie, loginHandler-background.js)
2. That the login and signup/in handler functions have some security on them that shield from non-approved callers

Netlify Identity solves this via a JWT secret in the header. One could implement these as webhooks and secure them with headers that a secure api service generates, perhaps.

**Comment by cannikin** [comment]
I'm not familiar with the background Netlify stuff...how does that work? Right now `signupHandler()` is a just a JS function (not a serverless function) that you provide as an option in `functions/auth.js` (which IS a serverless function!):

```javascript
import { db } from 'src/lib/db'
import { DbAuthHandler } from '@redwoodjs/api'

export const handler = async (event, context) => {
  const authHandler = new DbAuthHandler(event, context, {
    db: db,
    authModelAccessor: 'user',
    authFields: {
      id: 'id',
      username: 'email',
      hashedPassword: 'hashedPassword',
      salt: 'salt',
    },
    signupHandler: ({ username, hashedPassword, salt, userAttributes }) => {
      return db.user.create({
        data: {
          email: username,
          hashedPassword: hashedPassword,
          salt: salt,
          name: userAttributes.name
        },
      })
    },
    loginExpires: 60 * 60 * 24 * 365 * 10,
  })

  return authHandler.invoke()
}
```

If we added `loginHandler`, how would Netlify be able to background-ify that?

**Comment by dthyresson** [comment]
Sorry, I thought signup handler was a new handler that would be called after a signup - ie, to email the person a confirmation.

Is there an idea of a post-sign up type of event?

> If we added loginHandler, how would Netlify be able to background-ify that?

So - is the intention for loginHandler to be a method ... or invoke (post) to another serverless function. My concern would be that a login or signup (db access) and then some post processing to send an email *may* hit the 10second serverless function runtime limit.

So, if the loginHandler instead makes an http request to a named (by config( serverless function , then that function could be `something-background.js`.

But if the intention is to do the login/signup and post event email or confirm of whatnot all in the same `functions/auth.js` then still may hit 10 second limit timeouts maybe.

**Comment by cannikin** [comment]
Yeah the intention for `signupHandler()` was to do simple processing inline and return quick (by default, just creating the user in the database). If you need to do something like send an email, it'd be best to farm that out to another function call, or turn it into a background process like you're talking about. Same with `loginHandler()` I'd imagine.

**Comment by realStandal** [comment]
I'm so sorry I'm a slower thinker/worker and you're the opposite @cannikin...

I had a thought which I think builds off what David was saying, at least partially: the confirmation flow that I had described for this handler's use case may be better split into it's own process. To an end user, signing up is signing up but what it's doing is sending that confirmation email, once they click it or submit the code sent, `dbAuth` gets called into action. So logging in isn't even achievable because the account doesn't actually exist.

That said, I think the handler is still useful and worth having; disabling an account is something else I have on my list and I think it'd be the best place to put it.

**Comment by cannikin** [comment]
I could update `signupHandler()` so that returning `true` logs someone in and returning `false` or a string does NOT log them in, and shows a message at the top. You could also `throw` if you want to stop signup and show an error message for some reason. So you could `return "Check your email for a validation link!"` and that would show in a toast notification on the signup page, but NOT log you in.

If you try to login, you can have a check in `loginHandler()` that throws because they haven't verified yet. Once they do verify, everything works.

How's THAT sound?

**Comment by realStandal** [comment]
@cannikin I like it! Would clean up the error handling I have now and fits another need, actually!

**Comment by realStandal** [comment]
Is it going to be the same sort of setup with `loginHandler`, the returning `true`, `false`, or a string to determine the result?

**Comment by cannikin** [comment]
With `loginHandler()` I have it where you either have to return the user that can log in (really an object with at least an `id` field), or throw an error. At that point the user is who they say they are (dbAuth already checked their username and password) so it seems like throwing an error is the "right" way to disallow them to log in.

**Comment by dthyresson** [comment]
Update on my initial question about

> handler function be able to support Netlify background function 

If I were to implement some sort of email or confirmation job, I would use the `loginHandler` to either 

1. Pdd a job to a q and have a worker process and send the email (given I have such a q and worker) or
2. Post a webhook (normal http) to my app with a signature to verify my request and that web hook could be a background async Netlify function that sends the email. 

Same with a `signUpHandler()`

These functions are callbacks to my psuedo-queue that then performs the task.
