### ISSUE TITLE
The scaffold template for Auth page has some Typing issues

### ISSUE THREAD

**Issue by Albert-Gao** [redwoodjs/redwood#3067]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/18282328/126146454-0e34d137-eddc-4aec-b377-27638c56e4dc.png">

![image](https://user-images.githubusercontent.com/18282328/126148309-acea58c5-cfd7-465e-a1ab-250c32f4164a.png)

![image](https://user-images.githubusercontent.com/18282328/126148358-20165cbf-8071-4bc4-8e59-6adc2dea502c.png)

**Comment by dthyresson** [comment]
HI @Albert-Gao might this be the same issue as https://github.com/redwoodjs/redwood/issues/3049 ?

**Comment by Albert-Gao** [comment]
Good catch! tried that version, the style issue has been fixed, but not the type, I will remove the style fix from my commit. thanks :)

**Comment by Albert-Gao** [comment]
Updated the PR, removed the styling fix. :)
