### ISSUE TITLE
[RFC] Standardised CellError component to handle graphql failures

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3069]
### What?
Handling Cell errors, and graphql errors in general, are quite painful, with very nested syntax to get to the error code.

We should provide a more intuitive (i.e. Redwood-y) way of handling errors, as handling api errors forms a large part of buildling most projects! 

See idea in a bit more detail here:

[Graphql Error Hnadling.pdf](https://github.com/redwoodjs/redwood/files/6842653/Graphql.Error.Hnadling.pdf)

**Comment by thedavidprice** [comment]
@dac09 is there anything here that could be actionable for v1-rc and/or v1?

**Comment by dac09** [comment]
I think it should be possible to fit this in, during RC. Its just a utility component we could expose from `rwjs/web`, but I'm keen to get feedback from the community on how they would like to see errors handled too

**Comment by simoncrypta** [comment]
I think #3721 can solve this ?

**Comment by dac09** [comment]
Closing as this has become stale, and #3721 takes away a lot of the pain!
