### ISSUE TITLE
Improve E2E tests for framework

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3071]
Our current E2E tests have been _difficult_ to say the least.

This ticket is a prompt to investigate:

- [x] More reliable tests, using the test project generator
- [ ] Making the tests faster to run i.e. parallelised, so they don't depend on each other
- [x] Investigate using playwright, as our specific usecase may be more appropriate
- [ ] Be able to startup servers before running specs (and close them afterwards)

**Comment by thedavidprice** [comment]
- [ ] Windows support

**Comment by peterp** [comment]
What is the test project generator?

**Comment by dac09** [comment]
Done ages ago with smoke tests!
