### ISSUE TITLE
Add Auto-import for Nested Pages in App.js

### ISSUE THREAD

**Issue by pi0neerpat** [redwoodjs/redwood#3073]
## Problem 

When using the new "nested folder" scaffold feature (#2613), the developer must now manually import any nested pages in `Routes.js`

## Desired behavior

The Redwood Way says we shouldn't need to import Pages in `Routes.js`

## Potential solution

Update this function

https://github.com/cjreimer/redwood/blob/5db72448bd86999bf345a8ef18dd61da2082d6a0/packages/internal/src/paths.ts#L214

**Comment by thedavidprice** [comment]
I believe you mean `Routes.js` instead of `App.js`, correct?

Regardless, I'm guessing this was actually a problem you reported here #3056 and fixed in #3084

Maybe?

**Comment by pi0neerpat** [comment]
This is actually a different problem:

```js
// I have to import this manually now
import DappPage from 'src/pages/Dapp/DappPage/DappPage'

const Routes = () => {
  return (
    <Router>
        {/* I don't need an import for HomePage, since it is NOT nested: src/pages/HomePage */}
        <Route path="/" page={HomePage} name="home" />

        {/* I do need an import for DappPage, since it IS nested: src/pages/Dapp/DappPage/DappPage*/}
        <Route path="/{mnemonic}" page={DappPage} name="dapp" />
```

**Comment by thedavidprice** [comment]
Hmm, it seems you have something else going on. Here's the content of my `Routes.js`:
```js
import { Router, Route, Private, Set } from '@redwoodjs/router'
import PostsLayout from 'src/layouts/PostsLayout'
import BlogLayout from 'src/layouts/BlogLayout'

const Routes = () => {
  return (
    <Router>
      <Set wrap={BlogLayout}>
        <Route path="/contact" page={ContactPage} name="contact" />
        <Route path="/blog-post/{id:Int}" page={BlogPostPage} name="blogPost" />
        <Route path="/about" page={AboutPage} name="about" prerender />
        <Route path="/" page={HomePage} name="home" prerender />
      </Set>
      <Private unauthenticated="home">
        <Set wrap={PostsLayout}>
          <Route path="/admin/posts/new" page={PostNewPostPage} name="newPost" />
          <Route path="/admin/posts/{id:Int}/edit" page={PostEditPostPage} name="editPost" />
          <Route path="/admin/posts/{id:Int}" page={PostPostPage} name="post" />
          <Route path="/admin/posts" page={PostPostsPage} name="posts" />
        </Set>
      </Private>
      <Route notfound page={NotFoundPage} prerender />
    </Router>
  )
}

export default Routes
```

And a screenshot of my `pages/` dir, which shows all the Scaffolded pages are nested.

<img width="228" alt="Screen Shot 2021-07-21 at 4 34 59 PM" src="https://user-images.githubusercontent.com/2951/126572753-38866156-696c-4a5b-b37a-257d11fc89f2.png">

---

Are you doing anything non-standard with your Routes.js file or your web/src/pages directory?

**Comment by jtoar** [comment]
I think the difference is that now you have to prefix DappPage with Dapp because it's nested. So while DappPage isn't available, DappDappPage is available.

We could add an underscore between the directory and the component to make the level of nesting clearer? Like Dapp_DappPage

**Comment by thedavidprice** [comment]
@jtoar Ah, that's a great callout. When I first saw how we handled the nesting as `DappDapp...` I thought it wasn't very intuitive. Makes sense we need _something_ unique. 

Is there a way we can inline the usage documentation? I just don't think any way we handle the syntax we will be able to make it obvious.

**Comment by jtoar** [comment]
@thedavidprice we have this block already in the Routes.{js|tsx} template:

https://github.com/redwoodjs/redwood/blob/f359de4059f6b78226e332424447b637fba163e0/packages/create-redwood-app/template/web/src/Routes.tsx#L1-L8

**Comment by jtoar** [comment]
@pi0neerpat while we're working on the DX around nested scaffolds/pages/components, did you get this resolved and/or did our explanations help?

**Comment by pi0neerpat** [comment]
Yes it helped me solve it immediately. Thank you!
