### ISSUE TITLE
Scaffold: Update formatting for error messages

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#3076]
We should at least spiffy up the `<Failure>` component with some styling to make the errors formatted a little nicer. We now have react-hot-toast in place, we could update the error messages in the scaffolds to use it, rather than spitting them inline in the page?

![image](https://user-images.githubusercontent.com/300/126233821-0a830f00-1236-4e5a-a4aa-4a0d1ee9873d.png)

The error messages that are rendered by `<FormError>` are already styled nicely:

![image](https://user-images.githubusercontent.com/300/126359304-a436fd68-d7b5-4299-afbc-5b51644eaa2f.png)

So this is just focused on updating the styling of the `<Failure>` components in the cells.

**Comment by Albert-Gao** [comment]
![image](https://user-images.githubusercontent.com/18282328/126405102-b31d22d0-7772-4e7a-82da-6a129cb28a91.png)

Is this looks good? Just reused that style from scaffold styles but has to add one line for that missing border. :)

**Comment by cannikin** [comment]
I just opened a PR with this fix, sorry @Albert-Gao !
