### ISSUE TITLE
Should we add the `yarn build:clean && yarn build`  to the CONTRIBUTING.md

### ISSUE THREAD

**Issue by Albert-Gao** [redwoodjs/redwood#3078]
The local setup section:
https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md#local-setup

has a missing piece.

after a fresh `yarn install`, `yarn build:clean && yarn build` is a must-have for running the unit test. Currently, the doc only mentions the install but not the build part.

Should we add this into the local setup section?

**Comment by thedavidprice** [comment]
Moving this conversation to #3092

Thanks!
