### ISSUE TITLE
Customize webpack config

### ISSUE THREAD

**Issue by Idered** [redwoodjs/redwood#309]
I would like to use TailwindCSS. To do that, I need to add postcss-loader to redwood webpack config. Is there any way to do that? 

If there is no way I can create a PR that will handle `redwood.config.js` just like NextJS does it.

**Comment by peterp** [comment]
Thanks, that would be amazing! 

I would love to allow a user to define a custom config in `web/config/webpack.config.js` that's merged (with `webpack-merge`) in our main config in [`webpack.common.js`](https://github.com/redwoodjs/redwood/blob/09c2a446e6c9a5124be63d7b3e30a9f4a6a89226/packages/core/config/webpack.common.js#L40).

I would like users to be able to export a function that accepts a webpack env of `development` or `production`: Eg.: `module.exports = (webpackEnv) => {}`

Some pointers for implementation:
1. To get the location of the webpack config:
```
const { getPaths } = require('@redwoodjs/internal')
const userWebpackConfig = path.join(getPaths().web.config, 'webpack.config.js')
// getPaths.web.config needs to be implemented.
```
