### ISSUE TITLE
Reformatting boolean check in template on save

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#3103]
Not sure if this is a Prettier thing or an ESLint thing? 

This line generates with `!!roles` but as soon as the file is saved in VSCode it turns it into just `roles` instead:

https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/setup/auth/templates/auth.js.template#L80-L82

I don't have any custom config for either of these tools, so I assume it's inheriting whatever our default config files are telling them to do. Maybe it's a clash with VSCode plugins?

**Comment by cannikin** [comment]
@dthyresson does this happen to you as well? I think you added this check so I'm guessing your VS Code does *not* change this to just `roles` on save?

**Comment by thedavidprice** [comment]
Closing this as related code has since been changed.
