### ISSUE TITLE
Add completion shortcuts for commands and options

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#311]
@AryanJ-NYC made a suggestion to implement [completion shortcuts](https://github.com/yargs/yargs/blob/master/docs/api.md#completioncmd-description-fn) that would help self-document our CLI.

**Comment by jtoar** [comment]
It looks like we'd need to modify `yarn create` or add a completion-shortcuts generator.

Yargs does completions by appending a generated script to a user's ~/.bashrc (so, that brings up the Windows question). (Sources: [yargs](https://yargs.js.org/docs/#api-completioncmd-description-fn), [stackoverflow](https://stackoverflow.com/questions/32258362/setup-command-line-completion-with-yargs).)

I'm guessing that it wouldn't be a good idea to do this during `yarn create`, unless it was interactive. So there could be a generator, `yarn rw g completions` that modifies your ~/.bashrc. This way, when we update commands, people could just rerun the generator.

I'll try to spike it out. But thoughts?

**Comment by thedavidprice** [comment]
Thanks for looking into this!

But, oh my... I don't love it. We are updating CLI all the time, which means lots of remembering (and reminding) to update including cross-platform considerations. As of now our `--help` and Docs are in great shape and easy to reference.

So for now I'd say "pass" and revisit post v1.

**Comment by jtoar** [comment]
> But, oh my... I don't love it.

My thoughts exactly. 

We could probably set it up so that it automatically grabs all the commands/options. But that would probably require breaking more @redwoodjs/cli bones. +1 for revisit post v1. Maybe near or post.
