### ISSUE TITLE
`rw serve` does not display prerendered pages correctly

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3110]
This is a difficult one to describe, so I made a Tape to explain the issue https://s.tape.sh/QTDmQSPn

https://user-images.githubusercontent.com/1521877/126809929-31215b90-b98e-4432-ac3b-bf2bd7e38015.mp4

To summarise - the express static middleware seems to need `.html` extension to show a prerendered page.

Cases to test:

- [ ] Prerender top level page e.g. site.com/about should serve `web/dist/about.html`
- [ ] Prerender nested page i.e. trailing slashes not needed e.g. site.com/dashboard should serve `web/dist/dashboard/index.html`
- [ ] Prerender nested named page e.g. site.com/dashboard/otherpage should serve `web/dist/dashboard/otherpage.html`
- [ ] Handle trailing slashes e.g. site.com/about/ should serve `web/dist/about.html`

**Comment by macovedj** [comment]
Just a thought... This seems to be the case for `yarn rw dev` as well.  Wondering if it might be easier to solve w/o a build in the middle.  Or maybe harder idk.  Just wondering if we put thought into which makes most sense to start with.

**Comment by dac09** [comment]
You're right that dev does this - but eventually we might be moving away from webpack dev serve - watch this space. 

In response to your question on discord - if you wanted to automatically restart the server you could try nodemon? Something like:

`nodemon $FRAMEWORK_PATH/packages/api-server/dist yarn rw serve`

So it restarts rw serve on your changes? (Assuming you've linked)

**Comment by macovedj** [comment]
good to know.  started digging around [here](https://github.com/redwoodjs/redwood/pull/3113)

**Comment by macovedj** [comment]
think i solved it in the PR above
