### ISSUE TITLE
`yarn rw test` running tests from the `dist` folder.

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#3117]
![image](https://user-images.githubusercontent.com/44849/126874980-5b310657-520f-465f-89e3-9123c44eaa67.png)

- [ ] Do not run tests from the './dist` folder.
- [ ] Do not build test files 🤕

**Comment by thedavidprice** [comment]
Jest config is here:
https://github.com/redwoodjs/redwood/tree/main/packages/testing/config/jest

**Comment by callingmedic911** [comment]
@peterp I can't get any test case to be built and present in `/dist`. I tried `rw build`. Does this "don't build the tests" part already handled?

Though I'm able to reproduce the second one: if I place a file manually inside dist, it's getting executed in jest. To fix this, I can update the jest config to ignore whole `/dist` directory.

**Comment by peterp** [comment]
@callingmedic911 You're right, we shouldn't have tests in those folders - and this is probably a symptom of some other misconfiguration, but I'm wondering if `jest` over searching here could be a performance issue?

Maybe we should handle this in two ways:
1. Configure jest so that it only looks for tests in `src/`
2. Create some sort of postbuild hook that let's us validate that tests are not in the dist folder.

**Comment by callingmedic911** [comment]
>1. Configure jest so that it only looks for tests in `src/`

Okay, yes. 👍 
>2. Create some sort of postbuild hook that let's us validate that tests are not in the dist folder.

Okay. So it'll be like a fail-safe if there's any improper config and not to put test file in `/dist`, right? But do you think it's worth it overall - I mean it'll add a little bit of build time for something that could happen but hasn't happened yet. 
Just trying to understand the value. :) Would be happy to take this forward whatever we decide. 😄

**Comment by peterp** [comment]
> But do you think it's worth it overall - I mean it'll add a little bit of build time for something that could happen but hasn't happened yet. Just trying to understand the value.

Totally, and I was thinking about how much time this could take to write. Oddly enough this happened to me once above, and yesterday whilst playing around with different build-tools!

 I do not think it's mission critical - what I would hate to see is that we accidentally ship a test (increasing the bundle size), or that our test system is slow because it runs duplicates. But, since we're fixing the `src` directory it's likely that that'll be enough.

**Comment by callingmedic911** [comment]
> I do not think it's mission critical - what I would hate to see is that we accidentally ship a test (increasing the bundle size), or that our test system is slow because it runs duplicates. But, since we're fixing the `src` directory it's likely that that'll be enough.

Right, I'd go ahead with jest changes to look inside `src` only for both web and api sides for now. And in future, if we still see test cases after build, I think it could be a hint to an underlying issue which is best to address directly.

The PR should be fairly short - you can assign it to me, I'll get it as soon as I can squeeze a little time. Thanks for the help @peterp! :)
