### ISSUE TITLE
Type error with `beforeResolver` and `requireAuth`

### ISSUE THREAD

**Issue by zackdotcomputer** [redwoodjs/redwood#3142]
In Typescript, running Redwood 0.35.3 canary 66. I locally fixed the typing of the automatically generated `requireAuth` function to this:
```typescript
export const requireAuth = ({ roles }: { roles?: string | string[] } = {}) => void //...
```

(The generated version did not give a type for the argument so it was implicitly given `any` typing.)

However, this has exposed another type error. When trying to secure services using the `beforeResolver`, the suggested implementation is:
```typescript
export const beforeResolver = (rules: BeforeResolverSpecType) => {
  rules.add(requireAuth);
};
```

But this now yields the following error:
```
Argument of type '({ roles }?: { roles?: string | string[]; }) => void' is not assignable to parameter of type 'RuleValidator | RuleValidator[]'.
  Type '({ roles }?: { roles?: string | string[]; }) => void' is not assignable to type 'RuleValidator'.
    Types of parameters '__0' and 'name' are incompatible.
      Type 'string' has no properties in common with type '{ roles?: string | string[]; }'.ts(2345)
```

Tracing this back it appears to be because `rules.add` expects a function with the signature `(name: string, ...inputs: Array<unknown>) => void;`. Now that I've given the first argument to `requireAuth` a definite type, the compiler can alert me that there is a mismatch here.

I am assuming the actual bug here is not the typing of `rules.add` but rather that we were previously just relying on `requireAuth` to take in `name` as its first arg, fail to extract `roles` from it, and just proceed as if it had been given undefined? Like perhaps the implementation of `beforeResolver` should actually be something like:
```typescript
export const beforeResolver = (rules: BeforeResolverSpecType) => {
  rules.add(() => requireAuth());
};
```

But still new in the codebase - let me know if I'm missing something there.

**Comment by thedavidprice** [comment]
Thanks @zackdotcomputer! Looping in @dac09

**Comment by thedavidprice** [comment]
@dac09 ping

**Comment by zackdotcomputer** [comment]
As luck would have it, I was meaning to start a new project this weekend. Long story short, yes I am still seeing this @thedavidprice 

----

The long story long here's the exact steps I took to set up a new project with the two compiler errors:

```
yarn create redwood-app --ts test
cd test
yarn rw setup auth supabase
```

Add a random model to the Prisma schema:
```
model Profile {
  id        String @id @db.Uuid
  avatarUrl String
}
```

```
yarn rw prisma migrate dev
yarn rw g scaffold Profile
```

Ok setup now complete. You should see the two type issues I listed initially in `auth.ts` and the generated service file `profiles.ts`

**Comment by thedavidprice** [comment]
Thanks @zackdotcomputer Confirming I can reproduce this locally. 

Looks like there might be something with the type misfiring here in the template for Auth.ts:
https://github.com/redwoodjs/redwood/blob/00a91dee19e55bc574e716fd1ba6cabf6edc11df/packages/cli/src/commands/setup/auth/templates/auth.js.template#L66

Looping in @dthyresson Is the syntax for "optional" correct here?
