### ISSUE TITLE
Server-side router should not fail if query-unsafe characters are in `/path/{variable}` open ended routes

### ISSUE THREAD

**Issue by zackdotcomputer** [redwoodjs/redwood#3146]
Let's say you have:
```tsx
<Route path="/search/{query}" page={SearchPage} name="searchQuery" />
```

And your user is going to search for a term with a character that can be used in a path but not in a query string. Let's assume their search query is `google.com`.

If you try to send the user to that page using `navigate(routes.searchQuery({ query: "google.com" }))` they will be sent to `/search/google.com`. This is a valid path (though a strange one) and the client-side navigation works. However, if the user hits "refresh" on this page, the **server** side request fails with the response `Cannot GET /search/google.com`.

If you uri-encode the value to `google%2Ecom`, then it works as intended.

I think the expected behavior would be that in-path variables could handle query-unsafe characters.

**Comment by zackdotcomputer** [comment]
Actually it appears that URI encoding *by hand* works but if you try to pass a URI-encoded value to the `routes` named function (at least on Safari) the user will always be redirected to the unencoded URI like `search/google.com`. So yeah - not sure there is a workaround for this at the moment.

**Comment by thedavidprice** [comment]
@Tobbe thoughts on this one? 

@LBrian @jtoar curious how/if #2683 intersects with this.

**Comment by zackdotcomputer** [comment]
@thedavidprice @Tobbe at the head of `main` I can no longer reproduce this issue - possibly has been fixed by a commit in the intervening days?

Regardless, I added a test suite (linked above) to ensure that the router is doing correct encoding/unencoding of various safe and unsafe characters in the path and params. I'm not 100% sure this is doing a comprehensive test of both the client-side and the server-side routing logic, but I'm sure it's doing a comprehensive test of at least one of them.

**Comment by LBrian** [comment]
> @Tobbe thoughts on this one?
> 
> @LBrian @jtoar curious how/if #2683 intersects with this.

#2683 change is related to **path matching** (`NavLink` and `useMatch`), I had a quick look there is no intersection of this issue (`Route` using another `matchPath` in `utils`)
