### ISSUE TITLE
Difficult to add new GraphQL Scalars due to Scenario Value field limitations

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#3152]
I wanted to add both BigInt and Byte support using `graphql-scalars` because Prisma supports these now (Byte just in Postgres).

While it is easy to add both to the Redwood `rootSchema` https://github.com/redwoodjs/redwood/blob/d3b05e31efa5ab369f2b2f49db5d51af8a93286a/packages/graphql-server/src/makeMergedSchema/rootSchema.ts#L2, for example for BigInt:

```js
import {
  BigIntResolver,
  DateResolver,
  TimeResolver,
  DateTimeResolver,
  JSONResolver,
  JSONObjectResolver,
} from 'graphql-scalars

//...
export const schema = gql`
  scalar BigInt
  scalar Date
  scalar Time
  scalar DateTime
  scalar JSON
  scalar JSONObject

  type Redwood {
    version: String
    currentUser: JSON
    prismaVersion: String
  }

  type Query {
    redwood: Redwood
  }
`

export interface Resolvers {
  BigInt: typeof BigIntResolver
  Date: typeof DateResolver
  Time: typeof TimeResolver
  DateTime: typeof DateTimeResolver
  JSON: typeof JSONResolver
  JSONObject: typeof JSONObjectResolver
  Query: Record<string, unknown>
}

export const resolvers: Resolvers = {
  BigInt: BigIntResolver,
  Date: DateResolver,
  Time: TimeResolver,
  DateTime: DateTimeResolver,
  JSON: JSONResolver,
  JSONObject: JSONObjectResolver,
```

and then also update `internal`  https://github.com/redwoodjs/redwood/blob/d3b05e31efa5ab369f2b2f49db5d51af8a93286a/packages/internal/src/generate/graphqlSchema.ts#L7

it is not so easy to support scenario field generation because:

* A BigInt like `9007199254740991` is really `9007199254740991n` (see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt)

So code like

```js
export const scenarioFieldValue = (field) => {
  const randFloat = Math.random() * 10000000
  const randInt = parseInt(Math.random() * 10000000)

  switch (field.type) {
    case 'String':
      return field.isUnique ? `String${randInt}` : 'String'
    case 'BigInt':
      return 9007199254740991
```

Will fail when using the scenario in an app because `9007199254740991` isn't `9007199254740991n` and it is incompatible where the scenario just does a Prisma create on the model with the field data.

This is ever harder withBytes because a Byte has to be created using Buffer like

`Buffer.from('these-will-be-bytes')`

And that cannot be set as the output of the `switch (field.type)` in `scenarioFieldValue`.

There is a JSON representation of it... as in:

```js
import { Buffer } from 'buffer';

const buf = Buffer.from([0x1, 0x2, 0x3, 0x4, 0x5]);
const json = JSON.stringify(buf);

console.log(json);
// Prints: {"type":"Buffer","data":[1,2,3,4,5]}
```

But you need to have some special handling to convert it back as part of the scenario where the create happens also

```
const copy = JSON.parse(json, (key, value) => {
  return value && value.type === 'Buffer' ?
    Buffer.from(value) :
    value;
});

console.log(copy);
// Prints: <Buffer 01 02 03 04 05>
```

So, while can add these types, need to figure out a better way to support or make the scenario data loading smarter.

**Comment by peterp** [comment]
If you're currently stuck on this and would like to add scalars to your graphql-project, create 
`api/src/graphql/scalars.ts`

with the following content:
```
import { BigIntResolver } from 'graphql-scalars'

export const schema = gql`
  scalar BigInt
`

export const resolvers = { BigInt: BigIntResolver }
```

**Comment by dthyresson** [comment]
@Burnsy See https://github.com/redwoodjs/redwood/issues/3152#issuecomment-896311413 for a better workaround for adding BigInt support (without scenarios)

**Comment by dthyresson** [comment]
Note https://github.com/redwoodjs/redwood/pull/3884 made it easier, but didn't necessarily resolve the scenario issue.
