### ISSUE TITLE
Customizable error messages for `dbAuth`

### ISSUE THREAD

**Issue by realStandal** [redwoodjs/redwood#3178]
cc @cannikin 

Mainly looking at the "Username `XXXXXXX@gmail.com` already in use", I can't recall off the top of my head others.

Any valid string could be set as, for example, an environment variable. If the variable is undefined a default value is used.
I'd vote `''` is a valid, but discouraged, value; just for simplicity's sake.

Use cases:

* I care about my application's UX, and am strict on how I refer to certain information. My application only uses a user's `email`, and the default error message causes a footprint on this.
* The primary (or entire) audience of my application do not speak English as a native language, or at all. To keep things clear for them, I'd like to go ahead and make what errors I can in their native tongue.
  * Because any string is valid, I could also set this to a `key` used by i18next to "translate"(?) client-side.
* ??

Happy to take this one on, and I'm not necessarily saying everything should be customizable if there's some I'm not thinking of/know about that don't make sense.

**Comment by realStandal** [comment]
I also didn't search before I posted!! let me do that

**Comment by cannikin** [comment]
Oh yeah, I forgot about that text! If you want to take a stab at a PR for that, please do! I’m on vacation for the next two weeks but can check in for any help or review. 

Where were you thinking the text would go? In the same block of options as stuff like signupHandler? I guess that doesn’t make it very easy for I18n though…maybe it’s an option passed to signUp()? I guess logIn() could take similar options.

**Comment by realStandal** [comment]
No rush on my end! With what's come up the past day or so having an excuse to draw it out helps!

I was thinking do the lookup as part of the result of signUp, so in the same way I'd throw an error as part of a signupHandler and use its message to provide a translated, contextual message.

I think alongside signupHandler makes the most sense. Now would a generic `errorMessages` split into signup and login suffice? Or should each get their own options, and `loginExpires` can be relocated to `login.expires`; errors could fall under `login.errors[...]`.

**Comment by cannikin** [comment]
Back from vacation! I'll think about this some and reply soon!

**Comment by cannikin** [comment]
Okay, how about something like this:

```javascript
import { db } from 'src/lib/db'
import { DbAuthHandler } from '@redwoodjs/api'

export const handler = async (event, context) => {
  const authHandler = new DbAuthHandler(event, context, {
    db: db,

    authModelAccessor: 'user',

    authFields: {
      id: 'id',
      username: 'email',
      hashedPassword: 'hashedPassword',
      salt: 'salt',
    },

    login: {
      hander: (user) => {
        return user
      },
      errors: {
        usernameOrPasswordMissing: 'Both username and password are required',
        usernameNotFound: 'Username ${username} not found',
        incorrectPassword: 'Incorrect password for ${username}',
      },
      expires: 60 * 60 * 24 * 365 * 10,
    },
    
    signup: {
      handler: ({ username, hashedPassword, salt, userAttributes }) => {
        return db.user.create({
          data: {
            email: username,
            hashedPassword: hashedPassword,
            salt: salt,
            // name: userAttributes.name
          },
        })
      },
      errors: {
        fieldMissing: '${field} cannot be blank',
        usernameTaken: 'Username ${username} already in use',
      },
    },
  })

  return authHandler.invoke()
}
```

I'm not a huge fan of having *everything* be a function so I made the errors just strings...how does that feel?

**Comment by realStandal** [comment]
What I was thinking as well, especially with the strings over functions. Love the templating too!

**Comment by realStandal** [comment]
Closing in favor of the PR

**Comment by cannikin** [comment]
When the PR is linked to the issue it'll automatically close it when the PR is merged. Pretty handy!
