### ISSUE TITLE
Deploy command exit code incorrect on migration failures

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3205]
The deploy cli command does not fail with exit code 1, when migration failures happen.

e.g. Repro: `DATABASE=make_it_fail yarn rw deploy vercel --no-build`

See output here:
https://s.tape.sh/NcEl1JbM

Which can lead to all sorts of nastiness

**Comment by zakmandhro** [comment]
FYI: I could not reproduce this with rw-test-app on [current main branch (4112c2c8)](https://github.com/redwoodjs/redwood/commit/4112c2c87912b7f4239d423cefdc0a9c407e29b4).

**Comment by dac09** [comment]
Thanks for looking into this @zakmandhro - note that it'll "say" failed with exit code 1, but if oyu see the "✨ Done" that means actual exit code was 0.

But perhaps the tires just needed kicking - I will check again as soon as I can find some time.

**Comment by callingmedic911** [comment]
@dac09 Just tried to reproduce this. Like @zakmandhro said, seems like it's exiting with 1 now.

![Screenshot 2021-08-20 at 2 32 25 PM](https://user-images.githubusercontent.com/2629902/130209034-2184b4bc-72d7-4241-a035-e86f939177ae.png)

**Comment by dac09** [comment]
Thanks for confirming. I'll close the issue :)

**Comment by zakmandhro** [comment]
Thanks for confirming Aditya. I meant to add a screenshot/tape but couldn't
get a chance due to travel.
