### ISSUE TITLE
Feature: Add a CLI command to print environment information

### ISSUE THREAD

**Issue by weaversam8** [redwoodjs/redwood#321]
> @weaversam8 that's 100% the problem. Sorry, I didn't realise you're on Windows.
>_Originally posted by @peterp in https://github.com/redwoodjs/redwood/issues/209#issuecomment-602428395_

Many devtools CLIs include an "info" command (like [`gatsby info`](https://www.gatsbyjs.org/docs/gatsby-cli/#info)) that prints out helpful environment information, like the operating system, Node & Yarn versions, and the package versions in a particular project.

Repositories create issue templates that encourage users to post the output of this command when reporting new issues, to ensure that there's no confusion about the environment when troubleshooting a bug. We should add this functionality to `@redwood/cli`.

**Edit:** This is actually probably a really easy PR. You could use [Gridsome's example](https://github.com/gridsome/gridsome/blob/master/packages/cli/lib/commands/info.js) of their `info` command, which seems to use the very convenient [`envinfo`](https://www.npmjs.com/package/envinfo) package ([which is apparently also what Gatsby uses](https://github.com/gatsbyjs/gatsby/blob/8c2528db5c1a7b229a3ca343840c5bf18ebedb68/packages/gatsby-cli/src/create-cli.js#L228) for their above mentioned command.)

**Comment by thedavidprice** [comment]
🤦‍♂ we’ve needed this for so long now. Great suggestion!

PR is open (for review and debate). Thanks.

**Comment by weaversam8** [comment]
This is released in v0.3.0, and working great!
