### ISSUE TITLE
generate scaffold fails with Float

### ISSUE THREAD

**Issue by leetmachine** [redwoodjs/redwood#3214]
version: redwood/core@0.35.2
db: postgres

I have a model with lat, lng as Float types. When I run `generate scaffold Business` it gives the following error. [prisma docs #float](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#float) states Float mapping was updated for psql 2.17.0, so wondering if thats the cause. It _appears_ rwjs is using 2.26 ( ? ).

```
X  Generating scaffold files...
     Cannot read property 'replace' of undefined
    Adding layout import...
    Adding set import...
    Adding scaffold routes...
    Adding scaffold asset imports...
Cannot read property 'replace' of undefined
error Command failed with exit code 1.
```

model:
```
model Business {
  id           Int      @id @default(autoincrement())
  name         String
  lat          Float
  lng          Float
}
```

**Comment by dthyresson** [comment]
Thanks @leetmachine. 

I just created a PR https://github.com/redwoodjs/redwood/pull/3218 that should fix this in the next release.


As a workaround until then (0.36 should be out this week) you can try to use a Decimal.

**Comment by leetmachine** [comment]
cool, thanks for the quick turnaround!
