### ISSUE TITLE
[rwfw] Rwfw broken in canary

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3239]
On re-running rwfw a second time in a project, we receive this error from the config-store module

```terminal
❯ yarn rwfw project:sync
yarn run v1.22.10
$ /Users/dac09/Experiments/test-3/node_modules/.bin/rwfw project:sync
internal/modules/cjs/loader.js:438
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './index' is not defined by "exports" in /Users/dac09/Experiments/test-3/node_modules/configstore/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/dac09/Experiments/test-3/node_modules/@redwoodjs/cli/dist/rwfw.js:16:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
error Command failed with exit code 1.
```
The only way to work around this is to run `yarn install --check-files` - the checkfiles flag is important, otherwise it doesn't fix the issue (See analysis as to why).

#### Variant A: Run rwfw multiple times
1. Run `yarn rwfw project:sync`
2. Ctrl+C to exit
3. Run `yarn rwfw project:sync` again

This is a common thing to do when testing with multiple projects

#### Variant B: When rwfw steps run internally
1. Generate a test project with either `./tasks/run-e2e` or `yarn build:test-project ~/Experiments/rwfw-error --link` 
2. Once the project is created, run `yarn rwfw project:sync`

This is the same issue, because the project generated in (1) actually runs the steps using in project:sync without the watcher

### Varaint C: Create a canary test project
1. Generate a test project with `yarn build:test-project --canary`
2. Once the project is create, run `yarn rwfw project:sync`

### A bit more analysis
I'm not able to pin point exactly why the issue occurs, ~but it seems when `redwoodjs/cli` is copied over, it can't import config-store which is an es module. When you reinstall with `--check-files` it reinstalls the published CLI and everything starts working again. This _probably_ means that the cli package that we copy over isn't quite the same as the published one~

On further investigation it looks like rwfw is broken in canary/main - which is why we see this issue on the second run

**Comment by dac09** [comment]
@jtoar I'm going to leave this for you when you're back - more than happy to pair on it, but I'm a little bit stumped on this at the moment.

**Comment by jtoar** [comment]
Still TBD, but pretty sure this has to do with configstore being an ECMAScript module

**Comment by jtoar** [comment]
Configstore was recently upgraded from v3.1.5 to v6 (v6 came after v3.1.5). In v6, it became an ESM. We upgraded it recently, in https://github.com/redwoodjs/redwood/pull/3194. Seeing if downgrading back to 3.1.15 solves the issue for the time being.
