### ISSUE TITLE
Make Prisma Slow Query logging threshold duration configurable

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#3248]
The `SLOW_QUERY_THRESHOLD` is a fixed 2 seconds.

![image](https://user-images.githubusercontent.com/1051633/129811155-f66b92c6-620a-4a61-abf0-a0ae7b708e54.png)

Could make this a configurable optional value that defaults if not set:

https://github.com/redwoodjs/redwood/blob/4112c2c87912b7f4239d423cefdc0a9c407e29b4/packages/api/src/logger/index.ts#L347

That way people could lower or raise the threshold if they so choose.

Note that the query output is auto added as a warn if exceeds the threshold.

https://github.com/redwoodjs/redwood/blob/4112c2c87912b7f4239d423cefdc0a9c407e29b4/packages/api/src/logger/index.ts#L386

**Comment by callingmedic911** [comment]
@dthyresson Hi! Is it okay to pick this one? :)

**Comment by dthyresson** [comment]
@callingmedic911 Please do! That would be excellent. Thanks.
