### ISSUE TITLE
[v0.37 critical] Provide an ergonomic way to mockCurrentUser on the API side

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3258]
As part of writing api-side tests, its often very useful to mock the current user.

This is currently possible with `@redwoodjs/api` - but we don't have a recommended way with helix/envelop yet.

Tasks:

- [x] Find a way to mock the context/currentUser with envelop
- [x] Expose ergonomic helpers to do this
- [ ] Update testing docs to demonstrate this

**Comment by dthyresson** [comment]
>  Find a way to mock the context/currentUser with envelop

I think we might be able to create a useMockedUser plugin that uses ContextBuilding or perhaps a similar approach that we took in Webhook testing to mock the event and set the headers such that there is a current user.

I imagine this is more for how to test authenticated api services, correct?

**Comment by dac09** [comment]
AFter all our refactoring and diving deep into graphql server, it turns out we can just mock current user like this: 

```
setContext({
currentUser: {
//... deets
}
})
```
