### ISSUE TITLE
Prisma db undefined in getCurrentUser when using Prisma middleware in 0.36

### ISSUE THREAD

**Issue by o0charlie0o** [redwoodjs/redwood#3260]
The upgrade to 0.36 appears to have created an issue when using prisma middleware. We have a `getCurrentUser` function that starts like so:

```ts
export const getCurrentUser = async (decoded) => {
  const user = await db.user.findUnique({
```

This throws a context creation error because `db` is undefined. In our `db.ts` file we are using a prisma middleware function like so:

```ts
export const db = new PrismaClient({
  log: emitLogLevels(['info', 'warn', 'error']),
})

db.$use(async (params, next) => {
```

If I comment out the middleware everything is fine. The middleware is working correctly in 0.35.2. `db` is not undefined in other functions while using the middleware. It appears just the `graphql` function when the `__REDWOOD__AUTH_GET_CURRENT_USER` query is ran on the client side.

**Comment by thedavidprice** [comment]
cc @dthyresson 

Hi @o0charlie0o Sorry you're bumping into an issue with v0.36. Definitely want to help figure this out.

I’m having a bit of trouble following your explanation; specifically, which issues were happening that required you to use the middleware and which issues were happening due to v0.36 upgrade.
- Is there any chance you could create a minimum reproduction so we can experience it on our end?
- What is your system info? (`yarn rw info`)
- Could you copy+paste 1) the error you get and how to reproduce (e.g. run `rw dev`, build, etc` and 2) The changes to the code you are making to resolve the error
- We upgraded to Prisma v2.29 Have you checked Prisma Issues for similar errors?

**Comment by o0charlie0o** [comment]
@thedavidprice @dthyresson Apologies for the confusing explanation. I tried to create a minimum reproduction from a fresh project but I was unable to reproduce the issue so it must be something in our project. I'll go ahead and close this now.

Thanks!

**Comment by o0charlie0o** [comment]
A quick follow up on this incase anyone else comes across this issue. I was using a module within the Prisma middleware that was imported using the ES6 import syntax: `import { x } from './'`. Changing this to the CommonJS: `const { x } = require('./')` syntax resolved the issue.

**Comment by peterp** [comment]
@o0charlie0o Could you share more about how this middleware? Was it something that you wrote yourself, and were you setting it up in `./api/src/lib/db.js`?

**Comment by o0charlie0o** [comment]
@peterp Sure. It is custom and it lives in `./api/src/lib/imgix.ts` and then imported into `./api/src/lib/db.ts`.

#### imgix.ts
```ts
import { URL } from 'url'
import ImgixClient from 'imgix-core-js'

export const ImgixUrl = (img, options = {}) => {
  const imgixClient = new ImgixClient({
    domain: process.env.IMGIX_HOST,
    secureURLToken: process.env.IMGIX_SECURE_URL_TOKEN,
  })

  const url = new URL(img)

  return imgixClient.buildURL(url.pathname, options)
}
```

#### db.ts
> The following is the original code
```ts
import { PrismaClient } from '@prisma/client'
import { emitLogLevels, handlePrismaLogging } from '@redwoodjs/api/logger'
import { ImgixUrl } from 'src/lib' // There is an index.ts which exports all our modules in lib
import { logger } from './logger'

export const db = new PrismaClient({
  log: emitLogLevels(['info', 'warn', 'error']),
})

handlePrismaLogging({
  db,
  logger,
  logLevels: ['info', 'warn', 'error'],
})

db.$use(async (params, next) => {
  let result = await next(params)
  const imgixOptions = { w: 60 }

  if (params.model && params.model === 'UserApplication') {
    return result
  }

  if (
    ['findFirst', 'findUnique'].includes(params.action) &&
    result &&
    result.profileImageUrl
  ) {
    result.profileImageUrl = result.profileImageUrl.includes('s3.amazonaws.com')
      ? ImgixUrl(result.profileImageUrl, imgixOptions)
      : result.profileImageUrl
  } else if (params.action === 'findMany' && result) {
    result = result.map((r) =>
      r.profileImageUrl
        ? {
            ...r,
            profileImageUrl: r.profileImageUrl.includes('s3.amazonaws.com')
              ? ImgixUrl(r.profileImageUrl, imgixOptions)
              : r.profileImageUrl,
          }
        : r
    )
  }

  return result
})
```

I had to replace `import { ImgixUrl } from 'src/lib'` with `const { ImgixUrl } = require('./imgix')` to get this working in `0.36` otherwise any reference to `ImgixUrl` within the Prisma middleware caused `db` to be undefined within the graphql layer. All other functions we use for various webhooks worked just fine though (potentially because they don't call into the `getCurrentUser` function in `./api/src/lib/auth.ts`. Just to be clear this all worked just fine until `0.36`.

**Comment by peterp** [comment]
Very strange! I'm going to re-open this because my expectation is that it should work - I'll create a reproduction on my side and try to understand exactly what's causing this.

**Comment by dthyresson** [comment]
@o0charlie0o Checking in to see if you were able to reproduce -- or the issue arose again re: Prisma currentUser and middleware.
