### ISSUE TITLE
[RFC] Cannot Nest Routes: Can't create routes with unknown number of parameters in path

### ISSUE THREAD

**Issue by macovedj** [redwoodjs/redwood#3263]
Github, or other applications that function as a UI by which somebody can view files, organizes urls as file paths.  Because there is no limit to how deeply nested folders can be in a repo... this means that routing has to be defined such that a route can include an arbitrary number of subfolders.  I acknowledge that this is a rather specific use case... but I'm sure that there are other instances where a dev might feel the need to organize routes in a manner where the number of 'subroutes' is not predictable.  I think that nesting routes could offer up a solution.

**Comment by macovedj** [comment]
I don't mind looking into implementing this if there isn't opposition

**Comment by mojombo** [comment]
This is true! I would enjoy seeing a proposal (could just be docs to start with) for how Redwood could accommodate this.

**Comment by macovedj** [comment]
> This is true! I would enjoy seeing a proposal (could just be docs to start with) for how Redwood could accommodate this.

Sure I can do some digging and try and write something up as I have time.  Is there a place in the repo where you recommend writing up the docs?  Was just looking through react-router docs.  Is redwood using react-router, and if not, is there a reason behind it?  I kindof like that you can choose whether the route path there has to be an exact match or not via an `exact` prop, and if you don't include it, then so long as the beginning of the route matches the specified path, you'll see your content rendered.  Would that be functionality that would be desirable for redwood?  They're `Switch` component seems like it could be good to draw inspiration from as well.

**Comment by macovedj** [comment]
Sorry I'm not super used to writing up proposals... so hopefully this is the kindof thing you had in mind.  I drew some inspiration from react router, and also linked a draft PR that I think roughly implements the idea.  It creates an `exact` prop, which would preserve current behavior, while the absence of the exact prop would enable one to append additional characters to the url.

`<Route exact path="/path/to/page" />` <-- preserves behavior, only works for `/path/to/page`
`<Route path="/path/to/page" />` <-- enables any url of form `/path/to/page/*`

The first go that I linked below breaks when you refresh... not sure why.

https://github.com/redwoodjs/redwood/pull/3283/files

^^Is this the kindof thing you had in mind for a proposal? @mojombo

**Comment by Tobbe** [comment]
If we want to work with what we already have maybe something like this could work?

```
const userRouteParamTypes = {
  dir: {
    constraint: /.*/,
  },
  moreThingsDir: {
    constraint: /.*(?=\/more\/things)/,
  },
}

<Router paramTypes={userRouteParamTypes}>
  <Route path="/path/to/page/{fullDir:dir}" page={FullDirPage} name={fullDir} />
  <Route path="/path/to/page/{partialDir:moreThingsDir}/more/things" page={FullDirPage} name={fullDir} />
</Router>
```

If we want new syntax, what about `{...myVariable}`? as in `<Route path="/path/to/page/{...myvariable}" />` or `<Route path="/path/to/page/{...myVariable}/more/things" />`

**Comment by macovedj** [comment]
@Tobbe I think I see what you're saying... and will try and see if I can implement it in the draft PR I linked up above later.  For syntax,  I don't really have too many ideas... I guess what @peterp provided as suggestion above indicates that a wildcard was used... which feels expressive, always a good thing.  Since the number of "subfolders" or "/" characters in the var is not known in advance... I'm curious if people have opinions regarding a good way to systematically name each "subfolder" in the path.  The only thing I can think of is the bashish inspired arg syntax I referenced above.  Or I guess the dev utilizing this could just be responsible for doing a split on "/" and naming things as they wish?

**Comment by mojombo** [comment]
We often take cues from Rails on the routing side, @cannikin do you have thoughts here?

**Comment by peterp** [comment]
@Tobbe I really like that `{...myvariable}` syntax!

**Comment by macovedj** [comment]
Looks like this is the analog in rails https://guides.rubyonrails.org/routing.html#route-globbing-and-wildcard-segments

**Comment by Tobbe** [comment]
> Since the number of "subfolders" or "/" characters in the var is not known in advance... I'm curious if people have opinions regarding a good way to systematically name each "subfolder" in the path.

The way we currently handle this is with the `transform` option for the param types. See the docs for an example where it's split on '-' and you get an array of values.  https://redwoodjs.com/docs/redwood-router#user-route-parameter-types

**Comment by cannikin** [comment]
> We often take cues from Rails on the routing side, @cannikin do you have thoughts here?

In Rails you can specify a glob or wildcard variable that sucks up everything else in the URL and puts it into the variable name of your choice:

```ruby
get 'photos/*other'
```

Would provide you with a path param called `other` that contained everything else after `photos/`, for example:

```ruby
'/photos'         # params[:other] => nil
'/photos/new'     # params[:other] => 'new'
'/photos/show/1'  # params[:other] => 'show/1'
```

And then you can decide what to do with those extra parts in your own code.

You can have multiple wildcards in one route:

```ruby
get '*object/edit/*id'

'/user/posts/edit/12/34' # params[:object] => "/user/posts", params[:id] => "12/34"
```

Or include them with regular, named variables:

```ruby
get 'books/*section/:title'

'/books/fiction/sci-fi/Dune' # params[:section] => 'fiction/sci-fi', params[:title] => 'Dune'
```

You can even wildcard the whole URL if you want:

```ruby
get '*pages'
```

That syntax seems pretty clear and expressive to me. In our Router it could look like:

```jsx
<Route path="/books/{*section}" page={BooksBySection} name="booksBySection" />
```

I'm not sure about the `:` syntax as we're currently using that as a typing indicator: `{id:Int}` means "coerce the `id` variable to an `Int`". I read `{myvariable:*}` as "cast this to anything?" These path globbers would always return strings (unless we want to try and split on `/` and return an array of strings?).

Likewise the spread syntax `...` to me means "take this one enumerable thing and separate them out", which isn't what's happening here. It's just taking out a section of the path, as a string, and returning it, as a string. My gut reaction when seeing that syntax `{...myvariable}`was to look for a declaration of `myvariable` above to see what it is and how it's being substituted into that path—I thought it was some shared path string that you wanted to use in multiple routes and so rather than repeating them, just put them into a variable to be re-used across multiple routes.

**Comment by macovedj** [comment]
So I think that enabling the glob syntax from rails would require [this line](https://github.com/redwoodjs/redwood/blob/main/packages/router/src/util.ts#L24) which appears to parse the route params out of the route url to incorporate a ternary or something.  I think something along the lines of `match[0] === * ? match.slice(1) : match.split(:)`

**Comment by Tobbe** [comment]
I just tried this on gitpod

Router:
```
const userRouteParamTypes = {
  dir: {
    constraint: /.*/,
  },
}

const Routes = () => {
  return (
    <Router paramTypes={userRouteParamTypes}>
      <Route path="/nested/{fullDir:dir}" page={NestedPage} name="nested" />
```

Page
```
const NestedPage = ({ fullDir }) => {
  return (
    <>
      <h1>NestedPage</h1>
      dir: {fullDir}
    </>
  )
}
```

Result
![image](https://user-images.githubusercontent.com/30793/132917229-73aff2ce-cb6a-4fb4-8a21-7c15c5f9b589.png)

**Comment by KrisCoulson** [comment]
@Tobbe this seems like a pretty straightforward way of handling it does it breakdown with other named parameter?

**Comment by Tobbe** [comment]
First, just to be super clear, that example I gave is with *no* changes to RW at all. 100% current functionality.

@KrisCoulson you can have other parameters earlier in the route no problem, but it won't work if you try to have it after since it'll "eat" all that's left of the url.

BUT you should be able to make it work if you're more clever with your regex. Just need some way of telling the regex where to stop.

**Comment by macovedj** [comment]
@Tobbe I think I misinterpreted your earlier posts.  I noticed some similar looking code in redwood source code, and that you were referring to that.  I tried your suggestion and it seems to be working well... and I'm also making network requests based on the route params.  I think the only thing to point out is that if you wanted to have a route param of known length after a `dir` type route param... signifying the end of a `dir` type param is still up in the air from what I can tell.  Do you have thoughts about that?  I guess it might be an edge case... and you could just always save your `dir` type param for last... provided you only have one of them.

**Comment by thedavidprice** [comment]
Proposal Issue has been created here (by @macovedj) https://github.com/redwoodjs/redwood/issues/3375

**Comment by Tobbe** [comment]
> I think the only thing to point out is that if you wanted to have a route param of known length after a dir type route param... signifying the end of a dir type param is still up in the air from what I can tell.

I'm not sure I fully understand what you mean. Can you please provide an example or two? Thank you 😀

**Comment by macovedj** [comment]
Sure... do you know if the following would be supported?

`  <Route path="/nested/{fullDir:dir}/fixedString/{otherVar:String}" page={NestedPage} name="nested" />`

^^ The hope would be that the router is aware enough to interpret `fixedString` as a signifier that the `fullDir` variable is no longer being read from the url, and then move on to another variable.  If you only have one var of type `dir` then shouldn't matter too much because you could just leave that var at the end... 

`  <Route path="/nested/{otherVar:String}/{fullDir:dir}" page={NestedPage} name="nested" />`

unless you had query params after or something... in which case it might matter.

But if seems like it would definitely matter if you had two vars of type `dir`. 

`  <Route path="/nested/{fullDir:dir}/{subsequentDir:dir}" page={NestedPage} name="nested" />`

Does it also make sense to add something to the docs to make clear that the functionality you pointed out is available for devs?

**Comment by Tobbe** [comment]
> Sure... do you know if the following would be supported?
> 
> ` <Route path="/nested/{fullDir:dir}/fixedString/{otherVar:String}" page={NestedPage} name="nested" />`

I haven't tried it, but I think this should do it

```
const userRouteParamTypes = {
  dir: {
    constraint: /.*(?=\/fixedString)/,
  },
}

<Router paramTypes={userRouteParamTypes}>
  <Route path="/nested/{fullDir:dir}/fixedString/{otherVar:String}" page={NestedPage} name="nested" />
</Router>
```

> <Route path="/nested/{otherVar:String}/{fullDir:dir}" page={NestedPage} name="nested" />

The above should be covered by the basic example I showed earlier with just `constraint: /.*/,`

> `<Route path="/nested/{fullDir:dir}/{subsequentDir:dir}" page={NestedPage} name="nested" />`

If you had a url like /nested/a/b/c/d/e/f what would you want in `fullDir` and what should end up in `subsequentDir`?

> Does it also make sense to add something to the docs to make clear that the functionality you pointed out is available for devs?

More advanced examples like these for how to use `paramTypes` sounds like a great idea! Are you up for adding some?

**Comment by macovedj** [comment]
I think I'm trying to express that your `/nested/a/b/c/d/e/f` example is inherently ambiguous.  As a dev, If I want `fullDir` to end after any letter, and/or `subsequentDir` to begin at any letter, how do I specify that with the current capabilities?  Also I'm happy to give the advanced examples a go.

**Comment by Tobbe** [comment]
You could do something like `/(\w+\/){3}/` for your constraint I think, and it would be a/b/c/ or change the 3 to 4 and it'd be a/b/c/d/

**Comment by cannikin** [comment]
@mojombo and I had an API brainstorming session and settled on a syntax we like!

```jsx
<Route path="/books/{details...}" page="BooksPage" name="books" />
```

It even reads kinda like real text—the ellipsis implies "and everything else..."! The value that's returned is *always* a string and contains no additional processing (don't try to split on `/` and turn into an array, for example).

It should let you:

1. have additional URL parts after the glob
2. have multiple globs
3. mix with regular variables

```jsx
<Route path="/files/{path...}/edit" page="PhotosPage" name="photos" />
<Route path="/photos/{categories...}/modify/{options...}" page="PhotosPage" name="photos" />
<Route path="/products/{shelf...}/{id:Int}" page="PhotosPage" name="photos" />
```

If you include the glob, it must match *something*. This means that given these two routes:

```jsx
<Route path="/books" page="BooksPage" name="books" />
<Route path="/books/{details...}" page="BooksDetailPage" name="booksDetail" />
```

Then the following URLs would *only* match the first route:

* https://example.com/books
* https://example.com/books/

And these would match the second:

* https://example.com/books/fiction
* https://example.com/books/fiction/
* https://example.com/books/fiction/authors/Claire-North
* https://example.com/books/123
* https://example.com/books/-

But given only a single globbing route:

```jsx
<Route path="/books/{details...}" page="BooksDetailPage" name="booksDetail" />
```

Then the URL `https://example.com/books` would be a 404.

---

How does that feel @macovedj? Does that cover all of your use cases?

**Comment by thedavidprice** [comment]
@macovedj given the above API syntax via @cannikin and @mojombo, is this something you'd like to take on? It's a great candidate for including in v1 requirements, but not something anyone on the core team is able to take on at this time. No pressure. Just communicating status.

**Comment by macovedj** [comment]
Hi all.  @cannikin and @mojombo that syntax seems like it certainly gets the job done to me.  Happy to take it on... but also @Tobbe I'm curious what you think, given the points you've made about what is already supported.  Does it maybe just make sense to make a new glob [coreParamType](https://github.com/redwoodjs/redwood/blob/main/packages/router/src/util.ts#L36)?  I think if  we implement the logic you've mentioned Tobbe in that file I linked... then we can keep people from having to add that as boilerplate to their project whenever want to implement this functionality.  And then we could add something to the docs about that paramType that redwood offers.  Would love to get whether or not that is a good idea finalized before picking it up... and also I'm up for collaborating/pairing if anybody wants to do that.

**Comment by cannikin** [comment]
> we can keep people from having to add that as boilerplate to their project whenever want to implement this functionality

Hmm, there shouldn't be any boilerplate needed from the developer's standpoint—this is a brand new syntax that will just be supported automatically. The Router code needs some updated logic to look for `...` and act accordingly. If it's by associating that syntax to a new `coreParamType` then that's cool, but the end user would never know that's what's actually happening.

It seems like adding a new "glob" type or whatever we want to call it, and adding a constraint regex that matches "everything until the end of the string or a `/`" would do the trick. Everything else should magically work! Looks like it's time for some [positive lookaheads](https://www.regular-expressions.info/lookaround.html)!

**Comment by cannikin** [comment]
Sounds good! Yeah I read your previous post as "let's add a core type that the user can use" and that the syntax in the actual routes file would look something like `/photos/{path:glob}`. 

But if that's what's actually happening behind the scenes to enable the preferred `{path...}` syntax, then that's awesome!
