### ISSUE TITLE
Throw better/specific errors when sdl files can't be parsed

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3264]
`yarn rw dev` does not throw errors on what sdls/imports could not be processed - instead we get a puzzling 404 function not found 

```json
{"error":"Function \"graphql\" was not found.","availableFunctions":["..."]}
```

What's important to note is that this seems to happen at **runtime** - not at buildtime.

### How to reproduce
SDLs do not support the `"""` comment syntax (to be looked into separately). So in any sdl, we can add a comment like this

```
export const schema = gql`
  type User {
    id: String!
    email: String!
"""
comment <----------------------- bad!
"""
```
And it should error out

### Expected behaviour
Better errors logged to console, so it can be debugged more easily.

**Comment by peterp** [comment]
I'm think we could get build-time errors if we fixed #3193

**Comment by dac09** [comment]
> I'm think we could get build-time errors if we fixed #3193

I was just thinking this!

**Comment by dac09** [comment]
Linking graphql-tools issue: https://github.com/ardatan/graphql-tools/issues/3244

**Comment by dthyresson** [comment]
My understanding having asked The Guild is that the following comments/descriptions should be permitted:

* single line description
```

" test "
type Query { ... }
```

* multiline description:

```
"""
this
is 
a
test
"""
type Query { ... }
```

* legacy (now used ONLY for comments, not descriptions):

```
# test 
type Query { ... }
```

![image](https://user-images.githubusercontent.com/1051633/130545411-1c66b7e9-5852-4cb1-8438-f6cea2aa7b99.png)

**Comment by dac09** [comment]
Closing as resolved in downstream dependency
