### ISSUE TITLE
MetaTags component causes tests to fail

### ISSUE THREAD

**Issue by domnantas** [redwoodjs/redwood#3268]
### Steps to reproduce

1. `yarn create redwood-app name`
2. `yarn rw g page home`
3. `yarn rw test`

Test fails with `Cannot read property 'add' of undefined`. Running `yarn rw storybook` shows the same error when page is rendered in the browser.

Removing `<MetaTags>` component from the page fixes the issue

Node v14.17.5

**Comment by simoncrypta** [comment]
This error came from react-helmet-async : https://github.com/staylor/react-helmet-async/issues/99 
I will work on a fix ASAP 😁 thank you for reporting this bug.
