### ISSUE TITLE
Scaffold generator ignores relations

### ISSUE THREAD

**Issue by weaversam8** [redwoodjs/redwood#327]
This issue is for improving Redwood's relation support (see #316).

------------------------------------------------

## Summary

When running `yarn rw generate scaffold ModelName`, if a model include relations, the scaffolded pages will all (or almost all) be broken. This primarily comes from generating invalid GraphQL queries.

## Example

If we use the following example schema (`prisma.schema`)

```prisma
// datasource + generator statements omitted
// [...]

model IceCream {
  id       String @id @default(cuid())
  flavor   String
  toppings Topping[]
}

model Topping {
  id   String @id @default(cuid())
  name String
}
```

The [Cell](https://redwoodjs.com/tutorial/cells) to display a single `IceCream` (`web/src/components/IceCreamCell/IceCreamCell.js` will generate a GraphQL query like this:

```js
export const QUERY = gql`
  query FIND_POST_BY_ID($id: String!) {
    iceCream: iceCream(id: $id) {
      id
      flavor
      toppings
    }
  }
`
```

This is strictly not valid GraphQL. Since `toppings` is a relation, referencing the `Topping` model, the query would need to select some subfields. In the above example, modifying the query to the following would fix the problem.

```js
export const QUERY = gql`
  query FIND_POST_BY_ID($id: String!) {
    iceCream: iceCream(id: $id) {
      id
      flavor
      toppings {
        id
      }
    }
  }
`
```

Additionally, the `IceCream` component itself would need to be modified to reference the `iceCream.toppings.id` field instead of just `iceCream.toppings`.

## Solution

> Although scaffolds will probably never be built out to the point of adding forms for relationships, the SDL and service generators should be able to introspect and build them when possible. [[source]](https://github.com/redwoodjs/redwood/issues/316#issuecomment-602274285)

[It is an open question](https://github.com/redwoodjs/redwood/issues/316#issuecomment-602274285) exactly how much the scaffolding generator should assume, but I think we can agree that it shouldn't generate broken code when relations are involved. 

We don't know for sure what fields we should query for on an item that has a relation, but maybe for starters, we can assume an `id` field exists, query for that, and display a hyperlinked ID in the generated pages when displaying a relation. [(There's already evidence that we enforce an ID column to exist on all generated models.)](https://github.com/redwoodjs/redwood/blob/master/packages/cli/src/commands/generate/commands/sdl.js#L37-L43)

This is probably a big PR, but definitely necessary.

**Comment by jkntji** [comment]
I just hit this issue, while trying to make a simple app.

**Comment by Jaikant** [comment]
I just hit this issue, while attempting to build a simple app.

**Comment by cannikin** [comment]
@Jaikant We're working on adding support to our SDL generator for relations, but you can always write the code manually to get them working. Here's some example code that you would add to your service: https://github.com/redwoodjs/redwood/issues/316#issuecomment-603466685 I've verified this in the example-blog branch here (see the `Post` export at the very bottom): https://github.com/redwoodjs/example-blog/blob/rc-prisma-beta/api/src/services/posts/posts.js This allows the GraphQL to return tags inside of a post using a query like:

```gql
export const QUERY = gql`
  query ALL_POSTS() {
    allPosts() {
      id
      title
      body
      tags {
        id
        name
      }
    }
  }
```
