### ISSUE TITLE
Sunset Apollo Server and make GraphQL Helix and Envelop default

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#3271]
RedwoodJS v0.37 aims to sunset the use of Apollo Server as the GraphQL server and instead use GraphQL Helix and Envelop that has been an experimental preview feature.

To this end, first need to repackage GraphQL Helix and Envelop into `api` from `graphql-server`:

- [ ] Deprecate `@graphql-server` package in v0.37 and remove each of a release candidate (v.38?)
- [ ] Migrate `@graphql-server` use of Helix and envelop to `api` package
- [ ] Ensure e2e tests pass

There are other tasks related to this effort, but will be created as separate issues and PR's.

This includes 

- [ ] use of `apollo-server-lambda` in errors.
- [ ] logic in dev server for `useEnvelop` experimental feature
- [ ] Remove Helix/Envelop e2e integration scenario

**Comment by peterp** [comment]
@dthyresson I would suggest just keeping the `@redwoodjs/graphql-server` package and instead deprecating the `api` package, the reason for this is that I would like to introduce some other ways of building api's that aren't graphql, and it makes sense to call the package `graphql-server`

**Comment by dthyresson** [comment]
I will close this PR and start afresh.

**Comment by dthyresson** [comment]
> @dthyresson I would suggest just keeping the `@redwoodjs/graphql-server` package and instead deprecating the `api` package, the reason for this is that I would like to introduce some other ways of building api's that aren't graphql, and it makes sense to call the package `graphql-server`

I can see both sides of the case to have api or graphql-server (or both ... or to have one import the other, or vise versa), but having an api package seemed a clean approach and I began to outline the rationale in the PR that @dac09 and @thedavidprice were going to continue to explain the case for this approach after our Monday morning checking here:

```
Rationale for removing graphql-server:

* Clear packaging - your api is serverless functions, services, and your graphql endpoint
* Single package for where Global Context lives is critical because we have seen that the Global Context can get confused if set in Envelop-based AuthContext such that using context in services leads to authentication issues
* Ease transition for existing apps using api
* Fewer documentation changes. Do not need to explain api vs graphql-server and how, why and when to use
* Less dependencies (api doesn't depend of graphql-server for the graphql implemetation and graphql-server doesn't depend off api for logger, webhooks, etc
* Easier to manage and generate envelop plugins and GraphQL directives
```

Would you mind clarifying a few items if we keep and transition more to to graphql-server package:

* Do you mean to deprecate the *entire* api package -- or just the graphql portions of it? 
* Would logger, webhooks, Serverless functions (and tests) all move the `graphql-server`?
* Do services live in api or graphql-server? Might I not have services that are not used by a graphql resolver, but used by a serverless function?
* Does api/auth, its providers, decoders also move to graphql-server?
* How does this change impact the CRWA templates for the graphql function -- does it import `api` or `graphql-server`?
* How does this change impact documentation that says RedwoodJS has an "api side"? 
* How does this change documentation such as service testing that refers to the api (https://redwoodjs.com/docs/testing#writing-service-tests)
* Does the Global Context now live in `graphql-server` and gets auto-imported? See: https://github.com/redwoodjs/redwood/blob/bb814ca0ab8d188cc1a8d14ecdb7619fbdca0125/packages/internal/src/build/babel/api.ts#L41 
* We have seen this become an issue where context.currentUser can be null if created in graphql-server, but context is auto-imported from api.
```js
          {
            // import { context } from '@redwoodjs/api'
            members: ['context'],
            path: '@redwoodjs/api',
          },
        ],
```

**Comment by peterp** [comment]
@dthyresson My apologies for throwing a spanner in the works. I thought I communicated the intentions to remove GraphQL from `@redwoodjs/api` package at the start of the envelop journey, but am understood to be poor at communication, so I apologize for not being clearer when we started this work.

Also, please note that I commented on this issue before the PR was linked to it and I did not realize the work was already done, so my suggestion was more of a "hey before you do this work... think about this... let's have a conversation" rather than a "hey... you done all the work already, but I don't care, so please change."

**Comment by peterp** [comment]
I'll try to answer your questions here, but maybe we should jump on a call to chat it over.

> Do you mean to deprecate the entire api package -- or just the graphql portions of it?

Just the GraphQL portion!

> Do services live in api or graphql-server? Might I not have services that are not used by a graphql resolver, but used by a serverless function?

I think they should live in `/api`

> Does api/auth, its providers, decoders also move to graphql-server?

Nope, they should stay in `/api`


> How does this change impact the CRWA templates for the graphql function -- does it import api or graphql-server?

Yup.

> How does this change impact documentation that says RedwoodJS has an "api side"?

Nope, it's still true - it's just that the graphql-server part is in a different package.

> Would this change the dev and api server? What does it mean to start the api side? Is api-server now graphql-server-server?

It won't change anything.

> How does this change documentation such as service testing that refers to the api (https://redwoodjs.com/docs/testing#writing-service-tests)

Nope.

> Does the Global Context now live in graphql-server and gets auto-imported? 

This would still live in the api-package.

>  // import { context } from '@redwoodjs/api' 
> We have seen this become an issue where context.currentUser can be null if > created in graphql-server, but context is auto-imported from api.

I would love to understand this better - in my mind this shouldn't be the case, but probably something that I can help with figuring out.

**Comment by dthyresson** [comment]
> I'll try to answer your questions here, but maybe we should jump on a call to chat it over.

Thanks @Peter - this helps: api is ... auth, functions/webhooks, logging, maybe Global Context?  (common api infrasctructurish items ... though are functions/webhooks too Lambda-y?) -- and graphql-server is the schema, parsing, http request pipeline, plugins ... and mapping a resolver to the service. 

An app's api -- if exposing a GraphQL endpoint-- will use both redwoodjs/api and redwoodjs/graphql-server. If the api has some other serverless function that returned a basic RESTful JSON api (json-api.ts) then it might use some other redwood package to implement that data fetching (maybe using same services), then doing that serialization and request/response handling.

Let me and @dac09 walk through these points and then we perhaps can chat, but I think I get it now. Cheers.

> // import { context } from '@redwoodjs/api'
> We have seen this become an issue where context.currentUser can be null if > created in graphql-server, but context is auto-imported from api.
> I would love to understand this better - in my mind this shouldn't be the case, but probably something that I can help with figuring out.

@dac09 Just wrote some envelop plugin tests for setting the global context in the graphql handler and may have reproduced it. Will be able to show you once we confirm.

**Comment by peterp** [comment]
Ok, great! And sorry again for the miscommunication - let me know if you need any help.
