### ISSUE TITLE
Issue importing deeply nested files such as services via CLI Exec feature

### ISSUE THREAD

**Issue by viperfx** [redwoodjs/redwood#3279]
There are two main issues i've come across with the CLI exec feature and how it's currently doing importing.

- Yarn workspace and shared packages cannot be used - there is an issue picking it
- Imports (relative and aliased) must be used with a lot of care. The exec feature needs to use `../api/src/....` where most of the codebase has an alias to use `src/...` which pick it up from `api/src`

### Reproduction Repo
https://github.com/viperfx/rw-cli-import-issue

- clone this repo
- install deps
- run yarn rw prisma migrate dev
- run either yarn rw exec aliasImport or yarn rw exec relativeImport
- Both produce a import error.

### Loom video discussing issues

https://www.loom.com/share/a270c72668ae4030902a2e0c3c7e8b9d

### Current Blockers
- This is currently preventing me from running background workers with my production application.
- One of scripts or scheduled scripts (run via repeater.dev) also also prevented from using deeply nested files in api.

**Comment by dac09** [comment]
the fix will need to take into consideration if the user is also importing from the web side.
So I think... it would need to:

- use the overrides option in babelRegister (not the plugins one), and add the alias for src to web and api both
- Figured out why TS doesn't work with these imports: we should add $api and $web to the tsconfig - but should be a tsconfig in the scripts folder only. We will probably
