### ISSUE TITLE
Determine if api pre-transpilation is including polyfills

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#3280]
Babel transpiles syntax and includes polyfills. I'm not 100% sure if we're properly handling the polyfill case in pre-transpilation.

- [x] Write a test case that proves pre-transpilation is inserting polyfills correctly.

@dac09 Wanted to put this potential issue on your radar.

**Comment by peterp** [comment]
I can confirm that we are not doing any polyfilling, an example of such thing is:

```js
'dog dog dog'.replaceAll('dog', 'cat')
```

The `.replaceAll` method was introduced in `V8  8.5`, and NodeJS 14 only support `V8 8.4`, so we need to polyfill this method and in order to do that we need to import it from `core-js`, this can be done automatically with `@babel/preset-env` or `@babel/runtime`

I think using `@babel/preset-env` will also transpile the syntax, which is something that we don't want, since we transpile the code with ESBuild a bit further down the line because it's fast.

I'm going to test `@babel/runtime` and ESBuild to calculate how fast it is. If `@babel/runtime` is slow then I'll use `@babel/preset-env` and remove ESBuild.

**Comment by dac09** [comment]
There really ought to be an equivalent esbuild plugin or something right? Their docs leave so much to be desired!

**Comment by peterp** [comment]
I actually got the idea that this polyfill issue might be a problem whilst I was digging into building the framework via ESBuild or SWC:

I was evaluating both tools by transpiling the `@redwoodjs/api` package, but I couldn't run the ESBuild version because it was not polyfilling methods. When I dug a bit deeper it realized that ESBuild is JUST a bundler and it transpiles syntax, but it doesn't offer any additional support beyond that, and polyfilling is determined to be ["out of scope"](https://github.com/evanw/esbuild/issues/1415#issuecomment-873350428).

SWC does transpiles syntax, polyfills, but the transpiled syntax I tried on the RedwoodJS project had [some syntax errors.](https://github.com/redwoodjs/redwood/pull/3266#issuecomment-903299206).

I think eventually we'll get the most mileage out of SWC, but it's too early to be considered stable enough.

**Comment by peterp** [comment]
[The current relationship between Babel and `core-js` (2019).](https://github.com/babel/babel/issues/10008#user-content-annex-b) is super useful to understand how Babel is thinking about polyfills, and their future, the result of this RFC is the [@babel/babel-polyfills](https://github.com/babel/babel-polyfills) package.

I'm going to use the babel-polyfill package.

**Comment by peterp** [comment]
### Next steps:

- [ ] Make it work:
- [ ] Try examples from babel polyfill documentation.
- [ ] Write test case.
---
- [ ] Make it right:
- [ ] Create common function to get babel configuration.
- [ ] Get targets for browserlist.
- [ ] Create function to convert browserlist to esbuild configuration.
- [ ] Use common configuration in "parse", "register" and "transpile."
- [ ] Use pre-transpilation for web side.
