### ISSUE TITLE
yarn rw g scaffold seems broken

### ISSUE THREAD

**Issue by moorels** [redwoodjs/redwood#3292]
getting Response not successful: Received status code 400   Unknown type "CreateUserInput". when i try to access users url  to create a new user. in a basic user scaffold

so when i created a new project and created a basic user model scaffold ,it seems be generating weird files like
users.js.map with this content below, inside the api/services folder and also the api/graphql folder has similar files generated

all was fine until the last update i could create scaffolds no problem..

this inside the users.js.map which i have never seen that file generated before

{
  "version": 3,
  "sources": ["../../../src/services/users/users.js"],
  "sourcesContent": ["import { db } from 'src/lib/db'\nimport { requireAuth } from 'src/lib/auth'\n\n// Used when the environment variable REDWOOD_SECURE_SERVICES=1\nexport const beforeResolver = (rules) => {\n  rules.add(requireAuth)\n}\n\nexport const users = () => {\n  return db.user.findMany()\n}\n\nexport const user = ({ id }) => {\n  return db.user.findUnique({\n    where: { id },\n  })\n}\n\nexport const createUser = ({ input }) => {\n  return db.user.create({\n    data: input,\n  })\n}\n\nexport const updateUser = ({ id, input }) => {\n  return db.user.update({\n    data: input,\n    where: { id },\n  })\n}\n\nexport const deleteUser = ({ id }) => {\n  return db.user.delete({\n    where: { id },\n  })\n}\n"],
  "mappings": ";;;;;;;;;;;;;;;;;;;;;;;AAAA;;;;;;;;gBAAA;AACA,kBAAA;AAGO,MAAM,iBAAkB,WAAU;AACvC,QAAM,IAAI;;AAGL,MAAM,QAAQ,MAAM;AACzB,SAAO,aAAG,KAAK;;AAGV,MAAM,OAAO,CAAC;EAAE;MAAS;AAC9B,SAAO,aAAG,KAAK,WAAW;IACxB,OAAO;MAAE;;;;AAIN,MAAM,aAAa,CAAC;EAAE;MAAY;AACvC,SAAO,aAAG,KAAK,OAAO;IACpB,MAAM;;;AAIH,MAAM,aAAa,CAAC;EAAE;EAAI;MAAY;AAC3C,SAAO,aAAG,KAAK,OAAO;IACpB,MAAM;IACN,OAAO;MAAE;;;;AAIN,MAAM,aAAa,CAAC;EAAE;MAAS;AACpC,SAAO,aAAG,KAAK,OAAO;IACpB,OAAO;MAAE;;;;",
  "names": []
}

also the users.js file in api/services has this content
```js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
__export(exports, {
  beforeResolver: () => beforeResolver,
  createUser: () => createUser,
  deleteUser: () => deleteUser,
  updateUser: () => updateUser,
  user: () => user,
  users: () => users
});
var import_db = __toModule(require("..\\..\\lib\\db"));
var import_auth = __toModule(require("..\\..\\lib\\auth"));
const beforeResolver = (rules) => {
  rules.add(import_auth.requireAuth);
};
const users = () => {
  return import_db.db.user.findMany();
};
const user = ({
  id
}) => {
  return import_db.db.user.findUnique({
    where: {
      id
    }
  });
};
const createUser = ({
  input
}) => {
  return import_db.db.user.create({
    data: input
  });
};
const updateUser = ({
  id,
  input
}) => {
  return import_db.db.user.update({
    data: input,
    where: {
      id
    }
  });
};
const deleteUser = ({
  id
}) => {
  return import_db.db.user.delete({
    where: {
      id
    }
  });
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  beforeResolver,
  createUser,
  deleteUser,
  updateUser,
  user,
  users
});
//# sourceMappingURL=users.js.map
```

**Comment by jtoar** [comment]
Hey @moorels sorry things aren't working for you. The files you're talking about sound like the files in `api/dist`, which are the result of running your code through babel and esbuild.

Do you mind sharing more details about this User model? Maybe there's a field in there that we don't have support for yet that's causing issues for you.

**Comment by moorels** [comment]
Im running  a basic 

 

model User {

  id    Int     @id @default(autoincrement())

  email String  @unique

  name  String?

}

 

From a fresh redwood installation 

 

No other models

**Comment by moorels** [comment]
Im running  a basic fresh redwood installation

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}

From a fresh redwood installation 

No other models

**Comment by iamgmd** [comment]
I can confirm the same problem 'Response not successful: Received status code 400' when following the tutorial. When using 'yarn rw g scaffold post', the graphql query/types/etc are created but the posts.sdl.js schema is not picked up at runtime and merged causing a GRAPHQL_VALIDATION error.

**Comment by moorels** [comment]
thanks hopefully its fixed next update 
i thought i was going crazy :)

**Comment by cannikin** [comment]
@iamgmd and @moorels are either of you using Windows?

**Comment by cannikin** [comment]
On macOS I just created a brand new app from scratch with `yarn create redwood-app` and created a single user model: 

```
model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

And then a scaffold and everything is working as expected.

Can you give us the output of running `yarn rw info` please?

**Comment by iamgmd** [comment]
@cannikin Yes, the problem reported was running Windows, I can confirm that everything works as expected on a Mac.

**Comment by iamgmd** [comment]
@cannikin The output of 'yarn rw info' on Windows:-

C:\Code\RedwoodJs\redwoodblog>yarn rw info
yarn run v1.22.11
$ C:\Code\RedwoodJs\redwoodblog\node_modules\.bin\rw info

  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.17.6 - ~\AppData\Local\Temp\yarn--1630512577029-0.677367170914223\node.CMD
    Yarn: 1.22.11 - ~\AppData\Local\Temp\yarn--1630512577029-0.677367170914223\yarn.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.84)    
  npmPackages:
    @redwoodjs/core: 0.36.2 => 0.36.2

Done in 2.80s.

**Comment by cannikin** [comment]
@iamgmd Thanks! We think this problem actually stems from this issue, which should be fixed soon: https://github.com/redwoodjs/redwood/pull/3311

**Comment by iamgmd** [comment]
@cannikin Thanks for triarging so quickly, I will continue to work on macOS until it is fixed.

**Comment by moorels** [comment]
yes i checked on 3 computers running windows and same problem across all 3

**Comment by cannikin** [comment]
I'm going to close this in favor of tracking #3311, thanks!
