### ISSUE TITLE
@db.Text throws error on migration

### ISSUE THREAD

**Issue by shansmith01** [redwoodjs/redwood#3299]
Hi There,

I'm following along on the tutorial and I am on this page https://learn.redwoodjs.com/docs/tutorial/getting-dynamic

When I attempt to migrate i get the following error

"Native type Text is not supported for sqlite connector."  relating to the use of @db.Text on the body

Is it me or is it a bug?

Thanks for the help

**Comment by callingmedic911** [comment]
It looks like an issue with the doc to me. I think we're using for SQLite for this tutorial and Prisma maps `String` to `TEXT` for SQLite [by default](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#default-type-mappings). Also `@db.Text` native mapping is supported only in Postgres, MySQL and SQL Server. 

@cannikin What do you think?

**Comment by dthyresson** [comment]
> It looks like an issue with the doc to me. I think we're using for SQLite for this tutorial and Prisma maps `String` to `TEXT` for SQLite [by default](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#default-type-mappings).

Thanks @callingmedic911 for looking into this issue -- I agree that this is an issue in the Tutorial documentation as SQLite does not support native types and a simple String is the proper way to declare the title and body:

See: https://www.prisma.io/docs/concepts/database-connectors/sqlite

It uses `TEXT`. I think a long time ago Prisma used VARCHAR or some shorter type for string and here in the tutorial they explicitly wanted to use a longer TEXT column.

Let's add an issue in the website repo if this is the case.

**Comment by cannikin** [comment]
Why does Prisma not just map this to the native SQLite data type? The type in SQLite is literally called `TEXT`...they couldn't just map `@db.Text` to `TEXT`!?!?! C'MON.

Isn't this the whole point of a decoupled schema, so you can write one consistent way and have a computer translate it into something else for you? 😢

This is just one PR: https://github.com/redwoodjs/learn.redwoodjs.com/pull/145 that I made to close: https://github.com/redwoodjs/learn.redwoodjs.com/issues/76 which, apparently, was a bad idea.

**Comment by cannikin** [comment]
Just reverted, site should be updated soon.

**Comment by cannikin** [comment]
Opened an issue with Prisma to see if I can convince them to allow this syntax! https://github.com/prisma/prisma/issues/9012

**Comment by cannikin** [comment]
Site's updated, thanks for the note @shansmith01, sorry for the confusion!

**Comment by shansmith01** [comment]
No probs. Thanks, Y'all.
