### ISSUE TITLE
`TypeError: Cannot read property 'add' of undefined` when using MetaTags component with Storybook

### ISSUE THREAD

**Issue by bashbaugh** [redwoodjs/redwood#3300]
Self-explanatory. Unless I've somehow broken things, the `MetaTags` component from `@redwoodjs/web` doesn't work when used with the default storybook config.

![image](https://user-images.githubusercontent.com/32651204/131235839-89f83e9b-6542-428e-8dfb-c8cfd1ba0612.png)

I will try to research this further & fix with a PR sometime this week.

**Comment by simoncrypta** [comment]
Hey @bashbaugh what is your version of Redwood ? It should be fix at the [patch release V0.36.2](https://community.redwoodjs.com/t/redwood-v0-36/2372/20) from PR #3269

**Comment by bashbaugh** [comment]
Ah, thank you. I thought I was on the latest version but I guess not.
