### ISSUE TITLE
Can't create redwood app with an arbitrary version

### ISSUE THREAD

**Issue by ajoslin103** [redwoodjs/redwood#3304]
How do I create a redwood app on an arbitrary version?

Say I wanted to create an app on 0.33 as opposed to the current 0.36.2

(it doesn’t look like version is an option in the create-redwood-ap.sh)

As much as I like keeping up with the leading edge - Webpack 5 support is _killing_ me right now at  a crucial juncture

Thanks!

**Comment by macovedj** [comment]
For the time being does retroactively changing your package file versions to use that version work for you?

**Comment by ajoslin103** [comment]
I tried downgrading by specifying an older tag with the upgrade command

didn't work 

I have since (i think) dealt with my problems w/webpack 5

so the pressure is off -- but since it wasn't behind a flag I felt dumped upon 

I think we should have the option while we are pre-release but it's not a panic anymore

cheers!

**Comment by ajoslin103** [comment]
I ended up copying the /api & /web folders into a copy of an old 35.2 project - so the pressure is off.

I still think it's a good idea tho'

Also, now I understand what you meant - deleting all node_modules folders and changing the redwood version #'s and rebuilding.

Thanks

**Comment by jtoar** [comment]
You should be able to do this in two steps:

```
yarn install -g create-redwood-app@0.35.2
create-redwood-app my-redwood-project
```

What `yarn create redwood-app` actually does is 1) install the latest version of the create-redwood-app binary globally, and then 2) run it with the args you provided.

Unfortunately yarn doesn't have a way to do it all in one go, but you can achieve the same effect by separating the steps.

**Comment by ajoslin103** [comment]
very nice !!

we'll call this one closed, thanks very much !

**Comment by Tobbe** [comment]
yarn has had an issue open about this since 2018 https://github.com/yarnpkg/yarn/issues/6587

**Comment by ajoslin103** [comment]
FWIW: RW is a lot more stable now and I haven't needed to roll back anything since then.

**Comment by jtoar** [comment]
> the command now is more like:
> ```
> yarn global add create-redwood-app@4.1.0-canary.630
> ```

For those using yarn 3 everywhere, `yarn global` isn't a thing anymore. Instead, using `yarn dlx` (which is yarn's equivalent of npm's `npx`):

```
yarn dlx create-redwood-app@<version> <path>
# example
yarn dlx create-redwood-app@3.6.0 my-redwood-app
```

But there's a catch: this only works for stable versions. As in, 3.6.0, 3.5.0, etc. Not canary or RC versions—it looks like there's a bug in our publishing process there. You'll just end up getting the latest stable version of the packages. But you can go into the package.json's and manually change the versions.

**Comment by Tobbe** [comment]
I tried `dlx`, but got this
![image](https://user-images.githubusercontent.com/30793/219497440-c635a016-3500-4eaf-a209-0cfb175749df.png)

So I used `npx` instead, and that worked fine. But just like with dlx I also couldn't use `@canary`

**Comment by jtoar** [comment]
@Tobbe yeah that'll only work with yarn 3; you can try `yarn global` if you're on yarn 1.

**Comment by Tobbe** [comment]
Thanks to some updates I did over the weekend `npx create-redwood-app@canary` should now also use the latest canary versions of the RW packages in the app you create

For anyone interested:
The changes to make the above possible started with this PR: https://github.com/redwoodjs/redwood/pull/8862
And the last one (as of now) is this one: https://github.com/redwoodjs/redwood/pull/8868
GitHub Actions are a pain to debug locally. Especially when it involves publishing new packages to npm, so it took a few tries to get it right 🙂
