### ISSUE TITLE
Netlify deploy issue with @clerk/clerk-sdk-node

### ISSUE THREAD

**Issue by noire-munich** [redwoodjs/redwood#3312]
Deploying on netlify with v0.36.2 outputs this issue:

```
10:27:43 AM:   2. Functions bundling                                         
10:27:43 AM: ────────────────────────────────────────────────────────────────
10:27:43 AM: ​
10:27:43 AM: Packaging Functions from api/dist/functions directory:
10:27:43 AM:  - graphql.js
10:27:43 AM:  - stripeWebhook.js
10:27:43 AM: ​
10:27:43 AM:  > node_modules/@redwoodjs/api/dist/auth/decoders/clerk.js:15:14: error: Could not resolve "@clerk/clerk-sdk-node" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
10:27:43 AM:     15 │   } = require('@clerk/clerk-sdk-node');
10:27:43 AM:        ╵               ~~~~~~~~~~~~~~~~~~~~~~~
10:28:21 AM: ​
10:28:21 AM: ❯ Failed to bundle functions with selected bundler (fallback used):
10:28:21 AM:    - graphql.zip
10:28:21 AM: ​
10:28:21 AM: (Functions bundling completed in 38.5s)
```

Resulting in a failed build.

Running this seems to fix it:
```
yarn workspace api add @clerk/clerk-sdk-node
```

I'm not sure this is specific to v0.36.x so it might be worth some lookin'.

**Comment by thedavidprice** [comment]
cc @dac09 

Hi @noire-munich I took a stab at recreating this with my test project (which does not use Clerk) but didn't run into any issues.

I know Danny changed the import recently so it would only be required in the case of using Clerk Auth, but it's possible things aren't working quite right after the change.

Related code here:
https://github.com/redwoodjs/redwood/blob/96cde295f11f823f8f9f53dffe0aed5d7c86c007/packages/api/src/auth/decoders/clerk.ts#L8-L10

Could you provide more info about your setup:
- are you using Clerk Auth?
- is this still an issue with v0.36.4?

**Comment by dac09** [comment]
The import was tested and deployed on the auth playground. I suspect its just node_modules not installing, or that your api/package.json doesn't have the clerk-sdk-node (did you use the setup cli command?)

**Comment by noire-munich** [comment]
Hi @thedavidprice and @dac09 

> are you using Clerk Auth?
and
> did you use the setup cli command?

Actually my project has never been using Clerk Auth, I wasn't aware of it until this error popped on netlify logs - hence I opened the issue, these choices have always been opt-in on RW and we didn't opt in that one.
We're still using Firebase for auth on our side.
Netlify, however, hopefully will not be around for long - but since it's sort of the provider to try out RedwoodJS, this could deserve a look.

> is this still an issue with v0.36.4?
Don't know yet, haven't made the upgrade. If I don't manage a swift switch to render.com I'll give it a look and report :).

**Comment by thedavidprice** [comment]
> Actually my project has never been using Clerk Auth

Whelp, this makes me nervous. My best guess here is that this package got stuck in your resolutions around v0.35 before @dac09 made the change for this package to only be required if Clerk Auth is being used.

Curious that you're not seeing this locally (correct)? In that case, might also have something to do with Netlify's build cache not updating.

**Comment by noire-munich** [comment]
Got me nervous too! But in itself the fix was straightforward.

I didn't have it locally, deploying on netlify made me aware of it.
In the past months I've had a lot of deploys on netlify where I came to doubt it's cache cleaning process, but I couldn't completely confirm it. It can show with changes in environment variables, for instance.
Maybe we should involve someone from their team to look into this with us.
