### ISSUE TITLE
Custom GraphQL Directives not working

### ISSUE THREAD

**Issue by RobertBroersma** [redwoodjs/redwood#333]
**Directive**
```javascript
import { SchemaDirectiveVisitor } from 'graphql-tools'
import { defaultFieldResolver } from 'graphql'

export class AuthDirective extends SchemaDirectiveVisitor {
  visitFieldDefinition(type) {
    const { resolve = defaultFieldResolver } = type
    type.resolve = async function(...args) {
      const result = await resolve.apply(this, args)

      console.log('This log does not show!')

      return result
    }
  }
}
```

**Handler**
```javascript
// api/src/functions/graphql.js

export const handler = createGraphQLHandler({
  schema: makeMergedSchema({
    schemas,
    services: makeServices({ services }),
  }),
  schemaDirectives: {
    auth: AuthDirective,
  },
})
```

**Schema**
```graphql
type Post {
    author: String @auth
}
```

I haven't dug too far, but according to the types of `createGraphQLHandler` it should accept `schemaDirectives`

If this is unexpected I'm happy to dig further. If it's expected and needs work I'm happy to make a PR!

**Comment by peterp** [comment]
Unfortunately we're using `makeMergedSchema` from `graphql-tools` which doesn't support directives. (Support was [merged](https://github.com/apollographql/graphql-tools/pull/1003), but not released.) 

Apollo has opted for federation instead.

We might want to switch to an alternative: 
- https://www.npmjs.com/package/graphql-tools-fork
- https://github.com/Urigo/merge-graphql-schemas

**Comment by RobertBroersma** [comment]
Ah, that explains!

What are the considerations for switching?

**Comment by peterp** [comment]
@RobertBroersma This is actually a fairly decent first issue, here's the [stitching documentation](https://graphql-tools-fork.netlify.com/modules/_stitch_index_.html) for `graphql-tools-fork` which would give us the most mileage without a ton (if any) of code changes.

It offers a ton of background about Apollo's new federation approach, and the impetus for creating the fork.

My gut feeling is that someone could switch out the `graphql-tools` imports in `@redwoodjs/api` with those of `graphql-tools-fork` and it'll "just work."

**Comment by peterp** [comment]
I think you could replace these two imports: 
https://github.com/redwoodjs/redwood/blob/e842179762093b2589c9eedc2b7b123bdea30693/packages/api/src/makeMergedSchema/makeMergedSchema.js#L1

With the same that are available in `graphql-tools-fork`

**Comment by RobertBroersma** [comment]
Sounds good, I'll give it a try!

**Comment by peterp** [comment]
Thank you @RobertBroersma! If you want to test this you can follow the `yarn link` guidelines in `CONTRIBUTING.md`

**Comment by thedavidprice** [comment]
Hi gents. Was this handled with #347 ?

**Comment by RobertBroersma** [comment]
Yep!
