### ISSUE TITLE
[Windows]: use a different ignore strategy for api-server's watch process

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#3338]
On Windows, it seems like api-server's watch process isn't actually ignoring any of the `includes` rules (except for the `'node_modules'` one):

https://github.com/redwoodjs/redwood/blob/e961b4b3981b502fba975d89d9986cb6a6566d8b/packages/api-server/src/watch.ts#L61-L66

Here's an app on the latest canary version (`0.36.3-canary.34+e961b4b3`), with graphql-server and everything. It has two models, `User` and `Post`.

I'm using [git bash](https://gitforwindows.org/). Running `yarn rw dev api` outputs (clipped for relevance):

```terminal
api | Building... Took 488 ms
api | [addDir] \dist
api | [addDir] \dist\graphql
api | [addDir] \dist\lib
api | [addDir] \dist\functions
api | [addDir] \dist\services
api | [add] \dist\graphql\users.sdl.js
api | [add] \dist\graphql\users.sdl.js.map
api | [add] \dist\graphql\vectors.sdl.js
api | [add] \dist\graphql\vectors.sdl.js.map
api | [add] \dist\lib\auth.js
api | [add] \dist\lib\auth.js.map
api | [add] \dist\lib\db.js
api | [add] \dist\lib\db.js.map
api | [add] \dist\lib\logger.js
api | [add] \dist\lib\logger.js.map
api | [add] \dist\functions\graphql.js
api | [add] \dist\functions\graphql.js.map
api | [addDir] \dist\services\users
api | [addDir] \dist\services\vectors
api | [add] \dist\services\users\users.js
api | [add] \dist\services\users\users.js.map
api | [add] \dist\services\vectors\vectors.js
api | [add] \dist\services\vectors\vectors.js.map
api | Building... Took 148 ms
api | [change] \dist\functions\graphql.js
api | [change] \dist\graphql\users.sdl.js
api | [change] \dist\lib\auth.js
api | [change] \dist\services\users\users.js
api | [change] \dist\services\vectors\vectors.js
api | Building... Took 162 ms
``` 

It looks like it's building three times. Moreover, it's running a function that should only be run on watched files:

https://github.com/redwoodjs/redwood/blob/e961b4b3981b502fba975d89d9986cb6a6566d8b/packages/api-server/src/watch.ts#L86-L88

So why's it not ignoring the `dist` files? What are `file` and `rwjsPaths.api.dist` actually?

```js
console.log(file)
console.log(rwjsPaths.api.dist)
console.log(file.includes(rwjsPaths.api.dist))
```

```terminal
api | C:/Users/dac09/dom/redwood-project-canary/api/dist   # <-- file
api | C:\Users\dac09\dom\redwood-project-canary\api\dist   # <-- rwjsPaths.api.dist
api | false
```

Note that `path.sep`, which is the platform-specific path segment separator, is `\`, so `rwjsPaths.api.dist` is using the "correct" separator. I'm not sure how the file from chokidar is coming back to us with a different separator.

**Comment by peterp** [comment]
Great catch dom! 🤦
