### ISSUE TITLE
Firebase v9 breaks redwood auth

### ISSUE THREAD

**Issue by domvernon** [redwoodjs/redwood#3344]
Hi 👋 

I recently added Firebase Auth to a new project. In my `package.json` In the web workspace I can see it has added `"firebase": "^9.0.1",`. As v9 [moves to a modular sdk ](https://firebase.google.com/support/release-notes/js#version_900_-_august_25_2021), I am seeing (not surprisingly) the following message when running `yarn rw dev`:

```
web | WARNING in ./src/App.js 23:7-27
web | export 'default' (imported as 'firebase') was not found in 'firebase/app' (possible exports: FirebaseError, SDK_VERSION, _DEFAULT_ENTRY_NAME, _addComponent, _addOrOverwriteComponent, _apps, _clearComponents, _components, _getProvider, _registerComponent, _removeServiceInstance, deleteApp, getApp, getApps, initializeApp, onLog, registerVersion, setLogLevel)
```

There are some workarounds which _appear_ to work, but I haven't throughly tested them:
1. Manually change the `package.json` version to v8 eg `"firebase": "^8",` or similar
2. Change the imports in `App.js` to the ones found in the compat guide [here](https://firebase.google.com/docs/web/modular-upgrade#update_imports_to_v9_compat). <-- this may be deprecated as soon as v10 though

The permanent solution will be to follow the [upgrade guide](https://firebase.google.com/docs/web/modular-upgrade#refactor_to_the_modular_style), which I haven't had a chance to try out, but just wanted to let everyone know in case they ran into this as well.

**Comment by doesnotexist** [comment]
Are you also using react-firebaseui or firebaseui?  I only see that error if I try to use it, otherwise my redwoodjs project does not care if I have a firebase v9 dependency. 
The react library has merged an upgrade of dependencies but there is no release with these changes yet https://github.com/shiiinji/firebaseui-web-react/pull/1

**Comment by thedavidprice** [comment]
Hi All, we've prioritized #3347 and will work to move it forward. Thanks!

**Comment by domvernon** [comment]
Perfect, this will do it 👍
