### ISSUE TITLE
Many to many docs have error.

### ISSUE THREAD

**Issue by shansmith01** [redwoodjs/redwood#3350]
Trying to work on manytomany relationships. I am copying the code form the example on the docs on this page https://redwoodjs.com/docs/schema-relations

```
model Product {
  id       Int      @id @default(autoincrement())
  title    String
  desc     String
  tags     Tag[]
}

model Tag {
  id       Int       @id @default(autoincrement())
  name     String
  products Product[]
}

model ProductsOnTags {
  id        Int       @id @default(autoincrement())
  tagId     Int
  tags      Tag[]     @relation(fields: [tagId], references: [id])
  productId Int
  products  Product[] @relation(fields: [productId], references: [id])
  @@unique([tagId, productId])
}
```

And I am getting red lines on this code. Specific issue is -

"Error validating field `tags` in model `ProductsOnTags`: The relation field `tags` on Model `ProductsOnTags` is missing an opposite relation field on the model `Tag`. Either run `prisma format` or add it manually.

This code is looking a little different to the primsa example here https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations

Based on that I would suggest that the product and tag model should be

```
`model Product {
  id       Int      @id @default(autoincrement())
  title    String
  desc     String
  tags     ProductsOnTags[]
}

model Tag {
  id       Int       @id @default(autoincrement())
  name     String
  products ProductsOnTags[]
}`
```

Is that correct?

Thanks

**Comment by thedavidprice** [comment]
Hi @shansmith01 Yes, indeed, we need to update that doc! Here's the lates conversation with example code (on our web + docs repo): 
https://github.com/redwoodjs/redwoodjs.com/issues/777

Closing this one out. And no pressure but help updating the doc would be greatly appreciated!
