### ISSUE TITLE
`graphql-server` asynchronous beforeResolver not being handled

### ISSUE THREAD

**Issue by realStandal** [redwoodjs/redwood#3366]
When writing an asynchronous `beforeResolver`, I'm finding that when I use the `graphql-server` package my resolver isn't being waited on.

OS: Windows
Redwood: 0.36.4

My `redwood.toml`:

```toml
...
[experimental]
  useEnvelop = true
```

My API side's `package.json`:

```YAML
{
  "dependencies": {
    "@redwoodjs/api": "^0.36.4",
    "@redwoodjs/graphql-server": "^0.36.4",
    // ...
  },
}
```

When I invoke a service which has an asynchronous resolver, using the above configuration and packages from `@redwoodjs/graphql-server`:

![image](https://user-images.githubusercontent.com/25166787/132579027-fc489707-73af-4f1e-87c3-a1efec13b414.png)

My request is allowed and I'm able to see the resources I should not have access to.

However, when I disable `useEnvelop` and use the Apollo server (`@redwoodjs/api`), it works as expected:

![image](https://user-images.githubusercontent.com/25166787/132578133-ded018e6-1dfc-429c-8176-8e7b37f506da.png)

When I make the request, that error's caught by the web-side and execution of my service never occurs.

**Comment by Tobbe** [comment]
@realStandal Can you please share the code for the resolver? Or even better, a trimmed down resolver that's as small as possible, but that still demonstrates the behavior.

**Comment by thedavidprice** [comment]
Hi @realStandal There are some major changes coming to graphql-server and beforeResolver in the upcoming v0.37 release.

We are moving the GraphQL Server to Envelop/Helix, which includes a ton of improvements and fixes. See #3286

This allows us to create a new way to secure Services via SDL Directives. See #3307 We think you're going to like the new directives. A lot.

But this means we are going to deprecate beforeResolver (currently planned as a two-release process; heads-up in v0.37 then deprecation in v0.38, but that plan might change).

I'm going to mark this Issue resolved by #3307 But please do keep us posted and re-open as needed.

**Comment by realStandal** [comment]
@Tobbe Removed where I'm putting together my variables.

```ts
export const validateIsAdmin = async (_s: string) => {
  const res = await fetch(something)

  if (!res) throw new AuthenticationError('auth-is-admin')
}
```

Which is then used across services:

```ts
export const beforeResolver = (rules: BeforeResolverSpecType) => {
  rules.add(validateIsAdmin)
}

---

@thedavidprice Sounds good! Been looking forward to understanding how I'm supposed to use Envlope+Helix in Redwood lol

**Comment by thedavidprice** [comment]
@realStandal Hopefully the change will be fairly seamless. Mostly you'll just get improved defaults and security out of the box.

**Comment by realStandal** [comment]
> @realStandal Hopefully the change will be fairly seamless. Mostly you'll just get improved defaults and security out of the box.

Very nice to hear!

Do you know/off the top of your head, will it make it easier to manipulate what's being handed to/happening after service invocation? From the Envlope/plugin perspective. Just looking at the PR you linked it looks like the answer's going to be 'yes, but with some restrictions'. Happy to start hacking at it either way!

**Comment by thedavidprice** [comment]
> will it make it easier to manipulate what's being handed to/happening after service invocation?

I believe the answer is a strong "yes", but I'm not the expert here. Have you read through David T's forum post here (especially the section "Better Plugins" about Envelop)?
- https://community.redwoodjs.com/t/using-graphql-envelop-helix-in-redwood-v0-35/2276
- more on Envelop specifically: https://www.envelop.dev/docs

**Comment by realStandal** [comment]
I did and switched too the envlope+helix soon as I could but didn't put much effort into trying out the plugins and what not - have only used it as a drop-in replacement for Apollo. I'm close to being done with that, agnostic part of my app and can start working on features that will need/benefit from the plugins. Here's hoping it lines up well 😁

Good to see this issue won't be here to stay, though!
