### ISSUE TITLE
yarn creator fails when trying to install redwoodjs@core

### ISSUE THREAD

**Issue by jsierles** [redwoodjs/redwood#3368]
Macbook, Big Sur  
node v14.17.6  
yarn 1.2.11  
  
\`\`\`  
  ✔ Creating Redwood app  
   ✔ Checking node and yarn compatibility  
   ✔ Creating directory '/Users/joshua/rwtest'  
 ❯ Installing packages  
   ✖ Running 'yarn install'... (This could take a while)  
     → info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.  
   Convert TypeScript files to JavaScript  
   Generating types

Error: Command failed with exit code 1: yarn install  
error An unexpected error occurred: "https://registry.yarnpkg.com/registry/@redwoodjs%2fcore: Request \\"https://registry.yarnpkg.com/registry/@redwoodjs%2fcore\" returned a 405".  
\`\`\`

**Comment by Tobbe** [comment]
What if you try again? Still get the same error?

Another thing you could try is `yarn create redwood-app --no-yarn-install my-app` and then manually running `yarn install` inside the my-app folder.

I just tried creating a new app, and had no problems

**Comment by jsierles** [comment]
The error happens consistently. Deferring the `yarn install` works, so I'll just close this as it must be something specific to my environment.
