### ISSUE TITLE
Glob routing

### ISSUE THREAD

**Issue by macovedj** [redwoodjs/redwood#3375]
An attempt to turn [this conversation](https://github.com/redwoodjs/redwood/issues/3263) into a proposal that can be easily followed:

I think it's easiest to describe the need that redwood-router currently doesn't fulfill via an example app... a clone of github.
In github, given a repo, there is a url per file in the repo.  The thing is that... because the folder structures change on a regular basis, there is no way to know in advance how deep the folder structure can get, but redwood-router requires that you know the number of `/` characters in your route when you declare the path, so you would not be able able to make an app where the number of `/` characters in your path is unknown at the time of route declaration.  This is clearly an issue for a github clone... but I'm sure there are other use cases that would require it as well.

Other frameworks handle this different ways.  The solution in rails is called "glob routing" and you can learn more about it [here](https://guides.rubyonrails.org/routing.html#route-globbing-and-wildcard-segments).  Various people in the issue referenced above proposed distinct syntax rules that redwood could adopt in the implementation.  They all appear equally expressive to me... but after looking at code a bit to see how hard it would be to implement I think that this one

`<Route path="/path/to/page/{myvariable:*}" />`

appears easiest to implement... as it wouldn't require new parsing logic for route variables.  The only thing that I'd say is that the `*` could be replaced by the word `glob` if we wanted to continue to use English for variable types.  

Is there more that needs to be determined in order to start working on a PR?

**Comment by Tobbe** [comment]
> but redwood-router requires that you know the number of `/` characters in your route when you declare the path

As I demonstrated in the linked issue (after you created this issue :) ) this is not entirely true. Using RW's regex support you can handle this case as well

> Is there more that needs to be determined in order to start working on a PR?

I think the main thing we need to determine is if any change is actually needed at all, or if we can already handle this with the features we have.

**Comment by thedavidprice** [comment]
Closing this issue to consolidate the topic over here:
https://github.com/redwoodjs/redwood/issues/3263#issuecomment-934564373
