### ISSUE TITLE
`msal` library is no longer receiving new features

### ISSUE THREAD

**Issue by andrewlamyw** [redwoodjs/redwood#3377]
According to https://www.npmjs.com/package/msal
> This library is no longer receiving new features and will only receive critical bug and security fixes. All new applications should use @azure/msal-browser instead.

It is currently used in https://github.com/redwoodjs/redwood/blob/main/packages/auth/package.json#L22

**Comment by thedavidprice** [comment]
Thanks for letting us know @andrewlamyw!

@jeliasson Any chance you could take a look at a migration for Azure Auth to use the new `@azure/msal-browser`? Migration docs are here:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v1-migration.md

Related files:
- Auth: https://github.com/redwoodjs/redwood/blob/main/packages/auth/src/authClients/azureActiveDirectory.ts
- Template: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/setup/auth/providers/azureActiveDirectory.js
- Test: [update test snapshot](https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/setup/auth/__tests__/__snapshots__/addAuthConfigToApp.test.js.snap)

Some notes after a quick glance:
- Will need to swap `UserAgentApplication` with `PublicClientApplication`
- and `client.logout` with `client.logoutPopup` (I think)
- and account for changes to token response e.g. " MSAL provides the handleRedirectPromise function which will return a promise that resolves when the redirect has been fully handled by MSAL."

**Comment by jeliasson** [comment]
@thedavidprice I started that a few weeks ago but have not had time to finish it off. I'll see if I can submit a PR for testing and review by the end of the month. I think you are on point with all things that needs to be done. 

@andrewlamyw If you want to take a swing at this, let me know, otherwise I'll get back to you asap.

**Comment by andrewlamyw** [comment]
@thedavidprice @jeliasson thanks for the response 🙏

@jeliasson I would like to try! 😁 

There is another new package `@azure/msal-react` in addition to the `@azure/msal-browser`, I'm not sure which one to migrate to...

**Comment by jeliasson** [comment]
@andrewlamyw Go for it! I'm on Discord if you want some collab, testing or battle testing in the wild. 🦒

> There is another new package [@azure/msal-react](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react) in addition to the `@azure/msal-browser`, I'm not sure which one to migrate to...

`@azure/msal-react` has `@azure/msal-browser` as dependency and looks like the majority of the documentation points the browser package. My guess would be to go with the most mature one, and use the [Authorization Code Flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) with redirect.

**Comment by thedavidprice** [comment]
After a quick glance, it seems `msal-react` is the better choice for Redwood (supports React and SPA Hooks, Events, Class Components, and SPA routing): 
- https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react

I'd suggest starting there — definitely not the expert here and will defer to @jeliasson

**Comment by jeliasson** [comment]
WiP on #3490
