### ISSUE TITLE
Make generators adhere to `prettier.config.js` in Redwood project

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#339]
Based on feedback from #317 
> I adore line ending semi-colons..... It would be great if the CLI ran prettier using my local config as the files were generated so that I did not have to deal with formatting on my own every time?

We should run prettier programatically over generated components.

Steps:
1. Install prettier as a dependency in the CLI.
2. Add a way to read the user's prettier config. (Use `getPaths`)
3. Read the template and format it with `prettier.format` (https://prettier.io/docs/en/api.html#prettierformatsource--options)

**Comment by satyarohith** [comment]
I'll take it.

**Comment by peterp** [comment]
Thanks @satyarohith, hit me up if you need any guidance!
