### ISSUE TITLE
Cookies are not sent when API is on different host such as subdomain. 

### ISSUE THREAD

**Issue by viperfx** [redwoodjs/redwood#3395]
So I recently implemented a team switcher for our app and it was working well locally, when we went to staging with this, I came across this issue. For context our app is hosted at `app.ourdomain.com` and the API is at `api.ourdomain.com`

To reproduce this issue locally, serve your redwood app using a local domain. By modifying /etc/hosts. 

```
127.0.0.1 localhost app.redwood.local api.redwood.local
```

The crux of the issue is that Apollo client needs to be told to pass cookies to different domains. By default it only passes cookies to the same domain. More info here - https://www.apollographql.com/docs/react/networking/authentication/#cookie

> If your app is browser based and you are using cookies for login and session management with a backend, tell your network interface to send the cookie along with every request. Pass the credentials option e.g. credentials: 'same-origin' if your backend server is the same domain, as shown below, or else credentials: 'include' if your backend is a different domain.

I updated the apollo provider to include this option. However, this was not properly passed down to all the necessary bits.

```
<RedwoodApolloProvider graphQLClientConfig={{ credentials: 'include' }}>
```

I had to make patches for redwood/auth and redwood/web to get it working cross domain. 

This patches the reauthenticate method so the cookies are passed. With credentials include option.
```
diff --git a/node_modules/@redwoodjs/auth/dist/AuthProvider.js b/node_modules/@redwoodjs/auth/dist/AuthProvider.js
index 199fae5..7e93760 100644
--- a/node_modules/@redwoodjs/auth/dist/AuthProvider.js
+++ b/node_modules/@redwoodjs/auth/dist/AuthProvider.js
@@ -58,9 +58,11 @@ class AuthProvider extends _react.default.Component {
       const token = await this.getToken();
       const response = await global.fetch(`${global.__REDWOOD__API_PROXY_PATH}/graphql`, {
         method: 'POST',
+	 credentials: 'include',      
         headers: {
           'content-type': 'application/json',
           'auth-provider': this.rwClient.type,
           authorization: `Bearer ${token}`
         },
         body: (0, _stringify.default)({
```

Per Apollo docs, httpLink is also meant to have the credentials option specified. 
```
diff --git a/node_modules/@redwoodjs/web/dist/apollo/index.js b/node_modules/@redwoodjs/web/dist/apollo/index.js
index 854b1d8..d591886 100644
--- a/node_modules/@redwoodjs/web/dist/apollo/index.js
+++ b/node_modules/@redwoodjs/web/dist/apollo/index.js
@@ -84,7 +84,8 @@ const ApolloProviderWithFetchConfig = ({
     return forward(operation);
   });
   const httpLink = createHttpLink({
-    uri
+    uri,
+    credentials: config.credentials
   });
   const {
     cacheConfig,

```

**Points of discussion:**
- should the config from RedwoodProvider be passed down to these options as the official fix?

**Comment by viperfx** [comment]
@jtoar have you guys discussed this internally? I have this working in production with a patch. So open to contributing a PR.

**Comment by jtoar** [comment]
@viperfx Yeah I was assigned because I usually handle Apollo issues but if you have a fix I'm happy to collaborate on it!
