### ISSUE TITLE
Update Magic Auth Provider and Decoder to latest

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#3400]
Magic auth has had significant upgrades since the initial implementation and now supports server-side verification of the auth token.

As such, Redwood's implementation and decoder needs to be upgraded to current.

**Comment by dthyresson** [comment]
@shahbaz17 Here is the issue for the upgrade Magic auth to latest PR.

**Comment by shahbaz17** [comment]
Thanks for the tag @dthyresson 

I will make a PR to add the Magic decoder.

**Comment by dthyresson** [comment]
Let's also wrap up https://github.com/redwoodjs/redwood/pull/2629#issuecomment-923090196 with the new PR if we can to get everything sorted and up-to-date. Thanks much!

**Comment by thedavidprice** [comment]
> Let's also wrap up #2629 (comment)

See my comments and approval
