### ISSUE TITLE
Add Forgot Password and Reset Password flows to dbAuth

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#3401]
You can sign up, and you can log in, but what about when you forget your password? Let's add a Forgot Password and Reset Password logic and pages/components to dbAuth!

Conceptual flow:

1. User goes to the Forgot Password page and enters their username/email
2. A `resetToken` UUID is added to their user record in the database and `resetExpiresAt` time after which it will no longer be valid
3. A user goes to the Reset Password page with the `resetToken` present in the query string (presumably they followed a link in an email)
4. Assuming the `resetToken` is correct, and we are still before the `resetExpiresAt` time, they are allowed to set a new password, which is hashed and saved to the db
5. `resetToken` and `resetExpiresAt` is set to `null` so that it can't be re-used

This means several new requirements/features will be added:

* Add `resetToken` and `resetExpiresAt` to schema.prisma
* Add `resetToken` and `resetExpiresAt` to list of customizable field names in `authFields` in `auth.js` function
* Add `resetPassword` key to `auth.js` function to allow some customization to the flow, like a `handler` and a `allowSamePassword` boolean (to enforce that the user actually uses a new password) and `resetExpiresWindow` for how long the reset token stays good for
* Create `ForgotPassword.tsx` and `ResetPassword.tsx` pages when running the dbAuth scaffold generator

**Comment by Tobbe** [comment]
Should we also have a time-out on that reset token? So that the reset link is only valid for an hour? Or 24 hours, or whatever we think is a good limit?

**Comment by zwl1619** [comment]
Hope to use jwt.

**Comment by cannikin** [comment]
Hmm, not sure why I reopened this, it's definitely done.

**Comment by domnantas** [comment]
Hi! What about other auth providers? I need this functionality and I'm using Supabase. It does have [reset password in its API](https://supabase.io/docs/reference/javascript/reset-password-email), so only the AuthProvider code needs to be updated to support it, should we start with a separate issue?

**Comment by cannikin** [comment]
I'm not really tracking the third party login providers so sorry if I come off sounding like a fool, but: does Supabase have a UI widget that you're using when integrate their login with Redwood? Or do you have to build everything yourself and setup your hooks?

I would create a new issue, yes. The code in this PR does [extend the authClient interface](https://github.com/redwoodjs/redwood/blob/main/packages/auth/src/authClients/index.ts#L88-L90) to allow for `resetPassword` and `forgotPassword` functions that live along side the existing ones `logIn`, `signUp`, etc. It would be a matter of extending the Supabase authClient to call the right functions in their client lib (see the end of this file): https://github.com/redwoodjs/redwood/blob/main/packages/auth/src/authClients/supabase.ts
