### ISSUE TITLE
Auto generator for schema and services

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#341]
We have a command to generate `schema` and `services` related to a model in Prisma:

```terminal
yarn rw g sdl <model>
yarn rw g service <model>
```

It would be great if we had a way to automatically generate these whilst changes are made to the `prisma.schema` file whilst `yarn rw dev` is running. 

Or when `yarn rw db up` is run, we could mention something along the lines of:
```terminal 
yarn rw db up
[ doing database things ]

Hey, we noticed that you changed <ModelName> and you have generated:
./api/src/sdl/modelname.sdl.js
./api/src/services/modelname.js

Would you like to update those generated files? Y/n
```

**Comment by cannikin** [comment]
I'm inclined to follow Rails's lead here—if you make a change to your database schema you're free to re-generate the file (`--force`) but there's isn't any kind of intelligence that attempts to keep your database schema changes in sync with any files that may have derived from it.

I can quickly see this ballooning into "well I did make a couple of changes to my `services` file and I don't want those to get overridden, could you provide an interactive diff when I regenerate so I can choose whether or not to merge the changes that I made?" 😫

Generators were never meant to a be a crutch that you use to support your entire application, just enough to get you started!

**Comment by thedavidprice** [comment]
I also agree that it should _not_ be the job of the generators to keep things in sync.

But being able to provide user feedback alerts/warnings when it appears the schema and files _are_ out of sync would be ideal behavior (in my opinion). 

The context for my suggestions:
There still seems to be a lot of confusion about the steps and process involving 1) model 2) generate 3) migrate. Unclear to me at this time, however, what needs to be done to improve user understanding vs. expectations, e.g. do we need better training or do we need to simplify/merge steps or … ? But one thing I believe can always help is more feedback from the system when and if possible.
