### ISSUE TITLE
Cell Input props are expecting type `never` if there's no Query variable

### ISSUE THREAD

**Issue by callingmedic911** [redwoodjs/redwood#3416]
If there's a Cell with a query that's doesn't need any variable AND we need some props for the Success component, it results in TS error.
![Screenshot 2021-09-22 at 9 55 05 PM](https://user-images.githubusercontent.com/2629902/134383521-53b4a6bf-801a-4bf7-94ee-a4c1396e0d02.png)
 
This happens because when Graphql Code Gen doesn't finds any variable it creates this type:
![Screenshot 2021-09-22 at 9 56 06 PM](https://user-images.githubusercontent.com/2629902/134383674-f822f9ea-b170-44e0-8976-0643ff9f543c.png)

and we use `Success & GraphQLVariable` type:
![Screenshot 2021-09-22 at 10 15 36 PM](https://user-images.githubusercontent.com/2629902/134386481-545e709b-942d-4371-bfc5-bbe80023a8c9.png)

Possible steps to fix:
- Either somehow disable this type in codegen
- Or Comeup with type which removes this behavior

**Comment by cjreimer** [comment]
I just hit this issue as well.  Great to see that it's already in the queue!
