### ISSUE TITLE
Component generator doesn't fully handle mixed casing

### ISSUE THREAD

**Issue by milancermak** [redwoodjs/redwood#3417]
I generated a new Redwood component using `yarn rw g component NFTImage`. As expected, it created a bunch of files in `web/src/components/NftImage`, here's the output:
```
yarn run v1.22.11
$ /Users/m/projects/ens-gallery/app/node_modules/.bin/rw g component NFTImage
  ✔ Generating component files...
    ✔ Successfully wrote file `./web/src/components/NftImage/NftImage.test.tsx`
    ✔ Successfully wrote file `./web/src/components/NftImage/NftImage.stories.tsx`
    ✔ Successfully wrote file `./web/src/components/NftImage/NftImage.tsx`
✨  Done in 1.76s.
```

When I then ran `yarn rw storybook`, I got the following error:
```
ModuleNotFoundError: Module not found: Error: [CaseSensitivePathsPlugin] `/Users/m/projects/ens-gallery/app/web/src/components/NftImage/NFTImage.tsx` does not match the corresponding path on disk `NftImage.tsx`.
```

If I run `yarn rw g component NftImage`, it all works fine.

I'm using Redwood v0.36.4.

**Comment by thedavidprice** [comment]
Thank you for reporting this @milancermak Looks like there could be some nuanced trouble here between case-sensitivity and our generators!

Can you please reply with the following:
- the output from `yarn rw info` (looking for your system info)?
- For the first case above (`rw g component NFTImage`), a screenshot of the component directory and files (to see the names of directories and files on disk — do they differ from the output)?
- does `yarn rw dev` work?
- snippet of the generated code from `NftImage/NftImage.tsx`? (curious if the export name matches filename)
- and snippet of the generated code from `NftImage/NftImage.stories.tsx`?

---

Notes for my future self and @jtoar:
- Is there a potential bug with our "directory named" babel plugin for this type of naming on a case-senstive OS?
- maybe we just messed up the export in the template... 🤞

**Comment by milancermak** [comment]
Sure thing.

```
yarn rw info
yarn run v1.22.11
$ /Users/m/projects/ens-gallery/app/node_modules/.bin/rw info

  System:
    OS: macOS 11.3
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /var/folders/5q/4xtxn4k91cj4ch27yjlx9d5r0000gn/T/yarn--1632380742307-0.7346726851815422/node
    Yarn: 1.22.11 - /var/folders/5q/4xtxn4k91cj4ch27yjlx9d5r0000gn/T/yarn--1632380742307-0.7346726851815422/yarn
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 93.0.4577.82
    Firefox: 91.0.2
    Safari: 14.1
  npmPackages:
    @redwoodjs/core: 0.36.4 => 0.36.4

✨  Done in 1.56s.
```

```
ls -l web/src/components/*
total 24
-rw-r--r--  1 m  staff  141 Sep 23 09:05 NftImage.stories.tsx
-rw-r--r--  1 m  staff  225 Sep 23 09:05 NftImage.test.tsx
-rw-r--r--  1 m  staff  187 Sep 23 09:05 NftImage.tsx
```

`yarn rw dev` does work.

Here's the contents of `NftImage/NftImage.tsx`:

```typescript
const NFTImage = () => {
  return (
    <div>
      <h2>{'NFTImage'}</h2>
      <p>{'Find me in ./web/src/components/NftImage/NftImage.tsx'}</p>
    </div>
  )
}

export default NFTImage
```

aaaand `NftImage.stories.tsx`
```typescript
import NFTImage from './NFTImage'

export const generated = () => {
  return <NFTImage />
}

export default { title: 'Components/NFTImage' }
```

HTH 🤓

**Comment by dac09** [comment]
Hey just a guess here, but it looks like you have a hint on the error you're receiving. 

In the first line of your stories - if you look at the import, the path casing doesn't match (after a manual change, right?)

import NFTImage from './NFTImage' <---- `NFTImage` != `NftImage`

**Comment by milancermak** [comment]
Yes, I know it doesn't match, that's why I fixed it for myself using `yarn rw g component NftImage`. I reported the bug because I believe this should work out-of-the-box.

**Comment by dac09** [comment]
Ah I understand!

**Comment by dac09** [comment]
@cannikin - this seems to be an area you're comfortable with. Interested in picking up?

**Comment by cannikin** [comment]
I noticed you asked that *after* assigning it to me. 😉
