### ISSUE TITLE
Generate interfaces based on client side queries

### ISSUE THREAD

**Issue by linde12** [redwoodjs/redwood#3418]
Hello! Been playing around with redwood a bit and enjoying it greatly so far.

I have a question regarding typescript interfaces or types: is there a way to get a hold of the return type for client queries?

E.g. if i have a query like this:

```ts
export const QUERY = gql`
  query FindFiveUsers {
    users(first: 5, after: ...) {
      id
      name
    }
  }
`
```

the type for my props will have a shape similar to this:
```
__typename: 'User'
id: number
name: string
```

Is there a way i can get a hold of this type? I'm thinking something like `type FindFiveUser = ReturnType<QUERY>` (which wont work but just as an example)

My problem is that sometimes i am requesting more fields from a user, and sometimes i'm requesting less so my web application needs interfaces for each query, not only each type, and i would like to avoid writing these myself (which is a bit time consuming and very verbose)

In this case i am then passing the result of the query to a component like so: `<UserList users={users} />` and in `UserList.tsx` i want to specify an interface for the props where i say something `users: FindFiveUser`.

I know i could say `Partial<User>` or even something like `DeepPartial<User>` but then _everything_ is optional and the point of specifying the type in the first place is partially (pun intended 😄) lost.

**Comment by dthyresson** [comment]
@dac09 Thoughts on generating types here?

**Comment by dac09** [comment]
Hej! These interfaces are actually already generated for you, _just make sure_ you have the dev server running, **or** you run `yarn rw g types` manually

---

You can import your type in this case like:

```ts
import type { FindFiveUsers } from 'types/graphql'
```

As a more generic answer, the generated type has the name of your operation, and will work for queries and mutations - and anywhere in the web codebase, not just cells!

```
import type { ${operationName} } from 'types/graphql'

export const QUERY = gql`
  query ${operationName} { // <--- your operation name
  }
```

Closing the issue, but please comment if this doesn't resolve it for you ✌️

**Comment by dthyresson** [comment]
@linde12 As a follow up to what @dac09 about generating types — I believe you’ll want to have unique Operation names per cell (that contains your query). If not then you may seen warnings or error during type generation.

**Comment by linde12** [comment]
Ah, thank you guys! I think i proper confused myself before posting the question.

I actually knew that the query types are available in types/graphql, i even use it in some places (sorry again for the confusion) but my problem was actually getting a subtype of the query type. In my case i have relay style pagination (with connections, nodes & edges) and want to access the "node" type.

I think i managed to solve it though:

```ts
  type TodoNode = typeof todos.todoConnection.edges[0]['node']
```

This would give me the type of a single `Todo` for this query. Im so used to REST so i thought i could just have a single `Todo` interface but of course that wont work with GraphQL since you can request partial & "nested resource" information.

If there is a more elegant solution i'd be happy to hear! Thanks again! :smile:
