### ISSUE TITLE
Merge "watchers" into a single process.

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#3424]
RedwoodJS runs a bunch of watchers that react to code changes, it would be great to reduce these into a single watcher because it would improve performance, but also give us a centralized place to formalize the concept of watching for file changes and reacting to them.

These are the file watchers we currently have:
1. dev-server: builds the code and reloads the api side when `api/*` changes.
2. type-generation: watches both the web and api sides and generates type definitions when a file changes.
3. webpack-dev-server: watches the `web/* files` and reloads the bundle when things change.

I think it would be great to expose a log of events: a file change and resulting in the following happening via an HTTP API. Doing so would allow us to expose those logs in more places than just the CLI.

---

There's a grand vision at play here and we've been slowly moving towards it, this is the next step in that evolution: The vision is that we are not longer reliant on the user's OS as the runtime for RedwoodJS but are only reliant on a JavaScript Runtime. 

This will allow us to code RedwoodJS from anywhere, not just a local dev-environment.

**Comment by thedavidprice** [comment]
> There's a grand vision at play here and we've been slowly moving towards it, this is the next step in that evolution: The vision is that we are not longer reliant on the user's OS as the runtime for RedwoodJS but are only reliant on a JavaScript Runtime.
>
> This will allow us to code RedwoodJS from anywhere, not just a local dev-environment.

🤩

**Comment by orta** [comment]
It's be great to have some sort of way to hook into this to start/stop our own watchers (for example I'd like to have the relay compiler in watch mode running in there)
