### ISSUE TITLE
TS error if query in a Cell is camelCased instead of PascalCase

### ISSUE THREAD

**Issue by callingmedic911** [redwoodjs/redwood#3425]
If we have query camel cased like:
![Screenshot 2021-09-24 at 6 14 04 PM](https://user-images.githubusercontent.com/2629902/134676108-5e60650c-0ec4-45f5-87c7-1af9ec2f6ab5.png)
then generated types throw an error 
![Screenshot 2021-09-24 at 6 14 35 PM](https://user-images.githubusercontent.com/2629902/134676184-ea0c063b-9733-4c75-bc60-bfca95088f6b.png)

This happens because graphql-codegen by default converts the case to pascal case - which makes sense because it's usually the convention when creating types - But when we pass the names of these types when generating mirror cell, it's fetched directly from AST as is.

Possible fix:
1) Disable default behavior of graphql-code-gen. `namingConvention:keep` (from: https://www.graphql-code-generator.com/docs/plugins/typescript)
2) When creating mirror cell, we modify it to pascal case.

I'm inclined towards the second one. What do you all think?

**Comment by dac09** [comment]
I think all we'd need to do really is make sure the that the types are pascalCased in the cell generator I believe.

Also worth looking at the scaffold one.

That being said.... I think I was using the wrong conventions in this case, should queries have pascal-cased names??

**Comment by callingmedic911** [comment]
Both scaffold and cell generate operation name in pascal case.

> That being said.... I think I was using the wrong conventions in this case, should queries have pascal-cased names??

I think so. But considering even if it's against convention, it's failing silently (unless someone checks the mirror cell) - losing the strongly typed benefits without alerting.

**Comment by thedavidprice** [comment]
@callingmedic911 Would you be available to work on a fix for this?

**Comment by callingmedic911** [comment]
@thedavidprice Yes! I'd be glad to work on it. Before creating the PR, checking in to finalize the approach.

>But considering even if it's against convention, it's failing silently (unless someone checks the mirror cell) - losing the strongly typed benefits without alerting.

@dac09 Adding to my last comment: if we don't modify types or the references, do you think can we somehow show error visible to user? ESLint maybe? But frankly speaking, I still don't think camel casing should turn out to be error.

**Comment by callingmedic911** [comment]
I agree, I think we should be able to keep queries in any case. But setting `namingConvention: keep` would produce TS type name is similarly "any case". Do you think that's also okay? Most commonly I've seen TS types in PascalCase.
