### ISSUE TITLE
GraphQL Healthcheck endpoint incorrectly references Apollo

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#3438]
In dev, try:

```
http://localhost:8911/graphql/.well-known/apollo/server-health
```

It will return the health check response such as::

```
 {"status":"pass"}
```

Because `healthcheck.ts` defines:

`const HEALTH_CHECK_PATH = '/.well-known/apollo/server-health'`

This should be some more appropriate path and convention perhaps referring to redwood or helix? or just general "healthz" (Like Hasura does).

![image](https://user-images.githubusercontent.com/1051633/135123270-1c15e185-6022-4d01-a376-04c1ef956aad.png)

**Comment by simoncrypta** [comment]
Well-known URIs is made for standardization of service in URL, but I don't see server-health as a mint Well-known. `healthz`seem to be a better standard in this case. I don't know any service who use` /.well-known/apollo/server-health` by default for the health check.
https://datatracker.ietf.org/doc/html/rfc8615
https://en.wikipedia.org/wiki/List_of_/.well-known/_services_offered_by_webservers

Also, I don't know how this will impact the `healthz.js` function for [Render.com deployment,](https://render.com/docs/deploy-redwood) Is it a better practice to check GraphQL health vs a function health ?

**Comment by thedavidprice** [comment]
@dthyresson is this a priority to include in v0.37?

**Comment by dthyresson** [comment]
> @dthyresson is this a priority to include in v0.37?

No, 38 is fine

**Comment by dthyresson** [comment]
> Also, I don't know how this will impact the `healthz.js` function for [Render.com deployment,](https://render.com/docs/deploy-redwood) Is it a better practice to check GraphQL health vs a function health ?

The GraphQL health check path will always be appended to `/graphql` (ie, the api endpoint) so it should not collide with render or other health checks (from my understanding).

>`healthz` seem to be a better standard in this case. 

Same. I am asking the Guild to see if there is any best practice or standard naming.

**Comment by dthyresson** [comment]
Info from The Guild:

> There isn't a real standard or convention on how it should look like - it can be any path that you wish, as long as the infrastructure that runs is supports it.

> And the basics of health checks are:
> Any path, just make sure it's available for your infrastructure.
> Some are doing it under .well-known but there isn't a real specification for that.
> Return 200 in case of valid, or >400 in case of an error. The infrastructure will use that probe.
> Make sure your server is capable of returning the health result as soon as possible (so it means you need to start the HTTP server as soon as possible, and serve this route)
