### ISSUE TITLE
Update Prisma2 (now @prisma/cli) to preview025 

### ISSUE THREAD

**Issue by janpio** [redwoodjs/redwood#344]
There will be an entry for `2.0.0-preview025` on https://github.com/prisma/prisma2/releases very soon.

The biggest change is that the CLI is now available via the package `@prisma/cli` instead of `prisma2`. The binary/executable stays `prisma2` for now, so the only change required from your side will probably be the dependency:

https://github.com/redwoodjs/redwood/blob/7516073ec6a330a59fd44bf18442006a1d79a012/packages/core/package.json#L48

**Comment by janpio** [comment]
FWIW the current `alpha`, which the preview will be based on, has passing tests: https://github.com/janpio/redwood/runs/537890992?check_suite_focus=true 👍

**Comment by thedavidprice** [comment]
@janpio but you assume we actually have good test coverage... 😆 

Thanks for this. We'll sort things out and take 'er from here. And give a big high ✋to the Prisma team for us!!

**Comment by janpio** [comment]
Some test coverage is better than no test coverage :trollface: 

Thanks, will do!

**Comment by janpio** [comment]
FYI: `preview025` was released this noon.

**Comment by cannikin** [comment]
See this comment from Prisma, it will probably require some updates to the SDL generator:

Hey folks :wave: another heads-up: We're planning to launch the Prisma 2.0 beta next Tuesday. The beta will come with two more major breaking changes:

**Renaming the prisma2 CLI command to prisma**

The command that invokes the Prisma 2 CLI will be renamed to just prisma. The recommended installation and usage is:

```
npm install @prisma/cli --save-dev
npx prisma
```

**New relation syntax**

Previously relations could be declared with two relation fields where one was "virtual", the other one "represented the foreign key", e.g.:

```
model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?
}
model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}
```

After the beta release, you will need to annotate author with the @relation attribute. In the @relation attribute you must specify a "link field" on the same model which references a key on another model (data modeling gets closer to SQL now):

```
model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields:  [authorId], references: [id]) // physical relation field
  authorId  Int?    // link field
}
model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]  // virtual relation field
}
```

We already updated our new docs to incorporate these changes, you can take a look here: https://prisma2.netlify.com/reference/tools-and-interfaces/prisma-schema/relations (edited)

**Comment by weaversam8** [comment]
@cannikin - this PR shouldn't be blocked on those updates, I'll handle those when I do the PR for #324 / #316.

**Comment by janpio** [comment]
@cannikin `preview025` is a pretty simple release with 1 breaking change in the package name, and a lot of bugfixes (e.g. for the segfault problem), see https://github.com/prisma/prisma2/releases/tag/2.0.0-preview025 I think it would make sense to get that out quite soon.

The other release we teasered in private, will be a bigger thing as it changes the relation syntax quite fundamentally (and adds a new executable name to the game). Doing that in context with other planned changes that @weaversam8 mentioned would probably make sense.

**Comment by thedavidprice** [comment]
PR for Prisma preview025 is here #350 Just wanted @peterp eyes on it along with my suggested dependency PR upgrading a lot of other packages.

**Comment by thedavidprice** [comment]
We should move Prisma 2.0 Beta topics to another tracking issue / PR.
