### ISSUE TITLE
Add AWS Cognito to redwood/auth

### ISSUE THREAD

**Issue by josuablejeru** [redwoodjs/redwood#3452]
I saw that Redwood supports a lot of Auth providers out of the box except for AWS Cognito.

After I did a little research here on Github and on the forum I was still surprised to find nothing.

Is there a reason why it's missing or could I go and try implementing it myself?

Thanks for your help in advance 🤗.

**Comment by ajcwebdev** [comment]
You are correct there is no current integration with Cognito and I'm unaware of anyone who has done it themselves (although I would guess someone, somewhere has done it and just hasn't documented it yet).

My theory is that Cognito sits in a middle zone between easy third party solutions and hardcore DIY so no one has tackled it yet. I also pointed out the lack of any native AWS auth solution in [this issue](https://github.com/aws-amplify/docs/issues/2583) about Amplify integration.

If you want to implement it I'm sure others would be thankful for someone to chart an initial course, and we're always happy to provide any guidance we can.

**Comment by josuablejeru** [comment]
Thanks, @ajcwebdev for the explanation. I will start then on implementing something that works and we iterate from what. Can I come to you back if I have any questions or are there other contributors I should go to?

**Comment by ajcwebdev** [comment]
Up to you, if you post back here then the core team will see it, if you're looking to get more eyes from the community you could start a [forum post](https://community.redwoodjs.com/).

**Comment by thedavidprice** [comment]
Hey there @josuablejeru Auth provider contributions are _very_ welcome. Here's the info you'll need via the Auth package README:
- https://github.com/redwoodjs/redwood/tree/main/packages/auth

A few things to keep in mind:
- we want to keep the providers as independent as possible (dynamic imports, etc) — use the existing implementations as guides
- if there's anything regarding approach/direction to suss out first, open an issue as an RFC to get feedback
- but don't hesitate to move quickly to a draft PR; that's the easiest way to collaborate (we'll loop in the right maintainers)

Lastly, we are getting _very_ close to a v1 release candidate. This will affect you in two ways:
- the sooner this can get moving the better 'cause we have a growing backlog — ideally this will land before the RC
- we are getting busy, so you'll need to nudge us frequently

Appreciate your patience most of all. Just know it's nothing to do with how excited we'd be to have your contribution here!

**Comment by josuablejeru** [comment]
@thedavidprice @ajcwebdev I have some changes for the Cognito Authprovider. I still have an issue what the login function is not correctly returned (please look at the PR for a screenshot). Hope you don't mind what it is not perfect.

**Comment by ajcwebdev** [comment]
No worries, thanks for taking the time to get the ball rolling. A couple of the core team members are more involved with auth integrations than others so we'll get some eyes on this and provide some notes soon.

cc @dthyresson @cannikin @pi0neerpat @jeliasson

**Comment by jtoar** [comment]
Closing for now; see https://github.com/redwoodjs/redwood/pull/3562#issuecomment-1102700851.
