### ISSUE TITLE
[Router] Typed route params seems broken

### ISSUE THREAD

**Issue by olance** [redwoodjs/redwood#346]
On the tutorial project, I'm faced with a routing issue that looks like a bug with typed route params.

Sample repo: https://github.com/olance/redwood-blog-tutorial

The `/admin/posts` Routes in this project have been added by the scaffold generator (following the tutorial):

```js
const Routes = () => {
  return (
    <Router>
      <Route path="/contact" page={ContactPage} name="contact" />
      <Route path="/blog-post/{id:Int}" page={BlogPostPage} name="blogPost" />
      <Route path="/admin/posts" page={PostsPage} name="posts" />
      <Route path="/admin/posts/{id:Int}" page={PostPage} name="post" />
      <Route
        path="/admin/posts/{id:Int}/edit"
        page={EditPostPage}
        name="editPost"
      />
      <Route path="/admin/posts/new" page={NewPostPage} name="newPost" />
      <Route path="/about" page={AboutPage} name="about" />
      <Route path="/" page={HomePage} name="home" />
      <Route notfound page={NotFoundPage} />
    </Router>
  )
}
```

If I navigate to `/admin/posts/new`, I'm getting the "Something went wrong" error.

In the console, I can see that a `/graphql` call failed, with the following error:

```
Variable "$id" of non-null type "Int!" must not be null.
```

The GraphQL query that had been sent is:

```gql
  query FIND_POST_BY_ID($id: Int!) {
    post: post(id: $id) {
      id
      title
      body
      createdAt
    }
  }
```

Which doesn't make sense for the new Post page.

What I have found is that the error disappears when I move the `/admin/posts/new` route **above** the `/admin/posts/{id:Int}` one:

```js
const Routes = () => {
  return (
    <Router>
      <Route path="/contact" page={ContactPage} name="contact" />
      <Route path="/blog-post/{id:Int}" page={BlogPostPage} name="blogPost" />
      <Route path="/admin/posts" page={PostsPage} name="posts" />
      <Route path="/admin/posts/new" page={NewPostPage} name="newPost" />
      <Route path="/admin/posts/{id:Int}" page={PostPage} name="post" />
      <Route
        path="/admin/posts/{id:Int}/edit"
        page={EditPostPage}
        name="editPost"
      />
      <Route path="/about" page={AboutPage} name="about" />
      <Route path="/" page={HomePage} name="home" />
      <Route notfound page={NotFoundPage} />
    </Router>
  )
}
```

So I believe the `:Int` type in the latter route is not working completely: it catches `new` as a valid ID for route matching, but then probably dismisses it, since `null` is passed to the GraphQL query.

**Comment by cannikin** [comment]
There was PR merged a couple of days ago that may have addressed this: https://github.com/redwoodjs/redwood/pull/336 Are you on the latest version of Redwood, 0.3.2? Could you try this again and see if it's still an issue?

**Comment by olance** [comment]
@cannikin I‘m already on 0.3.2 unfortunately. I don’t think it’s a route order issue?

From what I understood in the tutorial, providing a parameters’’s type is supposed to make sure the route only matches when the param’s value type is correct in the route?
To me it looks more like this part is broken, and placing the /new route above the /{id:Int} one « fixes » things by giving precedence to the more specific/imperative route.

It’s only a guess however. I can try and dig more into this during the week-end.

**Comment by cannikin** [comment]
We had a couple of other folks bring up a similar issue where they had to re-order the routes to get this working and we had a couple PRs which should have put them into an order that worked for everyone. Although I did just see that 0.3.2 we *reverse* the order of the routes as defined in the generator, which may have put them back into the incorrect order again! I'll take a look...

**Comment by cannikin** [comment]
Okay I just generated a scaffold using 0.3.2 and my routes were in the following order:

```jsx
<Route path="/users/new" page={NewUserPage} name="newUser" />
<Route path="/users/{id:Int}/edit" page={EditUserPage} name="editUser" />
<Route path="/users/{id:Int}" page={UserPage} name="user" />
<Route path="/users" page={UsersPage} name="users" />
```

And I can confirm that all the scaffolded pages work in the browser as expected. Is it possible you generated that scaffold on a 0.2.x version?

**Comment by olance** [comment]
@cannikin ha, indeed the routes had been generated by the 0.2.5 version.

But I don’t think that’s the point / don’t understand why you’re focusing on this here.

When I have a `/posts/new` route and a `/posts/{id:Int}` route, no matter their relative position to each other, I’d expect`http://localhost:8910/posts/new` to match the `/posts/new` route, because the `:Int` type of my `id` param should prevent a match on `new`, or any other non-integer value. Given the type constraint, this behavior should not be order-dependent.

That’s not what’s happening here: when the `/posts/{id:Int}` route comes first, `http://localhost:8910/posts/new` is considered a match for it and loads the wrong page, to which a `null` id is the passed.

**Comment by olance** [comment]
To illustrate my point even better, here's a much more telling scenario:

**Routes.js**

```js
...
      <Route path="/admin/posts/new" page={NewPostPage} name="newPost" />
      <Route path="/admin/posts/{id:Int}" page={PostPage} name="post" />
      <Route notfound page={NotFoundPage} />
...
```

**http://localhost:8910/admin/posts/new**
✅ Loads the new post page

**http://localhost:8910/admin/posts/1**
✅ Loads the first post's details

**http://localhost:8910/admin/posts/nope**
❌ "Something went wrong"

![image](https://user-images.githubusercontent.com/314079/77825253-5ea88180-7108-11ea-92a7-3d2d20b0085e.png)

![image](https://user-images.githubusercontent.com/314079/77825262-69fbad00-7108-11ea-962a-4afd6bef59c9.png)

![image](https://user-images.githubusercontent.com/314079/77825285-85ff4e80-7108-11ea-8d1a-d556c0052874.png)

Instead of going all the way down to the `notfound` route for `/posts/nope`, the router matched the `/posts/{id:Int}` route, ignoring the type constraint for `id` (at matching time at least).

**Comment by cannikin** [comment]
Ahhhh yes, okay. So the router isn't really the most robust thing in the world right now, we got it to the point of being able to release 0.1.0 but we know it has a lot of work to go! 😅

Sorry, I was coming from the perspective of knowing that it didn't work all that well, but I knew that as long as the routes are in the right order it'll work. So I was fixated on why your routes were in the wrong order, not the actual underlying problem of the router not really acting as expected.

We've taken a couple of PRs that get the generated routes in the correct order for the tutorial to work for everyone, but not to fix the router itself. We do need something for that!

**Comment by olance** [comment]
Gotcha!
No worries, we all have different contexts ^^

I just opened a PR to fix the issue 😉
