### ISSUE TITLE
Add Directives codemod outputs incorrect filename

### ISSUE THREAD

**Issue by domvernon** [redwoodjs/redwood#3487]
👋 Hi, I was just upgrading to 0.37.0 and ran `npx @redwoodjs/codemods add-directives`. I noticed type checking was failing and it turns out there is an extra `.` added to the file extensions.

```
./api/src/directives
├── requireAuth
│   ├── requireAuth..ts
│   └── requireAuth.test..ts
└── skipAuth
    ├── skipAuth..ts
    └── skipAuth.test..ts
```

Other than this everything seems to have worked very well!

**Comment by thedavidprice** [comment]
Thanks!! We have a fix coming via PR and patch here --> #3486

How's everything else going?!?

**Comment by domvernon** [comment]
😬 apologies, I did try and look to see if this had been raised - I'm going to go with searching in Github not being massively helpful.

It's going very well so far, I'm a DevOps engineer by day so really appreciate the batteries included approach.

**Comment by thedavidprice** [comment]
All good! Moving fast this morning and always appreciate people opening Issues.

Keep us posted.

**Comment by thedavidprice** [comment]
Oh, and we could use a lot of DevOps eyes and knowledge when it comes to things like our api-server for traditional hosting and containerization.

Docker is the hot new discussion over here: https://community.redwoodjs.com/t/dockerize-redwoodjs/2291/21
