### ISSUE TITLE
[RW 37] [Firebase] Null response from getCurrentUser 

### ISSUE THREAD

**Issue by viperfx** [redwoodjs/redwood#3489]
I tried the 0.37 upgrade today and for the most part, the upgrade was smooth. However, authentication with firebase is broken for me. I have followed the upgrade guide to update all the imports.

For me the firebase client on front-end seems to be working but the backend getCurrentUser returns as a null.

Request to firebase from client side SDK - getting the token back as expected.
![image](https://user-images.githubusercontent.com/328257/135663680-1c956b31-210b-48fc-bbb8-6f6aab41c15c.png)

That token then being passed to redwood for the getCurrentUser query.
![image](https://user-images.githubusercontent.com/328257/135663697-10c226c9-f5c8-4a28-9113-384b1d8ae4fb.png)

The response from the query in null
![image](https://user-images.githubusercontent.com/328257/135663733-552a840a-1557-4448-afb5-4a7918eed984.png)

Here is a gist of **App.js** and **getCurrentUser**
https://gist.github.com/viperfx/44c03b8a51b60bc7636a2ee206bbb8c2

Other steps I have taken:

- Nuke node_modules, remove yarn.lock and run yarn.
- Check packages are up to date. These are my package versions.
```
"@redwoodjs/api": "^0.37.0",
"@redwoodjs/graphql-server": "^0.37.0",
"firebase-admin": "^9.11.1",
"firebase": "^9.0.2",
```

**Comment by doesnotexist** [comment]
@viperfx  Are you using type='custom' for your AuthProvider?

I think if thats the case then that is the intended behavior now.  See the following:

https://community.redwoodjs.com/t/redwood-v0-37/2447#2-recommended-change-for-custom-auth-provider-implementations-13

https://github.com/redwoodjs/redwood/blob/main/packages/api/src/auth/decoders/custom.ts#L1-L7

So you could make the getCurrentUser() function on your api side do the decoding instead

Anyhow, perhaps we should add the custom token support to the firebase auth client as per discussion here https://github.com/redwoodjs/redwood/pull/3347#issuecomment-914833479

**Comment by thedavidprice** [comment]
> For me the firebase client on front-end seems to be working but the backend getCurrentUser returns as a null.

@dthyresson feels like the token changes you made are having an affect here, maybe?

**Comment by viperfx** [comment]
So on an unrelated issue - me and @dthyresson were discussing and we realized that I had token out the getCurrentUser function that get passed because I thought the upgrade guide made it seem like that was automatically imported. 

So once that was added - it all works now 🚀

Thanks for everyone's help!

**Comment by dthyresson** [comment]
@thedavidprice I think there was an entire new Firebase v9 upgrade, no? @dac09 Can you confirm Firebase?

**Comment by thedavidprice** [comment]
Awesome!

@viperfx no pressure but nudge to post on Forum upgrade guide if you think anything helpful to community

**Comment by dthyresson** [comment]
Oh, this is the issue @viperfx and I resolved in Slack. Disregard above comments.
