### ISSUE TITLE
[Netlify] GraphQL Function doesn't build without Services

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#3494]
The GraphQL Function doesn't build on Netlify without Services.

### To reproduce:
- create a new project (`yarn create redwood-app netlify-deploy-test`)
- setup netlify deploy (`yarn rw setup deploy netlify`)
- add a home page, whatever you want—but don't add any Services
- deploy to netlify
- after it builds, head to `your-random-domain.app/.netlify/functions/graphql`. you should see:

![image](https://user-images.githubusercontent.com/32992335/135692024-ab01430b-259f-4b69-a9c8-144bd0d117f6.png)

### Suggested fix

In line with the other brute-force PRs we were doing to get this to work, the suggested fix would be to add `graphql-tag` to graphql-server package.json. 

Thanks to @doesnotexist for reporting!

**Comment by dthyresson** [comment]
Not sure about building and deploying to Netlify, but a dev app locally w/out sdl or services is ok.

<img width="378" alt="image" src="https://user-images.githubusercontent.com/1051633/135761685-f50151d3-2125-42e0-a8ec-1f1654034caf.png">

And GraphQL playground is on on dev:

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/1051633/135761707-4f28da55-61ee-4aa2-8ff3-dcb2008bc408.png">


And a GraphQL.schema is generated:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/1051633/135761735-1440ecf3-8ccb-4f70-9884-b8a19b087362.png">

**Comment by dthyresson** [comment]
@jtoar Can we find out form this original poster what db they tried to use, if any? Maybe Prisma client tried to use a SQLite db?

**Comment by dthyresson** [comment]
Local Netlify build and dev is ok.

* `netlify init` and link to site
* `yarn rw setup deploy netlify`
* `netlify build`
* `netlify dev`

Can access local GraphQL playground


Actually, you can't make a GET request to `graphql` in production via a web browser -- the playground is disabled.

@jtoar Try a POST GraphQL query like:

```
query {
  redwood {
    version
    prismaVersion
  }
}
```

**Comment by jtoar** [comment]
@dthyresson sure; @doesnotexist let me know if theres more to it than this. I believe the user just created a new project, setup firebase auth, made a home page and a layout, then deployed to netlify. It sounds like it was just an early deployment to get things rolling.

Here's some messages from discord:

> I've essentially create-redwood-app ,, setup firebase auth and then added a little bit of web side components/layouts/pages
>
> api was essentially unchanged from create-redwood-app and yarn rw setup firebase auth
> just graphql/.keep and services/.keep in those directories
>
> I have one other function which is a remenant from trying out render
healthz.js
>
> I have no services yet
>
> when the app makes a request to .netlify/functions/graphql thats the response
502 status code

The user's api package.json:

```json
{
  "name": "api",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@redwoodjs/api": "0.37.0",
    "@redwoodjs/graphql-server": "0.37.0",
    "firebase-admin": "^9.12.0"
  }
}
```

I believe they also had success locally.

**Comment by dthyresson** [comment]
> when the app makes a request to .netlify/functions/graphql thats the response

Ok, but what exactly are you trying to request from the GraphQL api? What query or mutation is the cell making?

You have to make a proper GraphQL request -- ie, a post with application/json and a properly formed query.

But, what is it querying? Did the redwood version query work? Did the GraphQL api work when using in Postman or Insomnia?

When you say `app makes a request to .netlify/functions/graphql thats the response` I don't know what that means.

If the request is improperly formed, it's going to error.

Sorry to be curt, but if there's not much sense in debugging an api issue when there's no api.

**Comment by dthyresson** [comment]
So, my Netlify app w/ v37.1 and if I try to do

`https://redwoodblog-with-identity.netlify.app/.netlify/functions/graphql` from a browser which you cannot do because it isn't a post and it isn't a properly formatted GraphQL query:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/1051633/135764835-ee2ccce0-821e-4e19-b57c-45b48fed8893.png">

**Comment by dthyresson** [comment]
Can they share the repo?

**Comment by jtoar** [comment]
> Ok, but what exactly are you trying to request from the GraphQL api? What query or mutation is the cell making?

Not sure; just relaying what the user said on Discord. They did have auth setup so it could've been the query the AuthProvider makes for the currentUser? I was just able to reproduce a version of the error using the steps in the original post.

Making a POST request to the deploy in my original post doesn't work for me either. I might have something setup wrong? It can't introspect the schema either.

![image](https://user-images.githubusercontent.com/32992335/135765459-052fb7fa-f707-45a4-a186-aef9bb326ab9.png)

**Comment by doesnotexist** [comment]
Here's a repo that reproduces the issue:
https://github.com/doesnotexist/gqltag-test

Which I've deployed here:
https://rw-gqltag-test.netlify.app

The graphql request is sent when a user is logged in by the call to this.getCurrentUser()
https://github.com/redwoodjs/redwood/blob/main/packages/auth/src/AuthProvider.tsx#L204

**Comment by dthyresson** [comment]
Thanks for the repo. This should help.

> Also the error is retrievable via GET request: https://rw-gqltag-test.netlify.app/.netlify/functions/graphql
> 
> https://simple-service--rw-gqltag-test.netlify.app/.netlify/functions/graphql

So, you cannot make a GET request to the GraphQL server like that -- and in production, the GraphQL playground and introspection is disabled by default for extra security best practices.

Instead, use a tool like Postman or Insomnia to make a POST request with a query.

But, based on the error message, the graphql server isn't up.

**Comment by jtoar** [comment]
Just confirming that #3495 fixed this for me:

![image](https://user-images.githubusercontent.com/32992335/135902326-bf0b6ed1-2ab3-42eb-9ed4-75f9cab9e9cc.png)
