### ISSUE TITLE
With `trailingSlashes="always"` `yarn rw g page` will generate invalid paths

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#3501]
If you have `trailingSlashes` set to `"always"` and generate a new page with `yarn rw g page` the path for the generated page in Routes.tsx will *not* have a trailing space, so it will be impossible to go to.

![image](https://user-images.githubusercontent.com/30793/135767866-750d4ea8-b8a1-4c4d-9431-5d12eba15390.png)

In the screenshot above you can see I generated the "slash" page, and the path is only "/slash". The path should be "/slash/".

I'll work on a fix for this

**Comment by jtoar** [comment]
Very true; thanks @Tobbe!

**Comment by thedavidprice** [comment]
Looping in @KrisCoulson in case there's reason to sync up on this one.

Thanks!
