### ISSUE TITLE
yarn rw g types exit code

### ISSUE THREAD

**Issue by cjreimer** [redwoodjs/redwood#3514]
`yarn rw g types` is very helpful and indicates errors, such as below.

```
Generating...

Not all operations have an unique name: UpdateMilestoneMutation
Not all operations have an unique name: UpdateMilestoneMutation

Error: Could not generate GraphQL type definitions (web)
```

The type generation is also called automatically via various other redwood operations.  If not paying attention to the console, it's easy to miss errors.  

**Would it be possible to produce a failure exit code if there are errors?**  That we could run this command as part of CI checks to ensure that errors do not get overlooked.

**Comment by thedavidprice** [comment]
Please take it away @barakcodes That would be amazing!

Ah yes, that is confusing. This process is used in many places — the `rw g types` command is just a wrapper. The code can be found in this directory within the Internal package:
- https://github.com/redwoodjs/redwood/tree/main/packages/internal/src/generate

**Comment by MichaelrMentele** [comment]
@jeliasson did you debug those errors? When I run the type check itself it says all is well. When I generate my types I get the same generic output.
