### ISSUE TITLE
Contributing on Windows isn't currently possible

### ISSUE THREAD

**Issue by weaversam8** [redwoodjs/redwood#352]
Hey guys. As you know (by now) I'm a Windows user.

[The instructions provided in `CONTRIBUTING.md`](https://github.com/redwoodjs/redwood/blob/master/CONTRIBUTING.md) don't work on Windows, since build scripts take advantage of Linux shell specifics.

For example, `rm` is not a valid command on Windows, and prefixing scripts with `NODE_ENV=production` doesn't work, since that's not how environment variables work on Windows.

To achieve a platform-agnostic build process, I've seen packages use packages like [`win-node-env`](https://github.com/laggingreflex/win-node-env) and [`rimraf`](https://github.com/isaacs/rimraf) to replace these commands.

**Comment by thedavidprice** [comment]
Ah, @weaversam8 we had no idea! A frustrating issue indeed and appreciate you reporting it -- we need all the help we can get 😃

Could you take this PR for a local test run and let me know how it goes? #363

**Comment by weaversam8** [comment]
Yep! I'll take a look at this probably sometime before the end of the week!

**Comment by weaversam8** [comment]
Sorry this took so long, but I just added some feedback [over on the PR](https://github.com/redwoodjs/redwood/pull/363#issuecomment-609467882).
