### ISSUE TITLE
Capitalization inconsistency with `yarn rw g page` generator

### ISSUE THREAD

**Issue by doesnotexist** [redwoodjs/redwood#3568]
Reproducible by doing:
 `yarn rw g page ABTest`

Which will add the following line to Routes.tsx
```
<Route path="/ab-test" page={ABTestPage} name="abTest" />
```
But will generate directory pages/AbTestPage  with AbTestPage.tsx , stories, jest files with the b uncapitalized

**Comment by aggmoulik** [comment]
Thank you @doesnotexist for the update. I will confirm this and create a fix for this.

**Comment by jtoar** [comment]
Hey @aggmoulik, I think we want the latter—to retain the user's capitalization. @doesnotexist You expected the directory and file to be named `ABTestPage/ABTestPage.tsx` right?

**Comment by jtoar** [comment]
I'm with @cannikin in that I'd expect it to be `APIPage` if I typed in `APIPage` but not a hill that I'm going to die on or anything. 

I feel like the chances that someone types in `yarn rw g FOO_BAR` are pretty low; I'm not even sure what kind of casing they would want if they did that
