### ISSUE TITLE
Social Logins, SMS, WebAuthM for magic.links 

### ISSUE THREAD

**Issue by BurnedChris** [redwoodjs/redwood#3569]
Magic.Links now has multiple Social Logins.

![CleanShot 2021-10-14 at 17 19 06](https://user-images.githubusercontent.com/15834048/137357270-72ae7022-d108-4966-84ad-71c758293aee.png)

We can model it from the firebase code. 

https://github.com/redwoodjs/redwood/blob/main/packages/auth/src/authClients/firebase.ts

Happy to start pushing this one forward. :)

**Comment by Burnsy** [comment]
I have added the scaffolding code for WebAuthN, Social, SMS, and the standard magicLink.
