### ISSUE TITLE
Differentiate the Redwood favicon from the generated template favicon

### ISSUE THREAD

**Issue by orta** [redwoodjs/redwood#3575]
My tabs when working in Redwood basically is a sea of pinecones, simple example:

![Screen Shot 2021-10-15 at 12 39 53 PM](https://user-images.githubusercontent.com/49038/137481203-8c3b7af2-e8ba-4184-91f7-9fba7a9b2b08.png)

Perhaps using different colors, or fill types for the generated app's default icon?

![Screen Shot 2021-10-15 at 12 49 33 PM](https://user-images.githubusercontent.com/49038/137482266-d16b6201-1e0c-4d66-9cee-a85c397b92a4.png)

**Comment by Tobbe** [comment]
I think this is a great idea!
Can also play around with different colors.

Gray
![logo_bw](https://user-images.githubusercontent.com/30793/137531020-f62782ba-0b2b-4007-a945-599ee65dbbe0.png) 

Green
![logo_green](https://user-images.githubusercontent.com/30793/137531037-f6567118-2016-4665-b22f-3ce4c49e8251.png)

etc...

**Comment by mojombo** [comment]
Redwood cones are green-ish as they develop, that would be a good choice for your in-dev project!
