### ISSUE TITLE
[Scaffold] When focused on an input with an error, input border should be red

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#3579]
Focusing on the input makes the border gray, but it should stay red:

![image](https://user-images.githubusercontent.com/300/137522287-555099ba-8d98-4e34-b410-2e48ab6080d4.png)

This should just be a matter of adding a `:focus` style in `scaffold.css`.

**Comment by cannikin** [comment]
It's all yours! Let me know if you have any questions!

**Comment by SarveshLimaye** [comment]
@cannikin  I am not able to find the command to run this locally. What should be done after yarn install?

**Comment by cannikin** [comment]
You mean how do you get the scaffold form and fields to exist?

**Comment by SarveshLimaye** [comment]
@cannikin Yes !

**Comment by cannikin** [comment]
You'll need to create a model in `api/db/schema.prisma`, something like this:

```
model Product {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  age   Int?
}
```

And then run `yarn rw prisma migrate dev` and it'll ask you for a name, you can do whatever, like "create product".

Then run `yarn rw g scaffold Product` which will create the pages. 

Start your server with `yarn rw dev` which will open the browser. 

Go to http://localhost:8910/products and then click the "Create New" button. That should bring you to the form. Try to submit it with all of the boxes empty and you'll see the errors!

**Comment by SarveshLimaye** [comment]
@cannikin I am getting error after running command yarn rw prisma migrate dev.

![image](https://user-images.githubusercontent.com/74766567/137625377-7918ee40-2d0d-4c36-8efe-b94b42c6fcda.png)

**Comment by cannikin** [comment]
Ahh you're running those in the actual Redwood codebase. You'd need to run those in a regular Redwood app. I'd suggest doing that (`yarn create redwood-app app-name-here`) and making the changes in the `scaffold.css` file that gets created after you run the scaffold generator. Then once the styles look good, add them to the `scaffold.css.template` file that's here in the main Redwood repo: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/scaffold/templates/assets/scaffold.css.template
