### ISSUE TITLE
[Scaffold] Browser console error for `transformValue` prop

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#3582]
Getting this error in the console when viewing a form that contains a `transformValue` prop on an element:

![image](https://user-images.githubusercontent.com/300/137528211-94808e76-e9fe-4d52-9032-5a5e3c94567a.png)

The form contains this `<TextField>`:

```jsx
<TextField
  name="price"
  defaultValue={props.product?.price}
  className="rw-input"
  errorClassName="rw-input rw-input-error"
  transformValue="Float"
/>
```

Not sure if it really is as simple as renaming the prop `transformvalue` or if we need to somehow tell React not to freak out about that prop name?

**Comment by jtoar** [comment]
> Should we keep this open until we fix the scaffold templates, as a reminder? 
Yeah let's! I've already assigned myself so I know to fix it 👍
