### ISSUE TITLE
Publish redwood vscode extension to Open VSX Registry

### ISSUE THREAD

**Issue by greg-hoarau** [redwoodjs/redwood#3586]
Hello,

I'm new to RedwoodJS and i'm trying to setup it with Gitpod. 

It would be cool to make the vscode extension available on the Open VSX registry so that we can use it on Gitpod (and others).

**Comment by orta** [comment]
For Svelte we use CI to publish both to vscode/openvsx - https://github.com/sveltejs/language-tools/blob/master/.github/workflows/DeployExtensionsProd.yml when a human makes a tag for it

**Comment by thedavidprice** [comment]
This is a great idea @greg-hoarau The current published extension is effectively deprecated as it's very out of sync with the latest Redwood version. The good news is that there's a entire rewrite underway!

I'm labeling this to group with the group of issues we'll be prioritizing once the new extension is in beta. Thanks!

cc @jtoar @aldonline

**Comment by Josh-Walker-GM** [comment]
Hey all! I'm going to close this issue for just now. Feel free to reopen and restart the discussion at any time. We don't currently support a redwood vscode extension and we don't have it planned for the near future. Although we certainly can discuss prioritising it more if there is demand for it.
