### ISSUE TITLE
Create an Issue + PR Template that links to a Forum Post about v1 Roadmap Status

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#3587]
We are nearing the release of v1-rc, which means 1) we have completed core feature for v1, and 2) we have completed all (known) breaking features. Between the v1-rc and final v1 release, we will hold new features and breaking changes. This means we'll need to say "not yet" to incoming ideas, Issues, and PRs that fall into one of those two buckets (new feature or breaking).

This needs to be communicated to contributors.

Next Steps:
- @mojombo is going to post an article on the Forum with current v1 status, describing the process and steps forward to a v1
- @thedavidprice will create an Issue and PR Template that links to the post

**Comment by thedavidprice** [comment]
@mojombo nudge on this one; v0.39 priority

**Comment by mojombo** [comment]
Discourse post done! https://community.redwoodjs.com/t/what-the-1-0-release-candidate-phase-means-and-when-1-0-will-drop/2604
