### ISSUE TITLE
Confirm Auth provider templates are correctly typed

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#3596]
@dthyresson I'm not sure if your TS work in https://github.com/redwoodjs/redwood/pull/3431 has been correctly applied (and is still in sync) across all provider templates. Could you please take a look and evaluate if there are any further steps needed to reconcile across providers?

There was a `setup auth` fix for TS (plus template update) in this recent PR:
- https://github.com/redwoodjs/redwood/pull/3567/files

And there are several open PRs. I believe these include updates to Auth template:
- https://github.com/redwoodjs/redwood/pull/3337/
- https://github.com/redwoodjs/redwood/pull/3537/

And these do not:
- https://github.com/redwoodjs/redwood/pull/3490/
- https://github.com/redwoodjs/redwood/pull/3572/
- https://github.com/redwoodjs/redwood/pull/3562/

**Comment by dthyresson** [comment]
Added comments to #3562 but not sure yet is it need a custom template or not.

**Comment by thedavidprice** [comment]
cc @dac09

**Comment by pi0neerpat** [comment]
> I chatted with @pi0neerpat on Discord a few weeks ago and I believe he know has a different idea to update this provider based on some recent OAuth work.

Yup, made the issue just haven't had time https://github.com/oneclickdapp/ethereum-auth/issues/7

**Comment by thedavidprice** [comment]
@pi0neerpat did you see my question [over here in Forum](https://community.redwoodjs.com/t/eth-auth-to-extend-dbauth/2517/8?u=thedavid) about deprecating current Eth Auth?

**Comment by pi0neerpat** [comment]
Yeah, Idk why it needs to be deprecated. It still works fine. The new version will just be better.

**Comment by thedavidprice** [comment]
It's fine as is. We're headed into v1-rc cycle with the goal of having breaking changes completed beforehand. In general, I'm not sure what this means for Auth providers. So let's just take it a step at a time.

**Comment by pi0neerpat** [comment]
Ok yeah, I guess I see auth providers more as “external” add-ons rather than core rw.
