### ISSUE TITLE
[Router] NavLink and LocationProvider not implemented

### ISSUE THREAD

**Issue by RobertBroersma** [redwoodjs/redwood#360]
I noticed in `@redwoodjs/router` there's a `NavLink` exposed to provide some active styles for `Link` components, however using it crashes the app as `LocationProvider` is not yet implemented/exposed.

I'm in need for some active link styles in my app. Is there a vision for how to implement this?

I'd be happy to create a PR if there is!

Also curious what you guys think about a `getProps` prop for `NavLink` like in `@reach/router` (https://reach.tech/router/api/Link). This would be very helpful for people using `styled-components` or `emotion`.

Another alternative/extra option could be something like `useMatch` like in Reach Router so you can roll your own active link.

**Comment by thedavidprice** [comment]
@mojombo looping you in on this one when you have a chance.
