### ISSUE TITLE
Proposal for Input Mask

### ISSUE THREAD

**Issue by augustnmonteiro** [redwoodjs/redwood#3608]
One thing that most of the frameworks forget to add is input making.

We could have in redwood an attribute `mask` for the `TextField, NumberField`.

requirements for an input mask are:
* Direction (Enum: Start, End) (where does cursor should start in the mask)
* Pattern (String)
* FixedMaskPlacehold (String)

The fixed mask is for things like:
the input is going to show `0.000` and the user is going to type and replace the 0's to the actual number that it is typed

**Comment by thedavidprice** [comment]
@augustnmonteiro Couple more questions about this:
1. how is this different than an input placeholder? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-placeholder
2. could you provide an example via a link, screencast, etc?

**Comment by jtoar** [comment]
Closing for now due to inactivity, but thanks for the suggestion!
