### ISSUE TITLE
Update custom auth generator to generate auth client

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3617]
### What?
Currently the custom auth generator just changes App.tsx/js with the Auth provider, and generate src/lib/auth for the API side

However, its missing a crucial piece - generating the "scaffold" or an unimplemented custom auth client for the web side

### Why?
Often when you create a custom auth, you're looking for more control over the methods used to login/signup/logout - even if its a provider that we officially support. 

### Things to consider

- [ ] Generate AuthProvider for web
- [ ] Generate AuthClient to pass to the AuthProvider
- [ ] Modify App{.tsx/js} (and maybe other relevant parts of web) to use these custom client and provider
- [ ] Make sure `useAuth` uses custom client (or generate a customUseAuth hook)
- [ ] Do we need to update the types for AuthClient to be more flexible with types? I don't think so, but worth checking
- [ ] We don't want to encourage "all sorts" of auth at this stage. The limitation around the custom auth client should be that it uses a bearer token in requests, and sets the auth-provider to custom, the same way all the other auth providers do. 
- [ ] Provide documentation on how all this works, including if we want a custom serverless function to do the auth functionality for us (kind of like how dbAuth does)

**Comment by thedavidprice** [comment]
Hi all! Any further thoughts about this one? Especially when/if to prioritize it on the roadmap?

**Comment by doesnotexist** [comment]
Sorry, I haven't had a chance to really look into this or the related issue.  I'm happy if anyone else wants to take a crack, otherwise I'll try to come back to it in a few weeks time.

**Comment by Tobbe** [comment]
Work on this is ongoing in https://github.com/redwoodjs/redwood/pull/5985

Most things in Danny's list are already handled. Only thing I'm not doing is anything that touches stuff on the api side
