### ISSUE TITLE
[Feature] Apollo compatible Automatic Persisted Queries

### ISSUE THREAD

**Issue by ccollie** [redwoodjs/redwood#3619]
Spec: https://github.com/apollographql/apollo-link-persisted-queries#apollo-engine
Apollo: https://www.apollographql.com/docs/apollo-server/performance/apq/

WIP implementation:
https://github.com/ccollie/redwood/commits/automatic-persisted-queries

**Comment by dthyresson** [comment]
@thedavidprice I believe that persisted queries is different that the GraphQL cache. A persisted query stores the "query" ie what to fetch as a pre-parsed hash which is much smaller to send that a large query test payload. It's smaller and pre-parsed so it can just execute. The cache you noted is caching the response -- the result of the query.

@ccollie I believe that the Envelop plugin https://www.envelop.dev/plugins/use-persisted-operations is the equivalent, but am checking with the Guild if this is the cases.

**Comment by dthyresson** [comment]
@ccollie Yes, I confirmed that https://www.envelop.dev/plugins/use-persisted-operations is the plugin you can use to have similar hashed stored, pre-parsed queries defined like APQ.

However, this plugin doesn't whitelist all the queries you are allowed to run.

> Basically persisted queries are has 2 purposes:
> 1 - performance - skips parsing because you know the hash. and clients only sends hash over the network instead of a whole query.
> 2 - security - you can "lock" your graphql server for serving only known queries.

This plugin doesn't necessarily do 2. But that is something the Guild can look into maybe via a different plugin.

You would add the plugin to the `extraPlugins` configuration in your GraphQLHandler.

The plugin support other stores other than an in memory store like a JSON file store where you can predefine the queries.

Will this plugin work for you?

**Comment by ccollie** [comment]
@dthyresson this is different from  https://www.envelop.dev/plugins/use-persisted-operations precisely because of your point 2

> 2 - security - you can "lock" your graphql server for serving only known queries.

Instead of allowing only a particular set of queries defined a _build-time_, this plugin optimizes for arbitrary `graphql` at _runtime_ using (by default) a capped `lru` cache.  Of course this is necessarily less secure, but this is the case for any server not using persisted queries anyway.

The current envelop plugin is different in purpose (locked as opposed to arbitrary queries). More importantly `helix's` `processRequest` needs a resolved query before invoking `envelop`'s magic, whereas the [`APQ` protocol](https://github.com/apollographql/apollo-link-persisted-queries#apollo-engine) specifically relies on client-server negotiation in the case of cache misses. This is possible only at the level of the request handler as returned by `createGraphQLHandler`, not of the plugin.

**Comment by dthyresson** [comment]
> @dthyresson this is different from https://www.envelop.dev/plugins/use-persisted-operations precisely because of your point 2
> 
> > 2 - security - you can "lock" your graphql server for serving only known queries.
> 
> Instead of allowing only a particular set of queries defined a _build-time_, this plugin optimizes for arbitrary `graphql` at _runtime_ using (by default) a capped `lru` cache. Of course this is necessarily less secure, but this is the case for any server not using persisted queries anyway.
> 
> The current envelop plugin is different in purpose (locked as opposed to arbitrary queries). More importantly `helix's` `processRequest` needs a resolved query before invoking `envelop`'s magic, whereas the [`APQ` protocol](https://github.com/apollographql/apollo-link-persisted-queries#apollo-engine) specifically relies on client-server negotiation in the case of cache misses. This is possible only at the level of the request handler as returned by `createGraphQLHandler`, not of the plugin.

@dotansimha This is the persisted query topic we discussed earlier today. Do you have any ideas for which envelop plugins may fit better for this use case?

**Comment by dotansimha** [comment]
> Instead of allowing only a particular set of queries defined a _build-time_, this plugin optimizes for arbitrary `graphql` at _runtime_ using (by default) a capped `lru` cache. Of course this is necessarily less secure, but this is the case for any server not using persisted queries anyway.

This is what `useParserCache` and `useValidationCache` plugins are doing - it's using LRU to cache the parser and validation response. 
If you wish to extend that wish a hashing mechanism to add APQ functionality, you can do that by adding an Envelop plugin to extract the incoming hash from your incoming request and add that to your cache, and this way you can avoid parsing and validating of the same operation.

**Comment by ccollie** [comment]
> If you wish to extend that wish a hashing mechanism to add APQ functionality, you can do that by adding an Envelop plugin to extract the incoming hash from your incoming request and add that to your cache, and this way you can avoid parsing and validating the same operation.

Thanks for the feedback, @dotansimha.  I [tried initially](https://github.com/dotansimha/envelop/issues/496) to do this in `envelop` itself but hit a roadblock. I'll give it a shot later this week.

**Comment by ccollie** [comment]
@dotansimha from a cursory look, it seems like this should _mostly_ work. Has there been a discussion about making hooks _async_ ?

**Comment by dotansimha** [comment]
> @dotansimha from a cursory look, it seems like this should _mostly_ work. Has there been a discussion about making hooks _async_ ?

If we'll make some of the functions as `async`, this will lead to a different signature of `parse` and `validate` functions, and eventually will lead to errors when trying to integrate it with existing servers that assumes that `parse` / `validate` are sync. 

We are trying to make sure the signature of enveloped functions always matches the signature of `graphql-js` to make sure it's just wraps without modifying it.

**Comment by dotansimha** [comment]
> Thanks for the feedback, @dotansimha. I [tried initially](https://github.com/dotansimha/envelop/issues/496) to do this in `envelop` itself but hit a roadblock. I'll give it a shot later this week.

I think we can try to find a way to allow you to run this. A lot has changed in `envelop`'s core since then ;)

**Comment by ccollie** [comment]
@dotansimha thanks for the feedback. I'll have another look.

**Comment by dthyresson** [comment]
We've implemented Persisted Operations with Yoga and Apollo Client: https://github.com/redwoodjs/redwood/pull/9416
