### ISSUE TITLE
upgrade Yargs from v16.2.0 to v17

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#3621]
cc @jtoar 

Releases:
- https://github.com/yargs/yargs/releases

Breaking changes:
- https://github.com/yargs/yargs/releases/tag/v17.0.0

I attempted a naive upgrade, which didn't work. Couldn't quickly diagnose the issue.

Ideally we'd include this in v1-rc

**Comment by jtoar** [comment]
Upgraded in https://github.com/redwoodjs/redwood/pull/5416.
