### ISSUE TITLE
Upgrade ESLint from v7 to v8

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#3623]
_Ideally this will be upgraded for v1-rc._

### ESLint Release Notes:
- https://github.com/eslint/eslint/releases/tag/v8.0.0

After naive upgrade, I hit the following error:
```
$ yarn lint

Oops! Something went wrong! :(

ESLint: 7.32.0

ESLint couldn't find the plugin "eslint-plugin-react".

(The package "eslint-plugin-react" was not found when loaded as a Node module from the directory "/Users/price/Repos/redwoodjs-redwood".)
```

Ideally this will be upgraded for v1-rc.

**Comment by nzdjb** [comment]
Howdy,

I gave this a shot, but found after getting set up that there's no current release of eslint-plugin-react that is compatible with eslint 8: https://github.com/yannickcr/eslint-plugin-react/issues/3055

They have a PR to resolve that: https://github.com/yannickcr/eslint-plugin-react/pull/3059

Looks like there are other plugins that will need updating too, but I haven't found the status of those yet. Will look into them later on.

**Comment by dac09** [comment]
Requesting a HODL ✋ on this till we merge in the babel changes that are going in #3719 please!
