### ISSUE TITLE
[RFC] Run dedupe after rw upgrade

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3641]
Until we migrate redwood projects to yarn 3, it may be helpful to run `npx yarn-deduplicate` towards the end of the `rw upgrade` process.

This makes sure:
a) No duplicate deps exist in the yarn.lock
b) Prevents difficult to diagnose errors happening, and does _not_ require the user to regenerate a lockfile

This may not be necessary if we upgrade projects to yarn 3 because...
> This package only works with Yarn v1. Yarn v2 supports package deduplication natively!

**Comment by thedavidprice** [comment]
Yes. Yes we should!

Implementation suggestion: make this an option, defaulting to enabled, just in case someone need to skip it.

@SimeonGriggs and @callingmedic911, would either of you be able to prioritize this for the current release cycle?

**Comment by callingmedic911** [comment]
@thedavidprice I think you meant to tag @simoncrypta. But everyone's welcome here. 🥳

This should be a fairly short one, I think I should be able squeeze this one. @simoncrypta Let me know if you're interested in this one. 🙂
