### ISSUE TITLE
Reconsider `yarn rw test` flag `--runInBand`

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#3646]
For `v0.38`, due to a pseudo-random break, we had to change `yarn rw test` to "run in band" for each side. To be clear, this was already the case if you didn't specify a side. But if you specified just "web", they didn't run in band.

The reason we had to do this in the first place is that we were getting a `TextDecoder is not defined` error: https://github.com/redwoodjs/redwood/pull/3611. But as performance becomes more of a priority, we'll want to reconsider `--runInBand` if we can since it slows down running test suites.

**Comment by dac09** [comment]
Update: I managed to fix this using a custom jest environment for web, but then ran into issues when making babel changes.

Using a custom environment that loads TextEncoder and Decoder:
✅ No issues with TextDecoder not being defined
🛑 Failing to load babel settings when provided programatically to `babel-jest` via jest config
