### ISSUE TITLE
Getting Netlify deploy failures due to Node.js version? 

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#3647]
[Node.js v16.x entered Long Term Support (LTS)](https://nodejs.org/en/blog/release/v16.13.0/) on October 27th. For some deployment configurations, this might have caused your Netlify Build to fail. Here's what might be going on.

## How it works
**1. Check your Node.js engine version in ./package.json**
Example:
```
...
  "engines": {
    "node": ">=14.x",
    "yarn": ">=1.15"
  },
...
```

**2. Then check your `.nvmrc` file**
Example:
```
lts/*
```

_Does your project have similar settings?_ If so, this will fail the Netlify build. Here's why:
- Node.js engines are restricted to v14.x _only_
- Netlify uses `.nvmrc` to set the Build container Node.js version. In this case it's LTS, which is now Node.js 16.x

The Build container is using a Node.js version that your package.json does not allow.

## How to set your config
There are a few things you can do to fix this configuration conflict.

### Upgrade to Redwood v0.38
Redwood v0.38 is compatible with Node.js v16.x. 
- Read the [Release Notes](https://community.redwoodjs.com/t/redwood-v0-38/2506) and Upgrade

### Change your .nvmrc
For the example above, you would want to set the .nvmrc file to use Node.js v14. Update `.nvmrc`:
```diff
- lts/*
+ v14
```

## Final Steps
To apply the changes, you'll most likely need to Trigger a Deploy with the cache cleared.

<img width="266" alt="Screen Shot 2021-10-27 at 6 53 13 PM" src="https://user-images.githubusercontent.com/2951/139172615-39f072c2-f354-4e9d-9d6c-ef28d120da8e.png">

**Comment by thedavidprice** [comment]
Ah, @aggmoulik good idea. But I agree with @dac09 that we don't want to do this on the .com site directly. However, we could do a better job of pointing people to the GitHub Issues and Forum when they have issues. Not a priority, but a good idea for the future.

For now, a post on the Forums could be helpful (even if just linking to this Issue). Would you be able to do that @aggmoulik?

**Comment by doesnotexist** [comment]
Changing .nvmrc to v14 helps for deploying the v0.37 of my project.  However, I am unable to upgrade to v0.38 and successfully deploy to netlify.  Running into the size limit for the graphql function
```
2:50:33 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
2:50:33 PM: Failed to upload file: graphql
```

In addition to the instructions in this ticket, I also tried the npx yarn-deduplication from the upgrade guide but I don't think there was anything to deduplicate as my yarn.lock remain unchanged.

**Comment by thedavidprice** [comment]
@doesnotexist any updates here or still stuck on function size blowing up? These things can be tough to diagnose and, frankly, we've been struggling with Netlify's build the past few releases. My guess is you'll be just fine deploying if you make the switch to Vercel.

Please keep me posted.

**Comment by jtoar** [comment]
Netlify deploy has been quite stable since v1. Closing mainly due to staleness, and that things are so different now it'd be hard to diagnose whatever the original problem was.

Note that we could definitely still reduce the size of functions... see https://github.com/redwoodjs/redwood/issues/5160
