### ISSUE TITLE
Problems installing Redwood on Windows

### ISSUE THREAD

**Issue by yanielbf** [redwoodjs/redwood#3654]
Hi, I find RedwoodJs interesting and I'm starting to review it. When I try to install it in Windows using the command "yarn create redwood-app ./redwoodblog" from the documentation when I try to convert the typescript files to js it throws an error with the module ts-to-js.
![Captura](https://user-images.githubusercontent.com/11427255/139559140-c1fa007d-028d-4d91-ad61-6359a4592bc8.PNG)
s.

**Comment by Tobbe** [comment]
Hi @yanielbf. Sorry I'm replying in English, but I don't know any Spanish at at all 🙁 

Could you please try to install using git-bash instead?

**Comment by thedavidprice** [comment]
Here's a helpful post from the Redwood Forums:
- https://community.redwoodjs.com/t/thebest-windows-setup/2439

**Comment by simoncrypta** [comment]
I tested it with Git-Bash and also PowerShell on Windows and everything works now. 

```
  System:
    OS: Windows 10 10.0.21996
  Binaries:
    Node: 14.18.2 - ~\AppData\Local\Temp\yarn--1639250388301-0.9331442747944398\node.CMD
    Yarn: 1.22.17 - ~\AppData\Local\Temp\yarn--1639250388301-0.9331442747944398\yarn.CMD
  Browsers:
    Edge: Spartan (44.21996.1.0), Chromium (96.0.1054.43)
  npmPackages:
    @redwoodjs/core: 0.39.4 => 0.39.4
```

**Comment by simoncrypta** [comment]
@yanielbf @thedavidprice Should I close the issue ?

**Comment by jtoar** [comment]
@yanielbf feel free to reopen this if none of the suggestions above solved your issue.
