### ISSUE TITLE
Upgraded to v0.38 Jest db teardown Prisma +  Postgresql violation

### ISSUE THREAD

**Issue by LBrian** [redwoodjs/redwood#3655]
It seems `Prisma v3` upgrade breaks existing `Jest` teardown db clean up due to table dependency violation.
![Screen Shot 2021-10-31 at 5 46 14 pm](https://user-images.githubusercontent.com/3888780/139571857-9dc63f17-0511-4361-9c46-0bb7aedf5f5c.png)

Long story short, I have two tables, `Company` and `CompanyProfile`, they are basically coupled so when creating a new company will automatically create a new `companyProfile` as well then linked together, looks like the teardown trying to delete the `Company` table but due to relation so it is prohibited. I did a quick try by disabling `createCompanyProfile` in the `createCompany` service and it works just fine.

<img width="577" alt="Screen Shot 2021-10-31 at 5 46 22 pm" src="https://user-images.githubusercontent.com/3888780/139571837-a61049ad-6645-469d-b199-b1abff356828.png">
<img width="466" alt="Screen Shot 2021-10-31 at 5 50 14 pm" src="https://user-images.githubusercontent.com/3888780/139571846-9c75936a-4388-48fd-9d7f-27942abb34fd.png">
)

**Comment by thedavidprice** [comment]
Thanks for reporting this @LBrian 

@cannikin is this related to #3680? Either way, do you think this should be prioritized for a v0.38 patch?

**Comment by cannikin** [comment]
Yep looks like the same error I was seeing. Is there a Prisma-approved way to get around this I wonder? Otherwise, my suggestion in that issue works, but it's not the most elegant thing in the world. You either need to define that `global` in every test file, or figure out some shared place to put it so it's always set before any test...

```javascript
global.modelDeleteOrder = ['CompanyProfile', 'Company']
```

**Comment by cannikin** [comment]
Apparently you can tell deletes to be cascaded in Prisma now: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions

So this gets around this problem, but having a cascading delete may not be something they want to do depending on the use case. Hmmm...

**Comment by thedavidprice** [comment]
@cannikin Got it. Can you dig into this one? Seems like a priority bug to fix for this release cycle. Do let me know otherwise.

**Comment by cannikin** [comment]
In your use case @LBrian can you update your schema to have cascading deletes? https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions  And if so, does that fix the issue?

**Comment by LBrian** [comment]
> Apparently you can tell deletes to be cascaded in Prisma now: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions
> 
> So this gets around this problem, but having a cascading delete may not be something every person wants to do, depending on the use case. Hmmm...

@cannikin Awesome, that is good to know that but agreed with you it might not be always the case to delete relation. I disabled all my service tests at the moment as for `Company` and `CompanyProfile` I can do that for sure, but few of my tables dependency there are not 1-1 could be 1-many (e.g. `Address` of `Company` and `User` of `Company`). I will give it a try and dig in any better alternative solution.

**Comment by LBrian** [comment]
@cannikin  👆 cascading solves my issue, looked into my entire db schema it makes sense to have cascading enabled. 👍

**Comment by thedavidprice** [comment]
@cannikin possible to prioritize this for v0.39?

**Comment by cannikin** [comment]
@thedavidprice Let's discuss on Tuesday and see if we can come up with a reasonable solution...my personal fix was to use a `global` but there be other ways someone can suggest!

**Comment by cannikin** [comment]
We've got a plan! No need for a global, we'll have the computer figure this out. PR coming soon...

**Comment by dac09** [comment]
Reopening as the fix only solves on sqlite.... if only Prisma gave us a type for this.

**Comment by cannikin** [comment]
How come no one cares about MySQL

**Comment by ajcwebdev** [comment]
I would guess because of the hosting options are just so much nicer with PostgreSQL right now. Railway's got a nice MySQL offering but that's the only I know of except for maybe PlanetScale which is a few layers removed but ultimately MySQL.

**Comment by thedavidprice** [comment]
PR #3724 got us to 75% completion. Final To Do:
- [ ] Add SQLServer error code

**Comment by domvernon** [comment]
Hi, unfortunately the latest patch still doesn't quite do it for me in Postgres:
```
Raw query failed. Code: `42601`. Message: `db error: ERROR: syntax error at or near "User"`
```
I tested what the code was doing with raw statements through PSQL and `DELETE from User` doesn't work, whereas `DELETE from "User"` does. I'm not sure the implication of adding quotations for every model, but this might work.

**Comment by tilmann** [comment]
I ran in the same problem with postgres

Fixed it for now by changing ```await db.$executeRawUnsafe(`DELETE from ${modelName}`)``` to ```await db.$executeRawUnsafe(`DELETE from "${modelName}"`)``` in `jest.setup.js`

I don't know if this change will throw errors for other database systems.

**Comment by domvernon** [comment]
Single quotes in postgres is still causing a syntax error for me. This actually lines up with Prisma documentation that explains how it works. https://www.prisma.io/dataguide/postgresql/short-guides/quoting-rules

**Comment by cannikin** [comment]
HMMMMMMMM But according to that, quotes are kind of optional? But you're getting an error without them? It even says:

> It is much more common to see the identifier unquoted entirely
>
> `SELECT * FROM customer;`

Maybe it's a Postgres config setting that enforces that you HAVE to use double quotes around table names?

**Comment by domvernon** [comment]
I did some further testing and thought it must be something to do with specific DDL:
```
test=# select * from "User";
 id | uuid | email | createdAt | updatedAt 
----+------+-------+-----------+-----------
(0 rows)

test=# select * from User;
    user     
-------------
 testuser
(1 row)

test=# delete from user;
ERROR:  syntax error at or near "user"
LINE 1: delete from user;
                    ^

test=# delete from "User";
DELETE 0
```

Then I realised that `user` is a [reserved word](https://www.postgresql.org/docs/13/sql-keywords-appendix.html) so this would have been confounding things.

Nevertheless testing on a different table yields:
```
curtaincall_test=# delete from "UserRole";
DELETE 0
curtaincall_test=# delete from UserRole;
ERROR:  relation "userrole" does not exist
LINE 1: delete from UserRole;
```

Due to the naming conventions from the Redwood generators (I think), it seems we do need to preserve the case sensitivity with the double quotations somehow.

**Comment by cannikin** [comment]
Ugh. Well, we're already parsing `schema.prisma` in here to determine what models to delete, hopefully there's an entry in there for your db provider. 

If `postgres` then use quotes, otherwise not.

😬

**Comment by domvernon** [comment]
Yes there is:
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

**Comment by cannikin** [comment]
haha That's reading the file directly, which we could do, but the Prisma SDK has a function `getDMMF()` that turns that file into a big object, parsing out all their syntax and turning it into something like:

```
  "models": [
    {
      "name": "User",
      "isEmbedded": false,
      "dbName": null,
      "fields": [
        {
          "name": "id",
          "kind": "scalar",
          "isList": false,
          "isRequired": true,
          "isUnique": false,
          "isId": true,
          "isReadOnly": false,
          "type": "Int",
          "hasDefaultValue": true,
          "default": {
            "name": "autoincrement",
            "args": []
          },
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "email",
          "kind": "scalar",
          "isList": false,
          "isRequired": true,
          "isUnique": true,
          "isId": false,
          "isReadOnly": false,
          "type": "String",
          "hasDefaultValue": false,
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "name",
          "kind": "scalar",
          "isList": false,
          "isRequired": false,
          "isUnique": false,
          "isId": false,
          "isReadOnly": false,
          "type": "String",
          "hasDefaultValue": false,
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "posts",
          "kind": "object",
          "isList": true,
          "isRequired": true,
          "isUnique": false,
          "isId": false,
          "isReadOnly": false,
          "type": "Post",
          "hasDefaultValue": false,
          "relationName": "PostToUser",
          "relationFromFields": [],
          "relationToFields": [],
          "isGenerated": false,
          "isUpdatedAt": false
        }
      ]
    }
  ]
```

I'll have to inspect and see if it also has entries for the datasource stuff.

**Comment by domvernon** [comment]
🤦‍♂️I knew it couldn't be that simple!

**Comment by cannikin** [comment]
Ugh, just checked and the fact that you're using Postgres is *not* output anywhere in their parsing of the data model :( (It's got 20,000 entries, though!)

https://gist.github.com/cannikin/3b13392b0ed71e15947d3326f29d3d2d

**Comment by mojombo** [comment]
Prisma has to deal with this quoting issue, I wonder if they have a function you can import and use that knows the right thing to do.
