### ISSUE TITLE
Allow custom options to createGraphQLHandler

### ISSUE THREAD

**Issue by chris-hailstorm** [redwoodjs/redwood#366]
ENVIRONMENT

0.3.2

OBSERVATION

I needed to pass CORS settings to the `createGraphQLHandler` function in `node_modules/@redwoodjs/api/dist/graphQLServer.js` (runtime), originating in `../packages/api/src/graphQLServer.ts`.

Original code:

    const handler = new ApolloServer({
      playground: process.env.NODE_ENV !== 'production',
      ...options,
      context: handleContext(options),
    }).createHandler()

My ugly, local, dev-only patch:

    const handler = new _apolloServerLambda.ApolloServer({
      playground: process.env.NODE_ENV !== 'production',
      ...options,
      cors: { origin: '*', credentials: true },      // ADDED THIS
      context: handleContext(options)
    }).createHandler();

REQUEST

Let me provide an options object that's merged over the existing option keys.

Maybe there's already a way to do this, if so please point me in that direction!

If not, then some conventional place under `/api` where this can be defined.

Thanks!

**Comment by arjunv27** [comment]
To hook onto this thread, I'm attempting to add apollo-link-state for the web component, config requires me to hook into ApolloClient in packages/web/src/graphql/index.js

**Comment by chris-hailstorm** [comment]
I think this is resolved via the recent `./api/src/functions/graphql.js` module.

The options object passed to `CreateGraphQLHandler` in that module is expanded via the `...options` line in the above code sample.  Basically this file is now accessible in app source.

**Comment by peterp** [comment]
@chris-hailstorm Yup! This works right, can I close this off?

**Comment by steveharrison** [comment]
Like @arjunv27 mentioned, it would be great if a hook existed for passing a custom `ApolloClient` instance (rather than `ApolloBoost`) in `createGraphQLClient` in `@redwoodjs/web/dist/graphql/index.js`.

I'm happy to create a separate issue for this and do a pull request, but would appreciate some guidance on what you think the best way of doing this would be! 🙂

**Comment by peterp** [comment]
@steveharrison thanks for mentioning this! I'm actually busy adding this functionality right now because of the authentication stuff that I'm building.

**Comment by chris-hailstorm** [comment]
@peterp I think this can be closed with a small add to the how-to doco.

**Comment by dthyresson** [comment]
See the options available now as part of https://github.com/redwoodjs/redwood/pull/2827

```js
interface GraphQLHandlerOptions {
  /**
   * Customize GraphQL Logger
   */
  logger: BaseLogger

  /**
   * Modify the resolver and global context.
   */
  context?: Context | ContextFunction

  /**
   * An async function that maps the auth token retrieved from the request headers to an object.
   * Is it executed when the `auth-provider` contains one of the supported providers.
   */
  getCurrentUser?: GetCurrentUser

  /**
   * A callback when an unhandled exception occurs. Use this to disconnect your prisma instance.
   */
  onException?: () => void

  /**
   * The GraphQL Schema
   */
  schema: GraphQLSchema

  /**
   * CORS configuration
   */
  cors?: CorsConfig

  /**
   * Healthcheck
   */
  onHealthCheck?: OnHealthcheckFn

  /**
   * Limit the complexity of the queries solely by their depth.
   * @see https://www.npmjs.com/package/graphql-depth-limit#documentation
   */
  depthLimit?: DepthLimitConfig

  /**
   * Only allows the specified operation types (e.g. subscription, query or mutation).
   *
   * By default, only allow query and mutation (ie, do not allow subscriptions).
   *
   * @see https://github.com/dotansimha/envelop/tree/main/packages/plugins/filter-operation-type
   */

  allowedOperations?: AllowedOperations

  /**
   * Custom Envelop plugins
   */
  extraPlugins?: Plugin<any>[]

  /**
   * Customize the GraphiQL Endpoint
   *
   * Defaults to '/graphql'
   *
   */
  graphiQLEndpoint?: string
}
```


This issue seems out of date.

**Comment by dthyresson** [comment]
I believe you'd [write an envelop-based plugin](https://www.envelop.dev/docs/plugins) and then add to `extraPlugins`
