### ISSUE TITLE
Support Supertokens JWT Authentication

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#3679]
@rishabhpoddar noted that Supertokens https://supertokens.io will have a JWT-based authentication mechanism that better fits with Redwood's authentication provider and clients vs the current cookie mechanism.

We have closed https://github.com/redwoodjs/redwood/pull/2220 in favor of waiting for this new feature to be available and then will implement.

**Comment by aggmoulik** [comment]
Hey @dthyresson, Can I continue this issue?

**Comment by rishabhpoddar** [comment]
@aggmoulik we have yet to release our JWT based auth. Once that is done, you could help out with this issue :)

**Comment by dthyresson** [comment]
> @aggmoulik we have yet to release our JWT based auth. Once that is done, you could help out with this issue :)

Thanks @rishabhpoddar I was just about to reply to @aggmoulik with the same comment. 

But, yes, @aggmoulik happy to have you take on this feature once ready. I'll assign it to you now for the future. Thanks!

**Comment by aggmoulik** [comment]
Thanx @dthyresson, I will coordinate with @rishabhpoddar for the same.

**Comment by aggmoulik** [comment]
Hey @rishabhpoddar, Just want to know the update on JWT Authentication.

**Comment by rishabhpoddar** [comment]
@aggmoulik we have released the feature now and are almost done with the redwoodjs integration as well. We still have documentation remaining though - so you can help with that:
- docs in redwoodjs (https://redwoodjs.com/docs/authentication)
- docs on supertokens about integrating with redwoodjs

If you want to help, we can chat about this on our discord server (https://supertokens.io/discord)

**Comment by dthyresson** [comment]
Current SuperTokens implementation is now JWT-based.
