### ISSUE TITLE
Add dependbot integration 

### ISSUE THREAD

**Issue by mohsen1** [redwoodjs/redwood#368]
https://dependabot.com/

If you enable it, I can help with configuring it. Example config I've done before:

https://github.com/mohsen1/nice-commander/blob/master/.dependabot/config.yml

**Comment by thedavidprice** [comment]
Ohhh, I do like dependabot. Apparently I wrongfully assumed it was the automation behind the current automated Security PRs. 

My only concern is the sheer volume and how it handles minor and major releases. I did this manually last week and spent several hours testing breaking changes and applying fixes. But was helpful to do from a single working branch that I originated. So what's the frequency? And does it ever consolidate multiple updates into one PR?

What's your experience been so far? And any frustration related to what I mentioned about?

**Comment by mohsen1** [comment]
You can configure the frequency. I personally let patch and minor updates of dev dependencies merge automatically. Breaking changes and non-dev changes should be reviewed. Nice thing about it is that the changelog that is usually embedded in the PR.

**Comment by thedavidprice** [comment]
Picking up the thread here -- wow, has it really been 28 days?

I'm game to give this a go if you're still up for it. One question re:
> let patch and minor updates of dev dependencies merge automatically

Do you know if this can be configured to _only_ merge if CI passes? With a few of the type + lint plugins, more than once I've run into errors even with patch updates. So much config. Just grrr...

But that's why this could be a huge help. Completely agreed.

**Comment by thedavidprice** [comment]
Oh yeah... and Lerna. Does it play well with monorepos? Assuming yes but wanted to confirm if you have previous experience.

**Comment by mohsen1** [comment]
yes Dependbot merges only if all CI checks are ok. If you enable the app for this repo I can make a PR for configuration.

**Comment by thedavidprice** [comment]
Dependabot enabled! Only for this repo as of now. If this works well, as a next step we'll look at enabling fro create-redwood-app.

Looping in @peterp and @cannikin since this will involve automation. Any concerns at this point before @mohsen1 suggests config via a PR?

**Comment by thedavidprice** [comment]
Hi @mohsen1 Might you still be available to help me work on this? It's moving up my priority list with increasing velocity (aka _acceleration_ ⚡️)!

**Comment by mohsen1** [comment]
Hi sorry I've been busy with other projects. Yes I can take a look at configuration
