### ISSUE TITLE
Generate scaffolding should not include field using prisma's  @updatedAt flag

### ISSUE THREAD

**Issue by orta** [redwoodjs/redwood#3682]
```
model User {
  name String 
  createdAt  DateTime @default(now())
  modifiedAt DateTime @updatedAt
}
```

`yarn rw g scaffold User` would _ideally_ not include form elements and query SDL for `modifiedAt`.

**Comment by aggmoulik** [comment]
Hey @jtoar What are we looking at? Can you please give me a brief summary of this? Should we exclude `modifiedAt` and `createdAt` from forms?

**Comment by thedavidprice** [comment]
Looping in @cannikin about @aggmoulik's question

**Comment by cannikin** [comment]
I think right now we have a hard-coded list of field names not to include in the scaffolds (`id`, `createdAt`, `updatedAt`) but should probably be smarter about it and instead exclude fields that use Prisma's  keywords like `@id`, `@updatedAt` as @orta is suggesting. 

There's no keyword for a `createdAt` field though, right now we usually set that with `@default(now())` but you could have other fields that you *would* want to edit, that just happen to *default* to a timestamp of "now." Maybe we have both: a named exclusion list (that for now is just `createdAt`) and also a "smart" exclusion list that looks for these Prisma keywords. 

Looks like the object we get from `getDMMF()` includes indicators `isId` for `@id` and `isUpdatedAt` for `@updatedAt`:

```js
  "models": [
    {
      "name": "User",
      "isEmbedded": false,
      "dbName": null,
      "fields": [
        {
          "name": "id",
          "kind": "scalar",
          "isList": false,
          "isRequired": true,
          "isUnique": false,
          "isId": true,        // <----
          "isReadOnly": false,
          "type": "Int",
          "hasDefaultValue": true,
          "default": {
            "name": "autoincrement",
            "args": []
          },
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "updatedAt",
          "kind": "scalar",
          "isList": false,
          "isRequired": true,
          "isUnique": false,
          "isId": false,
          "isReadOnly": false,
          "type": "DateTime",
          "hasDefaultValue": false,
          "isGenerated": false,
          "isUpdatedAt": true    // <----
        }
      ],
      "isGenerated": false,
      "primaryKey": null,
      "uniqueFields": [],
      "uniqueIndexes": []
    },
  ]
```

**Comment by aggmoulik** [comment]
@cannikin @thedavidprice I think #766 is the duplicate here. If not, just let me know. I will include that in existing PR.

**Comment by thedavidprice** [comment]
@aggmoulik It seems to me they are related but not exact duplicates. If you can resolve both in one PR, that would be great! But doesn't have to be done that way.

**Comment by cannikin** [comment]
@aggmoulik Any updates on this? Or maybe I should be tracking it in the PR?
