### ISSUE TITLE
`@types/aws-lambda` should be a `devDependency` of Redwood apps

### ISSUE THREAD

**Issue by callingmedic911** [redwoodjs/redwood#3693]
In webhooks/functions, to get the type hints specifically from line
```typescript
import type { APIGatewayEvent, Context } from 'aws-lambda'
```
we need have package `@types/aws-lambda`. @dac09 like you said, it used be there earlier? Let me know if you have something in mind to address this.

Possible way to fix:
- Include as `dependency` (not as `devDependency`) in `@redwoodjs/api`.
- Include as `devDependency` in the `create-react-app` template directly. It would require codemod for existing projects. (I don't think this would a decent fix)
- Something else?

**Comment by orta** [comment]
It might be better to copy over the useful types into redwood itself as `@types/aws-lamba` has about 50 dts files and you probably only need one of those

**Comment by callingmedic911** [comment]
@orta You're right, we probably don't need all those types. We would need to maintain from upstream changes though, right? Updated types/newer fields perhaps. To be honest I'm really not sure how frequent this happens and if it's even maintenance overhead at all. What do you think?

**Comment by realStandal** [comment]
Fwiw and just to add to @orta's comment, I'm the one who originally used types from `aws-lambda` in the generated functions/webhooks; that was when AWS was a big part of Redwood's story. At this point, and with the future in mind, it seems Redwood is going to try to be more deployment agnostic.  I'd try to make them part of the framework, and not depend on `aws-lambda` (from an app), if I did it again :)

**Comment by dthyresson** [comment]
> At this point, and with the future in mind, it seems Redwood is going to try to be more deployment agnostic. I'd try to make them part of the framework, and not depend on `aws-lambda`

This is definitely a 2.0 roadmap item -- and one of the reasons to move the api-server Fastify was to make this easier. And perhaps [GraphQL Yoga](https://github.com/dotansimha/graphql-yoga) may even make this easier. We'll see.

But, redwood does want to make functions (not just GraphQL) be more extensively and easily deployed elsewhere (Azure, Google, Cloudflare, etc).
