### ISSUE TITLE
Auth is causing unnecessary hard rerenders (supabase)

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#3706]
I have a login/signup page that uses `React.useState` to toggle between a log in form and a sign up form, where sign up is the default. When using the log in form and clicking the button to log in the page does two unnecessary hard rerenders. I'm using supabase auth, and I haven't tried the other providers, so I don't know if this is isolated to supabase or not.

Here's a video

https://user-images.githubusercontent.com/30793/140638469-92f91d8b-412a-4633-8e3f-e772c2d91741.mov

By doing `const { client } = useAuth()` to bypass RW and login directly using the supabase client I can get it to work like I want.

https://user-images.githubusercontent.com/30793/140638547-6c2e1c6d-01ee-4e02-aedf-07f45b682901.mov

But that causes the RW auth client and the SB auth client to come out of sync (RW's `isAuthenticated` is in the wrong state for example)

**Comment by Tobbe** [comment]
Additional context: This is a Cell, and when (failing to) login the cycles through `<Loading />` twice

**Comment by Tobbe** [comment]
I tried to get it to work by manually logging in using SB's client, but as I said in the original post that causes RW and SB to get out of sync, and I never could get around that without at the same time triggering all the extra mounts/unmounts of `<Success>`. 

The workaround I'm using now, that actually seems to work all the way, is to *not* use a Cell, but rather implement all the Cell logic myself to get greater control over when the gql calls are made. I renamed my cell from `JoinTeamCell` to `JoinTeamCellish` 😁

**Comment by jtoar** [comment]
Sounds similar to this one over here but I'd have to dig in to be sure: https://github.com/redwoodjs/redwood/issues/3402. The `login` function does call `reauthenticate` which triggers a change in state, which definitely causes a rerender. But I'm not sure why it's recommitting the whole page like that. 

One thing that would be super helpful is a react profile; that way I could look at all the components and see why they're rerendering:

https://user-images.githubusercontent.com/32992335/140653955-37bb69f8-271e-47ee-9ca0-16956d1d6e3d.mp4

**Comment by Tobbe** [comment]
> The `login` function does call `reauthenticate` which triggers a change in state, which definitely causes a rerender. But I'm not sure why it's recommitting the whole page like that.

But the state update should only cause the Success component to rerender, right? Now I'm getting the whole gql dance. I'm not sure exactly how it works, but could it be that apollo wants to run the query again because we're now authenticated? And it's not just updating the query results either, it's running everything from fresh. I tried different caching strategies, but couldn't make it work the way I wanted. It runs the query again, and `data` is null, so the cell first renders `<Loading>` and then `<Success>` every time.

**Comment by jtoar** [comment]
> But the state update should only cause the Success component to rerender, right?

Maybe I'm confused about how much of that page is actually the Cell—in the first video, is everything on the screen the Cell?

**Comment by jtoar** [comment]
@Tobbe Something that recently worked for @KrisCoulson was getting rid of the `notifyOnNetworkStatusChange ` in beforeQuery; could you try that as well? https://github.com/redwoodjs/redwood/blob/52f728a1e13c79c06a4eebd222596b679c355c01/packages/web/src/components/createCell.tsx#L118

**Comment by Tobbe** [comment]
> is everything on the screen part of the Cell?

Yes

**Comment by Tobbe** [comment]
From what I can tell I get the same behavior even with `notifyOnNetworkStatusChange: false`. Also tried with `cache-first`, without any noticeable change.

```
export const beforeQuery = (props) => {
  return {
    variables: props,
    fetchPolicy: 'cache-first',
    notifyOnNetworkStatusChange: false,
  }
}
```

**Comment by Tobbe** [comment]
I ran the profiler. I've never used it before, so not entirely sure what to look for. But I though I'd see both the Success and Loading components in there, but I don't. They're definitely rendering though. `<Loading>` more than once. 

https://s.tape.sh/9X69gakn

[profiling-data.11-09-2021.08-59-19.json.txt](https://github.com/redwoodjs/redwood/files/7502981/profiling-data.11-09-2021.08-59-19.json.txt)

**Comment by jtoar** [comment]
@Tobbe Thanks for the tape and the profiler data! I'll have a look at those shortly.

I just saw that your redwood version is v0.37. @KrisCoulson was seeing the same thing on v0.37, but it went away after upgrading to v0.38. (We bumped the apollo version in v0.38.) Could you try doing that as well, and if there's anything that's blocking you from upgrading is there anything I can do to help you get around it?

**Comment by jtoar** [comment]
@Tobbe between #3753 (which is in progress) and https://github.com/redwoodjs/redwood/pull/3746, do you think that this one's covered?

**Comment by Tobbe** [comment]
I haven't been working on Strive for a while, so I haven't been able to revert my workaround and test with a newer version of RW. I'll close this for now. I can reopen if I run into the error again. Or if someone else finds this because of the same error they can reopen.
