### ISSUE TITLE
`yarn rw g dataMigration` always generates JS files

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3711]
## Expected behaviour
If the RW project is TypeScript - generating a new data migration should create a TS migration, and include types for db.

## What currently happens
a) Generates a JS file
b) TS files in the data migration folder are ignored, when `yarn rw dm up` is run

**Comment by jtoar** [comment]
@cannikin Danny asked me to assign this to you 👍

**Comment by cannikin** [comment]
Have you forgotten my stance on Typescript? ;)

Is there a way to tell inside of a generator if the project is typescript or not? I know you can set a flag with the CLI command, but I assume if the project is already in "typescript mode" that it should default to that instead of looking for the flag?

Also I don't know what this means: "include types for db"

**Comment by dac09** [comment]
Haha, I wanted to see your reaction to this. But I know you can do this @cannikin !

The `typescript` flag gets passed to the handler automatically. An example is this generate thing here: 
https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/script/script.js

And the type of db... here's your snippet for what the template should be like:
```
import type { PrismaClient } from '@prisma/client'

export default async ({ db }: {db: PrismaClient}) => {
  // Migration here...
}
```

**Comment by cannikin** [comment]
Ahhh okay, I thought that meant something like all the models that are defined in the database, include their types somehow. I was about to find a grassy hill, lay in it, and stare up and sky thinking about the meaningless of existence.

**Comment by dac09** [comment]
Hey @cannikin I"m assuming you're not gonna pick this up? Shall I assign back to me?

**Comment by cannikin** [comment]
HA I was going to, just been on other stuff! It is time sensitive, should I P1 it?

**Comment by dac09** [comment]
No worries :)
