### ISSUE TITLE
Confirm Compatibility with Tailwind v3

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#3712]
Tailwind v3 alphas have been released with stable version ETA later this month:
- https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.0.0-alpha.1
- https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.0.0-alpha.2

What's changed (per alpha.1 release notes):
- `purge` has changed to `content`
- Color name changes
- `overflow-clip` has changed to `text-clip`
- 🚨PostCSS 7 is no longer supported 

## To Do
- [ ] confirm v3 alpha is compatible with current Redwood settings/config (I.e. can I follow the instructions to install `tailwindss@next` and it JustWorks?)
- [ ] make a plan for tailwind v3 compatibility with `yarn rw setup tailwind` — include in v1-rc if possible

**Comment by thedavidprice** [comment]
@jtoar My current thoughts on this after a quick glance:
- it looks compatible with our internal config and setup (already using JIT but might need to update config); when v3 is released, the setup command will install v3
- but there are breaking changes coming that will affect specific implementations, so how to "include" those breaking changes along with v1-rc, especially if v3 tailwind isn't released before we release v1-rc?

**Comment by realStandal** [comment]
Just updated my app's Tailwind to v3 and it does, brilliantly, JustWork.

As far as `setup tailwind` goes, the API for the `tailwindcss init` command has changed. We may be better off providing the configuration using a template. Through `tailwindcss init`, the only option looks to be generating a configuration file, with all of Tailwind's defaults, located at the CWD. It's quite a large and verbose file.

**Comment by jtoar** [comment]
Hey @realStandal, thanks for checking this on a project already! I was getting up to speed on this and tried the `tailwindcss init` command; the result I got looked fairly similar to the v2 one:

```js
// v2

module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}

```

```js
// v3

module.exports = {
  content: [],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

Did you run init with the `--full` flag maybe?

**Comment by realStandal** [comment]
@jtoar I did use the `--full` option, thinking that was the *only* option - it also isn't documented in init's `--help` screen that a path can be set via argument, embarrassing 🤦 😆

**Comment by jtoar** [comment]
@realStandal Haha no worries all good!
