### ISSUE TITLE
Redwood not working with Node.js < v14.17

### ISSUE THREAD

**Issue by system32uwu** [redwoodjs/redwood#3728]
I've already installed like 5 node versions with nvm, I started with 14.0.0 which is the suggested version, then tried with 14.13.0, 15.0.0, 16.13.0, 17.0.0, but I always get a compatibility error with some of the libraries redwood uses, the last one I tried was 14.13.0 and get the following error with jest-watch-typeahead:

`'error jest-watch-typeahead@1.0.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "14.13.0"\n'`

So, which node version actually works?

**Comment by system32uwu** [comment]
Ok, I tried with 16.13.0 again and it worked, I'm making a PR for [prequisites](https://learn.redwoodjs.com/docs/tutorial/prerequisites#nodejs-and-yarn-versions)

**Comment by thedavidprice** [comment]
Thanks for reporting this @system32uwu You are correct that we expect Redwood to work with any version of Node 14.x — looks like a dependency is actually forcing this to be => 14.17. So we might need to bump our requirements.

I'll loop back after a bit of research.

**Comment by system32uwu** [comment]
No problem. But as I mentioned 15.0.0 is not working either. With said version I'm getting the following error:

error @typescript-eslint/eslint-plugin@5.1.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "15.0.0"

**Comment by thedavidprice** [comment]
We got bit by `jest-watch-typeahead` setting it's engine version to LTS, which changed at the end of October. At that time, there would have been a switch from 14.x to explicitly 14.17. OUCH

I will update the CRWA engine template and related docs.

Lastly, we will never support Odd numbered releases, as they are intentionally short-term and never enter a maintenance period. See:
https://nodejs.org/en/about/releases/

**Comment by system32uwu** [comment]
Nice! Thank you for tracking down this issue to its root, feel free to close once that gets sorted out
