### ISSUE TITLE
Support module aliases using tsconfig/jsconfig

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3729]
This is something we've been planning for a while, but never get round to. Currently its painful to declare import aliases in Redwood, and needs messing around with babel config. Since we are reducing the amount of babel things that can be configured, we should provide a way for users to add their own import aliases.

We can potentially extend packages/internal/src/build/babelPlugins/babel-plugin-redwood-src-alias.ts to support aliases such as:

```json
   "paths": {
      "@common/*": ["..common/*"],
      "@components/*": ["./src/components/*"],
      "@renderUtils/*": ["./src/utils/*"],
```

suppled in the jsconfig and tsconfig files. 

Things to do:
- [ ] check exec, data migrate and console are still working when we supply the aliases internally

**Comment by ChrisLFieldsII** [comment]
This would be an awesome nice-to-have feature!

The projects I work with alias `src` as `~` so I immediately tried this in `web/tsconfig.json` and was surprised to find out it just simply didn't work. TS and VSCode made it _seem_ like the path alias would work at first, but I experienced a runtime error from the babel side of things.

For others trying to get around this, do the following:
1. `yarn workspace web add --dev babel-plugin-module-resolver`
2. add `"~/*": ["./src/*"]` to `web/tsconfig.json` in `paths` (or desired alias)
3. create [babel config](https://redwoodjs.com/docs/project-configuration-dev-test-build#babel) file at `web/babel.config.js` with following contents
```javascript
module.exports = {
  plugins: [
    [
      'module-resolver',
      {
        alias: {
          '~': './src',
        },
      },
    ],
  ],
}
```

[This](https://haseebmajid.dev/blog/better-imports-with-babel-tspath) article helped guide me.

**Comment by esteban-url** [comment]
I'm able to configure almost* everything without too much of an issue. but the prerendering breaks.

I've describe it here https://github.com/redwoodjs/redwood/issues/7574

**Comment by raph90** [comment]
Hi @es

**Comment by raph90** [comment]
HI @esteban-url, did you manage to get aliases to default exports for Cells working? I'm able to get aliases working for everything for the src directory, but anything exported from the mirror types fails... it would be great to hear your input. Thanks!

**Comment by esteban-url** [comment]
hey @raph90 yes! but with some caveats, let me explain:
- there's a PR for this, so it's not out there yet
- that PR will allow you to do this:

```ts
"@ui/*":[
         "./src/components/*", // enables imports at run time
         "../.redwood/types/mirror/web/src/components/*", // stops vs code / ts from yelling with all those squiggly lines 
        ],
```

you can check out the pr here: https://github.com/redwoodjs/redwood/pull/7575

**Comment by esteban-url** [comment]
@raph90 It would be amazing if you can test it out and provide feedback! 😉

**Comment by raph90** [comment]
Thanks @esteban-url - the PR looks awesome. Looking forward to trying it once the changes go live. 👏

**Comment by esteban-url** [comment]
@ChrisLFieldsII  @raph90 FYI, there is a new RC that I think has a fix for this issue! https://github.com/redwoodjs/redwood/releases/tag/v5.4.0-rc.95

@dac09 @jtoar do you this this issue should be closed as well? I forgot to mention it in the PR

**Comment by jtoar** [comment]
@esteban-url ah yeah let's close this one now that we have support in main and an RC is out, thanks @esteban-url!
