### ISSUE TITLE
Context error message

### ISSUE THREAD

**Issue by paulmars** [redwoodjs/redwood#373]
`
yarn rw g scaffold post
`

causes

`
Cannot create property 'context' on string 'No schema definition found for `Post`'
`

unclear what a property context is on a string in this case. this happens if schema isn't set. just think the message could be more clear.

**Comment by thedavidprice** [comment]
🤔Good point... I have no idea what that means.

@cannikin Any suggestions here to improve error message?

**Comment by cannikin** [comment]
@thedavidprice As per our conversation, here's me throwing the "No schema definition" error: https://github.com/redwoodjs/redwood/blob/master/packages/cli/src/lib/index.js#L43

My guess is you need to do something special for Listr besides just throwing an error.

Maybe we can just:

    throw new Error(`No schema definition found for \`${name}\``)

**Comment by thedavidprice** [comment]
this was closed in #401
