### ISSUE TITLE
Endpoint for custom functions

### ISSUE THREAD

**Issue by pi0neerpat** [redwoodjs/redwood#3730]
On the FE we may want to call a custom function eg `api/src/functions/checkout`

For example, I used to be able to trigger my checkout function on the FE like 

```js
const response = await fetch(`${global.__REDWOOD__API_URL}/checkout`
```

A change was made in #2822 to no longer set `__REDWOOD__API_URL`. Now only `apiGraphQLUrl` and `apiDbAuthUrl` are available, so there is no easy way to target custom functions

### Workaround

If you have something like `apiUrl = "/api"`, then this may work in the meantime

```js
import { getConfig } from '@redwoodjs/internal'
const rwjsConfig = getConfig()
const response = await fetch(`${rwjsConfig.web.apiUrl}/checkout`
```
cc @thedavidprice @dac09 @dthyresson

**Comment by dac09** [comment]
> If you have something like apiUrl = "/api", then this may work in the meantime

Its best not to use rwjs/internal at runtime, you definitely don't want that bundled (either on FE or BE, tbh)

But perhaps we should expose a helper within rwjs/web that gives you access to these values.

**Comment by thedavidprice** [comment]
@pi0neerpat In your example above, `${rwjsConfig.web.apiUrl}/checkout` is going to have the value `/api/checkout`. Is that what you want (ideally)?

@dac09 I like the idea of a helper. But what about (re)adding global?

**Comment by jtoar** [comment]
@chrisvdm and I ran across this in the example store as well. A global seems the most natural to me; just another one of these:

https://github.com/redwoodjs/redwood/blob/8874cf7a27a916c10e88b337b4a74536a12ecca1/packages/core/config/webpack.common.js#L150-L155

**Comment by pi0neerpat** [comment]
> @pi0neerpat In your example above, `${rwjsConfig.web.apiUrl}/checkout` is going to have the value `/api/checkout`. Is that what you want (ideally)?
> 
> @dac09 I like the idea of a helper. But what about (re)adding global?

Correct!
