### ISSUE TITLE
Baseline Vercel deployment of `redwood-app` produces broken front-end

### ISSUE THREAD

**Issue by bosconian-dynamics** [redwoodjs/redwood#3737]
Unless you create a `/` route beforehand, setting up the out-of-the-box `yarn create redwood-app` project to deploy to Vercel (and likely other hosts) results in the deployed front-end consisting solely of the "Something went wrong" React message and the following console error:
> react-dom.production.min.js:216 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Meanwhile, in local development the project renders the placeholder Redwood landing page.

It makes sense to me that the production deployment does not render the placeholder (though it is nonetheless what I was expecting to see in the deployment), but it seems fairly strange and confusing that the production deployment does not even render the sole default `NotFoundPage` route. In my case at least, I went on a wild goose chase trying to sort out Vercel engine versions and spinning up additional test projects to ensure I hadn't missed some step in the documentation.

It would be nice to include a note in the tutorial/deployment documentation and/or render the default `NotFoundPage` or even placeholder landing page to alleviate this confusion :)

**Comment by thedavidprice** [comment]
Ah, deploying a project without a home page route is definitely not an edge-case we considered. 😂

But agreed the NotFoundPage should load and "Something went wrong" is misleading. To fix this, we'll need to improve the logic for loading the SplashPage in the router:
- https://github.com/redwoodjs/redwood/blob/main/packages/router/src/router.tsx

**Comment by DukeManh** [comment]
@thedavidprice, I'm interested, can I work on this issue?

**Comment by thedavidprice** [comment]
@DukeManh yes, please! @jtoar and I took a brief look and felt like the router.tsx just needed to handle this case. It's possible to add the condition to webpack config, but at first glance that doesn't seem preferred.

**Comment by thedavidprice** [comment]
@bosconian-dynamics 

PS I ❤️Glenwood Springs
