### ISSUE TITLE
Fix babel-plugin graphql-tag on api side 

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3764]
We include the babel-plugin graphql tag module in our list of pretranspile plugins. This plugin is advertised as doing the following:

    Compiling GraphQL queries at the build time:

    reduces the script initialization time; and
    removes the graphql-tag dependency
    Removing the graphql-tag dependency from the bundle saves approx. 50 KB.

At the moment it's not working, see the failing test case here: https://github.com/redwoodjs/redwood/blob/main/packages/internal/src/__tests__/build_api.test.ts#L137

**Comment by callingmedic911** [comment]
@jtoar Ref: https://github.com/PavelDymkov/babel-plugin-auto-import/issues/11 (from https://github.com/redwoodjs/redwood/pull/3193#issuecomment-895939673)

**Comment by jtoar** [comment]
I've queued this up for discussion.
