### ISSUE TITLE
Typechecking on web fails if src/lib/auth imports other functions

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3777]
### Whats the issue?
If I have any imports from `src/lib` in `src/lib/auth.ts` (e.g. `import { db } from 'src/lib/db'`), when running `yarn rw tsc web`, typechecking always fails with module resolution errors. For example:

![errors](https://user-images.githubusercontent.com/1521877/143246376-7e0b0311-b16c-4cb4-b4af-191111a7cb7b.png)

### Diagnosis
This happens because, we try to infer the currentUser on the web side, based on the `getCurrentUser` function in `src/lib/auth`. (See https://github.com/redwoodjs/redwood/blob/main/packages/internal/src/generate/templates/all-currentUser.d.ts.template)

However, when there are imports in this auth file, typescript cannot resolve them on the web side, resulting in the errors

**Comment by aggmoulik** [comment]
Hey @dac09 I am picking it up, if you are not working on it.

**Comment by dac09** [comment]
Hey @aggmoulik - this isn't a very straight forward one, but happy for you take a stab at it! 

I have half a solution so far, haven't figured out fully. Go ahead and give it a try though, maybe you can come up with a better solution than what I'm thinking!
