### ISSUE TITLE
Add messaging when `yarn rw open` is run while dev server is not running

### ISSUE THREAD

**Issue by clairefro** [redwoodjs/redwood#3781]
Running `yarn rw open` when the dev server is not running simply ends silently 

![image](https://user-images.githubusercontent.com/9841162/143626866-6ece4e67-7b93-4f12-8ab6-8daf9977e45c.png)

Adding a message print like `"Start your dev sever first!"` would be helpful for the tired dev that forgot to start their server :)

**Comment by clairefro** [comment]
actually, `yarn rw open` is doing nothing with my dev server on either. It **does** open browser on `yarn rw dev` 

investigating 

```
OS
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

Browser
Version 95.0.4638.54

yarn version 1.22.5
node version 16.13.0

```

**Comment by dthyresson** [comment]
I wonder if you could ping the GraphQL health check https://redwoodjs.com/docs/graphql#health-checks and if doesn't respond or responds with a file, prompt with a warning.

**Comment by thedavidprice** [comment]
I recommend we deprecate this command

**Comment by jtoar** [comment]
@thedavidprice I've queued this one up for discussion. I also tried this again and `yarn rw open` seemed to open the browser regardless of whether the dev server was running or not: https://s.tape.sh/BzCVHubQ. (Vim didn't start so ignore my typos.)

**Comment by thedavidprice** [comment]
Scheduling to be deprecated with v1
