### ISSUE TITLE
Logging in api-server with Fastify is overly chatty for each request/response

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#3784]
From @orta - Can we reduce the chattiness of the logging in api-server for each request and response?

See: https://community.redwoodjs.com/t/v0-39-release-candidate-is-available-feedback-wanted/2552/3

![image](https://user-images.githubusercontent.com/1051633/143914009-72a4daf3-9777-4f01-a477-deb1d23ad668.png)

Note: This logging is controlled by Fastify's logger and is separate for the api logger (used by GraphQL and services), but also uses Pino.

See: https://github.com/redwoodjs/redwood/blob/5280736241dd0e29107ecf8f88767aa0aab0dd95/packages/api-server/src/app.ts#L5

And how might Redwood expose a config to set the log level (and other options) for the api-server logging.

**Comment by dthyresson** [comment]
Idea: 💡 https://github.com/fastify/fastify/blob/main/docs/Logging.md

We can set better defaults to `ignore` unhelpful logging attributes like hostname, remoteAddress, remotePort etc and aim to resemble the one line GET log from prior api-server.

**Comment by dthyresson** [comment]
@orta I've made the api-server Fastify logging a little less chatty, but wanted to share to see if this is better for you:


```bash
api | INFO [2021-12-08 17:58:29.029 +0000]: fd34652b-9cadcaba-f8fe8b8b incoming request  POST 
api | DEBUG [2021-12-08 17:58:29.032 +0000] (graphql-server): GraphQL execution started: PollCurrentVersionQuery
api | DEBUG [2021-12-08 17:58:29.033 +0000] (graphql-server): GraphQL execution completed: PollCurrentVersionQuery
api | INFO [2021-12-08 17:58:29.033 +0000]: fd34652b-9cadcaba-f8fe8b8b request completed 200  3.8922499418258667
api | INFO [2021-12-08 17:58:49.060 +0000]: 14916b2a-6457c315-5c0aeabd incoming request  POST 
api | DEBUG [2021-12-08 17:58:49.063 +0000] (graphql-server): GraphQL execution started: PollCurrentVersionQuery
api | DEBUG [2021-12-08 17:58:49.064 +0000] (graphql-server): GraphQL execution completed: PollCurrentVersionQuery
api | INFO [2021-12-08 17:58:49.065 +0000]: 14916b2a-6457c315-5c0aeabd request completed 200  4.189792037010193
api | INFO [2021-12-08 17:59:09.086 +0000]: dda87a27-5bb92007-643caf26 incoming request  POST 
api | DEBUG [2021-12-08 17:59:09.092 +0000] (graphql-server): GraphQL execution started: PollCurrentVersionQuery
api | DEBUG [2021-12-08 17:59:09.093 +0000] (graphql-server): GraphQL execution completed: PollCurrentVersionQuery
api | INFO [2021-12-08 17:59:09.094 +0000]: dda87a27-5bb92007-643caf26 request completed 200  6.331083059310913
```

Debugs here are api Graphql logs.

I have redacted the `req` and `res` metadata that was included as seen in the above description.

The Info here is the Fastify request or response.

Since there is a log per request and response, not all info is available. Duration and status is available on the response and method is available on there request.

The old logger combined into a single statement (still looking of can do that or not).

The format is:

`'{reqId} {msg} {res.statusCode} {req.method} {responseTime}',`

Where `reqId` is a random request id used to tie the request and response together. This can be a function to return any string, so many more readable is better?

There isn't a way to truncate the time or optionally include some tokens.

But, wondered if this is better?

**Comment by orta** [comment]
I wonder if it's worth splitting dev logs vs prod logs? In prod this makes sense:

```
api | DEBUG [2021-12-08 17:58:49.063 +0000] (graphql-server): GraphQL execution started: PollCurrentVersionQuery
api | DEBUG [2021-12-08 17:58:49.064 +0000] (graphql-server): GraphQL execution completed: PollCurrentVersionQuery
api | INFO [2021-12-08 17:58:49.065 +0000]: 14916b2a-6457c315-5c0aeabd request completed 200  4.189792037010193
```

But when I'm on a dev server, the full time and `uuid` are not _that_ useful:

```
api | INFO request routed to graphql-server at 17:58:49
api | DEBUG (graphql-server): GraphQL execution started: PollCurrentVersionQuery
api | DEBUG (graphql-server): GraphQL execution completed: PollCurrentVersionQuery
api | INFO request completed 200 4.18ms
```

As an example I booted up rails:

```
Started GET "/" for 127.0.0.1 at 2021-12-09 07:25:54 +0000
   (1.8ms)  SELECT sqlite_version(*)
Processing by Rails::WelcomeController#index as HTML
  Rendering /Users/ortatherox/.gem/gems/railties-6.1.4.1/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /Users/ortatherox/.gem/gems/railties-6.1.4.1/lib/rails/templates/rails/welcome/index.html.erb (Duration: 7.8ms | Allocations: 492)
Completed 200 OK in 30ms (Views: 12.8ms | ActiveRecord: 0.0ms | Allocations: 4138)
```

So perhaps a tighter dev version could look like:

```
api | INFO Received POST "/graphql" at 17:58:49, routed to graphql-server 
api | DEBUG graphql-server: Begin execution: PollCurrentVersionQuery 
api | DEBUG graphql-server: Ended execution: PollCurrentVersionQuery (3.23ms total, 2.1ms db, 4 roundtrips)
api | INFO request completed 200 in 4.18ms
```

- Begin and Ended have the same number of letters and thus a visual rhythm in monospace font
- The opener tells you the input URL, time and tells you the service handler name which will be in the next logs
- Completions uses human readable numbers

Personally I'd love to see the number of _unique_ queries to the db which an graphql operation makes, e.g. how many round-trips did prisma and the server take to grab my data) in Artsy I expanded [the JSON response](https://metaphysics-staging.artsy.net/v2?query=%7B%0AartworksConnection(first%3A5%2C%20after%3A%20%22YXJyYXljb25uZWN0aW9uOjE0%22)%20%7B%0A%20%20pageInfo%20%7B%0A%20%20%20%20hasNextPage%0A%20%20%20%20endCursor%0A%20%20%7D%0A%20%20pageCursors%7B%0A%20%20%20%20first%20%7B%0A%20%20%20%20%20%20cursor%0A%20%20%20%20%20%20page%0A%20%20%20%20%20%20isCurrent%0A%20%20%20%20%7D%0A%20%20%20%20last%20%7B%0A%20%20%20%20%20%20cursor%0A%20%20%20%20%20%20page%0A%20%20%20%20%20%20isCurrent%0A%20%20%20%20%7D%0A%20%20%20%20around%20%7B%0A%20%20%20%20%20%20cursor%0A%20%20%20%20%20%20page%0A%20%20%20%20%20%20isCurrent%0A%20%20%20%20%7D%0A%20%20%20%20previous%20%7B%0A%20%20%20%20%20%20page%0A%20%20%20%20%20%20cursor%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%7D) on staging/dev builds to give you an idea of how many requests to microservices you were making ) but that can be a separate issue

**Comment by dthyresson** [comment]
Moving back to draft. I want to remove the requestId and rethink the `rw dev` output vs `serve api` and `serve web` since those output non-prettified NDJSON then could be piped into something that formats instead.

Then there is no need for Pino Pretty and that dependency is removed completely.
