### ISSUE TITLE
Add Redwood equivalent of `prisma introspect`

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#379]
For those that have an existing database and want to generate their `schema.prisma` file based on that, we should make a Redwood version of `yarn prisma introspect`. `yarn rw db introspect` perhaps?

https://www.prisma.io/docs/reference/tools-and-interfaces/introspection

**Comment by Jaikant** [comment]
@cannikin submitted a PR for this.

**Comment by cannikin** [comment]
Awesome, thanks! I'll open a review over there...

**Comment by peterp** [comment]
This is now done, thanks @Jaikant
