### ISSUE TITLE
[workaround] Updates to Tailwind css don't refresh when running dev server

### ISSUE THREAD

**Issue by edapm** [redwoodjs/redwood#3792]
I have just started a new Redwood project and have added Tailwind. When writing pages, the updates to Tailwind classes do not show when running the dev server. I have to restart the dev server every time I make a change. Not sure if this is a Tailwind problem or a Redwood one.

I am running the project in Gitpod; I experienced the problem in v0.38 and after I upgraded to v0.39.

**Comment by jtoar** [comment]
Hey @edapm thanks for reporting this! @clairefro and I have confirmed this. It's a huge blow to DX. 

Do you happen to know if it was working ok in v0.37 and that it broke when you upgraded to v0.38?

**Comment by edapm** [comment]
I created the project with v0.38 so not sure.

**Comment by mojombo** [comment]
I know that @Burnsy has this working with GitPod, perhaps he can share his insights.

**Comment by jtoar** [comment]
@edapm I believe I've found a temporary workaround for this. I've confirmed it locally but if you could confirm it as well that'd be great / give me more confidence.

In your `.env` file can you put:
```
TAILWIND_MODE=watch
```

**Comment by edapm** [comment]
@jtoar That works for me!

**Comment by aggmoulik** [comment]
> Hey @edapm thanks for reporting this! @clairefro and I have confirmed this. It's a huge blow to DX.
> 
> Do you happen to know if it was working ok in v0.37 and that it broke when you upgraded to v0.38?

@jtoar I have set up my project on `v0.37` and it was working very well for me. So, I suppose it must be a change in `v0.38`

**Comment by zackdotcomputer** [comment]
Just ran into this as well and also fixed it with `TAILWIND_MODE=watch`.

Worth noting as an avenue for debugging that the [TW docs on that env flag](https://v2.tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files) say that it is a workaround for a failure in the usual flow. Usually the rebuild should be triggered by:

> As of Tailwind CSS v2.2+, the JIT engine depends on PostCSS’s directory dependency messages to register your content files as CSS build dependencies with your build tool.

I confirmed that if I downgrade to Tailwind 2.2 and disable JIT, then the correct refresh behavior returns. So it does appear to be an issue with the pipeline from JIT to the build tool via the directory dependency system.

**Comment by jtoar** [comment]
Based on some of the recent comments in [this thread](https://github.com/tailwindlabs/tailwindcss/issues/6340), I've tested hot reloading again and it seems to work like before, without the need for the workaround. If someone who was using the workaround before could confirm that would give me more confidence!

**Comment by zackdotcomputer** [comment]
@jtoar Just tested locally on the latest rw (0.41.0) and tailwind (3.0.9) and can confirm that autorefresh appears to be functioning normally once again when using `yarn rw dev`
