### ISSUE TITLE
CurrentUser query fails CORS

### ISSUE THREAD

**Issue by Irev-Dev** [redwoodjs/redwood#3812]
When deploying an app that has authentication with serverless (the api is on a different domain with this setup) there seems to be a CORS issue that only effects the currentUser query.

Where as other queries using the same graphQL endpoint don't have the same problem. I had [posted this](https://community.redwoodjs.com/t/cors-issue-specific-to-auth-request/2575) on the forum, after which I strongly suspected this was a bug and not a config problem so thought making a minimum replicating project was the best way to proceed. See that project here.

https://github.com/Irev-Dev/redwood-serverless-cors-demo

It covers steps to replicate with the website I've deployed as will as what steps I took to make the project.

----

Other than the project I have tried to dig into this myself adding some extra logging to a deployed api to see if something strange was happening when deployed, so I logged out `lambdaResponse` in `packages/graphql-server/src/functions/graphql.ts` and checking in Cloudwatch showed the following:

```
    {
      body: '{"data":{"redwood":{"currentUser":null}}}',
      statusCode: 200,
      headers: {
        'access-control-allow-credentials': 'true',
        'access-control-allow-origin': '*'
      }
    }
```
 
So it seems the headers are been added but are lost somewhere along the way?
To be clear I'm happy to keep digging into this, but I'm not sure where to look other than `packages/graphql-server/src/functions/graphql.ts` now, so need some help.

**Comment by Irev-Dev** [comment]
Closing this issue because it's not a bug, extra steps in the serverless.yml are needed when using the graphql endpoint for auth/credentials.

'*' is not good enough for CORS for requests with credentials. this was the diff that fixed it for me in my test project.

![image](https://user-images.githubusercontent.com/29681384/144500738-58225b43-6810-4aae-b657-e31ce80faeb1.png)

Though @thedavidprice @virtuoushub does this have implications for the serverless setup commend? if we detect they have an auth provider we add this to the serverless config?

**Comment by thedavidprice** [comment]
> Though @thedavidprice @virtuoushub does this have implications for the serverless setup commend? if we detect they have an auth provider we add this to the serverless config?

💯

We should assume projects have Auth as the default.

@Irev-Dev could you add this topic as something to address/discuss on #3755?

Thanks!

**Comment by Irev-Dev** [comment]
@thedavidprice Done!

https://github.com/redwoodjs/redwood/pull/3755#discussion_r763526904
