### ISSUE TITLE
[Router] Routes allow spaces but fail on them

### ISSUE THREAD

**Issue by olance** [redwoodjs/redwood#382]
The `/\{([^}]+)\}/g` regexp that's widely used in the router's implementation allows spaces in param names and types, as well as before or after the colon.

However, the rest of the code is not prepared for spaces within the type names: trying to match the route `/posts/{id: Int}` will fail trying to look for a `" Int"` type within the known types...

Happy to open a PR to change that, however I'm wondering how you'd treat the issue:
- Disallow spaces in route params
- or be space-proof in route processing?

Personally, I'd vote for the former, as that'd make it easier to have a single way of doing things, and who wants a `/route/{my param: Int}` anyway?

**Comment by peterp** [comment]
> Personally, I'd vote for the former

100% agree with you.

**Comment by jrhorn424** [comment]
As a new learner, I'd say my vote is for the former, as well. Spaces don't seem natural in a URL, so disallowing them seems natural, too.

**Comment by mojombo** [comment]
Agreed. No spaces!

**Comment by olance** [comment]
Perfect then, I’ll start a PR ASAP!

**Comment by thedavidprice** [comment]
@olance no pressure or rush here, but checking in to see if the PR did get started. Just didn’t want this one to get lost or remain open if fix is already complete.

**Comment by olance** [comment]
@thedavidprice yeah sorry work as been crazier recently so didn't have time for Redwood 😕 
But I'm still planning on pushing a PR! Hopefully this week-end 🤞
