### ISSUE TITLE
Setup commands should respect the current redwood version

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3876]
### Whats the issue?
Setup commands e.g. `rw setup auth dbAuth` currently install the latest version of the `@redwoodjs/*` packages. This can lead to all sorts of havoc, especially in the case of auth.

### Scenario
I'm on Redwood v1.0.0-rc1, and run `yarn rw setup dbAuth`

It will install the latest `@redwoodjs/auth` package e.g. `0.40.0`, while all the other packages are at `1.0.0-rc1`.

### Expected result
The setup command should install `@redwoodjs/auth` at `1.0.0-rc1`

**Comment by Tobbe** [comment]
https://github.com/redwoodjs/redwood/issues/2696
