### ISSUE TITLE
License in new RW projects should not be licensed to redwood

### ISSUE THREAD

**Issue by orta** [redwoodjs/redwood#3889]
![Screen Shot 2021-12-10 at 10 16 53 PM](https://user-images.githubusercontent.com/49038/145648386-fefb9925-e0ec-4cce-8cf0-fed0a4479b02.png)

It could instead be `git config user.name` which most folks are forced to put in for github:

```
❯ git config user.name
Orta
```

Or something more generic like "Repo Contributors" if that's not set/

**Comment by jtoar** [comment]
@thedavidprice @mojombo want to get this one on your radar.
