### ISSUE TITLE
Scaffold Typing Errors for Model

### ISSUE THREAD

**Issue by aggmoulik** [redwoodjs/redwood#3893]
I am working on a basic test example, I found something that it should not happen:

I have the below model: 
```js
model URL {
  id        Int      @id @default(autoincrement())
  fullURL   String
  slug      String   @unique
  views     Int      @default(0)
  createdAt DateTime @default(now())
}
```
I have created a scaffold just like always but it created very different things which are automatically generated.
Now, the Prisma client types were created with unconventional naming  i.e.,

// DB Model In services

It generated the below pattern in services: 
```ts
db.url.findMany() // Expected and Generated in scaffold
```
But I have to correct to this one:
```ts
db.uRL.findMany() // Generated Types  ( which fixed the errors )
```

// Prisma Types for the CRUD Resolvers
generated interface in services:
```ts
interface UpdateUrlArgs extends Prisma.UrlWhereUniqueInput {
  input: Prisma.UrlUpdateInput // Generated
}
```
But, I have to recorrect to this:
```ts
interface UpdateUrlArgs extends Prisma.URLWhereUniqueInput {
  input: Prisma.URLUpdateInput // Expected ( I think )
}
```

 @jtoar @cannikin Can you confirm what is the expected behaviour? I think the types were messed up. I will work on it after the confirmation on generated services file.

**Comment by orta** [comment]
There's probably some sort of 'name canonicalization' function in Redwood which should have `URL` allowed listed so that it doesn't get changed to `Url`

**Comment by cannikin** [comment]
We had another issue like this where some capitalization wasn't consistent and we included a bunch of updates to for PascalCase or camelCase in all cases, even if it's something that would usually be all capitals, like `APIPage`. It should generate `ApiPage` (for components) and `apiPage` for route naming. 

But in your first case it looks like *Prisma* is the one with the weird casing...you need to call `db.uRL.findMany()`? That prop `uRL` is from Prisma, they must be converting your model name using some weird custom casing logic...if they used a standard camelCase library it should just become `url`. You should probably [open an issue](https://github.com/prisma/prisma/issues) with them (or see if one is already open) and see what they say. As far as the types I don't know, maybe @dac09 has an idea?

I think in general you probably don't want all-caps for model names as weird issues like this are bound to come up. Prisma has a [doc](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/use-custom-model-and-field-names) on naming conventions, and they say:

> Prisma has a naming convention of camelCasing and using the singular form for Prisma models. If these naming conventions are not met, the Prisma schema can become harder to interpret and the generated Prisma Client API will feel less natural.

**Comment by thedavidprice** [comment]
@aggmoulik checking in here -- any thoughts or updates on this one?

**Comment by thedavidprice** [comment]
Sounds good and 100% understood @aggmoulik Appreciate all your continued contributions. And that sounds like a great plan!

**Comment by jtoar** [comment]
Closing for now, let us know if you'd like to pick this back up!
