### ISSUE TITLE
Remove unnecessary package.jsons in tasks

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#3900]
While I'm a bit fuzzy on the details, the `tasks` directory isn't a workspace so most of the scripts in `tasks` (such as `release-notes.js`) can list their dependencies in the root-workspace package.json's `devDependencies`.
- [x] https://github.com/redwoodjs/redwood/pull/3898
- [x] https://github.com/redwoodjs/redwood/pull/3899
- [x] https://github.com/redwoodjs/redwood/pull/3901
- [x] https://github.com/redwoodjs/redwood/pull/3907
- [x] https://github.com/redwoodjs/redwood/pull/3908

**Comment by thedavidprice** [comment]
@jtoar you crushed this one! Leaving the final steps to close for your own satisfaction 😄
