### ISSUE TITLE
Expose a way to customize fastify in `@redwoodjs/api-server`

### ISSUE THREAD

**Issue by jmackie** [redwoodjs/redwood#3909]
It would be really helpful if there was some way to hook into the fastify configuration that happens as part of:

```
$ yarn redwood serve api
```

Particularly, I'd like to be able to customize some of the logging options. 

Maybe `@redwoodjs/api-server` could check for a config file (e.g. `fastify.config.js`) and merge it into the default `Fastify` constructor arguments if it exists?

❤️

**Comment by jmackie** [comment]
To make this more concrete, my use case is that I'd like to be able to set:

- `genReqId` - the default `reqId` isn't useful for logging/tracing (I'd prefer a UUID or `nanoid` or anything other than an incrementing counter 😂 )
- `requestIdLogLabel` - I'd prefer to have something other than `reqId`
- `requestIdHeader` - we use `x-request-id`

Alternatively, if I could set `disableRequestLogging: true` I could handle logging entirely from my functions (as you say) _without_ the noise coming from fastify defaults. Maybe this specific option could be set via an environment variable [here](https://github.com/redwoodjs/redwood/blob/ae08fe06c825761c0d4e6e304dcf0fbb64d9b6cb/packages/api-server/src/app.ts#L5)?

**Comment by dac09** [comment]
Great detailed explanation @jmackie, thanks!

Let me discuss this over with @dthyresson and see if we can come up with something, there's probably other settings that someone might want to modify anyway.

`fastify.config.js` seems like a reasonable option, but let us explore a little more
