### ISSUE TITLE
Datamigrate failures do not exit properly in `rw deploy {provider}`

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3910]
### Whats the issue? 
When you have a datamigration fail, you expect the whole build to fail, whoever it continues to a "successful" state. This is misleading:
e.g. 
```
1 data migration(s) exited with errors.
7 data migration(s) skipped due to previous error.
--
Done in 18.39s.
```

### What should happen?
If any of the data migrations fail, the whole deploy command should fail

**Comment by dac09** [comment]
@cannikin would you like to take a look at this please?

**Comment by cannikin** [comment]
So we `exit(1)` if there's an un-caught error, but in this case the error is caught and reported. But, there's no check that says to also `exit(1)` on *caught* errors. Want to try merging in or patching this PR and see if if does what you expect? #3911

**Comment by dac09** [comment]
@cannikin looks like this has solved the issue, but we don't get the nice logs we had before OH NO 😱

Example:
```
$ /Users/dac09/Projects/tape/tape-web/node_modules/.bin/rw deploy vercel --no-build --no-prisma

Running:
yarn rw data-migrate up

$ /Users/dac09/Projects/tape/tape-web/node_modules/.bin/rw data-migrate up
error Command failed with signal "SIGKILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
rw deploy vercel [...commands]

Build command for Vercel deploy
...
```

I wonder why it exits before it logs the errors?

**Comment by cannikin** [comment]
Hmm... `report()` is just `console.info/error/warn` statements...there shouldn't be any weird promises or anything, what the heck?

**Comment by dac09** [comment]
Btw... to reproduce, just create a datamigrate with a `new Error('boom')` in it, and also generate a couple of other datamigrations.

**Comment by dac09** [comment]
Hmmm... weird, its not doing it anymore :S. Closing back down. Thanks @cannikin !
