### ISSUE TITLE
`mockCurrentUser` returns null `currentUser` on web side

### ISSUE THREAD

**Issue by callingmedic911** [redwoodjs/redwood#3912]
**What is happening?**
My expectation was: immediately after the `mockCurrentUser` call, the given component should render the mocked user from the first render, but it first renders null, then sets mocked user after.

**Background on how currently auth works on the web side**
As soon as the page loads or the whole page refreshes, then Auth context provider (React context) triggers the GraphQL call for `currentUser` and update the context with the result. And since auth provider is at the root level, this process only happens when the app loads, not when sub-tree/components are swapped.

**Why is this happening?**
In web unit tests, we mock the auth context in each `render` call which means the initial value of `currentUser` is always `null` in the first render. Then, it triggers a GraphQL call which will return mocked user in the second render. So if test `expect` is immediately after `mockCurrentUser`, it’ll fail.

**Can I not just use `waitFor`?** 
The component may be behind some private route, so it is practical to think that component doesn’t need to handle the `null` case for `currentUser` because the router is checking that for us. And expect to force the mock from the first render.

**Possible next steps:**
Even though we can override the auth context for `mockCurentUser` but since these are unit tests, I am inclined towards keeping this behaviour as is - without caring about router behaviour. That means component should handle null `currentUser`. Also, we can update the documentation to explain this behaviour, and we clearly say that we must use `waitFor` (or anything that waits) expected user or derivative values with `mockCurrentUser`.

@dac09 What do you think?

**Comment by dac09** [comment]
>  Also, we can update the documentation to explain this behaviour, and we clearly say that we must use waitFor (or anything that waits) expected user or derivative values with mockCurrentUser.

I'm not sure what you mean here Aditya.

**Comment by dac09** [comment]
If I understand correctly... its just that the components don't typically wait for `useAuth.loading` to become true? 

I think maybe in that case we ought to update the documentation, yes. 

Because there maybe cases where you're using a component that uses `useAuth` in a public page (like we do on Tape)

**Comment by callingmedic911** [comment]
> If I understand correctly... its just that the components don't typically wait for `useAuth.loading` to become true?

Yes exactly, especially if component is likely to be behind private route.

> I think maybe in that case we ought to update the documentation, yes.
> 
> Because there maybe cases where you're using a component that uses `useAuth` in a public page (like we do on Tape)

👍 Will update docs.

**Comment by jtoar** [comment]
@cannikin You're good with docs! Think you can take this one?

**Comment by cannikin** [comment]
It sounds like @callingmedic911 was going to update?

**Comment by cannikin** [comment]
In this doc we already show usage examples with `waitFor()` and even a callout underneath explaining why we have to use it with `mockCurrentUser()`. What else would you add to clarify?

**Comment by dac09** [comment]
I think the issue is:
A) not super clear what you need to waitFor
B) not clear why currentUser is initially null, and why it actually would be good practice to not use currentUser until loading has finished

It's come up a few times on discord!

**Comment by cannikin** [comment]
I must not fully understand what the problem is..."not use currentUser until loading has finished", what does that mean? In the cell or in the test? I use `currentUser` all over the place in a cell, I don't care if it's loading or not. As long as I `waitFor()` in my test I get the expected result?

Do we just want an extra sentence that says "you have to use waitFor() because `currentUser` will be `null` on the first render of the component and only after checking with the authentication system will `currentUser` have the proper value"?  

If you guys understand what's going on here, feel free to update the doc!

**Comment by pi0neerpat** [comment]
> initial value of currentUser is always null in the first render
I think its good to preserve this behavior, instead of hide it in tests and stories.

Also, I think it would be helpful for the docs to show an example of mockCurrentUser in storybook too.

**Comment by callingmedic911** [comment]
> Do we just want an extra sentence that says "you have to use waitFor() because currentUser will be null on the first render of the component and only after checking with the authentication system will currentUser have the proper value"?

@cannikin  Yes, exactly! I just wasn't sure why the currentUser is null on the initial render. And similar to me, I guess many others have felt that it's a bug, but it's not. So I thought it's best to document this line.

> Also, I think it would be helpful for the docs to show an example of mockCurrentUser in storybook too.

I'm not much familiar with the storybook right now, still not part of my daily dev flow 😅. It would be great if I can get your help to setup an example with storybook. 🚀
