### ISSUE TITLE
Cannot use scaffolded form to insert Float datatype into database

### ISSUE THREAD

**Issue by Takashiidobe** [redwoodjs/redwood#392]
Hello nice folks of Redwood, I have run into a bit of a problem with the scaffolding, hope you can help me out.

After working my way through the tutorial, I decided to create a small app, grabbed a bunch of json data for it, and decided to go to work.

I edited my `schema.prisma` to look like this:

```js
datasource DS {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = env("BINARY_TARGET")
}

model CostOfLiving {
  id             Int      @default(autoincrement()) @id
  city           String
  state          String
  index          Float
  grocery        Float
  housing        Float
  utilities      Float
  transportation Float
  healthcare     Float
  misc           Float
  createdAt      DateTime @default(now())
}

model State {
  id     Int    @default(autoincrement()) @id
  abbrev String
  name   String
}
```

And ran and applied the migration with `yarn rw db save` and yarn rw db up`. The tables were created as required.  (I can see them in my sqlite3 database).

I ran `yarn rw g scaffold state` to create the forms for states, and entered a new abbreviation-state pair at `http://localhost:8910/states/new`. This worked fine, and the row was added to by sqlite db.

I ran `yarn rw g scaffold CostOfLiving` and went to `http://localhost:8910/costOfLivings/new` (bit funky url, i was expecting `cost-of-living/new`, but that's a question for another time. I entered in my data, and this prompt shows up.

In the console it tells me that the form is trying to convert Float values into Strings, and these are being rejected because sqlite wants data of the `REAL` datatype.

![Screen Shot 2020-04-06 at 8 57 24 PM](https://user-images.githubusercontent.com/26013562/78621894-4c85bc00-7849-11ea-8877-7e19dbbb96a8.png)

Is there a way to make the scaffolding aware of the underlying data types, or should I go try to parseFloat the form inputs manually?

Thank you in advance!

**Comment by cannikin** [comment]
Ahh yes, the good ol' DOM. All input fields return strings, so you'll need to transform those into your desired datatype before calling your mutation. The simplest way to do this currently is in your `onSubmit` handler where you get the form field values from Redwood Form as an object and you then call your mutation with that object.

In the scaffolded code that might look something like:

```jsx
// web/src/componets/NewPost/NewPost.js

const NewPost = () => {
  const [createPost, { loading, error }] = useMutation(CREATE_STATE_MUTATION)

  const onSave = (input) => {
    const castInput = { 
      city,
      state, 
      index: parseFloat(index), 
      grocery: parseFloat(grocery),
      // ...
    }
    createPost({ variables: { castInput } })
  }

  return (
    // ...
  )
}
```

Since we're all about the developer experience we're looking into ways to handle this for you. Maybe an attribute you pass to `<TextField>` that tells it what data type its value should be turned into before calling `onSave`. Not sure yet, we're working on it!

**Comment by Takashiidobe** [comment]
Gotcha. @cannikin, do you think there should be a general issue that encompasses this issue?
I think it might be nice to have some more visibility on it.
Feel free to close this issue after answering that :)

**Comment by thedavidprice** [comment]
@Takashiidobe great question and I'm adding some thoughts here -- no pressure for you specifically to take action, but we would welcome the help to move this into an Issue/Discussion if you (or anyone) might have the time.

- **Form Input Types** Currently our Redwood Form component <TextField /> does accept any/all [React Hook Form types](https://react-hook-form.com/form-builder). However:
    - this is not well documented
    - begs the question whether we should create a "generic/default" input component OR consider a specific component for some or all type as needed (TBD)
- **Input Validation vs. Data Type** It's plenty confusing that input validation does _not_ apply any kind of value/data type casting --> the return value is still a string regardless of input type=X
    - this also could be better documented
    - BUT this is going to be an issue shared by everyone. Maybe we should look into a solution like [Yup](https://github.com/jquense/yup), which is what [React Hook Form recommends](https://react-hook-form.com/advanced-usage#SchemaValidation) for schema validation. (note: I haven't looked deeply here -- need to confirm this does what I think it does.)

**Comment by thedavidprice** [comment]
Forum topic posted:
https://community.redwoodjs.com/t/redwood-forms-input-validation-type-errors-schema-validation-how-to-example/336

**Comment by Takashiidobe** [comment]
Sounds like a plan of action!

I'm going to add my thoughts here and other people can chip in, or if these thoughts should be posted in another issue that's linked or another forum, I'd be fine with moving them as well.

As a developer who is looking to use redwood in the future, I would prefer it if the redwood scaffold could introspect my `schema.prisma` file and have some mapping of prisma data type to javascript, and apply that to the scaffolded form. (for example, if my prisma data type is a float, to wrap the input.attribute in a parseFloat call before sending it over), and *maybe* using yup to verify that.

While doing the above would be great for developer experience, I do know there are some cons: first and foremost would be the tighter coupling to prisma, making it hard to change to another database layer, and opening up redwood to subtle bugs when the mappings fail to be generated properly, so this would introduce some long lasting maintenance burden compared to simply writing up documentation and asking the developer to change code in their project.

That being said, I do believe strongly in having generated code do work for you, and not minding when the abstraction might leak from time to time, but I know not everyone is the same, so I'm looking forward to hearing some other viewpoints on this issue.

**Comment by jtoar** [comment]
I believe we've fixed this one; just went through the same steps without errors. We've done a lot of work to parse the types for forms; there's still some discussions we should have, so saving this issue but closing out for now.
