### ISSUE TITLE
Scaffold generator doesn't rename query names (i.e. everything's a POST 😅)

### ISSUE THREAD

**Issue by saimonmoore** [redwoodjs/redwood#394]
e.g.

https://github.com/redwoodjs/redwood/blob/master/packages/cli/src/commands/generate/templates/scaffold/components/NamesCell.js.template#L6

I'm guessing something like this would fix it:

```
export const QUERY = gql`
    query ${pluralCamelName.toUpperCase()} {
      ${pluralCamelName} {<% columns.forEach(column => { %>
        <%= column.name %><% }) %>
      }
    }
  `
```

if so I can probably create a PR for it if this is the right approach?

**Comment by cannikin** [comment]
hahaha Whoops! Yes we'd love a PR! Really the name should be ALL_CAPS with underscores, so I don't think `pluralCamelName` will get you there.

I'd add a new variant here so it's available in all the templates, something like `pluralConstantName` and `singularConstantName`: https://github.com/redwoodjs/redwood/blob/master/packages/cli/src/lib/index.js#L50-L75 I'm sure there's an NPM package that'll create uppercase names with underscores out there...

**Comment by saimonmoore** [comment]
ok sounds good...I'll see what I can do...
