### ISSUE TITLE
Cells only support GraphQL queries

### ISSUE THREAD

**Issue by olance** [redwoodjs/redwood#3944]
To the question ["Can I Perform a Mutation in a Cell?"](https://redwoodjs.com/docs/cells#can-i-perform-a-mutation-in-a-cell), the docs say: "Absolutely".

So I created a new cell with this:

```js
export const QUERY = gql`
  mutation saveScore($score: Int!, $longestStreak: Int!) {
    saveScore(score: $score, longestStreak: $longestStreak) {
      bestScore
      longestStreak
    }
  }

...
```

This Cell would be rendered at the end of a game and be passed the score and longest streak from the last game they played to be saved.
The result of the mutation request tells me what the best score and all-time longest streak of the user now are, which allows me to display specific messages when player just improved their best scores.

Unfortunately, I discovered that this couldn't work.
The Cell internal code is invariably using `useQuery`:

https://github.com/redwoodjs/redwood/blob/a050396b2b4f230b73206ce9cb76d58fc87bb18a/packages/web/src/components/createCell.tsx#L242-L247

... and this will fail when `QUERY` actually contains a mutation request.

I'm wondering if we could make both queries and mutations work for cells? Or would _this_ be an anti-pattern?
Would be happy to work on a PR if we want this to work :)

**Comment by Tobbe** [comment]
You're not the first one to wish for this @olance 🙂 

There's a draft PR over here: https://github.com/redwoodjs/redwood/pull/2870 
Also a couple of posts to the forum here: https://community.redwoodjs.com/t/cells-with-mutation/2231

Look it through and then reach out to @ajoslin103 and maybe you two can work on it together 🙂

**Comment by olance** [comment]
ah! 😄 

I guess I should have done my homework ^^
Thanks @Tobbe, I'll have a look!
