### ISSUE TITLE
Get rid of PageLoader

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#3957]
https://github.com/redwoodjs/redwood/pull/3772 introduced a new component called `ActveRouteLoader`. It replaced `PageLoader` in the main Router flow. But PageLoader is still used when rendering the NotFoundPage. We should replace that usage with ARL as well, so we can get rid of PageLoader.

(There are also a couple of comments in the code that mentions PageLoader that we need to update)

**Comment by jtoar** [comment]
Pretty sure we got rid of `PageLoader` in https://github.com/redwoodjs/redwood/pull/5521.
