### ISSUE TITLE
`undefined` still causes (presence) validator to trigger

### ISSUE THREAD

**Issue by realStandal** [redwoodjs/redwood#3979]
I'm wanting to wrap a specific impl. of `validate()` for re-use. I'd like to use this wrapped validator for both creating and updating services - so it's important it can handle when a value *should* be undefined (a resource is being updated, but not all fields have changed) and when a specific field needs to have a value (when a resource is being created).

I assumed I'd be able to pass `undefined` to any of the validators, and that would function identically to if the validator was never configured in the first place. Instead, the validator *does* trigger, using the default configuration - or nothing, if the validator doesn't have a configuration.

Here's an example. Both `presence` and `format` validators will trigger.

```TypeScript
const required = false

validate(name, {
    presence: !required ? undefined : { message: 'name.required' },
    format: undefined,
    length: {
      max: 149,
      message: 'name.length',
    },
  })
```

I took a look at the documentation, to see if I was doing something wrong. I noticed that, for `presence`, the validator accepts a value of `true` in one of the examples. This led me to believe I could use `false`, but that made the TS-server yell at me, and had no functional change.

As expected, completely removing the field caused it to not trigger.

**Comment by realStandal** [comment]
As a work-around (and probably the preferred solution) for my problem, I can use the `allow*` family-and-friends.

The behavior in the issue still occurs. This can be closed or remain open.

**Comment by simoncrypta** [comment]
@cannikin Do you have any thought on this ?

**Comment by cannikin** [comment]
So the presence validator has options for whether to allow `null` and `undefined`: https://redwoodjs.com/docs/services#presence 

But either way, setting `undefined` on a validator should be the same as never having set it in the first place. Maybe we need an `if (options)` check inside this loop?

https://github.com/redwoodjs/redwood/blob/main/packages/api/src/validations/validations.ts#L552-L554

**Comment by jtoar** [comment]
@cannikin Just to confirm, it sounds like you're in agreement here about enabling this behavior?

**Comment by cannikin** [comment]
Yes, I think if you explicitly set a validator to `undefined` then it should act as if you never set it in the first place. Meaning these two declarations should be equivalent:

```
validate(name, {
  presence: true,
  format: undefined
})

validate(name, {
  presence: true
})
```

**Comment by jtoar** [comment]
@realStandal No pressure but would you be up for taking this one on?

**Comment by realStandal** [comment]
@jtoar I don't mind so long as "sometime this week" is an ok timeline.

**Comment by jtoar** [comment]
@realStandal absolutely—even sometimes this month is more-than ok.
