### ISSUE TITLE
Field does not exist on enclosing type (Prisma)

### ISSUE THREAD

**Issue by natserract** [redwoodjs/redwood#3982]
**Error message:**
`Failed to validate the query: 'Field does not exist on enclosing type.' at 'Query.findMany'.

**Version:**
- @redwoodjs/core: ^0.38.1
- @prisma/client: 3.3.0

**Related issues in [prisma](https://github.com/prisma/prisma)**
- https://github.com/prisma/prisma/issues/9553
- https://github.com/prisma/studio/issues/503

**Need to do is the following (from my case):**
- rm -rf  `yarn.lock` and `node_modules`
- yarn install
- generate your prisma -> `yarn rw prisma generate` or `prisma generate`
- yarn rw g types (optional)
- **yarn cache clean**

Running:
- yarn rw dev

Thanks, hope can helps.

**Comment by thedavidprice** [comment]
Thank you for posting this work-around @natserract!

I suggest we leave this open until prisma/prisma#9553 is resolved

**Comment by orta** [comment]
Yeah, this hit me earlier this week and was fixed after finding a second copy of `@prisma/client`. I think it was me working in a subdirectory and running Prisma commands in there.

**Comment by jtoar** [comment]
@thedavidprice do we feel good about this (i.e. isn't happening anymore?)
