### ISSUE TITLE
Allow FatalErrorBoundary to be more descriptive

### ISSUE THREAD

**Issue by jonniebigodes** [redwoodjs/redwood#399]
While working on the redwood test case with Preact i encountered a situation where the FatalErrorBoundary led to some headaches.

A example of this was, after setting up Preact i had a issue with the fragments as i configured them according to a wrong configuration option. 
So when i created a component/page or even change the code to include a fragment, when i fired up redwood it would lead me to the `FatalErrorPage` mentioning that something went wrong and even checking the console nothing was logged in it. And that led me to some real "fun" times trying to triage what was happening.

Another example of this is a simple one, as soon as the user creates a new redwood app following the instructions, if he fires up redwood he/she might see the same page and think that something was wrong as the index route and page does not exist and start populating the repo with issues that could be probably prevented.

I'm inclined to believe that the `FatalErrorBoundary` component and the page associated might need some changes to throw a more descriptive text in the future that the user can pinpoint the actual cause of the issue with his redwood app instead of the standard "Something went wrong".

Feel free to provide feedback.

**Comment by peterp** [comment]
@jonniebigodes Thanks for this, you're 100% right, we've got an issue open here #140

**Comment by jonniebigodes** [comment]
@peterp sorry for the delay in responding. I forgot to look it up and now this seems that is redundant, so with that i'm going to close it. Sounds good?

**Comment by peterp** [comment]
Thanks @jonniebigodes
