### ISSUE TITLE
[deploy: serverless] Add extra checks to `rw deploy aws serverless`

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3990]
### Goal
Serverless.yml file has to specify what API routes are exposed. When a new api function is generated, even when redwood builds these functions, they will not be deployed unless the yml file is also configured to deploy this to AWS Lambda.

We should add an extra step to the deploy process that will check that all of the functions present in the dist directory are configured in the yml file, and warn the user as part of deployment if one or more are missing.

**Comment by virtuoushub** [comment]
In case it helps this is where/how we currently generate the yml/package the js for these functions in the [`serverless-deploy-3686`](https://github.com/redwoodjs/redwood/tree/serverless-deploy-3686) branch:

https://github.com/redwoodjs/redwood/blob/b615def93bb17b2478716ae46b8d7ba9abaeea09/packages/cli/src/commands/setup/deploy/providers/aws-serverless.js#L41-L71

https://github.com/redwoodjs/redwood/blob/b615def93bb17b2478716ae46b8d7ba9abaeea09/packages/cli/src/commands/deploy/packing/nft.js#L54-L55

**Comment by ajoslin103** [comment]
FWIW: I've had quite good results from: https://www.npmjs.com/package/yaml -- it's the only one I found that would roundtrip comments.  It parses .yml into a javascript object, gives some yml routines (and accepts modifications to the exposed underlying javascript object) and then writes out the .yml file again.  👍🏼

**Comment by dac09** [comment]
Yup! This is a nice to have :)
