### ISSUE TITLE
Generated Test Files: add comment with link to Redwood Testing Doc

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#3991]
_continuing from #3601_

There are (plenty of) cases where the boilerplate tests will fail. One recent example is #3601 re: Float and DateTime types that don't play well with Jest expect(). Instead of attempting to configure boilerplate to handle all possible situations, we decided to update the docs over here https://github.com/redwoodjs/redwoodjs.com/pull/881

But what good are docs if you don't know about them? I suggest we add a comment block to all generated test files:
- link to the Redwood Testing Doc: https://redwoodjs.com/docs/testing
- explains that boilerplate isn't intended to work for all circumstances without adjustments, e.g. Float and DateTime types

**Comment by refactor-this** [comment]
I'd like to work on this one if that's ok

**Comment by thedavidprice** [comment]
Please do! Assigning it to you now.

And a (shameless) plug for the RedwoodJS Contributing Workshop I'm hosting next week. Would be a pleasure to have you join given interest + availability:
https://community.redwoodjs.com/t/contributing-workshop-thursday-january-20th/2605/4

😄

**Comment by refactor-this** [comment]
Thank you thank you, and I'll be there 😃

**Comment by thedavidprice** [comment]
Great! Also, when you open the PR please tag me via @thedavidprice I'll assign the PR to myself for help + review.

**Comment by refactor-this** [comment]
@thedavidprice will this work for a comment that will be placed at the top of every generated test file, under the imports?

```
// Generated boilerplate tests do not account for all circumstances
// and can fail without adjustments, e.g. Float and DateTime types.
//           Please refer to the RedwoodJS Testing Docs:
//               https://redwoodjs.com/docs/testing
```

**Comment by thedavidprice** [comment]
I like it! How about this link directly to the Type section:
- https://redwoodjs.com/docs/testing#jest-expect-type-considerations

Definitely good enough to get a PR going. We can finalize it there. Thank you!
