### ISSUE TITLE
Old nodejs target used for rw scripts

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#3999]
I'm on 0.39, so apologies if this is fixed in newer versions

I'd like to be able to use `replaceAll` and other modern JS features in my rw scripts.

![image](https://user-images.githubusercontent.com/30793/147229576-ca26e77e-b74a-4604-99e3-eb4baec046a1.png)

The screenshot above shows a rw script I'm editing.

Can/should we control this in tsconfig?

**Comment by Tobbe** [comment]
Node 14: https://stackoverflow.com/questions/61305578/what-typescript-configuration-produces-output-closest-to-node-js-14-capabilities/61305579#61305579
Node 16: https://stackoverflow.com/questions/67371787/what-typescript-configuration-produces-output-closest-to-node-js-16-capabilities/67371788#67371788

**Comment by jtoar** [comment]
I was able to reproduce this on v0.42. But I think it's just a linting error. I tried the example on mdn in a script:
```ts
// scripts/replace.ts

export default async () => {
  const p = 'The quick brown fox jumps over the lazy dog. If the dog reacted, was it really lazy?'
  console.log(p.replaceAll('dog', 'monkey'))
}
```

And it worked. You're probably right about it being a tsconfig setting. We use `replaceAll` a lot in the framework so I'll see what we do there.
