### ISSUE TITLE
Generated Form Decimal Input Error

### ISSUE THREAD

**Issue by BBurnworth** [redwoodjs/redwood#4012]
**Problem:** Generated forms with Decimal type return '**_non numeric value_**' error (see below).

**Reproduction:** Test Model schema below, along with errors from attempted form input. 

1. Created schema model.
2. `yarn rw prisma db push`
3. `yarn rw g scaffold numberTest`
4. Attempted to create new NumberTest.

**Error Message:** `Variable "$input" got invalid value "1.02" at "input.testDecimal"; Float cannot represent non numeric value: "1.02"`

**Workaround:** On the surface, the form input for Float has this `validation={{ valueAsNumber: true }}` on the Input component. I copied this line to the decimal input component and it seems to have worked correctly. The data stores in the database and I can retrieve and edit the record.

**Unknown:** I did not go deeper than copy/pasting this validation line to the other component. There may be deeper code changes that I am unaware of. Also, I was going to limit the decimal precision and scale to (4,2) _see prisma decimal field type below_, but I have not done nor tested this yet.

**References:** 
[Prisma decimal field type](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#decimal): 
`decimal | numeric    @db.Decimal(p, s)†`

From [Discord "quick-help" chat with David:](https://discord.com/channels/679514959968993311/716252919875240007/925084807917084672)
----------------------

Test model: 

```
model numberTest {
  id          Int      @id @default(autoincrement())
  cylinderId  String
  testDecimal Decimal?
  testFloat   Float?
}
```

(_On New NumberTest Form_) Initially, I cannot pass beyond the decimal field validation due to the following error. 

**Blank Input error:** `Variable "$input" got invalid value "" at "input.testDecimal"; Float cannot represent non numeric value: ""`

**Decimal Input error:** `Variable "$input" got invalid value "1.02" at "input.testDecimal"; Float cannot represent non numeric value: "1.02"`

_Float worked correctly._ 

**Changed generated TextField input from:** 
```
        <TextField
          name="testDecimal"
          defaultValue={props.numberTest?.testDecimal}
          className="rw-input"
          errorClassName="rw-input rw-input-error"
        />
```

**Changed to:** 
```
       <TextField
          name="testDecimal"
          defaultValue={props.numberTest?.testDecimal}
          className="rw-input"
          errorClassName="rw-input rw-input-error"
          validation={{ valueAsNumber: true }}
        />
```

**Comment by Tobbe** [comment]
@BBurnworth Hi! Thanks for the issue report 🙂 

`valueAsNumber` certainly looks like a way forward here. Another option to look at might be to use an `<input type="number">` instead. Both for floats and decimals. Maybe setting `step="any"`. Or, maybe even `step="0.01"` `"0.001"` etc depending on what precision is specified for the decimal, if that's possible to figure out.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#allowing_decimal_values

Using `step="any"`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#step

Someone probably/maybe had a good reason for making the float input a regular text input field, which again points to `valueAsNumber` being a good option.

As you can probably tell, I have no good straight answers here. And I'm not sure anyone else does either. So I invite you to think about what solution you would like best. Let us know what your thought process is 🧠 

I'll also ping @cannikin here, as he's our OG forms guy 😁

**Comment by dthyresson** [comment]
Hi @BBurnworth I just stumbled upon this issue and some of this may be fixes in PR https://github.com/redwoodjs/redwood/pull/4053.

It will help when using graphql scalars and the error message presented.


Also, it will better handle general type errors raised in GraphQL.

It might then be 

```Float cannot represent non numeric value: "1.02"```

Which may not be ideal, but better.

**Comment by BBurnworth** [comment]
I found a reference to this issue in [this blogpost on snipcart.](https://snipcart.com/blog/jamstack-framework-redwoodjs-tutorial) They a) parse the float to number prior to calling onSave and b) change the type to `number` in the `<TextField>`.

This is the mention and their workaround:

> One downside to RedwoodJS is that the created form _doesn't support floats by default_, so we have to update it.
> 
> In ProductForm.js replace the onSubmit to the following:

```
const onSubmit = (data) => {
   data.price = parseFloat(data.price)
   props.onSave(data, props?.product?.id)
 }
```
> 
> Also, make sure the type of the price TextField is set to number.
> 
```
<TextField
       name="price"
       type="number"
       defaultValue={props.product?.price}
       className={CSS.input}
       errorClassName={CSS.inputError}
       validation={{ required: true }}
       />
```
> 
> This is needed because by default “price” will be a string and it will later cause a problem when trying to add a new product.
> 

To @Tobbe's point, there may have been a good reason for handling this field in this way. 

As a newcomer going through the docs, stepping into the framework and testing things, this was confusing to run into since everything else seems to be handled so buttery smooth.  Scaffold was an easy way for me to start working with the framework, and this was a stumbling block to a smooth experience.

Suggestions if this is intentional and the user should work around it:

- **_Docs Update_**: Add a note in the generate scaffold docs about this field type issue and the most appropriate way of handling it.
- **_CLI Update_**: Detect this field type during scaffold generation and make a note about handling it. That way the user would not be surprised and spend time looking for the issue and how to best fix it.

**Comment by cannikin** [comment]
At the time I wrote this you couldn't determine the number of decimals from Prisma metadata (so I couldn't make it a `type="number"` and use the `step` attribute [and I didn't realize `step="any"` was a thing!]), and react-hook-form didn't have the inline validations (like `valueAsNumber`). 

Looking at the scaffold generator code now, it should set `valueAsNumber={true}` for `Float` fields: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/scaffold/scaffold.js#L387-L390 But you're saying you had to add that attribute manually? 

Looks like we could update that to use a `<NumberField>` and add the `step="any"` attribute which would help constrain the values going into that field. But it should still have been `valueAsNumber`ing the submitted value...

**Comment by BBurnworth** [comment]
@cannikin Float is working correctly. Decimal is not. I ran a 'test model' with both Float and Decimal types to confirm, and posted results in the middle/bottom of the [issue description](https://github.com/redwoodjs/redwood/issues/4012#issue-1089402601).

I probably should have separated that test into a second comment.

**Comment by cannikin** [comment]
Ahhh! Yep so in that code section I linked to above we just need to add an entry for `Decimal` and we can define what input is created and the validation options for formatting it. We love PRs, wanna take a shot? 😀

**Comment by BBurnworth** [comment]
Sure thing, I will give it a shot. Thanks for the suggestion. Should I clone the master repo `git clone https://github.com/redwoodjs/redwood.git` and work from there?

**Comment by cannikin** [comment]
Yep! And we’ve got a great write up for getting started on dev-ing on Redwood itself: https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md

**Comment by thedavidprice** [comment]
@dthyresson assigned you here as well as #4169 since you're doing review. Wasn't clear to me if that PR is going to close this Issue or if there's additional work to follow. So I'll let you manage if they should be linked and which you'd prefer to track on the project boards.

Thanks again for the help and PR @BBurnworth

**Comment by dthyresson** [comment]
> @dthyresson assigned you here as well as #4169 since you're doing review. Wasn't clear to me if that PR is going to close this Issue or if there's additional work to follow. So I'll let you manage if they should be linked and which you'd prefer to track on the project boards.
> 
> Thanks again for the help and PR @BBurnworth

A PR is up here https://github.com/redwoodjs/redwood/pull/4169 but just needs a few tests and should be good to go.
