### ISSUE TITLE
[Router] Navigating to the same route doesn't update parameters

### ISSUE THREAD

**Issue by rohmann** [redwoodjs/redwood#403]
Having a great time with Redwood so far! Running into a couple bugs with routing I wanted to report. Let's say I have this route:

```jsx
<Route path="/item/{id}" page={ItemPage} name="item" />
```

And a navigation where I can link between multiple items with different IDs:
```jsx
<Link to={routes.item({ id: 'a')} />
<Link to={routes.item({ id: 'b')} />
```

If I click between the routes, the browser's address bar will update to reflect the right ID (e.g. `/item/a` and `/item/b`). The page component will also re-render, but the params have not changed. It will only update the params if you actually refresh.

<hr>
Here's another odd one (might need to be a separate issue). Using the same a/b item Links above, say I want to name the param to add either a constraint or transform (or both) like this:

```jsx
<Route path="/item/{name:id}" page={ItemPage} name="item" />
```

The result of calling `routes.item` is `/item/{name:id}?color=a`. instead of `/item/a`.

**Comment by rohmann** [comment]
Ok, so I have a solution for the first issue. When it comes to submitting a PR, do you want tests? If so, any guidelines/direction on how those should be structured?  Doesn't look like the router has tests for the page loader yet.

**Comment by peterp** [comment]
@rohmann Ah, that was me making a stupid mistake. I would really appreciate a test, could you create a file of the same name in `__tests__, in this case I'm guessing it's `src/__tests__/page-loader.js`

Since you would be testing a React component I would suggest using `@testing-library/react`

If you would like, I could get the basic skeleton structure for testing a react component ready in the router, with an example, and then you could use that to provide a fix?

**Comment by rohmann** [comment]
Hi @peterp,

Sorry for missing this until now. If you could have some basic setup for tests in place that'd be awesome! I've honestly not used `@testing-library/react` but could certainly figure out how to add a test if the tooling was already in place.

**Comment by peterp** [comment]
hey @rohmann - someone recently added some tests for `Link`, and I don't think it would be dissimilar: https://github.com/redwoodjs/redwood/blob/master/packages/router/src/__tests__/links.test.js

**Comment by eurobob** [comment]
@rohmann did you make any progress on this?

**Comment by peterp** [comment]
@eurobob I believe that we've actually solved this, we just need some tests.
