### ISSUE TITLE
import_api.validateUniqueness) is not a function

### ISSUE THREAD

**Issue by wbashir** [redwoodjs/redwood#4063]
Hi,

I'm trying to use the **validateUniqueness** function but getting an error:

`import { validateUniqueness } from '@redwoodjs/api'

export const createIntroCapture = ({ input }) => {
  return validateUniqueness(
    'introcapture',
    { email: input.email },
    { message: 'Your email is already in use' },
    (db) => db.introCapture.create({ data: input })
  )
}
`

Here is the error:
```
 errors: [
api |       {
api |         "message": "(0 , import_api.validateUniqueness) is not a function",
api |         "locations": [
api |           
```

**Comment by jtoar** [comment]
Hey @wbashir, I just tried to reproduce this and couldn't. Could you provide a reproduction and/or any other details about your repo/where you're seeing this error (as soon as you run `yarn rw dev`? Or when creating an intro capture?).

You may have already done this but I often forget: using `validateUniqueness` requires you enable a preview feature and regenerate your prisma client (instructions here: https://redwoodjs.com/docs/services#enable-prisma-preview-feature). If you did those two things already then ignore me!

**Comment by wbashir** [comment]
@jtoar Thanks for looking into this. I realized from your documentation after carefully reviewing, I was on the wrong version of Redwood at 0.36. 

I'm in the process of upgrading to take advantage of these experimental features!
