### ISSUE TITLE
gql is not syntax highlighted in .tsx files

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#4085]
In tsx cells the gql is missing syntax highlighting

FooCell.tsx
![image](https://user-images.githubusercontent.com/30793/148651034-843f9727-6e53-4a7f-bc72-abe5b615d74d.png)

BarCell.js
![image](https://user-images.githubusercontent.com/30793/148651047-efa450d8-add3-4017-9139-634ac3685cfe.png)

I'd like to have the same syntax highlighting support in .tsx files as in .js files

`yarn rw info`
```
  System:
    OS: macOS 11.6
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.12.0 - /var/folders/w7/hkfhzp4x68qcbr1ggchr7hx40000gn/T/yarn--1641657674986-0.8346933884565708/node
    Yarn: 1.22.17 - /var/folders/w7/hkfhzp4x68qcbr1ggchr7hx40000gn/T/yarn--1641657674986-0.8346933884565708/yarn
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 96.0.4664.110
    Edge: 97.0.1072.55
    Firefox: 94.0.1
    Safari: 15.0
  npmPackages:
    @redwoodjs/core: ^0.41.0 => 0.41.0
```

**Comment by realStandal** [comment]
Hey @Tobbe, do you by-chance not have the [GraphQL VSCode extension](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql) installed? (it should be one of the extensions recommended when first opening a new project)

(Although, still weird you're getting highlighting with JS, wonder if that's RW's doing or another extension)

From it's `README`:

> `gql`/`graphql` tagged template literal support for tsx, jsx, ts, js
> * syntax highlighting (type, query, mutation, interface, union, enum, scalar, fragments, directives)
> * autocomplete suggestions
> * validation against schema
> * ...

When I open a `*.tsx` file with it enabled:

![image](https://user-images.githubusercontent.com/25166787/148653236-3ea0dbe3-78f8-4a92-ba4f-0c80a82b6752.png)

After I disable that extension and reload:

![image](https://user-images.githubusercontent.com/25166787/148653297-31a7d55e-540b-4056-a730-0a8d10cf2902.png)

**Comment by Tobbe** [comment]
Installing the gql extension does indeed fix it. Thanks Ryan!
