### ISSUE TITLE
Matching named routes with location.pathname in V1 RC

### ISSUE THREAD

**Issue by viperfx** [redwoodjs/redwood#4087]
Prior to v1, 0.37 to be exact, I was using named routes in combination with an internal redwood method called `matchPath`.

In a layout I had code that roughly looked like this:

In short, it maps some routes to a help center article slug. I iterate through the map and build up a list of article slugs based on if the route matches the current location.

```
useEffect(() => {
  const articleRouteMap = {
    [routes.dashboard()]: ['getting-started', 'admin-portal-features', ],
    .... // more mappings
  }
  let suggestedArticles = []
  Object.keys(articleRouteMap).forEach((route) => {
    if (matchPath(route, location.pathname).match) {
      articleRouteMap[route].forEach((slug) => {
        suggestedArticles.push(slug)
      })
    }
  })
}, [location.pathname])
```

This method used to work because the evaluating named routes like this caused no errors. With the V1 RC upgrade, evaluating a route with params that do not have all the required params passed in - causes a fatal error in the application.

Calling `routes.dashboard()` causes the following error. 

`Error: Missing parameter 'workspace' for route '/w/{workspace}/dashboard'. `

Based on reading the redwood codebase 

The named routes are built up here 

https://github.com/redwoodjs/redwood/blob/main/packages/router/src/router.tsx#L192

`replaceParams` throws a fatal error here

https://github.com/redwoodjs/redwood/blob/4008f5ae37b7a15ec730c1f9bf60cff09c06468a/packages/router/src/util.ts#L233

Could redwood provide another way of doing this? So I can keep using named routes to match against the current location.

Happy to contribute something if I get some pointers on how to approach it and what methods to re-use. 👍

**Comment by Tobbe** [comment]
Here's the PR that changed this behavior. It has some good background info and reasonings around the change. Please have a read https://github.com/redwoodjs/redwood/pull/3714

Please let us know if reading that changes your view of this, or any other feedback you might have

**Comment by Tobbe** [comment]
@mojombo Pinging you here since you wrote the PR that changed this behavior

**Comment by viperfx** [comment]
Yea I get the reasoning in the PR and I don't disagree with that behavior or looking for it to be changed. 

It would be great to have a way to introspect my own routes to grab the props for my use case. As I am not actually trying to call the route and cause a navigation change - just wanted to check if the route matches the current path.

**Comment by Tobbe** [comment]
It ain't pretty 😬

But would this work?

```jsx
useEffect(() => {
  const articleRouteMap = {
    [routes.dashboard({ workspace: '{workspace}' })]: ['getting-started', 'admin-portal-features', ],
    // ... more mappings
  }
  // ...
}, [location.pathname])
```

**Comment by viperfx** [comment]
> But would this work?

Yes, it would work but I would have to add every parameter in the route. My articleRouteMap contains 18 routes and have other layouts using a similar technique. 

For now I have used patch-package because I was not able to find a workaround.

**Comment by viperfx** [comment]
Hey folks - I am currently in the process of upgrading to V1 and this is still an issue with my codebase. It does require a patch to remove the exception that's thrown.

Just wanted to give this a bump so it could be reviewed.

**Comment by dthyresson** [comment]
> require a patch to remove the exception that's thrown.

@viperfx Do you have the code that patches to share?

**Comment by viperfx** [comment]
Yes - quite a brute force solution though :) 

```diff
diff --git a/dist/util.js b/dist/util.js
index 57cc8a9a0296405200a0a5b65dc0c77a64d1f76c..55d7d078b12f0bd704b1a62d080f317b76549e00 100644
--- a/dist/util.js
+++ b/dist/util.js
@@ -279,10 +279,6 @@ const replaceParams = function (route) {
 
     if (value !== undefined) {
       path = path.replace(match, value);
-    } else {
-      var _context4;
-
-      throw new Error((0, _concat.default)(_context4 = "Missing parameter '".concat(name, "' for route '")).call(_context4, route, "'."));
     }
   });
   const paramNames = (0, _map.default)(params).call(params, param => param[0]);

```

**Comment by dthyresson** [comment]
Ok, so the patch is to ignore the exception -- but everything still works ok? A fix would not be to ignore the exception but rather allow "a route with params that do not have all the required params passed in"?

**Comment by Tobbe** [comment]
I haven't tried this, so the code might not even compile. But could something like this work?

```
const params = useParams()

useEffect(() => {
  const articleRouteMap = {
    dashboard: ['getting-started', 'admin-portal-features', ],
    .... // more mappings
  }
  
  let suggestedArticles = []
  Object.keys(articleRouteMap).forEach((routeName) => {
    try {
      if (matchPath(routes[routeName](params), location.pathname).match) {
        articleRouteMap[route].forEach((slug) => {
          suggestedArticles.push(slug)
        })
      }
    } catch {
      // ignore non-matching route
    }
  })
}, [location.pathname, params])
```

**Comment by Josh-Walker-GM** [comment]
Hey @viperfx, I'm going to close this issue because it is referring to a v1 issue and we have now reached v6 so this is likely not impacting many people now. Feel free to reopen if you feel we still need to address something here and we'll be more than happy to start chatting about this again
