### ISSUE TITLE
[Windows] `yarn rw dev` fails when path includes a space or special characters

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#409]
Windows: v10
Powershell
@redwoodjs: v0.4.0

See [this forum thread](https://community.redwoodjs.com/t/need-help-using-yarn-yarn-redwood-dev-command-not-working/268) for images and background information. 

I ran a test on my Windows virtual machine. The ",,," characters block the `yarn rw` command from being found, however, this feels like an edge case we might not need to support if the fix isn't obvious.

The space throws the error shown in the image below when running 'yarn rw dev'.

I thought we handled this previously here in the code for the 'dev' command: 🤔
https://github.com/redwoodjs/redwood/blob/153703f4b85fce11b2c7f083ca5176600ca25d62/packages/cli/src/commands/dev.js#L16-L18

<img width="851" alt="Screen Shot 2020-04-08 at 9 45 54 PM" src="https://user-images.githubusercontent.com/2951/78858811-568ef280-79e2-11ea-8315-c9c80d29b120.png">

**Comment by jonniebigodes** [comment]
@thedavidprice as the project is getting traction, it probably wouldn't be a bad idea to start consider trying to implement a solution for special characters like those used in the portuguese language, namely `ç`, `ã`,`ã`, in the spanish language `ñ` and the also some for the germanic languages like `Ü` to name a few. Most frameworks/cli tend to stick to ascii characters and tend to overlook it and it comes back to bite them at some point. If this is handled by redwood at boot i'm inclined to believe that it would be a bonus point for redwood.

**Comment by thedavidprice** [comment]
Closed by #457
