### ISSUE TITLE
Add CORS options to dbAuth

### ISSUE THREAD

**Issue by pi0neerpat** [redwoodjs/redwood#4103]
With `/graphql` we can set CORS using the methods here https://redwoodjs.com/docs/graphql.html#cors-configuration

However, the `/auth` function provided by dbAuth doesn't allow setting CORS. This means the web app cannot call `/auth?method=getToken`

**Comment by dthyresson** [comment]
Does this mean that the dbAuth function needs to return headers:

```ts
  headers: {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Credentials": true,
  },
```

in https://github.com/redwoodjs/redwood/blob/f77138fc6fb6b3e17b7e14f05a49793483b3d0df/packages/auth/src/authClients/dbAuth.ts#L42 and related?

**Comment by pi0neerpat** [comment]
Yes I believe that’s all that’s needed.

**Comment by pi0neerpat** [comment]
@cannikin I really like this solution, being able to set them this way would be awesome!

**Comment by dthyresson** [comment]
Agreed. I think we can move some of the CORS option handling and types from the graphql -server package into api and share.

**Comment by dac09** [comment]
+1 on having a config option, rather than assume it is required.

**Comment by dthyresson** [comment]
> +1 on having a config option, rather than assume it is required, and sharing the code with graphql-server if possible. I'll make it happen.

Nice. It looks like we could move the logic in 

https://github.com/redwoodjs/redwood/blob/17b9be564d68a140faacac37b3fa8a1db98f7bc0/packages/graphql-server/src/cors.ts#L16

to api and then share with both (since graphql-server depends on api already but not vice versa).
