### ISSUE TITLE
Update Auth0 auth template to extract namespaced roles

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#4139]
In her post ["Implementing RBAC in RedwoodJS using Auth0"](https://giannellitech.dev/rbac-redwoodjs-auth0/) @agiannelli notes that if you setup roles in Auth0, you probably will be using "namespaces":

```js
/**
 * @param {Event} event - Details about the user and the context in which they are logging in.
 * @param {PostLoginAPI} api - Interface whose methods can be used to change the behavior of the login.
 */
exports.onExecutePostLogin = async (event, api) => {
  const namespace = '<https://amazingredwoodsite.api>';
  if (event.authorization) {
    api.idToken.setCustomClaim(`${namespace}/roles`, event.authorization.roles);
    api.accessToken.setCustomClaim(`${namespace}/roles`, event.authorization.roles);
  }
}
```

Auth0 requires that "custom claims" on the JWT need to be namespaced -- see: https://auth0.com/docs/get-started/apis/scopes/sample-use-cases-scopes-and-claims#add-custom-claims-to-a-token

> To keep your custom claims from colliding with any reserved claims or claims from other resources, give them a globally unique name using a namespaced format.

> By default, Auth0 always enforces namespacing; any custom claims with non-namespaced identifiers will be silently excluded from tokens and silently ignored in Actions and Rules.

Because of this, the `auth.js` lib utility needs to change how it parses the JWT and extracts roles:

```js
- const { roles } = parseJWT({ decoded })
+ const roles = decoded[process.env.AUTH0_AUDIENCE + '/roles']
```

Therefore, should update the Auth0 with template so that roles are extracted properly.

**Comment by dthyresson** [comment]
@agiannelli are you interested in working on this issue?

**Comment by agiannelli** [comment]
@dthyresson yes! I'd love to.
