### ISSUE TITLE
Using HTML form primitives or Custom Form elements with the redwoodjs forms 

### ISSUE THREAD

**Issue by ghmeec** [redwoodjs/redwood#417]
cant seem to find the information in documentation on how to use the redwoodjs forms with html primitives and custom form elements or other libraries form elements. All shown is using form elements from "@redwoodjs/web"

**Comment by thedavidprice** [comment]
Hi @ghmeec The [Redwood Forms](https://github.com/redwoodjs/redwood/tree/master/packages/web/src/form) are an implementation of [React Hook Forms](https://react-hook-form.com/). Based on my understanding of your question, you might want to look through the documentation for React Hook Forms to learn more. There’s a lot there that has not been implemented (yet)in the Redwood Forms. You have a couple paths here: possibly extend Redwood Forms to meet your needs, or just import and use React Hoof Form directly.

Another form library that’s been recommended is [React Final Form](https://final-form.org/react). See this issue for some background and links. #446 

Closing this Issue for now. If you have more questions, want to show some example of code your trying, or in general are interested in more discussion, could you try our Community Forums? https://community.redwoodjs.com

If something isn’t working right or you have a proposal about making something work better, please do open an Issue. 

Thanks again. And we hope you’ve been enjoying Redwood! We’d be excited to hear more about what you build 😀

**Comment by ghmeec** [comment]
Thanks, this is helpful been able to figure it out
