### ISSUE TITLE
Redis cache timeouts

### ISSUE THREAD

**Issue by tctrautman** [redwoodjs/redwood#4187]
App hosting: Netlify
Redis hosting: [Railway](https://railway.app/)
Redwood version: `0.41.0`

While receiving a small spike in traffic today I started noticing intermittent timeouts that appeared to be coming from my Redis cache (configured via the `useResponseCache` Envelope plugin.)  This is what my logs looked like within Netlify:

![Screen Shot 2022-01-17 at 4 48 41 PM](https://user-images.githubusercontent.com/4513085/149855616-001000fd-e00e-4cc7-b5b1-dba2f25de61e.png)

I'm not entirely sure where this issue is coming from, but my best guess is that it's an issue with Railway or Envelope.  I contacted Railway and they seemed to think that this could be an issue with not closing connections properly.  They said this would flood the TCP proxy on a serverless deployment like Netlify, which I believe is handled by the Envelope plugin.

Unfortunately this isn't a part of the stack I've spent much time on before.  Has anyone seen issues like this or have thoughts about what might be causing them?

Thank you!

**Comment by dthyresson** [comment]
@tctrautman Netlify serverless functions (their lambda functions) run for 10 seconds and then will error.

It looks like here there was a connection timeout to your Redis server "connect ETIMEDOUT" that happened inside the `ioredis` client.

One thing I would check is how many connections does your Redis server support?

For example,. Heroku Redis plans have a certain number of connections 20, 40, 80, 200 depending on the plan:

https://elements.heroku.com/addons/heroku-redis


If you are using Upstash, I see there is a new Redis client made for their service than might not open connections and is better in a serverless world:

https://github.com/upstash/upstash-redis

Maybe give that a try?

**Comment by tctrautman** [comment]
Thank you @dthyresson!  Very helpful as always.

I'll investigate how many connections Railways supports and take a look at using the Upstash Redis client -- I somehow hadn't considered swapping out `ioredis` for another client.  Closing this out for now since I have a path forward, I'll reopen if I have more questions.
