### ISSUE TITLE
Setup netlify deploy command breaks app

### ISSUE THREAD

**Issue by memarino92** [redwoodjs/redwood#4246]
Running `yarn rw setup deploy netlify` inserts invalid configuration into `redwood.toml`.

Before command dev server runs as normal

After command dev server gives following error 

```
web | Error: `apiUrl` is configured incorrectly.
web | It should be an absolute path (thats starts with `/`) or an absolute URI that starts with `http[s]://`
error Command failed with exit code 1.
```

Replicated with fresh project [here](https://github.com/memarino92/deploy-breaks-app-test).

Redwood version: 0.42.1

Fix:

In `redwood.toml` under `[web]`, change the line that says:

`  apiUrl = "./netlify/function"`

to say:

`  apiUrl = "/.netlify/functions"`

**Comment by thedavidprice** [comment]
🤦‍♂️ 

Well, this one is just embarrasing. 😂

Excellent catch @memarino92 We re-architected that command a week ago and apparently dropped and "s".

**Comment by memarino92** [comment]
Happy to help! 😃
