### ISSUE TITLE
Scaffolded components do not handle null DateTimes

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#4264]
When scaffolding a model with a nullable DateTime, such as

```
model Post {
  id          Int       @id @default(autoincrement())
  title       String    @unique
  body        String
  publishedAt DateTime?
  comments    Comment[]
}
```

when rendering the list or view, the null date gets a default value:

![image](https://user-images.githubusercontent.com/1051633/150888389-5b79a1da-9f10-4628-be31-2f0825fef7c7.png)

because

```

const timeTag = (datetime) => {
  return (
    <time dateTime={datetime} title={datetime}>
      {new Date(datetime).toUTCString()}
    </time>
  )
}
```

is not checking for null like:

```
const timeTag = (datetime) => {
  return (
    datetime && (
      <time dateTime={datetime} title={datetime}>
        {new Date(datetime).toUTCString()}
      </time>
    )
  )
}
```

when the data really is null:

```json
{
    "data": {
        "posts": [
            {
                "id": 2,
                "title": "Hello",
                "body": "Happy Tuesday",
                "publishedAt": null,
                "__typename": "Post"
            },
            {
                "id": 1,
                "title": "TK",
                "body": "The Breeders album is 🔥",
                "publishedAt": null,
                "__typename": "Post"
            }
        ]
    }
}
```

**Comment by dthyresson** [comment]
Do people think 

```

const jsonDisplay = (obj) => {
  return (
    <pre>
      <code>{JSON.stringify(obj, null, 2)}</code>
    </pre>
  )
}

const checkboxInputTag = (checked) => {
  return <input type="checkbox" checked={checked} disabled />
}```

should check for null, too?

You can have an optional boolean and optional json

**Comment by cannikin** [comment]
This is in the `index` and/or `show` template? What would the checkbox show for `null`, no checkbox displayed at all? Maybe a subtle, grayed out `null` displayed in there to make it clear that's what's going on? I like that...

**Comment by dthyresson** [comment]
> This is in the `index` and/or `show` template? What would the checkbox show for `null`, no checkbox displayed at all? Maybe a subtle, grayed out `null` displayed in there to make it clear that's what's going on? I like that...

I think a null Boolean value for a checkbox would just be an empty unchecked box -- that could be checked, no

**Comment by cannikin** [comment]
In the editor yes, but I was thinking in the index/show page... since it could be three states null/true/false we should actually show what it is on that page.

If you edit the record, you can only check the box on or off, so I guess at that point leaving the check blank will force it to be false?

**Comment by dthyresson** [comment]
> In the editor yes, but I was thinking in the index/show page... since it could be three states null/true/false we should actually show what it is on that page.
> 

Ah, I see. Right.

> If you edit the record, you can only check the box on or off, so I guess at that point leaving the check blank will force it to be false?


Great point. You'd lose the ability to keep it null.
