### ISSUE TITLE
`rw deploy render api` command results in 2x running processes and > 500MB mem usage

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#4271]
Redwood deployments on Render.com have been failing due to exceeding the maximum allowed memory usage (specific to free and basic plans, which include 512MB of memory). This has likely been an issue from the start but only noticeable after Render created a new free plan offering and capped the mem usage.

After diagnosis, the core issue stems from how `yarn rw deploy render api` runs the commands in sequence, somehow resulting in additional processes. The command `yarn rw serve api` run stand-alone is working correctly and uses about 150-200MB memory, which is expected. (I confirmed this command works via a test deploy to Render using this command directly — the deployment was seamless and successful.)

cc @jtoar @dac09 @cannikin @Tobbe @SEANDOUGHTY @janpio @crcastle

# Diagnosing the problem
- Test Deployment Project branch with `render.yaml` (for reproduction): https://github.com/thedavidprice/redwood-tutorial-test/blob/render-external-postgres/render.yaml
    - note: I am using an external Postgres DB (Heruku) and have added the DATABASE_URL value to the Render Dashboard
    - note: currently the deploy command is `yarn rw serve api` --> check version history to revert and use `yarn rw deploy render api`
- api-server Package: https://github.com/redwoodjs/redwood/tree/main/packages/api-server
- `deploy render` code: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/deploy/render.js
- `rw serve` code: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/serve.js

## Test 1: Deploying without Prisma or data migrations
I deployed to Render.com using the command `yarn rw deploy render api --no-prisma --no-data-migration`, which means that this command will _only_ run the sub-command `yarn rw serve api`. (I confirmed this was the case in the deploy logs.)
- Result --> deployment **failed** due to exceeding memory > 512MB

## Test 2: Local inspection of `yarn  rw serve api`
Locally, I ran the command `yarn rw serve api` and inspected the Node processes.
- 2 processes, using 194MB and 36MB respectively
- ✅ success and normal, expected results

<img width="526" alt="Screen Shot 2022-01-24 at 11 48 17 PM" src="https://user-images.githubusercontent.com/2951/151057093-0fdaef3f-0c03-4246-bd6c-15e563035aac.png">

## Test 3: Local inspection of `yarn rw deploy render api --no-prisma --no-data-migration`
This command will, ultimately, result in _only_ running the command `yarn rw serve api`. Here are the results:
- 4 processes, using 198MB, 191MB, 36MB, and 35MB mem respectively
- ⛔️ Fail due to duplication of processes and exceeding 500MB mem

<img width="487" alt="Screen Shot 2022-01-24 at 11 50 48 PM" src="https://user-images.githubusercontent.com/2951/151057429-a6d8aeac-d036-4931-904c-15ab67704d43.png">

## Test 4: (re)Deploying to render using `yarn rw serve api`
I updated `render.yml` and replaced `yarn rw deploy render api --no-prisma --no-data-migration` with `yarn rw serve api`. Then deployed.
- ✅ success and normal, expected results
- https://tdp-redwood-tutorial-test-web-7b51.onrender.com/

# Next Steps
I need help resolving the "why is this happening?" along with fixing the `deploy render` command. I suspect the issue is related to our use of Execa (and config) here:
https://github.com/redwoodjs/redwood/blob/f4e594d12164878d316aeaa6d2137954be1d6564/packages/cli/src/commands/deploy/render.js#L57-L63

Execa might not be the correct tool given this is a long running process. Other options:
- use Concurrently
- use execa for the Prisma migrate and Data Migrate steps; run the Redwood api-server programatically via [apiCliOptions and apiServerHandler from @redwoodjs/api-server](https://github.com/redwoodjs/redwood/tree/main/packages/api-server/src)

Additionally, we might consider adding an option to `yarn rw serve` to output process heap size

## Goal
We have successfully resolved this issue when we can demonstrate:
1. deployment to Render on free plan using the `yarn rw deploy render api` command
2. _only_ api-server process is running and mem usage is normal (i.e. about 200MB or less)

**Comment by crcastle** [comment]
This is a great write-up @thedavidprice! Thank you for spending the time to do these tests and write it up clearly.

For next steps, my intuition (fwiw) says to explore both 1) running the api server programmatically (like you suggested) but also 2) either using something other than `execa` (is there a way to run the Prisma migrate and Data Migrate steps programmatically?) or figuring out why execa is using so much memory.

Running as few `node` processes as possible seems to have multiple benefits here:
1. Makes memory (and CPU) profiling easier now and in the future. It's easier to attach a debugging client to a single `node --inspect-brk` process than to multiple short-lived `node` processes.
2. It's difficult to control memory use when there are multiple processes. Controlling memory use is necessary in memory-constrained environments like Render (and Heroku, etc) provide. `node` has a flag to help control memory use: [`--max-old-space-size`](https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes). I wasn't able to determine its default value. Maybe it's dynamically determined as the process starts. I believe it used to be 1500MB but I couldn't find anything confirming that for current versions of Node. Regardless, one `node` process doesn't know about a second or more `node` processes, so it's difficult to coordinate memory use between them to keep total memory use below 512MB.

One question: have you seen any evidence that memory use is significantly different when using SQLite vs Postgres?

**Comment by thedavidprice** [comment]
> One question: have you seen any evidence that memory use is significantly different when using SQLite vs Postgres?

Late to the reply here. I have not tested this but we can once the fix is in canary release. My intuition says there will be 1) no difference in baseline memory and 2) minimal difference per DB (because Prisma in both cases). Will be interesting to verify one way or the other.

**Comment by Kombustor** [comment]
I just started using RedwoodJS and have this issue when deploying to Render.com using the free plan. I'm running out of memory and the deploy fails.

render.yaml:
```yaml
startCommand: yarn rw deploy render api
```
![image](https://user-images.githubusercontent.com/4238281/162338521-22d79269-1f15-4c9b-bcf7-607677489cb0.png)

I'm using redwoodjs 1.0.0, so this fix should definitely be included. @thedavidprice

**Comment by thedavidprice** [comment]
@Kombustor yes, we recently discovered this was popping up again, especially on the initial deploy where services are created. Note: this fix has been applied as of v0.44 — we've (I've) put a ton of time into it 😞 

I am continuing to work with the Render team and rely on their collaboration to improve the situation. It's very challenging to resolve as there's no way to observe processes within the build and start context.

Workarounds:
- bump up temporarily to the 1GB plan to get going
- do not run Prisma Migrate or Data Migrate during build step: update start command to be
```
yarn rw deploy render api --no-prisma --no-data-migrate
```

**Comment by Tobbe** [comment]
FYI: I tried running on their (paid) 512MB plan and noticed that even if/when I could get things deployed it would get killed after running for a while and getting some traffic. Should still be fine just to test the waters, but do know you'll likely need to go with their 1gb plan if you plan on getting some proper traffic.

![image](https://user-images.githubusercontent.com/30793/162515231-752d9cd2-31a9-4d92-a037-b7cd6a51a0fd.png)

**Comment by JustinAimiable** [comment]
Is this still an issue? We've had to skip the dataMigrate step recently to unblock deploys after getting OOM-killed during render deploy.
