### ISSUE TITLE
Provide a bit of information how to use Redwood as backend/api only

### ISSUE THREAD

**Issue by marceloverdijk** [redwoodjs/redwood#428]
See https://twitter.com/marceloverdijk/status/1246535967487426570?s=20

- Just delete the `web` folder?
- Provide a flag in `yarn create redwood-app`?

**Comment by thedavidprice** [comment]
Hi @marceloverdijk There’s some movement on this topic in motion 🚀 
- See[ this forum conversation](https://community.redwoodjs.com/t/deploying-to-aws-lambda/316), which is also a great place to jump in with current “how to” questions
- And @Jaikant opened [this Issue](https://github.com/redwoodjs/redwood/issues/431) #431 with a feature request and example process and config how he got it to work

Closing this out. And hope to see you in one of the other threads!
