### ISSUE TITLE
auth: Update Nhost Provider to version 2.0

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#4357]
Nhost recently announced v2 of their platform which has some new auth; see: https://nhost.io/blog/nhost-v2-the-beginning-of-something-big

> Hasura Backend Plus is replaced by Hasura Auth and Hasura Storage. The new authentication service is very similar to Hasura Backend Plus with one big difference; the users table has been moved to the auth schema and merged with the accounts table. This change was necessary to more easily release new features to Hasura Auth and for customers to track migrations separately from Hasura Auth.

This issue is to update:

* Nhost's auth setup to the latest provider
* Update docs
* Update Redwood Auth Playground (when complete) see [issue in that repo](https://github.com/redwoodjs/playground-auth/issues/95)

cc' @nunopato

**Comment by nunopato** [comment]
@dthyresson thanks for putting this up, I will start the work here tomorrow.

**Comment by jtoar** [comment]
Done in https://github.com/redwoodjs/redwood/pull/4770.
