### ISSUE TITLE
Failed db up does NOT fail Netlify build

### ISSUE THREAD

**Issue by chris-hailstorm** [redwoodjs/redwood#437]
ENVIRONMENT

v0.4.0

OBSERVATION

In `netlify.toml`, using the usual command: `yarn rw db up --no-db-client && yarn rw build`.

The build failed (because I messed up my `DATABASE_URL` env var) but the build continues:

    12:29:02 PM: $ /opt/build/repo/node_modules/.bin/rw db up --no-db-client
    12:29:02 PM: Migrate database up... [started]
    12:29:02 PM: $ /opt/build/repo/node_modules/.bin/prisma2 migrate up --experimental --create-db
    12:29:02 PM: Error: Unknown database type
    12:29:02 PM: error Command failed with exit code 1.
    12:29:02 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    12:29:02 PM: Migrate database up... [failed]
    12:29:02 PM: → Command failed with exit code 1: yarn prisma2 migrate up --experimental --create-db
    12:29:02 PM: Command failed with exit code 1: yarn prisma2 migrate up --experimental --create-db
    ...
    12:29:02 PM: yarn run v1.17.0
    12:29:02 PM: $ /opt/build/repo/node_modules/.bin/rw build
    12:29:02 PM: Generating the Prisma client... [started]
    ...
    12:29:35 PM: ​
    12:29:35 PM: ┌─────────────────────────────┐
    12:29:35 PM: │   Netlify Build Complete    │
    12:29:35 PM: └─────────────────────────────┘
    ...
    12:29:54 PM: Site is live

IMPACT

If auto deployment is used, code that's out of synch with its DB can be deployed.  Builds flagged as successful are only *potentially* successful; someone has to review the build log.

SUGGESTION

`yarn rw` should not consume errors from lower-level tools.

Any failure in a called utility should be allowed to bubble up and fail the build.

**Comment by thedavidprice** [comment]
Roger this — definitely been encountering this on our end. I’ll put this in front of Netlify team now for advice on best way to proceed. Something I don’t understand, for example, is how `error Command failed with exit code 1.` is in the output but not passed/consumed by the Netlify build process itself.

Will loop back once I learn more.
