### ISSUE TITLE
Service Validations should format error messages for form helpers

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#4371]
Not sure how I missed this, but I realized as I'm going back through the tutorial for 1.0 that the error messages raised by Service Validations aren't quite the right format for Form Helpers to parse them apart and highlight the fields that are invalid.

When we setup validation from scratch in the tutorial we raise this error:

```javascript
throw new UserInputError("Can't create new contact", {
  messages: {
    email: ['is not formatted like an email address'],
  },
})
```

Which, when using form helpers `<FormError>`  and `<FieldError>` results in:

![image](https://user-images.githubusercontent.com/300/152442561-108cc8e8-3c2a-45c1-bb7e-caffd8c466de.png)

But replacing the custom validation with Service Validations like:

```javascript
validate(input.email, 'Email', {
  email: true,
})
```

results in this:

![image](https://user-images.githubusercontent.com/300/152442488-34481044-d5c2-4631-82f6-508407a95331.png)

Ideally it would highlight the errored field, in addition to providing the blanket message the top.

I should be able to add this without too much fuss, but may be a breaking change for error handling in user apps if they are doing something custom with errors outside of the form helpers.

**Comment by dthyresson** [comment]
Confirmed ... 

```ts
import { UserInputError } from '@redwoodjs/graphql-server'
import { db } from 'src/lib/db'

const validate = (input) => {
  if (input.email && !input.email.match(/[^@]+@[^.]+\..+/)) {
    throw new UserInputError("Can't create new contact",{
      messages: {
        email: ['is not formatted like an email address'],
      },
    })
  }
}

export const contacts = () => {
  return db.contact.findMany()
}

export const createContact = ({ input }) => {
  validate(input)
  return db.contact.create({ data: input })
}

```

And no client side form validation results in:

import { UserInputError } from '@redwoodjs/graphql-server'
import { db } from 'src/lib/db'

const validate = (input) => {
  if (input.email && !input.email.match(/[^@]+@[^.]+\..+/)) {
    throw new UserInputError("Can't create new contact",{
      messages: {
        email: ['is not formatted like an email address'],
      },
    })
  }
}

export const contacts = () => {
  return db.contact.findMany()
}

export const createContact = ({ input }) => {
  validate(input)
  return db.contact.create({ data: input })
}

and the graphql response is:

```json
{
    "errors": [
        {
            "message": "Can't create new contact",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "createContact"
            ],
            "extensions": {
                "code": "BAD_USER_INPUT",
                "properties": {
                    "messages": {
                        "email": [
                            "is not formatted like an email address"
                        ]
                    }
                }
            }
        }
    ],
    "data": {
        "createContact": null
    }
}
```

Where the extension adds in the field level info.

And with service validations:


```ts
import { validate } from '@redwoodjs/api'

export const createContact = ({ input }) => {
  validate(input.email, 'Email', {
    email: true,
  })
  return db.contact.create({ data: input })
}
```

![image](https://user-images.githubusercontent.com/1051633/154522703-851b8c4d-1d09-411e-907f-4050c089ad21.png)

and the response has:

```json
{
    "errors": [
        {
            "message": "Email must be formatted like an email address",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "createContact"
            ]
        }
    ],
    "data": {
        "createContact": null
    }
}
```

**Comment by dthyresson** [comment]
Oh, all ServiceValidationError errors simply are an `Error`:

```
export class RedwoodError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'RedwoodError'
  }
}

//...

export class ServiceValidationError extends RedwoodError {
  constructor(message: string, substitutions = {}) {
    let errorMessage = message

    // replace instances of a string like `{max}` with any substituted values
    for (const [key, value] of Object.entries(substitutions)) {
      errorMessage = errorMessage.replaceAll(`\${${key}}`, String(value))
    }

    super(errorMessage)
    this.name = 'ServiceValidationError'
  }
}

//...

export class EmailValidationError extends ServiceValidationError {
  constructor(
    name: string,
    message = '${name} must be formatted like an email address',
    substitutions = {}
  ) {
    super(message, Object.assign(substitutions, { name }))
    this.name = 'EmailValidationError'
  }
}
```

So it won't have any of those Apollo specific error messages or info.


And the mask error imports this generic RedwoodError in the masked formatting...

```
export const formatError: FormatErrorHandler = (err: any, message: string) => {
  const allowErrors = [EnvelopError, RedwoodError]
```

So it allows it to pass through.

**Comment by cannikin** [comment]
Maybe `ServiceValidationError` accepts the field name and the message as two separate parameters and then formats it in the style that the form error handling likes:

```
{"messages": {
    "email": [
        "is not formatted like an email address"
    ]
}
```

Rather than just outputting a single error string like it does now? Unfortunately I don't think we can just raise `UserInputError` because you could have one service calling another and that may have no thing to do with user input. What's the next level up from `UserInputError`? Maybe `ServiceValidationError` should extend from that?

We could come at it from the other direction and have the error handling code in the form helpers look for a different error object structure instead of/in addition to the `hasNetworkError` and `hasGraphQLError` checks that it does now. We could format the error however we want as long as that code new how to interpret the error and turn it into the field and message for highlighting in the form inputs.

**Comment by dthyresson** [comment]
> Maybe `ServiceValidationError` accepts the field name and the message a

I'll check. The issue is that the Form handling/error messaging relies on Apollo Server specific error handling extensions (which are not standard GraphQL). So we have a little mismatch between the message content and the rendering.

**Comment by dthyresson** [comment]
Also, the api `RedwoodError` is a little different that  graphql-server's:

```ts
import { EnvelopError } from '@envelop/core'

export class RedwoodGraphQLError extends EnvelopError {
  constructor(message: string, extensions?: Record<string, any>) {
    super(message, extensions)
  }
}
```
 Which does allow those extensions -- since we wanted to be compatible for the time being with the Apollo flavor errors.

Ultimately, we'd want errors as part of the payload as seen here (for v2) https://blog.logrocket.com/handling-graphql-errors-like-a-champ-with-unions-and-interfaces/.

but, maybe the formatter can convert or transform the api `RedwoodError` to a `RedwoodGraphQLError` given some extra bits of info (like the field name and/optional message).

**Comment by dthyresson** [comment]
Extending the api `RedwoodError` has promise:


```ts
export class RedwoodError extends Error {
  extensions: Record<string, any> | undefined
  constructor(message: string, extensions?: Record<string, any>) {
    super(message)
    this.name = 'RedwoodError'
    this.extensions = extensions
  }
}
```

and then 


```ts
export class ServiceValidationError extends RedwoodError {
  constructor(
    message: string,
    substitutions = {},
    extensions?: Record<string, any>
  ) {
    let errorMessage = message

    // replace instances of a string like `{max}` with any substituted values
    for (const [key, value] of Object.entries(substitutions)) {
      errorMessage = errorMessage.replaceAll(`\${${key}}`, String(value))
    }

    super(errorMessage, extensions)
    this.name = 'ServiceValidationError'
  }
}
```

and then in each specific type of service error:


```ts
export class EmailValidationError extends ServiceValidationError {
  constructor(
    name: string,
    message = '${name} must be formatted like an email address',
    substitutions = {}
  ) {
    super(message, Object.assign(substitutions, { name }))
    this.name = 'EmailValidationError'
    this.extensions = {
      code: 'BAD_USER_INPUT',
      properties: {
        messages: {
          email: ['is not formatted like an email address'],
        },
      },
    }
  }
}
```

Results in:

![image](https://user-images.githubusercontent.com/1051633/154690774-e531798d-f88c-4cff-84e7-9ff69bef7c50.png)


This is "better" but a little repetitive.

The extra "extensions" option on RedwoodError seems ok, but probably a better type on `ServiceValidationError` that only allows certain codes is needed.

And of course, the key here of `email` is hardcoded which is a problem. But, maybe that is just the "name"?

**Comment by dthyresson** [comment]
Hmmm ... but then the service is more tied to the form element:

```ts

export const createContact = ({ input }) => {
  validate(input.email, 'Email', {
    email: true,
    fieldName: 'email_4',
  })
  return db.contact.create({ data: input })
}
```

And that's not great. And the key cannot be derived from the label to show because the human text may not be the input name.

Yeah, gotta think on this more.

**Comment by cannikin** [comment]
Depending on how big this change is I may need to update RedwoodRecord as well...it parses apart the errors from Service Validations to use in its own internal error handling:

```
export default class User extends RedwoodRecord {
  static validates = {
    email: { presence: true, email: true },
    username: { length: { min: 2, max: 50 } }
  }
}

const user = User.build({ username: 'r' })
await user.save() // => false
user.errors.email = ['must be present']
user.errors.username = ['must be at least 2 characters']
user.email = 'rob@redwoodjs.com'
user.username = 'rob'
await user.save()
```

**Comment by dthyresson** [comment]
Ok, so maybe we CTM this and decide if we want to support for v1 or not -- given v2's GraphQL error rework that will likely happen. @thedavidprice I just need a decision.

**Comment by thedavidprice** [comment]
@dthyresson Added to discussion topics. Understood ✅

**Comment by cannikin** [comment]
Pre-discussion context: this came up as I was re-working the tutorial for 1.0 and was going to introduce Service Validations, but couldn't because they don't show the magical error messages in the forms. For now I stuck with the original solution (throwing `UserInputError` manually) but if we want the tutorial to be the ultimate introduction to the framework then I think we should get this working properly for 1.0, even if that means throwing that weird Apollo-formatted error for now (which we then clean up in 2.0).

**Comment by Tobbe** [comment]
Tangent: https://github.com/redwoodjs/redwood/issues/4547
