### ISSUE TITLE
Prisma v3.9.1 Bug: Generated resolver causes error

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#4396]
## Workaround
This is an upstream issue with Prisma v3.9.1. The currently workaround is to use Redwood v0.44.1, which has downgraded Prisma to v3.8.1

---
Using the default resolvers generated by scaffolding and the sdl generator I'm getting this error

![image](https://user-images.githubusercontent.com/30793/152685842-a518c9ac-d555-4225-a319-17b3bb3eeb85.png)

Repro:
```
yarn create redwood-app my-app
cd my-app
```
Replace the content of `schema.prisma` with this
```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = "native"
}

model Product {
  id                Int                 @id @default(autoincrement())
  createdAt         DateTime            @default(now())
  updatedAt         DateTime            @default(now()) @updatedAt
  name              String
  CategoryToProduct CategoryToProduct[]
}

model Category {
  id                 Int                 @id @default(autoincrement())
  name               String
  parent             Int?
  parentCategory     Category?           @relation("CategoryParent", fields: [parent], references: [id])
  childrenCategories Category[]          @relation("CategoryParent")
  CategoryToProduct  CategoryToProduct[]
}

model CategoryToProduct {
  id         Int      @id @default(autoincrement())
  product    Product  @relation(fields: [productId], references: [id])
  productId  Int
  category   Category @relation(fields: [categoryId], references: [id])
  categoryId Int

  @@unique([productId, categoryId])
}
```
```
yarn rw prisma migrate dev --name init
yarn rw g scaffold product
yarn rw g scaffold category
yarn rw g sdl categoryToProduct
```
Now launch the dev server and go create a new product. Maybe a Barcode Scanner
![image](https://user-images.githubusercontent.com/30793/152685940-8d30fc43-90f0-4e8c-bde2-c38ee1896cbf.png)
You're taken to a list of your products
![image](https://user-images.githubusercontent.com/30793/152685979-59bf1d20-62cd-4a21-9fe2-7f4f0278d03e.png)

Now go edit the `ProductsCell` code. Make the gql query also include the CategoryToProduct relation, like this
```gql
query FindProducts {
  products {
    id
    createdAt
    updatedAt
    name
    CategoryToProduct {
      categoryId
    }
  }
}
```
As soon as you save your changes you should see an error in the console as it rebuilds.
```
api | Invalid `db.product.findUnique()` invocation in
api | /Users/tobbe/tmp/mnresolver/api/src/services/products/products.js:34:55
api | 
api |   31 
api |   32 export const Product = {
api |   33   CategoryToProduct: (_obj, { root }) =>
api | → 34     db.product.findUnique({
api |            where: {
api |              id: 3
api |            },
api |            select: {
api |              categoryToProduct: true,
api |              ~~~~~~~~~~~~~~~~~
api |          ?   id?: true,
api |          ?   createdAt?: true,
api |          ?   updatedAt?: true,
api |          ?   name?: true,
api |          ?   CategoryToProduct?: true,
api |          ?   _count?: true
api |            }
api |          })
api | 
api | 
api | Unknown field `categoryToProduct` for select statement on model Product. Available options are listed in green. Did you mean `CategoryToProduct`?
```
It tries to include `categoryToProduct`, but there isn't anything named that. Should be with a capital `C`. The code that's executing is the resolver for `CategoryToProduct` at the end of `products.js`:

```js
export const Product = {
  CategoryToProduct: (_obj, { root }) =>
    db.product.findUnique({ where: { id: root.id } }).CategoryToProduct(),
}
```

**Comment by dthyresson** [comment]
Oh, I always use lowercase and plural fields for relations so that's why I haven't seen this I think:

`CategoryToProduct  CategoryToProduct[]`

vs

`categoryToProduct  CategoryToProduct[]`

As I guess then the crud resolvers camelcase the field?

**Comment by Tobbe** [comment]
I tried renaming my relation fields to be camelCase:

```prisma
model Product {
  id                Int                 @id @default(autoincrement())
  createdAt         DateTime            @default(now())
  updatedAt         DateTime            @default(now()) @updatedAt
  name              String
  categoryToProduct CategoryToProduct[]
}

model Category {
  id                 Int                 @id @default(autoincrement())
  name               String
  parent             Int?
  parentCategory     Category?           @relation("CategoryParent", fields: [parent], references: [id])
  childrenCategories Category[]          @relation("CategoryParent")
  categoryToProduct  CategoryToProduct[]
}
```

And ran the generators again, so now I have this in `products.js`
```
export const Product = {
  categoryToProduct: (_obj, { root }) =>
    db.product.findUnique({ where: { id: root.id } }).categoryToProduct(),
}
```

This seems to work! So something is not handling that initial uppercase letter properly

**Comment by dthyresson** [comment]
> This seems to work! So something is not handling that initial uppercase letter properly

I might be

https://github.com/redwoodjs/redwood/blob/529953b042e928cbe38652e0fd3455abbfb8bc08/packages/cli/src/commands/generate/service/templates/service.ts.template#L44

That formats the `relation` as camel case?

**Comment by Tobbe** [comment]
No, it works as expected. It matches what's in my `schema.prisma` file

**Comment by Tobbe** [comment]
If I want to keep my uppercase field names in my models I can make this change to make it work:
```diff
diff --git a/api/src/services/products/products.js b/api/src/services/products/products.js
index 2611986..3b4bc00 100644
--- a/api/src/services/products/products.js
+++ b/api/src/services/products/products.js
@@ -30,6 +30,12 @@ export const deleteProduct = ({ id }) => {
 }
 
 export const Product = {
-  CategoryToProduct: (_obj, { root }) =>
-    db.product.findUnique({ where: { id: root.id } }).CategoryToProduct(),
+  CategoryToProduct: async (_obj, { root }) => {
+    const product = await db.product.findUnique({
+      where: { id: root.id },
+      include: { CategoryToProduct: true },
+    })
+
+    return product.CategoryToProduct
+  },
 }
 ```

Apart from being a bit more verbose, are there any other downsides to this way of doing it? Should I update the generators to output this code instead?

**Comment by dthyresson** [comment]
> are there any other downsides to

It will "eager load" the `CategoryToProduct` items via the `include` which isn't a bad thing IMO.

I say try it and we can test the PR branch out.

@dac09 What do you think? We looked at resolvers a little last week.

**Comment by Tobbe** [comment]
I just tested on RW 0.40.0 and it works with the generated code. So something has changed that breaks this.
On RW 0.40.0 this works

```js
export const Product = {
  categoryToProduct: (_obj, { root }) =>
    db.product.findUnique({ where: { id: root.id } }).CategoryToProduct(),
}
```

**Comment by dthyresson** [comment]
Maybe it’s a newer Prisma client? 

I’ll try to check the release notes.

**Comment by Tobbe** [comment]
Did more testing with different version to narrow it down.
It broke going from .43 -> .44

**Comment by Tobbe** [comment]
This fixes it on RW .44

package.json:
```
  "resolutions": {
    "**/prisma": "3.8.1",
    "**/@prisma/sdk": "3.8.1",
    "**/@prisma/client": "3.8.1"
  },
```

**Comment by Tobbe** [comment]
Found a related issue over at Prisma's GitHub: https://github.com/prisma/prisma/issues/11641

**Comment by thedavidprice** [comment]
## Update
We have reverted the Prisma version to 3.8.1 in release patch v0.44.1

Awaiting a fix for the upstream bug (below) before upgrading Prisma in `main`:
- https://github.com/prisma/prisma/issues/11641

**Comment by Tobbe** [comment]
Prisma has fixed their bug now, so I created a PR to bring in their latest (fixed) version
https://github.com/redwoodjs/redwood/pull/4439
