### ISSUE TITLE
Remove WEBHOOK_SECRET from .env.defaults template

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#4399]
In a new Redwood app, the `.env.defaults` template contains a commented-out ENV var `WEBHOOK_SECRET`. This should go in the `.env` template since that file is ignored in `.gitignore`.

The comment at the top of `.env.defaults` states that it this file *can* be checked into your version control and so should contain no sensitive data.

**Comment by wiksien** [comment]
I will fix that.
