### ISSUE TITLE
Misleading JSON error when running dev server and api server reloads

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#4410]
When you are running the dev server, and re-generate the api say my scaffolding a new model or even re-scaffolding like

`yarn rw g scaffold admin/spot --force`

Apollo Client can respond with an error like:

![image](https://user-images.githubusercontent.com/1051633/152845751-98b9d22b-88bc-4e5c-b521-c2df37e34cc4.png)

Because the dev server is ready before the api server is, and the connection is a 504

```
Summary
URL: http://localhost:8910/.redwood/functions/graphql
Status: 504 Gateway Timeout
Source: Network
Address: 127.0.0.1:8910
Initiator: 
createHttpLink.js:96
```

Perhaps `createHttpLink` can handle the 504 better?

**Comment by dac09** [comment]
i think you might be better off modifying the dev server to return an error block similar to graphql resposes using the `byPass` property in webpack dev server proxy. Not tried it myself though!

**Comment by dthyresson** [comment]
@dac09 Good idea. Some Googling found this approach:

```
        onProxyRes: function (proxyRes, req, res) {
          console.log(proxyRes.statusCode)
        },
        onError: function (err, req, res) {
          console.log(`req.body: ${req.body}`) // here it returned undefined
          console.log(`err.code: ${err.code}`)
          if (err.code === 'ECONNRESET') {
            res.writeHead(204, { 'Content-Type': 'application/json' })
            res.end()
          }
        },
```

And this seems to prevent the JSON error ... but the cell is stuck in a `Loading` state.

Will experiment with different status codes returned.

**Comment by dthyresson** [comment]
So also needs `ECONNREFUSED ` and then by returning a response


```js
        onError: function (err, req, res) {
          console.log(`req.body: ${req.body}`) // here it returned undefined
          console.log(`err.code: ${err.code}`)
          if (err.code === 'ECONNRESET' || err.code === 'ECONNREFUSED') {
            const msg = { error: { message: 'foo' } }
            console.log(`err msg: ${msg}`)
            // res.writeHead(204, { 'Content-Type': 'application/json' })
            res.writeHead(200, { 'Content-Type': 'application/json' })
            res.write(JSON.stringify(msg))
            res.end()
          }
        },
``

gave me

<img width="511" alt="image" src="https://user-images.githubusercontent.com/1051633/152998434-3d001d2a-02c1-4e33-aedf-546e893d5f26.png">

So, definitely on the right track here.

**Comment by dthyresson** [comment]
Or returning `500`

```js
        if (err.code === 'ECONNRESET' || err.code === 'ECONNREFUSED') {
            const msg = { error: { message: 'foo' } }
            console.log(`err msg: ${msg}`)
            // res.writeHead(204, { 'Content-Type': 'application/json' })
            res.writeHead(500, { 'Content-Type': 'application/json' })
            res.write(JSON.stringify(msg))
            res.end()
          }
```

<img width="474" alt="image" src="https://user-images.githubusercontent.com/1051633/152998964-0323e6a1-fc49-4330-ad3a-eeb82ace04e5.png">

**Comment by dthyresson** [comment]
Aha!!

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1051633/153000037-aaca0442-bb95-45cd-857f-2dff88068dcc.png">

```js
        onError: function (err, req, res) {
          if (err.code === 'ECONNRESET' || err.code === 'ECONNREFUSED') {
            const msg = {
              errors: [
                {
                  message: 'API server not ready. Try again.',
                },
              ],
            }
            res.writeHead(200, { 'Content-Type': 'application/json' })
            res.write(JSON.stringify(msg))
            res.end()
          }
        },
```

**Comment by dthyresson** [comment]
Perhaps a status code of 205 https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/205

> The HTTP 205 Reset Content response status tells the client to reset the document view, so for example to clear the content of a form, reset a canvas state, or to refresh the UI.

refresh the UI ?

**Comment by dthyresson** [comment]
I found that the 503 status code with a retry in header time made the most sense -- and worked for CI (since this was not a 2xx code that would pass the wait until).
