### ISSUE TITLE
[priority] API GraphQL Server 404 Error on Windows with v0.44.1 "Unexpected token N in JSON"

### ISSUE THREAD

**Issue by leopen-hu** [redwoodjs/redwood#4424]
_Edit to add reproduction steps:_
```
git clone https://github.com/redwoodjs/redwood-tutorial
cd redwood-tutorial
yarn install
yarn rw prisma migrate dev
yarn rw dev
```

A tab will open in your browser on http://localhost:8910 showing this error

![image](https://user-images.githubusercontent.com/16874003/153111118-7d34eedd-7cc9-4bae-b6e0-1beb80a462af.png)

Original post below

---

when i try this framework as document described in Quick Start，it runs everything well，but just can‘t load any data and get a error for JSON.

i checked the network and find a 404 error for graphQL api.

- web page error:

![image](https://user-images.githubusercontent.com/16874003/153111118-7d34eedd-7cc9-4bae-b6e0-1beb80a462af.png)

- network error:

![image](https://user-images.githubusercontent.com/16874003/153111224-1625f64f-10d5-4d39-be1c-7174b2a2f1d1.png)
![image](https://user-images.githubusercontent.com/16874003/153111291-d3b10f38-9851-4e80-b5e0-08ce9b4b6293.png)

- cli info:

![image](https://user-images.githubusercontent.com/16874003/153111337-5260911d-f8d4-48ab-a64d-1df665e613f9.png)

**Comment by leopen-hu** [comment]
here is my env info:

![image](https://user-images.githubusercontent.com/16874003/153111549-5e0b9f70-eba2-4e9a-ae00-77173a6ae0e0.png)

**Comment by leopen-hu** [comment]
i just tried the cloned project named redwoodblog, but still run with this error, so i think the port maybe blocked.

i changed the port but the error still exist.

![image](https://user-images.githubusercontent.com/16874003/153112409-de0b4a06-a024-45aa-925f-d66a3ced164a.png)

**Comment by leopen-hu** [comment]
tried the url in browser

![image](https://user-images.githubusercontent.com/16874003/153112706-95e15056-6c5f-4a66-8147-d41e3d6ecd31.png)
![image](https://user-images.githubusercontent.com/16874003/153112737-c6fb372c-dcc8-4d0e-9aa2-071b806e0f30.png)
![image](https://user-images.githubusercontent.com/16874003/153112782-a8c302e5-21ff-4f50-af5a-bc0c9290f81c.png)

**Comment by thedavidprice** [comment]
Thanks for reporting this @leopen-hu Looking at our redwoodjs.com/docs/quick-start now, I realize we don't even mention needing to run `yarn rw dev` 🤦‍♂️ Glad you figured that out at least.

Your error indicates an issue with the local DB, e.g. the tables don't exist so the Prisma queries aren't working. Can you confirm you ran?
- `yarn rw prisma migrate dev`

This will apply the schema.prisma to your local DB.

It might also be helpful to use something like [TablesPlus](https://tableplus.com) to examine the local DB and confirm the schema has been applied correctly.

**Comment by leopen-hu** [comment]
It seems not the reason.
I am sure I had migrated the db:
- The `dev.db` file can be found in "/api/db".

![image](https://user-images.githubusercontent.com/16874003/153331270-62fd0405-0398-4722-b266-c7a344288b6f.png)

- Table `UserExample` can be seen by Prisma Studio. Here is the result for `yarn rw prisma studio`:

![image](https://user-images.githubusercontent.com/16874003/153331169-c801258a-5419-4cd5-9283-a6901670543a.png)

**Comment by Tobbe** [comment]
@leopen-hu I'm a little confused about your ports and urls.

Normally we run the web on 8910 and the server on 8911.
That means you can access the graphql playground on either:
http://localhost:8910/.redwood/functions/graphql
or
http://localhost:8911/graphql

When accessing it on the web port (so, on http://localhost:8910/.redwood/functions/graphql) you need to pay attention to the server url field that (at least for me) get automatically populated with http://localhost:8910/graphql, which is wrong. It has to be either http://localhost:8910/.redwood/functions/graphql or http://localhost:8911/graphql

**Comment by leopen-hu** [comment]
@Tobbe yeah, I am also confused. 
To avoid making mistakes by myself, I tried another example repo `redwood-tutorial` metioned in `Tutorial>Prerequisites>Using the Example Repo`.
I don't write anything and just run cli commands as document says but get the same error.
Perhaps something wrong with my env, but I have no idea.
can you run this repo well?

**Comment by leopen-hu** [comment]
@Tobbe so sad, can't.

![image](https://user-images.githubusercontent.com/16874003/153426028-c24b0318-cbe0-42a1-bc4a-35e1e944b08c.png)

**Comment by Tobbe** [comment]
And it works fine on my Mac.

(And it also took like 10 minutes just to get up and running on my Windows machine compared to like 2, max, on my Mac 😭 )

**Comment by Tobbe** [comment]
Look at this super weird output I get when running `yarn rw dev api`
![image](https://user-images.githubusercontent.com/30793/153433586-6b49b85a-b3a1-4297-a4a4-f25a7cda862d.png)

**Comment by leopen-hu** [comment]
@thedavidprice Yes, my project works fine now by running `yarn rw upgrade`. Thanks!!!

**Comment by thedavidprice** [comment]
Great! And huge Thank You as well for taking the time to report the error.

**Comment by josemasar** [comment]
@leopen-hu , do you use redwood dbAuth in your project?

@thedavidprice, upgrading to v0.45 did not resolve my issue when trying to sign up/login an user. See the thread I opened in the forum:  [Failed to load functions/auth & graphql since upgrade to 0.44](https://community.redwoodjs.com/t/failed-to-load-functions-auth-graphql-since-upgrade-to-0-44/2749/3).

Redwood dbAuth is looking for the auth function in `http://localhost:8910/undefined/auth`.
