### ISSUE TITLE
MSW isn't enabled in Storybook on Windows machines

### ISSUE THREAD

**Issue by realStandal** [redwoodjs/redwood#4450]
I'm relocating this issue from the [`redwood-tutorial` repository](https://github.com/redwoodjs/redwood-tutorial/issues/19).

In short:

> It seems the [MSW](https://mswjs.io/) isn't getting started when Storybook is, so queries and mutations aren't mocked.

@thedavidprice remarked that the issue isn't occurring on his MacOS machine. I use strictly Windows and am encountering the issue in the tutorial app and from within a fresh, `create-redwood-app` app.

---

### Using the tutorial app

1 - `git clone https://github.com/redwoodjs/redwood-tutorial.git`
2 - `cd redwood-tutorial`
3 - `yarn install`
4 - `yarn rw sb`
5 - Open your browser's developer tools -> console, notice the lack of a "[MSW] Mocking enabled." message.

### Using @Kritsatorn's repository where the issue was originally found

1 - `git clone https://github.com/Kritsatorn/RedwoodBug-1.git`
2 - `cd RedwoodBug-1`
3 - `yarn install`
4 - `yarn rw sb`
5 - Open your browser's developer tools -> console, notice the lack of a "[MSW] Mocking enabled." message.

### Using `create-redwood-app`

1 - `yarn create redwood-app windows-storybook-msw`
2 - `cd windows-storybook-msw`
3 - Create a [bone-simple story](https://gist.github.com/realStandal/56657b74f1ad1db3008ef2a79ceff293), as Storybook requires something.
4 - `yarn rw sb`
5 - Open your browser's developer tools -> console, notice the lack of a "[MSW] Mocking enabled." message.

## System Info

![image](https://user-images.githubusercontent.com/25166787/153658107-732b4e23-72a4-417f-9eb1-8f693e4f0241.png)

**Comment by thedavidprice** [comment]
Related code for Storybook command:
https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/storybook.js

**Comment by thedavidprice** [comment]
@realStandal Thank you for reporting this. If you're available, it would be helpful to know if the MSW process command used in [cli/src/commands/storybook.js](https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/storybook.js) works stand alone on your machine.

**Comment by realStandal** [comment]
> @realStandal Thank you for reporting this. If you're available, it would be helpful to know if the MSW process command used in [cli/src/commands/storybook.js](https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/storybook.js) works stand alone on your machine.

<details>
<summary>When I run it manually</summary>

![image](https://user-images.githubusercontent.com/25166787/153665545-106678e6-1608-4cf1-a9eb-0a20df2128b1.png)
</details>

<details>
<summary>Via the Storybook CLI command:</summary>

![image](https://user-images.githubusercontent.com/25166787/153665845-b44ac03d-56a9-4408-bdd1-f7f686c846fd.png)
</details>

---

What does seem to be different is from where Storybook is serving the static files:

<details>
<summary>The app created in the create-redwood-app reproduction</summary>

`info => Serving static files from ./.\public at /`
</details>

<details>
<summary>A Redwood app where mocking is enabled</summary>

`info => Serving static files from C:\Users\ryans\OneDrive\Desktop\LockTech\lab\palletized-chakra\web\public at /`
</details>

**Comment by simoncrypta** [comment]
This feel like a problem with Posix Path again. 
I know @Tobbe had fixes many of them, I will take a look and compare similar fix.

**Comment by thedavidprice** [comment]
Just want to make sure we're on the same page with what's expected here. I understand the "MSC Mocking enabled" isn't displayed, but what is the resulting behavior change relative to the exception?

I'm using the Redwood Tutorial repo and started `yarn rw sb` successfully. This is the output I see:
<img width="1032" alt="Screen Shot 2022-02-11 at 2 48 03 PM" src="https://user-images.githubusercontent.com/2951/153681168-e8c57d39-5082-40a7-8daf-10e4a3e6d390.png">

And here's the working components in SB on Chrome:
https://user-images.githubusercontent.com/2951/153681249-f1506ef0-c3a2-46ec-973c-a8fda9aac8c1.mp4

And the console for Chrome:
<img width="778" alt="Screen Shot 2022-02-11 at 2 51 14 PM" src="https://user-images.githubusercontent.com/2951/153681353-c9c51292-321b-462b-baec-4f277aed9560.png">

**Comment by realStandal** [comment]
> but what is the resulting behavior change relative to the exception?

GraphQL requests, be they queries or mutations, are not being mocked.

[Here is the same video demonstration as I see it](https://user-images.githubusercontent.com/25166787/153691065-b20b4fbc-23a7-40e7-8884-608ffe9ebc25.gif), using the latest version of the tutorial repo. The issue is in the `ArticlePages` story - all requests hang in the "loading..." state. I wasn't aware requests were automatically mocked (as in your video), but even explicitly mocking the query (`mockGraphQLQuery(...)`) hangs.

It's interesting/unfortunate the "Serving static files from..." is the same for you, yet everything still works :/

**Comment by Kritsatorn** [comment]
I am using MacOS on intel
Steps to reproduce

git clone https://github.com/redwoodjs/redwood-tutorial.git[](https://user-images.githubusercontent.com/32409782/153691903-3baf35ff-5cbd-4ef9-88ce-fea385c553c4.png)
cd redwood-tutorial
yarn install
yarn rw sb
yarn rw g cell comments
Add the CommentsCell to Article Component
the result is
Screen Shot 2565-02-12 at 08 56 45

and It is not what the tutorial said, It should be using mock data of that cell on storybook but It's always getting loading.

**Comment by realStandal** [comment]
...a few versions later and it appears that MSW is enabled:

![image](https://user-images.githubusercontent.com/25166787/157555440-89dc2719-e1ae-4e25-9194-81d10e7270f0.png)

Going to close this and hope it was a weird fluke with mine and @Kritsatorn's machines 🤷
