### ISSUE TITLE
Add SESSION_SECRET to 'Deployment' section of tutorial docs

### ISSUE THREAD

**Issue by aemann2** [redwoodjs/redwood#4477]
I just went through the tutorial documentation, and I noticed that the [deployment section](https://learn.redwoodjs.com/docs/tutorial/deployment) doesn't say to add the SESSION_SECRET variable to Netlify's Environment Variables.

Deploying the app without that variable in place crashed my app and generated some cryptic type errors. I was able to figure out the problem by looking at the Network logs, but including this in the docs would save new users some trouble.

**Comment by thedavidprice** [comment]
Hi @aemann2 Thanks for reporting this.

I've never had to include a SESSION_SECRET env var — as a matter of fact I'm not sure what that env var is used for.

Do you have any unique/different permissions for the repo you're deploying from (I'm assuming you're using GitHub)? Any links to docs you found helpful would be great.

Glad you figure out how to get it working. Want to make sure we can understand better for others who run into this as well.

**Comment by callingmedic911** [comment]
Hi @aemann2 and @thedavidprice! I think `SESSION_SECRET` is related to dbAuth. We recently moved from Netlify to dbAuth in this tutorial, and I also think it's fair to update the Deployment section to reflect the additional env var changes.

cc: @cannikin any suggestion for the next steps? :)

**Comment by cannikin** [comment]
Well, it’s automatically added when you `yarn rw setup auth dbAuth` so I don’t think I even mention it in the tutorial because it Just Works. Switching over from one auth provider to another is sort of an advanced topic, not really suited to the tutorial. We’re you previously using Netlify Identity and then switched over to dbAuth?

If anything we should just have better error handling that tells you specifically that SESSION_SECRET is missing if you get to the auth function and don’t have one set up.

**Comment by callingmedic911** [comment]
> Well, it’s automatically added when you `yarn rw setup auth dbAuth` so I don’t think I even mention it in the tutorial because it Just Works. 

.env file is not loaded in serverless deploys like Netlify, right? If I'm not missing anything, we may just want to mention something like: make sure copy over vars from .env and .env.defaults?

**Comment by cannikin** [comment]
Ahhh yes, we copy over `DATABASE_URL` but not `SESSION_SECRET`. Although I went through the whole deploy when re-doing the tutorial and wasn't getting an error so it never occurred to me that I forgot it! 

I'll add a section!

**Comment by aemann2** [comment]
Yep @callingmedic911, this is related to dbAuth. I just removed SESSION_SECRET from my environment variables in Netlify to test the errors. 

Without that variable in Netlify, I get the "Something went wrong" banner. For console.logs, I get 502 errors. Here is the error in the Network tab that led me to solving the problem. It's pretty descriptive and told me exactly what I needed to do:

```{"errorType":"NoSessionSecretError","errorMessage":"dbAuth requires a SESSION_SECRET environment variable that is used to encrypt session cookies. Use `yarn rw g secret` to create one, then add to your `.env` file. DO NOT check this variable in your version control system!!","trace":["NoSessionSecretError: dbAuth requires a SESSION_SECRET environment variable that is used to encrypt session cookies. Use `yarn rw g secret` to create one, then add to your `.env` file. DO NOT check this variable in your version control system!!","    at DbAuthHandler._validateOptions (/var/task/node_modules/@redwoodjs/api/dist/functions/dbAuth/DbAuthHandler.js:334:13)","    at new DbAuthHandler (/var/task/node_modules/@redwoodjs/api/dist/functions/dbAuth/DbAuthHandler.js:102:10)","    at Runtime.handler (/var/task/api/dist/functions/auth.js:83:23)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}```
