### ISSUE TITLE
Adding "release-candidate" appropriate tags to NPM and GitHub releases

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#448]
@peterp When we publish release-candidates on both GitHub and NPM, these `rc` versions are tagged with "latest". Users may unintentionally, automatically upgrade to a prerelease version. So it seems we should be tagging these with "prerelease" or something other than the "latest" tag used for stable releases. 

### `yarn lerna version --force-publish`
This step builds and updates local files, then pushes and publishes releases to GitHub. Ideally, the releases would be automatically tagged "prerelease" on GitHub when published.

I looked at lerna docs for [--conventional-prerelease](https://github.com/lerna/lerna/tree/master/commands/version#--conventional-prerelease), but it seems this only applies when already using `--conventional-commits`. 

Alternately, we might try [--no-git-tag-version](https://github.com/lerna/lerna/tree/master/commands/version#--no-git-tag-version) to see if that just "hides" the release on GitHub by not including a tag at all (if I'm assuming how this works correctly).

Lastly, we could manually edit the GitHub release and save as a "prerelease" (which I just did for v0.6.0-rc.1 to see how it worked -- and it worked just fine)

### `yarn lerna publish from-package`
This publishes to NPM.

Here we can use lerna [--dist-tag](https://github.com/lerna/lerna/tree/master/commands/publish#--dist-tag-tag). Instead of the recommendations given [here](https://carrot.is/coding/npm_prerelease), which seem to use a tag specifying rc version, we could use the same tag such as "prerelease" or "releasecandidate" and then be able to always upgrade to the latest _prerelease_ using `yarn add @redwoodjs/core@prerelease` (that would work, correct?).

---

Reactions and suggestions?

**Comment by peterp** [comment]
Thanks for writing down your thoughts and detailing the varying approaches.

I think there are two 3 types of releases that we need to consider, and each will have a varying approach when it comes to tags, releases, and tagging npm packages.

1. an actual release that's used by the general public
2. a release candidate that's released just before it goes to the public
3. pre-releases that are not meant for general consumption

I think creating tagging a commit is fine and is not synonymous with creating a release. It's only visible via the commit message and tags section of GitHub, but creating a release will notify people watching the releases on this repository.

![image](https://user-images.githubusercontent.com/44849/79681689-55e53000-821c-11ea-9690-7872bc4f2d78.png)

I think the `--dist-tag` is the way to go for both a release candidate and a pre-release.

For core developer convenience I would love to have the merged pull-requests automatically published under a "pre-release" tag to NPM.

**Comment by thedavidprice** [comment]
> For core developer convenience I would love to have the merged pull-requests automatically published under a "pre-release" tag to NPM.

Woah, I like this idea. I did some quick research and saw that Next.js is doing this automatically per PR using the `canary` tag.
- NPM releases: https://www.npmjs.com/package/next
- GitHub releases (canary with ‘Pre-release’): https://github.com/zeit/next.js/releases

### Nextjs Automation Example
Next is using GH Actions with custom scripts (including lerna).
- Build, test, deploy GH Action workflow: https://github.com/zeit/next.js/blob/canary/.github/workflows/build_test_deploy.yml
- `publish-release.sh`: https://github.com/zeit/next.js/blob/canary/publish-release.sh

It seems they are using automation in combination with Branch management, i.e. PRs are against branch `canary`. They are also using version-specific Milestones, e.g. `v9.4.6`.

And stable releases are a manual merge of `canary` into `master`, which then kicks off the specific publishing automation.
> note: they have an ‘alpha’ branch that seems to no longer be used

### Misc Reactions
- if we automate each PR merge, I’m not sure we’ll need to use release-candidates that often given our current setup. If we implement branch management process, then I see it been needed.
- is `yarn lerna version --force-publish` necessary for us because of still needing manual server at times? And/or is there a way we can eliminate this step?

### Misc Research re: Build Stats
Next has a very cool automation for Stats that runs on PRs and Publishing.  Description: 
> Downloads and runs project with provided configs gathering stats to compare branches. 

Check the output here for the commit related to most recent stable release:
https://github.com/zeit/next.js/commit/c0724cac821a98489f5cbb48ec5471e12177c0ec#commitcomment-38500814

🤩

Here’s the simple workflow file for PRs:
https://github.com/zeit/next.js/blob/canary/.github/workflows/pull_request_stats.yml

It’s using this public GH Action: 
https://github.com/zeit/next-stats-action

#want

**Comment by Rosenberg96** [comment]
Just my two-cents even though this is mostly a concern for the core team:

Branching strategies is beneficial in clearly distinguishing the canary branch (i.e. _development_ in git flow) and the `master` with the production ready code - also having the `canary` npm publish action sounds great. 

A Github Action I have used with great success to automatically generate the change log and make Github Releases is [release-drafter](https://github.com/release-drafter/release-drafter). I can tell that their config also enables you to set `prelease` to true if you want an automatic `prerelease` on `push` to `canary` branch. That combined with a `lerna` as linked above would be great for the purpose imo.

**Comment by thedavidprice** [comment]
@Rosenberg96 thanks for this! I’m taking a look at release-drafter now.

We’re big on incremental changes, so our (my) first step here will be to implement automated canary publishing on the current `master`. We’ll see how/if that works and then re-evaluate implementing branch management as well.

To be clear, I’m very aligned with the process you outlined. We’re trying to err on the side of maximizing simplicity right now.

**Comment by peterp** [comment]
Closed  by 2341368cefefa288acfe0470070236c1bc09f74e
