### ISSUE TITLE
Disparity of singular vs. plural `role` and `roles` in Router vs auth.js

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#4488]
To limit a route to a role you use the singular `role` in a prop containing either a string or an array of strings:

```jsx
<Private unauthenicated="home" role="admin">
```

However, in both `requireAuth()` and `useRole()` you pass a plural `roles` argument:

```javascript
requireAuth({ roles: 'admin' })
hasRole({ roles: ['admin', 'moderator'] })
```

I think this should be plural `roles` everywhere. All forms appear to accept both a string or an array of strings, and I think we should preserve this behavior. I have an issue for [the docs](https://github.com/redwoodjs/redwoodjs.com/issues/973) to document this behavior in the Router.

We could accept both prop names for a time with a deprecation warning on the singular version so as to not introduce a breaking change.

**Comment by cannikin** [comment]
Outcome of core meeting discussion: 

1. Pluralize `role` in the Router prop
2. Wait to hear if directives can be changed to accept string in addition to array

**Comment by dthyresson** [comment]
Note:

To fix https://github.com/redwoodjs/redwood/issues/4489

```
requireAuth({ roles: 'admin' })
hasRole({ roles: ['admin', 'moderator'] })
```

on the api side has been changed to


```
requireAuth({ 'admin' })
hasRole({['admin', 'moderator'] })
```

This is part of the PR https://github.com/redwoodjs/redwood/pull/4680

**Comment by cannikin** [comment]
Hmm, I think that second code snippet has some extra curly brackets, those aren't valid syntax are they?

But, in the outcome comments from our meeting, only `hasRole` should change to not need an object with a `roles` key. We were going to keep `requireAuth` the way it is because it's not *only* checking for the roles, it's doing other things as well, so it's okay to be explicit here. 

So the resulting valid function calls should look like:

```javascript
requireAuth({ roles: 'admin' })
requireAuth({ roles: ['admin', 'moderator'] })
hasRole('admin')
hasRole(['admin', 'moderator'])
```

**Comment by dthyresson** [comment]
Wait, I thought that it should be:

```
requireAuth( 'admin' )
requireAuth( ['admin', 'editor'] )
```

so it matches

```
@requireAuth(roles: "admin")
@requireAuth(roles: ["admin", "editor"])
```

Oh, I guess that isn't a match ok.

**Comment by dthyresson** [comment]
So:

* `requireAuth` always has a key of `roles` and can take string, string[]
* `hasRole` never has a key and can take string, string[]

@cannikin correct?

**Comment by cannikin** [comment]
Correct! Although the object is *optional* for `requireAuth()`. But if you do want to match against roles, you need an object with a `roles` key. So the following should all be valid:

```javascript
requireAuth()
requireAuth({ roles: 'admin' })
requireAuth({ roles: ['admin', 'moderator'] })
```

Inside the `api/src/lib/auth.js` templates if requireAuth() *does* receive an object with `roles`, then it just delegates to `hasRole()`.

**Comment by dthyresson** [comment]
@cannikin Do I need to deprecate to `role` on the Set or private route?

I'd rather force roles and make the change before v1.

And `role` is more used for aria roles such as:

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/heading_role

```
<div role="heading" aria-level="1">This is a main page heading</div>
```

So, we should not re-use `role` for authentication checks.

This could also be confusing.

**Comment by cannikin** [comment]
We could skip the deprecation warning, but this would be a pretty massive breaking change: anyone that has a `<Private role="whatever">` route will not authenticate to the page they're trying to get to, and there'd be no notice telling them why. We have to really hope the read the release notes, or look up the docs. Or I guess include a codemod that makes the change for them.

How do you feel about that @thedavidprice?
