### ISSUE TITLE
Disparity between `hasRole()` usage on web and api sides

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#4489]
The arguments passed to the `hasRole()` function that you destructure from `useAuth()` are different than those passed to `hasRole()` that's used on the API side `api/src/lib/auth.js`.

```javascirpt
// web side
hasRole("admin")
hasRole(["admin", "moderator"])

// api side
hasRole({ roles: "admin" })
hasRole({ roles: ["admin", "moderator"] })
```

I prefer the web side usage—we're only checking one thing (whether the user has the role) so there's no need to pass an object that could have multiple, named keys. My thought is that this was done so that `requireAuth()` and `hasRole()` have the same signature? You currently call `requireAuth()` like so:

```javascript
requireAuth() // checks for isAuthenticated
requireAuth({ roles: "admin" }) // checks for both isAuthenticated and then calls hasRole() internally
```

In this case it makes sense, you're being explicit about what you're checking in that function, in addition to the "default" functionality of just checking if someone is logged in or not. But I think `hasRole()` can be safely updated to expect a top-level string or array. 

We could accept both and add a deprecation notice to the `hasRole({ roles: [] })` version that could be removed in v2.0 or whenever so as to not introduce a breaking change this late into the 1.0 schedule.

**Comment by dac09** [comment]
Just putting on here that we are also missing some logic in the hasRoles code (the one we found in the dbAuth template) 

-> Passing the roles to be checked as an array (i.e. `hasRoles(['BAZINGA'])`) but current user returns a string e.g. ```{
email: 'xxx',
role: 'BAZINGA'
}
````
