### ISSUE TITLE
[docs] colocating database and lambdas

### ISSUE THREAD

**Issue by benmccann** [redwoodjs/redwood#449]
The [deployment page in the tutorial](https://redwoodjs.com/tutorial/deployment) doesn't seem like a realistic deployment scenario to me or at least leaves me with some questions:

* Won't it result in high latency to have the database on Heroku and the Lambdas on AWS?
* Are we exposing the Postgres database to the internet in order to be able to access it from AWS?
* What Region / Availability Zone are the Lambdas running in? I'd think we'd want to place the DB there

**Comment by cannikin** [comment]
The deployment scenario in the tutorial was optimized for ease-of-use and is definitely not a high availability, low latency, production-ready design!

* Netlify deploys lambdas to us-east-1
* By default the Heroku DB is open to the world

We felt that the overhead of setting up an AWS DB instance didn't lend itself to the tutorial. People are already learning so many new concepts, we didn't want to try and cram in instance types, regions, security groups, and everything else that goes into setting up a DB instance on AWS from scratch.

We have a Cookbook section on the site that we're developing articles for. Getting a secure instance of AWS RDS could make for a fine article <hint, hint> 😉

**Comment by benmccann** [comment]
Thanks for the pointers! I do see that in their docs now. Linking it here for reference: https://docs.netlify.com/functions/overview/#default-deployment-options

**Comment by benmccann** [comment]
Making some more notes here. I've never used serverless before, so just learned that Lambda can "can have a large number of open connections to the database server, and may open and close database connections at a high rate, exhausting database memory and compute resources."  As a result, you probably also want to setup [RDS Proxy](https://aws.amazon.com/rds/proxy/) or [Aurora Serverless](https://aws.amazon.com/rds/aurora/serverless/).

**Comment by thedavidprice** [comment]
Hi @benmccann Connecting some dots here. There's a new community contributed Doc related to this called Connection Pooling:
https://github.com/redwoodjs/redwood/blob/master/docs/connectionPooling.md

And you'll see in this other new Doc, Local Postgres Setup, there's mention about using `?connection_limit=1` string, which is a related issue and Prisma recommendation:
https://github.com/redwoodjs/redwood/blob/master/docs/localPostgresSetup.md

**Comment by benmccann** [comment]
Cool. Thanks for the pointers.

I wonder for the Local Postgres Setup, have you considered recommending Docker for that? I've personally found that to be a fairly easy way to develop against a local DB (though my experience with it is somewhat limited). At least with MySQL the install on a local machine makes you setup a root user and is more involved than just pulling down a Docker image where that's already setup by default. Even if you don't have Docker installed yet it might still be the easier route

**Comment by thedavidprice** [comment]
**re: Docker**
We have not. Personally I've had great success using Docker for local dev workflow, but in this case, I'm not sure how that would work without setting up the _entire_ dev environment inside containers. Specifically, I'm not sure what you'd pass to Prisma here `DATABASE_URL=file:./dev.db` that would work to connect a container to the host. Perhaps file mounting would be fine... but they who/what is spinning up/down the container when you do/don't need it. 🤔

**Comment by benmccann** [comment]
I just put the database in Docker for local development and leave everything else outside it. Then the client talks to the database over the normal TCP connection using the provided connection string. So then you'd have `DATABASE_URL=postgresql://myuser:mypassword@localhost:5432/mydb`. SqlLite is a little funny in that you're specifying a file for the connection string, but I don't think you'd have that issue for the Local Postgres Setup, which makes things a lot easier. Does that make sense? Let me know if I'm missing anything still

**Comment by weaversam8** [comment]
We should definitely provide an example of spinning up a Postgres or MySQL instance in docker as part of the development flow, but I don't think this should replace SQLite as our de-facto development flow... I don't think Redwood should _require_ Docker to do development, but we should provide an option (maybe a Docker Compose setup) to develop with it.

**Comment by cannikin** [comment]
We've got the **Guides** section of the site for docs like this (someone wrote one for [local Postgres setup](https://redwoodjs.com/guides/local-postgres-setup)). Want to write a Docker one? 😀

**Comment by thedavidprice** [comment]
Some notes by way of link:
https://dev.to/pfreitag/running-postgresql-in-docker-for-local-dev-2ojk

I'm more conceptually interested in how this could be the simplest possible workflow; e.g. how to avoid having to "spin up all the things" and _then_ run `yarn rw dev`. Not for now, but it might be nice to have command options for different DBs (or possibility to write you own). E.g. In the case of postgres, I could run `yarn rw dev --postgres`.

**Comment by benmccann** [comment]
You could make `yarn rw dev` run `docker-compose up` and then it would work with any database as long as the `docker-compose.yml` had the correct configuration. The `docker-compose.yml` could be auto-created during app creation (E.g. `yarn create redwood-app --mysql` if you want to specify database flavor)

You can also setup an database admin UI to run, which is a big plus to doing things this way. Also, I like creating a `.env` file for the database credentials. E.g.:
```
version: "3.0"
services:
  postgres:
    image: postgres:12.2
    ports:
      - "3306:3306"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - "3000:8080"
```

**Comment by weaversam8** [comment]
@benmccann - I like this option actually, if we ever decided that this was an approach we decided to pursue. I definitely think that it should be something that's opt-in, obviously, but if someone decided they did want to use Docker, this would be a great development experience for it.

**Comment by thedavidprice** [comment]
this turned into a discussion -- closing for now but reopen as/if needed.
