### ISSUE TITLE
Disparity between `requireAuth()` usage in directive vs. function call

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#4492]
Related: https://github.com/redwoodjs/redwood/issues/4489

When calling `requireAuth()` on the api side, you can pass in an optional list of roles that the user must have in addition to being logged in:

```javascript
requireAuth({ roles: "admin" })
requireAuth({ roles: ["admin", "moderator"] })
```

Note that it allows both a string and an array of strings as valid values on the `roles` property.

When using the `@requireAuth` directive, however, only the array version is valid:

```javascript
type Mutation {
  deleteComment(id: Int!) Comment! @requireAuth(roles: ["admin"])
}
```

I'm not sure if this was an oversight or a limitation of GraphQL Directives. Here's the gql statement in the directive as created in a new app:

```javascript
export const schema = gql`
  """
  Use to check whether or not a user is authenticated and is associated
  with an optional set of roles.
  """
  directive @requireAuth(roles: [String]) on FIELD_DEFINITION
`
```

If possible, we should homogenize the usage between these different calls of what's essentially the same function. As stated in https://github.com/redwoodjs/redwood/issues/4489 I personally preferring letting users pass strings or arrays of strings and we'll worry about doing the right thing.

**Comment by dthyresson** [comment]
> I'm not sure if this was an oversight

I believe I did it to simplify the nature of the SDL for the directive.

```ts
export const schema = gql`
  """
  Use to check whether or not a user is authenticated and is associated
  with an optional set of roles.
  """
  directive @requireAuth(roles: [String]) on FIELD_DEFINITION
`
```

It was trickier (and not sure if possible) to have `roles` and `role` and then a string or array of strings.

It may be possible, but figured it was more straightforward to have an array of roles -- which is typically how they get stored on the User.

**Comment by cannikin** [comment]
Roger that! Let's discuss this one and the other two in the next core meeting.

**Comment by cannikin** [comment]
Outcome of core meeting discussion: keep object with `roles` key, but will always accept only an array of strings.

**Comment by dthyresson** [comment]
So, after going down a rabbit hole of creating a custom GraphQL scalar for the roles, it turns out that GraphQL will coerce values.


```
@requireAuth(roles: "admin")
```

will be forced such that the value on roles is `["admin"]` an array of a single string.

This is done as part of the directive definition that says roles is a `[String]`.

This means you can use either a string or an array and the auth checked can handle either.
