### ISSUE TITLE
Discussion) Maybe adding a generator for react context?

### ISSUE THREAD

**Issue by guledali** [redwoodjs/redwood#4510]
I was reading through the router documentation when I encountered this code block

```jsx
import { Router, Route, Set } from '@redwoodjs/router'
import BlogContext from 'src/contexts/BlogContext' // ⬅ Here is something intresting
import BlogLayout from 'src/layouts/BlogLayout'

const Routes = () => {
  return (
    <Router>
      <Set wrap={[BlogContext, BlogLayout]}> 
        <Route path="/" page={HomePage} name="home" />
        <Route path="/about" page={AboutPage} name="about" />
        <Route path="/contact" page={ContactPage} name="contact" />
        <Route path="/blog-post/{id:Int}" page={BlogPostPage} name="blogPost" />
      </Set>
    </Router>
  )
}

export default Routes
```

@mojombo  @thedavidprice  @jtoar  @dthyresson @cannikin  @dac09 It looks to me like Redwood.JS has some opinion regarding state management and where to put the react context, in this case in  a sub-folder called contexts. Giving that redwood is very very close 1.0 release. Adding a generator for context will it consinder it to be a breaking change? 

I honestly believe that the contexts subfolder should be part of any redwood app when you first initialise one. It will bring standardization to most apps out there, when it comes to state-management and where to put files. 

What do you guys think here?

**Comment by Tobbe** [comment]
I added that piece of documentation when I wanted to show how to use `<Set>`. Didn't mean to try to tell you how to use contexts 🙈 

That said, personally I do think it's a very useful pattern that I use in all my apps 🙂

**Comment by guledali** [comment]
@Tobbe I could not get this to work though,

```js
import React from 'react'

const UserExampleContext = React.useContext({
  id: 13,
  email: 'test@gmail.com',
  name: 'test',
})

export default UserExampleContext
```


```jsx

import UserExampleContext from 'src/contexts/UserExampleContext'

const Routes = () => {
  return (
    <Router>
      <Set wrap={[UserExampleContext, UserExamplesLayout]}>
        <Route path="/user-examples/new" page={UserExampleNewUserExamplePage} name="newUserExample" />
        <Route path="/user-examples/{id:Int}/edit" page={UserExampleEditUserExamplePage} name="editUserExample" />
        <Route path="/user-examples/{id:Int}" page={UserExampleUserExamplePage} name="userExample" />
        <Route path="/user-examples" page={UserExampleUserExamplesPage} name="userExamples" />
      </Set>
      <Route notfound page={NotFoundPage} />
    </Router>
  )
}
```

This the error on the  browser console
<img width="1440" alt="Screenshot 2022-02-18 at 11 15 25" src="https://user-images.githubusercontent.com/20647282/154663167-d517982a-5fde-48b9-9491-9ab2e63ae3ee.png">

**Comment by guledali** [comment]
@Tobbe  @jtoar  Any news on this feature?

**Comment by Tobbe** [comment]
@guledali Thanks for the ping.

We had a meeting yesterday, but it turns out this is an area where there are many different (strong) opinions. So the only thing we decided was to continue the discussion later. Our initial take was that this can easily be added at any time as it's not a breaking change. Most likely we will continue the discussion post v1. Unless, you know, I finish all my tasks and find myself with a bunch of free time before v1. Because I personally want at least to try it out, to see how it would look/work 🙂

**Comment by guledali** [comment]
> Huh, I had no idea that was a thing! I've been using Recoil for global state management, contexts just don't click in my brain for some reason. :(

@cannikin Recoil is really nice it fits the react model a little better, do you got any recoil examples with redwoodjs.

**Comment by cannikin** [comment]
Hmm, nothing open source I don't think. But it's nothing specific to Redwood, it's just like you'd use it in a React app. I've got a `web/src/lib/state.js` file that defines all my stuff and then any component where I need access to that state I just `useRecoilState()`, pretty simple!

**Comment by guledali** [comment]
> Hmm, nothing open source I don't think. But it's nothing specific to Redwood, it's just like you'd use it in a React app. I've got a `web/src/lib/state.js` file that defines all my stuff and then any component where I need access to that state I just `useRecoilState()`, pretty simple!

@cannikin I know you’re really busy man nowadays preparing for the v.1 launch that will happen anytime soon now, but can we expect some page in the cookbook describing how to handle global state management in redwoodjs with recoil.js

**Comment by cannikin** [comment]
Have you tried just going through the regular Recoil docs? That's really all you need to do, nothing special for Redwood! 

When it talks about wrapping your app in `<RecoilRoot>` just put that in App.js around `<Router>`:

```javascript
import { RecoilRoot } from 'recoil'

const App = () => (
  <FatalErrorBoundary page={FatalErrorPage}>
    <RedwoodProvider titleTemplate="%AppTitle">
      <RedwoodApolloProvider>
        <RecoilRoot>
          <Routes />
        </RecoilRoot>
      </RedwoodApolloProvider>
    </RedwoodProvider>
  </FatalErrorBoundary>
)
```

Put this in `web/src/lib/state.js`:

```javascript
export const randomState = atom({
  key: 'randomState', // unique ID (with respect to other atoms/selectors)
  default: 0.0, // default value (aka initial value)
});
```

Then in a component:

```javascript
import { randomState } from 'src/lib/state'
import { useRecoilState } from 'recoil'

const MyComponent = () => {
  const [random, setRandom] = useRecoilState(randomState)

  const onClick = () => {
    setRandom(Math.random())
  })

  return (
    <div>
      <span>randomState is currently: {random}</span>
      <button type="button" onClick={onClick} />
    </div>
  )
}
```

And you can use that same state in another component and it's value will update as well.

I just typed that up without testing but it should be pretty close!

**Comment by jtoar** [comment]
We've gone back and forth on this a few times as a team that I don't think it'll be implemented in the near future. And if we were to discuss it again, I'd probably push back on it again. Thanks for the RFC @guledali, but closing this one. If anyone else feels strongly about it I'll reopen, but just being honest with expectations about this being implemented soon.

**Comment by Tobbe** [comment]
For anyone interested in state management, I can recommend reading this https://frontendmastery.com/posts/the-new-wave-of-react-state-management
