### ISSUE TITLE
dependencies working by accident 

### ISSUE THREAD

**Issue by mohsen1** [redwoodjs/redwood#452]
I'm working on converting the router to TypeScript. I noticed this:

Router is using two `@testing-library` packages:
https://github.com/redwoodjs/redwood/blob/714a185b7f4578ed89caf9e0e139f7c29dcea8e2/packages/router/src/__tests__/links.test.js#L1-L3

While they are not listed in its package.json

https://github.com/redwoodjs/redwood/blob/714a185b7f4578ed89caf9e0e139f7c29dcea8e2/packages/router/package.json#L23-L26

This is working because other packages (`core` in this case) have this dependency. Yarn is too forgiving because it has hoisted this package. 

Is there a way to lint for this?

**Comment by RobertBroersma** [comment]
I didn't try this, but I think you can lint this using [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md) which is already a dependency of the redwood eslint config!
