### ISSUE TITLE
Netlify Identity Auth, currentUser context goes undefined on refresh of page.

### ISSUE THREAD

**Issue by vchoy** [redwoodjs/redwood#4520]
Tested Version: rw 0.46

Navigate to page that has a cell that calls sdl, that has @requriresAuth ...

On first load of page. it works.. 
`console.log(context.currentUser)`

```
api | {
api |   exp: 1645260849,
api |   sub: 'xxx-1c26-4d33-b6c5-xxx',
api |   email: 'testuser@gmail.com',
api |   app_metadata: { provider: 'email', roles: [ 'admin', 'tester' ] },
api |   user_metadata: { full_name: 'VinChoy' },
api |   roles: [ 'admin', 'tester' ]
api | }
```

on press 'refresh on browser' , the context.currentUser = undefined

```
api | undefined
api | 19:00:46 🚦  graphql-server 'UNAUTHENTICATED' error 'You don't have permission to do that.' occurred in RecordsQuery
```

auth.ts as follows:
```
export const getCurrentUser = async (
  decoded,
  { token, type },
  { event, context }
): Promise<RedwoodUser> => {
  if (!decoded) {
    return null
  }

  const { roles } = parseJWT({ decoded })

  if (roles) {
    return { ...decoded, roles }
  }

  return { ...decoded }
}

/**
 * The user is authenticated if there is a currentUser in the context
 *
 * @returns {boolean} - If the currentUser is authenticated
 */
export const isAuthenticated = (): boolean => {
  return !!context.currentUser
}
```

I'm thinking createGraphQLHandler (graphql.ts)  probably not awaiting on promise?

I reverted back to 0.45 and cannot reproduce the issue.

**Comment by Tobbe** [comment]
This sounds like a likely suspect https://github.com/redwoodjs/redwood/pull/4320

**Comment by vchoy** [comment]
I've seen some previous issue before reverting: I've removed yarn.lock 

but did NOT do the  `npx yarn-deduplicate`, I'll try that again tomorrow.

Thank you for pointing me to right direction.

**Comment by Tobbe** [comment]
I tried to reproduce this

```
yarn create redwood-app rw-auth-netlify
cd rw-auth-netlify
yarn rw prisma migrate dev -n initial
yarn rw g scaffold UserExample
yarn rw setup auth netlify
yarn rw g page Home /
```
Now we have to do some manual code modifications. On `HomePage` I created a button that calls `logIn` from RW's `useAuth`

Fire up the dev server
```
yarn rw dev
```
Log in, and then go to http://localhost:8910/user-examples.
Create a new user example.
Then I'm redirected back to /user-examples and see this
![image](https://user-images.githubusercontent.com/30793/154821719-0267eb24-3c96-47b4-953e-a4d737cebfbb.png)

Downgrading to 0.45.0 everything works

**Comment by Tobbe** [comment]
> This sounds like a likely suspect #4320

Reverting *just* that one did not help.

**Comment by Tobbe** [comment]
Some bisecting later I've most likely found the commit that introduced this bug: https://github.com/redwoodjs/redwood/commit/faede7f5dbcf7291fe4a5813c10175b056b9abbb

**Comment by Tobbe** [comment]
Yeah, reverting just that commit on top of `main` auth starts working again

**Comment by Tobbe** [comment]
Found a much less invasive fix https://github.com/redwoodjs/redwood/pull/4538

**Comment by Tobbe** [comment]
@vchoy It would be awesome if you could upgrade your RW installation to canary (`yarn rw upgrade -t canary`) and then report back whether your issue is fixed or not 🙂  It should be 🤞

**Comment by vchoy** [comment]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/1700776/154891055-e0fb9344-3577-46fd-ab0d-abe896271320.png">

w00t! :)

15:51:23 🌲 incoming request POST xxx /graphql
api | 15:51:23 🐛 graphql-server GraphQL execution started: __REDWOOD__AUTH_GET_CURRENT_USER
api | 15:51:23 🐛 graphql-server GraphQL execution completed: __REDWOOD__AUTH_GET_CURRENT_USER
api | 15:51:23 🌲 request completed 77ms
api | 15:51:35 🌲 incoming request POST xxx /graphql
api | 15:51:35 🐛 graphql-server GraphQL execution started: FindUserProfileById
api | 15:51:35 🌲 Starting a postgresql pool with 1 connections.
api | 15:51:35 🐛 graphql-server GraphQL execution completed: FindUserProfileById
api | 15:51:35 🌲 request completed 122ms
api | 15:51:38 🌲 incoming request POST xxx /graphql
api | 15:51:38 🐛 graphql-server GraphQL execution started: RecordsQuery
api | 15:51:38 🐛 graphql-server GraphQL execution completed: RecordsQuery
api | 15:51:38 🌲 request completed 56ms
api | 15:51:40 🌲 incoming request POST xxx /graphql
api | 15:51:40 🐛 graphql-server GraphQL execution started: FindUserProfileById
api | 15:51:40 🐛 graphql-server GraphQL execution completed: FindUserProfileById
api | 15:51:40 🌲 request completed 7ms
api | 15:51:54 🌲 incoming request POST xxx /graphql
api | 15:51:54 🐛 graphql-server GraphQL execution started: RELATIONS_FOR_CELL
api | 15:51:54 🐛 graphql-server GraphQL execution completed: RELATIONS_FOR_CELL
api | 15:51:54 🌲 request completed 15ms
api | 15:51:56 🌲 incoming request POST xxx /graphql
api | 15:51:56 🐛 graphql-server GraphQL execution started: FindRelationByIdWithRecordCount
api | 15:51:56 🐛 graphql-server GraphQL execution completed: FindRelationByIdWithRecordCount
api | 15:51:56 🌲 request completed 22ms
api | 15:51:58 🌲 incoming request POST xxx /graphql
api | 15:51:58 🐛 graphql-server GraphQL execution started: Anonymous Operation
api | 15:51:58 🐛 graphql-server GraphQL execution completed: Anonymous Operation
api | 15:51:58 🌲 request completed 12ms
api | 15:51:59 🌲 incoming request POST xxx /graphql
api | 15:51:59 🐛 graphql-server GraphQL execution started: FindRelationByIdWithRecordCount
api | 15:51:59 🐛 graphql-server GraphQL execution completed: FindRelationByIdWithRecordCount
api | 15:51:59 🌲 request completed 10ms
api | 15:52:00 🌲 incoming request POST xxx /graphql
api | 15:52:00 🐛 graphql-server GraphQL execution started: RELATIONS_FOR_CELL
api | 15:52:00 🐛 graphql-server GraphQL execution completed: RELATIONS_FOR_CELL
api | 15:52:00 🌲 request completed 8ms
api | 15:52:02 🌲 incoming request POST xxx /graphql
api | 15:52:02 🐛 graphql-server GraphQL execution started: FindUserProfileById
api | 15:52:02 🐛 graphql-server GraphQL execution completed: FindUserProfileById
api | 15:52:02 🌲 request completed 5ms


LGTM. Thank you!! - How you worked it out to bisect to evelop upgrade is nothing short of amazing. I wouldn't of known where to look.

**Comment by noire-munich** [comment]
For the record I've had recently the same on localhost, reverting to 0.45 stabilized the app.
Patch release is welcome!

**Comment by thedavidprice** [comment]
@noire-munich try `yarn rw upgrade` 😉

**Comment by noire-munich** [comment]
@thedavidprice the release mail got me here 😋
