### ISSUE TITLE
Error in ValidationRecipe type for some of the validators that can receive boolean as options

### ISSUE THREAD

**Issue by aguscha333** [redwoodjs/redwood#4527]
Hi, I am using the `validate` function provided by the framework in one of my services and I got a typescript error when using the following code:
```js
validate(input.email, 'Email', { email: true })
```
The error:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/9297073/154816869-df9bc563-82e4-43d5-97c7-dd807c5703e8.png">

This is because in the interface `ValidationRecipe` the email is defined like this:
```js
email?: EmailValidatorOptions;
```

But then in the `VALIDATORS` object used insde `validate`, for the email validator, options is defined like this: `options: boolean | EmailValidatorOptions` so there is a missmatch of types there.

This also happens with `absence`, `acceptance`, `numericality`, and `presence`.

I wanted to create this issue to better keep track of it but I will be creating a PR to fix as well, already have the code changes ready.

**Comment by aguscha333** [comment]
@simoncrypta created a PR with the fix

**Comment by thedavidprice** [comment]
Amazing! Thank you.
