### ISSUE TITLE
Scenarios and Tests lost when re-scaffolding or re-generating SDL

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#4540]
If you are building your api, you will want to create scenarios and tests that use that scenario data.

It can take some time to mock up this data -- and you don't want to lose it ... or all the test cases you wrote.

But, that's exactly what happens if you `--force` generation of scaffold or SDLs when you iterate on your data model -- something you will most always do while building an app/api.

One could argue that once you generate -- you should never re-generate (and hand code the SDL changes ... ultimately you will have to add the new fields or make changes to the scenarios). But, instead the entire file is wiped out.

And unless you have committed or save the changes, they are gone and you have to start over.

Not a fun DX.

Perhaps `--force` for should ONLY overwrite the sdl file ... and not the others?

That would save much accidental loss.

**Comment by cannikin** [comment]
Could provide an absolute-last-chance prompt when you use `--force` and we detect that the tests/scenario files aren't the same as the ones that are about to be generated:

```
It looks like your test and scenario files have changed since they were generated.
If you continue, those changes will be overwritten. Are you sure? [y/n]
```

Although if you're re-running them because you added something to the DB, presumably the test/scenario *would* be different than the one that's about to be generated, so you'll see that prompt 100% of the time (which kind of defeats the purpose of making you add `--force` in the first place).

You could make the same argument for not wanting to override the SDL or service files themselves—someone may have made changes and not committed them yet. I don't know if everything bad that could possibly happen falls under "bad DX"...sometimes that's just the way computers work. Is running `rm -rf *` bad DX, or just a potentially dangerous command that you have to be careful about running?

**Comment by Tobbe** [comment]
I think `--force` should really be "force", like it currently is.

But what if we added another flag for regenerating/overwriting the sdl files but keeping test and scenarios? Could that work?

Maybe add a prompt when running without flags

```
It looks like you have already run the generator. Would you like to overwrite the .sdl.ts file? [y/n]
```

And then add a `--yes/-y` flag for skipping the prompt

(Exact wording very much up for discussion)

**Comment by thedavidprice** [comment]
For components, we have the options `--tests` and `--stories`, which are true by default.

So what about `yarn rw g sdl foo --force --no-tests --no-scenarios`?

**Comment by cannikin** [comment]
If you want to stretch the thought experiment even further: could *not* overriding the tests/scenarios actually lead to problems? Let's say you write some tests for your service. Then you realize you need to modify the schema, so you re-generate (but skip the tests/scenarios). Now your scenario data does not represent the current structure of the database. Depending on what you were testing, you could end up with falsely passing tests, and you go about your day thinking everything is just fine.

There's only so much we can do to protect people from themselves, and there's always going to be another case we can come up that could potentially make the situation *worse*. If a developer is in the mindset that they can continually use the generators over and over for the life of their app as it evolves I think they're going to have a hard time, and I don't know that we can ever satisfy that use case. I know in the Rails world, folks would generally use the generators a few times when they start learning, or for the basic shell of a controller or model, but I don't know anyone that expected to be able to re-generate those files as they make changes to their database schema. They mostly got used to just create the shell of the base classes and their tests to give you that bare-bones starting point. 

I don't *think* the docs promote the idea that generators should be used over and over to take care of the plumbing of your app forever, but if folks are getting that impression we should probably tweak them to make it clear they're just a starting point—you still need to write and be responsible for your application code!

**Comment by Tobbe** [comment]
> you still need to write and be responsible for your application code

One thing I think would really help here is showing people how to manually do what the generators does for them. So when they do tweak their schema, they have a doc to reference for what updates to other files they need to do.

**Comment by dthyresson** [comment]
Let's do:

```
yarn rw g sdl foo --force --no-tests --no-scenarios
``

and a `--force` **always** asks to confirm (like auth and destroy does).

**Comment by cannikin** [comment]
Seems like if we're going to confirm the `--force` here we should do it on all generators with `--force`. Not it!

**Comment by Tobbe** [comment]
I still don't think `--force` should ask to confirm. To me `--force` is "I know what I'm doing. Don't annoy me with any prompts"

How about adding `--overwrite` and have that one prompt for confirmation?

**Comment by dthyresson** [comment]
What about “—sdl-only —force” and that generates and overwrites sdl and service … but leaves tests and stories untouched?

**Comment by dthyresson** [comment]
@thedavidprice did we come to a consensus yesterday to help mitigate this issue?

**Comment by dthyresson** [comment]
I experimented with commands and yargs aliases and all got too wonky complication -- and was hard to limit regeneration to just SDLs, and, you cannot send options when defining an alias.

So, in short, not a great way to do this in the current state with low risk.

That said:

```bash
yarn rw generate sdl UserExample --tests=false --force
```

Is what I want and need.

```
  ✔ Generating SDL files...
    ✔ Successfully wrote file `./api/src/graphql/userExamples.sdl.js`
    ✔ Successfully wrote file `./api/src/services/userExamples/userExamples.
js`
  ✔ Generating types ...
```

And works perfectly w/out any fw code changes.
