### ISSUE TITLE
GraphQL Error (Code: 504) 504 Gateway Time-out

### ISSUE THREAD

**Issue by Montana** [redwoodjs/redwood#4553]
I sometimes get this error in my Chrome dev console:

```graphql
Error: GraphQL Error (Code: 504): {
  "response": {
    "error":"<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n",
    "status":504,
    "headers":{
      "map":{
        "content-length":"578",
        "content-type":"text/html",
        "date":"Sun, 13 Feb 2022 23:48:59 GMT",
        "server":"nginx/1.18.0 (Ubuntu)"
      }
    }
  },
  "request":{
    "query":"query CarInfoQuery($licenseNbr: String!) {\n  carInfo: getCarInfo(licenseNbr: $licenseNbr) {\n    abrNo\n    year\n    brandModel\n    vin\n  }\n}",
    "variables":{
      "licenseNbr":"MHT534"
    }
  }
}
```
Looking at my server logs it looks like the request came in at about a second before-hand, also I see this in my logs: `api | 00:49:00 🌲 request completed 5.8s`

What is it exactly that times out? And how can I increase the time-out?

**Comment by simoncrypta** [comment]
Hi @Montana, thanks for reporting this error. 
Is this happen in development or in production/staging and if it is production/staging where did you deploy your server ?

**Comment by simoncrypta** [comment]
You can also look at this discussion that look similar to your error, see if that can help you :
https://community.redwoodjs.com/t/504-gateway-timeout-for-8910-netlify-functions-graphql/686

**Comment by jtoar** [comment]
Closing due to staleness but feel free to let us know where you landed with this and if Simon's comments helped!
