### ISSUE TITLE
Investigate Windows CI running out of memory

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#4557]
Jest tests for `redwoodjs/cli` run out of memory on Node 16 on Windows.

We know this is partially an issue somewhere in the jest-node-v8 stack (see facebook/jest#11956), but there's probably more we can do to reduce memory consumption.

Potential areas to check:

- [ ] Does running jest with `--detectLeaks` give us any more useful info?
- [ ] Are our require statements, and mocks in the cli tests specific enough?
- [ ] Should we start mocking out rwjs/structure instead of mocking the paths like we do in `lib/test`? This could significantly reduce the number of imports we have.
- [ ] Does mocking Listr out reduce memory consumption?

Note: this refers to internal redwood unit tests, not tests on a users project

**Comment by Jolg42** [comment]
Random question @dac09: can this be closed now?

It looks like the file where the Node.js version was pinned to 16.10 is gone.

I think it was moved there https://github.com/redwoodjs/redwood/blob/main/.github/workflows/ci.yml#L60?

**Comment by dac09** [comment]
Hey @Jolg42, I guess so! I actually completely lost track of this :)
