### ISSUE TITLE
Auth setup script issues

### ISSUE THREAD

**Issue by justindeguzman** [redwoodjs/redwood#4593]
### Error 1: Auth setup does not work when \<RedwoodApolloProvider/> has props

When I attempt to setup `Auth0` using `yarn rw setup auth auth0`, it results in an error:

```
/workspaces/my_app/node_modules/@redwoodjs/cli/dist/commands/setup/auth/auth.js:135
  const [_, indent, redwoodApolloProvider] = content.match(/(\s+)(<RedwoodApolloProvider>.*<\/RedwoodApolloProvider>)/s);
                                             ^

TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at addWebRender (/workspaces/my_app/node_modules/@redwoodjs/cli/dist/commands/setup/auth/auth.js:135:46)
    at addConfigToApp (/workspaces/my_app/node_modules/@redwoodjs/cli/dist/commands/setup/auth/auth.js:235:15)
    at Task.task (/workspaces/my_app/node_modules/@redwoodjs/cli/dist/commands/setup/auth/auth.js:347:9)
    at /workspaces/my_app/node_modules/listr/lib/task.js:167:3
```

This is in my `App.tsx`:

```js
<RedwoodApolloProvider graphQLClientConfig={{ cache }}>
  <Routes />
</RedwoodApolloProvider>
```

It works when I remove `graphQLClientConfig`, so this line in the auth script needs to be improved to take into account props in `<RedwoodApolloProvider/>`:

```js
const [_, indent, redwoodApolloProvider] = content.match(/(\s+)(<RedwoodApolloProvider>.*<\/RedwoodApolloProvider>)/s);
```

### Error 2: Auth0 object not added to App.tsx

After the auth setup script completes, it references an `auth0` object and adds it as a prop to `<AuthProvider/>`:

```js
<AuthProvider client={auth0} type="auth0">
  <RedwoodApolloProvider>
    <Routes />
  </RedwoodApolloProvider>
</AuthProvider>
```

However, this object from the docs is not actually added to `App.tsx`:

```js
const auth0 = new Auth0Client({
  domain: process.env.AUTH0_DOMAIN,
  client_id: process.env.AUTH0_CLIENT_ID,
  redirect_uri: process.env.AUTH0_REDIRECT_URI,

  // ** NOTE ** Storing tokens in browser local storage provides persistence across page refreshes and browser tabs.
  // However, if an attacker can achieve running JavaScript in the SPA using a cross-site scripting (XSS) attack,
  // they can retrieve the tokens stored in local storage.
  // https://auth0.com/docs/libraries/auth0-spa-js#change-storage-options
  cacheLocation: 'localstorage',
  audience: process.env.AUTH0_AUDIENCE,

  // @MARK: useRefreshTokens is required for automatically extending sessions
  // beyond that set in the initial JWT expiration.
  //
  // @MARK: https://auth0.com/docs/tokens/refresh-tokens
  // useRefreshTokens: true,
})

```

**Comment by simoncrypta** [comment]
> Error 1: Auth setup does not work when <RedwoodApolloProvider/> has props

I confirmed that we should accept props in the regex, 
we need to replace the regex : 
`/(\s+)(<RedwoodApolloProvider>.*<\/RedwoodApolloProvider>)/s`
for :
`/(\s+)(<RedwoodApolloProvider.*>.*<\/RedwoodApolloProvider>)/s`
on this file :
https://github.com/redwoodjs/redwood/blob/905ca4b6e99cddd07468bffaf9bb42e45cf2b1c6/packages/cli/src/commands/setup/auth/auth.js#L99

> Error 2: Auth0 object not added to App.tsx

This looks fine for me, it's probably cause by the regex error at the first time.

**Comment by justindeguzman** [comment]
For *Error 2*, I removed `graphQLClientConfig={{ cache }}` so that the setup script worked, and the `auth0` object was still not added to the file. I also tried it with Firebase and `firebaseConfig` was also not added. It definitely can be how my `App.tsx` is setup though, although I haven't edited the file significantly.

**Comment by simoncrypta** [comment]
The only thing I see that it could make it fail for the Auth0 object, is if you change `const App = () => ( ` for something else inside `App.tsx`

**Comment by justindeguzman** [comment]
Yep, I think that's it. I changed it to

```js
const App = () => {}
```

as I had to use `useEffect(, [])` to do some initialization for my app.

**Comment by Tobbe** [comment]
@justindeguzman Thanks for your issue report! Great find 👍 

Would you like to try to create a PR to fix these issues, or do you want us to do it? Up to you! No pressure 🙂

**Comment by simoncrypta** [comment]
> as I had to use useEffect(, []) to do some initialization for my app.

Interesting ! This use case was probably not taking in consideration, I guessed change this line  

https://github.com/redwoodjs/redwood/blob/905ca4b6e99cddd07468bffaf9bb42e45cf2b1c6/packages/cli/src/commands/setup/auth/auth.js#L72
for

`'const App = () => '`

can make it works !

**Comment by justindeguzman** [comment]
> @justindeguzman Thanks for your issue report! Great find 👍
> 
> Would you like to try to create a PR to fix these issues, or do you want us to do it? Up to you! No pressure 🙂

Unfortunately, I don't have the bandwidth currently, but the two lines @simoncrypta mentioned above should easily fix it :) I may spend more time setting up the Redwood development environment than submitting the PR 😄

**Comment by Tobbe** [comment]
100% no worries. Someone else will pick it up 🙂

**Comment by kengreeff** [comment]
@Tobbe looking for someone to do this one? I’m happy to have a go

**Comment by thedavidprice** [comment]
@kengreeff yes, please!! I'll assign to you now. Please take 'er away.

Also, has @Tobbe invited you to our next Contributors Meetup? We'd love to have you attend anytime in the future.

**Comment by Tobbe** [comment]
> Also, has @Tobbe invited you to our next Contributors Meetup?

I have not. But you're right, I totally should have. @kengreeff if you haven't already received an email from David, expect one from him or me about that soon
