### ISSUE TITLE
How to keep auth cookie stored on backend?

### ISSUE THREAD

**Issue by ShehabSN** [redwoodjs/redwood#460]
I am using passportjs and before moving to redwood js it was a simple flow where user signs in and then that triggers a passportjs strategy in the backend which creates a cookie using express session and stores it in both the backend and client side. This allows me to test graphql queries and mutations in the playground with no issue, however when moving this to redwood for some reason the cookie is not stored in the backend at localhost://8911/graphql, is this because its a proxy server? Instead its only stored on the client at localhost://8910 and so I cannot access the logged in user in my backend, even if i log in directly at localhost://8911/graphql in the graphql playground it does not store the cookie. How can i ensure the cookie is stored in here as well?

**Comment by peterp** [comment]
Hey @ShehabSN,

At the moment we're busy working on authentication over here: #214  - here's a guide on how to add passportjs to a serverless function: https://medium.com/@svengau/authentication-using-netlify-lambda-and-passportjs-%EF%B8%8F-51bfd80c6c11

I think you would have to include an auth endpoint on the api side, and once you get an auth token you would have to pass that along with the requests via the Apollo Client, and then use that token (and some kind of session storage) to determine if a user it logged in.

If you would like to share some code that takes this approach I would be happy to contribute to making this work.

Please feel free to continue this discussion on the community: https://community.redwoodjs.com/t/how-to-integrate-routing-for-google-authentication/393
