### ISSUE TITLE
Track package READMEs

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#461]
The Redwood Framework comprises many packages. This issue organizes the effort to document them.

From issue #434  via @thedavidprice:

> Where we are headed is that each package will have it's own README, e.g. "packages/cli/README.md", with information and instructions specific to 1) how that package works and 2) how to contribute to that package.

As of now, there's ten packages in the monorepo, three of which have a README:

 - [x] api
 - [x] web
 - [x] [router](https://github.com/redwoodjs/redwood/blob/master/packages/router/README.md)
 - [x] [dev-server](https://github.com/redwoodjs/redwood/tree/master/packages/dev-server/README.md)
 - [x] [cli](https://github.com/redwoodjs/redwood/tree/master/packages/cli/README.md)
 - [x] core
 - [x] eslint-config
 - [x] eslint-plugin-redwood
 - [x] create-redwood-app
 - [x] [internal](https://github.com/redwoodjs/redwood/tree/master/packages/internal/README.md) 

The goal's to populate the others with a starter README, which, at the least, should contain a description about what the package does. The router's README is a full-fledged document and might be an example of what the others will look like at some point.

I'm not sure how rank these in terms of priority (@thedavidprice, @peterp). I'm guessing the eslint packages would be lower on the list?

**Comment by peterp** [comment]
I think the api and web packages are probably the highest priority since they're the ones that user's interact with the most (I've re-ordered them in this list.)

**Comment by jtoar** [comment]
Attempted to start to address this with #500.

**Comment by thedavidprice** [comment]
FYI: just notice the CLI package has a README in root and also in src/commands/generate. Will need to reconcile.

**Comment by thedavidprice** [comment]
@jtoar should we close out this tracking issue?

**Comment by jtoar** [comment]
@thedavidprice Maybe we could still use this to track the fleshing out of the readmes as well, like #663, or should there be a separate issue for that?

**Comment by thedavidprice** [comment]
Yeah, let's just close out this one. Can copy+paste when/if we tackle the rest as a group. Thanks!
