### ISSUE TITLE
Document the creation of the .env.defaults in the beginning context of Tutorial I

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood#4614]
I believe that this should be explained in a single sentence in the section [Installation & Starting Development](https://learn.redwoodjs.com/docs/tutorial/installation-starting-development).

#### Here is why:

The documentation for the current release candidate (0.46.1) mentions the .env.default file only in the [Deployment](https://learn.redwoodjs.com/docs/tutorial/deployment/#recreate-migrations) section, explaining what needs to be **removed** from the project, to be ready for deployment). Assuming that the project was created by the RedwoodJS app bootstrap package ['Create Redwood App'](https://github.com/redwoodjs/redwood/tree/main/packages/create-redwood-app), all is fine, as this file (.env.defaults):
```
# schema.prisma defaults
DATABASE_URL=file:./dev.db

# location of the test database for api service scenarios (defaults to ./.redwood/test.db if not set)
# TEST_DATABASE_URL=file:./.redwood/test.db

# disables Prisma CLI update notifier
PRISMA_HIDE_UPDATE_MESSAGE=true
```

is created as a side effect of the command `yarn create redwood-app ./redwoodblog`

If however someone creates the projects from parts of existing projects using copy and paste of bunch of files, the file .env.defaults did not get copied (at least did not for me- using finder), and that someone created a nice hole, described as
```
 PrismaClientInitializationError: error: Environment variable not found: DATABASE_URL.
api |   -->  schema.prisma:5
api |    | 
api |  4 |   provider = "sqlite"
api |  5 |   url      = env("DATABASE_URL")
api |    | 
```
I discovered it with some pain trying to find out why my project did not have the file .env.default .

**Comment by simoncrypta** [comment]
Hey @adriatic I put what you had post in the [forum](https://community.redwoodjs.com/t/proposing-a-new-category-for-rwjs-discourse/2810/6?u=simoncrypta) here :
> It would be nice to have a tool (say rw-doctor) which can verify the correctness of a project - by asserting that all the .files created by the [create-redwood-app](https://github.com/redwoodjs/redwood/tree/main/packages/create-redwood-app) are present and correct.

It's feel like a nice solution for this type of problem!

**Comment by thedavidprice** [comment]
Thanks, all!

We are going to announce a community effort to QA the Redwood Tutorials next week. I've added the appropriate label for now. We'll make sure this is on the list of tasks to address.

@simoncrypta assigning to you for now. Ok?

**Comment by simoncrypta** [comment]
I just think about it, does `yarn redwood check` can do the trick @adriatic ? 
https://redwoodjs.com/docs/cli-commands#check-alias-diagnostics

**Comment by cannikin** [comment]
Any issues related to the tutorial should be opened in the https://github.com/redwoodjs/learn.redwoodjs.com repo where the tutorial lives, please! 🙂

In this case I don't think it warrants a text update: if you follow along with the steps in the tutorial then `.env.defaults` does exist. The tutorial isn't meant to cater to every possible use case, for example someone creating an app by copying and pasting a codebase from somewhere else. The tutorial is meant to be followed step-by-step with some callouts about gotchas once you start branching off on your own. My gut tells me that >95% of Redwood projects will start with `yarn create redwood-app` so this is not going to be a common pitfall.

**Comment by adriatic** [comment]
Yes, @simoncrypta , it does, although in a very basic way. Thanks for saving me from a likely embarrassment that would follow, had I continued this thread without knowing about `yarn redwood check` feature. Nevertheless, my proposal includes a lot more powerful functional tool, that can "disassemble" a logically coherent application, into parts and then recreate it with several different components that comply RW requirements.

**Comment by adriatic** [comment]
Thanks, @cannikin for sharing your interpretation 

> The tutorial is meant to be followed step-by-step with some callouts about gotchas once you start branching off on your own
This approach is common for all similar platforms, so my "science fiction" extensions will certainly cost RW some customers.

**Comment by adriatic** [comment]
@jtoar, @simoncrypta, @thedavidprice - sorry for creating waves. In my future company, the "create-application", will be reversible 😸
