### ISSUE TITLE
Codemod needed currentTimestampOverride

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#4615]
Need to write a codemod for https://github.com/redwoodjs/redwood/pull/4608

I will do this, just adding an issue to not lose track of it

**Comment by jtoar** [comment]
I can't remember if we implemented this or not, but it's been quite a while now so I'm going to close this. Let me know if you feel otherwise though @Tobbe

**Comment by Tobbe** [comment]
We did! I just forgot to link it properly. Thanks for helping with housekeeping Dom!

https://github.com/redwoodjs/redwood/pull/4675

**Comment by jtoar** [comment]
Oh nice! 🚀
