### ISSUE TITLE
[community] the community site bugs

### ISSUE THREAD

**Issue by ZiNai** [redwoodjs/redwood#462]
[redwoodjs community]( https://community.redwoodjs.com)
Home list works fine，but  when I enter any article, I cannot see the specific content.
There are some useful infos I want to know.
i.e. db surpport, redux, css surport .etc.

Is there any other community ?

### The picture show the details.
<img width="803" alt="Screen Shot 2020-04-23 at 2 57 58 PM" src="https://user-images.githubusercontent.com/18731079/80068830-dc7a7400-8572-11ea-8220-3525f97d2661.png">

**Comment by mojombo** [comment]
I've seen this problem in mobile Chrome. Do you have another browser you could try? And what OS/Browser are you using now?

@thedavidprice, did you say you had a lead on why this is happening?

**Comment by thedavidprice** [comment]
Yes, I'm on it with a previous bug/support request to Discourse. But it has been super hard to diagnose, so this is really helpful.

@ZiNai thank you so much for letting us know. And to repeat what Tom wrote above, it would be really helpful to learn more from you if you have time:
- what browser were you using? (e.g. Chrome v80)
- is it still broken?
- could you try a different browser to see if it works?
- lastly, could you use your GitHub account to login and see if it continues or works?

Lastly, please feel free to reach out to me directly for questions and I'd be happy to try and help if I can. My Twitter DMs are open [@thedavidprice](https://twitter.com/thedavidprice) (preferred if works for you) or email is thedavid@thedavidprice.com Happy to help!

**Comment by ZiNai** [comment]
Thank you very much for your prompt reply.
 I really like redwoodjs and thank for your cool work.

- Chrome V80,Safari V13.1 both can`t work
- until now It`s broken
- I tried my iPhone Safari and Quark brower.It also can`t work
- I have logined, but the bug continues.

**Comment by ZiNai** [comment]
when I get back the browser history,I got the https://community.redwoodjs.com/logs/report_js_error.
It`s a Rata Limit. 
Maybe you should set the rate limit is disabled.
[Global rate limits and throttling in Discourse](https://meta.discourse.org/t/global-rate-limits-and-throttling-in-discourse/78612)

**Comment by thedavidprice** [comment]
> I have logined, but the bug continues.
Hmm, typically that fixes the issue.

Thanks again for all this. I’m doing my best to use this information to work with the Discourse people. Very helpful to have your information to assist with reproducing the issue.

**Comment by thedavidprice** [comment]
@ZiNai 
>when I get back the browser history,I got the https://community.redwoodjs.com/logs/report_js_error.

Any chance you still have access to the logs and could post them here?

**Comment by ZiNai** [comment]
> @ZiNai
> 
> > when I get back the browser history,I got the https://community.redwoodjs.com/logs/report_js_error.
> 
> Any chance you still have access to the logs and could post them here?
> 
> [EDIT: never mind. I just reproduced and got a “Rate Limited” with no other info 🤔]

The log shows only "Rate Limit".

Today I try the community ,It works well now.
Has the bug been fixed?

**Comment by thedavidprice** [comment]
>Today I try the community ,It works well now.
Has the bug been fixed?

Maybe! There was an available update, which I upgraded. It's possible that somehow the upgrade fixed the bug. Please let me know if you have any problems again. But hopefully it's resolved 🤞
