### ISSUE TITLE
Deprecate VS Code IDE Extension

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#4625]
The extension is effectively not compatible with v1. It's planned for a re-implementation, which will not be started by v1 launch. Basically it's now a "use-at-your-own-risk" extension.

Need to mark the extension as deprecated. 

It's been removed from CRWA template extension recommendations in #4613

**Comment by jtoar** [comment]
@thedavidprice just checked if it was deprecated; looks like it's not (using this link as reference: https://marketplace.visualstudio.com/items?itemName=redwoodjs.redwood). Still plan to do this?

**Comment by jkjetty** [comment]
What is the recommended alternative now? Just to use `yarn redwood` from the terminal and other extensions (graphql, eslint) for codebase management?

**Comment by jtoar** [comment]
@jkjetty that's right. The CLI + the recommended extensions = the experience™. (Note: we're working on making the CLI faster, 'cause it's way too slow.) The Redwood IDE extension had some super cool features that the CLI and recommended extensions don't have, so the experience won't be 1:1. Maybe we'll prioritize the extension again in the future but right now it's not one of our priorities and hasn't been for a while, so we're just trying to communicate that is all. Did you use it before and like the experience?

**Comment by jkjetty** [comment]
I hadn't given it a try but I had to do a bit of searching around to figure out why it wasn't working. I like and probably prefer the CLI for most things, but the project explorer seemed worthwhile!

**Comment by thedavidprice** [comment]
This has been unpublished from the VS Code Marketplace. 

At this time, there is no plan to replace the IDE Extension. It was a brilliant idea, but would need:
- new initiative and lead
- entire rewrite
