### ISSUE TITLE
Error: usePageLoadingContext must be used within a PageLoadingContext provider

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#4705]
Please see the issue raised in Discourse here: 

https://community.redwoodjs.com/t/usepageloadingcontext-not-working/2839

![image](https://user-images.githubusercontent.com/1051633/157436510-50617e9d-8f74-4c7b-8d3d-b94f524a6fc2.png)

I replicated this issue by following the code sample in the Redwood docs:

https://redwoodjs.com/docs/router#using-pageloadingcontext

```
import { usePageLoadingContext } from '@redwoodjs/router'

type PageLayoutProps = {
  children?: React.ReactNode
}

const PageLayout = ({ children }: PageLayoutProps) => {
  const { loading } = usePageLoadingContext()

  return (
    <div className="relative bg-white">
      {loading && <div>Loading...</div>}

```

and got the same error:

![](https://rwjs-discourse.nyc3.cdn.digitaloceanspaces.com/original/2X/0/091cf64c554ea8a1540de34b512141a46fe3d60f.jpeg)

**Comment by cannikin** [comment]
I don't think I'll have time to work on this: this is my last week of work before the launch and I'm recording tutorial videos every day! Maybe @Tobbe can take a look?

**Comment by Tobbe** [comment]
I can confirm this is reproducible on a regular page as well, not just in a Layout.

And I have a fix working in GitPod. I'll work on a PR as soon as I can find some free time

**Comment by FrankMbappe** [comment]
Any update on this ? I've encountered the same problem and this issue has been open for a month and plus now

**Comment by jtoar** [comment]
Hey @FrankMbappe, does this work for you in the meantime? This is much the same how mocking `LocationProvider` works:

```jsx
// web/src/pages/HomePage/HomePage.test.js

// Import the PageLoadingContext from the router
import { PageLoadingContext } from '@redwoodjs/router'
import { render } from '@redwoodjs/testing/web'
import HomePage from './HomePage'

describe('HomePage', () => {
  it('renders successfully', () => {
    expect(() => {
      render(
        // Wrap the component (a page in this case) in the PageLoadingContext.Provider
        // with the desired value
        <PageLoadingContext.Provider value={{ loading: true }}>
          <HomePage />
        </PageLoadingContext.Provider>
      )
    }).not.toThrow()
  })
})

``` 

> this issue has been open for a month and plus now

First off thanks for bumping this issue—knowing what Redwood users' pain points are helps us know prioritize, and often times we don't know until people tell us. We have a lot of open issues, and fixing them doesn't include the time we need to spend researching and working on new features. That said I'll bring this up to the team again to see if we can get a fix for it sooner than later.

**Comment by FrankMbappe** [comment]
> Hey @FrankMbappe, does this work for you in the meantime?

Yes, it does 👍🏾. Hopefully, this issue can be fixed quickly
Are there any workarounds in the meantime?

**Comment by jtoar** [comment]
@FrankMbappe that is the workaround—explicitly wrapping the component being tested in `PageLoadingContext.Provider` and passing a value (`{ loading: true }`, or `false` if you want to test if the page isn't loading).

**Comment by FrankMbappe** [comment]
I mean a workaround to get the loading state of a page
Is there any function or component from `@redwoodjs/router` that can provide us with the actual loading state?

**Comment by FrankMbappe** [comment]
@jtoar Yes, but I'm not talking about testing `PageLoadingContext` 🙇🏾‍♂️. Is there any workaround to make it work as it should in the browser while you guys are fixing this issue?

**Comment by Tobbe** [comment]
> And I have a fix working in GitPod. I'll work on a PR as soon as I can find some free time

Which is now long gone :(  I'll get up to speed and see what I can do

**Comment by jtoar** [comment]
@FrankMbappe ah I get it now, it's just broken-I thought it was only broken in the test. Sorry about the confusion!

**Comment by FrankMbappe** [comment]
@jtoar No problem, I'll just wait for the fix

**Comment by Tobbe** [comment]
Fixed here: https://github.com/redwoodjs/redwood/pull/5521

**Comment by jtoar** [comment]
@FrankMbappe the latest release (v1.4.2) includes the fix for this:
```
yarn rw upgrade
```
