### ISSUE TITLE
`yarn rwt` missing symlink

### ISSUE THREAD

**Issue by Jaikant** [redwoodjs/redwood#471]
I noticed that we have updated the [contributing](https://github.com/redwoodjs/redwood/blob/master/CONTRIBUTING.md) page, and now have a new `rwt` cli command. 

The command does not work as the `node-modules/.bin` directory is missing the `rwt` symlink to  `packages/cli/dist/redwood-tools.js`

PS: I tried to use the previous method of `yarn link` that fails with the error below (not sure why)
```
yarn link v1.22.4
error Couldn't find package name.
info Visit https://yarnpkg.com/en/docs/cli/link for documentation about this command.

```

**Comment by peterp** [comment]
@Jaikant Do you have v0.6.0 of `@redwoodjs/core` installed?

**Comment by Jaikant** [comment]
I updated the package.json    ` "@redwoodjs/core": "^0.6.0",` did a `yarn` and it worked. Thanks @peterp
