### ISSUE TITLE
Rc6 release notes - update-dev-fatal-error-page 

### ISSUE THREAD

**Issue by vchoy** [redwoodjs/redwood#4724]
when running 
`npx @redwoodjs/codemods@canary update-dev-fatal-error-page`
Changes from: 

-  RedwoodDevFatalErrorPage = require('@redwoodjs/web').DevFatalErrorPage
 which is what the manual steps specify

to: 

+  RedwoodDevFatalErrorPage =
+    require('@redwoodjs/web/dist/components/DevFatalErrorPage').DevFatalErrorPage

Which one would you like  (for consistency) ...I can make the PR.

**Comment by thedavidprice** [comment]
@vchoy! I think you and @dthyresson are in sync right now --> this what you're looking to fix?
https://github.com/redwoodjs/redwood/pull/4723/files

**Comment by vchoy** [comment]
@thedavidprice , yes. Looks like the release notes should change then?

**Comment by thedavidprice** [comment]
AH, good catch, and yes indeed. Let me get the PR in now (which will fix the codemod) and then I'll update notes on GitHub and Forum. Thank you!

**Comment by thedavidprice** [comment]
Done and done:
- https://community.redwoodjs.com/t/redwood-v1-0-0-rc-6-is-now-available/2832
- https://github.com/redwoodjs/redwood/releases/tag/v1.0.0-rc.6

Could you help confirm I didn't miss anything and then close this Issue once all gtg?

Thanks!

**Comment by vchoy** [comment]
LGTM. 
if you want to add optional extra tab: 
+   RedwoodDevFatalErrorPage =
+   <TAB> require('@redwoodjs/web/dist/components/DevFatalErrorPage').DevFatalErrorPage
+ }

as per : https://github.com/redwoodjs/redwood/pull/4723/files#diff-6fb3ebe24c0a698fd369cdd5959d83e15f0fdf076e768814726863a120a08a00R14

up to you. Thanks again!!! :)
