### ISSUE TITLE
yarn rw dev fails after yarn create redwood-app 

### ISSUE THREAD

**Issue by kadarp** [redwoodjs/redwood#474]
After creating a new project (following the tutorial) with "yarn create redwood-app ./redwoodblog", yarn redwood dev fails, complains about MODULE_NOT_FOUND rxjs

[redwoodblog.zip](https://github.com/redwoodjs/redwood/files/4533727/redwoodblog.zip)

> yarn -v && node -v
1.22.4
v12.16.2

After cd web && yarn upgrade it works
[yarn_upgrade_output.txt](https://github.com/redwoodjs/redwood/files/4533747/yarn_upgrade_output.txt)

Log:
kadarp@Peter-Precision-M6800:~/rwTest$ yarn create redwood-app ./redwoodblog
yarn create v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-redwood-app@0.6.0" with binaries:
      - create-redwood-app
[#################################################################################################################################################################################] 455/455   ✔ Creating Redwood app
    ✔ Creating directory '/home/kadarp/rwTest/redwoodblog'
    ✔ Downloading latest release
    ✔ Extracting latest release
    ✔ Clean up
  ✔ Installing packages
    ✔ Checking node and yarn compatibility
    ✔ Running yarn install... (This could take a while)

Thanks for trying out Redwood! We've created your app in '/home/kadarp/rwTest/redwoodblog'

Inside that directory you can run yarn rw dev to start the development server.
Done in 12.38s.
kadarp@Peter-Precision-M6800:~/rwTest$ cd redwoodblog/
kadarp@Peter-Precision-M6800:~/rwTest/redwoodblog$ yarn redwood dev
yarn run v1.22.4
$ /home/kadarp/rwTest/redwoodblog/node_modules/.bin/redwood dev
internal/modules/cjs/loader.js:327
      throw err;
      ^

Error: Cannot find module '/home/kadarp/rwTest/redwoodblog/node_modules/rxjs/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:319:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:703:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:967:27)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/kadarp/rwTest/redwoodblog/node_modules/listr/lib/task.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/kadarp/rwTest/redwoodblog/node_modules/rxjs/package.json',
  requestPath: 'rxjs'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by thedavidprice** [comment]
@kadarp Thanks for trying out Redwood and letting us know about these issues you encountered.

To confirm, you ARE now able to run `yarn redwood dev` after upgrading the packages?

**Comment by kadarp** [comment]
@thedavidprice I can confirm, after upgrading `yarn rw dev` works. 
Btw I tried on relatively newly installed OS, and it worked without needing the upgrade...

**Comment by thedavidprice** [comment]
Thanks! And keep us posted if anything else comes up as you try out the Tutorial.
