### ISSUE TITLE
<FieldError> Wrong reference link in documentation and a question

### ISSUE THREAD

**Issue by joriswill** [redwoodjs/redwood#4748]
Hey, 

in the Documentation for the <FieldError> React Component is a wrong reference link to the tutorial. It redirects to a page 404.
https://github.com/redwoodjs/redwood/blob/959b00fb95157ce0e9d0421238919a1b388d3ea5/packages/forms/src/index.tsx#L448

And then I have a additional question for the <FieldError> Component (I'm new to the subject). Is it possible to change/influence the text by parameters (for example to translate the error Message)?

**Comment by thedavidprice** [comment]
Thanks @joriswill I made the change easy peasy! (Also, we ❤️ contributors. Let me know if you ever want to learn how to help make Redwood even better via PRs of your own!)

re:
> And then I have a additional question for the Component (I'm new to the subject). Is it possible to change/influence the text by parameters (for example to translate the error Message)?

There are ways to change the error message as well as (still improving) i18n support. The best place to start with questions like these are Redwood's Discord Sever and the Redwood Forums — there's a dyanmic, helpful community of people that are always open to helping new people get started!
- https://discord.gg/redwoodjs
- https://community.redwoodjs.com/

Also, don't hesitate to look through and search our Docs. There are a lot of them!
- https://redwoodjs.com/docs/introduction
