### ISSUE TITLE
The URL for datasource `DS` must start with the protocol `postgresql://`.  

### ISSUE THREAD

**Issue by chris-hailstorm** [redwoodjs/redwood#477]
ENVIRONMENT

0.6.0

OBSERVATION

Deploying remotely on Netlify.  Build phase runs with no errors. The database migration phase (no steps needing to run, but must connect to database to check migration status) works fine.

My site opens fine to a static page.  On the first GraphQL query, I get this error:

```
Error: GraphQL error: 
Invalid `prisma.project.findMany()` invocation in
/var/task/src/api/dist/services/projects/projects.js:27:25

error: Error validating source `DS`: The URL for datasource `DS` must start with the protocol `postgresql://`.
  -->  schema.prisma:3
   | 
 2 |   provider = "postgresql"
 3 |   url      = env("DATABASE_URL")
   | 
```

Nothing strange in `api/prisma/schema.prisma`:

```
datasource DS {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

Corresponding section of my `netlify.toml` does use "postgresql":

```
[context.BRANCHNAME.environment]
  DATABASE_URL = 'postgresql://PASSWORD@HOST:5432/DBNAME?connection_limit=1'
  DB_PROVIDER = 'postgresql'
```

Problem happens with or without the `netlify-plugin-prisma-provider` build plugin.

If I put the database URL directly into `schema.prisma` like this, everything works:

```
datasource DS {
  provider = "postgresql"
  url      = "postgresql://PASSWORD@HOST:5432/DBNAME?connection_limit=1"
}
```

The `env("DATABASE_URL")` part worked fine before; now seems to be the problem.

QUESTIONS

Is it possible the environment lookup no longer works?  Or no longer works for a branch build?

Maybe something changed at Netlify and Redwood isn't implicated?  I'll cross-post there.

Or could the problem be in the updated Prisma client version used by 0.6.0 (2.0.0-beta.3)?

**Comment by thedavidprice** [comment]
Related to #469 

I suspect their Beta Build environment has changed in a way that is causing issues with Prisma. 

I am **not** having issues with deploy or API on my test site, which I upgraded to v0.6.0 and just redeployed. Perhaps there were no errors because I didn't have any DB migrations to apply? Here's the site: https://redwoodjs-tutorial-test.netlify.app/

**Comment by cannikin** [comment]
I’ll take a look at this in the morning!

**Comment by thedavidprice** [comment]
@chris-hailstorm Your specific error would indicate that Netlify Beta Build is **not** enabled, which is required for the plugin to work. The process has recently changed on their end. 

You should now see a button in the top right corner. Could you please confirm it’s enable for your site?

<img width="203" alt="Screen Shot 2020-04-28 at 12 33 01 PM" src="https://user-images.githubusercontent.com/2951/80529500-6730e980-894c-11ea-9023-cb2b7e96fd44.png">

**Comment by thedavidprice** [comment]
See update here about a possibly related Netlify deploy issue:
https://github.com/redwoodjs/redwood/issues/469#issuecomment-620809868

**Comment by cannikin** [comment]
@thedavidprice and I went down quite a rabbit hole trying to figure out deployments lately. I can deploy successfully with just `postgres://` even though the error message mentions requiring `postgresql://`. I'm guessing they check for both, or use a regex like `/postgres/`, but if there's some other problem like the url not existing at all, the error message just happens to say `postgresql://` is required.

We've got a ticket open with prisma https://github.com/prisma/migrate/issues/433 and started a discussion with Netlify to try and find out what the hell is going on.

In the meantime we've done two things: 

1. update the netlify plugin that swaps out the provider, can you try upgrading that? It's the `netlify-plugin-prisma-provider` package in your root `package.json`
2. rename the environment variable from `DATABASE_URL` to literally anything else

It's weird, I know, but both David and I both are unable to apply migrations during a build on Netlify unless we name that variable something else. Prisma snapshots your schema.prisma file into the migration and it appears it checks for THAT provider (which will be "sqlite" if you use sqlite locally and created your migrations locally), but now compares the provider THERE against the URL in the main `schema.prisma` and if the protocol isn't what's expected it blows up.

It seems like something similar may be happening even if gets past the build phase (if no migrations are required then `DATABASE_URL` doesn't seem to cause any problems) then it blows up in the db code in your services.

**Comment by thedavidprice** [comment]
@chris-hailstorm we think this issue might be resolved [with the fix here](https://github.com/redwoodjs/redwood/issues/469#issuecomment-622608642).

Assuming you are using the Redwood Netlify Plugin (are you?), could you upgrade to v0.3.0 and give it a go?

_Note:_ if you have your own deploy setup, you might be running into the core issue we encountered with Prisma's change in migration validation between beta.2 and beta.3. Migration `steps.json` files need to have matching datasource `provider` and `url` values compared to your `schema.prisma` file. The Netlify Plugin might be the easiest fix for you if this is the case.

**Comment by thedavidprice** [comment]
Checking back to see if this issue has been resolved. True? 🤞

**Comment by chris-hailstorm** [comment]
I think this is implicated in the larger Prisma migration issue you've been discussing.
