### ISSUE TITLE
[Auth] Clerk GetToken returning wrong value

### ISSUE THREAD

**Issue by Burnsy** [redwoodjs/redwood#4793]
Just had a debugging conversation with Sokratis Vidros at Clerk

Get token should return the JWT token but instead it the session id

**Wrong:**
https://github.com/redwoodjs/redwood/blob/3943bd1a1653fb76adca0306c115dcfd22954998/packages/auth/src/authClients/clerk.ts#L39

**Correct:**
It Needs to be `clerk.session?.getToken()`

**Comment by thedavidprice** [comment]
@devchampian Is this something you could take a look at?

**Comment by dthyresson** [comment]
I chatted with Clerk and they said that this implementation isn’t 100% correct and instead they’ll be upgrading the client in Redwood next week to the latest version that will not use the session.

**Comment by thedavidprice** [comment]
> next week

😬

**Comment by Tobbe** [comment]
Work started over here https://github.com/redwoodjs/redwood/pull/4846
