### ISSUE TITLE
Restart development servers when redwood.toml is modified

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#481]
The api server and webpack dev server should be restarted when the `redwood.toml` configuration is modified.

Related: #478

**Comment by sherry808** [comment]
Hi @peterp, new redwood contributor here. May I take this up?

**Comment by peterp** [comment]
Hey Sherry, that would be amazing! I think there's a way to do this via nodemon instead of directly executing webpack-dev-server.

**Comment by sherry808** [comment]
Thanks, will check it out.

**Comment by thedavidprice** [comment]
@sherry808 Thanks for jumping in! Assigning this one to you. Just let me know otherwise.

And keep the questions coming. Anytime.
