### ISSUE TITLE
Proposed tutorial reorganization into chapters

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#4811]
The fact that there's a Part 1 and Part 2 to the tutorial is a relic of the fact that Storybook and Jest weren't ready when I wrote part 1. Once they were, rather than making the original longer I made a sequel. Reflecting on it now it's probably not necessary.

After discussing with the core team we liked the idea of still breaking up into digestible chunks, otherwise it looks kind of overwhelming. Here's my first take at breaking down into chapters, each one has sort of a self-contained theme:

* Forward
* Chapter 1
  * Prerequisites
  * Installation & Getting Started
  * Redwood File Structure
  * Our First Page
  * A Second Page and a Link
  * Layouts
* Chapter 2
  * Getting Dynamic
  * Cells
  * Side Quest: How Redwood Works with Data
  * Routing Params
* Chapter 3
  * Building a Form
  * Saving Data
* Chapter 4
  * Authentication
  * Deployment
* Chapter 5
  * Introduction to Storybook
  * First Test
  * Introduction to Testing
  * Our First Test
* Chapter 6
  * Building a Component the Redwood Way
  * Multiple Comments
  * Adding Comments to the Schema
  * Creating a Comment Form
* Chapter 7
  * Role-based Access Control
  * Wrapping up

**Comment by thedavidprice** [comment]
Looks great to me!

**Comment by cannikin** [comment]
Now gotta reword the start/end of these sections so they're not so final (like the end part 1, start of part2, etc.)
