### ISSUE TITLE
Add Issue template to this repo

### ISSUE THREAD

**Issue by sohailg** [redwoodjs/redwood#4817]
Adding a issue template will help the maintainers to sort out whether it is a bug/feature/documentation.

**Comment by sohailg** [comment]
I would like to assign myself to this issue,if possible.

**Comment by simoncrypta** [comment]
Hi @sohailg,

Welcome and thank you for this suggestion!  

We already have a discussion about how we want issue template that you could interest you before you start
https://github.com/redwoodjs/redwood/pull/3551#pullrequestreview-781373560

I cc @thedavidprice if he has something else to add about it and assign the issue to you :smile:

**Comment by thedavidprice** [comment]
Hi all! The short answer is that we're not ready for this. But after v1 launches it is something we can revisit.

@sohailg appreciate your offer to help out! There are a lot of open issues and areas where we need help right now. If you are interested, please do take a look at the links in this doc:
- https://redwoodjs.com/docs/contributing-overview
