### ISSUE TITLE
wrong reference link while setting up tailwind.

### ISSUE THREAD

**Issue by joriswill** [redwoodjs/redwood#4818]
I found in the forum the old command (yarn rw setup tailwind) and so i stumbled over this old reference link.

https://github.com/redwoodjs/redwood/blob/ffedd087273420ff7c7ba3fe81831afac4efb235/packages/cli/src/commands/setup/tailwind.js#L18

The right Link would be "https://redwoodjs.com/docs/cli-commands#setup-ui".

**Comment by simoncrypta** [comment]
Good catch ! Do you want to open a PR for that ? No pressure if you don't  ;)

**Comment by joriswill** [comment]
Thanks for the response :) I can open a PR later when I'm back home. It is good to learn a little bit more about GitHub and working on a project together.
