### ISSUE TITLE
📢 Community Help Wanted 📢 - Help QA the new & improved Tutorial!

### ISSUE THREAD

**Issue by agiannelli** [redwoodjs/redwood#4820]
## The Redwood v1 Launch :rocket: is fast approaching and we need your help

@cannikin has revamped both Tutorial I & II for v1 RC and we need you, our amazing community members, to help QA the new & improved version to ensure the Tutorial is as amazing as ever. :sunglasses:

## :zap: TL;DR

- :construction: Go through Tutorial I & II on [redwoodjs.com](https://redwoodjs.com/docs/tutorial/welcome-to-redwood)
use the [sample repo](https://github.com/redwoodjs/redwood-tutorial) to Quick Start on Tutorial II
- :exclamation:If you find something…
  - 💬 reply to this issue
  - :loudspeaker: [Open an issue](https://github.com/redwoodjs/redwood/issues/new)
  - :arrow_heading_down: [Open a PR](https://github.com/redwoodjs/redwood/compare) (We love [contributors](https://redwoodjs.com/docs/contributing-overview)! :heart: )
- :question: Questions? Reach out here, in the [forums](https://community.redwoodjs.com/t/community-help-wanted-help-qa-the-new-improved-tutorial/2825) :fountain_pen:, or on [Discord](https://discord.gg/redwoodjs) :speech_balloon:

## :question:What we need from you

Head over to [redwoodjs.com](https://redwoodjs.com/docs/tutorial/welcome-to-redwood)[](https://community.redwoodjs.com/t/community-help-wanted-help-qa-the-new-improved-tutorial/2825#types-of-tests-were-looking-for-4):arrow_upper_right: and start the Tutorial!

As you work your way through make note of typos :fountain_pen:, sections that are confusing :thinking:, instructions or code that do not work as expected 🙅 , bugs you find :lady_beetle: - any & all hiccups you run into.

We want to know about it. If you’re struggling, chances are someone else is too.

## :test_tube: Types of tests we’re looking for:

- :hash: Different Node versions (Redwood is compatible with v14 → v16)
- :desktop_computer: Operating Systems - Windows, Mac, Linux
- :closed_book: Walk through Tutorial I
- :green_book: Walk through Tutorial II based on self-built Tutorial I
- :blue_book: Tutorial II based on the [sample repo](https://github.com/redwoodjs/redwood-tutorial)[](https://community.redwoodjs.com/t/community-help-wanted-help-qa-the-new-improved-tutorial/2825#reporting-an-issue-5) (The sample repo is the final state of Tutorial I)
 
## :exclamation: Reporting an Issue

If you find something, you can report below ⬇️, [open an issue](https://github.com/redwoodjs/redwood/issues/new):rotating_light: against the [redwood](https://github.com/redwoodjs/redwood) repository or feel free to [open a PR](https://github.com/redwoodjs/redwood/compare):arrow_heading_down: if you want to fix it yourself. We love [contributors](https://redwoodjs.com/docs/contributing-overview)[](https://community.redwoodjs.com/t/community-help-wanted-help-qa-the-new-improved-tutorial/2825#final-thoughts-6). :heart:

Be sure to include the following in your report:

- :hash: Node Version
- :desktop_computer: OS
- :keyboard: any commands that failed
- :x: error messages
- :camera_flash: screenshots
- :open_book: which part of the Tutorial you were working on
- etc…

## :thought_balloon: Final Thoughts
Feel free to reach out to core team members on this issue, in the [forums](https://community.redwoodjs.com/t/community-help-wanted-help-qa-the-new-improved-tutorial/2825) :fountain_pen:, or on [Discord](https://discord.gg/redwoodjs) :speech_balloon: if you need any assistance.

Go forth and help make Redwood even better. :woman_technologist::man_technologist::rocket:

>By helping each other be successful with Redwood, we make the Redwood project successful. :heart:

**Comment by Josh-Walker-GM** [comment]
We're always happy to receive feedback on our tutorial so everyone should keep doing so.

I'm closing this because our tutorial has been out now for a while and we no longer need this particular issue open.
