### ISSUE TITLE
Tutorial II issue - When using the example repo - seed not used

### ISSUE THREAD

**Issue by jacebenson** [redwoodjs/redwood#4833]
I'm not sure if there was something I missed but nothing triggered the `yarn rw exec seed` and it should have been called out either in the tutorial or in the example repo.

**Comment by thedavidprice** [comment]
cc @cannikin

**Comment by cannikin** [comment]
Did you run `yarn rw prisma migrate dev` after cloning? Seeds should be automatically run after that command, as well as `yarn rw prisma migrate reset`.

**Comment by jacebenson** [comment]
Sorry, I'm reopening.  I made a video of me running through this and was able to tack down exactly what I did.
1. Cloned the example. ([0:11](https://youtu.be/qpc3shFh1tM?t=11))
2. Ran `yarn` to install the dependencies ([0:28](https://youtu.be/qpc3shFh1tM?t=29))
3. Ran `yarn rw dev` Saw no records ([1:51](https://youtu.be/qpc3shFh1tM?t=111))
4. Noticed I missed `yarn rw prisma migrate dev`, ran that.([2:52](https://youtu.be/qpc3shFh1tM?t=172))
5. Ran `yarn rw dev` to load the dev server ([3:34](https://youtu.be/qpc3shFh1tM?t=214))
6. Server loaded with no seeded data ([4:00](https://youtu.be/qpc3shFh1tM?t=240))

**Comment by cannikin** [comment]
Hmm strange, wonder if that could be getting left out on Windows?

Here's what happens when I run it (`yarn rw prisma db seed` runs after the migrate completes): https://youtu.be/XmaZGST98IA

**Comment by cannikin** [comment]
@Tobbe Do you still have a Windows machine laying around? When you run `yarn rw prisma migrate dev` does it automatically run the `prisma db seed` command afterwords?

**Comment by Tobbe** [comment]
I use my son's computer, but he just went to bed and I don't want to go disturb him. I can test it for you tomorrow.

That said, I've also experienced `seed` not running after migrating (on my MBP). It happened while I was talking to Thomas

---

![image](https://user-images.githubusercontent.com/30793/159995702-86fa0618-0f17-42dd-9075-b1b9aee87b89.png)

noire_munich  [08:58]
that worked
seed?

Tobbe Lundberg [08:59]
hmm
I thought it would run that automatically for me, but I guess not

noire_munich [09:01]
i'd have expected that as well actually 🤔

**Comment by thedavidprice** [comment]
Great find, all. But blast this seems like Windows bug with Prisma (very likely).

@dac09 Is there a (simple) way to add a functional test for this in the CI Smoke Test? E.g. You're starting the server and clicking pages here, but it doesn't seem like we ever migrate dev (or migrate reset), seed DB and check for Post content:
https://github.com/redwoodjs/redwood/blob/1a78f8583bd56a5828b795de0510f6133a159058/tasks/smoke-test/tests/common.ts#L15-L30

**Comment by cannikin** [comment]
Hmm, well in the meantime I can just include the `seed` command and if it runs twice, no biggie.

**Comment by dthyresson** [comment]
Prisma says it will seed on migrate, but my impression is it seeds on reset: https://www.prisma.io/docs/guides/database/seed-database#integrated-seeding-with-prisma-migrate. 

or according to the scenarios they document here:

If there is significant  drift, then it will seed on a dev:


> Prisma Migrate resets the database and triggers seeding in the following scenarios:
> 
> * You manually run the prisma migrate reset CLI command.
> *The database is reset interactively in the context of using prisma migrate dev - for example, as a result of migration history conflicts or database schema drift.
> *When you want to use prisma migrate dev or prisma migrate reset without seeding, you can pass the --skip-seed flag

Actually, I don't want a seed on dev. Why would I want to add the same data I have, if I just add a column?

I can simply run `db reset` if so.

So, I don't think this is an issue, just a clarification perhaps to the docs.

**Comment by cannikin** [comment]
Hmm so they should definitely run on first migrate, after cloning a repo you’d think? The original problem was that after checking out the tutorial repo that it didn’t seed. I can just add that as an additional step after clone that you also seed. They’re idempotent so it won’t hurt.

**Comment by dthyresson** [comment]
> after checking out the tutorial repo that it didn’t seed.

Ah, I see. I bet that the SQLite db in the repo maybe hasn't drifted? So, therefore Prisma won't seed.

> They’re idempotent so it won’t hurt.

:+1:

**Comment by jtoar** [comment]
@cannikin We didn't add the extra seed step yet did we? It'd be in the [intermission](https://redwoodjs.com/docs/tutorial/intermission) right?

**Comment by cannikin** [comment]
Yes! Just added it (finally).
