### ISSUE TITLE
Tutorial II - Our First Test - errors not quite right.

### ISSUE THREAD

**Issue by jacebenson** [redwoodjs/redwood#4835]
I was going through the tutorial and when we were expecting a specific error the actual error is slightly differnet in the docs.

Expected error is a little different than actual error;
Actual error is ...

```
 FAIL   web  web/src/components/ArticlesCell/ArticlesCell.test.js (10.484 s)
  ● ArticlesCell › Success renders successfully                                                               
                                                                                                              
    **TestingLibraryElementError: **Unable to find an element with the text: Neutra tacos 

```

This is what is in the docs today: https://user-images.githubusercontent.com/300/153312402-dd7f08bc-e23d-4acc-8202-cdfc9798a911.png

This is what I saw on the terminal
![image](https://user-images.githubusercontent.com/638764/159142824-02d93fdc-09a1-4eaa-8179-81e527b8913b.png)

**Comment by thedavidprice** [comment]
cc @cannikin

**Comment by cannikin** [comment]
Next time I go through the tutorial and get to this step I'll be sure to take a new screenshot and replace!

**Comment by jtoar** [comment]
@cannikin do you remember if you got around to this one? I think the main difference in the screenshots is the `TestingLibraryElementError` bit that comes before the hipster ipsum

**Comment by cannikin** [comment]
Haven't got to it yet. I don't think it's a huge deal, basically just the name/description of the error that's being thrown right? I'm just focused on that huge block of text output showing you what's different.

**Comment by jtoar** [comment]
Thanks @nikfp!
