### ISSUE TITLE
[Generator] Scaffold Component `.js` throws Error on NULL values

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#484]
See original topic from the forum:
https://community.redwoodjs.com/t/dealing-with-null-values/464

> One of the const in the components is: truncate, that truncates the length of the returned value to the defined max 150 characters. This definition of the const doesn’t correctly handle NULL values.

> The const before the correction (as created by the scaffold action):
```javascript
const truncate = (text) => {
  let output = text
  if (text.length > MAX_STRING_LENGTH) {
    output = output.substring(0, MAX_STRING_LENGTH) + '...'
  }
  return output
}
```
> The corrected function should include ‘text && ’ to ‘text.length’
```javascript
const truncate = (text) => {
  let output = text
  if (text && text.length > MAX_STRING_LENGTH) {
    output = output.substring(0, MAX_STRING_LENGTH) + '...'
  }
  return output
}
```

Here’s the source code:
https://github.com/redwoodjs/redwood/blob/955c3612a7ab56020b2af54974135470a66f6ac6/packages/cli/src/commands/generate/scaffold/templates/components/Names.js.template#L14-L20

And the corresponding test fixture:
https://github.com/redwoodjs/redwood/blob/955c3612a7ab56020b2af54974135470a66f6ac6/packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/index.js#L14-L20

**Comment by kwyoung11** [comment]
Took a stab at this in #485
