### ISSUE TITLE
[Docs] Authentication docs for Netlify reference a section of the tutorial that no longer exists

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#4860]
https://redwoodjs.com/docs/authentication#netlify-identity-widget

Says to follow the instructions in the tutorial for enabling the Netlify Identity Widget but we use dbAuth in the tutorial now.

**Comment by jtoar** [comment]
@cannikin I think you may have removed this info when you moved the docs over. I don't see it there anymore.
