### ISSUE TITLE
[Tutorial] Add note about TEST_DATABASE_URL

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#4894]
If someone sticks with their current codebase as they get into the second half of the tutorial, and they switched over their database to Postgres, they're going to get an error when trying to run the test suite for the first time: 

```
Environment variables loaded from .env
Prisma schema loaded from api/db/schema.prisma
Error: Get config: Schema Parsing P1012

error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
  -->  schema.prisma:3
   | 
 2 |   provider = "postgresql"
 3 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1

● Validation Error:

  An unknown error occurred in @redwoodjs/testing/config/jest/api:
```

Let's add a note about setting the TEST_DATABASE_URL env var if they're using Postgres. This is covered in the [Local Postgres Setup](https://redwoodjs.com/docs/local-postgres-setup) doc, but if you didn't follow that you would have no idea.

New language will go here: https://github.com/redwoodjs/redwood/blob/main/docs/docs/tutorial/chapter5/testing.md

**Comment by Isaac-Tait** [comment]
Can I work on this doc update?

**Comment by Isaac-Tait** [comment]
I came across this issue after working through the "Deployment" [section](https://github.com/redwoodjs/redwood/blob/main/docs/docs/tutorial/chapter4/deployment.md) of the starter docs. Perhaps it would be better to update the docs at the 4th Chapter *Deployment* section instead of Chapter 5 Testing? Thoughts?
