### ISSUE TITLE
v1.0.0-rc.final.1 release notes routes.ts|js change to routes.tsx|js 

### ISSUE THREAD

**Issue by vchoy** [redwoodjs/redwood#4897]
Very minor correction

page:
https://github.com/redwoodjs/redwood/releases/tag/v1.0.0-rc.final.1

in the section
Update roles for role in Private routes and Sets:

the file affected; Routes.ts please change to Routes.tsx
the |js bit works. 

Thanks.

**Comment by vchoy** [comment]
I'm in the process of coverting my js to tsx..

as per: https://github.com/redwoodjs/redwood/blob/main/packages/create-redwood-app/template/web/src/Routes.tsx

**Comment by thedavidprice** [comment]
Done! Thanks again!!
