### ISSUE TITLE
0.50.0 regression where errors are masked even for the api server

### ISSUE THREAD

**Issue by twodotsmax** [redwoodjs/redwood#4913]
I noticed last night that after pulling all the stuff included in 0.50.0 on my local redwood framework dev branch, I was getting 'Something went wrong' on the api side as well as on the web side. This meant that even Prisma errors, etc. were being masked.

See fix: https://github.com/redwoodjs/redwood/pull/4912

See forum post / complaint: https://community.redwoodjs.com/t/unreasonably-opaque-graphql-errors-non-error-thrown-as-error/2905

**Comment by twodotsmax** [comment]
Made a PR on redwoodjs/redwood: https://github.com/redwoodjs/redwood/pull/4912

**Comment by dthyresson** [comment]
Thanks @twodotsmax! Have added comments to the PR as I had a draft fix in -- but #4912 might be a better solution. Asking the Guild to review.
