### ISSUE TITLE
Missing auth information in tutorial

### ISSUE THREAD

**Issue by npostulart** [redwoodjs/redwood#4927]
Going through the tutorial there is a little part missing about implementing the checks for the `hasRole` function inside the `api/src/lib/auth.js` file.

It just works by commenting out lines 58 and 62.

**Comment by thedavidprice** [comment]
looping in @cannikin 

@npostulart would you be able to help with a PR given direction? No pressure, but it would be helpful. Thanks for creating this Issue!

**Comment by npostulart** [comment]
Of course: here you go #4929

**Comment by cannikin** [comment]
Fixed in the redwood-tutorial code!
