### ISSUE TITLE
More specific documentation to validateUniqueness

### ISSUE THREAD

**Issue by LotuxPunk** [redwoodjs/redwood#4939]
## Problem

Returning validateUniqueness doesn't return the actual result of the callback but throw : 'promises.map is not a function' instead if you don't enable `previewFeatures = ["interactiveTransactions"]`.

## Soluce

Adding a clearer message could probably help other users to avoid those kind of troubles:

> Being able to use transactions with the above syntax is experimental for Prisma as of v2.29.0, so you need to enable it as a preview feature. In your api/db/schema.prisma file:

to :

>Being able to use transactions or validateUniqueness with the above syntax is experimental for Prisma as of v2.29.0, so you need to enable it as a preview feature. In your api/db/schema.prisma file:

## Reference

Documentation : https://redwoodjs.com/docs/services#validateuniqueness

**Comment by dthyresson** [comment]
I chatted with @LotuxPunk on Discord about this issue, and we both missed the crucial point that `previewFeatures = ["interactiveTransactions"]` needed to be enabled as it came after the code examples which was used.

The phrase `Being able to use transactions` made it sound like that referred to the "equivalent code example":

<img width="916" alt="image" src="https://user-images.githubusercontent.com/1051633/160256195-cf21e3c3-446e-4aa3-8121-3331c8d92b1d.png">

And not the `validateUniquess` syntax.

Perhaps a note to enable the feature or a note to mention the error message and away to correct would help?

See: https://redwoodjs.com/docs/services#validateuniqueness

Once the feature was turned on, the validation worked as expected.

**Comment by cannikin** [comment]
I came across this code the other day and made a mental note to ask: is this still only in preview I wonder? Although it sounds like the OP was getting an error without it so I guess so!

I’m out this week so if someone wants to take this, be my guest! I’ll be checking in periodically and can make a PR approval if needed.
