### ISSUE TITLE
Lack of access to Fastify App Object in Redwood Project

### ISSUE THREAD

**Issue by twodotsmax** [redwoodjs/redwood#4945]
Recently, I wanted to log every HTTP body going in and out of Fastify. This is not supported by Fastify via their default Pino setup, because request bodies are not parsed before the request is logged to Pino. The workaround is something like this in Redwood Framework's app.ts:

```
const app = Fastify(options || DEFAULT_OPTIONS)
  app.addHook('preHandler', function (req, _, done) {
    req.log.info(
      { ... },
      'request body'
    )
    done()
  })
  app.addHook('onSend', function (_request, reply, payload: string, next) {
    let body = payload
    try {
      body = JSON.parse(payload)
    } catch (err) {
      body = payload
    }
    reply.log.info(
      { ... },
      'response body'
    )
    next()
  })
```

I notice that Redwood can read the server config out of server.config.js or a configured path, but there is no way to configure "app" directly. Is there a reason to avoid exposing "app" to the Redwood Project, maybe by calling a user-defined function in createApp?

**Comment by dthyresson** [comment]
@dac09 Remember when we were implementing Fastify and we did the server config, I think we considered exposing the app (or a "BYO server" idea). 

I think that as the api-server enters more use (perhaps with the new [baremetal deploy](https://redwoodjs.com/docs/deploy/baremetal)? ) additional configuration and setup can be considered.

> by calling a user-defined function in createApp

That could be an option. @twodotsmax  Would you be interested in a PR to do that?

Or - we can treat this issue like an RFC and do some design here to review.

**Comment by dac09** [comment]
If you wanted to achieve request logging, you can probably achieve this with the Redwood logger @twodotsmax

The reason, IMHO, it is the better option is because it is deployment agnostic. 

Say you configure the Fastify app, then decide, hey I want to deploy to Vercel now, you'd have to do a little or a lot of refactoring depending on how much you've locked yourself into.

That being said, we will probably let you bring your own server at some point, but certainly not priority for v1.

**Comment by dthyresson** [comment]
> you can probably achieve this with the Redwood logger @twodotsmax

@dac09 make a great point: you have access to the complete event in your service as well as serverless function -- and that event has the complete event and requestContxtd info (headers, query params, etc) so you can use the logger to surface that info.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/1051633/160382596-b6fa712d-f5f7-461a-acba-28f96fa74b7f.png">

<img width="552" alt="image" src="https://user-images.githubusercontent.com/1051633/160382752-a46a038e-57d5-4549-9a14-e75f7f6486a3.png">

If you need to log that info in production, just be sure to set your logger's level to `debug` (as we default it to `warn` in production).

See: https://redwoodjs.com/docs/logger#log-level

**Comment by twodotsmax** [comment]
Thanks guys. Part of me feels logging in the function is probably fine, but I wonder about:
1. Scalability of having an eng team add functions and have to think about logging their requests in a standard way instead of an automagical approach
2. There is some non-trivial code standing between Fastify and the actual Function invocation... so ideally I'd be able to see Fastify HTTP interactions as well as the Function calls

**Comment by twodotsmax** [comment]
Will follow up with a PR for the createApp hook

**Comment by jtoar** [comment]
https://github.com/redwoodjs/redwood/pull/5903 will add this feature.
