### ISSUE TITLE
something went wrong in graphql playground

### ISSUE THREAD

**Issue by bobwatcherx** [redwoodjs/redwood#4946]
![dongo](https://user-images.githubusercontent.com/52072811/160273598-de4792dc-dcba-4dc7-9345-0f39321ecff2.png)

i follow redwood tutorial
from prisma , migration, and SDL 
but i have error like that

my tables is not empty , i using sqlite db

**Comment by dthyresson** [comment]
Hi @bobwatcherx I also responded to your Discourse post here: https://community.redwoodjs.com/t/error-something-went-wrong/2786/14?u=dthyresson.

This PR fixes the masked error case and will be in the next patch: https://github.com/redwoodjs/redwood/pull/4912

However, I don't know what is causing the error -- it may be database related, so as I noted in the post above, I suggest adding Prisma logging to see the sql and and error.
