### ISSUE TITLE
Entering `rs` in redwood dev server terminal does nothing (does not restart)

### ISSUE THREAD

**Issue by Philzen** [redwoodjs/redwood#4952]
Supposedly, one can restart the redwood dev server at any time by typing <kbd>rs</kbd> in the terminal currently executing `yarn rw dev`:

![grafik](https://user-images.githubusercontent.com/1634615/160491250-77802837-2dc2-4128-976a-c22bb48b4492.png)

However, nothing happens when i do as advised by that message.

It's not like i ever had to rely on restarting so far, the redwood server dev-server turns out to be very resilient – in stark contrast to the storybook server (where autorefresh misses any updates to theme customizations and it needs to be completely restarted whenever the addons-config is changed) – but i wanted to report this, so either the advice can be removed or this can be fixed.

**Comment by simoncrypta** [comment]
Hi @Philzen Thanks for reporting this ! :smiley: 

>  but i wanted to report this, so either the advice can be removed or this can be fixed.

I wonder where is the advice for `rs`, I never see this before ?

**Comment by simoncrypta** [comment]
> so i suppose this is coming from the nodemon component 

You right ! It's there, let me check if is supposed to work, if not we just need to change the default config of nodemon
https://github.com/remy/nodemon/blob/0823f18435e43639f3b6b9f296b7385e99cffa3b/lib/nodemon.js#L149

**Comment by simoncrypta** [comment]
Feel like we have no way to change this config with our current implementation of nodemon. Since @dac09 works on dev CLI recently I take my chance to ask, is it possible to use a file like `nodemon.json` to add all our nodemon config for `yarn rw dev` ?
https://github.com/remy/nodemon/wiki/Sample-nodemon.json

**Comment by dac09** [comment]
I think we should just remove the message if possible. I don't think we should commit to having a nodemon.json - and as the issue mentions, our watching doesn't seem to have issues that often!

**Comment by simoncrypta** [comment]
@dac09 having a nodemon.json is actually to remove the message, I didn't find a way to change the default config for that otherwise.

**Comment by thedavidprice** [comment]
Yeah, that output is meaningless in the context of `rw dev`. What would happen if we just suppressed nodemon default output. Don't we just need to know state, e.g. "started", "error", "stopped"?

**Comment by simoncrypta** [comment]
> What would happen if we just suppressed nodemon default output.

I tried nodemon with `--quiet` option and I like it ! I don't think we need nodemon output. 

> Don't we just need to know state, e.g. "started", "error", "stopped"?

From their [wiki](https://github.com/remy/nodemon/wiki)  : 
"Minimise nodemon messages to start/stop only."

I tried to reproduce as many type of error I can and it's works, but I don't know what kind of specific error for nodemon I can reproduce to see what happen.
