### ISSUE TITLE
Linting Import Ordering

### ISSUE THREAD

**Issue by nickpdemarco** [redwoodjs/redwood#4953]
On a freshly created Redwood project, it seems that import ordering is not enforced by `yarn rw lint`. Here's a basic setup:

``` bash
$ yarn create redwood-app x-repro-lint
$ cd x-repro-lint
# Not necessary to repro, but gives a good example of imports to sort.
$ yarn rw setup ui chakra-ui 
$ yarn rw lint web/src/App.js
$ # Note no output, implying linting passed.
```

Now, let's take a look at `App.js`:

```javascript
import { ChakraProvider, ColorModeScript } from '@chakra-ui/react'
import { FatalErrorBoundary, RedwoodProvider } from '@redwoodjs/web'
import { RedwoodApolloProvider } from '@redwoodjs/web/apollo'

import FatalErrorPage from 'src/pages/FatalErrorPage'
import Routes from 'src/Routes'

import './index.css'

// Remainder of file omitted
```

We have `@chakra-ui/react` imported above `@redwoodjs/*`, which seems to violate our `.eslint.js` configuration. Note that if we switch this order, and rerun the linter, there's still no complaint. Presumably one of these orders is wrong, and should be logged.

In newly-generated projects, `package.json` shows:

```json
  "eslintConfig": {
    "extends": "@redwoodjs/eslint-config",
    "root": true
  },
```

which is generated from `packages/eslint-config`. In there, the [README suggests we sort imports](https://github.com/redwoodjs/redwood/blob/main/packages/eslint-config/README.md#purpose-and-vision) but if you look at the relevant code, it doesn't seem to do anything:

[`shared.js` does include the `import` plugin](https://github.com/redwoodjs/redwood/blob/main/packages/eslint-config/shared.js#L28), but neither it nor [`index.js`](https://github.com/redwoodjs/redwood/blob/main/packages/eslint-config/index.js) in that same directory use it.

Though, we do specify `import/order` in the [Redwood Framework root .eslintrc.js](https://github.com/redwoodjs/redwood/blob/main/.eslintrc.js#L34), so it seems to me that this is just a misplaced configuration. 

# Easy Fix!

To fix this issue, I propose we simply move the `import/order` rules into `packages/eslint-config/shared.js` so we can match the behavior described in the documentation and get import linting working for generated projects as well as the framework. 

I'm happy to raise a PR to do this, if needed.

**Comment by dthyresson** [comment]
> I'm happy to raise a PR to do this, if needed.

Please do. Then others can review and give feedback. Thanks!
