### ISSUE TITLE
Use ref to reset form

### ISSUE THREAD

**Issue by vikash-eatgeek** [redwoodjs/redwood#498]
@cannikin I was watching the 3rd part in the youtube RedwoodJS series. Great videos. 👏 
I saw that we were importing the `react-hook-forms` to reset the form using `fromMethods.reset()`.
I was just giving a thought, Could we use ref to reset the form? if we use ref, the developer doesn't need to import `react-hook-form`. What do you think about this approach? 
I think, through `ref` something like this  `formElement.current.reset()` will reset the form. thanks!!

**Comment by thedavidprice** [comment]
pin @cannikin

**Comment by cannikin** [comment]
@vikash-eatgeek Sorry for the late reply, this slipped under my radar! 

I actually haven't done much with refs in React, how would you see this working? Can Redwood always add a ref to the `<Form>` and then you can choose to import it along with the other form helpers and use it if needed?

**Comment by vikash-eatgeek** [comment]
thanks, @thedavidprice @cannikin for getting back to me on this issue. I need to look back into this task/issue. I will get back to you guys probably over the weekend. :)

**Comment by jtoar** [comment]
@vikash-eatgeek using a ref seems like a valid approach, but it's probably a good idea to stick to react-hook-forms for the tutorial at least, if only to show that @redwoodjs/forms still allows access to all of react hook forms' "lower-level" APIs. I'll close this out for now but if you feel strongly feel free to ping us back here!
