### ISSUE TITLE
Embedded YouTube video in tutorial's Chapter 3/Forms page is marked as private

### ISSUE THREAD

**Issue by ofu997** [redwoodjs/redwood#4988]
See link
[https://redwoodjs.com/docs/tutorial/chapter3/forms](https://redwoodjs.com/docs/tutorial/chapter3/forms)

**Comment by jtoar** [comment]
Thanks @ofu997! It's probably still under development, but I'll tag @cannikin for a final answer.

**Comment by thedavidprice** [comment]
Try now!
