### ISSUE TITLE
[Tutorial w/TypeScript] Warning: 'ArticlesCell' return type 'Element[]' not a valid JSX element.

### ISSUE THREAD

**Issue by Philzen** [redwoodjs/redwood#5008]
Working through the tutorial in TypeScript mode, VSCode complains about the `ArticlesCell` return type:

![grafik](https://user-images.githubusercontent.com/1634615/161425728-a6b19f1d-12cc-4bc9-8314-18c4af731964.png)

Interestingly, the warning doesn't appear while the `Success` function still returns the Articles wrapped in `<ul>`, it only starts appearing when we change them to render as individual `<article>`s as advised at the end of https://redwoodjs.com/docs/tutorial/chapter2/cells#our-first-cell

However, wrapping `<ArticlesCell />` in a fragment or a div in `Homepage.tsx` does not make the warning go away.

Compilation succeeds nevertheless so it's possible to continue the tutorial, but still it would be nice to know which type to annotate the cell with so this warning goes away.

Reporting this non-critical finding here [as advised](https://github.com/redwoodjs/redwood/issues/234#issuecomment-1086800949).

**Comment by Philzen** [comment]
Suggestion: enhance the tutorial code snippets with a TypeScript tab so that first-timers can also learn about the correct types while working through it.

**Comment by Philzen** [comment]
@simoncrypta I've created a [repository that follows each of the steps](https://github.com/Philzen/redwoodblog-tutorial/commits/main) for your convenience, you can checkout / reset to https://github.com/Philzen/redwoodblog-tutorial/commit/2acdd8432a5b67c732e1805bc4637eb4aa4b70fc and play that through yourself.

**Comment by simoncrypta** [comment]
Typescript see success as an array of element (but I think it should be an array of component, but I don't know if this really change something) which is not, like the error say, a valid JSX component. I wrap the map function inside a React fragment to fix this. Maybe we should have done this way in the tutorial, but I let @cannikin decide what he thinks about that. 
```
// web/src/components/ArticlesCell/ArticlesCell.tsx

[...]

export const Success = ({ articles }: CellSuccessProps<ArticlesQuery>) => {
  return (
    <>
      {articles.map((article) => (
        <Article key={article.id} article={article} />
      ))}
    </>
  )
}
```

**Comment by simoncrypta** [comment]
Also, the error will be fixed later in the tutorial 
```
export const Success = ({ articles }) => {
  return (
    <div className="space-y-10">
      {articles.map((article) => (
        <Article article={article} key={article.id} />
      ))}
    </div>
  )
}
```

**Comment by Philzen** [comment]
> I wrap the map function inside a React fragment to fix this. Maybe we should have done this way in the tutorial, but I let @cannikin decide what he thinks about that.
> ```typescript 
> // web/src/components/ArticlesCell/ArticlesCell.tsx
> export const Success = ({ articles }: CellSuccessProps<ArticlesQuery>) => {
>   return (
>     <>
>       {articles.map((article) => (
>         <Article key={article.id} article={article} />
>       ))}
>     </>
>   )
> }

Thanks, of course that is the obvious solution and makes the error go away :+1:  ... why didn't i think of that – i did actually try React fragment around `<ArticlesCell />` but of course that's the same difference :facepalm: :laughing: 

IMHO it should be done that way for the time being in chapter 2 so RedwoodJS learners are left with valid code until they get to chapter 5.
