### ISSUE TITLE
Can't work with elm-react-component

### ISSUE THREAD

**Issue by dowdiness** [redwoodjs/redwood#501]
Hi.

I added elm-webpack-loader and elm-hot-webpack-loader to my webpack config in order to use Elm in my redwood project. However, it doesn't work with [elm-react-component](https://github.com/Parasrah/elm-react-component). I suspect redwood default webpack config affected elm-webpack-loader.

I also made an issue on  elm-react-component
https://github.com/Parasrah/elm-react-component/issues/39

My repository
https://github.com/dowdiness/hello-redwood/pull/1

Working Website
https://5eae0852b7c7290006ff335d--hello-redwood.netlify.app

**Comment by thedavidprice** [comment]
Hi @dowdiness Excited you are trying out Redwood! And how is it going with this issue? 

I do not have any experience with Elm or these packages. I did take a look at the Issue you reference above, but there wasn't much I could interpret there about how Redwood config is affecting this.
