### ISSUE TITLE
Global Authentication State (querying outside of Cells)

### ISSUE THREAD

**Issue by raph90** [redwoodjs/redwood#5012]
I've started a Redwood project (it's awesome by the way, thank you everyone for the hard work) and I'm using Auth0 for authentication. I've managed to set up the authentication correctly, but I'm struggling to implement a particular flow. 

When a user logs in (using Auth0) I want to check if they've logged in before. If not, I want to redirect them to a page where they can add more details about themselves. I'm going to check if they've logged in before by using the email address provided during authentication (accessing this with `getCurrentUser()`). 

So the flow is:
- the user authenticates
- in the Layout wrapper (for me, called MainLayout) I want to call a query that looks in the database for a record with that email address
- redirect to /users/new if there is no-one there. 

So in my layout I have something that looks like this:
```javascript
export const QUERY = gql`
  query UserQuery($email: String!) { // I've added this to services and to the sdl
    user: userByEmail(email: $email) {
      id
      email
    }
  }
`

const MainLayout = ({ children }) => {
  const { logIn, logOut, isAuthenticated, userMetadata, getCurrentUser } =
    useAuth()

  useEffect(() => {
    const checkCurrentUserAndRedirect = async () => {
      try {
        const user = await getCurrentUser()
        const userInDb = await // how do I actually call QUERY above? 
      } catch (err) {
         console.log(err)
        return;
      }
      if (!userInDb) {
           // redirect to /users/new
      }
    }
    checkCurrentUserAndRedirect()
  }, [])
```

Is the only way to call this to use a Cell? It seems to me that cells aren't really for this kind of use case, but I could use props.children and use a Cell to wrap my layout contents...

It would be great to hear from Redwood contributors about the 'Redwoody' way to solve this problem. I can also absolutely take this to SO if this isn't the place for this question.

Many thanks.

**Comment by jtoar** [comment]
Hey @raph90 glad to hear you're liking the framework so far!

> Is the only way to call this to use a Cell? It seems to me that cells aren't really for this kind of use case, but I could use props.children and use a Cell to wrap my layout contents...

I think your intuition is right; a Cell seems like overkill here. A one-off query may be better. You can import `useApolloClient` to do just that:

```js
import { useApolloClient } from '@apollo/client'

// ...

// Call this before or after useAuth, just not in useEffect; rules of hooks
const client = useApolloClient()

// ...

// In useEffect
const res = await client.query({ query: QUERY })
const { user } = res.data // If everything went well, user's on here

// ...
```

There may be a better way to that still, but see if that works and let me know what you think.

- `useApolloClient` https://www.apollographql.com/docs/react/api/react/hooks/#useapolloclient
- `client.query` https://www.apollographql.com/docs/react/api/core/ApolloClient#ApolloClient.query

**Comment by raph90** [comment]
Thanks @jtoar, I'll give this a try 🙌

**Comment by jtoar** [comment]
Hey @raph90 did that end up working for you?

**Comment by raph90** [comment]
@jtoar it did! Many thanks for your help, and my apologies for the late reply.
