### ISSUE TITLE
[Tutorial] GraphQL Playground screenshots need update (and show a wrong datatype)

### ISSUE THREAD

**Issue by Philzen** [redwoodjs/redwood#5016]
1. The screenshots on https://redwoodjs.com/docs/tutorial/chapter3/saving-data don't reflect the current state of the way the playground looks, mainly the docs on the left are now on their own, while the "schema" explorer is now on the left and just called "Exporer". But most importantly, the awesome "Redwood GraphQL Playground" logo is missing :wink: 
2. The datatype of the posts id in the third screenshot on that page seems wrong:  
    ![tutorial-screenshot](https://user-images.githubusercontent.com/300/70951466-52e0f580-2018-11ea-91d6-5a5712858781.png)  
   It shows as `String`, but actually is `Int` following the tutorial:  
   ![grafik](https://user-images.githubusercontent.com/1634615/161443057-48c14686-8346-44f6-8752-d4e940462057.png)

**Comment by thedavidprice** [comment]
Thanks @Philzen 🚀

Looping in @cannikin
