### ISSUE TITLE
Cannot get to the Tutorial from a locally built welcome application

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood#5019]
### Steps

1. Build the **Welcome to RedwoodJS application**
2. Click on the big Tutorial button
3. "The Welcome" page is rendered again (instead of the local version of the `https://redwoodjs.com/docs/tutorial/foreword` page

---
---

Just tried to build the Redwood blog app, as explained on the https://redwoodjs.com/docs/tutorial/chapter1/installation page. The app builds fine and the browser pointed to `http://localhost:8910/` renders as

![image](https://user-images.githubusercontent.com/2712405/161454517-c48a4956-9cc7-44ef-ad53-a438174fcdde.png)

If you click on the big red Tutorial button - instead of getting to the tutorial home page fetched from the redwoodjs.com  (https://redwoodjs.com/docs/introduction)

![image](https://user-images.githubusercontent.com/2712405/161454611-cf72823b-9758-477b-9185-eea0fdbdbc36.png)

you land on the same application home page (this time the URL is http://localhost:8910/docs/tutorial/foreward)

![image](https://user-images.githubusercontent.com/2712405/161454517-c48a4956-9cc7-44ef-ad53-a438174fcdde.png)

**Comment by jtoar** [comment]
Thanks @adriatic!

**Comment by adriatic** [comment]
I feel **nearly** the same responsibility for RedwoodJS  as you do, Dominic
