### ISSUE TITLE
Docs translation to Spanish

### ISSUE THREAD

**Issue by slf188** [redwoodjs/redwood#5035]
Hey everyone from **RedwoodJS**,
I'd like to be part of this open-source community, perhaps I can help translate the documentation to Spanish and Mandarin in the near future??
Greetings from Ecuador!

**Comment by KrisCoulson** [comment]
Hey @slf188 we just recently ended our translation efforts for the time being. You can check out a detailed post about our learnings and what to look forward to in the future [here](https://community.redwoodjs.com/t/announcement-ending-the-tutorial-translation-project-for-now/2931)

That being said translations aren't the only way to be a part of this community. You can check out how to get started in the community [here](https://community.redwoodjs.com/t/getting-started-as-a-contributor/2752)

**Comment by slf188** [comment]
Great thanks for the info! I'll check the link asap :)
