### ISSUE TITLE
[Tutorial/TypeScript] TS warning when no RBAC scheme is implemented

### ISSUE THREAD

**Issue by Philzen** [redwoodjs/redwood#5038]
Reporting this non-critical finding here [as advised](https://github.com/redwoodjs/redwood/issues/234#issuecomment-1086800949):

Discovered in https://redwoodjs.com/docs/tutorial/chapter4/authentication#an-admin-section

The `auth.ts` file generated by `yarn rw setup auth dbAuth` expects a roles property to exist on the user object. However, implementers may choose (like in this tutorial chapter) not to implement role-based access control.

In that case, we're getting 

```bash
Property 'roles' does not exist on type '{ id: number; email: string; }'.ts(2339)
```

in three places in `api/src/lib/auth.ts`.

Maybe there is way to expand the interface `InferredCurrentUser`, making this an optional field?

**Comment by Philzen** [comment]
Just commited this chapter to 35c479ac04a06c80f9000059efb86c5cb033ae6b if that helps.

**Comment by Tobbe** [comment]
Thanks for the issue report @Philzen. Do you want to have a look at fixing this, or do you want me to do that?

**Comment by Philzen** [comment]
@Tobbe it would be an honor, however i'm still relatively new to TypeScript and how to fix this relatively complex / inferred type (at least in the most appropriate way) seems a bit over the top of my head currently, i'm unsure which would be the correct spot.

If you have a clue, kindly go ahead with a fix.

**Comment by dac09** [comment]
Thanks again for yet another good issue @Philzen ✌️

This is expected behaviour, though I believe. We ship auth templates with the ability to handle roles, but there's no reason you _have_ to use it - all you have to do is remove the `hasRole` function if you don't want auth in your project. I think its a _good_ thing that you get that TypeScript error - imagine trying to implement Roles, if we made it optional - you wouldn't be able to spot that Roles isn't being picked out from the DB.

**Comment by thedavidprice** [comment]
**Off Topic**
@Philzen your participation is 🤯 It would be a pleasure to have you join a future Contributors Meetup if you're interested:
https://community.redwoodjs.com/t/contributors-meetups-a-next-step-for-redwoodjs-participation/2470

DM me `@thedavidprice` on Twitter, Forums, or Discord. And/or email via my GH profile.

Most of all, thank you! 🙏

_Someone else might have already invited you. Just know we're all super excited to have your help with these things._

**Comment by Tobbe** [comment]
> This is expected behaviour, though I believe. We ship auth templates with the ability to handle roles, but there's no reason you _have_ to use it - all you have to do is remove the `hasRole` function if you don't want roles in your project.
> 
> I think its a _good_ thing that you get that TypeScript error - imagine trying to implement Roles, if we made it optional - you wouldn't be able to spot that Roles isn't being picked out from the DB.

I can't decide if I agree or not here 😆

I love the help TS gives you in spotting errors like what you describe above. But I also don't like it when generated code is throwing errors in my face 🙂  Always leaves me with questions like "Have I done something wrong?", "Is the generator broken?", "What do I need to do to fix this?" etc.

I need to go through the tutorial with a TS project to see this for myself to be able to give any good suggestions on how to handle this

**Comment by Philzen** [comment]
I had totally forgotten about the fact i had written this issue when i handed in #5856  :laughing: 
Guess i lost track of it, sorry for not following up earlier.

@Tobbe 
> I also don't like it when generated code is throwing errors in my face :slightly_smiling_face Always leaves me with questions like "Have I done something wrong?", "Is the generator broken?", "What do I need to do to fix this?" etc

That's exactly what i think and feel like. Another important question to add "Is RedwoodJS somehow broken?" – something that should never be part of the DX. Imho it must not ever generate code that violates its own ESLint rules (see #5827) or worse (like in this case) generates invalid types that will make `yarn rw check-types` fail.

@dac09 
> imagine trying to implement Roles, if we made it optional - you wouldn't be able to spot that Roles isn't being picked out from the DB.

What about adding some JSDoc [here](https://github.com/redwoodjs/redwood/pull/5856/files#diff-19207f9f38a02daf1f1149d742fb1a430dedc189a1313a14a4487c6a03d4d438R11), linking to the `getCurrentUser` function and giving the heads-up that roles will always be undefined unless included in the selection ... would that suffice?

**Comment by Tobbe** [comment]
Discussion (also) continues in https://github.com/redwoodjs/redwood/issues/5866
