### ISSUE TITLE
Running a 2nd dev server kills the first one

### ISSUE THREAD

**Issue by Philzen** [redwoodjs/redwood#5039]
Not sure if this hasn't been reported before.

### Steps to reproduce the issue

1. Have a redwood project in Folder A and start `yarn rw dev`
2. Have a redwood project in Folder B and start `yarn rw dev`

### What happens

The terminal window running the dev server of project A reports:

```
cd "/home/user/redwood-project-A/web" && yarn cross-env NODE_ENV=development RWJS_WATCH_NODE_MODULES= webpack serve --config "/home/user/redwood-project-A/node_modules/@redwoodjs/core/config/webpack.development.js"  exited with code 1
```

However, the process is not terminated cleanly at that point, i still need to interrupt it with <kbd>CTRL</kbd>+<kbd>C</kbd>

### Expected behaviour

Either:
1. dev server B fails to start up b/c it checks the port and realizes there is already a service running
2. project B should startup at a different port range, possibly ask the use whether that is OK.

I've just crosschecked, when i run `yarn rw storybook` and port 7910 is already taken, it provides this gentle fallback:

```bash
? Port 7910 is not available. Would you like to run Storybook on port 7911 instead?
```

That maybe a nice / ideal thing to have for the redwood server well, e.g. offer to start up on 8920/8921, 8930/8931, and so on if the former are taken.

**Comment by realStandal** [comment]
Duplicate #4697

**Comment by Philzen** [comment]
Uhhh snap. Would have though so. Closing this in favour of https://github.com/redwoodjs/redwood/issues/4697
