### ISSUE TITLE
[Tutorial] Link to prisma connection limit has changed

### ISSUE THREAD

**Issue by Philzen** [redwoodjs/redwood#5041]
Under https://redwoodjs.com/docs/tutorial/chapter4/deployment#environment-variables there is the recommendation to append `?connection_limit=1` to DB connection URI.

In the Info-Box, there is supposed to be a link to an explanation on that recommendation. The Hash-Value for name/id on that URL actually doesn't exist on that page and no direct explanation is found there.

It seems to have been changed to https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#serverless-environments-faas

**Comment by thedavidprice** [comment]
@Philzen really appreciate all these details PRs! Truly helpful to get these things right.

Yup, Prisma overhauled this documentation. Looks really good now.

But for our purposes I think this is the closest section to what we originally linked.
https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#recommended-connection-pool-size-1
