### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by pavelloz** [redwoodjs/redwood#5050]
Hello,

I tried to optimize images from https://redwoodjs.com/ but I couldn't even find them in the repo.
Is is possible to check them out?

Im pretty sure there is a lot to gain in that department.
<img width="305" alt="image" src="https://user-images.githubusercontent.com/546845/161745397-e20ae5b7-e236-44aa-902e-e7ce80d91c1b.png">

Best, Paweł

**Comment by jtoar** [comment]
Hey @pavelloz thanks for looking at this! We've been at this on and off for a few days. First question: did you look in this repo for the images, or the https://github.com/redwoodjs/sprout repo? The latter houses the site. If you did and still couldn't find them, would you mind if I transferred the issue to https://github.com/redwoodjs/sprout?

**Comment by pavelloz** [comment]
Oh! I looked only in redwoodjs/redwood - I dont know why i assumed docs are in docs/ directory - i think i found that information somewhere. Thank you :)

**Comment by jtoar** [comment]
@pavelloz Ah gotcha; the introduction probably said that. The docs are in the docs directory, but the landing page site (everything that _isn't_ `/docs`) is in the redwoodjs/sprout repo. 

The URL's the same, but that's actually a ruse: there's a few Netlify redirects to stitch things together. Definitely a little confusing—sorry about that!
