### ISSUE TITLE
[Docs] Improve "local-postgres-setup" instructions

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#508]
Docs are now located in https://github.com/redwoodjs/redwoodjs.com 

For this specific doc, see:
https://github.com/redwoodjs/redwoodjs.com/blob/master/docs/localPostgresSetup.md

This doc should **not** include a deep dive on Postgres installation and setup, but it could be improved with things like the following:
- better explain "user" and "database" in the connection string, i.e. "postgres" and "redwoodblog_dev" -- the first must be created and the second will be created if it doesn't exist
- an example or link regarding how to create a user
- mention that local postgres server will need manual start/stop -- this is **not** handled automatically by RW CLI in a manner similar to sqlite
- link to a local DB tool like https://tableplus.com/

**Comment by guledali** [comment]
@thedavidprice prisma documentation they go through installing postgres for mac, windows and linux

https://www.prisma.io/docs/guides/database-workflows/setting-up-a-database/postgresql

**Comment by thedavidprice** [comment]
Sweet! That would be a great link to add. I still think it would be helpful to give an example of creating user and starting server in the RWJS doc. But open to ideas.

And leaving this one open for someone to help with a PR if/when they are interested.

**Comment by chaharshivam** [comment]
Hi @thedavidprice , new contributor here. May I take this up?

**Comment by thedavidprice** [comment]
@chaharshivam yes, please! Thanks so much in advance. 🚀

**Comment by thedavidprice** [comment]
Thanks again @chaharshivam 🎉

Closing this out
