### ISSUE TITLE
Can I call a backend service function from the Success function of the MainCell?

### ISSUE THREAD

**Issue by Montana** [redwoodjs/redwood#5080]
Hey all, 

I've seen a similar thread somewhere else - but I'm having the exact same issue. Let me try and explain this to the best of my ability.

My frontend files are working e.g. `Homepage.ts`, but I now want to start caching the results from a third party API. I've created a database table and a back-end "service" called `cachedQueries.ts` (using Prisma), which has:

```javascript
export async function getFromCacheOrFresh(key: string, getFresh: Function, expiresInSec: number): Promise<any> {
  const nowMoment = dayjs.utc();
  const nowStr = nowMoment.format(dbTimeFormatUtc);
  const cached = await getCachedQuery({ key, expiresAtCutoff: nowStr });
  console.log('getFromCacheOrFresh cached', cached);
  if (cached) {
    const cachedValueParsed = JSON.parse(cached.value);
    console.log('cachedValueParsed', cachedValueParsed);
    return cachedValueParsed;
  } else {
    const fresh = await getFresh();
    saveToCache(key, JSON.stringify(fresh), expiresInSec);
    return fresh;
  }
}
```

While doing some local testing, I've proven that this `cachedQueries.ts` service works and properly saves to and retrieves from the database  _e.g._ for any third-party APIs that can be called from the back-end (instead of from the front-end), the flow all works well. So my current challenge is to enable it to cache front-end 3rd-party API queries too.

How I can call my `getFromCacheOrFresh` function from the Success function of the `MainCell` in the front-end? I must be confused about Apollo, GraphQL, RedwoodJS, Prisma, etc relate to each other.

The client-side caching will not suffice. I really need the third-party API, that gives me results to be saved in the database on my server.

Say if I created a new cell called `MontanaCell`, and that returns an empty string that might work but this feels unintuitive to me. I'm hoping I don't have to be required to use a JSX component (since Apollo would never let me query or mutate GraphQL outside of a JSX component).

Cheers,
Montana Mendy

**Comment by dac09** [comment]
Hey @Montana - are you exposing the backend function as an API endpoint? i.e. A a different api function? 

**Option 1: Exposed as a custom api endpoint**
If so, there's no reason to use Apollo/Graphql/etc. to query your custom endpoint. This would be a standard fetch call:

```js

const [myResults, setMyResults] = useState()

useEffect(() => {
	const {response} = await fetch('/api/my-custom-endpoint')
	
   setMyResults(response.data)
}, [])
```

It's a totally standard React component!


**Option 2: Exposed as a query in graphql**
However, if you want all the benefits of Cells (and to do it in the standard GraphQL-Redwood way) - you could just expose a new query - you don't _need_ a model to add queries and sdls. 

Steps to do this would be:
1. Create thirdPartyApi.sdl.js in your api/src somewhere
2. Add a query, lets call this getThirdPartyResults
```gql
  type Query {
    getThirdPartyResults: Results! @requireAuth
  }
```
You can also choose to add this to any of your existing sdl files, you don't need to add a new file
3. Now implement the service: api/src/services/myThirdPartyApi.ts
```js
export const getThirdPartyResults = () => {
	return getFromCacheOrFresh(/*your params*/) 
} 
```

You can now add a cell that lets you query this endpoint like this:

```gql
 query getThirdPartyResults {
   someData {
  id
 name
}
}
```

**Comment by thedavidprice** [comment]
@Montana no pressure recommendation --> once you get some clarity, this would make for a great quick snippet example for others to find on the Redwood Forums. Post over here if that's of interest to you: https://community.redwoodjs.com/c/get-help-and-help-others/15

**Comment by dac09** [comment]
Hi @Montana - did my suggestion help at all? Please let us know, and please close out the issue if you've got stuff up and running!

**Comment by Montana** [comment]
Hey @dac09, 

Sorry for the late response, this ended up working:

```javascript
 query getThirdPartyResults {
   someData {
  id
 name
}
}
```

I appreciate it a lot.
