### ISSUE TITLE
Baremetal deploy fails on Starting serve serve process step - pm2

### ISSUE THREAD

**Issue by zpeters** [redwoodjs/redwood#5081]
I am happy to do additional testing and contribute patches, etc to help solve this issue.

### Main issue
- What happens
  - I have run `yarn rw setup deploy baremetal` and made the necessary config settings (below)
  - When i run `yarn rw deploy baremetal --firstrun` all steps succeed until i get to "Starting  serve process ofr the first time".  At that step i get an error that the Deploy Failed running the command `yarn pm2 start ecosystem.config.js --only serve`
  - If i ssh into the server  i can manually  start the service using the "manual" pm2 command of `pm2 start ecosystem.config.js`
- What is expected
  - I am expecting that this step should be running `pm2 start ecosystem.config.js` to install the initial api services.  I cannot find a reference to using yarn to run the pm2 command.  I suspect i am missing something in my packages config possibly?

### Additional thoughts
- I found it necessary to run `pm2 save` to make my settings persist, this would be helpful to add
- possibly a statement about `pm2 startup` to discuss injecting pm2 into the systems normal services so it will run on reboot

### Relevant configs
```
deploy.toml
[[servers]]
host = "redwood"
username = "zach"
agentForward = false
privateKey = "/Users/zachpeters/.ssh/id_rsa"
migrate = false
sides = ["api","web"]
path = "/var/www/oblique-strategies"
processNames = ["serve"]
```

```
package.json (root)
{
  "private": true,
  "workspaces": {
    "packages": [
      "api",
      "web",
      "packages/*"
    ]
  },
  "devDependencies": {
    "@redwoodjs/core": "^1.0.0",
    "node-ssh": "^12.0.4"
  },
  "eslintConfig": {
    "extends": "@redwoodjs/eslint-config",
    "root": true
  },
  "engines": {
    "node": ">=14.19 <=16.x",
    "yarn": ">=1.15"
  },
  "prisma": {
    "seed": "yarn rw exec seed"
  },
  "packageManager": "yarn@3.2.0"
}
```

```
ecosystem.config.js
module.exports = {
  apps: [
    {
      name: 'api',
      script: 'node_modules/.bin/rw',
      args: 'serve api',
      instances: 'max',
      exec_mode: 'cluster',
      wait_ready: false,
      listen_timeout: 10000,
    },
  ],
}
```

**Comment by thedavidprice** [comment]
Looping in @cannikin

**Comment by cannikin** [comment]
Hi @zpeters did you add pm2 to your app's package.json or install globally? Right now it always tries to run with `yarn pm2` which will only be available if you add it to your app via `yarn add -W pm2`. I have a note in the docs about [licensing concerns](https://redwoodjs.com/docs/deploy/baremetal#setup) with pm2 but I should also add a note about installing it properly!

At some point I'd like to make it an option whether to use globally installed pm2 (by just running `pm2`) vs the local install (run with `yarn pm2`).

**Comment by cannikin** [comment]
Hi @zpeters did you add pm2 to your app's package.json or install globally? Right now it always tries to run with `yarn pm2` which will only be available if you add it to your app via `yarn add -W pm2`. I have a note in the docs about [licensing concerns](https://redwoodjs.com/docs/deploy/baremetal#setup) with pm2 but I should also add a note about installing it properly!

At some point I'd like to make it an option whether to use globally installed pm2 (by just running `pm2`) vs the local install (run with `yarn pm2`).

**Comment by cannikin** [comment]
Added a couple of issues to track this:  https://github.com/redwoodjs/redwood/issues/5083 https://github.com/redwoodjs/redwood/issues/5082

**Comment by zpeters** [comment]
@cannikin This sounds like the right track.  I will report back.  Happy to help contribute to the docs or code if needed.

**Comment by zpeters** [comment]
@cannikin Confirming that adding the pm2 dep did solve my issue.

One thing to note, i needed to manually run "yarn pm2 startup" and "yarn pm2 save" to add the systemd hooks and to have it retain the services on reboot. 

My thoughts would be to have the adding of the pm2 dep part of the "yarn rw deploy setup baremetal" process and have the "pm2 save" and "pm2 startup" part of the "first run" process.

I saw a few different issues get created so im going to pause here and get your thoughts. 

Im happy to spend time documenting, submitting a patch or testing to help with the project.  just let me know how you'd like time spent.

**Comment by cannikin** [comment]
Awesome! I actually hadn’t run those commands myself, and I agree: we should execute them on —first-run

If you wanted to take a look at the code and see about adding that option, that would be great! I was thinking of adding a config option like `pm2Install = “local”` or `”global”` (default is local for backwards compatibility) and then it would run the correct command during the restart phase.

Thanks for volunteering, I’m glad someone is as excited as I am about this feature! :)

**Comment by zpeters** [comment]
Nearly have the first part of this complete.  I am wrapping up the command to save the state.  It looks like the "startup" command just spits out a sudo command to run.  To avoid complication i will not try to tackle this in the setup, but rather add a note in the documentation.

After i have this i'd like to tackle the local/global option we discussed

**Comment by zpeters** [comment]
#5139 for review

**Comment by zpeters** [comment]
#5139 merged - adds "save" step to baremetal and add docs for baremetal startup

continuing on local/global pm2 options

**Comment by zpeters** [comment]
- [ ] check if setup deploy baremetal adds the pm2 dependency
- [ ] add config switch for "global"
- [ ] add actual commands for "global"
- [ ] update relevant docs

**Comment by zpeters** [comment]
@cannikin im getting ready to look at adding a pm2 local/global switch.  Having a little trouble finding where to get started on where configuration settings are handled.  Any pointers?

**Comment by cannikin** [comment]
Sure thing! So the TOML file is parsed here: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/deploy/baremetal.js#L110-L112

Then we loop through each server: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/deploy/baremetal.js#L110-L112

And pick out the options needed for ssh at the top there: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/deploy/baremetal.js#L110-L112

So if you add a new config option you can get it there and then modify the commands that run, like the restart: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/deploy/baremetal.js#L110-L112

**Comment by zpeters** [comment]
This is prefect thanks!

**Comment by zpeters** [comment]
PRs submitting, awaiting approval

**Comment by cannikin** [comment]
Going to close this along with the PR, thanks again for working on it!

**Comment by shobhitic** [comment]
I keep getting this error: 

`bash: line 1: pm2: command not found`

I've added pm2 to package.json, installed globally on the server. In deploy.toml, I have:

```
packageManagerCommand = "yarn"
monitorCommand = "pm2"
```

This issue is the closest I got to find the answer, please let me know what am I doing wrong (and also let me know if this isn't the right place to ask the question)

**Comment by cannikin** [comment]
Hello! You shouldn't need to add `pm2` to `package.json`, it really needs to be installed globally on the server, not in your app:

    yarn global add pm2
    # or
    npm install -g pm2

We usually prefer to do help like this in the [Discord](https://discord.gg/redwoodjs)!
