### ISSUE TITLE
Add the Tailwind CSS IntelliSense extension to the `recommendations` list in `.vscode/extensions.json` when the user runs `rw setup ui tailwindcss`

### ISSUE THREAD

**Issue by benrosen** [redwoodjs/redwood#5089]
RedwoodJS provides a list of [recommended extensions for VS Code](https://github.com/redwoodjs/redwood/blob/37570bb8deff3daac2221ba4998f05608e5e7897/.vscode/extensions.json).

Tailwind provides an [official extension](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) for VS Code, which is recommended in the [editor setup portion of the Tailwind CSS docs](https://tailwindcss.com/docs/editor-setup). 

The Tailwind CSS IntelliSense extension is not currently included in the list of recommended extensions by default, nor is it added to the list of recommended extensions when the user runs the `rw setup ui tailwind` command.

Could/should/will`"bradlc.vscode-tailwindcss"` be automatically added to the list of recommended extensions when the user sets up Tailwind in their RedwoodJS project?

**Comment by jtoar** [comment]
@benrosen great idea! That extension is a must. No pressure, but we'd happily accept a PR for this. The code for the `setup ui tailwindcss` command is in https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/setup/ui/libraries/tailwindcss.js.

**Comment by zygopleural** [comment]
I picked this up as been wanting this for a while!
