### ISSUE TITLE
Using redwood authentication (requireAuth) on a non-lambda Function causes infinite loop

### ISSUE THREAD

**Issue by twodotsmax** [redwoodjs/redwood#5095]
See https://github.com/redwoodjs/redwood/pull/5094 for fix.

High level problem: If you get the current auth token with `await useAuth().getToken()` to construct headers of:
```
'auth-provider': 'auth0',
Authorization: `Bearer ${token}`,
```
 and try to call a Function defined with:
```
useRequireAuth({
  handlerFn: async (event: APIGatewayEvent, ctx: Context) => {
    requireAuth({ roles: ['MyRole'] })
    // do stuff
  },
  getCurrentUser,
})
```

If async local storage is being used to manage the global context, it causes "Maximum call stack size exceeded" due to a bug in requireAuth.ts

**Comment by jtoar** [comment]
Closing as https://github.com/redwoodjs/redwood/pull/5094 was merged. Thanks @dac09 and @twodotsmax!
