### ISSUE TITLE
Automatically import and `makeMergedSchema` for all SDLs

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#51]
Right now these lines are required for every SDL in your codebase:

```js
import * as posts from 'src/graphql/posts.sdl'

const schema = makeMergedSchema([posts])
```

Let's not require that.

**Comment by mojombo** [comment]
[babel-plugin-wildcard](https://github.com/vihanb/babel-plugin-wildcard) is very close, but doesn't handle the `import *` part like we want. I'm going to extract the bits of it that we need so we have our own version that works for us.

**Comment by peterp** [comment]
@mojombo If you're in a research phase also check out my old PR for auto importing pages: https://github.com/redwoodjs/redwood/pull/22/files

It added `require.context` to nodejs apps that webpack introduced.

`const pages = require.context(path, true, regExp)`

I would love to have a standard interface for importing modules in subdirectories across the webpack and nodejs environments.

**Comment by mojombo** [comment]
@peterp Ok, I looked at that but didn't think it was going to solve the problem; will it indeed result in static import declarations for each file it matches in the dir?

**Comment by mojombo** [comment]
@peterp I don't understand how this will get us what we need for Zip It And Ship It. In Webpack, `require.context` will cause the matched modules to be included in the pack, but ZIASI won't know anything about `babel-plugin-require-context-hook` and all I get out of it are the filenames of the matched modules, which would then have to be imported with a dynamic import, which ZIASI isn't going to be able to traverse. Unless I'm misunderstanding something.

**Comment by peterp** [comment]
You're right. It is me who is misunderstood.

I was not considering this from the perspective of transpiling dynamic imports into static ones during build time, but instead wanted to provide a common interface to developers wanting to dynamically import things.

I assumed converting dynamic imports into static ones to be something that could be deal with during packaging or build time for production.

`require.context` gives you:

1. a function that gives you the results from your search

```js
const req = require.context('./graphql')
req.keys() // ['posts.sdl.js', 'authors.sdl.js']

2. And the ability to import them:

```js
req('posts.sdl.js') //  the JS module
```

**Comment by peterp** [comment]
Maybe a common interface between environments shouldn't be a concern, in which case this babel macro looks great: https://github.com/kentcdodds/import-all.macro

**Comment by mojombo** [comment]
Let me go up a conceptual level here and explore something before we get into the nitty-gritty of directory imports.

If I'm reading the Netlify docs correctly, it sounds like if you want to deliver unbundled functions code, you can do it (via ZiSi), but it means abandoning the CI system built in to Netlify and you have to manually deploy. Is that true? If so, that's a lot to give up, and I think a discussion is relevant about whether we should be using Webpack on the api side as well, in order to produce a single file deliverable compatible with Netlify CI.

In that world, we could just use normal `require.context` from Webpack and be done with it.

**Comment by mojombo** [comment]
Closed by https://github.com/redwoodjs/create-redwood-app/pull/16
