### ISSUE TITLE
Type Checking on Typescript project finds errors with an unchanged project

### ISSUE THREAD

**Issue by KatrinaAS** [redwoodjs/redwood#5104]
## Expected Behavior
Type checking on a unchanged fresh typescript project to return 0 errors

## Current Behavior
Type checking on an unchanged fresh typescript project
returns 
```
(node:19764) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  ✔ Generating the Prisma client...
  ✔ Generating types
src/App.tsx:10:4 - error TS2786: 'FatalErrorBoundary' cannot be used as a JSX component.
  Its instance type 'FatalErrorBoundary' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'import("/Users/katrinaknight/Projects/redwood/test-app/node_modules/@types/react/index").ReactNode' is not assignable to type 'import("/Users/katrinaknight/Projects/redwood/test-app/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.

10   <FatalErrorBoundary page={FatalErrorPage}>
      ~~~~~~~~~~~~~~~~~~


Found 1 error in src/App.tsx:10
```

## Steps to Reproduce
1. yarn create redwood-app  --ts test-app
2. cd test-app
3. yarn rw type-check

## Why this effects things
This doesn't effect me too much right now, as long as it can be ignored and will show other errors in addition to this one, but it is a minor issue if I try to later do CI based on the type-checking.

**Comment by jtoar** [comment]
Thanks @KatrinaAS! I can reproduce this and the clue is this line here:
```
Type 'import("/Users/katrinaknight/Projects/redwood/test-app/node_modules/@types/react/index").ReactNode' is not assignable to type 'import("/Users/katrinaknight/Projects/redwood/test-app/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode'.
```

It looks like we're getting the type from two places. I looked at the latter (`@types/react-dom/node_modules/@types/react/index`) and it turns out those type definitions are for React 18. I'll continue investigating!

**Comment by Tobbe** [comment]
Maybe relevant

https://github.com/facebook/react/issues/24304

**Comment by thedavidprice** [comment]
If I understand correctly, the problem here is how tsc module resolution is handling the `@types/react` package as a dependency of:
- `@types/react-dom`
- `@types/react-syntax-highlighter`

Is this something that can be handled via tsconfig.json?

**Comment by cq-ubaid-khan** [comment]
The equivalent of `resolution` for npm is `overrides` see documentation https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Comment by tiff0000** [comment]
any resolution to this issue?

**Comment by jtoar** [comment]
@tiff0000 if I recall correctly the original issue was resolved a while ago from `@type/react`'s side, but I just tried reproducing it and I see other, node-related type errors. Is this what you're referring to or are you still seeing the original issue? 

```
> yarn rw type-check
✔ Generating the Prisma client...
✔ Generating types
src/pages/FatalErrorPage/FatalErrorPage.tsx:12:5 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.

12 if (process.env.NODE_ENV === 'development') {
       ~~~~~~~

src/pages/FatalErrorPage/FatalErrorPage.tsx:14:5 - error TS2591: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.

14     require('@redwoodjs/web/dist/components/DevFatalErrorPage').DevFatalErrorPage
       ~~~~~~~


Found 2 errors in the same file, starting at: src/pages/FatalErrorPage/FatalErrorPage.tsx:12
```

**Comment by tiff0000** [comment]
Hey! Thanks for the reply, I resolved the issue by upgrading types/react from 17 to 18.

**Comment by snurfer0** [comment]
having the same issue with `"@types/react": "18.2.13",`
