### ISSUE TITLE
typescript - Why the types in Service and SDL are seperated???

### ISSUE THREAD

**Issue by igmyung** [redwoodjs/redwood#5109]
![image](https://user-images.githubusercontent.com/29830781/162626000-8bd7d20e-087d-45f9-997e-3548e0b673af.png)
![image](https://user-images.githubusercontent.com/29830781/162626011-416c5546-d81d-42ec-b37d-3fdf631f1e2a.png)
In my example, CreatePostInput type and Prisma.PostCreateInput type have to be same since CreatePostInput type object is passed to the createPost service. I think it seems it has to be updated. Am I right???

**Comment by KrisCoulson** [comment]
@igmyung you don't have to declare an interface in your services if you want to just use the grapqhl input types

So you don't need to do this in your services

```
interface CreatePostArgs {
  input: Prisma.PostCreateInput
}
```

you can just 
```
import { MutationcreatePostArgs } from 'types/graphql'
```
it just prefixes Query or Mutation and then the name of your service

**Comment by jtoar** [comment]
Closing for now due to inactivity but happy to reopen if that didn't answer your question.
