### ISSUE TITLE
Prisma Relation stuff

### ISSUE THREAD

**Issue by igmyung** [redwoodjs/redwood#5110]
Let's say we have following Prisma and GraphQL schema:

```prisma
model Teacher {
  id      Int      @id @default(autoincrement())
  name    String
  courses Course[]
}

model Course {
  id        Int     @id @default(autoincrement())
  name      String
  teacher   Teacher @relation(fields: [teacherId], references: [id])
  teacherId Int
}
```

```ts
type Teacher {
  id: Int!
  name: String!
  courses: Course
}

type Course {
  id: Int!
  name: String!
  teacher: Teacher
} 
```

If I want to create course with a teacher related: 

```js
export const createCourse = ({ input }) => {
  return db.course.create({
    data: input,
  })
}
```

This didn't work, and I had to do it like this:

```js
export const createCourse = ({ input: { teacher, ...input } }) => {
  return db.course.create({
    data: { ...input, teacher: { connect: { id: teacher } } },
  })
}
```

It's kind of annoying. Am I doing something wrong? https://github.com/redwoodjs/redwood/issues/316 I saw this article, but it seems it wasn't fixed.

**Comment by jtoar** [comment]
Hey @igmyung, it is indeed kind of annoying to have to destructure out teacher and pass it to connect. It looks like `teacher` is actually `teacherId` there in your example. You can actually pass `teahcerId` straight to the data prop on `createCourse` to connect the course to a teacher. I didn't see `teacherId` listed in your GraphQL schema. Did you try that approach or was there a reason you weren't able to?

**Comment by jtoar** [comment]
Closing for now but happy to reopen, just let us know.
