### ISSUE TITLE
Tutorial: Production example link not reachable

### ISSUE THREAD

**Issue by ronatory** [redwoodjs/redwood#5111]
Hello, just want to inform you that the production example link https://predictcovid.com linked [here](https://redwoodjs.com/docs/cells#loading) isn't reachable. 

I noticed it, because the full documentation about Cells in the tutorial [Chapter 2 Cells](https://redwoodjs.com/docs/tutorial/chapter2/cells) was linked there.

**Comment by jtoar** [comment]
Thanks @ronatory! It may just be time to remove that link link for now.
