### ISSUE TITLE
'Find a Good First Issue' link from create-redwood-app 404s

### ISSUE THREAD

**Issue by jacobarriola** [redwoodjs/redwood#5113]
Hi all!

The 'Find a Good First Issue' link from the create-redwood-app that renders when you first create an app results in a 404.

Repro steps:
1. Start a new Redwood app `yarn create redwood-app <APP_NAME>`
2. Click on  `❖ Find a Good First Issue: https://redwoodjs.com/good-first-issue`

Expected results
1. Page should render

Actual results
1. Page 404s

Perhaps we should send users to https://github.com/redwoodjs/redwood/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 instead?

I'd love to get a PR rolling on this. Let me know!

**Comment by dac09** [comment]
We meet again @jacobarriola - and thank you for this, and welcome back!

We've recently moved our website over to another repo (Which is a Redwood app!) - and I've added the redirect back in this PR: https://github.com/redwoodjs/redwood/issues/5113

Thanks for raising the issue, and let's see if we can find you another good one :)

**Comment by jacobarriola** [comment]
Hi @dac09! Good to see you again, and sorry for the long absence!

Thanks for the PR and I'll be looking for another issue.
