### ISSUE TITLE
Regression in scaffold styling

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#5116]
We used to have alternating background colors in scaffolded tables. At some point we lost that. Also lost rounded corners and the outline.

Before:
![image](https://user-images.githubusercontent.com/30793/162803247-8adad28c-0011-45bf-8e3d-e87d3bfacf8b.png)

Now:
![image](https://user-images.githubusercontent.com/30793/162803124-8f7ff92e-9515-4f37-9b82-91c0c31584c4.png)

I think we should bring back the old styles.

**Comment by ccnklc** [comment]
Hi @Tobbe ,If this is still free to pick, I can take this issue as part of my first contribution to Redwood repo.

**Comment by Tobbe** [comment]
@ccnklc Yes, please do! And just ask if you have any questions at all along the way 🙂
