### ISSUE TITLE
yarn create redwood-app <AppName> not working 

### ISSUE THREAD

**Issue by suraj0901** [redwoodjs/redwood#5131]
i don't why but i tried on everywhere on my pc, stackblizt, gitpod everywhere at the step of "yarn install" it is throwing err.
is it a bug ? or i am doing something wrong.
[git pod link](https://suraj0901-blogapi-uuvwv9l0iht.ws-us39a.gitpod.io/)

**Comment by Tobbe** [comment]
@suraj0901 Thanks for opening an issue! Unfortunately it seems like I can't open your gitpod link

![image](https://user-images.githubusercontent.com/30793/163050546-a3cd1960-1f88-4d3b-a5e1-1315f2332bae.png)

Could you perhaps share some logs with the error you're getting when trying to install? And also the exact steps you're trying. Thank you!
