### ISSUE TITLE
`yarn rw prisma migrate dev -n "create user"` not working

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#5135]
When trying to set the name for a migration on the command line like `yarn rw prisma migrate dev -n "create user"` Prisma says it can't find the schema file `Error: Could not find a schema.prisma file that is required for this command.`

![image](https://user-images.githubusercontent.com/30793/163050948-668cf340-96c7-4df0-bdcd-8d9b8d79fe05.png)

**Comment by jtoar** [comment]
@Tobbe this command similarly fails for me:

```bash
# fails
yarn rw prisma migrate dev -n "create user"
```

But curiously if you pass just one word, it works:

```bash
# works
yarn rw prisma migrate dev -n "user"
```

**Comment by Tobbe** [comment]
> Could you confirm that behavior?

Yes! Same for me. I've been working around it by doing `-n create_user`
