### ISSUE TITLE
Scaffold datetime fields as <DatetimeLocalField>

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#514]
https://community.redwoodjs.com/t/presenting-null-datetime-values-in-db-correctly/500

**Comment by brianespinosa** [comment]
@cannikin I think it would also be great to coerce the values to ISO when the form posts as well, otherwise I think we are just going to get errors for invalid DateTime values.

**Comment by cannikin** [comment]
Hmmm I'm fairly sure I tested this and Apollo actually accepts the format returned from that field and turns it into a date properly! But we should double check!

**Comment by brianespinosa** [comment]
I was (finally) getting a chance to play around with Redwood this weekend and it wasn't, both in terms of either defining the input type directly, or using the `<DatetimeLocalField />` component instead. Technically dropping the Z from the time passed from the component does work correctly when posting from Apollo.

@cannikin I am happy to take this task actually, both in terms of jumping in to get the scaffolds to generate with `<DatetimeLocalField />` and also creating whatever helper functions we need to coerce the values on POST. If you'd like me to take a stab at this, we could discuss how/where you'd prefer the helpers to be implemented. I am actually surprised there is not already something available in Apollo. I know they already have a `coerceInputValue` utility.

**Comment by cannikin** [comment]
Awesome! We've got a coercion function in the form helper in a PR now: https://github.com/redwoodjs/redwood/pull/749 Maybe you could ping @Tobbe and work together on adding that? Or wait for his to merge and then open yours afterwords?

**Comment by Tobbe** [comment]
@brianespinosa My PR is merged now, so now would be a good time to start working on this issue, if you still want to tackle it. (No pressure if you don't. I'm sure someone else will get to it in that case. Just let us know 😀)

**Comment by brianespinosa** [comment]
@Tobbe I have something started that came from your other branch already, but I will pull the latest in from our main redwood branch now in case there are changes.

I may need to submit a PR and then ping you for some help since there was something in there that was causing me some problems in the coerce function. I am guessing you'll be able to see right away what it is. I'll try to get that up today so you can see.

**Comment by brianespinosa** [comment]
Just a heads up for anyone landing on this issue, sadly, it turns out I have not had the time available to tackle this that I thought I would. If anyone is interested in picking this issue up, please do so.

**Comment by jtoar** [comment]
I think we can close this one!

<image src="https://user-images.githubusercontent.com/32992335/118607874-eff41080-b76d-11eb-97e9-bdc8bd62f7c2.png" width="600px" />
