### ISSUE TITLE
Tutorial text and screenshot isn't matching current RW output

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#5166]
Tutorial:
![image](https://user-images.githubusercontent.com/30793/163328666-555bb77a-77f0-4104-ac21-fd80ba60eac2.png)

What I'm seeing:

![image](https://user-images.githubusercontent.com/30793/163329195-dc146376-6e22-483f-ad2f-4834436243e4.png)

![image](https://user-images.githubusercontent.com/30793/163329128-f07ae92d-d299-44f3-b447-268ddb92c340.png)

I haven't kept on-top of the recent work done to mask gql errors. But could it be that one of those PRs forgot to update the tutorial? Have we made any changes that should affect dev? Or have we only changed the behavior in prod?

@dthyresson Tagging you here because you usually know about these gql things

**Comment by cannikin** [comment]
Hmm, I re-did most of these screenshots when I re-wrote the tutorial against the release candidate, so it definitely *used* to display that error. Maybe that was locked down for security reasons, not to leak error details since rc.1?

**Comment by Josh-Walker-GM** [comment]
@Tobbe, @cannikin 

I haven't confirmed personally that the tutorial screenshot and redwood output are in sync but the discrepancy highlighted in this issue appears to have been resolved. The current tutorial screenshot matches the expected output as stated in the issue.

See for the relevant section (I think):
https://redwoodjs.com/docs/tutorial/chapter6/comment-form#updating-graphql

I think this one can be closed?
