### ISSUE TITLE
Hardcoded query name is refetched after deleting item in scaffolding table

### ISSUE THREAD

**Issue by cephalization** [redwoodjs/redwood#518]
I've scaffolded a data model called `PAGES`. Data appears in the `/pages` route as I would expect but I noticed that the list of pages did not update when I deleted one. 

Looking at the generated scaffolding code, I noticed that the `refetchQueries` key in the delete handler was for `POSTS` query rather than `PAGES`. Changing this manually fixed the issue, and my pages data correctly refreshed after a delete.

Redwood code in question:

https://github.com/redwoodjs/redwood/blob/7be1543c8ca5104158111a1a2e3b1cc5b1c55df3/packages/cli/src/commands/generate/scaffold/templates/components/Names.js.template#L35

I think I could fix this issue, just posting here first for posterity :)

**Comment by thedavidprice** [comment]
Saw your tweet and just wanted to say thanks again for jumping here! 🙌
