### ISSUE TITLE
Mocking `useLocation` in `web/src/components` tests

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#5190]
Edit: seem Kris Coulson's comment: https://github.com/redwoodjs/redwood/issues/5190#issuecomment-1100275186

---

Currently it doesn't seem like it's possible to mock `useLocation` in components that use it. See https://discord.com/channels/679514959968993311/964542735614881862

**Comment by KrisCoulson** [comment]
@jtoar this is how we mock the location in Teamstream

```
import { LocationProvider } from '@redwoodjs/router'

render(
<LocationProvider location={{ pathname: '', search: '?cancelled=true' }}>
   <Component />
</LocationProvider>
)
```

**Comment by jtoar** [comment]
@KrisCoulson thanks! That seems super obvious now. Let's keep this open as a reminder to add this to the docs.

**Comment by MagnusHJensen** [comment]
A discord link like that, which doesn't actually work is not a very reliable way to indicate a reference 😅
