### ISSUE TITLE
node dev server on high CPU

### ISSUE THREAD

**Issue by dnprock** [redwoodjs/redwood#520]
Our redwoodjs app has grown a little bit more complex. We recently added material-ui package. I notice the node dev server is spinning very high CPU.

Our codebase is here:

https://github.com/vidalab/vida

This is the change that adds material-ui package:

https://github.com/vidalab/vida/commit/4cc6a44b12e39a2883474bb85c17738da4287e67

Before adding material-ui package, CPU is usually sits at 60-70%. After material-ui package, CPU goes up to 200%. It seems like redwoodjs dev server is watching some directories too aggressively.

**Comment by dnprock** [comment]
I've got some updates. I was using node v12.6.0. When I switch to v14.0.0, CPU is much lower. But I got the SIGENV error with v14.0.0.

I upgraded to 12.16.3 (LTS). The issue went away.

**Comment by thedavidprice** [comment]
Thanks for letting us know! 

Node has been a bit problematic lately. I've stuck with v12.16.3 as well.
