### ISSUE TITLE
Fastify does not support gzip compression out of the box.

### ISSUE THREAD

**Issue by ATheCoder** [redwoodjs/redwood#5215]
I first encountered this problem when trying to use `form-data` in order to upload a file to the graphql server.

What happens is that if the file length is more than a certain size (e.g: `10kb`) Postman tried to use gzip in order to compress the request and sets the `Content-Length` based on the compressed request. However since `fastify` does not support compression on it's `defaultTextParser` it will return a `FST_ERR_CTP_INVALID_CONTENT_LENGTH` error.

If you search around you'll find [this](https://stackoverflow.com/questions/59345698/fastify-returns-fst-err-ctp-invalid-content-length/59359972#59359972) stackoverflow question asking about the same thing.

I also found a package called [fastify-compress](https://github.com/fastify/fastify-compress) that seems to be fixing this issue.

Is it possible to add this into RedWood's fastify?

Is there anyway to register fastify plugins on my own redwood project?

**Comment by thedavidprice** [comment]
Looping in @dthyresson

**Comment by AidaRvi** [comment]
You can set `bodyLimit` option in server.config.js file (fastify related config) in order to increase your body size.
But I have same issue about FST_ERR_CTP_INVALID_CONTENT_LENGTH error too. How can we deal with gzip problem?
