### ISSUE TITLE
realworld.io example

### ISSUE THREAD

**Issue by franciscolourenco** [redwoodjs/redwood#5221]
It would be nice to have an example at https://codebase.show/projects/realworld?category=fullstack

**Comment by jtoar** [comment]
That'd be cool indeed. @Tobbe maybe this'd make a great example app? @franciscolourenco I'm not sure if we'll be able to prioritize it soon, but we're definitely open to anyone taking it on.

**Comment by Tobbe** [comment]
Could definitely link to this as a community example if you wanted to take a stab at it @franciscolourenco 🙂  But absolutely no pressure. If you don't want to, maybe someone else want 🙂

**Comment by franciscolourenco** [comment]
Can't do it at the moment, sorry.

**Comment by samullman** [comment]
Hey I'm new around here.  Happy to take a stab at this possibly with Chakra-UI -- fun way to learn the framework 👍 let me know if anyone has anything started ... thx

**Comment by Tobbe** [comment]
@samullman Go for it! 🚀

**Comment by TristanWYL** [comment]
Hi guys, as I have not found a related repository under active development, so I develop this on my own. Hopefully I can finish it within this weel. Check the [repo](https://github.com/TristanWYL/redwood-realworld-example-app) in case you are interested.

**Comment by TristanWYL** [comment]
> Hi guys, as I have not found a related repository under active development, so I develop this on my own. Hopefully I can finish it within this week. Check the [repo](https://github.com/TristanWYL/redwood-realworld-example-app) in case you are interested.

Hi guys, this piece of work is basically done, and I have already submitted it to [realworld](https://codebase.show/projects/realworld?category=fullstack) for further review. 

In addition, as I have to work on other projects, so I have not finished the test part, and some potential performance improvement. I shall work on the improvement/test when I have time. Any contribution and advice will be much appreciated. The works which can make this project better have been listed in the readme of the repo. 

I will let you guys know once REALWORLD finish reviewing the project, so that we could close this issue.

Thanks guys!

**Comment by TristanWYL** [comment]
> > Hi guys, as I have not found a related repository under active development, so I develop this on my own. Hopefully I can finish it within this week. Check the [repo](https://github.com/TristanWYL/redwood-realworld-example-app) in case you are interested.
> 
> Hi guys, this piece of work is basically done, and I have already submitted it to [realworld](https://codebase.show/projects/realworld?category=fullstack) for further review.
> 
> In addition, as I have to work on other projects, so I have not finished the test part, and some potential performance improvement. I shall work on the improvement/test when I have time. Any contribution and advice will be much appreciated. The works which can make this project better have been listed in the readme of the repo.
> 
> I will let you guys know once REALWORLD finish reviewing the project, so that we could close this issue.
> 
> Thanks guys!

Hi guys, our implementation has been approved and is now listed on the [project's home page](https://codebase.show/projects/realworld?category=fullstack).

**Comment by callingmedic911** [comment]
Thank you @TristanWYL! Really appreciate the effort you put together to make this and get this approved.

@jtoar I'm closing this issue but please let me know if there's something else to follow up on here.
