### ISSUE TITLE
Scenarios don't support filenames with an extra dot: `.`

### ISSUE THREAD

**Issue by freddydumont** [redwoodjs/redwood#5222]
When using file names like the ones in the example below, scenarios won't seed the database:

```
something.machine.ts
something.machine.test.ts
something.machine.scenario.ts
```

I believe the issue is happening at the `split` here:

https://github.com/redwoodjs/redwood/blob/f57b605ed62da5515508512f2592a1ef99a10bfb/packages/testing/config/jest/api/jest.setup.js#L135-L137

Removing the first dot from the file names fixes the issue.

For context, this isn't using generators. I'm testing a state machine which invoke services (promises) that talk to the database using prisma. I understand this is outside of the redwood happy path. The main purpose of this issue is to document the edge case.

**Comment by Tobbe** [comment]
Thanks for the issue report @freddydumont. And especially for pointing out the exact place in the code that needed fixing. I have a PR up here: https://github.com/redwoodjs/redwood/pull/5248
I don't have time to properly test it right now. But will get to it within the next 24 hours.

**Comment by freddydumont** [comment]
Thanks for the fix @Tobbe ! Looking forward to having dots in my filenames again 😁
