### ISSUE TITLE
`mockServiceWorker.js` created by storybook is copied into web dist

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#5225]
`yarn rw build web` copies `web/public` to `web/dist`. This has the unintended side effect of copying the MSW file used for storybook to dist.

Steps to reproduce:

```
yarn rw storybook
# Creates web/public/mockServiceWorker.js
yarn rw build web
# Copies mockServiceWorker.js to web/dist/mockServiceWorker.js
```

**Comment by thedavidprice** [comment]
It's supposed to be ignored via .gitignore here:
https://github.com/redwoodjs/redwood/blob/main/packages/create-redwood-app/template/gitignore.template

**Comment by jtoar** [comment]
Not 100% how building web works but does the `.gitignore` affect the build process at all? It looks like we have it so that webpack just copies anything in `web/public` over to `web/dist`, except the `README.md`:

https://github.com/redwoodjs/redwood/blob/879cdf9b07fb969da81cf2a5aacd56e5b7bb47d8/packages/core/config/webpack.common.js#L243-L251

**Comment by thedavidprice** [comment]
If it's in the repo at the time of build, it will be copied into /dist. So it depends on the context at time of build.

> Also, just ran yarn rw build web again and even README.md gets copied over so not sure that that's working as configured.

Well, that's no good 😦

**Comment by standup75** [comment]
I can look into this if you want to assign it to me

**Comment by jtoar** [comment]
@standup75 sure thing! Let us know if you have any questions.
