### ISSUE TITLE
logFormatter doesn't print metadata

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#5228]
I have this in my code
```
  logger.debug(
    { foo: 'foo', nested: { arr: ['one', 'two', 'three'] } },
    'Example debug log'
  )
```  

This is what it looks like on LogFlare

<img width="485" alt="image" src="https://user-images.githubusercontent.com/30793/163835663-da131fa0-b473-4f09-8e36-17f1372f7aab.png">

Running `yarn rw dev` and letting it print to my console, all I get is this

<img width="358" alt="image" src="https://user-images.githubusercontent.com/30793/163836011-704565a5-4197-4d96-a71e-61a8de2b7332.png">

I get the "Example debug log" text, but none of the metadata.

I think we should print the metadata locally too. I'll start working on a PR

Also found this:
When generating a directive the generated code contains this debug log:
![image](https://user-images.githubusercontent.com/30793/165149156-09f7d944-aa15-4edb-bac8-912a7abe605b.png)

`directiveArgs` will never be printed when running locally because we're not printing any metadata

**Comment by jtoar** [comment]
@Tobbe I had run into this some time ago too, and I thought it may be related to https://github.com/redwoodjs/redwood/issues/4154. It looks like that's been closed now. Also see the description in the PR here: https://github.com/redwoodjs/redwood/pull/4619. Does it look like this has already been implemented via `custom`?

**Comment by Tobbe** [comment]
@jtoar Thanks for linking those. Will continue discussion in #5235
