### ISSUE TITLE
RC publishing workflow: Next Steps

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#5229]
continuing #5199

@jtoar 

# To Do
- [x] (manual check) Make sure publishing fails when branch tag >= release tag
- [x] check on var stripping `v` character correctly (see [this comment](https://github.com/redwoodjs/redwood/pull/5199#issuecomment-1100750401))
- [x] can we save the published package semver in the Workflow and pass to Slack json payload? 
- [x] in the `yarn release` script, can we add a "create RC Release Notes" that effectively gives us [these two links](https://github.com/redwoodjs/redwood/releases/tag/v1.1.0-rc.215):
    - diff between the release branch and the latest published version tag
    - Pulls filtered by `merged` and the upcoming version milestone

**Comment by jtoar** [comment]
Confirmed one on the list: the semver compare CLI does stripe the `v` before comparing: https://github.com/jceb/semver-compare-cli/blob/08f5bf157a5109f8bf03fac81823693e6eb5e62c/cli.js#L60

**Comment by jtoar** [comment]
@thedavidprice this issue is wrapped pending your review on these two:
- https://github.com/redwoodjs/redwood/pull/5324
- https://github.com/redwoodjs/redwood/pull/5324

**Comment by thedavidprice** [comment]
YES 🚀🚀

Thank you. Closing this out.

@jtoar I made some minor tweaks here:
- #5338

Primarily reverted to the Slack Workflow I created and added you as a collaborator so we can edit together. Changed dir name and description to be more precise.
