### ISSUE TITLE
Jest Web Test Run Initialization is Slow O(10x) Slower than it Should Be

### ISSUE THREAD

**Issue by MichaelrMentele** [redwoodjs/redwood#5231]
**Problem** When running jest tests the runtime seems to be 12-14 seconds just to spin up a test and mount a component. The actual tests are fast. That implies 99% of the wall time is due to setup -- possibly because we have several chained yarn calls but most likely due to source maps (usual suspect for this).

As evidence, API tests are MUCH faster.

```
 PASS   api  api/src/services/stages/stages.test.ts
  stages
    ✓ returns all stages (45 ms)
    ✓ returns a single stage (19 ms)
    ✓ creates a stage (16 ms)
    ✓ updates a stage (14 ms)
    ✓ deletes a stage (12 ms)

Test Suites: 1 passed, 1 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        1.043 s
```

```
 FAIL   web  web/src/layouts/DefaultLayout/DefaultLayout.test.tsx (13.13 s)
  DefaultLayout
    ✓ defaults to open (260 ms)
    ✓ opens on menu click (88 ms)
    ✓ closes on chevron click (58 ms)
    ✕ should navigate to '/home' (47 ms)
    ✓ renders successfully (33 ms)
```

**Resolution**
We should probably add an option to ignore source maps / use an ugly version by default and then use a full fidelity one when useing a debugger launch config -- something like that. 

I have a PR cooking that adds the debugging config for jest in vscode. I may be able to address this as well with a bit of advice on where to stick an option -- perhaps just as an ENV variable.

**Comment by thedavidprice** [comment]
Looping in @dac09 and @callingmedic911 

Related to #4569 #4360 — not necessarily duplicate but we definitely want to keep this topic linked/consolidated as much as possible.

**Comment by callingmedic911** [comment]
Thanks for working on it @MichaelrMentele!

I will defer to @dac09 on how/if we can configure this. Meanwhile, would it be possible to share the difference in the benchmark with and without the sourcemap?

**Comment by MichaelrMentele** [comment]
Let me take a poke at it.

**Comment by MichaelrMentele** [comment]
Should get to it this week

**Comment by MichaelrMentele** [comment]
Feeling a bit blocking profiling this by https://github.com/redwoodjs/redwood/issues/5425

**Comment by MichaelrMentele** [comment]
I did toggle the source map in a generated webpack config -- I need to run several trials to see if it made a reasonable difference.

**Comment by MichaelrMentele** [comment]
I noted that the actual subtests take O(ms) while the net runtime takes O(10s) this implies that the bottleneck is at transpilation or loading or some other setup / initialization step. I had a vague idea that it might have to do with building source maps.

However, it looks like source maps was NOT the bottleneck:
* removing source maps made about a 5% difference (it seems) in run time for tests

Another idea is to use `runInBand` since then the setup would be shared (the transpilation at least) and indeed this seemed about 3x faster on an average test basis but slower on a total wait time basis.

It's difficult to actually profile the jest test -- other than simply using a node profiler which is awkward to actually pass down through the redwood CLI (not quite sure how to do it)

I started looking at how things were cached. My understanding is that jest relies on babel directly to transpile code and doesn't use webpack for bundling at all (other than for transforming assets perhaps which we don't care about for headless jest tests anyway). 

A few areas that are promising:
* babel-loader `cacheDirectory` -- we aren't actually caching the transpiled code anywhere I can see for webpack builds with babel <link PR>
* mocking out assets https://jestjs.io/docs/webpack#:~:text=Jest%20can%20be%20used%20in,assets%2C%20styles%2C%20and%20compilation.
* making sure we only include source files

Interesting reference for ideas: https://github.com/facebook/jest/issues/10833

**Comment by finalight** [comment]
are there plans to use swc/jest? they could significantly increase the speed of the test itself

**Comment by dac09** [comment]
Hey @MichaelrMentele - I wonder if you've had a chance to try out your project on Redwood V3? Hoping that this improves the performance for you.

> are there plans to use swc/jest? 

Hey @finalight - thanks for the suggestion here - but I'm not super sure we would see much benefit from swc. We would love to move in that direction in general, but we'd have to move the custom babel plugins we use to SWC plugins (which are in Rust). Would be great to start in that direction, but its outside of my comfort zone - maybe something you would be interested in? 

SWC also currently has a big limitation right now (AFAIK) - the polyfill process https://github.com/swc-project/swc/issues/5584 - which means internally its not something we can use to build Redwood packages right now.

**Comment by MichaelrMentele** [comment]
I do believe the initialization is much improved to your optimizations @dac09 still more startup time than I would expect.

On the API side it takes several seconds, and IIRC this is mostly not transpilation time. 

```
 PASS   api  api/src/services/residences/residences.test.ts (5.03 s)
  residences
    ✓ returns all residences (403 ms)
    ✓ returns a single residence (102 ms)
    ✓ creates a residence (106 ms)
    ✓ updates a residence (99 ms)
    ✓ deletes a residence (98 ms)
``` 

It's no longer a huge pain point and more of an optimization (I think) so perhaps we can close..? I think at some point we will need to circle back -- might be more we can do. WDYT?

**Comment by dac09** [comment]
Hey Michael, thanks for getting back and confirming things are better for you! 

I'll close this down, but know that we do have an initiative to see if we can improvement the performance here further!
