### ISSUE TITLE
CLI command `yarn rw setup deploy serverless` command not working.

### ISSUE THREAD

**Issue by NoahC5** [redwoodjs/redwood#5234]
Running the command `yarn rw setup deploy serverless` fails with the error: 
### Command error output
``` 
TypeError: Cannot read properties of null (reading 'toString')
    at addPackagesTask (C:\Users\NoahC\Desktop\training-tracker\node_modules\@redwoodjs\cli\dist\commands\setup\deploy\helpers\index.js:136:32)
    at Object.handler (C:\Users\NoahC\Desktop\training-tracker\node_modules\@redwoodjs\cli\dist\commands\setup\deploy\providers\serverless.js:81:66)
    at C:\Users\NoahC\Desktop\training-tracker\node_modules\yargs\build\index.cjs:443:71
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
### rw Info output
```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.14.2 - ~\AppData\Local\Temp\yarn--1650313814186-0.9144416547167742\node.CMD
    Yarn: 1.23.0-20220130.1630 - ~\AppData\Local\Temp\yarn--1650313814186-0.9144416547167742\yarn.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.44)
  npmPackages:
    @redwoodjs/core: ^1.0.1 => 1.0.1
```
@thedavidprice 
I attempted running the command on a fresh Redwood project and got the same error.

**Comment by thedavidprice** [comment]
@simoncrypta my guess is that we're having path issues on Windows specific to the `addPackagesTask()` step. Anything you could help look into?

**Comment by simoncrypta** [comment]
That's possible since we use addPackagesTask() only for serverless, baremetal and layer0, and I never tried those. I would compare with others fix for path issues we had done, see what's wrong here.

**Comment by joriswill** [comment]
We had the same error on Windows 11. Our workaround was to switch to macOS. There were no errors under MacOS and the setup ran flawlessly.
So the assumptions with Windows path issues could be correct.

**Comment by NoahC5** [comment]
I am currently unable to switch to macOS. Is there possibly another workaround for this issue?

**Comment by jtoar** [comment]
@NoahC5 I'll prioritize looking into it this week. Switching to MacOS isn't a legitimate workaround anyway 😅

**Comment by simoncrypta** [comment]
> I am currently unable to switch to macOS. Is there possibly another workaround for this issue?

A quick workaround for now is working with WSL. https://community.redwoodjs.com/t/windows-subsystem-for-linux-setup/2439

But we sure need to prioritize this to make sure it's work on Windows.

**Comment by jtoar** [comment]
This is only explicit call to `toString` in the `addPackagesTask` function:

https://github.com/redwoodjs/redwood/blob/3ee9af82c3a10320be386cfc98bf23b8b1372e63/packages/cli/src/commands/setup/deploy/helpers/index.js#L119

@NoahC5 does the `yarn --version` command give any output for you? This isn't a legitimate workaround, but if you're feeling adventurous, you can go into `node_modules/@redwoodjs/cli/dist/commands/setup/deploy/helpers/index.js` and edit that line to be something like:

```js
const yarnVersion = "1"
```

just to see if it gets past that step.

**Comment by jtoar** [comment]
Was able to get my hands on a windows box thanks to @dac09 and it's throwing at line: stdout is `null`. Still investigating why.

**Comment by jtoar** [comment]
@NoahC5 @joriswill the latest release (v1.4.2) includes the fix for this:
```
yarn rw upgrade
```
