### ISSUE TITLE
Writing and editing @redwoodjs/api README

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#526]
> [Link to the @redwoodjs/api README](https://docs.google.com/document/d/1vHCzo3mz4XcXizttYj9JDYIiMZ0PCyE8XNbBrsO2B2A/edit?usp=sharing)

Because you guys already wrote great content, I didn't feel like I wrote this as much as gathered material. So if you find me quoting you, it's probably because I did. And where I could, I tried to source it. 

I started with the `api` package because @peterp said it was one of the more important ones (#461) as far as docs go. But before I write any more, I figured I'd better get feedback (@thedavidprice @cannikin):

**Purpose and Vision**

Right now (pre-auth, although I saw it just got merged) the `api` package seem to do two things--expose functions to build the GraphQL API and provide services with `context`. Did I get that right? And if so, that seems to be it's purpose, but what's it's vision?

**Package Lead**

Who should I put? In the google doc, I used @peterp as an example. It's short enough to reproduce:

> Have questions? Get in touch with Peter [on discourse](https://community.redwoodjs.com/) or [on GitHub](https://github.com/redwoodjs/redwood/issues).

**Roadmap**

The roadmap's something I cobbled together. My primary source is the tutorial's [wrapping up](https://redwoodjs.com/tutorial/wrapping-up#roadmap) section. Secondary sources include discourse, github, podcasts. I linked to the source where I could.

It's currently divided into a coming-to-a-redwood-app-near-you section and a part-of-the-plan-but... section.

Please 1) add/remove/change anything 2) make it more specific 3) rearrange it because I didn't list anything in any specific order.

_But I definitely need your help with the future of services._

From what I gathered namely via podcast, services are a really important part of the backend, and while they get some treatment in the tutorial (validating email), it's not clear what the plan is, esp. given this comment in [`makeServices`](https://github.com/redwoodjs/redwood/blob/master/packages/api/src/makeServices.ts):
```
/**
 * This function is a stub for when we fully introduce the concept of
 * services.
 */
```

When are they going to be fully introduced / what does it mean to fully introduce them?

**Contributing**

I really didn't know anything specific about this package before today, so most of the content here's me trying to explain the source code as I learned it. Some sections are incomplete--namely, `makeMergedSchema` (I didn't explain how services get wrapped into resolvers because damn those `importAll` returns are nested). If what's there's the kind of style we're going for, then I'll happily write the rest! I'll also happily change it too. It's a win-win situation.

**Comment by peterp** [comment]
You hit the nail on the head for the purposes.

As far as vision goes, maybe something along the lines of the following:

> To provide a frictionless, and understandable, integrations between the boundaries of Functions (Capital F for Serverless-Functions), GraphQL's Schema and Resolvers, Services, The Database, and Authentication.

I think each one of those could probably expand into an area of future goals, but services are probably a top priority:
> **Services' middleware layer**
> Provide a run-time middleware layer that can run before or after a service is executed; example: create a way for securing service functions based on a user's role, or if a user is authenticated.
```js
import { debugToConsole, printExecutionTimeInMs } from '@redwoodjs/services-middleware-debug'
import { verifyUserRole } from '@redwoodjs/services-auth-middleware'

// services/todos.js

export const before = { 
   deleteTodo: verifyUserRole('admin'),
}

export const after = {
    'all': [debugToConsole, printExecutionTimeInMs]
}

export const deleteTodo = ({ id } ) => {
   // delete from prisma
}
```
^ This is very much just an example.

> Provide a built-time middleware layer so that we can add CRUD like operations, example:
```js
// services/todos.js
export const PRISMA_CRUD_SERVICES = ['create', 'update']
```
Would create those functions at build time.

**Comment by peterp** [comment]
**Functions**
We would also like to make Functions platform agnostic. At the moment we're targeting AWS Lambda Functions, but we should provide a single interface for other providers, and built-time support when you've targeted them.

**Comment by jtoar** [comment]
Thanks! I updated Purpose and Vision and `makeServices` with your input.

One ?: I don't think I understand the second example yet.

> Provide a built-time middleware layer so that we can add CRUD like operations, example:

```
// services/todos.js
export const PRISMA_CRUD_SERVICES = ['create', 'update']
```
> Would create those functions at build time.

Like is this the function its creating? (Taken from the prisma docs)

```
const user = await prisma.user.create({
  data: { email: 'alice@prisma.io' },
})
```

And create/update et al. are usually already defined as services because they're our resolvers. So would they be created again? Or is this in place of that?
