### ISSUE TITLE
Directive generator fails to generate TypeScript definitions and GraphQL schemas

### ISSUE THREAD

**Issue by benrosen** [redwoodjs/redwood#5268]
When I run `yarn rw g directive isOwner`, I see the following output:

```
✔ What type of directive would you like to generate? › Validator
  ✔ Generating directive file ...
    ✔ Successfully wrote file `./api/src/directives/isOwner/isOwner.test.ts`
    ✔ Successfully wrote file `./api/src/directives/isOwner/isOwner.ts`
  ✖ Generating TypeScript definitions and GraphQL schemas ...
    → $ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-onl
…
    Next steps...
Command failed with exit code 1: yarn rw-gen
Usage Error: Couldn't find a script named "rw-gen".

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
```

I have tried:
- using various other directive names
- using the long-form versions of `rw` and `g` (`redwood` and `generate`, respectively)
- appending the `--validator` flag to the command
- upgrading to the latest version of RedwoodJS using the `rw upgrade` command
- going to bed and trying again in the morning

But I'm still seeing the issue. Any ideas on how I can make it work? Thanks in advance for any feedback.

**Comment by jtoar** [comment]
Hey @benrosen I saw this too and fixed it over here: https://github.com/redwoodjs/redwood/pull/5211. It's not in a release yet, but will be in the next one. It's in the unstable canary version of Redwood if you want to try it out now:

```
yarn rw upgrade --tag canary
```

The workaround right now is just to run the `yarn rw g types` command yourself after generating the directive.

**Comment by benrosen** [comment]
Thanks for the temporary workaround and the upcoming fix! I'm loving Redwood so far. It's fun to use. Keep up the good work!

**Comment by jtoar** [comment]
Forgot to close this one after #5211 was merged. Last time I checked it worked but do let me know otherwise!
