### ISSUE TITLE
Improve e2e coverage on storybook 

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#5276]
### What?

We need to increase the e2e/smoke test coverage on storybook, and make sure stories are loaded and running correctly.

Things to check would include:

- [ ] Storybook server launches correctly 
- [ ] `mockCurrentUser` works as expected
- [ ] Cell mocks work correctly
	- [ ] When used for the cell story
	- [ ] When used for a layout embedding a story

**Comment by thedavidprice** [comment]
Also need to check Cell mocks in the context of a Page. During local dev, this hasn't been working for me without a restart.

This leads me to another aspect of the functional test — to test a real workflow, you'll want to create components and mocks _while_ the SB server is already running. In the past, we've added everything and _then_ fired up SB. This is not how we use it when developing.

Thanks for taking this on!

**Comment by dac09** [comment]
Hey @thedavidprice - for the smoke tests, I’m trying to avoid changing source during the test (like we do in e2e). My gut says this is an anti pattern, and eventually becomes difficult to maintain and flakey. 

Once I have my tests up and running, I’ll see if I can find an elegant way though.

**Comment by thedavidprice** [comment]
Understood. But the point of functional tests is to replicate real usage

**Comment by dac09** [comment]
> point of functional tests is to replicate real usage

Yeah totally understand the need - just need to think about how to implement it a bit better, so we don't regret it later!

**Comment by thedavidprice** [comment]
> so we don't regret it later!

hahaha! I feel like all my relationships with CI leave me with regrets. You're saying there's another way?!?

😂
