### ISSUE TITLE
[Docs] Deprecate Self-hosting doc

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#5292]
https://redwoodjs.com/docs/how-to/self-hosting-redwood

We can just point people to Docs > Deployment > Baremetal instead.

**Comment by pantheredeye** [comment]
@cannikin Specifically, are you talking about deprecating the [self-hosting How-To](https://redwoodjs.com/docs/how-to/self-hosting-redwood)?

This is marked as a good first issue - what is needed to 'deprecate' a doc?
