### ISSUE TITLE
Disconnect after a photon request

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#53]
Prisma recommends explicitly disconnecting after a photon request is made. 

We want to simplify DB setup for the tutorial and that means avoiding having to include a connection proxy in front of the DB (many services don't have them yet). If we disconnect after each request then we shouldn't 😬 have any problems overflowing our connection limit.

**Comment by peterp** [comment]
@cannikin I'm trying to find the docs where they mention this because i'm not sure how to go about implementing it,

I did [find this](https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/deployment.md#deployment-providers) though:
> In order to not exhaust the connection limits of your database, you should set the connection_limit parameter of your database connection string in the Prisma schema to 1 when deploying your Prisma-based application to AWS Lambda.

**Comment by cannikin** [comment]
Yeah they've changed their docs so many times recently I couldn't find it either. Maybe that connection_limit setting is their new recommendation?

**Comment by peterp** [comment]
I found [this](https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/api.md#managing-connections):

> IMPORTANT: It is recommended to always explicitly call prisma.disconnect() in your code. Generally the PrismaClient instance disconnects automatically. However, if your program terminates but still prismas an unhandled promise rejection, the port will keep the connection to the data source open beyond the lifetime of your program!

**Comment by cannikin** [comment]
THAT’S THE ONE
