### ISSUE TITLE
Make graphql exceptions visible during development

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#535]
Based off of the discussion over here: https://community.redwoodjs.com/t/uncaught-api-exceptions/531

![image](https://user-images.githubusercontent.com/44849/81791035-7bf1ad80-9506-11ea-97a4-23a6c86414cf.png)

Right now if your GraphQL api returns an exception it's only visible in the console.log of the browser, and you have to drill down into the JSON response to see what's going on.

We should make this more visible during development.

**Comment by MarkPollmann** [comment]
I think an easy first step would be to add a simple [formatError](https://www.apollographql.com/docs/apollo-server/data/errors/#for-the-client-response) to ApolloServer to show the error in the cli console.

**Comment by peterp** [comment]
Oooh, I didn't know about that @MarkPollmann. That's great!

**Comment by MarkPollmann** [comment]
@peterp yep, it's a bit hidden in the documentation 😄 
I tried it with a simple
```ts
formatError: err => console.log(err)
```
and it worked quite nicely. 

We could also take a look at Spectrum for inspiration: 
[Server](https://github.com/withspectrum/spectrum/blob/36eb482917c3d368ef1914b6cd1627aaaeb316e4/api/apollo-server.js#L56) with a [createErrorFormatter function](https://github.com/withspectrum/spectrum/blob/36eb482917c3d368ef1914b6cd1627aaaeb316e4/api/utils/create-graphql-error-formatter.js)

**Comment by thedavidprice** [comment]
@MarkPollmann did you want to give this a go via a PR? (No pressure 😉)

Regarding the two options, any chance you have an example of the output difference between the two? All for a simple approach, but if there's a definitive gain to be had...

**Comment by MarkPollmann** [comment]
Sure, I can do that! I'll post later in the thread Peter linked to.

**Comment by peterp** [comment]
@MarkPollmann Just wanted to give you a heads up that I've already started working on this.

**Comment by MarkPollmann** [comment]
@peterp ah, right, I saw that you assigned yourself two days ago. Let me know if I can help somehow.
