### ISSUE TITLE
Typescript |  Add strict return types for mocks

### ISSUE THREAD

**Issue by s-petey** [redwoodjs/redwood#5354]
The idea would be to generate an `interface` or `type` based off of when a `*.mock.ts` is generated.
Here is my proposed addition, unless I'm missing something that is more complicated than initially thought.

```TypeScript
// ArticlesCell.mock.ts
import type { Post } from 'types/graphql';

export const standard = (): {
  articles: Pick<Post, 'id' | 'title' | 'body' | 'createdAt'>[];
} => {
  return { 
    articles: [
       //   ...
    ]
  }
}

// An additional example for CommentsCell.mock.ts
import type { Comment } from 'types/graphql';

// Define your own mock data here:
export const standard = (): {
  comments: Pick<Comment, 'postId' | 'id' | 'name' | 'createdAt' | 'body'>[]
} => ({
  comments: [
    //    ...
  ]
})
```

An additional example would be using the schema.prisma a type could be generated or used for the mocks off of that. Values wouldn't need to be added, but some generic or "default"  values could be added for different data types.
https://github.com/redwoodjs/example-todo/blob/main/api/db/schema.prisma#L14-L18
https://github.com/redwoodjs/example-todo/blob/main/web/src/components/TodoListCell/TodoListCell.mock.js#L4-L8

**Comment by Tobbe** [comment]
I like this idea. But as I mentioned in the linked (closed) PR #5325  I'm not entirely sure how to construct the types. Should we base them on some other (gql) type? Not sure...

Either way, this file would have to be updated https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/cell/templates/mock.js.template and also https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/cell/templates/mockList.js.template

**Comment by jtoar** [comment]
@Tobbe your question here sounds similar to what we discussed at the last meeting (roughly, should the types get generated from the SDL or the Prisma model?). I'm sure there's still a lot process from that discussion, but did it answer any questions for you here?

@dac09 not a priority for you to answer, but I'm wondering if the TS strict mode PR covers mocks at all? I don't remember reading about mocks in the docs, though how scenario data is typed seems very similar to me here. This is also on the web side, so I'm aware that most of the work in the strict mode PR was focused on the api side.

**Comment by Tobbe** [comment]
@jtoar I didn't remember we had this issue! This is exactly what I wanted to discuss on the call after we were done with the api side. But we never got that far. Hopefully we can discuss this next week.

**Comment by will-ks** [comment]
Hi, this is what I've done in my cell mock.js.template override:

```
import { CellSuccessProps } from '@redwoodjs/web'
import { Find${pascalName}Query, Find${pascalName}QueryVariables } from 'types/graphql'

export const standard = (/* vars, { ctx, req } */): CellSuccessProps<
  Find${pascalName}Query,
  Find${pascalName}QueryVariables
> => ({
  ${camelName}: {
      id: ${mockIdValues[0]}
  },
})
```

Works for me, though I'm not sure if I'm missing some use cases.

**Comment by dac09** [comment]
Thanks @will-ks - this looks like a great solution to me. 

All the types for the mocks are already generated, so reusing it seems like the right thing to do! 

@llmaboi - does this answer your question? In essense you can use the same types that are used in the `Success` component of your cell, for your mocks.
