### ISSUE TITLE
[CLI] automate background checks for new versions, prompt for upgrade

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#537]
This is an enhancement to CLI behavior. 

Ideally, the Redwood CLI will auto-check if it can be upgraded:
- run background check 
- if a more recent version is available, unobtrusively prompt user (e.g. do not interrupt a process like `yarn rw dev`, although this will likely be the most frequently used command)
- confirm the current version and provide the most recent version
- bonus: Provide a link to release notes and/or strong messaging to read release notes before upgrading
    - many releases include breaking changes, we need to emphasize this will messaging/content
    - consider checking release notes if the words "break" or "breaking" are included; give warning if so
- prompt user to run `yarn rw upgrade` when ready to upgrade all RW packages

**Comment by geoff616** [comment]
I would like to help with this, and wanted to confirm I understand the goal of the feature and figure out where the notice should be displayed. 

The goal of the feature is to inform developers they are not running the latest version of redwood, and encourage them to safely upgrade?

I've started looking into how it could be implemented, and thinking it makes sense as a [yargs middleware](https://yargs.js.org/docs/#api-middlewarecallbacks-applybeforevalidation) so the feature can run on all (or a subset) of `yarn redwood` commands without changing anything in `commands/`. For checking the versions, I can get both currently installed and latest by shelling out to `yarn outdated @redwoodjs/core`. Going to defer on the bonus part until the main part is working, but I could try to parse the release notes returned from [Github's API](https://api.github.com/repos/redwoodjs/redwood/releases).

The main decision I need to make next is how to inform the user there is a newer version. I don't want to slow down the CLI with the `yarn outdated` check (400-1000ms in local testing), but do want the notice to consistently be in the same place (i.e. not logging it immediately in the middle of the console when the async check returns). To get the notice at the top of the logs like the examples below, I am thinking of having the middleware run a non-blocking check for a new version on every command. If there is a new version, I would set a flag in a file to indicate there is a newer version. To consistently have the notice at the top of the logs, I could block (1-2 ms in local testing) while reading the flag before kicking off another async check for a new version. This would prompt the user to upgrade on the 2nd `redwood` command after the new version becomes available. 

Do you think the consistent location of the message is important for users, or that the notice should be somewhere other than the top of the logs? 

#### Example Notices
```
~/redwood-app$ yarn rw dev
yarn run v1.22.4
$ /redwood-app/node_modules/.bin/rw dev
Notice - A Redwood Upgrade is Available to 0.10.0 from 0.8.2 - Check out the [Release Notes](https://github.com/redwoodjs/redwood/releases) before running `yarn rw upgrade`
$ /redwood-app/node_modules/.bin/prisma generate --watch
...
09:17:05 web | ℹ ｢wds｣: 404s will fallback to /index.html

---

~/redwood-app$ yarn rw build
yarn run v1.22.4
$ /redwood-app/node_modules/.bin/rw build
Notice - A Redwood Upgrade is Available to 0.10.0 from 0.8.2 - Check out the [Release Notes](https://github.com/redwoodjs/redwood/releases) before running `yarn rw upgrade`
  ✔ Generating the Prisma client...
  ✔ Building "api"...
  ✔ Building "web"...
✨  Done in 14.90s.
```

**Comment by thedavidprice** [comment]
@geoff616 this would be fantastic! Thank you for offering to jump in. I've assigned this to you.

>The goal of the feature is to inform developers they are not running the latest version of redwood, and encourage them to safely upgrade?

^^ Yes indeed! In general, we are attempting to release more often and want it to be convenient+simple to 1) know a release is available and 2) upgrade. However, because Redwood is early it's often not "safe" to upgrade without checking the release notes. This is also important because most new feature and improvement communication is via Release Notes. Here's how I'd prioritize goals:
1. Notify developer a new version is available: display new version number and display current version for comparison
2. Provide the link to GitHub Release Notes: I suggest this be the static link to the [overview Release page](https://github.com/redwoodjs/redwood/releases) (and not the specific release).
3. Give `yarn rw upgrade` command reminder

> yargs middleware

^^ ✅ 🚀

> Going to defer on the bonus part about breaking changes

^^ understood and we'd want to discuss implications for standardizing the Release Notes structure.

But, thinking from how we can "help developers follow best practices and develop good habits" --> I'd rather individuals assume _every_ upgrade has the potential to break things and looking at Release Notes is not skippable. If they rely on the tool to warn them, then their habits will be formed differently. Thoughts/reactions to this?

> Do you think the consistent location of the message is important for users, or that the notice should be somewhere other than the top of the console logs?

^^ In regards to your overall design approach discuss prior to this question, I definitely give it a 👍. Doing this somehow async from the command being run was a primary concern of mine. And it feels very reasonable this would show up on the _next_ command run.

But personally I had assumed this message would display at the end of the console logs. It feels a bit out of context to me if there's content between the command and the initial command output. Some output has many lines (especially for generators) and could easily push this off-screen. Also, in response to your mockup (very helpful!), I'm ok with it spanning multiple lines and including a symbol/emoji to stand out. TBD

Additionally, if this is potentially a "final task" that runs at the end of a command, it could always check for the _flag_ as the last step -- if `yarn outdated` was run async, in some cases, it might have had time to run and would catch the update on the same command. Otherwise, it would catch on the next command run.
 
Last question --> what event would clear the flag and/or how many times should the "hey, you there, upgrade your things!" message be displayed. Once, X times, ... or forever until they upgrade?

**Comment by geoff616** [comment]
Thanks for the additional context @thedavidprice.  

I agree with 
>  individuals assume every upgrade has the potential to break things and looking at Release Notes is not skippable.'

and always pointing people to the [release notes](https://github.com/redwoodjs/redwood/releases). 

I also agree with your point about `console.log` at the beginning not being ideal. `yargs` middleware is a hook prior to the command executing, but `yargs` also provides a hook after the command executes with `onFinishCommand`. Unfortunately, because some of the commands are long-running and kick off other things (i.e. `rw dev`) this doesn't seem like it will provide a consistent user experience across commands - examples below show when middleware/`onFinishCommand` are executing. 

Some options I see:
1. Always insert notice with `onFinishCommand`
2. Only insert notice with `onFinishCommand` on subset of commands where it is guaranteed to be the last console.log (i.e. not `rw dev`)
3. Move the notification out of the terminal console.log, and use a different mechanism to inform the user:
a: OS notification using a package like [node-notifier](https://www.npmjs.com/package/node-notifier) 
b: browser notification in the redwood web application 
c: browser console.log in redwood web application 

where 3a seems like the most consistent, avoids the complexity of branching on "type" of commands, and has the clearest implementation. Do you see another option that makes more sense?

Re clearing the flag/stopping reminders, I think this feature should be possible to turn off for a project. I will think about how this could work and the default behavior a little more once we decide on the notification approach. 

#### Example timing for middleware and onCommandFinish
```
~/redwood-app$ yarn redwood info
yarn run v1.22.4
$ /redwood-app/node_modules/.bin/redwood info
middleware executes

  System:
    ...
    @redwoodjs/core: ^0.8.2 => 0.8.2 

onFinishCommand executes

---

~/redwood-app$ yarn rw g cell BlogPosts
yarn run v1.22.4
$ /redwood-app/node_modules/.bin/rw g cell BlogPosts
middleware executes
  ✔ Generating cell files...
    ✔ Writing `./web/src/components/BlogPostsCell/BlogPostsCell.test.js`...
    ✔ Writing `./web/src/components/BlogPostsCell/BlogPostsCell.js`...
onFinishCommand executes

---

~/redwood-app$ yarn rw dev
yarn run v1.22.4
$ /redwood-app/node_modules/.bin/redwood dev
middleware executes
onFinishCommand executes
$ /redwood-app/node_modules/.bin/dev-server
$ /redwood-app/node_modules/.bin/prisma generate --watch
...
web | ℹ ｢wds｣: 404s will fallback to /index.html

```

**Comment by Josh-Walker-GM** [comment]
I recently ran into two separate times when the bug I was experiencing had been patched and when I realised and updated then I was happy and able to continue. I think an available update notice would have made this an easier process for me and possibly others.

It's over two years since the last comment here. I notice the last mentioned PR was closed and nothing more sadly materialised after that. I had a read through the comments here and on the associated PR but perhaps it would be best to document the current collective opinion of the project/package leads (@cannikin, @thedavidprice, @peterp et al)  here?

In principle I'd be happy to work on this when the proposed specs are clear and no one objects.

**Comment by Tobbe** [comment]
This is good timing @Josh-Walker-GM! We've been focusing a little bit more on our CLI lately, and *I* think something like this would go great with the other work we're doing. But I'd like to give the people you tagged a chance to jump in here if they want before I start making any plans/guidelines. I think Rob and David might be busy today though, so you might have to wait until next week before you hear anything from any of them (or they could find some time sooner, if we're lucky 🙂)

**Comment by Josh-Walker-GM** [comment]
Excellent to hear. I simply had a scroll though oldest outstanding issues and this seemed like a good fit for a renewed discussion.

Absolutely no issues with the timescale or anything like that.

**Comment by cannikin** [comment]
Related to: https://github.com/redwoodjs/redwood/issues/6113

**Comment by cannikin** [comment]
This could be part of the more expansive CLI notification system I discussed in #6113, where we can notify users about important messages, like available upgrades, but also security notices, upcoming events, etc. Just checking for more recent versions seems like a more attainable goal for the near term! And we could continually show it on every CLI invocation until they upgrade, or disable with an ENV var. 

The solution I discussed in #6113 would let us show arbitrary messages, but probably only a single time to prevent annoyance. But maybe some messages are persistent and others only display a configurable number of times.

**Comment by Tobbe** [comment]
@Josh-Walker-GM if you could think of a way to first build out a solution for just this issue, but that is then easily expanded upon to include the ideas in #6113 that'd be great way to get started on all of this

**Comment by Josh-Walker-GM** [comment]
I love the ideas in #6113! I can imagine how this particular update check could be a nice starting point to the bigger system imagined there, I'll give it some thought.

**Comment by Josh-Walker-GM** [comment]
Started #6461 with an implementation of the basic upgrade availablity checker 😄
