### ISSUE TITLE
export dbAuth Types

### ISSUE THREAD

**Issue by shuaixr** [redwoodjs/redwood#5463]
I hope to get better type hints(not any) when configuring dbAuth, but DbAuthHandlerOptions has not been exported
![https://ibb.co/3mW6zMq](https://i.ibb.co/23PVNsQ/ksnip-20220507-062721.png)

**Comment by jtoar** [comment]
Thanks @shuaixr, I think @dac09 is currently investigating this as a part of strict mode: https://github.com/redwoodjs/redwood/pull/5491.
