### ISSUE TITLE
Add typed-document-node to GraphQL plugins

### ISSUE THREAD

**Issue by HikaruEgashira** [redwoodjs/redwood#5468]
## Enhancement of GraphQL

I would like to introduce `typed-document-node` for better type support in GraphQL.
Currently, `DocumentNode` is not typed.

https://github.com/dotansimha/graphql-code-generator

**Comment by orta** [comment]
( looks like it's a client query to types lib, https://github.com/dotansimha/graphql-typed-document-node )

**Comment by HikaruEgashira** [comment]
This tool may not be necessary.
Because naming the query solves the problem.

```typescript
import type { FindAccounts } from 'types/graphql' // typed

export const QUERY = gql`
  query FindAccounts { // named FindAccounts
    --any query--
  }
`
```

**Comment by dac09** [comment]
@HikaruEgashira - you can customise graphql codegenerator with any plugins you like. Please see docs here: https://redwoodjs.com/docs/project-configuration-dev-test-build#graphql-codegen

What would be useful to understand is your actual requirements though - as in why you wanted typed document nodes in the first place? 

Feel free to close the issue too if you've found a solution :)

**Comment by HikaruEgashira** [comment]
Thanks!
