### ISSUE TITLE
Investigate using TypeScript strict mode with Redwood

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#5481]
Things to investigate: 

**Resolvers**
Following #5437 we make it hard to use Resolvers with TS strict mode, because for convenience of testing we set obj and args as optional (which is technically not correct). 

When strict mode is ON, we can switch to using the complete definition of `ResolverFn`

**Docs on:**
- [ ] Prisma types in scenario tests
- [ ] DbAuth functions
- [ ] Src/lib/auth in db auth
- [ ] Resolver configuration changing with typegen
- [ ] Add docs on how to extend context

**Comment by orta** [comment]
Just bumped my app to canary and there still seems to be issues on cross calling resolvers which is kind of intrinsic to how GraphQL resolvers work, I'll explain via an example. This mutation returns a legit slug or empty string to imply you can't use it:

```ts
export const canUseHandle: MutationResolvers["canUseHandle"] = async ({ handle }) => {
  const invalid = leo.check(handle)
  if (invalid) return ""

  const handleSlug = slugify(handle)
  const exists = await db.user.findUnique({ where: { username: handleSlug } })
  if (exists) return ""

  return handleSlug
}
```
Which looks like this to the type system:

```ts
const canUseHandle: (args: RequireFields<MutationcanUseHandleArgs, "handle">, obj: {
    root: {};
    context: RedwoodGraphQLContext;
    info: GraphQLResolveInfo;
}) => Partial<...> | Promise<...>
```

The tricky bit is here `Partial<...>` - which means you cannot write

```ts
export const createNewUserOnAccount: MutationResolvers["createNewUserOnAccount"] = async (args) => {
  const username = await canUseHandle({ handle: args.input.username }, {} as any)
  if (!username) {
    return null
  }
  // ....
```

Because the type of `canUseHandle` is either a string or a Promise<string>. E.g. _not a function to a string or the promise_ but the `T` or `Promise<T>` directly. I would have expected that `makeResolverTypeCallable` would make those callable?

Looking at [the codegen code](https://github.com/dotansimha/graphql-code-generator/blob/a11817bac5bf012715d043559dabb1b9fb34a0a9/packages/plugins/typescript/resolvers/src/index.ts#L42-L43) - I think I would have expected to see a lot of `ResolverFnModelName` in the .d.ts files - but I think the config change isn't doing the work

**Comment by dac09** [comment]
I'm also super stuck with this problem... I don't understand why TypeScript doesn't let me await a Promise<Partial<X>>?

**Comment by orta** [comment]
There's a possibility of a TS bug here, this [simplified model](https://www.typescriptlang.org/play?#code/PTAEGUEsFsAcBsCmBnALqAxgQ2YgUHqgJ6yKgDiATlrABYCKAMgEooD28AbogJIB2AMzagAvKADeAX0IkyrACYB3Nm3lUaDRgGE2fVIgAe6MVJmlQrZB26VkABSyVEegCqzkoidMOw2ldMTmALJYRABGiAA8LgB8ni6gAD6gfACu8PAEeD5+AbIW7FyIlABifNGW6agANKAuDk56tS46eoY1dQCClADmyHFiABR4oKCOfQBcXb3I1SOgbGEAVlPioJQqqFP1js6oANyYuvpG260nB6CQgmxT6nRMlta8N6DSAJSicXYb0JC4kQaqEgWHgFRQVRiMQIOX8oECckKNnByCqzQae08Uma53aWMkzW6fXxAwKViKpXKLkq8A6O0adNxRkJM2hZjIQVSqCwwN0TwpyEiTNQbnMYgUylU900wtJ4nm2D4AFVcAAJLB8eRIAD8U35yJC4SiaEo1x6MVqGqItWFosQlr4RGh0jwGF0aEwGpViHVmqQU053N5fH1xWQAG0AESK72+rWISMAXU8OCIfAwoEGa1oGvjb0+Iji8tGTlQqUofFAOb9+Bdbr4HtSuArWGgZDEWEUWEg6BjatzSCzVYHiCmkdyWEjb1qUjGHit7wIIFAAHU-ABrDyKHu0NhcsaOzDVnooPBAA) of the issue doesn't have issues when doing `await () => Promise<Partial<X>>`

**Comment by dac09** [comment]
> We'd either need a Promise-y only version of MutationResolvers["canUseHandle"] to use after the const - e.g.
Think I follow what you mean... but what I still dont understand is why removing `Partial` makes it stop complaining? If you leave all the other types exactly the same, but just remove the Partial, [there's be no errors](https://www.typescriptlang.org/play?#code/PTAEDEFcBttBjA9gBwJ6kQM1AFwBYCmuqyBAzqAFCU4lEDiATgIbJ4CKAMgErmLQA3AgEkAdpkSgAvKADeAXxp1QvACYB3RIlVNWHTgGFEonAQAeOaXMXnkiRpdqlQAWWaoARgQA8AFQB8Vr6gAD6gojDQlLb2jsoAyvDM0MyMFDKylKCg8TiMAJaiAOYAXKBkeYVFANyUitFmdg7Ezrxk-EJpvnTpclnZA7kFxWVtHQSM3aQA6izIpIzeicmpZADaAORDVRsAuv61dQ1Nca18ghNTBLOsC36BMgAKjIgAtvlkPgGhoL6Hx7EWkQXJAcMwcPljElRABVT4ACWYolU0AIAEFGEVeplsngkSiCGUKsManVDjFmk4iGMLmlHqkCCYrtj+tkQWCIcYygpavUKadqQQAI6QfKMAjgfIEaCqMh+AA0oAA0qBzKZkRQANYEVBYX4PUAAeXeOAVysCADI5KA1o9QIVlbsALQAfjKADljO7IswPKi-Lb9qB5OTGoCqSpzp1wKI-G0YDhFb56eKTEmjCY1UmMViDQAKfqpLFlXw5sjy-qIDwAK25oBeiBwJZTjJw1QQxlMFhLGa7bft4kQZV0bC4NKEYgkwcoAEppIFnm8Pl949AcIEQKBALwbgAkd0AAEQMZXy9YIr0QQlUoGQqQhyVAhHFivxqs6qHwVVAmkYmrIADpQAAIVBUBpnhNFhBdah+SBSN2lpONyATJMWxMKwFHTTs1XQ+Rs0xbF5ANccJhjRCyGQ35UMTX5eyzX4y38aCw0pZR2XBSFRGItJvFoiwrisNRNG0Ed9F46iqP4tVGVlODxjpBkmR6TY2M5UQ9gEqMJjICSlI2FSOL2A0cQQJE4QIRFkVRN1ZIQtxPB8LiyGZTZtmKQzFR00hFTEq5FV4EUxQlKUZTlfSoVMhF8VRMtFQ2PFLIIDZ-AOI5KCQUQKhM2FIoSsows4zS0jWAAiaEzIsglit2KxmDIVBRHgUA81kB8oqIeQ5ykQJjPFHBIEYURWoS1L0sy9pXgID9iisMqcoJZqhoJMpitiZhiuDRUFFAWrttEVAZ0oTcBlAAA9KCAWaUbLHgcVwQId0CHUMzGENUQ0XgJBIDQmRavqxq8yLMhOu6-ortASBPgG5gJpq9RmHya6IvMtqFvipbQBWhw1o26xtooJF9rqIA)

**Comment by Tobbe** [comment]
I think there might be an issue with the type generation here.
If I'm reading the full failing repro correctly the type pretty much boils down to 
```ts
type CanUseHandle = ({ handle }: { handle: string }) => Promise<Partial<Promise<string> | string>>
```
But I think it should be
```
type CanUseHandle = ({ handle }: { handle: string }) => Promise<Partial<string>> | Partial<string>
```

Having `Partial<Promise<string>>` makes no sense. It's like "Here's a promise, but it might not have a `then` method..."

**Comment by dac09** [comment]
Think you misread. It's not a Partial of a promise. It's a promise of a partial.

**Comment by dac09** [comment]
So looks like we have a fix based on @Tobbe's observation. 

Since our types weren't complex enough, we made it a little more complex:

```ts
export type ResolverFn<TResult, TParent, TContext, TArgs> = (
  args: TArgs,
  obj?: { root: TParent; context: TContext; info: GraphQLResolveInfo }
) => TResult extends PromiseLike<infer TResult>
  ? Promise<Partial<ThenArg<TResult>>>
  : Promise<Partial<TResult>> | Partial<TResult>
```

@orta  thoughts?

**Comment by Tobbe** [comment]
@dac09 With the code you posted above you've added `Partial<TResult>`to the return value. Previously it was always a Promise. (`Promise<Partial<TResult>>`)

**Comment by dac09** [comment]
The problem you're seeing here, I believe is something with how typescript in strict mode interprets `Promise<Game | null` vs `Promise<Game> | Promise<null>` - which _I think_ should be equivalent. If it isn't.... whats the difference?!

I'm waiting to hear back from the Prisma team - this seems to be the last unresolved issue on the API side - it happens exclusively on the `findUnique` ones because findUniques return `Promise<TData | null>`

> creating per-service file type definition which are explicitly generating the exact types for the exports
The reason I prefer gql-codegen still, is because if, for example, you use "select" in your Prisma queries, without using the codegen types, we wouldn't know what fields are required. e.g.

```ts
// This will error out with gql-codegen, telling us we need to return atleast whatever the sdl defines bazingas as
const bazingas: QueryResolvers['bazingas'] = () => {
  return db.bazinga.findMany({select: {id: true}}
}
```

On similar note, I'm also not sure about whether `Partial<TResult>` is correct - will need to look into this more.

**Comment by dac09** [comment]
Hey @orta - I'm wondering if I could get your help on the last remaining issue? 

To summarise the problem:

- Prisma's return types for findUnique is `Promise<Model | null>`
- vs graphql-codegen expected type is `Promise<Model> | Promise<null>`

This means that you can't just return from a `db.model.findUnique` call in a service/resolver, but instead you need to do 
```
return db.model.findUnique(...) as Promise<Model> | Promise<null>
```

Here's [a playground repro](https://www.typescriptlang.org/play?strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&jsx=0&ts=4.7.0-beta#code/CYUwxgNghgTiAEEQBd4FcB2BLA9hgkhgAow4C2WAziAFzwnlUgA8AjPAD7wBMAfAFChIsBElSZcGAPJpklLKAYVqdJUza9O9UspZ9+-CXhlyFINdXgBedNjyELCAPRP4yABZV4UCJRzwQGFIYSngcWUM7AmIdJmtbSRN5RVjqA34XeABBDBwPQICADygyAAckQXBoOEQUbzoACgaASmtNVlauJtarTW5myuEasXgAI0aWtvh2Ln6DKHjR+EyPL0Dg0PDkfiWbKH4gA) of the problem. I understand that the types aren't _exactly_ the same, but in reality this really shouldn't be an issue because at runtime there's no difference between the two types.

For now I'm just going to document it, but if you had any tips or suggestions I'm all ears!

**Comment by ebramanti** [comment]
@dac09 Not sure if this helps for the `findUnique` but maybe there's a way to use mappers to override the type in the codegen? I saw this comment, pretty old so not sure if it exactly solves the issue: https://github.com/dotansimha/graphql-code-generator/issues/1793#issuecomment-488302686

**Comment by orta** [comment]
I asked in the discord, where we got some pretty good explanations about why structurally you can only really compare in one direction:

![image](https://user-images.githubusercontent.com/49038/174581146-e54b915d-12d1-4472-b326-0255c20e257b.png)

Which I think makes sense generally, what you accept for one of those - personally, I think switching graphql-codegen to use `Promise<Model | null>` makes sense because it is the more flexible of the two ways to describe that pattern of something or nothing
