### ISSUE TITLE
"Uncaught Error: Function components cannot have string refs" when adding a "?ref=xyz" param to the base url

### ISSUE THREAD

**Issue by ronatory** [redwoodjs/redwood#5497]
Seems to be easy reproducible. Just create a new redwood project and start the dev server via `yarn rw dev` and then add to the base url a `ref` parameter like this -> `http://localhost:8910?ref=example`. Then the error in the title will occur -> `Uncaught Error: Function components cannot have string refs`

**Comment by KrisCoulson** [comment]
I just took a look into it.

I think we spread all the params and ref is being passed as a string 
https://github.com/redwoodjs/redwood/blob/230f79d07b50e8aad3635ffe1484531a6ae31342/packages/router/src/router.tsx#L101

https://github.com/redwoodjs/redwood/blob/230f79d07b50e8aad3635ffe1484531a6ae31342/packages/router/src/router.tsx#L118

**Comment by jtoar** [comment]
@KrisCoulson Nice, that looks like what's happening indeed. I haven't thought about it much yet, but a solution that comes immediately to mind is renaming `ref` to something else. Is that too superficial?

**Comment by arrbrk1** [comment]
It worked, thank you! :)

**Comment by jtoar** [comment]
@arrbrk1 the patch with the fix just went out: https://github.com/redwoodjs/redwood/releases/tag/v2.2.4. When you upgrade be sure to get rid of the yarn patch file, or at least change the resolution so that it's just `2.2.4`.

**Comment by ronatory** [comment]
Hello @jtoar I just upgraded to v3.0.0 and the error still occurs when doing the same steps as in my first [comment](https://github.com/redwoodjs/redwood/issues/5497#issue-1231525375)

**Comment by Tobbe** [comment]
@ronatory I tried to reproduce, but I couldn't.

![image](https://user-images.githubusercontent.com/30793/191256786-fe345997-9b75-4f48-873a-287ce083f30b.png)

Seems to work fine. 

Just had to do `yarn create redwood-app` and then `yarn rw dev`, right?

**Comment by ronatory** [comment]
@Tobbe thanks for checking. I just didn't upgraded correctly to v3.0.0. Now I did and everything works fine 🎉
