### ISSUE TITLE
Is the auth system completed? 

### ISSUE THREAD

**Issue by zwl1619** [redwoodjs/redwood#552]
Is the auth system completed? I find [https://github.com/redwoodjs/redwood/issues/214](url) has been closed.   If completed, I have two questions:

1、in [https://github.com/redwoodjs/redwood/issues/217](url) , @chris-hailstorm said:

> the easy way is to use Gatsby for the static parts of your site and Redwood for the dynamic parts. The great thing about a static site is, you don't need a server or any kind of hosting -- e.g. with Gatsby, you can publish static files to an AWS S3 bucket and be done. Add a DNS name that points to that static file location and you have a very simple solution.

>So maybe `www.whatever.com` is in Gatsby, and `app.whatever.com` is in Redwood. You can share React components, styling etc. between sites using normal JS tools if that makes sense.

I plan to use gatsby for static pages. Could give a tutorial about Single Sign On (SSO) ?

2、Can the auth system implement RBAC now? This issue was mentioned in [https://github.com/redwoodjs/redwood/issues/212](url)

Thanks!

**Comment by thedavidprice** [comment]
Hi @zwl1619 

The Auth package is in master branch and is being tested. Things are looking good! Expect a RWJS release v0.7 within a few days. For testing purposes, we are now publishing `canary` tagged branches on NPM. [Here's the latest one for Auth](https://www.npmjs.com/package/@redwoodjs/auth/v/0.6.1-canary.42).
- ⚠️these are _unstable_ releases and should be for testing only
- you'll need to update all 4 RWJS packages to @canary if you want to try them
- you should install Auth in web/ `yarn workspace web add @redwoodjs/auth@canary`

Here are the current Docs for Auth:
https://github.com/redwoodjs/redwood/tree/master/packages/auth

We will be updating the Tutorial with an example of using Netlify Auth. You could have a "Login" link from your Gatsby site that redirects to `app.yoursite.com` login page (or modal). It's possible to pass Auth token between domains, but that will require more work.

RBAC will not be supported at this time. It is on the roadmap. And we hope to release a roadmap document in the near future.
