### ISSUE TITLE
GraphQL mocks do not work in built/deployed storybook

### ISSUE THREAD

**Issue by pvenable** [redwoodjs/redwood#5534]
[Mocking GraphQL in Storybook](https://redwoodjs.com/docs/how-to/mocking-graphql-in-storybook) works great in development (`yarn rw sb`):

![image](https://user-images.githubusercontent.com/590685/168409134-bcac3415-609b-4a58-970d-f53616bcd809.png)

But in a built/deployed environment (`yarn rw sb --build && yarn rw build`, then deploy or otherwise serve `web/dist` somewhere), the mock request handlers are missing:

![image](https://user-images.githubusercontent.com/590685/168409153-89f274df-5f01-48e8-8ead-23bb0854f8ad.png)

Because the mock handlers are missing, this also means that the storybook graphql queries are being passed through to the live server, so in some cases it may not be immediately apparent that something is broken -- stories may render live data from the hosting app's API!

_Note: _some_ mocking does work even when deployed -- for example `__REDWOOD__AUTH_GET_CURRENT_USER`:_

![image](https://user-images.githubusercontent.com/590685/168409683-bccd74a1-0ae5-42bf-8a2d-798f7f812c18.png)

Development behavior can be observed by cloning https://github.com/redwoodjs/example-storybook and running `yarn && yarn rw sb`, and "production" can be observed in the live app at https://redwoodjs-example-storybook.netlify.app/storybook/.  The screenshots above are taken from console output for the [`ArticlePage` entry](https://redwoodjs-example-storybook.netlify.app/storybook/?path=/story/pages-articlepage--generated).

The expected behavior would be that graphql mocking works in deployed storybooks just as it does in development.

---

On a related note (mainly because this is what led me to this issue), it would be nice (and perhaps expected) to be able to deploy a storybook build _independently_ of an app deployment; for example, I would like to deploy just the output of `yarn rw sb --build` (which outputs to `web/public/storybook/`) somewhere without needing to build or deploy the main app along with it.  It's possible all that's needed for this to work is to put a copy of `mockServiceWorker.js` in `web/public/storybook/` too, but it's hard to be sure until the above issue is resolved.

**Comment by jtoar** [comment]
Thanks @pvenable! Linking the original discord thread here for reference: https://discord.com/channels/679514959968993311/974036287315132466.

**Comment by jonocodes** [comment]
I can confirm this is still and issue. I am using core 3.5.0

And as stated in the original post, this URL still shows the issue
https://redwoodjs-example-storybook.netlify.app/storybook/?path=/story/pages-aboutpage--generated

The interesting thing is when visiting the page it first gives the error: "mockGraphQLMutation is not defined"
Then I click another story and it errors: "[MSW] Failed to register the Service Worker:"
Then I click another story and it works without errors. So at some point redwood testing must be making it into the live storybook.

**Comment by simoncrypta** [comment]
The solution for now is to add a new webpack config to storybook. 
The reason it doesn't work now is that Mocks is only enable on dev mode in the default Redwood config right now. 
You can make it work by modify your `web/config/storybook.config.js` file
```js
const webpack = require('webpack')

module.exports = {
  addons: [
    'YOUR ADDONS',
  ],
  webpackFinal: async (config, { configType }) => {
    configType === 'PRODUCTION' &&
      config.plugins.push(
        new webpack.ProvidePlugin({
          mockGraphQLQuery: ['@redwoodjs/testing/web', 'mockGraphQLQuery'],
          mockGraphQLMutation: [
            '@redwoodjs/testing/web',
            'mockGraphQLMutation',
          ],
          mockCurrentUser: ['@redwoodjs/testing/web', 'mockCurrentUser'],
        })
      )
    return config
  },
}
```

**Comment by jonocodes** [comment]
Thanks @simoncrypta . I tried your config. It got rid of the mockGraphQLMutation errors. But does not solve the "[MSW]" error.

**Comment by simoncrypta** [comment]
@jonocodes Oh yes, that's another issue where MSW is always built into web/public. 
Right now, you can drag and drop the mockServiceWorker.js file into your storybook build folder.
I will work on a fix soon.

**Comment by jonocodes** [comment]
Thanks @simoncrypta, that works. It gets me exactly where I need for now.
