### ISSUE TITLE
Missing field 'roles' in auth.ts during tutorial 

### ISSUE THREAD

**Issue by Avataw** [redwoodjs/redwood#5542]
During the tutorial chapter 4 / Authentication, I've noticed that in the auth.ts I get some errors: 

![image](https://user-images.githubusercontent.com/60570041/168467215-66db0578-1562-416a-9a78-bab916a54d4b.png)

Makes sense as I was not supposed to add roles to the user in the model 
```prisma
model User {
  id                  Int       @id @default(autoincrement())
  name                String?
  email               String    @unique
  hashedPassword      String
  salt                String
  resetToken          String?
  resetTokenExpiresAt DateTime?
}
```
nor in the select of getCurrentUser in auth.ts
```ts
export const getCurrentUser = async (session) => {
  return await db.user.findUnique({
    where: { id: session.id },
    select: { id: true, email: true },
  })
}
```

The tutorial does mention (see "AUTHENTICATION VS. AUTHORIZATION" infobox) above that Authorization is going to come up later - still I think that stumbling upon errors while doing the tutorial can be confusing or distracting to new users.

I'd propose the following options: 
A) Address the missing roles in auth.ts with a warning and mention that it's going to come later in the tutorial
B) add roles to the model already and leave it empty with a comment that it's going to be correctly implemented later

**Comment by simoncrypta** [comment]
Hi @Avataw, 

Option A) is a great idea! 
I think the best way to do it is to write a comment in TS version of the code exemple where the error show up.

Feel free to open a PR if you want ! 
https://github.com/redwoodjs/redwood/blob/main/docs/docs/tutorial/chapter4/authentication.md

**Comment by Avataw** [comment]
I'll take care of it, feel free to assign me :)
