### ISSUE TITLE
Cannot find module 'terminal-link'

### ISSUE THREAD

**Issue by pi0neerpat** [redwoodjs/redwood#5584]
Error after running command `rw-server api` using global install of `@redwoodjs/api-server` and `@redwoodjs/internal`. Redwood v1.0.0 using docker container https://github.com/redwoodjs/docker/blob/main/docker/pi0neerpat-packages/api/Dockerfile

Is anyone else is getting this?

```
Error: Cannot find module 'terminal-link'
Require stack:
- /usr/local/share/.config/yarn/global/node_modules/@redwoodjs/internal/dist/generate/graphqlSchema.js`
```

```
yarn why v1.22.5
[1/4] Why do we have the module "terminal-link"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "terminal-link@2.1.1"
info Reasons this module exists
   - "_project_#@redwoodjs#core#@redwoodjs#cli" depends on it
   - Hoisted from "_project_#@redwoodjs#core#@redwoodjs#cli#terminal-link"
   - Hoisted from "_project_#@redwoodjs#core#@redwoodjs#cli#@prisma#sdk#terminal-link"
   - Hoisted from "_project_#@redwoodjs#core#@redwoodjs#cli#@prisma#sdk#@prisma#engine-core#terminal-link"
   - Hoisted from "_project_#@redwoodjs#core#@redwoodjs#cli#@redwoodjs#structure#@prisma#sdk#terminal-link"
   - Hoisted from "_project_#@redwoodjs#core#@redwoodjs#cli#@redwoodjs#structure#@prisma#sdk#@prisma#engine-core#terminal-link"
   - Hoisted from "_project_#@redwoodjs#core#@redwoodjs#testing#jest#@jest#core#@jest#reporters#terminal-link"
```

https://github.com/sindresorhus/terminal-link

Temporary solution is to also global install `terminal-link`

**Comment by pi0neerpat** [comment]
Update: Looks like a recent update to redwood is causing the issue.  I applied a fix by pinning the version for global installs to v1.0.0 for now.

https://github.com/pi0neerpat/redwood-devops-example/pull/5/files

**Comment by jtoar** [comment]
It looks like `graphqlSchema` in `@redwoodjs/internal` imports `terminalLink`:

https://github.com/redwoodjs/redwood/blob/dec0bd9f8b546de1bf007992554bb648bfda67b0/packages/internal/src/generate/graphqlSchema.ts#L10

But `terminalLink` isn't in the `package.json` of `@redwoodjs/internal`, so if only internal is being installed, that's of course a no go. I'm sure in redwood apps, `@redwodjs/cli` provides and it's being hoisted which is why it works.

> Update: Looks like a recent update to redwood is causing the issue

@pi0neerpat did you know exactly which update that was? Or did you just mean running the upgrade command?

**Comment by pi0neerpat** [comment]
Its a global install, so I don't see the versions unfortunately. Our last deployment was 13 days ago, which had no issue, so I'm guessing v1.3 or v1.4.

```dockerfile
RUN yarn global add @redwoodjs/api-server@1.0.0 @redwoodjs/internal@1.0.0 lerna prisma && \
```

**Comment by jtoar** [comment]
@pi0neerpat if we got https://github.com/redwoodjs/redwood/pull/5590 into canary would you be able to test it?

**Comment by pi0neerpat** [comment]
Yes for sure

**Comment by jtoar** [comment]
@pi0neerpat the canary with that PR just published: `1.4.2-canary.130+2145f443`. But `yarn rw upgrade --tag canary` is all you should have to do to get there. Or `@redwoodjs/api-server@1.4.2-canary.130`, `@redwoodjs/internal@1.4.2-canary.130`.

**Comment by pi0neerpat** [comment]
Working! ![image](https://user-images.githubusercontent.com/35622595/169364931-431ac422-16d7-442d-b0a1-9f519dd1f0d7.png)

**Comment by jeliasson** [comment]
I can also confirm `1.4.2-canary.130` fixes it.

**Comment by jtoar** [comment]
Thanks guys! I included the fix in the latest patch: https://github.com/redwoodjs/redwood/releases/tag/v1.4.2. You should be able to remove the canary part now, and even the specific version as it's the latest.

**Comment by jtoar** [comment]
Will close but let me know if anything else goes wrong.
