### ISSUE TITLE
Investigate building lambda functions with webpack

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#56]

**Comment by sw-yx** [comment]
you might crib heavily from https://github.com/netlify/netlify-lambda

**Comment by mojombo** [comment]
@sw-yx Will do! We used to use it way back, but switched to ZiSi, and are now wondering if a Webpack-based solution could give a more consistent web/api experience.

**Comment by sw-yx** [comment]
ah, didnt know. tough call here. if typescript/esmodules are high priority, definitely use it. if they're not, then its more of a coin toss. i know it well so  i know when to use it in my projects, but as to whether its a good fit for redwood, i have no idea

**Comment by mojombo** [comment]
I experimented with this a tiny bit, but immediately ran into dynamic `require` issues in Photon. I feel like this might be an uphill battle with server-side node libraries that expect to be able to do dynamic `require`s.

**Comment by mojombo** [comment]
We got things working properly with ZiSi, I don't think we need to go down this road anymore at the moment.
