### ISSUE TITLE
Chakra UI set up is incompatible with initial project template

### ISSUE THREAD

**Issue by djaustin** [redwoodjs/redwood#5601]
Creating a new project with `yarn create redwood-app <name>` followed by setting up the project with Chakra UI causes errors in the web project.

It seems that the version of Chakra being installed by the setup CLI is dependent on `useId` from React which was only [introduced in React 18](https://reactjs.org/blog/2022/03/29/react-v18.html#new-hooks).

Upgrading React to version 18 in the web project seems to resolve this.

## Steps to reproduce
1. `yarn create redwood-app chakra-test`
2. `cd chakra-test`
3.  `yarn rw setup ui chakra-ui`
4. `yarn rw dev`

## Expected outcome
The Redwood welcome page is displayed

## Actual outcome
An error is thrown
```
Uncaught TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.startTransition) is not a function
    at ref (chakra-ui-react-env.esm.js:137:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at safelyDetachRef (react-dom.development.js:20435:1)
    at commitUnmount (react-dom.development.js:20959:1)
    at commitNestedUnmounts (react-dom.development.js:21004:1)
    at unmountHostComponents (react-dom.development.js:21290:1)
    at commitDeletion (react-dom.development.js:21347:1)
    at commitMutationEffects (react-dom.development.js:23407:1)
```
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/9084497/169497150-35aa9aed-d2ea-4594-b00a-bbd4599af656.png">

**Comment by callingmedic911** [comment]
We're discussing this here: https://github.com/redwoodjs/redwood/pull/5570#issuecomment-1132504462

As a temporary workaround, you can change this line in `web/package.json`:
```diff
-"@chakra-ui/react": "^2.0.2",
+"@chakra-ui/react": "^1.3.0",
```

**Comment by zygopleural** [comment]
> As a temporary workaround, you can change this line in `web/package.json`:
> 
> ```diff
> -"@chakra-ui/react": "^2.0.2",
> +"@chakra-ui/react": "^1.3.0",
> ```

`Error: @chakra-ui/react@npm:1.3.0: No candidates found`

FYI for anyone coming here, I got this working with:
```diff
-"@chakra-ui/react": "^2.0.2",
+"@chakra-ui/react": "^1.8.8",
```

Full config:
```json
"dependencies": {
  "@chakra-ui/icons": "^2.0.0",
  "@chakra-ui/react": "^1.8.8",
  ...
},
"devDependencies": {
  "@chakra-ui/storybook-addon": "^1.0.3"
}
```

**Comment by Philzen** [comment]
Is there already an upgrade plan to React 18 or are there any showstoppers for that?

Asking b/c we would love to update our existing project to Chakra UI 2.x to utilize the new storybook addon.
