### ISSUE TITLE
developer experience: mocking Date.now()

### ISSUE THREAD

**Issue by alephao** [redwoodjs/redwood#5605]
Hello, while doing the tutorial I saw this line:

> We could test that the actual timestamp is correct, but that involves freezing the Javascript Date object...

And then it points out to [an article](https://codewithhugo.com/mocking-the-current-date-in-jest-tests/) showing how hard it is to mock/stub the javascript `Date` object.

I come from the iOS world and there I started using a pattern that is pretty straight forward, easy to implement and easy to use. Since this is an opinionated framework that suggests doing things in a certain way on many topics, I thought would be good to introduce this idea here so it would be another one of those ideas that will make developer's life easier:

So here it goes:

The idea is to provide a proxy for `Date.now`, in one of RedwoordJS's packages and suggest that users use it. Here is an example implementation with mocking capabilities:

```ts
// ------- Implementation

// This class is just a wrapper around the `now` function, to have a reference to it
class Now {
  now: () => number

  constructor() {
    this.now = () => Date.now()
  }
}

// Create an internal (and the only) instance of Now
const _Now = new Now()

// external: users can access it. constant: users can't change it
// referencing _Now.now. If _Now.now changes, this changes, making it mockable.
export const now = () => _Now.now()

// can be mocked with a number or a Date
export const withNow = (date: number | Date, callback: () => void) => {
  _Now.now = typeof date === "number" ? () => date : () => date.getTime()
  callback()
  _Now.now = () => Date.now()
}

// other option for mocking
export const mockNow = (date: number | Date) => {
  _Now.now = typeof date === "number" ? () => date : () => date.getTime()
}
export const unmockNow = () => {
  _Now.now = () => Date.now()
}

// ------- Usage

// Mocking with option 1
console.log(now())      // current timestamp
withNow(10, () => {
  console.log(now())    // 10
})
console.log(now())      // current timestamp

// Mocking with option 2
console.log(now())      // current timestamp
mockNow(10)
console.log(now())      // 10
unmockNow()
console.log(now())      // current timestamp
```

This would probably live in the `internals` package, then the `testing` package exports `withNow` while `api` and `web` packages export the `now` function.

Users would replace every `Date.now()` and `new Date().getTime()` instances with `now()`.

--

This is an example specific to `Date`, but it can be used for everything out of the developer's control, there is a great video explaining the overall idea: https://www.pointfree.co/blog/posts/21-how-to-control-the-world

**Comment by callingmedic911** [comment]
Thanks for the feedback @alephao! Do you think using timer mocks with jest would help with your use case? https://jestjs.io/docs/timer-mocks

We may want to update the tutorial to recommend Jest's timer. @jtoar What do you think?

**Comment by Tobbe** [comment]
@alephao Thanks for your Issue/RFC. Well written and with good reference links 👍

**Comment by alephao** [comment]
@Tobbe thank you!

@callingmedic911 Thanks for answering! The timer mocks with jest doesn't help because I'm trying to mock the current Date/timestamp, and not a timer!

I'll try to clarify with my real use case

**Intro**

In my app, people do some action, and they can claim a reward 7 days after doing that action. I want to show the user the time left until the next reward, depending on how much time left, I show `7 days left` or `23 hours left` or `40 minutes left`  etc. I store the timestamp of when the user did the action for the last time, and use the timestamp to calculate what to show them in the UI.

**Concrete example with code**

I make a request and get the following data:

```json
{
  "timestamp": 12345678
}
```

With that timestamp I derive what I want to show the user with a function like that:

```ts
const seconds = 1
const minutes = 60 * seconds
const hours = 60 * minutes
const days = 24 * hours

const timeLeftForNextReward = (timestamp: number) => {
  const nextRewardTimestamp = timestamp + (7 * days)
  const timeLeft = nextRewardTimestamp - now()

  // User can already claim reward
  if (timeLeft <= 0) {
    return 'now'
  }

  if (timeLeft > days) {
    const daysLeft = Math.ceil(timeLeft / days)
    return daysLeft > 1 ? `${daysLeft} days` : `${daysLeft} day`
  }

  if (timeLeft > hours) {
    const hoursLeft = Math.ceil(timestampDiff / hours)
    return hoursLeft > 1 ? `${hoursLeft} hours` : `${hoursLeft} hour`
  }

  if (timeLeft > minutes) {
    const minutesLeft = Math.ceil(timestampDiff / minutes)
    return minutesLeft > 1 ? `${minutesLeft} mins` : `${minutesLeft} mins`
  }

  return 'few secs'
}
```

This function is a perfect candidate for a unit test, and I do want to make sure it is working how I expect. Since I'm using `now()` (the thing proposed above) instead of `Date.now()`, I can easily do that:

```ts
describe('timeLeftForNextReward', () => {
  it('should return now for past date', () => {
    withNow(weeks, () => {
      expect(timeLeftForNextReward(weeks - days)).toEqual('now')
    })
  })

  it('should return days left if more than a day from now', () => {
    withNow(weeks, () => {
      expect(timeLeftForNextReward(2 * weeks)).toEqual('7 days')
    })
  })

  it('should return hours if less than a day from now', () => {
    withNow(weeks, () => {
      expect(timeLeft(weeks + days - hours)).toEqual('23 hours')
    })
  })

  it('should return minutes if less than an hour from now', () => {
    withNow(weeks, () => {
      expect(timeLeft(weeks + hours - minutes)).toEqual('59 mins')
    })
  })

  it('should return few seconds if less than a minute from now', () => {
    withNow(weeks, () => {
      expect(timeLeft(weeks + minutes - seconds)).toEqual('few secs')
    })
  })
})
```

I hope it clarifies a bit

**Comment by callingmedic911** [comment]
@alephao Your example is really helpful. I'm trying to understand if the following would work with your example - I see `now()` uses `Date.now()` internally so setting system time should work I think. If this works, perhaps we can directly use `Date.now()`?

```js
describe('timeLeftForNextReward', () => {
  beforeAll(() => {
   // This should change system time and `Date.now()` should return provided value here.
    jest
      .useFakeTimers()
      .setSystemTime(new Date(/* provide any date here */))
  })

  afterAll(() => {
    // Reset mock timer
    jest.useRealTimers()
  })

  it('should return now for past date', () => {
    expect(timeLeftForNextReward(testTimeStamp)).toEqual('now')
  })
})
```

**Comment by alephao** [comment]
@callingmedic911 it should work! I missed that in the documentation, thanks!
