### ISSUE TITLE
Command "rtw" not found

### ISSUE THREAD

**Issue by Burnsy** [redwoodjs/redwood#561]
Hello, 

I have built a new auth provider, but when i go to inject it into the example invoice app, it cannot find the command.

error `error Command "rtw" not found.`.
I also tried globally installing redwood-tools, but package is not found.

what is the best way to get access to the package so that i can move onto testing the auth provider.

Thanks

**Comment by peterp** [comment]
Hey @Burnsy,

I would recommend upgrading the `@redwoodjs/core` package in `package.json` to the latest canary release.

You can do that by changing this line to `0.7.0-canary.0`:
https://github.com/redwoodjs/create-redwood-app/blob/master/package.json#L10

And running `yarn install`

At this stage you'll have the `rwt` command installed.
