### ISSUE TITLE
[Testing] Support Jest --config extensibility

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#564]
_related to #502_
_original conversation [here in #521](https://github.com/redwoodjs/redwood/pull/521#issuecomment-630770488)_

**Goal:**
> if additional Jest config is needed, add the capability for simple config extension managed from either App root or specific to App sides (e.g. web/, api/, etc.).

From @RobertBroersma 
**Option 1:** a simple near-term solution is to document
>Atm you could extend the config by directly importing the jest config from core and merging it with your local jest config, however this is Currently undocumented

**Option 2:** improved solution
>I'm thinking along the way of exposing the Redwood jest config(s) as a function that you could call. Something like:

```js
import { createJestConfig } from '@redwoodjs/core' (or @redwoodjs/testing)

export default createJestConfig({
 ...myCustomStuff,
})
```

**Targeting Sides (TBD)**
>About targeting different sides; I thought it could be good to use Jest's [projects](Jest --config extensibility) config instead of running all sides in the command, so we offload more stuff to the Jest side, and new sides with their own jest.configs are automatically picked up!

**Add Jest Watch (TODO)**
>One more thing I'd also like to do in the future is add https://github.com/jest-community/jest-watch-typeahead to the base config. This of course requires yarn rw test to work with watch!

**Comment by peterp** [comment]
This was handled by @RobertBroersma
