### ISSUE TITLE
Docs: Document how to customize FatalError and NotFound pages

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#5642]
Documentation is lacking that explains how the FatalError and NotFound pages work and can be customized.

For example, if you wanted each to share a common Layout you cannot include them as a child of a Set. You’d need to use the layout in your page.

For the error page, then care needs to be done to still include the development page that provides the stack trace.

Tasks

* add docs section
* Describe each page
* Not how to customize with attention to layouts
* Any deploy specific needs such as public error pages and Netlify or other redirects

**Comment by msichterman** [comment]
For the `NotFoundPage`, can we open a separate ticket to support wrapping it with layouts in a `Set`? Curious to hear your thoughts.

**Comment by jtoar** [comment]
Hey @msichterman, that's an interesting idea. You're more than welcome to open an issue in this repo; I can share it with the team and then we can discuss more there.

**Comment by jtoar** [comment]
(We could also discuss it here too. Just wanted you to know that you could open an issue if you wanted.)

**Comment by dthyresson** [comment]
@msichterman We discussed the idea of having the NotFound wrapped in a Set, but determined that this would be difficult for the router to do and involve significant change. cc @Tobbe 

Instead, we'll document that you can include a Layout inside your custom NotFound page.

Thanks for understanding.
