### ISSUE TITLE
Add UUID support for scaffold generation

### ISSUE THREAD

**Issue by tctrautman** [redwoodjs/redwood#5649]
Hello!

As of v1.4.1, `yarn rw g scaffold [data-model]` generates files that assume in some places that a data model has an `id` column, even when it has been instead created with a `uuid` column.  It would be nice if scaffolding was able to generate `uuid` columns, too, since editing manually requires opening many files and is prone to error, though this is not a blocking issue.

As always, thanks for everyone's hard work.

**Comment by callingmedic911** [comment]
Thanks for the feedback @tctrautman! Just to confirm, you mean the scaffold (and other generators) should allow a column with any name as long as it's marked as `@id`, right?

**Comment by tctrautman** [comment]
@callingmedic911 ah, yes that's exactly what I meant.  Great clarification, thank you!

**Comment by samthuang** [comment]
hey @jtoar - sam here 👋  I'd like to take on this issue if no one is actively working on it. If I understand this issue correctly, we want to have the flexibility to name the @id field however we want right? 

This is the error we want to address:
<img width="500" alt="Screenshot 2023-04-27 at 17 37 34" src="https://user-images.githubusercontent.com/35948805/234807336-e3020504-3d91-4ab7-b202-b00d7b910790.png">

**Comment by thedavidprice** [comment]
@samthuang help on this would be very welcome! I'm assigning to you now. As a first step, I recommend a 1) open draft PR that communicates your approach, then 2) loop in @jtoar for initial review + confirmation of approach, then 3) implement fully.

Sound good?

**Comment by samthuang** [comment]
hello hello, @jtoar - sorry it took me a while. I took some time off from the computer last week (japan public holiday 🎉 ). I have a draft PR #8264 up, and please let me know what you think : ) cheers
