### ISSUE TITLE
Union Types With Same Shape Return Incorrect Type

### ISSUE THREAD

**Issue by tal** [redwoodjs/redwood#5661]
For the following type definitions:

```graphql
type One {
  id: String!
  other: String
}

type Two {
  id: String!
  other: String
}

union All = One | Two
```

The type will always come out as `__typename: "One"`

```js
{
  __typename: 'One',
  id: 'twoone',
  other: 'other',
}
```

![2084×658 58.6 KB](https://rwjs-discourse.nyc3.cdn.digitaloceanspaces.com/original/2X/0/0ebccff3a986ee75e499b6d39172e1794c03dd0f.png)

This happens regardless of what __typename is set to or any typescript types.

The issue is reproduced in this repo: https://github.com/tal/graphql-type-issue

**Comment by Tobbe** [comment]
Forum thread for context: https://community.redwoodjs.com/t/rw-1-0-1-5-upgrade-started-overwriting-typename-for-similar-object-shapes/3308

**Comment by simoncrypta** [comment]
@alicelovescake I see that you have talk with the guild about this issue. Seem to be a normal behaviour of GraphQL if I understand correctly? 
https://graphql.org/learn/schema/#union-types

**Comment by alicelovescake** [comment]
@tal I tested your repo with a member of the Guild and we spent a few hours looking into the issue. In `packages/graphql-server/src/makeMergedSchema/makeMergedSchema.ts` file in Redwood framework, we automatically generate resolvers for every field in an object type and for union types.

I know that technically if the returned object contains `__typename` like in your example, we are able to resolve the type by comparing `__typename` of the returned object with the `name` of each type of the union.

However, the returned object is the raw object from the database that has not been converted to  an `GraphQLObjectType` yet. Therefore, there is no `__typename` or `name` associated with that returned object. It just has the fields of that object.

Therefore, we have to take a look at the actual fields to resolve the type, using the code below. I can add a check for `__typename` in the `obj` but it would only work for your example or any services that manually adds `__typename` and not when you just return the result of the database call. 

I've tried to solve this issue, but I think this is a limitation. Feel free to dive into the Redwood code in the file that I pointed out to see if think of something that I haven't. 

```
const resolveUnionType = (types: readonly GraphQLObjectType[]) => ({
  __resolveType(obj: GraphQLObjectType) {

    let maxIntersectionType
    let maxIntersectionFields = 0

    for (const type of types) {
      const fieldIntersection = Object.keys(type.getFields()).filter(
        (field) => field in obj
      )

      if (fieldIntersection.length > maxIntersectionFields) {
        maxIntersectionFields = fieldIntersection.length
        maxIntersectionType = type
      }
    }

    return maxIntersectionType?.name ?? null
  },
})
```

**Comment by tal** [comment]
I can have personal suggestions for how to handle this ambiguous case well (I'd probably error if it's ambiguous and encourage the person to include `__typename`). But if two identically shaped types cannot be resolved from each other then there should at least be an error when the sdl is parsed.

In the app code that caused this problem I manually assigned `__typename` anyways, so that's not an issue for me.

My personal preferred outcome of this is to have `__typename` always be respected, and potentially a performance boost. But if lacking that it should error so the user knows this is an unsupported usage.
