### ISSUE TITLE
[Storybook] Critical error message when running SB build, after creating a project version 1.5.1

### ISSUE THREAD

**Issue by timseriakov** [redwoodjs/redwood#5668]
![image](https://user-images.githubusercontent.com/59409712/171259796-15f2e39e-628a-4072-8e9b-321892e86fcb.png)

MacOS Monterey 2.3.1 (21E258)
NodeJS 16.14.2
Yarn 3.2.1
RedwoodJS 1.5.1
 
## Steps to reproduce

```
yarn create redwood-app rw-clean --typescript && cd rw-clean
yarn rw setup ui tailwindcss
yarn rw generate page home
NODE_ENV=production yarn rw storybook --build --open=false && npx http-server ./web/public/storybook
```

Open in browser `http://127.0.0.1:8080` or `index.html` from build directly

First encountered this when upgrading from version 1.0.2 to 1.5.1

**Comment by timseriakov** [comment]
##Snapshot after executing steps commands:

https://gitpod.io/#snapshot/8c6d9ef0-f063-42e2-b8fd-ed06eaefb11f

**Comment by thedavidprice** [comment]
Thank you for reporting, @timseriakov 

@virtuoushub Any chance you'd have time to take a look at this one?

**Comment by timseriakov** [comment]
Found a solution in my case, my project has been successfully upgraded to RedwoodJS `1.5.2-canary.99`

**Comment by timseriakov** [comment]
Thanks, that's right, after upgrading to version 1.5.2-canary.99, the error is gone

**Comment by jtoar** [comment]
Hey @timseriakov I was able to reproduce using the steps you enumerated (thanks!) and while upgrading to the canary does fix that error, do you not get this one about mock service worker after?

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/32992335/173095725-dcb9ced0-1878-4a41-aa78-7fcc7f1d9d88.png">

**Comment by timseriakov** [comment]
> 

Thank you for your time. Absolutely right, at the moment I am getting this error in SB build after upgrading to canary.99. Everything else works well
