### ISSUE TITLE
Yarn warning on new app creation: upgrade the uuid lib to version 7 or higher

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#5682]
Full message:

```
warning create-redwood-app > @redwoodjs/telemetry > @redwoodjs/structure > @prisma/sdk > temp-write > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

**Comment by Anishpras** [comment]
@cannikin Can I work on this issue?

**Comment by cannikin** [comment]
Sure thing!

**Comment by jtoar** [comment]
@Anishpras still interested in this one? No worries if not!

**Comment by Josh-Walker-GM** [comment]
Hope you don't mind I had a quick look at this?

I checked prisma's repo and they have an issue for this at https://github.com/prisma/prisma/issues/11960 however https://github.com/prisma/prisma/issues/7618 is blocking them from upgrading some of their dependencies, including this `uuid` one.

The last comment in https://github.com/prisma/prisma/issues/11960 seems to suggest they find nothing particularly important about having `uuid@3.4.0` specifically.

Could this be added to `resolutions`? If so what testing is needed to ensure there aren't any side effects?

**Comment by Josh-Walker-GM** [comment]
@cannikin I didn't see this warning when I ran CRWA just now, are you still seeing them? I have went ahead and added a PR with resolutions to prevent using the old version because there are still warnings present in the yarn output when working within the framework code itself.

**Comment by cannikin** [comment]
Just ran CRWA and saw no warning! Closing!
