### ISSUE TITLE
Typo in tutorial routing params

### ISSUE THREAD

**Issue by mdkess** [redwoodjs/redwood#5693]
https://redwoodjs.com/docs/tutorial/chapter2/routing-params

In the part for `web/src/components/ArticleCell/ArticleCell.tsx`, it has the snippet

```
export const Success = ({ articles }: CellSuccessProps<ArticleQuery>) => (
  <Article article={article} />
)
```

This should be `article` instead of `articles`, and also handle the null case (at least as far as typescript is concerned)

```
export const Success = ({ article }: CellSuccessProps<ArticleQuery>) =>
  article ? <Article article={article} /> : <h1>Not found</h1>
```

**Comment by Leon-Sam** [comment]
I just ran into the same issue today, I made a quick PR for it. [HERE](https://github.com/redwoodjs/redwood/pull/5695) is a link to the PR.

**Comment by callingmedic911** [comment]
Thanks to both of you for spotting and quickly fixing the issue. Much appreciated!
