### ISSUE TITLE
When Building with Netlify Env does not get passed down to the API when served

### ISSUE THREAD

**Issue by MichaelrMentele** [redwoodjs/redwood#5696]
DISCLAIMER: it seems this is a quirk of the netlify implementation details for serving up functions rather than a redwood issue but raising it here for posterity, searchability, and for capturing any discussion about possible ways forward.

When running the build and deploy step for netlify we are using a plugin that overrides the `DATABASE_URL` environment based on the context. 

We have verified in the logs that the deploy command `yarn deploy netlify` i.e. `yarn rw build --verbose && yarn rw prisma migrate deploy && yarn rw data-migrate up` all of these seem to get the correct environment values.

But when redwood is _served_ it does not use the overridden value. It seems that the issue is that netlify looks at the generated build functions and then serves them irrespective of the environment values that were previously overridden. It's almost as if the contextual replace is discarded when it comes time to actually serve the functions up.

**Comment by MichaelrMentele** [comment]
Our current way plan to get around this is to modify the `netlify.toml` file at build time as suggested by @KrisCoulson in slack

**Comment by AlejandroFrias** [comment]
We have found a solution!

We use the plugin [netlify-plugin-contextual-env](https://github.com/cball/netlify-plugin-contextual-env) in combination with a custom script based off of [netlify-plugin-inline-functions-env](https://github.com/bencao/netlify-plugin-inline-functions-env).

1. Modify `api/src/lib/db.[js|ts]` to programmatically override the db url: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#examples

```js
export const db = new PrismaClient({
  log: emitLogLevels(['info', 'warn', 'error']),
  datasources: {
    db: {
      url: process.env.DATABASE_URL,
    },
  },
})
```

I've added this script to our `package.json`

```json
    "template-db": "node scripts/inlineDbUrl.js"
```

In `netlify.toml` I've added this custom command and the contextual env plugin"

```toml
[build]
command = "yarn template-db && yarn rw deploy netlify"

[[plugins]]
package = 'netlify-plugin-contextual-env'
  [plugins.inputs]
  mode = 'prefix'
```

And the `inlineDbUrl.js` script is here:
```
const fs = require('fs')
const util = require('util')
const babel = require('@babel/core')
const inlinePlugin = require('babel-plugin-transform-inline-environment-variables')
const writeFile = util.promisify(fs.writeFile)

async function inlineEnv(path) {
  const transformed = await babel.transformFileAsync(path, {
    configFile: false,
    plugins: [babel.createConfigItem([inlinePlugin])],
    retainLines: true,
  })

  await writeFile(path, transformed.code, 'utf8')
}

inlineEnv('api/src/lib/db.ts')
```

**Comment by dac09** [comment]
Thank you for raising this issue and the suggested solutions!

Let's keep them coming but I'll close out the issue as it is specific to Netlify
