### ISSUE TITLE
yarn rw prisma migrate dev fails on nixOS

### ISSUE THREAD

**Issue by aleeusgr** [redwoodjs/redwood#5700]
Following the tutorial
`yarn rw prisma migrate dev`
returns
```
Warning Precompiled engine files are not available for nixos.
> Downloading Prisma engines for Node-API for linux-nixos [                    ] 0%Error: Not Found https://binaries.prisma.sh/all_commits/2b0c12756921c891fec4f68d9444e18c7d5d4a6a/linux-nixos/libquery_engine.so.node.gz
```

I found this doc: Provide precompiled binaries for NixOS 
https://github.com/prisma/prisma/issues/3026

I will update the issue if I find a way to make it work
Thanks

**Comment by aleeusgr** [comment]
following the doc, created the `flake.nix` and `.envrc` files
also need to `mkdir .direnv`
then:
`$direnv eval`
returns
```
Prisma schema loaded from api/db/schema.prisma
Error: Unable to require(`/nix/store/cmqn5bg9z8gfh8ijnvnkni2xn8b2v6la-prisma-engines-3.14.0/lib/libquery_engine.node`)
 /nix/store/g02b1lpbddhymmcjb923kf0l7s9nww58-glibc-2.33-123/lib/libc.so.6: version `GLIBC_2.34' not found (required by /nix/store/cmqn5bg9z8gfh8ijnvnkni2xn8b2v6la-prisma-engines-3.14.0/lib/libquery_engine.node)
 ```
 step:
 add glibc to configuration.nix and `#nixos-rebuild switch`

**Comment by jtoar** [comment]
Hey @aleeusgr I tried to use NixOS once and ran into this. Safe to say I didn't get it working, but it looks like support for it improved in the time since (referring to that Prisma thread you linked).

I couldn't quite tell from your second comment—did you get it working?

**Comment by aleeusgr** [comment]
@jtoar not yet.
`cd redwoodblog`
`direnv allow`
`eval "$(direnv hook bash)"`
```
copying '/home/alex/workshop/redwoodblog'direnv: ([/nix/store/jmq8rb7iii2h69pfmmxfac8g7gjr0g9v-direnv-2.29.0/bin/direnv export bash]) is taking a while to execute. Use CTRL-C to give up.
direnv: export +AR +AS +CC +CONFIG_SHELL +CXX +HOST_PATH +IN_NIX_SHELL +LD +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_BUILD_CORES +NIX_BUILD_TOP +NIX_CC +NIX_CC_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_CFLAGS_COMPILE +NIX_ENFORCE_NO_NATIVE +NIX_HARDENING_ENABLE +NIX_INDENT_MAKE +NIX_LDFLAGS +NIX_STORE +NM +OBJCOPY +OBJDUMP +PRISMA_FMT_BINARY +PRISMA_INTROSPECTION_ENGINE_BINARY +PRISMA_MIGRATION_ENGINE_BINARY +PRISMA_QUERY_ENGINE_BINARY +PRISMA_QUERY_ENGINE_LIBRARY +RANLIB +READELF +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +TEMP +TEMPDIR +TMP +TMPDIR +buildInputs +buildPhase +builder +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +doCheck +doInstallCheck +dontAddDisableDepTrack +name +nativeBuildInputs +out +outputs +patches +phases +propagatedBuildInputs +propagatedNativeBuildInputs +shell +shellHook +stdenv +strictDeps +system ~PATH ~XDG_DATA_DIRS
```
`yarn rw prisma migrate dev`
```
Running Prisma CLI...
$ yarn prisma migrate dev --schema /home/alex/workshop/redwoodblog/api/db/schema.prisma

Warning Precompiled engine files are not available for nixos.
Environment variables loaded from .env
Prisma schema loaded from api/db/schema.prisma
Error: Unable to require(`/nix/store/cmqn5bg9z8gfh8ijnvnkni2xn8b2v6la-prisma-engines-3.14.0/lib/libquery_engine.node`)
 /nix/store/g02b1lpbddhymmcjb923kf0l7s9nww58-glibc-2.33-123/lib/libc.so.6: version `GLIBC_2.34' not found (required by /nix/store/cmqn5bg9z8gfh8ijnvnkni2xn8b2v6la-prisma-engines-3.14.0/lib/libquery_engine.node)
```

I added glibc to my nixOS configuration, but it didn't help. I'm figuring out why

**Comment by aleeusgr** [comment]
also found this: 
https://github.com/pimeys/nixos-prisma

**Comment by aleeusgr** [comment]
updated nix-channel 
```nix-channel --list
nixos https://nixos.org/channels/nixos-22.05```

enabled `direnv` 

```
$cat flake.nix 
{
  description = "A prisma test project";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/master";
  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system: let
      pkgs = nixpkgs.legacyPackages.${system};
    in {
      devShell = pkgs.mkShell {
        nativeBuildInputs = [ pkgs.bashInteractive ];
        buildInputs = with pkgs; [
          nodePackages.prisma
        ];
        shellHook = with pkgs; ''
          export PRISMA_MIGRATION_ENGINE_BINARY="${prisma-engines}/bin/migration-engine"
          export PRISMA_QUERY_ENGINE_BINARY="${prisma-engines}/bin/query-engine"
          export PRISMA_QUERY_ENGINE_LIBRARY="${prisma-engines}/lib/libquery_engine.node"
          export PRISMA_INTROSPECTION_ENGINE_BINARY="${prisma-engines}/bin/introspection-engine"
          export PRISMA_FMT_BINARY="${prisma-engines}/bin/prisma-fmt"
        '';
      };
    });
}
```
```
$ cat .envrc 
use flake
```
`mkdir .direnv`
`direnv allow`
 `eval "$(direnv hook bash)"` builds prisma and  `yarn rw prisma studio` can run successfully.

**Comment by jtoar** [comment]
Nice @aleeusgr! Judging by the way you ended your last comment, it sounds like you got it working? It'd be great to get more visibility on this somehow, cause configuring NixOS isn't easy. I feel like it may be too soon to have a "RedwoodJS on NixOS" how to, but something along those lines would be great, whether it's a blog post or a [forum topic](https://community.redwoodjs.com/).

**Comment by bbbenji** [comment]
@aleeusgr thanks, that helped me out! I had to make a small change though.

this:

```
export PRISMA_MIGRATION_ENGINE_BINARY="${prisma-engines}/bin/migration-engine"
```
changed into:
```
export PRISMA_SCHEMA_ENGINE_BINARY="${prisma-engines}/bin/schema-engine"
```
