### ISSUE TITLE
Telemetry opens an onslaught of command prompts when ran on Windows

### ISSUE THREAD

**Issue by realStandal** [redwoodjs/redwood#5728]
> [Original report from `Werewolf#5740` via Discord](https://discord.com/channels/679514959968993311/984358955583160401).

### What's happening?

Whenever a command is ran which hooks into [RedwoodJS' telemetry](https://telemetry.redwoodjs.com/), it causes an assortment of command prompts to open - breaking the user's focus and being a general nuisance. It appears this issue is only occurring on Windows machines - though this may be wrong.

![ezgif com-gif-maker_4](https://user-images.githubusercontent.com/25166787/172923810-41071b8f-378f-4c4e-92c4-bee16c71c46a.gif)

### Current Resolution

Turning off Redwood's telemetry acts as a solution, preventing the additional prompts from opening.

The `REDWOOD_DISABLE_TELEMETRY=1` environment variable can be added per-project (via `.env`) or [at the system-level](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0).

**Comment by jtoar** [comment]
I'm hoping that if we set the `windowsHide` property to true here, this may go away:

https://github.com/redwoodjs/redwood/blob/39e86c68d23552a8bf811c5bad7ab1ce0e8d89c4/packages/telemetry/src/telemetry.ts#L8-L17

@realStandal would you be able to test https://github.com/redwoodjs/redwood/pull/5734 locally? Or if it's easier, just make the change to `node_modules/@redwoodjs/telemetry/dist/telemetry.js`?

**Comment by realStandal** [comment]
@jtoar I don't actually use Windows anymore, just creating the issue for the community member who ran into the bug - sorry!

(not sure of their GitHub, but I linked their Discord username in the issue)

**Comment by rushabhhere** [comment]
> Or if it's easier, just make the change to `node_modules/@redwoodjs/telemetry/dist/telemetry.js`?

I am on Windows and I tried adding this to the telemetry.js file but to no avail, the issue persists.

**Comment by jtoar** [comment]
No worries @realStandal, the write up was great as is, and thanks @rushabhhere! I'll keep thinking about what could be the issue.

**Comment by AlonHor** [comment]
The title says "Windows (PowerShell)" but I have the same issue when using Git Bash on Windows.

**Comment by jtoar** [comment]
This should be fixed but only because we disabled telemetry on Windows completely.
