### ISSUE TITLE
I'm too lazy to write `yarn redwood dev`

### ISSUE THREAD

**Issue by NotoriousGOR** [redwoodjs/redwood#5729]
Can we add a simple script to the package.json file where we can do something like `yarn dev` instead of `yarn redwood dev`?

proposed code:

`"scripts": {
    "dev": "redwood dev"
  },`

**Comment by simoncrypta** [comment]
Ahaha I feel you, I was probably too ashamed to say it :zany_face: 

You know that you can also write `rw` as short for `redwood`.

What do you think if the default command for `yarn rw` will be `yarn redwood dev ` like `yarn`  is default for `yarn install`?
It will probably be more maintainable. I also like your idea !

**Comment by NotoriousGOR** [comment]
I think that can work! As long as it’s not the full `yarn redwood dev` Lol

**Comment by KrisCoulson** [comment]
@NotoriousGOR another thing you can do in your .bashprofile or .zshrc is add an alias

`alias rw="yarn rw"`

boom now you can just do `rw dev` or an other command

**Comment by dthyresson** [comment]
@NotoriousGOR does the "rw" shortcut and/or alias solution work for you. If so, then we can close out this issue. Thanks!
