### ISSUE TITLE
Weird Issue with Windows 11 cmd

### ISSUE THREAD

**Issue by ThirenG187** [redwoodjs/redwood#5757]
Hi, When opening vscode and when running 'yarn rw dev' my cmd keeps poping up and closing not sure what tasks is being run, but can this not be a background process as the windows keep getting focus when I am writing code and it's getting annoying.

**Comment by jtoar** [comment]
Hey @ThirenG187, sorry for the late response—we're aware of this: https://github.com/redwoodjs/redwood/issues/5728. It's related to redwood telemetry and can be disabled by turning it off (see the issue I linked to). We're going to work on a legit fix, but in the meantime we're going to patch it in the next release.
