### ISSUE TITLE
Add note in tutorial about potential error messages when generating a Cell without a corresponding SDL

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#5762]
In the later sections of the tutorial we build out the comment engine totally in Storybook before doing anything with the backend. Currently we show some nasty warning/error messages about types not being able to be generated. There will also be red squiggles in VS Code around the QUERY at the top since there's no SDL that provides those types/fields.

Let's add a callout block before this section in the tutorial warning people that they will see some of these warning messages and that they can still build out their frontend in Storybook, but it won't work for real until they create the SDL.

**Comment by cannikin** [comment]
@dac09 How's this sound?

<img width="735" alt="image" src="https://user-images.githubusercontent.com/300/173691554-b689b792-fad0-4b62-a25f-5d21275dffc6.png">

**Comment by dac09** [comment]
LGTM!
