### ISSUE TITLE
Redwood project doesn't have sufficient permissions to save files on Mac.

### ISSUE THREAD

**Issue by mileshenry31** [redwoodjs/redwood#5779]
Every time I create a new Redwood project and try to edit/save a file I don't have sufficient permissions. After I run `sudo chmod 7777 -R [project-directory]` it gives me the correct permissions for all the current files but when I add more I have to rerun the command every time.

**Comment by simoncrypta** [comment]
Hey @mikenikles,
It is the first time a heard about a problem with OS permissions for Redwood.
Is it happened everywhere, and what is the path of your redwood project ?

**Comment by mikenikles** [comment]
Hi 👋,

I don't actually develop on a local computer. All my projects run on Gitpod.

**Comment by jtoar** [comment]
> It is the first time a heard about a problem with OS permissions for Redwood.

Echoing what @simoncrypta said here; @mileshenry31 I'm going to close this one, but if you have time, let us know if things were resolved for you or not. If not, happy to reopen this one and discuss further.
