### ISSUE TITLE
Allow us to override input type

### ISSUE THREAD

**Issue by gfpacheco** [redwoodjs/redwood#578]
Previously I had a component that used `TextField` internally, I was happy to be able to just tell him its type by sending a prop:

```
// ...somewhere in my component
<TextField type={type} />
```

But with the release of `0.7.0` you're overriding my prop and always setting `type="text"` anytime I use `TextInput`.

I get that you wanted to create different components for different types, and even if I think that's unnecessary I respect that. But let me override the type if I want, otherwise I'll have to keep switching between different components depending on the type of the input.

Does it work if I just move [this line](https://github.com/redwoodjs/redwood/blob/master/packages/web/src/form/form.js#L248) just after `type={type}`?

Would you approve if I opened that PR?

**Comment by peterp** [comment]
Thanks for brining this to our attention @gfpacheco. We would 100% accept a PR that introduces that!

You could move `{...tagProps}` all the way to the bottom so that everything is overrideable.

**Comment by cannikin** [comment]
I was going to suggest creating a new generic `<InputField>` where it is expected that you set the type. Seems kind of weird to explicitly say `<TextField>` and then set `type="number"`.

**Comment by gfpacheco** [comment]
I like that!

But that doesn't change my mind about users being able to override any default prop, does it make sense?

**Comment by thedavidprice** [comment]
> I was going to suggest creating a new generic <InputField> where it is expected that you set the type. Seems kind of weird to explicitly say <TextField> and then set type="number".

^^ If we don't have it already, this is a much better long-term solution. But given all the new field types with v0.7.0 ([here in docs](https://redwoodjs.com/reference/redwood-form)), I guess the new `<NumberField>` would be best in this case, for example, correct? (@gfpacheco You're probably already ahead of me here, but wanted to make sure you also saw the additions to Forms in v0.7)

**Comment by gfpacheco** [comment]
Yes, I did see them! And it's great that we have these single-purpose components, but in my particular case my CustomComponent gets the `type` prop and I just wanted it to pass that to its own `TextField` as a prop as well. A generic `InputField` would work just as fine, though.

And again, I still think letting the user override any default props is always a good thing.

**Comment by thedavidprice** [comment]
@gfpacheco Ah, completely understood. Thanks for the reply and, again, for the input + help here!
