### ISSUE TITLE
Auth0 & Vercel deployment

### ISSUE THREAD

**Issue by nikospapcom** [redwoodjs/redwood#5784]
Hello there

I'm using auth0 to authenticate my users but I have a problem when I'm pushing to vercel

I don't know what I need to put in  `Allowed Callback URLs` and `Allowed Logout URLs` for dynamic branches preview in vercel

I tried something like this `https://*.vercel.app` but it didn't work

Has anyone else the same problem?

Thanks

**Comment by simoncrypta** [comment]
Hey @nikospapcom ! 
I think this is more a problem between Auth0 and Vercel or a “how do I do this?”  that something we can really change in the framework. 
The forum https://community.redwoodjs.com/ is the best place to discuss a how-to question like this.

I will close this issue, but feel free to post it on the forum or reopen it if you think we can do something about it.
Thanks !  😄
