### ISSUE TITLE
dbAuth: Provide a possibility to disable certain flows completely

### ISSUE THREAD

**Issue by Morishiri** [redwoodjs/redwood#5792]
**Feature request**
As a developer I would like to have an option to disable dbAuth handlers completely, e.g. `signup`, `forgotPassword`, `resetPassword`, Doesn't make sense to disable `login` I think.

**Motivation**
I want to create an app with just few users I will create via seed and I don't want anyone to change/reset passwords or create new accounts. Currently the only way is to throw error in `handler` which still doesn't stop e.g. `forgotPassword` from generating reset tokens. I would love to be able to disable the flow completely so it is not even making actions up-front.

**Possible solution**
Add `disable: Boolean?` to handler options. Enabled by default to keep it backward-compatible.

**Additional remarks**
I'm happy to contribute to it if you agree.

**Comment by dac09** [comment]
@cannikin this seems right up your alley, just putting it on your radar.

**Comment by cannikin** [comment]
I've added an `enable` flag for the upcoming WebAuthn integration #5680 and that seems like a nice pattern for the other functions as well. I like having flags named for the "positive" version ("enabled" rather than "disabled").

You're more than welcome to add that functionality in a PR @Morishiri, thanks!

**Comment by Morishiri** [comment]
@cannikin wouldn't that mean a breaking change for existing redwood projects? Or do we default to `enabled = true` then?

**Comment by cannikin** [comment]
Yep, default to `enabled: true`! So if the property is `undefined` or `true`, it's enabled, otherwise it's disabled.

**Comment by sidshetty** [comment]
I think of this today for the first time and happy to see you guys already on it @cannikin @Morishiri . Appreciate it ♥
