### ISSUE TITLE
dbAuth: Make it possible to seed users with hashedPasswords and seed

### ISSUE THREAD

**Issue by Morishiri** [redwoodjs/redwood#5793]
**Feature request**
As a developer I would like to be able to generate users with `hashedPassword` and salt the same way signup handler does that

**Motivation**
I want to create an app with just few users I will create via seed and I don't want anyone to change/reset passwords or create new accounts. Currently I need to provide correctly hashed password and salt to prisma create call.

**Possible solution**
Export hash and salt generation mechanism from `@redwoodjs/api`
```typescript
_hashPassword(text, salt) {
  const useSalt = salt || _cryptoJs.default.lib.WordArray.random(128 / 8).toString();

  return [_cryptoJs.default.PBKDF2(text, useSalt, {
    keySize: 256 / 32
  }).toString(), useSalt];
} // figure out which auth method we're trying to call
```

and make it possible to use it outside of it.

So then in seed you can simply do:
```typescript
const [password, salt] = hashPassword('password');
await db.user.create({ data: { username: 'user', password, salt }});
```

Or even better, make the exported version return an object with named properties instead.

**Additional remarks**
I'm happy to contribute to it if you agree.

**Comment by jtoar** [comment]
Hey @Morishiri, thanks for the detailed write up! Pinging @cannikin (the author of dbAuth)—he'll take a look at this and get back to you.

**Comment by cannikin** [comment]
We're talking about doing a total auth overhaul in the near future, where each auth provider will be its own separate package you can install. That would include dbAuth, and exporting ancillary functions like this from that package would be perfect. Right now there's not really a clean way to do that: we discussed earlier and wouldn't want to export this specific hashing algorithm from the general `@redwoodjs/auth` package.

In the meantime I would just copy that `_hashPassword` function and use it directly in your seeds for now!

**Comment by Morishiri** [comment]
Thanks @cannikin, that's exactly what I did - copied the hasPassword implementation. But while doing so I thought that others may benefit from this approach as well do I opened this issue.

Great that there is an improvement coming to this topic. Lets close it then and wait for the separate packages approach in the future :)
