### ISSUE TITLE
tailwindcss ui: Add tailwindcss prettier rules

### ISSUE THREAD

**Issue by Morishiri** [redwoodjs/redwood#5795]
Tailwind introduced https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

What do you think about adding that when setting up tailwindcss as ui?

**Comment by simoncrypta** [comment]
Amazing ! We use Yargs for the CLI, you can find the file for the tailwind setup here https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/setup/ui/libraries/tailwindcss.js

Don't hesitate to ask for help if you need it :)

**Comment by vincentri** [comment]
broken for new repo cannot install tailwind

**Comment by Morishiri** [comment]
> broken for new repo cannot install tailwind

https://github.com/redwoodjs/redwood/pull/5812#issuecomment-1203837571
