### ISSUE TITLE
Looks like array index needs optional chaining operator

### ISSUE THREAD

**Issue by joconor** [redwoodjs/redwood#5802]
https://github.com/redwoodjs/redwood/blob/053b22dc90e0b81f42f68d8ec06046169184e070/packages/forms/src/index.tsx#L556

I'm receiving an error during form handling: `undefined is not an object (evaluating 'errorProps.graphQLErrors[0]')`. I'm sure I'm doing something wrong, but in trying to track down the root problem, I notice the above reference line seems to expect a null reference anywhere along its chain of references. If that's the case, then it's missing the optional chaining operator before the array index reference.

**Comment by joconor** [comment]
Additional info:
I think I tracked down my root cause. After successful form submission, the `onCompleted` function is attempting to navigate to a route I renamed but failed to change the reference to the route in `onCompleted`. As a result, I end up with a  TypeError (`TypeError: _redwoodjs_router__WEBPACK_IMPORTED_MODULE_15__.routes.dummyPolicies is not a function.`) (pardon my braindead naming) caught by the Form.

**Comment by dthyresson** [comment]
Possible fix, but I need to write some tests:

```
        <ServerErrorsContext.Provider
          value={
            errorProps?.graphQLErrors?.[0].extensions?.properties?.messages || {}
          }
```

>  but Form error handling is only prepared to deal with GraphQL errors

@joconor Question - what info would be sent to the form `errors` in your example (so I could write a test case).

**Comment by dthyresson** [comment]
@joconor Question - what info would be sent to the form errors in your example (so I could write a test case).

**Comment by joconor** [comment]
Hey David,

It was just a generic Javascript TypeError thrown during the `onCompleted` function after successful GraphQL mutation via RedwoodJS form submission. It’s not a GraphQL error, so the RWJS error handling doesn’t really know what to do with it. I.e., there is nothing in errorProps.graphQLErrors if a generic javascript error is thrown

— Jay

**Comment by cattre** [comment]
Just to add my experience here, I was getting a similar error ("errorProps.graphQLErrors is undefined") following some renaming.

After reading this ticket I found some routes that hadn't been renamed, but I'm still getting the error after doing so (albeit now with the graphQL request and succesful response objects also displayed on the error page).

**Comment by dthyresson** [comment]
Thanks! I was able to reproduce it in our test project:

![image](https://user-images.githubusercontent.com/1051633/179762232-7585e721-ff79-4f78-a53b-cd8d2643bbaa.png)


```ts

export const Success = ({ post }: CellSuccessProps<EditPostById>) => {
  const [updatePost, { loading, error }] = useMutation(UPDATE_POST_MUTATION, {
    onCompleted: () => {
      toast.success('Post updated2')
      null.f() // <--- boom
      navigate(routes.posts())
    },
    onError: (error) => {
      toast.error(error.message)
    },
  })
...
```

**Comment by cattre** [comment]
@dthyresson sure, I'd expect that error to show in the normal dev error page.

Incidentally, I've found some more references that needed renaming (might need to configure more type checking). I'm now getting the below error (which may be unrelated so feel free to ignore, I'll keep debugging):

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/39544048/180079491-4ac6d95b-07c1-4088-9416-29e47372426e.png">

**Comment by dthyresson** [comment]
strict type checking, you say, @cattre? it's coming https://github.com/redwoodjs/redwood/pull/5491
