### ISSUE TITLE
extremely slow when using any redwood commands

### ISSUE THREAD

**Issue by jeremyjfleming** [redwoodjs/redwood#5813]
Using any redwood command will take 2+ minutes to execute. This is not an issue with kill-port, issue #861, as the version I am using is currently using kill-port 1.6.1
![image](https://user-images.githubusercontent.com/58794462/175356201-3137e952-ccbf-4ffa-8862-1c1ade119bb1.png)
Additionally, hot reload does not work. here is my rw info
![image](https://user-images.githubusercontent.com/58794462/175357110-bac9f38e-b7cc-4339-b775-d942065eaf1d.png)
This happened after a fresh install and modifying nothing. 
I am using wsl if that helps.

**Comment by jeremyjfleming** [comment]
this was a problem with wsl. if anyone has this issue you need to switch to wsl 1 or move the project to the linux file system.

**Comment by orta** [comment]
Note: I'd say startup for the redwood CLI is very slow even on linux/mac too FWIW, and I've tried figuring out if it was a cheap fix it a few times ( if I recall it was a lot of file reads on launch) but I didn't see any standout easy wins
