### ISSUE TITLE
Test database doesn't apply migrations needed to create postgis extension

### ISSUE THREAD

**Issue by freddydumont** [redwoodjs/redwood#5818]
I have a postgis-enabled development database which works as expected. To get this to work, I had to use `prisma migrate dev --create-only`, and add the following block to the generated migration: `create extension postgis;`. Here's the full migration:

```sql
-- create postgis extension
CREATE EXTENSION postgis;
-- AlterTable
ALTER TABLE "Location"
ADD COLUMN "coords" geometry(Point, 4326);
-- CreateIndex
CREATE INDEX "location_idx" ON "Location" USING GIST ("coords");
```

And a simplified prisma schema:

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  binaryTargets   = "native"
  previewFeatures = ["extendedIndexes", "improvedQueryRaw"]
}

model Location {
  id        Int      @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  coords    Unsupported("geometry(Point, 4326)")?

  @@index([coords], name: "location_idx", type: Gist)
}

```

Again, this works as expected. I can use `rw prisma migrate reset` and seed the database with postgis coords by using raw queries.

Here's what happens when running the rw test command:
```sh
❯ rw test

Running Prisma CLI...
$ yarn prisma db push --force-reset --accept-data-loss --schema [...]

Environment variables loaded from .env
Prisma schema loaded from api/db/schema.prisma
Datasource "db": PostgreSQL database "db_test", schema "public" at "localhost:5432"

The PostgreSQL database "db_test" from "localhost:5432" was successfully reset.
Error: db error: ERROR: type "geometry" does not exist
   0: sql_migration_connector::apply_migration::apply_migration
             at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:9
   1: migration_core::state::SchemaPush
             at migration-engine/core/src/state.rs:349
``` 

Notice that the command uses `prisma db push --force-reset`, which doesn't appear to apply the migrations needed to enable postgis. So the question is, shouldn't the test command also be using `prisma migrate reset`? Or is there another way to enable postgis on the test database?

Here's what `db push --force-reset` does according to [the prisma docs](https://www.prisma.io/docs/reference/api-reference/command-reference#db-push):

```
Resets the database and then updates the schema - useful if you need to start from scratch due to unexecutable migrations.
```

**Comment by dac09** [comment]
Great issue and write up, thank you very much @freddydumont - indeed this isn’t something we considered!


@cannikin would you be interested in picking this up?

**Comment by cannikin** [comment]
Yeah I can take a look!

**Comment by dthyresson** [comment]
FYI Prisma has an existing issue to improve Postgres extension management. See: https://github.com/prisma/prisma/issues/12308

**Comment by jtoar** [comment]
@cannikin gentle ping, if you're still interested in picking this one up

**Comment by cannikin** [comment]
Yep, I'm on it!

**Comment by cannikin** [comment]
So using `prisma migrate reset` will actually re-run all migrations, in order, each time you run your test suite. Depending on the number of migrations you have, this could take a long time.

How about adding an ENV var that lets you override the default of `prisma db push` to use `prisma migrate reset` instead? So that in your case you can set that ENV var and that's the strategy it will always use, otherwise it will use the default of `prisma db push`?

I opened a PR here with the change, we can discuss over there: https://github.com/redwoodjs/redwood/pull/5883

**Comment by freddydumont** [comment]
@cannikin sounds good! 

FYI, prisma is [starting design work on PostGIS support](https://github.com/prisma/prisma/issues/2789#issuecomment-1176137254), so it's going to be fixed on their side at some point.
