### ISSUE TITLE
Issues with yarn create redwood-app

### ISSUE THREAD

**Issue by maransowthri** [redwoodjs/redwood#5819]
I have a directory called `redwoodjs` I `cd`ed into it and ran `yarn create redwood-app --ts .` Here's what I got

```
kmaran@ATH57322 MINGW64 ~/Documents/VS Code Projects/redwoodjs (master)
$ yarn create redwood-app --ts .
yarn create v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
....
@endemolshinegroup/cosmiconfig-typescript-loader > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
[4/4] Building fresh packages...

success Installed "create-redwood-app@2.0.0" with binaries:
      - create-redwood-app
  > Creating Redwood app
    / Checking node and yarn compatibility
      Using directory 'C:\Users\kmaran\Documents\VS Code Projects\redwoodjs'
    Installing packages
    Generating types

'C:\Users\kmaran\Documents\VS Code Projects\redwoodjs' already exists and is not empty
```

**Comment by callingmedic911** [comment]
If the said directory is empty `~/Documents/VS Code Projects/redwoodjs`, can you try removing it generate from a level up:
1. Delete `redwoodjs` directory.
2. CD into `~/Documents/VS Code Projects`
3. Run `yarn create redwood-app --ts redwoodjs`

Or if you want to create the app inside `redwoodjs` directory (alongside other files and folders), just give it a new app name and it'll create that directory:
1. CD into `~/Documents/VS Code Projects/redwoodjs`
2. Run `yarn create redwood-app --ts my-redwood-app`

**Comment by maransowthri** [comment]
@callingmedic911 thanks for the quick reply! I was looking for something similar to `npx create-react-app .`

**Comment by callingmedic911** [comment]
In terms of functionality `yarn create` is similar to `npx` and right now RedwoodJS is coupled with yarn but I'm sure there's interest to become package-manager agnostic in future.

Also, were you able to generate the new project?

**Comment by maransowthri** [comment]
Yes I was able to create it. But, my only question was that, is there a way to download all rw template files under my current directory without having a new folder?

Like I said before I thought `yarn create redwood-app --ts .` should help me out, but it didn't.

**Comment by maransowthri** [comment]
Ah, it works, thanks!
