### ISSUE TITLE
multiple relations and SDL genrations

### ISSUE THREAD

**Issue by MeetChaudhari** [redwoodjs/redwood#5838]
i tired the redwood way, by commenting the relations and then genrating SDL and etc.
still i cant get it working 

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model test {
  id         String    @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  created_at DateTime? @default(now()) @db.Timestamptz(6)
}

model users {
  id            String          @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  first_name    String?
  last_name     String?
  email         String?         @unique
  phone         String?         @unique
  created_at    DateTime?       @default(now()) @db.Timestamptz(6)
  artistMeta    artistMeta[]
  userAddresses userAddresses[]
  userIntrests  userIntrests?
  userMeta      userMeta?
}

model tags {
  tag_id       String         @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  tag          String?
  created_at   DateTime?      @default(now()) @db.Timestamptz(6)
  skillSet     skillSet[]
  userIntrests userIntrests[]
}

model DrawingArtistRef {
  artist_id   String       @id(map: "drawing_artist_ref_pkey") @db.Uuid
  banner_img  String?      @db.Uuid
  banner_name String?      @unique(map: "drawing_artist_ref_banner_name_key")
  description String?
  created_at  DateTime?    @default(now()) @db.Timestamptz(6)
  artistMeta  artistMeta   @relation(fields: [artist_id], references: [artist_id], onDelete: NoAction, onUpdate: NoAction)
  userAssests userAssests? @relation(fields: [banner_img], references: [id], onDelete: NoAction, onUpdate: NoAction)
}

model artistMeta {
  artist_id        String            @id(map: "artist_meta_pkey") @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  user_id          String            @db.Uuid
  created_at       DateTime?         @default(now()) @db.Timestamptz(6)
  artist_type      artist_type?
  social_links     String?           @db.Uuid
  socialSet        socialSet?        @relation(fields: [social_links], references: [id], onDelete: NoAction, onUpdate: NoAction)
  users            users             @relation(fields: [user_id], references: [id], onDelete: NoAction, onUpdate: NoAction)
  DrawingArtistRef DrawingArtistRef?
  skillSet         skillSet?
}

model skillSet {
  artist_id  String     @id(map: "skill_set_pkey") @db.Uuid
  skill      String?    @db.Uuid
  created_at DateTime?  @default(now()) @db.Timestamptz(6)
  artistMeta artistMeta @relation(fields: [artist_id], references: [artist_id], onDelete: NoAction, onUpdate: NoAction)
  tags       tags?      @relation(fields: [skill], references: [tag_id], onDelete: NoAction, onUpdate: NoAction)
}

model socialSet {
  id         String       @id(map: "social_set_pkey") @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  Instagram  String?      @unique(map: "social_set_Instagram_key")
  Facebook   String?      @unique(map: "social_set_Facebook_key")
  Dribble    String?      @unique(map: "social_set_Dribble_key")
  Pintrest   String?      @unique(map: "social_set_Pintrest_key")
  created_at DateTime?    @default(now()) @db.Timestamptz(6)
  artistMeta artistMeta[]
}

model userAddresses {
  id         String     @id(map: "user_addresses_pkey") @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  user_id    String?    @db.Uuid
  address1   String?
  address2   String?
  pincode    String?
  state      String?
  phone      String?
  created_at DateTime?  @default(now()) @db.Timestamptz(6)
  users      users?     @relation(fields: [user_id], references: [id], onDelete: NoAction, onUpdate: NoAction)
  userMeta   userMeta[]
}

model userAssests {
  created_at       DateTime?          @default(now()) @db.Timestamptz(6)
  is_public        Boolean            @default(true)
  type             asset_type
  id               String             @id(map: "user_assests_pkey") @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  DrawingArtistRef DrawingArtistRef[]
}

model userIntrests {
  user_id    String    @id(map: "user_intrests_pkey") @db.Uuid
  created_at DateTime? @default(now()) @db.Timestamptz(6)
  tag        String?   @db.Uuid
  tags       tags?     @relation(fields: [tag], references: [tag_id], onDelete: NoAction, onUpdate: NoAction)
  users      users     @relation(fields: [user_id], references: [id], onDelete: NoAction, onUpdate: NoAction)
}

model userMeta {
  id            String         @id(map: "user_meta_pkey") @db.Uuid
  avatar        String?
  role          core_roles
  gender        gender_roles
  created_at    DateTime?      @default(now()) @db.Timestamptz(6)
  def_address   String?        @db.Uuid
  userAddresses userAddresses? @relation(fields: [def_address], references: [id], onDelete: NoAction, onUpdate: NoAction)
  users         users          @relation(fields: [id], references: [id], onDelete: NoAction, onUpdate: NoAction)
}

enum core_roles {
  ADMIN
  ARTIST
  ARTSEEKER
}

enum gender_roles {
  Female
  Male
  Other
  Refrain_to_answers
}

enum artist_type {
  drawing_artist
  music_artist
}

enum asset_type {
  IMG
  VIDEO
  DOC
}

```
and sdl which is being generated has types error, eg- skillSets.sdl.ts

```
export const schema = gql`
  type SkillSet {
    artist_id: String!
    skill: String
    created_at: DateTime
    artistMeta: artistMeta!
    tags: tags
  }

  type Query {
    skillSets: [SkillSet!]! @requireAuth
    skillSet(id: String!): SkillSet @requireAuth
  }

  input CreateSkillSetInput {
    artist_id: String!
    skill: String
    created_at: DateTime
  }

  input UpdateSkillSetInput {
    artist_id: String
    skill: String
    created_at: DateTime
  }

  type Mutation {
    createSkillSet(input: CreateSkillSetInput!): SkillSet! @requireAuth
    updateSkillSet(id: String!, input: UpdateSkillSetInput!): SkillSet!
      @requireAuth
    deleteSkillSet(id: String!): SkillSet! @requireAuth
  }

```

in which "artistMeta!" is undefined , and like so in every model sdl file. 

Please help.

**Comment by Tobbe** [comment]
@MeetChaudhari Thanks for your issue report. Can you please help us out here a little bit by creating a smaller and simpler schema that still demonstrates the problem you're seeing?

**Comment by Hennessy811** [comment]
I have the same issue: TypeScript was used to create a project (I didnt spot this issue with [this JS example), ](https://github.com/dthyresson/redwoodblog-rbac/tree/master/api/src)

So I have the following schema:

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = "native"
}

model User {
  id        String     @id @default(cuid())
  name      String?
  email     String     @unique

  questions Question[]
}

model Question {
  id      String           @id @default(cuid())
  title   String
  userId  String

  author User @relation(fields: [userId], references: [id])
}
```

when I generate a scaffold, or sdl, I get errors in sdl files
Here is an example if we generate sdl for the User: `yarn rw g sdl User`:

```
export const schema = gql`
  type User {
    id: String!
    name: String
    email: String!
    questions: [Question]!
  }

  type Query {
    users: [User!]! @requireAuth
    user(id: String!): User @requireAuth
  }

  input CreateUserInput {
    name: String
    email: String!
  }

  input UpdateUserInput {
    name: String
    email: String
  }

  type Mutation {
    createUser(input: CreateUserInput!): User! @requireAuth
    updateUser(id: String!, input: UpdateUserInput!): User! @requireAuth
    deleteUser(id: String!): User! @requireAuth
  }
`
```

and I see error on `questions: [Question]!` - `Unknown type "Question". Did you mean "Mutation"?GraphQL: Validation` in my IDE
And the console where we run `yarn rw dev` gives me the folowing:

```
 ⚠️ GraphQL server crashed 
api |  
api | 
api | 🚨 Error Info
api | 
api | {}
api |  
api | 🥞 Error Stack
api | 
api | Error: Unknown type "Question". Did you mean "Mutation"?
api |     at assertValidSDL (/home/cskeleto/code/samples/redwood-sample/node_modules/graphql/validation/validate.js:135:11)
api |     at Object.buildASTSchema (/home/cskeleto/code/samples/redwood-sample/node_modules/graphql/utilities/buildASTSchema.js:44:34)
api |     at makeExecutableSchema (/home/cskeleto/code/samples/redwood-sample/node_modules/@redwoodjs/graphql-server/node_modules/@graphql-tools/schema/index.js:495:26)
api |     at makeMergedSchema (/home/cskeleto/code/samples/redwood-sample/node_modules/@redwoodjs/graphql-server/dist/makeMergedSchema/makeMergedSchema.js:217:51)
api |     at createGraphQLHandler (/home/cskeleto/code/samples/redwood-sample/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:128:53)
api |     at Object.<anonymous> (/home/cskeleto/code/samples/redwood-sample/api/src/functions/graphql.ts:9:24)
api |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
api |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
api |     at Module.load (node:internal/modules/cjs/loader:981:32)
api |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
api | 
```

So from this point I didnt find another working example or any explaination how to handle such cases

**Comment by dthyresson** [comment]
Hi @Hennessy811 and @MeetChaudhari thanks for the report.

Could this be the issue?

> Troubleshooting
> If you see Error: Unknown type: ..., don't panic! It's a known limitation with GraphQL type generation. It happens when you generate the SDL of a Prisma model that has relations before the SDL for the related model exists. Please see [Troubleshooting Generators](https://redwoodjs.com/docs/schema-relations#troubleshooting-generators) for help.

https://redwoodjs.com/docs/schema-relations#troubleshooting-generators

>Are you getting errors when generating SDLs or scaffolds for your Prisma models? There's a known limitation in Redwood's GraphQL type generation that happens when generating SDL for, or scaffolding out, a Prisma model that has relations before the SDL for the related model exists.

This might happen if you schema out an entire data model and try to generate the full schema.

It's a known limitation that we're trying to improve.

**Comment by MeetChaudhari** [comment]
@dthyresson i tried workaround still it does not work ,  but @dac09  i manually added the types and it was fine, still while scaffolding cells, i got error

```
34 files generated
api | SyntaxError: F:\Artnyu-Reboot\My-forks\red-picaso\api\src\services\userIntrestses\userIntrestses.ts: Identifier 'userIntrests' has already been declared. (13:13)
api |
api |   11 | }
api |   12 |
api | > 13 | export const userIntrests: QueryResolvers['userIntrests'] = ({ id }) => {
api |      |              ^
api |   14 |   return db.userIntrests.findUnique({
api |   15 |     where: { id },
api |   16 |   })
api |     at instantiate (F:\Artnyu-Reboot\My-forks\red-picaso\node_modules\@babel\parser\src\parse-error\credentials.js:61:22)
api |     at toParseError (F:\Artnyu-Reboot\My-forks\red-picaso\node_modules\@babel\parser\src\parse-error.js:58:12)
api |     at raise (F:\Artnyu-Reboot\My-forks\red-picaso\node_modules\@babel\parser\src\tokenizer\index.js:1736:19)
api |     at checkRedeclarationInScope (F:\Artnyu-Reboot\My-forks\red-picaso\node_modules\@babel\parser\src\util\scope.js:153:19)
api |     at declareName (F:\Artnyu-Reboot\My-forks\red-picaso\node_modules\@babel\parser\src\util\scope.js:114:12)
api |     at declareName (F:\Artnyu-Reboot\My-forks\red-picaso\node_modules\@babel\parser\src\plugins\typescript\scope.js:52:11)
api |     at declareNameFromIdentifier (F:\Artnyu-Reboot\My-forks\red-picaso\node_modules\@babel\parser\src\parser\lval.js:707:16)
api |     at checkIdentifier (F:\Artnyu-Reboot\My-forks\red-picaso\node_modules\@babel\parser\src\parser\lval.js:702:12)
api |     at checkLVal (F:\Artnyu-Reboot\My-forks\red-picaso\node_modules\@babel\parser\src\parser\lval.js:605:12)
api |     at parseVarId (F:\Artnyu-Reboot\My-forks\red-picaso\node_modules\@babel\parser\src\parser\statement.js:1254:10) {
api |   code: 'BABEL_PARSE_ERROR',
api |   reasonCode: 'VarRedeclaration',
api |   loc: Position { line: 13, column: 13, index: 255 },
api |   pos: [Getter/Setter]
api | }
api | Unable to merge GraphQL type "Query": Field 'Query.userIntrests' changed type from '[UserIntrests!]!' to 'UserIntrests'
api | Building... [GQL Server Error] - Schema validation failed

```

**Comment by MeetChaudhari** [comment]
please reply guys

**Comment by dthyresson** [comment]
I'm not sure what you manually changed, but it seems that "UserIntrests" (or "UsersInterests"):

```
changed type from '[UserIntrests!]!' to 'UserIntrests'
```

The Query.userIntrests should return a required array: `[UserIntrests!]!` of the model `UserIntrests` -- your service is simply returning a model `UserIntrests` which typically is return from the findUnique or findOne `userIntrest` service.

BTW I would suggest for data model clarity maybe changing the schema to:

* User
* Interest
* and then a relation on User for `userInterests Interest[]` or even just `interests`.

Now, you have a model that is plural and that can be confusing down the road.

**Comment by jtoar** [comment]
@MeetChaudhari I think the main problem, or at least a confounding problem, is that you've pluralized and lowercased all your Prisma model names. Please try changing `model artistMeta` to `model ArtistMeta`.

To make what I'm talking about a little more explicit, go into `artistMeta.sdl.js`. You'll see that the type is uppercased, not lowercased: 

```gql
export const schema = gql`
  type ArtistMeta { # <-- this is uppercased
    artist_id: String!
    user_id: String!
    created_at: DateTime
    artist_type: artist_type
    social_links: String
    socialSet: socialSet
    users: users!
    DrawingArtistRef: DrawingArtistRef
    skillSet: skillSet
  }

  # ...

`
```

But in the generated `skillset.sdl.js`, it's looking for a lowercased type, which doesn't exist:

```gql
// skillSet.sdl.js
export const schema = gql`
  type SkillSet {
    artist_id: String!
    skill: String
    created_at: DateTime
    artistMeta: artistMeta! # <-- this is lowercased—not good!
    tags: tags
  }
```

A couple more questions:

- why do you have this block in your schema.prisma?

```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}
```

- I copy and pasted your schema and tried to run a migration but got an error:

```
> yarn rw prisma migrate dev -n 'setup'

Running Prisma CLI...
$ yarn prisma migrate dev -n setup --schema rwprj/sdl-gen/api/db/schema.prisma

Environment variables loaded from .env
Prisma schema loaded from api/db/schema.prisma
Datasource "db": PostgreSQL database "railway", schema "public" at "containers-us-west-71.railway.app:5627"

Applying migration `20220702111358_setup`
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20220702111358_setup

Database error code: 42883

Database error:
ERROR: function uuid_generate_v4() does not exist
HINT: No function matches the given name and argument types. You might need to add explicit type casts.

Position:
 10 -- CreateEnum
 11 CREATE TYPE "asset_type" AS ENUM ('IMG', 'VIDEO', 'DOC');
 12
 13 -- CreateTable
 14 CREATE TABLE "test" (
 15     "id" UUID NOT NULL DEFAULT uuid_generate_v4(),

DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42883), message: "function uuid_generate_v4() does not exist", detail: None, hint: Some("No function matches the given name and argument types. You might need to add explicit type casts."), position: Some(Original(410)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_func.c"), line: Some(620), routine: Some("ParseFuncOrColumn") }
```

It seems that I may have to load a Postgres module to faithfully reproduce this?

**Comment by dthyresson** [comment]
For example, first I have a schema like:


```
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = "native"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}

model Interest {
  id    Int    @id @default(autoincrement())
  title String
}
```

And migrate. `yarn rw prisma migrate dev`	

Then dal the User:

```
interests % yarn rw g sdl User --crud
  ✔ Generating SDL files...
    ✔ Successfully wrote file `./api/src/graphql/users.sdl.ts`
    ✔ Successfully wrote file `./api/src/services/users/users.scenarios.ts`
    ✔ Successfully wrote file `./api/src/services/users/users.test.ts`
    ✔ Successfully wrote file `./api/src/services/users/users.ts`
  ✔ Generating types ...
```

The the Interest

```
interests % yarn rw g sdl Interest --crud
  ✔ Generating SDL files...
    ✔ Successfully wrote file `./api/src/graphql/interests.sdl.ts`
    ✔ Successfully wrote file `./api/src/services/interests/interests.scenarios.ts`
    ✔ Successfully wrote file `./api/src/services/interests/interests.test.ts`
    ✔ Successfully wrote file `./api/src/services/interests/interests.ts`
  ✔ Generating types ...
interests % 
```

Then make the relation:

```
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = "native"
}

model User {
  id        Int        @id @default(autoincrement())
  email     String     @unique
  name      String?
  interests Interest[]
}

model Interest {
  id     Int    @id @default(autoincrement())
  title  String
  User   User?  @relation(fields: [userId], references: [id])
  userId Int?
}
```

And then redo to sdl's with a force

```
interests % yarn rw g sdl User --crud --force
  ✔ Generating SDL files...
    ✔ Successfully wrote file `./api/src/graphql/users.sdl.ts`
    ✔ Successfully wrote file `./api/src/services/users/users.scenarios.ts`
    ✔ Successfully wrote file `./api/src/services/users/users.test.ts`
    ✔ Successfully wrote file `./api/src/services/users/users.ts`
  ✔ Generating types ...
interests % yarn rw g sdl Interest --crud --force
  ✔ Generating SDL files...
    ✔ Successfully wrote file `./api/src/graphql/interests.sdl.ts`
    ✔ Successfully wrote file `./api/src/services/interests/interests.scenarios.ts`
    ✔ Successfully wrote file `./api/src/services/interests/interests.test.ts`
    ✔ Successfully wrote file `./api/src/services/interests/interests.ts`
  ✔ Generating types ...
```

And my graphql schema that is generated has:

```
"""
Use to check whether or not a user is authenticated and is associated
with an optional set of roles.
"""
directive @requireAuth(roles: [String]) on FIELD_DEFINITION

"""Use to skip authentication checks and allow public access."""
directive @skipAuth on FIELD_DEFINITION

scalar BigInt

input CreateInterestInput {
  title: String!
  userId: Int
}

input CreateUserInput {
  email: String!
  name: String
}

scalar Date

scalar DateTime

type Interest {
  User: User
  id: Int!
  title: String!
  userId: Int
}

scalar JSON

scalar JSONObject

type Mutation {
  createInterest(input: CreateInterestInput!): Interest!
  createUser(input: CreateUserInput!): User!
  deleteInterest(id: Int!): Interest!
  deleteUser(id: Int!): User!
  updateInterest(id: Int!, input: UpdateInterestInput!): Interest!
  updateUser(id: Int!, input: UpdateUserInput!): User!
}

type Query {
  interest(id: Int!): Interest
  interests: [Interest!]!
  redwood: Redwood
  user(id: Int!): User
  users: [User!]!
}

type Redwood {
  currentUser: JSON
  prismaVersion: String
  version: String
}

scalar Time

input UpdateInterestInput {
  title: String
  userId: Int
}

input UpdateUserInput {
  email: String
  name: String
}

type User {
  email: String!
  id: Int!
  interests: [Interest]!
  name: String
}
```

And ma good to go.

That's unfortunately the workaround as noted in troubleshooting.

**Comment by jtoar** [comment]
@Hennessy811 I've tried reproducing your issue but everything's working fine. Could you have a look at what I did to see what may be different? https://s.tape.sh/Enkmx7ds.

**Comment by MeetChaudhari** [comment]
> @MeetChaudhari I think the main problem, or at least a confounding problem, is that you've pluralized and lowercased all your Prisma model names. Please try changing `model artistMeta` to `model ArtistMeta`.
> 
> To make what I'm talking about a little more explicit, go into `artistMeta.sdl.js`. You'll see that the type is uppercased, not lowercased:
> 
> ```graphql
> export const schema = gql`
>   type ArtistMeta { # <-- this is uppercased
>     artist_id: String!
>     user_id: String!
>     created_at: DateTime
>     artist_type: artist_type
>     social_links: String
>     socialSet: socialSet
>     users: users!
>     DrawingArtistRef: DrawingArtistRef
>     skillSet: skillSet
>   }
> 
>   # ...
> 
> `
> ```
> 
> But in the generated `skillset.sdl.js`, it's looking for a lowercased type, which doesn't exist:
> 
> ```graphql
> // skillSet.sdl.js
> export const schema = gql`
>   type SkillSet {
>     artist_id: String!
>     skill: String
>     created_at: DateTime
>     artistMeta: artistMeta! # <-- this is lowercased—not good!
>     tags: tags
>   }
> ```
> 
> A couple more questions:
> 
> * why do you have this block in your schema.prisma?
> 
> ```prisma
> generator client {
>   provider      = "prisma-client-js"
>   binaryTargets = ["native"]
> }
> ```
> 
> * I copy and pasted your schema and tried to run a migration but got an error:
> 
> ```
> > yarn rw prisma migrate dev -n 'setup'
> 
> Running Prisma CLI...
> $ yarn prisma migrate dev -n setup --schema rwprj/sdl-gen/api/db/schema.prisma
> 
> Environment variables loaded from .env
> Prisma schema loaded from api/db/schema.prisma
> Datasource "db": PostgreSQL database "railway", schema "public" at "containers-us-west-71.railway.app:5627"
> 
> Applying migration `20220702111358_setup`
> Error: P3018
> 
> A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
> 
> Migration name: 20220702111358_setup
> 
> Database error code: 42883
> 
> Database error:
> ERROR: function uuid_generate_v4() does not exist
> HINT: No function matches the given name and argument types. You might need to add explicit type casts.
> 
> Position:
>  10 -- CreateEnum
>  11 CREATE TYPE "asset_type" AS ENUM ('IMG', 'VIDEO', 'DOC');
>  12
>  13 -- CreateTable
>  14 CREATE TABLE "test" (
>  15     "id" UUID NOT NULL DEFAULT uuid_generate_v4(),
> 
> DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42883), message: "function uuid_generate_v4() does not exist", detail: None, hint: Some("No function matches the given name and argument types. You might need to add explicit type casts."), position: Some(Original(410)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_func.c"), line: Some(620), routine: Some("ParseFuncOrColumn") }
> ```
> 
> It seems that I may have to load a Postgres module to faithfully reproduce this?



> @MeetChaudhari I think the main problem, or at least a confounding problem, is that you've pluralized and lowercased all your Prisma model names. Please try changing `model artistMeta` to `model ArtistMeta`.
> 
> To make what I'm talking about a little more explicit, go into `artistMeta.sdl.js`. You'll see that the type is uppercased, not lowercased:
> 
> ```graphql
> export const schema = gql`
>   type ArtistMeta { # <-- this is uppercased
>     artist_id: String!
>     user_id: String!
>     created_at: DateTime
>     artist_type: artist_type
>     social_links: String
>     socialSet: socialSet
>     users: users!
>     DrawingArtistRef: DrawingArtistRef
>     skillSet: skillSet
>   }
> 
>   # ...
> 
> `
> ```
> 
> But in the generated `skillset.sdl.js`, it's looking for a lowercased type, which doesn't exist:
> 
> ```graphql
> // skillSet.sdl.js
> export const schema = gql`
>   type SkillSet {
>     artist_id: String!
>     skill: String
>     created_at: DateTime
>     artistMeta: artistMeta! # <-- this is lowercased—not good!
>     tags: tags
>   }
> ```
> 
> A couple more questions:
> 
> * why do you have this block in your schema.prisma?
> 
> ```prisma
> generator client {
>   provider      = "prisma-client-js"
>   binaryTargets = ["native"]
> }
> ```
> 
> * I copy and pasted your schema and tried to run a migration but got an error:
> 
> ```
> > yarn rw prisma migrate dev -n 'setup'
> 
> Running Prisma CLI...
> $ yarn prisma migrate dev -n setup --schema rwprj/sdl-gen/api/db/schema.prisma
> 
> Environment variables loaded from .env
> Prisma schema loaded from api/db/schema.prisma
> Datasource "db": PostgreSQL database "railway", schema "public" at "containers-us-west-71.railway.app:5627"
> 
> Applying migration `20220702111358_setup`
> Error: P3018
> 
> A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
> 
> Migration name: 20220702111358_setup
> 
> Database error code: 42883
> 
> Database error:
> ERROR: function uuid_generate_v4() does not exist
> HINT: No function matches the given name and argument types. You might need to add explicit type casts.
> 
> Position:
>  10 -- CreateEnum
>  11 CREATE TYPE "asset_type" AS ENUM ('IMG', 'VIDEO', 'DOC');
>  12
>  13 -- CreateTable
>  14 CREATE TABLE "test" (
>  15     "id" UUID NOT NULL DEFAULT uuid_generate_v4(),
> 
> DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42883), message: "function uuid_generate_v4() does not exist", detail: None, hint: Some("No function matches the given name and argument types. You might need to add explicit type casts."), position: Some(Original(410)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_func.c"), line: Some(620), routine: Some("ParseFuncOrColumn") }
> ```
> 
> It seems that I may have to load a Postgres module to faithfully reproduce this?

thank you it worked, i would request you mention this naming convention in docs somewhere, like it could save some developer many days, i wasted 5 days on this . Thanks a lott.

**Comment by pixsrv** [comment]
generator still cannot handle names like AbcXYS
i tried also AbcXYS_ AbcXYSs AbcXYSes

it tries to change casing into something like AbcXySs (and the followings) and fails the same way
