### ISSUE TITLE
bug) Fix prisma not autocompleting in services files

### ISSUE THREAD

**Issue by guledali** [redwoodjs/redwood#584]
Autocompletion from prisma is missing in services file strangely enough it works in the 
[example-todo](https://github.com/redwoodjs/example-todo) example. 

This has also been reported a while ago back in 0.3 release, but has not seen a fix yet
https://community.redwoodjs.com/t/redwoodjs-v0-3-2-available-breaking-changes/220

**Comment by peterp** [comment]
@guledali I think the problem is that we ship with a tsconfig.json and jsconfig.json in create-redwood-app template:

Could you try deleting this file: https://github.com/redwoodjs/create-redwood-app/blob/master/api/jsconfig.json

**Comment by guledali** [comment]
Yeah you're right I just deleted tsconfig.json file locally and it worked,

**Comment by guledali** [comment]
@peterp Can you change so that it only ships with one of them?

**Comment by guledali** [comment]
https://github.com/redwoodjs/create-redwood-app/pull/60
