### ISSUE TITLE
Transformer directive throws during test due to `directiveArgs` always undefined

### ISSUE THREAD

**Issue by Philzen** [redwoodjs/redwood#5845]
We've written a transformer directive to filter unauthorized records such as this:

```ts
export const schema = gql`
  directive @ownDataOnly(list: Boolean) on FIELD_DEFINITION
`

const transform: TransformerDirectiveFunc = ({
  context,
  resolvedValue,
  directiveArgs,
}) => {
  const { list } = directiveArgs

  if (list) {
    return resolvedValue.filter(
      (record) => record.userId === context.currentUser.id
    )
  }

  return resolvedValue.userId === context.currentUser.id ? resolvedValue : null
}

export default createTransformerDirective(schema, transform)
```

When running a simple test on it, such as: 
```ts
  beforeEach(() => {
    mockCurrentUser({ id: 101, email: 'test101@test.com' })
  })

  it("returns null if it's not the user's own record", () => {
    const mockExecution = mockRedwoodDirective(ownDataOnly, {
      mockedResolvedValue: { userId: 666 },
    })

    expect(mockExecution()).toBe(null)
  })
```

The following error is thrown, causing this and basically any tests involving `mockRedwoodDirective` to fail:

```sh
TypeError: Cannot destructure property 'list' of 'directiveArgs' as it is undefined.
```

### Notable

- tried supplying `directiveArgs: { list: true }` in `mockRedwoodDirective`'s `executionMock` argument, but `directiveArgs`is still undefined. Not sure if that isn't a separate issue on its own or if i'm simply overlooking something.
- Interestingly enough the `requireAuth.ts` directive that ships with RedwoodJS also uses and destructures the `directiveArgs`-property – which comes into the validate-callback as an empty object, hence the `"requireAuth has stub implementation. Should not throw when current user"`-test passes fine.
- our transform directive works absolutely fine otherwise i.e. when running in dev-environment

**Comment by Philzen** [comment]
Hi @dac09, thanks for your immediate feedback!

> Hi @Philzen - this is probably a valid issue, but both @dthyresson and I think this isn't an appropriate use of transformer directives. [...] even if the userId requesting is not authorized, the code in your service would be running [...]

Actually the transformer code does also check for the currentUser in context and throws if not authenticated, i only out that line (and also our own comments making clear that this runs *after* any query retrieval :wink: ) for sake of this example (but looking at my explanation further below even that may be overkill in this transformer).

> It might be better to check the userId in your service, and throw an `ForbiddenError` if the user isn't authorized.

We're also doing that in the service as well (although we're leaving it off mostly to prisma, which will throw on connected records issues), i agree that a ForbiddenError would be nicer – though in our case it's really just an exercise to secure the api side against mischief (those endpoints are only intended to be used by the web workspace).

Actually, we currently have three layers of authentication security – `@requireAuth`, services (validateWith), `@ownDataOnly` – and two layers of authorization security – services (prisma [related records](https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries#update-a-specific-related-record)) and `@ownDataOnly`, which seems like overkill, but it's basically what we've learned from [Tutorial Chapter 4](https://redwoodjs.com/docs/tutorial/chapter4/authentication) ... better safe than sorry, in case some auth validation is simply forgotten or goes south during a refactoring.

I'd welcome your thoughts and feedback on this strategy. Personally, i'm a performance nerd and would go for one check is enough, but after careful discussion and consideration with my collegue we chose to go with the multiple safety-layer implementation.

**Comment by dac09** [comment]
I'll give you my 2p @Philzen - but please don't take this as gospel - for me, having complicated logic such as auth located in one place is always an advantage, especially if you are a growing team/building out your product. 

At some point in the future you may want to change parts of how your auth system works, and you'd have to refactor three different places, which is not ideal! 

Auth is also one of those things that needs a lot of "context" - so having your unit tests colocated, and in one place (even if not the same file) is a massive time saver

**Comment by dthyresson** [comment]
> Personally, i'm a performance nerd and would go for one check is enough, but after careful discussion and consideration with my collegue we chose to go with the multiple safety-layer implementation.

@Philzen My concern might be that the auth rules are now in three places and if the rules change, then the risk is higher because you do not have as much confidence in what the rule applied will be. Maybe the rule is changed in 2 places but then the third check is used and people access data the cannot.
