### ISSUE TITLE
[Docs] New Guide for using Cells

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#585]
_related to #332_

We need documentation for Redwood Cells. Suggested starting place:
- use copy from website homepage redwoodjs.com
- include some copy from https://redwoodjs.com/tutorial/cells
- include this new functionality to accept functions for a query. See #505 

@cannikin Any other suggestions here?

@jtoar wanna take a stab? All good if not.

**Comment by jtoar** [comment]
@thedavidprice I'm down--are you thinking more along the lines of a guide/recipe/reference?

**Comment by thedavidprice** [comment]
Admittedly, this one will have mixed content. But start it as a **how-to Guide** and let's see where it goes. Cells are a super important and super rad aspect of Redwood. So this one's important. 

Here's how I'd prioritize the information architecture:
1. **Reference:** make it clear how to use them --> generator and overview of elements. This is straight forward and should make it clear how Cells work. And do include #505 info
2. **How To:** add an example problem/solution (maybe). Better yet, it might be best to just say "Want to see the guides in action? Check out this section of the Tutorial?"
3. **Explanation:** some "side quest"-type copy. This is where we can highlight especially what makes Cells unique and rad. Could even link to articles written about cells. E.g. 

Make sense? Suggestions/thoughts otherwise?

**Comment by cannikin** [comment]
This sounds good to me! I'm trying to think if there's some kind of Cookbook recipe that could highlight using them in some unique way that isn't covered in the tutorial or any of these upcoming docs...

**Comment by jtoar** [comment]
Was working on this now and planned to report back with questions, but the discussion in #322 seems more pressing and will have some bearings on this.
