### ISSUE TITLE
[RFC]: Show stack trace of errors in dev server console

### ISSUE THREAD

**Issue by Philzen** [redwoodjs/redwood#5853]
### Summary

Enable error stack trace visibility in the dev console for development (and potentially in logs for production).

### Motivation

When devs make a coding mistake in a directive, the only information given is the error message, both in graphQL playground

![grafik](https://user-images.githubusercontent.com/1634615/176556545-dc328902-d6cf-4ffc-aff0-c3425fe5249a.png)

and the terminal output

![grafik](https://user-images.githubusercontent.com/1634615/176556663-4537ba22-fd6b-4e1b-8d9e-c2bae5d39696.png)

Impossible to tell in which file or even line of code the error happened with that information. Because i'd just refactored a [transformer directive](#5845) the day before i had a lucky hunch this error was thrown there because resolvedValue i was trying to access was already null for a given query.

Hunches are good and sometimes helpful – but i'd argue that a good stack trace is much more helpful in the first place :wink: 

### Detailed proposal

This is about the API side and shouldn't be a breaking change of any sorts.

For starters, root cause visibility needs to be the default in development env. I'm agnostic about how this is configured in production, but i guess it should fall in the lines of current logging configuration.

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Philzen** [comment]
OK, i'm confused now:

My main project i'm working on is on 1.5.1, but i have a sandbox project based on 2.0.0 – and in the the latter i get full-on stack traces, preceded by a `🚨 GraphQLError Info` object.

**Comment by Philzen** [comment]
Confusion solved: #5816 which was shipped with 2.0.0 fixed this.

Guess it's high time to upgrade.

**Comment by dthyresson** [comment]
Sorry for the confusion - we got that regression fix in during the last release. Glad it’s working for you.
