### ISSUE TITLE
In scaffolds, `show` action raises a GraphQL error if a record isn't returned

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#586]
Not sure if is technically a bug or a feature. If you only used the scaffolded pages through the UI you wouldn't run into this issue. But as soon as you go outside those bounds (like try to view a record that doesn't exist, or view a record that doesn't belong to you) you'll see this.

The default for single record GraphQL types includes a ! to make them required:

```graphql
  type Query {
    images: [Image!]!
    image(id: Int!): Image!   //  <---
  }
```

We're seeing that if you try to `show` a record that doesn't exist at all you get a GraphQL error instead of just showing the `Empty` component in the Cell.

**Comment by thedavidprice** [comment]
Hmm, I'd put it in the "unexpected behavior of a feature" category.

Could we solve it with something as simple as improving the _error messaging_ when this situation throws?

**Comment by cannikin** [comment]
It seems totally reasonable that you might query a record and that record doesn't exist, it just should just be `null`, right? Rather than raising an error, which is usually reserved for "exceptional" circumstances. If you tried to query by a string or a datetime or something, that seems error worthy.

**Comment by thedavidprice** [comment]
> It seems totally reasonable that you might query a record and that record doesn't exist, it just should just be null, right? Rather than raising an error, which is usually reserved for "exceptional" circumstances. If you tried to query by a string or a datetime or something (when the primary key is an Int), that seems error worthy.

Ah, definitely 💯

I just didn't understand that behavior was possible. If so, it makes all the sense.
