### ISSUE TITLE
"yarn rw g auth netlify" is a noop

### ISSUE THREAD

**Issue by mateja176** [redwoodjs/redwood#589]
## Steps to reproduce

```sh
git clone https://github.com/mateja176/redwoodblog
cd redwoodblog
yarn rw g auth netlify
```

## Expected behavior

Described in the respective tutorial [section](https://redwoodjs.com/tutorial/authentication#authentication-generation)

## Actual behavior

`git status`

> nothing to commit, working tree clean

**Comment by thedavidprice** [comment]
Hi @mateja176 Sorry for the confusion here. You'll first need to update to Redwood v0.7.0 (you're on v0.6.0). The good news is that it's as simple as running the command `yarn rw upgrade`.

cc @cannikin what do you think about adding a "Heads Up" note toward the beginning of the new Auth section in the Tutorial? 

Closing for now. But please loop back if anything else is giving your trouble!

**Comment by cannikin** [comment]
@thedavidprice Roger that, will do
