### ISSUE TITLE
[Bug?]: Generating the Prisma client.

### ISSUE THREAD

**Issue by wbashir** [redwoodjs/redwood#5897]
### What's not working?

Hi,

I'm getting the same **Error: The service was stopped**
```
Generating TypeScript definitions and GraphQL schemas...
gen | 91 files generated
api | dyld: Symbol not found: _SecTrustEvaluateWithError
api |   Referenced from: .../node_modules/esbuild-darwin-64/bin/esbuild
api |   Expected in: flat namespace
api | 
api | Error: The service was stopped
api |     at ../node_modules/esbuild/lib/main.js:1335:25
api |     at ..web/node_modules/esbuild/lib/main.js:666:9
api |     at Socket.afterClose (../node_modules/esbuild/lib/main.js:644:7)
api |     at Socket.emit (events.js:388:22)
api |     at endReadableNT (internal/streams/readable.js:1336:12)
api |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

### How do we reproduce the bug?

Just by running `yarn rw dev api` on either versions 1.5 or 2.0

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jtoar** [comment]
Hey @wbashir. I can't reproduce this one just by creating a new redwood app then running `yarn rw dev api`. Both of those errors mention `esbuild`—maybe it didn't install correctly? Have you tried the tried-and-true remove `node_modules` and `yarn install` again already?

The output of `yarn rw info` could also give us a few more leads on what could be wrong, or any other details about your repo if it's different from just `yarn create redwood-app`. Let us know—thanks!

**Comment by wbashir** [comment]
I removed all node_modules in `Web, Api, and Main` folder and re-ran `yarn install`.

Here is the output from `yarn rw info`

```
System:
    OS: macOS Sierra 10.12.6
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.0 - /var/folders/g8/v3pg_x4979sb908w9v6dxzpr0000gn/T/yarn--1657595192398-0.904692110004736/node
    Yarn: 1.17.3 - /var/folders/g8/v3pg_x4979sb908w9v6dxzpr0000gn/T/yarn--1657595192398-0.904692110004736/yarn
  Databases:
    SQLite: 3.26.0 - /anaconda/bin/sqlite3
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 72.0.2
    Safari: 12.1.2
  npmPackages:
    @redwoodjs/core: 2.0.0 => 2.0.0 
```

@jtoar

**Comment by wbashir** [comment]
I just tried on a new project and it's still not working either. 

Output from `yarn rw info`

`System:
    OS: macOS Sierra 10.12.6
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.19.0 - /private/var/folders/g8/v3pg_x4979sb908w9v6dxzpr0000gn/T/xfs-ef1588b1/node
    Yarn: 3.2.1 - /private/var/folders/g8/v3pg_x4979sb908w9v6dxzpr0000gn/T/xfs-ef1588b1/yarn
  Databases:
    SQLite: 3.26.0 - /anaconda3/bin/sqlite3
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 72.0.2
    Safari: 12.1.2
  npmPackages:
    @redwoodjs/core: 2.0.0 => 2.0.0 `

**Comment by dac09** [comment]
I'm not a 100% sure on this, but this looks like the reason - the macOS version you're on does not support Go: https://github.com/evanw/esbuild/issues/2183

We don't typically test on such an old version of MacOS - admittedly! 

I'm afraid the only option here would be to upgrade macOS to 10.13+.

**Comment by wbashir** [comment]
Painful but thanks
