### ISSUE TITLE
[Tech debt]: Re-enable telemetry for windows

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#5901]
### What's not working?

We are disabling telemetry on Windows in https://github.com/redwoodjs/redwood/pull/5899 - due to the terminal windows opening when using the CLI.

We need to renable telemetry, once we can workout a way of preventing the terminal windows spawining.

### Related Issues
- https://github.com/redwoodjs/redwood/issues/5757
- https://github.com/redwoodjs/redwood/issues/5728

**Comment by Gresliebear** [comment]
Node added a windowHide option 

https://github.com/nodejs/node/pull/15380

**Comment by jtoar** [comment]
@Gresliebear thanks for looking into this. We've tried `windowsHide` (https://github.com/redwoodjs/redwood/pull/5734), but it doesn't seem to work with detached processes: https://github.com/nodejs/node/issues/21825.
