### ISSUE TITLE
[Tutorial]: Chapter 3 Saving Data code blocks inconsistency 

### ISSUE THREAD

**Issue by pwellner** [redwoodjs/redwood#5902]
### Summary and description

The "[Saving Data](https://redwoodjs.com/docs/tutorial/chapter3/saving-data
)" section of Chapter 3 (v2.0) is inconsistant with what  I observe.

After executing `yarn rw g sdl Contact`, where the tutorial says "let's take a look at the service:" and displays the file `api/src/services/contacts/contacts.ts`  I see a very different result.

First line of the tutorial version is `import type { Prisma } from '@prisma/client'`
whereas my first line is `import type { QueryResolvers, MutationResolvers } from 'types/graphql'`

After that, some instructions for editing `web/src/pages/ContactPage/ContactPage.tsx`  do not work.  For example, the following does not compile:

```
import {
  CreateContactMutation,
  CreateContactMutationVariables,
} from 'types/graphql'
````

My version is as follows:
```bash
$ yarn rw info

  System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.16.0 - /tmp/xfs-2481bfb6/node
    Yarn: 3.2.1 - /tmp/xfs-2481bfb6/yarn
  Databases:
    SQLite: 3.33.0 - /home/pwellner/miniconda3/bin/sqlite3
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 102.0
  npmPackages:
    @redwoodjs/core: 2.0.0 => 2.0.0
```

Does the tutorial need an update, or do I need an update?  Thanks

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by pwellner** [comment]
Workaround for anyone finding this issue and wanting to move forward with the tutorial:

Forget about the recommended `import` and use less Typescript in your code.  The following works:

```
  const [create] = useMutation(CREATE_CONTACT)
```

**Comment by dac09** [comment]
Hi @pwellner - the tutorial does go a little out of date, when we update our generators. We'll have to make an effort to redo some of the codeblocks - sorry about this.

Using less TypeScript is always an option ;) - but perhaps this will help you

The reason you see the red squiggles under the imported types is that these types are generated. If you have `yarn rw dev` running, they will automatically be generated. If you would like to trigger them, you can run `yarn rw g types`

**Comment by simoncrypta** [comment]
@dac09 Does PR #5873 solved this, or we need to wait for strict mode and update the tutorial ?
