### ISSUE TITLE
When approximately will it be ready for production

### ISSUE THREAD

**Issue by BeaRRRRR** [redwoodjs/redwood#591]
_I know that this is a very broad question to ask, and apologize in advance._

In the README it is said that this framework is only in alpha and shouldn't be used in production, but this framework seems like the perfect thing for my new website/startup, which I plan to launch sometime in July. 

So I was wondering if it's going to be somewhat production-ready by July, or I am better off just setting up everything from scratch and not using this framework for the time-being?

**Comment by jtoar** [comment]
Not an authority here, but I think @mojombo mentioned on a podcast that 1.0 (I'm assuming that means production ready?) would be an end-of-the-year goal. So a hard no on July (but wait for someone else to weigh in too).

But if you do decide to use Redwood, you could help us learn how to bring Redwood to production faster! And note that there is actually already a site made with Redwood out there in the wild: https://predictcovid.com/, and all the code's open source.

**Comment by zwl1619** [comment]
Hi @jtoar 
1、Open https://predictcovid.com , but it has nothing. 
2、Where is the code of https://predictcovid.com ?

**Comment by jtoar** [comment]
Hey @zwl1619 the link wasn't working for you? The code is at https://github.com/lachlanjc/covid19, there's a link to the site there. Tagging @lachlanjc here as well because we're talking about your awesome work!

**Comment by lachlanjc** [comment]
Hey! I’m not seeing any issues—what specifically are you running into? That’s the code link already, so you’re welcome to check it out as well or run locally.

**Comment by zwl1619** [comment]
I see it now!

**Comment by BeaRRRRR** [comment]
@jtoar Thanks for the answer! It is a pity that I want my startup to be out at least by August. Also, there is no first-class typescript support yet, which is crucial for me. But this framework seems like a very promising thing, so keep up the great work guys!
