### ISSUE TITLE
[Tutorial]: Chapter 2 Generating Cell doesn't produce query type for graphql

### ISSUE THREAD

**Issue by ldm-accenture** [redwoodjs/redwood#5917]
### Summary and description

Following chapter 2 of the tutorial and using typescript the flow is:

- create a Post type in `schema.prisma`
- generate a migration for it `yarn rw prisma migrate dev`
- scaffold crud for Post `yarn rw g scaffold post`
- generate an Article cell that will edited to point to the Post queries `yarn rw g cell Articles`

the generated code produces an `ArticlesQuery` type which wasn't added to the graphql types because there is no sdl for Articles.

The error isn't blocking or anything, but it isn't clear how to generate the query types required to remove the typescript errors when creating cells named differently than existing model types.

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by ldm-accenture** [comment]
after a round of delete and redo (with some `yarn rw g types` in between), I can't replicate the error

**Comment by noire-munich** [comment]
Thank you @ldm-accenture

We are aware of type issues on generated types, it's great that you are not blocked by this, we'll keep looking into these 👍
