### ISSUE TITLE
[Bug?]: Typescript – type incompatibility Form.onSubmit

### ISSUE THREAD

**Issue by Philzen** [redwoodjs/redwood#5956]
### What's not working?

When using the Form with another component library such as ChakraUI, TypeScript produces a warning:

```sh
Type '(input: any, e: any) => void' is not assignable to type 'FormEventHandler<HTMLFormElement>'.ts(2322)
index.d.ts(1410, 9): The expected type comes from property 'onSubmit' which is declared here on type 'IntrinsicAttributes & OmitCommonProps<DetailedHTMLProps<FormHTMLAttributes<HTMLFormElement>, HTMLFormElement>, keyof ChakraProps> & ChakraProps & OmitCommonProps<...> & { ...; }'
```

This seems to be caused by the different signature and behaviour (a rather convenient though) of the `onSubmit` handler type. 

I threw up a sandbox to demonstrate a Redwood Forms + Chakra UI integration (which generally is a breeze) where you can see the error on line 40: https://codesandbox.io/s/epic-christian-3mfvct?file=/src/index.tsx:696-728

Everything works fine, all components i integrated so far `forwardRef`s successfully, but i cannot seem to come up with a workaround that does not show this typescript warning. 

### What's your environment? (If it applies)

Discovered in 1.5.1, as the sandbox shows also applicable to 2.1.0

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by TristanWYL** [comment]
Hi, I checked the definition of the FormEvent:
```typescript
type EventHandler<E extends SyntheticEvent<any>> = { bivarianceHack(event: E): void }["bivarianceHack"];
type FormEventHandler<T = Element> = EventHandler<FormEvent<T>>;
...
    onSubmit?: FormEventHandler<T> | undefined;
...
```
This means `onSubmit` can only be assigned with a function with single argument, so updating the function `handleSubmit` as below can fix this problem.
```ts
function handleSubmit(e) {
    // alert(input.message);
    console.log(e);
}
```

Actually according to the description of Chakra-UI, 

>  * Box is the most abstract component on top of which other chakra
>  * components are built. It renders a `div` element by default.

I have never used Chakra-UI before, so I guess we may not be able to use Box as Form to auto-submit the data. Actually, Chakra-UI has its own [Form-related components](https://chakra-ui.com/docs/components/form-control), I guess you could give them a try.

**Comment by Philzen** [comment]
@TristanWYL 

> updating the function handleSubmit as below can fix this problem.
    function handleSubmit(e) {
        // alert(input.message);
        console.log(e);
    }

This works b/c `e` has an implicit `any` type – while it is not a event at all, the correct typing for a single argument callback still is:

```
function handleSubmit(input: { message: string }) { … }
```

… which again makes a typescript error.

> I have never used Chakra-UI before, so I guess we may not be able to use Box as Form to auto-submit the data. 

Yes, one can actually use most Chakra UI components to render something else – the `as` property simply set's the `ref` to pass on to `forwardRefs`, *which is a React mechanism, not a Chakra UI invention*. `<Box>` was just used in this example for the sake of brevity – here is another example using `<chakra.form>`: https://codesandbox.io/s/stupefied-mayer-hvvpwd?file=/src/index.tsx (which is functionally exactly the same).

> Actually, Chakra-UI has its own [Form-related components](https://chakra-ui.com/docs/components/form-control), I guess you could give them a try

That one is already used in both examples as you can see :wink: 
----
I am no TypeScript wizard, but i believe the `onSubmit`-definition simply needs to be overwritten. If one navigates to the type definition, it resolves to `@types/react`, while it'd need to resolve to RedwoodJS's own one.

**Comment by TristanWYL** [comment]
Hi @Philzen , I am pretty sure, that the `onSubmit` method of Chakra's Form only accepts one arg which is of FormEvent. However, you used Redwoodjs's Form for the `as` prop, so the `Box` component is replaced by Redwoodjs's Form, but the props type still keep same as `Box`, rather than replaced by Redwoodjs Form's props. I guess this is a bug of Chakra, and probably you should turn to Chakra community. 

In addition, though Chakra does not replace the props automatically for you, you could also `manually` replace the props. I attach a solution [here](https://codesandbox.io/s/quizzical-colden-zyi0gi?file=/src/index.tsx) for your reference.

**Comment by TristanWYL** [comment]
Actually I am very curious about how ChakraUI component's `as` props works, so I submitted [an issue](https://github.com/chakra-ui/chakra-ui/issues/6367) in ChakraUI's github. Hope any responses can help us.

**Comment by TristanWYL** [comment]
I guess [this reply](https://github.com/chakra-ui/chakra-ui/issues/6367#issuecomment-1193245029) could help!

**Comment by Philzen** [comment]
I have forked the sandbox and made some additional tests, building two additional silly components that `forwardRef`s and redefine 

1. [a prop with a different typing than found in `@react/types`](https://codesandbox.io/s/competent-dubinsky-n0wymw?file=/src/other-example.tsx:500-561) – same as RedwoodJS' `<Form>` does, apart from it being all but silly :wink: 
2. [a prop with a different typing than found in `@chakra-ui/system`](https://codesandbox.io/s/competent-dubinsky-n0wymw?file=/src/another-example.tsx:657-729)

… and both examples show the same TypeScript error. So ultimately, i believe that i've literally been barking at the wrong Redwood tree all along :laughing: 

Therefore i've reported this now over at https://github.com/chakra-ui/chakra-ui/issues/6439 and will close this one.

**Comment by Philzen** [comment]
@TristanWYL Thanks heaps for all your help and support along the way :green_heart: 

As you seem pretty skilled with TypeScript maybe you'll be able to look at 

https://github.com/chakra-ui/chakra-ui/blob/ff0dfb2b735a047c7a811f65b20fb81fa3db6f4a/packages/system/src/system.types.tsx#L75-L76

… and tell why that's misbehaving – in case you fancy the challenge or simply want to chime in to the discussion over at the referenced issue. But hopefully it will go well over there.
