### ISSUE TITLE
Include example of `role` usage in <Private> route

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#5997]
There's a single sentence that mentions using `role` to limit a route, but no actual code sample: https://redwoodjs.com/docs/router#private-set

It also states that it takes an array of strings, but it also accepts a single string (at least in my testing as I'm updating the tutorial). That's good, and this is the same for the argument passed to `requireAuth()` on the API side and `hasRole()` on the web side. We should just document (and show code examples) of both usages.

Note: depending on the outcome of https://github.com/redwoodjs/redwood/issues/4488 this may become `roles` instead of `role`

**Comment by marko-hologram** [comment]
Not sure if this was already addressed to a certain extent, but I've ran into some of these examples in docs here https://redwoodjs.com/docs/how-to/role-based-access-control-rbac#how-to-protect-a-route.

This isn't listed in `<Private />` component docs, but I guess it could be copied over?

**Comment by samthuang** [comment]
Hello @cannikin and @marko-hologram 

I saw that this needed help and seems stale, so I took the liberty and opened a draft PR https://github.com/redwoodjs/redwood/pull/7779, including how to use `roles` in the private Set part of the documentation. I mainly copied over the examples in https://redwoodjs.com/docs/how-to/role-based-access-control-rbac#how-to-protect-a-route as mentioned, and added a backlink. 

Note: It's my first time contributing, and I welcome feedback, comments, and guidance.
