### ISSUE TITLE
[RFC]: Use Case for GraphQL Scalar Types - Primsa lists/arrays Multiple Upload Photos 

### ISSUE THREAD

**Issue by Gresliebear** [redwoodjs/redwood#6009]
### Summary

I would like to present my issues/experience currently with redwood so bare with me, on this Use Case its from my own challenges with Redwood, I don't know it indepth, its outsiders point of view. I have a simple idea that I am currently implementing in a app "uploading Multiple  Photos" for example I am uploading many photos and converting into base64 to store as a string. I thought its fine I can store in a array in backend. So I tried making a array in the schema.prisma 

![image](https://user-images.githubusercontent.com/13157730/180126600-25ea7ef9-ddc5-4fc9-9f86-dcc6bde17b64.png)

Annnnnnnd it doesn't work, I am definitely a beginner developer in terms of the tools of redwood. However from a User Experience point of view, or a Developer Experience Redwood Docs and its Marketing definitely gave me the Message that Redwood uses Prisma so the same concepts from Prisma should work in Redwood exactly. For example if I google Prisma Lists/Arrays I get a working example from Prisma but this doesn't translate into Redwood. However I am aware that in the docs they mention Redwood "Limitations".

![image](https://user-images.githubusercontent.com/13157730/180126881-bee43f42-6118-4ff7-8573-a05657e5479a.png)

But after hours of reading and hacking together solutions, it could definitely be a bitter experience to find out this is not going to work, thus a Developer/User could get frustrated and move on etc. I am not trying to be negative, about sharing this. I actually really love this project and its ideas and I want to improve it by contributing it but I have to share my frustrations and Potential Frustration for Future Developers.  Or make a strong argument/Use Case why the docs need changes or hopefully future implementations of GraphQL Scalar etc  

Anyways I find out we can build a one-to-many relation with this however this was limitation was referring to it was awkward and this is due for a future improvement but that's another Issue for another day to code Generators for schema relationships 

![image](https://user-images.githubusercontent.com/13157730/180127699-9d9d199e-4531-4f2a-afc0-ed31695f7f7c.png)

So I implement this one-to-many relationship

![image](https://user-images.githubusercontent.com/13157730/180127920-ca065f64-d822-44a3-a919-8c01caa52144.png)

And then I am stuck because I don't know how to call a one-to-many relationship in this syntax below. What is this syntax? is it graphQL yoga? is it grpahQL itself I don't really. I think I need to destructure my Photo[] from my One Schema, somehow I am referencing this old [forum post](https://community.redwoodjs.com/t/how-to-create-a-one-to-many-relationship/200/6) 2 years ago as a solutions could be in the docs possibly 

![image](https://user-images.githubusercontent.com/13157730/180128078-beabbc9d-282d-4f1e-9f47-711c09c7f2d1.png)

The only good example I see for one-to-many graphql call is 'Multiple Comments' and 'Creating a Comment Form' in Chapter 6. I just don't get it basically like how do I upload many photos in my many schema 'Photos' and maintain saving data in a different schema.

Like how does schema.prisma know this one-to-many relationship? How does SDLs know that this relationship is being maintain? since I 'yarn rw g sdl Photo --force --no-tests' since there was no testing?? I don't know I am stuck. 

How do you destructure one-to-many relationship on my web component? from api backend is the simple question. 

![image](https://user-images.githubusercontent.com/13157730/180129213-0699b771-6e21-49f9-859e-bff195b88b27.png)

 

### Motivation

Final thoughts or possible solutions in the tutorial the idea is that I write a schema.primsa and I scaffold my SDL, services, and components according to that schema. However, when a type is missing such as List/Arrays or Bytes that Prisma can access on its own and their is a supported GraphQL library for Scalar Types that match up to Prisma also why not have Bytes or Lists, in Redwood. 

RedwoodJS Homepage has this idea on the website its front page "When you start with a GraphQL backend server, you'll end up with the only backend you ever need. We call it: One API to rule them all."  but because we have these missing types and we cannot scaffold on these types, this promise on the website has left me thinking that promise is somewhat a little unfilled. Sorry for posting, or being critical, so often in the issues by the way. 

### Detailed proposal

I need to come up with a detail proposal, however I need more time to learn redwood and its functionality typscript etc I don't  know enough to implement this User Story. 

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by Gresliebear** [comment]
Nevermind I just found a solution to my problem I think its GraphQL 101 page this is very helpful

https://github.com/redwoodjs/redwood/pull/5800/commits/f5c36a903711d304bdd0684eb076e7d220bab1c1

**Comment by callingmedic911** [comment]
Thanks for following up @Gresliebear. I'm closing this issue but feel free to re-open it if you want to explore new ideas.
