### ISSUE TITLE
In Getting Dynamic tutorial section, `yarn rw db up`  returns error

### ISSUE THREAD

**Issue by sfat-llc** [redwoodjs/redwood#602]
Following tutorial up to the Getting Dynamic section, `yarn rw db up` returned this error:
```
Segmentation fault (core dumped)
Command failed with exit code 139.
Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Migrate database up... [failed]
→ Command failed with exit code 139: yarn prisma migrate up --experimental --create-db
Command failed with exit code 139: yarn prisma migrate up --experimental --create-db 
```

Running on Windows 10 WSL WLinux distro.

**Comment by peterp** [comment]
Could you try reinstalling your node_modules, but running
```terminal
cd <redwood>
rm -rf node_modules
yarn install
```

**Comment by sfat-llc** [comment]
A lot has changed since initial comment.
1) Reinstalled W10.
2) Updated Windows 10 to build 2004.
3) Moved from WSL1 to WSL2.
3) Installed new Pengwin distro upon WSL2.

Long story short - all works fine now.
