### ISSUE TITLE
Pages stemming from "yarn rw g scaffold <name>" are missing tests

### ISSUE THREAD

**Issue by AryanJ-NYC** [redwoodjs/redwood#603]
As a user, I expect pages created with `yarn rw g scaffold <name>` to be the same as `yarn rw g page <name>`

# Expected Result
Both `yarn rw g scaffold <name>` and `yarn rw g page <name>` generate `<Name>Page.test.js` files in their respective `<Name>Page` directories.

# Actual Result
Only `yarn rw g page <name>` generates test files.

# Steps to Recreate
1. `yarn create redwood-app ./redwoodblog`
2. `cd redwoodblog`
3. `y rw g scaffold userExample` and note the lack of test files in the generated pages.
4. `y rw g page hello` and note the test file in the generated page.

**Comment by cannikin** [comment]
Honestly the reason we don't have them is that we haven't fully figured out the best way to test cells, GraphQL and Prisma in an easy, opinionated, Redwood way. We would happily accept help in  figuring out these problems! 

We've got a GitHub Project that's tracking the various issues/PRs around testing: https://github.com/redwoodjs/redwood/projects/4 and a big discussion thread around testing: https://community.redwoodjs.com/t/testing-in-redwood/482/17

**Comment by thedavidprice** [comment]
See https://github.com/redwoodjs/redwood/issues/1149

The decision is to leave as is --> CRUD generated components tests would be redundant to purpose.
