### ISSUE TITLE
[Bug]: Upgrades don't update the executable in .yarn/release

### ISSUE THREAD

**Issue by Philzen** [redwoodjs/redwood#6040]
I was just revisiting the tutorial (which i can see has had some nice evolution and really useful additions) and wanted to upgrade the RedwoodJS stack as storybook just didn't want to start and i [recalled we had some problems with it back in 1.0.0](https://github.com/redwoodjs/redwood/issues/5054).

Unfortunately, running `yarn redwood upgrade -t v1.5.2` didn't run smooth:

```bash
  ✔ Checking latest version
  ✔ Updating your project package.json(s)
    ✔ Updating /home/phil/prog/testing/rwb-tutorial/package.json
    ✔ Updating /home/phil/prog/testing/rwb-tutorial/api/package.json
    ✔ Updating /home/phil/prog/testing/rwb-tutorial/web/package.json
  ✖ Running yarn install

    Refreshing the Prisma client
    De-duplicating dependencies
    One more thing..

Unable to verify yarn version.
```

I have no idea why it stopped there being unable to verify the yarn version – after manually running `yarn install` and being pleased to see storybook starting successfully re-running the upgrade command also finished smoothly :shrug: . 

However i did realize one thing: The binary in `.yarn/release/` is still on v3.2.0 – although it was bumped to v3.2.1 before the release of RedwoodJS 1.5.1. I've retried with `yarn redwood upgrade -t canary` and the `.cjs` still remains untouched.

As it has just [recently been updated to 3.2.2](https://github.com/redwoodjs/redwood/pull/6012) which is about to ship in RedwoodJS 2.2: Shouldn't there be a codemod or so to upgrade the yarn executable (and packageManager-entry in package.json) as well whenever it is upgraded in `create-redwood-app`?

**Comment by jtoar** [comment]
These are both valid concerns. The upgrade command needs some TLC. It's error messages aren't great, and you're right that when we update the CRWA yarn version, we don't do anything for existing redwood apps.

**Comment by Philzen** [comment]
### Suggestion

Instead of committing the yarn executable code into the repository (twice!), why not use `git submodules` and link to the yarn executable directly?

#### Advantages

* Avoid unnecessary repository growth (b/c updates are compiled, amount of reusable / compressable code is limited to git, thus the repository grows faster with every yarn update)
* Refer to a single source of truth, namely https://github.com/yarnpkg/berry instead of copying their project's compiled code into our own
* Clearer Separation Of Concerns (git is for code, not for compiled stuff, just like it is good practice not to check an NPM packages `dist`-folder into main)

*

**Comment by Tobbe** [comment]
I think the yarn people actually recommended us to commit the yarn bin. Dom will definitely know more. But I did also find this issue that sounds related https://github.com/yarnpkg/berry/issues/2216 It is from 2020 though, so might not be relevant anymore

**Comment by Philzen** [comment]
With the advent of Yarn 4 in RW 6 this requirement seen the best of it's days :wink: 

Closing.
