### ISSUE TITLE
[Bug?]: Error building context with Azure AD B2C authentication: JWT issuer invalid

### ISSUE THREAD

**Issue by iskandersierra** [redwoodjs/redwood#6041]
### What's not working?

When I call `logIn()` function from HomePage, and a JWT token is issued to call the graphql API (`redwood.currentUser`), the API prints an error saying that jwt issuer is invalid:

```
api | 00:05:13 🌲 incoming request POST xxx /graphql
api | 00:05:13 🐛 Parsing request to extract GraphQL parameters
api | 00:05:13 🐛 Processing GraphQL Parameters
api | (node:2184) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
api | (Use `node --trace-warnings ...` to show where the warning was created)
api | 00:05:13 🚨 graphql-server Error building context. Error: Exception in getAuthenticationContext: jwt issuer invalid. expected: https://<domainname>.b2clogin.com/<domainname>.onmicrosoft.com/v2.0/
api | 00:05:13 🌲 request completed 273ms
```

### How do we reproduce the bug?

I followed the documentations at: https://redwoodjs.com/docs/authentication and https://redwoodjs.com/docs/auth/azure over a recently created rw project, with only a `yarn rw g page Home /` to test login logout functions.

Added `.env` entries like:

```
AZURE_ACTIVE_DIRECTORY_CLIENT_ID=<Client ID from Azure>
AZURE_ACTIVE_DIRECTORY_AUTHORITY=https://<domainname>.b2clogin.com/<domainname>.onmicrosoft.com/B2C_1_signin
AZURE_ACTIVE_DIRECTORY_JWT_ISSUER=https://<domainname>.b2clogin.com/<domainname>.onmicrosoft.com/v2.0/
AZURE_ACTIVE_DIRECTORY_KNOWN_AUTHORITY=https://<domainname>.b2clogin.com
AZURE_ACTIVE_DIRECTORY_REDIRECT_URI=http://localhost:8910/login
AZURE_ACTIVE_DIRECTORY_LOGOUT_REDIRECT_URI=http://localhost:8910/logout
```

- The `JWT_ISSUER` variable matches the same value from the error reported from the API.
- I printed to console `process.env` and these variables are set
- In browser developer console, the call to `POST /graphql` is issued, with an `Authorization: Bearer ...` header

The problem is decoding the JWT token on API side, because a variable doesn't have an expected value, that it actually has.

### What's your environment? (If it applies)

```shell
System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 16.14.2 - ~\AppData\Local\Temp\xfs-4a0386e0\node.CMD
    Yarn: 3.2.1 - ~\AppData\Local\Temp\xfs-4a0386e0\yarn.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.49)
  npmPackages:
    @redwoodjs/core: 2.1.0 => 2.1.0
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by Tobbe** [comment]
Hi @iskandersierra 

I've never used Azure before, but I spent some time this morning trying to set it up. I'm still not done, but I think your JWT_ISSUER might be wrong.

You said you have 
```
AZURE_ACTIVE_DIRECTORY_JWT_ISSUER=https://<domainname>.b2clogin.com/<domainname>.onmicrosoft.com/v2.0/
```

From what I'm reading it should be
```
AZURE_ACTIVE_DIRECTORY_JWT_ISSUER=https://<domainname>.b2clogin.com/<domainid>/v2.0/
```

So, for example

```
AZURE_ACTIVE_DIRECTORY_JWT_ISSUER=https://rwauthtestb2c.b2clogin.com/775527ef-8a37-4307-8b3d-cc311f58d922/v2.0/
```

I'll continue trying to set everything up on my end, but if you could try with "domain id" instead of "domain name" (and no ".onmicrosoft.com"), and report back as well that would be great. Thanks!

**Comment by Tobbe** [comment]
I got started on a PR for updating the docs https://github.com/redwoodjs/redwood/pull/6086 but I'll leave it as a draft until I've verified that I can get it working on my own.

Here's a preview of the updated docs https://deploy-preview-6086--redwoodjs-docs.netlify.app/docs/canary/auth/azure

**Comment by Tobbe** [comment]
I've confirmed it working. I can login using Azure B2C.

I'll try to get those updated docs merged, and then I'll close this issue

**Comment by iskandersierra** [comment]
Perfect! @Tobbe . I'll check that out this weekend and confirm if it's working for me too. Thanks!

**Comment by iskandersierra** [comment]
Confirmed. I just tested it and it worked using the Directory/Tenant Id (GUID) in the second placeholder of the JWT_ISSUER
