### ISSUE TITLE
[Bug?]: Windows Bug Contributing Issues with project sync

### ISSUE THREAD

**Issue by Gresliebear** [redwoodjs/redwood#6055]
### What's not working?

I am stuck on development/contributing  when I make changes to redwood framework RedwoodIssues https://github.com/Gresliebear/redwoodIssues/tree/redwoodIssues and run 
`yarn cross-env RWFW_PATH=E:\RedWoodIssues\redwoodIssues\ rwfw project:sync`

 it completely overwrite my changes that I just wrote in the framework and it doesn't put the changes into the test-project.

### How do we reproduce the bug?

1. git clone 

`git clone https://github.com/Gresliebear/redwoodIssues.git`

2.  Make a test directory 

`mkdir testdir`

3. yarn build the test-project

`yarn build:test-project E:\RedWoodIssues\testdir`

4. cd into the test-project

5. make changes now or after the rwfw call 

6. now sync the project

`yarn cross-env RWFW_PATH=E:\RedWoodIssues\redwoodIssues\ rwfw project:sync`

So if made the changes to framework it gets deleted
![broke](https://user-images.githubusercontent.com/13157730/181165120-f1045b4b-9d2e-4790-a9a0-73d65f458e5c.gif)

the sync doesn't pick up?
![broke2](https://user-images.githubusercontent.com/13157730/181165327-4dfe9d88-ecd8-4c67-b4db-03eac35eab4b.gif)

### What's your environment? (If it applies)

```shell
System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 16.14.0 - ~\AppData\Local\Temp\xfs-4e2eb50b\node.CMD
    Yarn: 3.2.1 - ~\AppData\Local\Temp\xfs-4e2eb50b\yarn.CMD
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.71)
  npmPackages:
    @redwoodjs/core: ^2.1.2-canary.147 => 2.0.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by dac09** [comment]
Hi @Gresliebear - thanks for raising the issue, and for trying to contribute!

I think perhaps you're changing the code in your test-project under `node_modules/@redwoodjs/xxx` ? In that case this is expected behaviour that it gets overwritten.

What the expected flow is:
- run `yarn rwfw project:sync` in your _project_ - not in the framework
- make changes to the framework _source_ - in your case would be in E:\RedWoodIssues
- `rwfw` will automatically build and copy over changes from the framework, and then into your test project you'll be able to try your changes

I would also suggest that you try creating the test project outside your framework directory so e.g. `yarn build:test-project E:\redwood-test-project`.

---

If all of this feels complciated, you may find it easier to contribute using Gitpod (https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md#cloud-developer-environment)

**Comment by Gresliebear** [comment]
> 
the expected behavior is not happening. Because I checked before posting the issue in this screen shot and the path for the framework is` E:\RedWoodIssues\redwoodIssues`

![image](https://user-images.githubusercontent.com/13157730/181378325-79b0aed0-7899-4d93-9273-2e3f60f7f9d2.png)

Then the path for the test-project is `PS E:\RedWoodIssues\redwoodblog> `

![image](https://user-images.githubusercontent.com/13157730/181378910-5c1ae1b4-70b4-4b6c-b9e1-1d1f075ad51c.png)

I ran `yarn rwfw project:sync` in my project and not in the framework before I posted to make sure and I tried again just now its over writing my framework directory.

----RedwoodIssues
   -- RedwoodIssues (Framework)
-- Folder A
-- Folder B
   -- testdir
     ------test-project (project)

I suspect its going be solved with. `I would also suggest that you try creating the test project outside your framework directory so e.g. yarn build:test-project E:\redwood-test-project.` but technically its outside of the framework already. right? 

I have another branch RedwoodWindows for React 18 upgrade and all my changes disappeared! disastrous!! on my part didn't git push.

I will try this last suggestions give me sometime

**Comment by Gresliebear** [comment]
> Hi @Gresliebear - thanks for raising the issue, and for trying to contribute!
> 
> I think perhaps you're changing the code in your test-project under `node_modules/@redwoodjs/xxx` ? In that case this is expected behaviour that it gets overwritten.
> 
> What the expected flow is:
> 
> * run `yarn rwfw project:sync` in your _project_ - not in the framework
> * make changes to the framework _source_ - in your case would be in E:\RedWoodIssues
> * `rwfw` will automatically build and copy over changes from the framework, and then into your test project you'll be able to try your changes
> 
> I would also suggest that you try creating the test project outside your framework directory so e.g. `yarn build:test-project E:\redwood-test-project`.
> 
> If all of this feels complicated, you may find it easier to contribute using Gitpod (https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md#cloud-developer-environment) - where the test project is setup for you, and all you'll need to do is run `rwfw project:sync` if you want to keep your changes in sync.

I tried it and didn't work

**Comment by dac09** [comment]
I still think there’s some wires crossed here. As we use rwfw every day, a large bug like this should be something we would notice - admittedly none of the core team use Windows on a day to day basis, but our CI smoke tests do something similar.  

I’m not sure what the gif is showing - are you making changes inside your node modules that gets overwritten? The idea isn’t that changes you make in your project’s node_modules get synced backed to the framework, but instead your project will receive the modified framework if you make changes to the framework source - I.e. the code the lives in this GitHub repository.  

I’ll dig up a contributing session YouTube video tomorrow!

**Comment by dac09** [comment]
Also is there a chance you’re modifying code in the “dist” folders?

**Comment by Gresliebear** [comment]
> Also is there a chance you’re modifying code in the “dist” folders? The dist folder is for the output of the build process, your changes should go in the “src” folders.

yes

**Comment by Gresliebear** [comment]
@dac09  it works now I was editing inside of dist facepalm

**Comment by Gresliebear** [comment]
@dac09  Thank you Dac
