### ISSUE TITLE
[Bug]: jest.config.ts not supported

### ISSUE THREAD

**Issue by richard-stafflink** [redwoodjs/redwood#6063]
### What's not working?

I can not use a `api/jest.config.ts` (TS version of the Jest config) as the name check in RW is hard coded:
https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/test.js#L37

According to the Jest [docos](https://jestjs.io/docs/configuration) `jest.config.ts` is allowed.

### How do we reproduce the bug?

Rename `jest.config.js` -> `jest.config.ts`

```bash
yarn rw test api
```

> Error: Missing Jest config file api/jest.config.js
> To add this file, run `npx @redwoodjs/codemods update-jest-config`

### What's your environment? (If it applies)

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.15.1 - /tmp/xfs-298f0c87/node
    Yarn: 3.2.2 - /tmp/xfs-298f0c87/yarn
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 103.0
  npmPackages:
    @redwoodjs/core: 1.2.1 => 1.2.1
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by dac09** [comment]
Hello @richard-stafflink - thanks for raising the issue.

To be clearer, is the problem that you can't run the codemod? Or that when you run jest it doesn't use your TS jest.config file?

**Comment by richard-stafflink** [comment]
Thanks for the quick turnaround - much appreciated :+1:
