### ISSUE TITLE
[Bug?]: The section Using the Example Repo has a redundant command 

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood#6075]
### What's not working?

The section [Using the Example Repo](https://redwoodjs.com/docs/tutorial/intermission#using-the-example-repo-recommended) lists the several commands that need to be executed in order to build this app:

```
git clone https://github.com/redwoodjs/redwood-tutorial
cd redwood-tutorial
yarn install
yarn rw prisma migrate dev
yarn rw prisma db seed
yarn rw g secret
```

The line `yarn rw prisma db seed` should be removed since the previous command (`yarn rw prisma migrate dev`) does the seeding as it last action:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/2712405/181573357-19be2f22-1f45-49fc-bd31-fea451413b5b.png">

### How do we reproduce the bug?

Execute the commands listed in the above section "What's not working?"

Note that the command `yarn rw prisma migrate dev` "internally" executes the command `yarn rw prisma db seed`. So, I think that the command `yarn rw prisma db seed` is superfluous and should be deleted. 

### What's your environment? (If it applies)

```shell
nik$ yarn rw info

  System:
    OS: macOS 12.4
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /private/var/folders/y3/n2p741pj7vq9ckj9jrmlbp6m0000gn/T/xfs-09bc2477/node
    Yarn: 3.2.1 - /private/var/folders/y3/n2p741pj7vq9ckj9jrmlbp6m0000gn/T/xfs-09bc2477/yarn
  Databases:
    SQLite: 3.37.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 102.0.1
    Safari: 15.5
  npmPackages:
    @redwoodjs/core: 2.2.0 => 2.2.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by noire-munich** [comment]
@adriatic nicely spotted!
Indeed, `yarn rw prisma migrate dev` seeds at the end. Not sure why we've kept both, probably it's old doc that needs updating.

@dac09 can you confirm this is only about updating the docs?
