### ISSUE TITLE
[Bug?]: The type `ArticlesQuery` does not exist in types/grapql

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood#6078]
### What's not working?

The tutorial section [Getting Dynamic](https://redwoodjs.com/docs/tutorial/chapter2/getting-dynamic) defines the code for the file web/src/components/ArticlesCell/ArticlesCell.tsx. TS version as:

```
import type { ArticlesQuery } from 'types/graphql'
import type { CellSuccessProps, CellFailureProps } from '@redwoodjs/web'

export const QUERY = gql`
  query ArticlesQuery {
    posts {
      id
    }
  }
`
```

However the `ArticlesQuery` type does not exist in `types/graphql` as shown below:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/2712405/181671455-e3b7bfed-4a9e-44ef-9f2a-3c966adddcad.png">

Note that the file `types/graphql.d.ts` does not compile and this is the real problem IMHO

### How do we reproduce the bug?

Reproducing the problem requires typing the whole tutorial (the TypeScript) version up to (including) section https://redwoodjs.com/docs/tutorial/chapter2/cells#our-first-cell as this version does not exist anywhere (to the best of my knowledge).

A better alternative is to verify that `graphql.d.ts` does not export type `ArticlesQuery`. 

Vscode claims that there are two additional problems in the `graphql.d.ts` file, as shown below

<img width="488" alt="image" src="https://user-images.githubusercontent.com/2712405/181672257-233243a5-4032-4eb9-8772-ee1c6ac2174c.png">

Problem 1
<img width="626" alt="image" src="https://user-images.githubusercontent.com/2712405/181672624-5b84d27b-5936-47e1-8db1-23f3f2c3c279.png">

Problem 2
<img width="626" alt="image" src="https://user-images.githubusercontent.com/2712405/181672719-999e729f-c89b-4844-9b15-09308b46b0a0.png">

### What's your environment? (If it applies)

```shell
nik$ yarn rw info

  System:
    OS: macOS 12.4
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /private/var/folders/y3/n2p741pj7vq9ckj9jrmlbp6m0000gn/T/xfs-ed49c479/node
    Yarn: 3.2.1 - /private/var/folders/y3/n2p741pj7vq9ckj9jrmlbp6m0000gn/T/xfs-ed49c479/yarn
  Databases:
    SQLite: 3.37.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 102.0.1
    Safari: 15.5
  npmPackages:
    @redwoodjs/core: 2.2.0 => 2.2.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by noire-munich** [comment]
Thanks @adriatic , we are aware of issues in typescript tutorial so any reporting is useful to us 👍🏻 .

@jtoar I'm not sure how to reassign this, so I'll pass it up to you.

**Comment by adriatic** [comment]
@noire-munich is there some workaround / temporary re-declarations to get me going? It is hard to believe that typescript development is dead at this moment?

**Comment by adriatic** [comment]
Since my original write up I found a lot easier proof of this bug. 

type `yarn create redwood-app --ts ./redwood-stripe` to the terminal and use VSCode to view the just generated application. Observe that the generated file `graphql.d.ts` lacks the definition of the `prisma` namespace. 

This of course has consequences for each and every Redwood TypeScript application

**Comment by whaleAPI** [comment]
I experienced the same thing and in chapter 7 when adding roles: true in the getCurrentUser function I get a type error
![Screenshot_3](https://user-images.githubusercontent.com/95057356/182530113-08d2df3c-1b6f-4ec7-9acf-79410e648c1a.png)

**Comment by dac09** [comment]
1. `type ArticlesQuery does not exist`

You just have have to run `yarn rw g types` or have your dev server running. See more info on generating types here: https://redwoodjs.com/docs/typescript#auto-generated-types 

This is mentioned in the tutorial a few lines above. 
<img width="954" alt="Screenshot 2022-08-03 at 13 50 00" src="https://user-images.githubusercontent.com/1521877/182611966-b8918395-8bfc-40bf-9fd2-19f55513023a.png">


Any thoughts on how we could make this more obvious for you within the tutorial? 


> This of course has consequences for each and every Redwood TypeScript application

I don't believe the Prisma error actually has _any_ consequences on Redwood applications, it's a bug in the generated types but actually doesn't break anything within your application. This is being tracked in #6096, and will close this issue as duplicate.
