### ISSUE TITLE
[Bug]: `yarn rw lint --fix` does not fix non-source files

### ISSUE THREAD

**Issue by Philzen** [redwoodjs/redwood#6094]
After having recently upgraded our project to 2.x, i just opened `web/config/storybook.preview.js` and found those imports not yet reordered, giving a couple of red squiggles.

Our whole project is ts-based, so i'm not sure if the fix command only looked at ts files, or whether those folders are just ignored in the process (while i believe it would be practical to have them included).

**Comment by Philzen** [comment]
Just discovered our custom seed script in the `scripts/` folder (which is a `.ts`) also was not updated in the process, so i guess it's down to folder configuration.

**Comment by dac09** [comment]
@Philzen - this is extremely unlikely to be on our priority list, just FYI. 

Something to note - if you have prettier configured in your editor (which is shipped in the template) - this is a total non-issue.

**Comment by Philzen** [comment]
@dac09 Thanks & no worries … no problem here, just noticed it and thought it may be noteworthy.
