### ISSUE TITLE
[RFC]: Support Sign Up with Additional Metadata for Supabase 

### ISSUE THREAD

**Issue by asfiowilma** [redwoodjs/redwood#6146]
### Summary

Supabase supports sign up with additional user metadata, but redwood's useAuth's signUp function does not support this yet. 

### Motivation

I needed to have a trigger that will create a UserProfile record when a new profile signs up to my app. Several suggestions across the internet suggested that I use postgres triggers and functions. I'm using supabase for my auth and database purposes, and I found this [github issue comment](https://github.com/supabase/supabase/discussions/3491#discussioncomment-1703953) that tells me I can utilize additional metadata on sign up. 
But right now, there's no way to do it this way without a workaround. 

### Detailed proposal

It's small change to make. I've tried it on my local env and it works nicely. 

```typescript
// packages/auth/src/authClients/supabase.ts

export interface AuthClientSupabase extends AuthClient {
   // ...
   signup(options: {
    // ...
    data?: Record<string, unknown>
  }): Promise<{
    // ...
  }>
}

export const supabase = (client: Supabase): AuthClientSupabase => {
  return {
    // ...
    signup: async ({ email, password, phone, redirectTo, data }) => {
      return await client.auth.signUp(
        { email, password, phone },
        { redirectTo, data }
      )
    },
  // ...
  }
}
```

## Example Usage 

```ts
const { signUp } = useAuth()

const onSubmit = async (data) => {
    const { email, password, phone, ...rest } = data
    const response = await signUp({ email, password, phone, data: rest })
}
```

This way, the user metadata would be accessible by supabase's postgres functions. 

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by dthyresson** [comment]
Hi @asfiowilma Thanks for raising this issue?

Would you like to work on a PR to update the Supabase client to their latest gotrue-js?

See: https://github.com/supabase/gotrue-js/blob/9bc36431423434cf839fd6e00871672e1d2d9b5c/src/GoTrueClient.ts#L130

It could pass `data` like you said, but also the `recaptcha` for sign in and up.

I'd be happy to review the PR and then you can also test and update it in the [Redwood Auth playground](https://github.com/redwoodjs/playground-auth).

**Comment by asfiowilma** [comment]
Sure thing~ I'd love to work on this. May I also update the [How to > Supabase Auth](https://redwoodjs.com/docs/how-to/supabase-auth) docs as well, or should I submit a different PR for that?

**Comment by dthyresson** [comment]
Great question. If you feel the docs help explain and “go with” the code changes, then it’s often best to include in same PR. That way can better understand The change and when the PR is merged it can go in one set of changes. But I’d there isn’t total overlap then a separate one is often better.

**Comment by Tobbe** [comment]
Auth updates 😬 

I'm working on a huge auth rewrite over here: https://github.com/redwoodjs/redwood/pull/5985
I'd rather we wait with other auth updates until that one is merged.

**Comment by dthyresson** [comment]
@asfiowilma Auth for Supabase v2 has been merged in after the auth provider refactor for v2.

Your issues re: adding metadata is now possible and tests have been added for that use case in https://github.com/redwoodjs/redwood/pull/7765
