### ISSUE TITLE
[Bug?]: Running yarn create redwood-app --ts ./redwoodblog crashes

### ISSUE THREAD

**Issue by Christian24** [redwoodjs/redwood#6148]
### What's not working?

Hello,

I was just trying to run redwood for the first time. Running `yarn create redwood-app --ts ./redwoodblog` as suggested by the tutorial and it errors with: 

````
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "14.20.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
````

Not sure what's wrong, not sure this is widespread, probably not, but I don't really know how to proceed on this. 

Thanks in advance. 

### How do we reproduce the bug?

Run `yarn create redwood-app --ts ./redwoodblog`. 

### What's your environment? (If it applies)

```shell
Sytem: Mac 12.1
Yarn: 1.22.10
Node: v14.20.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by pantheredeye** [comment]
[This answer, on a previous issue with the exact same error message,](https://github.com/redwoodjs/redwood/issues/227#issuecomment-602037860) suggest the issue may be a global package conflict installed with a previous version of node.

> Just to chime in; ***the cause of the errors is because there are global modules installed which are incompatible with your current node version.*** Running `yarn create` is equivalent to `yarn global add`, which means that it validates the globally installed packages.

> For example; use an old version of node and install a module that targets older node versions and then switch to a newer version and do a global install. This will fail due to incompatible engines, specified by the module.

**Comment by Christian24** [comment]
Oh I am so sorry. For whatever reason when I searched for preexisting issues, this one did not come up. Thank you so much. That fixed it. Sorry again.

**Comment by jpollone** [comment]
Unfortunately I need to use 4 different versions of node, but I found success with this combo on my M1 MacBook Pro running this configuration. 

```
nvm install 14.20.0
npm install --global yarn
```
`node -v`
14.20.0

`yarn -v`
1.22.19

**Comment by eltonstewart** [comment]
just to confirm that the removal of global packages and ensuring I was using nvm installations and then using v14.20.0 worked.

There are lots of warnings but it worked.

`[3/4] 🔗  Linking dependencies...
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/typescript-react-apollo@3.3.2" has unmet peer dependency "graphql-tag@^2.0.0".
warning "create-redwood-app > @redwoodjs/internal > babel-plugin-graphql-tag@3.3.0" has unmet peer dependency "graphql-tag@^2.10.1".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/depth-limit@1.6.0" has unmet peer dependency "@envelop/core@^2.4.0".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/disable-introspection@3.4.0" has unmet peer dependency "@envelop/core@^2.4.0".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/filter-operation-type@3.4.0" has unmet peer dependency "@envelop/core@^2.4.0".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/parser-cache@4.5.0" has unmet peer dependency "@envelop/core@^2.4.0".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/validation-cache@4.5.0" has unmet peer dependency "@envelop/core@^2.4.0".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > cosmiconfig-typescript-loader@3.1.1" has unmet peer dependency "@types/node@*".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > cosmiconfig-typescript-loader@3.1.1" has unmet peer dependency "typescript@>=3".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > ts-node@10.9.1" has unmet peer dependency "typescript@>=2.7".`

Macbook M1
MacOS 12.4
NVM
Yarn: 1.22.19
Node: 14.20.0
/.nvm/versions/node/v14.20.0/bin/yarn 
/.nvm/versions/node/v14.20.0/bin/node

**NOTE It seems that node v16.6.0 doesn't work.**
