### ISSUE TITLE
Integrate with The Serverless Framework

### ISSUE THREAD

**Issue by slavakurilyak** [redwoodjs/redwood#615]
I would like to deploy Redwood on cloud providers such as Microsoft Azure, Google Cloud Platform, Apache OpenWhisk, Cloudflare Workers, or a Kubernetes-based solution like Kubeless.

Consider integrating Redwood with [The Serverless Framework](https://www.serverless.com/) to accomplish this.

**Comment by peterp** [comment]
@slavakurilyak the last time I checked out the serverless framework, which might have been ~1.5 years ago they had very good integration for AWS Lambda functions, but not complete support for the other providers.

Do you know if that situation has changed?

From what I remember the configurations scripts did not fully support Google Cloud, it would be interesting for me to see what the differences are between configuration and commands for deploying to AWS Lambda vs Azure.

**Comment by slavakurilyak** [comment]
@peterp The Serverless Framework has [expanded its provider list](https://www.serverless.com/framework/docs/providers/).

**Comment by Jaikant** [comment]
@slavakurilyak Related post https://github.com/redwoodjs/redwood/issues/431

**Comment by andrew-hwahin** [comment]
+1 for Azure 🙏

**Comment by mnapoli** [comment]
Should this issue be closed since the v1 release integrates with Serverless Framework?

**Comment by jtoar** [comment]
Wow this is an old one. @mnapoli Good call, thanks!
