### ISSUE TITLE
[Docs]: Chapter 2 Getting Dynamic cannot create post

### ISSUE THREAD

**Issue by QQCif** [redwoodjs/redwood#6198]
### Summary and description

Hello
I'm following alone the tutorial. In Chapter 2 Getting Dynamic, after running `yarn rw g scaffold post`, in generated `posts.sdl.ts`, `createAt` is marked as non-nullable, causing error saving any post. I have to remove that line to continue. 

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jtoar** [comment]
Hey @QQCif! Do your input mutations look like the following? These are just the generated ones (from `yarn rw g scaffold`):

```graphql
  input CreatePostInput {
    title: String!
    body: String!
  }

  input UpdatePostInput {
    title: String
    body: String
  }
```

Redwood doesn't generate fields in input types for Prisma fields with defaults, so createdAt shouldn't be necessary for creating or updating a post.
