### ISSUE TITLE
[RFC]: New How To: Design Driven Full-Stack

### ISSUE THREAD

**Issue by pantheredeye** [redwoodjs/redwood#6207]
### Summary and description

# Motivation

For some reason, I naturally fall into the camp of structuring my data first and then getting into design. When I came to Redwood, the elegance of Prisma models led me to map out my entire schema before working on any components. This may still be a valid way to work for some uses-cases. However, after watching David's videos, I realized that I was leaving things on the table that could improve my workflow. Even though I had been through the tutorial, I realized had not really shifted my mindset to designing in isolation. I was not using mock data well, and I was sort of 'frozen' into the data model that I had built out in my schema file. I had not truly designed in isolation. 

When I realized this, I felt the need for a cheat-sheet, or checklist. I wanted a quick overview of the process without having to reference the videos. While this How-To doesn't exactly provide a check-list, this is my first stab at such a resource.

Anyway, I have been working this up and wanted to get comments from you all before putting much more effort in. I took a lot of concepts and some verbiage from David's videos. I can see potential for improvements from top-to-bottom across this thing. I don't think the "Basic Flow" section really does justice to the process. The sections and section headers could be better organized or named. The resources are thin; I would like more mock data/query structure resources.... 

Any comments/suggestions/thoughts? Is this something to continue with? 

---

# Design Driven Full-Stack Workflow

If you have completed the Tutorial, especially [Chapters 5 and 6](https://redwoodjs.com/docs/tutorial/chapter5/storybook), you have experienced Redwood's preferred development flow. Generate a component, design it, and update your schema as necessary. Redwood calls this workflow 'Design Driven Full-Stack (DDFS?).' This is made easy by Redwood's combination of Generators (pages/cells/components/etc.), Storybook, Prisma, and all of the other goodies woven into Redwood. The keys to this process are baked into Redwood, but it may take time to build the habit of designing in isolation. Hence this resource.

Use this How-To as a shortcut that outlines the general process and provides related resources. 

### Why

DDFS helps get you designing, completing, and shipping designs, faster. Redwood provides the architecture, processes and conventions to help keep you away from back-end/database/api/etc. configuration or setup during the design process. This keeps you moving forward with the design and development of your product. Finally, the Full-Stack portion allows you the freedom to reach into all parts of the application if you ever need to.

Redwood generators provide boilerplate and conventions that are repeatable and will become more familiar the more you work with them. Cells, in particular, are a very important part of the DDFS workflow. Cells provide you with a graphql query, state management options (loading, failure, success, etc.), and cells kick start your data structure by providing a mock data file which you can craft to fit your specific component's data needs. Combined, these parts allow you to design entire components in 'isolation.' This means you do not have to leave the frontend to go work on the backend while designing.

In isolation, you can design and update your mock data file repeatedly until your design is finalized. Then, you can use the resulting data structure to go and update the backend/database/api/etc., as needed. 

### The Goal

Ship features frequently, continually, and as soon as possible. 

## Assumptions

You are familiar with Redwood cli commands, Prisma schema, and Storybook. 

## Gotchas

Seeing: `Error: Unexpected token < in JSON at position 0` on your generated page? Try going to your terminal and restarting the Storybook server. When Pages contain Mock data from a Cell [they do not hot-reload.](https://github.com/redwoodjs/redwood/issues/4717)

## Basic Design Flow

The general concept is to leverage Storybook and its mock data feature to design, code and test components in isolation. Once design is completed, any fields from the mock data structure can easily be mirrored in the Prisma schema file. 

The basic flow, using a [cell](https://redwoodjs.com/docs/cells), is below. 

*Steps 5, 6 & 7 are what DDFS truly revolves around.*

1) [Start Storybook](https://redwoodjs.com/docs/storybook) `yarn rw sb`
2) [Generate a Page](https://redwoodjs.com/docs/tutorial/chapter1/first-page) `yarn rw g page <pageName>`
3) [Generate a Cell](https://redwoodjs.com/docs/cells) `yarn rw g cell <cellName>`:
    * ✔ Writing `./web/src/components/<cellName>/<cellName>.mock.js`...
    * ✔ Writing `./web/src/components/<cellName>/<cellName>.stories.js`...
    * ✔ Writing `./web/src/components/<cellName>/<cellName>.test.js`...
    * ✔ Writing `./web/src/components/<cellName>/<cellName>.js`...
4) [Import the Cell component into the Page](https://redwoodjs.com/docs/tutorial/chapter2/cells#our-first-cell)
5) [***Create/Edit Mock Data***](https://redwoodjs.com/docs/mocking-graphql-requests) in `<cellName>.mock.js|ts`
6) [***Update the Cell Query***](https://redwoodjs.com/docs/mocking-graphql-requests#mocking-a-cells-query) in `<cellName>.js|ts`
7) [***Design Layout***](https://redwoodjs.com/docs/tutorial/chapter6/the-redwood-way)
   * Generate a Component `yarn rw g component <componentName>`
     * Import Cell Mock File into component 
8) Repeat as necessary until finalized
9) [Update `schema.prisma`](https://redwoodjs.com/docs/tutorial/chapter6/comments-schema) with Mock Data Structure

*Step 5: It is suggested to let the Cell simply handle the data fetching/state and then pass the data to subcomponents which handle the layout and design.

See DDFS Workflow Resources below for videos outlining this workflow.

# Resources

## DDFS Workflow Resources

[Design-Driven Full-Stack: GitNation 2021](https://portal.gitnation.org/contents/design-driven-full-stack-an-end-to-end-dev-workflow-that-scales) Skip to 13:40 to match Step 2.

[Design-Driven Full-Stack: YouTube Demo](https://youtu.be/dWWFZV6ML3k) Skip to [10:50 to match Step 2](https://www.youtube.com/watch?v=dWWFZV6ML3k&t=650s).

[What is Design-driven Full-stack Development?](https://community.redwoodjs.com/t/what-is-design-driven-full-stack-development/2966)

## Mock Data Resources

Mock data is essentially what you expect to be returned from the GraphQL queries. This becomes the Props that your component needs. Redwood 

[RW How-To: Mocking GraphQL in Storybook](https://redwoodjs.com/docs/how-to/mocking-graphql-in-storybook)

[RW Tutorial: Our First Cell](https://redwoodjs.com/docs/tutorial/chapter2/cells#our-first-cell)

## Storybook Resources

[Advanced RW Storybook Integration Demo](https://youtu.be/tHW7Gn6WCSc)

[Storybook Demo with Redwood](https://www.youtube.com/watch?v=zYm1a39Lpgs)

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by ehowey** [comment]
Hey just a note to say I appreciated your write up and perspectives here - made me reconsider how I would/should do things.

I would probably have done what you mentioned at the start with a full Prisma schema deep dive...

**Comment by pantheredeye** [comment]
@ehowey Thanks for the note! I am curious to know what led you to it - meaning, a keyword search or something, or were you just browsing the issues?

Anyway, thanks again for the affirmation. If you have any critique or suggestions for the how-to itself, please shoot them over also 😅. Glancing over it again, a few days removed, I do not like the way I have put it together. But, like I said, it was a start! (David's videos are the better resource, imo 😄)

**Comment by ehowey** [comment]
Just browsing issues - I sometimes take a scroll though issues just to see what is shaking.  I have been toying around with a SaaS idea on/off based on time I have so keep an eye on where things are at with RWJS.

**Comment by pantheredeye** [comment]
@virtuoushub Thanks for the note! I saw it last night. It made me sit down and work through it some more. I had actually rewritten almost the entire thing a few weeks ago. I need to stick a pin in it. I am happy with this version, it does a nice job of immediately explaining the benefits and providing a workflow template. However, this version lacks any code in the design section. Any ideas there are welcome, if it needs changing, addition, etc. or if it can stay as-is.

Also, the second part of the tutorial says all of this this in much more detail and more correctness. I have some heartburn submitting this as a potential alternate, but that is not the intention. This was intended foremost as a boiled down version of the workflow as a sort of design-time checklist. As mentioned in the initial RFC post, the intent is to help you quickly focus on the main steps of the process instead of taking time to look back through the tutorial or david's videos.

FWIW, here is the updated version:

# Fullstack Driven Design

Design in isolation, leveraging Redwood's integration of Storybook with mock data capabilities.
Free your design process from the restraint of pre-existing data structures.

## The End, at the Beginning. 

### The Reason

Ship features frequently, continually, and as soon as possible.
### The Goal

Incorporate the fullstack driven design process into your workflow.
Design front-end components in isolation, then copy the constructed data models to the api side for setup and integration.

This workflow results in, essentially, a two-for-one:
1) Fully designed, functional component(s) 
2) Data model(s) ready for your prisma schema

* _Also_: [Tests can be developed during this process]([https://redwoodjs.com/docs/tutorial/chapter5/testing)

 ### The (Condensed) Steps
 
 The process is described more fully in the sections below. 
 More mature workflows may differ distinctly than the below. 
 In-fact, the [Tutorial, Part II](https://redwoodjs.com/docs/tutorial/intermission) differs from below by taking a slightly longer design path.
 
 However, the main steps revolve around this workflow:
 1) Start Storybook `yarn rw sb`
 2) Generate a cell `yarn rw g cell item` and shape your initial Storybook mock data structure in `itemCell.mock.ts`
 3) Generate a component `yarn rw g component` to import into the cell [\*]
 4) Design and develop your component using the mock data passed from the cell
 5) ***Iterate*** on both the data structure and component design
 
 6) _When Finished_: Convert your data structure into prisma models

[\*] A recommended best practice is to avoid design work in the cell itself. 
Do this by importing a component into the cell and designing on the component.
Pass the props from the cell to the component like normal react components.

### Assumptions

You are familiar with Redwood cli commands, Prisma schema, and Storybook. 

### Gotchas

Seeing: `Error: Unexpected token < in JSON at position 0` on your generated page? Try going to your terminal and restarting the Storybook server. When Pages contain Mock data from a Cell [they do not hot-reload.](https://github.com/redwoodjs/redwood/issues/4717)

### Other Notes

This basic workflow is explained in much more detail in the second part of the [Tutorial, starting at Chapter 5](https://redwoodjs.com/docs/tutorial/chapter5/storybook). 
This document was foremost intended as a process checklist and morphed into another explainer.

While this is a powerful design process, it does not complete everything.
There will still be a need for services, scripts, directives, and other backend functions to be developed.

## Why design this way?

A primary focus of startups is often product design.
Developing, shipping and iterating on feature design is important, especially for young applications.
This approach speeds up this process for small teams. 
Designing components around data structures or API's is not a new concept. 
Teams have been successfully working this way for years.
Fullstack Driven Design tweaks this approach slightly by putting mock data files between your design and the api layer.

Using mock data allows you to more 'freely' design your components, without being bound to the 'contract' of an existing api structure or data model. 
This freedom allows you to iterate on your design without worrying about fitting the design to the data structure. 
You are free to shape, and reshape, your data structure and display logic while your design changes.
When you are done, you can take the data structure to your prisma schema file and connect everything together.

As your team and application mature, this approach may not work for all situations.
Also see: Atomic Design Structure

## Start with Mock Data

Start by creating some mock data in your `<name>Cell.mock.ts` file. 
Once an initial data structure is in place, you can move forward and design against this data.
At times, your workflow may have you constantly weaving between the mock data file and the component files.
It is perfectly OK to do so. 
The fact that you can, and the ease at which you can, is why this process is so powerful.

Redwood provides mock data and Storybook integration out of the box.
The mock data file represents the data structure that would be returned from your GraphQL query.
However, it is completely separate from the api backend.
This converts api design process from a **pre-design requirement** into a _**design-time**_ process.
This is a solid first step in the Fullstack Driven Design process.

Getting into this step first does two things. 

> 1) _This is a pseudo schema modeling step._ 
> Schema modeling is sometimes a natural first step for outlining application data needs.
> However, design is often an iterative process.
> It is important to develop a loose idea of your overall data needs/structure.
> That general structure will be important during design.
> As you design your component, you may realize that you want to reshape your data. 
> Reshaping mock data structure is easier than modifying a model with existing sdls, and services that will need to be regenerated.

> 2) _This method keeps your data structure flexible._
> When designing a component layout, it is liberating to be free of a strict data structure.
> If you are working from the backend to the frontend, then your schema and data structure have already been developed.
> This may limit your options or give you tunnel vision.
> Being flexible allows you to mold the data structure as you iterate on your design.

### Mock Data Structure

Creating your mock data structure is very similar to creating a prisma schema model.
However, instead of defining fields and types, you define fields and sample values.
The mock data structure resembles the JSON response you would expect from a GraphQL query.
Unlike the `Field: Type` structure of prisma models, you create the `field: property` or `field: 'value'` structure of objects.
You add actual values so that your components will be able to use and/or display the data in Storybook.

This process can be a little slow, since you need to mock out an initial data structure and possible return values.
Integers and strings are simple enough to mock.
Dates are complicated more complicated to remember the exact format that Redwood expects. 
Using a fake data generator such as copycat or faker can make mocking some values easier, but may not be worth the extra steps of setup and use.

Redwood generates mock data files when cells are generated.
The mock data is then provided as a property of the cell exports.

* Generate a cell: `yarn rw g cell inspectionItem`
* Edit the standard export in the mock data file:

```
InspectionItemCell.mock.ts

// Define your own mock data here:
export const standard = (/* vars, { ctx, req } */) => ({
  inspection: {
    id: 42,
    contractor: {
      id: 2,
      name: 'Nickson Twoson',
    },
    date: '2011-10-05T14:48:00.000Z',
    startTime: '2011-10-05T14:48:00.000Z',
    endTime: '2011-10-05T15:36:00.000Z',
    inspector: {
      id: 5,
      name: 'Jerry Whitehead',
    },
    site: {
      id: 24,
      name: 'Water Valley Water Plant',
    },
    permitFound: true,
    swpppFound: true,
    bmpInstalled: false,
    inspReportsFound: true,
    inspType: 'Default',
    description:
      'This was a normal inspection, not before or after a specific rain event.',
    title: 'Chuckabee Inspection',
    severity: ' None',
    violations: 'None',
    notes: 'There are no notes to speak of.',
    bmp: [
      {
        name: 'bmp 1',
        custom: false,
        implemented: true,
        maintenance: false,
      },
      {
        name: 'bmp 2',
        custom: true,
        implemented: false,
        notes:
          'This is a note saying that maintenance bmp needs to be implemented. It has not been',
      },
    ],
  },
})
```

This is a mildly complex mock data structure, developed after several design iterations.
It is representative of how the component wants to consume the data.
Implementing this workflow reduces overhead associated with context switching from api design to component design.
Using mock data means you do not have to leave the design space to update back-end models and relations, services, sdl's, etc.
Once design is completed then simply convert the properties and objects in the mock data file into prisma models.

### Passing Mock Data through Cells & Components

Storybook passes the mock data to the cell as a mocked query response [through the cell's stories file](https://redwoodjs.com/docs/tutorial/chapter5/first-story).

```
import { Loading, Empty, Failure, Success } from './InspectionItemCell'
import { standard } from './InspectionItemCell.mock'

export const loading = (args) => {
  return Loading ? <Loading {...args} /> : null
}

export const empty = (args) => {
  return Empty ? <Empty {...args} /> : null
}

export const failure = (args) => {
  return Failure ? <Failure error={new Error('Oh no')} {...args} /> : null
}

export const success = (args) => {
  return Success ? <Success {...standard()} {...args} /> : null
}

export default { title: 'Cells/InspectionItemCell' }
```

The `standard` export in the mock data file is imported at the top of the stories file, and passed to the `success` export.

## Building your Component

Get started designing your component.

`yarn rw g component InspectionItem`

Keep Storybook, `yarn rw sb`, running while in design.
Storybook will hot-reload as you update your design files.
Any changes to your mock data files or components are automatically updated in Storybook.
(Help needed on design blurb)

Using templates is a quick way to get started with layout structuring.
TailwindUI provides nice pre-defined templates for different data structures.
However, RedwoodJS also makes it easy to pick a component library and build your own layout from scratch.
Either way, this is the point where you enter your [Cell](https://redwoodjs.com/docs/cells) and start to integrate your mock data with your component design.

Revisit the [Tutorial, Part II](https://redwoodjs.com/docs/tutorial/chapter6/the-redwood-way) to work through the design process.

# Resources

## DDFS Workflow Resources

[Design-Driven Full-Stack: GitNation 2021](https://portal.gitnation.org/contents/design-driven-full-stack-an-end-to-end-dev-workflow-that-scales) 

[Design-Driven Full-Stack: YouTube Demo](https://youtu.be/dWWFZV6ML3k)

[What is Design-driven Full-stack Development?](https://community.redwoodjs.com/t/what-is-design-driven-full-stack-development/2966)

## Mock Data Resources

Mock data is essentially what you expect to be returned from the GraphQL queries. This becomes the Props that your component needs. 

[RW How-To: Mocking GraphQL in Storybook](https://redwoodjs.com/docs/how-to/mocking-graphql-in-storybook)

[RW Tutorial: Our First Cell](https://redwoodjs.com/docs/tutorial/chapter2/cells#our-first-cell)

## Storybook Resources

[Advanced RW Storybook Integration Demo](https://youtu.be/tHW7Gn6WCSc)

[Storybook Demo with Redwood](https://www.youtube.com/watch?v=zYm1a39Lpgs)

**Comment by pantheredeye** [comment]
Oh, apologies to anyone reading the comment above. I write in markdown and use single lines. In markdown, single lines turn into paragraphs. But, as seen above, GitHub comments do not do this.
