### ISSUE TITLE
[Bug?]: yarn create redwood-app my-redwood-project

### ISSUE THREAD

**Issue by miguelgargallo** [redwoodjs/redwood#6217]
### What's not working?

While I try to code and play with it, it simply do not allow me!?
Thanks for your job, I would like to be a contributor, by introducing this error:
miguelgargallo@macbookpro folder % yarn create redwood-app my-redwood-project

### How do we reproduce the bug?

yarn create v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/typescript-react-apollo@3.3.2" has unmet peer dependency "graphql-tag@^2.0.0".
warning "create-redwood-app > @redwoodjs/internal > babel-plugin-graphql-tag@3.3.0" has unmet peer dependency "graphql-tag@^2.10.1".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/depth-limit@1.6.0" has unmet peer dependency "@envelop/core@^2.4.0".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/disable-introspection@3.4.0" has unmet peer dependency "@envelop/core@^2.4.0".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/filter-operation-type@3.4.0" has unmet peer dependency "@envelop/core@^2.4.0".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/parser-cache@4.5.0" has unmet peer dependency "@envelop/core@^2.4.0".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/validation-cache@4.5.0" has unmet peer dependency "@envelop/core@^2.4.0".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > cosmiconfig-typescript-loader@3.1.1" has unmet peer dependency "@types/node@*".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > cosmiconfig-typescript-loader@3.1.1" has unmet peer dependency "typescript@>=3".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > ts-node@10.9.1" has unmet peer dependency "typescript@>=2.7".
[4/4] 🔨  Building fresh packages...
success Installed "create-redwood-app@2.2.0" with binaries:
      - create-redwood-app
  ❯ Creating Redwood app
    ✖ Checking node and yarn compatibility
      Creating directory '/Users/miguelgargallo/Documents/Code/Labs/folder/my-re
dwood-project'
    Installing packages
    Convert TypeScript files to JavaScript
    Generating types

Error: node >=14.19.0 <17.0.0 required, but you have 18.7.0

Visit requirements documentation:
/docs/tutorial/chapter1/prerequisites/#nodejs-and-yarn-versions

    at /Users/miguelgargallo/.config/yarn/global/node_modules/create-redwood-app/dist/create-redwood-app.js:148:25
    at /Users/miguelgargallo/.config/yarn/global/node_modules/check-node-version/index.js:163:5
    at end (/Users/miguelgargallo/.config/yarn/global/node_modules/run-parallel/index.js:21:15)
    at done (/Users/miguelgargallo/.config/yarn/global/node_modules/run-parallel/index.js:25:10)
    at each (/Users/miguelgargallo/.config/yarn/global/node_modules/run-parallel/index.js:31:7)
    at /Users/miguelgargallo/.config/yarn/global/node_modules/run-parallel/index.js:41:43
    at /Users/miguelgargallo/.config/yarn/global/node_modules/check-node-version/index.js:201:16
    at ChildProcess.exithandler (node:child_process:402:7)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16) {
  context: [Object: null prototype] {}
}
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-redwood-app
Arguments: my-redwood-project
Directory: /Users/miguelgargallo/Documents/Code/Labs/folder
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

### What's your environment? (If it applies)

```shell
MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by miguelgargallo** [comment]
❌ node --version
v18.7.0

Redwood requires [Node.js](https://nodejs.org/en/) (>=14.19.x <=16.x) 

✅ yarn -v
1.22.19

When [Yarn](https://yarnpkg.com/) (>=1.15)

**Comment by dac09** [comment]
Hello @miguelgargallo - please see the prerequisites section as per the error https://redwoodjs.com/docs/tutorial/chapter1/prerequisites#nodejs-and-yarn-versions

**Comment by miguelgargallo** [comment]
Please ensure correct setup devs, source: https://redwoodjs.com/docs/quick-start
I put this here, in case someone gets the error too
