### ISSUE TITLE
[RFC]: Update on Redwood Webpack Documentation 

### ISSUE THREAD

**Issue by Gresliebear** [redwoodjs/redwood#6225]
### Summary

Lately I have been getting this error when I wrote nodemailer into the frontend of my application

![image](https://user-images.githubusercontent.com/13157730/185023387-b372b7d3-5d15-4adc-9f81-dcf087656b37.png)

Long story short Webpack 5 removed polyfills so the work around I found out was you had to yarn add node-polyfill-webpack-plugin

### Motivation

Webpack is used lot, so if a developer is familiar with webpack its more apparent to them to implement it and stick with the framework. 

### Detailed proposal

```
const NodePolyfillPlugin = require("node-polyfill-webpack-plugin")

    plugins: [
      new NodePolyfillPlugin()
  ]

```

which if you `yarn rw setup webpack ` creates a webpack.config.js

redwood I think runs webpack under the hood some where couldnt find but this solution made no changes I read the docs but I completely missed this "config.plugins.push(PLUGINS) since it was commented out. 

This is my request for prosposal improve docs a little to show a example, I finally out polyfill to work on redwood with

```
const NodePolyfillPlugin = require("node-polyfill-webpack-plugin")

module.exports = (config, { mode }) => {

  if (mode === 'development') {
    // Add dev plugin
    config.plugins.push(
      new NodePolyfillPlugin()
  )

....

```

if you are encountering polyfill errors related to these modules, `config.resolve.fallback.push()` this is untested

```
 resolve: {
      mainFields: ['browser', 'module', 'main', 'nodemailer']
      fallback: {
        assert: require.resolve('assert')
        buffer: require.resolve('buffer')
        console: require.resolve('console-browserify')
        constants: require.resolve('constants-browserify')
        crypto: require.resolve('crypto-browserify')
        domain: require.resolve('domain-browser')
        events: require.resolve('events')
        http: require.resolve('stream-http')
        https: require.resolve('https-browserify')
        os: require.resolve('os-browserify/browser')
        path: require.resolve('path-browserify')
        punycode: require.resolve('punycode')
        process: require.resolve('process/browser')
        querystring: require.resolve('querystring-es3')
        stream: require.resolve('stream-browserify')
        string_decoder: require.resolve('string_decoder')
        sys: require.resolve('util')
        timers: require.resolve('timers-browserify')
        tty: require.resolve('tty-browserify')
        url: require.resolve('url')
        util: require.resolve('util')
        vm: require.resolve('vm-browserify')
        zlib: require.resolve('browserify-zlib')
      }
    }
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Gresliebear** [comment]
```
 - configuration.module.rules[1] has an unknown property 'fs'. These properties are valid:
web |    object { assert?, compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, issuerLayer?, layer?, loader?, mimetype?, oneOf?, options?, 
parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, scheme?, sideEffects?, test?, type?, use? }
web |    -> A rule description with conditions and effects for modules.
```

**Comment by jtoar** [comment]
Hey @Gresliebear! Got around to triaging this one and wondered why you're using nodemailer on the frontend? Redwood definitely polyfills, but doesn't polyfill Node.js builtins because, well, it's the web side. And you're right that the webpack config could have a better example or at least talk more about the existing config.

**Comment by Gresliebear** [comment]
@jtoar  I am going close this issue I was having trouble deploying on netlify. I was using their CLI and when you build on windows machine or mac machine the serverless function fails you can read it here https://github.com/netlify/zip-it-and-ship-it/issues/1167 oor here https://github.com/Gresliebear/TestingRedwoodDeployment/issues/3  

Basically you need to compile on a linux OS like debian to deploy on netlify. 

So out of desperation I implement node mailer on the front end to meet a deadline for a customer. it didn't work. so I am going close this issue its a suggestion. 

I do find that config parameter or passing it to be interesting and worth mentioning it I am not expert though I don't have a example.
