### ISSUE TITLE
[Bug]: Fastify { configureFastify } not being picked up in fresh project

### ISSUE THREAD

**Issue by zakmandhro** [redwoodjs/redwood#6254]
### What's not working?

The `configureFastify` override in `api/server.config.js` is not being picked up, even in a freshly created RedwoodJS 2.2.0 app. Oddly, it _is_ being picked up in the project generated by `yarn build:test-project ../rw-test-app --typescript --link --verbose`.

### How do we reproduce the bug?

Create new app:

```sh
yarn create redwood-app server-config-test --typescript
```

Modify api/server.config.js to add:

```ts
const configureFastify = async (fastify, options) => {
  if (options.side === 'api')
    fastify.log.info({ custom: { options } }, 'OVERRIDE Configuring api side')
  return fastify
}
// export as
module.exports = { config, configureFastify }
```

Run the dev server.

```sh
yarn rw serve api
```

or

```sh
yarn rw build && yarn rw serve api
```

#### Failure

Expected to see in the log output:
`OVERRIDE Configuring api side`
but seeing this instead:
`Loading server config from ***/api/server.config.js`

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 12.5
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.3
    Yarn: 3.2.1
  Databases:
    SQLite: 3.37.0
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.6
  npmPackages:
    @redwoodjs/core: 2.2.0 => 2.2.0
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by zakmandhro** [comment]
@dac09 @dthyresson could this related to #5903 ?

**Comment by zakmandhro** [comment]
If I run with the latest code, i.e. `yarn rwfw project:sync` from `main` (commit 92a207ae2f306b4af6336577c2b9e13fe8c14b90), this problem does not exist. Perhaps an issue with Release 2.2.0 only?

**Comment by dthyresson** [comment]
Yes. I believe so.

Please see https://github.com/redwoodjs/redwood/pull/5903

the latest has breaking changes and there is a code mod and instructions to update apps.

I’m not aware of 2.2 issues though.

**Comment by dthyresson** [comment]
The 2.x and 3.x server config files are not backwards compatible

**Comment by zakmandhro** [comment]
@dthyresson for 2.2, should my reproduce steps above work or am I missing something? The 2.2.0 docs suggest that `configureFastify` should work.

**Comment by zakmandhro** [comment]
Cool. Will wait for the next release to customize fastify.

**Comment by dthyresson** [comment]
2.2 should work — but only set certain server settings like the timeout and body size. Fastify calls these the Factory instance settings.

And only in dev or when deployed to serverful.
