### ISSUE TITLE
[Bug?]: Getting white screen when trying to load http://localhost:8911/graphql

### ISSUE THREAD

**Issue by shansmith01** [redwoodjs/redwood#6256]
### What's not working?

Hi There,

I am am getting a white screen and the following error in the console when trying to load up the Graphql explorer

Uncaught SyntaxError: The requested module 'https://unpkg.com/@graphql-yoga/graphiql' does not provide an export named 'renderYogaGraphiQL' (at graphql:1:384)

Not sure when this started but i am getting the issue in both 2.1.1 and 2.20

Thanks for the help

### How do we reproduce the bug?

Running a pretty vanilla install. 

- Yarn rw dev
- Navigate to http://localhost:8911/graphql
- Get white screen

I can access everything using a desktop explorer client

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  binaryTargets   = "native"
  previewFeatures = ["interactiveTransactions"]
}

model User {
  id                  Int           @id @default(autoincrement())
  email               String        @unique
  hashedPassword      String?       @default("")
  salt                String?       @default("")
  resetToken          String?
  resetTokenExpiresAt DateTime?
  company             Company?      @relation(fields: [companyId], references: [id])
  companyId           Int?          @unique
  transactions        Transaction[]
  passes              Pass[]
  cardnumber          String?       @unique
  fullName            String?
  cardIssuedby        String?
}

model Pass {
  id             Int           @id @default(autoincrement())
  user           User?         @relation(fields: [userId], references: [id])
  userId         Int?          @default(autoincrement())
  purchasedAt    DateTime?     @default(now())
  product        Product       @relation(fields: [productId], references: [id])
  productId      Int           @default(autoincrement())
  agentReference String        @default("")
  transactions   Transaction[]
  status         passStatus    @default(value: PENDING)
  notes          String?
  nights         Int           @default(0)
  price          Int           @default(0)
  company        Company?      @relation(fields: [companyId], references: [id])
  companyId      Int?          @default(autoincrement())
  customerName   String?       @default("")
}

enum passStatus {
  PENDING
  ACTIVE
  CANCELED
  COMPLETE
  EXPIRED
}

model Company {
  id           Int           @id @default(autoincrement())
  name         String        @unique
  identifier   String        @unique @default("")
  users        User[]
  transactions Transaction[]
  passes       Pass[]
  companyTypes CompanyType[]
}

enum CompanyType {
  AGENT
  HOSTEL
}

model Transaction {
  id              Int             @id @default(autoincrement())
  user            User            @relation(fields: [userId], references: [id])
  userId          Int
  nights          Int
  value           Int
  createdAt       DateTime        @default(now())
  transactionType TransactionType
  company         Company?        @relation(fields: [companyId], references: [id])
  companyId       Int?
  pass            Pass?           @relation(fields: [passId], references: [id])
  passId          Int?
  staffMember     String
}

enum TransactionType {
  PURCHASE
  REFUND
  SPEND
  CANCEL
  EXPIRE
}

model Product {
  id        Int       @id @default(autoincrement())
  name      String    @unique
  netPrice  Int
  createdAt DateTime  @default(now())
  validFrom DateTime?
  validTo   DateTime?
  nights    Int
  passes    Pass[]
}

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 12.5.1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.9.1 - /private/var/folders/t3/gmgw2_c966sdwbh8whw_0cx00000gn/T/xfs-8e192ed0/node
    Yarn: 3.2.1 - /private/var/folders/t3/gmgw2_c966sdwbh8whw_0cx00000gn/T/xfs-8e192ed0/yarn
  Databases:
    SQLite: 3.37.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.6.1
  npmPackages:
    @redwoodjs/core: ^2.1.1 => 2.2.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Tobbe** [comment]
Hi @shansmith01. Thanks for the bug report. A new version of graphiql was released which caused this problem together with the fact that the version of yoga we use always pulls in the latest version of graphiql. 

We're trying to upgrade to a later version of yoga which will fix this issue. As soon as we can get the tests passing here we'll merge it https://github.com/redwoodjs/redwood/pull/5962

Our current plan is to do a patch release as soon as we've upgraded yoga

**Comment by jomarmontuya** [comment]
Same issue encountered today, is there a workaround to rollback and use the old graphql version on my project?

**Comment by Tobbe** [comment]
We just merged the latest version of yoga. So anyone can now upgrade to canary (`yarn rw upgrade -t canary`) to fix this

**Comment by jomarmontuya** [comment]
Awesome! I can confirm that this is working thank you! @Tobbe

**Comment by Tobbe** [comment]
Patch release out: https://github.com/redwoodjs/redwood/releases/tag/v2.2.1
