### ISSUE TITLE
0.8.0 Auto imports not working for clean install

### ISSUE THREAD

**Issue by dardub** [redwoodjs/redwood#626]
I'm following along with the tutorial. I ran the generator `yarn redwood generate page home /` and HomePage was added to my Routes. However, it resulted in an error `ReferenceError: HomePage is not defined`.

If I explicitly add an import for HomePage, the error goes away.

Redwood version: 0.8.0.

**Comment by cannikin** [comment]
We've got a couple other reports of this here: https://community.redwoodjs.com/t/unable-to-create-homepage-referenceerror-homepage-is-not-defined/637/9

**Comment by thedavidprice** [comment]
## Short term solution:
Downgrade all `@redwoodjs` packages to `v0.7.0`. 

Anyone who is starting a new Create Redwood project will currently be using v0.7.0 -- we rolled-back the upgrade.

**Comment by peterp** [comment]
This has been fixed in `0.8.1`, if you experience this issue please upgrade using `yarn rw upgrade`

**Comment by rockymeza** [comment]
this is still happening on `0.8.1` for me

**Comment by thedavidprice** [comment]
Thanks @rockymeza We've confirmed on our end and are continuing to work on it. 

Current working issue: https://github.com/redwoodjs/redwood/issues/630
