### ISSUE TITLE
[Docs]: Clarify Netlify deployment should use the providers build and deploy flow, and not the "netlify cli" local

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#6260]
### Summary and description

See docs here: https://redwoodjs.com/docs/tutorial/chapter4/deployment#netlify

There has been some confusion in Discord where some people were trying to build and deploy a redwoodJS app to Netlofy using Netlify's CLI and the [build](https://cli.netlify.com/commands/build/) and [deploy](https://cli.netlify.com/commands/deploy) commands.

These commands with build the RedwoodJS locally (using the local settings and local OS) and then deploy the `dist`.

Problems arise with some package locations and how the list in bundled ... but the biggest issue is that the Prisma client will build using Windows or OSX and Netlfiy deploys need a linux variant.

So, the Prisma client that gets deployed is incompatible and fails.

Therefore, documentation needs to advise against using the Netlify and use the approach already documented in:

See docs here: https://redwoodjs.com/docs/tutorial/chapter4/deployment#netlify

Also, add a note in the `yarn rw setup deploy netlify` command.

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by Gresliebear** [comment]
I completely agree!!! I have been using Netlify CLI for 2 weeks as deployment tool that fails I recreated it as a public issue https://github.com/Gresliebear/TestingRedwoodDeployment/issues/3 here don't make  the same mistake!!! I wasted weeks of my life!!! 

Will there be a future long-term solution until a fixed is made? I don't know I will post a solution or deadend but I am working with Netlify devs on a solution here https://github.com/netlify/zip-it-and-ship-it/issues/1167 no luck gonna try esbuild setting to see if it resovles!
