### ISSUE TITLE
yarn creator doesn't delete folder on failure

### ISSUE THREAD

**Issue by goleary** [redwoodjs/redwood#627]
I'm trying to go through the redwood tutorial and I've had the first command (`yarn create redwood-app ./redwoodblog`) fail twice.  Both times the `redwoodblog` folder sticks around and I have to go delete it after (hopefully) fixing whatever caused the error.

I would assume that when the creator fails it would also delete all of the files/folder so I don't have to do this manually each time.

**Comment by thedavidprice** [comment]
Hi @goleary thanks for putting this on our radar. The way you described your expected behavior would definitely be a better process.

> I've had the first command (yarn create redwood-app ./redwoodblog) fail twice

^^ The "fail twice" definitely caught my eye -- anything more you can tell us about why the installation process was failing in the first place?

**Comment by goleary** [comment]
The first failure was due to node version (10 instead of 12) altho with it I got a message that my yarn was out of date (even though I have 1.22). After switching to node 12 I got some kind of network error which on retry succeeded.

Thanks for your quick and thorough response to my issue 😁.

It won't be forgotten and I'll make sure to pass along any additional issues/ideas/suggestions I have.

**Comment by thedavidprice** [comment]
You bet! And, most of all, thanks for putting up with some messiness out of the gate but still giving Redwood a go 🚀

And I look forward to the feedback 😀

**Comment by jtoar** [comment]
> The first failure was due to node version (10 instead of 12) altho with it I got a message that my yarn was out of date (even though I have 1.22). After switching to node 12 I got some kind of network error which on retry succeeded.

Fixed in https://github.com/redwoodjs/redwood/pull/2810. When the node/yarn version is different from the recommended a folder is no longer created:

```
  ❯ Creating Redwood app
    ✖ Checking node and yarn compatibility
      Creating directory '/Users/dom/prjcts/rw/_sandbox/redwoodblog'
    Installing packages
    Convert TypeScript files to JavaScript
    Generating types

```
