### ISSUE TITLE
[Bug?]: Netlify Production CORS Issue with Multi Value Headers with multiple origins

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#6279]
### What's not working?

CORS issue reported in Discourse:

https://community.redwoodjs.com/t/more-than-one-domain-for-cors/3846

---

Hi! We're having an issue while using CORS, we're on Redwood 2.2.0, and using Netlify for hosting. This behaviour is only happening in production, when following [this guide] (https://redwoodjs.com/docs/cors#testing-cors-locally) to test it locally it works fine.

Previously, we only needed to make CORS requests from a specific URL. With this configuration:
```javascript
// api/src/functions/graphql.ts
// ...
export const handler = createGraphQLHandler({
  // ...
  cors: {
    origin: 'https://internal.abillion.com',
  },
```
It works fine, here are the relevant response headers of the preflight request to `/graphql` from https://internal.abillion.com:
```
access-control-allow-credentials: true
access-control-allow-headers: authorization,content-type, authorization,content-type
access-control-allow-methods: POST, POST
access-control-allow-origin: https://internal.abillion.com
```

However, when we try to change that to an array:
```javascript
// api/src/functions/graphql.ts
// ...
  cors: {
    origin: ['https://internal.abillion.com', 'https://someotherdomain.com'],
  },
```
We get `null` in the allowed origin:
```
access-control-allow-credentials: true
access-control-allow-headers: authorization,content-type, authorization,content-type
access-control-allow-methods: POST, POST
access-control-allow-origin: null
```

And when we try with "*":
```javascript
// api/src/functions/graphql.ts
// ...
  cors: {
    origin: ['https://internal.abillion.com', 'https://someotherdomain.com'],
  },
```
We strangely get the same domain twice in the allowed origin, which gives a CORS error as well:
```
access-control-allow-credentials: true
access-control-allow-headers: authorization,content-type, authorization,content-type
access-control-allow-methods: POST, POST
access-control-allow-origin: https://internal.abillion.com, https://internal.abillion.com
```

We don't have any other CORS configuration, be it for authentication, or on Netlify (including netlify.toml).

Has anybody else faced this issue? Any pointers how we could fix it? Thanks a lot!

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by finalight** [comment]
what's the status of this ticket? is it being fix or needs more investigation?

**Comment by dthyresson** [comment]
@finalight are you seeing this behavior? If so and you have a reproducible case please do she’s as I want to fix this … but I haven’t found a way to reproduce quite yet. Thanks.

**Comment by finalight** [comment]
> @finalight are you seeing this behavior? If so and you have a reproducible case please do she’s as I want to fix this … but I haven’t found a way to reproduce quite yet. Thanks.

actually both of us are sort of working together, so we have the same codebase

**Comment by finalight** [comment]
i can show the package dependencies that we have as well

in the API folder, the package.json is as follow:

```
    "@redwoodjs/api": "^1.4.1",
    "@redwoodjs/graphql-server": "^1.4.1",
    "@redwoodjs/record": "^1.5.2",
```


for the web's package.json

```
    "@redwoodjs/forms": "^1.4.1",
    "@redwoodjs/router": "^1.4.1",
    "@redwoodjs/web": "^1.4.1",
```


for the root package.jso

```
"@redwoodjs/core": "^2.2.4",
```

**Comment by dac09** [comment]
@finalight - this seems very odd that your redwood versions don't match ;) I think maybe you did a manual upgrade?

Perhaps try upgrading like this `yarn rw upgrade -t 2.2.4`. or if you're ready to jump to the latest, just `yarn rw upgrade`.

**Comment by dthyresson** [comment]
To add to this thread and investigate, I just deployed a v3.0.1 app to Netlify with CORS configured as:

```
export const handler = createGraphQLHandler({
  loggerConfig: { logger, options: { operationName: true, query: true } },
  cors: {
    origin: [
      process.env.DEPLOY_URL,
      'http://localhost:8910',
      'https://www.example.com',
      process.env.DEPLOY_PRIME_URL,
      process.env.URL,
    ],
  }
```

Sending an Origin that is allowed results in a expected response (no dupes and origin is allowed) like:

![image](https://user-images.githubusercontent.com/1051633/190655081-7befaed2-c180-4f1d-871b-2b1c9df825b9.png)

While omitting a listed origin results in null as allowed:

![image](https://user-images.githubusercontent.com/1051633/190655210-49764c16-2bd4-43fd-bf61-6f7956ac9c5c.png)


And a bad origin, the same (also no duplicated headers):

![image](https://user-images.githubusercontent.com/1051633/190655341-777e3c03-8378-4160-9257-562e2e9bca2a.png)

**Comment by dthyresson** [comment]
From Discourse (https://community.redwoodjs.com/t/more-than-one-domain-for-cors/3846/5):

>  After updating to Redwood 3.0.0, CORS with more than one domain started working. I’m going to mark this as the solution and close the thread.

Closing.
