### ISSUE TITLE
[Bug?]:  Missing parameter for route when using glob pattern

### ISSUE THREAD

**Issue by cattre** [redwoodjs/redwood#6319]
### What's not working?

I'm trying to change a couple of routes to use the glob param pattern, in order to work with nested items, e.g.:

`<Route path='/category/{categoryIds...}/edit' page={CategoryEditCategoryPage} name='editCategory' />`

This working fine when I manually enter the URL, but I get an error when creating navigate links, e.g.:

`<Link to={routes.editCategory({ 'categoryIds...': category.id })}>Edit</Link>`

![image](https://user-images.githubusercontent.com/39544048/187047522-c14dae92-e002-4841-839b-b56722cb551a.png)

### How do we reproduce the bug?

https://gitpod.io#snapshot/f051b363-f867-42e0-8153-8c300d52439e

Navigate to categories list - https://8910-redwoodjs-gitpodstarter-im8r4cjqmdr.ws-eu63.gitpod.io/categories

### What's your environment? (If it applies)

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - /tmp/xfs-12e552be/node
    Yarn: 3.2.0 - /tmp/xfs-12e552be/yarn
  Databases:
    SQLite: 3.31.1 - /usr/bin/sqlite3
  npmPackages:
    @redwoodjs/core: 2.2.3 => 2.2.3
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by cattre** [comment]
I'm assuming the syntax for the navigate link is as above, although if I remove the ... the app loads and functions correctly, e.g.:

`<Link to={routes.editCategory({ 'categoryIds': category.id })}>Edit</Link>`

However, I then get a TS error:

TS2345: Argument of type ‘{ categoryIds: any; }’ is not assignable to parameter of type ‘{ “categoryIds…”: string; } & QueryParams’. Property ‘“categoryIds…”’ is missing in type ‘{ categoryIds: any; }’ but required in type ‘{ “categoryIds…”: string; }’.

**Comment by jtoar** [comment]
Hey @cattre thanks for the Gitpod snapshot! 🚀 As you mentioned in your second comment it looks like the types Redwood generates wrong. Let me step through [babel-plugin-redwood-routes-auto-loader](https://github.com/redwoodjs/redwood/blob/main/packages/internal/src/build/babelPlugins/babel-plugin-redwood-routes-auto-loader.ts) to see exactly what's going on there.

**Comment by jtoar** [comment]
The generator also need updating so that the page it generates doesn't throw; it needs a parameter.

**Comment by jtoar** [comment]
So turns out the utility type [here](https://github.com/redwoodjs/redwood/blob/455bcafb6b3b301d62f2a082f076642dd35e73ba/packages/internal/src/generate/templates/web-routerRoutes.d.ts.template#L32-L58) doesn't handle glob routes, so this now very much a TS problem

**Comment by nbushe** [comment]
I had this problem because of a link **without a parameter** in a layout.
