### ISSUE TITLE
[Bug?]: WindiCSS Storybook Config

### ISSUE THREAD

**Issue by pantheredeye** [redwoodjs/redwood#6356]
### What's not working?

The out-of-the-box `yarn rw setup ui windi` does correctly install WindiCSS, however it does not seem to pre-configure to work with storybook.

_**_Storybook view:_**_

![image](https://user-images.githubusercontent.com/77902178/188512251-8f8e7904-8a5d-40d5-a9ba-4753c413cb7e.png)

**_Dev server view:_**

![image](https://user-images.githubusercontent.com/77902178/188512283-88019180-1520-4276-96b8-53dd5b588d4b.png)

### How do we reproduce the bug?

Install fresh redwood app and run `yarn rw setup windi`. Do not run `yarn rw setup ui tailwind`, or the styles will work in storybook.

I would take a stab, except I am somewhat lost how to integrate with sb config. [Here is the WindiCSS webpack Storybook install page](https://windicss.org/integrations/webpack.html#storybook). It references adding a few lines of config to `.storybook/main.js` and to `.storybook/preview.js`

There may be a hint in the tailwind setup files. I didn't think to check there until typing this up.

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by callingmedic911** [comment]
Chakra also does something similar. Have a look at this file: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/lib/configureStorybook.js

`extendStorybookConfiguration` is used here during Chakra setup https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/setup/ui/libraries/chakra-ui.js#L93

Maybe we can do something similar for WindiCSS.

**Comment by callingmedic911** [comment]
Also (from https://redwoodjs.com/docs/storybook#configuring-storybook):

>[main.js](https://github.com/redwoodjs/redwood/blob/main/packages/testing/config/storybook/main.js)—gets merged with your project's storybook.config.js
>    [manager.js](https://github.com/redwoodjs/redwood/blob/main/packages/testing/config/storybook/manager.js)—gets >merged with your project's storybook.manager.js
>    [preview.js](https://github.com/redwoodjs/redwood/blob/main/packages/testing/config/storybook/preview.js)—gets >merged with your project's storybook.preview.js

So you probably need to configure storybook.config.js and storybook.preview.js in the user's project.

**Comment by callingmedic911** [comment]
Pinging @virtuoushub, he understands storybook very well. :)

**Comment by pantheredeye** [comment]
@callingmedic911 This is still a valid issue - however, I have not seen anyone complain about it on the forums or discord. So, not sure how pressing it is - but it does leave a gap.

**Comment by jtoar** [comment]
@callingmedic911 that does seem like the move; this is a good first issue so let's market it a bit that way now that it's hacktoberfest

**Comment by akashroy1** [comment]
I want to work on this. Is it still open?

**Comment by pantheredeye** [comment]
@akashroy1 Your help would be very welcome :) As far as I know, it is still a bug. You can double check following the steps to reproduce - basically just install a new version of redwood, install windi without running tailwind setup, and check storybook. It should be grey instead of colored like you will see in running `yarn rw dev.` 

There are some comments above that may help you track down the solution.

**Comment by pantheredeye** [comment]
@akashroy1 closed because WindiCSS is sunsetting, and the windi setup command has been deprecated.
