### ISSUE TITLE
Firebase Auth: Next Steps

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#636]
follow up from #593 

cc @peterp 

@noire-munich huge thanks again for diving in with this one! Well done 🚀

Some remaining items to cover:

**Documentation**
I didn't see an update to the documentation for this in the PR, correct? Without docs, it's almost like things don't exist 'cause people can't find them. So please do prioritize if it hasn't happened. https://github.com/redwoodjs/redwood/tree/master/packages/auth

**Auth Generator**
Is there a next step in process for adding this as a provider option for the Auth Generator? If not, at a minimum let's open a new Issue outlining the steps and adding the "Help Wanted" label. The similar issue process for Magic.Link was picked up very quickly. But please feel free to take a stab if you'd like @noire-munich!

**Summary of final implementation for Identity Providers and FirebaseUI**
Reading through [this original discussion comment about approach](https://github.com/redwoodjs/redwood/pull/593#issuecomment-633870588), I don't have enough familiarity with Firebase to understand what the final PR included by way of decisions about these. Could you provide a quick summary (maybe even as a comment on the PR for archiving)? My primary reason for asking the question is that depending on the implementation there might be a few more topics in the docs that need to be covered, e.g. default Identity Providers and how to swap, need to manage FirebaseUI separately, etc.

---

I was excited to see this one happen. Thanks again!

**Comment by peterp** [comment]
Hey @thedavidprice,

I'm busy with the additions to authentication from our core-team discussion last week. There's some refactoring work that I want to do related to that which includes the Firebase PR #593.

Included in my restructuring is the docs.

**Comment by noire-munich** [comment]
Hello guys and thanks again for your help on this :)

### Documentation
@thedavidprice my shameful bad x), didn't get where I could put the documentation... it was right beneath my nose.
I'd be happy to add it, @peterp , once the restructuring you mention is available. Is it fine by you?

### Generator
I'd be happy to help here as well providing I find enough time for it this week :) ( I'm trying to catch up on my RW project in the meantime )

### Summary of final implementation for Identity Providers and FirebaseUI
Well... that's the one that bugged me initially.
The PR is very straightforward, it offers only a sign up with redirect feature, it lets Google take on the entire process ( display & events ).

It doesn't cover:
- Allowing to change the provider - GoogleAuth is forced by default.
- Allowing to change the sign up method - signUpWithRedirect is forced, firebase offers a couple more.
- Support for FirebaseUi or any sort of ui packed in RW
- Testing ( ;)... and that's one I'm eager to see happening, but I'm not confident at all in initiating the topic )

In my project's roadmap I intend to come back to it and develop a bit more the use of firebase, it could be a use case to add more providers while using firebaseui ( which also needs a list of providers to use ). That could be a start to see it in action, before working on a draft for RW.

**Comment by thedavidprice** [comment]
@noire-munich This is great + helpful. And saw that you added it to the PR = perfect.

If you want to implement the Auth generator for this as well (which would be 🚀). Even if you can't get to it for a bit, you could initiate by creating a new issue with a simple outline of steps/plan, and saying that you're going to work on it.

Thanks again.

**Comment by peterp** [comment]
I believe that we've covered all the cases here.
