### ISSUE TITLE
[Docs]: Webhook instructions for Clerk don't work on Vercel

### ISSUE THREAD

**Issue by skyriverbend** [redwoodjs/redwood#6386]
### Summary and description

These instructions on integrating Clerk webhooks don't work when deploying to Vercel:
https://redwoodjs.com/docs/webhooks#base64-sha256-verifier-used-by-svix-clerk

It ends up throwing `WebhookVerificationError`. The instructions do, however, work on Netlify.

I believe this may have to do with Vercel somehow pre-parsing and modifying the body.

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by simoncrypta** [comment]
Hi @jonlemmon Thank you for open this issue. 
If you need any help for working on it, don't hesitate to ask :)

**Comment by tmikeschu** [comment]
@skyriverbend I got it working in vercel with a fix from this issue:

https://github.com/redwoodjs/redwood/issues/1410#issuecomment-825156426

```
export const handler = async (event: APIGatewayEvent) => {
  const clerkInfo = { webhook: 'clerk' }
  const webhookLogger = logger.child({ clerkInfo })
  const body = event.isBase64Encoded
    ? Buffer.from(event.body, 'base64').toString('utf-8')
    : event.body
  ...
```

**Comment by dac09** [comment]
Closing the issue, as suggested solution from @tmikeschu looks to me the probable cause.

Feel free to re-open if I'm mistaken :)
