### ISSUE TITLE
Add tests for Auth generator

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#639]
We've got great test coverage for our other generators, we need some for auth! The testing pattern should be pretty similar to the other generators. Check out the Page generator since it looks not only at files generated completely from scratch but existing files (like the Router) where the contents are modified.

**Comment by gizmoGremlin** [comment]
I'd like to work on this if no else is. I haven't written that many tests before.. so I may need some advice at some point :+1:  Cheers

**Comment by cannikin** [comment]
@gizmoGremlin yes please! We've got lots of tests for the other generators so those should give you a great starting point. We just test that files were generated at the expected path and that the context matches against a file in the `fixtures` directory.

**Comment by gizmoGremlin** [comment]
@cannikin I'm having alot of trouble importing auth.js into the test file auth.test.js
Its throwing the following error at the import statement when I run yarn test:

The error  :                                                                                                                                              ●  process.exit called with "0"
@redwoodjs/cli:       209 |   } catch (e) {
@redwoodjs/cli:       210 |     console.error(c.error(e.message))
@redwoodjs/cli:     > 211 |     process.exit(0)
@redwoodjs/cli:           |             ^
@redwoodjs/cli:       212 |   }
@redwoodjs/cli:       213 | }
@redwoodjs/cli:       214 | 
@redwoodjs/cli:       at getPaths (src/lib/index.js:211:13)
@redwoodjs/cli:       at Object.<anonymous> (src/commands/generate/auth/auth.js:11:36)
@redwoodjs/cli:       at Object.<anonymous> (src/commands/generate/auth/__tests__/auth.test.js

The import statement: 
import * as auth from '../auth'
p.s. I also tried import { files } from '../auth'

I'm not sure why this error is thrown before any code is run.
Any thoughts?I'm at a loss

**Comment by cannikin** [comment]
It could be the directory name...it should `__tests__` (two underscores before and after). I'm not a Jest expert, but maybe that's required for directory stuff to resolve properly?

**Comment by gizmoGremlin** [comment]
@cannikin .. The test file(auth.test.js) is in a __tests__ folder already. Is that what you mean?

**Comment by cannikin** [comment]
From that screenshot of the error it looks like the directory is just called "tests" without the underscores?

`@redwoodjs/cli: at Object. (src/commands/generate/auth/tests/auth.test.js`

Unless the error output removed the underscores? That would be strange...

**Comment by gizmoGremlin** [comment]
Good point. That is really wierd. When I look at the directory structure in vscode its `auth/__tests__/auth.test.js`,  I don't know why that is..

**Comment by cannikin** [comment]
Ahhh that explains it!

Question: how are you running the tests? You should be able to cd into `packages/cli` and run `yarn test` for the whole CLI suite, or `yarn test src/commands/generate/auth` and just run the tests in that directory.

**Comment by gizmoGremlin** [comment]
I'm doing the former.. cd into packages/cli and running yarn test. I also just tried the latter and got the same result.

**Comment by cannikin** [comment]
Hmmm

Okay so let's start from scratch. If you take the component generator test and copy that, remove the actual tests, then just find/replace "component" for "auth", do you get the same error?

**Comment by gizmoGremlin** [comment]
If i'm understanding you correctly, I get the same error.
`●  process.exit called with "0"

      209 |   } catch (e) {
      210 |     console.error(c.error(e.message))
    > 211 |     process.exit(0)
          |             ^
      212 |   }
      213 | }
      214 | 

      at getPaths (src/lib/index.js:211:13)
      at Object.<anonymous> (src/commands/generate/auth/auth.js:11:36)
      at Object.<anonymous> (src/commands/generate/component/__tests__/component.test copy.ts:7:1)`

I copied the component generator test (within the same folder).  I then removed all the tests(except the setup.. so it would not trigger the linter).  Then, Imported auth into the file instead of component.

**Comment by cannikin** [comment]
Oooo `getPaths` is a clue... you have to stub those out so that it's not actually accessing the filesystem to try and find things in an app that doesn't exist.

We do a default stub in cli/src/lib/test.js that mocks out locations for the `api` and `web` directories. I bet that one of the ones that the auth generator uses isn't in that list. Check out all the references for `getPaths()` in the auth generator and see if they're all present... I bet `getPaths().api.lib` isn't!

**Comment by gizmoGremlin** [comment]
@cannikin  You sir are correct!...  the api object (in cli/src/lib/test.js ) consists of db,src,services,graphql,functions.... no lib!

**Comment by cannikin** [comment]
Yep you can just add in your PR, we're always tweaking that test.js file.

**Comment by gizmoGremlin** [comment]
Ok thanks for your help!

**Comment by gizmoGremlin** [comment]
@cannikin I still can't get it to work.  It throws the same error. 

The error happens at `const API_GRAPHQL_PATH = path.join(getPaths().api.functions, 'graphql.js')`  in `src/commands/generate/auth/auth.js:11:36)` upon import into my test.

I took a look at the getPaths() function, It calls the `getRedwoodPaths()` function which returns a bunch of constants that seem to be well defined...
So, I'm still a bit lost on this one.

**Comment by cannikin** [comment]
Hmmm...so it looks like auth.js is the only generator that accesses `getPaths()` in constants, not inside of a function. So something about the way we're mocking out `getPaths()` seems like it's not available in time for when the constants are trying to use the results?

@peterp Sorry to bug you, but do you have any ideas here? Background:

* We import `loadGeneratorFixture` from `src/lib/test` at the top of all our test files, and that mocks out what `getPaths()` should return:

```javascript
jest.mock('@redwoodjs/internal', () => {
  const path = require('path')
  return {
    ...require.requireActual('@redwoodjs/internal'),
    getPaths: () => {
      const BASE_PATH = '/path/to/project'
      return {
        base: BASE_PATH,
        api: {
          db: path.join(global.__dirname, 'fixtures'), // this folder
          lib: path.join(BASE_PATH, './api/src/lib'),
          src: path.join(BASE_PATH, './api/src'),
          services: path.join(BASE_PATH, './api/src/services'),
          graphql: path.join(BASE_PATH, './api/src/graphql'),
          functions: path.join(BASE_PATH, './api/src/functions'),
        },
        web: {
          src: path.join(BASE_PATH, './web/src'),
          routes: path.join(BASE_PATH, 'web/src/Routes.js'),
          components: path.join(BASE_PATH, '/web/src/components'),
          layouts: path.join(BASE_PATH, '/web/src/layouts'),
          pages: path.join(BASE_PATH, '/web/src/pages'),
        },
      }
    },
  }
})
```

In every other generator, we only ever access `getPaths()` from inside functions, but in auth.js it's used to define a bunch of constants right at the start of the file, like:  

```javascript
const API_GRAPHQL_PATH = path.join(getPaths().api.functions, 'graphql.js')
```

When that `getPaths()` is hit it returns this weird error:

```terminal
rob$ yarn test src/commands/generate/auth
yarn run v1.22.4
$ jest src/commands/generate/auth
  ●  process.exit called with "0"

      209 |   } catch (e) {
      210 |     console.error(c.error(e.message))
    > 211 |     process.exit(0)
          |             ^
      212 |   }
      213 | }
      214 | 

      at getPaths (src/lib/index.js:211:13)
      at Object.<anonymous> (src/commands/generate/auth/auth.js:11:36)
      at Object.<anonymous> (src/commands/generate/auth/__tests__/auth.test.js:4:1)

 RUNS  src/commands/generate/auth/__tests__/auth.test.js
✨  Done in 2.79s.
```

If I remove those constants from auth.js completely then everything else can import properly and a simple "expect(true).toEqual(true)" works just fine.

Do you think this is a fix we can implement in the mocking stuff, or should we update the auth generator to make sure `getPaths()` is only used in functions that are evaluated later?

**Comment by peterp** [comment]
> should we update the auth generator to make sure getPaths() is only used in functions that are evaluated later

@cannikin I think that sounds reasonable for now, considering that we're going to make path testing much easier in the future.

**Comment by cannikin** [comment]
@gizmoGremlin Doing this would involve changing the auth generator itself to not use `getPaths()` in those constants and only use it inside functions. 😕 I wouldn't blame you one bit if you want to pass on this one, it turned into something much bigger than I thought it would.

**Comment by gizmoGremlin** [comment]
Yes, I'll pass on this one.. thanks for asking though

**Comment by gizmoGremlin** [comment]
@cannikin I think I know how to do this and I have a bit of time now to work on this. Could you reassign me?

Cheers

**Comment by cannikin** [comment]
Done! Looking forward to seeing how you tackle it!

**Comment by gizmoGremlin** [comment]
@cannikin Sorry to disturb, I have quick question about testing the auth generator.. 
Test the auth generator methods, that return a path or something else(similar to the page generator tests .. ) are fairly straight forward such as 
` magicFile = auth.files(['magicLink'])`
`test('creates a regular auth component', () => {
  expect(
    magicFile[path.normalize('/path/to/project/api/src/lib/auth.js')]
  ).toEqual(loadGeneratorFixture('auth', 'authFixture.js'))
})`
But the auth generator methods that write to the file system and return void seem less straight forward.
 such as 
`export const addApiConfig = () => {
  const API_GRAPHQL_PATH = resolveFile(
    path.join(getPaths().api.functions, 'graphql')
  )

  let content = fs.readFileSync(API_GRAPHQL_PATH).toString()

  // add import statement
  content = content.replace(
    /^(.*services.*)$/m,
    `$1\n\nimport { getCurrentUser } from 'src/lib/auth'`
  )
  // add object to handler
  content = content.replace(
    /^(\s*)(schema: makeMergedSchema)(.*)$/m,
    `$1getCurrentUser,\n$1$2$3`
  )
  fs.writeFileSync(API_GRAPHQL_PATH, content)
}`
Currently, to test these methods that write to the client filesystem, i'm using spy functions. such as 
`
test('addConfigToIndex is called', () => {
  const spy = jest.spyOn(auth, 'addApiConfig')
  auth.addApiConfig({
    imports: [`import { Magic } from 'magic-sdk'`],
    init: 'const m = new Magic(process.env.MAGICLINK_PUBLIC)',
    authProvider: {
      client: 'm',
      type: 'magicLink',
    },
  })

  expect(spy).toBeCalled()
})`

These work pretty well, but they don't test the content of what was saved to the file system, only if a function was called.

So, should I create some sort of mock client file system to test the file changes created by the generator or are spy functions sufficient?

Thanks in advance,
Cheers

**Comment by cannikin** [comment]
@gizmoGremlin We've avoided mocking out the file system for now and just assume that file writes will be successful. Although whether or not our code *tries* to write something to the file system would be nice to know. I'm not familiar enough with spies in Jest—can you spy on `fs.writeFileSync`? Can a spy/mock overwrite the function completely so it doesn't even bother trying to write a real file? Otherwise I guess we'd need a bunch of teardown functions to clean up any files written during the test run?

**Comment by gizmoGremlin** [comment]
@cannikin  Basically, I'm spying on the functions that contain writes to the file system, not the `fs.writeFileSync` itself.  As well, I'm mocking out the  `fs.writeFileSync` so it won't return null...  I'll push my pr so you can see and tell me what you think.

**Comment by peterp** [comment]
Hi 👋,

I wanted to point out that I'm currently making the generators output json in this pull-request: #902. By using that we won't have to test the filesystem anymore.

**Comment by dac09** [comment]
Closing, as this was implemented with snapshot tests in one of my PRs a while ago!
