### ISSUE TITLE
[Bug?]: Cannot find module 'headers-polyfill/lib' from 'node_modules/msw/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/NodeClientRequest.js'

### ISSUE THREAD

**Issue by finalight** [redwoodjs/redwood#6430]
### What's not working?

I've updated redwoodjs version to 3.0.1 and encounter this error:

```
Cannot find module 'headers-polyfill/lib' from 'node_modules/msw/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/NodeClientRequest.js'

    Require stack:
      node_modules/msw/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/NodeClientRequest.js
      node_modules/msw/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/http.get.js
      node_modules/msw/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/index.js
      node_modules/msw/node/lib/index.js
      api/test/utils/restServer.js
      api/src/services/postMedias/postMedias.test.ts
```

### How do we reproduce the bug?

Create a new redwood application with version 3.0.1 and write any test

run the test, you will encounter the error

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jtoar** [comment]
Hey @finalight, I can't reproduce this by creating a new redwood app. You mention that you've updated to 3.0.1, so it's an existing project right? I'm guessing your project's yarn.lock file may need regenerating. But to be sure, could you run a few commands and paste their output here:

```
yarn why msw
yarn why @mswjs/interceptors
```

The output of those for a project I just made is:

```
└─ @redwoodjs/testing@npm:3.0.1
   └─ msw@npm:0.47.3 [a16be] (via npm:0.47.3 [a16be])

├─ msw@npm:0.47.3
│  └─ @mswjs/interceptors@npm:0.17.5 (via npm:^0.17.5)
│
└─ msw@npm:0.47.3 [a16be]
   └─ @mswjs/interceptors@npm:0.17.5 (via npm:^0.17.5)
```

Also have you tried some basic debugging steps like deleting and re-installing `node_modules`? Not sure if it's that simple but sometimes it works, especially when upgrading.

**Comment by finalight** [comment]
thanks a lot for the quick reply!

upon further investigation, it turns out that we installed `msw` into our devDependencies ourselves, so that's why it's always using the specific version of msw

i can close this!
