### ISSUE TITLE
[Bug]: Web (Jest) tests will fail in v3.x if certain packages are used

### ISSUE THREAD

**Issue by jmackie** [redwoodjs/redwood#6452]
### What's not working?

While migrating from v2 to v3 we found our `web` tests broke due to esmodule syntax errors.

The issue we were hitting is essentially this one: https://github.com/react-hook-form/resolvers/issues/396

Packages like `react-hook-form` and `firebase` have an `exports` key in their `package.json`, which results in "browser" modules (with `import` and `export` statements) being pulled in by `jest-environment-jsdom`. And given that Jest doesn't transform `node_modules` by default, this caused things to blow up. 

The fix we went with was to force using the Node versions of libraries via [`testEnvironmentOptions.customExportConditions`](https://jestjs.io/docs/configuration#testenvironmentoptions-object):
```
  // ...jest config stuff
  testEnvironmentOptions: {
    customExportConditions: ['node', 'node-addons']
  }
```

We could also have used `transformIgnorePatterns` here, but didn't want to maintain a (long?) list of packages that export esmodules under `jest-environment-jsdom` conditions.

I'm not sure what the "best" solution is here, but I'll happily raise a PR if someone else does 🙏 

### How do we reproduce the bug?

1. Generate a new Redwood v3 project
2. Import and use `react-hook-form` in a `web/**/*.test.js` file
3. Run the `web` test suite

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by jtoar** [comment]
Hey @jmackie, I can't seem to reproduce this one. Creating a new RW v3 project and importing and using react-hook-form in a web test is just green checks for me.

Could you give me the version of react-hook-form your project has? Just with `yarn why react-hook-form`. Here's mine (not totally sure why it's duplicated; may just be yarn showing virtual packages or something like that):

```
├─ @redwoodjs/forms@npm:3.0.3
│  └─ react-hook-form@npm:7.35.0 (via npm:7.35.0)
│
└─ @redwoodjs/forms@npm:3.0.3 [42b1e]
   └─ react-hook-form@npm:7.35.0 [e8177] (via npm:7.35.0 [e8177])
```

Also, looking at the issue you linked to, it's not for react-hook-form but for `@hookform/resolvers`, which Redwood apps don't install by default. Did you install and are importing from `@hookform/resolvers` too in a test? 

Lastly, we did have some instructions in the upgrade guide for this situation. We recommend using a custom resolver. We're constantly worried that the fact that they're in a dropdown may cause people to miss them. Did you happen to see them? Not trying to make you feel bad or anything, I'm just wondering if you missed them cause they're in a dropdown. If so we've got to rethink how we do release notes: https://community.redwoodjs.com/t/redwood-3-0-0-is-now-available/3989#jest-v29-15

**Comment by jmackie** [comment]
> Also, looking at the issue you linked to, it's not for react-hook-form but for @hookform/resolvers, which Redwood apps don't install by default. Did you install and are importing from @hookform/resolvers too in a test?

Ahh you're right, `@hookform/resolvers` is what caused the problem for us 🤦 But FWIW I think importing `firebase/*` packages also hits this, and they're close to being default Redwood packages?

> Lastly, we did have some instructions in the upgrade guide for this situation. We recommend using a custom resolver. We're constantly worried that the fact that they're in a dropdown may cause people to miss them. Did you happen to see them?

I did miss that I'm afraid 🥲 OOI why do you recommend a custom resolver? We did that initially (as per [this issue response](https://github.com/react-hook-form/resolvers/issues/396#issuecomment-1114248072)) but it felt more heavy handed then changing `testEnvironmentOptions`?

**Comment by jtoar** [comment]
No worries! It's definitely more heavy handed, but it's scoped to the packages causing problems. It's probably just a result of my nervousness when it comes to changes that have global affects. Setting `testEnvironmentOptions` affects packages that do have the proper export conditions. But you're welcome to use any strategy you'd like! 

Maybe this is a good compromise (and is one that you're alluding to by `firebase/*` packages being close to Redwood defaults): let's add firebase to the framework's custom resolver? That way any Redwood apps using firebase don't have to worry about it.

Lastly, it looks like `@hookform/resolver` is ok now—is there a reason you can't upgrade that one?
