### ISSUE TITLE
[Bug?]: Types not automatically generated when the dev server is running

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#6471]
### What's not working?

When the Redwood dev server is running, it is meant to watch all relevant files and automatically generate types. 

In the case of Cells, this doesn't seem to be working - i.e. typegen is not run automatically.

Work around temporarily is to run `yarn rw g types` manually.

### How do we reproduce the bug?
- Start with test project, or a fresh Redwood project
- Create a Cell `yarn rw g cell UserExample`
- Make a change to the Cell's query

Now check the type for `FindUserExampleById` type - it won't have generated the new type automatically.

### Diagnosis
The problem isn't in the actual type generator, as `yarn rw g types` will fix the issue. It seems that the generate watcher that runs inside `yarn rw dev` does not pick up changes

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 12.5.1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /private/var/folders/s5/9hjh2cw51w714bw6px5nspr00000gn/T/xfs-b829b0d7/node
    Yarn: 3.2.3 - /private/var/folders/s5/9hjh2cw51w714bw6px5nspr00000gn/T/xfs-b829b0d7/yarn
  Databases:
    SQLite: 3.37.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 104.0.2
    Safari: 15.6.1
  npmPackages:
    @redwoodjs/core: 3.0.2 => 3.0.2
```

### Are you interested in working on this?

- [x] I'm interested in working on this

**Comment by dthyresson** [comment]
@dac09 I'll try to reproduce with your example, but I just tried in a v3.0.3-canary project (via project:sync) I was working on and I am seeing the types update:

1. This is before a cell query change (notice no `userId` in `FindPostQuery`):

![image](https://user-images.githubusercontent.com/1051633/193357463-b652e2f9-2d7e-4cd9-8470-482433f1f5c7.png)

2. Now while dev server running, I add `userId` to the query, and save
3. And I do see that types generate... notice logging ... and my types are updated. Notice `userId?: string | null `4. !4. [image](https://user-images.githubusercontent.com/1051633/193357621-9b3be666-a607-412c-94ef-02cee2267285.png)

This is in `/web/types/graphql.d.ts`.

4. If I query with an invalid field, it does error:5. 

![image](https://user-images.githubusercontent.com/1051633/193357969-f58d4106-63ea-413c-b3a5-9611f1a70a9b.png)

Let me try with the example test project, but am I reproducing the case here as you expect?

**Comment by dac09** [comment]
Thanks DT - your repro is correct, I'll see if I can reproduce this. I was seeing this in github.com/redwoodjs/nodeconf-redwood-recipes (private repo)

**Comment by jtoar** [comment]
@dthyresson heads up that I cleared the "next-release-patch" milestone cause that one's only for PRs and affects the release script, but happy to get this into a patch when the PRs up, and feel free to throw milestone on that one

**Comment by dac09** [comment]
Closing this.... I think caused by Vscode TS cache! Will reopen if I see it again!
