### ISSUE TITLE
[Bug?]: Potential issue with teardown in jest.setup.ts

### ISSUE THREAD

**Issue by stephenhandley** [redwoodjs/redwood#6475]
### What's not working?

We are trying to upgrade to `3.0.2` and have run into an issue where between individual scenarios, it appears that teardown isn't happening, and we are getting uniqueness collisions when a standard scenario is used repeatedly. 

We have a test structured like this:
- Scenario standard
- Scenario standard
- Scenario standard

The first Scenario runs fine however, the second two fail with uniqueness violations based since the rows are sticking around from the previous run.

It appears that this [change](https://github.com/redwoodjs/redwood/commit/51e13cd2066e14d7a42b494b4f24d1408739c160#diff-a83a50e3dfa07d044bc47d6b2070a853a8cafdcdd68688e0dfe128da3db0bbceR45-R51) introduced a check on `wasDbUsed()` in the `beforeAll`. This is returning false and so `configureTeardown()` is not called and `teardownOrder=[]` for the rest of the test run

We've reverted that change locally, and then our tests pass as before. 

### How do we reproduce the bug?

Create a test file that reuses standard scenario that includes a db model with an `@unique` field that is hardcoded to some fixed value in the scenario
```
// schema.prisma
model Something {
  id String @id @default(cuid())
  code String @unique
  foo String
}

// scenario
export const mockSomething = {
  foo: 'bar',
  code: 'test' // hard coded to value that is unique to scenarios but will cause collision without teardown
}

// test 
describe('something', () => {
  scenario(
    'something using standard scenario',
    async (scenario: StandardScenario) => {
      //...
    }
  )

  scenario(
    'another test using standard scenario',
    async (scenario: StandardScenario) => {
      //... 
    }
  )
)
```

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 12.4
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /var/folders/q5/y3831g4x7_j3nnzd_7qj2rhh0000gn/T/yarn--1664563625440-0.3078630727413023/node
    Yarn: 1.22.18 - /var/folders/q5/y3831g4x7_j3nnzd_7qj2rhh0000gn/T/yarn--1664563625440-0.3078630727413023/yarn
  Databases:
    SQLite: 3.37.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 15.5
  npmPackages:
    @redwoodjs/core: 3.0.2 => 3.0.2
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by MehdiSv** [comment]
Our db was not sitting in `api/src/lib/db` but in `api/src/db`

This caused the `wasDbUsed` check to fail in `beforeAll`

No need to remove that check, cc @pantheredeye

**Comment by jtoar** [comment]
Hey @stephenhandley thanks for reporting and great diagnosis, we've had a lot of trouble trying to make the api side tests faster while keeping scenarios the same. It looks like we may have crossed the line with this one, but I'm curious—do your scenario tests not use the database at all? Or is it required asynchronously within a test?
