### ISSUE TITLE
Unable to clone repo and work on redwood app

### ISSUE THREAD

**Issue by davidrhoderick** [redwoodjs/redwood#651]
So I'm following the tutorial and was able to upgrade to Redwood 0.8.2 after having issues with 0.8.0.  However, I wanted to update the same project based on the tutorial on my other computer.  When I clone the repository and run `yarn && yarn rw dev`, I get the following errors:

```
yarn run v1.22.4
$ /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.bin/rw dev
$ /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.bin/dev-server
$ /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.bin/prisma generate --watch
$ /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.bin/webpack-dev-server --config ../node_modules/@redwoodjs/core/config/webpack.development.js
22:54:46 api | Running at 'http://localhost:8911'
22:54:46 api | Watching files in '/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api/src/functions'
22:54:47 api | /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.prisma/client/index.js:3
22:54:47 api |     throw new Error(
22:54:47 api |     ^
22:54:47 api | 
22:54:47 api | Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
22:54:47 api | In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
22:54:47 api |     at new PrismaClient (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.prisma/client/index.js:3:11)
22:54:47 api |     at Object.<anonymous> (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api/src/lib/db.js:6:19)
22:54:47 api |     at Module._compile (internal/modules/cjs/loader.js:1158:30)
22:54:47 api |     at Module._compile (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/pirates/lib/index.js:99:24)
22:54:47 api |     at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
22:54:47 api |     at Object.newLoader [as .js] (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/pirates/lib/index.js:104:7)
22:54:47 api |     at Module.load (internal/modules/cjs/loader.js:1002:32)
22:54:47 api |     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
22:54:47 api |     at Module.require (internal/modules/cjs/loader.js:1044:19)
22:54:47 api |     at require (internal/modules/cjs/helpers.js:77:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
22:54:47 api | cd "/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api" && yarn dev-server exited with code 1
22:54:47 api | cd "/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api" && yarn dev-server restarted
22:54:47 web | ℹ ｢wds｣: Project is running at http://localhost:8910/
22:54:47 web | ℹ ｢wds｣: webpack output is served from /
22:54:47 web | ℹ ｢wds｣: Content not from webpack is served from /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/web
22:54:47 web | ℹ ｢wds｣: 404s will fallback to /index.html
$ /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.bin/dev-server
22:54:47  db | 
22:54:47  db | Watching... /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api/
22:54:47  db | prisma/schema.prisma
22:54:47  db | 
22:54:47  db | Get config {"is_panic":false,"message":"error: Environment variable not found: B
22:54:47  db | INARY_TARGET.\n  -->  schema.prisma:8\n   | \n 7 |   provider      = \"prisma-cl
22:54:47  db | ient-js\"\n 8 |   binaryTargets = env(\"BINARY_TARGET\")\n   | \n\nValidation Er
22:54:47  db | ror Count: 1","meta":{"full_error":"error: Environment variable not found: BINAR
22:54:47  db | Y_TARGET.\n  -->  schema.prisma:8\n   | \n 7 |   provider      = \"prisma-client
22:54:47  db | -js\"\n 8 |   binaryTargets = env(\"BINARY_TARGET\")\n   | \n\nValidation Error 
22:54:47  db | Count: 1"},"error_code":"P1012"}
22:54:47  db | 
22:54:47  db | 
22:54:47 api | Running at 'http://localhost:8911'
22:54:47 api | Watching files in '/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api/src/functions'
22:54:49 api | /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.prisma/client/index.js:3
22:54:49 api |     throw new Error(
22:54:49 api |     ^
22:54:49 api | 
22:54:49 api | Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
22:54:49 api | In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
22:54:49 api |     at new PrismaClient (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.prisma/client/index.js:3:11)
22:54:49 api |     at Object.<anonymous> (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api/src/lib/db.js:6:19)
22:54:49 api |     at Module._compile (internal/modules/cjs/loader.js:1158:30)
22:54:49 api |     at Module._compile (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/pirates/lib/index.js:99:24)
22:54:49 api |     at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
22:54:49 api |     at Object.newLoader [as .js] (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/pirates/lib/index.js:104:7)
22:54:49 api |     at Module.load (internal/modules/cjs/loader.js:1002:32)
22:54:49 api |     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
22:54:49 api |     at Module.require (internal/modules/cjs/loader.js:1044:19)
22:54:49 api |     at require (internal/modules/cjs/helpers.js:77:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
22:54:49 api | cd "/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api" && yarn dev-server exited with code 1
22:54:49 api | cd "/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api" && yarn dev-server restarted
$ /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.bin/dev-server
22:54:49 api | Running at 'http://localhost:8911'
22:54:49 api | Watching files in '/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api/src/functions'
22:54:50 api | /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.prisma/client/index.js:3
22:54:50 api |     throw new Error(
22:54:50 api |     ^
22:54:50 api | 
22:54:50 api | Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
22:54:50 api | In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
22:54:50 api |     at new PrismaClient (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.prisma/client/index.js:3:11)
22:54:50 api |     at Object.<anonymous> (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api/src/lib/db.js:6:19)
22:54:50 api |     at Module._compile (internal/modules/cjs/loader.js:1158:30)
22:54:50 api |     at Module._compile (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/pirates/lib/index.js:99:24)
22:54:50 api |     at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
22:54:50 api |     at Object.newLoader [as .js] (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/pirates/lib/index.js:104:7)
22:54:50 api |     at Module.load (internal/modules/cjs/loader.js:1002:32)
22:54:50 api |     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
22:54:50 api |     at Module.require (internal/modules/cjs/loader.js:1044:19)
22:54:50 api |     at require (internal/modules/cjs/helpers.js:77:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
22:54:50 api | cd "/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api" && yarn dev-server exited with code 1
22:54:50 api | cd "/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api" && yarn dev-server restarted
$ /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.bin/dev-server
22:54:51 api | Running at 'http://localhost:8911'
22:54:51 api | Watching files in '/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api/src/functions'
22:54:52 api | /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.prisma/client/index.js:3
22:54:52 api |     throw new Error(
22:54:52 api |     ^
22:54:52 api | 
22:54:52 api | Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
22:54:52 api | In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
22:54:52 api |     at new PrismaClient (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.prisma/client/index.js:3:11)
22:54:52 api |     at Object.<anonymous> (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api/src/lib/db.js:6:19)
22:54:52 api |     at Module._compile (internal/modules/cjs/loader.js:1158:30)
22:54:52 api |     at Module._compile (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/pirates/lib/index.js:99:24)
22:54:52 api |     at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
22:54:52 api |     at Object.newLoader [as .js] (/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/pirates/lib/index.js:104:7)
22:54:52 api |     at Module.load (internal/modules/cjs/loader.js:1002:32)
22:54:52 api |     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
22:54:52 api |     at Module.require (internal/modules/cjs/loader.js:1044:19)
22:54:52 api |     at require (internal/modules/cjs/helpers.js:77:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
22:54:52 api | cd "/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api" && yarn dev-server exited with code 1
22:54:54 web | [HPM] Error occurred while trying to proxy request /graphql from localhost:8910 to http://localhost:8911 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

Which looks to me like there are mostly issues with the database.  So I've tried `yarn rw db save` and I get the following:

```
yarn run v1.22.4
$ /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.bin/rw db save
Creating database migration... [started]
$ /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.bin/prisma migrate save --experimental
Error: Get config {"is_panic":false,"message":"error: Environment variable not found: DATABASE_URL.\n  -->  schema.prisma:3\n   | \n 2 |   provider = \"sqlite\"\n 3 |   url      = env(\"DATABASE_URL\")\n   | \n\nValidation Error Count: 1","meta":{"full_error":"error: Environment variable not found: DATABASE_URL.\n  -->  schema.prisma:3\n   | \n 2 |   provider = \"sqlite\"\n 3 |   url      = env(\"DATABASE_URL\")\n   | \n\nValidation Error Count: 1"},"error_code":"P1012"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Creating database migration... [failed]
→ Command failed with exit code 1: yarn prisma migrate save --experimental
Command failed with exit code 1: yarn prisma migrate save --experimental
Done in 2.67s.
```
So it looks like the .env is needed, but it should explicitly not be a part of a repo and is ignored in the .gitignore file.  What is then the way to work on a project in a git repo?  Shouldn't there perhaps be a way to re-create a .env in a cloned repo?

**Comment by davidrhoderick** [comment]
It's very odd because if I copy and paste the .env file, which contains nothing but comments when creating a new redwood app, I still get the errors.  If I try to define some .env variables, such as `DATABASE_URL=file:./dev.db` and `BINARY_TARGET=rhel-openssl-1.1.x`, I get the following errors on the home page:

```Error: GraphQL error: Invalid `prisma.post.findMany()` invocation in /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/api/src/services/posts/posts.js:4:18 Query engine binary for current platform "debian-openssl-1.1.x" could not be found. This probably happens, because you built Prisma Client on a different platform. (Prisma Client looked in "/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/@prisma/client/runtime/query-engine-debian-openssl-1.1.x") Files in /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/@prisma/client/runtime: Dataloader.d.ts browser-chalk.d.ts browser-terminal-link.d.ts browser.d.ts dmmf-types.d.ts dmmf.d.ts error-types.d.ts externalToInternalDmmf.d.ts getLogLevel.d.ts getPrismaClient.d.ts highlight index.d.ts index.js index.js.map mergeBy.d.ts query.d.ts transformDmmf.d.ts utils visit.d.ts To solve this problem, add the platform "debian-openssl-1.1.x" to the "generator" block in the "schema.prisma" file: generator client { provider = "prisma-client-js" binaryTargets = ["native", "rhel-openssl-1.1.x"] } Then run "prisma generate" for your changes to take effect. Read more about deploying Prisma Client: https://pris.ly/d/client-generator```

And running `yarn prisma generate` or even `yarn rw db save` and `yarn rw db up` doesn't fix anything.

In general, I'm finding it hard to use a repo of a project if it includes the database i.e., is dynamic.

**Comment by cannikin** [comment]
Best practice is to *not* check sensitive environment variables into your repo where they could be seen by prying eyes, so we provide a `.env.defaults` which contains the minimum you need to get running locally (and doesn't contain anything sensitive).  If you don't have a `.env` file (or it contains only comments, like the one provided with a new Redwood app) it should fall back to using `.env.defaults`.

However, if you create custom ENV vars in a `.env` file, and another developer needs to work on your code, you'll need to get them a copy of the contents of `.env` in another way (Slack, email, etc.). That's not us being jerks, it's just good security practice! 😃

If you don't need to worry about that at all then you could edit `api/prisma/schema.prisma` and remove the ENV vars completely and just replace them with the actual string values from your `.env` file so they're available everywhere to everyone.

**Comment by cannikin** [comment]
Have you tried `yarn rw db generate`? That should automatically happen when starting `yarn rw dev` but just in case.

What is your value for `BINARY_TARGET` in `.env.defaults`? The default value should be `native` which means that prisma should look up what client libs it needs based on the native operating system you're running on. Are you developing on an Ubuntu-based system? This message makes it sound like it thinks it's running on Ubuntu/Debian: `Query engine binary for current platform "debian-openssl-1.1.x" could not be found.`

**Comment by thedavidprice** [comment]
Hi @davidrhoderick Thanks for checking in about this. 

The local Prisma db is in `.gitignore` -- that's the `dev.db` file. But your Prisma migration files are being committed (which is important). When you clone a repo, you have to _create_ and _apply migration_ on a new local db. (Note: this is not the "save" step, which is what _creates_ a migration -- the next step is to apply the migration.

Try this:
- start fresh: either re-clone or run `git clean -fxd`
- `yarn`
- `yarn rw db up`
- `yarn rw dev`

**Comment by davidrhoderick** [comment]
@cannikin thanks for the explanation, it certainly makes sense to me why you'd want to avoid the .env files synchronizing in the repo.  However, I feel as if there should be a way I can clone a repo of a redwood app and get it up and running some way, even if the database isn't synchronized and has to be recreated.

Also, when I run `yarn rw db generate`, I get the following:

```
yarn run v1.22.4
$ /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.bin/rw db generate
Generating the Prisma client... [started]
$ /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.bin/prisma generate
Error: Get config {"is_panic":false,"message":"error: Environment variable not found: BINARY_TARGET.\n  -->  schema.prisma:8\n   | \n 7 |   provider      = \"prisma-client-js\"\n 8 |   binaryTargets = env(\"BINARY_TARGET\")\n   | \n\nValidation Error Count: 1","meta":{"full_error":"error: Environment variable not found: BINARY_TARGET.\n  -->  schema.prisma:8\n   | \n 7 |   provider      = \"prisma-client-js\"\n 8 |   binaryTargets = env(\"BINARY_TARGET\")\n   | \n\nValidation Error Count: 1"},"error_code":"P1012"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Generating the Prisma client... [failed]
→ Command failed with exit code 1: yarn prisma generate
Command failed with exit code 1: yarn prisma generate
Done in 2.97s.
```
Also, my repo doesn't contain any `.env.defaults` file.  Should it?  What should the contents of that file be?

I am running Pop!_OS 20.04, so basically Ubuntu.

**Comment by davidrhoderick** [comment]
@thedavidprice thanks for the the steps, that's honestly what I thought would work (although the first time, I tried `yarn rw db save` before `yarn rw db up`) and when I get to `yarn rw db up`, it gives me the following:

```
yarn run v1.22.4
$ /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.bin/rw db up
Migrate database up... [started]
$ /home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/node_modules/.bin/prisma migrate up --experimental --create-db
Error: Get config {"is_panic":false,"message":"error: Environment variable not found: DATABASE_URL.\n  -->  schema.prisma:3\n   | \n 2 |   provider = \"sqlite\"\n 3 |   url      = env(\"DATABASE_URL\")\n   | \n\nValidation Error Count: 1","meta":{"full_error":"error: Environment variable not found: DATABASE_URL.\n  -->  schema.prisma:3\n   | \n 2 |   provider = \"sqlite\"\n 3 |   url      = env(\"DATABASE_URL\")\n   | \n\nValidation Error Count: 1"},"error_code":"P1012"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Migrate database up... [failed]
→ Command failed with exit code 1: yarn prisma migrate up --experimental --create-db
Command failed with exit code 1: yarn prisma migrate up --experimental --create-db
Done in 2.77s.
```

Anything else I can try?

**Comment by cannikin** [comment]
Hmmm yeah in the root of your repo should be a file `.env.defaults` that contains:

```
# These environment variables will be used by default if you do not create any
# yourself in .env. This file should be safe to check into your version control
# system. Any custom values should go in .env and .env should *not* be checked
# into version control.

DATABASE_URL=file:./dev.db
BINARY_TARGET=native
```

**Comment by cannikin** [comment]
That should fix the errors about missing environment variables. If you continue to get the error `Query engine binary for current platform "debian-openssl-1.1.x" could not be found.` that's a bigger issue. You may be the first developer we've found that's using a Debian-based dev environment! This would actually be an issue with Prisma, not us. We can point you in the right direction for opening an issue with them if that persists.

**Comment by thedavidprice** [comment]
^^ definitely check into Rob's comments as well.

> Anything else I can try?

^^ Ah, that could be an issue with the migration files themselves. You said you _upgraded_ at one time? I just assumed it was from v0.8 to v0.8.2. BUT there have been several upgrades where new versions of Prisma were incompatible with previous.

You can see if this is your case by deleting the /migrations directory and starting again, but this time make sure you add a new migration with `yarn rw db save`. 

Make sense?

**Comment by thedavidprice** [comment]
sorry for tag-team here with @cannikin (lots of incoming, but hopefully helpful). 

I'm checking for Prisma compatibility with that version of System now.

Rob, I'll hand off and leave things be 😉

**Comment by davidrhoderick** [comment]
@cannikin You are the man!  That's the ticket!

I actually created the .env.defaults file as per your suggestion and then decided to run yet again `git clean -fxd`, which _removed_ that file, then I ran `yarn`, `yarn rw db up`, and `yarn rw dev`.  So is it a good idea to unignore the .env.defaults in the repo at least so it can be rebuilt without too much of this hassle?  I leave that up to you.  But I do concur that .env needs to be ignored...

**Comment by cannikin** [comment]
Excellent!

We're not ignoring `.env.defaults` in our `.gitignore` so I'm not sure why that file wouldn't have been there for you...we only ignore `.env` (no wildcards).

I've got a bunch of sample apps I've built for various testings in Redwood and they all have `.env.defaults` checked in: https://github.com/cannikin/grover so I'm not sure why it wasn't checked in for you...

**Comment by davidrhoderick** [comment]
That's weird.  So I tried `git clean -xfd` in my just created redwood app, which I was using to pull .env contents and made no other changes, and it removed `.env.defaults`.  Do you manually check in `.env.defaults`?

Does the `.gitignore` need to be as follows?

```
.DS_Store
.env
!.env.defaults
.netlify
dev.db
dist
dist-babel
node_modules
yarn-error.log
```

**Comment by cannikin** [comment]
You shouldn't have to manually check in `.env.defaults`, no. We've had plenty of people go through the tutorial and so far you're the only person that's reported this happening, so strange!

If `.gitignore` had `.env*` then it would ignore both files, but `.env` should *only* ignore `.env` exactly and not `.env.defaults`.

I created a new app from scratch to make sure I'm not losing my marbles, here's a recording: https://www.youtube.com/watch?v=dkJbjVXfYzE

**Comment by davidrhoderick** [comment]
Huh, you definitely have your marbles and when I tried the same thing, it did indeed work.

My only thought is if `.env.defaults` was added between 0.7.0 and 0.8.2 but even my `.gitignore` didn't explicitly ignore `.env.defaults` (it only ignored `.env`).

So I'll close this because it's working now but it is odd and hopefully just a one-off.  Thanks for all your help!

**Comment by mahemoff** [comment]
I had a similar issue. Adding back the `.env.defaults` as above fixed it.
