### ISSUE TITLE
Adding node-sass results in missing sass-loader

### ISSUE THREAD

**Issue by davidrhoderick** [redwoodjs/redwood#652]
Hello again, really great job on this project but I'm just seeing what it can do and running into these issues.  Hopefully this is a good place to put this even if it is a bit of an enhancement.

I'm trying to include .scss files and I first presumed it could be done simply by installing `node-sass` just like a `create-react-app` project works.  I use the code `yarn workspace web add node-sass --dev` and whether I restart the dev server or not, I get the following error:

```
Failed to compile

./src/index.js
Module not found: Can't resolve 'sass-loader' in '/home/davidrhoderick/Development/redwoodjs-tutorial/redwoodblog/web'
```
Is this something on redwood's side or should I be looking for another integration of SASS?

**Comment by thedavidprice** [comment]
Hi (again) @davidrhoderick 😉

Currently Redwood doesn't handle SASS compiling. But it's possible via Webpack. If you're looking for some other options/examples in general, there are several related topics on our forums:
- https://community.redwoodjs.com/t/recommendations-for-integrating-a-css-library/305/
- https://community.redwoodjs.com/t/how-to-use-linaria-css-in-js-with-redwoodjs/612/
- https://community.redwoodjs.com/t/how-to-add-tailwindcss-to-redwoodjs/334/

Here's an example webpack config specific to SCSS that might be what you need (or can be modified as needed): 
https://gist.github.com/bjackson/0216081965babd482448c42961798b2e

You'll need this doc about extending Webpack config within your application:
https://redwoodjs.com/docs/webpack-configuration

We are considering adding that Webpack module to core config -- if you happened to try it out, could you let us know how it goes?

**Comment by peterp** [comment]
@davidrhoderick I thought we actually _do_ support scss out of the box; we have it configured over here: 
https://github.com/redwoodjs/redwood/blob/9ea29e728ed58134aad67d9518102a4b96143047/packages/core/config/webpack.common.js#L40-L47

If it's not working it definitely should be, and maybe this is a bug.

**Comment by davidrhoderick** [comment]
@thedavidprice thanks for pointing me in that direction.  I already tried implementing the [webpack config here](https://gist.github.com/bjackson/0216081965babd482448c42961798b2e) that you provided but I still get the `sass-loader` missing issue.

@peterp are you suggesting that if I just include `.scss` files it should work, without creating my own webpack config file?  I just uninstalled `node-sass` and `sass-loader` (maybe I should have left them in...) and removed my custom webpack config file and I get the same missing `sass-loader` error.  Are you able to get scss preprocessing working without installing anything?

Thanks for your patience, I didn't have as much time to check this out as I thought I would so hopefully around the start of next week, I'll bumble through this and give you some more information.

**Comment by peterp** [comment]
> Are you able to get scss preprocessing working without installing anything?

That should be the idea - I'll check this out

**Comment by peterp** [comment]
@davidrhoderick Ok, so in order to make this work you need to install `sass-loader` and `sass` as a devDep in the `web` package:

```terminal
cd web
yarn add -D sass-loader sass
```

The configuration is already setup, so that's all you need.

**Comment by peterp** [comment]
- [ ] Add documentation that details sass support
- [ ] Add support for sass modules

**Comment by davidrhoderick** [comment]
@peterp I just wanted to confirm that those steps work above exactly right.  Thanks for your help!

**Comment by peterp** [comment]
I've updated the docs for this, but they're still not perfect, I think we could just install `sass` and `sass-loader`, or prompt a person that installation is required when they try to import a scss or sass file.

**Comment by thedavidprice** [comment]
@peterp was this one ready to close out? Or are you thinking about working on the items you mention above?
