### ISSUE TITLE
Upgrade Command: Add link to Release Notes via

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#658]
Using `terminal-link' package and Yargs `.epilogue()`, add a message with a link to https://github.com/redwoodjs/redwood/releases 

Should emphasize breaking changes occur frequently 'cause < v1.

**Comment by jtoar** [comment]
Added this to #594. Does the output look ok/what you wanted?

![rw-upgrade](https://user-images.githubusercontent.com/32992335/83927485-e979ae00-a741-11ea-8696-80a47bbc0b54.png)

**Comment by thedavidprice** [comment]
hey! great timing on this -- I was rebasing, checking file changes, and about to MERGE when I saw that come in... was so confused 🤣

Ok, that looks really good. BUT I wrote Yargs + epilogue, but what I was really thinking was to output that same text+link at the end of the command output -- maybe as a final Listr task our perhaps just outside List entirely inside `try` at the end of `upgrade.js`.

Let me merge #594 as is. But do you want to handle the above in a separate PR?

**Comment by jtoar** [comment]
Sorry if I scared you. :sweat_smile:  And sure thing!

**Comment by thedavidprice** [comment]
And feel free to start it with something bold like "WARNING" or ⚠️ or ... you get the idea. As a general habit+practice, we really don't want anyone upgrading without viewing release notes.

**Comment by thedavidprice** [comment]
Very similar to #664 

Might be able to handle both at the same time.

**Comment by jtoar** [comment]
![image](https://user-images.githubusercontent.com/32992335/118895579-49b62100-b8bb-11eb-94f8-1c75ff5425f0.png)
