### ISSUE TITLE
[Bug?]: Redwood Form, DateField's defaultValue isn't working

### ISSUE THREAD

**Issue by NetLancer** [redwoodjs/redwood#6585]
### What's not working?

RW Form's <DateField defaultValue /> does not set the value by default, just renders empty with date format mask. 
Although i've tried date values in different formats and simple string 

### What's your environment? (If it applies)

```shell
System:
    OS: Linux 5.15 Void
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.16.0 - /tmp/xfs-bf05bf4b/node
    Yarn: 3.2.1 - /tmp/xfs-bf05bf4b/yarn
  Databases:
    SQLite: 3.39.4 - /usr/bin/sqlite3
  npmPackages:
    @redwoodjs/core: ^3.1.1 => 3.1.1
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by NetLancer** [comment]
...and neither does it work with <DatetimeLocalField /> (defaultValue prop), so for DAteTime needs i'm using third party react lib now. Browsers in use: Falkon, Chromium latest the voidLinux repo can afford. 
Please hElp(!)

**Comment by Tobbe** [comment]
@NetLancer Could you please provide some steps for reproducing your issue? That would help us debug this. Thanks!

**Comment by NetLancer** [comment]
Oh, sorry for delay, so its just about using RW provided Form & its controls: 
Namely DateField component for which i failed to set defaultValue 
`<Form>
    <DateField 
      name="whatever" 
      defaultValue={dateVariable}` 
and no matter how i formatted the dateVariable it doesn't reflect in the form upon load, so i'm temporarily using (third party) npm lib DatePicker instead

**Comment by zygopleural** [comment]
The problem that I had was that by default the scaffolds use `DateTimeLocalField` but when you change to `DateField` it required a different formatter function. I made a quick repo here: https://github.com/zygopleural/date-field-defaultValue the fixes I did to make it work are here https://github.com/zygopleural/date-field-defaultValue/commit/ff578a7ed46ea1e8a581babfef216e1f9915ab32

**Comment by NetLancer** [comment]
Many thanx!

**Comment by ahaywood** [comment]
I ran into some issues with RedwoodJS and the `Date` and `DateTime` component and stumbled upon this issue. After doing a deep dive, I realized this isn't a bug in RedwoodJS or React Hook form, but a "feature" of how the `date` and `dateTime` HTML inputs work.

I created a demo repo with extensive documentation in the README explaining (including helper functions): https://github.com/ahaywood/redwood-date-test
