### ISSUE TITLE
Show auth installation docs when `yarn rw g auth <type>` is run

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#664]
I think it would be great if we could give detailed instructions on how to complete the generated auth types that require additional setup, as an example:

```terminal
$ yarn rw g auth auth0
[... auth work ...]

[IMPORTANT] The auth0 generator requires additional setup to work, please follow the instructions over here: https://redwoodjs.com/docs/auth/auth0
```

**Comment by cannikin** [comment]
So you mean rather than showing "The generator requires additional setup..." that we actually list out what those steps are right there inline? Or that we make our own version of the remaining setup instructions, instead of linking to a third-party site? 

Linking to a page somewhere (rather than showing instructions inline) is that there may be more complex instructions that have helpful images showing where to go to get stuff like API keys.

**Comment by peterp** [comment]
@cannikin I just thought that it would be easier to maintain those instructions on the web, like for auth0's setup we say something like:  "Follow the first part of the quick-start tutorial over here", but I guess it could be inline?

**Comment by cannikin** [comment]
Yeah I agree it would be easier to maintain on the web. But we *are* showing a link to those setup instructions already at the end of the install. Did you just mean that we should be writing and linking to setup docs on our own site instead of linking to the auth provider's description?

**Comment by thedavidprice** [comment]
Ah, thanks for pointing that out @cannikin I think I missed the link when I was testing this the first time around. Here's the current output:
```bash
$ /Users/price/Repos/tdp-tutorial-blog-test/node_modules/.bin/rw g auth netlify
  ✔ Adding required packages...
  ✔ Installing packages...
  ✔ Generating auth lib...
    ✔ Writing `./api/src/lib/auth.js`...
  ✔ Adding auth config to web...
  ✔ Adding auth config to GraphQL API...
  ✔ One more thing...

    You will need to enable Identity on your Netlify site and configure the API endpoint.
    See: https://github.com/netlify/netlify-identity-widget#localhost
```

@peterp do you think there should also be a link to the Redwood Auth Docs?

**Comment by peterp** [comment]
@cannikin @thedavidprice I actually didn't know it did that. My apologise!

**Comment by thedavidprice** [comment]
ditto ¯\_(ツ)_/¯
