### ISSUE TITLE
Wrong pluralization used in generated page name

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#666]
Note the plural "settings" was used to generate the page:

```terminal
rob$ yarn rw g page settings
yarn run v1.22.0
$ /Users/rob/Sites/pwv/conway/node_modules/.bin/rw g page settings
  ✔ Generating page files...
    ✔ Writing `./web/src/pages/SettingsPage/SettingsPage.test.js`...
    ✔ Writing `./web/src/pages/SettingsPage/SettingsPage.js`...
  ✔ Updating routes file...
✨  Done in 1.42s.
```

The files are created with the correct plural name. However, in the generated page the title is singluar, "SettingPage":

![image](https://user-images.githubusercontent.com/300/84063228-96883c80-a975-11ea-92c5-c32bf16e96a1.png)

**Comment by evanmoncuso** [comment]
I'm looking for a first issue! Happy to take a look at this.

**Comment by cannikin** [comment]
@evanmoncuso That'd be awesome, thank you! You'll see a big list of variables we make available to the templates when they're being generated, looks like we just picked the wrong one!

**Comment by evanmoncuso** [comment]
Yep. Seemed to be the case. Thanks!

PR: https://github.com/redwoodjs/redwood/pull/683

**Comment by dthyresson** [comment]
Issue was fixed in https://github.com/redwoodjs/redwood/pull/683 merged on Jun 12.

`yarn rw g page settings`

```
✔ Generating page files...
    ✔ Writing `./web/src/pages/SettingsPage/SettingsPage.stories.js`...
    ✔ Writing `./web/src/pages/SettingsPage/SettingsPage.test.js`...
    ✔ Writing `./web/src/pages/SettingsPage/SettingsPage.js`...
  ✔ Updating routes file...
✨  Done in 2.80s.
```

```js
import { Link } from '@redwoodjs/router'

const SettingsPage = () => {
  return (
    <>
      <h1>SettingsPage</h1>
      <p>Find me in "./web/src/pages/SettingsPage/SettingsPage.js"</p>
      <p>
        My default route is named "settings", link to me with `
        <Link to="settings">routes.settings()</Link>`
      </p>
    </>
  )
}

export default SettingsPage
```

**Comment by peterp** [comment]
😈
