### ISSUE TITLE
Next release (3.6.0)

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#6684]
> This page is synced automatically from RedwoodJS's Notion
> Notion page URL: https://www.notion.so/Next-release-3-6-0-f12dfa06faf24334bad04dd4b3104f4f

We want to work in public as much as we can, so we’re making the roadmap for the next few releases available here. This is so that you’ll…

1. know what we’re working on, what we consider high priority, and know what to expect from future releases
2. be able to share your thoughts about what we do and influence our direction and decisions
3. join us and contribute!

If you want to discuss any of this or help contribute, join our office hours and contributing workshops: https://redwoodjs.com/events

## 3.6.0

| RC available? | ❌      |
| ------------- | ------ |
| Release date  | 11/07  |
| Lead          | @jtoar |
| PRs           | TBD    |
| Diff          | TBD    |

## 4.0.0-rc

> **Note**  
>   
> We try to release a minor every week, so there may be more minors before v4. I.e. once we release v3.3.0, we’re not automatically releasing v4. This is just to keep track of priorities.

| RC available? | ❌                                                                                                                          |
| ------------- | -------------------------------------------------------------------------------------------------------------------------- |
| Release date  | TBD                                                                                                                        |
| Lead          | @jtoar                                                                                                                     |
| PRs           | [https://github.com/redwoodjs/redwood/milestone/132?closed=1](https://github.com/redwoodjs/redwood/milestone/132?closed=1) |
| Diff          | TBD                                                                                                                        |

**Comment by jtoar** [comment]
Not sure why the notion sync opened this one.

**Comment by Josh-Walker-GM** [comment]
Closing this as I don't think it's adding anything valuable anymore.
