### ISSUE TITLE
Ctrl Click/ F12 on a function doesn't take you to definition (vs code)

### ISSUE THREAD

**Issue by goleary** [redwoodjs/redwood#669]
When I Ctrl+ click a function or component in VS Code (or use F12) I'm taken to the import statement at the top of the file I'm already in, not the definition in that file.  I figured maybe this had to do with the `src/...` aliasing, but even when I import regularly this is still happening.

https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition

This makes it difficult to get to the definition of a function/component.

vs code 1.45.1
windows 10

**Comment by peterp** [comment]
I'll take a look at this, thanks for reporting it!

**Comment by jtoar** [comment]
Here's an example I came across:

https://user-images.githubusercontent.com/32992335/119906157-8bba1500-bf02-11eb-83cd-b35d78093e75.mp4

**Comment by Tobbe** [comment]
This is one of the things I miss the most when working on a RW project compared to say a CRA project. Thankfully it's going to be solved by our TS efforts. It's the second to last item here https://github.com/redwoodjs/redwood/issues/234#issuecomment-848483967

**Comment by dac09** [comment]
Fixed in #2614 !! 🍾
