### ISSUE TITLE
SDL generated code now contains `gql` import statement

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#670]
@cannikin @peterp 

From the work on #515, the SDL generated code now includes `import gql from 'graphql-tag'`, which is a change. Functionally this does _not_ conflict with the auto-import or cause issues. But it is a (small) deviation from the Tutorial code.

I’m assuming this is the case because it's required for the generated TS code to work, correct?
- if so, should we update the Tutorial? (example section "[Saving Data](https://redwoodjs.com/tutorial/saving-data)")
- if not, should we remove from source template?

**Comment by cannikin** [comment]
Hmm yeah we purposely made an effort to remove this import (like with 'react') to make everyone's lives easier.

If it's required, it must only be required if you generate TS templates, correct? So if you generate JS can we remove it somehow?

If it's not required let's definitely remove from the template altogether!

**Comment by peterp** [comment]
We can take it out, I'll add an ambient declaration that makes this work.
