### ISSUE TITLE
[Bug?]: Tailwind Prettier formatting not applied on save

### ISSUE THREAD

**Issue by Benjamin-Lee** [redwoodjs/redwood#6701]
### What's not working?

#5795 added support for Prettier formatting of Tailwind classes. However, the default VS Code configuration of `"editor.formatOnSave": false,` means that, even with the Prettier VS Code plugin installed, the formatting is not fixed automatically. This section:

```
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
```
should be enough to apply Tailwind/Prettier on save since `yarn rw lint --fix` works but for whatever reason, it doesn't.

### How do we reproduce the bug?

1. Create a Redwood project with Tailwind
2. Open in VS Code
3. Put class names in the wrong order (try: `lg: text-red-500 text-blue-500`)
4. Hit save

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 12.0.1
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.10.0 - /private/var/folders/gw/sk03t1cn3wlgclyc55yst44w0000gn/T/xfs-d0862bc4/node
    Yarn: 3.2.3 - /private/var/folders/gw/sk03t1cn3wlgclyc55yst44w0000gn/T/xfs-d0862bc4/yarn
  Databases:
    SQLite: 3.36.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 104.0.2
    Safari: 15.1
  npmPackages:
    @redwoodjs/core: 3.2.0 => 3.2.0
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by noire-munich** [comment]
@Benjamin-Lee thank you for taking the time to file this, are you willing to work on a PR?
I'm looping in @simoncrypta who's worked on the ticket you've mentioned.

**Comment by Benjamin-Lee** [comment]
For reference, this problem has resolved itself. I didn't change any VS Code settings (`"editor.formatOnSave": false,` is still in my config) but now my editor does correctly format on save.

**Comment by noire-munich** [comment]
Weird.
If problem self solved though I'll close it.
