### ISSUE TITLE
[RFC]: Automatic upgrade migrations

### ISSUE THREAD

**Issue by Josh-Walker-GM** [redwoodjs/redwood#6726]
### Summary

A proposed solution to #5153 and an idea I initially laid out in #6113 but I think is best separated out given it doesn't directly relate to arbitrary user messaging but to upgrading instead.

### Motivation

It would be an improvement to developer experience to be guided through the upgrade process and have any potential code modifications available to be performed automatically. Clearly an idea with some existing motivation given #5153.

### Detailed proposal

There will be a repository which stores a `versions.json` file at it's root. This file will document currently released redwood versions, it will do this by containing an array of upgrade messages that take the form of:

```ts
interface UpgradeMessage {
  id: string // uuid
  toVersion: string // updated version eg 3.2.0
  fromVersion: string // previous version eg 3.1.7
  transitionScriptURLs: string[] // repo urls which contain scripts that can perform any required checks or modifications needed to transition from "fromVersion" to "toVersion"
  preMessage: string // message to show the user before running the first script
  postMessage: string // message to show the user after running all scripts
}
```

Given the form of the upgrade message it will be possible to construct a linked list. This way upon invocation of the upgrade command it will be possible to determine the users current redwood version and form an unbroken list of releases (and any associated modification scripts) up to the current latest release.

The upgrade command can then walk up the release list and perform the following actions:

1. Show the user any pre-upgrade messages for the current version transition
2. Offer to run any amount of automatic code migrations by fetching and executing the transition scripts
3. Show the user any post-upgrade messages

This would repeat until the user has reached the latest version. This approach allows any important pre or post upgrade messages to be shown before upgrading between certain versions. For example if there are code modifications which cannot be performed automatically and requires manual editing. It also allows any number of code modifications scripts for version transitions. They can be stored in a required order in the list if needed. 

I propose the upgrade scripts be specific in their design - that is that they export a specific set of functions to be consistent over time. I would suggest we have it similar to a database migration like:
```ts
export const up = () => {} // Performs the code modifications
export const down = () => {} // Reverts the code modifications
export const title = "" // Some descriptive title of what this migration is for
export const preMessage = () => { return "" } // A specific message that will be shown to the user when prompting to run this specific migration
export const postMessage = () => { return "" } // A specific message that will be shown to the user after running this specific migration
```
These migration scripts can be stored within the same repository under a folder with a name consisting of the to and from versions together, e.g. `1.1.0-1.2.0`. These scripts can be fetched at the time they are needed preventing unnecessary bloat locally for the user.

These migrations will likely require some local storage of data in order to support the `down` operation - i.e. to restore to the un-upgraded state. I would argue that the existing `.redwood` folder would be suited to store this persistent data. There would be some log file which can store information related to the various `up` operations - names of files changed, their original unaltered contents etc. This can then if required be accessed during `down` operations to restore to the previous state. We could either overwrite the log file each time to prevent it ballooning in size or we could store 3 such log files and override the oldest copy - this would allow greater rollback potential than one single log file.

I would propose this is only for users not running any specific version tags i.e. `-rc` or `-canary`. Attempting to keep up a consistent unbroken upgrade migration list for this would be far too demanding.

A potential benefit of this system is that it will also simplify and centralise the detection of latest versions. Currently this is done by searching npm for a greater version but this repository could instead serve as the source of that information.

The use of a github repository also enables any potential CI benefits too. CI could ensure that; the linked list has no missing links, could ensure upgrade messages and transition scripts follow the standard etc.

Hopefully this acts as a reasonable starting point for discussions before a potential go-ahead to attempt any kind of implementation.

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by noire-munich** [comment]
Thank you for this @Josh-Walker-GM, since there's some overlap I'm setting the "Needs discussion" flag on this one.

**Comment by Josh-Walker-GM** [comment]
This is a difficult problem in general and we're not going to prioritise adding this as a feature. We do keep good upgrade guides and produce codemods where possible which should address most of the concern here anyway.
