### ISSUE TITLE
[Bug?]: Can't signin with Supabase auth

### ISSUE THREAD

**Issue by wilhg** [redwoodjs/redwood#6729]
### What's not working?

I am using the version 3.2.0 and trying to integrate the Supabase auth with this example: [Supabase Auth | RedwoodJS Docs](https://redwoodjs.com/docs/how-to/supabase-auth#sign-in)

However, on the page, it will show this error message:

> client.auth.signIn is not a function

### How do we reproduce the bug?

Source code is below, which can be also fin:

```tsx
const SigninPage = () => {
  const { logIn } = useAuth()
  const [error, setError] = React.useState(null)

  const onSubmit = async (data) => {
    setError(null)
    try {
      const response = await logIn({
        email: data.email,
        password: data.password,
      })
      response?.error?.message
        ? setError(response.error.message)
        : navigate(routes.home())
    } catch (error) {
      setError(error.message)
    }
  }

  return (
    <>
      <h1>Sign In</h1>
      <Form onSubmit={onSubmit}>
        {error && <p>{error}</p>}
        <TextField name="email" placeholder="email" />
        <PasswordField name="password" placeholder="password" />
        <Submit>Sign In</Submit>
      </Form>
    </>
  )
}
```
Thank you for help!

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by wilhg** [comment]
I worked this around by locking the supabase-js version to 1.35.7
> yarn up @supabase/supabase-js@^1.35.7

However, it's obvious that the redwood has compatibility issues with supabase-js@2

**Comment by Alonski** [comment]
Thanks I also found this issue :) Trying to find a workaround.

**Comment by jtoar** [comment]
Thanks for reporting @wilhg, this has been fixed in https://github.com/redwoodjs/redwood/releases/tag/v3.2.1.

**Comment by wilhg** [comment]
Thank you very much, @jtoar !
