### ISSUE TITLE
[Bug?]:  WebAuthn not working in production but works perfectly in development

### ISSUE THREAD

**Issue by arimendelow** [redwoodjs/redwood#6730]
### What's not working?

Hi! For some reason, WebAuthn isn’t working with my webapp once I deploy it. The most information I’m able to get is as follows:

```
Error while registering: Could not complete registration: Unexpected token e in JSON at position 0
    at Object.register
```

The Auth payloads look exactly the same. This happens in both Chrome and Safari.

I have configured it as described for production in [the docs](https://redwoodjs.com/docs/auth/dbauth#webauthn).

The error is thrown specifically on line 163 in @redwoodjs/auth/dist/webAuthn/index.js:
```
    xhr.send((0, _stringify.default)({
      method: 'webAuthnRegister',
      ...regResponse
    }));
```

Using the Chrome debugger, I can see that it looks the exact same in dev and in prod. Maybe the following is the issue - that the token is being sent in a key that looks like it should be JSON (clientDataJSON)?

<img width="1595" alt="Screen Shot 2022-10-24 at 8 00 08 PM" src="https://user-images.githubusercontent.com/16390116/197671994-90eee9f2-11b5-49ae-bfaa-1982ac859345.png">

### How do we reproduce the bug?

It's just a scaffolded RedwoodJS app with dbAuth and WebAuthn set up as specified in the docs.

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by arimendelow** [comment]
I should also note that this is being thrown on client-side code, and the server is showing no signs of issues.

**Comment by cannikin** [comment]
We've had a bunch of back and forth in [this discussion thread](https://community.redwoodjs.com/t/webauthn-cryptically-not-working-in-production-but-works-perfectly-in-development/4206). Will update here if/when we find out what's happening.

**Comment by arimendelow** [comment]
We can close this - this issue has been fixed in a later version of RedwoodJS. See that discussion thread for more info.
