### ISSUE TITLE
[Feature request] Add support to ArangoDB via GraphQL Yoga

### ISSUE THREAD

**Issue by mysticaltech** [redwoodjs/redwood#675]
Hello, thank you for your amazing work. I would love to see support for [ArangoDB](https://www.arangodb.com/). Unlike PostgresDB that is under Prisma, it is a multi-model, Document, Graph, Key-Value and Search database.

A GraphQL layer could possibly be added with the Prisma project https://github.com/prisma-labs/graphql-yoga and its JS driver library https://github.com/arangodb/arangojs.

**Comment by thedavidprice** [comment]
Hi @mysticaltech Thanks for suggesting this!

As it stands now, Redwood is focused on Prisma 2 and won't be adding other first-class support in the near-term. Understandably this feels a bit limiting if you want to use anything other than SQL/relational right now via Prisma. But do know that there's going to be many more types of DBs that Prisma supports directly by the end of this year (e.g. no-sql like MongoDB, etc.).

ArangoDB does look amazing. And what is possible right now with Redwood is to _not_ use Prisma and instead set up a connection to any DB you'd like within the API (or multiple DBs if needed). Here's an example for a different graph DB, Neo4j, in our forums: https://community.redwoodjs.com/t/using-redwood-with-neo4j-database/282

Lastly, if you do want to try this yourself, please loop us in via the Forums and let us know if you get it working and especially if you need help getting it to work. We'd be happy to try and help.

**Comment by mysticaltech** [comment]
Thank you, appreciate the details, I will sure keep you guys in the loop if I get to it one day. I will also keep a close eye on Prisma's support for new DBs.
