### ISSUE TITLE
Provide a way to Mock user authentication in jest tests

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#680]
Allow a user to pass:
```js
{ auth: {
   currentUser: {},
   isAuthenticated: {},
}}
```
to render in `@redwoodjs/testing`

We will provide a default user and the hook will always be authenticated.

/cc @RobertBroersma

**Comment by thedavidprice** [comment]
@peterp Checking in on this one -- it seems this can now be done using MSW + 'mock' file, correct?

If so, then would there be any other action step here other than documentation?

**Comment by dthyresson** [comment]
@peterp @cannikin @thedavidprice @dac09  I thought there may have been some recent work done to help with mocking auth.

Does this issue still apply or can it be closed?

**Comment by peterp** [comment]
@dthyresson We are super close. We just need to mock the api side! Myself and Rob have spoken about doing the following:

![Uploading image.png…]()

**Comment by dthyresson** [comment]
> We are super close

Great news! I'll move this issue card into in progress then.
