### ISSUE TITLE
[RFC]: Warn on duplicate routes

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#6833]
### Summary

A tutorial user just ran into this issue, and I've seen it myself: a route is listed more than once in `Routes.tsx` and the first one always matches. Which is the expected behavior, but it can be scary if you overlook the duplication (which several of us did when trying to debug this issue).

Maybe it would be possible to scan through the Routes file and generate a warning to the console if a duplicate is found? Just a nice little DX addition.

### Motivation

Being confused as hell as to why I route wasn't including the <Set> layout wrapped around it: a duplicate route was *outside* the <Set> and matching first.

### Detailed proposal

Write code to make this work.

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
> Question - has this been attempted in some form with `yarn rw check`?

Thanks @pantheredeye for pointing this out to me. I see now that when you have duplicate paths (I copy paste'd the home route so there were 4 of them) you get output like:

![image](https://user-images.githubusercontent.com/56300765/200833682-33a47cb6-0eb5-43f2-874b-271582f467f1.png)

I'll close what I opened. The check command functions fine in this case given it shows the exact line number of the duplicates even if the actual text description is minimal.

It appears check the command is based off of the redwood language server? A great way to reuse logic already written! Just isn't as pretty to the eye but works fine.

**Comment by pantheredeye** [comment]
Also - neither @cannikin or I thought to use this command when trying to diagnose the user's problem... which, back to the spirit of the RFC, is how can we get in front of the problem without the user having to have deep knowledge of when to use the check command...

**Comment by Josh-Walker-GM** [comment]
@pantheredeye No it's fine it can always be reopened if the wind changes direction. 

I don't have a great understanding of the check code itself. It would appear to me that given that the underlying logic is from the language server we'd ideally be able to squiggle someones code to highlight duplicate routes in real time as they write/read their code. However, it doesn't appear to function that way. This would directly solve the issue of not thinking about the check command - I have never really run it either. 

From my quick googling and a brief read over the README.md in the structure package I think the following:

1. Someone spent time developing this language server stuff - great job it appears to work well when used within check
2. There used to be a redwoodjs vscode extension which allowed vscode to use this language server stuff to show diagnostics like this? So we would have seen squiggles about duplicate routes etc?
3. The vscode extension was deprecated and removed - don't know why wasn't around at the time.

This might be a total misunderstanding but just my initial impressions.

If we didn't already have a quite fully featured checker then I'd have ideally parsed the routes file and shown output like:
```
Warning: You have two routes named "home" and "home" which both use path "/", only the route closest to the head of the file will be used. These are defined at web/src/Routes.js:21 and web/src/Routes.js:48.
```

**Comment by Josh-Walker-GM** [comment]
@cannikin to show in vscode live as they edit would require an extension is my understanding.

When you say show in the console? You mean when you navigate to a path with more than one option you'd see a warning in the web console?

**Comment by cannikin** [comment]
I'm not worried about VS Code personally, I ignore all squiggles in there. haha But I'm sure some people would love that. If we ever resurrect the Redwood IDE extension that'd be a prime candidate.

Yeah, or even on every page load if possible, show that warning. I can't think of a case where you'd *want* there to be two identical routes, so I think it's okay to warn always.

But we've also got the web process that's running that monitors for changes and runs everything through webpack/babel? I was thinking it could show a warning message there as well.

**Comment by Josh-Walker-GM** [comment]
@cannikin Okay this is an area of redwood I haven't much looked into yet. I'll have a little look and play around and see if I can come up with anything in the direction of your idea.

**Comment by audreyfeldroy** [comment]
Hi, just a newbie here but thought I'd try and contribute at least a tiny useful thing. I dug around a bit to see what other web frameworks do with duplicate route console warnings. The only example I could find was from vue-router, which is nice though could perhaps be improved:

```
vue-router.esm.js:16 [vue-router] Duplicate named routes definition: { name: "some_url", path: "/some_url" }
```

@pantheredeye @cannikin thank you for your thoughtful help yesterday when I ran into this error as a tutorial user, and for thinking of other users who may run into similar bugs.

**Comment by Josh-Walker-GM** [comment]
I've reopened #6835 with an implementation of a routes checker which runs and warns automatically during the dev server.

**Comment by cannikin** [comment]
> I guess a good point to make on this RFC is what counts as a duplicate route? Currently I've only considered if there are routes with duplicate paths but perhaps we should also have an error for routes which share a name? Routes which share a page is fine I think because it's not unthinkable someone might mean to do that.

Ahh, interesting. I was just thinking if the whole `<Route>` tag was literally identical would it warn. I could see someone possibly having two URLs to the same page:

```jsx
<Route path="/products/all" page={ProductsPage} name="allProducts" />
<Route path="/products" page={ProductsPage} name="products" />
```

As well as two different names that go to the same URL (maybe one feels more natural to use on certain links than the other):

```jsx
<Route path="/login" page={ProductsPage} name="login" />
<Route path="/login" page={ProductsPage} name="adminLogin" />
```

But each actual name has to be unique. So maybe it checks if any two routes have the identical props signature, OR if the same `name` appears more than once?

**Comment by cannikin** [comment]
> Hi, just a newbie here but thought I'd try and contribute at least a tiny useful thing. I dug around a bit to see what other web frameworks do with duplicate route console warnings. The only example I could find was from vue-router, which is nice though could perhaps be improved:

@audreyfeldroy Thanks for the reference! Does this show in the browser console, or in the terminal where you started the vue process? Do you only see it once, or when you save a file, or maybe any time you browse to a new page?

**Comment by Josh-Walker-GM** [comment]
@cannikin Okay so we'll decide on duplicates based on name then.

>But each actual name has to be unique. So maybe it checks if any two routes have the identical props signature, OR if the same name appears more than once?

I think we can get a 2 for 1 here. Searching for all routes which share a name would include the routes which share all props automatically - I think?

**Comment by cannikin** [comment]
Ahhh interesting! Looks like it uncovered a bug in the test project! What do you think @jtoar? I'm guessing we should rename the scaffold ones something like `adminContact`?

**Comment by Josh-Walker-GM** [comment]
Worth noting that when the current diagnostics that are run within `rw check` were written they only examined paths and not names. Hence why this is being shown up here but wouldn't when running `check`. Just must have been a decision someone made at the time.

**Comment by Josh-Walker-GM** [comment]
Just for the record I updated the test-project to have a `ContactUs` page rather than just `Contact`, so the names no longer conflict with the scaffolded contacts.
