### ISSUE TITLE
Words that can't be pluralized will blow up some of the generators

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#684]
## Problem

Create a model named `Pokemon` and then try to generate the scaffold for it:

```
yarn rw g scaffold pokemon    
yarn run v1.22.4
$ /Users/price/Repos/xx-delete/node_modules/.bin/rw g scaffold pokemon
  ✖ Generating scaffold files...
    →   15 |   })
    Adding scaffold routes...
    Adding scaffold asset imports...
/Users/price/Repos/xx-delete/api/src/services/pokemon/pokemon.ts: Identifier 'pokemon' has already been declared (12:13)
  10 | }
  11 | 
> 12 | export const pokemon = ({ id }: PokemonWhereUniqueInput) => {
     |              ^
  13 |   return db.pokemon.findOne({
  14 |     where: { id },
  15 |   })
✨  Done in 4.19s.
```

It turns out this is because the plural and singular forms of "pokemon" are the same. :( The JS generators don't actually care, but if you try to generate TS (which the scaffold, service and SDL generators all do by default) it will complain that an identifier already exists and refuse to continue. But even with the JS generators, some files aren't created because some of the filenames are identical.

## Proposal

Run a check at the start of any generator that depends on generating things specifically with singular/plural name differences that will blow up with a message letting the user know before generating anything:

```
[ERROR] Singular and plural are returning the same string! You should add a rule
to disambiguate:

pluralize.addPluralRule(/pokemon$/i, 'pokemonii')
```

I'm not sure where this custom rule can go so that it actually gets picked up by the scaffold generators. In Rails, a brand new app will include a file `config/initializers/inflections.rb` where you can add custom pluralization rules and they are picked up for use by the generators:

```ruby
# Be sure to restart your server when you modify this file.

# Add new inflection rules using the following format. Inflections
# are locale specific, and you may define rules for as many different
# locales as you wish. All of these examples are active by default:
ActiveSupport::Inflector.inflections(:en) do |inflect|
  # inflect.plural /^(ox)$/i, '\1en'
  # inflect.singular /^(ox)en/i, '\1'
  # inflect.irregular 'person', 'people'
  # inflect.uncountable %w( fish sheep )
  inflect.irregular 'human', 'humans'
end

# These inflection rules are supported but not enabled by default:
# ActiveSupport::Inflector.inflections(:en) do |inflect|
#   inflect.acronym 'RESTful'
# end
```

Maybe we can include some kind of `web/src/lib/pluralizationRules.js` file and the generators will include that file if it exists before starting.

**Comment by jtoar** [comment]
@cannikin Would `redwood.toml` be a good place for this?

```
[generators]
  pluralRules = [/pokemon$/i, 'pokemonii']
```

**Comment by cannikin** [comment]
Ooooo interesting....what do you think @peterp?

**Comment by peterp** [comment]
I think it would be easier to put it in a specific place - I like your suggestion of placing it in `web`, but maybe we could put it in `web/config/pluralizationRules.js`

**Comment by cannikin** [comment]
Right now the only place it's biting us in the scaffold generators which are the CLI, not the user's web or api side. I don't think we have any other pluralization in the web or api side after your app is created. Maybe this just needs to be a flag you can set when generating:

    yarn rw g scaffold pokemon --plural=pokemons

And then we'll use that as the plural form, rather than generating it from the name of the model. We probably also need a singular flag if your model name is plural:

    yarn rw g scaffold pokemons --singular=pokemon

**Comment by thedavidprice** [comment]
I think this is helpful, but should be prioritized as step 2. Step 1 would be to modify the generators so they fail gracefully, e.g. don't blow up on a word like "pokemon" and give a readable message with suggestion to use a different word for the model.

> yarn rw g scaffold pokemon --plural=pokemons

^^ As for handling specifics words (which will also be awesome for multi-language support), this makes the most sense to me. I think config is a bit overkill for something a developer will likely do once or twice. (i.e. run the generator.)

> We probably also need a singular flag if your model name is plural

^^ I thought the "rule" was for model names to _only_ be singular?

**Comment by cannikin** [comment]
> Step 1 would be to modify the generators so they fail gracefully, e.g. don't blow up on a word like "pokemon" and give a readable message with suggestion to use a different word for the model.

Makes sense, although if we're only releasing once a week we can probably get both the warning and the `--plural` flag done to ship together...

> I think config is a bit overkill for something a developer will likely do once or twice. (i.e. run the generator.)

Yeah, I was thinking for some reason that we use the pluralization rules in the app itself (web and/or api) side but I don't think we do at this point. Again I'm used to Rails where those rules are used EVERYWHERE and so you need them configured app-wide.

> ^^ I thought the "rule" was for model names to only be singular?

That's the syntax that Prisma shows in their schema-from-scratch examples, but there's nothing stopping someone from putting whatever they want for the model name. I haven't checked the docs for this in a while, but one of their other big examples is introspecting an existing DB and converting to Prisma, and in that example the table names are all lowercase and plural.

**Comment by thedavidprice** [comment]
@cannikin Ah, makes sense across the board. Especially the "introspecting" case.

**Comment by billsaysthis** [comment]
I agree with the two part approach, the problem has bit me again today.

**Comment by bennettrogers** [comment]
I don't know if this is possible, but what if the pluralized version didn't rely on hard-to-generalize rules of English, but instead just appended some string to the model name? I'm not sure where all the pluralized version is used, but instead of trying to go from `pokemon` --> `pokemans`, could it just be `pokemon` --> `pokemonList`?

A very similar issue came up in the CRUD function generators for `nexus-plugin-prisma` where they are trying to use the `pluralize` package. There is an [issue](https://github.com/graphql-nexus/nexus-plugin-prisma/issues/537) open to address it, and one [recommendation](https://github.com/graphql-nexus/nexus-plugin-prisma/issues/537#issuecomment-667515753) is to do what Prisma apparently decided to do, which was to switch from trying to explicitly pluralize the model names to instead using e.g. `pokemon.findOne()` and `pokemon.findMany()`.

**Comment by cannikin** [comment]
A quick fix could be to just compare the output of `pluralize` with the input. If they're the same (in the case of `pokemon`) then just append an "s" and continue with life as usual. We could add a warning in the console output letting the user know we did that if it happens.

**Comment by thedavidprice** [comment]
^^ @forresthayes here you go 🚀

**Comment by Tobbe** [comment]
How about using "list" for the plural form here as well, to keep it consistent with how the cell case is handled?

Like if you generate sdl for "news":

```
type Query {
  newsList: [News!]!
  news(id: Int!): News
}
```

**Comment by cannikin** [comment]
> I'm pretty sure you're already aware but to confirm - appending an `s` in rare cases like `News`, it will generate `Newss`. Looks weird but this is acceptable to me as a quick fix.

We could say that if the word already ends in "s" then append "es" instead. Not that "Newses" is grammatically any better, but at least it doesn't sound like a snake is saying it!

In a perfect world, we'd let people decide beforehand! Like once the CLI command detects that "pluralize package says that the singular and plural versions are identical" then we prompt the user and ask them what they would want to use for singular and plural.

```
Generating scaffold...

Hmm, English is weird so I can't figure out how to turn 
"News" into a singular or plural version. Can you help?

The singular of "News" should be [News]: _
The plural of "News" should be [Newses]: _
```

The square brackets denoting what the default would be if you just press `Enter`.

In Rails there's a config file where you determine ahead of time what you want to do for irregular pluralizations:

```ruby
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.plural /^(ox)$/i, '\1\2en'
  inflect.singular /^(ox)en/i, '\1'

  inflect.irregular 'octopus', 'octopi'

  inflect.uncountable 'equipment'
end
```

The pluralize package we're using does have a similar config:

```javascript
pluralize.singular('singles') //=> "single"
pluralize.addSingularRule(/singles$/i, 'singular')
pluralize.singular('singles') //=> "singular"
```

But it depends on users knowing that they're going to have an irregular pluralization and knowing to fill out the config ahead of time. I like the idea of just prompting them on the command line for what they want to use, and then we use that for the remainder of the generation.

**Comment by thedavidprice** [comment]
Thank you @callingmedic911 Grateful for your help with this one! Yes, please, this is long overdo for being fixed. And a two-step (or PR) process might be appropriate as well: 1) quick fix 2) make it good

@dthyresson You mentioned having to solve a lot of this for Cells recently (or something like that if I recall). Could you please offer insights if/as applicable?

Appreciate everyone's help here!

**Comment by dthyresson** [comment]
> You mentioned having to solve a lot of this for Cells recently (or something like that if I recall). Could you please offer insights if/as applicable?

We only have to handle a GraphQL Operation Name and either a single item or multiple item rendered -- so we could do `Find_Model_By_Id` and Models (whatever the plural was) and the append "List" for the control.

So, we could side step the plural issue.

**Comment by callingmedic911** [comment]
> How about using "list" for the plural form here as well, to keep it consistent with how the cell case is handled?

Certainly more consistent, however, so far `model`/`name` is one word and having two words probably would require changes at a few more places.

> We could say that if the word already ends in "s" then append "es" instead. Not that "Newses" is grammatically any better, but at least it doesn't sound like a snake is saying it!

👍👍 

> I like the idea of just prompting them on the command line for what they want to use, and then we use that for the remainder of the generation.

Just to highlight, so far I haven't seen anything interactive with Redwood CLI, that's why I wanted to check if having interactive CLI will have any challenges. For example, if I want to throw-in a couple of rw command in a shell script, it would a bit more challenging to manage, probably will have to use something like `expect`.
Do you think even if we have interactive inputs from the user, should we keep the flags like --plural and --singular to avoid such issue?

And... we'd probably need something like [inquirer](https://www.npmjs.com/package/inquirer).

> And a two-step (or PR) process might be appropriate as well: 1) quick fix 2) make it good

How about this? :
As a quick fix: let's go with modifying the original word to either s or es like @cannikin suggested when executing generators (sdl, service, scaffold).

Meanwhile, we can discuss here which route we want to take for the long run. Even though I haven't deep-dived into complexity with what @Tobbe and @cannikin have suggested, I'd be glad to implement it whichever one we finalize will result in a good experience.

**Comment by cannikin** [comment]
We actually do have an interactive generator now! Check out the setup/auth command—it looks to see if you already have an auth.js file in your project and asks if you want to replace it. It was easier than I thought it would be, there’s a package that handles all the formatting and answer types, it’s great.

**Comment by pdjota** [comment]
could it make sense to extract the `nameVariants` from `packages/cli/src/lib/index.js` which is used in templates e.g. `singularPascalName` so we override the if only once?

**Comment by callingmedic911** [comment]
> We actually do have an interactive generator now! Check out the setup/auth command—it looks to see if you already have an auth.js file in your project and asks if you want to replace it. It was easier than I thought it would be, there’s a package that handles all the formatting and answer types, it’s great.

@cannikin Great! `prompts` looks very similar to `inquirer`. Trying it out, I've couple of finding, will raise WIP PR.

> could it make sense to extract the `nameVariants` from `packages/cli/src/lib/index.js` which is used in templates e.g. `singularPascalName` so we override the if only once?

@pdjota I think adding a `pluraize` rule (like @cannikin shared earlier) would require overall least change, because as soon as rule is added, pluralize will return custom word for that generator run.
