### ISSUE TITLE
[Bug?]:  Installing Redwood on Windows 10 Freezes it

### ISSUE THREAD

**Issue by Gresliebear** [redwoodjs/redwood#6856]
### What's not working?

CPU 100% uilitiznation 

and its took  277.74s. to complete 

```


------------------------------------------------------------------
🌲⚡️ Welcome to RedwoodJS! ⚡️🌲
------------------------------------------------------------------
√ Use TypeScript? ... no
✔ Creating Redwood app
  ✔ Checking node and yarn compatibility
  ✔ Creating directory 'E:\VTKRW\VTKRedwood\vtkrw3'
✔ Installing packages
  ✔ Running 'yarn install'... (This could take a while)
✔ Convert TypeScript files to JavaScript
✔ Generating types

Thanks for trying out Redwood!

 ⚡️ Get up and running fast with this Quick Start guide: https://redwoodjs.com/docs/quick-start
Join the Community

 ❖ Join our Forums: https://community.redwoodjs.com
 ❖ Join our Chat: https://discord.gg/redwoodjs

Get some help

 ❖ Get started with the Tutorial: https://redwoodjs.com/docs/tutorial
 ❖ Read the Documentation: https://redwoodjs.com/docs

Stay updated

 ❖ Sign up for our Newsletter: https://www.redwoodjs.com/newsletter
 ❖ Follow us on Twitter: https://twitter.com/redwoodjs

Become a Contributor ❤

 ❖ Learn how to get started: https://redwoodjs.com/docs/contributing
 ❖ Find a Good First Issue: https://redwoodjs.com/good-first-issue

Fire it up! 🚀

 > cd ./vtkrw3
 > yarn rw dev

Done in 277.74s.
```

### How do we reproduce the bug?

yarn create redwood-app ./redwood app

### What's your environment? (If it applies)

```shell
System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 16.14.0 - ~\AppData\Local\Temp\xfs-ed8b8c85\node.CMD
    Yarn: 3.2.3 - ~\AppData\Local\Temp\xfs-ed8b8c85\yarn.CMD
  Browsers:
    Chrome: 107.0.5304.106
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.35)
  npmPackages:
    @redwoodjs/core: 3.3.1 => 3.3.1
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Gresliebear** [comment]
PS E:\VTKRW\VTKRedwood\vtkrw3> yarn rw dev     
Internal Error: root-workspace-0b6124@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at OR.getCandidates (E:\VTKRW\VTKRedwood\vtkrw3\.yarn\releases\yarn-3.2.3.cjs:435:5209)
    at Bd.getCandidates (E:\VTKRW\VTKRedwood\vtkrw3\.yarn\releases\yarn-3.2.3.cjs:391:1281)
    at E:\VTKRW\VTKRedwood\vtkrw3\.yarn\releases\yarn-3.2.3.cjs:439:7764
    at Tg (E:\VTKRW\VTKRedwood\vtkrw3\.yarn\releases\yarn-3.2.3.cjs:390:11154)
    at ce (E:\VTKRW\VTKRedwood\vtkrw3\.yarn\releases\yarn-3.2.3.cjs:439:7744)

**Comment by simoncrypta** [comment]
Hi @Gresliebear do you use `git-bash `or `WLS2` to run Redwood ? 

You can check the recommend [Windows Development Setup](https://redwoodjs.com/docs/how-to/windows-development-setup)

Installing packages take some time and resources, so depend on your computer and internet is normal that is taking some time.

Tell me if that help :)

**Comment by Gresliebear** [comment]
> Hi @Gresliebear do you use `git-bash `or `WLS2` to run Redwood ?
> 
> You can check the recommend [Windows Development Setup](https://redwoodjs.com/docs/how-to/windows-development-setup)
> 
> Installing packages take some time and resources, so depend on your computer and internet is normal that is taking some time.
> 
> Tell me if that help :)

I have both of those installed but I did not use them for this set up

My hardware is good, & internet 500 mpbs so i dont think its that

**Comment by simoncrypta** [comment]
> I have both of those installed But I did not use them for this set up


Using one of those will probably solve the problem, using node with CMD is not recommended since it have a lot of issue and is not POSIX compatible.

**Comment by simoncrypta** [comment]
@Gresliebear I'm closing this issue for now. Feel free to reopen if it still freezes with git-bash or WSL.
