### ISSUE TITLE
yarn rw g scaffold post, is missing tests files(layouts, pages and cells)

### ISSUE THREAD

**Issue by guledali** [redwoodjs/redwood#686]
https://github.com/redwoodjs/redwood/tree/master/packages/cli/src/commands/generate/scaffold/templates

- [ ] Layout missing test file
- [ ] Page missing test file
- [ ] Cell is missing test file

Individually they all have test files in them, just not when you run the `yarn rw g scaffold` command. So we can just copy them into scaffold folder.

Cell: https://github.com/redwoodjs/redwood/blob/master/packages/cli/src/commands/generate/cell/templates/test.js.template
 

Pages:
https://github.com/redwoodjs/redwood/blob/master/packages/cli/src/commands/generate/page/templates/test.js.template

Layout
https://github.com/redwoodjs/redwood/blob/master/packages/cli/src/commands/generate/layout/templates/test.js.template

**Comment by jtoar** [comment]
@guledali Thanks for noticing this. @AryanJ-NYC brought this up as well in issue #603. As @cannikin said there, the reason we don't have tests is we haven't figured out the best way to test cells, GraphQL, and Prisma yet. But this is probably also going to have to wait for the generator refactor, which is being discussed in #653.

Moreover, we probably won't just copy the files over. Ideally, the tests for scaffolds will be one of the ways we show off Redwood's testing package and some best practices for it.

**Comment by guledali** [comment]
@jtoar I'm closing this issue then

**Comment by thedavidprice** [comment]
@guledali thanks for making sure this was on our radar! Always appreciate your help.
