### ISSUE TITLE
[Bug?]: GraphiQL headers is not working

### ISSUE THREAD

**Issue by zaiyou12** [redwoodjs/redwood#6894]
### What's not working?

Following the [setup graphiQL headers](https://redwoodjs.com/docs/cli-commands#setup-graphiql-headers) in official document, but it doesn't work in local. DbAuth all works fine in local and production, only graphiql (Redwood graphql playground) doesn't work.

![Screenshot 2022-11-14 at 9 45 56 PM](https://user-images.githubusercontent.com/17160208/201663704-a303585f-1267-49f7-b00c-cab99274984a.png)

Here is the log in context:

```bash
api | 21:44:52 🌲 incoming request POST xxx /graphql
api | 21:44:52 🐛 Parsing request to extract GraphQL parameters
api | 21:44:52 🌲 request completed 29ms
api | 21:44:52 🐛 Processing GraphQL Parameters
api | 21:44:52 🚨 graphql-server Error building context. Error: Exception in getAuthenticationContext: Cannot read properties of undefined (reading 'id')
```

### How do we reproduce the bug?

1. Follow [dbAuth](https://redwoodjs.com/docs/auth/dbauth) document
2. Setup [GraphiQL header](https://redwoodjs.com/docs/cli-commands#setup-graphiql-headers)
3. Open `http://localhost:8911/graphql` in browser

```bash
yarn redwood setup auth dbAuth

## Set up user and userCredentials...

yarn redwood setup graphiql dbAuth

yarn rw dev
```

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 13.0.1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - /private/var/folders/g5/gjrvbjr91g37mz5qzbnxncpr0000gn/T/xfs-0896ea29/node
    Yarn: 3.2.1 - /private/var/folders/g5/gjrvbjr91g37mz5qzbnxncpr0000gn/T/xfs-0896ea29/yarn
  Databases:
    SQLite: 3.39.4 - /usr/bin/sqlite3
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 16.1
  npmPackages:
    @redwoodjs/core: ^3.2.0 => 3.2.0
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by dthyresson** [comment]
Hi @zaiyou12 ...

Did you  

`yarn redwood setup graphiql dbAuth --view --id <yourid>`

as per the docs:

> Unique id to identify current user (required only for DBAuth)`

?

**Comment by zaiyou12** [comment]
Hi @dthyresson , 

Yes, I ran the script as the docs and the `request headers` on the screenshot was generated. 

Below is the actual script that I ran and the header generated from the script.

```bash
yarn redwood setup graphiql dbAuth --view --id 3
```

```json
{
  "auth-provider": "dbAuth",
  "cookie": "session=U2Fs...",
  "authorization": "Bearer 3"
}
```
