### ISSUE TITLE
Using generate sdl --force removed singular model find

### ISSUE THREAD

**Issue by csellis** [redwoodjs/redwood#698]
I had created my schema before, then added a relationship and regenerated.

```
// schema.prisma
...
model Prize {
  id               Int      @id @default(autoincrement())
  name             String
  imageUrl         String
  lessonsNeeded    String
  lessonsCompleted String
  createdAt        DateTime @default(now())
  lessons          Lesson[]
}

model Lesson {
  id            Int      @id @default(autoincrement())
  name          String
  prizeId       Int
  prize         Prize    @relation(fields: [prizeId], references: [id])
  dateCompleted DateTime
  createdAt     DateTime @default(now())
}
```

Forcing SDL generate changed **prizes.sdl.js** from:
```
export const schema = gql`
  type Prize {
    id: Int!
    name: String!
    imageUrl: String!
    lessonsNeeded: String!
    lessonsCompleted: String!
    createdAt: DateTime!
  }

  type Query {
    prizes: [Prize!]!
    prize(id: Int!): Prize!
  }

  input CreatePrizeInput {
    name: String!
    imageUrl: String!
    lessonsNeeded: String!
    lessonsCompleted: String!
  }

  input UpdatePrizeInput {
    name: String
    imageUrl: String
    lessonsNeeded: String
    lessonsCompleted: String
  }

  type Mutation {
    createPrize(input: CreatePrizeInput!): Prize!
    updatePrize(id: Int!, input: UpdatePrizeInput!): Prize!
    deletePrize(id: Int!): Prize!
  }
```
To:
```
export const schema = gql`
  type Prize {
    id: Int!
    name: String!
    imageUrl: String!
    lessonsNeeded: String!
    lessonsCompleted: String!
    createdAt: DateTime!
    lessons: Lesson
  }

  type Query {
    prizes: [Prize!]!
  }

  input CreatePrizeInput {
    name: String!
    imageUrl: String!
    lessonsNeeded: String!
    lessonsCompleted: String!
  }

  input UpdatePrizeInput {
    name: String
    imageUrl: String
    lessonsNeeded: String
    lessonsCompleted: String
  }
```

It looks like it also dropped the mutation.

What have I done wrong folks?

**Comment by thedavidprice** [comment]
Hi @csellis! This is a strange one indeed -- thanks for creating the Issue.

Looping in @cannikin who's our MasterofGenerators™. 😉

Few questions:
- could you reply with a copy+paste of your system information via running `yarn rw info`?
- is there a chance you originally generated this SDL file with one version of Redwood, then upgraded and ran the `g sdl <model> --force`?
- when you originally generated this file, did you use the SDL or the Scaffold (i.e. CRUD) generator?

Lastly, wanted to confirm you're still able to move forward with manual fixes for now, correct?

**Comment by csellis** [comment]
@thedavidprice Hi! I was thrown off to begin with.


```
yarn rw info
System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.16.3 - /tmp/yarn--1592265682147-0.9240075440922317/node
    Yarn: 1.21.1 - /tmp/yarn--1592265682147-0.9240075440922317/yarn
  Databases:
    SQLite: 3.22.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 76.0.1
  npmPackages:
    @redwoodjs/core: ^0.8.2 => 0.8.2 
```

I did not upgrade between running the scaffolding, then generating the SDL.

So I ran scaffold to begin with, then realized I hadn't included the relationship. Updated the schema, and db up'd it. Then I performed `g sdl <model> --force`.

I was able to go in and update my service with
```
export const prize = ({ id }) => {
  return db.prize.findOne({
    where: { id },
  })
}
```

It may be a case of cognitive tunneling. I was so focused on having it just generated that I forgot I could go in and do it myself. 
## :man_facepalming:

It's still very strange and took me a while to realize the singular service had been removed.

**Comment by cannikin** [comment]
When you generate a scaffold it adds a flag `--crud` to the end of the SDL generator. If you run the SDL generator yourself, but leave off that flag, you'll get the generated output you saw above (no create/update/delete mutations, and just a single "select all" query).

**Comment by csellis** [comment]
Ahh, I didn't see that in the documentation. I just added it.

**Comment by thedavidprice** [comment]
Just commented on your doc update as well -- thanks again and apologies for the missing documentation!
