### ISSUE TITLE
Signup duplication

### ISSUE THREAD

**Issue by fakkio** [redwoodjs/redwood#6988]
### What's not working?

Hi 👋🏼,

during signup with authdb authentication, rw checks for duplication in the username (i.e. email), but I think, the username check should be case insensitive. 

### How do we reproduce the bug?

GitPod snapshot: https://gitpod.io#snapshot/61447fb9-8e28-4093-a1ee-b7f0dc65f6e2

try to sigup with email@example.com and then with Email@example.com. You can signup without any problem.

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by ageddesi** [comment]
I would be interested in working on this by adding .toLowerCase on the checks.

**Comment by thedavidprice** [comment]
This is effectively a duplicate of https://github.com/redwoodjs/redwood/issues/7787 At the very least it would be best to combine efforts. @fakkio do take a look at some suggestions there as well.

@ageddesi could you join the conversation on #7787 and offer thoughts/help based on the discussion so far? @ched-dev is looking for feedback/suggestions. And both Rob and Tobbe are out this week.

Zero pressure either way. Closing this out.
