### ISSUE TITLE
[Bug?]: CSS bundling when serving different from dev

### ISSUE THREAD

**Issue by razzeee** [redwoodjs/redwood#7000]
### What's not working?

Setting toasts to dark mode via tailwind.

It seems to work in dev `yarn rw dev`, but if you run it via serve `yarn rw serve` it changes behavior and won't render correctly.

https://github.com/timolins/react-hot-toast/issues/242

### How do we reproduce the bug?

You should be able to use any redwood project with tailwind, then:

- Use this for your toast
```tsx
 <Toaster
          position="top-right"
          toastOptions={{
            className:
              'bg-white text-black dark:bg-black dark:text--white rounded-2xl shadow-md',
          }}
          containerStyle={{
            top: 76,
            right: 24,
            bottom: 24,
            left: 24,
          }}
        />
```
- A loading button is useful to see it for longer
```
<button onClick={() => toast.loading('loading')}>Click me</button>
```
- Serve it via dev and check it in dark mode
- Serve it via serve and check it in dark mode

### What's your environment? (If it applies)

```shell
System:
    OS: Linux 6.0 Fedora Linux 37 (Workstation Edition)
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - /tmp/xfs-1acbe224/node
    Yarn: 3.3.0 - /tmp/xfs-1acbe224/yarn
  Databases:
    SQLite: 3.40.0 - /usr/bin/sqlite3
  Browsers:
    Firefox: 107.0
  npmPackages:
    @redwoodjs/core: ^3.5.0 => 3.5.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by razzeee** [comment]
Pushed a repro repo here https://github.com/razzeee/redwood-toast-repro

**Comment by dac09** [comment]
This is likely caused by tailwind's optimisations during production.

You can probably get around this by adding those dark classes to your safelist: https://tailwindcss.com/docs/content-configuration#safelisting-classes

**Comment by razzeee** [comment]
Tried that, and it doesn't seem to help. It would also be pretty weird, as those classes are already used all over the project, it's just in the toast where it's not working in prod.

**Comment by razzeee** [comment]
Well, for what it's worth, it's now consistent between dev and deploy. Will close.
