### ISSUE TITLE
Error after upgrade: Cannot find module 'graphql-type-json'

### ISSUE THREAD

**Issue by Terris** [redwoodjs/redwood#709]
I've just upgraded using the CLI command, i.e. `yarn rw upgrade`.

After running `yarn rw dev`, the terminal logs read:

```
yarn run v1.22.4
$ /Users/terriskremer/Sites/redwood/redwood-shop/node_modules/.bin/rw dev
$ /Users/terriskremer/Sites/redwood/redwood-shop/node_modules/.bin/dev-server
$ /Users/terriskremer/Sites/redwood/redwood-shop/node_modules/.bin/webpack-dev-server --config ../node_modules/@redwoodjs/core/config/webpack.development.js
api | Running at 'http://localhost:8911'
api | Watching files in '/Users/terriskremer/Sites/redwood/redwood-shop/api/src/functions'
web | ℹ ｢wds｣: Project is running at http://localhost:8910/
web | ℹ ｢wds｣: webpack output is served from /
web | ℹ ｢wds｣: Content not from webpack is served from /Users/terriskremer/Sites/redwood/redwood-shop/web
web | ℹ ｢wds｣: 404s will fallback to /index.html
api | 
api | Error: Cannot find module 'graphql-type-json'
api | Require stack:
api | - /Users/terriskremer/Sites/redwood/redwood-shop/node_modules/@redwoodjs/api/dist/makeMergedSchema/rootSchema.js
api | - /Users/terriskremer/Sites/redwood/redwood-shop/node_modules/@redwoodjs/api/dist/makeMergedSchema/makeMergedSchema.js
api | - /Users/terriskremer/Sites/redwood/redwood-shop/node_modules/@redwoodjs/api/dist/main.js
api | - /Users/terriskremer/Sites/redwood/redwood-shop/api/src/functions/graphql.js
api | - /Users/terriskremer/Sites/redwood/redwood-shop/node_modules/require-dir/index.js
api | - /Users/terriskremer/Sites/redwood/redwood-shop/node_modules/@redwoodjs/dev-server/dist/watchApiSide.js
api | - /Users/terriskremer/Sites/redwood/redwood-shop/node_modules/@redwoodjs/dev-server/dist/main.js
api | 
api | 
api | 1 anonymous
api |   /Users/terriskremer/Sites/redwood/redwood-shop/node_modules/@redwoodjs/api/src/makeMergedSchema/rootSchema.ts:5
api | 
api | 2 Module._compile
api |   /Users/terriskremer/Sites/redwood/redwood-shop/node_modules/pirates/lib/index.js:99
api | 
api | 3 Object.newLoader [as .js]
api |   /Users/terriskremer/Sites/redwood/redwood-shop/node_modules/pirates/lib/index.js:104
api | 
api | Function "graphql" was not found.
api | POST /graphql 404 3.650 ms - 33
```

And browser console reads:

```
POST http://localhost:8910/.netlify/functions/graphql 404 (Not Found)
```

**Comment by peterp** [comment]
Could you try to run `yarn --check-files` to re-install the node_modules, since `graphql-type-json` is referenced here: https://github.com/redwoodjs/redwood/blob/master/packages/api/package.json#L21

**Comment by Terris** [comment]
@peterp - Thanks for the quick response! Sadly, running this command did not fix the issue as I'm still getting the same output. Strangely enough, I also just fired up a brand new redwood app and am experiencing the same issue.

**Comment by thedavidprice** [comment]
@Terris could you paste the output from `yarn rw info` in reply?

Also, any chance you have multiple node versions or environments running at the same time?

I'll try a fresh install myself to see if I can reproduce. Lastly, I heard NPMJS.org had an outage yesterday... could have messed up things somehow. ¯\_(ツ)_/¯

BRB

**Comment by Terris** [comment]
@thedavidprice - thank you for helping! I've done a restart and checked that I'm only running one node version/env. All seems well there. 

```
$ yarn rw info

System:
    OS: macOS Mojave 10.14.6
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.11.1 - /var/folders/s3/jyccmmxs11j893bfb92tt0900000gn/T/yarn--1592421547364-0.747396037582372/node
    Yarn: 1.22.4 - /var/folders/s3/jyccmmxs11j893bfb92tt0900000gn/T/yarn--1592421547364-0.747396037582372/yarn
  Databases:
    SQLite: 3.24.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 83.0.4103.106
    Firefox: 74.0
    Safari: 13.1.1
  npmPackages:
    @redwoodjs/core: ^0.10.0 => 0.10.0 
```

**Comment by thedavidprice** [comment]
Blast. I can't reproduce locally, which means there's likely something system-level going on. Tom is running MacOS 10.14 as well and occasionally runs into issues with packages not being installed... none of us can figure it out. Just frustrating. And `git clean -fxd` or `yarn install --force` just never seems to help things.

Ideas:
- you might try upgrading Node to latest 12.18.1
- turn things "on" and "off" (the good ol' restart...)
- if you _downgrade_ from v0.10.0, do you still have the problem?

**Comment by Terris** [comment]
@peterp @thedavidprice Thank you both for jumping in to help. It looks as though the problem stems from the local redwoodjs development I've been doing. When I switch to the master branch and rebuild redwood (via `yarn rebuild:watch`) the issue goes away.

I don't know why I can't get the packages to align in my development branch as I've merged in master, double checked the package is up to date, force installed, etc.. I may just need to start from scratch.

Anyhow, this issue is definitely my own so I'll close this issue. Thanks again and I apologize for the time I've taken from you.
