### ISSUE TITLE
RW v4 canary: Nicer dbAuth config api

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#7106]
This is how dbAuth is setup in RW v3:

```tsx
const App = () => (
  <FatalErrorBoundary page={FatalErrorPage}>
    <RedwoodProvider titleTemplate="%PageTitle | %AppTitle"> 
      <AuthProvider type="dbAuth">
        <RedwoodApolloProvider>
          <Routes />
        </RedwoodApolloProvider>
      </AuthProvider>
    </RedwoodProvider>
  </FatalErrorBoundary>
)
```

For adding CORS config you do this:

```tsx
<AuthProvider
  type="dbAuth"
  config={{ fetchConfig: { credentials: 'include' } }}
>
```

Switching to RW v4, you setup dbAuth like this:

```ts
import { createDbAuth } from '@redwoodjs/auth-dbauth-web'

export const { AuthProvider, useAuth } = createDbAuth()
```

For adding CORS config you do this:

```ts
import { createDbAuth } from '@redwoodjs/auth-dbauth-web'

export const { AuthProvider, useAuth } = createDbAuth(null, { fetchConfig: { credentials: 'include' }})
```
And that's not very nice (the first `null` argument). We need to come up with something better.

The reason it's that way is that all the other auth providers take the auth client as the first parameter to `createXyzAuth()`, and it's required. Like auth0 for example:

```ts
const auth0 = new Auth0Client({
  domain: process.env.AUTH0_DOMAIN || '',
  client_id: process.env.AUTH0_CLIENT_ID || '',
  redirect_uri: process.env.AUTH0_REDIRECT_URI,
  cacheLocation: 'localstorage',
  audience: process.env.AUTH0_AUDIENCE,
})

export const { AuthProvider, useAuth } = createAuth0Auth(auth0)
```

For dbAuth, the "client" is webAuthn (if you choose to set that up):

```ts
import { createDbAuth } from '@redwoodjs/auth-dbauth-web'
import WebAuthnClient from '@redwoodjs/auth-dbauth-web/webAuthn'

export const { AuthProvider, useAuth } = createDbAuth(new WebAuthnClient())
```

So only for dbAuth is the client optional.

- [x] I'm interested in working on this

**Comment by Tobbe** [comment]
I see two options right now, but I'm open to other ideas as well

1. Create a separate `createDbAuthn` function that creates the webAuthn client internally. That way both functions only take the config option, and you never have to "pad" the argument list with `null` or `undefined`
2. Add the webAuthn client as an option on the config object. So if you want to add webAuthn support you do `createDbAuth({ webAuthn })`. This also makes it so the function only takes one argument and you don't need to "pad" the arg list.

Both options make the setup of dbAuth more different to the other providers. But it already was different, so maybe that's not too bad

**Comment by dac09** [comment]
There's also a third option, right? Which is extracting the dbAuth client (packages/auth-providers/dbAuth/web/src/dbAuth.ts) and passing it in? Like the other auth providers. This should make it perfectly in-line with the other auth providers

**Comment by Tobbe** [comment]
Yes. Could do that too.
Then we'd have something like this in `dbAuth.ts`
```ts
function createDbAuthAuthImplementation(dbAuth: DbAuth) {
  return {
    ...dbAuth,
    type: 'dbAuth',
    getUserMetadata: dbAuth.getToken,
  }
}
```

Or we make `type` and `getUserMetadata` part of `DbAuth` too (unlike any other auth provider), and skip `createDbAuthAuthImplementation` altogether. Would have to make `dbAuth.client` be a WebAuthn instance for the code above to work too.
