### ISSUE TITLE
[RFC]: change in seed.ts template - hashPassword remark in 'seed.ts' tempalte

### ISSUE THREAD

**Issue by wiezmankimchi** [redwoodjs/redwood#7128]
### Summary

The current remark in the `seed.ts` template is:
`// import { hashPassword } from '@redwoodjs/auth-providers-api'`
and it should changed to:
`// import { hashPassword } from '@redwoodjs/api'`.

as if implemented as is, you will get an error:
`Error in script: Cannot find module '@redwoodjs/auth-providers-api'
Require stack:
- /Users/wiezmankimchi/dev/car-fleet-manager/scripts/seed.ts
- /Users/wiezmankimchi/dev/car-fleet-manager/node_modules/@redwoodjs/cli/dist/lib/exec.js
- /Users/wiezmankimchi/dev/car-fleet-manager/node_modules/@redwoodjs/cli/dist/commands/execHandler.js
- /Users/wiezmankimchi/dev/car-fleet-manager/node_modules/@redwoodjs/cli/dist/commands/exec.js
- /Users/wiezmankimchi/dev/car-fleet-manager/node_modules/@redwoodjs/cli/dist/index.js
- /Users/wiezmankimchi/dev/car-fleet-manager/node_modules/@redwoodjs/cli/package.json`

### Motivation

corrected template

### Detailed proposal

remove 
`// import { hashPassword } from '@redwoodjs/auth-providers-api'`
add
`// import { hashPassword } from '@redwoodjs/api'`

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by jtoar** [comment]
Hey @wiezmankimchi, you're right. Now that we've fully decoupled the auth providers, it should actually be:

```ts
import { hashPassword } from '@redwoodjs/auth-dbauth-api
```

You can make that change if you're still up for it, but no pressure.

**Comment by dthyresson** [comment]
@jtoar I believe the seed template in main has already been updated.

https://github.com/redwoodjs/redwood/blob/99fce77e01198cddd1fcea83453f25562952e280/packages/create-redwood-app/template/scripts/seed.ts#L41

Perhaps this is a release notes item to update seeds (or use of this import?).

**Comment by jtoar** [comment]
@dthyresson yeah you're right—and good call, definitely belongs in the release notes.

**Comment by jtoar** [comment]
I got this wrong—the existing comment doesn't look right to me.

**Comment by Tobbe** [comment]
Confirming that the current comment is wrong
![image](https://user-images.githubusercontent.com/30793/214144723-2238767e-304d-4b03-baa5-81b3e5cd00b3.png)

Here's the proper import
![image](https://user-images.githubusercontent.com/30793/214145020-582aede5-9979-4ca1-9c0e-35d965aa6850.png)

@wiezmankimchi Do you want to create a PR with the fix, or should I do it? I don't mind either way, so totally up to you 🙂
