### ISSUE TITLE
[Bug?]: Generator fails if [name] positional argument is '/'

### ISSUE THREAD

**Issue by pantheredeye** [redwoodjs/redwood#7136]
### What's not working?

Generating a page with '/' as the value causes problems. 

It would be good to have a check to prevent '/' from being used here.

### How do we reproduce the bug?

`yarn rw g page /`

outputs 

```
✔ Generating page files...
  ✔ Successfully wrote file `./web\src\pages\CProgramFilesGitPage\CProgramFilesGitPage.stories.tsx`
  ✔ Successfully wrote file `./web\src\pages\CProgramFilesGitPage\CProgramFilesGitPage.test.tsx`
  ✔ Successfully wrote file `./web\src\pages\CProgramFilesGitPage\CProgramFilesGitPage.tsx`
✔ Updating routes file...
⠹ Generating types...
◼ One more thing...
Error parsing: .../web/src/pages/CProgramFilesGitPage/CProgramFilesGitPage.tsx
SyntaxError: Unexpected token, expected "}" (15:26)
```

Also it creates this route:

`<Route path="/c-program-files-git" page={CProgramFilesGitPage} name="c:/programFiles/git/" />`

Also, `yarn rw d page /` fails to clean it up and the files/folders and route need to be manually deleted.

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by cannikin** [comment]
I think we just need a check that the `[name]` positional argument to these generators can't start with a `/`. This would be used in any generator that creates a file:

* cell
* component
* dataMigration
* directive
* function
* layout
* model
* page
* scaffold
* script
* sdl
* service

**Comment by pantheredeye** [comment]
@cannikin - this does not catch / for me. I checked the pattern in a regex debugger and the / matches. But, our CLI tool doesn't prevent us from submitting a page with /...

```
$ yarn rw g page /test
← Reverted because: Unexpected token, expected "}" (15:27)
13 |       <p>
14 |         My default route is named <code>c:/programFiles/git/test</code>, link to me with `
15 |         <Link to={routes.c:/programFiles/git/test()}>CProgramFilesGitTest</Link>`
|                           ^
16 |       </p>
17 |     </>
18 |   )
◼ Updating routes file...
◼ Generating types...
◼ One more thing...
```
and 
```
$ yarn rw g page /
← Reverted because: Unexpected token, expected "}" (15:27)
13 |       <p>
14 |         My default route is named <code>c:/programFiles/git/</code>, link to me with `
15 |         <Link to={routes.c:/programFiles/git/()}>CProgramFilesGit</Link>`
|                           ^
16 |       </p>
17 |     </>
18 |   )
```

with other special characters the helper catches it:

```
$ yarn rw g page .
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Error: The <name> argument must start with a letter, number or underscore.
    at validateName (C:\Users\bburnworth\Documents\Code\aiWorkers\node_modules\@redwoodjs\cli\dist\commands\generate\helpers.js:144:11)
    at Object.handler (C:\Users\bburnworth\Documents\Code\aiWorkers\node_modules\@redwoodjs\cli\dist\commands\generate\page\page.js:161:35)
```

Is this worth opening as a minor issue or something?

**Comment by pantheredeye** [comment]
strange because i'm guessing [the tests must be passing](https://github.com/redwoodjs/redwood/blob/78cced0c997d23a05c633dc49fb05864c6c1a4f9/packages/cli/src/commands/generate/__tests__/helpers.test.js#L548)...


```
describe('validateName', () => {
  it('throws an error if name starts with an invalid character', () => {
    expect(() => helpers.validateName('/')).toThrow()
```

**Comment by cannikin** [comment]
We do allow `/` in the name, so you can generate in a subdirectory, but having it *start* with a `/` wasn't intended. I guess the regex needs an update! I wonder if that test checked against `/test`it would fail (maybe just `/` alone is sneaking through somehow)...

Yeah we should open an issue and mark it `good first issue` see if anyone picks it up!

**Comment by pantheredeye** [comment]
Yeah, the first codeblock i posted when[ i necro'd this thread](https://github.com/redwoodjs/redwood/issues/7136#issuecomment-2313360254) shows /test failing

```
$ yarn rw g page /test
← Reverted because: Unexpected token, expected "}" (15:27)
13 |       <p>
14 |         My default route is named <code>c:/programFiles/git/test</code>, link to me with `
15 |         <Link to={routes.c:/programFiles/git/test()}>CProgramFilesGitTest</Link>`
|                           ^
16 |       </p>
17 |     </>
18 |   )
◼ Updating routes file...
◼ Generating types...
◼ One more thing...
```
I'll convert to an issue! 👍
