### ISSUE TITLE
Default to 'cache-and-network' Apollo policy

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#717]
I propose that we set a default caching strategy of `cache-and-network` in the `beforeQuery` function of cells:

```javascript
export const beforeQuery = (props) => {
  return { variables: props, fetchPolicy: 'cache-and-network' }
}
```

As the [Apollo docs](https://www.apollographql.com/docs/react/api/react-apollo/#optionsfetchpolicy) say:

> This fetch policy will have Apollo first trying to read data from your cache. If all the data needed to fulfill your query is in the cache then that data will be returned. However, regardless of whether or not the full data is in your cache this fetchPolicy will always execute query with the network interface unlike cache-first which will only execute your query if the query data is not in your cache. This fetch policy optimizes for users getting a quick response while also trying to keep cached data consistent with your server data at the cost of extra network requests.

Otherwise when you make a change to data via a mutation, navigate away and then return, you still see stale data forever (Apollo cached it for you). Using this fetchPolicy will always use the cache to display the component, but then immediately make a network request to get the fresh data and rerender the component if it has changed.

I feel like this is the expected behavior 95% of the time, and we should optimize for the most common and expected behavior.

**Comment by peterp** [comment]
Sounds super reasonable to me
