### ISSUE TITLE
Transitioning to "main" default branch

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#718]
On Friday, June 19th, we are initiating a transition to use "main" as the default branch across all RedwoodJS Organization repositories on GitHub. All steps will be handled primarily by the core maintainers.

For more information on this change as well as background, please see [this Form topic](https://community.redwoodjs.com/t/transitioning-to-main-default-branch/776).

### Steps
1. Create a new branch `main` from the current `master`
2. Switch GitHub repository settings to use `main` as the default
3. For each open PR, edit and change the target from `master` to `main`†
4. Change GH Actions to use `main` where applicable
5. Lastly, delete the `master` branch

† as needed, maintainers will coordinate with each PR author if additional steps are required — for most PRs, however, the transition should be seamless

### Repos
- [x] [redwood](https://github.com/redwoodjs/redwood)
    - GH Actions, Netlify
- [x] [awesome-redwood](https://github.com/redwoodjs/awesome-redwood)
- [x] [redwoodjs.com](https://github.com/redwoodjs/redwoodjs.com) @cannikin 
    - Netlify
- [x] [playground-auth](https://github.com/redwoodjs/playground-auth) @peterp 
    - Netlify
- [x] [create-redwood-app](https://github.com/redwoodjs/create-redwood-app) @thedavidprice 
- [x] [example-blog](https://github.com/redwoodjs/example-blog) @peterp 
    - Netlify
- [x] [example-todo](https://github.com/redwoodjs/example-todo) @peterp 
    - Netlify
- [x] [example-invoice](https://github.com/redwoodjs/example-invoice) @peterp 
    - Netlify
- [x] [cookbook-third-party-apis](https://github.com/redwoodjs/cookbook-third-party-apis) @cannikin 
- [x] [netlify-plugin-prisma-provider](https://github.com/redwoodjs/netlify-plugin-prisma-provider) @cannikin 
    - will this effect connection to Netlify marketplace?

**Comment by thedavidprice** [comment]
@cannikin @peterp @mojombo 
Does anyone know what happens to github links after we make this transition? E.g. will the following link still work if we delete 'master'?

https://github.com/redwoodjs/redwood/blob/master/CODE_OF_CONDUCT.md

**Comment by cannikin** [comment]
😬 I would guess not? It's probably the same behavior if you try to go to any old branch URL that's since been deleted...

**Comment by thedavidprice** [comment]
### Update
The steps are complete for all repos at this time.

However, we are leaving `master` active on `redwoodjs/redwood`, `redwoodjs/create-redwood-app`, and `redwoodjs/redwoodjs.com` for a few more days to let the dust settle on any nuanced issues and to work on transitioning links to files.

**Comment by thedavidprice** [comment]
Checked and updated permalinks across Framework, CRA, and .com repos.

Team decided to archive (not delete) `master` at this time. Concern is losing permalinks externally on Slack, Discord, Forums, and Twitter. Fingers crossed this is something GitHub is working on resolving for their own org transition. In the meantime, I set up a branch protection rule for `master` effectively blocking commits.

**Comment by cannikin** [comment]
@thedavidprice Should we do the same thing for the other repos?

**Comment by thedavidprice** [comment]
@cannikin 

re: permalinks -- I _can_ think of instances where files and code for the Example Apps are being referenced (e.g. the Forum). So it would make sense to keep master around.

But I think we can safely delete master branch for:
- awesome-redwood
- playground-auth 
- cookbook-third-party-apis
- netlify-plugin-prisma-provider

Want me to effectively "lock" master on the example apps? I can delete master from the others, too, with the exception of letting Peter make the call on playground-auth.

**Comment by cannikin** [comment]
Sounds good to me!

**Comment by thedavidprice** [comment]
Done. Branch settings applied across the board. I deleted master for those mentioned above.

@peterp I'll let you handle deleting 'master' branch on playground-auth.
