### ISSUE TITLE
Guide/Explanation: How to think in Services

### ISSUE THREAD

**Issue by benjaminsehl** [redwoodjs/redwood#722]
In the Frontend First podcast, @mojombo gave a great breakdown of services (starts at 22:57, [link to episode](https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5zaW1wbGVjYXN0LmNvbS9zT0pBTW9oUA/episode/ZmI4MTAwNzEtYTAwYS00ZWNmLWI2OTctNDg0NjNlN2U1ZWFi?hl=en-CA&ved=2ahUKEwjkqpmG-o3qAhWllHIEHSo6B6oQieUEegQICxAG&ep=6)).

As he’s describing services, there is confusion around the scope of what a service would cover (in the discussed scenario, a "billings" service wouldn't include "users" which Tom clarifies would likely be a separate service).

**At the 26:52 mark, Tom says:**
> Think from the very beginning, architecturally, about your application, as a collection of services. If you start there, then as your app gets more complex, you can eventually tease your services apart if they get to big. You could turn one service into three, where you separate out the SDL from the GraphQL into a couple of different things, and then your services turn into two or three or whatever it needs to be. It allows you to isolate those things, and when a person is working on the billings service, they know what their area of responsibility is, they know how to act with things outside of it through other services. So if you need to update a user from your billings service, then you know how to do it — you know you're not going to go straight to the table, you're going to go through another service. 

At about 40m in, Tom goes into a bit more detail into how to think in services. In the current docs, there is a quick idea about it [in the cli-commands doc](https://redwoodjs.com/docs/cli-commands#generate-service), and then more nuance in the ['how redwood works with data'](https://redwoodjs.com/tutorial/side-quest-how-redwood-works-with-data) doc.

Perhaps just me — but would be very helpful for a doc/guide/video/rant into how to think in services and 'the redwood way'. Especially for those of us that are coming from backgrounds with less exposure to this idea. How to separate concerns at different sizes of an application (i.e. when to use one service, vs. breaking it into three).

If these concepts are taught well in other resources already, perhaps just links to those references would suffice — I don't know whether the mental models of Redwood application architecture are exclusive to Redwood, and if not, would love to have a "further reading/how to think" resource, but if so, this kind of documentation would be super helpful to me as someone coming from a frontend background and now moving to fullstack (thanks in large part to Redwood and similar frameworks like Next).

**Comment by jtoar** [comment]
@benjaminsehl Thank you for all the awesome and well-linked content in your comment. And it's definitely not just you. You got it exactly right with that blurb from the podcast. I think that bit really made people (myself included) want to know everything and more about services.

While I can't point you to any resources, I can assure you that docs are on the way! 

Actually maybe there's one resource I can point you: How Buildings Learn by Stewart Brand (tagging @cannikin cause I saw him tweet about it recently). One of the fundamental components of a building is its services:

![rw-stewart-brand](https://user-images.githubusercontent.com/32992335/85159857-e0451280-b212-11ea-9493-999b8361da4b.png)

So maybe we can think of services in a Redwood app like those in a building? The web-equivalents of water, electricity... (Might have to do more reading on this too. :sweat_smile:)

**Comment by jtoar** [comment]
Closed by https://github.com/redwoodjs/redwoodjs.com/pull/857. Definitely check out the new docs here: https://redwoodjs.com/docs/services.
