### ISSUE TITLE
Name component files .jsx instead of .js

### ISSUE THREAD

**Issue by YeapGuy** [redwoodjs/redwood#734]
Hey, I'm new around Redwood, and this is my first issue, so please don't be harsh on me.

I think that since Redwood is so naming opinionated, it should use the .jsx extension for React component files instead of .js.
This helps differentiate those files at the first sight and also helps IDEs understand them (like enabling Emmet abbreviations).

**Comment by thedavidprice** [comment]
Hi @YeapGuy! One thing I can tell you about the Redwood community is that we're never harsh on anyone! (Even when it really seems like someone deserves it 😆). Just happy to be here and stoked you are too. Truly.

I'm surprised you're the first to bring this up. And the "Emmet abbreviation" case makes sense for sure. You _can_ use `.jsx` in your app if you'd like -- you'll have to change or not use the RW Generators -- if you:
- rename files
- change imports from things like `import BlogLayout from 'src/layouts/BlogLayout'` to `import BlogLayout from 'src/layouts/BlogLayout/BlogLayout.jsx'`
    - Wondering why you have to add both the file name and extension and not just the extension? There's a Webpack setting for Redwood that handles looks for .js files of the same name as the directory -- but we might be able to add the `.jsx` extension to this behavior 🤔

In the near term, I don't think there's much momentum to make this change for JavaScript Redwood Applications. But we are working on full support for TypeScript and currently the generated files are `.tsx`, which might end up moving this conversation along as well.

**Comment by YeapGuy** [comment]
I see. Thanks a lot for the kind welcome as well as detailed explanation, although I don't think it's worth for me to go over all the hassle just to get a few IDE features and _fancy icons in VSCode:_
![image](https://user-images.githubusercontent.com/43749899/85520976-e61c6880-b603-11ea-8c66-557d21d7973c.png)

And about TypeScript: if you're planning to use .tsx files, it would make sense to use .jsx, at least for consistency. So I'll wait for TypeScript support and see 😉.

**Comment by cannikin** [comment]
I was under the impression that JSX was just the JS-as-HTML syntax that makes up components, like:

```jsx
<div className="mt-1 hidden md:block relative">
  <Tags tags={contact.tags} />
</div>
```

But all of our components are actual Javascript, usually containing at least one function that happens to *return* JSX. In that case I think the extension should remain `.js` since that's what they contain. 

If you wanted to store the JSX in a separate file and then import it and return it, I could see those separate files being `.jsx` since that's all they contain.

**Comment by YeapGuy** [comment]
`.jsx` is just like `.tsx`, but for plain old JavaScript. `.tsx ` also obviously contains non-JSX syntax, the X at the end is just supposed to show it contains some JSX elements to help the parser, IDE or whatever else processes the code somehow, @cannikin.

**Comment by cannikin** [comment]
All Tailwind, all the time! Building entire sites and not writing any custom CSS...

![Relaxing frog](https://media.giphy.com/media/9u1J84ZtCSl9K/giphy.gif)

**Comment by peterp** [comment]
I personally don't think this distinction is helpful - since you might have a file that's mostly just javascript but has a tiny little bit of JSX in it and then you have to name it JSX.

**Comment by YeapGuy** [comment]
I think that's how it should be - that is how it works with TypeScript anyway. Naming every file which contains JSX `.jsx`, helps to distinguish between files which interact with the DOM and utility files - e.g. API calls.

This topic is definitely opinionated, but I wanted to see what the people of Redwood think about this, as I prefer the `.jsx` and `.tsx` naming scheme personally.

**Comment by mikebobadilla** [comment]
I just use `.jsx` so vscode automatically enables emmet without me having to change it in the dropdown.
![2020-12-18 12 58 47](https://user-images.githubusercontent.com/5985141/102661000-da33de00-4130-11eb-853b-101164eeb29c.gif)

**Comment by wminshew** [comment]
jsx seems like the right extension here to me from an IDE perspective, even if it's only a "small" amount (is there a downside I'm not aware of to using the jsx extension? bc the downside to using js is that my IDE doesn't recognize/colorize the jsx fragments. Maybe your IDEs are smarter than mine and so it seems like a trivial request?)

ps tailwind 4 lyfe

**Comment by thedavidprice** [comment]
### Update
Per Core Team discussion, we are going to default generators to use `.jsx` while allowing `.js`. Benefits:
- consistent with TS .tsx
- leverages code editors and extensions that target .jsx specifically

**Comment by dthyresson** [comment]
Questions for @peterp @dac09 @thedavidprice should:

* Routes be jsx/tsx or js/ts
* App be jsx/tsx or js/ts
* Generated stories be jsx/tsx or js/ts

Will keep:

* tests as ts/js
* cell mocks as ts/js

**Comment by Tobbe** [comment]
I think an easy "rule" for this would be: Anything that's .tsx in a Typescript project should be .jsx in a Javascript project (and anything that's .ts should be .js)

That means it should be Routes.jsx for example.

**Comment by thedavidprice** [comment]
I agree with @Tobbe's logic about this. Keep'n it simple.

**Comment by peterp** [comment]
And then when we use modules we name them .mjsx

**Comment by thedavidprice** [comment]
> And then when we use modules we name them .mjsx

Ha! Please don't let this ever be a thing... 🤦‍♂️

**Comment by peterp** [comment]
Want to note my opposition to this decision.

I think we're operating under false assumptions, and here's why: The reason why the `.tsx` extension exists is because TypeScript and JSX share similar syntax.

JSX Unfriendly: `<Type>expression` vs. JSX Friendly: `expression as Type`
JSX Unfriendly: `<T>(x: T) => x` vs. JSX Friendly: `<T extends unknown>(x: T) => x`

So, it's technical debt because these two syntaxes step on each other's toes?

React themselves do not recommend the use the JSX extension:
https://github.com/facebook/create-react-app/issues/87#issuecomment-234627904

VSCode actually treats `javascript` and `javascriptreact` the same. The language definition files are identical. So you do not get any additional syntax support when using `.js` vs. `.jsx`: https://github.com/microsoft/vscode/issues/82793

My recommendation is to let this linger for a short while to see what TypeScript does with JavaScript modules.

**Comment by Tobbe** [comment]
And just to be clear: I don't have a strong opinion or preference either way (js vs jsx), but \*if\* we decide to name some files .jsx, then I'd like to use my "rule" posted previously.

**Comment by YeapGuy** [comment]
@peterp Yeah, .tsx exists for exactly that reason - it isn't standard TS and needs to be treated specially. Just like files with JSX aren't standard JS and need to be treated specially. The .jsx extension tells you that you can't throw it in a standard JS compiler and expect it to work.

About VSC treating it the same: VSC isn't the only editor, and even if it was, the benefit isn't just syntax highlighting. If you have separate extensions for JS and JSX, you can specify separate snippets & Emmet abbreviations and you also get distinctive icons (which you may think is purely cosmetic, but it can really help finding the right file visually). Then you can also search for the files with the right extension (or filter by them in a search & replace or whatever).

Anyway, yay! I'm happy to see my issue had some effect!

**Comment by peterp** [comment]
> Just like files with JSX aren't standard JS and need to be treated specially. The .jsx extension tells you that you can't throw it in a standard JS compiler and expect it to work.

I do not think that "Standard JS" (that can be thrown into a JS compiler) is a concept that actually exists in modern frontend JavaScript development? I cannot think of any instances where I've written JS (for the browser) without transpilation in the last several years.

RedwoodJS is transpiled, and we are a React based framework.
The recommendation from React is to use `.js` and not `.jsx`:

1. Next.js uses `.js`
2. Gatsby uses `.js`
3. create-react-app uses `.js`

So why are we going against that recommendation?

Regarding the editor: They're configurable. I would actually assume that if you're going against the recommendations, and what the majority of frameworks are doing, then we're going to have to do _more_ configuration than less.

**Comment by dthyresson** [comment]
I have to say I cannot see the overwhelming advantage of `.jsx` at this time and the changes it requires.

I vote to keep `.js` as per:

> RedwoodJS is transpiled, and we are a React based framework.
> The recommendation from the React team is to use .js and not .jsx:

On the topic of 

> you can specify separate snippets & Emmet abbreviations and you also get distinctive icons (which you may think is purely cosmetic, but it can really help finding the right file visually). 

The work on the RedwoodJS IDE can help here via its organization and outline -- although, yes, VSCode only.

Can we close out this issue?

**Comment by dthyresson** [comment]
@thedavidprice can I get a verdict to close out and *not* use .jsx. Thanks.

**Comment by thedavidprice** [comment]
Let's ping @mojombo about this since it was a group discussion/decision involving him. (I can do that.)

For me VS Code language support was the primary rationale. If there's no difference, then I'm pretty meh about making a change.

Thanks for going further into the details @peterp

**Comment by thedavidprice** [comment]
**Update:** @mojombo agrees with @peterp So closing this out. Carry on @dthyresson!

Also, modules are going to be a thing... Wha?? 😬
