### ISSUE TITLE
Prisma did not initialize yet, expected?

### ISSUE THREAD

**Issue by corymcdonald** [redwoodjs/redwood#743]
👋 Apologies if this has been answered somewhere, I saw this issue pop up in some upgrades but wanted to document that it is happening following the normal "Starting development flow"

On a brand new clean install of RedwoodJS following the document guide below
https://redwoodjs.com/tutorial/installation-starting-development

I run into the following issue when running the server for the first time 

```sh
yarn run v1.22.4
$ /Users/cory/repos/redwoodblog/node_modules/.bin/redwood dev
$ /Users/cory/repos/redwoodblog/node_modules/.bin/webpack-dev-server --config ../node_modules/@redwoodjs/core/config/webpack.development.js
$ /Users/cory/repos/redwoodblog/node_modules/.bin/dev-server
api | Running at 'http://localhost:8911'
api | Watching files in '/Users/cory/repos/redwoodblog/api/src/functions'
web | ℹ ｢wds｣: Project is running at http://localhost:8910/
web | ℹ ｢wds｣: webpack output is served from /
web | ℹ ｢wds｣: Content not from webpack is served from /Users/cory/repos/redwoodblog/web
web | ℹ ｢wds｣: 404s will fallback to /index.html
api |
api | Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
api | In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
api |
api | at /Users/cory/repos/redwoodblog/api/src/lib/db.js(anonymous):6
api | 1  // See https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/api.md#constructor
api | 2  // for options.
api | 3
api | 4  import { PrismaClient } from '@prisma/client'
api | 5
api | 6  export const db = new PrismaClient()
api | 7
api |
api | 1 new PrismaClient
api |   /Users/cory/repos/redwoodblog/node_modules/.prisma/client/index.js:3
api |
api | 2 Module._compile
api |   /Users/cory/repos/redwoodblog/node_modules/pirates/lib/index.js:99
api |
api | 3 Object.newLoader [as .js]
api |   /Users/cory/repos/redwoodblog/node_modules/pirates/lib/index.js:104
api |
```

**Comment by corymcdonald** [comment]
Running the solution here worked for me - https://github.com/redwoodjs/redwood/issues/726

Should this be part of the initialization for a new project?

**Comment by thedavidprice** [comment]
Hi @corymcdonald! Thank you for checking in about this and sorry for the hassle. The intended use is for `yarn rw dev` to work out of the box regardless of Prisma already being generated. Last release included some updates per Prisma improvements, but we ended up breaking things.

We have a fix for this that's coming in our next release (v0.12.0), which should be out tomorrow.

Closing this issue, but please don't hesitate to reopen or even start a topic on our Forum if/as needed https://community.redwoodjs.com

**Comment by corymcdonald** [comment]
Thanks David! Really appreciate it.
