### ISSUE TITLE
[Bug]: Type generator throws an un-related error if two cell queries have the same name

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#7444]
### What's not working?

If you accidentally have two cell queries with the same name, the type generator throws an error from the `@graphql-codegen` package about a function not being a constructor, rather than our own which may actually explain what the problem was:

```terminal
% yarn rw g types

Generating...

Error: Could not generate GraphQL type definitions (web)
TypeError: plugin_helpers_1.DetailedError is not a constructor
    at /Users/rob/Sites/spoke/node_modules/@graphql-codegen/core/cjs/codegen.js:209:19
    at Array.forEach (<anonymous>)
    at validateDuplicateDocuments (/Users/rob/Sites/spoke/node_modules/@graphql-codegen/core/cjs/codegen.js:188:11)
    at /Users/rob/Sites/spoke/node_modules/@graphql-codegen/core/cjs/codegen.js:16:40
    at /Users/rob/Sites/spoke/node_modules/@graphql-codegen/plugin-helpers/cjs/profiler.js:7:49
    at async codegen (/Users/rob/Sites/spoke/node_modules/@graphql-codegen/core/cjs/codegen.js:16:9)
    at async runCodegenGraphQL (/Users/rob/Sites/spoke/node_modules/@redwoodjs/internal/dist/generate/graphqlCodeGen.js:123:18)
    at async generateTypeDefGraphQLWeb (/Users/rob/Sites/spoke/node_modules/@redwoodjs/internal/dist/generate/graphqlCodeGen.js:94:12)
    at async generateTypeDefs (/Users/rob/Sites/spoke/node_modules/@redwoodjs/internal/dist/generate/typeDefinitions.js:47:18)
    at async generate (/Users/rob/Sites/spoke/node_modules/@redwoodjs/internal/dist/generate/generate.js:17:25)
````

Ideally this would actually inform you of what the problem actually was (duplicate query name) and would be even better if it give you one of the files that had an identical name (if not list all of them).

It may actually be trying to do this, but the `DetailedError` class is messed up for some reason, and so you don't get to see the real message.

/cc @dac09 as he witnessed this happening!

### How do we reproduce the bug?

Create two cells and give them the same name. Run `yarn rw g types`

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Hey @cannikin, could you confirm you still see this issue? I just tried locally with the test project. I duplicated a cell, gave them the same name and then modified one of the queries so they aren't the same. The result of `yarn rw g types` was the following:

<img width="1061" alt="image" src="https://github.com/redwoodjs/redwood/assets/56300765/06fae34f-d0b0-40dc-9e52-a2addb7c0776">

I think that error is probably as clear as we could hope for. 

Maybe there are more conditions need to replicate this error obfuscation?

**Comment by cannikin** [comment]
I’ll take a look again, I feel like this was a while ago! We may have improved that error message since and I forgot I had opened this!On Oct 7, 2023, at 9:30 AM, Josh GM Walker ***@***.***> wrote:﻿
Hey @cannikin, could you confirm you still see this issue? I just tried locally with the test project. I duplicated a cell, gave them the same name and then modified one of the queries so they aren't the same. The result of yarn rw g types was the following:

I think that error is probably as clear as we could hope for.
Maybe there are more conditions need to replicate this error obfuscation?
