### ISSUE TITLE
[RFC]: service validators exclusion and inclusion should be case-insensitive or have option

### ISSUE THREAD

**Issue by taivo** [redwoodjs/redwood#7482]
### Summary

From what I can see in Redwood version 3.8, the service validators `exclusion` and `inclusion` are case sensitive. Because of that, the following validation code

```
validate(input.name, 'Name', {
  exclusion: ['Admin', 'Owner']
})
```

would not be able to catch case variations such as `admin` or `owner`.

Imo, these validators would be much more useful and see more adoption if they just work in a case-insensitive manner. Another alternative is to introduce a case-sensitivity flag to the option list.

### Motivation

From a usability standpoint, `exclusion` and `inclusion` validators should be case-insensitive or have an boolean option to be so.

### Detailed proposal

This applies to the `exclusion` and `inclusion` service validators on the API side. 

My current understanding is that changes will only involve a few lines in this file https://github.com/redwoodjs/redwood/blob/main/packages/api/src/validations/validations.ts

Implementation should be fairly trivial but consensus is needed first on whether we're choosing options:

1. Just make them case-insensitive
or
2. Introduce a `caseInsensitive` option.

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by jtoar** [comment]
Thanks @taivo, I'll get @cannikin to look at this one next week.

**Comment by cannikin** [comment]
I'm okay with adding a case-insensitive option, but I think case sensitivity should be defaulted to ON. If you're specifying a list of things that *must* or *must not* exist, you're already being very specific, and I feel like case sensitivity enabled is in the spirit of being specific.

This validation is most likely to be used as the result of picking something from a `<select>` where the options will be set in stone already, so you know what they're likely to be. And defaulting to case sensitivity makes extra sense here, as your backend is probably expecting very specific values, and someone hacking the value to be `ADMIN` instead of `admin` could have bad consequences!

**Comment by taivo** [comment]
Ah ok, I see your point of view. I was mimicking the docs and adapted the usage for username instead of names in order to filter out a shortlist of troll usernames that would come from a text field. I guess my thinking was primed toward that use case.

I think case-sensitive by default would work well and avoid backward compatibility issue for existing users. I can whip up a PR to help with this in a few days. Right now I'm thinking the option name would be `caseInsensitive` and defaults to `false`. Lmk if you have a different preferred name for this option.

**Comment by jtoar** [comment]
@taivo will let Rob chime in, but Tom usually wants the option to be phrased positively, in the sense that it'd be `caseSensitive: true`, not `caseInsensitive: false`, cause it's just a bit harder to figure out if it's on or off.

**Comment by taivo** [comment]
I had some spare time over the weekend to code up a draft. It's ready for review, has tests, and ready to be merged if you guys agree with the implementation. It's PR #7573 and it uses your suggested `caseSensitive: true` convention @jtoar 

P.S. I'm not a fan of the utility function I ended up writing to share between exclusion and inclusion (something about it tells me it's not the cleanest possible implementation) but it's what I could do with the bit of spare time I had. If you can think of a clearer way to express what we want, lmk.

**Comment by jtoar** [comment]
Thanks @taivo I'll try to review today
