### ISSUE TITLE
[Bug?]: Type generator FAILS when using GraphQL fragments if the query is NOT returned from a function

### ISSUE THREAD

**Issue by arimendelow** [redwoodjs/redwood#7491]
### What's not working?

When attempting to create reusable query fragments, as in the [Apollo docs](https://www.apollographql.com/docs/react/data/fragments/#example-usage), if you try to declare your query as a variable directly, it fails.

This does NOT work:
```typescript
export const SHORT_INFO = gql`
  fragment ShortInfo on Model {
    id
    ...
  }
`

export const QUERY = gql`
  ${SHORT_INFO}
  query ExampleQuery($id: String!) {
    parentModel: parentModel(id: $id) {
      id
      models {
        model {
          ...ShortInfo
        }
      }
    }
  }
`
```

This DOES work:
```typescript
export const SHORT_INFO = gql`
  fragment ShortInfo on Model {
    id
    ...
  }
`

export const QUERY = () => {
  return gql`
    ${SHORT_INFO}
    query ExampleQuery($id: String!) {
      parentModel: parentModel(id: $id) {
        id
        models {
          model {
            ...ShortInfo
          }
        }
      }
    }
  `
}
```

The error thrown is as follows:
```
▶ yarn rw g types

Generating...

/Users/arimendelow/Documents/code/sj/spoonjoy/node_modules/graphql/error/syntaxError.js:15
  return new _GraphQLError.GraphQLError(`Syntax Error: ${description}`, {
         ^

GraphQLError: Syntax Error: Unexpected <EOF>.
    at syntaxError (/Users/arimendelow/Documents/code/sj/spoonjoy/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.unexpected (/Users/arimendelow/Documents/code/sj/spoonjoy/node_modules/graphql/language/parser.js:1458:41)
    at Parser.parseDefinition (/Users/arimendelow/Documents/code/sj/spoonjoy/node_modules/graphql/language/parser.js:212:16)
    at Parser.many (/Users/arimendelow/Documents/code/sj/spoonjoy/node_modules/graphql/language/parser.js:1511:26)
    at Parser.parseDocument (/Users/arimendelow/Documents/code/sj/spoonjoy/node_modules/graphql/language/parser.js:122:25)
    at parse (/Users/arimendelow/Documents/code/sj/spoonjoy/node_modules/graphql/language/parser.js:32:17)
    at parseGqlQueryToAst (/Users/arimendelow/Documents/code/sj/spoonjoy/node_modules/@redwoodjs/internal/dist/gql.js:18:34)
    at generateMirrorCell (/Users/arimendelow/Documents/code/sj/spoonjoy/node_modules/@redwoodjs/internal/dist/generate/typeDefinitions.js:102:48)
    at /Users/arimendelow/Documents/code/sj/spoonjoy/node_modules/@redwoodjs/internal/dist/generate/typeDefinitions.js:79:86
    at Array.map (<anonymous>) {
  path: undefined,
  locations: [ { line: 2, column: 3 } ],
  extensions: [Object: null prototype] {}
}
rw g types

Generate supplementary code

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  --cwd      Working directory to use (where `redwood.toml` is located)

Error: Command failed with exit code 1: yarn rw-gen
    at makeError (/Users/arimendelow/Documents/code/sj/spoonjoy/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/Users/arimendelow/Documents/code/sj/spoonjoy/node_modules/execa/index.js:194:17)
    at Object.handler (/Users/arimendelow/Documents/code/sj/spoonjoy/node_modules/@redwoodjs/cli/dist/commands/generate.js:18:18)
    at /Users/arimendelow/Documents/code/sj/spoonjoy/node_modules/yargs/build/index.cjs:1:8891
    at /Users/arimendelow/Documents/code/sj/spoonjoy/node_modules/yargs/build/index.cjs:1:4949
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: yarn rw-gen',
  command: 'yarn rw-gen',
  escapedCommand: '"yarn rw-gen"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by jtoar** [comment]
@arimendelow I've confirmed this; curiously, inlining the fragment works:

```graphql
export const QUERY = gql`
  fragment ShortInfo on UserExample {
    id
  }

  query FindUserExampleQuery($id: Int!) {
    userExample: userExample(id: $id) {
      ...ShortInfo
    }
  }
`
```

**Comment by jtoar** [comment]
I think I've got a lead as to why this is happening... it's the function here:

https://github.com/redwoodjs/redwood/blob/5ec571f0461e472c459e0b9d2bf9595d5a3b1d20/packages/internal/src/ast.ts#L109-L137

But also the way type generation works I think. I still need to confirm this, but I don't think the file is evaluated, it's just read, so the template literal never gets evaluated and we end up trying to parse/generate types from a string like `'\n   \n'`.

@arimendelow you mentioned you'd be interested in helping—this one is a bit involved, still feel up for it?

**Comment by arimendelow** [comment]
Right I did notice that too - that it does work if you include the fragment in the same `gql`. But then you can't reuse it :/

Sure! :) I'm sure I'll need some guidance, but it would be cool to peek under the hood and understand some of the magic that's happening here.

**Comment by jtoar** [comment]
@arimendelow ok, let me try to lay out what's happening a bit. When you run `yarn rw g types`, here's the file that it's running: https://github.com/redwoodjs/redwood/blob/main/packages/internal/src/generate/generate.ts.

The chain of events is
- `yarn rw g types` -> `node node_modules/@redwoodjs/internal/dist/generate/generate.js`
- then in that file, the stack is something like `run` -> `generate` -> `generateTypeDefs` 

`generateTypeDefs` does a lot of work, but only one of the `generate*` functions is failing here, `generateMirrorCells`. It fails specifically here:

https://github.com/redwoodjs/redwood/blob/546a6c456a5984403a99715c01a3c9ddefee3121/packages/internal/src/generate/typeDefinitions.ts#L121

I'm pretty sure I wrote that `parseGqlQueryToAst` function, so if I can be a bit self deprecating, I'm not surprised there's an edge case here.

You may need some kind of GraphQL ast explorer to help you through that one. It'll give you the chance to look at the specifics of a GraphQL, which may be cool! But if this all sounds like too much don't worry haha. Hope this kind of helps though, and feel free to ask me anything if you want to give it a shot.

**Comment by cannikin** [comment]
This is happening to me on Spoke as well, we're using fragments as suggested in the Apollo docs!

**Comment by arimendelow** [comment]
> This is happening to me on Spoke as well, we're using fragments as suggested in the Apollo docs!

Yeah! And thanks @jtoar for the context!

**Comment by keeganthomp** [comment]
+1 here

It seems as though fragments, when in their own `gql` tag, are ignored by codegen. The codegen runs successfully with the below and produces no errors at the time of graphql type generation. However, the fragment is "unknown" when trying to use said fragment in a query. (_Redwood core version 4.3.1_)

For clarity, I get `graphql-server Unknown fragment TestFragment` in the CLI  when executing the following `SearchArtistsAndBands ` query (`artists` is an array of `User`'s):

```
export const TEST_FRAGMENT = gql`
  fragment TestFragment on User {
    id
    username
  }
`

export const ARTISTS_AND_BANDS_SEARCH = gql`
  query SearchArtistsAndBands($searchTerm: String!) {
    searchArtistsAndBands(searchTerm: $searchTerm) {
      artists {
        ...TestFragment
      }
    }
  }
`
```
Adding the fragment in the same gql tag as the `QUERY` (`ARTISTS_AND_BANDS_SEARCH`)  works as @jtoar illustrated above.
However, as @arimendelow mentioned, these fragments cannot be reused which defeats the purpose of fragments.

That said, very much enjoying Redwood overall. If this gets resolved, will be absolutely heavenly :)

**Comment by KrasniqiR** [comment]
I've run into this as well. Really enjoying Redwood so far however this is somewhat of a blocker for us. We render many feeds of polymorphic content, thus need to re-use fragments in many places. Our current workaround is just pasting the fragments into the first line of every query, which is extremely brittle but we're under some time pressure at the moment.

Hopefully I can find some time over a weekend to investigate this and possibly contribute.

**Comment by dthyresson** [comment]
Fixed in https://github.com/redwoodjs/redwood/pull/9140
