### ISSUE TITLE
Determine why production CSS isn't minified

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#753]
https://community.redwoodjs.com/t/production-webpack-builds-css-incorrectly/803/2

**Comment by thedavidprice** [comment]
Adjacent issue: "CSS import order differs between dev and prod" #549

**Comment by dac09** [comment]
Bump. This seems to still be an issue, hadn't noticed because I had optimisations enabled on netlify. 

I can definitely see the unminified CSS, and maps generated.
