### ISSUE TITLE
Implement authentication client for a non supported third party API

### ISSUE THREAD

**Issue by xeloader** [redwoodjs/redwood#755]
The current situation requires us to use a third party authentication api for one of our projects.

I'm wondering if it's possible to implement our own authentication client, that is completely custom for us. We would like to use the `Private` routes and `useAuth` hook throughout the project without having to use `react-router` for example.

Is it possible? I looked through the documentation for `Authentication` but could only find examples of implementing netlify, firebase or Auth0. What we want to do is to create and adapt for a third party api and utilize the built in authentication methods. 

Thank you for working on redwood, looking forward to future updates and follow along on this journey.

**Comment by jtoar** [comment]
Hey @xeloader thanks for trying out Redwood.

I'm pretty sure it's possible. The way we're able to support multiple providers already is via its plug-in architecture, so I think the idea is you'd basically following the instructions in the auth's [contributing section](https://redwoodjs.com/docs/authentication#contributing) without actually make it a part of redwood (that is, submitting a PR).

You might find this topic in the forum to be a better resource, it's really in-depth:

- [Custom github JWT Auth with Redwood Auth [Advice needed] 
](https://community.redwoodjs.com/t/custom-github-jwt-auth-with-redwood-auth-advice-needed/610)

It might also be helpful to look at the PRs for magic link and firebase which are the providers we most recently added (thanks to the community!):

- firebase: https://github.com/redwoodjs/redwood/pull/593 (generator: https://github.com/redwoodjs/redwood/pull/643)
- magic.link: https://github.com/redwoodjs/redwood/pull/562 (generator: https://github.com/redwoodjs/redwood/pull/644)

We also have a lot more docs incoming for auth, namely a cookbook on getting the database involved: https://github.com/redwoodjs/redwoodjs.com/issues/212.

**Comment by pi0neerpat** [comment]
Howdy @xeloader ! In case you're still working on this, I recently wrote a tutorial on custom auth. Let me know if it helps, and good luck! https://community.redwoodjs.com/t/custom-auth-web3-ethereum/1618
