### ISSUE TITLE
Use react-query for data fetching

### ISSUE THREAD

**Issue by willopez** [redwoodjs/redwood#758]
Hello, wondering if there are any plans for supporting [react-query](https://github.com/tannerlinsley/react-query) for data fetching? I have encountered issues with Apollo Client and its cache. Further, react-query reduces the amount of client-side state management necessary which reduces complexity.

**Comment by peterp** [comment]
Hey @willopez, funny you should mention this, we're busy exploring ideas around replacing Apollo's Client for exactly the reasons you mentioned, and because we want to offer a smaller bundle size.

**Comment by willopez** [comment]
@peterp great to hear, and the big bundle size of Apollo Client is another reason I don't like it. Also [SWR](https://github.com/vercel/swr) seems like a good library as well.

**Comment by redbar0n** [comment]
FWIW, here is a useful comparison of Apollo Client, React Query, SWR, and Relay: [https://react-query-git-ce4fe79195bc3c2d81a564e80473188eb00f62e8.tannerlinsley.vercel.app/docs/comparison](https://react-query-git-ce4fe79195bc3c2d81a564e80473188eb00f62e8.tannerlinsley.vercel.app/docs/comparison)

**Comment by jtoar** [comment]
@willopez Just to follow up, although Redwood still ships with Apollo Client, you can use any GraphQL client you want. Moreover, if you don't import the RedwoodApolloProvider, it won't be included in your bundle! There's even this awesome package provided by @marceloalves to use react-query with Redwood https://www.npmjs.com/package/redwoodjs-react-query-provider.

**Comment by jtoar** [comment]
We've had some internal discussions recently about adding another client, opting for [urql](https://formidable.com/open-source/urql/). (We haven't made any headway on that yet though.) So closing this just for transparency, but we should definitely decouple things more.
