### ISSUE TITLE
Adding Snyk To Redwood.js

### ISSUE THREAD

**Issue by Burnsy** [redwoodjs/redwood#759]
Whilst using Snyk VS Code Vulnerability scanning tool ([link here](https://snyk.io/security-scanner-vuln-cost/)), it shown me that there are a few vulnerability in redwood.

one example
![CleanShot 2020-06-26 at 18 09 38](https://user-images.githubusercontent.com/15834048/85883036-39471480-b7d8-11ea-8760-4005057b6723.png)

The tool has free tier but to what I understand an open source project can have unlimited scans and fixes. 

Snky scans all NPM packages in the repo for vulnerability. So as you can guess how important this is because as a framework you don't want to pass them vulnerability to the user base if it can be avoided.

Any questions please ask!

**Comment by thedavidprice** [comment]
[Dependabot](https://dependabot.com/)! (Now owned by GitHub)

Mohsen has been helping out with setup beyond GitHub standard security alerts: https://github.com/redwoodjs/redwood/pull/752

I’ve just been delayed to pull the trigger this week -- I'm taking time offline on vacation and didn't want to turn it one if I'm not here to clean up any potential mess 😬

Care to help us out as resident Dependabot expert?? (no pressure as always 😀)

**Comment by Burnsy** [comment]
@thedavidprice Yes, I noticed Dependabot and that's why I also said about integration of Snyk as its another dev ops tool as well as its also to do with security of the project! 

Yes snky does do dendency upgrade it also scans all dependencies for venerabilities  and can managed a automatic patch of them dependencies. 

I will tag @lirantal  in this topic as he is there node security expert for snky!  

as to my point, The API may have one security vulnerability that could not be fixed by simplify upgrading the version of the package but may need a manual patch that synk has already created. 

I believe all of these tools are free on open source projects. so it might be worth just looking fully into it  :) 

there is also some great projects that have came out from @lirantal such as 

- [https://github.com/lirantal/lockfile-lint](https://github.com/lirantal/lockfile-lint)
- [https://github.com/lirantal/is-website-vulnerable](https://github.com/lirantal/is-website-vulnerable)
