### ISSUE TITLE
[Bug?]: SyntaxError: Unexpected token '??=' after upgrade to Redwood 4 + changed engine to node > 16

### ISSUE THREAD

**Issue by schybo** [redwoodjs/redwood#7597]
### What's not working?

👋 Currently trying to deploy to Flightcontrol per usual after upgrading to Redwood 4. Seems like it's not liking the null coalescing assignment [here](https://github.com/redwoodjs/redwood/blame/8529ef8ff48f4fb2b4c5c4b81fd5a0f0359d7fe4/packages/cli/src/index.js#L60) that has only gained support in node > 15. I added `"node": ">=16.x <=18.x",` under engines to my `package.json` but it still doesn't seem to be functional.

```
[Container] 2023/02/08 23:11:47 Running command (yarn rw deploy flightcontrol web)
6:11:48 PM: /codebuild/output/src513646770/src/node_modules/@redwoodjs/cli/dist/index.js:63
6:11:48 PM: cwd ??= process.env.RWJS_CWD;
6:11:48 PM:     ^^^
6:11:48 PM: 
6:11:48 PM: SyntaxError: Unexpected token '??='
6:11:48 PM:     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
6:11:48 PM:     at Module._compile (internal/modules/cjs/loader.js:1049:27)
6:11:48 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
6:11:48 PM:     at Module.load (internal/modules/cjs/loader.js:950:32)
6:11:48 PM:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
6:11:48 PM:     at Module.require (internal/modules/cjs/loader.js:974:19)
6:11:48 PM:     at require (internal/modules/cjs/helpers.js:101:18)
6:11:48 PM:     at Object.<anonymous> (/codebuild/output/src513646770/src/node_modules/@redwoodjs/core/dist/bins/redwood.js:30:1)
6:11:48 PM:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
6:11:48 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

Builds fine locally as really all that the web site is doing is `yarn rw build web` based upon [this code](https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/deploy/flightcontrol.js#L79).

Wondering if any ideas?

I'll try a completely new build on Flightcontrol soon. I've already reached out on their discord. Thanks!

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jtoar** [comment]
Hey @schybo, in v4, we only support Node.js versions 16.19 and up, and since when you deploy to flightcontrol, you deploy to AWS (pretty sure), you should be able to deploy on Node.js 18 even. Do you know if you just happen to be deploying using Node.js 15 or lower? You may also need an `.nvmrc` file like the one here: https://github.com/redwoodjs/deploy-target-ci/blob/main/flightcontrol/.nvmrc

**Comment by schybo** [comment]
Flightcontrol team got back to me. Needed to add `buildType: "nixpacks"` to your "redwood web" service. This will enable proper node version detection

They need to update the redwood cli so that this is auto-generated for individuals.

**Comment by schybo** [comment]
Thanks for the response @jtoar btw!
