### ISSUE TITLE
Auth Provider GoTrue renaming and re-arranging of overview in Auth docs

### ISSUE THREAD

**Issue by jeliasson** [redwoodjs/redwood#762]
As a follow-up to the additional feedback provided in #760;
> I noticed that `goTrue` was added as Auth Provider in the same commit. Two points here;
> 
> - As `goTrue` is part of Netify, would it make it sense to prefix this Auth provider with e.g. `netifyGoTrue`?
> - In the [Auth documentation overview](https://github.com/redwoodjs/redwood/tree/main/packages/auth#authentication) I suggest that this can be re-ordered, e.g. having 
> 1. Netify, 2. Netify GoTrue, 3. Auth0 4. ...

Considering GoTrue to be part of Netify, to my understanding, I think it would make sense to rename the auth provider from `goTrue` to `netifyGoTrue` and at the same time re-arrange the Auth Documentation as order above, or equivalent. 

This is obviously a low-prio thing, but thought I might bring it up :)

Ping @peterp 
CC @thedavidprice 

Thanks guys!

**Comment by Terris** [comment]
Hey @jeliasson  I may very well be confused here but I believe that GoTrue is just an API service layer and not exclusively associated with Netlify as an auth provider. For instance, I could setup GoTrue on my own server and pass it to Redwood Auth just as I would any other client. See, [GoTrue](https://github.com/netlify/gotrue).

Of course, the chances of this happening are slim-to-none but I don't think we'd want to dismiss the possibility, even if only per the meager coercion of naming conventions :)

**Comment by jeliasson** [comment]
> [...] I believe that GoTrue is just an API service layer and not exclusively associated with Netlify as an auth provider. [...]

You are completely right. I'll go ahead and close this issue, and thanks for the clarification on this.
