### ISSUE TITLE
[Bug-ish]: Be less aggressive when rolling back errors during generation

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#7659]
### What's not working?

@Josh-Walker-GM did some excellent work [rolling back the generators](https://github.com/redwoodjs/redwood/pull/6947) if any error occurs. But, I'm in a situation right now where that rollback is a little too aggressive! I'm running into this [other bug](https://github.com/redwoodjs/redwood/issues/7491), and because an error occurs during type generation, I can no longer generate anything that contains a follow-up type generation run. :( All of the files that were generated (correctly!) are wiped out because of a bug in an (I would argue) optional following step.

I'm wondering if there is a way to mark certain steps of the generation process "optional" or otherwise flag them that they should not trigger a full rollback.

### How do we reproduce the bug?

If you using GraphQL fragments as detailed in [this bug report](https://github.com/redwoodjs/redwood/issues/7491), you'll be unable to run type generation. Now try generating a page: `yarn rw g page Foo`:

![image](https://user-images.githubusercontent.com/300/220205288-59cb1790-4638-4a85-99a6-57b5f808caad.png)

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Note to self: also fix so that `-f` disables any rollback

**Comment by cannikin** [comment]
Also can't generate an SDL file

**Comment by Josh-Walker-GM** [comment]
@cannikin - You'd be happy enough with the proposed fix? Essentially if you run into an error and decide you want to run the command anyway you use the `-f` flag and it will also prevent the rollback. Not a perfect solution but I think it fixes the issue.

**Comment by cannikin** [comment]
Yep, this sounds good!
