### ISSUE TITLE
[Bug?]: Supabase auth handlers have untyped `options` param

### ISSUE THREAD

**Issue by bnn1** [redwoodjs/redwood#7689]
### What's not working?

Auth handlers returned by `useAuth()` have their `options` param untyped - it's of type "unknown".
```ts
const { signUp, logIn, logOut } = useAuth();
          // ^^^^^^^^^^^^^^^^^ all have type (options?: unknown) => SomeType
```
Possible options are not covered in documentation so you have to crawl the internet to search example usage of these functions to figure out what options are available. 

### How do we reproduce the bug?

In a RW app initialize supabase auth `yarn rw setup auth supabase`
Destructure object returned from `useAuth` call `const { logIn } = useAuth()`
Call `logIn` passing it an object `logIn({})` then realize there's no typing and you have no way to know what options are required or available.

### What's your environment? (If it applies)

```shell
System:
    OS: Linux 6.1 undefined
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.14.2 - /tmp/xfs-5a61aa00/node
    Yarn: 3.4.1 - /tmp/xfs-5a61aa00/yarn
  Databases:
    SQLite: 3.41.0 - /usr/bin/sqlite3
  npmPackages:
    @redwoodjs/auth-supabase-setup: 4.2.0 => 4.2.0 
    @redwoodjs/core: 4.2.0 => 4.2.0
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by jtoar** [comment]
Hey @bnn1, yeah we need to improve the TS experience here. Would you be up for giving it a shot? All the code for the supabase auth packages is here: https://github.com/redwoodjs/redwood/tree/main/packages/auth-providers/supabase.

**Comment by bnn1** [comment]
@jtoar I will give it a try, sure =)

**Comment by dthyresson** [comment]
@bnn1 Please see https://github.com/redwoodjs/redwood/pull/7745 and this address the Supabase types
