### ISSUE TITLE
[Bug?]: Webauthn login is never prompted after scaffolding dbAuth

### ISSUE THREAD

**Issue by Leon-Sam** [redwoodjs/redwood#7751]
### What's not working?

After doing a standard issue dbAuth scaffold and when logging in using dBAuth , normal username/password works fine. But the prompt for registering WebAuthn never show ups. 

I also smoke tested my browser to make sure it can actually do webauth via https://webauthn.io/ , and my browser is supported/works.

I was able to trace the issue down to the webAuthn.isSupported() function call. It always returns false. 
So it seems like the exact method to detect support might have a bug in it. 

 ``` js
const onSubmit = async (data) => {
    const webAuthnSupported = await webAuthn.isSupported()
    console.log('is webauthn supported on submit:', webAuthnSupported) //THIS RETURNS False
    }
```

I made a quick repo with debug statements. You can find the link below.  I'll be chipping away at this, but I wanted to put this up for others to know

### How do we reproduce the bug?

Link to test repo:
[REPO](https://github.com/Leon-Sam/redwood-webauthn-bug)

Commands to replicate:
1. yarn create redwood-app ./redwoodblog
2. cd ./redwoodblog
3. yarn redwood generate page home /
4. yarn rw g dbAuth --webauthn
5. yarn rw setup auth dbAuth "Click Y during webauthn prompt"
6. "Add user schema described in generator for Users and UserCredential in the schema.prisma file"
7. yarn rw prisma migrate dev
8. yarn rw dev
8. manually visit the /signup and /login endpoints and try to use webauthn

### What's your environment? (If it applies)

```shell
System:
    OS: Linux 5.19 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.14.2 - /tmp/xfs-6e247494/node
    Yarn: 3.4.1 - /tmp/xfs-6e247494/yarn
  Browsers:
    Chrome: 109.0.5414.119
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 4.2.2 => 4.2.2 
    @redwoodjs/core: 4.2.2 => 4.2.2
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by Leon-Sam** [comment]
I think I got this figured out!

The [isSupported() ](https://github.com/redwoodjs/redwood/blob/85ba8f74e7f175df5ac3f9c06be97b8aed1d9942/packages/auth-providers/dbAuth/web/src/webAuthn.ts#L57)function in dbAuth/web calls the [ platformAuthenicatorIsAvailable() ](https://simplewebauthn.dev/docs/packages/browser/#platformauthenticatorisavailable)from the 3rd party package. 

Which only looks up for "Platform" authenticators ie (Apple Touch ID, Windows Hello etc). Ubuntu has no platform authentication to my knowledge, but can do 3rd party based hardware devices.

We should be calling [browserSupportsWebAuthn() ](https://simplewebauthn.dev/docs/packages/browser/#browsersupportswebauthn)from the 3rd party library for the isSupported function in dbauth/webauthn.

Can somebody check/confirm my logic? Once confirmed, I'll make a PR for this.

**Comment by Tobbe** [comment]
Ping @cannikin

**Comment by cannikin** [comment]
So `platformAuthenticatorIsAvailable()` calls `browserSupportsWebAuthn()` internally, but adds an [additional check](https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/browser/src/helpers/platformAuthenticatorIsAvailable.ts) for the platform authenticator. I didn't realize that would exclude third party authenticators altogether! We'd love to get a PR that enables them everyone, thanks!

**Comment by Leon-Sam** [comment]
Just posted up the PR, let me know if you need anything else from me
