### ISSUE TITLE
[Bug?]: Basic dbAuth CLI setup throws an exception

### ISSUE THREAD

**Issue by lidor30** [redwoodjs/redwood#7801]
### What's not working?

I created a new project and only added a user entity.
I tried adding dbAuth using this command:
`yarn rw setup auth dbAuth `

And received this error:
`Error: Command failed with exit code 1: yarn npm info @redwoodjs/auth-dbauth-setup --fields versions --json
error Command "npm" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    at makeError (/Users/lidor/Projects/gotech/gotech-pm/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/lidor/Projects/gotech/gotech-pm/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getAuthHandler (/Users/lidor/Projects/gotech/gotech-pm/node_modules/@redwoodjs/cli/dist/commands/setup/auth/auth.js:107:9)
    at async Object.handler (/Users/lidor/Projects/gotech/gotech-pm/node_modules/@redwoodjs/cli/dist/commands/setup/auth/auth.js:53:21) {
  shortMessage: 'Command failed with exit code 1: yarn npm info @redwoodjs/auth-dbauth-setup --fields versions --json',
  command: 'yarn npm info @redwoodjs/auth-dbauth-setup --fields versions --json',
  escapedCommand: 'yarn npm info "@redwoodjs/auth-dbauth-setup" --fields versions --json',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.',
  stderr: 'error Command "npm" not found.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.`

### How do we reproduce the bug?

Create a new RW project and run `yarn rw setup auth dbAuth `

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 13.0
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - /var/folders/49/l705jn0x5r9cmfb8tps8hxy80000gn/T/yarn--1678629101040-0.6740823634981656/node
    Yarn: 1.22.19 - /var/folders/49/l705jn0x5r9cmfb8tps8hxy80000gn/T/yarn--1678629101040-0.6740823634981656/yarn
  Databases:
    SQLite: 3.39.4 - /usr/bin/sqlite3
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.1
  npmPackages:
    @redwoodjs/core: 4.3.1 => 4.3.1
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Leon-Sam** [comment]
Hi lidor30, I was able to setup dbAuth with the commands you mentioned. The error states "npm not found", have you installed nodejs on your system? 
![image](https://user-images.githubusercontent.com/18523441/224891654-f725b753-c6b5-4083-8804-c77c99c7d885.png)

**Comment by Tobbe** [comment]
I don't think it's `npm` that's failing. It looks like it's `yarn npm info` https://yarnpkg.com/cli/npm/info

@lidor30 I think the problem is that you're using yarn 1. Should be yarn 3. I'm afraid I don't know why that happens, or how to properly fix it. (System-level yarn can be v1, but inside a project it should be v3.)

@jtoar is better at this stuff than I am. I'll ask him to take a look.
