### ISSUE TITLE
[Testing] Replace hacky DB clearing with official Prisma method when available

### ISSUE THREAD

**Issue by RobertBroersma** [redwoodjs/redwood#782]
Discussion running over here: https://github.com/prisma/prisma/issues/742

Relevant piece of code:
https://github.com/redwoodjs/redwood/blob/main/packages/core/config/jest.setup.api.js

**Comment by thedavidprice** [comment]
note: code moved here https://github.com/redwoodjs/redwood/blob/main/packages/core/src/configs/node/jest.setup.js

**Comment by dac09** [comment]
@cannikin mind taking a look at this and closing if not required anymore?

**Comment by thedavidprice** [comment]
I can confirm it's no longer hacky 😉
