### ISSUE TITLE
Upgrade to React Hook Form 6.0

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#784]
https://github.com/react-hook-form/react-hook-form/releases/tag/v6.0.0

I haven't looked into the details much yet but it's supposed to have a smaller package size, which we always like!

**Comment by Ako92** [comment]
i Can handle this issue. assign it to me

**Comment by cannikin** [comment]
Done!

**Comment by Ako92** [comment]
https://github.com/redwoodjs/redwood/pull/964
Please check this Pull Request

**Comment by jvanbaarsen** [comment]
@cannikin I think this issue can be closed since the PR has been merged, correct?
