### ISSUE TITLE
Improving scaffold error output

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#787]
If scaffolding the first file (the sdl) fails, it might be clearer to _not_ say "Writing..." for all the other files. 

![rw-scaffold-failure](https://user-images.githubusercontent.com/32992335/86299696-c19d2f00-bbb5-11ea-9a2f-ca1caf5b3ee7.png)

I think the original thinking was: the fact that we use a gerund should mean that nothing has actually been written (plus, there's no green check). But the fact that there's only one red X instead of red X's across the board might leave some users wondering, "But what about the other files?"

I think the original thinking was: the red X is to show exactly where the scaffold failed. And since the other files didn't fail (moreover, didn't even start), it'd technically be incorrect to red-X them.

For reference, here is successful scaffold output:

![rw-scaffold-success](https://user-images.githubusercontent.com/32992335/86300218-0c6b7680-bbb7-11ea-9bec-be8637f9b213.png)

The current design makes the most sense in light of the partial success output:

![rw-scaffold-success-partial](https://user-images.githubusercontent.com/32992335/86300372-7dab2980-bbb7-11ea-82d5-2094d41bc354.png)

The way our CLI's setup, it's probably too hard to suppress output if the scaffold fails. But what we could do is add some kind of identifier (like a dash: - ) next to the tasks that haven't started.

Discord message for reference: https://discord.com/channels/679514959968993311/716252919875240007/728024690433589301 (do these links actually work?)

**Comment by santhoshle** [comment]
@jtoar @peterp
I'm a first-time contributor, can I work on this?

**Comment by thedavidprice** [comment]
Hi @santhoshle Thanks for offering to help! We're grateful to have you. 

### Getting Started for First Time Contributors
Before you get started, please do take a look at this info if you haven't already: https://github.com/redwoodjs/redwood/issues/1266

### Helpful information for this Issue
For this Issue, you'll also want to look at these files and links README specific to the CLI package:
- CLI Package README: https://github.com/redwoodjs/redwood/tree/main/packages/cli
- Scaffold Generator File: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/scaffold/scaffold.js
- List for Shell Task Management: https://github.com/SamVerschueren/listr

Listr provides a way to update each Task Title based on status or conditional. A simple path forward might be to set the initial title for each task to be:
- `...waiting to write file` (or something similar)

And then update the title when the task starts to the current:
- `Writing`

If you're feeling ambitious, you could even update the title if a task is successful:
- `Wrote file` or `Successfully wrote file` or ...

---

What do you think? Just let me know and I'll assign this issue to you.

**Comment by santhoshle** [comment]
Hi @thedavidprice Thank you for providing the required information for this issue. 
I can handle this issue, please assign it to me.

**Comment by santhoshle** [comment]
Hi @thedavidprice, Currently improved the scaffold output handling while generating the files in #1320.
Please confirm whether this is the right approach. Once confirmed, I will update it in other places.
