### ISSUE TITLE
[Bug?]: When using the `directUrl` functionality in Prisma, `yarn rw test` runs against the `DIRECT_URL` variable instead of the `TEST_DATABASE_URL` variable.

### ISSUE THREAD

**Issue by aslaker** [redwoodjs/redwood#7886]
### What's not working?

When using connection pooling with Prisma, you often have to utilize the `directUrl` functionality to make sure that any Prisma operations that require direct access to the DB have a proper string that is not behind a connection pool.

```
datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}
```

When running tests in Redwood, we typically set a `TEST_DATABASE_URL` that replaces the `DATABASE_URL` during testing.  If you are leveraging the `directUrl` functionality in Prisma however, Prisma will use the value for `directUrl` instead for all operations that need direct access, even if a `TEST_DATABASE_URL` is set in your `.env` file.  Two of the Prisma operations leveraged by the Redwood testing system (`prisma migrate reset` and `prisma db push`) both require direct url access so they default to using the `directUrl` instead of the `url` in the Prisma `datasource` block.  

This will run a `prisma migrate reset` against the `directUrl` instead of the expected `TEST_DATABASE_URL`.  If the `directUrl` is set to your production database (which it likely is) this will cause all of the production data to be reset during the test run.

### How do we reproduce the bug?

1. Create a brand new RedwoodJS project.
2. Create a sample model inside of the `schema.prisma` file.
3. Set up a sample database in Supabase
4. Set your `DATABASE_URL` in your `.env` file to the connection string from the database created in step 3
5. Run `yarn rw prisma migrate dev`
6. Run `yarn rw generate scaffold {sample model}` to generate UI to enter data and all of the basic tests with scenarios
7. Insert some data for the sample model using the scaffold UI
8. Follow this article to turn on connection pooling and set a direct url for migrations [Supabase Prisma Connection Pooling](https://supabase.com/docs/guides/integrations/prisma#connection-pooling-with-supabase)
9. Set up a sample test database in Supabase
10. In your `.env` file, set the `TEST_DATABASE_URL` to the connection string for the sample test database from step 8
11. Run `yarn rw test` and see that the application connects to the `DIRECT_URL` from the production database, not the `TEST_DATABASE_URL`
12. Log into Supabase and verify that the sample data you created in step 7 has been deleted during the `prisma migrate reset` step that occurs as setup for the Redwood tests.

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by amicharski** [comment]
Run `yarn rw info` and show me your output

**Comment by aslaker** [comment]
@amicharski apologies, I should have included that before.  Below is the output from `yarn rw info`

```
  System:
    OS: macOS 13.1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /private/var/folders/mg/2gry037d7pv16cm7_sr6fj440000gn/T/xfs-2991e4b7/node
    Yarn: 3.4.1 - /private/var/folders/mg/2gry037d7pv16cm7_sr6fj440000gn/T/xfs-2991e4b7/yarn
  Databases:
    SQLite: 3.38.3 - /Users/adamslaker/opt/miniconda3/bin/sqlite3
  Browsers:
    Safari: 16.2
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 4.3.1 => 4.3.1 
    @redwoodjs/core: 4.3.1 => 4.3.1 
```
