### ISSUE TITLE
[Docs]: [Bugs]: DateTimeLocalField

### ISSUE THREAD

**Issue by NetLancer** [redwoodjs/redwood#7923]
### Summary and description

DateTimeLocalField (Form control) - no way i could format the field to make it look sane for my region/mentality. 
I'm duplicating an issue, sorry, for there's no documentation on this and no other methods i managed to find & try out work(!) 
Hate to think i'll be polluting RW Issues space echoing the same problem over and over every week, but the issue is clear and simple and strongly believe SHOULD BE solved.
Please, give any info: How i make the field look different if for example, in my region people are accustomed to read dates like: "04(day)-04(month)-2020(year)" or any other shape ?

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by thedavidprice** [comment]
Hi @NetLancer I agree, Forms are _rough_ at best. And formatting forms is even worse. This isn't a bug or issue with Redwood, however, it's implementation support.

There is a way to get some help from the community at large. Here's my recommendation:
- create a post here in the Forums: [Get Help and Help Others](https://community.redwoodjs.com/c/get-help-and-help-others/15)
- Your title matters a lot. I'd suggest: "Help formatting a date-time form field"
- A simple ask really matters. Make it clear what the goal is: "I need help understanding how to format the date-time field below to be X" (Is is display only? Validation? Etc.)
- Show some example code and a screenshot --> you need to provide more information: are you using a UI library, what is your current code, can you create a screenshot of what you're trying to achieve?
- give it some time

Lastly, and I kid you not, ChatGPT can be insanely helpful with things like this. AND explain why/and how it works. https://chat.openai.com/

**Comment by NetLancer** [comment]
Thank you a lot, and my apologies))

**Comment by thedavidprice** [comment]
No apologies are necessary! And you're very welcome — we don't take anyone for granted just excited you're using Redwood 🚀

**Comment by NetLancer** [comment]
Unfortunately, my issue/question/helpScream on this very DateTim thing posted on community forum quite a while ago, still not answered. 
The only answer i found on stackoverflow didn't work either, and chatpgpt seems not serving in my region )). 
So, still looking for help, but i think the issue's generic enough to be included in documentation. 
[My DateTimeField formatting issue, community](https://community.redwoodjs.com/t/forms-datetimelocalfield-props/4641/2?u=netlancer)

**Comment by thedavidprice** [comment]
replied on Forum thread
