### ISSUE TITLE
Generators spitting out transpiled code

### ISSUE THREAD

**Issue by cephalization** [redwoodjs/redwood#798]
After creating a few new pages just fine, all further generating (components, and layouts) produces transpiled code instead of jsx.

The command `yarn rw g layout primary` produces:

```js
'use strict'
var _interopRequireDefault = require('@babel/runtime-corejs3/helpers/interopRequireDefault')
var _Object$defineProperty = require('@babel/runtime-corejs3/core-js/object/define-property')
_Object$defineProperty(exports, '__esModule', { value: true })
exports['default'] = void 0
var _react = _interopRequireDefault(require('react'))
var PrimaryLayout = function PrimaryLayout(_ref) {
  var children = _ref.children
  return /*#__PURE__*/ _react['default'].createElement(
    _react['default'].Fragment,
    null,
    children
  )
}
var _default = PrimaryLayout
exports['default'] = _default
```

Here is my reproduction repo https://github.com/cephalization/features

I can't generate components nor layouts at the moment.

Here are is my info:

```
System:
    OS: macOS 10.15.5
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.8.0 - /var/folders/x3/_d69178975g3lng0k5sbjc_h0000gn/T/yarn--1593923578574-0.3263824546889318/node
    Yarn: 1.22.0 - /var/folders/x3/_d69178975g3lng0k5sbjc_h0000gn/T/yarn--1593923578574-0.3263824546889318/yarn
  Databases:
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 77.0.1
    Safari: 13.1.1
```

**Comment by peterp** [comment]
Hey there @cephalization,

I just checked out your branch did the following:

```bash
➜ yarn rw g layout primary
yarn run v1.22.4
$ /Users/peterp/x/cephalization/features/node_modules/.bin/rw g layout primary
  ✔ Generating layout files...
    ✔ Writing `./web/src/layouts/PrimaryLayout/PrimaryLayout.test.js`...
    ✔ Writing `./web/src/layouts/PrimaryLayout/PrimaryLayout.js`...
✨  Done in 1.24s.

➜ cat ./web/src/layouts/PrimaryLayout/PrimaryLayout.js
const PrimaryLayout = ({ children }) => {
  return <>{children}</>
}

export default PrimaryLayout
```

Could you try do the following:

```terminal
yarn --force
```

And then re-run the commands above?

**Comment by cephalization** [comment]
Hmm still the same output. I also tried manually wiping all node_modules folder in root and each workspace but that did not fix it either.

Oddly enough, if I run `yarn rw build` the next generate command I run works correctly but then the following commands generate the babelified code again.

**Comment by cephalization** [comment]
I've narrowed it down to it occurring if I run a generator from the `web` directory. It was just a coincidence that I navigated to root to perform a build that I generated a component from root as well and it worked fine.

**Comment by peterp** [comment]
Woah, strange! And thanks for information, we can solve this fairly easily by setting the current working directory when running the generators
