### ISSUE TITLE
[RFC] Support for Vercel and Netlify Edge functions

### ISSUE THREAD

**Issue by arimendelow** [redwoodjs/redwood#8003]
### What's not working?

There is currently no way to deploy to Vercel and execute long-running API calls (single API calls that take longer than the execution limit to return).

In [this community discussion](https://community.redwoodjs.com/t/handling-long-running-apis), @dthyresson suggests using Inngest - but in [this thread on the Inngest Discord](https://discord.com/channels/842170679536517141/1089456173863944192), you can see that this is not actually a solution.

One reason for this is that RedwoodJS does not support deploying to Vercel Edge functions. I confirmed this with Vercel support, who pointed me towards the RedwoodJS builder, which needs to be updated to support Edge functions. See here: https://github.com/vercel/vercel/tree/main/packages/redwood

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by thedavidprice** [comment]
You're correct, Ari, that Redwood currently supports Node.js and does not support either Deno or V8 runtime. Netlify uses Deno for their edge and Vercel uses Cloudflare (which is v8). 

This isn't a bug or something we (Core Team) will be able to implement near-term.

**Comment by arimendelow** [comment]
I thought Node.js runs on V8, but I've still got a very basic understanding of Javascript runtimes.

If Netlify uses Deno, and Redwood doesn't support Deno, how does that impact Redwood support of Netlify?

**Comment by thedavidprice** [comment]
You and the rest of us, Ari! It's confusing indeed. There's more nuance than this, I'll take a stab at describing it in terms of context and APIs:
- **Browsers**: JS on a Browser needs APIs and a way to execute (run); V8 is the engine (execute) and the browsers provide the API (note: v8 isn't the only browser engine, it's probably the most popular, however)
- **Server** (Node.js): V8 can also run on a server; think of Node.js as providing the API for JS on a server, using V8 as the engine
- **Server** (AWS Lambda, Serverless): has many language runtimes, one of which is Node.js; the marketing term is "Serverless", which is describing the _kind_ of server it is (on demand, non-persistent, billed by usage)
- **Server** (Cloudflare Worker, Edge): uses V8 as the engine and it's own API; the marketing term is "Edge", which you can think of as Serverless 2.0 (I suggest searching for "serverless vs. edge" if you want nuance)
- **Server** (Deno, Edge): uses V8 as the engine and it's own API; note: Deno is adding Node/npm compatibility, which means it's becoming interoperable with the Node API; Deno, the company, provides an Edge deployment; Deno can also run as a long-running http server 

Ok, I feel like that's almost a solid story (not precise, but hopefully helpful).

Now on to Deployment Providers:
- Netlify: uses AWS Lambdas for Serverless Functions (main product) and Deno for Edge Functions (add-on feature)
- Vercel: uses AWS Lambdas for Serverless Functions (main product) and Cloudflare Workers for Edge Functions (add-on feature)

That's a lot of details, but is it helpful in answering your question?

**Comment by dthyresson** [comment]
FYI @arimendelow while there may not be setup commands for Netlify Edge Functions, you can most certainly create and deploy them.

See https://github.com/redwoodjs/redwood-office-hours/tree/main/2022-11-02-og-image-demo

and a demo https://rw-office-hours-og-images.netlify.app

Note that Netlify edge functions have a limited execution time (50msec) and memory footprint (1MB). So they are useful for very specific edge features.

**Comment by dthyresson** [comment]
Also, Netlify and Vercel support longer function runtimes.

Netlify can do this via an async background function: https://docs.netlify.com/functions/background-functions/

For Vercel they offer them on certain paid plans:

> The amount of time (in seconds) that a [Serverless Function](https://vercel.com/docs/concepts/functions/serverless-functions) is allowed to process an HTTP request before it must respond. The maximum execution timeout is 10 seconds when deployed on a Personal Account (Hobby plan). For Teams, the execution timeout is 60 seconds (Pro plan) or 900 seconds (Enterprise plan)

**Comment by arimendelow** [comment]
@thedavidprice @dthyresson realized I never replied back here - thanks for taking the time to provide all this color!! definitely helpful.

**Comment by Tobbe** [comment]
Running RW on other runtimes is definitely intriguing and something that's brought up for discussion from time to time within the core team. For new features we add we try to keep it in mind, but we also try not to spend extra time on it right now. I'm closing this for now, but feel free to keep the discussion going here, or, perhaps even better, on the forums.
