### ISSUE TITLE
Using TypeGraphql to generate schemas instead of using gpl

### ISSUE THREAD

**Issue by hatim-heffoudhi** [redwoodjs/redwood#802]
Hello, 
It' will be a nice feature, if we can create a common model or just the model (input and types)  in typescript class adding some decorators to generate schema,  by using the library typegraphql 

And with this you can share model between the API and the WEB part (in a module...)
```TS
@ObjectType()
class Recipe {
  @Field(type => ID)
  id: string;

  @Field()
  title: string;

  @Field({ nullable: true })
  description?: string;

  @Field()
  creationDate: Date;

  @Field(type => [String])
  ingredients: string[];
}
```
with this, we can avoid boilerplate code and some duplicates...
With typeGraphql we can add some logic code in our model (types), instead of 
````TS
export const schema = gql`
  type Todo {
    id: Int!
    body: String!
    status: String!
  }
  type Query {
    todos: [Todo]
  }
  type Mutation {
    createTodo(body: String!): Todo
    updateTodoStatus(id: Int!, status: String!): Todo
    renameTodo(id: Int!, body: String!): Todo
  }
```

**Comment by guledali** [comment]
Those duplicates you mentioned becomes a hell on large project, you should also mention this https://www.npmjs.com/package/typegraphql-prisma

**Comment by hatim-heffoudhi** [comment]
yep, I know the concept of DTO , it's a pattern used in many languages to fix duplications,  decoupled models, etc....
and the benefits of using class/model instead of GPL is to use like a dto from front to back and vice versa... i used typegraphql is a framework inspired by typeorm, you can define your model, service, resolvers, generate documentation, maybe its a framework we can explore it in redwoodsjs,   for that I'm ready to contribute it

**Comment by guledali** [comment]
Also lack of autocompletion and go-to-definition inside sdl can probably make it harder to scale in long-term, and I agree having `code-first` approach it better TypeScript all the way of through.

**Comment by jtoar** [comment]
I'll be sure to bring this up for discussion, but we've stuck to our sdl so far; here's Tom's response to "why doesn't redwood use something like nexus" in the forums: https://community.redwoodjs.com/t/anyone-playing-around-with-nexus-js/360/5.

That doesn't mean we can't provide types across sides. The TS experience is already getting a lot better with https://github.com/redwoodjs/redwood/pull/2485. 

> Also lack of autocompletion and go-to-definition inside sdl can probably make it harder to scale as in long-term maintainability and also getting out-of-sync really quickly when the project grows

The RedwoodJS IDE handles this beautifully; granted, it doesn't right now (we're breaking it constantly as we're nearing a v1 rc, but as a rule, tooling comes last—after the project's defined).

**Comment by jtoar** [comment]
Now that we're post v1, something like this really doesn't seem like it's in the cards. Happy to discuss again if there's community interest but closing for now.
