### ISSUE TITLE
Docs inaccurate statement

### ISSUE THREAD

**Issue by NickBolles** [redwoodjs/redwood#812]
I'm not sure this statement on the homepage is true:

> we didn't even omit any import statements or cheat to get the code smaller, honest!

Pretty sure an import for `db` is missing. If your going to explicitly claim that might as well add it :)

**Comment by jtoar** [comment]
@NickBolles Before #334 we used to auto import `db` too! But very true, those days are behind us. Maybe we could add `import db ...` to the top and then say "we didn't omit any _other_ import statements..."

**Comment by NickBolles** [comment]
> @NickBolles Before #334 we used to auto import `db` too! But very true, those days are behind us. Maybe we could add `import db ...` to the top and then say "we didn't omit any _other_ import statements..."

Gotcha! Makes sense.

**Comment by ryanmdoyle** [comment]
> @NickBolles Before #334 we used to auto import `db` too! But very true, those days are behind us. Maybe we could add `import db ...` to the top and then say "we didn't omit any _other_ import statements..."

Just started poking around with redwood and saw this is a few months old. I think I could handle this. It should be in the redwoodjs.com repo so I can handle it there. Should I create a new issue in that repo or just go for it?

**Comment by forresthayes** [comment]
Hey @ryanmdoyle 

I think you should go for it! You're correct that the change should be to the [redwoodjs.com](https://github.com/redwoodjs/redwoodjs.com) repo. I've been making some minor docs changes recently, so feel free to reach out if you have any questions.

**Comment by thedavidprice** [comment]
@ryanmdoyle just wanted to give another 👍 that you should just go for it. Here's the code that needs updating (no screenshot required; just markdown!):
https://github.com/redwoodjs/redwoodjs.com/blob/main/code/html/index.html

Please link to this issue when you do creat the PR so we can close it out. 

And thanks in advance!

**Comment by ryanmdoyle** [comment]
@thedavidprice Thanks!  Working on it now.

**Comment by ryanmdoyle** [comment]
Should be good now. Thanks!
