### ISSUE TITLE
[Bug]: Compatibility Check Error Message with the wrong link (Page Not Found error)

### ISSUE THREAD

**Issue by ahaywood** [redwoodjs/redwood#8224]
### What's not working?

If there's a compatibility issue when installing Redwood, the link in the error message goes to the wrong place.

### How do we reproduce the bug?

I ran `yarn create redwood-app my-successful-app`

I ran into a compatibility issue:
<img width="533" alt="CleanShot 2023-05-04 at 15 31 43@2x" src="https://user-images.githubusercontent.com/212300/236322795-e6b97bc2-f96a-44d5-bcbc-00e0c72ccc9c.png">

When I click on the link, it takes me here: https://redwoodjs.com/docs/tutorial/chapter1/prerequisites%E2%80%8B
<img width="1434" alt="CleanShot 2023-05-04 at 15 33 43@2x" src="https://user-images.githubusercontent.com/212300/236322902-63e64067-a640-4995-a728-e077498b6346.png">

which does not exist. 

It looks like the printed link is correct, but somehow I zero-width space character `%E2%80%8B` is tacked on and encoded at the end of the URL.

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by thedavidprice** [comment]
Oh, one more thing you can do to help @ahaywood From the parent directory you are attempting to install into (probably `/Users/amydutton/Dropbox/1 - PROJECTS/ENDLESS-IDEAS-MACHINE/CODE/`) can you check the yarn version and report back? 

I feel like this could also be the case where you've installed Yarn 3 globally and our semver check gets messed up.

PS: don't you know that it's a part of developer lore to _never_ put your repos inside Dropbox cause sync fights with git?? 😉

**Comment by ahaywood** [comment]
😂 Guilty and caught red-handed. I keep thinking, "I'm invincible. Dropbox likes me. It won't give me trouble." 

<img width="278" alt="CleanShot 2023-05-04 at 16 19 18@2x" src="https://user-images.githubusercontent.com/212300/236332425-ba5fe1cc-a040-4f2f-9d27-c27ed6b16aef.png">

**Comment by ahaywood** [comment]
Update: Worked with @jtoar 

The error message being reported by `yarn create redwood-app` is wrong: it should be saying “node is too low,” but it says “yarn is too low/high” which isn’t true

If I set Node to v18 and try again it works like a champ.

**Comment by jtoar** [comment]
I can't reproduce the link being wrong yet in my terminal; here it is in the source: https://github.com/redwoodjs/redwood/blob/8913c0558865c30642de92415647c8c93a072307/packages/create-redwood-app/src/create-redwood-app.js#L103

If you copy paste that it's right, so maybe something is going wrong with `terminalLink` rendering that's specific to your terminal—mind sharing which terminal emulator you're using locally so I could try reproducing?

**Comment by jtoar** [comment]
Reopening till we get the link sorted out

**Comment by ahaywood** [comment]
I'm using Hyper 
<img width="372" alt="CleanShot 2023-05-04 at 19 23 43@2x" src="https://user-images.githubusercontent.com/212300/236356342-33db0f05-70e2-4945-8d4c-122b59d16e75.png">

**Comment by Josh-Walker-GM** [comment]
Sounds similar to https://github.com/sindresorhus/terminal-link/issues/18

**Comment by jtoar** [comment]
I can reproduce this in hyper, thanks @ahaywood!
