### ISSUE TITLE
CoercedValues function in web/form breaks forms that include any direct child node without props

### ISSUE THREAD

**Issue by Terris** [redwoodjs/redwood#825]
https://github.com/redwoodjs/redwood/blob/96be36ab705ae5f7ec30262e2167e7bcb8ce4a87/packages/web/src/form/form.js#L190

This line is passing in direct children of `<Form />` to the coercedValues function. If any of these elements are not Inputs with name props, the form throws an error onSubmit.

To replicate, create a Redwood form that includes any direct children other than RW Inputs:

```js
<Form onSubmit={onSubmit}>
  <p>Some text</p>
  <div className="field">
    <TextField name="email" />
  </div>
</Form>
```
and submit =>

```bash
Uncaught (in promise) TypeError: Cannot read property 'props' of null
    at form.js:186
    at Array.forEach (<anonymous>)
    at coerceValues (form.js:183)
    at form.js:221
    at react-hook-form.es.js:1215
```
![Screen Shot 2020-07-11 at 1 23 51 AM](https://user-images.githubusercontent.com/458233/87217257-33dbe500-c315-11ea-9269-688e4439a58d.png)

**Comment by Tobbe** [comment]
I'll take a look at this as soon as I can

**Comment by Tobbe** [comment]
I have a unittest that triggers this bug now; tbc

**Comment by Terris** [comment]
@Tobbe Hey there. I put together some ideas for how we might be able to solve this over on my forked repo: https://github.com/Terris/redwood/pull/1

In a nutshell, I'm using the event api to target and iterate over the forms fields and to match field attributes with the proper function. I'm note sure it's what you were originally going for this is just some ideas. Thanks for helping me with this!

**Comment by Tobbe** [comment]
@Terris I made a PR, can you please have a look?

**Comment by Terris** [comment]
Fix: #834

**Comment by thedavidprice** [comment]
Hi gents! Thanks so much for collaborating on this -- I'd like to help make sure a fix is merged before our next release. Is this the current status:
- You've both decided this should be closed https://github.com/redwoodjs/redwood/pull/826
- And this one should be close https://github.com/redwoodjs/redwood/pull/826
- In favor of using this ==> https://github.com/redwoodjs/redwood/pull/834

??

Please confirm and I’ll help get Rob's eye's on this asap.

🚀

**Comment by Terris** [comment]
> In favor of using this ==> #834 

Yes, correct.

**Comment by Tobbe** [comment]
> In favor of using this ==> #834

Agreed 👍
