### ISSUE TITLE
[RFC]: use `yarn rw exec` to execute scripts in subfolders within the scripts directory

### ISSUE THREAD

**Issue by virtuoushub** [redwoodjs/redwood#8259]
### Summary

>  several scripts that are called from cronjobs. I’d like to create a directory `scripts/jobs` for those scripts, to separate them from my data import scripts.
>
> But if I call, e.g., `yarn rw exec jobs/updateActualRuns`, I get an error:
>
> `No script called jobs/updateActualRuns in ./scripts folder.`

### Motivation

https://community.redwoodjs.com/t/organizing-the-scripts-directory-with-subfolders/4862

### Detailed proposal

- add ability for `exec` command to take a path

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by thedavidprice** [comment]
Do it 🚀

**Comment by shivghai** [comment]
@virtuoushub we definitely use subfolders for our scripts (and have done so since RW 3.x). e.g. we have a script in `scripts/maintenance/updateXYZ.ts` and use that via `yarn rw exec maintenance/updateXYZ`. Might not actually be an issue

**Comment by virtuoushub** [comment]
> @virtuoushub we definitely use subfolders for our scripts (and have done so since RW 3.x). e.g. we have a script in `scripts/maintenance/updateXYZ.ts` and use that via `yarn rw exec maintenance/updateXYZ`. Might not actually be an issue. Unhelpful screenshot here, but i just tested it out again on redwood 5.0:
> 
> <img alt="Screen Shot 2023-05-08 at 5 17 28 PM" width="265" src="https://user-images.githubusercontent.com/8965168/236937266-c70dcaec-1ed1-4573-b8a7-ced8bc7e8a70.png">

thanks @shivghai ! do you mind sharing the output from `yarn rw info`?

**Comment by virtuoushub** [comment]
closing this issue as it [looks to be working in v5](https://community.redwoodjs.com/t/organizing-the-scripts-directory-with-subfolders/4862/4?u=bitshift).
