### ISSUE TITLE
Implement Winston for logging

### ISSUE THREAD

**Issue by RobertBroersma** [redwoodjs/redwood#827]
Implement Winston for some more fine-grained logging control.
https://github.com/winstonjs/winston

Some messages suggested by @peterp :
- authentication header detected (provider)
- authentication header decoded
- getCurrentUser returned
- graphQL lifecycle methods?
- request body? response?
- sql statements?

@jtoar I guess logging and docs are quite intertwined. Any opinions on this or tips/suggestions for moving forward?

**Comment by jtoar** [comment]
@RobertBroersma Not sure experienced here. I'd add environment vars to that list, maybe? And on the web side (this might really just be the api side though?), the lifecycle methods around Cells (`beforeQuery`, `afterQuery`) sound like good logging candidates.

But I don't think you're asking for more list items :sweat_smile: so I'll do some more research and report back.

**Comment by jtoar** [comment]
Here is a short list of some relevant forum topics / GitHub materials

- [Logging for RedwoodJS](https://community.redwoodjs.com/t/logging-for-redwoodjs/625)&mdash;logging via https://logre.io/ and Apollo Server
- [Where is the server-side (API) console output or log?](https://community.redwoodjs.com/t/where-is-the-server-side-api-console-output-or-log/485)
- [@redwoodjs/api README](https://github.com/redwoodjs/redwood/blob/60cb628d5f369d62607fa2f47c694d9a5c00540d/packages/api/README.md#graphql-serverless-function)&mdash;On our GraphQL Function roadmap, we say we want to "Connect to a 'Redwood universal logging service' for exceptions and info"

**Comment by RobertBroersma** [comment]
Relevant Slack conversation:
> so for us internally, I want to do something like
`import log from '@redwoodjs/logging'`
// something deep in the bowels of redwood
`log.debug(`"auth-provider" header found with a value of ${provider}`)`
and then if I do something like DEBUG=* yarn rw dev
I would be able to see those messages
It would be great to filter them, but I think we need to determine a way to categorise the messages.
like: `DEBUG=api/* yarn rw dev`
but... there are better CLI tools for handling filtering of things
so, maybe the important part is just categorising the messages?

> Another example might be in core, with the configurations:
`log.debug("webpack is in production mode")` / "we have rules and loaders for the following extensions" (edited) 
or with the babel loaders "we just imported the following services with this glob"
and when I'm writing these debug logs I might want to filter them because I just want to focus on the ones in my current mental model

> It would be really cool, if we can grab all those messages and pump them into the browsers console.log to have unified logging across the platforms
I would imagine that they have a transport for that kind of thing
And of course... then we can write some docs on how to have logs in production :P

**Comment by dthyresson** [comment]
RedwoodJS [release v0.28](https://community.redwoodjs.com/t/redwood-v0-28-is-amazing/1982) includes Logging, but with pino.

See https://redwoodjs.com/docs/logger.html#logger for details.

Closing issue.
