### ISSUE TITLE
[Bug?]: useRedwoodOpenTelemetry GraphQL plugin refers incorrectly to new relic

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#8270]
### What's not working?

See `graphql-server/src/plugins/useRedwoodOpenTelemetry.ts`

The error warning message refers to newrelic, but this is the open telemetry plugin.

```ts
      const resultCbs: OnExecuteHookResult<PluginContext> = {
        onExecuteDone({ result }) {
          if (isAsyncIterable(result)) {
            executionSpan.end()
            // eslint-disable-next-line no-console
            console.warn(
👉              `Plugin "newrelic" encountered a AsyncIterator which is not supported yet, so tracing data is not available for the operation.`
            )
            return
          }
```

### How do we reproduce the bug?

Reproduced by running Redwood test project in local prod via `yarn rw serve` and testing live queries:

```
Web server started on http://localhost:8910
API serving from http://localhost:8910
API listening on http://localhost:8910/.redwood/functions/
GraphQL endpoint at /.redwood/functions/graphql
Plugin "newrelic" encountered a AsyncIterator which is not supported yet, so tracing data is not available for the operation.
Plugin "newrelic" encountered a AsyncIterator which is not supported yet, so tracing data is not available for the operation.
Plugin "newrelic" encountered a AsyncIterator which is not supported yet, so tracing data is not available for the operation.
```

### What's your environment? (If it applies)

```shell
OSX
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
This appears to have been pulled in from the 'upstream' evelop plugin which I used as the base implementation before performing some updates.

https://github.com/n1ru4l/envelop/blob/2fa8c2f78ca160dc69cfa0735f019efc1968b042/packages/plugins/opentelemetry/src/index.ts#L114

Is it just the error message that you're wishing to highlight or is it the support for AsyncIterator too?
