### ISSUE TITLE
[Bug?]: Experimental (?) `useRedwoodOpenTelemetry` is unconditionally enabled without opt-in as of Redwood 5.x

### ISSUE THREAD

**Issue by pvenable** [redwoodjs/redwood#8332]
### What's not working?

The `useRedwoodOpenTelemetry` plugin -- which currently seems to be the foundation for an experimental feature (#7829) -- seems to be hardwired into `createGraphQLHandler`, and there doesn't appear to be a way to disable or configure it.

<img width="565" alt="image" src="https://github.com/redwoodjs/redwood/assets/590685/0bc7c16d-8233-4374-b7f4-f0864fcbdfd0">

We are already using a customized OpenTelemetry plugin (`based on @envelop/opentelemetry`, but customized for our needs) in our app that does similar work, and `useRedwoodOpenTelemetry` is causing essentially duplicate event traffic for us.

It's possible we could switch to using `useRedwoodOpenTelemetry` instead of our custom plugin once the former can be configured for our needs -- primarily setting options like `{ resolvers: false, result: false, variables: true }` to reduce noise, and starting an **active** span -- but in the meantime we would appreciate a way to opt out of `useRedwoodOpenTelemetry`.

It seems as though `useRedwoodOpenTelemetry` shouldn't (yet?) be enabled in the first place without opting in to the Experimental RedwoodJS Studio feature referenced above, but I'm not certain of the intent since I can't find any other references to it.

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jtoar** [comment]
Hey @pvenable, I've tagged @Josh-Walker-GM who did the open telemetry implementation. It's late for him right now but he'll get back to you tomorrow or so and we're in touch on this one.

**Comment by Josh-Walker-GM** [comment]
@pvenable Apologies for any issues this has caused you with the duplicate traffic. I'll add a fix to disable this plugin unless it has been explicitly enabled.

I too didn't find the existing envelop plugin to fit our needs. I understand the need for the `{ resolvers: false, result: false, variables: true }` options as a way to tailor which data is reported. I am planning to add these options back in as they did form part of the original envelop plugin and make perfect sense. I just hadn't yet decided the best place for these options to live.

I had also hoped to explore refactoring to use `startActiveSpan` but unfortunately I have been focused elsewhere recently. If you have details around this requirement I'd love to know about them. I'd definitely like to make the existing redwood plugin suit your needs so please feel free to document any other issues that would prevent this.

**Comment by jtoar** [comment]
@pvenable I just released the fix for this in https://github.com/redwoodjs/redwood/releases/tag/v5.1.5

**Comment by pvenable** [comment]
@Josh-Walker-GM @jtoar No worries here -- thanks for the quick attention!

The short version of the explanation for our use of an active span is that we need to get `traceparent` data from the active context and set a header in our requests to backend services so we can trace requests across our system.  As someone who is not an opentelemetry expert, it took me a while to figure out that the _active_ span was the missing piece of the puzzle for this case -- without it I couldn't get the opentelemetry API to give me the traceparent data I needed.  Ultimately this need for an active span was the reason we had to write a custom plugin instead of using `@envelop/opentelemetry` directly.

It looks like `wrapWithOpenTelemetry` in `makeMergedSchema` is going to wrap resolvers with an active span when experimental opentelemetry is enabled.  Perhaps that will actually suit our use case once we can otherwise customize `useRedwoodOpenTelemetry`.  I'll have to take a closer look when it's a bit further along in development.

Thanks again for the fix!

**Comment by thedavidprice** [comment]
@pvenable We'd welcome more information about your use case and requests for the experimental OpenTelemetry feature. Please! The best place to provide feedback is via this [OpenTelemetry Support [Experimental]](https://community.redwoodjs.com/t/opentelemetry-support-experimental/4772) forum post. Given enough community interest + momentum, we'd like to make this a first-class feature for Redwood.

**Comment by Josh-Walker-GM** [comment]
Looks like we may have inadvertently regressed on this. I was about to add the config options for the verbosity of the graphql instrumentation so I will refix this as I do.

**Comment by jtoar** [comment]
Quick update: this has regressed in canary but not in stable, so @pvenable you should be ok
