### ISSUE TITLE
[Bug?]: URL for GraphiQL header help docs is wrong

### ISSUE THREAD

**Issue by Benjamin-Lee** [redwoodjs/redwood#8359]
### What's not working?

The error currently reads:

```
{"x-auth-comment": "See documentation: https://redwoodjs.com/docs/cli-commands#setup-graphiQL-headers on how to auto generate auth headers"}
```

However, the link needs to have lowercase QL in it: `https://redwoodjs.com/docs/cli-commands#setup-graphiql-headers`. When I went to the link, it didn't jump to the right section. I'd fix it but can't find where the code for the error message is.

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 13.3
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.8.1 - /private/var/folders/gw/sk03t1cn3wlgclyc55yst44w0000gn/T/xfs-885782e8/node
    Yarn: 3.5.1 - /private/var/folders/gw/sk03t1cn3wlgclyc55yst44w0000gn/T/xfs-885782e8/yarn
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 111.0.1
    Safari: 16.4
  npmPackages:
    @redwoodjs/auth-supabase-setup: 5.2.0 => 5.2.0 
    @redwoodjs/core: 5.2.0 => 5.2.0
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by dthyresson** [comment]
Fixed by https://github.com/redwoodjs/redwood/pull/8408

**Comment by dthyresson** [comment]
Was fixed in https://github.com/redwoodjs/redwood/pull/8408
