### ISSUE TITLE
Setting `AuthProvider.isAuthenticated` to true despite failure to authenticate

### ISSUE THREAD

**Issue by biphobe** [redwoodjs/redwood#837]
Failure to fetch data via `getCurrentUser` pushes (among others) this data to AuthProvider's state:
```
{
  currentUser: undefined,
  isAuthenticated: true
}
```
If app creator's implementation of `getCurrentUser` has thrown an exception or connection issue happened, then even if client's (e.g. Magic Link) authentication succeeded, application's server-side authentication has failed and this should be reflected in AuthProvider's state as, if I understand the intent correctly, it should reflect application-wide authentication, not simply map authentication state of client which is being used.

I believe something similar to following changes would fix the issue:

[AuthProvider.tsx#L111](https://github.com/redwoodjs/redwood/blob/main/packages/auth/src/AuthProvider.tsx#L108) - adding the `else` block:

```
import { AuthenticationError } from "@redwoodjs/api";
```
```
if (response.ok) {
  const { data } = await response.json()
  return data?.redwood?.currentUser
} else {
  throw new AuthenticationError();
}
```

[AuthProvider.tsx#L111](https://github.com/redwoodjs/redwood/blob/main/packages/auth/src/AuthProvider.tsx#L114) - rewriting the `reauthenticate` method:

```
const userMetadata = await this.rwClient.getUserMetadata()
const hasUserMetadata = userMetadata !== null

let currentUser = null;
const state = {
  userMetadata,
  currentUser,
  isAuthenticated: false,
  loading: false
}

if (hasUserMetadata) {
  try {
    currentUser = await this.getCurrentUser()

    this.setState({
      ...state,
      currentUser,
      isAuthenticated: true
    })
  } catch {
    this.setState(state);
  }
} else {
  this.setState(state);
}
```

I've duplicated the `this.setState(state)` intentionally to avoid redundant potential rerender with partial data while settings state twice, e.g. causing components which rely on `useAuth()` hook to rerender with state change `{ currentUser: {<user>}, isAuthenticated: true }` which would be followed by second rerender with state change of `{ loading: false }`.

---

I've encountered this issue while trying to figure out the conditions to determine if user has been authenticated server-side.

The only way to do this right now is to check if `authData.isAuthenticated === true && authData.currentUser !== null`, but it's also an issue for `<Private />` routes which check `authData.isAuthenticated` internally. Right now unauthenticated user for which `getCurrentUser()` has thrown an error will be able to access the private route even though `getCurrentUser()` failed and `authData.currentUser` has not been properly populated.

**Comment by thedavidprice** [comment]
Ah @biphobe this is an important case/catch. Looping in @peterp to evaluate your proposal for the next steps. 

But do know he's been heads down on several things — if you don't hear from Peter in the next day or so, I do recommend you move forward with this as a draft PR and request Peter's review at that time.

Huge thanks!

**Comment by peterp** [comment]
@biphobe Thanks for the detailed bug report and a fix!

**Comment by biphobe** [comment]
@peterp Glad I could help. It's good that I hesitated with creating a PR after @thedavidprice comment since I see that you've assigned yourself. Good luck!
