### ISSUE TITLE
[RFC]: yarn rw g types - errors

### ISSUE THREAD

**Issue by razzeee** [redwoodjs/redwood#8423]
### Summary

I've been doing this for months, at this point, but it seems kinda stupid to always have to run `yarn rw g types` and then scroll up to find if there were any errors.

Can we just move the errors to the end of the return? I don't really care that much about the other content of what's being returned.

### Motivation

Having to scroll up all the time.

### Detailed proposal

This is  about the cli specifically `yarn rw g types`

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by pantheredeye** [comment]
hah; I have noticed this UX also, but didn't think about changing to the bottom of the list! +1 from me, if this is possible :)
