### ISSUE TITLE
Lambda functions don't support sub-paths on localhost (but they do on Netlify)

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#846]
I have `api/src/functions/hello.js`
```
export const handler = async (event, context) => ({
  statusCode: 200,
  body: 'Hello from ' + event.path,
})
```

Accessing http://localhost:8911/hello I get
"Hello from /hello"

Accessing http://localhost:8911/hello/world I get
"Cannot GET /hello/world"

However, if I deploy to Netlify and access https://my-app.netlify.app/.netlify/functions/hello/world
"Hello from /.netlify/functions/hello/world"

I expected local behavior to match deployed behavior

**Comment by peterp** [comment]
We should definitely add support for this, here are some steps:

- [ ] Determine how many levels on nesting is supported on netlify, vercel, etc.
- [ ] Make the [import code](https://github.com/redwoodjs/redwood/blob/1845c2372efb583155d9f483bdbd4100fa141deb/packages/dev-server/src/watchApiSide.ts#L28-L31) support nested subdirectories.
- [ ] Make the [various parts](https://github.com/redwoodjs/redwood/blob/1845c2372efb583155d9f483bdbd4100fa141deb/packages/dev-server/src/http.ts#L9-L12) that reference the "name" work with subdirectories.
- [ ] Write tests.

**Comment by Tobbe** [comment]
> Make the import code support nested subdirectories.

Yes and no.
This is not what this issue is about, but you're still kind of right 🙂 
The base dir is `functions/` and adding a `functions/hello.js` file sets up a lambda function at http://localhost:8911/hello This works properly today.
Adding a `functions/hello/hello.js` file should also set up a lambda function at http://localhost:8911/hello This is the only valid subdir case.

Both ways of doing it should still listen to http://localhost:8911/hello/any/sub/path/file.ext

From Netlify's docs

> Note that, with one exception, any files in subdirectories will be ignored.

> You can use either a standalone .js file that exports a handler (e.g. functions/{function_name}.js) or a folder with the same name as a .js file in it that exports a handler (e.g. functions/{function_name}/{function_name}.js).

https://docs.netlify.com/functions/build-with-javascript/

**Comment by Tobbe** [comment]
> Determine how many levels on nesting is supported on netlify, vercel, etc.
I have only tried Netlify, and I think it's pretty much unlimited. 

https://MY_APP.netlify.app/.netlify/functions/hello/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z
Hello from /.netlify/functions/hello/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z

**Comment by Tobbe** [comment]
I'm looking in to this. Expect a PR in a bit

**Comment by peterp** [comment]
Thanks for looking into this Tobbe!

I don't think we should make our implementation directly match what Netlify supports since we want to be "deployment agnostic", and I can definitely see someone attempting to use `src/functions/hello/index.js` and wanting it to work locally, but then it won't work on Netlify.

So, we need to come up with something that makes sense from a DX perspective to support nested subdirectories, and we can convert it to match the deployment target during the build phase.

**Comment by Tobbe** [comment]
Vercel does nested dirs (and dynamic path segments using specific file names)
https://vercel.com/docs/v2/serverless-functions/introduction#path-segments

Not sure really how RW should support all the different hosting options...

**Comment by peterp** [comment]
Ok, so for now could we do the following:

```
/functions/a.js -> works
/functions/a/b/b.js -> works (directory named)
/functions/a/b/c/index.js -> won't work now, but we can make it work during the build step. (we can provide diagnostics.)
```

**Comment by peterp** [comment]
After some synchronous discussion with Tobbe I finally grasp what he's talking about, in retrospect I don't know where I go off the beaten path.

@Tobbe This seems totally reasonable.

**Comment by Tobbe** [comment]
I've been playing around with Vercel's implementation of lambda functions for the last hour...

As I wrote above, they do directory routing inside /api
So to be able to handle requests to my.domain.com/api/a/b I need a file at /api/a/b.js  (or /api/a/[dynamic].js)

What I want is to be able to have a file handle all sub routes to that file. It's possible out-of-the-box on Netlify, but not with RW right now.
To support it on Vercel there's a workaround you can use. You add the file /api/a.js and then you define a route in `vercel.json` for all sub-routes; `"routes": [ { "src": "/api/a/(.*)", "dest": "/api/a.js" } ]`
