### ISSUE TITLE
lambda functions can't be placed in sub directories

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#849]
This issue is a spin-off of #846 

On Netlify, if you want to have the serverless function `hello` you can either have the file `functions/hello.js` or `functions/hello/hello.js`

Redwood currently only supports the first of those two options (`functions/hello.js`)

This issue is about adding support for the second way of doing it as well. Plus, possibly, `functions/hello/index.js`

All three options would result in a function available at http://localhost:8911/hello 

Netlify's docs for this are here https://docs.netlify.com/functions/build-with-javascript/

Potential steps brought over from the linked Issue

- [x]  Determine how many levels on nesting is supported on netlify, vercel, etc.
 Netlify: Only one level. Vercel: Unlimited
- [ ]  Make the [import code](https://github.com/redwoodjs/redwood/blob/1845c2372efb583155d9f483bdbd4100fa141deb/packages/dev-server/src/watchApiSide.ts#L28-L31) support nested subdirectories.
- [ ]  Make the [various parts](https://github.com/redwoodjs/redwood/blob/1845c2372efb583155d9f483bdbd4100fa141deb/packages/dev-server/src/http.ts#L9-L12) that reference the "name" work with subdirectories.
- [ ]  Write tests.

(Personally I don't have a need for this right now, so anyone else; please feel free to pick this up if you want to)

**Comment by Tobbe** [comment]
Potential steps brought over from the linked Issue

- [x]  Determine how many levels on nesting is supported on netlify, vercel, etc.
 Netlify: Only one level. Vercel: Unlimited
- [ ]  Make the [import code](https://github.com/redwoodjs/redwood/blob/1845c2372efb583155d9f483bdbd4100fa141deb/packages/dev-server/src/watchApiSide.ts#L28-L31) support nested subdirectories.
- [ ]  Make the [various parts](https://github.com/redwoodjs/redwood/blob/1845c2372efb583155d9f483bdbd4100fa141deb/packages/dev-server/src/http.ts#L9-L12) that reference the "name" work with subdirectories.
- [ ]  Write tests.

**Comment by dthyresson** [comment]
Here's how we organized nested functions in an app built ~ 14 months ago. 

Maybe not the best/fastest way as it added a layer, but it did make it organized and might be host-platform agnostic (works on Netlify and Vercel).

We had an endpoint `/feed` like a Stream feed that had other related functions: `/feed/me` (my feed), '/feed/follow/<name>` follow this feed, `/feed/unfollow`, `/feed/count/<name>` (get the number of items in the feed), among 6-8 others, etc.

Each then could include multiple sets of functionality to have nesting like: `/feed/me/following`, `/feed/me/starred` as inside the `me` was an implementation of `following` and `starred`.

Used a router, to direct to the nested functions.

```js
import { Router } from 'express';
...
import follow from './follow';
import me from './me';
import unfollow from './unfollow';
...
import { APIClient, mapRoutes } from '../utils';

const client = APIClient.stream();

const router = Router();

const routes = [
  {
    path: '/me',
    route: me,
  },
  {
    path: '/count',
    route: count,
  },
  {
    path: '/follow',
    route: follow,
  },
  {
    path: '/unfollow',
    route: unfollow,
  },
];

mapRoutes(router, routes, client);

export default router;
```

The the `me` could further separate functionality into

* `/feed/me/activities` ie the content in my personalized feed
* `/feed/me/starred` ie get the items I starred in my feed
* `/feed/me/following` ie what feeds am I currently following

```js
export default (router, path, client) => {
  router.get(`${path}/activities`, authWithToken(true, env.SOME_SECRET), async (req, res) => {
    // do stuff
  };

  router.get(`${path}/starred`, authWithToken(true, env.SOME_SECRET), async (req, res) => {
    // do stuff
  };


  router.get(`${path}/following`, authWithToken(true, env.SOME_SECRET), async (req, res) => {
     // do stuff
  };
}

```

and `mapRoutes`:

```js
/**
 * Adds all of the given routes to the router, passing any additional args
 * needed to all routes.
 *
 * @param {express.Router} router the router to add the routes to
 * @param {object[]} routes the routes to be added to the router
 * @param {string|string[]} routes.path the path of the route
 * @param {function} routes.route a function that accepts the router, path, and
 * additional args to create the routes
 * @param {...any} args any additional args to be sent into every route
 */
const mapRoutes = (router, routes, ...args) => {
  routes.forEach(({ path, route }) => {
    const paths = Array.isArray(path) ? path : [path];
    paths.map(path => route(router, path, ...args));
  });
};

export default mapRoutes;
```

So - maybe RW's router could live at the root level and then orchestrate out to really any level of nesting -- because the path defines that level.

Might work.

**Comment by Tobbe** [comment]
> Maybe not the best/fastest way as it added a layer, but it did make it organized and might be host-platform agnostic (works on Netlify and Vercel).

Having an Express app as a router on the top level (`/feed` in this case) is exactly what Netlify themselves use in their examples, so I think that's a perfectly valid approach. To get that to work on Vercel I had to do some tricks with the `vercel.json` config files and the routing in there.

So if we choose this route (sorry 😛😁) we need to do this setup on Vercel as part of deployment. 

next.js does some magic with their `/pages/api` folder. So it's not impossible, just a bit of work :)

**Comment by dthyresson** [comment]
> Having an Express app as a router on the top level

Yes, exactly. I forgot to include that part as the example:

```js
import serverless from 'serverless-http';
import app from './lib/app';
import feed from './lib/feed';

app.use('/.netlify/functions/feed', feed);

export const handler = serverless(app);
export default app;
```

and `app.js` is:

```js
  
import '@babel/polyfill';
import express from 'express';
import bodyParser from 'body-parser';

const app = express();
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

// Enable CORS header
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  next();
});

export default app;
```

**Comment by viperfx** [comment]
Would like to just add my use case here for this feature

With the redwood app I am working on, the application and API integrate to different services. We are working on a Slack app, Intercom app, Zapier App etc.

We use the serverless functions to the do following functionality:
- Oauth redirect and callback URLs
- Incoming webhook support to integrate with platforms
- APIs we create according to the platform spec.

So the project close to 20 functions, and we are not yet done with the integrations we want to develop.

For code organization, I have used the following naming scheme, to make things a bit more manageable. 
[platform]-[function].js

e.g. intercom-oauth-callback.js, slack-auth.js

**Comment by dac09** [comment]
I've set up the #3207 to close this issue, because it does handle the original ask. 

I'm going to take @viperfx's comment and create a different issue, as its requesting something a little different.
