### ISSUE TITLE
[Bug?]: Redwood 5.2 requires Node 18.x but rw setup deploy render outputs NODE_VERSION = 18

### ISSUE THREAD

**Issue by Benjamin-Lee** [redwoodjs/redwood#8508]
### What's not working?

I'm running into errors on a Render deploy and noticed that the Render template is out of date. Is this intentional?

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by thedavidprice** [comment]
> I'm running into errors on a Render deploy and noticed that the Render template is out of date. Is this intentional?

Definitely **not** intentional! PR would be very welcome. Additionally, if you can consider including more scope, auditing the other deploy templates would be welcome + helpful as well.

Thanks!
