### ISSUE TITLE
[Bug?]: create redwood-app didnt work on windows

### ISSUE THREAD

**Issue by cubu** [redwoodjs/redwood#8530]
### What's not working?

I run the command: yarn create redwood-app --ts ./redwoodblog

but it stop at Checking node and yarn compatibility

    ➤ YN0000: ┌ Resolution step
    ➤ YN0000: └ Completed in 4s 61ms
    ➤ YN0000: ┌ Fetch step
    ➤ YN0000: └ Completed
    ➤ YN0000: ┌ Link step
    ➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
    ➤ YN0000: └ Completed in 0s 383ms
    ➤ YN0000: Done with warnings in 4s 551ms
    
    ------------------------------------------------------------------
                    🌲⚡️ Welcome to RedwoodJS! ⚡️🌲
    ------------------------------------------------------------------
    ⠏ Checking node and yarn compatibility
    C:\Users\LAPTOP\AppData\Local\Yarn\Berry\cache\create-redwood-app-npm-5.2.4-89a5b8212e-8.zip\node_modules\create-redwood-app\dist\create-redwood-app.js:6
    `));try{(await o.prompt({type:"select",name:"override-engine-error",message:"How would you like to proceed?",choices:["Override error and continue install","Quit install"],initial:0}))["override-engine-error"]==="Quit install"&&(c("User quit after engine check error"),await s(),process.exit(1))}catch{c("User cancelled install at engine check error"),await s(),process.exit(1)}}}function ae(e){return new Promise(t=>{let{engines:i}=require(p.default.join(e,"package.json"));(0,J.default)(i,(n,a)=>t([a.isSatisfied,a.versions]))})}async function se(e,{templateDir:t,overwrite:i}){let n=new r.ReactiveTUIContent({mode:"text",content:"Creating project files",spinner:{enabled:!0}});o.startReactive(n),u.default.existsSync(e)&&!i&&u.default.readdirSync(e).length>0&&(o.stopReactive(!0),o.displayError("Project directory already contains files",[`'${r.RedwoodStyling.info(e)}' already exists and is not empty`,"",`You can use the '${r.RedwoodStyling.info("overwrite")}' flag to create the project even if target directory isn't empty`].join(`
    
    
                                                                                         ^
    
    TypeError: Cannot read properties of undefined (reading 'isSatisfied')
        at C:\Users\LAPTOP\AppData\Local\Yarn\Berry\cache\create-redwood-app-npm-5.2.4-89a5b8212e-8.zip\node_modules\create-redwood-app\dist\create-redwood-app.js:6:504
        at C:\Users\LAPTOP\AppData\Local\Yarn\Berry\cache\check-node-version-npm-4.2.1-c9ead05689-8.zip\node_modules\check-node-version\index.js:130:7
        at end (C:\Users\LAPTOP\AppData\Local\Yarn\Berry\cache\run-parallel-npm-1.2.0-3f47ff2034-8.zip\node_modules\run-parallel\index.js:21:15)
        at done (C:\Users\LAPTOP\AppData\Local\Yarn\Berry\cache\run-parallel-npm-1.2.0-3f47ff2034-8.zip\node_modules\run-parallel\index.js:25:10)
        at each (C:\Users\LAPTOP\AppData\Local\Yarn\Berry\cache\run-parallel-npm-1.2.0-3f47ff2034-8.zip\node_modules\run-parallel\index.js:31:7)
        at C:\Users\LAPTOP\AppData\Local\Yarn\Berry\cache\run-parallel-npm-1.2.0-3f47ff2034-8.zip\node_modules\run-parallel\index.js:41:43
        at C:\Users\LAPTOP\AppData\Local\Yarn\Berry\cache\check-node-version-npm-4.2.1-c9ead05689-8.zip\node_modules\check-node-version\index.js:226:12
        at ChildProcess.exithandler (node:child_process:397:5)
        at ChildProcess.emit (node:events:537:28)
        at maybeClose (node:internal/child_process:1091:16)
    
    Node.js v18.4.0

### How do we reproduce the bug?

Run the command:

    yarn create redwood-app --ts ./redwoodblog

### What's your environment? (If it applies)

```shell
System:
  OS: Windows 10 x64
  Shell: Windows PowerShell
Binaries:
- node version 18.4.0
- npm version 8.13.2
- yarn version 3.6.0
Browsers:
 Chrome: latest version
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Hey @cubu thanks for reporting!

I haven't been able to reproduce this unfortunately. I've got windows 11 running locally and I used powershell to try and reproduce. I could run through create redwood app and then ran the dev server to check. 

We do recommend git bash (https://gitforwindows.org/) when using redwood on windows. We also have some docs on developing on windows (https://redwoodjs.com/docs/how-to/windows-development-setup). If any of that could help?

I'm happy to try and reproduce again if there's any more insight on the issue 🙂

**Comment by cubu** [comment]
Forgot to close this one. Turn out the problem is nvm with multiple Nodejs installation. I reinstalled it and it worked.

**Comment by nbushe** [comment]
> Forgot to close this one. Turn out the problem is nvm with multiple Nodejs installation. I reinstalled it and it worked.
Could you kindly explain how did you do it? I've got the same error and nvm reinstallation doesn't help.

**Comment by loddaa** [comment]
I got the exact same issue on macOS Sonoma after running the command `yarn create redwood-app ./redwoodblog`

yarn -v : 4.0.2
node -v : v20.10.0

```bash
⠙ Checking node and yarn compatibility
/private/var/folders/4h/f7hlg4h14tg26ksnw0cd35tc0000gn/T/xfs-1c4d71bd/dlx-8475/.yarn/cache/create-redwood-app-npm-6.6.4-68d6479ed8-ce143e0722.zip/node_modules/create-redwood-app/dist/create-redwood-app.js:6
`));try{(await o.prompt({type:"select",name:"override-engine-error",message:"How would you like to proceed?",choices:["Override error and continue install","Quit install"],initial:0}))["override-engine-error"]==="Quit install"&&(c("User quit after engine check error"),await a(),process.exit(1))}catch{c("User cancelled install at engine check error"),await a(),process.exit(1)}}}function pe(e){return new Promise(t=>{let{engines:n}=require(l.default.join(e,"package.json"));(0,J.default)(n,(r,s)=>t([s.isSatisfied,s.versions]))})}async function de(e,{templateDir:t,overwrite:n}){let r=e,s=new i.ReactiveTUIContent({mode:"text",content:"Creating project files",spinner:{enabled:!0}});return o.startReactive(s),r=await U(r,{overwrite:n}),y.default.ensureDirSync(l.default.dirname(r)),y.default.copySync(t,r,{overwrite:n}),y.default.renameSync(l.default.join(r,"gitignore.template"),l.default.join(r,".gitignore")),y.default.ensureDirSync(l.default.join(r,".redwood")),y.default.writeFileSync(l.default.join(r,".redwood","telemetry.txt"),A),s.update({spinner:{enabled:!1},content:`${i.RedwoodStyling.green("\u2714")} Project files created`}),o.stopReactive(),r}async function ue(e){let t=new i.ReactiveTUIContent({mode:"text",header:"Installing node modules",content:"  \u23F1 This could take a while...",spinner:{enabled:!0}});o.startReactive(t);let n=process.cwd();process.chdir(e);let r=(0,k.default)("yarn install",{shell:!0,cwd:e});try{await r}catch(s){o.stopReactive(!0),o.displayError("Couldn't install node modules",[`We couldn't install node modules via ${i.RedwoodStyling.info("'yarn install'")}. Please see below for the full error message.`,"",s].join(`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ^

TypeError: Cannot read properties of undefined (reading 'isSatisfied')
    at /private/var/folders/4h/f7hlg4h14tg26ksnw0cd35tc0000gn/T/xfs-1c4d71bd/dlx-8475/.yarn/cache/create-redwood-app-npm-6.6.4-68d6479ed8-ce143e0722.zip/node_modules/create-redwood-app/dist/create-redwood-app.js:6:504
    at /private/var/folders/4h/f7hlg4h14tg26ksnw0cd35tc0000gn/T/xfs-1c4d71bd/dlx-8475/.yarn/cache/check-node-version-npm-4.2.1-c9ead05689-7778e04d24.zip/node_modules/check-node-version/index.js:130:7
    at end (/private/var/folders/4h/f7hlg4h14tg26ksnw0cd35tc0000gn/T/xfs-1c4d71bd/dlx-8475/.yarn/cache/run-parallel-npm-1.2.0-3f47ff2034-200b5ab25b.zip/node_modules/run-parallel/index.js:21:15)
    at done (/private/var/folders/4h/f7hlg4h14tg26ksnw0cd35tc0000gn/T/xfs-1c4d71bd/dlx-8475/.yarn/cache/run-parallel-npm-1.2.0-3f47ff2034-200b5ab25b.zip/node_modules/run-parallel/index.js:25:10)
    at each (/private/var/folders/4h/f7hlg4h14tg26ksnw0cd35tc0000gn/T/xfs-1c4d71bd/dlx-8475/.yarn/cache/run-parallel-npm-1.2.0-3f47ff2034-200b5ab25b.zip/node_modules/run-parallel/index.js:31:7)
    at /private/var/folders/4h/f7hlg4h14tg26ksnw0cd35tc0000gn/T/xfs-1c4d71bd/dlx-8475/.yarn/cache/run-parallel-npm-1.2.0-3f47ff2034-200b5ab25b.zip/node_modules/run-parallel/index.js:41:43
    at /private/var/folders/4h/f7hlg4h14tg26ksnw0cd35tc0000gn/T/xfs-1c4d71bd/dlx-8475/.yarn/cache/check-node-version-npm-4.2.1-c9ead05689-7778e04d24.zip/node_modules/check-node-version/index.js:226:12
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
```

**Comment by loddaa** [comment]
I could solve the issue by downgrading my yarn version.
I ran the command : `yarn set version 1.22.21`

After running the command `yarn create redwood-app ./redwoodblog`, I got a warning : 

```bash
 Warning: Compatibility checks failed ─────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                     │
│     You may want to downgrade the version of node you're using.                                                     │
│     You're using 20.10.0 and we currently support node >=18.0.0 <19.0.0.   
```
I just downgraded my node version to `node 18.18.1` to make it work.

**Comment by Tobbe** [comment]
> I could solve the issue by downgrading my yarn version.
> I ran the command: `yarn set version 1.22.21`

What folder were you in when you ran this command?

**Comment by loddaa** [comment]
> > I could solve the issue by downgrading my yarn version.
> > I ran the command: `yarn set version 1.22.21`
> 
> What folder were you in when you ran this command?

I was in  ~/Programming/projects directory when I ran this command.

**Comment by Tobbe** [comment]
@loddaa Can you please check if you now have a `package.json` in `~/Programming/projects`? I think `yarn set version` would have created that for you

**Comment by loddaa** [comment]
> @loddaa Can you please check if you now have a `package.json` in `~/Programming/projects`? I think `yarn set version` would have created that for you

@Tobbe Yes I have a `package.json` and a `yarn.lock`. Apparently I did the `yarn set version` in my root directory `~/` and not in my `projects` directory.

Now I have removed the `package.json` and the `yarn.lock` and the command to create a new redwood project still works.

**Comment by Tobbe** [comment]
`yarn set version <version>` will update the `package.json` file in the project you're currently in. So if you have a RW project at `~/projects/my-rw-app`, and you're currently in `~/project/my-rw-app` in your terminal and you run `yarn set version <version>` it will update the `packageManager` field in `~/project/my-rw-app/package.json`. In a fresh RW project that setting will be `4.0.2`. If you run `yarn set version 1.22.21` you will downgrade the RW app to use yarn v1, and this is not recommended or supported and has a big risk of breaking your RW project.

If you're in another folder, that isn't already a node project, running `yarn set version` will create a `package.json` file in that directory and set the `packageManager` field. (IMHO yarn shouldn't do this; I think it should just error out instead saying it couldn't find a `package.json` and ask you to set up a project)

**The correct way to change your global version of yarn is to use corepack**

The exact command to use depends on your node version. For Node 20 or newer it's this:
```
corepack install --global yarn@1.22.21 # For a specific version
corepack install --global yarn@stable # For latest stable version. 4.0.2 right now.
```
(Read more here: https://nodejs.org/api/corepack.html#upgrading-the-global-versions)

For older Node versions (like Node 18), the command is this:
```
corepack prepare yarn@x.y.z --activate
```
(from https://nodejs.org/docs/latest-v18.x/api/corepack.html#upgrading-the-global-versions)
