### ISSUE TITLE
[Bug?]: project:sync is broken

### ISSUE THREAD

**Issue by arimendelow** [redwoodjs/redwood#8580]
### What's not working?

Following the [contribution instructions](https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md), I'm attempting to work on a Redwood package alongside my existing project. My project is fully up to date.

I'm running into a few fully breaking issues:
# It flat out breaks my project
After I run the `project:sync` command, I see a successful output:

<img width="589" alt="Screenshot 2023-06-09 at 5 10 59 PM" src="https://github.com/redwoodjs/redwood/assets/16390116/9135bb99-cff8-4535-aa63-46f749f0a4fd">

I then run `yarn rw dev`, but my project now has random breaking issues:

<img width="1282" alt="Screenshot 2023-06-09 at 5 12 09 PM" src="https://github.com/redwoodjs/redwood/assets/16390116/a6dc96a1-bb74-4815-b6ca-98d8df318c88">

# Sync is broken and crashes
I then tried to see if syncing even worked, so I went to the package that I want to work on (auth-providers/dbAuth), and added a simple console log just to see if it would sync. Doing that leads to project:sync crashing:

<img width="884" alt="Screenshot 2023-06-09 at 5 13 37 PM" src="https://github.com/redwoodjs/redwood/assets/16390116/dbf6ffab-c5d4-4bf9-a75e-0dad813b5262">

I've run `git clean -fxd`, `yarn cache clean`... it seems to be an issue with the project itself.

Am I doing something wrong?

Thanks!

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by arimendelow** [comment]
I confirmed that the first issue (failed to execute 'createElement' on 'Document') is a problem with the canary, not the sync itself.

However, trying to run sync once I've upgraded my project to the canary now gives the following:

<img width="890" alt="Screenshot 2023-06-09 at 5 32 20 PM" src="https://github.com/redwoodjs/redwood/assets/16390116/032fd50c-155d-4921-b1aa-bbff1d157a9c">

**Comment by jtoar** [comment]
Hey @arimendelow, I'm actually working on that fixing that error here https://github.com/redwoodjs/redwood/pull/8579. I think I have it fixed and discovered a few more things that weren't quite right with that script. There's still a few improvements I want to make, but I think it fixes the issue you're seeing. Could you confirm for me by pulling down that branch and running `yarn rwfw project:sync` from there?

**Comment by jtoar** [comment]
@arimendelow and about the SVG change, yes that's one of the breaking changes we're working out for the next major. The change was in this PR: https://github.com/redwoodjs/redwood/pull/8301, and WIP codemod here: https://github.com/redwoodjs/redwood/pull/8564

**Comment by arimendelow** [comment]
@jtoar ahhh thanks for the quick reply! that SVG change is easy enough.

I pulled down and built your branch, and then after cleaning up my project, ran `yarn rwfw project:sync` - same error on attempt to sync. Should I be doing something differently?

**Comment by jtoar** [comment]
@arimendelow No I don't think so, all the steps you mentioned seemed like enough. I'll just have to keep trying things to figure out what's going on. I'll post a short video soon showing what I'm doing just so you can double check

**Comment by arimendelow** [comment]
@jtoar sounds good :)

**Comment by jtoar** [comment]
@arimendelow A higher resolution is taking longer to process but here's what I'm doing (there's no audio, just a quick recording I did with Mac's screenshot utility): https://www.youtube.com/watch?v=0yLUZ2GhX-A

One thing I should've asked: what's your OS?

**Comment by jtoar** [comment]
Also add sorry, I'm force pushing to that branch a lot which means if you want the new changes they're a little harder to get locally

**Comment by arimendelow** [comment]
@jtoar thanks! that's pretty in line with what I was doing, I'll pull down your latest changes and report back.

macOS....whatever the latest is 😄

**Comment by arimendelow** [comment]
lol yeah i was wondering what was going on there. no worries!

**Comment by arimendelow** [comment]
@jtoar just tried with your latest changes, still have this issue.

are you able to make edits to DbAuthHandler in sync mode? maybe give that a try as a repro

**Comment by arimendelow** [comment]
@jtoar is there a recommended workflow for working on the framework while you're working on this fix? cc @thedavidprice @cannikin if you have any suggestions :)

**Comment by cannikin** [comment]
You could use `project:copy` instead...you'd have to do it every time there's a change in the framework though. :(

**Comment by arimendelow** [comment]
yeah, i was thinking there'd be a command like that - better than nothing! is that what you've been doing?

**Comment by cannikin** [comment]
Yeah there's been a couple of times when `project:sync` wouldn't work for me. I believe there's a `--watch` flag which makes it even better, it kind of acts like `sync` but isn't quite as fast!

**Comment by arimendelow** [comment]
cool, thanks @cannikin! do you folks think there's an ETA on this fix or should I get used to using project:copy? 🙃

**Comment by thedavidprice** [comment]
@arimendelow If you could try out this PR locally and provide feedback to @jtoar it would be very helpful! (no pressure, to be clear)
https://github.com/redwoodjs/redwood/pull/8579

**Comment by arimendelow** [comment]
@thedavidprice do you know if there have been meaningful updates to the PR since yesterday? as of yesterday, it still didn't work (see above)

**Comment by arimendelow** [comment]
@thedavidprice have you tried editing `packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts`? I just tried with the latest changes (did git clean etc ofc) and I'm still getting the error out.

**Comment by thedavidprice** [comment]
@arimendelow Gah, I just reproduced the error after editing the file. The first time I simply walked through the steps outlined in the PR. Great catch.

I've updated the review here:
https://github.com/redwoodjs/redwood/pull/8579#pullrequestreview-1476060741

**Comment by arimendelow** [comment]
@jtoar @thedavidprice `project:sync` is now working perfectly for me, with one exception - whenever I make a change in a web-side file, I need to do a git clean and rebuild on the project side before it's reflected. Even `project:copy` didn't work for this.

Is that expected? It's quite annoying, but workable.

**Comment by jtoar** [comment]
@arimendelow By web side file, do you mean in your redwood project? Or in the `@redwoodjs/web` package?

**Comment by arimendelow** [comment]
It was specifically the web side auth stuff from the Redwood side

**Comment by arimendelow** [comment]
The auth context provider, for example

**Comment by jtoar** [comment]
Thanks @arimendelow I can reproduce that; the first change takes effect but not subsequent ones, even after re-starting the dev server. I'm guessing it has to do with Vite caching, but don't know for sure so I'll read up on it and ask the team.

**Comment by jtoar** [comment]
@arimendelow so Vite node_modules caching is definitely a thing and it only re-bundles based on these events, which `project:sync` doesn't fall under:

> - Package manager lockfile content, e.g. package-lock.json, yarn.lock, pnpm-lock.yaml or bun.lockb.
> - Patches folder modification time.
> - Relevant fields in your vite.config.js, if present.
> - NODE_ENV value.

Source: https://vitejs.dev/guide/dep-pre-bundling.html#file-system-cache.

We'll figure out how to make this easier, but for now this should save you from having to do a git clean and rebuild. Start your dev server like this:

```
yarn rw dev --forward="--force"
```

Make sure you see this in your terminal:

```
web | Forced re-optimization of dependencies
```

You'll have to restart your dev server every time you make a change, but it'll be much faster than a full git clean and rebuild.

**Comment by arimendelow** [comment]
ahhhh yup makes sense - the workaround works great, thanks @jtoar! :)

**Comment by arimendelow** [comment]
I'll close this bug as I feel your PR fixed it
