### ISSUE TITLE
Redwood CLI Function Generator default body can return HTTP 502 Bad Gateway when deployed to Netlify

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#864]
I generated a new function, let's say it is called "my":

`yarn rw g function my`

and I get the function: `my.js`:

```
export const handler = async (event, context) => {
  return {
    statusCode: 200,
    body: `my function`,
  }
}
```

which is the template:

https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/function/templates/function.js.template#L4

But when deploying to Netlify, having the body not `JSON.stringify`-ed can result in `502 Bad Gateway` errors due to a "Netlify encoding hiccup".

Perhaps it is best to wrap it in a stringify  -- at least to call out/alert the developer that practice.

The lack of JSON.stringify has been noted several times on Netlify community as well:

https://community.netlify.com/t/debugging-a-function-returns-502/429/5

> can you try returning the data like:
```
callback(null, {
  statusCode: 200,
  body: JSON.stringify({
    result: result
  })
});
```

> Let me know if that fixes the issue. It appears to be an encoding hiccup on our end with the raw number/string response

Instead:

```
  return {
    statusCode: 200,
    body: JSON.stringify(`my function`),
  }
```

**Comment by peterp** [comment]
That seems reasonable to me!

**Comment by dthyresson** [comment]
> That seems reasonable to me!

I'll make a quick PR if want to assign to me.

**Comment by peterp** [comment]
Done!
