### ISSUE TITLE
[Bug?]: Clerk auth provider being rate limited due to auth decoder implementation

### ISSUE THREAD

**Issue by o0charlie0o** [redwoodjs/redwood#8641]
### What's not working?

Some quick background:
We have been in touch with Clerk regarding this issue for the last couple of months. They lifted our rate limits in our instance to help out but have recently decided to reinstate them. At the time we were debugging this issue we were able to track it down to the way the auth decoder is implemented in Redwood.

We have a relatively large project with a large number of E2E tests that when running almost immediately triggers the rate limits on the Clerk side due to the number of requests to their backend api.

I think it all comes down to the following line:
https://github.com/redwoodjs/redwood/blob/3dc666d702a8a5c438232558440d878e1384d613/packages/auth-providers/clerk/api/src/decoder.ts#L26

Basically it appears that every single request in the app sends a request to clerk to get the user object. I was able to confirm with Braden at Clerk that this information should just be stored in the jwt using their jwt templates feature.

To test I went ahead and implemented a custom auth decoder which bypasses the line above and adds the user id in using the `jwtPayload.sub`. With the custom auth decoder in place we no longer hit the rate limits.

We would prefer not to have the custom decoder for maintenance reasons so I just wanted to open this issue to get the teams opinion on this issue.

From Clerk: The Backend API current limit (that we apply to all customers) is 100reqs per 10sec.

### How do we reproduce the bug?

This is difficult to reproduce unless you can initiate a bunch of requests from the same IP address (such as during a test run). One thing you could try is having a project with a page that has at least 10 requests (10 different graphql queries) then open 10 tabs and refresh them all within the 10 second time limit. It's pretty easy to hit the other rate limits such as trying to login with 5 tabs one after another as fast as you can.

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by thedavidprice** [comment]
@jtoar and @asher-eastham My understanding is that there's already a fix for this. Correct?

**Comment by asher-eastham** [comment]
@thedavidprice There's a workaround if you write your own `authDecoder` function that doesn't call Clerk's `getUser`, but AFAIK the current `@redwoodjs/auth-clerk-api` package still exhibits the behavior described in the bug. I think the call to `getUser` in the built-in `authDecoder` should get removed since it breaks use cases that make more than 100 API requests every 10s.

Happy to help in any way with the fix!

**Comment by jtoar** [comment]
Opened a PR here where we can talk about the implementation @o0charlie0o and @asher-eastham: https://github.com/redwoodjs/redwood/pull/8642

**Comment by Josh-Walker-GM** [comment]
I think we can close this one now that we have the new and improved clerk specific decoder available. Feel free to reopen if this is still an active issue. 

For people who find themselves here I'd recommend looking at the release notes that cover this as it includes the background and required migration steps: https://github.com/redwoodjs/redwood/releases/tag/v5.3.2
