### ISSUE TITLE
[Bug?]: Login Handler of `dbAuth` cannot handle case insensitive usernames

### ISSUE THREAD

**Issue by dennemark** [redwoodjs/redwood#8676]
### What's not working?

The following issue and PRs introduced feature to allow case insensitive usernames on signup
https://github.com/redwoodjs/redwood/issues/7787
https://github.com/redwoodjs/redwood/pull/7979
https://github.com/redwoodjs/redwood/pull/8045

While it works for the signup handler, it does not work for Login.

@ageddesi mentioned he knows how to solve this, so I hope he can have a look at it :)

### How do we reproduce the bug?

Using a redwoodjs project with standard `dbAuth` flow installed:

- Signup for an account with case sensitive username (Ex: `demoUser` )
- Log out, then log back in trying to use username in all lowercase (Ex: `demouser`)
- Error: Could not find account with matching username
-

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by ageddesi** [comment]
I will get a PR in for this fix :)

**Comment by ageddesi** [comment]
PR Raised. <3
