### ISSUE TITLE
[Bug?]: Redirecting to route "home" would require route parameters, which currently is not supported. Please choose a different route

### ISSUE THREAD

**Issue by anaclumos** [redwoodjs/redwood#8685]
### What's not working?

`<Private unauthenticated="home">` when Home requires parameters will throw an error.

```tsx
const HomePage = ({ locale }) => {
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Tobbe** [comment]
As you discovered, redirecting to a route that requires path parameters is currently not supported. What I recommend you do instead is redirect to a temporary page where you determine the value you want for your route parameter(s) and then just render a `<Redirect />` component.

```tsx
import { Redirect, routes } from '@redwoodjs/router'

const UnauthenticatedPage = () => {
  const locale = 'en'
  return <Redirect to={routes.home({ locale })} />
}
```
