### ISSUE TITLE
[RFC]: Setting for ignoring a folder in chokidar

### ISSUE THREAD

**Issue by hacknaked** [redwoodjs/redwood#8752]
### Summary

Add a configuration setting to instruct `chokidar` ignore a folder in the root project. 

### Motivation

Working with RedwoodJS and Docker in a local environment, I run a Docker container with an external service and mounted a  volume "data" for container persistence.

This folder is scanned by `chokidar` and fails with EACCESS (given that Docker set root permissions on that folder)
```
Error: EACCES: permission denied, watch '..../git/proj/data/bitcoind/testnet3/blocks'
gen |     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
gen |     at Object.watch (node:fs:2343:34)
gen |     at createFsWatchInstance (....../node_modules/chokidar/lib/nodefs-handler.js:119:15
```

There are other use cases when would be nice to add folders in the Redwood root project and prevent `chokidar` to scan them (3rd party tools, infrastructure folders, etc.)

### Detailed proposal

1. Adding a `[chokidar]` section in `redwood.toml ` is probably enough. 
2.  Other option (simpler) would be to hardcode the setting when creating the `chokidar` instance (for example: "ignore all folders that begins with a dot like .data")

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by Tobbe** [comment]
This comment on another issue is also in favor of this feature: https://github.com/redwoodjs/redwood/issues/5403#issuecomment-1337695776

**Comment by hacknaked** [comment]
Seems to be the same feature request! Sorry for the noise, closing this one in favor of #7761.
