### ISSUE TITLE
[Bug?]: [FAILED] nftPack is not a function when running yarn rw deploy serverless

### ISSUE THREAD

**Issue by joeyhotz** [redwoodjs/redwood#8804]
### What's not working?

When I run: `yarn rw deploy serverless --stage dev`, I get a fatal error:

```
25h[COMPLETED] Building api & web...
[STARTED] Packing Functions...
[FAILED] nftPack is not a function
```

### How do we reproduce the bug?

Run `yarn rw deploy serverless --stage dev`

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by geetika-kathuria** [comment]
How do I submit a PR for this, I was able to fix it in my local environment

**Comment by jtoar** [comment]
@joeyhotz could you please fill out the environment information? Namely, what version you're experiencing this on.

We noticed this on the v6 RC, and I merged a fix for it here: https://github.com/redwoodjs/redwood/pull/8857. Are you seeing it on a different version? Are you using the latest v6 RC if you're on the RC?

Hey @geetika-kathuria, if you've discovered a different fix or way this could be going wrong, we'd love a fix. Submitting a PR is just like any other repo—fork, make changes, I'll review them. We have specific contributing instructions here: https://redwoodjs.com/docs/contributing

**Comment by jtoar** [comment]
@joeyhotz, @geetika-kathuria I just released a fix for this: https://github.com/redwoodjs/redwood/releases/tag/v5.4.3. If one of you has time to confirm it works, that'd be great—thank you!

**Comment by joeyhotz** [comment]
@jtoar can confirm that serverless deploy is now working for me 😄 

fwiw I was experiencing this on a github actions agent configured as `runs-on: ubuntu-latest`. I can get the environment information if still necessary but seems its fixed, thank you so much! :)
