### ISSUE TITLE
Move from graphql-iso-date to graphql-scalars

### ISSUE THREAD

**Issue by hemildesai** [redwoodjs/redwood#881]
This is the notice on the [graphql-iso-date](https://github.com/excitement-engineer/graphql-iso-date) GitHub repo - 
```
NOTICE: The scalars defined in this repository have moved to the GraphQL-scalars repository where they will be maintained.
```

It seems like a good idea to start using (graphql-scalars)[https://github.com/Urigo/graphql-scalars] at https://github.com/redwoodjs/redwood/blob/main/packages/api/src/makeMergedSchema/rootSchema.ts#L3

**Comment by peterp** [comment]
Ooh, that's good to know - could you interest you in opening a pull-request?

**Comment by peterp** [comment]
We could also probably replace JSON and JSONObject with the same library.

**Comment by hemildesai** [comment]
Yeah, I'm happy to work on a PR.

**Comment by hemildesai** [comment]
Closing this since the PR has been merged.
