### ISSUE TITLE
[Bug?]: Custom scalars result in untyped resolver arguments

### ISSUE THREAD

**Issue by will-ks** [redwoodjs/redwood#8852]
### What's not working?

If I follow the documentation on [adding a custom scalar](https://redwoodjs.com/docs/graphql#how-to-add-a-custom-scalar) and use the new scalar in an sdl query, the generated QueryResolver's Args type correctly types the argument with the new scalar's type `Scalars['Currency']`:
<img width="321" alt="Screenshot 2023-07-07 at 15 28 23" src="https://github.com/redwoodjs/redwood/assets/12501819/b3f3025f-c55b-4821-b384-06d139a999b3">

However, following this to it's definition shows it is mapped to `any` type:
<img width="589" alt="Screenshot 2023-07-07 at 15 28 30" src="https://github.com/redwoodjs/redwood/assets/12501819/e5fbbe1a-176f-4add-a035-9901d602d226">

Obviously this would be more usefully typed as `string`. Looking at the source of the scalar from `graphql-scalars`, it is asserted as `GraphQLScalarTypeConfig<string, string>`, so it seems like this type is getting lost somewhere in the codegen?: https://github.com/Urigo/graphql-scalars/blob/5dd19a19c392d7e25766099fe589880e6c0bcead/src/scalars/Currency.ts#L57

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 13.4.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /private/var/folders/qw/1z7gzlws32qbjz4k2nhc0rf80000gn/T/xfs-7b181046/node
    Yarn: 3.2.1 - /private/var/folders/qw/1z7gzlws32qbjz4k2nhc0rf80000gn/T/xfs-7b181046/yarn
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 114.0.5735.198
    Firefox: 111.0.1
    Safari: 16.5.1
  npmPackages:
    @redwoodjs/auth-supertokens-setup: 5.3.0 => 5.3.0 
    @redwoodjs/core: 5.3.0 => 5.3.0
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by orta** [comment]
Pretty sure this sort of thing needs to be set up in your gql-codegen config: https://github.com/dotansimha/graphql-code-generator/issues/153#issuecomment-776735610

**Comment by will-ks** [comment]
Thanks @orta, that does the trick!

For anyone else facing this issue, the solution is as simple as creating a `codegen.yml` file in your project root, containing:
```yml
config:
  scalars:
    MyScalar: "string"
# or
    MyScalar: "path/to/file/my-custom-type#MyCustomType"
```

Bit of a shame it can't be inferred, but I guess that's a [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator) issue, not a redwood one.
