### ISSUE TITLE
[Docs]: Tutorial Chapter 2 on routing params ArticleQuery type

### ISSUE THREAD

**Issue by ekafyi** [redwoodjs/redwood#8889]
### Summary and description

I just started doing the tutorials, great job. Came across this minor issue I'd like to clarify.

The [tutorial on Routing Params](https://redwoodjs.com/docs/tutorial/chapter2/routing-params) uses `CellSuccessProps<ArticleQuery>`. While the auto-generated code I get from running `yarn rw g cell Article` uses `CellSuccessProps<FindArticleQuery, FindArticleQueryVariables>` instead.

I use this version: `"@redwoodjs/web": "5.4.3"`

Is the tutorial intentional, or should it be updated? 

eg.

```diff
- export const Success = ({ articles }: CellSuccessProps<ArticlesQuery>) => {
+ export const Success = ({ articles }: CellSuccessProps<FindArticleQuery, FindArticleQueryVariables>) => {
  // ...
}
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by jtoar** [comment]
Hey @ekafyi, glad to hear you're liking the tutorial! Thanks for opening an issue, I think the tutorial is out dated here. If you're up for opening a PR, I'll review.
