### ISSUE TITLE
Could update apollo-client to 3.0?

### ISSUE THREAD

**Issue by zwl1619** [redwoodjs/redwood#89]
Could update apollo-client to 3.0 in this package.json below?
https://github.com/redwoodjs/redwood/blob/master/packages/web/package.json

Apollo Client 3 blog article: 
https://blog.apollographql.com/previewing-the-apollo-client-3-cache-565fadd6a01e

**Comment by thedavidprice** [comment]
We’re watching the releases but currently apollo-client3 and apollo-react4 are in beta. Caching improvements looks nice but not must have forcurrent path. 

Will revisit and open new issue once stable releases are in the wild.
