### ISSUE TITLE
VS Code features not working in RW (b/c of imports)

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#896]
Because of the way RW does imports there are a few useful features of VS Code that aren't working.

# Go to Definition

"Go to Definition" is triggered by F12 or Ctrl+Click in VS Code. The way it should work is, if I Ctrl+Click on a component it should open up the file with the source code for that component. With the way Redwood does imports that doesn't work.

## Current behavior

I start with this
![image](https://user-images.githubusercontent.com/30793/88514782-f0f36000-cfea-11ea-80c3-adfc9788d1e6.png)

I then Ctrl+Click on `<MainLayout>` and the highlight jumps to the import at the top of the file

![image](https://user-images.githubusercontent.com/30793/88515230-aa523580-cfeb-11ea-99ef-99fbcd1e3a18.png)

Ctrl+Click on the import gives me this

![image](https://user-images.githubusercontent.com/30793/88515292-c3f37d00-cfeb-11ea-915e-49b06255b699.png)

This isn't very useful

## Expected behavior

I start with this (notice that I changed to a relative import)

![image](https://user-images.githubusercontent.com/30793/88521094-c3131900-cff4-11ea-8712-5c4976de0223.png)

Ctrl+Click on `<MainLayout>` and I'm taken to this file instead

![image](https://user-images.githubusercontent.com/30793/88515517-1fbe0600-cfec-11ea-8d7f-321abb64803c.png)

# Hover

When hovering a component VS Code should show the "signature" of that component (i.e. telling you what props it takes, what it returns, etc)

## Current behavior

![image](https://user-images.githubusercontent.com/30793/88521426-2dc45480-cff5-11ea-9599-79232dd5b9a1.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/30793/88521287-01103d00-cff5-11ea-84a4-d53dace95322.png)

# Ctrl+Hover

This is the combination of the two features above

## Current behavior

![image](https://user-images.githubusercontent.com/30793/88520920-87784f00-cff4-11ea-97d0-f2ddba8ef11b.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/30793/88520285-a88c7000-cff3-11ea-8257-0ad152ac98d0.png)

**Comment by aldonline** [comment]
In order for VSCode to understand the "src/x/y/z" import specifiers, one option is to include a jsconfig.json (or tsconfig.json) that sets the "paths" compiler option. Something like this:

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "src/*":["src/*"]
    }
  }
}
```

However, given how much "redwood magic" is going on (with "directory named" convention, automatic imports and the importAll macro),
I'm not sure how this interacts with everything else. This is something that needs to be solved holistically, so I defer to @peterp for the final answer.

**Comment by Tobbe** [comment]
Another thing that's not working because of how RW does imports is JSDocs

With a relative import I get this on hover
![image](https://user-images.githubusercontent.com/30793/89693289-67a72c00-d90e-11ea-9f13-335f7dc03b16.png)

With RW imports all I get is this
![image](https://user-images.githubusercontent.com/30793/89693064-ae485680-d90d-11ea-8c89-2b9be977a455.png)

Given how many awesome/helpful VSCode features we're missing out on to have "nicer" imports - is it really worth it?

In the TS projects at work I never manually write any imports anymore, I just let VSCode autoimport whatever I need. So it doesn't matter if it's `../../../` or `../../../../`, I never have to care about that anyway. VSCode does it for me.

**Comment by peterp** [comment]
Hey Tobbe,

This type of DX is an area that really matters to us, so thanks for bringing this up, we're going to fix all of these.

There are really three magical things at play here. I'll explain how they work and give guidance on how one can opt-out if you don't like the behaviour, but I fully expect to make the experience "VSCode compliant" in the near future. Along with the TypeScript work that I'm currently doing.

## Module Alias

1. We introduce an alias `src` that maps against `./api/src/` and `./web/src`:
```js
import { db } from 'src/lib/db'
// -> ./api/src/lib/db
```

@Tobbe I do not know why you're not seeing JSDoc and type information, this is working for me with a standard "create redwood app". Do you have a `jsconfig.json` or `tsconfig.json` that specifies that alias in [paths](https://github.com/redwoodjs/create-redwood-app/blob/21960fe7cd9c41c1546d239c6950a6db4199b6f5/api/jsconfig.json#L4-L6)?

![image](https://user-images.githubusercontent.com/44849/89705989-3eb08680-d962-11ea-8878-cb517a3d5068.png)

### Opting out

Remove the "paths" part from your `{js,ts}config.json` and VSCode should be able to determine the relative imports again.

I believe the amount of places where we reference the `src/` alias is only in  `api/src/functions/graphql.js`

## Directory named imports

2. We use directory named imports.
```js
import MyHeader from 'src/components/MyHeader' 
// -> ./web/src/components/MyHeader/MyHeader.js
```

This is a webpack plugin, we have an open issue to convert it to babel, which will fix a lot of the issues mentioned here.

This only applies to the `web` side.

### Opting out

Rename your component from `MyHeader/MyHeader.js` to `MyHeader/index.js`

## Auto global imports

We use another babel plugin that detects when you're trying to use `gql`, `React` or `PropTypes`

When you use one of those we automatically import them for you. We have just very recently shipped a PR that adds global TypeScript definitions for those.

![image](https://user-images.githubusercontent.com/44849/89705901-520f2200-d961-11ea-9c9d-bd88b4848255.png)

### Opting out

Pretend they don't exist and import them yourself. The plugin is intelligent enough to not import it twice.


## ImportAll/ Import *

These will go away soon. It's an implementation detail that doesn't add any value to the consumer of RWJS.

**Comment by Tobbe** [comment]
Thanks for the detailed response 👍 

> This type of DX is an area that really matters to us, so thanks for bringing this up, we're going to fix all of these.
❤️ 

> @Tobbe I do not know why you're not seeing JSDoc and type information, this is working for me with a standard "create redwood app". Do you have a jsconfig.json or tsconfig.json that specifies that alias in paths?
That screenshot I posted was from the RW framework project. I haven't touched any of the {j,t}sconfnig.json files. But I just went and looked, and it does not seem like these aliases are specified.

> We use another babel plugin that detects when you're trying to use gql, React or PropTypes
This is really nice!

**Comment by Philzen** [comment]
@Tobbe This is also something that has been nagging me every now and then. It's strange, b/c sometimes it works in VSCode, sometimes CTRL-Click just makes it jump to the import statement just as you described.

From my observations, using an absolute import such as `src/layouts/MainLayout/MainLayout` (referencing the file instead of only the component directory) also works, doesn't it?

Related issues:
- #5097
- #5862

**Comment by Tobbe** [comment]
I hadn't seen those other issues, thanks for linking.

If getting rid of directory named imports solves this then I'm all for getting rid of them. But the pushback from the rest of the team is probably going to be pretty strong. So we need to build a very solid case to get this one through. 

I think we need:
 * A clear demonstration of what's not working right now that's reproducible on multiple machines 
 * A PR that removes the directory named imports and instead uses full imports `MainLayout/MainLayout`
 * Another clear demonstration showing all the awesome features we get access to with full imports
   * I know an early argument for using directory named imports was so you wouldn't have to put an `index.js` file in every single directory. So we also need to show that no index file is needed.

Do you want to help with that?

**Comment by Josh-Walker-GM** [comment]
@Tobbe I just ran through your example at the top and in the second comment. I could see the expected behaviour for all of these in a new 6.3.1 project. I'm not sure exactly when these would have been resolved. I also know there are likely other issues like this one that aren't resolved. Thoughts on closing this one?

**Comment by Tobbe** [comment]
Confirmed. Works for me too!
