### ISSUE TITLE
[Bug?]: v6 doesn't allow for a Subscription sdl type.

### ISSUE THREAD

**Issue by noire-munich** [redwoodjs/redwood#8988]
### What's not working?

# What's happening

Going through the normal process to upgrade to v6-rc, here's what I got when running `yarn rw dev`, an issue with my sdl types:

![af1e8869f08b7a24f4d99de282a4bc4a09754c96](https://github.com/redwoodjs/redwood/assets/10271407/641bdefc-4f63-4423-a1ad-86ae8cc992bd)

As mentioned here: https://community.redwoodjs.com/t/redwood-v6-0-0-upgrade-guide/5044/33?u=noire.munich.

I've tried with other types, here's what I got:
![image](https://github.com/redwoodjs/redwood/assets/10271407/11df6d84-a310-4371-bde5-4a2a529a9ba4)

Interestingly, the Client type isn't failing.

# What's expected

I'm not a fan of having a functionaly meaningful term being reserved so ideally, a `Subscription` type should not be a problem. If this is not possible, a warning once the upgrade is complete would do nicely in informing of the reserved names being used in sdl types, maybe with a link to some documentation explaining why it's better to keep those terms reserved.

### How do we reproduce the bug?

All you need is to export such an sdl, only the names of the types matter, not the fields they have:

```ts
export const schema = gql`
  type Mutation {
    id: Int!
    label: String!
    i18nKey: String!
    slug: String!
    status: SubscriptionStatus!
    description: String!
    stripe_id: String!
    base_amount: Int!
    accounts: [Account]!
  }
  type Query {
    id: Int!
    label: String!
    i18nKey: String!
    slug: String!
    status: SubscriptionStatus!
    description: String!
    stripe_id: String!
    base_amount: Int!
    accounts: [Account]!
  }
  type Client {
    id: Int!
    label: String!
    i18nKey: String!
    slug: String!
    status: SubscriptionStatus!
    description: String!
    stripe_id: String!
    base_amount: Int!
    accounts: [Account]!
  }
`
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by dthyresson** [comment]
I believe that the following are reserved types:

```
The following names are reserved and can’t be used to define any other identifiers:

Int
Float
Boolean
String
DateTime
ID
uid
Subscription
as (case-insensitive)
Query
Mutation
Point
PointList
Polygon
MultiPolygon
Aggregate (as a suffix of any identifier name)
```

Therefore if you had a Prisma model and sdl type called Query, this would be a problem, too.

I think the solution isn't to make the type check more lenient, but instead discourage or warn that a model or type uses a reserved term.

For now, the only workaround I can think of is to rename the model and type from `Subscription` to maybe something like `ProductSubscription` etc.

I'll try to think of a better workaround, but that's the only option I have at the moment.

Or ... maybe I can detect if redwood Realtime subscriptions are enables and only check for that reserved term is used. That might be better?

**Comment by dthyresson** [comment]
I confirmed that it is possible to:

* check for some reserved GraphQL types that shouldn't be used (like Float, Polygon,  String etc)
* only check directives of Subscription types if realtime is enabled.

In the latter case, if one uses graphQL Subscriptions you should rename your Type.

You don't have to rename your model, just the types and in your service, return the data for that type instead like 'ProductSubscription'

**Comment by dthyresson** [comment]
@noire-munich have a WIP here https://github.com/redwoodjs/redwood/pull/9005 with an explanation.
