### ISSUE TITLE
Could update apollo-client to 3.0?

### ISSUE THREAD

**Issue by zwl1619** [redwoodjs/redwood#900]
Could update apollo-client to 3.0?

https://www.apollographql.com/blog/announcing-the-release-of-apollo-client-3-0/

**Comment by thedavidprice** [comment]
Hi @zwl1619 and thanks for the prompt! Yes, we've been following this and are eager to take a look at the upgrade path to get to v3! There are a lot of breaking changes so it won't be happening immediately.

Closing this out for now, but don't hesitate to reopen if needed.
