### ISSUE TITLE
[Docs]: Fastify configuration

### ISSUE THREAD

**Issue by chicoxyzzy** [redwoodjs/redwood#9000]
### Summary and description

I want to add some custom Fastify configuration in the Tutorial app from the redwood-tutorial repo, but there's no `api/server.config.js` (and `serverConfig` is not provided in the `redwood.toml`). How can I configure the API server?

**Comment by chicoxyzzy** [comment]
Solved with a Fastify Server File experiment with https://community.redwoodjs.com/t/fastify-server-file-experiment/4851

**Comment by jtoar** [comment]
Hey @chicoxyzzy, glad you found what you were looking for but do take into consideration that the server file is experimental. That post is also unlisted—so props for finding it—but yeah it's very much subject to change. It's something we're excited about though! Also that file missing from the redwood-tutorial repo sounds like a bug, it should be available there.
