### ISSUE TITLE
[Bug]:  Issue generating a component when Tailwind has been added

### ISSUE THREAD

**Issue by ahaywood** [redwoodjs/redwood#9046]
### What's not working?

I'm getting the following error when I try to generate a fresh Redwood component:
![CleanShot 2023-08-16 at 22 34 35](https://github.com/redwoodjs/redwood/assets/212300/fcb9f0b7-0d40-4765-9ff0-2874921d0c41)

### How do we reproduce the bug?

I'm running `@redwoodjs/core": "6.0.7"`

- I created a fresh RedwoodJS project: `yarn create redwood-app partner-tickets`
![CleanShot 2023-08-16 at 22 34 00](https://github.com/redwoodjs/redwood/assets/212300/6433bca5-f7cf-4a32-9117-dd9485c56fd8)
- Ran `yarn install`
- Ran `yarn rw g component badge` and it works 🎉 
- I deleted the `Badge` component so I could test the same command again
- Installed Tailwind: `yarn rw setup ui tailwindcss`
- Now, when I run `yarn rw g component badge` I get the error message

![CleanShot 2023-08-16 at 22 32 24](https://github.com/redwoodjs/redwood/assets/212300/fea67dba-194e-4ea2-92fa-3509b0b15fd5)

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 13.3
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.0 - /private/var/folders/f4/q5j7cnt15hvftx0cp3w8h8nr0000gn/T/xfs-b5f28d87/node
    Yarn: 3.6.1 - /private/var/folders/f4/q5j7cnt15hvftx0cp3w8h8nr0000gn/T/xfs-b5f28d87/yarn
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 115.0.5790.170
    Edge: 115.0.1901.203
    Safari: 16.4
  npmPackages:
    @redwoodjs/core: 6.0.7 => 6.0.7
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by ahaywood** [comment]
I'm getting the same error if I try generating a page or a layout

**Comment by ahaywood** [comment]
Just to make sure this wasn't a user error, I set node to use `v18.16.0` and I'm still getting the same result

**Comment by ahaywood** [comment]
Looks like this is a duplicate of #9035

**Comment by ahaywood** [comment]
Found this on the forums: https://community.redwoodjs.com/t/error-after-setup-tailwind-with-rw-6-0-typescript/5213

**Comment by pantheredeye** [comment]
[Bruce on discord wrote](https://discord.com/channels/679514959968993311/679514959968993476/1142650621921611776):

> FYI I got it to work by running this command. `yarn add --dev prettier prettier-plugin-tailwindcss`

**Comment by faizalheesyam** [comment]
> [Bruce on discord wrote](https://discord.com/channels/679514959968993311/679514959968993476/1142650621921611776):
> 
> > FYI I got it to work by running this command. `yarn add --dev prettier prettier-plugin-tailwindcss`

it works!
this seems better than altering the `package.json` 👍🏻

**Comment by ahaywood** [comment]
I believe this has been resolved.
