### ISSUE TITLE
[Bug?]: RedwoodRecord generate model errors out on parseDatamodel

### ISSUE THREAD

**Issue by Cluster444** [redwoodjs/redwood#9069]
### What's not working?

When running the model generator the file gets written out but then the task fails on the second step writing the new index.js.

yarn rw g model Foo
✔ Generating model file...
  ✔ Successfully wrote file `./api/src/models/TrainingEquipment.js`
← Reverted because: parseDatamodel is not a function
parseDatamodel is not a function

### How do we reproduce the bug?

1) Create a prisma model Foo
2) Run `rw record init`
3) Run `rw g model Foo`

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 13.2.1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /private/var/folders/gp/d_b2mzdn4x3_vqfcjs21k59h0000gn/T/xfs-25d32553/node
    Yarn: 3.6.0 - /private/var/folders/gp/d_b2mzdn4x3_vqfcjs21k59h0000gn/T/xfs-25d32553/yarn
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.3
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 6.1.0 => 6.1.0
    @redwoodjs/core: 6.1.0 => 6.1.0
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by jtoar** [comment]
Hey @Cluster444, thanks for reporting! In reproducing this one, I found that the fix was simple and stole your chance to contribute and opened a PR here, sorry about that: https://github.com/redwoodjs/redwood/pull/9158

**Comment by jtoar** [comment]
Fixed in https://github.com/redwoodjs/redwood/releases/tag/v6.2.1
