### ISSUE TITLE
[Bug?]: Storybook 7.2.0 'Broken Build' error

### ISSUE THREAD

**Issue by pantheredeye** [redwoodjs/redwood#9073]
### What's not working?

I keep running into this problem:

![image](https://github.com/redwoodjs/redwood/assets/77902178/060d27f9-7801-4750-b1ba-3f660b8d5c5a)

and I do not know what is causing it. There was a bug in Storybook 7.2.0 that swallows errors, which is what I am experiencing above. The issue [was patched in 7.2.1](https://github.com/storybookjs/storybook/pull/23689).

Is there a way that I can manually bump the version of storybook to upgrade to 7.2.1?

### How do we reproduce the bug?

I am not sure... storybook was working before I added a couple of components. I feel like there is a problem in my code that is causing this, but I don't see any errors in my code right now. The nature of this issue is that storybook errors are swallowed, so I cannot debug from their end.

### What's your environment? (If it applies)

```shell
System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.14.1 - C:\Users\BBURNW~1\AppData\Local\Temp\xfs-1ac32ce6\node.CMD
    Yarn: 3.6.1 - C:\Users\BBURNW~1\AppData\Local\Temp\xfs-1ac32ce6\yarn.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.54)
  npmPackages:
    @redwoodjs/cli-storybook: 6.1.0 => 6.1.0
    @redwoodjs/core: 6.1.0 => 6.1.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by pantheredeye** [comment]
Update on this:

Storybook fails on a fresh install with this error:

```
99% end closing watch compilationWARN Force closed preview build
ModuleBuildError: Module build failed (from ../node_modules/babel-loader/lib/index.js):
Error: Cannot find package 'babel-plugin-graphql-tag' imported from C:\Users\bburnworth\Documents\Code\SBTest2\babel-virtual-resolve-base.js
```

![image](https://github.com/redwoodjs/redwood/assets/77902178/faf3daa2-6b36-4072-8429-e52a0cca3232)

### Yarn RW Info

```
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.14.1 - C:\Users\BBURNW~1\AppData\Local\Temp\xfs-c2900538\node.CMD
    Yarn: 3.6.3 - C:\Users\BBURNW~1\AppData\Local\Temp\xfs-c2900538\yarn.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.69)
  npmPackages:
    @redwoodjs/cli-storybook: 6.2.0 => 6.2.0
    @redwoodjs/core: 6.2.0 => 6.2.0
    ```

### Help 

Where should I look to try and help diagnose or fix this?

**Comment by pantheredeye** [comment]
Temp fix within a project from @Josh-Walker-GM works for me:

`yarn add babel-plugin-graphql-tag @babel/plugin-transform-runtime`

**Comment by chenull** [comment]
i had the same issue, but then upgraded to `6.2.0` which just released days ago, and storybook came back normal

**Comment by jtoar** [comment]
@pantheredeye, @chenull, could you two try the latest patch? I believe I've gotten to the bottom of the issue: https://github.com/redwoodjs/redwood/releases/tag/v6.2.1

**Comment by chenull** [comment]
> @pantheredeye, @chenull, could you two try the latest patch? I believe I've gotten to the bottom of the issue: https://github.com/redwoodjs/redwood/releases/tag/v6.2.1

@jtoar just upgraded. storybook is now working

**Comment by jtoar** [comment]
@chenull awesome! closing this one for now then
