### ISSUE TITLE
[Bug?]: Tailwind setup fails due to latest dep requiring Prettier v3 

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#9075]
### What's not working?

See this Forum thread: https://community.redwoodjs.com/t/error-after-setup-tailwind-with-rw-6-0-typescript/5213

^^ Includes a workaround.

## What's happening?
The Tailwind dependency `prettier-plugin-tailwindcss` requires Prettier v3 as of version >= 0.5.
- https://github.com/tailwindlabs/prettier-plugin-tailwindcss/releases/tag/v0.5.0

Prettier v3 was released on July 5th (bummer we missed it for RW v6), and will need to be included in the next Redwood major:
- https://prettier.io/blog/2023/07/05/3.0.0.html

Prettier v3 is now ESM but does support CJS (migration guide in post above).

## Next Steps
PR to work around for now is here:
 - #9076

For v7 (next major), here are the PRs to revert current workaround and resolve via Prettier v3 support:
- https://github.com/redwoodjs/redwood/pull/9077
- https://github.com/redwoodjs/redwood/pull/9078

### How do we reproduce the bug?

This will fail for _any_ version of Redwood when running the command: `yarn rw setup ui tailwindcsss`

The setup command always uses the latest versions of the Tailwind dependencies.

### Are you interested in working on this?

- [x] I'm interested in working on this

**Comment by ahaywood** [comment]
Once this is resolved, it will also fix #9046 and #9035 (duplicates)

**Comment by papaponmx** [comment]
Not sure if this adds to the conversation but I can confirm that today.
I have a fresh setup, that just ran `yarn rw setup ui tailwindcss` 

then ran 
```
yarn redwood generate page Home
```
and found the error below which is quite similar to [#9076](https://github.com/redwoodjs/redwood/pull/9076).

```
← Reverted because: Error applying template at
  /Users/papaponmx/Projects/prioritize-me/node_modules
  /@redwoodjs/cli/dist/commands/generate/page/template
  s/page.tsx.template for Home: require() of ES Module
  /Users/papaponmx/Projects/prioritize-me/node_modules
  /prettier-plugin-tailwindcss/dist/index.mjs not
  supported.
  Instead change the require of
  /Users/papaponmx/Projects/prioritize-me/node_modules
  /prettier-plugin-tailwindcss/dist/index.mjs to a
  dynamic import() which is available in all CommonJS
  modules.
◼ Updating routes file...
◼ Generating types...
◼ One more thing...
Error applying template at /Users/papaponmx/Projects/prioritize-me/node_modules/@redwoodjs/cli/dist/commands/generate/page/templates/page.tsx.template for Home: require() of ES Module /Users/papaponmx/Projects/prioritize-me/node_modules/prettier-plugin-tailwindcss/dist/index.mjs not supported.
Instead change the require of /Users/papaponmx/Projects/prioritize-me/node_modules/prettier-plugin-tailwindcss/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.

```

**Comment by dustinsgoodman** [comment]
I think there may be some other lint related issues to installing Tailwind. I took the patch and locked in at version 0.4.1 for the tailwind prettier plugin but I also had to install several other deps to get linting to work again. I'm on a `v6.2.0` install of Redwood with Tailwind installed as of `v6.1.0`. If you revert [this commit on this repo](https://github.com/dustinsgoodman/event-platform/commit/29ef9e049dfddf5c02e1af2d9827dc627b6c9711), linting will start failing.

![image](https://github.com/redwoodjs/redwood/assets/1815379/42bcdf20-2876-42ad-9506-5f9e84f99dc7)

Here are the error messages I got:
![image](https://github.com/redwoodjs/redwood/assets/1815379/4fbc174c-7702-46c4-a4e9-f5292f770f9c)
![image](https://github.com/redwoodjs/redwood/assets/1815379/dcaf95ae-1273-46f5-a04b-36c6ffded4a4)
![image](https://github.com/redwoodjs/redwood/assets/1815379/3eebbb44-c6da-430e-9897-5de4a14971ed)


The first 2 were resolved but adding the specified dep to devDeps. The last one required the patch fix from this issue.

**Comment by dustinsgoodman** [comment]
Adding to the above, turns out I had to do one more dependency install to fix the dev server. Seems like [this](https://github.com/dustinsgoodman/event-platform/commit/9f92b7cc8dcb73cd2d39233664f0aec847abc11b#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R11) is also needed to resolve dev server issues. I did try reducing down to just the tailwind patch but that wasn't sufficient here.

**Comment by dustinsgoodman** [comment]
I did the following to get back to a stable state for those following along:
1. Upgrade to Redwood 6.2.2
2. Re-run the tailwind set up with `yarn rw setup ui tailwindcss --force`
3. I had manually installed prettier and needed to uninstall it.

All good now.

**Comment by ehowey** [comment]
> I did the following to get back to a stable state for those following along:
> 
> 1. Upgrade to Redwood 6.2.2
> 2. Re-run the tailwind set up with `yarn rw setup ui tailwindcss --force`
> 3. I had manually installed prettier and needed to uninstall it.
> 
> All good now.

This worked for me too in case anyone else runs into the issue.

**Comment by ahaywood** [comment]
I believe this has been resolved.
