### ISSUE TITLE
further "join the discussion" Redwood Installation copy

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#909]
this is Part 2 of https://github.com/redwoodjs/redwood/issues/811 and #889

- [ ] make two sections: current one for community, second for Tutorial and Docs
- [ ] add redirect for signup via Netlify settings on .com
- [ ] cleanup and/or redirect discord server (probably not necessary)

**Merging content originally in #200**
Other ideas for improvements, which we should scrutinize as we don’t want to overdue it.
- CLI help/commands -- or list main commands
- cleaner text for `cd your-new-dir` then `yarn rw dev`
- `git init && git add .` then first commit

Perhaps we need a "Next Steps" page to link to on website -- bare-bones how to get started and helpful links. Maybe?

_Example from CreateReactApp_
```bash
Created git commit.

Success! Created my-app at /Users/price/Repos/my-app
Inside that directory, you can run several commands:

  yarn start
    Starts the development server.

  yarn build
    Bundles the app into static files for production.

  yarn test
    Starts the test runner.

  yarn eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd my-app
  yarn start

Happy hacking!
```

**Comment by robobunny** [comment]
I think I could help with this. I'm going to post on the discord though because I may need a bit of hand holding as it's my first OSS contribution...
