### ISSUE TITLE
[Bug?]: redwood doesn't recognize storybook config files with `ts`, `tsx` extensions.

### ISSUE THREAD

**Issue by bnn1** [redwoodjs/redwood#9118]
### What's not working?

After I rename storybook config files, for example `storybook.preview.js` to `storybook.preview.ts`, storybook reverts back to default preview configuration.

### How do we reproduce the bug?

1. init a ui library, i.e. `yarn rw setup ui mantine`
2. rename `storybook.preview.js` to `storybook.preview.tsx`
3. run storybook to see that providers/css files imported in preview file have no effect

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by bnn1** [comment]
I'd want to work on this issue. I already am 😅

**Comment by jtoar** [comment]
Hey @bnn1, thanks for reporting this and sorry for the delay! Have you started on a PR? I'd be happy to review.

**Comment by bnn1** [comment]
Hi @jtoar. I've been working on the issue but no PR yet. I'll keep you updated.

**Comment by beardo01** [comment]
Adding support for this PR. Would like to get this working as Storybook is currently not working with Mantine UI for me.

**Comment by bnn1** [comment]
@beardo01 it's most likely related to another issue: https://github.com/redwoodjs/redwood/issues/9316
That issue is already being worked on
