### ISSUE TITLE
Add missing "documentation" links to vscode outline

### ISSUE THREAD

**Issue by aldonline** [redwoodjs/redwood#915]
This is an easy issue on an interesting part of the codebase.

# The feature

* I added a few documentation links to the outline but I left the job unfinished (on purpose). There are more documentation links to be added.
* This is what the feature looks like:

<img width="336" alt="Screen Shot 2020-07-30 at 4 11 27 PM" src="https://user-images.githubusercontent.com/154884/88983313-8444c380-d27f-11ea-9ee0-1e55acf4ef74.png">

* The code for the outline is [here](https://github.com/redwoodjs/redwood/blob/main/packages/structure/src/outline/outline.ts)
* And here's the [interesting bit](https://github.com/redwoodjs/redwood/blob/ffed13f62826b6b725c971bd0dcd6d346de6878d/packages/structure/src/outline/outline.ts#L27)
* You should be able to see the pattern and repeat

# How to develop and test IDE Features

* Install the [Decoupled Studio](https://marketplace.visualstudio.com/items?itemName=decoupled.studio) VSCode extension
* Open (in vscode) any Redwood project ( >= 0.15.0 )
* Confirm that you see the outline and other IDE features
* This means that the VSCode extension is reaching into the node_modules folder and using the installed redwood framework version for the workspace/app. In other words, VSCode is calling the `redwood` CLI under the hood (this is not 100% accurate but it gives you an idea)
* This means that, if you make changes to the redwood framework you're using, you should see the outline change (after refreshing/restarting the VSCode window)
* In order to edit the redwood framework, you need to follow the [local development instructions](https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md#local-development)

Please feel free to comment and improve on these instructions.

**Comment by awey95** [comment]
I would like to try my hand at this since it's tagged as `good first issue`. This is probably simple since you left it unfinished but I'm not exactly sure what it is I'm suppose to be fixing. I installed the extention, created a new RW project, opened up VSCode but I do not see any of those icons.

**Comment by jtoar** [comment]
Hey @awey95 glad you're excited to start contributing! :rocket: There's actually a PR (#935) aiming to close this one out. You're more than welcome to get in touch with @forresthayes over there. Every PR always has a ton of discussion around it, and adding to the discussion around a PR _is_ contributing!  

But if you're looking to champion an approachable issue, might I suggest https://github.com/redwoodjs/redwood/issues/912? You'd get to dive into the toml file, which is much more the hub of a Redwood app than it looks on the surface.

And if anything else looks interesting to you, `good first issue` or not, we're all ready to help and make it as approachable as possible!

**Comment by awey95** [comment]
Hey @jtoar I'll take a look at the discussion for #935 and also see if I'm capable of working on #912. Thanks for the encouragement. :)
