### ISSUE TITLE
[Bug?]: yarn rw dataMigrate up not recognized on 6.2.0

### ISSUE THREAD

**Issue by jacebenson** [redwoodjs/redwood#9150]
### What's not working?

I was working on a little project and saw in the terminal I could upgrade from 6.1.0 to 6.2.0, so i did.

After I spent the next hour trying to figure out why I couldn't deploy.  It seems that `yarn rw dataMigrate up` doesn't work on 6.2.0 for me on windows.

I haven't tried it else where. 

After reverting my version of redwood in my package.json files to 6.1.0 all is well.

Here's the output I got when trying to run that manually (it's a part of the deploy command, `yarn rw deploy render api`)

![image](https://github.com/redwoodjs/redwood/assets/638764/ed3d6932-1925-4970-ab99-69c5c7dbcae2)

### How do we reproduce the bug?

```sh
# upgrade to 6.2.0
yarn rw upgrade
# make a schema change to yoru database
yarn rw dataMigrate up
```

### What's your environment? (If it applies)

```shell
System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 18.17.1 - ~\AppData\Local\Temp\xfs-6d54c121\node.CMD
    Yarn: 3.6.1 - ~\AppData\Local\Temp\xfs-6d54c121\yarn.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.76)
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 6.1.0 => 6.1.0
    @redwoodjs/core: 6.1.0 => 6.1.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
@jacebenson I have one idea in my head why this might not be working. Could you try upgrading again and then deleting the `.redwood/commandCache.json` file. Hopefully you should then be able to run the command normally after that. If you can confirm this fix then I'll implement the patch framework side to fix this - should be just a one or two line update :crossed_fingers:

**Comment by jacebenson** [comment]
The repo I was working on I can't modify today.  Tomorrow I'll work on recreating the issue and follow your suggestion.

**Comment by jtoar** [comment]
Hey @jacebenson, gentle ping—did @Josh-Walker-GM's suggestion work?

**Comment by jacebenson** [comment]
@jtoar and @Josh-Walker-GM I'm giving it a go now.

```sh
yarn rw upgrade # to 6.2.1
yarn rw dataMigrate up # results in "Unknown arguments: dataMigrate, up
# Trying Josh's suggestion.
rm .redwood/commandCache.json # no error seems to deleted it
yarn rw dataMigrate up # seems to work
```

**Comment by jtoar** [comment]
thanks @jacebenson!

**Comment by jtoar** [comment]
Closed by https://github.com/redwoodjs/redwood/pull/9169
