### ISSUE TITLE
[Bug?]: Better error message expected when another file ends with Page.tsx in a page component folder

### ISSUE THREAD

**Issue by standuprey** [redwoodjs/redwood#9165]
### What's not working?

I often create hooks with the same name has the component prefixed with use to extract logic from component and being able to test that logic in isolation. But Redwood doesn't allow to do that for page components.

In my case I have
```
WaitlistPage
- WaitlistPage.tsx
- useWaitlistPage.tsx
```

The extension of my hook being tsx is an oversight, but the error was not helpful to uncover this:

```
web |   The symbol "WaitlistPage" has already been declared
web |   273|    LazyComponent: lazy(() => import( /* webpackChunkName: "WaitlistPage" */"./pages/WaitlistPage/WaitlistPage"))
web |   274|  };
web |   275|  const WaitlistPage = {
web |      |        ^
web |   276|    name: "WaitlistPage",
web |   277|    prerenderLoader: name => ({
```

A good error message would be to just say that only one *Page.tsx file should be present in this folder

### How do we reproduce the bug?

Add a file in a page folder ending with Page.tsx

### What's your environment? (If it applies)

redwood 6.2.0

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by standup75** [comment]
Actually this seems to be an issue regardless of the extension being `ts` or `tsx`

**Comment by jtoar** [comment]
Thanks for reporting @standup75! Yeah the error message could be better here. I'm guessing the error originates in the babel plugin for auto loading routes: https://github.com/redwoodjs/redwood/blob/main/packages/babel-config/src/plugins/babel-plugin-redwood-routes-auto-loader.ts. Looking at the tests, there's no test case that covers two files ending in "Page.{js,jsx,ts,tsx}".
