### ISSUE TITLE
VSCode outline item for "private" routes should have a different icon

### ISSUE THREAD

**Issue by aldonline** [redwoodjs/redwood#917]
This is another feature I left un-implemented on purpose. It has two parts:

1. Implement an isPrivate() getter in [RWRoute.ts](https://github.com/redwoodjs/redwood/blob/main/packages/structure/src/model/RWRoute.ts) that captures the heuristics to determine if a route is private or not. This is the hard bit.
2. Modify [getOutline()](https://github.com/redwoodjs/redwood/blob/ffed13f62826b6b725c971bd0dcd6d346de6878d/packages/structure/src/outline/outline.ts#L8) to change the icon when `route.isPrivate === true`. You'll notice that there is some old code/stub that references a property called `route.isAuthenticated`. The "isAuthenticated" name is from before the "Private" tag name was chosen.

Here are some pointers:

* In the isPrivate() method, you can start from the [JSX node (ts-morph)](https://github.com/redwoodjs/redwood/blob/ffed13f62826b6b725c971bd0dcd6d346de6878d/packages/structure/src/model/RWRoute.ts#L25) of the route and check if the parent's tag name is "Private"
* The outline uses [Codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html). I am using `gist` and `gist-secret`
* You can find more details on the dev workflow on [this issue](https://github.com/redwoodjs/redwood/issues/915)

**Comment by aldonline** [comment]
While you're at it, delete the [`route.isAuthenticated`](https://github.com/redwoodjs/redwood/blob/ffed13f62826b6b725c971bd0dcd6d346de6878d/packages/structure/src/model/RWRoute.ts#L41) getter. It is a leftover from the old days. The new name should be `isPrivate`.

**Comment by M0nica** [comment]
I am planning on working on this ticket and https://github.com/redwoodjs/redwood/issues/920.

**Comment by aldonline** [comment]
Closed by @M0nica in #1331
