### ISSUE TITLE
[Bug?]: issue setting up WebAuthn with dbAuth

### ISSUE THREAD

**Issue by charity1475** [redwoodjs/redwood#9170]
### What's not working?

trying to setup rw dbAuth using both username pass and WebAuthn , https://redwoodjs.com/docs/auth/dbauth . here is my prisma types: 
```js
model User {
  id                  Int              @id @default(autoincrement())
  email               String           @unique
  hashedPassword      String
  salt                String
  resetToken          String?
  resetTokenExpiresAt DateTime?
  role                String
  webAuthnChallenge   String?          @unique
  verified            Boolean          @default(false)
  credentials         UserCredential[]
}

model UserCredential {
  id         String  @id
  userId     Int
  user       User    @relation(fields: [userId], references: [id])
  publicKey  Bytes
  transports String?
  counter    BigInt
}
```
  did every thing as in docs but could not understand this line 
 import WebAuthnClient from '@redwoodjs/auth/webAuthn'
 when i try to import it i get the error 
[plugin:vite:import-analysis] Failed to resolve import "@redwoodjs/auth/webAuthn" from "src/App.jsx". Does the file exist?
```
/Users/charity/Github/e-shop/web/src/App.jsx:4:27
18 |  import { RedwoodApolloProvider } from "@redwoodjs/web/apollo";
19 |  import { AuthProvider, useAuth } from "@redwoodjs/auth";
20 |  import WebAuthnClient from "@redwoodjs/auth/webAuthn";
   |                              ^
21 |  import FatalErrorPage from "./pages/FatalErrorPage/FatalErrorPage";
22 |  import Routes from "./Routes";
```
  also in my generated pages : 
```js
import { Link, navigate, routes } from '@redwoodjs/router'
import { MetaTags } from '@redwoodjs/web'
import { toast, Toaster } from '@redwoodjs/web/toast'

import { useAuth } from 'src/auth'

const LoginPage = () => {
  const { isAuthenticated, logIn } = useAuth()
```
  this src/auth was not generated
[Self-hosted Authentication (dbAuth) | RedwoodJS Docs](https://redwoodjs.com/docs/auth/dbauth)
Redwood's own dbAuth provides several benefits:

### How do we reproduce the bug?

https://redwoodjs.com/docs/auth/dbauth

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 11.7.8
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /private/var/folders/37/06hrjysj5775q979wm1dph600000gn/T/xfs-76f46826/node
    Yarn: 3.6.3 - /private/var/folders/37/06hrjysj5775q979wm1dph600000gn/T/xfs-76f46826/yarn
  Databases:
    SQLite: 3.32.2 - /Users/charity/Library/Android/sdk/platform-tools/sqlite3
  Browsers:
    Chrome: 117.0.5938.62
    Safari: 16.6
  npmPackages:
    @redwoodjs/auth: ^6.2.1 => 6.2.1
    @redwoodjs/auth-dbauth-setup: 6.2.1 => 6.2.1
    @redwoodjs/cli-storybook: 6.2.1 => 6.2.1
    @redwoodjs/core: 6.2.1 => 6.2.1
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jtoar** [comment]
hey @charity1475, thanks for reporting—unfortunately it looks like some of that documentation is outdated. instead of importing it from the auth package, it should be imported from `@redwoodjs/auth-dbauth-web/webAuthn`.  

if you use the setup command, it'll do the right thing for you: `yarn rw setup auth dbAuth`. just say "yes" at the webAuthn prompt.

i'll see about updating the docs here.

**Comment by charity1475** [comment]
thanks, I see.
