### ISSUE TITLE
Add error diagnostic: notfound page cannot be private

### ISSUE THREAD

**Issue by aldonline** [redwoodjs/redwood#920]
* Today, the IDE has no problem with me wrapping the `notfound` page with a `<Private>` tag.
* This should be an error.

How to implement this?

* You just need to modify the [RWRoute class](https://github.com/redwoodjs/redwood/blob/main/packages/structure/src/model/RWRoute.ts)
  * Implement the `isPrivate` getter (see #917 - another issue that requires this getter to be implemented - so both issues could be solved together)
  * modify the `diagnostics()` method to check for an additional error condition

**Comment by M0nica** [comment]
I am planning on working on this ticket and https://github.com/redwoodjs/redwood/issues/917.

**Comment by M0nica** [comment]
This issue _should_ be resolved now as of https://github.com/redwoodjs/redwood/pull/1325
