### ISSUE TITLE
[RFC]: Pass props to a cell's Success component

### ISSUE THREAD

**Issue by taivo** [redwoodjs/redwood#9263]
### Summary

Currently props assigned to a cell is only passed to `beforeQuery`. It would be useful to have `props` passed to the Success component as well. One example usecase is for using a list cell to generate a `<SelectField`, something like this:

```
export const Success = ({ skills }: CellSuccessProps<SkillsQuery>) => {
  return (
    <SelectField name="skills" multiple={true} className="rw-input">
      {skills.map(({ id, skillName, skillLevel }) => {
        return (
          <option key={id} value={id}>
            {skillName} - {skillLevel}
          </option>
        )
      })}
    </SelectField>
  )
}
```

If we have access to props here, `multiple, className, etc.` can be set via the parent SkillsCell component, giving it more flexible usage. 

### Motivation

More flexibility and power for cells.

### Detailed proposal

Info in the summary section.

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Tobbe** [comment]
This should already work

I just tried it in a fresh project, and it seems to work for me

I added the `successProp` here
<img width="499" alt="image" src="https://github.com/redwoodjs/redwood/assets/30793/9c095e68-cc98-4d56-ba35-8f4273c28f71">

Here I receive the prop and print it to the console
<img width="617" alt="image" src="https://github.com/redwoodjs/redwood/assets/30793/b8114d66-2ecc-4572-bc20-c439aa6d306f">

And this is the text showing up in my browser console
<img width="492" alt="image" src="https://github.com/redwoodjs/redwood/assets/30793/b56295f0-b5cf-4f10-a17d-2e048a4617ab">

**Comment by taivo** [comment]
My mistake. Type intersection was the missing part of the puzzle for me, e.g. `{ successProp: string } & CellSuccessProps<FindUserExamples>)`

Thank you @Tobbe
