### ISSUE TITLE
[Bug?] [Documentation] Implicit n:m in prisma does not have `@@id` (*explicit* does)

### ISSUE THREAD

**Issue by Philzen** [redwoodjs/redwood#9287]
### What's not working?

I was trying to understand how to create SDL for a composite primary key (but failed so far so [asked over here](https://community.redwoodjs.com/t/composite-primary-keys-howto-prisma-is-fine-sdl-generator-fails/5435)) which led me to https://redwoodjs.com/docs/schema-relations#many-to-many-relationships which mentions the `@@id` token. There it says:

> Prisma's **implicit** many-to-many relationships create a table without a single field marked with the @id attribute. Instead, it uses a similar attribute: [@@id](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#id-1) to define a multi-field ID.

Looking at the prisma docs for [implicit](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#implicit-many-to-many-relations) vs. [explicit](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#explicit-many-to-many-relations) n:m relations, it shows clearly that only *explicit* have an `@@id` primary key.

The Redwood docs go on to say:

> Since there's no single `@id` field in implicit many-to-many relationships, you can't use the SDL generator with the --crud flag.

That is true, there is no `@id` field in implicit (but there is, however, a composite primary key in explicit) relationships.

So what is unclear about reading this section (and browsing the page) is:
1. isn't that first doc section actually referring to *explicit* n:m relationships?
2. so what about primary composite keys (`@@id`) at all?

- [X] I'm interested in working on this (but i have virtually no time atm)

**Comment by Tobbe** [comment]
Sorry this issue slipped through without any response @Philzen.

> Prisma's implicit many-to-many relationships create a table without a single field marked with the `@id` attribute. Instead, it uses a similar attribute: [`@@id`](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#id-1) to define a multi-field ID.

I still think this is correct. Notice how it says Prisma creates a *table*. The table isn't visible in your schema file. So you won't see the `@@id` stuff. If you inspect your DB though, I'm sure you'll find this table that prisma created for you, and it should have constraints/keys matching up with what's essentially `@@id`. Exactly how this looks will depend on what DB engine you use.

And to answer your second question, the answer is unfortunately that RW's generators don't support composite IDs. You need to create a separate id field and then use `@@unique` to get the same effect as `@@id`. I know that can be a little annoying, but shouldn't actually matter in practice.

For now we don't plan on adding support for this to our generators. Or other more advanced features for that matter. The generator code is plenty complex as it is already 😅 

That said - if someone from the community came with a clean PR for adding this we'd be very grateful 😉 

Closing this for now. For anyone looking to pick this up, the next step would be to submit a well tested PR 🙏
