### ISSUE TITLE
Generators: When building a sdl file the model is case sensitive

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#93]
Causing the following failure:

```
➜ yarn rw g sdl userexamples
yarn run v1.21.1
$ /Users/peterp/Personal/redwoodjs/xxx/node_modules/.bin/rw g sdl userexamples
Invoking service generator
Wrote ./api/src/services/userexamples.js 152 bytes
(node:11457) UnhandledPromiseRejectionWarning: No schema definition found for `Userexample`
(node:11457) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Invoking service generator
Wrote ./api/src/services/userexamples.js 152 bytes
```

`UserExample` exists in schema.prisma

**Comment by cannikin** [comment]
I have a note in the tutorial that you have to give SOME indication that there are separate words when using the generators, in this case either `user_example`, `UserExample` or `userExample`.

We could parse the schema and downcase everything to match in this case, but when creating pages or cells or anything else we couldn’t do anything to help them. I’m inclined to stick with the case requirement in all cases. We could even do that here but provide a “did you mean UserExample?” error message if something in the schema DID match, to get them in the habit of casing?

**Comment by peterp** [comment]
Aight, I see... I was thinking that the schema would be the source of truth, and it would generate files based on the cases in the schema?

**Comment by cannikin** [comment]
Well, one issue may be that we're settling on the convention that all components/cells are Uppercase first letter, kind of React convention. But I noticed that in the latest Prisma [getting started guide](https://github.com/prisma/prisma2/blob/master/docs/getting-started.md) they're actually naming models with lowercase (they're also plural here where they used to be singular): 

```
model posts {
  author_id  users?
  content    String?
  created_at DateTime?
  post_id    Int       @id
  title      String
}

model profiles {
  bio        String?
  profile_id Int     @id
  user_id    users
}

model users {
  email      String     @unique
  name       String?
  user_id    Int        @id
  postses    posts[]
  profileses profiles[]
}
```

So if we used that case as the gospel then we'd have lowercase files all over the place. 

The way the generators work currently is that they try to look up the schema definition by whatever case you supplied on the command line, but then always set "proper" case for the generated files.

What do you think @mojombo? How to reconcile what users enter on the command line with what's defined in the schema?
