### ISSUE TITLE
[Bug?]: Props from nested sets are propagating up to parent sets

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#9304]
### What's not working?

We have this test case in the framework
```tsx
describe('Multiple nested sets', () => {
  const HomePage = () => <h1>Home Page</h1>
  const Page = () => <h1>Page</h1>

  const DebugLayout = (props) => {
    return (
      <div>
        <p>Theme: {props.theme}</p>
        <p>Other Prop: {props.otherProp}</p>
        <p>Page Level: {props.level}</p>
        {props.children}
      </div>
    )
  }

  const TestRouter = () => (
    <Router>
      <Route path="/" page={HomePage} name="home" />
      <Set level="1" theme="blue" wrap={DebugLayout}>
        <Route path="/level1" page={Page} name="level1" />
        <Set level="2" theme="red" otherProp="bazinga">
          <Route path="/level2" page={Page} name="level2" />
          <Set level="3" theme="green">
            <Route path="/level3" page={Page} name="level3" />
          </Set>
        </Set>
      </Set>
    </Router>
  )

  test('level 1, matches expected props', async () => {
    const screen = render(<TestRouter />)

    act(() => navigate('/level1'))

    await waitFor(() => {
      expect(screen.queryByText(`Theme: blue`)).toBeInTheDocument()
      expect(screen.queryByText(`Page Level: 1`)).toBeInTheDocument()
    })
  })

  test('level 2, should override level 1', async () => {
    const screen = render(<TestRouter />)

    act(() => navigate('/level2'))

    await waitFor(() => {
      expect(screen.queryByText(`Theme: red`)).toBeInTheDocument()
      expect(screen.queryByText(`Other Prop: bazinga`)).toBeInTheDocument()
      expect(screen.queryByText(`Page Level: 2`)).toBeInTheDocument()
    })
  })

  test('level 3, should override level 1 & 2 and pass through other props', async () => {
    const screen = render(<TestRouter />)

    act(() => navigate('/level3'))

    await waitFor(() => {
      expect(screen.queryByText(`Theme: green`)).toBeInTheDocument()
      expect(screen.queryByText(`Other Prop: bazinga`)).toBeInTheDocument()
      expect(screen.queryByText(`Page Level: 3`)).toBeInTheDocument()
    })
  })
})
```

I think it's wrong. The `theme` prop from level 2 and level 3 should not be passed to `DebugLayout`. It should only always see "blue".

Going back to RW v4.5.0 I see the behavior I'm expecting. So this is new(ish)

### How do we reproduce the bug?

Just run `yarn test` in the framework and that testcase will be run. But because the assumptions in the test case are wrong (IMO) it'll pass. But if you update them to behave like the router used to be have the test case will start to fail.

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by dac09** [comment]
@Tobbe could you write up the expected behaviour please? I kind of understand what you've written, but the tests look correct to me - so must not fully understand.

**Comment by Tobbe** [comment]
Sure. The `DebugLayout` is specified on the "level 1" Set. So it should only ever get the props also specified on that same Set. So `DebugLayout` should always print "Theme: blue" etc, no matter what props might be present on other (nested) Sets. And going back to RW v4 that's the behavior I'm seeing. But currently, on the latest version of RW props on nested sets overwrite the props of Sets higher up in the tree.

I've got a fix for this cooking. Just need a bit more time to finish it off.

**Comment by dac09** [comment]
> Sure. The `DebugLayout` is specified on the "level 1" Set. So it should only ever get the props also specified on that same Set. So `DebugLayout` should always print "Theme: blue" etc, no matter what props might be present on other (nested) Sets. And going back to RW v4 that's the behavior I'm seeing. But currently, on the latest version of RW props on nested sets overwrite the props of Sets higher up in the tree.
> 
> 
> 
> I've got a fix for this cooking. Just need a bit more time to finish it off.

Haha I'm not sure that is the desired behaviour though - it seems odd to me. For non-auth props, I think the child set's props should take precedence. Auth is a special case ofcourse. 

Let's say you want to use the same layout, but change theme colour between sets (exactly as the example) - this makes it possible where as the old way did not.

**Comment by Tobbe** [comment]
I think it's super unintuitive. But of course that's just me. What seems odd to you or unintuitive to me doesn't matter much in the grand scheme of things 🙂 

I just think it goes against how components usually work. If I add a `style` prop to a nested div I'd be very surprised if it changed the style of parent divs.

If you want to change theme colors you'd use a theme context or some other state management tool. If you store your theme preferences on your backend you might use the Apollo cache for that kind of thing for example.

You also get a TS error if you try to do it, because the nested sets don't know about the params parent sets accept 
![image](https://github.com/redwoodjs/redwood/assets/30793/55e89a66-b8b4-4a32-b24b-dc1952f313db)

Regardless – when changing behavior like this I think we should discuss it with the team.

**Comment by dac09** [comment]
Depends how you frame it - I don't see it as passing props to a parent at all. 

I imagine it overriding the prop in the current instance of wrap. You just happen to define what that wrapper is in a parent component, like a render prop.

**Comment by Tobbe** [comment]
We discussed this at the Core Team meeting yesterday and agreed that nested sets should *not* overwrite props in parent sets. So the old RW v4 behavior was correct
