### ISSUE TITLE
[Bug]: Red squiggle for `<Set>` with array of wrappers

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#9313]
### What's not working?

1. Generate a new project: `yarn create redwood-app -y ~/tmp/rw-app`
2. Run `yarn rw g page home /`
3. Add a component to use as a wrapper component to `Routes.tsx`
    ```tsx
    const Wrapper = ({ children }: { children: React.ReactNode }) => {
      return <>{children}</>
    }
    ```
4. Update the `Routes` component in your `Routes.tsx` file to look like this:
    ```tsx
    const Routes = () => {
      return (
        <Router>
          <Set wrap={Wrapper}>
            <Route path="/" page={HomePage} name="home" />
          </Set>
          <Route notfound page={NotFoundPage} />
        </Router>
      )
    }
    ```
5. Everything looks good:
    ![image](https://github.com/redwoodjs/redwood/assets/30793/a893335d-efb8-4d9e-b587-08f7a0904765)
6. Now change to using an array of wrappers so you have this:
    ```tsx
    <Set wrap={[Wrapper]}>
    ```
7. You'll see this error:
    ![image](https://github.com/redwoodjs/redwood/assets/30793/dddb8bad-b446-4899-9d39-b60723037569)

Scrolling to the end of that error message shown in step 7 above I get this:
```
Property 'wrap' is missing in type '{ children: ReactNode; }' but required in type
'{ children: Element; wrap: (({ children }: { children: ReactNode; }) => Element)[]; }'.
```
And also see this:
![image](https://github.com/redwoodjs/redwood/assets/30793/fe5cac2a-39b3-413e-8424-6cfb8092a612)

So, when having an array of wrappers TS for some reason includes `wrap` in the list of props it expects on the wrapper components themselves. Plus the `children` type is wrong (`Element` instead of `ReactNode`)

The fix is to omit `wrap` and `children` from the props type we require all wrappers to match

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by orta** [comment]
FWIW, this is something which I think might have come back in some sense - I just upgraded my app to Redwood 7 and a layout like: 

```ts 
type AdminLayoutProps = {
  children?: React.ReactNode
}

const AdminLayout = ({ children }: AdminLayoutProps) => {
    ....
```

with 

```ts
      <Set wrap={[AdminLayout]} roles="admin" private unauthenticated="login">
        <Route path="/admin" page={AdminPage} name="admin" />
```

Fails type checking with the same kinds of errors you note, but switching it out of the array syntax fixes it
