### ISSUE TITLE
[Bug?]: Starting docker dev container first time fails with Error: EACCES: permission denied, open '/home/node/app/.yarn/install-state.gz'

### ISSUE THREAD

**Issue by Jonathan-Dobson** [redwoodjs/redwood#9320]
### What's not working?

<img width="551" alt="image" src="https://github.com/redwoodjs/redwood/assets/52715503/ae43bfcc-91cf-4961-a6a5-386274e839fe">

```shell
02-rw-redwood-1  | Internal Error: EACCES: permission denied, open '/home/node/app/.yarn/install-state.gz'
02-rw-redwood-1  | Error: EACCES: permission denied, open '/home/node/app/.yarn/install-state.gz'
02-rw-redwood-1 exited with code 1
```

### How do we reproduce the bug?

1. clone a project and `cd` into it.
2. add the four docker files as described int [redwood github docker section](https://github.com/redwoodjs/redwood/tree/main/packages/cli/src/commands/experimental/templates/docker) into the root directory of the project.
3. Start up dev: `docker compose -f ./docker-compose.dev.yml up`

### What's your environment? (If it applies)

```shell
Docker
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by jtoar** [comment]
@Jonathan-Dobson this may be the same as @Josh-Walker-GM comment here: https://github.com/redwoodjs/redwood/issues/9321#issuecomment-1772702619.

The Docker work was merged to main but not released yet. It'll be available in the next minor. I'll try to get the RC for that out today.

**Comment by jtoar** [comment]
See https://github.com/redwoodjs/redwood/issues/9321#issuecomment-1781301677.
