### ISSUE TITLE
yarn create redwood-app looking for creat-next-app?

### ISSUE THREAD

**Issue by RobRoseKnows** [redwoodjs/redwood#933]
I'm trying to follow along the tutorial but I'm getting an error when I try to run the command `yarn create redwood-app ./redwoodblog`:

```
yarn create v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-redwood-app@0.15.3" with binaries:
      - create-redwood-app
error An unexpected error occurred: "ENOENT: no such file or directory, chmod '/home/rob/.asdf/installs/nodejs/12.13.1/.npm/bin/create-next-app'".
info If you think this is a bug, please open a bug report with the information provided in "/home/rob/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```
It seems to be looking for `create-next-app`? Is that a peer dependency of redwood? I thought at first this was a problem with my yarn being installed separately from `asdf`, but that's not it since reinstalling yarn as an NPM package didn't resolve it.

which yarn:
```
/home/rob/.asdf/shims/yarn
```

Is this a problem with asdf or with redwood? I would usually think it was asdf's problem, but it seems to be looking for create-next-app?

**Comment by peterp** [comment]
Weird! We don't use `create-next-app` anywhere; do you have create-next-app installed? Maybe this is a problem with yarn.

**Comment by thedavidprice** [comment]
Woah, super weird indeed. Thanks for letting us know @RobRoseKnows. We haven't seen this one before.

`yarn create` does install globals. Maybe try:
- `yarn global list`
- then `yarn global remove <package>` for anything related to next or redwood

And/or something could be jammed up with [yarn create](https://classic.yarnpkg.com/en/docs/cli/create) (even a bug in current version). Might be worth checking yarn github issues and our looking for latest yarn release and upgrading if possible. I'll try to do the same investigation when I have time today.

**Comment by thedavidprice** [comment]
I did a quick check installation of Redwood. Interestingly, I saw some `yarn` warnings for other global packages installed via `yarn create ...`. However, there were no errors and the installation completed successfully.

I then did `yarn global remove <package>` for the packages that produced the errors, and then next time I ran installation it was clean. So it seems Yarn Create is also doing something across all global packages (likely just those installed with `yarn create`) when it's run. This seems like new behavior.

@RobRoseKnows please let us know if you have success trying my steps in the previous comment.

**Comment by RobRoseKnows** [comment]
So it's no longer looking for `create-next-app` but it is failing with:

```An unexpected error occurred: "ENOENT: no such file or directory, chmod '/home/rob/.asdf/installs/nodejs/12.13.1/.npm/bin/create-redwood-app'".```

I think this is an issue with yarn though, so I'm creating an issue in it.

**Comment by peterp** [comment]
@RobRoseKnows Just checking in here to see if you've managed to resolve this?

**Comment by RobRoseKnows** [comment]
I never got an answer from the yarn team. Ended up installing just with NPM which worked fine. It's been a while though and I don't have time to work on the project I was planning on using Redwood for.

**Comment by thedavidprice** [comment]
This is likely an Ubuntu + Yarn Version/Installation issue and not Redwood. Closing for now. Please re-open if needed.

## Workarounds
- use a [Yarn recommended installation method](https://classic.yarnpkg.com/en/docs/install/) for your system
- ...and...
- make sure you're using the latest Yarn version (as of this writing it's 1.22.5)
- ...or...
- use `npx create-redwood-app [project-directory]`
    - Because the installation script handles `yarn install` as an individual step in the process, this should still work fine. Yarn is still required, however, as Redwood projects rely on Yarn Workspaces.
   - As a last resort if failing on `yarn install` during the process, it might be possible to try `npx create-redwood-app [project-directory] --no-yarn-install`. In this case, the project will be created. Afterwards, you'll need to manually run `yarn install` within the project directory
