### ISSUE TITLE
[Bug?]: Redwood Console is not Working Properly

### ISSUE THREAD

**Issue by yusufarsln98** [redwoodjs/redwood#9356]
### What's not working?

Hello,
I am trying to follow the tutorial on [Redwood Blog](https://redwoodjs.com/docs/tutorial/chapter6/comment-form#introducing-the-redwood-console). 
When I want to call database functions via redwood **console**, the `.` character I add in the middle of a line locks the console. Afterward, I can't write anything.
When I copy and paste the same function, it works.

For example, trying to write `db.` is breaks the console, however copying `db.comment.findMany({ where: { postId: 1 }})` works fine.

### How do we reproduce the bug?

Trying to write `db.comment.findMany({ where: { postId: 1 }})` or something that `.` middle in the line. (not the beginning)

### What's your environment? (If it applies)

```shell
System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 18.12.1 - ~\AppData\Local\Temp\xfs-2d74baa5\node.CMD
    Yarn: 3.6.3 - ~\AppData\Local\Temp\xfs-2d74baa5\yarn.CMD
  Browsers:
    Edge: Chromium (118.0.2088.76)
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 6.3.2 => 6.3.2 
    @redwoodjs/cli-storybook: 6.3.2 => 6.3.2 
    @redwoodjs/core: 6.3.2 => 6.3.2
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Hey :wave: Could this be the same issue as #8817? If you wait long enough after typing the `.` does the console become responsive again?

**Comment by yusufarsln98** [comment]
Yes, It seems like same issue, sorry I didn't notice. When I looked at [#8817](https://github.com/redwoodjs/redwood/issues/8817), I realized that the problem in the terminal had nothing to do with typing '.' After typing `db`, the terminal crashes.

**Comment by Josh-Walker-GM** [comment]
No problem! I'll close this one and we can use the other issue to track everything.
