### ISSUE TITLE
[usability req] Schema fields that have a default should not be required

### ISSUE THREAD

**Issue by turadg** [redwoodjs/redwood#951]
When I created this model,
```
model Measurement {
  id           Int        @id @default(autoincrement())
  takenAt      DateTime   @default(now())
  value        Int
}
```
the resulting scaffold was,
```
  input CreateMeasurementInput {
    takenAt: DateTime!
    value: Int!
  }
```
Redwood was smart enough to omit the `id` but not the `takenAt`. While `takenAt` has a default, there's no way to express whether it is allowed to be specified at creation time so I think it makes sense the the field is included in `CreateMeasurementInput`, but I think it shouldn't be required with the `!`.

For my particular use case I switched to `createdAt` (which is omitted completely like `id`) but I think it would help in general for fields that have defaults to be modeled as optional.

**Comment by Rosenberg96** [comment]
Related issue: #766 - also an open forum post on exactly this: https://community.redwoodjs.com/t/scaffold-and-default-values/1026

**Comment by thedavidprice** [comment]
@turadg @Rosenberg96 
Thank you both for communicating here and moving this one forward. It definitely needs some momentum, which I'll also try to give a boost. Here's my plan:
- I'm going to close this out in favor of #766 
- I'll add some content from here and links to #766 as well
- Rob is effectively the lead on the Scaffold, I'll nudge him
- give his direction, I'm going to ask if either of you would be willing to take a stab at a PR. No pressure here, but hoping that can help momentum as well

🚀
