### ISSUE TITLE
Rename 'diagnostics' to 'check'

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#957]
Hey Aldo,

Had a suggestion from @schickling that diagnostics is a rather difficult command to spell, and I agree, he made a suggestion to rename it "doctor" which I really like, thoughts?

An example of this is `brew doctor`.

## TODO

- [ ] Alias `diagnostics` command to `check`.

**Comment by thedavidprice** [comment]
I'd prefer to keep diagnostics and alias to something like `diag` or (I haven't checked namespace if possible) even just `d`.

**Comment by mojombo** [comment]
What about `check` or `verify`?

**Comment by Tobbe** [comment]
> `diag` or (I haven't checked namespace if possible) even just `d`.

`d` is already used as an alias for `destroy`

**Comment by peterp** [comment]
Given the destructive nature of `destroy` we should consider aliasing it to something like `rm` instead of `d`.

**Comment by Tobbe** [comment]
I like that it's so easy to remember the aliases used by the rw cli, so I'd prefer to keep it as `d`. But I agree that it's very destructive. How about a confirmation step? "Are you sure you want to delete the <entity-type> <entity-name>? This can not be undone."

**Comment by Tobbe** [comment]
I'd love to PR the confirmation if that's something you'd want. Should be easy to get going with https://www.npmjs.com/package/yargs-interactive

**Comment by peterp** [comment]
@Tobbe I don't really find `d` to be an immediately obvious a choice for destroy, but I for this issue it looks like we're going to either rename the command to `check` or alias it to `check`.

**Comment by aldonline** [comment]
I like check.
Specially if we extend it to include not only the diagnostics from redwoodjs/structure, but also TSC errors, prisma errors, etc.
See [this comment] for a longer explanation (https://github.com/redwoodjs/redwood/issues/970#issuecomment-677794325)

**Comment by peterp** [comment]
Closed by #351
