### ISSUE TITLE
[Bug]: Unable to cancel process after launching studio

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#9584]
### What's not working?

Ctrl+C should stop process when running studio. 

**Expected behaviour:** Studio process should close down
**Actual behaviour**: Nothing happens.

Video walkthrough: https://s.tape.sh/9ZIkKUrn

Likely related to "analysing mailer templates", and maybe macos specific. Does not happen on Gitpod. 

### How do we reproduce the bug?

Launch rw studio by running `yarn rw experimental studio` 

Then press Ctrl+C.

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 13.4.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /private/var/folders/s5/9hjh2cw51w714bw6px5nspr00000gn/T/xfs-ec55d9f5/node
    Yarn: 3.7.0 - /private/var/folders/s5/9hjh2cw51w714bw6px5nspr00000gn/T/xfs-ec55d9f5/yarn
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 16.5.2
  npmPackages:
    @redwoodjs/core: 6.4.0 => 6.4.0
    @redwoodjs/studio: 6.4.0 => 6.4.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by dac09** [comment]
@Josh-Walker-GM we spoke about this before, just creating an issue because I've come across it again.

**Comment by Josh-Walker-GM** [comment]
This is a confirmed issue in the current version of the studio. I'm in the process of porting studio over to its own repository and using redwood itself to build studio. In the new version this issue does not exist. I do not plan on addressing this issue in the current version that lives in this repo.
