### ISSUE TITLE
Could replace axios with `zeit/swr`?

### ISSUE THREAD

**Issue by zwl1619** [redwoodjs/redwood#97]
Could replace [axios](https://github.com/redwoodjs/redwood/blob/master/packages/create-redwood-app/package.json) with [zeit/swr](https://github.com/zeit/swr) in [packages/create-redwood-app/package.json](https://github.com/redwoodjs/redwood/blob/master/packages/create-redwood-app/package.json)?

**Comment by peterp** [comment]
Hey there, we're moving away from using `react-ink` to generate our CLIs, so a hooks based request library won't make sense.

Thanks for opening the issue.
