### ISSUE TITLE
[Bug]: cannot set jest testTimeout

### ISSUE THREAD

**Issue by ThomasGHenry** [redwoodjs/redwood#9712]
### What's not working?

I'm trying to set the jest config attribute testTimeout in my redwoodjs api. 

https://redwoodjs.com/docs/testing#jest

https://jestjs.io/docs/cli#--testtimeoutnumber

https://jestjs.io/docs/configuration#testtimeout-number

https://jestjs.io/docs/api#testname-fn-timeout

I tried:
 - `./jest.config.js` in the project root
```
// This the Redwood root jest config
// Each side, e.g. ./web/ and ./api/ has specific config that references this root
// More info at https://redwoodjs.com/docs/project-configuration-dev-test-build

module.exports = {
  rootDir: '.',
  projects: ['<rootDir>/{*,!(node_modules)/**/}/jest.config.js'],
  testTimeout: 10000,
}
```

 - `./api/jest.config.js` 
```
// More info at https://redwoodjs.com/docs/project-configuration-dev-test-build

const config = {
  rootDir: '../',
  preset: '@redwoodjs/testing/config/jest/api',
  testTimeout: 10000,
}

module.exports = config
```
 - passing it as a flag like `yarn rw test -- --testTimeout=10000`
 - setting it as the last argument to the scenario function E.g. - `scenario('returns all bills', /* test body callback */, 10000)`

In most cases it seems to be ignored or maybe overwritten, but in the case of setting it in `./api/jest.config.js` I do get a message saying the attribute is unknown. 

```
● Validation Warning:

  Unknown option "testTimeout" with value 10000 was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration
```

I tried it both as a string and a number in this last case, just in case, but no love.

Putting `jest.setTimeout(10000)` in the test file itself works.

Other attempts at answers:
- https://discord.com/channels/679514959968993311/1142813226153820181/1184218318303924275
- https://stackoverflow.com/questions/77648717/set-testtimeout-in-redwoodjs
- https://community.redwoodjs.com/t/set-jest-testtimeout/5618

### How do we reproduce the bug?

1. have a long running test case (> 5000ms, < 10000ms)
2. `yarn rw test`
3. expect your test to timeout at 5 seconds 
4. observe your test times out at 5 seconds
5. set `testTimeout: 10000` in jest.config.js
6. `yarn rw test` 
7. expect your test not to timeout
8. observe your test still times out at 5 seconds

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 13.6.1
    Shell: 3.6.1 - /usr/local/bin/fish
  Binaries:
    Node: 18.18.2 - /private/var/folders/59/tynw6p_96w1626jbzhg31y_00000gn/T/xfs-86d49808/node
    Yarn: 3.7.0 - /private/var/folders/59/tynw6p_96w1626jbzhg31y_00000gn/T/xfs-86d49808/yarn
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Safari: 17.1
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 6.4.0 => 6.4.0 
    @redwoodjs/cli-storybook: 6.4.0 => 6.4.0 
    @redwoodjs/core: 6.4.0 => 6.4.0
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by dthyresson** [comment]
@ThomasGHenry Hi again, I did reply in the community thread here https://community.redwoodjs.com/t/set-jest-testtimeout/5618 but will keep this issue up-to-date with any findings to help customize and set the test timeout on the api side tests.

**Comment by dthyresson** [comment]
@ThomasGHenry Did you try

```
yarn rw test --testTimeout=10000
```

Not that your issue said you tried `yarn rw test -- --testTimeout=10000`

From what I see in https://github.com/redwoodjs/redwood/blob/7960c3fe3554f6845fdf753abcab436d05f512f6/packages/cli/src/commands/testHandler.js#L79 all other flags are forwarded,

If I do 

```
`yarn rw test --timoutt=10000`
```

A non-recognized flag, then it errors:

```
● Unrecognized CLI Parameter:

  Unrecognized option "timoutt".

  CLI Options Documentation:
  https://jestjs.io/docs/cli
```

It might that that extra `--` that prevent the string to be forwarded.

**Comment by dthyresson** [comment]
Also, @ThomasGHenry could you try running `yarn rw test --debug`, the warning might be just that, an odd warning, but the actual setting `testTimeout` seems to be there in the config:

```
    "testFailureExitCode": 1,
    "testPathPattern": "",
    "testSequencer": ".....demos/node_modules/@jest/test-sequencer/build/index.js",
    "testTimeout": 30000, <---------------------------
    "updateSnapshot": "new",
    "useStderr": false,
    "verbose": true,
    "watch": true,
    "watchAll": false,
    "watchPlugins": [
```

**Comment by dthyresson** [comment]
Actually, @ThomasGHenry I was about to set a custom test timeout for the api side `api/jest.config.js`:


```
// api/jest.config.js
// More info at https://redwoodjs.com/docs/project-configuration-dev-test-build

const config = {
  rootDir: '../',
  preset: '@redwoodjs/testing/config/jest/api',
  testTimeout: 80000,
}

module.exports = config
```

and `yarn rw test api --debug` shows:

```
    "testFailureExitCode": 1,
    "testPathPattern": "",
    "testSequencer": "..../node_modules/@jest/test-sequencer/build/index.js",
    "testTimeout": 80000, <--------------------------
    "updateSnapshot": "new",
    "useStderr": false,
    "watch": true,
    "watchAll": false,
    "watchPlugins": [
```

Does that work for you?

Note: I did not set that for the web side test in the config.

**Comment by ThomasGHenry** [comment]
> It might that that extra `--` that prevent the string to be forwarded.

That did it on the CLI! 

I'll circle back for the other suggestions another time, but nothing I've tried json-wise worked as expected so far.

Thanks!
