### ISSUE TITLE
[Bug?]: NODE_OPTIONS in .env file not pulled in correctly

### ISSUE THREAD

**Issue by cjreimer** [redwoodjs/redwood#9733]
### What's not working?

The code in redwood is:

```
export function getDevNodeOptions() {
  const { NODE_OPTIONS } = process.env

  const enableSourceMapsOption = '--enable-source-maps'

  if (!NODE_OPTIONS) {
    return `NODE_OPTIONS=${enableSourceMapsOption}`
  }

  if (NODE_OPTIONS.includes(enableSourceMapsOption)) {
    return NODE_OPTIONS
  }

  return `${NODE_OPTIONS} ${enableSourceMapsOption}`
}

```

If an .env file with NODE_OPTIONS is provided, we get an error: 
```
api | '--enable-source-maps' is not recognized as an internal or external command,
api | operable program or batch file.
api | node:events:495
api |       throw er; // Unhandled 'error' event
api |       ^
```

At first glance, it looks to me like `NODE_OPTIONS=` is not appropriately inserted in front of the combined options.

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jtoar** [comment]
Thanks @cjreimer, fixed this one in https://github.com/redwoodjs/redwood/pull/9735. We'll get a release out within a day or two.

**Comment by cjreimer** [comment]
Thanks for the quick response @jtoar!
