### ISSUE TITLE
feat: Setup GraphQL Trusted Documents with a setup command

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#9739]
### Summary

See: https://github.com/redwoodjs/redwood/pull/9594 for context.

A setup command to configure Redwood projects with:

* toml
* graphql handler to add store
* setup cli docs with pointer to TD docs

### Motivation

to improve the DX.

### Detailed proposal

Let's create a namespace for graphql-related setups:

`yarn rw setup graphql trusted-documents`

This could be used to also do setups for response caching, or other graphql related featues.

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by dthyresson** [comment]
@Tobbe Would this setup command be helpful?

**Comment by Tobbe** [comment]
> @Tobbe Would this setup command be helpful?

💯
