### ISSUE TITLE
Using Existing GraphQL endpoint.

### ISSUE THREAD

**Issue by brianraila** [redwoodjs/redwood#974]
Is it possible to use Redwood with an already existing GraphQL endpoint or using a service such as Hasura or FaunaDB?

**Comment by thedavidprice** [comment]
Hi @brianraila If you haven't seen these already, here are some relevant docs and conversations:
- https://redwoodjs.com/cookbook/using-a-third-party-api
- https://redwoodjs.com/cookbook/disable-api-database (e.g. you just want Redwood Web to connect to existing API that's not Redwood)
- https://community.redwoodjs.com/t/building-a-minimum-viable-stack-with-redwoodjs-and-faunadb/1048
    https://community.redwoodjs.com/t/building-a-minimum-viable-stack-with-redwoodjs-and-faunadb/1048/11
- https://community.redwoodjs.com/t/using-redwood-with-neo4j-database/282
- https://community.redwoodjs.com/t/what-dbs-does-redwood-support/143/14 (Example Redwood using graphql-request)

Hope this helps!

Closing this Issue for now. But (re)open as needed and/or reach out on the Forums!

**Comment by brianraila** [comment]
Thanks for that @thedavidprice

**Comment by brianraila** [comment]
But does this mean I am not able to take advantage of "cells" in Redwood when using an external GraphQL API?

**Comment by jtoar** [comment]
@brianraila A Cell will still work just fine :+1:
