### ISSUE TITLE
[Bug?]: Generators Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by xmaxcooking** [redwoodjs/redwood#9760]
### What's not working?

I've run into this issue:
```
Cannot read properties of undefined (reading 'startsWith')
◼ Generating types ...
Error applying template at F:\Git\my-redwood-project\node_modules\@redwoodjs\cli\dist\commands\generate\cell\templates\cell.tsx.template for Profile: Cannot read properties of undefined (reading 'startsWith')`
```

when running `yarn rw g cell Profile`

After backtracking my steps to a working state I found the issue to be that I installed `prettier` because of the `yarn install` warnings.

`➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide prettier (pfdc36), requested by prettier-plugin-tailwindcss.`

I'm unsure if this is a redwood bug but either way it's good to document this here for others to find.

### How do we reproduce the bug?

```
yarn create redwood-app my-redwood-project --typescript
cd my-redwood-project
yarn install 
yarn rw setup ui tailwindcss
yarn add prettier -D
yarn rw g component Broken
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Tobbe** [comment]
@xmaxcooking What version of prettier did that install for you?

**Comment by xmaxcooking** [comment]
Hi @Tobbe!👋

```
"prettier": "^3.1.1",
"prettier-plugin-tailwindcss": "0.4.1"
  ```

**Comment by Tobbe** [comment]
Yeah, unfortunately RW doesn't work with prettier v3 yet. See more here https://github.com/redwoodjs/redwood/pull/9077

That's still a pretty weird error to be getting though 🤔 
Seeing how it's Cell related I'm worried it's somehow caused by this PR https://github.com/redwoodjs/redwood/pull/8264

**Comment by xmaxcooking** [comment]
> That's still a pretty weird error to be getting though 🤔 Seeing how it's Cell related I'm worried it's somehow caused by this PR #8264

Actually all generators were broken.

**Comment by xmaxcooking** [comment]
@Tobbe I just verified this and everything works with prettier@2.8.8
