### ISSUE TITLE
hasRole should also accept an array of roles.

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#977]
A developer should be able to specify an array of valid roles in `hasRole(['admin', 'contributor'])`

Since `<Private role="" />` is backed up via `hasRole` is should also be able to accept an array.

**Comment by dthyresson** [comment]
On the `api` side in the RBAC blog app, I chose to do something where roles could be a string or an string[].

```js
xport const requireAuth = ({ roles } = {}) => {
  if (!context.currentUser) {
    throw new AuthenticationError("You don't have permission to do that.")
  }

  if (
    typeof roles !== 'undefined' &&
    typeof roles === 'string' &&
    !context.currentUser.roles?.includes(roles)
  ) {
    throw new ForbiddenError("You don't have access to do that.")
  }

  if (
    typeof roles !== 'undefined' &&
    Array.isArray(roles) &&
    !context.currentUser.roles?.some((role) => roles.includes(role))
  ) {
    throw new ForbiddenError("You don't have access to do that.")
  }
}
```

@peterp  do you think that the `hasRole` on `web` in the AuthProvider **only** should take an array or string || array?

For example:

`hasRole(["admin"])` and `hasRole("admin")` are both permitted?

Current:

```
  hasRole = (role: string): boolean => {
    return this.state.currentUser?.roles?.includes(role) || false
  }
```

but change to?

```
 hasRole = (role: string | string[]): boolean => 
```

And change logic to handle both string or string[]. Probably make string into a `[value]` (one element array) and use same role check?

**Comment by peterp** [comment]
I really like that it can take both a string and an array!
