### ISSUE TITLE
Remove `@redwoodjs/forms` from `@redwoodjs/web`

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#978]
This should be an optional dependency in order to reduce our overall bundle size:

## steps:
- [ ] remove it from `@redwoodjs/web`
- [ ] add it to `<project>/web/package.json`, if it's not imported it won't be included.

**Comment by alvincrespo** [comment]
@peterp I was thinking this might be a good one for me to start on. This would be my first technical contribution. Do you think this is good to get started on?

**Comment by peterp** [comment]
@alvincrespo Yes please, I'll assign it to you, please let me know if you have any questions.

**Comment by peterp** [comment]
Here's the command that we run when you type `yarn rw storybook`

https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/storybook.js

So you would:
1. Add an `--open` flag
2. Conditionally set `--ci` when the command is run.

**Comment by alvincrespo** [comment]
Awesome! Thanks @peterp - I'll take a shot at it.
