### ISSUE TITLE
Remove older browsers from browserlists target

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#979]
Right now we use "defaults" for our browserlists configuration. This means that we automatically polyfill browsers that aren't very relevant (`ie11`, and `ie11_mobile`) and it increases our bundle size.

I think we should remove support for much older browsers. We would need to let people know which browsers we support, and if supporting older browsers is a priority that they should build the packages themselves.

This would only affect:
- [x] @redwoodjs/router
- [x] @redwoodjs/web
- [x] <project>/web/package.json

**Comment by thedavidprice** [comment]
Yes, please! I'd like to see:
```
  "browserslist": [
    "defaults",
    "not IE 11",
    "not IE_Mob 11"
  ]
```

**Comment by peterp** [comment]
Done in v0.19.0!
