### ISSUE TITLE
Do we want to generate MDX and test files for all generated files?

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#98]
Right now only the Component generator creates MDX and test files along side the actual component JS file. Do we want to create them for Pages, Cells, Services, etc?

If we do create them for Services we'll probably want to start putting them in a subdirectory just like we do for components. Otherwise we're going to have a LOT of files in that one directory.

```
.
├── prisma
│   ├── dev.db
│   ├── migrations
│   ├── schema.prisma
│   └── seeds.js
└── src
    ├── functions
    │   └── graphql.js
    ├── graphql
    │   ├── contacts.sdl.js
    │   └── posts.sdl.js
    └── services
        ├── contacts
        │   ├── contacts.js
        │   ├── contacts.mdx
        │   └── contacts.test.js
        └── posts
            ├── posts.js
            ├── posts.mdx
            └── posts.test.js
```

**Comment by peterp** [comment]
I think it mostly makes most sense with components because we could load them into storybook. For things like Pages and Cells it might be a bit more complicated since they require external run times or additional components.

But, I guess it depends on the person.

**Comment by mojombo** [comment]
I think we should directorize services files and add test files there, and the other places where it makes sense. Let's wait to add Storybook files until after we get that integrated.

**Comment by thedavidprice** [comment]
Question about this related to the Web Side —> what is the intended behavior for `generate` creating `.mdx` and `.test.js` along with the component `.js` files? Right now the behavior doesn’t seem consistent. And I’m not sure what expectations to provide readers in the tutorial. 

What I expected to be the generator behavior:
- All non-cell `components/` would include all 3 files
- Everything else would include 1 file

**Here’s a snapshot of my directory halfway through the tutorial**

<img width="252" alt="Screen Shot 2020-02-19 at 10 34 10 AM" src="https://user-images.githubusercontent.com/2951/74864012-af57de00-5303-11ea-9933-3d3daedb2aa5.png">

Everything looks as expected _except for_ `NewPost/` and `Post/`. **Is this because `rw g scaffold` isn’t including the `.mdx` and `.test.js` files? Or is something else going intentionally that I don’t yet understand?**

**Comment by cannikin** [comment]
So @peterp was auto-generating `test` and `mdx` files in the `component` generator which for a long time was the only one that existed. I built out the rest of the generators but didn't include test or mdx files as we didn't have a real decision on whether we wanted those on *everything* so I just left them out. @mojombo said we want them for services for sure, so I just added those, but that's it.

I'd guess we want them for cells for sure, not sure about pages and layouts. SDL is kind of self explanatory, and really shouldn't have logic so I'm not sure they would need tests? But maybe a readme? The scaffold doesn't generate them either. Whether we add those is probably dependent on how we position scaffolds—are they meant to be replaced completely (in which case test and readme files are just one more thing to delete) or do we think you'll keep using them forever and just subtly update the UI to work with your usecase (in which case you probably DO want to fill out tests and the readme).

**Comment by cannikin** [comment]
But we also don't have any helpers in place for writing tests for cells or services or anything else, or even a recommended testing methodology/library in place. I included just a single test that (hopefully) passes so it shouldn't lock anyone into something once we settle on The True Testing Way.

**Comment by thedavidprice** [comment]
Roger that. I vote for now that we stop creating the `test` and `mdx` files for now on the Web Side when `g component` is run. Seems great for v0.2 improvements.

y/n/mabye?

**Comment by cannikin** [comment]
That seems logical to me. But I know one of the core tenets of Redwood is the code organization aspect and the idea that tests and documentation go right next to the components is near and dear to @mojombo. Creating those files with the generators would get people into that mindset from day 1. 

But from the point of view of the tutorial, it is a lot of extra "stuff" floating around in directories and makes the file browser *extremely* busy. Hmmm...

**Comment by thedavidprice** [comment]
👍 for the priority of tests and docs integrated deeply into dev workflow. It's just the inconsistencies in the current implementation that beg questions. And I'd love to ship `create-rw-app` with a GH Action for CI (possibly along with the Netlify preview action -- double 🔥)!

So maybe for now the decision tree is:
a) add these files to generator for cells and include in scaffolding files created
b) remove from generate components for now but prioritize CI post 0.1

**Comment by thedavidprice** [comment]
@mojombo thoughts on near-term steps here?

**Comment by mojombo** [comment]
I would add test files, but not mdx files right now. Rob is right that it's important to get people into the "everything in one directory" mindset right away, and we can put simple test stubs in there without causing any problems. I expect we'll get some proper testing methodology going soon after we launch, it's high priority. I would also NOT produce mdx files for anything right now. When we integrate Storybook, we can add mdx in all the right places.

**Comment by cannikin** [comment]
Created #137 to handle this. Closing this one, we can revisit MDX files in the future.
