### ISSUE TITLE
Change auth impersonation in Studio to not use Request body

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#9801]
### What's not working?

Currently for auth impersonation in studio, we use this function: https://github.com/redwoodjs/redwood/blob/main/packages/auth-providers/dbAuth/api/src/shared.ts#L45 to "override" the auth sent by requests from studio. 

The problem with this approach is that with [Web API Requests](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) - the body has to be parsed async. i.e.

```js
const body = await request.text() 
```

This requires the function to be async - and needs a lot of changes in the `dbAuthHandler` to make it work. 

---
I'm not sure how the impersonated Cookie gets set in studio but...

**Suggestion:** use a different header like `X-RWS-AuthImpersonation` so that the `eventGraphiQLHeadersCookie` can continue to be sync (just like `req.headers.get('Authorization')`

### How do we reproduce the bug?

N/A

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Tobbe** [comment]
Just leaving this here as a note for whoever takes this on: Custom headers should not start with "X-" anymore. (They're still allowed to, but it's not recommended.) 

See https://stackoverflow.com/a/3561399/88106 for more info
