### ISSUE TITLE
[Bug]: yarn create redwood-app ... stopped by ERR_IMPORT_ASSERTION_TYPE_MISSING

### ISSUE THREAD

**Issue by willmruzek** [redwoodjs/redwood#9815]
### What's not working?

When I run either of the two following commands, I get the following error:
```
yarn create redwood-app hello-redwood
yarn create redwood-app hello-redwood --typescript
```

Error:
```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
TypeError [Error]: [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///Users/mruzekw/.yarn/berry/cache/create-redwood-app-npm-6.6.2-cffa98002c-8.zip/node_modules/create-redwood-app/templates/ts/package.json" needs an import assertion of type "json"
    at load$1 (file:///private/var/folders/6x/6h44csd50hn7q73f4q5cfl940000gn/T/xfs-07a144e6/dlx-26367/.pnp.loader.mjs:1457:17)
    at nextLoad (node:internal/modules/esm/hooks:865:28)
    at Hooks.load (node:internal/modules/esm/hooks:448:26)
    at handleMessage (node:internal/modules/esm/worker:196:24)
    at checkForMessages (node:internal/modules/esm/worker:138:28)
    at process.<anonymous> (node:internal/modules/esm/worker:157:5)
    at process.emit (node:events:514:28)
    at process.emit (/private/var/folders/6x/6h44csd50hn7q73f4q5cfl940000gn/T/xfs-07a144e6/dlx-26367/.pnp.cjs:10037:25) {
  code: 'ERR_IMPORT_ASSERTION_TYPE_MISSING'
}
```

### How do we reproduce the bug?

```
yarn create redwood-app hello-redwood
yarn create redwood-app hello-redwood --typescript
```

### What's your environment? (If it applies)

```shell
**Node version**: `20.10.0`
**Yarn version**: `3.4.1`

MacOS Ventura 13.6.2 (22G320)
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by ahaywood** [comment]
@willmruzek Thanks for reporting! I'll see if I can reproduce your issue.

**Comment by ahaywood** [comment]
Hey @willmruzek 👋 I talked to another core team member and he said that he's seen some weird instances before where other global npm packages have created conflicts.

Will you try running `npx create-redwood-app` and see if that works for some reason?

Or, do you have any stray `package.json` or `.yarnrc.yml` files lying around in your home directory?

**Comment by willmruzek** [comment]
Hi @ahaywood, thanks for looking into this. `npx create-redwood-app` runs great! I wondered if there was a npm version of the command.

It turns out I did have a `.yarnrc.yml` file in my `Code` dir. I just ran the yarn version, and it works fine now. Thanks again!

**Comment by karabayyazilim** [comment]
yarn create redwood-app my-redwood-project --typescript
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + create-redwood-app@npm:6.6.2, and 86 more.
➤ YN0000: └ Completed in 0s 346ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 87 packages were added to the project (+ 12.32 MiB).
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 0s 498ms

------------------------------------------------------------------
                🌲⚡️ Welcome to RedwoodJS! ⚡️🌲
------------------------------------------------------------------
⠹ Checking node and yarn compatibility
/private/var/folders/r_/f5wmjtxn0_5739xcl_rwztk40000gn/T/xfs-a98d1b25/dlx-9196/.yarn/cache/create-redwood-app-npm-6.6.2-cffa98002c-ea942673b3.zip/node_modules/create-redwood-app/dist/create-redwood-app.js:6
`));try{(await o.prompt({type:"select",name:"override-engine-error",message:"How would you like to proceed?",choices:["Override error and continue install","Quit install"],initial:0}))["override-engine-error"]==="Quit install"&&(c("User quit after engine check error"),await s(),process.exit(1))}catch{c("User cancelled install at engine check error"),await s(),process.exit(1)}}}function pe(e){return new Promise(t=>{let{engines:n}=require(l.default.join(e,"package.json"));(0,J.default)(n,(r,a)=>t([a.isSatisfied,a.versions]))})}async function de(e,{templateDir:t,overwrite:n}){let r=e,a=new i.ReactiveTUIContent({mode:"text",content:"Creating project files",spinner:{enabled:!0}});return o.startReactive(a),r=await U(r,{overwrite:n}),y.default.ensureDirSync(l.default.dirname(r)),y.default.copySync(t,r,{overwrite:n}),y.default.renameSync(l.default.join(r,"gitignore.template"),l.default.join(r,".gitignore")),y.default.ensureDirSync(l.default.join(r,".redwood")),y.default.writeFileSync(l.default.join(r,".redwood","telemetry.txt"),_),a.update({spinner:{enabled:!1},content:`${i.RedwoodStyling.green("\u2714")} Project files created`}),o.stopReactive(),r}async function ue(e){let t=new i.ReactiveTUIContent({mode:"text",header:"Installing node modules",content:"  \u23F1 This could take a while...",spinner:{enabled:!0}});o.startReactive(t);let n=(0,k.default)("yarn install",{shell:!0,cwd:e});try{await n}catch(r){o.stopReactive(!0),o.displayError("Couldn't install node modules",[`We couldn't install node modules via ${i.RedwoodStyling.info("'yarn install'")}. Please see below for the full error message.`,"",r].join(`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ^

TypeError: Cannot read properties of undefined (reading 'isSatisfied')
    at /private/var/folders/r_/f5wmjtxn0_5739xcl_rwztk40000gn/T/xfs-a98d1b25/dlx-9196/.yarn/cache/create-redwood-app-npm-6.6.2-cffa98002c-ea942673b3.zip/node_modules/create-redwood-app/dist/create-redwood-app.js:6:504
    at /private/var/folders/r_/f5wmjtxn0_5739xcl_rwztk40000gn/T/xfs-a98d1b25/dlx-9196/.yarn/cache/check-node-version-npm-4.2.1-c9ead05689-7778e04d24.zip/node_modules/check-node-version/index.js:130:7
    at end (/private/var/folders/r_/f5wmjtxn0_5739xcl_rwztk40000gn/T/xfs-a98d1b25/dlx-9196/.yarn/cache/run-parallel-npm-1.2.0-3f47ff2034-200b5ab25b.zip/node_modules/run-parallel/index.js:21:15)
    at done (/private/var/folders/r_/f5wmjtxn0_5739xcl_rwztk40000gn/T/xfs-a98d1b25/dlx-9196/.yarn/cache/run-parallel-npm-1.2.0-3f47ff2034-200b5ab25b.zip/node_modules/run-parallel/index.js:25:10)
    at each (/private/var/folders/r_/f5wmjtxn0_5739xcl_rwztk40000gn/T/xfs-a98d1b25/dlx-9196/.yarn/cache/run-parallel-npm-1.2.0-3f47ff2034-200b5ab25b.zip/node_modules/run-parallel/index.js:31:7)
    at /private/var/folders/r_/f5wmjtxn0_5739xcl_rwztk40000gn/T/xfs-a98d1b25/dlx-9196/.yarn/cache/run-parallel-npm-1.2.0-3f47ff2034-200b5ab25b.zip/node_modules/run-parallel/index.js:41:43
    at /private/var/folders/r_/f5wmjtxn0_5739xcl_rwztk40000gn/T/xfs-a98d1b25/dlx-9196/.yarn/cache/check-node-version-npm-4.2.1-c9ead05689-7778e04d24.zip/node_modules/check-node-version/index.js:226:12
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)

Node.js v18.19.0
