### ISSUE TITLE
GraphQL Function Prisma DB Disconnect Warn

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#982]
In [Primsa 2.4](https://github.com/prisma/prisma/releases/tag/2.4.0) introduced some changes to top level methods like `disconnect`:

```
Top-level Client Methods: $ dollar prefix for top-level Prisma Client methods
In recent versions, we introduced a couple of top-level methods in Prisma Client (e.g. prisma.transaction() and prisma.use()) in preview mode. The immediate feedback was that the denylist for model names grew - which breaks Prisma schemas where a model is called Transaction, transaction, use, or Use. And the list goes on...

In order to have a future-proof API, that allows maximum expressibility in terms of model names, we decided to prefix all non-query methods with a dollar sign $. That means Prisma Client will from now on ship with the following methods:

Pre-existing
$disconnect
$connect
$on
$queryRaw
$executeRaw
```

`warn prisma.disconnect() is deprecated, please use prisma.$disconnect() instead`

https://github.com/redwoodjs/redwood/blob/main/packages/api/src/functions/graphql.ts

needs to use `db.$disconnect()`

**Comment by zackmckenna** [comment]
@peterp This would be my first contribution ever, I just wanted to confirm that adding the $ prefix to disconnect is all that is required for this issue.

**Comment by peterp** [comment]
Hey @zackmckenna! Welcome! 🙌

That is 100% the change we're looking for :)

**Comment by dthyresson** [comment]
Double points for updating the seeds.js in Create Redwood app?

See: https://github.com/redwoodjs/create-redwood-app/blob/main/api/prisma/seeds.js

```js
main()
  .catch((e) => console.error(e))
  .finally(async () => {
    await db.disconnect()
  })
```

**Comment by zackmckenna** [comment]
@dthyresson Well I have go for the double points. I'm on it!
