### ISSUE TITLE
Diagnostics: Web side env var configuration

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#983]
For env vars to be used by the Web Side in production, they must be configured with either a prefix or included in `redwood.toml`. (Docs here.) This config step is specific to serverless infrastructure and trips people up.

If possible, we should add a check to the CLI diagnostics to:
1) look in /web for process.env
2) if found, confirm either env var begins with `REDWOOD_ENV_` or is included in `redwood.toml`

Lastly, if this diagnostic check fails, we should recommend the `redwood.toml` option as it's the most error-resistant. (E.g. if you are using Auth0 in your project, the required env vars _must_ be exact matches to the docs — using the prefix will fail.)

**Comment by dthyresson** [comment]
I did something like this using a Netlify build plugin:

https://github.com/dthyresson/netlify-plugin-redwoodjs-env-validator

But having the diagnostic/check is excellent.
