### ISSUE TITLE
[Bug?]: Routes should use encodeURIComponent when appending unnamed params

### ISSUE THREAD

**Issue by sean-ac** [redwoodjs/redwood#9839]
### What's not working?

Doing something like:

```
routes.homePage({ search: 'home & garden' });
```

Produces a route:

```
/home?search=home%20&%20garden
```

Which is malformed due to missing `encodeURIComponent`.

I believe the bug is on this line:

https://github.com/redwoodjs/redwood/blob/v6.6.2/packages/router/src/util.ts#L340

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Tobbe** [comment]
Thanks for your issue report. And even linking to the code needed to change is awesome 🙏 

I'll try to take a look
