### ISSUE TITLE
Can't run web tests - can't find module whatwg-fetch

### ISSUE THREAD

**Issue by darryl-snow** [redwoodjs/redwood#985]
Just spun up my first project, created a page, a component, and a layout and when I try to test the web side using `yarn rw test web` each test results in the following error:

```
- Test suite failed to run

    Cannot find module 'whatwg-fetch' from '../node_modules/@redwoodjs/core/dist/configs/browser/jest.setup.js'
```

The tests are just those that were generated, I didn't modify them.

If I try to install `whatwg-fetch` and try again, then I get this error:

"Cannot find module '@redwoodjs/router/dist/index' from '../node_modules/@redwoodjs/testing/dist/MockRouter.js'"

```
  System:
    OS: macOS 10.15.5
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.7.0 - /var/folders/4b/7qkvj0p12_ddjbv8s6rmrl7h0000gp/T/yarn--1598070881071-0.6316991447276004/node
    Yarn: 1.22.4 - /var/folders/4b/7qkvj0p12_ddjbv8s6rmrl7h0000gp/T/yarn--1598070881071-0.6316991447276004/yarn
  Databases:
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 84.0.4147.135
    Safari: 13.1.1
  npmPackages:
    @redwoodjs/core: ^0.15.3 => 0.15.3 
```

**Comment by thedavidprice** [comment]
@darryl-snow Thanks for this! Just confirming it's on our radar. Not sure what's going on yet, unfortunately.

**Comment by peterp** [comment]
@thedavidprice Is this still hapenning?

**Comment by thedavidprice** [comment]
`yarn rw test` is broken due to Apollo v3 (for some strange reason). 

Closing this one out in favor of https://github.com/redwoodjs/redwood/issues/1264
