### ISSUE TITLE
Allow users to set a custom config for Storybook

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#989]
Right now it's not possible to merge a user's configuration with our own. It would be great if we specified a storybook config path in getPaths(), like we do over here for webpack:

https://github.com/redwoodjs/redwood/blob/main/packages/internal/src/paths.ts#L66

And then attempt to import this over here:
https://github.com/redwoodjs/redwood/blob/main/packages/core/config/storybook/preview.js#L10

and add it as a decorator, I'm assuming that we're able to add multiple decorators.

**Comment by peterp** [comment]
Related to #887

**Comment by thedavidprice** [comment]
@peterp @jtoar 
I believe this Issue has been resolve via #1828 and also the just-merged https://github.com/redwoodjs/redwood/issues/2054 (upgrade to Storybook v6) Correct?

Dom, further thoughts on a Doc for Storybook? All good if it hasn't started. Just let me know as I'd like to create an issue for tracking.

**Comment by jtoar** [comment]
@thedavidprice yeah I would think those two PRs close this issue. And doc's been started here: https://github.com/redwoodjs/redwoodjs.com/pull/611. Definitely on my list for this week

**Comment by thedavidprice** [comment]
Roger that and closing out. Thanks!
