### ISSUE TITLE
Recommended VSCode Extensions for local Package Dev

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#99]
Been going through the setup process and had questions about extensions as well as encountered an issue with beautify extension (most likely) conflicting  with `prettier.config.js`. 

I’m working on a draft doc with steps to setup for local dev. But suggesting it also be helpful if we suggest extenstions similar to /redwoodjs/create-redwood-app/.vscode/settings.json?

So what packages would that be beyond ESLint and Prettier?

**Comment by cannikin** [comment]
I started a list over in the tutorial, thinking we could mention them there and what each of them do: https://github.com/redwoodjs/tutorial/issues/9 But we should also have an issue here as they need to get added to redwood itself.
