### ISSUE TITLE
[Docs]: Algolia search is not working

### ISSUE THREAD

**Issue by beardo01** [redwoodjs/redwood#9996]
### Summary and description

At the moment the search functionality on the docs part of the website is not working. All search results return `No results for *`

<img width="615" alt="image" src="https://github.com/redwoodjs/redwood/assets/11054688/529f4e94-b90e-4ba0-bddd-99a0ae9e4b68">

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jtoar** [comment]
Thank you @beardo01! Working on this now should be back online soon.

**Comment by beardo01** [comment]
Legend @jtoar! Happy to test on my end if you want someone to validate with.

**Comment by jtoar** [comment]
@beardo01 took a little longer than expected because the crawler wasn't just working like it normally does but think I've got it fixed—could you confirm @beardo01?

**Comment by beardo01** [comment]
Looks good on my side! Thanks for the fix @jtoar.
